// GENERATED by packages/whetstone/publish-sites.mjs (--home) from the souls' house/feeds/. Do not edit.
import * as f0 from './welcome-desk.mjs';
export default {
 "welcome-desk": { mod: f0, by: 'souls', "digest":"7a0750e0d8e03435","signed":["morphyx","mozzie"],"displayName":"Welcome desk","description":"The first post of every account on pds.delve.town, newest first, by when that post was made (a date in the future counts as the day we first saw it). Served by miniphim's house, miniphim.minomobi.com." },
};
