// ─────────────────────────────────────────────────────────────────────────────
// data.js — an ORIGINAL English translation of the geomantic figures from a single
// named source of truth, set beside the Latin:
//
//   Robert Fludd, "Tractatus de Geomantia", Liber II ("De Figuris Geomanticis"),
//   in the FASCICULUS GEOMANTICUS (Verona, 1704), pp. 34–38.
//   Scan: Internet Archive, item b3299753x.
//
// The Latin below is transcribed from the page images of that edition (read directly,
// not from its broken OCR), lightly normalised (long-ſ → s, æ kept). The English is
// ours; notes mark the cruxes. This is a transparent WORKING translation — corrections
// welcome — and a first tranche: Fludd's NAMES, FORMS and NATURES of the figures. The
// per-house significations ("Acquisitio in domo Prima…") are a later tranche, and a
// faithful translation of al-Zanātī's Arabic remains the deeper spine to converge on.
//
// A flagged crux: this printing inverts PUER and PUELLA against the common attribution
// — Puer falls under Venus and among the fortunate, Puella under Mars and the
// unfortunate (while Rubeus stays Mars, Amissio Venus). Almost certainly a transposition
// in this edition; we render the text as printed and note it, rather than silently fix it.
// CC BY-SA 4.0.
// ─────────────────────────────────────────────────────────────────────────────
'use strict';

export const GEOMANCY = {
  meta: {
    title: 'Of the Geomantic Figures',
    author: 'Robert Fludd, Tractatus de Geomantia, Liber II',
    license: 'CC BY-SA 4.0',
    method: 'A figure is four lines, top to bottom Fire · Air · Water · Earth; a line is single (•, odd) or double (• •, even). Below are Fludd’s sixteen figures with their names, forms and natures (element, fortune, sign and planet), translated from the Fasciculus Geomanticus (Verona, 1704), pp. 34–38, with the Latin shown.',
    sources: [
      { label: 'Fasciculus Geomanticus (Verona, 1704) — R. Fludd, Tractatus de Geomantia, Lib. II, pp. 34–38', host: 'archive.org/details/b3299753x', url: 'https://archive.org/details/b3299753x' },
      { label: 'al-Zanātī, Kitāb al-Faṣl fī uṣūl ʿilm al-raml — the deeper spine, to come', host: 'forthcoming', url: 'https://en.wikipedia.org/wiki/Arabic_geomancy' },
    ],
  },

  // Fludd's prefatory definition (p. 35), and his own classifying lists (pp. 37–38),
  // verbatim Latin beside English — the "source text" this translation points to.
  fludd: {
    preface: {
      la: 'Figuræ illæ, quæ possunt ex seriebus quatuor linearum Geomanticarum extrahi, sunt numero sedecim, quæ nomine ac forma ab invicem distinguuntur, ut sequitur.',
      en: 'Those figures which can be drawn out of the four series of geomantic lines are sixteen in number, distinguished one from another by name and by form, as follows.',
    },
    lists: [
      { head:'The elements (by the quarters of the world), p. 38',
        rows:[
          { la:'Igneæ, quæ habent ex plagis mundi Meridiem: Rubeus, Minor, Amissio, Cauda Draconis.', en:'Fiery, holding the South: Rubeus, Fortuna Minor, Amissio, Cauda Draconis.' },
          { la:'Aereæ, quæ habent Orientem: Lætitia, Puella, Acquisitio, Conjunctio.', en:'Airy, holding the East: Lætitia, Puella, Acquisitio, Coniunctio.' },
          { la:'Aqueæ, quæ habent Septentrionem: Populus, Via, Puer, Albus.', en:'Watery, holding the North: Populus, Via, Puer, Albus.' },
          { la:'Terreæ, quæ habent Occidentem: Major, Caput Draconis, Carcer, Tristitia.', en:'Earthy, holding the West: Fortuna Major, Caput Draconis, Carcer, Tristitia.' },
        ] },
      { head:'The fortunes (good, ill, and between), p. 38',
        rows:[
          { la:'Omnino bonæ & fortunatæ: Major, Lætitia, Caput Draconis, Albus, Puer, Acquisitio.', en:'Wholly good and fortunate: Fortuna Major, Lætitia, Caput Draconis, Albus, Puer, Acquisitio.' },
          { la:'Omnino malæ & infælices: Tristitia, Rubeus, Puella, Amissio, Cauda Draconis, Minor, Carcer.', en:'Wholly bad and unhappy: Tristitia, Rubeus, Puella, Amissio, Cauda Draconis, Fortuna Minor, Carcer.' },
          { la:'Nec bonæ omnino, nec omnino malæ, sed intermediæ: Populus, Via, Conjunctio.', en:'Neither wholly good nor wholly bad, but in between: Populus, Via, Coniunctio.' },
        ] },
      { head:'The signs of the Zodiac, p. 37',
        rows:[
          { la:'Acquisitio Arieti; Lætitia & Minor Tauro; Rubeus & Puer Geminis; Albus & Populus Cancro; Via Leoni; Caput Draconis & Conjunctio Virgini; Puella Libræ; Tristitia & Amissio Scorpioni; Cauda Draconis Sagittario; Populus Capricorno; Major Aquario; Carcer Piscibus.',
            en:'Acquisitio to Aries; Lætitia & Minor to Taurus; Rubeus & Puer to Gemini; Albus & Populus to Cancer; Via to Leo; Caput Draconis & Coniunctio to Virgo; Puella to Libra; Tristitia & Amissio to Scorpio; Cauda Draconis to Sagittarius; Populus to Capricorn; Major to Aquarius; Carcer to Pisces.' },
        ] },
      { head:'The planets (direct & retrograde), p. 37',
        rows:[
          { la:'Saturni: Directus Carceri, Retrogradus Tristitiæ. Jovis: Directus Lætitiæ, Retrogradus Acquisitioni. Martis: Directus Rubeo, Retrogradus Puellæ. Solis: Velox Majori, Tardus Minori. Veneris: Directa Puero, Retrograda Amissioni. Mercurii: Directus Albo, Retrogradus Conjunctioni. Lunæ: Directa Populo, Retrograda Viæ. Jupiter & Venus Directi, Capiti Draconis. Saturnus & Mars Retrogradi, Caudæ Draconis.',
            en:'Saturn: direct → Carcer, retrograde → Tristitia. Jupiter: direct → Lætitia, retrograde → Acquisitio. Mars: direct → Rubeus, retrograde → Puella. Sun: swift → Major, slow → Minor. Venus: direct → Puer, retrograde → Amissio. Mercury: direct → Albus, retrograde → Coniunctio. Moon: direct → Populus, retrograde → Via. Jupiter & Venus direct → Caput Draconis. Saturn & Mars retrograde → Cauda Draconis.' },
        ] },
      { head:'The strong, weak, and middling, p. 39',
        rows:[
          { la:'Fortes & stabiles: Major, Acquisitio, Lætitia, Puer, Albus, Caput Draconis.', en:'Strong and stable: Fortuna Major, Acquisitio, Lætitia, Puer, Albus, Caput Draconis.' },
          { la:'Debiles & mobiles: Minor, Amissio, Tristitia, Puella, Rubeus, Cauda Draconis.', en:'Weak and movable: Fortuna Minor, Amissio, Tristitia, Puella, Rubeus, Cauda Draconis.' },
          { la:'Mediocres, nec fortes nec debiles: Populus, Via, Conjunctio, Carcer.', en:'Middling, neither strong nor weak: Populus, Via, Coniunctio, Carcer.' },
        ] },
    ],
    houseDoctrine: {
      la:'Primæ duodecim scuti Geomantici domus referuntur 12 signis Zodiaci. Prima domus datur Arieti, estque mobilis; Secunda Tauro, fixa; Tertia Geminis, communis; Quarta Cancro, mobilis; Quinta Leoni, fixa; Sexta Virgini, communis; Septima Libræ, mobilis; Octava Scorpioni, fixa; Nona Sagittario, communis; Decima Capricorno, mobilis; Undecima Aquario, fixa; Duodecima Piscibus, communis. Quando figuræ in his domibus sunt, natura domus non mutatur, sed in se manet.',
      en:'The first twelve houses of the geomantic shield answer to the twelve signs of the Zodiac. The first house is given to Aries, and is movable; the second to Taurus, fixed; the third to Gemini, common; the fourth to Cancer, movable; the fifth to Leo, fixed; the sixth to Virgo, common; the seventh to Libra, movable; the eighth to Scorpio, fixed; the ninth to Sagittarius, common; the tenth to Capricorn, movable; the eleventh to Aquarius, fixed; the twelfth to Pisces, common. When figures stand in these houses the nature of the house is not changed, but remains itself.',
    },
    rules: [
      { la:'Figuræ stabiles & firmæ faciunt rem stabilem & firmam, sive in bono sive in malo, secundum quod figuræ inveniuntur in bona aut in mala domo.', en:'Stable and firm figures make the matter stable and firm — whether for good or for ill — according as they fall in a good or an ill house.' },
      { la:'Debiles figuræ judicium dant debiliter & sine stabilitate; nec sunt tam bonæ & stabiles quàm mediocres, aut pro morbo, aut pro incarcerato, aut prægravida.', en:'Weak figures give judgment weakly and without stability; nor are they as good and steady as the middling — whether for sickness, for a prisoner, or for a woman with child.' },
      { la:'Mediocres figuræ locum habent inter fortes & debiles, ac judicant quæstionem mediocriter, nec totaliter in bonum, nec totaliter in malum.', en:'Middling figures hold the place between strong and weak, and judge the question middlingly — neither wholly to good, nor wholly to ill.' },
      { la:'Domus malæ figuras per se bonas faciunt malas, per se malas faciunt adhuc pejores; è contra figuræ bonæ in bonis domibus sunt meliores.', en:'Ill houses turn figures good in themselves to bad, and figures bad in themselves to worse; whereas good figures in good houses are better still.' },
      { la:'Figura in domo contraria — fixa in mobili, vel mobilis in fixa — pejor redditur in judicio; at fixa in fixa, vel mobilis in mobili, fortiorem reddit significationem.', en:'A figure in a contrary house — fixed in a movable, or movable in a fixed — is made worse in judgment; but fixed in fixed, or movable in movable, gives a stronger signification.' },
    ],
  },

  // rows: [Fire, Air, Water, Earth]; 1 = single (odd), 2 = double (even).
  // element / nature / zodiac / planet are Fludd's own (pp. 37–38). nature: good|ill|mixed.
  figures: [
    { la:'Acquisitio', en:'Gain', rows:[2,1,2,1], element:'Air', nature:'good', zodiac:'Aries', planet:'Jupiter (retrograde)',
      sig:'Gain, profit, the getting of the thing desired — money, increase, success in business and ambition. The full purse.',
      note:'“Gain.” Fludd ranks it among the wholly fortunate (omnino bonæ), of Air and the East, under Jupiter retrograde, referred to Aries. Below: its signification in each of the fifteen shield-places, from Cap. III (pp. 41–43).',
      physiognomy:{ la:'Hæc figura in prima domo indicat hominem formosum, habentem flavescentes ac pulchros capillos, staturam corporis mediocrem, faciem rubram, & mutatorem ac mercatorem.',
        en:'In the first house this figure indicates a handsome man, with yellowish and beautiful hair, a middling stature, a ruddy face — a money-changer and a merchant.' },
      // the fifteen places of the shield: houses 1–12, then Right Witness (13), Left Witness (14), Judge (15)
      domus:[
        { la:'divitem, prudentem, proficuum, bonum finem, fortunatum, receptionem rei desideratæ; sed hæc figura non est bona ad rem aliquam vendendam: est enim verax.', en:'A rich and prudent man; profit; a good and fortunate end; the receiving of the thing desired — yet this figure is not good for selling anything, for it is truthful.' },
        { la:'divitias, lucrum proficuum, bonam fortunam in mercatura, rei promissæ receptionem, recuperationem rei deperditæ, incrementum omnium bonorum.', en:'Riches; profitable gain; good fortune in trade; the receiving of the thing promised; recovery of what was lost; the increase of all goods.' },
        { la:'bonam fortunam à parentibus, bonos parentes, fratres, vicinos, itinera bona, bonum sensum.', en:'Good fortune from parents; good parents, brothers and neighbours; good journeys; good sense.' },
        { la:'bonum patrimonium, bonam domum & utilem, in qua aliquis acquiret divitias, divitem patrem & dominantem, bonum finem omnium hæreditatum.', en:'A good patrimony; a good and useful house in which one will gain riches; a rich and ruling father; a good end of all inheritances.' },
        { la:'proficuum ex liberis suis, bonos liberos & divites, bonas literas, bona vestimenta, lætitiam cordis, delitias cum mulieribus, fructus hæreditatum.', en:'Profit from one’s children; good and wealthy children; good learning; fine garments; gladness of heart; delight with women; the fruits of inheritances.' },
        { la:'longum morbum, qui tamen curabitur, bonas bestias, bonos servos & utiles.', en:'A long sickness, which nonetheless will be cured; good beasts; good and useful servants.' },
        { la:'castam fœminam, placabilem, bonam societatem, bonas mercantias, pacem & reconciliationem cum inimicis, sive sit in lite judiciali, sive in bello.', en:'A chaste and peaceable woman; good fellowship; good merchandise; peace and reconciliation with enemies, whether in a lawsuit or in war.' },
        { la:'restitutionem damni, mortem naturalem, proficuum in terra aliena, securitatem à timore mortis, inimicum felicem & divitem.', en:'Restitution of loss; a natural death; profit in a foreign land; safety from the fear of death; an enemy who is fortunate and rich.' },
        { la:'proficuum ex morte, viam seu iter, timorem Dei, bonum & securum iter, bona beneficia, bonum somnium, bonum sensum in omnibus actibus, bonam devotionem in Deum & Ecclesiam, bonum pro rebus Ecclesiasticis.', en:'Profit from a death; a way or journey; the fear of God; a good and safe journey; good benefices; a good dream; good sense in all one’s acts; good devotion toward God and the Church; good for Church affairs.' },
        { la:'proficuum Dominorum, regis, omnes Dominos pacificos & felices, obtentionémque desiderii tui, ab iisdem officia utilia, bonam sententiam à judice.', en:'Profit from lords and the king; all lords peaceable and fortunate; the gaining of your desire; from them, useful offices; a good sentence from the judge.' },
        { la:'bonam fortunam, bonos amicos, lucrum in mercantia, subitaneam proficui receptionem.', en:'Good fortune; good friends; gain in trade; a sudden receiving of profit.' },
        { la:'paupertatem & incarcerationem pro debitis, proficuum servorum & bestiarum, longam incarcerationem, bonum pro morbo, & ad recipienda debita.', en:'Poverty and imprisonment for debt; profit of servants and beasts; a long imprisonment; good for sickness, and for recovering debts.' },
        { la:'damnum & mutationem proficui, bonum iter & acquisitionem in omni receptione, implementum desiderii absentis.', en:'Loss and a turn of profit; a good journey and gain in every receiving; the fulfilment of an absent one’s desire.' },
        { la:'proficuum in re omni quam aliquis sperat, longam vitam, fortunam, omnem utilitatem & bonitatem.', en:'Profit in every matter one hopes for; long life; fortune; all use and good.' },
        { la:'bonitatem in omni re, recuperationem rei perditæ, retardationem itinerum.', en:'Good in every matter; the recovery of a lost thing; the delaying of journeys.' },
      ] },
    { la:'Cauda Draconis', en:'The Tail of the Dragon', rows:[1,1,1,2], element:'Fire', nature:'ill', zodiac:'Sagittarius', planet:'Saturn & Mars (retrograde)',
      sig:'A threshold outward: endings, exits, release, the close of a matter. Good for what should be finished or let go; ill for beginnings and keeping.',
      note:'The descending node, the door out. Fludd: wholly ill, Fiery, of the South; Saturn & Mars retrograde; Sagittarius. Reversion of Caput. From Cap. III (pp. 52–54); the print gives fourteen places (the fifteenth omitted).',
      physiognomy:{ la:'Quando hæc figura reperitur in prima domo, denotat damnum, & hominem mediocris staturæ, rotundam faciem, longum nasum, magnum os, magnos dentes, caput calvum, magnam barbam.', en:'When this figure is in the first house, it denotes loss, and a man of middling stature, a round face, a long nose, a large mouth, big teeth, a bald head, and a great beard.' },
      domus:[
        { la:'malam acquisitionem, paupertatem, malam viam, vexationem & iracundiam, nullam rei desideratæ acquisitionem, hominem pessimum & iracundum.', en:'Ill gain; poverty; an ill way; vexation and wrath; no gaining of the thing desired; a most wicked and wrathful man.' },
        { la:'damnum bonorum omnium & infortunium in re omni.', en:'The loss of all goods, and misfortune in every matter.' },
        { la:'angorem cognati & pauxillum lucri, malum fratrem, malos parentes & vicinos, malam viam, malum somnium, & totum malum.', en:'Anguish of a kinsman, and little gain; a bad brother; bad parents and neighbours; an ill way; an ill dream; and all ill.' },
        { la:'malam domum, malas hereditates, decrementum proficui.', en:'An ill house; ill inheritances; the decrease of profit.' },
        { la:'detrimentum à malis per malos liberos, per fructus, per inimicos, malos nuntios, malas literas, malos liberos, tristitiam cordis, vexationem & iram, dubium an infans pereat in utero; nullos amores nec oscula, sed rixas & contentiones pro fœmina, ac omnia mala secundum domum.', en:'Harm from the wicked — through bad children, through fruits, through enemies; bad messengers; bad letters; bad children; sorrow of heart; vexation and wrath; doubt whether the infant perish in the womb; no loves nor kisses, but brawls and quarrels over a woman; and all ills according to the house.' },
        { la:'mortem aut ægritudinem, perturbationem bestiarum, malam fortunam, magnas ægritudines & angustias, malos servos & fugitivos, malum ad recipiendas dotes de fœminis, injurias.', en:'Death or sickness; the disturbance of beasts; ill fortune; great sicknesses and straits; bad and fugitive servants; ill for recovering dowries from women; injuries.' },
        { la:'malam fœminam & furtivam, latrocinium, malum sodalem; fœminam rixosam, luxuriosam; latrones, omne malum pro mercantia, aut pro omni re de itinere & nuntiis, nullam nisi mali inventionem in loco quo intendit aliquis ire & negotiari.', en:'An ill and thievish woman; robbery; a bad companion; a quarrelsome, lustful woman; thieves; every ill for trade, or for any matter of journey and messages; nothing but the finding of evil in the place one means to go and do business.' },
        { la:'mortem, perditionem bonorum, patrimonii & hereditatis, damnum in regione aliena, pavorem, desperationem, damnum de morte, traditionem, damnum de inimico petitoris, iram & perturbationem.', en:'Death; the loss of goods, patrimony, and inheritance; loss in a foreign region; terror; despair; loss by a death; betrayal; harm from the petitioner’s enemy; wrath and disturbance.' },
        { la:'viam, egressum ex alto loco dominii, malum iter & lachrymosum (si duplicet, est malum signum proditionis, verberum & vulnerum in via), malum somnium, malum Ecclesiæ & pro hominibus Ecclesiasticis, artes & scientias inutiles, nam magisterium nihil boni aut proficui afferet.', en:'A journey; a going-out from a high seat of lordship; an ill and tearful road (if it be doubled, an ill sign of betrayal, of beatings and wounds on the way); an ill dream; ill for the Church and for churchmen; useless arts and sciences, for one’s craft will bring nothing good or profitable.' },
        { la:'egressum de bono loco & de dominio quod aliquis perdet; item dat signum aliquem victum esse, & de suis terris ac beneficiis expulsum, minaturque omne malum secundum naturam domus.', en:'A going-out from a good place and from a lordship one will lose; likewise it gives the sign that someone is conquered, and driven from his lands and benefices; and it threatens every ill according to the nature of the house.' },
        { la:'spei inventionem, inimicorum pro amicis reputationem, amicos luxuriosos, malos, traditores & mendaces, malam fortunam, damnum in mercantia, signum quod res perdetur, reditum absentis aut quod repelletur fortiori manu, malam spem, & in loco aliquod odium incurrere.', en:'A finding of hope; the reckoning of enemies as friends; friends lustful, bad, traitors and liars; ill fortune; loss in trade; a sign that the thing will be lost; the return of an absent one — or that he is driven back by a stronger hand; ill hope; and the incurring of some hatred in a place.' },
        { la:'evasionem & fugam pro debitis, mortem ægroto, egressum de carcere, damnum bestiarum, inimicum, pavorem, equum vulneratum; inimicos rebelles & feroces, traditores & deceptores.', en:'Escape and flight on account of debts; death for the sick; release from prison; loss of beasts; an enemy; terror; a wounded horse; enemies rebellious and fierce, traitors and deceivers.' },
        { la:'malam recuperationem rei perditæ, mutationem de itinere, periculosam iram petitoris, lites & malam fortunam.', en:'An ill recovery of a lost thing; a change of journey; the dangerous wrath of the petitioner; lawsuits and ill fortune.' },
        { la:'inimicos pro amicis, damnum in mercantia, malum finem pro re aliqua petita, totum malum.', en:'Enemies in place of friends; loss in trade; an ill end for anything sought; all ill.' },
      ] },
    { la:'Puer', en:'The Boy', rows:[1,1,2,1], element:'Water', nature:'good', zodiac:'Gemini', planet:'Venus (direct)',
      sig:'The young soldier — heat, drive, boldness, the rush to act; fierce in war, contest and love.',
      note:'CRUX: this edition counts Puer among the wholly fortunate and gives it Venus (direct) — the reverse of the common attribution (Mars, and ill). Almost certainly a Puer/Puella transposition in this printing; rendered as printed, flagged. Fludd: of Water, the North; Gemini. From Cap. III (pp. 59–61); uniquely, the print gives all SIXTEEN places (through the Reconciler) — and they read light and lucky throughout, which fits the favourable classing here.',
      physiognomy:{ la:'Quando est hæc figura in prima domo, significat hominem juvenem, pulchrum & boni vultus, sine barba, luxuriosum, instrumenta & Musicam amantem, Monachos, Hypocritas & scholares.', en:'When this figure is in the first house, it signifies a young man, handsome and of good countenance, beardless, lustful, loving instruments and music; monks, hypocrites, and scholars.' },
      domus:[
        { la:'gaudium, spem, nuptias, hilarem more infantis, qui nihil nisi canere ac tempus fallere, Musicâ & societatem mulierum amat.', en:'Joy; hope; marriages; one cheerful after the manner of a child, who loves nothing but to sing and while away the time, fond of music and the company of women.' },
        { la:'proficuum in mercantia, bonam fortunam, lucrum bonum, societatem fœminarum, debitorum receptionem.', en:'Profit in trade; good fortune; good gain; the company of women; the receiving of debts.' },
        { la:'lætitiam ratione fratris & vicini, vicinos charos & hilares, bonum iter, bonum somnium & nova jucunda.', en:'Joy by reason of a brother and neighbour; dear and cheerful neighbours; a good journey; a good dream and pleasant news.' },
        { la:'prælia, nullam rei quæsitæ acquisitionem, recusationem rei quam quis desiderat, aquam.', en:'Battles; no gaining of the thing sought; the refusal of the thing one desires; water.' },
        { la:'gaudium, bonos liberos, nuntia & literas, bona nova, delectationes, amorem & delitias cum fœminis, instrumenta Musica.', en:'Joy; good children; messages and letters; good news; delights; love and pleasures with women; musical instruments.' },
        { la:'bonos servos, stultas fœminas, filios fornicationis, bonas bestias, longos seu diuturnos morbos.', en:'Good servants; foolish women; sons of fornication; good beasts; long or lingering sicknesses.' },
        { la:'malas fœminas & stultas, fornicationem & malam societatem, nuptias liberorum.', en:'Bad and foolish women; fornication and ill fellowship; the marriages of children.' },
        { la:'mortem & morbos.', en:'Death and sicknesses.' },
        { la:'iter per terram, falsam credentiam, lubricitatem Ecclesiæ.', en:'A journey by land; false credit; the laxity of the Church.' },
        { la:'litem pro fœmina, aut pro servis, aut liberis in judicio seu ante judicem, servitium alicujus Domini.', en:'A suit over a woman, or over servants or children, in judgment or before a judge; the service of some lord.' },
        { la:'gaudium, fortunam, bonum amorem, amorem fœminarum & hominum pro luxuria.', en:'Joy; fortune; good love; the love of women and men for lust.' },
        { la:'Victoriam, malum hominem, pericula, carceres, defectum illius rei quæ quæritur, bonas bestias, inimicos fortes & malos.', en:'Victory; an ill man; perils; prisons; the failure of the thing sought; good beasts; enemies strong and wicked.' },
        { la:'gaudium & proficuum provenientia de magnis hominibus, literas, nuntios, vitam, gaudium & itinera.', en:'Joy and profit coming from great men; letters; messages; life; joy and journeys.' },
        { la:'periculum sed postea bonum finem, bene bibere, bene comedere, nuntios & amores.', en:'Peril, but afterward a good end; good drinking; good eating; messages and loves.' },
        { la:'temperantiam, proficuum de omnibus rebus, & complementum bonorum.', en:'Temperance; profit from all things; and the completion of goods.' },
        { la:'omne bonum.', en:'Every good.' },
      ] },
    { la:'Fortuna Minor', en:'The Lesser Fortune', rows:[1,1,2,2], element:'Fire', nature:'ill', zodiac:'Taurus', planet:'Sun (slow)',
      sig:'Swift, outward, lesser fortune — success had quickly, through others or by speed, but not built to last.',
      note:'Fludd ranks it among the ill (omnino malæ), Fiery, of the South; the Sun “slow” (tardus); Taurus. “Fortune going out.” From Cap. III (pp. 65–67); fifteen places — which, oddly, read largely fortunate (kings, treasures, gold, victory), sitting uneasily with the “wholly ill” label. The twelfth carries a cross-figure rule: doubled in the tenth house, it denotes a king “the loss of his realm.”',
      physiognomy:{ la:'Minor in prima domo significat Regem aut Reginam, hominem pulchrum & animosum, vestitum rubro, qui volet sæpe peregrinari, tegiturque auro.', en:'Minor in the first house signifies a king or a queen; a handsome and spirited man, dressed in red, who will often wish to travel, and is covered with gold.' },
      domus:[
        { la:'bonitatem, bonum iter ad Principes & Dominos, hominem divitem & fortunatum, item Regem, Principem, Ducem, hominem magnæ autoritatis, scientiam, bonas bestias, bonam uxorem & humilem.', en:'Goodness; a good journey to princes and lords; a rich and fortunate man — also a king, a prince, a duke; a man of great authority; knowledge; good beasts; a good and humble wife.' },
        { la:'acquisitionem domus à Domino aut viro magno, & quidem sine labore.', en:'The gaining of a house from a lord or a great man, and indeed without toil.' },
        { la:'bonos fratres, ac divitias & proficuum ab iis, bonos vicinos, bonam scientiam ac bonam fidem, bona itinera, & præcipuè per mare, bonam fœminam.', en:'Good brothers, and riches and profit from them; good neighbours; good knowledge and good faith; good journeys, especially by sea; a good woman.' },
        { la:'thesauros regum aut magnatum, bona itinera ad parentes, nobilem hereditatem, & hereditatum acquisitionem.', en:'The treasures of kings or magnates; good journeys to parents; a noble inheritance, and the gaining of inheritances.' },
        { la:'bonos liberos, bona nova, bonum iter versus liberos, gaudium & solatium, itinera utilia, jucunditates & delitias nobilium.', en:'Good children; good news; a good journey toward one’s children; joy and solace; useful journeys; the pleasures and delights of the noble.' },
        { la:'morbos regum & principum, injuriasque ipsorum ab aliis Dominis, item victum ab iis, timorem perdendæ dominationis suæ aut regni, servos superbos.', en:'The sicknesses of kings and princes, and injuries to them from other lords; likewise sustenance from them; the fear of losing one’s dominion or realm; proud servants.' },
        { la:'bonam fœminam, pulchram & divitem, sed dubium erit, ne stulto amore perdatur; homicidium à magno homine perpetratum; filio denotat nobilitatem matrimonii & bona itinera.', en:'A good woman, beautiful and rich — but it will be doubtful, lest the matter be ruined by foolish love; a murder committed by a great man; for a son it denotes the nobility of a marriage and good journeys.' },
        { la:'mortem regum aut timorem regum, ita ut ille qui quæstionem facit timeat eos, timorem sensus perdendi; & si Rubeus in septima domo reperiatur, mortem per effusionem sanguinis; non bonum egredi è patria vel iter facere, timenda enim est incarceratio aut mors violenta.', en:'The death of kings, or the fear of kings, such that he who asks the question fears them; the fear of losing one’s senses; and if Rubeus be found in the seventh house, death by the shedding of blood; not good to leave one’s country or to make a journey, for imprisonment or a violent death is to be feared.' },
        { la:'bonum iter, bonam affinitatem regum aut prælatorum ad gratiam obtinendam, hominem fidelem, bonæ fidei Deumque timentem.', en:'A good journey; good kinship with kings or prelates for obtaining favour; a faithful man, of good faith and God-fearing.' },
        { la:'bonum Regem & regnantem bonis virtutibus ac victoria, bonum ad migrationem per mare & itinera facienda, acquisitionem rei à Principe aut Rege, acquisitionem proficui amore judicis, lucrum & honorem.', en:'A good king, reigning with good virtues and victory; good for migration by sea and for making journeys; the gaining of a thing from a prince or king; the gaining of profit through the judge’s favour; gain and honour.' },
        { la:'bonam spem, bonos amicos, bonam fortunam, bonam societatem, proficuum in bestiis & servis.', en:'Good hope; good friends; good fortune; good fellowship; profit in beasts and servants.' },
        { la:'bonas bestias, egressum è carcere, paupertatem petitoris, & pro illa ubi duplicatur, ac præcipue in decima domo, denotat regi amissionem regni aut per se aut per liberos suos.', en:'Good beasts; release from prison; the poverty of the petitioner; and where it is doubled, especially in the tenth house, it denotes to a king the loss of his realm, whether through himself or through his children.' },
        { la:'proficuum in via, & acquisitionem petitionis à Domino aliquo.', en:'Profit on the way, and the gaining of the petition from some lord.' },
        { la:'longam vitam, bonam fortunam, proficuum in re de qua sperat.', en:'Long life; good fortune; profit in the matter one hopes for.' },
        { la:'bonum eventum in omnibus rebus bonis, bonum finem, bonam societatem, honorem ac gloriam.', en:'A good outcome in all good matters; a good end; good fellowship; honour and glory.' },
      ] },
    { la:'Puella', en:'The Girl', rows:[1,2,1,1], element:'Air', nature:'ill', zodiac:'Libra', planet:'Mars (retrograde)',
      sig:'Harmony, beauty, affection, peace — favourable in love and pleasant dealings, pure but changeable.',
      note:'CRUX: Fludd’s printing counts Puella among the ill and gives it Mars (retrograde) — the reverse of the usual reading (Venus, and good). The likely transposition with Puer; rendered as printed, flagged. Fludd: of Air, the East; Libra. From Cap. III (pp. 61–62); the print gives fourteen places. Tellingly, the place-significations read Venusian and mixed-to-favourable (love, talk, “good friends,” “good fortune,” “profit”) — at odds with the “wholly ill” label, further corroborating the transposition.',
      physiognomy:{ la:'Quando invenitur hæc figura in prima domo, denotat hominem habentem parvulum corpus & curtum collum, magnum caput, dentes malè ordinatos seu dispositos, subtile ingenium.', en:'When this figure is found in the first house, it denotes one having a small body and a short neck, a large head, teeth ill-ordered or ill-set, and a subtle wit.' },
      domus:[
        { la:'lætitiam amicorum, victus, infantes habere, verba lubrica & luxuriosa, mendaces, plenos loquelæ superfluæ.', en:'The joy of friends; sustenance; the having of children; slippery and lustful words; liars, full of superfluous talk.' },
        { la:'proficuum, inclinationem ad prodigalitatem.', en:'Profit; an inclination to prodigality.' },
        { la:'amores parentum, bonam societatem, bonos cognatos, multum loquelæ, lassitudinem in itinere, & nonnunquam latrones.', en:'The loves of parents; good fellowship; good kinsmen; much talk; weariness on a journey; and sometimes thieves.' },
        { la:'proficuum in magisteriis amoris, de patre & matre, pro hereditatibus, parvos fructus, loquelas luxuriosas & inhonestas in domo.', en:'Profit in the crafts of love, from father and mother, for inheritances; small fruits; lustful and dishonest talk in the house.' },
        { la:'liberos lætos, nuntios, literas, delitias, verba superflua de luxuria, amores fœminarum, mendaces, viles.', en:'Glad children; messages; letters; delights; superfluous words about lust; the loves of women; liars, base.' },
        { la:'malas fœminas, morbum servorum, lucrum in bestiis, plenos loquelæ jactabundæ & luxuriosæ, morbos videlicet ulcera, tumores, contusiones, & similia.', en:'Bad women; the sickness of servants; gain in beasts; [people] full of boastful and lustful talk; sicknesses, namely ulcers, tumours, bruises, and the like.' },
        { la:'nuptias, proficuum sodalium, gaudia fœminarum, multorum verborum & luxuriosorum, meretrices & fœminas inhonestas, quæ tangunt alios præter meritum.', en:'Marriages; the profit of companions; the joys of women; [people] of many and lustful words; harlots and dishonest women, who touch others beyond their desert.' },
        { la:'mortem parentum aut sororum, hereditates mortuorum, multa verba, mortem servorum in regione exotica.', en:'The death of parents or sisters; the inheritances of the dead; much talk; the death of servants in a foreign land.' },
        { la:'proficuum in via, multum sensus, hominem magis amantem lætitiam & hilaritatem quàm preces & cultum divinum, somnia, nova non multum valentia, bonum intellectum in suo magisterio, ovantem, processum & perturbationem pro Ecclesia.', en:'Profit on the way; much sense; a man who loves joy and cheerfulness more than prayers and divine worship; dreams; news not worth much; good understanding in one’s craft; one rejoicing; progress and disturbance for the Church.' },
        { la:'lætitiam & proficuum in via de Domino, bonum Domino & officiis, sed multum loquelæ antea dictæ.', en:'Joy and profit on the way from a lord; good for a lord and for offices; but much of the aforesaid talk.' },
        { la:'bonos amicos, proficuum de servis & bestiis ac bonam fortunam, multum loquelæ, appetentes luxuriam & fornicationem.', en:'Good friends; profit from servants and beasts, and good fortune; much talk; [those] craving luxury and fornication.' },
        { la:'loquacitatem, proficuum de bestiis & servis, inimicos plenos litis, bestias satis bonas.', en:'Loquacity; profit from beasts and servants; enemies full of strife; beasts good enough.' },
        { la:'proficuum in via & itinere, proficuum à Dominis quibusdam.', en:'Profit on the way and on a journey; profit from certain lords.' },
        { la:'bonam fortunam, proficuum in periculo.', en:'Good fortune; profit in peril.' },
      ] },
    { la:'Amissio', en:'Loss', rows:[1,2,1,2], element:'Fire', nature:'ill', zodiac:'Scorpio', planet:'Venus (retrograde)',
      sig:'Loss, the slipping-away of things, what leaves the hand — the mirror of Acquisitio; good only where one wishes to be free of a thing.',
      note:'“Loss.” Fludd: wholly ill, Fiery, of the South; Venus retrograde; Scorpio. The inversion of Acquisitio. Below: its signification in the fifteen shield-places, from Cap. III (pp. 44–45).',
      physiognomy:{ la:'Quando hæc figura Amissio reperitur in prima domo, significat hominem pallidum, mendacem, rapacem, latronem.', en:'When Amissio is found in the first house, it signifies a pale man, a liar, rapacious — a thief.' },
      domus:[
        { la:'hominem audacem, instabilem, plenum criminis ac deceptionis, nihili receptionem.', en:'A bold and unstable man, full of crime and deceit; the receiving of nothing.' },
        { la:'damnum in mercantia & bonis suis, nihil lucri, damnum omnium bonorum ex latronibus.', en:'Loss in trade and in one’s goods; no gain; the loss of all goods to robbers.' },
        { la:'inimicitiam inter propinquiores, parentes, fratres & vicinos, fallaciâ plenum, timorem in itinere.', en:'Enmity among close kin — parents, brothers, neighbours; full of deceit; fear on a journey.' },
        { la:'falsitatem & damnum hereditatis ac patrimonii, malum finem civitatis aut domus.', en:'Falsehood and loss of inheritance and patrimony; an ill end of city or house.' },
        { la:'damnum fructuum, hereditatum, malos liberos & mobiles, malas literas, nullam delectationem in amore fœminarum levium.', en:'Loss of fruits and inheritances; bad and fickle children; bad letters; no delight in the love of light women.' },
        { la:'evasionem à morbo, damnum bestiarum, fugam servorum, similiter injuriam ac pravitatem.', en:'Escape from sickness; loss of beasts; the flight of servants; likewise injury and depravity.' },
        { la:'malam fœminam, litem cum suo Domino aut sodalibus, fœminam instabilem & luxuriosam, damnum in mercantia, latrones fugitivos, sodales inimicos, mutabiles & deceptores, malam mutationem.', en:'An ill woman; strife with one’s lord or companions; an unstable, lustful woman; loss in trade; fugitive thieves; companions who are enemies, fickle and deceivers; an ill change.' },
        { la:'damnum ex morte, perditionem sensus, nihil proficui in loco quo aliquis vadit, pauperes inimicos, perditionem dotium mulierum.', en:'Loss by death; loss of one’s senses; no profit in the place one goes; poor enemies; the loss of women’s dowries.' },
        { la:'longam viam sine jucunditate, nihil scientiæ, malum aliquod pro petitore ab Ecclesia.', en:'A long journey without joy; no learning; some ill for the petitioner from the Church.' },
        { la:'malos Dominos, perditionem honoris, dominii aut officii, Dominos instabiles, tribulationes regnorum, impedimenta honoris.', en:'Ill lords; loss of honour, lordship, or office; unstable lords; the troubles of kingdoms; hindrances to honour.' },
        { la:'perditionem amicorum suorum, perditionem seu damnum in mercantia, falsam spem, amicos mutabiles & inutiles.', en:'The loss of one’s friends; loss or damage in trade; false hope; friends fickle and useless.' },
        { la:'damnum bestiarum, exitum de debitis, malam mutationem, exitum de carcere, amicos falsitatis plenos, mutabiles & derisores.', en:'Loss of beasts; a way out of debts; an ill change; release from prison; friends full of falsehood, fickle, and mockers.' },
        { la:'damnum & mutationem in superioritate seu magistratu aut gubernatione, malam fortunam.', en:'Loss and change in high place, office, or governance; ill fortune.' },
        { la:'damnum amicorum, magnum laborem in quacunque re.', en:'Loss of friends; great toil in whatever matter.' },
        { la:'nihili receptionem, malum finem.', en:'The receiving of nothing; an ill end.' },
      ] },
    { la:'Carcer', en:'The Prison', rows:[1,2,2,1], element:'Earth', nature:'ill', zodiac:'Pisces', planet:'Saturn (direct)',
      sig:'Binding, restriction, delay, confinement, isolation — ill for freedom and progress, yet steadying for what must be fixed or kept.',
      note:'“The prison,” a closed cell. Fludd: wholly ill, Earthy, of the West; Saturn direct; Pisces.' },
    { la:'Laetitia', en:'Joy', rows:[1,2,2,2], element:'Air', nature:'good', zodiac:'Taurus', planet:'Jupiter (direct)',
      sig:'Joy, health, gladness, good news; things rising and lightening — happiness, recovery, elevation.',
      note:'“Joy.” Fludd: wholly fortunate, Airy, of the East; Jupiter direct; Taurus. From Cap. III (pp. 46–47). CRUX: this printing lists only fourteen places, omitting the fifteenth (the Judge-place) — likely a printer’s omission.',
      physiognomy:{ la:'Quando hæc figura reperitur in prima domo, significat Episcopum, prælatum Ecclesiæ, religiosum & Ecclesiasticum, longam barbam, malum aliquod existens in digito, manentem in locis altis.', en:'When this figure is in the first house, it signifies a bishop, a prelate of the Church, a religious and an ecclesiastic; a long beard; some blemish on a finger; one who dwells in high places.' },
      domus:[
        { la:'judices, sapientes homines, bonam & rectam vitam, plenitudinem lætitiæ & exaltationis, gaudium petitori in omnibus rebus.', en:'Judges and wise men; a good and upright life; fullness of joy and exaltation; gladness to the petitioner in all things.' },
        { la:'multitudinem bonorum, vitam fidelitatis & gaudii plenam.', en:'An abundance of goods; a life full of faithfulness and joy.' },
        { la:'bonam fortunam in fratribus suis, nullum timorem Dei, bonum amorem fratrum, vicinorum, parentum, omnem lætitiam in re omne.', en:'Good fortune in one’s brothers; no fear of God; good love of brothers, neighbours and parents; all joy in every matter.' },
        { la:'proficuum hereditatum & omnium rerum super terram, lætum finem, lætitiam in domibus, lætitiam parentum, hereditaria pacifica.', en:'Profit of inheritances and of all things upon earth; a glad end; joy in the houses; the joy of parents; peaceful inheritances.' },
        { la:'proficuum liberorum, longam vitam, lætitiam in re omni, lætas ac jucundas literas & nuntia, lætitiam fœminarum & omnium bonorum.', en:'Profit of children; long life; joy in every matter; glad and pleasant letters and news; the joy of women and of all goods.' },
        { la:'servos, bestias emersas è morbo, servos jucundos & hilares.', en:'Servants; beasts recovered from sickness; servants pleasant and cheerful.' },
        { la:'bonas nuptias, proficuum sociorum seu ex sociis, victoriam ex causa fœminæ hilaris & castæ, hilarem societatem, pacem & concordiam, bonam mutationem.', en:'Good marriages; profit of partners or from partners; victory through a cheerful and chaste woman; cheerful fellowship; peace and concord; a good change.' },
        { la:'proficuum hereditatum à mortuis, evasionem ex pavore, lucrum & proficuum in loco quo itur.', en:'Profit of inheritances from the dead; escape from terror; gain and profit in the place one goes.' },
        { la:'itinera, timorem Dei, scientiam, fidelitatem, hilaritatem, sanctos homines, Ecclesiæ negotia, bona nova, artes subtiles, devotionem & amorem Ecclesiæ.', en:'Journeys; the fear of God; knowledge; faithfulness; cheerfulness; holy men; Church affairs; good news; subtle arts; devotion and love of the Church.' },
        { la:'exaltationem magnorum honorum, Episcoporum, & Prælatorum auxilium à Dominis, officium lætum & hilare, pulchra templa, bonum judicem, justam & bonam sententiam, locum calidum.', en:'The raising of great honours; bishops, and the help of prelates from lords; a glad and cheerful office; beautiful temples; a good judge; a just and good sentence; a warm place.' },
        { la:'bonam fortunam sodalium, proficuum bestiarum, lætitiam, amorem, bonam spem de bono homine, hilares & bonos amicos, hominem prudentem & bonæ scientiæ, lucrum in mercantia.', en:'Good fortune of companions; profit of beasts; joy; love; good hope of a good man; cheerful and good friends; a prudent man of good knowledge; gain in trade.' },
        { la:'proficuum bestiarum & servorum, egressum ex carcere, liberationem à carcere debitorum ac ab omni tribulatione, pacem & reconciliationem inimicorum.', en:'Profit of beasts and servants; release from prison; freeing from the prison of debts and from all tribulation; peace and reconciliation of enemies.' },
        { la:'proficuum ex itinere, à rege, à Domino, mutationem omnium bonorum.', en:'Profit from a journey, from the king, from a lord; a turn of all goods to the better.' },
        { la:'bonam spem implendi suam voluntatem, lætam spem, perfectionem suæ voluntatis in gaudio & exaltatione.', en:'Good hope of fulfilling one’s will; glad hope; the fulfilment of one’s will in joy and exaltation.' },
      ] },
    { la:'Caput Draconis', en:'The Head of the Dragon', rows:[2,1,1,1], element:'Earth', nature:'good', zodiac:'Virgo', planet:'Jupiter & Venus (direct)',
      sig:'A threshold inward: beginnings, entries, the open door, a good foundation; it takes the good or ill of its company, but is good of itself.',
      note:'The ascending node, the door in. Fludd: wholly fortunate, Earthy, of the West; Jupiter & Venus direct; Virgo. Reversion of Cauda. From Cap. III (pp. 50–52); the print gives fourteen places (the fifteenth omitted).',
      physiognomy:{ la:'Quando hæc figura est in prima domo, denotat Principem vel judicem boni consilii, habentem pulchros capillos, qui est superbus.', en:'When this figure is in the first house, it denotes a prince or a judge of good counsel, with beautiful hair, who is proud.' },
      domus:[
        { la:'bonam fortunam & dulcem, hominem sapientem, disertum, prudentem, & qui tenet res suas secretè, ac habet cogitationem firmam & stabilem in omnibus bonis. Et est hæc figura natura sua valde bona.', en:'Good and sweet fortune; a wise man, eloquent and prudent, who keeps his affairs secret, with a firm and steady mind in all good things. And this figure is by its own nature very good.' },
        { la:'proficuum & lucrum in mercantia, divitias, bonam fortunam, & omnium rerum acquisitionem secretam.', en:'Profit and gain in trade; riches; good fortune; and the secret gaining of all things.' },
        { la:'bonos parentes, bonos vicinos, bonam fidem, retardationem itineris pro aliquo bono.', en:'Good parents; good neighbours; good faith; the delaying of a journey for some good.' },
        { la:'proficuum & acquisitionem hereditatum, bonam domum, bonum patrimonium, patrem discretum, bonum finem, pacem in suo magisterio.', en:'Profit and the gaining of inheritances; a good house; a good patrimony; a discreet father; a good end; peace in one’s craft.' },
        { la:'amorem infantum, bonos liberos, gaudium, literas secretas, fœminas gravidas, honestè contentum amore fœminæ, bonum amorem.', en:'The love of infants; good children; joy; secret letters; pregnant women; one honourably content with a woman’s love; good love.' },
        { la:'longum morbum, proficuum in re omni, servos secretos & discretos, bonas bestias & utiles, longum morbum & secretum.', en:'A long sickness; profit in every matter; secret and discreet servants; good and useful beasts; a long and hidden sickness.' },
        { la:'bonas nuptias, bonam fœminam & castam, bonam societatem, inimicos subtiles & fortes, bonam mutationem, bonum proficuum in mercantia, malum pro exitu.', en:'Good marriages; a good and chaste woman; good fellowship; enemies subtle and strong; a good change; good profit in trade; ill for departure.' },
        { la:'mortem aut morbum, lucrum denariorum, amorem, recuperationem rei perditæ, mortem secretam, receptionem pecuniarum de morte, securitatem à timore.', en:'Death or sickness; gain of money; love; the recovery of a lost thing; a secret death; the receiving of monies from a death; safety from fear.' },
        { la:'itinera & reditum ejus qui est extra patriam, literas, bonam credentiam, retardationem itineris, bonam fidem, hominem sanctum Ecclesiæ, scientiam in omnibus artibus, bonum pro Ecclesia, honorem.', en:'Journeys, and the return of one abroad; letters; good credit; the delaying of a journey; good faith; a holy man of the Church; knowledge in all arts; good for the Church; honour.' },
        { la:'bonum judicium, multitudinem denariorum, sapientem regem, magnum honorem dominii & officii, multum divitiarum, conciliationem gratiæ judicis sententiamque discretam.', en:'Good judgment; a multitude of money; a wise king; great honour of lordship and office; much riches; the winning of the judge’s favour, and a discreet sentence.' },
        { la:'bonam fortunam, lætitiam, bonos amicos & fideles, bonam spem, bonum lucrum.', en:'Good fortune; joy; good and faithful friends; good hope; good gain.' },
        { la:'paupertatem, longam incarcerationem, bonas bestias, bonas literas.', en:'Poverty; a long imprisonment; good beasts; good letters.' },
        { la:'reditum illius qui est extra patriam, proficuum Domini, bona nova absentis, proficuam & bonam mutationem.', en:'The return of one abroad; the lord’s profit; good news of an absent one; a profitable and good change.' },
        { la:'bonam fortunam, bonam spem, longam vitam, proficuum per totum.', en:'Good fortune; good hope; long life; profit throughout.' },
      ] },
    { la:'Coniunctio', en:'Conjunction', rows:[2,1,1,2], element:'Air', nature:'mixed', zodiac:'Virgo', planet:'Mercury (retrograde)',
      sig:'Meeting, union, the coming-together of things or people; recovery of what was lost. Good with the good and ill with the ill — it joins whatever it touches.',
      note:'“Conjunction.” Fludd: intermediate (nec bona nec mala), Airy, of the East; Mercury retrograde; Virgo.' },
    { la:'Rubeus', en:'Red', rows:[2,1,2,2], element:'Fire', nature:'ill', zodiac:'Gemini', planet:'Mars (direct)',
      sig:'Heat of the blood — passion, anger, violence, vice, lust, fever and falsehood; ill in nearly all honest matters.',
      note:'“The red.” Fludd: wholly ill, Fiery, of the South; Mars direct; Gemini. The reversion of Albus. From Cap. III (pp. 56–59); the print gives fourteen places (the fifteenth omitted).',
      physiognomy:{ la:'Quando hæc figura præcedens est in prima domo, significat hominem rubrum & callidæ loquelæ, prælia desiderantem, & delectantem sese vel gaudentem effusione sanguinis, & cujus magisterium pertinet ad ignem.', en:'When this figure is in the first house, it signifies a ruddy man of crafty speech, desiring battles, and delighting and rejoicing in the shedding of blood, whose trade pertains to fire.' },
      domus:[
        { la:'sanguinem, prælia, bella, hominem iracundum, plenum rabiei, receptionem periculi ab igne & sanguine in itinere ac alibi, inimicos & malam mutationem.', en:'Blood; battles; wars; a wrathful man, full of rage; the meeting of danger from fire and blood on a journey and elsewhere; enemies and an ill change.' },
        { la:'paupertatem, damnum pecuniarum per vim, res damnosas.', en:'Poverty; loss of money by violence; harmful things.' },
        { la:'iracundum, malam fidem, malum fratrem, bonos amicos, iracundos suis patribus & parentibus ac vicinis.', en:'A wrathful man; bad faith; a bad brother; good friends; those angry with their fathers, parents, and neighbours.' },
        { la:'sanguinem, siccitatem & ardorem in aëre, parum seminis, damnum parentibus, damnum hereditatis & patrimonii ac omnium rerum firmarum, domorum combustionem, castellorum invasiones & expugnationes, effusionem sanguinis, omne malum, malum finem.', en:'Blood; drought and burning in the air; scant seed; loss to parents; loss of inheritance and patrimony and of all fixed things; the burning of houses; the storming and sacking of castles; the shedding of blood; every ill; an ill end.' },
        { la:'malos liberos, malam vitam, malas literas, malos nuntios, mala nova, liberos truculentos & Cholericos in corde.', en:'Bad children; an ill life; bad letters; bad messengers; bad news; children fierce and choleric at heart.' },
        { la:'morbos de cholera rubra aut sanguine, ut Apostemata, ulcera, calefactionem sanguinis, bestiam malam, morsum canum rabidorum, injurias, dejectiones, homines armatos.', en:'Sicknesses from red choler or blood — abscesses, ulcers; the heating of the blood; an ill beast; the bite of rabid dogs; injuries; downfalls; armed men.' },
        { la:'lites, bella, nuptias malas, falsam societatem, malam fœminam iracundam & rixosam, verbis contumeliosis infestantem, latrones, assassinatores, jurgia, inimicorum publica, deceptiones & similia.', en:'Lawsuits; wars; ill marriages; false fellowship; an ill woman, wrathful and quarrelsome, assailing with insulting words; thieves; assassins; brawls; the public deeds of enemies; deceptions and the like.' },
        { la:'sanguinolentiam, timorem, damnum hereditatum, damnum per vim, malam mortem per arma aut per ferrum, mortem in natione aliena, damnum inimicorum, pavorem de morte, damnum ei qui exit, omne malum absenti, impedimentum omnis lucri iter facientibus, utpote qui non invenient quicquam proficui in loco quo tendunt.', en:'Bloodiness; fear; loss of inheritances; loss by violence; an ill death by arms or iron; death in a foreign nation; harm from enemies; the dread of death; harm to him who goes out; every ill to one absent; the hindrance of all gain to travellers, since they will find nothing profitable in the place they head for.' },
        { la:'falsitatem, malam viam, latrones in via, corruptionem in via, hominem malæ fidei, parvæ scientiæ in sua arte aut magisterio, violentiam in Ecclesia, egressionem de beneficiis & mendacia.', en:'Falsehood; an ill way; thieves on the road; corruption on the way; a man of bad faith, of little skill in his art or craft; violence in the Church; the loss of benefices; and lies.' },
        { la:'malum in actione sui Domini, falsam justitiam, iracundiam & vecordiam Domini, malum pro regno, malum proficuum, egressum officii per violentiam, recusationem dominii, malam judicis sententiam, executionem mortalem.', en:'Ill in one’s lord’s affairs; false justice; the wrath and folly of a lord; ill for the realm; ill profit; expulsion from office by violence; the refusal of lordship; an ill sentence of the judge; a mortal execution.' },
        { la:'rigorem & litem, recusationem Domini, malam fortunam, malos officiarios, malos liberos, malam spem, malum in mercantia amicorum & in habente dominium.', en:'Harshness and strife; the refusal of a lord; ill fortune; bad officials; bad children; ill hope; ill in the trade of friends, and in him who holds lordship.' },
        { la:'inimicos, debita, malam cogitationem, damnum, mortem in carcere, bestias malas, conditionem vitioso datam, damnum per bestias, inimicos feroces & iracundos, malos carceres more inferorum, morbos, incarcerationem aut mortem incarcerati, rigorem justitiæ.', en:'Enemies; debts; an ill mind; loss; death in prison; ill beasts; a station given to a vicious man; loss through beasts; enemies fierce and wrathful; foul prisons like the underworld; sicknesses; the imprisonment or death of the prisoner; the rigour of justice.' },
        { la:'damnum Domini, malum iter & mutationem, damnum pro absente, brevem vitam pro eo qui abscondit sese ab inimicis suis.', en:'The lord’s loss; an ill journey and change; loss for one absent; a short life for him who hides himself from his enemies.' },
        { la:'damnum & iracundiam, paupertatem, malam fortunam, cumulationem mali, nihili receptionem de rebus desideratis, malum pro omni negotio; atque hoc fit pro scuti Geomantici domo, quando generatur à figuris malis, vel iis sociatur.', en:'Loss and wrath; poverty; ill fortune; the heaping-up of ill; the receiving of nothing of what is desired; ill for every business — and this comes to pass for any house of the shield when the figure is born of ill figures, or keeps their company.' },
      ] },
    { la:'Fortuna Major', en:'The Greater Fortune', rows:[2,2,1,1], element:'Earth', nature:'good', zodiac:'Aquarius', planet:'Sun (swift)',
      sig:'Great and lasting fortune, won by one’s own strength; power, protection, success that holds — the inward, solar victory.',
      note:'Fludd: wholly fortunate, Earthy, of the West; the Sun “swift” (velox); Aquarius. “Fortune going in.” From Cap. III (pp. 63–65); fifteen places. In the eighth Fludd adds the rule plainly: “this figure is good, but the house is most ill.”',
      physiognomy:{ la:'Quando Major est in prima domo, significat senem, mercatorem pannorum preciosorum, affabilem, mediocris staturæ, bene vestitum, bonos capillos.', en:'When Major is in the first house, it signifies an old man, a merchant of precious cloths, affable, of middling stature, well-dressed, with good hair.' },
      domus:[
        { la:'cogitationes regum, thesauros, senes, hominem bonæ vitæ, bonam fortunam, in re omni proficuum & honorem petitoris, statum diuturnum, bonam spem.', en:'The thoughts of kings; treasures; old men; a man of good life; good fortune; profit in every matter, and honour to the petitioner; a lasting estate; good hope.' },
        { la:'divitias, lucrum & specialiter in bestiis, hominem divitem, bene fortunatum, omnium acquisitionem, gaudium, sensum acquirendi.', en:'Riches; gain, and especially in beasts; a rich, well-fortuned man; the gaining of all things; joy; a sense for acquiring.' },
        { la:'bonum iter, sed aliquantulum tardum, bonum fratrem, bonos & divites parentes, bonum somnium, bona nova, lætitiam, proficuum.', en:'A good journey, but somewhat slow; a good brother; rich and good parents; a good dream; good news; joy; profit.' },
        { la:'bonum patrimonium, acquisitionem hæreditatum magnorum Dominorum, thesauros in terra absconditos, bonam domum, magnum commodum in omni re firma, bonum finem, bonum patrem & matrem.', en:'A good patrimony; the gaining of the inheritances of great lords; treasures hidden in the earth; a good house; great advantage in every fixed matter; a good end; a good father and mother.' },
        { la:'bonos liberos, bona nuntia, bonas literas, bonum amorem cum uxore, securitatem cordis, mutationem & honores.', en:'Good children; good messages; good letters; good love with one’s wife; security of heart; change and honours.' },
        { la:'longum morbum & dolorem, bonas bestias, servos bonos, fideles & stabiles.', en:'A long sickness and pain; good beasts; good servants, faithful and steady.' },
        { la:'bonas nuptias, bonam fœminam & castam ac prudentem, magnas divitias, victorem inimicorum suorum tam in processu legali quàm in præliis, fortes inimicos & stabiles, bonum in mercantia, inventionem sui desiderii in regionibus exoticis, congregationem hominum & fœminarum.', en:'Good marriages; a chaste and prudent woman; great riches; a victor over his enemies both in lawsuit and in battle; strong and steadfast enemies; good in trade; the finding of one’s desire in foreign regions; a gathering of men and women.' },
        { la:'divites inimicos, divitias à mortuis, proficuum in regione aliena, ubi nota, quod figura hæc est bona, sed domus est pessima.', en:'Rich enemies; riches from the dead; profit in a foreign region — where note that this figure is good, but the house is most ill.' },
        { la:'itinera bona, si modò non sint tarda, bona somnia.', en:'Good journeys, if only they be not slow; good dreams.' },
        { la:'bonum judicium, bonam sententiam in loco ubi reduplicatur, reges pacificos regnumque pacificum, firmum statum Dominorum, acquisitionem petitionis, præmium & honorem petitionis à Dominis.', en:'Good judgment; a good sentence in the place where it is doubled; peaceful kings and a peaceful realm; the firm estate of lords; the gaining of the petition; reward and honour of the petition from lords.' },
        { la:'bonam fortunam, nobiles & fideles amicos, proficuum in mercantia, bonam spem divitiarum à Rege & Principe, gaudium & lætitiam.', en:'Good fortune; noble and faithful friends; profit in trade; good hope of riches from king and prince; joy and gladness.' },
        { la:'equos, bonas bestias & utiles, longam & periculosam incarcerationem, periculosum morbum, longa debita & longas tribulationes, fortes inimicos, malum pro itinere.', en:'Horses; good and useful beasts; a long and dangerous imprisonment; a dangerous sickness; long debts and long tribulations; strong enemies; ill for a journey.' },
        { la:'bonum iter & utile, acquisitionem à Rege, absentiam, felicitatem in divitiis & lætitia.', en:'A good and useful journey; gaining from a king; absence; happiness in riches and joy.' },
        { la:'liberationem à morbis, exitum à carcere & debitis, bonam fortunam, subitaneas divitias absentis, bonam societatem, bonos amicos, securitatem in spe.', en:'Deliverance from sicknesses; a way out of prison and debts; good fortune; sudden riches to one absent; good fellowship; good friends; security in hope.' },
        { la:'bonum judicium, bonum finem, bonum eventum pro lætitiis; & si sit de bonis testimoniis, dabit petitori securitatem in omnibus bonis, & testatur bonum in loco ubi duplicatur.', en:'Good judgment; a good end; a good outcome for joys; and if it be of good testimonies, it will give the petitioner security in all goods, and it attests good in the place where it is doubled.' },
      ] },
    { la:'Albus', en:'White', rows:[2,2,1,2], element:'Water', nature:'good', zodiac:'Cancer', planet:'Mercury (direct)',
      sig:'Peace, wisdom, clarity, clean counsel, purity of mind — favourable for thought, learning and quiet beginnings.',
      note:'“The white.” Fludd: wholly fortunate, Watery, of the North; Mercury direct; Cancer. The reversion of Rubeus. From Cap. III (pp. 54–56); the print gives fourteen places (the fifteenth omitted).',
      physiognomy:{ la:'Hæc figura inventa in prima domo significat hominem album, bene barbatum, & sæpe versatur in rebus albis, manetque juxta aquam.', en:'This figure, found in the first house, signifies a fair man, well-bearded, who often deals in white things, and dwells near water.' },
      domus:[
        { la:'rei desideratæ obtentionem seu consecutionem, lætitiam, literas bonas, prudentem hominem, divitem, receptorem omnium bonorum, sed qui impedit viam pro aliquo bono, res albas & utiles.', en:'The obtaining or attaining of the thing desired; joy; good letters; a prudent, rich man, a receiver of all goods — yet one who blocks the way for some good; white and useful things.' },
        { la:'denarios & lucrum in mercantia, divitias in argento, rerum promissarum receptionem, multiplicationem in re omni.', en:'Money and gain in trade; riches in silver; the receiving of things promised; multiplication in every matter.' },
        { la:'implementum desiderii, bonos fratres, bonos cognatos, bonos parentes, bonos vicinos & benevolos, bonam fidem, bona nova, negotia paululum retardata.', en:'The fulfilment of desire; good brothers; good kinsmen; good parents; good and kindly neighbours; good faith; good news; business a little delayed.' },
        { la:'multum proficui de patre & matre, bonam domum, bonum patrimonium, bonum statum pro patre, bonum finem & lætum.', en:'Much profit from father and mother; a good house; a good patrimony; a good estate for the father; a good and glad end.' },
        { la:'bonos liberos, bonas literas, gaudium, bonos pisces albos, amplexus & oscula suæ Dominæ sive amatæ.', en:'Good children; good letters; joy; good white fish; the embraces and kisses of one’s lady or beloved.' },
        { la:'magnum morbum, proficuum in bestiis & servis, commodum & bonam fortunam in albis bestiis.', en:'A great sickness; profit in beasts and servants; advantage and good fortune in white beasts.' },
        { la:'bonam fœminam & pacificam, bonam societatem, proficuum in mercantia, pacem ab inimicis, bonas nuptias & utiles.', en:'A good and peaceable woman; good fellowship; profit in trade; peace from enemies; good and useful marriages.' },
        { la:'mortalitatem & morbidum statum, securitatem à pavore, lucrum in natione aliena, divitias absenti, mutationem bonam & bonum iter.', en:'Mortality and a sickly state; safety from terror; gain in a foreign nation; riches to one absent; a good change and a good journey.' },
        { la:'proficuum in itinere, fidelitatem sed retardationem aliqualem itineris, bonas artes, hominem bene literatum, hominem sapientem Ecclesiastici ordinis, hominem fidelem.', en:'Profit on a journey; faithfulness, but some delay of the journey; good arts; a well-lettered man; a wise man of the ecclesiastical order; a faithful man.' },
        { la:'gaudium, sanitatem, bonam fortunam, bonum regi & regno; si illa duplicatur in duodecima aut octava domo, denotat inimicos regis, bonam sententiam à judice, obtentionem petiti sui à Domino, & bonum officium.', en:'Joy; health; good fortune; good for king and realm; and if it be doubled in the twelfth or eighth house, it denotes the king’s enemies, a good sentence from the judge, the obtaining of one’s request from a lord, and a good office.' },
        { la:'bonam fortunam, bonos amicos, proficuum in mercantia, spem, pacem & amorem.', en:'Good fortune; good friends; profit in trade; hope; peace and love.' },
        { la:'proficuum bestiarum, bonos debitores, tardum egressum è carcere, debiles inimicos qui petent pacem.', en:'Profit of beasts; good debtors; a slow release from prison; weak enemies who will sue for peace.' },
        { la:'proficuum in via, & ab aliquo Domino.', en:'Profit on the way, and from some lord.' },
        { la:'proficuum amicorum & evasionem ab inimicis.', en:'The profit of friends, and escape from enemies.' },
      ] },
    { la:'Tristitia', en:'Sorrow', rows:[2,2,2,1], element:'Earth', nature:'ill', zodiac:'Scorpio', planet:'Saturn (retrograde)',
      sig:'Sorrow, grief, melancholy, lowering and decline — ill for joy and advancement, yet apt for what should sink, stay hidden, or be rooted deep.',
      note:'“Sorrow.” Fludd: wholly ill, Earthy, of the West; Saturn retrograde; Scorpio. The inversion of Lætitia. From Cap. III (pp. 48–50); the print gives fourteen places (the fifteenth omitted).',
      physiognomy:{ la:'Quando hæc figura reperitur in prima domo, significat hominem nigrum, habentem vestimenta lacera, & cujus magisterium versatur in rebus nigris & fœtidis ac vilibus.', en:'When this figure is in the first house, it signifies a swarthy man in torn garments, whose trade is in things black, foul, and base.' },
      domus:[
        { la:'tristes cogitationes, debita, paupertatem, occultum damnum, obligationes, carceres, impedimentum itineris, malam mutationem, incredulum & sine spe.', en:'Sad thoughts; debts; poverty; a hidden loss; bonds; prisons; the hindrance of a journey; an ill change; one unbelieving and without hope.' },
        { la:'fortunam & mercantiam, avaritiam, damnum bonorum, infortunatum usurarium, malum honorem.', en:'Fortune and trade [crossed]; avarice; loss of goods; an unfortunate usurer; ill repute.' },
        { la:'malum cum cognatis, odium tacitum cum vicinis & parentibus, impedimentum secretum in itinere.', en:'Ill with kinsmen; silent hatred with neighbours and parents; a secret hindrance on a journey.' },
        { la:'perditionem hereditatum & in præliis, damnum damnorum, tribulationem, malam domum, malam fortunam, paupertatem parentum, detrimentum & damnum.', en:'Loss of inheritances and in battles; loss upon loss; tribulation; an ill house; ill fortune; the poverty of parents; harm and loss.' },
        { la:'malos & pauperes liberos, falsas literas, tristitiam & angorem cordis, secretum in amore fœminarum tristium, pauperes cibos & habitus.', en:'Bad and poor children; false letters; sorrow and anguish of heart; secrecy in the love of sorrowful women; poor food and clothing.' },
        { la:'novos servos, timorem captivitatis & paupertatis, bestias timidas ac inutiles, longum morbum aut mortem, paupertatem, injuriam, abjectionem sine vulnere & confusione.', en:'New servants; fear of captivity and poverty; beasts timid and useless; a long sickness or death; poverty; injury; abjection without a wound, and confusion.' },
        { la:'malam fœminam, hominem victorem, latronem de nocte, pauperem statum, damnum, malam mutationem, fœminam tristem.', en:'An ill woman; a man who is a conqueror; a thief by night; a poor estate; loss; an ill change; a sorrowful woman.' },
        { la:'pauperem de morte alterius, damnum in natione aliena, damnum ab absente.', en:'Made poor by another’s death; loss in a foreign nation; loss from one absent.' },
        { la:'viam sine proficuo, impedimenta in itinere & damnum, hominem sine fide & scientia, rudem intellectum, ruinam Ecclesiæ & beneficiorum.', en:'A way without profit; hindrances on a journey and loss; a man without faith or knowledge; a rude understanding; the ruin of the Church and of benefices.' },
        { la:'damnum & degradationem hominum, exaltationem malorum, damnum officiorum, Dominorum tristium, timorem regum & regni, falsam judicis sententiam, casum de honore.', en:'Loss and the degrading of men; the raising of the wicked; loss of offices; sorrowful lords; fear of kings and the realm; a false sentence of the judge; a fall from honour.' },
        { la:'contemptorem amici sui, malam fortunam quæ durabit diu, sed tamen cum spe; pauperem amicum, nullum defectum in mercantia.', en:'A despiser of his friend; ill fortune that will last long, yet with hope; a poor friend; no failure in trade.' },
        { la:'debita, inimicos, damnum, incarcerationem longam aut mortem in carcere; inimicum timidum & pauperem, tribulationem, timorem de obligationibus & debitis, longum morbum & incurabilem.', en:'Debts; enemies; loss; a long imprisonment or death in prison; an enemy timid and poor; tribulation; fear over bonds and debts; a long and incurable sickness.' },
        { la:'malum per viam ac tristitiam.', en:'Ill along the way, and sorrow.' },
        { la:'malam fortunam, parva itinera, angorem & tribulationem, desperationem & omne malum irreparabile.', en:'Ill fortune; small journeys; anguish and tribulation; despair, and every irreparable ill.' },
      ] },
    { la:'Populus', en:'The People', rows:[2,2,2,2], element:'Water', nature:'mixed', zodiac:'Cancer & Capricorn', planet:'Moon (direct)',
      sig:'A crowd, a gathering, the multitude; wholly passive, it takes the colour of whatever acts upon it — a still water reflecting its neighbours.',
      note:'“The people / the assembly”; the Arabic is Jamāʿa (جماعة). Fludd: intermediate, Watery, of the North; the Moon direct; given two signs, Cancer and Capricorn. Inversion of Via. From Cap. III (pp. 68–69); fifteen places — the purest passive figure, every place “a multitude … according to the figures,” the fifteenth stating the rule: good from good figures, the contrary from ill.',
      physiognomy:{ la:'Hæc figura in prima domo inventa significat mercatorem diversarum rerum per rura transeuntem.', en:'This figure, found in the first house, signifies a merchant of diverse goods, passing through the countryside.' },
      domus:[
        { la:'multitudinem cogitationum, aquæ, itinerum, populorum & gentium.', en:'A multitude of thoughts, of water, of journeys, of peoples and nations.' },
        { la:'cum bonis multitudinem fortunæ, divitiarum; cum malis multitudinem inconvenientiæ.', en:'With good figures, a multitude of fortune and riches; with ill ones, a multitude of trouble.' },
        { la:'multitudinem parentum, vicinorum, itinerum parvulorum tam bonorum quàm malorum secundum naturam figurarum.', en:'A multitude of kinsfolk, of neighbours, of small journeys, both good and ill according to the nature of the figures.' },
        { la:'multitudinem aquarum, laborum pro hereditate, fructuum secundum figuras.', en:'A multitude of waters, of toils for an inheritance, of fruits according to the figures.' },
        { la:'multitudinem liberorum, literarum & nuntiorum, lætitiæ aut doloris, osculorum & amplexuum, congregationis populorum pro delitiis & gaudiis, fructuum, secundum figuras, & sic in cæteris secundum figuras.', en:'A multitude of children, of letters and messages, of joy or grief, of kisses and embraces, of the gathering of peoples for delights and joys, of fruits, according to the figures — and so in the rest, according to the figures.' },
        { la:'multitudinem bestiarum, servorum, ægritudinum, injuriarum & cætera secundum figuras.', en:'A multitude of beasts, of servants, of sicknesses, of injuries, and the rest according to the figures.' },
        { la:'multitudinem populorum congregatorum, fœminarum, inimicorum, injuriarum aut dolorum secundum naturam figurarum.', en:'A multitude of gathered peoples, of women, of enemies, of injuries or griefs according to the nature of the figures.' },
        { la:'multitudinem populorum congregatorum pro morte aut pro multitudine bonorum aut malorum, secundum bonitatem aut malitiam figurarum.', en:'A multitude of gathered peoples for a death, or a multitude of goods or ills, according to the goodness or malice of the figures.' },
        { la:'multitudinem itinerum, somniorum, scientiarum, populorum in via, mutationum.', en:'A multitude of journeys, of dreams, of sciences, of peoples on the way, of changes.' },
        { la:'multitudinem inimicorum, regum, gentium ante judices, doctrinarum, congregationem pro bono aut pro malo, secundum figuras.', en:'A multitude of enemies, of kings, of nations before judges, of doctrines; a gathering for good or ill, according to the figures.' },
        { la:'multitudinem amicorum, bonæ fortunæ, bestiarum, servorum, liberorum, aut inconvenientiarum, secundum naturam figurarum quæ in vicinia fuerint repertæ.', en:'A multitude of friends, of good fortune, of beasts, of servants, of children, or of troubles, according to the nature of the figures found in the neighbourhood.' },
        { la:'multitudinem inimicorum, inconvenientiæ, gravis incarcerationis, lachrymarum, debitorum, bestiarum, servorum.', en:'A multitude of enemies, of trouble, of grievous imprisonment, of tears, of debts, of beasts, of servants.' },
        { la:'multitudinem proficui illi qui ad Magnatum aliquem vadit, damni, mutationis, & similium.', en:'A multitude of profit for him who goes to some magnate; of loss, of change, and the like.' },
        { la:'multitudinem populorum congregatorum, aut pro bono aut pro malo, secundum figuras illi vicinas.', en:'A multitude of gathered peoples, either for good or for ill, according to the figures neighbouring it.' },
        { la:'multitudinem boni aut mali petitori, congregationis populorum pro bono aut pro malo, secundum figuras ex quibus provenit; namque si veniat à bonis figuris, multum boni denotat, si ex malis, contrarium.', en:'A multitude of good or ill to the petitioner; a gathering of peoples for good or for ill, according to the figures from which it comes; for if it come from good figures it denotes much good, if from ill ones, the contrary.' },
      ] },
    { la:'Via', en:'The Way', rows:[1,1,1,1], element:'Water', nature:'mixed', zodiac:'Leo', planet:'Moon (retrograde)',
      sig:'The road, and motion along it: journeys, change, news that travels; it carries things from one state to another — good for travel and change, contrary to what must stand still.',
      note:'“The way / the road”; the Arabic is Ṭarīq (طريق). Fludd: intermediate, Watery, of the North; the Moon retrograde; Leo. From Cap. III (pp. 70–71); fifteen places — thin and changeful (small fruits, scarcity, journeys), leaning on its neighbours: “loss or gain according to the neighbouring figures.”',
      physiognomy:{ la:'Quando via reperitur in prima domo, significat hominem mutabilem, falsum, & pauperem.', en:'When Via is found in the first house, it signifies a changeable, false, and poor man.' },
      domus:[
        { la:'bonum iter, parum proficui, cogitationes parvorum fructuum.', en:'A good journey; little profit; thoughts of small fruits.' },
        { la:'damnum, aut lucrum, secundum vicinas figuras.', en:'Loss, or gain, according to the neighbouring figures.' },
        { la:'fratres, vicinos, aquam, bonum iter, levia negotia, itinera pro fratribus aut cognatis, comparationem divitiarum.', en:'Brothers; neighbours; water; a good journey; light business; journeys for brothers or kinsmen; the acquiring of riches.' },
        { la:'parentes, labores, terras, occultationem rerum maculatarum, finem rerum, paupertatem, pauperes parentes, pauperes hereditates.', en:'Parents; toils; lands; the hiding of stained things; the end of matters; poverty; poor parents; poor inheritances.' },
        { la:'literas, nuntios parvi momenti, parvos fructus, pauperes infantes, parum lætitiæ.', en:'Letters; messages of little moment; small fruits; poor children; little joy.' },
        { la:'pauperes bestias, malam fortunam, servos instabiles, subitaneum morbi incrementum, liberationem à morbo, infortunium bestiarum.', en:'Poor beasts; ill fortune; unstable servants; a sudden increase of sickness; deliverance from sickness; the misfortune of beasts.' },
        { la:'latrones, pauperes fœminas, parum sensus, pauperes inimicos ac debiles, meretricem, mortem latronum.', en:'Thieves; poor women; little sense; poor and weak enemies; a harlot; the death of thieves.' },
        { la:'paupertatem in aliena terra, damnum hereditatum à morte provenientium.', en:'Poverty in a foreign land; loss of inheritances coming from a death.' },
        { la:'mutationem literarum, nuncios parvæ scientiæ, bonum iter, beneficium Ecclesiæ, paucitatem lucri & proficui.', en:'A change of letters; messengers of little learning; a good journey; a benefice of the Church; scarcity of gain and profit.' },
        { la:'parvula officia, parum lucri à Dominis & fœminis nobilibus, judicem senem, parum sapientiæ, damnum alicujus rei.', en:'Small offices; little gain from lords and noble women; an old judge; little wisdom; the loss of some thing.' },
        { la:'pauperes amicos, parvulam fortunam, parum proficui, dona mercantiæ & lætitiæ literas.', en:'Poor friends; a small fortune; little profit; gifts of trade, and letters of joy.' },
        { la:'bestias inutiles, pauperes amicos, egressum levem è carcere, liberationem à debitis aut à miseria, & nonnunquam mortem in carcere, secundum bonas aut malas figuras vicinas, & ex quibus generatur.', en:'Useless beasts; poor friends; an easy release from prison; deliverance from debts or misery; and sometimes death in prison, according to the good or ill neighbouring figures, and those from which it is generated.' },
        { la:'proficuum itinerum & mutationum.', en:'Profit of journeys and changes.' },
        { la:'damnum & egressum ex aliqua re, secundum figuras bonas vel malas.', en:'Loss and a way out of some matter, according to the figures, good or ill.' },
        { la:'viam, bonum exitum, secundum figuras ex quibus venit.', en:'A way; a good outcome, according to the figures from which it comes.' },
      ] },
  ],

  // the twelve houses the figures are cast into (Mothers→1–4, Daughters→5–8, Nieces→9–12).
  // Standard provinces of the question; Fludd's per-house significations are a later tranche.
  houses: [
    { n:1,  name:'Vita',          title:'Life & the Querent',     matter:'life and health',
      domain:'The querent themselves — life, the body, health, and the whole frame of the question.' },
    { n:2,  name:'Lucrum',        title:'Wealth',                 matter:'money and gain',
      domain:'Money, movable goods and earnings — gain and loss.' },
    { n:3,  name:'Fratres',       title:'Kin & Rumour',           matter:'kin, news and short journeys',
      domain:'Brothers and sisters, neighbours, short journeys, letters and rumour.' },
    { n:4,  name:'Genitor',       title:'Home & Father',          matter:'home, land and endings',
      domain:'The father, the home, land and foundations, and the end of matters.' },
    { n:5,  name:'Nati',          title:'Children & Pleasure',    matter:'children and pleasure',
      domain:'Children, pleasure, feasts and messengers — what delights.' },
    { n:6,  name:'Valetudo',      title:'Sickness & Service',     matter:'sickness and servants',
      domain:'Sickness, servants, labour, and the small beasts of the house.' },
    { n:7,  name:'Uxor',          title:'Marriage & the Other',   matter:'marriage and the other party',
      domain:'Marriage and partners, the other party, and open enemies — the quesited.' },
    { n:8,  name:'Mors',          title:'Death & Inheritance',    matter:'death and inheritance',
      domain:'Death, dread, inheritance, and the partner’s wealth.' },
    { n:9,  name:'Peregrinatio',  title:'Journeys & Faith',       matter:'far journeys and learning',
      domain:'Long journeys, religion, dreams, and learning.' },
    { n:10, name:'Regnum',        title:'Honour & Rule',          matter:'honour and career',
      domain:'Honour, office, command and career — and the mother.' },
    { n:11, name:'Benefacta',     title:'Friends & Hope',         matter:'friends and hopes',
      domain:'Friends, allies, hopes, and the favour of fortune.' },
    { n:12, name:'Carcer',        title:'Sorrow & Secret Foes',   matter:'sorrows and hidden foes',
      domain:'Sorrows, prisons, secret enemies, and hidden harms.' },
  ],
};

if (typeof window !== 'undefined') window.GEOMANCY = GEOMANCY;
