/**
 * Curated pool of high-signal Wikipedia articles.
 * Every entry is a Featured or Vital article — guaranteed charismatic.
 * Categories map to card "types" for future game mechanics.
 */

const CATEGORIES = {
  SCIENCE:     { name: "Science & Nature",       color: "#2563eb", icon: "🧬" },
  HISTORY:     { name: "History & Civilization",  color: "#d97706", icon: "🏛️" },
  PEOPLE:      { name: "People",                  color: "#7c3aed", icon: "👤" },
  GEOGRAPHY:   { name: "Geography & Places",      color: "#059669", icon: "🌍" },
  TECHNOLOGY:  { name: "Technology & Engineering", color: "#475569", icon: "⚙️" },
  ARTS:        { name: "Arts & Culture",           color: "#e11d48", icon: "🎭" },
  WAR:         { name: "War & Conflict",           color: "#dc2626", icon: "⚔️" },
  COSMOS:      { name: "Space & Cosmos",           color: "#1e3a5f", icon: "🌌" },
};

// Each entry: [title, category_key]
// Titles must match Wikipedia article titles exactly (used for API fetch)
const POOL = [
  // ── Science & Nature ──────────────────────────────────────────
  ["DNA", "SCIENCE"],
  ["Evolution", "SCIENCE"],
  ["Photosynthesis", "SCIENCE"],
  ["General relativity", "SCIENCE"],
  ["Quantum mechanics", "SCIENCE"],
  ["Plate tectonics", "SCIENCE"],
  ["Periodic table", "SCIENCE"],
  ["Penicillin", "SCIENCE"],
  ["CRISPR gene editing", "SCIENCE"],
  ["Human brain", "SCIENCE"],
  ["Tyrannosaurus", "SCIENCE"],
  ["Great white shark", "SCIENCE"],
  ["Giant squid", "SCIENCE"],
  ["Tardigrade", "SCIENCE"],
  ["Mitochondrion", "SCIENCE"],
  ["Dinosaur", "SCIENCE"],
  ["Volcano", "SCIENCE"],
  ["Earthquake", "SCIENCE"],
  ["Lightning", "SCIENCE"],
  ["Aurora (astronomy)", "SCIENCE"],
  ["Black Death", "SCIENCE"],
  ["Malaria", "SCIENCE"],
  ["Tuberculosis", "SCIENCE"],
  ["Insulin", "SCIENCE"],
  ["Radioactivity", "SCIENCE"],
  ["Superconductivity", "SCIENCE"],
  ["Speed of light", "SCIENCE"],
  ["Entropy", "SCIENCE"],
  ["Golden ratio", "SCIENCE"],
  ["Pi", "SCIENCE"],
  ["Coral reef", "SCIENCE"],
  ["Amazon rainforest", "SCIENCE"],
  ["Blue whale", "SCIENCE"],
  ["Octopus", "SCIENCE"],
  ["Mantis shrimp", "SCIENCE"],
  ["Venus flytrap", "SCIENCE"],
  ["Komodo dragon", "SCIENCE"],
  ["Platypus", "SCIENCE"],
  ["Woolly mammoth", "SCIENCE"],
  ["Coelacanth", "SCIENCE"],

  // ── History & Civilization ────────────────────────────────────
  ["Roman Empire", "HISTORY"],
  ["Ancient Egypt", "HISTORY"],
  ["Silk Road", "HISTORY"],
  ["French Revolution", "HISTORY"],
  ["Renaissance", "HISTORY"],
  ["Industrial Revolution", "HISTORY"],
  ["Fall of Constantinople", "HISTORY"],
  ["Rosetta Stone", "HISTORY"],
  ["Library of Alexandria", "HISTORY"],
  ["Pompeii", "HISTORY"],
  ["Viking Age", "HISTORY"],
  ["Mongol Empire", "HISTORY"],
  ["Ottoman Empire", "HISTORY"],
  ["Byzantine Empire", "HISTORY"],
  ["Spanish Inquisition", "HISTORY"],
  ["Magna Carta", "HISTORY"],
  ["Black Death", "HISTORY"],
  ["Age of Discovery", "HISTORY"],
  ["Printing press", "HISTORY"],
  ["Gutenberg Bible", "HISTORY"],
  ["Dead Sea Scrolls", "HISTORY"],
  ["Code of Hammurabi", "HISTORY"],
  ["Colosseum", "HISTORY"],
  ["Parthenon", "HISTORY"],
  ["Great Wall of China", "HISTORY"],
  ["Machu Picchu", "HISTORY"],
  ["Stonehenge", "HISTORY"],
  ["Easter Island", "HISTORY"],
  ["Trail of Tears", "HISTORY"],
  ["Scramble for Africa", "HISTORY"],
  ["Russian Revolution", "HISTORY"],
  ["Cuban Revolution", "HISTORY"],
  ["Salem witch trials", "HISTORY"],
  ["Prohibition in the United States", "HISTORY"],
  ["Gold rush", "HISTORY"],
  ["Transatlantic slave trade", "HISTORY"],
  ["Samurai", "HISTORY"],
  ["Knights Templar", "HISTORY"],
  ["East India Company", "HISTORY"],
  ["Panama Canal", "HISTORY"],

  // ── People ────────────────────────────────────────────────────
  ["Leonardo da Vinci", "PEOPLE"],
  ["Nikola Tesla", "PEOPLE"],
  ["Cleopatra", "PEOPLE"],
  ["Genghis Khan", "PEOPLE"],
  ["Albert Einstein", "PEOPLE"],
  ["Marie Curie", "PEOPLE"],
  ["Isaac Newton", "PEOPLE"],
  ["Charles Darwin", "PEOPLE"],
  ["Ada Lovelace", "PEOPLE"],
  ["Alan Turing", "PEOPLE"],
  ["Alexander the Great", "PEOPLE"],
  ["Napoleon", "PEOPLE"],
  ["Julius Caesar", "PEOPLE"],
  ["Queen Victoria", "PEOPLE"],
  ["Mahatma Gandhi", "PEOPLE"],
  ["Martin Luther King Jr.", "PEOPLE"],
  ["Nelson Mandela", "PEOPLE"],
  ["Frida Kahlo", "PEOPLE"],
  ["Wolfgang Amadeus Mozart", "PEOPLE"],
  ["Ludwig van Beethoven", "PEOPLE"],
  ["William Shakespeare", "PEOPLE"],
  ["Galileo Galilei", "PEOPLE"],
  ["Archimedes", "PEOPLE"],
  ["Pythagoras", "PEOPLE"],
  ["Marco Polo", "PEOPLE"],
  ["Amelia Earhart", "PEOPLE"],
  ["Houdini", "PEOPLE"],
  ["Tutankhamun", "PEOPLE"],
  ["Sun Tzu", "PEOPLE"],
  ["Socrates", "PEOPLE"],
  ["Aristotle", "PEOPLE"],
  ["Plato", "PEOPLE"],
  ["Joan of Arc", "PEOPLE"],
  ["Rasputin", "PEOPLE"],
  ["Blackbeard", "PEOPLE"],
  ["Sitting Bull", "PEOPLE"],
  ["Ramesses II", "PEOPLE"],
  ["Boudica", "PEOPLE"],
  ["Hannibal Barca", "PEOPLE"],
  ["Hypatia", "PEOPLE"],

  // ── Geography & Places ────────────────────────────────────────
  ["Mariana Trench", "GEOGRAPHY"],
  ["Mount Everest", "GEOGRAPHY"],
  ["Sahara", "GEOGRAPHY"],
  ["Antarctica", "GEOGRAPHY"],
  ["Great Barrier Reef", "GEOGRAPHY"],
  ["Galápagos Islands", "GEOGRAPHY"],
  ["Bermuda Triangle", "GEOGRAPHY"],
  ["Niagara Falls", "GEOGRAPHY"],
  ["Grand Canyon", "GEOGRAPHY"],
  ["Dead Sea", "GEOGRAPHY"],
  ["Lake Baikal", "GEOGRAPHY"],
  ["Yellowstone National Park", "GEOGRAPHY"],
  ["Krakatoa", "GEOGRAPHY"],
  ["Mount Vesuvius", "GEOGRAPHY"],
  ["Chernobyl disaster", "GEOGRAPHY"],
  ["Angkor Wat", "GEOGRAPHY"],
  ["Petra", "GEOGRAPHY"],
  ["Taj Mahal", "GEOGRAPHY"],
  ["Venice", "GEOGRAPHY"],
  ["Timbuktu", "GEOGRAPHY"],
  ["Pompeii", "GEOGRAPHY"],
  ["Alcatraz Island", "GEOGRAPHY"],
  ["Silk Road", "GEOGRAPHY"],
  ["Panama Canal", "GEOGRAPHY"],
  ["Suez Canal", "GEOGRAPHY"],
  ["Nile", "GEOGRAPHY"],
  ["Amazon (river)", "GEOGRAPHY"],
  ["Himalayas", "GEOGRAPHY"],
  ["Ring of Fire", "GEOGRAPHY"],
  ["Serengeti", "GEOGRAPHY"],
  ["Madagascar", "GEOGRAPHY"],
  ["Iceland", "GEOGRAPHY"],
  ["Svalbard", "GEOGRAPHY"],
  ["Socotra", "GEOGRAPHY"],
  ["Baikonur Cosmodrome", "GEOGRAPHY"],

  // ── Technology & Engineering ───────────────────────────────────
  ["Internet", "TECHNOLOGY"],
  ["World Wide Web", "TECHNOLOGY"],
  ["Transistor", "TECHNOLOGY"],
  ["Nuclear weapon", "TECHNOLOGY"],
  ["Steam engine", "TECHNOLOGY"],
  ["Telephone", "TECHNOLOGY"],
  ["Television", "TECHNOLOGY"],
  ["Radio", "TECHNOLOGY"],
  ["Radar", "TECHNOLOGY"],
  ["Enigma machine", "TECHNOLOGY"],
  ["Artificial intelligence", "TECHNOLOGY"],
  ["ARPANET", "TECHNOLOGY"],
  ["GPS", "TECHNOLOGY"],
  ["Large Hadron Collider", "TECHNOLOGY"],
  ["Hubble Space Telescope", "TECHNOLOGY"],
  ["James Webb Space Telescope", "TECHNOLOGY"],
  ["Nuclear reactor", "TECHNOLOGY"],
  ["Submarine", "TECHNOLOGY"],
  ["Jet engine", "TECHNOLOGY"],
  ["3D printing", "TECHNOLOGY"],
  ["Blockchain", "TECHNOLOGY"],
  ["Machine learning", "TECHNOLOGY"],
  ["Lithium-ion battery", "TECHNOLOGY"],
  ["Solar cell", "TECHNOLOGY"],
  ["Concorde", "TECHNOLOGY"],
  ["SR-71 Blackbird", "TECHNOLOGY"],
  ["International Space Station", "TECHNOLOGY"],
  ["Voyager 1", "TECHNOLOGY"],
  ["Deep Blue (chess computer)", "TECHNOLOGY"],
  ["CERN", "TECHNOLOGY"],
  ["Manhattan Project", "TECHNOLOGY"],
  ["Human Genome Project", "TECHNOLOGY"],
  ["Printing press", "TECHNOLOGY"],
  ["Telescope", "TECHNOLOGY"],
  ["Microscope", "TECHNOLOGY"],

  // ── Arts & Culture ────────────────────────────────────────────
  ["Mona Lisa", "ARTS"],
  ["Sistine Chapel ceiling", "ARTS"],
  ["The Starry Night", "ARTS"],
  ["Guernica (Picasso)", "ARTS"],
  ["The Great Wave off Kanagawa", "ARTS"],
  ["Hamlet", "ARTS"],
  ["Odyssey", "ARTS"],
  ["Iliad", "ARTS"],
  ["Epic of Gilgamesh", "ARTS"],
  ["One Thousand and One Nights", "ARTS"],
  ["Don Quixote", "ARTS"],
  ["Frankenstein", "ARTS"],
  ["Dracula", "ARTS"],
  ["The Art of War", "ARTS"],
  ["I Ching", "ARTS"],
  ["Rosetta Stone", "ARTS"],
  ["Voynich manuscript", "ARTS"],
  ["Chess", "ARTS"],
  ["Go (game)", "ARTS"],
  ["Olympic Games", "ARTS"],
  ["FIFA World Cup", "ARTS"],
  ["Jazz", "ARTS"],
  ["Blues", "ARTS"],
  ["Hip hop", "ARTS"],
  ["Opera", "ARTS"],
  ["Ballet", "ARTS"],
  ["Kabuki", "ARTS"],
  ["Haiku", "ARTS"],
  ["Origami", "ARTS"],
  ["Tarot", "ARTS"],
  ["Hieroglyphics", "ARTS"],
  ["Sanskrit", "ARTS"],
  ["Latin", "ARTS"],
  ["Esperanto", "ARTS"],
  ["Braille", "ARTS"],

  // ── War & Conflict ────────────────────────────────────────────
  ["Battle of Thermopylae", "WAR"],
  ["Battle of Hastings", "WAR"],
  ["Battle of Waterloo", "WAR"],
  ["Battle of Gettysburg", "WAR"],
  ["Battle of Stalingrad", "WAR"],
  ["Battle of Midway", "WAR"],
  ["D-Day", "WAR"],
  ["Siege of Masada", "WAR"],
  ["Trojan War", "WAR"],
  ["Hundred Years' War", "WAR"],
  ["Crusades", "WAR"],
  ["American Civil War", "WAR"],
  ["World War I", "WAR"],
  ["World War II", "WAR"],
  ["Cold War", "WAR"],
  ["Spanish Armada", "WAR"],
  ["Blitzkrieg", "WAR"],
  ["Hiroshima and Nagasaki", "WAR"],
  ["Normandy landings", "WAR"],
  ["Battle of the Bulge", "WAR"],
  ["Charge of the Light Brigade", "WAR"],
  ["Battle of Agincourt", "WAR"],
  ["Siege of Constantinople (1453)", "WAR"],
  ["Punic Wars", "WAR"],
  ["Battle of Cannae", "WAR"],
  ["Gallipoli campaign", "WAR"],
  ["Tet Offensive", "WAR"],
  ["Operation Barbarossa", "WAR"],
  ["Pearl Harbor", "WAR"],
  ["Berlin Wall", "WAR"],
  ["Cuban Missile Crisis", "WAR"],
  ["Assassination of Archduke Franz Ferdinand", "WAR"],
  ["Treaty of Versailles", "WAR"],
  ["Geneva Conventions", "WAR"],
  ["Nuremberg trials", "WAR"],

  // ── Space & Cosmos ────────────────────────────────────────────
  ["Black hole", "COSMOS"],
  ["Supernova", "COSMOS"],
  ["Neutron star", "COSMOS"],
  ["Milky Way", "COSMOS"],
  ["Andromeda Galaxy", "COSMOS"],
  ["Big Bang", "COSMOS"],
  ["Dark matter", "COSMOS"],
  ["Dark energy", "COSMOS"],
  ["Exoplanet", "COSMOS"],
  ["Mars", "COSMOS"],
  ["Jupiter", "COSMOS"],
  ["Saturn", "COSMOS"],
  ["Europa (moon)", "COSMOS"],
  ["Titan (moon)", "COSMOS"],
  ["Io (moon)", "COSMOS"],
  ["Pluto", "COSMOS"],
  ["Asteroid belt", "COSMOS"],
  ["Kuiper belt", "COSMOS"],
  ["Oort cloud", "COSMOS"],
  ["Halley's Comet", "COSMOS"],
  ["Solar eclipse", "COSMOS"],
  ["Apollo 11", "COSMOS"],
  ["Apollo 13", "COSMOS"],
  ["Space Shuttle Challenger disaster", "COSMOS"],
  ["Voyager program", "COSMOS"],
  ["Pale Blue Dot", "COSMOS"],
  ["Cosmic microwave background", "COSMOS"],
  ["Fermi paradox", "COSMOS"],
  ["Drake equation", "COSMOS"],
  ["Dyson sphere", "COSMOS"],
  ["Kardashev scale", "COSMOS"],
  ["Panspermia", "COSMOS"],
  ["Magnetar", "COSMOS"],
  ["Pulsar", "COSMOS"],
  ["Gamma-ray burst", "COSMOS"],
];

// Deduplicate (some appear in multiple categories — keep first occurrence)
const seen = new Set();
const UNIQUE_POOL = POOL.filter(([title]) => {
  if (seen.has(title)) return false;
  seen.add(title);
  return true;
});

export { CATEGORIES, UNIQUE_POOL as POOL };
