// ── Tech — technology tree card pool ─────────────────────────

export const TECH_ERAS = {
  prehistoric:  { name: "Prehistoric",  icon: "🪨", color: "#8B7355", range: "< 3000 BCE" },
  ancient:      { name: "Ancient",      icon: "🏛", color: "#CD853F", range: "3000 BCE – 500" },
  medieval:     { name: "Medieval",     icon: "⚔", color: "#708090", range: "500 – 1400" },
  renaissance:  { name: "Renaissance",  icon: "🔭", color: "#9370DB", range: "1400 – 1700" },
  industrial:   { name: "Industrial",   icon: "⚙", color: "#B87333", range: "1700 – 1900" },
  modern:       { name: "Modern",       icon: "⚛", color: "#4682B4", range: "1900 – 1970" },
  information:  { name: "Information",  icon: "💾", color: "#32CD32", range: "1970 – 2010" },
  ai:           { name: "AI Era",       icon: "🤖", color: "#FF6347", range: "2010 –" },
};

export const TECH_DOMAINS = {
  materials:      { name: "Materials",      icon: "⚗" },
  energy:         { name: "Energy",         icon: "⚡" },
  communication:  { name: "Communication",  icon: "📡" },
  transportation: { name: "Transportation", icon: "⛵" },
  computing:      { name: "Computing",      icon: "⊞" },
  agriculture:    { name: "Agriculture",    icon: "⌘" },
  medicine:       { name: "Medicine",       icon: "⚕" },
  warfare:        { name: "Warfare",        icon: "☄" },
  construction:   { name: "Construction",   icon: "△" },
  optics:         { name: "Optics",         icon: "◎" },
};

// [title, era, { domain, year, status, complexity, prereqs, rarity }]
// status: "alive" | "dead" | "evolved"
// complexity: 1-10 (accidental → requires global infrastructure)
// prereqs: Wikipedia titles of prerequisite technologies

export const TECH_POOL = [
  // ── Prehistoric ────────────────────────────────────────────
  ["Control of fire by early humans", "prehistoric", { domain: "energy", year: -400000, status: "alive", complexity: 1, prereqs: [], rarity: "legendary" }],
  ["Stone tool", "prehistoric", { domain: "materials", year: -3300000, status: "dead", complexity: 1, prereqs: [], rarity: "common" }],
  ["Wheel", "prehistoric", { domain: "transportation", year: -3500, status: "alive", complexity: 2, prereqs: [], rarity: "legendary" }],
  ["Pottery", "prehistoric", { domain: "materials", year: -29000, status: "alive", complexity: 2, prereqs: ["Control of fire by early humans"], rarity: "common" }],
  ["Neolithic Revolution", "prehistoric", { domain: "agriculture", year: -10000, status: "alive", complexity: 2, prereqs: [], rarity: "legendary" }],
  ["Weaving", "prehistoric", { domain: "materials", year: -5000, status: "alive", complexity: 2, prereqs: [], rarity: "common" }],
  ["Bow and arrow", "prehistoric", { domain: "warfare", year: -10000, status: "dead", complexity: 2, prereqs: [], rarity: "uncommon" }],
  ["Fermentation in food processing", "prehistoric", { domain: "agriculture", year: -7000, status: "alive", complexity: 1, prereqs: ["Pottery"], rarity: "uncommon" }],
  ["Smelting", "prehistoric", { domain: "materials", year: -5000, status: "alive", complexity: 3, prereqs: ["Control of fire by early humans"], rarity: "rare" }],
  ["Dugout canoe", "prehistoric", { domain: "transportation", year: -8000, status: "dead", complexity: 2, prereqs: ["Stone tool"], rarity: "common" }],
  ["Rope", "prehistoric", { domain: "materials", year: -28000, status: "alive", complexity: 1, prereqs: [], rarity: "common" }],

  // ── Ancient ────────────────────────────────────────────────
  ["Bronze", "ancient", { domain: "materials", year: -3300, status: "evolved", complexity: 3, prereqs: ["Smelting"], rarity: "rare" }],
  ["Iron", "ancient", { domain: "materials", year: -1200, status: "alive", complexity: 4, prereqs: ["Smelting"], rarity: "rare" }],
  ["History of writing", "ancient", { domain: "communication", year: -3200, status: "alive", complexity: 3, prereqs: [], rarity: "legendary" }],
  ["Arch", "ancient", { domain: "construction", year: -2000, status: "alive", complexity: 3, prereqs: [], rarity: "uncommon" }],
  ["Aqueduct", "ancient", { domain: "construction", year: -700, status: "alive", complexity: 4, prereqs: ["Arch"], rarity: "uncommon" }],
  ["Roman concrete", "ancient", { domain: "construction", year: -300, status: "dead", complexity: 4, prereqs: [], rarity: "rare" }],
  ["Glassblowing", "ancient", { domain: "materials", year: -50, status: "alive", complexity: 3, prereqs: ["Control of fire by early humans"], rarity: "uncommon" }],
  ["Sail", "ancient", { domain: "transportation", year: -3000, status: "evolved", complexity: 3, prereqs: ["Weaving", "Rope"], rarity: "rare" }],
  ["Catapult", "ancient", { domain: "warfare", year: -400, status: "dead", complexity: 3, prereqs: ["Rope"], rarity: "uncommon" }],
  ["Abacus", "ancient", { domain: "computing", year: -2400, status: "dead", complexity: 2, prereqs: [], rarity: "uncommon" }],
  ["Sundial", "ancient", { domain: "optics", year: -1500, status: "dead", complexity: 2, prereqs: [], rarity: "common" }],
  ["Parchment", "ancient", { domain: "communication", year: -1500, status: "dead", complexity: 2, prereqs: [], rarity: "common" }],
  ["Chariot", "ancient", { domain: "transportation", year: -2000, status: "dead", complexity: 3, prereqs: ["Wheel"], rarity: "uncommon" }],
  ["Geocentric model", "ancient", { domain: "optics", year: -300, status: "dead", complexity: 3, prereqs: [], rarity: "uncommon" }],
  ["Greek fire", "ancient", { domain: "warfare", year: 672, status: "dead", complexity: 4, prereqs: [], rarity: "rare" }],
  ["Paper", "ancient", { domain: "communication", year: -100, status: "alive", complexity: 3, prereqs: [], rarity: "rare" }],
  ["Lever", "ancient", { domain: "construction", year: -5000, status: "alive", complexity: 1, prereqs: [], rarity: "uncommon" }],
  ["Water wheel", "ancient", { domain: "energy", year: -300, status: "evolved", complexity: 3, prereqs: [], rarity: "uncommon" }],

  // ── Medieval ───────────────────────────────────────────────
  ["Heavy plough", "medieval", { domain: "agriculture", year: 600, status: "evolved", complexity: 3, prereqs: ["Iron"], rarity: "uncommon" }],
  ["Compass", "medieval", { domain: "transportation", year: 1040, status: "alive", complexity: 3, prereqs: [], rarity: "rare" }],
  ["Gunpowder", "medieval", { domain: "warfare", year: 850, status: "alive", complexity: 4, prereqs: [], rarity: "legendary" }],
  ["Windmill", "medieval", { domain: "energy", year: 600, status: "evolved", complexity: 3, prereqs: [], rarity: "uncommon" }],
  ["Woodblock printing", "medieval", { domain: "communication", year: 200, status: "evolved", complexity: 3, prereqs: ["Paper"], rarity: "uncommon" }],
  ["Astrolabe", "medieval", { domain: "optics", year: -200, status: "dead", complexity: 4, prereqs: [], rarity: "uncommon" }],
  ["Stirrup", "medieval", { domain: "warfare", year: 300, status: "dead", complexity: 2, prereqs: [], rarity: "uncommon" }],
  ["Trebuchet", "medieval", { domain: "warfare", year: 1200, status: "dead", complexity: 3, prereqs: ["Catapult"], rarity: "common" }],
  ["Alchemy", "medieval", { domain: "materials", year: 300, status: "dead", complexity: 4, prereqs: [], rarity: "rare" }],
  ["Longbow", "medieval", { domain: "warfare", year: 1250, status: "dead", complexity: 2, prereqs: ["Bow and arrow"], rarity: "common" }],
  ["Mechanical clock", "medieval", { domain: "computing", year: 1300, status: "alive", complexity: 5, prereqs: [], rarity: "rare" }],
  ["Blast furnace", "medieval", { domain: "materials", year: 1100, status: "alive", complexity: 4, prereqs: ["Iron", "Control of fire by early humans"], rarity: "uncommon" }],

  // ── Renaissance ────────────────────────────────────────────
  ["Printing press", "renaissance", { domain: "communication", year: 1440, status: "alive", complexity: 5, prereqs: ["Woodblock printing", "Paper"], rarity: "legendary" }],
  ["Telescope", "renaissance", { domain: "optics", year: 1608, status: "alive", complexity: 5, prereqs: ["Glassblowing"], rarity: "rare" }],
  ["Microscope", "renaissance", { domain: "optics", year: 1620, status: "alive", complexity: 5, prereqs: ["Glassblowing"], rarity: "rare" }],
  ["Automaton", "renaissance", { domain: "computing", year: 1500, status: "dead", complexity: 5, prereqs: ["Mechanical clock"], rarity: "uncommon" }],
  ["Galleon", "renaissance", { domain: "transportation", year: 1500, status: "dead", complexity: 4, prereqs: ["Sail", "Compass"], rarity: "uncommon" }],
  ["Musket", "renaissance", { domain: "warfare", year: 1500, status: "dead", complexity: 4, prereqs: ["Gunpowder"], rarity: "uncommon" }],
  ["Phlogiston theory", "renaissance", { domain: "energy", year: 1667, status: "dead", complexity: 3, prereqs: [], rarity: "common" }],
  ["Pendulum clock", "renaissance", { domain: "computing", year: 1656, status: "dead", complexity: 5, prereqs: ["Mechanical clock"], rarity: "uncommon" }],

  // ── Industrial ─────────────────────────────────────────────
  ["Steam engine", "industrial", { domain: "energy", year: 1712, status: "evolved", complexity: 6, prereqs: ["Iron"], rarity: "legendary" }],
  ["Spinning jenny", "industrial", { domain: "materials", year: 1764, status: "dead", complexity: 4, prereqs: ["Weaving"], rarity: "uncommon" }],
  ["Voltaic pile", "industrial", { domain: "energy", year: 1800, status: "evolved", complexity: 5, prereqs: [], rarity: "rare" }],
  ["Steam locomotive", "industrial", { domain: "transportation", year: 1804, status: "dead", complexity: 6, prereqs: ["Steam engine", "Iron"], rarity: "rare" }],
  ["Photography", "industrial", { domain: "optics", year: 1826, status: "alive", complexity: 5, prereqs: ["Glassblowing"], rarity: "rare" }],
  ["Electrical telegraph", "industrial", { domain: "communication", year: 1837, status: "dead", complexity: 6, prereqs: ["Voltaic pile"], rarity: "rare" }],
  ["Bessemer process", "industrial", { domain: "materials", year: 1856, status: "evolved", complexity: 6, prereqs: ["Iron", "Blast furnace"], rarity: "uncommon" }],
  ["Telephone", "industrial", { domain: "communication", year: 1876, status: "alive", complexity: 6, prereqs: ["Electrical telegraph"], rarity: "legendary" }],
  ["Incandescent light bulb", "industrial", { domain: "energy", year: 1879, status: "dead", complexity: 5, prereqs: ["Glassblowing", "Voltaic pile"], rarity: "rare" }],
  ["Internal combustion engine", "industrial", { domain: "energy", year: 1876, status: "alive", complexity: 7, prereqs: ["Steam engine"], rarity: "rare" }],
  ["Automobile", "industrial", { domain: "transportation", year: 1886, status: "alive", complexity: 7, prereqs: ["Internal combustion engine", "Wheel"], rarity: "legendary" }],
  ["Pneumatic tube", "industrial", { domain: "communication", year: 1853, status: "dead", complexity: 4, prereqs: [], rarity: "common" }],
  ["Airship", "industrial", { domain: "transportation", year: 1852, status: "dead", complexity: 5, prereqs: [], rarity: "uncommon" }],
  ["Vaccination", "industrial", { domain: "medicine", year: 1796, status: "alive", complexity: 5, prereqs: ["Microscope"], rarity: "legendary" }],
  ["Dynamite", "industrial", { domain: "warfare", year: 1867, status: "alive", complexity: 5, prereqs: [], rarity: "uncommon" }],
  ["Typewriter", "industrial", { domain: "communication", year: 1868, status: "dead", complexity: 4, prereqs: ["Printing press"], rarity: "uncommon" }],
  ["Barbed wire", "industrial", { domain: "agriculture", year: 1873, status: "alive", complexity: 2, prereqs: ["Iron"], rarity: "common" }],

  // ── Modern (1900–1970) ─────────────────────────────────────
  ["Radio", "modern", { domain: "communication", year: 1895, status: "alive", complexity: 6, prereqs: ["Electrical telegraph"], rarity: "rare" }],
  ["Fixed-wing aircraft", "modern", { domain: "transportation", year: 1903, status: "alive", complexity: 7, prereqs: ["Internal combustion engine"], rarity: "legendary" }],
  ["Assembly line", "modern", { domain: "materials", year: 1913, status: "alive", complexity: 5, prereqs: ["Automobile"], rarity: "rare" }],
  ["Vacuum tube", "modern", { domain: "computing", year: 1904, status: "dead", complexity: 6, prereqs: ["Incandescent light bulb"], rarity: "uncommon" }],
  ["Television", "modern", { domain: "communication", year: 1927, status: "alive", complexity: 7, prereqs: ["Vacuum tube", "Radio"], rarity: "rare" }],
  ["Mechanical television", "modern", { domain: "communication", year: 1926, status: "dead", complexity: 5, prereqs: ["Radio"], rarity: "common" }],
  ["Radar", "modern", { domain: "warfare", year: 1935, status: "alive", complexity: 7, prereqs: ["Radio"], rarity: "uncommon" }],
  ["Nuclear weapon", "modern", { domain: "warfare", year: 1945, status: "alive", complexity: 9, prereqs: [], rarity: "rare" }],
  ["Nuclear power", "modern", { domain: "energy", year: 1951, status: "alive", complexity: 9, prereqs: ["Nuclear weapon"], rarity: "rare" }],
  ["Penicillin", "modern", { domain: "medicine", year: 1928, status: "alive", complexity: 5, prereqs: [], rarity: "rare" }],
  ["Transistor", "modern", { domain: "computing", year: 1947, status: "alive", complexity: 8, prereqs: ["Vacuum tube"], rarity: "legendary" }],
  ["Jet engine", "modern", { domain: "transportation", year: 1937, status: "alive", complexity: 7, prereqs: ["Fixed-wing aircraft"], rarity: "uncommon" }],
  ["Rocket", "modern", { domain: "transportation", year: 1942, status: "alive", complexity: 8, prereqs: ["Gunpowder"], rarity: "rare" }],
  ["Tetraethyllead", "modern", { domain: "energy", year: 1921, status: "dead", complexity: 5, prereqs: ["Automobile"], rarity: "common" }],
  ["DDT", "modern", { domain: "agriculture", year: 1939, status: "dead", complexity: 5, prereqs: [], rarity: "common" }],
  ["Nylon", "modern", { domain: "materials", year: 1935, status: "alive", complexity: 6, prereqs: [], rarity: "uncommon" }],
  ["Laser", "modern", { domain: "optics", year: 1960, status: "alive", complexity: 8, prereqs: [], rarity: "rare" }],
  ["Freeze-drying", "modern", { domain: "agriculture", year: 1906, status: "alive", complexity: 4, prereqs: [], rarity: "common" }],
  ["Wankel engine", "modern", { domain: "transportation", year: 1957, status: "dead", complexity: 6, prereqs: ["Internal combustion engine"], rarity: "common" }],

  // ── Information (1970–2010) ────────────────────────────────
  ["Integrated circuit", "information", { domain: "computing", year: 1958, status: "alive", complexity: 9, prereqs: ["Transistor"], rarity: "legendary" }],
  ["Microprocessor", "information", { domain: "computing", year: 1971, status: "alive", complexity: 9, prereqs: ["Integrated circuit"], rarity: "legendary" }],
  ["Optical fiber", "information", { domain: "communication", year: 1970, status: "alive", complexity: 7, prereqs: ["Laser", "Glassblowing"], rarity: "rare" }],
  ["Global Positioning System", "information", { domain: "transportation", year: 1973, status: "alive", complexity: 9, prereqs: ["Rocket", "Integrated circuit"], rarity: "rare" }],
  ["Personal computer", "information", { domain: "computing", year: 1975, status: "alive", complexity: 8, prereqs: ["Microprocessor"], rarity: "rare" }],
  ["Internet", "information", { domain: "communication", year: 1983, status: "alive", complexity: 9, prereqs: ["Personal computer", "Optical fiber"], rarity: "legendary" }],
  ["World Wide Web", "information", { domain: "communication", year: 1991, status: "alive", complexity: 8, prereqs: ["Internet"], rarity: "legendary" }],
  ["Mobile phone", "information", { domain: "communication", year: 1973, status: "alive", complexity: 7, prereqs: ["Radio", "Integrated circuit"], rarity: "rare" }],
  ["Liquid-crystal display", "information", { domain: "optics", year: 1968, status: "alive", complexity: 7, prereqs: [], rarity: "uncommon" }],
  ["Solar cell", "information", { domain: "energy", year: 1954, status: "alive", complexity: 7, prereqs: ["Transistor"], rarity: "rare" }],
  ["CRISPR gene editing", "information", { domain: "medicine", year: 2012, status: "alive", complexity: 9, prereqs: ["Microscope"], rarity: "rare" }],
  ["Betamax", "information", { domain: "communication", year: 1975, status: "dead", complexity: 6, prereqs: ["Television"], rarity: "common" }],
  ["MiniDisc", "information", { domain: "communication", year: 1992, status: "dead", complexity: 6, prereqs: ["Laser"], rarity: "common" }],
  ["Concorde", "information", { domain: "transportation", year: 1969, status: "dead", complexity: 8, prereqs: ["Jet engine"], rarity: "uncommon" }],
  ["Segway", "information", { domain: "transportation", year: 2001, status: "dead", complexity: 5, prereqs: ["Microprocessor"], rarity: "common" }],
  ["3D printing", "information", { domain: "materials", year: 1984, status: "alive", complexity: 7, prereqs: ["Microprocessor"], rarity: "uncommon" }],
  ["Cathode-ray tube", "information", { domain: "optics", year: 1897, status: "dead", complexity: 6, prereqs: ["Vacuum tube"], rarity: "common" }],
  ["Fax", "information", { domain: "communication", year: 1964, status: "dead", complexity: 5, prereqs: ["Telephone"], rarity: "common" }],
  ["HD DVD", "information", { domain: "communication", year: 2006, status: "dead", complexity: 7, prereqs: ["Laser"], rarity: "common" }],

  // ── AI Era (2010–) ────────────────────────────────────────
  ["Smartphone", "ai", { domain: "communication", year: 2007, status: "alive", complexity: 9, prereqs: ["Mobile phone", "Personal computer"], rarity: "rare" }],
  ["Deep learning", "ai", { domain: "computing", year: 2012, status: "alive", complexity: 9, prereqs: ["Microprocessor"], rarity: "rare" }],
  ["Blockchain", "ai", { domain: "computing", year: 2008, status: "alive", complexity: 7, prereqs: ["Internet"], rarity: "uncommon" }],
  ["Transformer (deep learning architecture)", "ai", { domain: "computing", year: 2017, status: "alive", complexity: 10, prereqs: ["Deep learning"], rarity: "legendary" }],
  ["Large language model", "ai", { domain: "computing", year: 2018, status: "alive", complexity: 10, prereqs: ["Transformer (deep learning architecture)"], rarity: "rare" }],
  ["Google Glass", "ai", { domain: "optics", year: 2013, status: "dead", complexity: 7, prereqs: ["Smartphone"], rarity: "common" }],
  ["Self-driving car", "ai", { domain: "transportation", year: 2014, status: "alive", complexity: 10, prereqs: ["Deep learning", "Automobile"], rarity: "uncommon" }],
  ["Intelligent agent", "ai", { domain: "computing", year: 2024, status: "alive", complexity: 10, prereqs: ["Large language model"], rarity: "uncommon" }],
  ["DALL-E", "ai", { domain: "computing", year: 2021, status: "alive", complexity: 10, prereqs: ["Transformer (deep learning architecture)"], rarity: "uncommon" }],
  ["Retrieval-augmented generation", "ai", { domain: "computing", year: 2020, status: "alive", complexity: 9, prereqs: ["Large language model", "World Wide Web"], rarity: "uncommon" }],
];
