// ── Tech — technology tree card pool ─────────────────────────

export const TECH_ERAS = {
  prehistoric:  { name: "Prehistoric",  icon: "🪨", color: "#8B7355", range: "< 3000 BCE" },
  ancient:      { name: "Ancient",      icon: "🏛", color: "#CD853F", range: "3000 BCE – 500" },
  medieval:     { name: "Medieval",     icon: "⚔", color: "#708090", range: "500 – 1400" },
  renaissance:  { name: "Renaissance",  icon: "🔭", color: "#9370DB", range: "1400 – 1700" },
  industrial:   { name: "Industrial",   icon: "⚙", color: "#B87333", range: "1700 – 1900" },
  modern:       { name: "Modern",       icon: "⚛", color: "#4682B4", range: "1900 – 1970" },
  information:  { name: "Information",  icon: "💾", color: "#32CD32", range: "1970 – 2010" },
  ai:           { name: "AI Era",       icon: "🤖", color: "#FF6347", range: "2010 –" },
};

export const TECH_DOMAINS = {
  materials:      { name: "Materials",      icon: "⚗",  color: "#CD853F" },
  construction:   { name: "Construction",   icon: "△",  color: "#A0826D" },
  energy:         { name: "Energy",         icon: "⚡", color: "#E8A838" },
  electronics:    { name: "Electronics",    icon: "∿",  color: "#58B4E8" },
  computing:      { name: "Computing",      icon: "⊞",  color: "#32CD32" },
  communication:  { name: "Communication",  icon: "📡", color: "#9370DB" },
  optics:         { name: "Optics",         icon: "◎",  color: "#E06080" },
  transportation: { name: "Transportation", icon: "⛵", color: "#4682B4" },
  agriculture:    { name: "Agriculture",    icon: "⌘",  color: "#6B8E23" },
  medicine:       { name: "Medicine",       icon: "⚕",  color: "#DC3545" },
  warfare:        { name: "Warfare",        icon: "☄",  color: "#708090" },
  finance:        { name: "Finance",        icon: "⚖",  color: "#DAA520" },
};

// [title, era, { domain, year, status, complexity, prereqs, rarity }]
// status: "alive" | "dead" | "evolved"
// complexity: 1-10 (accidental → requires global infrastructure)
// prereqs: Wikipedia titles of prerequisite technologies

export const TECH_POOL = [
  // ── Prehistoric ────────────────────────────────────────────
  ["Control of fire by early humans", "prehistoric", { domain: "energy", year: -400000, status: "alive", complexity: 1, prereqs: [], rarity: "legendary" }],
  ["Stone tool", "prehistoric", { domain: "materials", year: -3300000, status: "dead", complexity: 1, prereqs: [], rarity: "common" }],
  ["Rope", "prehistoric", { domain: "materials", year: -28000, status: "alive", complexity: 1, prereqs: [], rarity: "common" }],
  ["Basket weaving", "prehistoric", { domain: "materials", year: -12000, status: "alive", complexity: 1, prereqs: [], rarity: "common" }],
  ["Clothing", "prehistoric", { domain: "materials", year: -100000, status: "alive", complexity: 1, prereqs: [], rarity: "common" }],
  ["Bow and arrow", "prehistoric", { domain: "warfare", year: -10000, status: "dead", complexity: 2, prereqs: ["Rope", "Stone tool"], rarity: "uncommon" }],
  ["Pottery", "prehistoric", { domain: "materials", year: -29000, status: "alive", complexity: 2, prereqs: ["Control of fire by early humans"], rarity: "common" }],
  ["Neolithic Revolution", "prehistoric", { domain: "agriculture", year: -10000, status: "alive", complexity: 2, prereqs: [], rarity: "legendary" }],
  ["Animal husbandry", "prehistoric", { domain: "agriculture", year: -10000, status: "alive", complexity: 2, prereqs: ["Neolithic Revolution"], rarity: "uncommon" }],
  ["Irrigation", "prehistoric", { domain: "agriculture", year: -6000, status: "alive", complexity: 3, prereqs: ["Neolithic Revolution"], rarity: "rare" }],
  ["Weaving", "prehistoric", { domain: "materials", year: -5000, status: "alive", complexity: 2, prereqs: ["Rope"], rarity: "common" }],
  ["Leather", "prehistoric", { domain: "materials", year: -5000, status: "alive", complexity: 2, prereqs: ["Animal husbandry", "Stone tool"], rarity: "common" }],
  ["Wheel", "prehistoric", { domain: "transportation", year: -3500, status: "alive", complexity: 2, prereqs: [], rarity: "legendary" }],
  ["Fermentation in food processing", "prehistoric", { domain: "agriculture", year: -7000, status: "alive", complexity: 1, prereqs: ["Pottery"], rarity: "uncommon" }],
  ["Smelting", "prehistoric", { domain: "materials", year: -5000, status: "alive", complexity: 3, prereqs: ["Control of fire by early humans", "Pottery"], rarity: "rare" }],
  ["Dugout canoe", "prehistoric", { domain: "transportation", year: -8000, status: "dead", complexity: 2, prereqs: ["Stone tool"], rarity: "common" }],
  ["Mudbrick", "prehistoric", { domain: "construction", year: -7500, status: "alive", complexity: 2, prereqs: ["Neolithic Revolution"], rarity: "common" }],
  ["Post and lintel", "prehistoric", { domain: "construction", year: -3500, status: "alive", complexity: 1, prereqs: [], rarity: "common" }],
  ["Corbel arch", "prehistoric", { domain: "construction", year: -3000, status: "evolved", complexity: 2, prereqs: ["Mudbrick"], rarity: "common" }],

  // ── Ancient ────────────────────────────────────────────────
  ["Kiln", "ancient", { domain: "materials", year: -6000, status: "alive", complexity: 3, prereqs: ["Control of fire by early humans", "Pottery"], rarity: "uncommon" }],
  ["Bronze", "ancient", { domain: "materials", year: -3300, status: "evolved", complexity: 3, prereqs: ["Smelting"], rarity: "rare" }],
  ["Iron", "ancient", { domain: "materials", year: -1200, status: "alive", complexity: 4, prereqs: ["Smelting", "Bellows"], rarity: "rare" }],
  ["Bellows", "ancient", { domain: "materials", year: -1500, status: "alive", complexity: 2, prereqs: ["Leather"], rarity: "uncommon" }],
  ["History of writing", "ancient", { domain: "communication", year: -3200, status: "alive", complexity: 3, prereqs: [], rarity: "legendary" }],
  ["Alphabet", "ancient", { domain: "communication", year: -1800, status: "alive", complexity: 3, prereqs: ["History of writing"], rarity: "rare" }],
  ["Arch", "ancient", { domain: "construction", year: -2000, status: "alive", complexity: 3, prereqs: ["Mudbrick"], rarity: "uncommon" }],
  ["Barrel vault", "ancient", { domain: "construction", year: -1500, status: "alive", complexity: 4, prereqs: ["Arch"], rarity: "uncommon" }],
  ["Buttress", "ancient", { domain: "construction", year: -500, status: "alive", complexity: 3, prereqs: ["Mudbrick"], rarity: "common" }],
  ["Dome", "ancient", { domain: "construction", year: -100, status: "alive", complexity: 5, prereqs: ["Arch"], rarity: "rare" }],
  ["Aqueduct", "ancient", { domain: "construction", year: -700, status: "alive", complexity: 4, prereqs: ["Arch"], rarity: "uncommon" }],
  ["Roman concrete", "ancient", { domain: "construction", year: -300, status: "dead", complexity: 4, prereqs: ["Kiln"], rarity: "rare" }],
  ["Glassblowing", "ancient", { domain: "materials", year: -50, status: "alive", complexity: 3, prereqs: ["Control of fire by early humans", "Bellows"], rarity: "uncommon" }],
  ["Sail", "ancient", { domain: "transportation", year: -3000, status: "evolved", complexity: 3, prereqs: ["Weaving", "Rope"], rarity: "rare" }],
  ["Catapult", "ancient", { domain: "warfare", year: -400, status: "dead", complexity: 3, prereqs: ["Rope"], rarity: "uncommon" }],
  ["Abacus", "ancient", { domain: "computing", year: -2400, status: "dead", complexity: 2, prereqs: [], rarity: "uncommon" }],
  ["Sundial", "ancient", { domain: "optics", year: -1500, status: "evolved", complexity: 2, prereqs: [], rarity: "common" }],
  ["Parchment", "ancient", { domain: "communication", year: -1500, status: "dead", complexity: 2, prereqs: ["Leather"], rarity: "common" }],
  ["Chariot", "ancient", { domain: "transportation", year: -2000, status: "dead", complexity: 3, prereqs: ["Wheel", "Animal husbandry"], rarity: "uncommon" }],
  ["Geocentric model", "ancient", { domain: "optics", year: -300, status: "dead", complexity: 3, prereqs: ["History of writing", "Sundial"], rarity: "uncommon" }],
  ["Greek fire", "ancient", { domain: "warfare", year: 672, status: "dead", complexity: 4, prereqs: [], rarity: "rare" }],
  ["Paper", "ancient", { domain: "communication", year: -100, status: "alive", complexity: 3, prereqs: ["History of writing"], rarity: "rare" }],
  ["Lever", "ancient", { domain: "construction", year: -5000, status: "alive", complexity: 1, prereqs: [], rarity: "uncommon" }],
  ["Pulley", "ancient", { domain: "construction", year: -1500, status: "alive", complexity: 2, prereqs: ["Rope", "Lever"], rarity: "uncommon" }],
  ["Water wheel", "ancient", { domain: "energy", year: -300, status: "evolved", complexity: 3, prereqs: ["Wheel"], rarity: "uncommon" }],
  ["Gear", "ancient", { domain: "construction", year: -300, status: "alive", complexity: 3, prereqs: ["Wheel", "Bronze"], rarity: "uncommon" }],
  ["Road", "ancient", { domain: "construction", year: -4000, status: "alive", complexity: 2, prereqs: [], rarity: "common" }],
  ["Calendar", "ancient", { domain: "computing", year: -2600, status: "alive", complexity: 3, prereqs: ["History of writing", "Sundial"], rarity: "uncommon" }],
  ["Geometry", "ancient", { domain: "computing", year: -300, status: "alive", complexity: 4, prereqs: ["History of writing"], rarity: "rare" }],
  ["Coin", "ancient", { domain: "materials", year: -600, status: "alive", complexity: 3, prereqs: ["Smelting"], rarity: "uncommon" }],
  ["Chainmail", "ancient", { domain: "warfare", year: -300, status: "dead", complexity: 4, prereqs: ["Iron"], rarity: "uncommon" }],
  ["Cartography", "ancient", { domain: "communication", year: -600, status: "alive", complexity: 3, prereqs: ["History of writing", "Geometry"], rarity: "uncommon" }],
  ["Water clock", "ancient", { domain: "computing", year: -1500, status: "dead", complexity: 2, prereqs: ["Sundial", "Pottery"], rarity: "uncommon" }],

  // ── Medieval ───────────────────────────────────────────────
  ["Heavy plough", "medieval", { domain: "agriculture", year: 600, status: "evolved", complexity: 3, prereqs: ["Iron", "Animal husbandry"], rarity: "uncommon" }],
  ["Compass", "medieval", { domain: "transportation", year: 1040, status: "alive", complexity: 3, prereqs: ["Iron"], rarity: "rare" }],
  ["Gunpowder", "medieval", { domain: "warfare", year: 850, status: "alive", complexity: 4, prereqs: ["Alchemy"], rarity: "legendary" }],
  ["Windmill", "medieval", { domain: "energy", year: 600, status: "evolved", complexity: 3, prereqs: ["Gear", "Sail"], rarity: "uncommon" }],
  ["Woodblock printing", "medieval", { domain: "communication", year: 200, status: "evolved", complexity: 3, prereqs: ["Paper"], rarity: "uncommon" }],
  ["Astrolabe", "medieval", { domain: "optics", year: 550, status: "dead", complexity: 4, prereqs: ["Geometry", "Gear", "Sundial"], rarity: "uncommon" }],
  ["Stirrup", "medieval", { domain: "warfare", year: 300, status: "dead", complexity: 2, prereqs: ["Iron", "Leather"], rarity: "uncommon" }],
  ["Trebuchet", "medieval", { domain: "warfare", year: 1200, status: "dead", complexity: 3, prereqs: ["Catapult"], rarity: "common" }],
  ["Alchemy", "medieval", { domain: "materials", year: 300, status: "dead", complexity: 4, prereqs: ["Kiln"], rarity: "rare" }],
  ["Longbow", "medieval", { domain: "warfare", year: 1250, status: "dead", complexity: 2, prereqs: ["Bow and arrow"], rarity: "common" }],
  ["Pointed arch", "medieval", { domain: "construction", year: 1100, status: "alive", complexity: 4, prereqs: ["Arch"], rarity: "uncommon" }],
  ["Rib vault", "medieval", { domain: "construction", year: 1150, status: "alive", complexity: 6, prereqs: ["Barrel vault", "Pointed arch"], rarity: "uncommon" }],
  ["Flying buttress", "medieval", { domain: "construction", year: 1180, status: "alive", complexity: 6, prereqs: ["Buttress", "Pointed arch"], rarity: "rare" }],
  ["Mechanical clock", "medieval", { domain: "computing", year: 1300, status: "alive", complexity: 5, prereqs: ["Gear", "Water clock", "Calendar"], rarity: "rare" }],
  ["Blast furnace", "medieval", { domain: "materials", year: 1100, status: "alive", complexity: 4, prereqs: ["Iron", "Bellows"], rarity: "uncommon" }],
  ["Spectacles", "medieval", { domain: "optics", year: 1286, status: "alive", complexity: 3, prereqs: ["Glassblowing"], rarity: "uncommon" }],
  ["Crop rotation", "medieval", { domain: "agriculture", year: 800, status: "alive", complexity: 2, prereqs: ["Heavy plough"], rarity: "common" }],
  ["Spinning wheel", "medieval", { domain: "materials", year: 1200, status: "evolved", complexity: 3, prereqs: ["Weaving", "Wheel"], rarity: "uncommon" }],
  ["Steel", "medieval", { domain: "materials", year: 1200, status: "alive", complexity: 5, prereqs: ["Blast furnace"], rarity: "rare" }],
  ["Distillation", "medieval", { domain: "materials", year: 800, status: "alive", complexity: 3, prereqs: ["Glassblowing", "Alchemy"], rarity: "uncommon" }],
  ["University", "medieval", { domain: "communication", year: 1088, status: "alive", complexity: 3, prereqs: ["Alphabet", "Paper"], rarity: "rare" }],
  ["Plate armour", "medieval", { domain: "warfare", year: 1350, status: "dead", complexity: 4, prereqs: ["Steel"], rarity: "uncommon" }],
  ["Hourglass", "medieval", { domain: "optics", year: 1300, status: "dead", complexity: 2, prereqs: ["Glassblowing"], rarity: "common" }],
  ["Paper money", "medieval", { domain: "finance", year: 1024, status: "alive", complexity: 3, prereqs: ["Paper", "Coin", "Woodblock printing"], rarity: "rare" }],
  ["Insurance", "medieval", { domain: "finance", year: 1347, status: "alive", complexity: 3, prereqs: ["Cartography", "Coin"], rarity: "uncommon" }],

  // ── Renaissance ────────────────────────────────────────────
  ["Printing press", "renaissance", { domain: "communication", year: 1440, status: "alive", complexity: 5, prereqs: ["Woodblock printing", "Paper", "Steel"], rarity: "legendary" }],
  ["Telescope", "renaissance", { domain: "optics", year: 1608, status: "alive", complexity: 5, prereqs: ["Spectacles", "Glassblowing"], rarity: "rare" }],
  ["Microscope", "renaissance", { domain: "optics", year: 1620, status: "alive", complexity: 5, prereqs: ["Spectacles", "Glassblowing"], rarity: "rare" }],
  ["Automaton", "renaissance", { domain: "computing", year: 1500, status: "dead", complexity: 5, prereqs: ["Mechanical clock", "Gear"], rarity: "uncommon" }],
  ["Galleon", "renaissance", { domain: "transportation", year: 1500, status: "dead", complexity: 4, prereqs: ["Sail", "Compass", "Cartography"], rarity: "uncommon" }],
  ["Musket", "renaissance", { domain: "warfare", year: 1500, status: "dead", complexity: 4, prereqs: ["Gunpowder", "Steel"], rarity: "uncommon" }],
  ["Phlogiston theory", "renaissance", { domain: "energy", year: 1667, status: "dead", complexity: 3, prereqs: ["Alchemy"], rarity: "common" }],
  ["Pendulum clock", "renaissance", { domain: "computing", year: 1656, status: "dead", complexity: 5, prereqs: ["Mechanical clock"], rarity: "uncommon" }],
  ["Barometer", "renaissance", { domain: "optics", year: 1643, status: "alive", complexity: 3, prereqs: ["Glassblowing", "Distillation"], rarity: "common" }],
  ["Thermometer", "renaissance", { domain: "optics", year: 1612, status: "alive", complexity: 3, prereqs: ["Glassblowing"], rarity: "common" }],
  ["Calculus", "renaissance", { domain: "computing", year: 1665, status: "alive", complexity: 7, prereqs: ["Geometry", "Printing press"], rarity: "rare" }],
  ["Heliocentrism", "renaissance", { domain: "optics", year: 1543, status: "alive", complexity: 4, prereqs: ["Telescope", "Geometry", "Geocentric model"], rarity: "rare" }],
  ["Lock (water navigation)", "renaissance", { domain: "construction", year: 1495, status: "alive", complexity: 3, prereqs: ["Gear"], rarity: "common" }],
  ["Sextant", "renaissance", { domain: "optics", year: 1600, status: "alive", complexity: 5, prereqs: ["Telescope", "Astrolabe"], rarity: "uncommon" }],
  ["Slide rule", "renaissance", { domain: "computing", year: 1622, status: "dead", complexity: 4, prereqs: ["Geometry", "Printing press"], rarity: "uncommon" }],
  ["Double-entry bookkeeping", "renaissance", { domain: "finance", year: 1494, status: "alive", complexity: 4, prereqs: ["Alphabet", "Coin", "Printing press"], rarity: "rare" }],
  ["Stock exchange", "renaissance", { domain: "finance", year: 1602, status: "alive", complexity: 5, prereqs: ["Double-entry bookkeeping", "Insurance"], rarity: "rare" }],
  ["Central banking", "renaissance", { domain: "finance", year: 1694, status: "alive", complexity: 5, prereqs: ["Paper money", "Stock exchange"], rarity: "rare" }],
  ["Joint-stock company", "renaissance", { domain: "finance", year: 1602, status: "alive", complexity: 4, prereqs: ["Insurance", "Galleon"], rarity: "uncommon" }],
  ["Leyden jar", "renaissance", { domain: "electronics", year: 1745, status: "evolved", complexity: 3, prereqs: ["Glassblowing"], rarity: "uncommon" }],

  // ── Industrial ─────────────────────────────────────────────
  ["Steam engine", "industrial", { domain: "energy", year: 1712, status: "evolved", complexity: 6, prereqs: ["Iron", "Bellows"], rarity: "legendary" }],
  ["Spinning jenny", "industrial", { domain: "materials", year: 1764, status: "dead", complexity: 4, prereqs: ["Spinning wheel"], rarity: "uncommon" }],
  ["Voltaic pile", "industrial", { domain: "energy", year: 1800, status: "evolved", complexity: 5, prereqs: ["Coin", "Alchemy"], rarity: "rare" }],
  ["Steam locomotive", "industrial", { domain: "transportation", year: 1804, status: "dead", complexity: 6, prereqs: ["Steam engine", "Iron", "Road"], rarity: "rare" }],
  ["Photography", "industrial", { domain: "optics", year: 1826, status: "alive", complexity: 5, prereqs: ["Glassblowing", "Alchemy"], rarity: "rare" }],
  ["Electrical telegraph", "industrial", { domain: "communication", year: 1837, status: "dead", complexity: 6, prereqs: ["Relay", "Alphabet"], rarity: "rare" }],
  ["Bessemer process", "industrial", { domain: "materials", year: 1856, status: "evolved", complexity: 6, prereqs: ["Blast furnace", "Steel"], rarity: "uncommon" }],
  ["Telephone", "industrial", { domain: "communication", year: 1876, status: "alive", complexity: 6, prereqs: ["Electrical telegraph"], rarity: "legendary" }],
  ["Incandescent light bulb", "industrial", { domain: "energy", year: 1879, status: "dead", complexity: 5, prereqs: ["Glassblowing", "Voltaic pile"], rarity: "rare" }],
  ["Internal combustion engine", "industrial", { domain: "energy", year: 1876, status: "alive", complexity: 7, prereqs: ["Steam engine", "Voltaic pile"], rarity: "rare" }],
  ["Automobile", "industrial", { domain: "transportation", year: 1886, status: "alive", complexity: 7, prereqs: ["Internal combustion engine", "Wheel", "Vulcanization"], rarity: "legendary" }],
  ["Pneumatic tube", "industrial", { domain: "communication", year: 1853, status: "dead", complexity: 4, prereqs: ["Steam engine"], rarity: "common" }],
  ["Airship", "industrial", { domain: "transportation", year: 1852, status: "dead", complexity: 5, prereqs: ["Steam engine"], rarity: "uncommon" }],
  ["Vaccination", "industrial", { domain: "medicine", year: 1796, status: "alive", complexity: 5, prereqs: ["Microscope"], rarity: "legendary" }],
  ["Dynamite", "industrial", { domain: "warfare", year: 1867, status: "alive", complexity: 5, prereqs: ["Gunpowder", "Alchemy"], rarity: "uncommon" }],
  ["Typewriter", "industrial", { domain: "communication", year: 1868, status: "dead", complexity: 4, prereqs: ["Printing press"], rarity: "uncommon" }],
  ["Barbed wire", "industrial", { domain: "agriculture", year: 1873, status: "alive", complexity: 2, prereqs: ["Steel"], rarity: "common" }],
  ["Electric motor", "industrial", { domain: "electronics", year: 1821, status: "alive", complexity: 5, prereqs: ["Electromagnet"], rarity: "rare" }],
  ["Dynamo", "industrial", { domain: "electronics", year: 1831, status: "alive", complexity: 6, prereqs: ["Electric motor"], rarity: "rare" }],
  ["Anesthesia", "industrial", { domain: "medicine", year: 1846, status: "alive", complexity: 4, prereqs: ["Distillation"], rarity: "uncommon" }],
  ["Antiseptic", "industrial", { domain: "medicine", year: 1867, status: "alive", complexity: 4, prereqs: ["Microscope", "Distillation"], rarity: "uncommon" }],
  ["Vulcanization", "industrial", { domain: "materials", year: 1844, status: "alive", complexity: 4, prereqs: ["Alchemy"], rarity: "uncommon" }],
  ["Truss", "industrial", { domain: "construction", year: 1820, status: "alive", complexity: 5, prereqs: ["Iron", "Geometry"], rarity: "uncommon" }],
  ["Portland cement", "industrial", { domain: "construction", year: 1824, status: "alive", complexity: 4, prereqs: ["Kiln"], rarity: "uncommon" }],
  ["Suspension bridge", "industrial", { domain: "construction", year: 1826, status: "alive", complexity: 7, prereqs: ["Iron", "Road"], rarity: "rare" }],
  ["I-beam", "industrial", { domain: "construction", year: 1849, status: "alive", complexity: 4, prereqs: ["Bessemer process"], rarity: "uncommon" }],
  ["Cantilever", "industrial", { domain: "construction", year: 1867, status: "alive", complexity: 6, prereqs: ["I-beam"], rarity: "uncommon" }],
  ["Sewing machine", "industrial", { domain: "materials", year: 1846, status: "alive", complexity: 4, prereqs: ["Spinning jenny", "Steel"], rarity: "common" }],
  ["Aluminium", "industrial", { domain: "materials", year: 1886, status: "alive", complexity: 5, prereqs: ["Smelting", "Dynamo"], rarity: "rare" }],
  ["Reinforced concrete", "industrial", { domain: "materials", year: 1867, status: "alive", complexity: 5, prereqs: ["Portland cement", "Iron"], rarity: "uncommon" }],
  ["Refrigeration", "industrial", { domain: "energy", year: 1834, status: "alive", complexity: 5, prereqs: ["Steam engine", "Thermometer"], rarity: "uncommon" }],
  ["Stethoscope", "industrial", { domain: "medicine", year: 1816, status: "alive", complexity: 2, prereqs: [], rarity: "common" }],
  ["Rifling", "industrial", { domain: "warfare", year: 1710, status: "alive", complexity: 4, prereqs: ["Musket", "Steel"], rarity: "uncommon" }],
  ["Electromagnet", "industrial", { domain: "electronics", year: 1824, status: "alive", complexity: 5, prereqs: ["Voltaic pile", "Iron"], rarity: "rare" }],
  ["Electromagnetic induction", "industrial", { domain: "electronics", year: 1831, status: "alive", complexity: 6, prereqs: ["Electromagnet", "Calculus"], rarity: "rare" }],
  ["Relay", "industrial", { domain: "electronics", year: 1835, status: "evolved", complexity: 4, prereqs: ["Electromagnet"], rarity: "uncommon" }],
  ["Transformer", "industrial", { domain: "electronics", year: 1885, status: "alive", complexity: 6, prereqs: ["Electromagnetic induction", "Iron"], rarity: "rare" }],
  ["Turbine", "industrial", { domain: "energy", year: 1849, status: "alive", complexity: 6, prereqs: ["Water wheel", "Steam engine"], rarity: "rare" }],
  ["Chronometer", "industrial", { domain: "computing", year: 1761, status: "alive", complexity: 5, prereqs: ["Pendulum clock"], rarity: "uncommon" }],
  ["Bicycle", "industrial", { domain: "transportation", year: 1885, status: "alive", complexity: 3, prereqs: ["Wheel", "Vulcanization", "Steel"], rarity: "common" }],
  ["Gold standard", "industrial", { domain: "finance", year: 1821, status: "dead", complexity: 4, prereqs: ["Coin", "Central banking"], rarity: "uncommon" }],
  ["Wire transfer", "industrial", { domain: "finance", year: 1872, status: "evolved", complexity: 5, prereqs: ["Electrical telegraph", "Central banking"], rarity: "uncommon" }],
  ["Futures exchange", "industrial", { domain: "finance", year: 1848, status: "alive", complexity: 5, prereqs: ["Stock exchange", "Steam locomotive"], rarity: "uncommon" }],

  // ── Modern (1900–1970) ─────────────────────────────────────
  ["Radio", "modern", { domain: "communication", year: 1895, status: "alive", complexity: 6, prereqs: ["Electrical telegraph", "Dynamo"], rarity: "rare" }],
  ["Fixed-wing aircraft", "modern", { domain: "transportation", year: 1903, status: "alive", complexity: 7, prereqs: ["Internal combustion engine", "Calculus"], rarity: "legendary" }],
  ["Assembly line", "modern", { domain: "materials", year: 1913, status: "alive", complexity: 5, prereqs: ["Automobile", "Electric motor"], rarity: "rare" }],
  ["Crystal detector", "modern", { domain: "electronics", year: 1906, status: "dead", complexity: 4, prereqs: ["Radio"], rarity: "uncommon" }],
  ["Triode", "modern", { domain: "electronics", year: 1906, status: "evolved", complexity: 6, prereqs: ["Vacuum tube"], rarity: "uncommon" }],
  ["Vacuum tube", "modern", { domain: "computing", year: 1904, status: "dead", complexity: 6, prereqs: ["Incandescent light bulb", "Dynamo"], rarity: "uncommon" }],
  ["Television", "modern", { domain: "communication", year: 1927, status: "alive", complexity: 7, prereqs: ["Vacuum tube", "Radio"], rarity: "rare" }],
  ["Mechanical television", "modern", { domain: "communication", year: 1926, status: "dead", complexity: 5, prereqs: ["Radio"], rarity: "common" }],
  ["Radar", "modern", { domain: "warfare", year: 1935, status: "alive", complexity: 7, prereqs: ["Radio", "Vacuum tube"], rarity: "uncommon" }],
  ["Nuclear weapon", "modern", { domain: "warfare", year: 1945, status: "alive", complexity: 9, prereqs: ["Calculus", "Dynamo"], rarity: "rare" }],
  ["Nuclear power", "modern", { domain: "energy", year: 1951, status: "alive", complexity: 9, prereqs: ["Nuclear weapon", "Steam engine"], rarity: "rare" }],
  ["Penicillin", "modern", { domain: "medicine", year: 1928, status: "alive", complexity: 5, prereqs: ["Microscope"], rarity: "rare" }],
  ["Transistor", "modern", { domain: "computing", year: 1947, status: "alive", complexity: 8, prereqs: ["Vacuum tube", "Radar"], rarity: "legendary" }],
  ["Jet engine", "modern", { domain: "transportation", year: 1937, status: "alive", complexity: 7, prereqs: ["Fixed-wing aircraft", "Turbine"], rarity: "uncommon" }],
  ["Rocket", "modern", { domain: "transportation", year: 1942, status: "alive", complexity: 8, prereqs: ["Gunpowder", "Calculus"], rarity: "rare" }],
  ["Tetraethyllead", "modern", { domain: "energy", year: 1921, status: "dead", complexity: 5, prereqs: ["Automobile"], rarity: "common" }],
  ["DDT", "modern", { domain: "agriculture", year: 1939, status: "dead", complexity: 5, prereqs: ["Alchemy"], rarity: "common" }],
  ["Nylon", "modern", { domain: "materials", year: 1935, status: "alive", complexity: 6, prereqs: ["Alchemy", "Distillation"], rarity: "uncommon" }],
  ["Laser", "modern", { domain: "optics", year: 1960, status: "alive", complexity: 8, prereqs: ["Vacuum tube", "Calculus"], rarity: "rare" }],
  ["Freeze-drying", "modern", { domain: "agriculture", year: 1906, status: "alive", complexity: 4, prereqs: ["Refrigeration"], rarity: "common" }],
  ["Wankel engine", "modern", { domain: "transportation", year: 1957, status: "dead", complexity: 6, prereqs: ["Internal combustion engine"], rarity: "common" }],
  ["X-ray", "modern", { domain: "medicine", year: 1895, status: "alive", complexity: 6, prereqs: ["Vacuum tube", "Photography"], rarity: "rare" }],
  ["Stainless steel", "modern", { domain: "materials", year: 1913, status: "alive", complexity: 5, prereqs: ["Bessemer process"], rarity: "uncommon" }],
  ["Bakelite", "modern", { domain: "materials", year: 1907, status: "dead", complexity: 5, prereqs: ["Alchemy", "Dynamo"], rarity: "common" }],
  ["Synthetic rubber", "modern", { domain: "materials", year: 1909, status: "alive", complexity: 5, prereqs: ["Vulcanization", "Alchemy"], rarity: "uncommon" }],
  ["Czochralski process", "modern", { domain: "materials", year: 1916, status: "alive", complexity: 6, prereqs: ["Alchemy", "Kiln"], rarity: "uncommon" }],
  ["Fiberglass", "modern", { domain: "materials", year: 1938, status: "alive", complexity: 5, prereqs: ["Glassblowing"], rarity: "uncommon" }],
  ["Epoxy", "modern", { domain: "materials", year: 1936, status: "alive", complexity: 5, prereqs: ["Alchemy", "Distillation"], rarity: "uncommon" }],
  ["Float glass", "modern", { domain: "materials", year: 1959, status: "alive", complexity: 5, prereqs: ["Glassblowing", "Steel"], rarity: "uncommon" }],
  ["Curtain wall (architecture)", "modern", { domain: "construction", year: 1918, status: "alive", complexity: 6, prereqs: ["I-beam", "Glassblowing"], rarity: "uncommon" }],
  ["Prestressed concrete", "modern", { domain: "materials", year: 1928, status: "alive", complexity: 6, prereqs: ["Reinforced concrete", "Steel"], rarity: "uncommon" }],
  ["Deep foundation", "modern", { domain: "construction", year: 1930, status: "alive", complexity: 7, prereqs: ["Reinforced concrete"], rarity: "uncommon" }],
  ["Space frame", "modern", { domain: "construction", year: 1943, status: "alive", complexity: 6, prereqs: ["Truss", "Aluminium"], rarity: "uncommon" }],
  ["Geodesic dome", "modern", { domain: "construction", year: 1948, status: "alive", complexity: 7, prereqs: ["Dome", "Aluminium"], rarity: "rare" }],
  ["Cable-stayed bridge", "modern", { domain: "construction", year: 1956, status: "alive", complexity: 8, prereqs: ["Suspension bridge", "Reinforced concrete"], rarity: "uncommon" }],
  ["Sonar", "modern", { domain: "warfare", year: 1906, status: "alive", complexity: 5, prereqs: ["Electrical telegraph"], rarity: "uncommon" }],
  ["Helicopter", "modern", { domain: "transportation", year: 1939, status: "alive", complexity: 7, prereqs: ["Fixed-wing aircraft"], rarity: "uncommon" }],
  ["Air conditioning", "modern", { domain: "energy", year: 1902, status: "alive", complexity: 5, prereqs: ["Refrigeration", "Electric motor"], rarity: "uncommon" }],
  ["Insulin", "modern", { domain: "medicine", year: 1921, status: "alive", complexity: 6, prereqs: ["Microscope", "Anesthesia"], rarity: "rare" }],
  ["Printed circuit board", "modern", { domain: "electronics", year: 1936, status: "alive", complexity: 5, prereqs: ["Vacuum tube"], rarity: "uncommon" }],
  ["Magnetic tape", "modern", { domain: "communication", year: 1928, status: "dead", complexity: 5, prereqs: ["Dynamo", "Steel"], rarity: "uncommon" }],
  ["Haber process", "modern", { domain: "agriculture", year: 1909, status: "alive", complexity: 7, prereqs: ["Steam engine", "Alchemy"], rarity: "rare" }],
  ["Alternating current", "modern", { domain: "electronics", year: 1891, status: "alive", complexity: 7, prereqs: ["Dynamo", "Transformer"], rarity: "rare" }],
  ["Power grid", "modern", { domain: "energy", year: 1882, status: "alive", complexity: 7, prereqs: ["Dynamo", "Incandescent light bulb"], rarity: "rare" }],
  ["Submarine", "modern", { domain: "transportation", year: 1900, status: "alive", complexity: 7, prereqs: ["Steam engine", "Sonar", "Steel"], rarity: "uncommon" }],
  ["Hydroelectric power", "modern", { domain: "energy", year: 1882, status: "alive", complexity: 6, prereqs: ["Turbine", "Dynamo"], rarity: "rare" }],
  ["Fluorescent lamp", "modern", { domain: "energy", year: 1926, status: "evolved", complexity: 5, prereqs: ["Vacuum tube", "Incandescent light bulb"], rarity: "common" }],
  ["Containerization", "modern", { domain: "transportation", year: 1956, status: "alive", complexity: 5, prereqs: ["Steel", "Sextant", "Steam locomotive"], rarity: "uncommon" }],
  ["Credit card", "modern", { domain: "finance", year: 1950, status: "alive", complexity: 4, prereqs: ["Telephone", "Central banking"], rarity: "uncommon" }],

  // ── Information (1970–2010) ────────────────────────────────
  ["Atomic clock", "information", { domain: "computing", year: 1955, status: "alive", complexity: 8, prereqs: ["Chronometer", "Radar"], rarity: "rare" }],
  ["Semiconductor diode", "information", { domain: "electronics", year: 1947, status: "alive", complexity: 6, prereqs: ["Crystal detector", "Vacuum tube"], rarity: "uncommon" }],
  ["MOSFET", "information", { domain: "electronics", year: 1959, status: "alive", complexity: 8, prereqs: ["Transistor"], rarity: "rare" }],
  ["Operational amplifier", "information", { domain: "electronics", year: 1963, status: "alive", complexity: 6, prereqs: ["Transistor", "Printed circuit board"], rarity: "uncommon" }],
  ["Thyristor", "information", { domain: "electronics", year: 1957, status: "alive", complexity: 6, prereqs: ["Semiconductor diode"], rarity: "uncommon" }],
  ["Integrated circuit", "information", { domain: "computing", year: 1958, status: "alive", complexity: 9, prereqs: ["Transistor"], rarity: "legendary" }],
  ["Microprocessor", "information", { domain: "computing", year: 1971, status: "alive", complexity: 9, prereqs: ["Integrated circuit"], rarity: "legendary" }],
  ["Optical fiber", "information", { domain: "communication", year: 1970, status: "alive", complexity: 7, prereqs: ["Laser", "Glassblowing"], rarity: "rare" }],
  ["Global Positioning System", "information", { domain: "transportation", year: 1973, status: "alive", complexity: 9, prereqs: ["Rocket", "Integrated circuit", "Radio", "Atomic clock"], rarity: "rare" }],
  ["Personal computer", "information", { domain: "computing", year: 1975, status: "alive", complexity: 8, prereqs: ["Microprocessor", "Magnetic tape"], rarity: "rare" }],
  ["Internet", "information", { domain: "communication", year: 1983, status: "alive", complexity: 9, prereqs: ["Personal computer", "Optical fiber"], rarity: "legendary" }],
  ["World Wide Web", "information", { domain: "communication", year: 1991, status: "alive", complexity: 8, prereqs: ["Internet"], rarity: "legendary" }],
  ["Mobile phone", "information", { domain: "communication", year: 1973, status: "alive", complexity: 7, prereqs: ["Radio", "Integrated circuit"], rarity: "rare" }],
  ["Charge-coupled device", "information", { domain: "electronics", year: 1969, status: "alive", complexity: 7, prereqs: ["MOSFET"], rarity: "uncommon" }],
  ["Power inverter", "information", { domain: "electronics", year: 1968, status: "alive", complexity: 6, prereqs: ["Thyristor", "Alternating current"], rarity: "uncommon" }],
  ["Flash memory", "information", { domain: "electronics", year: 1984, status: "alive", complexity: 8, prereqs: ["MOSFET", "Integrated circuit"], rarity: "rare" }],
  ["Liquid-crystal display", "information", { domain: "optics", year: 1968, status: "alive", complexity: 7, prereqs: ["Transistor"], rarity: "uncommon" }],
  ["Solar cell", "information", { domain: "energy", year: 1954, status: "alive", complexity: 7, prereqs: ["Transistor"], rarity: "rare" }],
  ["CRISPR gene editing", "information", { domain: "medicine", year: 2012, status: "alive", complexity: 9, prereqs: ["Genetic engineering"], rarity: "rare" }],
  ["Betamax", "information", { domain: "communication", year: 1975, status: "dead", complexity: 6, prereqs: ["Television", "Magnetic tape"], rarity: "common" }],
  ["MiniDisc", "information", { domain: "communication", year: 1992, status: "dead", complexity: 6, prereqs: ["Laser", "Integrated circuit"], rarity: "common" }],
  ["Concorde", "information", { domain: "transportation", year: 1969, status: "dead", complexity: 8, prereqs: ["Jet engine", "Radar"], rarity: "uncommon" }],
  ["Segway", "information", { domain: "transportation", year: 2001, status: "dead", complexity: 5, prereqs: ["Microprocessor", "Electric motor"], rarity: "common" }],
  ["3D printing", "information", { domain: "materials", year: 1984, status: "alive", complexity: 7, prereqs: ["Microprocessor", "Laser"], rarity: "uncommon" }],
  ["Carbon fiber", "information", { domain: "materials", year: 1958, status: "alive", complexity: 7, prereqs: ["Nylon", "Kiln"], rarity: "uncommon" }],
  ["Kevlar", "information", { domain: "materials", year: 1965, status: "alive", complexity: 6, prereqs: ["Nylon"], rarity: "uncommon" }],
  ["Photolithography", "information", { domain: "materials", year: 1958, status: "alive", complexity: 8, prereqs: ["Photography", "Czochralski process"], rarity: "rare" }],
  ["Cyanoacrylate", "information", { domain: "materials", year: 1958, status: "alive", complexity: 4, prereqs: ["Alchemy"], rarity: "common" }],
  ["Cathode-ray tube", "information", { domain: "optics", year: 1897, status: "dead", complexity: 6, prereqs: ["Vacuum tube", "Glassblowing"], rarity: "common" }],
  ["Fax", "information", { domain: "communication", year: 1964, status: "dead", complexity: 5, prereqs: ["Telephone", "Photography"], rarity: "common" }],
  ["HD DVD", "information", { domain: "communication", year: 2006, status: "dead", complexity: 7, prereqs: ["Laser", "Microprocessor"], rarity: "common" }],
  ["Communication satellite", "information", { domain: "communication", year: 1962, status: "alive", complexity: 8, prereqs: ["Rocket", "Radio", "Solar cell"], rarity: "rare" }],
  ["Light-emitting diode", "information", { domain: "optics", year: 1962, status: "alive", complexity: 6, prereqs: ["Transistor"], rarity: "uncommon" }],
  ["MRI", "information", { domain: "medicine", year: 1977, status: "alive", complexity: 8, prereqs: ["Microprocessor", "Nuclear power"], rarity: "rare" }],
  ["Lithium-ion battery", "information", { domain: "energy", year: 1991, status: "alive", complexity: 7, prereqs: ["Voltaic pile", "Alchemy"], rarity: "rare" }],
  ["Compact disc", "information", { domain: "communication", year: 1982, status: "dead", complexity: 6, prereqs: ["Laser", "Integrated circuit"], rarity: "uncommon" }],
  ["Digital camera", "information", { domain: "optics", year: 1975, status: "alive", complexity: 7, prereqs: ["Integrated circuit", "Photography"], rarity: "uncommon" }],
  ["Touchscreen", "information", { domain: "computing", year: 1965, status: "alive", complexity: 7, prereqs: ["Integrated circuit", "Liquid-crystal display"], rarity: "uncommon" }],
  ["Wi-Fi", "information", { domain: "communication", year: 1997, status: "alive", complexity: 7, prereqs: ["Radio", "Microprocessor"], rarity: "uncommon" }],
  ["USB", "information", { domain: "computing", year: 1996, status: "alive", complexity: 6, prereqs: ["Personal computer", "Microprocessor"], rarity: "common" }],
  ["Lithium polymer battery", "information", { domain: "energy", year: 1997, status: "alive", complexity: 7, prereqs: ["Lithium-ion battery"], rarity: "common" }],
  ["Cloud computing", "information", { domain: "computing", year: 1999, status: "alive", complexity: 8, prereqs: ["Internet", "Microprocessor"], rarity: "rare" }],
  ["Robotics", "information", { domain: "computing", year: 1961, status: "alive", complexity: 8, prereqs: ["Microprocessor", "Assembly line", "Electric motor"], rarity: "uncommon" }],
  ["Genetic engineering", "information", { domain: "medicine", year: 1973, status: "alive", complexity: 8, prereqs: ["Microscope", "Personal computer"], rarity: "rare" }],
  ["Search engine", "information", { domain: "computing", year: 1993, status: "alive", complexity: 7, prereqs: ["World Wide Web"], rarity: "rare" }],
  ["Machine learning", "information", { domain: "computing", year: 1959, status: "alive", complexity: 8, prereqs: ["Personal computer", "Calculus"], rarity: "rare" }],
  ["E-commerce", "information", { domain: "finance", year: 1995, status: "alive", complexity: 7, prereqs: ["World Wide Web", "Credit card"], rarity: "rare" }],
  ["Algorithmic trading", "information", { domain: "finance", year: 1998, status: "alive", complexity: 8, prereqs: ["Stock exchange", "Microprocessor"], rarity: "uncommon" }],

  // ── AI Era (2010–) ────────────────────────────────────────
  ["Smartphone", "ai", { domain: "communication", year: 2007, status: "alive", complexity: 9, prereqs: ["Mobile phone", "Touchscreen", "Wi-Fi"], rarity: "rare" }],
  ["Deep learning", "ai", { domain: "computing", year: 2012, status: "alive", complexity: 9, prereqs: ["Machine learning", "Cloud computing"], rarity: "rare" }],
  ["Blockchain", "ai", { domain: "finance", year: 2008, status: "alive", complexity: 7, prereqs: ["Internet", "E-commerce"], rarity: "uncommon" }],
  ["Transformer (deep learning architecture)", "ai", { domain: "computing", year: 2017, status: "alive", complexity: 10, prereqs: ["Deep learning"], rarity: "legendary" }],
  ["Large language model", "ai", { domain: "computing", year: 2018, status: "alive", complexity: 10, prereqs: ["Transformer (deep learning architecture)", "Internet"], rarity: "rare" }],
  ["Google Glass", "ai", { domain: "optics", year: 2013, status: "dead", complexity: 7, prereqs: ["Smartphone"], rarity: "common" }],
  ["Self-driving car", "ai", { domain: "transportation", year: 2014, status: "alive", complexity: 10, prereqs: ["Deep learning", "Automobile", "Global Positioning System"], rarity: "uncommon" }],
  ["Intelligent agent", "ai", { domain: "computing", year: 2024, status: "alive", complexity: 10, prereqs: ["Large language model"], rarity: "uncommon" }],
  ["DALL-E", "ai", { domain: "computing", year: 2021, status: "alive", complexity: 10, prereqs: ["Transformer (deep learning architecture)", "Digital camera"], rarity: "uncommon" }],
  ["Retrieval-augmented generation", "ai", { domain: "computing", year: 2020, status: "alive", complexity: 9, prereqs: ["Large language model", "World Wide Web"], rarity: "uncommon" }],
  ["Gallium nitride power device", "ai", { domain: "electronics", year: 2010, status: "alive", complexity: 8, prereqs: ["MOSFET", "Power inverter"], rarity: "uncommon" }],
  ["Graphene", "ai", { domain: "materials", year: 2004, status: "alive", complexity: 8, prereqs: ["Alchemy", "Microscope"], rarity: "rare" }],
  ["Gorilla Glass", "ai", { domain: "materials", year: 2007, status: "alive", complexity: 7, prereqs: ["Float glass", "Alchemy"], rarity: "uncommon" }],
  ["Extreme ultraviolet lithography", "ai", { domain: "materials", year: 2019, status: "alive", complexity: 10, prereqs: ["Photolithography", "Laser"], rarity: "rare" }],
  ["Aerogel", "ai", { domain: "materials", year: 2011, status: "alive", complexity: 7, prereqs: ["Fiberglass", "Epoxy"], rarity: "uncommon" }],
  ["Electric vehicle", "ai", { domain: "transportation", year: 2012, status: "alive", complexity: 8, prereqs: ["Lithium-ion battery", "Electric motor", "Microprocessor"], rarity: "uncommon" }],
  ["Unmanned aerial vehicle", "ai", { domain: "transportation", year: 2010, status: "alive", complexity: 7, prereqs: ["Helicopter", "Microprocessor", "Global Positioning System"], rarity: "uncommon" }],
  ["MRNA vaccine", "ai", { domain: "medicine", year: 2020, status: "alive", complexity: 9, prereqs: ["Vaccination", "Genetic engineering"], rarity: "rare" }],
  ["Quantum computing", "ai", { domain: "computing", year: 2019, status: "alive", complexity: 10, prereqs: ["Integrated circuit", "Laser", "Calculus"], rarity: "rare" }],
  ["5G", "ai", { domain: "communication", year: 2019, status: "alive", complexity: 8, prereqs: ["Mobile phone", "Optical fiber"], rarity: "uncommon" }],
  ["Augmented reality", "ai", { domain: "optics", year: 2016, status: "alive", complexity: 8, prereqs: ["Smartphone", "Deep learning"], rarity: "uncommon" }],
  ["Nuclear fusion", "ai", { domain: "energy", year: 2022, status: "alive", complexity: 10, prereqs: ["Nuclear power", "Laser"], rarity: "rare" }],
  ["Reusable rocket", "ai", { domain: "transportation", year: 2015, status: "alive", complexity: 9, prereqs: ["Rocket", "Microprocessor"], rarity: "uncommon" }],
  ["Brain-computer interface", "ai", { domain: "medicine", year: 2024, status: "alive", complexity: 10, prereqs: ["Deep learning", "MRI"], rarity: "rare" }],
  ["Autonomous robot", "ai", { domain: "computing", year: 2024, status: "alive", complexity: 9, prereqs: ["Robotics", "Deep learning"], rarity: "uncommon" }],
  ["Artificial general intelligence", "ai", { domain: "computing", year: 2025, status: "alive", complexity: 10, prereqs: ["Intelligent agent", "Quantum computing"], rarity: "legendary" }],
];
