/**
 * Yum ingredient pool — raw ingredients only, no prepared dishes.
 * Every entry is a single food item you'd buy, grow, or forage.
 * Categories map to Wikipedia's food classification.
 *
 * Stats themed for food:
 *   ATK = Flavor intensity
 *   DEF = Shelf stability
 *   SPC = Uniqueness / cultural significance
 *   SPD = Prep speed
 *   HP  = Satiety / filling power
 *
 * Rarity: 45% common, 30% uncommon, 15% rare, 10% legendary
 */

export const FOOD_CATEGORIES = {
  FRUIT:     { name: "Fruits",          color: "#e74c3c", icon: "🍎" },
  VEGETABLE: { name: "Vegetables",      color: "#27ae60", icon: "🥦" },
  GRAIN:     { name: "Grains & Flour",  color: "#d4a017", icon: "🌾" },
  DAIRY:     { name: "Dairy & Eggs",    color: "#f5f0cd", icon: "🧀" },
  MEAT:      { name: "Meat & Poultry",  color: "#c0392b", icon: "🥩" },
  SEAFOOD:   { name: "Seafood",         color: "#2980b9", icon: "🐟" },
  OIL:       { name: "Oils & Fats",     color: "#d4a017", icon: "🫒" },
  SPICE:     { name: "Herbs & Spices",  color: "#8e44ad", icon: "🌿" },
  CONDIMENT: { name: "Ferments & Sauces", color: "#a0522d", icon: "🫙" },
  SWEET:     { name: "Sweeteners",      color: "#e91e8c", icon: "🍯" },
  LEGUME:    { name: "Legumes & Nuts",  color: "#795548", icon: "🥜" },
  BEVERAGE:  { name: "Beverages",       color: "#3498db", icon: "🍵" },
};

// seeded stat generator for consistency
function s(seed) {
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (Math.imul(31, h) + seed.charCodeAt(i)) | 0;
  const m = (off) => {
    h = (h + 0x6d2b79f5 + off) | 0;
    let t = Math.imul(h ^ (h >>> 15), 1 | h);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
  return {
    atk: Math.max(5, Math.min(99, Math.round(m(1) * 94 + 5))),
    def: Math.max(5, Math.min(99, Math.round(m(2) * 94 + 5))),
    spc: Math.max(5, Math.min(99, Math.round(m(3) * 94 + 5))),
    spd: Math.max(5, Math.min(99, Math.round(m(4) * 94 + 5))),
    hp:  Math.max(100, Math.min(999, Math.round(m(5) * 899 + 100))),
  };
}

function r(seed) {
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (Math.imul(31, h) + seed.charCodeAt(i)) | 0;
  h = (h + 0x9e3779b9) | 0;
  let t = Math.imul(h ^ (h >>> 15), 1 | h);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  const v = ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  if (v < 0.45) return "common";
  if (v < 0.75) return "uncommon";
  if (v < 0.90) return "rare";
  return "legendary";
}

function f(title, cat) {
  const stats = s(title);
  stats.rarity = r(title);
  return [title, cat, stats];
}

export const FOOD_POOL = [
  // ══════════════════════════════════════════════════════════
  // FRUITS — 100
  // ══════════════════════════════════════════════════════════
  f("Apple", "FRUIT"),
  f("Banana", "FRUIT"),
  f("Orange", "FRUIT"),
  f("Mango", "FRUIT"),
  f("Pineapple", "FRUIT"),
  f("Strawberry", "FRUIT"),
  f("Blueberry", "FRUIT"),
  f("Raspberry", "FRUIT"),
  f("Blackberry", "FRUIT"),
  f("Cherry", "FRUIT"),
  f("Grape", "FRUIT"),
  f("Watermelon", "FRUIT"),
  f("Cantaloupe", "FRUIT"),
  f("Honeydew", "FRUIT"),
  f("Peach", "FRUIT"),
  f("Plum", "FRUIT"),
  f("Apricot", "FRUIT"),
  f("Nectarine", "FRUIT"),
  f("Pomegranate", "FRUIT"),
  f("Fig", "FRUIT"),
  f("Date (fruit)", "FRUIT"),
  f("Papaya", "FRUIT"),
  f("Guava", "FRUIT"),
  f("Passion fruit", "FRUIT"),
  f("Lychee", "FRUIT"),
  f("Dragon fruit", "FRUIT"),
  f("Kiwifruit", "FRUIT"),
  f("Persimmon", "FRUIT"),
  f("Jackfruit", "FRUIT"),
  f("Durian", "FRUIT"),
  f("Starfruit", "FRUIT"),
  f("Rambutan", "FRUIT"),
  f("Mangosteen", "FRUIT"),
  f("Coconut", "FRUIT"),
  f("Cranberry", "FRUIT"),
  f("Grapefruit", "FRUIT"),
  f("Lemon", "FRUIT"),
  f("Lime (fruit)", "FRUIT"),
  f("Tangerine", "FRUIT"),
  f("Kumquat", "FRUIT"),
  f("Clementine", "FRUIT"),
  f("Avocado", "FRUIT"),
  f("Plantain", "FRUIT"),
  f("Quince", "FRUIT"),
  f("Tamarind", "FRUIT"),
  f("Soursop", "FRUIT"),
  f("Breadfruit", "FRUIT"),
  f("Mulberry", "FRUIT"),
  f("Gooseberry", "FRUIT"),
  f("Boysenberry", "FRUIT"),
  f("Cherimoya", "FRUIT"),
  f("Açaí", "FRUIT"),
  f("Feijoa", "FRUIT"),
  f("Sapodilla", "FRUIT"),
  f("Longan", "FRUIT"),
  f("Cactus pear", "FRUIT"),
  f("Finger lime", "FRUIT"),
  f("Yuzu", "FRUIT"),
  f("Pomelo", "FRUIT"),
  f("Blood orange", "FRUIT"),
  f("Bergamot orange", "FRUIT"),
  f("Damson", "FRUIT"),
  f("Medlar", "FRUIT"),
  f("Pawpaw", "FRUIT"),
  f("Salak", "FRUIT"),
  f("Jabuticaba", "FRUIT"),
  f("Ackee", "FRUIT"),
  f("Carambola", "FRUIT"),
  f("Physalis", "FRUIT"),
  f("Currant", "FRUIT"),
  f("Elderberry", "FRUIT"),
  f("Huckleberry", "FRUIT"),
  f("Bilberry", "FRUIT"),
  f("Lingonberry", "FRUIT"),
  f("Cloudberry", "FRUIT"),
  f("Loganberry", "FRUIT"),
  f("Cempedak", "FRUIT"),
  f("Noni", "FRUIT"),
  f("Cupuaçu", "FRUIT"),
  f("Lucuma", "FRUIT"),
  f("Pear", "FRUIT"),
  f("Olive", "FRUIT"),
  f("Tomato", "FRUIT"),
  f("Jujube", "FRUIT"),
  f("Loquat", "FRUIT"),
  f("Calamansi", "FRUIT"),
  f("Sudachi", "FRUIT"),
  f("Makrut lime", "FRUIT"),
  f("Satsuma", "FRUIT"),
  f("Tangelo", "FRUIT"),
  f("Meyer lemon", "FRUIT"),
  f("Key lime", "FRUIT"),
  f("Ugli fruit", "FRUIT"),
  f("Miracle fruit", "FRUIT"),
  f("Mamey sapote", "FRUIT"),
  f("Canistel", "FRUIT"),
  f("Rollinia", "FRUIT"),
  f("Babaco", "FRUIT"),
  f("Pepino", "FRUIT"),
  f("Buddha's hand", "FRUIT"),

  // ══════════════════════════════════════════════════════════
  // VEGETABLES — 110
  // ══════════════════════════════════════════════════════════
  f("Potato", "VEGETABLE"),
  f("Onion", "VEGETABLE"),
  f("Garlic", "VEGETABLE"),
  f("Carrot", "VEGETABLE"),
  f("Broccoli", "VEGETABLE"),
  f("Cauliflower", "VEGETABLE"),
  f("Spinach", "VEGETABLE"),
  f("Kale", "VEGETABLE"),
  f("Lettuce", "VEGETABLE"),
  f("Cabbage", "VEGETABLE"),
  f("Brussels sprout", "VEGETABLE"),
  f("Asparagus", "VEGETABLE"),
  f("Artichoke", "VEGETABLE"),
  f("Celery", "VEGETABLE"),
  f("Cucumber", "VEGETABLE"),
  f("Zucchini", "VEGETABLE"),
  f("Eggplant", "VEGETABLE"),
  f("Bell pepper", "VEGETABLE"),
  f("Radish", "VEGETABLE"),
  f("Turnip", "VEGETABLE"),
  f("Beetroot", "VEGETABLE"),
  f("Sweet potato", "VEGETABLE"),
  f("Yam (vegetable)", "VEGETABLE"),
  f("Pumpkin", "VEGETABLE"),
  f("Butternut squash", "VEGETABLE"),
  f("Leek", "VEGETABLE"),
  f("Fennel", "VEGETABLE"),
  f("Bok choy", "VEGETABLE"),
  f("Watercress", "VEGETABLE"),
  f("Arugula", "VEGETABLE"),
  f("Endive", "VEGETABLE"),
  f("Radicchio", "VEGETABLE"),
  f("Kohlrabi", "VEGETABLE"),
  f("Daikon", "VEGETABLE"),
  f("Okra", "VEGETABLE"),
  f("Taro", "VEGETABLE"),
  f("Cassava", "VEGETABLE"),
  f("Jicama", "VEGETABLE"),
  f("Chayote", "VEGETABLE"),
  f("Bamboo shoot", "VEGETABLE"),
  f("Water chestnut", "VEGETABLE"),
  f("Lotus root", "VEGETABLE"),
  f("Rhubarb", "VEGETABLE"),
  f("Swiss chard", "VEGETABLE"),
  f("Collard greens", "VEGETABLE"),
  f("Mustard greens", "VEGETABLE"),
  f("Rutabaga", "VEGETABLE"),
  f("Parsnip", "VEGETABLE"),
  f("Celeriac", "VEGETABLE"),
  f("Sunchoke", "VEGETABLE"),
  f("Konjac", "VEGETABLE"),
  f("Moringa", "VEGETABLE"),
  f("Nopales", "VEGETABLE"),
  f("Hearts of palm", "VEGETABLE"),
  f("Fiddlehead fern", "VEGETABLE"),
  f("Samphire", "VEGETABLE"),
  f("Romanesco broccoli", "VEGETABLE"),
  f("Rapini", "VEGETABLE"),
  f("Shallot", "VEGETABLE"),
  f("Scallion", "VEGETABLE"),
  f("Chive", "VEGETABLE"),
  f("Ramp (plant)", "VEGETABLE"),
  f("Chinese cabbage", "VEGETABLE"),
  f("Mizuna", "VEGETABLE"),
  f("Tatsoi", "VEGETABLE"),
  f("Kai-lan", "VEGETABLE"),
  f("Dulse", "VEGETABLE"),
  f("Kelp", "VEGETABLE"),
  f("Wakame", "VEGETABLE"),
  f("Nori", "VEGETABLE"),
  f("Kombu", "VEGETABLE"),
  f("Broccolini", "VEGETABLE"),
  f("Delicata squash", "VEGETABLE"),
  f("Acorn squash", "VEGETABLE"),
  f("Spaghetti squash", "VEGETABLE"),
  f("Kabocha", "VEGETABLE"),
  f("Bitter melon", "VEGETABLE"),
  f("Snake gourd", "VEGETABLE"),
  f("Bottle gourd", "VEGETABLE"),
  f("Wax gourd", "VEGETABLE"),
  f("Corn", "VEGETABLE"),
  f("Mushroom", "VEGETABLE"),
  f("Shiitake", "VEGETABLE"),
  f("Portobello mushroom", "VEGETABLE"),
  f("Oyster mushroom", "VEGETABLE"),
  f("Enoki mushroom", "VEGETABLE"),
  f("Chanterelle", "VEGETABLE"),
  f("Morel", "VEGETABLE"),
  f("Truffle", "VEGETABLE"),
  f("Porcini", "VEGETABLE"),
  f("Maitake", "VEGETABLE"),
  f("King trumpet mushroom", "VEGETABLE"),
  f("Lion's mane mushroom", "VEGETABLE"),
  f("Black garlic", "VEGETABLE"),
  f("Horseradish", "VEGETABLE"),
  f("Wasabi", "VEGETABLE"),
  f("Ginger", "VEGETABLE"),
  f("Galangal", "VEGETABLE"),
  f("Lemongrass", "VEGETABLE"),
  f("Turmeric", "VEGETABLE"),
  f("Cress", "VEGETABLE"),
  f("Purslane", "VEGETABLE"),
  f("Sorrel", "VEGETABLE"),
  f("Dandelion greens", "VEGETABLE"),
  f("Mâche", "VEGETABLE"),
  f("Chicory", "VEGETABLE"),
  f("Cardoon", "VEGETABLE"),
  f("Nopal", "VEGETABLE"),
  f("Chili pepper", "VEGETABLE"),
  f("Jalapeño", "VEGETABLE"),
  f("Habanero", "VEGETABLE"),
  f("Green bean", "VEGETABLE"),
  f("Snow pea", "VEGETABLE"),
  f("Sugar snap pea", "VEGETABLE"),
  f("Garden pea", "VEGETABLE"),

  // ══════════════════════════════════════════════════════════
  // GRAINS & FLOUR — 50
  // ══════════════════════════════════════════════════════════
  f("Rice", "GRAIN"),
  f("Wheat", "GRAIN"),
  f("Oat", "GRAIN"),
  f("Barley", "GRAIN"),
  f("Quinoa", "GRAIN"),
  f("Millet", "GRAIN"),
  f("Sorghum", "GRAIN"),
  f("Couscous", "GRAIN"),
  f("Polenta", "GRAIN"),
  f("Bulgur", "GRAIN"),
  f("Farro", "GRAIN"),
  f("Amaranth (grain)", "GRAIN"),
  f("Teff", "GRAIN"),
  f("Spelt", "GRAIN"),
  f("Freekeh", "GRAIN"),
  f("Kamut", "GRAIN"),
  f("Buckwheat", "GRAIN"),
  f("Wild rice", "GRAIN"),
  f("Jasmine rice", "GRAIN"),
  f("Basmati rice", "GRAIN"),
  f("Arborio rice", "GRAIN"),
  f("Sticky rice", "GRAIN"),
  f("Cornmeal", "GRAIN"),
  f("Semolina", "GRAIN"),
  f("Tapioca", "GRAIN"),
  f("Bread", "GRAIN"),
  f("Sourdough", "GRAIN"),
  f("Tortilla", "GRAIN"),
  f("Pita", "GRAIN"),
  f("Naan", "GRAIN"),
  f("Flatbread", "GRAIN"),
  f("Rye bread", "GRAIN"),
  f("Pasta", "GRAIN"),
  f("Spaghetti", "GRAIN"),
  f("Udon", "GRAIN"),
  f("Soba", "GRAIN"),
  f("Rice noodles", "GRAIN"),
  f("Egg noodle", "GRAIN"),
  f("Vermicelli", "GRAIN"),
  f("Orecchiette", "GRAIN"),
  f("Penne", "GRAIN"),
  f("Fettuccine", "GRAIN"),
  f("Rigatoni", "GRAIN"),
  f("Orzo", "GRAIN"),
  f("Rice flour", "GRAIN"),
  f("Almond flour", "GRAIN"),
  f("Chickpea flour", "GRAIN"),
  f("Coconut flour", "GRAIN"),
  f("Cornstarch", "GRAIN"),
  f("Arrowroot", "GRAIN"),
  f("All-purpose flour", "GRAIN"),

  // ══════════════════════════════════════════════════════════
  // DAIRY & EGGS — 65
  // ══════════════════════════════════════════════════════════
  f("Cheddar cheese", "DAIRY"),
  f("Mozzarella", "DAIRY"),
  f("Parmesan cheese", "DAIRY"),
  f("Brie", "DAIRY"),
  f("Camembert", "DAIRY"),
  f("Gouda cheese", "DAIRY"),
  f("Gruyère cheese", "DAIRY"),
  f("Roquefort", "DAIRY"),
  f("Gorgonzola", "DAIRY"),
  f("Feta", "DAIRY"),
  f("Ricotta", "DAIRY"),
  f("Mascarpone", "DAIRY"),
  f("Cottage cheese", "DAIRY"),
  f("Cream cheese", "DAIRY"),
  f("Stilton cheese", "DAIRY"),
  f("Manchego cheese", "DAIRY"),
  f("Emmental cheese", "DAIRY"),
  f("Halloumi", "DAIRY"),
  f("Paneer", "DAIRY"),
  f("Provolone", "DAIRY"),
  f("Pecorino Romano", "DAIRY"),
  f("Monterey Jack", "DAIRY"),
  f("Butter", "DAIRY"),
  f("Yogurt", "DAIRY"),
  f("Ghee", "DAIRY"),
  f("Kefir", "DAIRY"),
  f("Clotted cream", "DAIRY"),
  f("Quark (dairy product)", "DAIRY"),
  f("Labneh", "DAIRY"),
  f("Époisses", "DAIRY"),
  f("Taleggio", "DAIRY"),
  f("Fontina", "DAIRY"),
  f("Asiago cheese", "DAIRY"),
  f("Havarti", "DAIRY"),
  f("Raclette", "DAIRY"),
  f("Comté cheese", "DAIRY"),
  f("Reblochon", "DAIRY"),
  f("Burrata", "DAIRY"),
  f("Scamorza", "DAIRY"),
  f("Queso fresco", "DAIRY"),
  f("Oaxaca cheese", "DAIRY"),
  f("Cotija cheese", "DAIRY"),
  f("Skyr", "DAIRY"),
  f("Dulce de leche", "DAIRY"),
  f("Condensed milk", "DAIRY"),
  f("Heavy cream", "DAIRY"),
  f("Sour cream", "DAIRY"),
  f("Crème fraîche", "DAIRY"),
  f("Buttermilk", "DAIRY"),
  f("Whey", "DAIRY"),
  f("Milk", "DAIRY"),
  f("Goat milk", "DAIRY"),
  f("Sheep milk", "DAIRY"),
  f("Egg (food)", "DAIRY"),
  f("Chicken egg", "DAIRY"),
  f("Duck egg", "DAIRY"),
  f("Quail egg", "DAIRY"),
  f("Egg yolk", "DAIRY"),
  f("Egg white", "DAIRY"),
  f("Goat cheese", "DAIRY"),
  f("Blue cheese", "DAIRY"),

  // ══════════════════════════════════════════════════════════
  // MEAT & POULTRY — 55
  // ══════════════════════════════════════════════════════════
  f("Beef", "MEAT"),
  f("Pork", "MEAT"),
  f("Chicken (food)", "MEAT"),
  f("Lamb and mutton", "MEAT"),
  f("Turkey (food)", "MEAT"),
  f("Duck (food)", "MEAT"),
  f("Venison", "MEAT"),
  f("Rabbit (food)", "MEAT"),
  f("Goat meat", "MEAT"),
  f("Bison", "MEAT"),
  f("Bacon", "MEAT"),
  f("Ham", "MEAT"),
  f("Salami", "MEAT"),
  f("Prosciutto", "MEAT"),
  f("Chorizo", "MEAT"),
  f("Sausage", "MEAT"),
  f("Bratwurst", "MEAT"),
  f("Pepperoni", "MEAT"),
  f("Pastrami", "MEAT"),
  f("Corned beef", "MEAT"),
  f("Jerky", "MEAT"),
  f("Mortadella", "MEAT"),
  f("Bresaola", "MEAT"),
  f("Pancetta", "MEAT"),
  f("Guanciale", "MEAT"),
  f("Steak", "MEAT"),
  f("Wagyu", "MEAT"),
  f("Biltong", "MEAT"),
  f("Foie gras", "MEAT"),
  f("Pâté", "MEAT"),
  f("Rillettes", "MEAT"),
  f("Nduja", "MEAT"),
  f("Jamón ibérico", "MEAT"),
  f("Coppa (meat)", "MEAT"),
  f("Soppressata", "MEAT"),
  f("Longaniza", "MEAT"),
  f("Kielbasa", "MEAT"),
  f("Andouille", "MEAT"),
  f("Merguez", "MEAT"),
  f("Lap cheong", "MEAT"),
  f("Droëwors", "MEAT"),
  f("Lard", "MEAT"),
  f("Tallow", "MEAT"),
  f("Bone marrow", "MEAT"),
  f("Offal", "MEAT"),
  f("Liver (food)", "MEAT"),
  f("Sweetbread", "MEAT"),
  f("Tripe", "MEAT"),
  f("Tongue (food)", "MEAT"),
  f("Quail", "MEAT"),
  f("Pheasant", "MEAT"),
  f("Goose", "MEAT"),
  f("Elk meat", "MEAT"),
  f("Wild boar", "MEAT"),
  f("Ostrich meat", "MEAT"),

  // ══════════════════════════════════════════════════════════
  // SEAFOOD — 70
  // ══════════════════════════════════════════════════════════
  f("Salmon", "SEAFOOD"),
  f("Tuna", "SEAFOOD"),
  f("Shrimp (food)", "SEAFOOD"),
  f("Lobster", "SEAFOOD"),
  f("Crab", "SEAFOOD"),
  f("Oyster", "SEAFOOD"),
  f("Mussel", "SEAFOOD"),
  f("Clam", "SEAFOOD"),
  f("Scallop", "SEAFOOD"),
  f("Squid (food)", "SEAFOOD"),
  f("Octopus", "SEAFOOD"),
  f("Cod", "SEAFOOD"),
  f("Halibut", "SEAFOOD"),
  f("Sardine", "SEAFOOD"),
  f("Anchovy", "SEAFOOD"),
  f("Mackerel", "SEAFOOD"),
  f("Swordfish", "SEAFOOD"),
  f("Trout", "SEAFOOD"),
  f("Sea bass", "SEAFOOD"),
  f("Tilapia", "SEAFOOD"),
  f("Catfish", "SEAFOOD"),
  f("Crayfish", "SEAFOOD"),
  f("Sea urchin", "SEAFOOD"),
  f("Caviar", "SEAFOOD"),
  f("Abalone", "SEAFOOD"),
  f("Geoduck", "SEAFOOD"),
  f("Conch", "SEAFOOD"),
  f("Whelk", "SEAFOOD"),
  f("Langoustine", "SEAFOOD"),
  f("King crab", "SEAFOOD"),
  f("Snow crab", "SEAFOOD"),
  f("Dungeness crab", "SEAFOOD"),
  f("Monkfish", "SEAFOOD"),
  f("Grouper", "SEAFOOD"),
  f("Red snapper", "SEAFOOD"),
  f("Mahi-mahi", "SEAFOOD"),
  f("Barramundi", "SEAFOOD"),
  f("Branzino", "SEAFOOD"),
  f("Dover sole", "SEAFOOD"),
  f("Turbot", "SEAFOOD"),
  f("John Dory", "SEAFOOD"),
  f("Arctic char", "SEAFOOD"),
  f("Herring", "SEAFOOD"),
  f("Eel (food)", "SEAFOOD"),
  f("Ikura", "SEAFOOD"),
  f("Tobiko", "SEAFOOD"),
  f("Surimi", "SEAFOOD"),
  f("Bonito", "SEAFOOD"),
  f("Yellowtail", "SEAFOOD"),
  f("Wahoo (fish)", "SEAFOOD"),
  f("Pompano", "SEAFOOD"),
  f("Skate (fish)", "SEAFOOD"),
  f("Haddock", "SEAFOOD"),
  f("Pollock", "SEAFOOD"),
  f("Plaice", "SEAFOOD"),
  f("Pike (fish)", "SEAFOOD"),
  f("Perch", "SEAFOOD"),
  f("Walleye", "SEAFOOD"),
  f("Crawfish", "SEAFOOD"),
  f("Prawn", "SEAFOOD"),
  f("Cockle (bivalve)", "SEAFOOD"),
  f("Razor clam", "SEAFOOD"),
  f("Cuttlefish", "SEAFOOD"),
  f("Dried shrimp", "SEAFOOD"),
  f("Katsuobushi", "SEAFOOD"),
  f("Dried squid", "SEAFOOD"),
  f("Fish roe", "SEAFOOD"),
  f("Smelt (fish)", "SEAFOOD"),
  f("Whitebait", "SEAFOOD"),
  f("Sprat", "SEAFOOD"),
  f("Smoked salmon", "SEAFOOD"),

  // ══════════════════════════════════════════════════════════
  // OILS & FATS — 25
  // ══════════════════════════════════════════════════════════
  f("Olive oil", "OIL"),
  f("Sesame oil", "OIL"),
  f("Coconut oil", "OIL"),
  f("Peanut oil", "OIL"),
  f("Sunflower oil", "OIL"),
  f("Canola oil", "OIL"),
  f("Avocado oil", "OIL"),
  f("Walnut oil", "OIL"),
  f("Grapeseed oil", "OIL"),
  f("Flaxseed oil", "OIL"),
  f("Truffle oil", "OIL"),
  f("Chili oil", "OIL"),
  f("Palm oil", "OIL"),
  f("Mustard oil", "OIL"),
  f("Perilla oil", "OIL"),
  f("Hazelnut oil", "OIL"),
  f("Macadamia oil", "OIL"),
  f("Rice bran oil", "OIL"),
  f("Schmaltz", "OIL"),
  f("Duck fat", "OIL"),
  f("Suet", "OIL"),
  f("Cocoa butter", "OIL"),
  f("Shea butter", "OIL"),
  f("Margarine", "OIL"),
  f("Shortening", "OIL"),

  // ══════════════════════════════════════════════════════════
  // HERBS & SPICES — 90
  // ══════════════════════════════════════════════════════════
  f("Basil", "SPICE"),
  f("Oregano", "SPICE"),
  f("Thyme", "SPICE"),
  f("Rosemary", "SPICE"),
  f("Sage", "SPICE"),
  f("Parsley", "SPICE"),
  f("Cilantro", "SPICE"),
  f("Dill", "SPICE"),
  f("Mint", "SPICE"),
  f("Tarragon", "SPICE"),
  f("Bay leaf", "SPICE"),
  f("Lavender", "SPICE"),
  f("Marjoram", "SPICE"),
  f("Chervil", "SPICE"),
  f("Epazote", "SPICE"),
  f("Lemon balm", "SPICE"),
  f("Savory (plant)", "SPICE"),
  f("Lovage", "SPICE"),
  f("Curry leaf", "SPICE"),
  f("Pandan leaf", "SPICE"),
  f("Shiso", "SPICE"),
  f("Black pepper", "SPICE"),
  f("Cinnamon", "SPICE"),
  f("Cumin", "SPICE"),
  f("Coriander", "SPICE"),
  f("Paprika", "SPICE"),
  f("Saffron", "SPICE"),
  f("Vanilla", "SPICE"),
  f("Nutmeg", "SPICE"),
  f("Cardamom", "SPICE"),
  f("Star anise", "SPICE"),
  f("Clove", "SPICE"),
  f("Fenugreek", "SPICE"),
  f("Asafoetida", "SPICE"),
  f("Szechuan pepper", "SPICE"),
  f("Grains of paradise", "SPICE"),
  f("Long pepper", "SPICE"),
  f("Annatto", "SPICE"),
  f("Sumac", "SPICE"),
  f("Za'atar", "SPICE"),
  f("Ras el hanout", "SPICE"),
  f("Berbere", "SPICE"),
  f("Duqqa", "SPICE"),
  f("Garam masala", "SPICE"),
  f("Five-spice powder", "SPICE"),
  f("Herbes de Provence", "SPICE"),
  f("Italian seasoning", "SPICE"),
  f("Allspice", "SPICE"),
  f("Juniper berry", "SPICE"),
  f("Mace (spice)", "SPICE"),
  f("Caraway", "SPICE"),
  f("Celery seed", "SPICE"),
  f("Fennel seed", "SPICE"),
  f("Mustard seed", "SPICE"),
  f("Poppy seed", "SPICE"),
  f("Nigella seed", "SPICE"),
  f("Anise", "SPICE"),
  f("Dill seed", "SPICE"),
  f("Coriander seed", "SPICE"),
  f("Cumin seed", "SPICE"),
  f("Togarashi", "SPICE"),
  f("Gochugaru", "SPICE"),
  f("Aleppo pepper", "SPICE"),
  f("Urfa pepper", "SPICE"),
  f("Chipotle", "SPICE"),
  f("Ancho chile", "SPICE"),
  f("Guajillo chile", "SPICE"),
  f("Pasilla chile", "SPICE"),
  f("Cayenne pepper", "SPICE"),
  f("Crushed red pepper", "SPICE"),
  f("Smoked paprika", "SPICE"),
  f("White pepper", "SPICE"),
  f("Pink peppercorn", "SPICE"),
  f("Green peppercorn", "SPICE"),
  f("Tellicherry pepper", "SPICE"),
  f("Cubeb", "SPICE"),
  f("Sassafras", "SPICE"),
  f("Licorice root", "SPICE"),
  f("Tonka bean", "SPICE"),
  f("Mahlab", "SPICE"),
  f("Kaffir lime leaf", "SPICE"),
  f("Lemon verbena", "SPICE"),
  f("Rose water", "SPICE"),
  f("Orange blossom water", "SPICE"),
  f("Dried oregano", "SPICE"),
  f("Dried thyme", "SPICE"),
  f("Dried basil", "SPICE"),
  f("Dried rosemary", "SPICE"),
  f("Garlic powder", "SPICE"),
  f("Onion powder", "SPICE"),
  f("Salt", "SPICE"),
  f("Sea salt", "SPICE"),
  f("Old Bay seasoning", "SPICE"),

  // ══════════════════════════════════════════════════════════
  // FERMENTS & SAUCES — 55
  // ══════════════════════════════════════════════════════════
  f("Soy sauce", "CONDIMENT"),
  f("Fish sauce", "CONDIMENT"),
  f("Oyster sauce", "CONDIMENT"),
  f("Hoisin sauce", "CONDIMENT"),
  f("Worcestershire sauce", "CONDIMENT"),
  f("Tabasco sauce", "CONDIMENT"),
  f("Sriracha", "CONDIMENT"),
  f("Ketchup", "CONDIMENT"),
  f("Mustard (condiment)", "CONDIMENT"),
  f("Vinegar", "CONDIMENT"),
  f("Balsamic vinegar", "CONDIMENT"),
  f("Rice vinegar", "CONDIMENT"),
  f("Apple cider vinegar", "CONDIMENT"),
  f("Red wine vinegar", "CONDIMENT"),
  f("Sherry vinegar", "CONDIMENT"),
  f("Miso", "CONDIMENT"),
  f("Doenjang", "CONDIMENT"),
  f("Gochujang", "CONDIMENT"),
  f("Tahini", "CONDIMENT"),
  f("Mirin", "CONDIMENT"),
  f("Ponzu", "CONDIMENT"),
  f("Yuzu kosho", "CONDIMENT"),
  f("XO sauce", "CONDIMENT"),
  f("Black bean sauce", "CONDIMENT"),
  f("Sambal", "CONDIMENT"),
  f("Harissa", "CONDIMENT"),
  f("Dijon mustard", "CONDIMENT"),
  f("Mole poblano", "CONDIMENT"),
  f("Adobo (sauce)", "CONDIMENT"),
  f("Aji amarillo", "CONDIMENT"),
  f("Chili crisp", "CONDIMENT"),
  f("Ajvar", "CONDIMENT"),
  f("Kimchi", "CONDIMENT"),
  f("Sauerkraut", "CONDIMENT"),
  f("Pickled ginger", "CONDIMENT"),
  f("Pickle", "CONDIMENT"),
  f("Caper", "CONDIMENT"),
  f("Anchovy paste", "CONDIMENT"),
  f("Tomato paste", "CONDIMENT"),
  f("Tomato sauce", "CONDIMENT"),
  f("Coconut milk", "CONDIMENT"),
  f("Coconut cream", "CONDIMENT"),
  f("Tamarind paste", "CONDIMENT"),
  f("Pomegranate molasses", "CONDIMENT"),
  f("Date syrup", "CONDIMENT"),
  f("Furikake", "CONDIMENT"),
  f("Nutritional yeast", "CONDIMENT"),
  f("Brewer's yeast", "CONDIMENT"),
  f("Malt extract", "CONDIMENT"),
  f("Dashi", "CONDIMENT"),
  f("Bouillon", "CONDIMENT"),
  f("Gelatin", "CONDIMENT"),
  f("Agar", "CONDIMENT"),
  f("Pectin", "CONDIMENT"),
  f("Rennet", "CONDIMENT"),
  f("Mayonnaise", "CONDIMENT"),
  f("Pesto", "CONDIMENT"),
  f("Chimichurri", "CONDIMENT"),
  f("Hot sauce", "CONDIMENT"),
  f("White wine", "CONDIMENT"),
  f("Red wine", "CONDIMENT"),

  // ══════════════════════════════════════════════════════════
  // SWEETENERS — 25
  // ══════════════════════════════════════════════════════════
  f("Sugar", "SWEET"),
  f("Brown sugar", "SWEET"),
  f("Powdered sugar", "SWEET"),
  f("Muscovado", "SWEET"),
  f("Demerara sugar", "SWEET"),
  f("Palm sugar", "SWEET"),
  f("Jaggery", "SWEET"),
  f("Honey", "SWEET"),
  f("Maple syrup", "SWEET"),
  f("Agave nectar", "SWEET"),
  f("Molasses", "SWEET"),
  f("Corn syrup", "SWEET"),
  f("Golden syrup", "SWEET"),
  f("Treacle", "SWEET"),
  f("Stevia", "SWEET"),
  f("Monk fruit", "SWEET"),
  f("Chocolate", "SWEET"),
  f("Cocoa powder", "SWEET"),
  f("Cacao nib", "SWEET"),
  f("White chocolate", "SWEET"),
  f("Dark chocolate", "SWEET"),
  f("Caramel", "SWEET"),
  f("Toffee", "SWEET"),
  f("Marzipan", "SWEET"),
  f("Malt syrup", "SWEET"),

  // ══════════════════════════════════════════════════════════
  // LEGUMES & NUTS — 65
  // ══════════════════════════════════════════════════════════
  f("Peanut", "LEGUME"),
  f("Almond", "LEGUME"),
  f("Walnut", "LEGUME"),
  f("Cashew", "LEGUME"),
  f("Pistachio", "LEGUME"),
  f("Hazelnut", "LEGUME"),
  f("Macadamia nut", "LEGUME"),
  f("Pecan", "LEGUME"),
  f("Brazil nut", "LEGUME"),
  f("Pine nut", "LEGUME"),
  f("Chestnut", "LEGUME"),
  f("Chickpea", "LEGUME"),
  f("Lentil", "LEGUME"),
  f("Black bean", "LEGUME"),
  f("Kidney bean", "LEGUME"),
  f("Lima bean", "LEGUME"),
  f("Navy bean", "LEGUME"),
  f("Soybean", "LEGUME"),
  f("Edamame", "LEGUME"),
  f("Tofu", "LEGUME"),
  f("Tempeh", "LEGUME"),
  f("Mung bean", "LEGUME"),
  f("Fava bean", "LEGUME"),
  f("Pinto bean", "LEGUME"),
  f("Adzuki bean", "LEGUME"),
  f("Black-eyed pea", "LEGUME"),
  f("Split pea", "LEGUME"),
  f("Sunflower seed", "LEGUME"),
  f("Pumpkin seed", "LEGUME"),
  f("Chia seed", "LEGUME"),
  f("Flax seed", "LEGUME"),
  f("Hemp seed", "LEGUME"),
  f("Sesame seed", "LEGUME"),
  f("Lotus seed", "LEGUME"),
  f("Lupini bean", "LEGUME"),
  f("Cannellini bean", "LEGUME"),
  f("Pigeon pea", "LEGUME"),
  f("Cowpea", "LEGUME"),
  f("Peanut butter", "LEGUME"),
  f("Almond butter", "LEGUME"),
  f("Tahini paste", "LEGUME"),
  f("Coconut cream (solid)", "LEGUME"),
  f("Soy milk", "LEGUME"),
  f("Almond milk", "LEGUME"),
  f("Oat milk", "LEGUME"),
  f("Coconut water", "LEGUME"),
  f("Tiger nut", "LEGUME"),
  f("Kola nut", "LEGUME"),
  f("Breadnut", "LEGUME"),
  f("Baru nut", "LEGUME"),
  f("Sacha inchi", "LEGUME"),
  f("Watermelon seed", "LEGUME"),
  f("Poppy seed (legume)", "LEGUME"),
  f("Black sesame", "LEGUME"),
  f("White sesame", "LEGUME"),

  // ══════════════════════════════════════════════════════════
  // BEVERAGES — 30
  // ══════════════════════════════════════════════════════════
  f("Coffee", "BEVERAGE"),
  f("Tea", "BEVERAGE"),
  f("Beer", "BEVERAGE"),
  f("Wine", "BEVERAGE"),
  f("Whisky", "BEVERAGE"),
  f("Vodka", "BEVERAGE"),
  f("Rum", "BEVERAGE"),
  f("Gin", "BEVERAGE"),
  f("Tequila", "BEVERAGE"),
  f("Sake", "BEVERAGE"),
  f("Champagne", "BEVERAGE"),
  f("Cider", "BEVERAGE"),
  f("Mead", "BEVERAGE"),
  f("Absinthe", "BEVERAGE"),
  f("Matcha", "BEVERAGE"),
  f("Kombucha", "BEVERAGE"),
  f("Mezcal", "BEVERAGE"),
  f("Grappa", "BEVERAGE"),
  f("Calvados", "BEVERAGE"),
  f("Pisco", "BEVERAGE"),
  f("Soju", "BEVERAGE"),
  f("Baijiu", "BEVERAGE"),
  f("Ouzo", "BEVERAGE"),
  f("Amaretto", "BEVERAGE"),
  f("Limoncello", "BEVERAGE"),
  f("Campari", "BEVERAGE"),
  f("Vermouth", "BEVERAGE"),
  f("Pu-erh tea", "BEVERAGE"),
  f("Oolong tea", "BEVERAGE"),
  f("Rooibos", "BEVERAGE"),
];
