/**
 * Food pool for Yum — sourced from Wikipedia's "Lists of foods"
 * Categories map to Wikipedia's food classification sub-lists.
 *
 * Stats are themed for food:
 *   ATK = Flavor intensity
 *   DEF = Shelf stability
 *   SPC = Uniqueness / cultural significance
 *   SPD = Prep speed (how fast to prepare)
 *   HP  = Satiety / filling power
 *
 * Rarity: 45% common, 30% uncommon, 15% rare, 10% legendary
 */

export const FOOD_CATEGORIES = {
  FRUIT:     { name: "Fruits",             color: "#e74c3c", icon: "🍎" },
  VEGETABLE: { name: "Vegetables",         color: "#27ae60", icon: "🥦" },
  GRAIN:     { name: "Breads & Grains",    color: "#d4a017", icon: "🍞" },
  DAIRY:     { name: "Dairy & Cheese",     color: "#f5f0cd", icon: "🧀" },
  MEAT:      { name: "Meats",              color: "#c0392b", icon: "🥩" },
  SEAFOOD:   { name: "Seafood",            color: "#2980b9", icon: "🐟" },
  DESSERT:   { name: "Desserts & Sweets",  color: "#e91e8c", icon: "🍰" },
  SOUP:      { name: "Soups & Stews",      color: "#e67e22", icon: "🍲" },
  CONDIMENT: { name: "Condiments & Spices",color: "#8e44ad", icon: "🌶️" },
  BEVERAGE:  { name: "Beverages",          color: "#3498db", icon: "🍵" },
  PASTA:     { name: "Pasta & Noodles",    color: "#f39c12", icon: "🍝" },
  LEGUME:    { name: "Legumes & Nuts",     color: "#795548", icon: "🥜" },
};

// seeded stat generator for consistency
function s(seed) {
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (Math.imul(31, h) + seed.charCodeAt(i)) | 0;
  const m = (off) => {
    h = (h + 0x6d2b79f5 + off) | 0;
    let t = Math.imul(h ^ (h >>> 15), 1 | h);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
  return {
    atk: Math.max(5, Math.min(99, Math.round(m(1) * 94 + 5))),
    def: Math.max(5, Math.min(99, Math.round(m(2) * 94 + 5))),
    spc: Math.max(5, Math.min(99, Math.round(m(3) * 94 + 5))),
    spd: Math.max(5, Math.min(99, Math.round(m(4) * 94 + 5))),
    hp:  Math.max(100, Math.min(999, Math.round(m(5) * 899 + 100))),
  };
}

function r(seed) {
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (Math.imul(31, h) + seed.charCodeAt(i)) | 0;
  h = (h + 0x9e3779b9) | 0;
  let t = Math.imul(h ^ (h >>> 15), 1 | h);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  const v = ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  if (v < 0.45) return "common";
  if (v < 0.75) return "uncommon";
  if (v < 0.90) return "rare";
  return "legendary";
}

function f(title, cat) {
  const stats = s(title);
  stats.rarity = r(title);
  return [title, cat, stats];
}

// ── The Food Pool ───────────────────────────────────────────
// Sourced from Wikipedia's Lists of foods sub-articles

export const FOOD_POOL = [
  // ── Fruits ──
  f("Apple", "FRUIT"),
  f("Banana", "FRUIT"),
  f("Orange", "FRUIT"),
  f("Mango", "FRUIT"),
  f("Pineapple", "FRUIT"),
  f("Strawberry", "FRUIT"),
  f("Blueberry", "FRUIT"),
  f("Raspberry", "FRUIT"),
  f("Blackberry", "FRUIT"),
  f("Cherry", "FRUIT"),
  f("Grape", "FRUIT"),
  f("Watermelon", "FRUIT"),
  f("Cantaloupe", "FRUIT"),
  f("Honeydew", "FRUIT"),
  f("Peach", "FRUIT"),
  f("Plum", "FRUIT"),
  f("Apricot", "FRUIT"),
  f("Nectarine", "FRUIT"),
  f("Pomegranate", "FRUIT"),
  f("Fig", "FRUIT"),
  f("Date (fruit)", "FRUIT"),
  f("Papaya", "FRUIT"),
  f("Guava", "FRUIT"),
  f("Passion fruit", "FRUIT"),
  f("Lychee", "FRUIT"),
  f("Dragon fruit", "FRUIT"),
  f("Kiwifruit", "FRUIT"),
  f("Persimmon", "FRUIT"),
  f("Jackfruit", "FRUIT"),
  f("Durian", "FRUIT"),
  f("Starfruit", "FRUIT"),
  f("Rambutan", "FRUIT"),
  f("Mangosteen", "FRUIT"),
  f("Coconut", "FRUIT"),
  f("Cranberry", "FRUIT"),
  f("Grapefruit", "FRUIT"),
  f("Lemon", "FRUIT"),
  f("Lime (fruit)", "FRUIT"),
  f("Tangerine", "FRUIT"),
  f("Kumquat", "FRUIT"),
  f("Clementine", "FRUIT"),
  f("Avocado", "FRUIT"),
  f("Plantain", "FRUIT"),
  f("Quince", "FRUIT"),
  f("Tamarind", "FRUIT"),
  f("Soursop", "FRUIT"),
  f("Breadfruit", "FRUIT"),
  f("Mulberry", "FRUIT"),
  f("Gooseberry", "FRUIT"),
  f("Boysenberry", "FRUIT"),

  // ── Vegetables ──
  f("Potato", "VEGETABLE"),
  f("Tomato", "VEGETABLE"),
  f("Onion", "VEGETABLE"),
  f("Garlic", "VEGETABLE"),
  f("Carrot", "VEGETABLE"),
  f("Broccoli", "VEGETABLE"),
  f("Cauliflower", "VEGETABLE"),
  f("Spinach", "VEGETABLE"),
  f("Kale", "VEGETABLE"),
  f("Lettuce", "VEGETABLE"),
  f("Cabbage", "VEGETABLE"),
  f("Brussels sprout", "VEGETABLE"),
  f("Asparagus", "VEGETABLE"),
  f("Artichoke", "VEGETABLE"),
  f("Celery", "VEGETABLE"),
  f("Cucumber", "VEGETABLE"),
  f("Zucchini", "VEGETABLE"),
  f("Eggplant", "VEGETABLE"),
  f("Bell pepper", "VEGETABLE"),
  f("Radish", "VEGETABLE"),
  f("Turnip", "VEGETABLE"),
  f("Beetroot", "VEGETABLE"),
  f("Sweet potato", "VEGETABLE"),
  f("Yam (vegetable)", "VEGETABLE"),
  f("Pumpkin", "VEGETABLE"),
  f("Butternut squash", "VEGETABLE"),
  f("Leek", "VEGETABLE"),
  f("Fennel", "VEGETABLE"),
  f("Bok choy", "VEGETABLE"),
  f("Watercress", "VEGETABLE"),
  f("Arugula", "VEGETABLE"),
  f("Endive", "VEGETABLE"),
  f("Radicchio", "VEGETABLE"),
  f("Kohlrabi", "VEGETABLE"),
  f("Daikon", "VEGETABLE"),
  f("Okra", "VEGETABLE"),
  f("Taro", "VEGETABLE"),
  f("Cassava", "VEGETABLE"),
  f("Jicama", "VEGETABLE"),
  f("Chayote", "VEGETABLE"),
  f("Bamboo shoot", "VEGETABLE"),
  f("Water chestnut", "VEGETABLE"),
  f("Lotus root", "VEGETABLE"),
  f("Rhubarb", "VEGETABLE"),
  f("Swiss chard", "VEGETABLE"),
  f("Collard greens", "VEGETABLE"),
  f("Mustard greens", "VEGETABLE"),
  f("Rutabaga", "VEGETABLE"),
  f("Parsnip", "VEGETABLE"),
  f("Celeriac", "VEGETABLE"),

  // ── Breads & Grains ──
  f("Bread", "GRAIN"),
  f("Sourdough", "GRAIN"),
  f("Baguette", "GRAIN"),
  f("Ciabatta", "GRAIN"),
  f("Focaccia", "GRAIN"),
  f("Pita", "GRAIN"),
  f("Naan", "GRAIN"),
  f("Tortilla", "GRAIN"),
  f("Croissant", "GRAIN"),
  f("Brioche", "GRAIN"),
  f("Pumpernickel", "GRAIN"),
  f("Rye bread", "GRAIN"),
  f("Challah", "GRAIN"),
  f("Cornbread", "GRAIN"),
  f("Flatbread", "GRAIN"),
  f("Chapati", "GRAIN"),
  f("Paratha", "GRAIN"),
  f("Injera", "GRAIN"),
  f("Lavash", "GRAIN"),
  f("Pretzel", "GRAIN"),
  f("Bagel", "GRAIN"),
  f("English muffin", "GRAIN"),
  f("Rice", "GRAIN"),
  f("Wheat", "GRAIN"),
  f("Oat", "GRAIN"),
  f("Barley", "GRAIN"),
  f("Quinoa", "GRAIN"),
  f("Millet", "GRAIN"),
  f("Sorghum", "GRAIN"),
  f("Couscous", "GRAIN"),
  f("Polenta", "GRAIN"),
  f("Bulgur", "GRAIN"),
  f("Farro", "GRAIN"),
  f("Amaranth (grain)", "GRAIN"),
  f("Teff", "GRAIN"),

  // ── Dairy & Cheese ──
  f("Cheddar cheese", "DAIRY"),
  f("Mozzarella", "DAIRY"),
  f("Parmesan cheese", "DAIRY"),
  f("Brie", "DAIRY"),
  f("Camembert", "DAIRY"),
  f("Gouda cheese", "DAIRY"),
  f("Gruyère cheese", "DAIRY"),
  f("Roquefort", "DAIRY"),
  f("Gorgonzola", "DAIRY"),
  f("Feta", "DAIRY"),
  f("Ricotta", "DAIRY"),
  f("Mascarpone", "DAIRY"),
  f("Cottage cheese", "DAIRY"),
  f("Cream cheese", "DAIRY"),
  f("Stilton cheese", "DAIRY"),
  f("Manchego cheese", "DAIRY"),
  f("Emmental cheese", "DAIRY"),
  f("Halloumi", "DAIRY"),
  f("Paneer", "DAIRY"),
  f("Provolone", "DAIRY"),
  f("Pecorino Romano", "DAIRY"),
  f("Colby cheese", "DAIRY"),
  f("Monterey Jack", "DAIRY"),
  f("Butter", "DAIRY"),
  f("Yogurt", "DAIRY"),
  f("Ghee", "DAIRY"),
  f("Kefir", "DAIRY"),
  f("Clotted cream", "DAIRY"),
  f("Quark (dairy product)", "DAIRY"),
  f("Labneh", "DAIRY"),

  // ── Meats ──
  f("Beef", "MEAT"),
  f("Pork", "MEAT"),
  f("Chicken (food)", "MEAT"),
  f("Lamb and mutton", "MEAT"),
  f("Turkey (food)", "MEAT"),
  f("Duck (food)", "MEAT"),
  f("Venison", "MEAT"),
  f("Rabbit (food)", "MEAT"),
  f("Goat meat", "MEAT"),
  f("Bison", "MEAT"),
  f("Bacon", "MEAT"),
  f("Ham", "MEAT"),
  f("Salami", "MEAT"),
  f("Prosciutto", "MEAT"),
  f("Chorizo", "MEAT"),
  f("Sausage", "MEAT"),
  f("Bratwurst", "MEAT"),
  f("Pepperoni", "MEAT"),
  f("Pastrami", "MEAT"),
  f("Corned beef", "MEAT"),
  f("Jerky", "MEAT"),
  f("Mortadella", "MEAT"),
  f("Bresaola", "MEAT"),
  f("Pancetta", "MEAT"),
  f("Guanciale", "MEAT"),
  f("Hot dog", "MEAT"),
  f("Steak", "MEAT"),
  f("Kebab", "MEAT"),
  f("Fried chicken", "MEAT"),
  f("Roast chicken", "MEAT"),

  // ── Seafood ──
  f("Salmon", "SEAFOOD"),
  f("Tuna", "SEAFOOD"),
  f("Shrimp (food)", "SEAFOOD"),
  f("Lobster", "SEAFOOD"),
  f("Crab", "SEAFOOD"),
  f("Oyster", "SEAFOOD"),
  f("Mussel", "SEAFOOD"),
  f("Clam", "SEAFOOD"),
  f("Scallop", "SEAFOOD"),
  f("Squid (food)", "SEAFOOD"),
  f("Octopus", "SEAFOOD"),
  f("Cod", "SEAFOOD"),
  f("Halibut", "SEAFOOD"),
  f("Sardine", "SEAFOOD"),
  f("Anchovy", "SEAFOOD"),
  f("Mackerel", "SEAFOOD"),
  f("Swordfish", "SEAFOOD"),
  f("Trout", "SEAFOOD"),
  f("Sea bass", "SEAFOOD"),
  f("Tilapia", "SEAFOOD"),
  f("Catfish", "SEAFOOD"),
  f("Crayfish", "SEAFOOD"),
  f("Sea urchin", "SEAFOOD"),
  f("Caviar", "SEAFOOD"),
  f("Sashimi", "SEAFOOD"),
  f("Sushi", "SEAFOOD"),
  f("Fish and chips", "SEAFOOD"),
  f("Ceviche", "SEAFOOD"),
  f("Calamari", "SEAFOOD"),
  f("Smoked salmon", "SEAFOOD"),

  // ── Desserts & Sweets ──
  f("Chocolate", "DESSERT"),
  f("Ice cream", "DESSERT"),
  f("Cake", "DESSERT"),
  f("Cookie", "DESSERT"),
  f("Pie", "DESSERT"),
  f("Doughnut", "DESSERT"),
  f("Brownie", "DESSERT"),
  f("Cheesecake", "DESSERT"),
  f("Tiramisu", "DESSERT"),
  f("Crème brûlée", "DESSERT"),
  f("Panna cotta", "DESSERT"),
  f("Macaron", "DESSERT"),
  f("Éclair", "DESSERT"),
  f("Profiterole", "DESSERT"),
  f("Baklava", "DESSERT"),
  f("Mochi", "DESSERT"),
  f("Gelato", "DESSERT"),
  f("Sorbet", "DESSERT"),
  f("Fudge", "DESSERT"),
  f("Toffee", "DESSERT"),
  f("Caramel", "DESSERT"),
  f("Marzipan", "DESSERT"),
  f("Meringue", "DESSERT"),
  f("Pavlova (dessert)", "DESSERT"),
  f("Churro", "DESSERT"),
  f("Waffle", "DESSERT"),
  f("Pancake", "DESSERT"),
  f("Crêpe", "DESSERT"),
  f("Strudel", "DESSERT"),
  f("Tart", "DESSERT"),
  f("Pudding", "DESSERT"),
  f("Custard", "DESSERT"),
  f("Mousse", "DESSERT"),
  f("Truffle (confectionery)", "DESSERT"),
  f("Gulab jamun", "DESSERT"),
  f("Jalebi", "DESSERT"),
  f("Rasgulla", "DESSERT"),
  f("Mille-feuille", "DESSERT"),
  f("Cannoli", "DESSERT"),
  f("Biscotti", "DESSERT"),

  // ── Soups & Stews ──
  f("Chicken soup", "SOUP"),
  f("Tomato soup", "SOUP"),
  f("Minestrone", "SOUP"),
  f("Clam chowder", "SOUP"),
  f("French onion soup", "SOUP"),
  f("Gazpacho", "SOUP"),
  f("Pho", "SOUP"),
  f("Ramen", "SOUP"),
  f("Miso soup", "SOUP"),
  f("Tom yum", "SOUP"),
  f("Borscht", "SOUP"),
  f("Goulash", "SOUP"),
  f("Bouillabaisse", "SOUP"),
  f("Bisque (food)", "SOUP"),
  f("Chili con carne", "SOUP"),
  f("Beef stew", "SOUP"),
  f("Irish stew", "SOUP"),
  f("Mulligatawny", "SOUP"),
  f("Laksa", "SOUP"),
  f("Pozole", "SOUP"),
  f("Menudo (soup)", "SOUP"),
  f("Wonton soup", "SOUP"),
  f("Hot and sour soup", "SOUP"),
  f("Egg drop soup", "SOUP"),
  f("Vichyssoise", "SOUP"),
  f("Avgolemono", "SOUP"),
  f("Congee", "SOUP"),
  f("Dal", "SOUP"),
  f("Sambar (dish)", "SOUP"),
  f("Callaloo", "SOUP"),

  // ── Condiments & Spices ──
  f("Ketchup", "CONDIMENT"),
  f("Mustard (condiment)", "CONDIMENT"),
  f("Mayonnaise", "CONDIMENT"),
  f("Soy sauce", "CONDIMENT"),
  f("Hot sauce", "CONDIMENT"),
  f("Sriracha", "CONDIMENT"),
  f("Tabasco sauce", "CONDIMENT"),
  f("Wasabi", "CONDIMENT"),
  f("Horseradish", "CONDIMENT"),
  f("Vinegar", "CONDIMENT"),
  f("Olive oil", "CONDIMENT"),
  f("Sesame oil", "CONDIMENT"),
  f("Fish sauce", "CONDIMENT"),
  f("Hoisin sauce", "CONDIMENT"),
  f("Worcestershire sauce", "CONDIMENT"),
  f("Chutney", "CONDIMENT"),
  f("Salsa (sauce)", "CONDIMENT"),
  f("Guacamole", "CONDIMENT"),
  f("Hummus", "CONDIMENT"),
  f("Tahini", "CONDIMENT"),
  f("Pesto", "CONDIMENT"),
  f("Chimichurri", "CONDIMENT"),
  f("Gochujang", "CONDIMENT"),
  f("Miso", "CONDIMENT"),
  f("Sambal", "CONDIMENT"),
  f("Harissa", "CONDIMENT"),
  f("Chili pepper", "CONDIMENT"),
  f("Black pepper", "CONDIMENT"),
  f("Cinnamon", "CONDIMENT"),
  f("Turmeric", "CONDIMENT"),
  f("Cumin", "CONDIMENT"),
  f("Coriander", "CONDIMENT"),
  f("Paprika", "CONDIMENT"),
  f("Saffron", "CONDIMENT"),
  f("Vanilla", "CONDIMENT"),
  f("Nutmeg", "CONDIMENT"),
  f("Cardamom", "CONDIMENT"),
  f("Star anise", "CONDIMENT"),
  f("Clove", "CONDIMENT"),
  f("Ginger", "CONDIMENT"),

  // ── Beverages ──
  f("Coffee", "BEVERAGE"),
  f("Tea", "BEVERAGE"),
  f("Beer", "BEVERAGE"),
  f("Wine", "BEVERAGE"),
  f("Whisky", "BEVERAGE"),
  f("Vodka", "BEVERAGE"),
  f("Rum", "BEVERAGE"),
  f("Gin", "BEVERAGE"),
  f("Tequila", "BEVERAGE"),
  f("Sake", "BEVERAGE"),
  f("Champagne", "BEVERAGE"),
  f("Cider", "BEVERAGE"),
  f("Mead", "BEVERAGE"),
  f("Absinthe", "BEVERAGE"),
  f("Espresso", "BEVERAGE"),
  f("Cappuccino", "BEVERAGE"),
  f("Matcha", "BEVERAGE"),
  f("Chai", "BEVERAGE"),
  f("Kombucha", "BEVERAGE"),
  f("Horchata", "BEVERAGE"),
  f("Lemonade", "BEVERAGE"),
  f("Smoothie", "BEVERAGE"),
  f("Milkshake", "BEVERAGE"),
  f("Lassi", "BEVERAGE"),
  f("Boba tea", "BEVERAGE"),
  f("Agua fresca", "BEVERAGE"),
  f("Hot chocolate", "BEVERAGE"),
  f("Mulled wine", "BEVERAGE"),
  f("Sangria", "BEVERAGE"),
  f("Mojito", "BEVERAGE"),

  // ── Pasta & Noodles ──
  f("Spaghetti", "PASTA"),
  f("Penne", "PASTA"),
  f("Fettuccine", "PASTA"),
  f("Lasagna", "PASTA"),
  f("Ravioli", "PASTA"),
  f("Tortellini", "PASTA"),
  f("Gnocchi", "PASTA"),
  f("Macaroni", "PASTA"),
  f("Linguine", "PASTA"),
  f("Rigatoni", "PASTA"),
  f("Farfalle", "PASTA"),
  f("Orzo", "PASTA"),
  f("Udon", "PASTA"),
  f("Soba", "PASTA"),
  f("Rice noodles", "PASTA"),
  f("Egg noodle", "PASTA"),
  f("Ramen noodles", "PASTA"),
  f("Pad thai", "PASTA"),
  f("Chow mein", "PASTA"),
  f("Lo mein", "PASTA"),
  f("Japchae", "PASTA"),
  f("Pappardelle", "PASTA"),
  f("Orecchiette", "PASTA"),
  f("Vermicelli", "PASTA"),
  f("Spätzle", "PASTA"),
  f("Pierogi", "PASTA"),
  f("Dumpling", "PASTA"),
  f("Gyoza", "PASTA"),
  f("Wonton", "PASTA"),
  f("Khinkali", "PASTA"),

  // ── Legumes & Nuts ──
  f("Peanut", "LEGUME"),
  f("Almond", "LEGUME"),
  f("Walnut", "LEGUME"),
  f("Cashew", "LEGUME"),
  f("Pistachio", "LEGUME"),
  f("Hazelnut", "LEGUME"),
  f("Macadamia nut", "LEGUME"),
  f("Pecan", "LEGUME"),
  f("Brazil nut", "LEGUME"),
  f("Pine nut", "LEGUME"),
  f("Chestnut", "LEGUME"),
  f("Chickpea", "LEGUME"),
  f("Lentil", "LEGUME"),
  f("Black bean", "LEGUME"),
  f("Kidney bean", "LEGUME"),
  f("Lima bean", "LEGUME"),
  f("Navy bean", "LEGUME"),
  f("Soybean", "LEGUME"),
  f("Edamame", "LEGUME"),
  f("Tofu", "LEGUME"),
  f("Tempeh", "LEGUME"),
  f("Mung bean", "LEGUME"),
  f("Fava bean", "LEGUME"),
  f("Pinto bean", "LEGUME"),
  f("Adzuki bean", "LEGUME"),
  f("Black-eyed pea", "LEGUME"),
  f("Split pea", "LEGUME"),
  f("Sunflower seed", "LEGUME"),
  f("Pumpkin seed", "LEGUME"),
  f("Chia seed", "LEGUME"),
];
