/**
 * Food pool for Yum — 780 foods sourced from Wikipedia's "Lists of foods"
 * Categories map to Wikipedia's food classification sub-lists.
 *
 * Stats are themed for food:
 *   ATK = Flavor intensity
 *   DEF = Shelf stability
 *   SPC = Uniqueness / cultural significance
 *   SPD = Prep speed (how fast to prepare)
 *   HP  = Satiety / filling power
 *
 * Rarity: 45% common, 30% uncommon, 15% rare, 10% legendary
 */

export const FOOD_CATEGORIES = {
  FRUIT:     { name: "Fruits",             color: "#e74c3c", icon: "🍎" },
  VEGETABLE: { name: "Vegetables",         color: "#27ae60", icon: "🥦" },
  GRAIN:     { name: "Breads & Grains",    color: "#d4a017", icon: "🍞" },
  DAIRY:     { name: "Dairy & Cheese",     color: "#f5f0cd", icon: "🧀" },
  MEAT:      { name: "Meats",              color: "#c0392b", icon: "🥩" },
  SEAFOOD:   { name: "Seafood",            color: "#2980b9", icon: "🐟" },
  DESSERT:   { name: "Desserts & Sweets",  color: "#e91e8c", icon: "🍰" },
  SOUP:      { name: "Soups & Stews",      color: "#e67e22", icon: "🍲" },
  CONDIMENT: { name: "Condiments & Spices",color: "#8e44ad", icon: "🌶️" },
  BEVERAGE:  { name: "Beverages",          color: "#3498db", icon: "🍵" },
  PASTA:     { name: "Pasta & Noodles",    color: "#f39c12", icon: "🍝" },
  LEGUME:    { name: "Legumes & Nuts",     color: "#795548", icon: "🥜" },
};

// seeded stat generator for consistency
function s(seed) {
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (Math.imul(31, h) + seed.charCodeAt(i)) | 0;
  const m = (off) => {
    h = (h + 0x6d2b79f5 + off) | 0;
    let t = Math.imul(h ^ (h >>> 15), 1 | h);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
  return {
    atk: Math.max(5, Math.min(99, Math.round(m(1) * 94 + 5))),
    def: Math.max(5, Math.min(99, Math.round(m(2) * 94 + 5))),
    spc: Math.max(5, Math.min(99, Math.round(m(3) * 94 + 5))),
    spd: Math.max(5, Math.min(99, Math.round(m(4) * 94 + 5))),
    hp:  Math.max(100, Math.min(999, Math.round(m(5) * 899 + 100))),
  };
}

function r(seed) {
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (Math.imul(31, h) + seed.charCodeAt(i)) | 0;
  h = (h + 0x9e3779b9) | 0;
  let t = Math.imul(h ^ (h >>> 15), 1 | h);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  const v = ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  if (v < 0.45) return "common";
  if (v < 0.75) return "uncommon";
  if (v < 0.90) return "rare";
  return "legendary";
}

function f(title, cat) {
  const stats = s(title);
  stats.rarity = r(title);
  return [title, cat, stats];
}

// ── The Food Pool ───────────────────────────────────────────
// Sourced from Wikipedia's Lists of foods sub-articles

export const FOOD_POOL = [
  // ── Fruits ──
  f("Apple", "FRUIT"),
  f("Banana", "FRUIT"),
  f("Orange", "FRUIT"),
  f("Mango", "FRUIT"),
  f("Pineapple", "FRUIT"),
  f("Strawberry", "FRUIT"),
  f("Blueberry", "FRUIT"),
  f("Raspberry", "FRUIT"),
  f("Blackberry", "FRUIT"),
  f("Cherry", "FRUIT"),
  f("Grape", "FRUIT"),
  f("Watermelon", "FRUIT"),
  f("Cantaloupe", "FRUIT"),
  f("Honeydew", "FRUIT"),
  f("Peach", "FRUIT"),
  f("Plum", "FRUIT"),
  f("Apricot", "FRUIT"),
  f("Nectarine", "FRUIT"),
  f("Pomegranate", "FRUIT"),
  f("Fig", "FRUIT"),
  f("Date (fruit)", "FRUIT"),
  f("Papaya", "FRUIT"),
  f("Guava", "FRUIT"),
  f("Passion fruit", "FRUIT"),
  f("Lychee", "FRUIT"),
  f("Dragon fruit", "FRUIT"),
  f("Kiwifruit", "FRUIT"),
  f("Persimmon", "FRUIT"),
  f("Jackfruit", "FRUIT"),
  f("Durian", "FRUIT"),
  f("Starfruit", "FRUIT"),
  f("Rambutan", "FRUIT"),
  f("Mangosteen", "FRUIT"),
  f("Coconut", "FRUIT"),
  f("Cranberry", "FRUIT"),
  f("Grapefruit", "FRUIT"),
  f("Lemon", "FRUIT"),
  f("Lime (fruit)", "FRUIT"),
  f("Tangerine", "FRUIT"),
  f("Kumquat", "FRUIT"),
  f("Clementine", "FRUIT"),
  f("Avocado", "FRUIT"),
  f("Plantain", "FRUIT"),
  f("Quince", "FRUIT"),
  f("Tamarind", "FRUIT"),
  f("Soursop", "FRUIT"),
  f("Breadfruit", "FRUIT"),
  f("Mulberry", "FRUIT"),
  f("Gooseberry", "FRUIT"),
  f("Boysenberry", "FRUIT"),

  // ── Vegetables ──
  f("Potato", "VEGETABLE"),
  f("Tomato", "VEGETABLE"),
  f("Onion", "VEGETABLE"),
  f("Garlic", "VEGETABLE"),
  f("Carrot", "VEGETABLE"),
  f("Broccoli", "VEGETABLE"),
  f("Cauliflower", "VEGETABLE"),
  f("Spinach", "VEGETABLE"),
  f("Kale", "VEGETABLE"),
  f("Lettuce", "VEGETABLE"),
  f("Cabbage", "VEGETABLE"),
  f("Brussels sprout", "VEGETABLE"),
  f("Asparagus", "VEGETABLE"),
  f("Artichoke", "VEGETABLE"),
  f("Celery", "VEGETABLE"),
  f("Cucumber", "VEGETABLE"),
  f("Zucchini", "VEGETABLE"),
  f("Eggplant", "VEGETABLE"),
  f("Bell pepper", "VEGETABLE"),
  f("Radish", "VEGETABLE"),
  f("Turnip", "VEGETABLE"),
  f("Beetroot", "VEGETABLE"),
  f("Sweet potato", "VEGETABLE"),
  f("Yam (vegetable)", "VEGETABLE"),
  f("Pumpkin", "VEGETABLE"),
  f("Butternut squash", "VEGETABLE"),
  f("Leek", "VEGETABLE"),
  f("Fennel", "VEGETABLE"),
  f("Bok choy", "VEGETABLE"),
  f("Watercress", "VEGETABLE"),
  f("Arugula", "VEGETABLE"),
  f("Endive", "VEGETABLE"),
  f("Radicchio", "VEGETABLE"),
  f("Kohlrabi", "VEGETABLE"),
  f("Daikon", "VEGETABLE"),
  f("Okra", "VEGETABLE"),
  f("Taro", "VEGETABLE"),
  f("Cassava", "VEGETABLE"),
  f("Jicama", "VEGETABLE"),
  f("Chayote", "VEGETABLE"),
  f("Bamboo shoot", "VEGETABLE"),
  f("Water chestnut", "VEGETABLE"),
  f("Lotus root", "VEGETABLE"),
  f("Rhubarb", "VEGETABLE"),
  f("Swiss chard", "VEGETABLE"),
  f("Collard greens", "VEGETABLE"),
  f("Mustard greens", "VEGETABLE"),
  f("Rutabaga", "VEGETABLE"),
  f("Parsnip", "VEGETABLE"),
  f("Celeriac", "VEGETABLE"),

  // ── Breads & Grains ──
  f("Bread", "GRAIN"),
  f("Sourdough", "GRAIN"),
  f("Baguette", "GRAIN"),
  f("Ciabatta", "GRAIN"),
  f("Focaccia", "GRAIN"),
  f("Pita", "GRAIN"),
  f("Naan", "GRAIN"),
  f("Tortilla", "GRAIN"),
  f("Croissant", "GRAIN"),
  f("Brioche", "GRAIN"),
  f("Pumpernickel", "GRAIN"),
  f("Rye bread", "GRAIN"),
  f("Challah", "GRAIN"),
  f("Cornbread", "GRAIN"),
  f("Flatbread", "GRAIN"),
  f("Chapati", "GRAIN"),
  f("Paratha", "GRAIN"),
  f("Injera", "GRAIN"),
  f("Lavash", "GRAIN"),
  f("Pretzel", "GRAIN"),
  f("Bagel", "GRAIN"),
  f("English muffin", "GRAIN"),
  f("Rice", "GRAIN"),
  f("Wheat", "GRAIN"),
  f("Oat", "GRAIN"),
  f("Barley", "GRAIN"),
  f("Quinoa", "GRAIN"),
  f("Millet", "GRAIN"),
  f("Sorghum", "GRAIN"),
  f("Couscous", "GRAIN"),
  f("Polenta", "GRAIN"),
  f("Bulgur", "GRAIN"),
  f("Farro", "GRAIN"),
  f("Amaranth (grain)", "GRAIN"),
  f("Teff", "GRAIN"),

  // ── Dairy & Cheese ──
  f("Cheddar cheese", "DAIRY"),
  f("Mozzarella", "DAIRY"),
  f("Parmesan cheese", "DAIRY"),
  f("Brie", "DAIRY"),
  f("Camembert", "DAIRY"),
  f("Gouda cheese", "DAIRY"),
  f("Gruyère cheese", "DAIRY"),
  f("Roquefort", "DAIRY"),
  f("Gorgonzola", "DAIRY"),
  f("Feta", "DAIRY"),
  f("Ricotta", "DAIRY"),
  f("Mascarpone", "DAIRY"),
  f("Cottage cheese", "DAIRY"),
  f("Cream cheese", "DAIRY"),
  f("Stilton cheese", "DAIRY"),
  f("Manchego cheese", "DAIRY"),
  f("Emmental cheese", "DAIRY"),
  f("Halloumi", "DAIRY"),
  f("Paneer", "DAIRY"),
  f("Provolone", "DAIRY"),
  f("Pecorino Romano", "DAIRY"),
  f("Colby cheese", "DAIRY"),
  f("Monterey Jack", "DAIRY"),
  f("Butter", "DAIRY"),
  f("Yogurt", "DAIRY"),
  f("Ghee", "DAIRY"),
  f("Kefir", "DAIRY"),
  f("Clotted cream", "DAIRY"),
  f("Quark (dairy product)", "DAIRY"),
  f("Labneh", "DAIRY"),

  // ── Meats ──
  f("Beef", "MEAT"),
  f("Pork", "MEAT"),
  f("Chicken (food)", "MEAT"),
  f("Lamb and mutton", "MEAT"),
  f("Turkey (food)", "MEAT"),
  f("Duck (food)", "MEAT"),
  f("Venison", "MEAT"),
  f("Rabbit (food)", "MEAT"),
  f("Goat meat", "MEAT"),
  f("Bison", "MEAT"),
  f("Bacon", "MEAT"),
  f("Ham", "MEAT"),
  f("Salami", "MEAT"),
  f("Prosciutto", "MEAT"),
  f("Chorizo", "MEAT"),
  f("Sausage", "MEAT"),
  f("Bratwurst", "MEAT"),
  f("Pepperoni", "MEAT"),
  f("Pastrami", "MEAT"),
  f("Corned beef", "MEAT"),
  f("Jerky", "MEAT"),
  f("Mortadella", "MEAT"),
  f("Bresaola", "MEAT"),
  f("Pancetta", "MEAT"),
  f("Guanciale", "MEAT"),
  f("Hot dog", "MEAT"),
  f("Steak", "MEAT"),
  f("Kebab", "MEAT"),
  f("Fried chicken", "MEAT"),
  f("Roast chicken", "MEAT"),

  // ── Seafood ──
  f("Salmon", "SEAFOOD"),
  f("Tuna", "SEAFOOD"),
  f("Shrimp (food)", "SEAFOOD"),
  f("Lobster", "SEAFOOD"),
  f("Crab", "SEAFOOD"),
  f("Oyster", "SEAFOOD"),
  f("Mussel", "SEAFOOD"),
  f("Clam", "SEAFOOD"),
  f("Scallop", "SEAFOOD"),
  f("Squid (food)", "SEAFOOD"),
  f("Octopus", "SEAFOOD"),
  f("Cod", "SEAFOOD"),
  f("Halibut", "SEAFOOD"),
  f("Sardine", "SEAFOOD"),
  f("Anchovy", "SEAFOOD"),
  f("Mackerel", "SEAFOOD"),
  f("Swordfish", "SEAFOOD"),
  f("Trout", "SEAFOOD"),
  f("Sea bass", "SEAFOOD"),
  f("Tilapia", "SEAFOOD"),
  f("Catfish", "SEAFOOD"),
  f("Crayfish", "SEAFOOD"),
  f("Sea urchin", "SEAFOOD"),
  f("Caviar", "SEAFOOD"),
  f("Sashimi", "SEAFOOD"),
  f("Sushi", "SEAFOOD"),
  f("Fish and chips", "SEAFOOD"),
  f("Ceviche", "SEAFOOD"),
  f("Calamari", "SEAFOOD"),
  f("Smoked salmon", "SEAFOOD"),

  // ── Desserts & Sweets ──
  f("Chocolate", "DESSERT"),
  f("Ice cream", "DESSERT"),
  f("Cake", "DESSERT"),
  f("Cookie", "DESSERT"),
  f("Pie", "DESSERT"),
  f("Doughnut", "DESSERT"),
  f("Brownie", "DESSERT"),
  f("Cheesecake", "DESSERT"),
  f("Tiramisu", "DESSERT"),
  f("Crème brûlée", "DESSERT"),
  f("Panna cotta", "DESSERT"),
  f("Macaron", "DESSERT"),
  f("Éclair", "DESSERT"),
  f("Profiterole", "DESSERT"),
  f("Baklava", "DESSERT"),
  f("Mochi", "DESSERT"),
  f("Gelato", "DESSERT"),
  f("Sorbet", "DESSERT"),
  f("Fudge", "DESSERT"),
  f("Toffee", "DESSERT"),
  f("Caramel", "DESSERT"),
  f("Marzipan", "DESSERT"),
  f("Meringue", "DESSERT"),
  f("Pavlova (dessert)", "DESSERT"),
  f("Churro", "DESSERT"),
  f("Waffle", "DESSERT"),
  f("Pancake", "DESSERT"),
  f("Crêpe", "DESSERT"),
  f("Strudel", "DESSERT"),
  f("Tart", "DESSERT"),
  f("Pudding", "DESSERT"),
  f("Custard", "DESSERT"),
  f("Mousse", "DESSERT"),
  f("Truffle (confectionery)", "DESSERT"),
  f("Gulab jamun", "DESSERT"),
  f("Jalebi", "DESSERT"),
  f("Rasgulla", "DESSERT"),
  f("Mille-feuille", "DESSERT"),
  f("Cannoli", "DESSERT"),
  f("Biscotti", "DESSERT"),

  // ── Soups & Stews ──
  f("Chicken soup", "SOUP"),
  f("Tomato soup", "SOUP"),
  f("Minestrone", "SOUP"),
  f("Clam chowder", "SOUP"),
  f("French onion soup", "SOUP"),
  f("Gazpacho", "SOUP"),
  f("Pho", "SOUP"),
  f("Ramen", "SOUP"),
  f("Miso soup", "SOUP"),
  f("Tom yum", "SOUP"),
  f("Borscht", "SOUP"),
  f("Goulash", "SOUP"),
  f("Bouillabaisse", "SOUP"),
  f("Bisque (food)", "SOUP"),
  f("Chili con carne", "SOUP"),
  f("Beef stew", "SOUP"),
  f("Irish stew", "SOUP"),
  f("Mulligatawny", "SOUP"),
  f("Laksa", "SOUP"),
  f("Pozole", "SOUP"),
  f("Menudo (soup)", "SOUP"),
  f("Wonton soup", "SOUP"),
  f("Hot and sour soup", "SOUP"),
  f("Egg drop soup", "SOUP"),
  f("Vichyssoise", "SOUP"),
  f("Avgolemono", "SOUP"),
  f("Congee", "SOUP"),
  f("Dal", "SOUP"),
  f("Sambar (dish)", "SOUP"),
  f("Callaloo", "SOUP"),

  // ── Condiments & Spices ──
  f("Ketchup", "CONDIMENT"),
  f("Mustard (condiment)", "CONDIMENT"),
  f("Mayonnaise", "CONDIMENT"),
  f("Soy sauce", "CONDIMENT"),
  f("Hot sauce", "CONDIMENT"),
  f("Sriracha", "CONDIMENT"),
  f("Tabasco sauce", "CONDIMENT"),
  f("Wasabi", "CONDIMENT"),
  f("Horseradish", "CONDIMENT"),
  f("Vinegar", "CONDIMENT"),
  f("Olive oil", "CONDIMENT"),
  f("Sesame oil", "CONDIMENT"),
  f("Fish sauce", "CONDIMENT"),
  f("Hoisin sauce", "CONDIMENT"),
  f("Worcestershire sauce", "CONDIMENT"),
  f("Chutney", "CONDIMENT"),
  f("Salsa (sauce)", "CONDIMENT"),
  f("Guacamole", "CONDIMENT"),
  f("Hummus", "CONDIMENT"),
  f("Tahini", "CONDIMENT"),
  f("Pesto", "CONDIMENT"),
  f("Chimichurri", "CONDIMENT"),
  f("Gochujang", "CONDIMENT"),
  f("Miso", "CONDIMENT"),
  f("Sambal", "CONDIMENT"),
  f("Harissa", "CONDIMENT"),
  f("Chili pepper", "CONDIMENT"),
  f("Black pepper", "CONDIMENT"),
  f("Cinnamon", "CONDIMENT"),
  f("Turmeric", "CONDIMENT"),
  f("Cumin", "CONDIMENT"),
  f("Coriander", "CONDIMENT"),
  f("Paprika", "CONDIMENT"),
  f("Saffron", "CONDIMENT"),
  f("Vanilla", "CONDIMENT"),
  f("Nutmeg", "CONDIMENT"),
  f("Cardamom", "CONDIMENT"),
  f("Star anise", "CONDIMENT"),
  f("Clove", "CONDIMENT"),
  f("Ginger", "CONDIMENT"),

  // ── Beverages ──
  f("Coffee", "BEVERAGE"),
  f("Tea", "BEVERAGE"),
  f("Beer", "BEVERAGE"),
  f("Wine", "BEVERAGE"),
  f("Whisky", "BEVERAGE"),
  f("Vodka", "BEVERAGE"),
  f("Rum", "BEVERAGE"),
  f("Gin", "BEVERAGE"),
  f("Tequila", "BEVERAGE"),
  f("Sake", "BEVERAGE"),
  f("Champagne", "BEVERAGE"),
  f("Cider", "BEVERAGE"),
  f("Mead", "BEVERAGE"),
  f("Absinthe", "BEVERAGE"),
  f("Espresso", "BEVERAGE"),
  f("Cappuccino", "BEVERAGE"),
  f("Matcha", "BEVERAGE"),
  f("Chai", "BEVERAGE"),
  f("Kombucha", "BEVERAGE"),
  f("Horchata", "BEVERAGE"),
  f("Lemonade", "BEVERAGE"),
  f("Smoothie", "BEVERAGE"),
  f("Milkshake", "BEVERAGE"),
  f("Lassi", "BEVERAGE"),
  f("Boba tea", "BEVERAGE"),
  f("Agua fresca", "BEVERAGE"),
  f("Hot chocolate", "BEVERAGE"),
  f("Mulled wine", "BEVERAGE"),
  f("Sangria", "BEVERAGE"),
  f("Mojito", "BEVERAGE"),

  // ── Pasta & Noodles ──
  f("Spaghetti", "PASTA"),
  f("Penne", "PASTA"),
  f("Fettuccine", "PASTA"),
  f("Lasagna", "PASTA"),
  f("Ravioli", "PASTA"),
  f("Tortellini", "PASTA"),
  f("Gnocchi", "PASTA"),
  f("Macaroni", "PASTA"),
  f("Linguine", "PASTA"),
  f("Rigatoni", "PASTA"),
  f("Farfalle", "PASTA"),
  f("Orzo", "PASTA"),
  f("Udon", "PASTA"),
  f("Soba", "PASTA"),
  f("Rice noodles", "PASTA"),
  f("Egg noodle", "PASTA"),
  f("Ramen noodles", "PASTA"),
  f("Pad thai", "PASTA"),
  f("Chow mein", "PASTA"),
  f("Lo mein", "PASTA"),
  f("Japchae", "PASTA"),
  f("Pappardelle", "PASTA"),
  f("Orecchiette", "PASTA"),
  f("Vermicelli", "PASTA"),
  f("Spätzle", "PASTA"),
  f("Pierogi", "PASTA"),
  f("Dumpling", "PASTA"),
  f("Gyoza", "PASTA"),
  f("Wonton", "PASTA"),
  f("Khinkali", "PASTA"),

  // ── Legumes & Nuts ──
  f("Peanut", "LEGUME"),
  f("Almond", "LEGUME"),
  f("Walnut", "LEGUME"),
  f("Cashew", "LEGUME"),
  f("Pistachio", "LEGUME"),
  f("Hazelnut", "LEGUME"),
  f("Macadamia nut", "LEGUME"),
  f("Pecan", "LEGUME"),
  f("Brazil nut", "LEGUME"),
  f("Pine nut", "LEGUME"),
  f("Chestnut", "LEGUME"),
  f("Chickpea", "LEGUME"),
  f("Lentil", "LEGUME"),
  f("Black bean", "LEGUME"),
  f("Kidney bean", "LEGUME"),
  f("Lima bean", "LEGUME"),
  f("Navy bean", "LEGUME"),
  f("Soybean", "LEGUME"),
  f("Edamame", "LEGUME"),
  f("Tofu", "LEGUME"),
  f("Tempeh", "LEGUME"),
  f("Mung bean", "LEGUME"),
  f("Fava bean", "LEGUME"),
  f("Pinto bean", "LEGUME"),
  f("Adzuki bean", "LEGUME"),
  f("Black-eyed pea", "LEGUME"),
  f("Split pea", "LEGUME"),
  f("Sunflower seed", "LEGUME"),
  f("Pumpkin seed", "LEGUME"),
  f("Chia seed", "LEGUME"),
  f("Flax seed", "LEGUME"),
  f("Hemp seed", "LEGUME"),
  f("Sesame seed", "LEGUME"),
  f("Lotus seed", "LEGUME"),
  f("Lupini bean", "LEGUME"),
  f("Cannellini bean", "LEGUME"),
  f("Great northern bean", "LEGUME"),
  f("Pigeon pea", "LEGUME"),
  f("Cowpea", "LEGUME"),
  f("Bambara groundnut", "LEGUME"),

  // ── Fruits (expanded) ──
  f("Cherimoya", "FRUIT"),
  f("Açaí", "FRUIT"),
  f("Feijoa", "FRUIT"),
  f("Sapodilla", "FRUIT"),
  f("Longan", "FRUIT"),
  f("Cactus pear", "FRUIT"),
  f("Miracle fruit", "FRUIT"),
  f("Finger lime", "FRUIT"),
  f("Buddha's hand", "FRUIT"),
  f("Yuzu", "FRUIT"),
  f("Pomelo", "FRUIT"),
  f("Ugli fruit", "FRUIT"),
  f("Blood orange", "FRUIT"),
  f("Bergamot orange", "FRUIT"),
  f("Damson", "FRUIT"),
  f("Greengage", "FRUIT"),
  f("Medlar", "FRUIT"),
  f("Pawpaw", "FRUIT"),
  f("Salak", "FRUIT"),
  f("Jabuticaba", "FRUIT"),
  f("Ackee", "FRUIT"),
  f("Carambola", "FRUIT"),
  f("Physalis", "FRUIT"),
  f("Currant", "FRUIT"),
  f("Elderberry", "FRUIT"),
  f("Huckleberry", "FRUIT"),
  f("Bilberry", "FRUIT"),
  f("Lingonberry", "FRUIT"),
  f("Cloudberry", "FRUIT"),
  f("Loganberry", "FRUIT"),
  f("Marionberry", "FRUIT"),
  f("Cempedak", "FRUIT"),
  f("Noni", "FRUIT"),
  f("Cupuaçu", "FRUIT"),
  f("Lucuma", "FRUIT"),

  // ── Vegetables (expanded) ──
  f("Sunchoke", "VEGETABLE"),
  f("Konjac", "VEGETABLE"),
  f("Moringa", "VEGETABLE"),
  f("Nopales", "VEGETABLE"),
  f("Hearts of palm", "VEGETABLE"),
  f("Fiddlehead fern", "VEGETABLE"),
  f("Samphire", "VEGETABLE"),
  f("Romanesco broccoli", "VEGETABLE"),
  f("Rapini", "VEGETABLE"),
  f("Galangal", "VEGETABLE"),
  f("Lemongrass", "VEGETABLE"),
  f("Shallot", "VEGETABLE"),
  f("Scallion", "VEGETABLE"),
  f("Chive", "VEGETABLE"),
  f("Ramp (plant)", "VEGETABLE"),
  f("Chinese cabbage", "VEGETABLE"),
  f("Mizuna", "VEGETABLE"),
  f("Tatsoi", "VEGETABLE"),
  f("Kai-lan", "VEGETABLE"),
  f("Amaranth (vegetable)", "VEGETABLE"),
  f("Dulse", "VEGETABLE"),
  f("Kelp", "VEGETABLE"),
  f("Wakame", "VEGETABLE"),
  f("Nori", "VEGETABLE"),
  f("Kombu", "VEGETABLE"),
  f("Broccolini", "VEGETABLE"),
  f("Delicata squash", "VEGETABLE"),
  f("Acorn squash", "VEGETABLE"),
  f("Spaghetti squash", "VEGETABLE"),
  f("Kabocha", "VEGETABLE"),
  f("Bitter melon", "VEGETABLE"),
  f("Snake gourd", "VEGETABLE"),
  f("Ridge gourd", "VEGETABLE"),
  f("Bottle gourd", "VEGETABLE"),
  f("Wax gourd", "VEGETABLE"),

  // ── Breads & Grains (expanded) ──
  f("Roti", "GRAIN"),
  f("Dosa", "GRAIN"),
  f("Idli", "GRAIN"),
  f("Arepa", "GRAIN"),
  f("Pupusa", "GRAIN"),
  f("Gordita", "GRAIN"),
  f("Sope", "GRAIN"),
  f("Johnnycake", "GRAIN"),
  f("Damper (food)", "GRAIN"),
  f("Bannock (food)", "GRAIN"),
  f("Matzo", "GRAIN"),
  f("Grissini", "GRAIN"),
  f("Cracker (food)", "GRAIN"),
  f("Melba toast", "GRAIN"),
  f("Breadstick", "GRAIN"),
  f("Crumpet", "GRAIN"),
  f("Scone", "GRAIN"),
  f("Biscuit (bread)", "GRAIN"),
  f("Mantou", "GRAIN"),
  f("Baozi", "GRAIN"),
  f("Pão de queijo", "GRAIN"),
  f("Khachapuri", "GRAIN"),
  f("Blini", "GRAIN"),
  f("Lefse", "GRAIN"),
  f("Spelt", "GRAIN"),
  f("Freekeh", "GRAIN"),
  f("Kamut", "GRAIN"),
  f("Buckwheat", "GRAIN"),
  f("Wild rice", "GRAIN"),
  f("Jasmine rice", "GRAIN"),

  // ── Dairy & Cheese (expanded) ──
  f("Époisses", "DAIRY"),
  f("Taleggio", "DAIRY"),
  f("Fontina", "DAIRY"),
  f("Asiago cheese", "DAIRY"),
  f("Havarti", "DAIRY"),
  f("Jarlsberg cheese", "DAIRY"),
  f("Muenster cheese", "DAIRY"),
  f("Limburger cheese", "DAIRY"),
  f("Raclette", "DAIRY"),
  f("Morbier cheese", "DAIRY"),
  f("Comté cheese", "DAIRY"),
  f("Reblochon", "DAIRY"),
  f("Burrata", "DAIRY"),
  f("Stracchino", "DAIRY"),
  f("Scamorza", "DAIRY"),
  f("Queso fresco", "DAIRY"),
  f("Oaxaca cheese", "DAIRY"),
  f("Cotija cheese", "DAIRY"),
  f("Queijo coalho", "DAIRY"),
  f("Curd (food)", "DAIRY"),
  f("Skyr", "DAIRY"),
  f("Ayran", "DAIRY"),
  f("Kumis", "DAIRY"),
  f("Dulce de leche", "DAIRY"),
  f("Condensed milk", "DAIRY"),

  // ── Meats (expanded) ──
  f("Wagyu", "MEAT"),
  f("Biltong", "MEAT"),
  f("Carne asada", "MEAT"),
  f("Carnitas", "MEAT"),
  f("Tandoori chicken", "MEAT"),
  f("Chicken tikka", "MEAT"),
  f("Shawarma", "MEAT"),
  f("Gyro (food)", "MEAT"),
  f("Doner kebab", "MEAT"),
  f("Satay", "MEAT"),
  f("Bulgogi", "MEAT"),
  f("Galbi", "MEAT"),
  f("Char siu", "MEAT"),
  f("Peking duck", "MEAT"),
  f("Confit", "MEAT"),
  f("Foie gras", "MEAT"),
  f("Pâté", "MEAT"),
  f("Rillettes", "MEAT"),
  f("Nduja", "MEAT"),
  f("Sobrassada", "MEAT"),
  f("Jamón ibérico", "MEAT"),
  f("Coppa (meat)", "MEAT"),
  f("Soppressata", "MEAT"),
  f("Longaniza", "MEAT"),
  f("Kielbasa", "MEAT"),
  f("Andouille", "MEAT"),
  f("Merguez", "MEAT"),
  f("Lap cheong", "MEAT"),
  f("Suya", "MEAT"),
  f("Droëwors", "MEAT"),

  // ── Seafood (expanded) ──
  f("Abalone", "SEAFOOD"),
  f("Geoduck", "SEAFOOD"),
  f("Conch", "SEAFOOD"),
  f("Whelk", "SEAFOOD"),
  f("Periwinkle (food)", "SEAFOOD"),
  f("Langoustine", "SEAFOOD"),
  f("Soft-shell crab", "SEAFOOD"),
  f("King crab", "SEAFOOD"),
  f("Snow crab", "SEAFOOD"),
  f("Dungeness crab", "SEAFOOD"),
  f("Monkfish", "SEAFOOD"),
  f("Grouper", "SEAFOOD"),
  f("Red snapper", "SEAFOOD"),
  f("Mahi-mahi", "SEAFOOD"),
  f("Wahoo (fish)", "SEAFOOD"),
  f("Barramundi", "SEAFOOD"),
  f("Branzino", "SEAFOOD"),
  f("Dover sole", "SEAFOOD"),
  f("Turbot", "SEAFOOD"),
  f("John Dory", "SEAFOOD"),
  f("Arctic char", "SEAFOOD"),
  f("Herring", "SEAFOOD"),
  f("Whitebait", "SEAFOOD"),
  f("Eel (food)", "SEAFOOD"),
  f("Uni (food)", "SEAFOOD"),
  f("Ikura", "SEAFOOD"),
  f("Tobiko", "SEAFOOD"),
  f("Surimi", "SEAFOOD"),
  f("Lutefisk", "SEAFOOD"),
  f("Gravlax", "SEAFOOD"),

  // ── Desserts & Sweets (expanded) ──
  f("Affogato", "DESSERT"),
  f("Semifreddo", "DESSERT"),
  f("Cassata", "DESSERT"),
  f("Sfogliatella", "DESSERT"),
  f("Pastel de nata", "DESSERT"),
  f("Tres leches cake", "DESSERT"),
  f("Flan (dessert)", "DESSERT"),
  f("Brigadeiro", "DESSERT"),
  f("Alfajor", "DESSERT"),
  f("Mantecada", "DESSERT"),
  f("Loukoumades", "DESSERT"),
  f("Kolompeh", "DESSERT"),
  f("Künefe", "DESSERT"),
  f("Lokum", "DESSERT"),
  f("Halva", "DESSERT"),
  f("Basbousa", "DESSERT"),
  f("Knafeh", "DESSERT"),
  f("Maamoul", "DESSERT"),
  f("Barfi", "DESSERT"),
  f("Laddu", "DESSERT"),
  f("Kheer", "DESSERT"),
  f("Kulfi", "DESSERT"),
  f("Daifuku", "DESSERT"),
  f("Taiyaki", "DESSERT"),
  f("Dorayaki", "DESSERT"),
  f("Castella", "DESSERT"),
  f("Bingsu", "DESSERT"),
  f("Tanghulu", "DESSERT"),
  f("Sachertorte", "DESSERT"),
  f("Black Forest cake", "DESSERT"),
  f("Baumkuchen", "DESSERT"),
  f("Kransekake", "DESSERT"),
  f("Lamington", "DESSERT"),
  f("Anzac biscuit", "DESSERT"),

  // ── Soups & Stews (expanded) ──
  f("Cioppino", "SOUP"),
  f("Ribollita", "SOUP"),
  f("Caldo verde", "SOUP"),
  f("Soto (food)", "SOUP"),
  f("Sinigang", "SOUP"),
  f("Rasam", "SOUP"),
  f("Harira", "SOUP"),
  f("Shorba", "SOUP"),
  f("Solyanka", "SOUP"),
  f("Ukha", "SOUP"),
  f("Żurek", "SOUP"),
  f("Chlodnik", "SOUP"),
  f("Tteokguk", "SOUP"),
  f("Sundubu-jjigae", "SOUP"),
  f("Kimchi-jjigae", "SOUP"),
  f("Doenjang-jjigae", "SOUP"),
  f("Budae-jjigae", "SOUP"),
  f("Mole (sauce)", "SOUP"),
  f("Birria", "SOUP"),
  f("Sancocho", "SOUP"),
  f("Ajiaco", "SOUP"),
  f("Locro", "SOUP"),
  f("Feijoada", "SOUP"),
  f("Cassoulet", "SOUP"),
  f("Pot-au-feu", "SOUP"),
  f("Tagine", "SOUP"),
  f("Rendang", "SOUP"),
  f("Massaman curry", "SOUP"),
  f("Green curry", "SOUP"),
  f("Vindaloo", "SOUP"),

  // ── Condiments & Spices (expanded) ──
  f("Mirin", "CONDIMENT"),
  f("Ponzu", "CONDIMENT"),
  f("Yuzu kosho", "CONDIMENT"),
  f("Furikake", "CONDIMENT"),
  f("Togarashi", "CONDIMENT"),
  f("Doenjang", "CONDIMENT"),
  f("Gochugaru", "CONDIMENT"),
  f("XO sauce", "CONDIMENT"),
  f("Oyster sauce", "CONDIMENT"),
  f("Black bean sauce", "CONDIMENT"),
  f("Chili crisp", "CONDIMENT"),
  f("Zhug", "CONDIMENT"),
  f("Amba (condiment)", "CONDIMENT"),
  f("Ajvar", "CONDIMENT"),
  f("Tkemali", "CONDIMENT"),
  f("Balsamic vinegar", "CONDIMENT"),
  f("Dijon mustard", "CONDIMENT"),
  f("Aioli", "CONDIMENT"),
  f("Remoulade", "CONDIMENT"),
  f("Béarnaise sauce", "CONDIMENT"),
  f("Hollandaise sauce", "CONDIMENT"),
  f("Mole poblano", "CONDIMENT"),
  f("Adobo (sauce)", "CONDIMENT"),
  f("Aji amarillo", "CONDIMENT"),
  f("Berbere", "CONDIMENT"),
  f("Ras el hanout", "CONDIMENT"),
  f("Duqqa", "CONDIMENT"),
  f("Za'atar", "CONDIMENT"),
  f("Sumac", "CONDIMENT"),
  f("Fenugreek", "CONDIMENT"),
  f("Asafoetida", "CONDIMENT"),
  f("Szechuan pepper", "CONDIMENT"),
  f("Grains of paradise", "CONDIMENT"),
  f("Long pepper", "CONDIMENT"),
  f("Annatto", "CONDIMENT"),

  // ── Beverages (expanded) ──
  f("Mezcal", "BEVERAGE"),
  f("Grappa", "BEVERAGE"),
  f("Calvados", "BEVERAGE"),
  f("Pisco", "BEVERAGE"),
  f("Soju", "BEVERAGE"),
  f("Baijiu", "BEVERAGE"),
  f("Raki", "BEVERAGE"),
  f("Ouzo", "BEVERAGE"),
  f("Amaretto", "BEVERAGE"),
  f("Limoncello", "BEVERAGE"),
  f("Chartreuse (liqueur)", "BEVERAGE"),
  f("Campari", "BEVERAGE"),
  f("Aperol", "BEVERAGE"),
  f("Vermouth", "BEVERAGE"),
  f("Amaro", "BEVERAGE"),
  f("Pu-erh tea", "BEVERAGE"),
  f("Oolong tea", "BEVERAGE"),
  f("Rooibos", "BEVERAGE"),
  f("Yerba mate", "BEVERAGE"),
  f("Turkish coffee", "BEVERAGE"),
  f("Cold brew coffee", "BEVERAGE"),
  f("Café au lait", "BEVERAGE"),
  f("Cortado", "BEVERAGE"),
  f("Flat white", "BEVERAGE"),
  f("Dalgona coffee", "BEVERAGE"),
  f("Tonic water", "BEVERAGE"),
  f("Ginger beer", "BEVERAGE"),
  f("Tepache", "BEVERAGE"),
  f("Kvass", "BEVERAGE"),
  f("Switchel", "BEVERAGE"),

  // ── Pasta & Noodles (expanded) ──
  f("Cavatappi", "PASTA"),
  f("Bucatini", "PASTA"),
  f("Paccheri", "PASTA"),
  f("Tagliatelle", "PASTA"),
  f("Campanelle", "PASTA"),
  f("Strozzapreti", "PASTA"),
  f("Trofie", "PASTA"),
  f("Cacio e pepe", "PASTA"),
  f("Carbonara", "PASTA"),
  f("Bolognese sauce", "PASTA"),
  f("Aglio e olio", "PASTA"),
  f("Puttanesca", "PASTA"),
  f("Biang biang noodles", "PASTA"),
  f("Dan dan noodles", "PASTA"),
  f("Zha jiang mian", "PASTA"),
  f("Laksa noodles", "PASTA"),
  f("Misua", "PASTA"),
  f("Bánh canh", "PASTA"),
  f("Bún", "PASTA"),
  f("Kalguksu", "PASTA"),
  f("Naengmyeon", "PASTA"),
  f("Mandu", "PASTA"),
  f("Xiaolongbao", "PASTA"),
  f("Har gow", "PASTA"),
  f("Siu mai", "PASTA"),
  f("Momo (food)", "PASTA"),
  f("Samosa", "PASTA"),
  f("Empanada", "PASTA"),
  f("Pelmeni", "PASTA"),
  f("Maultasche", "PASTA"),
];
