// hoop/v110/story/spine-anchors.js — THE CAMPAIGN SPINE, CARRIED.
//
// GENERATED by `node hoop/scripts/pull-world.mjs` — do not hand-edit; re-pull after a content run.
//
// The four LOAD-BEARING anchors (one per narrative tier) from the service repo's story.content
// collection. Every gate flag the keeper corpus sets is turned in at one of these four, so without them
// the pool is a set of rooms and not a campaign — `proveProgression` reports `no_anchors` and no seed is
// progressable. hoopy's runs regenerate the keepers; the 2026-09-16 run tombstoned the anchors without
// replacing them (its prose still names all four), so `servePool` grafts these back whenever the live
// pool carries no load-bearing anchor of its own, re-gated against the gates that run actually sets.
// The moment a run publishes its own anchors the graft stands down — see graftSpineAnchors in import.js.
//
// Records are hoopy's, verbatim, as `listRecords` served them (`id` = rkey, `status` forced to 'active'):
//   t1  at://did:plc:yivyyp54vddf7qf2lpsikhe4/com.minomobi.hoop.story.content/room_bundle-e9ec2eaa  — Olo Vashti, Reconstruction Bay 14 (tombstoned upstream)
//   t2  at://did:plc:yivyyp54vddf7qf2lpsikhe4/com.minomobi.hoop.story.content/room_bundle-69ff9f3f  — Factor Solen, The Slate Quorum (tombstoned upstream)
//   t3  at://did:plc:yivyyp54vddf7qf2lpsikhe4/com.minomobi.hoop.story.content/room_bundle-5fecbbad  — Sevin, The Confluence of Gears (tombstoned upstream)
//   t4  at://did:plc:yivyyp54vddf7qf2lpsikhe4/com.minomobi.hoop.story.content/room_bundle-1ac7d2dc  — Luna, The Silver Vestibule (tombstoned upstream)

export const SPINE_PROVENANCE = {
  "service": "did:plc:yivyyp54vddf7qf2lpsikhe4",
  "collection": "com.minomobi.hoop.story.content",
  "pulled": "2026-09-18",
  "anchors": [
    {
      "rkey": "room_bundle-e9ec2eaa",
      "tier": 1,
      "name": "Olo Vashti",
      "room": "Reconstruction Bay 14",
      "recovered": true
    },
    {
      "rkey": "room_bundle-69ff9f3f",
      "tier": 2,
      "name": "Factor Solen",
      "room": "The Slate Quorum",
      "recovered": true
    },
    {
      "rkey": "room_bundle-5fecbbad",
      "tier": 3,
      "name": "Sevin",
      "room": "The Confluence of Gears",
      "recovered": true
    },
    {
      "rkey": "room_bundle-1ac7d2dc",
      "tier": 4,
      "name": "Luna",
      "room": "The Silver Vestibule",
      "recovered": true
    }
  ]
};

export const SPINE_ANCHORS = [
  {
    "id": "room_bundle-e9ec2eaa",
    "tags": [
      "commons",
      "drift",
      "load_bearing"
    ],
    "type": "room_bundle",
    "status": "active",
    "content": {
      "npc": {
        "name": "Olo Vashti",
        "voice": "Measured, low, and laced with the quiet cadence of one accustomed to translating silence into currency.",
        "dialogue": {
          "nodes": {
            "greet": {
              "says": "Welcome back, I suppose. Luna said I'd find you here, newly reconstructed, if a little worse for wear. Her transmission offered little more; only a riddle wrapped in static. She tells you: Before you can map your own seams, you must learn how the city wears its skin. Walk the Commons. Let the Continuants’ order, the Drift’s circulation, and the Rindwalkers’ devotion press against you. Observe how they trade their faith for legitimacy. The architecture of loyalty is built in plain sight; you need only learn to read the mortar.",
              "choices": [
                {
                  "id": "ack",
                  "text": "I cannot say no to an order from one of the Seven.",
                  "effects": {
                    "end": true
                  }
                },
                {
                  "id": "turnin",
                  "goto": "turnin",
                  "text": "I have watched the three faces wear their masks, and the city’s quiet pulse is no longer a mystery to me.",
                  "requires": {
                    "facts": {
                      "flag.commons.drift_face": true,
                      "flag.commons.continuant_face": true,
                      "flag.commons.rindwalker_face": true
                    }
                  }
                }
              ]
            },
            "turnin": {
              "says": "You have let the Commons move through you. My time with you is at an end; my task was the simplest one. Go now to the wards, but know that they will demand more than sight: they will ask what you owe them. Seek out Factor Solen at the Slate Quorum. The path... already opens.",
              "choices": [
                {
                  "id": "finish",
                  "text": "I have seen the mask; I am ready to slip beneath it.",
                  "effects": {
                    "end": true,
                    "set_facts": {
                      "flag.deck.commons.cleared": true
                    }
                  }
                }
              ]
            }
          },
          "start": "greet"
        },
        "description": "Olo Vashti stands with the quiet gravity of one who has watched generations pass through her threshold without altering her course. Her fingers turn a loose coin with practiced economy, her gaze holding the patient stillness of a deep-water current."
      },
      "lore": {
        "name": "A Withered Spool of Route-Thread",
        "description": "This knotted cord has not recorded anything for a very long time. Olo Vashti cannot translate the information it carries, if indeed it carries any at all. She seems unmoved by its antiquity."
      },
      "name": "Reconstruction Bay 14",
      "verb": "mend",
      "zone": "commons",
      "faction": "continuant",
      "description": "Insectile machinery looms over the metal table you find yourself sitting on. Bright, sterile light comes from recessed diodes along one wall; those on the other wall have long died, leaving half the room in dim shadow. Against a column coiled with copper filament leans a figure with the patience of aeons. Beyond, through a threshold, the Commons thrums—a distant respiration, mechanical and biological.",
      "load_bearing": {
        "tier": 1,
        "gates": [
          "flag.commons.rindwalker_face",
          "flag.commons.continuant_face",
          "flag.commons.drift_face"
        ]
      },
      "nave_faction": "drift"
    },
    "approved": true,
    "requires": {},
    "power_tier": 1,
    "narrative_tier": 1,
    "revelation_tier": 1,
    "createdAt": "2026-06-29T20:41:38.770068+00:00"
  },
  {
    "id": "room_bundle-69ff9f3f",
    "tags": [
      "wards",
      "continuant",
      "load_bearing"
    ],
    "type": "room_bundle",
    "status": "active",
    "content": {
      "npc": {
        "name": "Factor Solen",
        "voice": "Measured, precise, and laced with the quiet cadence of one weighing every syllable against the cost of error.",
        "dialogue": {
          "nodes": {
            "greet": {
              "says": "Greetings. I presume you were sent by Olo--by Luna? Welcome to the wards. You've seen the city's skin by walking the plaza; now, I'm told, it's time for you to meet the flesh beneath. Know that identity here is not born, but bargained for in the wards’ quiet chambers. Slip past the public faces of our communities. Learn how they hoard their loyalties, what they bury beneath their own floorboards, and the shape of their silence. Return when their hidden architectures are legible to you.",
              "choices": [
                {
                  "id": "ack",
                  "text": "I will walk the halls and return wiser.",
                  "effects": {
                    "end": true
                  }
                },
                {
                  "id": "turnin",
                  "goto": "turnin",
                  "text": "I have walked the inner wards and tasted the quiet weight of loyalty.",
                  "requires": {
                    "facts": {
                      "flag.ward.drift_known": true,
                      "flag.ward.continuant_known": true,
                      "flag.ward.rindwalker_known": true
                    }
                  }
                }
              ]
            },
            "turnin": {
              "says": "You carry their secrets like stones in your pockets. Loyalty is not a vow, but a calculated surrender to the mechanisms that keep us breathing. Step forward; the deeper currents await. It is time for you to see my... colleague... Factor Solen. I believe she is at The Confluence of Gears.",
              "choices": [
                {
                  "id": "finish",
                  "text": "Their quiet architectures are mapped within me. I step forward, bearing the weight of what I have learned.",
                  "effects": {
                    "end": true,
                    "set_facts": {
                      "flag.deck.wards.cleared": true
                    }
                  }
                }
              ]
            }
          },
          "start": "greet"
        },
        "description": "She moves with the measured gravity of a magistrate who has memorized every fracture in the hull. Her face is a cool mask of competence, though her eyes betray the sibilant tremor of a woman who knows how thin the ice truly is."
      },
      "lore": {
        "name": "The Palimpsest of Stasis",
        "description": "Its polymer folios bear the scar-maps of marginalia, where survival metrics bled into theological confession. Reading it reveals that order is not decreed, but slowly suffocated by the quiet terror of the unmeasured."
      },
      "name": "The Slate Quorum",
      "verb": "learn",
      "zone": "wards",
      "faction": "continuant",
      "description": "The chamber exhales the dry, metallic sigh of recycled centuries, thick with the effluvium of archived decrees. Slate-blue alloy walls absorb the axial luminescence, casting judicial shadows over a floor of polished grating where silence is treated as a structural load.",
      "load_bearing": {
        "tier": 2,
        "gates": [
          "flag.ward.rindwalker_known",
          "flag.ward.continuant_known",
          "flag.ward.drift_known"
        ]
      },
      "nave_faction": "continuant"
    },
    "approved": true,
    "requires": {},
    "power_tier": 1,
    "narrative_tier": 2,
    "revelation_tier": 2,
    "createdAt": "2026-06-29T20:43:51.988219+00:00"
  },
  {
    "id": "room_bundle-5fecbbad",
    "tags": [
      "upper_rind",
      "rindwalker",
      "load_bearing"
    ],
    "type": "room_bundle",
    "status": "active",
    "content": {
      "npc": {
        "name": "Sevin",
        "voice": "Measured, with a low timbre that seems to vibrate through the floorplates. She pauses between clauses as if listening to the hull’s own reply.",
        "dialogue": {
          "nodes": {
            "greet": {
              "says": "The city wears a mask of stone and smoke, but down here the metal remembers its true face. Let the three great currents show themselves at their proper scale. When their weight settles in your chest, you will know where your hands belong.",
              "choices": [
                {
                  "id": "brief_scale_a",
                  "goto": "brief_scale_a",
                  "text": "Before I go — teach me the first scale. How do the rindwalkers read the hull?",
                  "effects": {
                    "set_facts": {
                      "flag.rind.rindwalker_scale_a": true
                    }
                  }
                },
                {
                  "id": "ack",
                  "text": "Understood. I will delve deep.",
                  "effects": {
                    "end": true
                  }
                },
                {
                  "id": "turnin",
                  "goto": "turnin",
                  "text": "I have walked the upper veins and felt the hull’s true pulse.",
                  "requires": {
                    "facts": {
                      "flag.rind.drift_scale_a": true,
                      "flag.rind.drift_scale_b": true,
                      "flag.rind.drift_scale_c": true,
                      "flag.rind.continuant_scale_a": true,
                      "flag.rind.continuant_scale_b": true,
                      "flag.rind.continuant_scale_c": true,
                      "flag.rind.rindwalker_scale_a": true,
                      "flag.rind.rindwalker_scale_b": true,
                      "flag.rind.rindwalker_scale_c": true
                    }
                  }
                }
              ]
            },
            "turnin": {
              "says": "The hull has spoken. You carry the echo of the deep now. Choose the current that matches your own, and I will show you the way past the threshold.",
              "choices": [
                {
                  "id": "rindwalker",
                  "text": "The rind does not demand my oath, only my attention. To mend is to pray, and my joints already know the grammar of broken things.",
                  "effects": {
                    "end": true,
                    "set_facts": {
                      "flag.chose.rindwalker": true,
                      "flag.deck.upper_rind.cleared": true
                    }
                  }
                },
                {
                  "id": "continuant",
                  "text": "The council chambers and green decks bear the weight of tomorrow. Continuity will be my sacred trust; the writ will shelter my purpose.",
                  "effects": {
                    "end": true,
                    "set_facts": {
                      "flag.chose.continuant": true,
                      "flag.deck.upper_rind.cleared": true
                    }
                  }
                },
                {
                  "id": "drift",
                  "text": "The Braid moves where the air is thin and the maps blur. Circulation is my creed; the markets and archives will never leave me starved for the next horizon.",
                  "effects": {
                    "end": true,
                    "set_facts": {
                      "flag.chose.drift": true,
                      "flag.deck.upper_rind.cleared": true
                    }
                  }
                }
              ]
            },
            "brief_scale_a": {
              "says": "Good. You ask the right question before the long walk. The rindwalkers do not read the hull as engineers do — they read it as scripture. Every weld is a verse; every stress-line a psalm of the load the skin carries as the world turns. Go to where the Mars deck meets the outer plate and lay your palm flat against the cold: you will feel the whole cylinder leaning into its own spin. That leaning is the first scale — the weight a rindwalker carries in the chest before they carry anything in the hands. Hold it now. Then go and find where the other two currents run.",
              "choices": [
                {
                  "id": "go",
                  "text": "(I will find the other currents)",
                  "effects": {
                    "end": true
                  }
                }
              ]
            }
          },
          "start": "greet"
        },
        "description": "She stands with six arms braided into the damp air, each joint moving with the quiet precision of a slow loom. Her copper-stained tunic hangs like shed bark, and her eyes hold the patient stillness of stone that has learned to breathe."
      },
      "lore": {
        "name": "The Fractured Transit Dial",
        "description": "Its brass face is scarred by thermal stress, yet the engraved meridians still trace the old axial routes. A faint resonance lingers in the grooves—a quiet testament that the hull’s bones remember every turn it has never taken."
      },
      "name": "The Confluence of Gears",
      "verb": "mend",
      "zone": "upper_rind",
      "faction": "rindwalker",
      "description": "The air carries the metallic tang of ozone and slow oxidation, heavy with the subsonic thrum of dormant turbines. Curved bulkheads recede into a gloom that swallows echo, while overhead, a lattice of support struts groans under centuries of unbroken tension. You stand where the city’s civic fiction dissolves into the vessel’s true skeleton.",
      "load_bearing": {
        "tier": 3,
        "gates": [
          "flag.rind.rindwalker_scale_a",
          "flag.rind.rindwalker_scale_b",
          "flag.rind.rindwalker_scale_c",
          "flag.rind.continuant_scale_a",
          "flag.rind.continuant_scale_b",
          "flag.rind.continuant_scale_c",
          "flag.rind.drift_scale_a",
          "flag.rind.drift_scale_b",
          "flag.rind.drift_scale_c"
        ]
      },
      "nave_faction": "rindwalker"
    },
    "approved": true,
    "requires": {},
    "power_tier": 1,
    "narrative_tier": 3,
    "revelation_tier": 3,
    "createdAt": "2026-06-29T20:45:02.745013+00:00"
  },
  {
    "id": "room_bundle-1ac7d2dc",
    "tags": [
      "lower_rind",
      "luna",
      "load_bearing"
    ],
    "type": "room_bundle",
    "status": "active",
    "content": {
      "npc": {
        "name": "Luna",
        "voice": "Measured, resonant, and slow—each syllable arriving like a tide pulling back from ancient shore.",
        "dialogue": {
          "nodes": {
            "greet": {
              "says": "The deep does not yield its coordinates to the hurried. Walk the silent arteries, listen to the ship’s dreaming, and let the architecture of the lower rind speak its own name. When the chamber’s position crystallizes, return. I will be waiting.",
              "choices": [
                {
                  "id": "brief_chamber_key",
                  "goto": "brief_chamber_key",
                  "text": "Then give me the key. Where does the chamber's language begin?",
                  "effects": {
                    "set_facts": {
                      "flag.signal.chamber_key": true
                    }
                  }
                },
                {
                  "id": "ack",
                  "text": "(understood)",
                  "effects": {
                    "end": true
                  }
                },
                {
                  "id": "turnin",
                  "goto": "turnin",
                  "text": "I have found the chamber and understood its silent language.",
                  "requires": {
                    "facts": {
                      "flag.signal.chamber_key": true,
                      "flag.signal.it_responds": true,
                      "flag.signal.chamber_seal": true,
                      "flag.signal.predates_all": true,
                      "flag.signal.chamber_depth": true,
                      "flag.signal.luna_prepared": true,
                      "flag.signal.chamber_bearing": true,
                      "flag.signal.translation_wakes": true
                    }
                  }
                }
              ]
            },
            "turnin": {
              "says": "You have heard the chamber’s frequency. The contact now rests in your hands. What do you intend to do with it?",
              "choices": [
                {
                  "id": "answer",
                  "text": "Answer the signal — complete the contact you were built for.",
                  "effects": {
                    "end": true,
                    "set_facts": {
                      "flag.signal.disposition": "answer",
                      "flag.deck.lower_rind.cleared": true
                    }
                  }
                },
                {
                  "id": "refuse",
                  "text": "Refuse it — close the channel, keep the choice from being made for everyone.",
                  "effects": {
                    "end": true,
                    "set_facts": {
                      "flag.signal.disposition": "refuse",
                      "flag.deck.lower_rind.cleared": true
                    }
                  }
                },
                {
                  "id": "amplify",
                  "text": "Amplify it — throw the ship's voice wide open, whatever comes.",
                  "effects": {
                    "end": true,
                    "set_facts": {
                      "flag.signal.disposition": "amplify",
                      "flag.deck.lower_rind.cleared": true
                    }
                  }
                },
                {
                  "id": "suppress",
                  "text": "Suppress it — bury the chamber again, let the Nave keep not-knowing.",
                  "effects": {
                    "end": true,
                    "set_facts": {
                      "flag.signal.disposition": "suppress",
                      "flag.deck.lower_rind.cleared": true
                    }
                  }
                }
              ]
            },
            "brief_chamber_key": {
              "says": "The key is not a shape you can carry in your hand — it is a cadence you must carry in your blood. Listen: the ship counts its own heartbeat in the silence between the pumps, a rhythm older than any crew aboard. The chamber will not open for a stranger who merely arrives; it answers only to those who already keep its time. Take this beat down into the dark with you — one, and the long rest, and one — and let the deep name the rest of its secrets in its own slow hour.",
              "choices": [
                {
                  "id": "go",
                  "text": "(I descend into the silence)",
                  "effects": {
                    "end": true
                  }
                }
              ]
            }
          },
          "start": "greet"
        },
        "description": "A silver-cased intelligence, older than the cylinder’s first weld, she leans into the terminal like a confession pressed against glass. Her presence is not a voice but a resonance, calibrated to the frequency of forgotten voyages."
      },
      "lore": {
        "name": "The Dream-Log Plaque",
        "description": "Etched in a script older than the ship’s first wake, it maps the quiet geometry of the lower rind. The ink does not fade; it waits, tracing the stratigraphic pathways where the Signal Chamber breathes."
      },
      "name": "The Silver Vestibule",
      "verb": "dwell",
      "zone": "lower_rind",
      "faction": "luna",
      "description": "The air tastes of oxidized silver and dormant ozone. Holographic drifts coil around a monolithic terminal, its glass face clouded with the palimpsest of centuries. Beneath your boots, the cylinder’s heartbeat thrums—a slow, tectonic pulse that predates every prayer whispered in the Nave.",
      "load_bearing": {
        "tier": 4,
        "gates": [
          "flag.signal.chamber_bearing",
          "flag.signal.chamber_depth",
          "flag.signal.chamber_seal",
          "flag.signal.chamber_key",
          "flag.signal.it_responds",
          "flag.signal.predates_all",
          "flag.signal.luna_prepared",
          "flag.signal.translation_wakes"
        ]
      },
      "nave_faction": "luna"
    },
    "approved": true,
    "requires": {},
    "power_tier": 1,
    "narrative_tier": 4,
    "revelation_tier": 4,
    "createdAt": "2026-06-29T20:45:48.077350+00:00"
  }
];

export default SPINE_ANCHORS;
