/* The cross-tale layer — four tales side by side.
   Annotates the same call-numbers across Culhwch, Gawain, Orfeo and Pwyll
   so the comparative payoff of the annotation stack becomes visible at a
   glance. Three tables: shared motifs (Thompson codes), shared Propp
   functions (with absences flagged where present), and shared character
   archetypes. Loaded after data.js; attaches to window.PENDRAGON. */
window.PENDRAGON = window.PENDRAGON || {};
window.PENDRAGON.crosswalk = {
  intro: "With four poems now in the same apparatus — Culhwch ac Olwen (Welsh, c. 1100), Pwyll Pendefig Dyfed (Welsh, manuscripts c. 1350–1410, story-stratum older), Sir Orfeo (Middle English, c. 1300), and Sir Gawain and the Green Knight (Middle English, c. 1380) — the comparative layer the motif index and the story graph open up can do its work. Below: the same Thompson Motif codes laid against all four poems, the same Propp functions laid against all four, and a small map of character archetypes that recur in all four. Where a code is present in multiple tales the cross-reference is given; where it is sharply absent from one and central to another, the absence is named. Four tales gives the comparative pattern more traction: two Welsh and two Middle English, two cycles built on the Otherworld and two on the court, with two foundational Mabinogi tales (Culhwch, Pwyll) anchoring the Insular wonder-tale tradition the English romances inherit.",
  tales: [
    { id: "culhwch", title: "Culhwch ac Olwen",                short: "Culhwch", sigil: "🐗", href: "/culhwch/", color: "#7fb37f" },
    { id: "pwyll",   title: "Pwyll Pendefig Dyfed",            short: "Pwyll",   sigil: "🐎", href: "/pwyll/",   color: "#d8b24a" },
    { id: "orfeo",   title: "Sir Orfeo",                       short: "Orfeo",   sigil: "🎵", href: "/orfeo/",   color: "#6fa8c9" },
    { id: "gawain",  title: "Sir Gawain and the Green Knight", short: "Gawain",  sigil: "🪓", href: "/gawain/",  color: "#c97f9a" },
  ],

  motifIntro: "Thompson Motif codes shared across the four poems. Sorted by how many tales carry each: the codes at the top form the small structural backbone the four poems share. The codes at the bottom (single-tale) show what each poem brings uniquely into the comparison.",
  motifs: [
    // ── In all three ─────────────────────────────────────────────────
    { code: "M223", name: "The rash promise / blank check",
      culhwch: { passages: [2], note: "Arthur grants whatever Culhwch will name (save a reserved few treasures) before he hears the request." },
      pwyll:   { passages: [4], note: "Pwyll at the wedding feast grants Gwawl <em>“whatever you ask of me”</em> unheard — and Gwawl asks for the feast and Rhiannon. Rhiannon then turns the same form back on Gwawl with the bag-trick." },
      gawain:  { passages: [1, 3], note: "Arthur accepts the Green Knight's terms unheard; Bertilak's exchange-of-winnings struck on the same form." },
      orfeo:   { passages: [5], note: "Fairy King: <em>now aske of me what it be — largelich Ichil the pay; now speke, and tow might asay.</em> The hinge of the rescue." },
      gloss: "The single most ecumenical motif in the set. All four poems run on the rash boon — promise asked in the fairest possible form and then leveraged: in Culhwch to set the quest, in Pwyll to lose Rhiannon and then to recover her, in Gawain to extract the year-and-a-day, in Orfeo to recover the queen. The medieval Insular tradition is built on the binding force of the spoken word." },

    { code: "Z71.1", name: "Formulistic number: three",
      culhwch: { passages: [2, 7, 10], note: "Three shouts at Arthur's gate; three poisoned spears thrown back at Ysbaddaden; the boar Twrch hunted by Arthur and his men across three countries." },
      pwyll:   { passages: [3], note: "Three days of the chase on the Gorsedd Arberth — runner, fastest horseman, Pwyll himself; only the third asking halts Rhiannon. Three years of barren marriage before the men of Dyfed petition. Six women's lie pivots a third-night vigil." },
      gawain:  { passages: [1, 3, 4], note: "Three blows at the chapel, three hunts, three temptations, three exchanges of winnings, three days, three kisses. Z71.1 is pervasive." },
      orfeo:   { passages: [3, 5], note: "Three apparitions of the fae (hunt, host, dance); three laments; three harpings (wild beasts, Fairy King's court, the steward's hall). More sparing than Gawain." },
      gloss: "All four lean on triadic structure, with sharply different densities. Gawain is built triadically at every level; Orfeo uses the three in selected places; Pwyll uses it once with great precision on the Gorsedd; Culhwch lets the threes share space with nines and other formulistic numbers." },

    { code: "A186", name: "Demoted divinity walking as character",
      culhwch: { passages: [8, 9], note: "Mabon son of Modron — \"Divine Son\" of \"Divine Mother\" — the British god Maponos demoted to imprisoned heir. Gwyn ap Nudd, king of Annwn." },
      pwyll:   { passages: [1, 3], note: "The whole tale runs on this. Arawn, lord of Annwn; Rhiannon as <em>Rigantona</em>, the Great Queen, with Epona's horse and bird signatures; Pryderi's theft-and-recovery as a Mabon-type. Pwyll is the locus classicus of Welsh god-as-character." },
      gawain:  { passages: [4], note: "Morgan le Fay named \"Morgne the goddess\" by Bertilak at the reveal; the Green Knight with his vegetation-god iconography." },
      orfeo:   { passages: [1, 2, 5], note: "Pluto and Juno named as Orfeo's ancestors, immediately glossed: <em>that sum time were as godes y hold</em> — were <em>held</em> for gods. The Fairy King allowed to stand as <em>king o fairy</em> without Christian framing." },
      gloss: "Each poem manages older divinity differently. Culhwch lets old gods walk as heroes (Mabon's mythological lineage is part of his power). Pwyll runs an entire branch on demoted gods without ever flagging it — Arawn and Rhiannon are simply the king and the lady, and the audience is expected to feel the older weight. Gawain names Morgan a goddess as part of the unmasking. Orfeo opens by euhemerising Pluto and Juno explicitly — and then lets the Fairy King retain divine dignity under a different name. Pwyll's silence is the most archaic of the four." },

    { code: "F252", name: "The Otherworld and its court",
      culhwch: { passages: [8], note: "Annwn and its lord Gwyn ap Nudd, demanded for the hunt; behind the whole tradition stands Avalon." },
      pwyll:   { passages: [2], note: "The canonical onstage Welsh Otherworld court. Annwn rendered as a fully-furnished Welsh medieval great hall with queen, courtiers, hounds, feast and protocol; Pwyll spends a year inside it ruling. Where Culhwch and Orfeo show Annwn from outside, Pwyll shows it from the throne." },
      gawain:  { passages: [2, 3, 4], note: "Hautdesert as Morgan's court of enchantment — Bertilak, the lady, the ancient lady, the household." },
      orfeo:   { passages: [2, 3, 4, 5], note: "A hundred snow-white knights and a hundred milk-white damsels; the Fairy King and Queen on thrones in a tabernacle of light; porter, courtiers, the half-taken." },
      gloss: "All four stage an Otherworld court, with sharply different distances. Culhwch's is offstage — Annwn invoked, Gwyn drafted. Gawain's is hidden in plain sight as a Christmas castle. Orfeo's is the most fully imagined visually — crystal walls, ever-light, the yard of the half-taken. Pwyll's is the most fully <em>inhabited</em>: he rules it for a year, feasts with its queen, fights its civil war. Four distances on the same court." },

    { code: "N825.3", name: "Old person as helper at the threshold",
      culhwch: { passages: [4, 5], note: "Custennin the fire-breathing herdsman and his wife (Culhwch's aunt by marriage), who hide Goreu in a stone chest and warn the company of the giant's terms." },
      pwyll:   { passages: [6], note: "Teirnon Twrf Liant — <em>the best man in the world</em>, the old story says — keeps and raises the stolen child in his stable-court for years, then recognises him and brings him to Pwyll. The faithful threshold-keeper of the recognition arc." },
      gawain:  { passages: [2, 3, 4], note: "The \"auncian lady\" beside the young wife at Hautdesert — Morgan le Fay in age-disguise, honoured at table without ever being recognised." },
      orfeo:   { passages: [6], note: "The Winchester beggar at the town's edge, in his narrow hut. Houses Orfeo and Heurodis, tells the city's news, lends the borrowed clothes." },
      gloss: "An aged figure at the threshold turns out to hold the key in each tale. Moral colouring varies: Custennin's wife and Teirnon are helpers, the beggar is a quiet host, Morgan is the prime mover of the test. Same structural slot, four different moral occupants — the helper, the keeper-of-the-lost-child, the harmless witness, and the disguised antagonist." },

    { code: "F151.1", name: "Perilous path to the Otherworld",
      culhwch: { passages: [4], note: "The fortress that comes no closer however long you walk — the Otherworld holding its distance." },
      pwyll:   false,
      gawain:  { passages: [2], note: "The wild road through North Wales and the Wirral — wolves, wodwos, ice in the armour, the Christmas Eve prayer." },
      orfeo:   { passages: [4], note: "Three miles through solid stone in a rock-cleft. Orfeo spares neither stub nor stone." },
      gloss: "Three different terrain-shapes for the same motif — and sharply absent from Pwyll. The Welsh tradition uses the unreachable fort (Culhwch); the Gawain-poet's tradition uses the winter wilderness ride; Orfeo uses the cleft-in-the-rock. Pwyll's Annwn has no perilous path because Arawn brings Pwyll there as a guest — the Otherworld is entered by invitation, not by ordeal. The tale of host-substitution refuses the threshold-as-trial." },

    { code: "H1556", name: "Test of fidelity",
      culhwch: { passages: [8, 9, 10, 11], note: "The impossible tasks of the anoethau test Culhwch (in fact Arthur) and his band — by completing every one, faithfulness to the bargain is proved." },
      pwyll:   { passages: [2], note: "The chaste-bed: Pwyll in Arawn's form sleeps a year beside Arawn's queen and turns his back every night, saying nothing. The clean structural test of marital fidelity-by-bargain — the one beat that earns him the name Pen Annwn." },
      gawain:  { passages: [3], note: "The exchange-of-winnings — three days of paralleled hunts and bedroom encounters. The test of whether the guest will give back honestly all he gained. Gawain passes twice; fails once, by a hand's-breadth." },
      orfeo:   { passages: [6], note: "Inverted — the hero tests the steward. The lying tale of his death; the steward's total grief; the conditional reveal." },
      gloss: "All four poems revolve around a test of loyalty. The position of hero is different in each: Culhwch as the tested party in absence (Arthur and the band test for him); Pwyll as the tested party in another man's bed; Gawain as the tested party in person at his host's bed; Orfeo as the testing party against his own servant. Three bedside tests of three different forms of fidelity — to bargain, to host, to absent queen — and one chamber-emptied test of fidelity-by-quest." },

    // ── In multiple ─────────────────────────────────────────────────
    { code: "F156", name: "Door to the Otherworld at a marked place",
      culhwch: false,
      pwyll:   { passages: [3], note: "The Gorsedd Arberth — a real burial-mound just above Pwyll's court. The old custom: whatever nobleman sits on it suffers a hurt or sees a marvel. Pwyll sits there deliberately and Rhiannon comes." },
      gawain:  { passages: [4], note: "The Green Chapel turns out to be a hollow grass-grown barrow with three openings, beside a steaming brook." },
      orfeo:   { passages: [4], note: "A great rock with a vertical cleft, three miles through solid stone, onto the bright country." },
      gloss: "Pwyll's Gorsedd Arberth is the canonical Welsh form — a grass-covered mound above the court where the apparatus is openly named (sit here and a marvel comes). Gawain's Green Chapel is the same shape (grass-grown barrow with openings) restaged as Pearl-Poet wilderness. Orfeo's rock-cleft is the most decisively spatial. Only Culhwch refuses the motif — its Otherworld is the geometry of unreachability, not a marked place. Three of the four tales need a door; the oldest does not." },

    { code: "K1810", name: "Deception by disguise",
      culhwch: { passages: [11], note: "Cei as sword-burnisher to enter Wrnach's hall — the giant's death by his own blade." },
      pwyll:   { passages: [1, 4], note: "Two registers of disguise. Pwyll wears Arawn's body for a year while Arawn wears his — by mutual consent, not deception of the other. Then Pwyll dresses as a beggar at Gwawl's feast to spring the bag-trick — the trick that recovers Rhiannon." },
      gawain:  { passages: [1, 2, 3, 4], note: "Three masks: Bertilak is the Green Knight, the ancient lady is Morgan, the lady acts at Bertilak's direction. The poem keeps the audience inside Gawain's ignorance for two whole Fitts." },
      orfeo:   { passages: [4, 5, 6], note: "Orfeo as minstrel at the Fairy King's gate, as harper-from-heathenness to the steward, in borrowed beggar's clothes at Winchester." },
      gloss: "All four tales use the motif, in markedly different moral vectors. Culhwch and Gawain use disguise on the antagonist's side (Cei to enter the giant's hall; Bertilak to obscure himself); Pwyll and Orfeo use it on the hero's side (Pwyll to recover Rhiannon, Orfeo to recover Heurodis). Pwyll uniquely uses it consensually first (the year-exchange with Arawn) before using it adversarially second (the beggar at Gwawl's feast)." },

    { code: "N777", name: "Adventure follows the hunt",
      culhwch: false,
      pwyll:   { passages: [1], note: "The opening of the whole tale: Pwyll's hunt at Glyn Cuch summons Arawn's hunt, the year-exchange and the rest of the story. The canonical British wonder-tale opening — older than its Middle English re-uses." },
      gawain:  { passages: [3], note: "Three days of paralleled hunts cross-cut with three bedroom encounters; the hunt outside structurally summons and pays for the test inside." },
      orfeo:   { passages: [3, 4], note: "The sixty hawking ladies are an Otherworld hunt; Orfeo follows them through the rock-cleft. The hunt-as-threshold preserved cleanly." },
      gloss: "The hunt as plot-engine in three of the four — and Pwyll the locus classicus. The Middle English poems inherit the form from the older Welsh wonder-tale tradition: a hunt at a wood-border summons the Otherworld. Culhwch's great boar-hunt is the structural exception — there it is the climax of the quest, not its conjurer." },

    { code: "F771.6", name: "Castle in the wilderness / of crystal",
      culhwch: false,
      pwyll:   false,
      gawain:  { passages: [2], note: "Hautdesert appears in the trees in answer to Gawain's prayer to Mary on Christmas Eve — \"a castle full comely, gleamed and shone.\"" },
      orfeo:   { passages: [4], note: "The crystal castle of the Otherworld: outer wall of clear crystal, a hundred towers, red-gold buttresses, precious-stone chambers, the worst pillar of burnished gold." },
      gloss: "An English-only motif. Both English poems produce a wonder-castle out of the wilderness; Gawain's is rationalised as a great medieval fortress, Orfeo's is unembarrassedly fairy-architecture. The Welsh tales both stage their Otherworld as an inhabited hall (in Pwyll) or as offstage geometry (in Culhwch) — never as a wonder-architecture visible from the outside. Two registers of the same astonishment, both Insular-English." },

    { code: "F375", name: "Mortal returns from the Otherworld",
      culhwch: false,
      pwyll:   { passages: [2], note: "Pwyll returns from his year in Annwn unmarked and welcomed — Arawn's people praised the year's rule and Pwyll's own people received him as if no exchange had happened. The cleanest return arc in the four tales: no scar, no sash, no aged face." },
      gawain:  { passages: [4], note: "Gawain returns marked — nick on the neck, the green sash bound under his left arm — a partial return." },
      orfeo:   { passages: [5, 6], note: "Heurodis returns unchanged; Orfeo returns altered only by ten years of mourning that the bath and shaving undo. A full return." },
      gloss: "Three returns, three costs. Gawain comes back changed; Orfeo and Heurodis come back themselves; Pwyll comes back better — he gains an alliance and a name (Pen Annwn). The Welsh tale frames the Otherworld as a place a king may simply rule for a year and step out of; the English poems frame it as a place whose visit is paid for, either in the body or in years." },

    { code: "H1010", name: "Impossible tasks",
      culhwch: { passages: [8], note: "The ~40 anoethau Ysbaddaden imposes on pain of death — clear and reap a hill in a day, fetch the comb between the boar's ears, win the cauldron from Ireland." },
      pwyll:   false,
      gawain:  false,
      orfeo:   false,
      gloss: "The signature motif of Culhwch and absent from the other three. The wonder-tale's task-quest belongs to the oldest Welsh stratum; Pwyll uses a bargain and a trick where Culhwch would use a list of labours; the English romances substitute tests of honour and rash bargains for impossible labours. Culhwch alone keeps the catalogue." },

    { code: "G530.2", name: "Help from the ogre's daughter",
      culhwch: { passages: [6], note: "Olwen coaches Culhwch on how to out-promise her giant father — the precise motif at its purest." },
      pwyll:   { passages: [4], note: "The same shape, refigured: Rhiannon (whose father Hyfaidd Hen has given her to Gwawl against her will) coaches Pwyll on how to out-promise the rival suitor with the bag-trick. The bride-helps-suitor-against-father pattern, with the suitor's rival in the father's structural slot." },
      gawain:  false,
      orfeo:   false,
      gloss: "A motif the two Welsh tales share against the two English ones. Olwen and Rhiannon both coach their suitor in how to get past the figure barring the marriage — Olwen against her giant father, Rhiannon against her father's chosen suitor. Both tales are explicitly bride-led recovery stories. The English poems have queens taken or tested but never won from a parent or rival." },

    // ── Distinctively single ───────────────────────────────────────
    { code: "F407", name: "Talking severed head",
      culhwch: false,
      pwyll:   false,
      gawain:  { passages: [1], note: "The Green Knight's head, held in his hand from horseback, turns its eyes on Camelot and speaks the rules of the return-match." },
      orfeo:   false,
      gloss: "Gawain's distinctive opening miracle. The motif is older — see Bran the Blessed in the Mabinogi's Second Branch, the sibling of Pwyll's First — but Gawain's poem is the canonical Insular literary use. Pwyll's branch precedes Bran's by one position in the manuscript order." },

    { code: "F379.1", name: "The half-taken — body remains as if dead, self in fairyland",
      culhwch: false,
      pwyll:   false,
      gawain:  false,
      orfeo:   { passages: [4], note: "The yard inside the Otherworld castle: figures held in the postures they were taken in — some headless, some bound and mad, women in childbed, sleeping at noon. <em>Thought dede and nare nought.</em>" },
      gloss: "Orfeo's most distinctive contribution to the Otherworld tradition. Neither Culhwch nor Gawain nor Pwyll has anything quite like the yard of the half-taken; it is one of the most uncanny passages in medieval English and a motif Thompson's index does not fully cover." },

    { code: "Z356", name: "The unique exception (named within a catalogue)",
      culhwch: false,
      pwyll:   false,
      gawain:  { passages: [2], note: "The pentangle — five points each twined into the next — named explicitly <em>the endeles knot</em> within the catalogue of arming." },
      orfeo:   { passages: [4], note: "<em>Al that lond was ever light</em> — the ever-light Otherworld, named separately from the catalogue of the castle's wonders." },
      gloss: "Both English poems use the same rhetorical device: stop a catalogue of wonders to mark one wonder as unique among them. The Pearl-Poet does it with the pentangle, the Orfeo poet with the ever-light. The Welsh tales prefer to name things in lists or not name them at all — no such marked exception in either Culhwch or Pwyll." },

    // ── Brought into the corpus by Pwyll ───────────────────────────
    { code: "D1626.1", name: "Magic horse that cannot be overtaken",
      culhwch: false,
      pwyll:   { passages: [3], note: "Rhiannon's pale-white horse: walks at an easy pace, and yet no runner, no horseman, no rider however fast comes anywhere near catching her. Three days of attempts; only Pwyll's spoken asking halts her." },
      gawain:  false,
      orfeo:   { passages: [3], note: "Echo: the snow-white horses of the Fairy King's retinue and the sixty hawking ladies — never lamed, never caught, always at the threshold." },
      gloss: "Pwyll is the canonical Insular instance: Rhiannon's horse is a recoverable god (the horse-goddess Epona, demoted; <em>Rigantona</em>'s mount). Orfeo's snow-white fairy horses preserve the figure in attenuated form three centuries later. The Welsh tale anchors a motif the English lay inherits." },

    { code: "K1601", name: "Magic container that holds more than it should (badger-in-the-bag)",
      culhwch: false,
      pwyll:   { passages: [4], note: "Rhiannon's never-filling bag. Gwawl is invited to press the food down with his own two feet; Pwyll knots the bag shut over his head and blows the horn; a hundred horsemen come running. The trick that recovers the queen, naming the children's game <em>byw'r mochyn yn y cwd</em> — 'play badger-in-the-bag'." },
      gawain:  false,
      orfeo:   false,
      gloss: "A signature Welsh trick-motif. Pwyll uses an enchanted container as the lever of recovery — and gives Wales a children's game in the doing. The English poems do not reproduce the magic-bag motif; their tricks are bargains and disguises, not enchanted objects." },

    { code: "P528", name: "The calumniated wife (ATU 707)",
      culhwch: false,
      pwyll:   { passages: [5], note: "Rhiannon's penance. The six women, terrified of being punished for losing the prince's son, smear blood on the sleeping queen and accuse her of killing him. Pwyll refuses to set her aside; she sits at the gate for seven years, telling her story and offering to carry visitors on her back. The wife wrongfully accused of infanticide — a structural backbone of the ATU 707 tale-type." },
      gawain:  false,
      orfeo:   false,
      gloss: "The classic calumniated-wife motif, and Pwyll among its earliest Insular witnesses. The penance is handled with structural gravity — Pwyll keeps her even when his nobles press for her dismissal, and the false accusation is dissolved by Teirnon's evidence rather than her self-defence. None of the other three tales puts an accused queen on stage." },

    { code: "B538.1", name: "Severed monster's arm at the window",
      culhwch: false,
      pwyll:   { passages: [6], note: "Teirnon's vigil: at midnight the mare gives birth, a great dark clawed arm reaches through the high window for the foal, and Teirnon strikes the arm off at the elbow. From outside there comes a scream; the foal stays. The unseen power is never shown — only its severed limb." },
      gawain:  false,
      orfeo:   false,
      gloss: "A motif with deep North-Sea resonance — the closest cousin is Beowulf's tearing of Grendel's arm at Heorot. Pwyll's branch is the Insular Welsh witness of the figure. Outside our four-tale corpus the parallel is the most striking thing about Pwyll's Movement V–VI." },

    { code: "T563", name: "Recognition of unknown son by resemblance",
      culhwch: false,
      pwyll:   { passages: [6], note: "Teirnon, having been Pwyll's man years before, looks at the boy he raised and sees Pwyll's face. The boy is brought to Arberth; everyone in the hall agrees on the likeness; Rhiannon is released from her penance. Recognition not by ring or token but by the printed face." },
      gawain:  false,
      orfeo:   false,
      gloss: "Pwyll's recognition arc is built on the simplest possible token — the resemblance itself. Orfeo's recognition by the harp's tune and Gawain's by the green sash work the same structural slot through objects; only Pwyll lets the body do it. Culhwch never returns to be recognised." },

    { code: "F302", name: "Fairy bride / mortal weds Otherworld woman",
      culhwch: false,
      pwyll:   { passages: [3], note: "Rhiannon comes openly from the Otherworld on her pale-white horse to choose Pwyll. She is the canonical fairy bride of the Insular tradition — Epona / Rigantona in human form, choosing a Welsh prince over a fairy suitor (Gwawl)." },
      gawain:  { passages: [2, 3], note: "Echo, partial: Lady Bertilak is mortal in the surface story but bound to Morgan's Otherworld household at Hautdesert; she courts Gawain at her host's bidding." },
      orfeo:   false,
      gloss: "Pwyll's Rhiannon is the locus classicus — a fairy queen who chooses to enter the mortal world and marry within it. The Hautdesert lady is the same shape bent: a court woman in an Otherworld house, sent to test rather than to choose. Olwen and Heurodis are mortal; the role belongs distinctively to the two senior Welsh-Insular figures, Rhiannon directly and Lady Bertilak in shadow." },
  ],

  proppIntro: "The 31 Propp functions laid against the four poems. <em>✓</em> marks present; <em>·</em> marks the function as sharply absent (named in our story graphs as a meaningful refusal). The dense top — the wonder-tale's quest spine — is present in all four; the variations in the lower section are where each poem's individual project starts to surface.",
  propp: [
    { sym: "α", name: "Initial situation", culhwch: "present", pwyll: "present", gawain: "present", orfeo: "present",
      gloss: "All four poems open by introducing the court and family — Cilydd & Goleuddydd, Pwyll's Arberth, Arthur's Camelot, Orfeo's Winchester." },
    { sym: "A", name: "Villainy (Lack)", culhwch: "present", pwyll: "present", gawain: "present", orfeo: "present",
      gloss: "Culhwch: the stepmother's curse. Pwyll: the courtesy debt at Glyn Cuch (and later Gwawl's claim, and later the lost son — three lacks in one tale). Gawain: the Green Knight's challenge. Orfeo: the abduction. Each opens a lack that the rest fills." },
    { sym: "B", name: "Mediation / dispatch", culhwch: "present", pwyll: "present", gawain: "present", orfeo: "present",
      gloss: "Culhwch dispatched by his father; Pwyll dispatched by Arawn; Gawain dispatches himself (steps from the table); Orfeo dispatches himself (abdication speech). The Welsh tales have true mediation (a figure speaking the call); the English tales have self-mediation." },
    { sym: "C", name: "Counteraction begins", culhwch: "present", pwyll: "present", gawain: "present", orfeo: "present",
      gloss: "All four heroes accept the call. In Gawain instant (the axe-taking); in Culhwch deliberative; in Pwyll instant and pragmatic (the year-exchange handshake); in Orfeo after ten years of grief." },
    { sym: "↑", name: "Departure", culhwch: "present", pwyll: "present", gawain: "present", orfeo: "present",
      gloss: "All four: the hero leaves home. Pwyll departs for Annwn; Teirnon later departs for Arberth — Pwyll has the doubled departure structure." },
    { sym: "D", name: "Donor's first function", culhwch: "present", pwyll: "present", gawain: "present", orfeo: "present",
      gloss: "Culhwch: the six extraordinary companions are themselves the agents. Pwyll: Arawn IS the donor (and later Rhiannon is donor of the bag). Gawain: Bertilak's bargain. Orfeo: the Fairy King's rash boon. Strikingly often, the donor and the antagonist are the same figure." },
    { sym: "F", name: "Receipt of magical agent", culhwch: "present", pwyll: "present", gawain: "present", orfeo: "present",
      gloss: "Culhwch: the companions. Pwyll: Arawn's form (a body to wear for a year), and later Rhiannon's never-filling bag. Gawain: the green girdle. Orfeo: the harp. Each tale's agent is its central object — a band, a body and a bag, a sash, an instrument." },
    { sym: "G", name: "Guidance to the goal", culhwch: "present", pwyll: "present", gawain: "present", orfeo: "present",
      gloss: "Culhwch: Cynddylig the never-lost guide. Pwyll: Arawn brings him to Annwn's boundary; Rhiannon brings him to her father's court. Gawain: the Wirral road. Orfeo: the hawking ladies." },
    { sym: "H", name: "Struggle", culhwch: "present", pwyll: "present", gawain: "present", orfeo: "present",
      gloss: "Culhwch: combat (the boar hunt, the Black Witch). Pwyll: the duel at the ford with Hafgan; later the bag-trick at the feast. Gawain: standing still under the axe. Orfeo: a verbal contest of speech-acts. Four forms of contest — combat, duel, endurance, rhetoric." },
    { sym: "J", name: "Victory", culhwch: "present", pwyll: "present", gawain: "present", orfeo: "present",
      gloss: "Culhwch: boar driven into the sea; Witch beheaded. Pwyll: Hafgan defeated with one stroke; Gwawl bagged. Gawain: he survives the axe. Orfeo: the Fairy King yields by his own word." },
    { sym: "K", name: "Liquidation of lack", culhwch: "present", pwyll: "present", gawain: "present", orfeo: "present",
      gloss: "Culhwch: the treasures and the bride won. Pwyll: Annwn restored, Rhiannon won, Pryderi recovered (each of his three lacks resolved on its own arc). Gawain: the bargain discharged. Orfeo: Heurodis recovered." },
    { sym: "ε", name: "Reconnaissance", culhwch: "absent", pwyll: "minimal", gawain: "present", orfeo: "present",
      gloss: "Gawain and Orfeo have full scouting beats (the Green Knight's hall-survey, the two armed knights in Heurodis's vision). Pwyll has minimal reconnaissance — Arawn knows Pwyll's name before speaking, Teirnon recognises Pwyll's face in the child. Culhwch has no proper reconnaissance at all." },
    { sym: "η", name: "Trickery", culhwch: "absent", pwyll: "present", gawain: "present", orfeo: "minimal",
      gloss: "Gawain is BUILT on trickery (the Green Knight's bluff, the exchange-of-winnings, the lady's wooing). Pwyll uses trickery on the hero's side: the beggar-disguise and the never-filling bag that trap Gwawl. Orfeo's minstrel-disguise is sincere as far as it goes. Culhwch has no scheming at all." },
    { sym: "M", name: "Difficult task", culhwch: "present", pwyll: "minimal", gawain: "present", orfeo: "inverted",
      gloss: "Culhwch: the ~40 anoethau. Gawain: the temptation triptych. Pwyll: minimal — the chaste-bed beat is a single discrete task, not a catalogue. Orfeo: the hero tests the steward (M inverted — the hero sets the test rather than receiving it). Four registers of the same beat: list, triptych, vow, inversion." },
    { sym: "↓", name: "Return", culhwch: "absent", pwyll: "present", gawain: "present", orfeo: "present",
      gloss: "Culhwch stays at the wedding feast — no return arc. Pwyll returns from Annwn to Dyfed; later Teirnon brings the child to Arberth; later Pwyll returns to a court missing his queen. Gawain rides back to Camelot. Orfeo walks back to Winchester. Pwyll has the most layered return-structure of the four." },
    { sym: "o", name: "Unrecognised arrival", culhwch: "absent", pwyll: "present", gawain: "absent", orfeo: "present",
      gloss: "Pwyll and Orfeo both carry the unrecognised-return motif. Pwyll arrives at Gwawl's feast in heavy old rags asking for a bag's-worth of food; Orfeo arrives at Winchester as a wandering harper. Two Insular instances of the Odyssean shape." },
    { sym: "Q", name: "Recognition", culhwch: "present", pwyll: "present", gawain: "present", orfeo: "present",
      gloss: "Each poem has its recognition scene. Pwyll has the most decisive: Teirnon looks at the boy he raised and sees Pwyll's face — recognition by resemblance. Goreu beheads Ysbaddaden; Bertilak reveals himself to Gawain; Orfeo reveals himself to the steward in the conditional." },
    { sym: "T", name: "Transfiguration", culhwch: "present", pwyll: "present", gawain: "present", orfeo: "present",
      gloss: "Culhwch wins his bride; Pwyll changes name to <em>Pen Annwn</em> after the year-exchange; Gawain dons the green sash; Orfeo is bathed, shaved, re-crowned." },
    { sym: "W", name: "Wedding (or restoration)", culhwch: "present", pwyll: "present", gawain: "absent", orfeo: "present",
      gloss: "Culhwch closes on a wedding; Pwyll closes on a married couple, a recovered son, and an heir secured (a triple restoration); Orfeo closes on a re-coronation of a still-married couple. Gawain alone REFUSES the wedding explicitly — Bertilak invites, Gawain declines. The wedding's absence in Gawain is one of the poem's defining structural moves." },
    { sym: "U", name: "Punishment of the villain", culhwch: "present", pwyll: "minimal", gawain: "absent", orfeo: "absent",
      gloss: "Culhwch ends with Goreu beheading Ysbaddaden — the only full punishment. Pwyll punishes Gwawl partially (struck while in the bag) and then explicitly releases him on a sworn no-vengeance — a deliberate refusal of the full punishment-arc. Neither English poem punishes its antagonist at all. A clear gradient: Welsh tradition punishes, English tradition lets the antagonist persist as another kind of power; Pwyll sits between." },
    { sym: "I", name: "Branding", culhwch: "absent", pwyll: "absent", gawain: "present", orfeo: "absent",
      gloss: "Gawain alone carries a wound back. The other three return unmarked — Culhwch was always the catalyst, not the doer; Pwyll is restored to his own body without a sign; Orfeo's beard and rags are washed off." },
    { sym: "Pr Rs", name: "Pursuit & Rescue", culhwch: "absent", pwyll: "absent", gawain: "absent", orfeo: "absent",
      gloss: "None of the four poems uses the chase. The Welsh quests hunt but are not chased; the English tales walk away from the Otherworld unhindered. A shared structural absence across the medieval Insular tradition." },
    { sym: "L Ex", name: "False-hero / Exposure of impostor", culhwch: "absent", pwyll: "present", gawain: "absent", orfeo: "absent",
      gloss: "Pwyll has the corpus's only proper L/Ex pair — the six women lay a false claim against Rhiannon (L: false hero presents an unfounded claim); Teirnon's arrival with the boy exposes the claim (Ex). Neither English poem stages this; Culhwch never returns. The Insular wonder-tale's calumniated-wife pattern fires once, here." },
  ],

  archetypeIntro: "Six character archetypes that recur across the four poems, each filled by a different figure. The role-slots are remarkably consistent; what shifts is the moral occupant and the dramatic weight. Pwyll's most distinctive contribution to this grid is the seventh row, the calumniated wife — a figure none of the other three tales puts on stage.",
  archetypes: [
    { role: "The hero",
      culhwch: { who: "Culhwch", note: "A king's son and Arthur's cousin; less a doer than a catalyst." },
      pwyll:   { who: "Pwyll (and Teirnon)", note: "Prince of Dyfed in Movements I–IV; in Movements V–VI the structural hero is Teirnon, who rescues the foal and recovers the boy. The tale runs two heroes in sequence." },
      gawain:  { who: "Sir Gawain", note: "Arthur's nephew; the pentangle-knight; the youngest at the high table." },
      orfeo:   { who: "Sir Orfeo", note: "King of Winchester; the harper before all other roles." },
      gloss: "Each tale's hero is a king or king-adjacent young man. Pwyll is unique in fielding two heroes in succession — the young prince of the first half is replaced by the kindly older lord of the second. Only Orfeo is the king in his own right, and only Orfeo's hero brings the magical agent (the harp) with him; Pwyll, Culhwch and Gawain each receive theirs." },

    { role: "The taken / the goal",
      culhwch: { who: "Olwen", note: "Daughter of Ysbaddaden; coaches Culhwch to out-promise her father." },
      pwyll:   { who: "Rhiannon (and Pryderi)", note: "Rhiannon as bride-on-the-horse, won by asking; Pryderi as stolen infant recovered after seven years. Two goals across the tale's two halves — a queen, then a son." },
      gawain:  { who: "—", note: "No taken figure; the lack is moral, not personal." },
      orfeo:   { who: "Heurodis", note: "Queen abducted into Faerie at noon under the ympe-tree; speaks twice in the whole poem." },
      gloss: "Three of the four have a goal-figure; Gawain explicitly refuses one. Pwyll has a doubled goal — Rhiannon won-by-asking and Pryderi recovered-by-recognition. Olwen is prize-by-quest; Heurodis is prize-by-recovery; Rhiannon is both, across the two halves of her tale." },

    { role: "The Otherworld king (antagonist who is also host)",
      culhwch: { who: "Ysbaddaden Bencawr", note: "Chief of Giants; fated to die when his daughter weds; sets the impossible tasks." },
      pwyll:   { who: "Arawn (with Hafgan)", note: "Arawn IS the host — courteous, kingly, fair-dealing. The antagonism is structural (Pwyll owes him courtesy-debt) not moral. Hafgan stands in for the absent antagonist; Arawn keeps his throne, his queen, and his friendship with Pwyll." },
      gawain:  { who: "Bertilak / the Green Knight", note: "Antagonist, host, and donor fused in one figure. Bound to honour, but bound." },
      orfeo:   { who: "The Fairy King", note: "Otherworld king of his own kingdom. Bound by his own word; not punished, only constrained." },
      gloss: "Every tale has a figure who is at once antagonist and host. Culhwch's is a doomed giant; Gawain's is a fused triple-role; Orfeo's is a king who keeps his throne; Pwyll's is the only one who becomes a friend. Four theologies of the antagonist — and Pwyll the only one that ends in alliance." },

    { role: "The powers behind",
      culhwch: { who: "The stepmother (sets the geis)", note: "Lays the destiny on Culhwch out of spite; never reappears." },
      pwyll:   { who: "(unseen) — the foal-and-baby thief", note: "The hand that reaches through Teirnon's window for the foal — and presumably the same power that steals Pryderi from Arberth on May-eve — is never named or shown. Only its severed arm remains. Pwyll alone has an antagonist that is structural rather than dramatised." },
      gawain:  { who: "Morgan le Fay", note: "Off-stage prime mover of the whole test; in age-disguise at the castle; named at the reveal." },
      orfeo:   { who: "(none)", note: "The Fairy King acts on his own behalf; no off-stage mover." },
      gloss: "Two of the four have a named figure behind the figure (the stepmother and Morgan, both women, both work by spoken destiny). Pwyll has the figure but refuses to name it; Orfeo refuses the whole role. The Welsh and English traditions converge on the demoted-goddess-as-schemer where they don't simply refuse the layer." },

    { role: "The threshold helper",
      culhwch: { who: "Custennin & his wife", note: "Fire-breathing herdsman and Culhwch's aunt; warn the company; hide Goreu in a stone chest." },
      pwyll:   { who: "Teirnon Twrf Liant", note: "Lord of Gwent Is-Coed; raises the lost child as his own son for seven years; recognises Pwyll's face in the boy and brings him back. The keeper-of-the-lost-child, the most active threshold-helper in the corpus." },
      gawain:  { who: "Mary on the inside of the shield", note: "Patroness summoned in the Christmas Eve prayer; the castle appears in answer." },
      orfeo:   { who: "The Winchester beggar", note: "Houses Orfeo and Heurodis at the town's edge; lends the disguise; quiet hub of the recognition." },
      gloss: "An aged or marginal figure at the threshold turns the wheel in all four. Teirnon is the most dramatic of them — he doesn't merely warn or shelter, he keeps the lost prince's body for years. Each tradition draws on what is available to it: Welsh kin-network (Culhwch, Pwyll), English Marian piety (Gawain), English roadside almsgiving (Orfeo)." },

    { role: "The faithful one (rewarded)",
      culhwch: { who: "Goreu the avenger", note: "Hidden in the stone chest by his mother; emerges to behead Ysbaddaden and take the giant's lands." },
      pwyll:   { who: "Pryderi (and the Dyfed nobles)", note: "Pryderi as the recovered son who succeeds Pwyll and inherits the seven cantref of Dyfed (and later three more, and then four more). The Dyfed nobles who waited a year while Arawn ruled in Pwyll's body are tacitly rewarded with the king they had thought they had." },
      gawain:  { who: "—", note: "No faithful retainer figure in the same sense; the court itself adopts the green sash but no individual is singled out for reward." },
      orfeo:   { who: "The high steward", note: "Holds the kingdom honestly for ten years; tested by the lying tale; rewarded with the throne after Orfeo's day." },
      gloss: "Three of the four close on the reward of a faithful figure (Goreu inherits the giant's lands, Pryderi inherits Pwyll's, the steward inherits Orfeo's). Gawain has no equivalent. The three tales that walk back to a court at the end reward the faithful one; the tale that does not return offers no reward." },

    { role: "The wrongfully accused (Pwyll's contribution)",
      culhwch: { who: "—", note: "No accused figure; the tale's moral vector is straightforward." },
      pwyll:   { who: "Rhiannon", note: "Falsely accused of killing her son by six terrified attendants; refuses to denounce them; accepts her penance at the gate for seven years rather than abandon her marriage. Exonerated by Teirnon's evidence. The corpus's only proper calumniated-wife arc." },
      gawain:  { who: "—", note: "No accused figure; the test runs at the host's castle, not in court." },
      orfeo:   { who: "—", note: "Heurodis is taken, not accused; she vanishes from the poem until the rescue." },
      gloss: "Pwyll alone stages an accused queen — and stages her with structural gravity, putting her at the centre of two whole movements. The ATU 707 calumniated-wife pattern is the Welsh tale's distinctive contribution to the four-tale archetype grid: a role-slot the other three tales simply do not fill." },
  ],
};
