/* The cross-tale layer — three tales side by side.
   Annotates the same call-numbers across Culhwch, Gawain, and Orfeo so the
   comparative payoff of the annotation stack becomes visible at a glance.
   Three tables: shared motifs (Thompson codes), shared Propp functions
   (with absences flagged where present), and shared character archetypes.
   Loaded after data.js; attaches to window.PENDRAGON. */
window.PENDRAGON = window.PENDRAGON || {};
window.PENDRAGON.crosswalk = {
  intro: "With three poems now in the same apparatus — Culhwch (Welsh, c. 1100), Sir Gawain and the Green Knight (Middle English, c. 1380), and Sir Orfeo (Middle English, c. 1300) — the comparative layer the motif index and the story graph open up can finally do its work. Below: the same Thompson Motif codes laid against all three poems, the same Propp functions laid against all three, and a small map of character archetypes that recur in all three. Where a code is present in two or three tales the cross-reference is given; where it is sharply absent from one and central to another, the absence is named. Three tales is the minimum where structural assertions get traction; this is the first pass.",
  tales: [
    { id: "culhwch", title: "Culhwch ac Olwen", short: "Culhwch", sigil: "🐗", href: "/culhwch/", color: "#7fb37f" },
    { id: "gawain",  title: "Sir Gawain and the Green Knight", short: "Gawain", sigil: "🪓", href: "/gawain/", color: "#c97f9a" },
    { id: "orfeo",   title: "Sir Orfeo", short: "Orfeo", sigil: "🎵", href: "/orfeo/", color: "#6fa8c9" },
  ],

  motifIntro: "Thompson Motif codes shared across the three poems. Sorted by how many tales carry each: the codes at the top form the small structural backbone the three poems share. The codes at the bottom (single-tale) show what each poem brings uniquely into the comparison.",
  motifs: [
    // ── In all three ─────────────────────────────────────────────────
    { code: "M223", name: "The rash promise / blank check",
      culhwch: { passages: [2], note: "Arthur grants whatever Culhwch will name (save a reserved few treasures) before he hears the request." },
      gawain:  { passages: [1, 3], note: "Arthur accepts the Green Knight's terms unheard; Bertilak's exchange-of-winnings struck on the same form." },
      orfeo:   { passages: [5], note: "Fairy King: <em>now aske of me what it be — largelich Ichil the pay; now speke, and tow might asay.</em> The hinge of the rescue." },
      gloss: "The single most ecumenical motif in the set. All three poems run on the rash boon — promise asked in the fairest possible form and then leveraged: in Culhwch to set the quest, in Gawain to extract the year-and-a-day, in Orfeo to recover the queen. The medieval Insular tradition is built on the binding force of the spoken word." },

    { code: "Z71.1", name: "Formulistic number: three",
      culhwch: { passages: [2, 7, 10], note: "Three shouts at Arthur's gate; three poisoned spears thrown back at Ysbaddaden; the boar Twrch hunted by Arthur and his men across three countries." },
      gawain:  { passages: [1, 3, 4], note: "Three blows at the chapel, three hunts, three temptations, three exchanges of winnings, three days, three kisses. Z71.1 is pervasive." },
      orfeo:   { passages: [3, 5], note: "Three apparitions of the fae (hunt, host, dance); three laments; three harpings (wild beasts, Fairy King's court, the steward's hall). More sparing than Gawain." },
      gloss: "All three lean on triadic structure, but with sharply different densities. Gawain is built triadically at every level; Orfeo uses the three in selected places; Culhwch lets the threes share space with nines and other formulistic numbers." },

    { code: "A186", name: "Demoted divinity walking as character",
      culhwch: { passages: [8, 9], note: "Mabon son of Modron — \"Divine Son\" of \"Divine Mother\" — the British god Maponos demoted to imprisoned heir. Gwyn ap Nudd, king of Annwn." },
      gawain:  { passages: [4], note: "Morgan le Fay named \"Morgne the goddess\" by Bertilak at the reveal; the Green Knight with his vegetation-god iconography." },
      orfeo:   { passages: [1, 2, 5], note: "Pluto and Juno named as Orfeo's ancestors, immediately glossed: <em>that sum time were as godes y hold</em> — were <em>held</em> for gods. The Fairy King allowed to stand as <em>king o fairy</em> without Christian framing." },
      gloss: "Each poem manages classical or older divinity differently. Culhwch lets old gods walk as heroes (Mabon's mythological lineage is part of his power). Gawain names Morgan a goddess as part of the unmasking. Orfeo opens by euhemerising Pluto and Juno explicitly — and then lets the Fairy King retain divine dignity under a different name." },

    { code: "F252", name: "The Otherworld and its court",
      culhwch: { passages: [8], note: "Annwn and its lord Gwyn ap Nudd, demanded for the hunt; behind the whole tradition stands Avalon." },
      gawain:  { passages: [2, 3, 4], note: "Hautdesert as Morgan's court of enchantment — Bertilak, the lady, the ancient lady, the household." },
      orfeo:   { passages: [2, 3, 4, 5], note: "A hundred snow-white knights and a hundred milk-white damsels; the Fairy King and Queen on thrones in a tabernacle of light; porter, courtiers, the half-taken." },
      gloss: "Each poem stages an Otherworld court differently. Culhwch's is offstage — Annwn invoked, Gwyn drafted. Gawain's is hidden in plain sight as a Christmas castle. Orfeo's is the most fully imagined of the three — geography, architecture, retinue, court protocol all named — and the most ecumenically Insular." },

    { code: "N825.3", name: "Old person as helper at the threshold",
      culhwch: { passages: [4, 5], note: "Custennin the fire-breathing herdsman and his wife (Culhwch's aunt by marriage), who hide Goreu in a stone chest and warn the company of the giant's terms." },
      gawain:  { passages: [2, 3, 4], note: "The \"auncian lady\" beside the young wife at Hautdesert — Morgan le Fay in age-disguise, honoured at table without ever being recognised." },
      orfeo:   { passages: [6], note: "The Winchester beggar at the town's edge, in his narrow hut. Houses Orfeo and Heurodis, tells the city's news, lends the borrowed clothes." },
      gloss: "An aged figure at the threshold turns out to hold the key in each tale. The role's moral colouring differs sharply: Custennin's wife is a helper, Morgan is the prime mover of the test, the beggar is a quiet host. Same structural slot, three different moral occupants." },

    { code: "F151.1", name: "Perilous path to the Otherworld",
      culhwch: { passages: [4], note: "The fortress that comes no closer however long you walk — the Otherworld holding its distance." },
      gawain:  { passages: [2], note: "The wild road through North Wales and the Wirral — wolves, wodwos, ice in the armour, the Christmas Eve prayer." },
      orfeo:   { passages: [4], note: "Three miles through solid stone in a rock-cleft. Orfeo spares neither stub nor stone." },
      gloss: "Three different terrain-shapes for the same motif. The Welsh tradition uses the unreachable fort — the path is its impossibility. The Gawain-poet's tradition uses the winter wilderness ride. Orfeo uses the cleft-in-the-rock, the most decisively spatial. Each tradition makes the threshold what its geography most fears." },

    { code: "H1556", name: "Test of fidelity",
      culhwch: { passages: [8, 9, 10, 11], note: "The impossible tasks of the anoethau test Culhwch (in fact Arthur) and his band — by completing every one, faithfulness to the bargain is proved." },
      gawain:  { passages: [3], note: "The exchange-of-winnings — three days of paralleled hunts and bedroom encounters. The test of whether the guest will give back honestly all he gained. Gawain passes twice; fails once, by a hand's-breadth." },
      orfeo:   { passages: [6], note: "Inverted — the hero tests the steward. The lying tale of his death; the steward's total grief; the conditional reveal." },
      gloss: "All three poems revolve around a test of loyalty. The position of hero is different in each: Culhwch as the tested party in absence (Arthur and the band test for him); Gawain as the tested party in person; Orfeo as the testing party against his own servant." },

    // ── In two of three ─────────────────────────────────────────────
    { code: "F156", name: "Door to the Otherworld at a marked place",
      culhwch: false,
      gawain:  { passages: [4], note: "The Green Chapel turns out to be a hollow grass-grown barrow with three openings, beside a steaming brook." },
      orfeo:   { passages: [4], note: "A great rock with a vertical cleft, three miles through solid stone, onto the bright country." },
      gloss: "A motif Gawain and Orfeo share against Culhwch. Both English poems mark the threshold with a particular place; the Welsh tale's threshold is the geometry of unreachability, not a door. The English tradition seems to need a place; the Welsh tradition prefers a distance." },

    { code: "K1810", name: "Deception by disguise",
      culhwch: { passages: [11], note: "Cei as sword-burnisher to enter Wrnach's hall — the giant's death by his own blade." },
      gawain:  { passages: [1, 2, 3, 4], note: "Three masks: Bertilak is the Green Knight, the ancient lady is Morgan, the lady acts at Bertilak's direction. The poem keeps the audience inside Gawain's ignorance for two whole Fitts." },
      orfeo:   { passages: [4, 5, 6], note: "Orfeo as minstrel at the Fairy King's gate, as harper-from-heathenness to the steward, in borrowed beggar's clothes at Winchester." },
      gloss: "Gawain and Orfeo are built on disguise; Culhwch uses it once as a tactical trick. The two English poems use disguise in opposite directions: Gawain has disguise on the antagonist's side (the hero is fooled); Orfeo has disguise on the hero's side (the antagonist is met without recognition). Same motif, opposite moral vector." },

    { code: "N777", name: "Adventure follows the hunt",
      culhwch: false,
      gawain:  { passages: [3], note: "Three days of paralleled hunts cross-cut with three bedroom encounters; the hunt outside structurally summons and pays for the test inside." },
      orfeo:   { passages: [3, 4], note: "The sixty hawking ladies are an Otherworld hunt; Orfeo follows them through the rock-cleft. The hunt-as-threshold preserved cleanly." },
      gloss: "The hunt as plot-engine in Gawain and Orfeo, absent from Culhwch (which has its own great hunt, but it is the climax of the quest, not the conjuring of an adventure)." },

    { code: "F771.6", name: "Castle in the wilderness / of crystal",
      culhwch: false,
      gawain:  { passages: [2], note: "Hautdesert appears in the trees in answer to Gawain's prayer to Mary on Christmas Eve — \"a castle full comely, gleamed and shone.\"" },
      orfeo:   { passages: [4], note: "The crystal castle of the Otherworld: outer wall of clear crystal, a hundred towers, red-gold buttresses, precious-stone chambers, the worst pillar of burnished gold." },
      gloss: "Both English poems produce a wonder-castle out of the wilderness. Gawain's is rationalised as a great medieval fortress; Orfeo's is unembarrassedly fairy-architecture. Two registers of the same astonishment." },

    { code: "F375", name: "Mortal returns from the Otherworld",
      culhwch: false,
      gawain:  { passages: [4], note: "Gawain returns marked — nick on the neck, the green sash bound under his left arm — a partial return." },
      orfeo:   { passages: [5, 6], note: "Heurodis returns unchanged; Orfeo returns altered only by ten years of mourning that the bath and shaving undo. A full return." },
      gloss: "The Otherworld returns with different costs. Gawain comes back changed; Orfeo and Heurodis come back themselves. The contrast is exactly the moral architecture of the two poems: Gawain's test marks the hero; Orfeo's rescue does not." },

    { code: "H1010", name: "Impossible tasks",
      culhwch: { passages: [8], note: "The ~40 anoethau Ysbaddaden imposes on pain of death — clear and reap a hill in a day, fetch the comb between the boar's ears, win the cauldron from Ireland." },
      gawain:  false,
      orfeo:   false,
      gloss: "The signature motif of Culhwch and absent from both English poems. The wonder-tale's task-quest belongs to the older Welsh tradition; the English romances substitute tests of honour and rash bargains for impossible labours." },

    { code: "G530.2", name: "Help from the ogre's daughter",
      culhwch: { passages: [6], note: "Olwen coaches Culhwch on how to out-promise her giant father — the precise motif at its purest." },
      gawain:  false,
      orfeo:   false,
      gloss: "Another Culhwch signature. The motif requires a particular romantic shape — bride helping suitor against father — that neither English poem reproduces. Both English poems have their queens taken or tested, not won from a parent." },

    // ── Distinctively single ───────────────────────────────────────
    { code: "F407", name: "Talking severed head",
      culhwch: false,
      gawain:  { passages: [1], note: "The Green Knight's head, held in his hand from horseback, turns its eyes on Camelot and speaks the rules of the return-match." },
      orfeo:   false,
      gloss: "Gawain's distinctive opening miracle. The motif is older — see Bran the Blessed in the Welsh Mabinogi — but Gawain's poem is the canonical Insular literary use." },

    { code: "F379.1", name: "The half-taken — body remains as if dead, self in fairyland",
      culhwch: false,
      gawain:  false,
      orfeo:   { passages: [4], note: "The yard inside the Otherworld castle: figures held in the postures they were taken in — some headless, some bound and mad, women in childbed, sleeping at noon. <em>Thought dede and nare nought.</em>" },
      gloss: "Orfeo's most distinctive contribution to the Otherworld tradition. Neither Culhwch nor Gawain has anything quite like the yard of the half-taken; it is one of the most uncanny passages in medieval English and a motif Thompson's index does not fully cover." },

    { code: "Z356", name: "The unique exception (named within a catalogue)",
      culhwch: false,
      gawain:  { passages: [2], note: "The pentangle — five points each twined into the next — named explicitly <em>the endeles knot</em> within the catalogue of arming." },
      orfeo:   { passages: [4], note: "<em>Al that lond was ever light</em> — the ever-light Otherworld, named separately from the catalogue of the castle's wonders." },
      gloss: "Both English poems use the same rhetorical device: stop a catalogue of wonders to mark one wonder as unique among them. The Pearl-Poet does it with the pentangle, the Orfeo poet with the ever-light. A particular Middle English habit of attention." },
  ],

  proppIntro: "The 31 Propp functions laid against the three poems. <em>✓</em> marks present; <em>·</em> marks the function as sharply absent (named in our story graphs as a meaningful refusal). The dense top — the wonder-tale's quest spine — is present in all three; the variations in the lower section are where each poem's individual project starts to surface.",
  propp: [
    { sym: "α", name: "Initial situation", culhwch: "present", gawain: "present", orfeo: "present",
      gloss: "All three poems open by introducing the court and the family — Cilydd & Goleuddydd, Arthur's Camelot, Orfeo's Winchester." },
    { sym: "A", name: "Villainy (Lack)", culhwch: "present", gawain: "present", orfeo: "present",
      gloss: "Culhwch: the stepmother's curse. Gawain: the Green Knight's challenge. Orfeo: the abduction. Each poem opens a lack that the rest fills." },
    { sym: "B", name: "Mediation / dispatch", culhwch: "present", gawain: "present", orfeo: "present",
      gloss: "Culhwch is dispatched by his father; Gawain dispatches himself (steps from the table); Orfeo dispatches himself (abdication speech). The Welsh tale has true mediation; the English tales have self-mediation." },
    { sym: "C", name: "Counteraction begins", culhwch: "present", gawain: "present", orfeo: "present",
      gloss: "All three heroes accept the call. In Gawain the acceptance is instant (the axe-taking); in Culhwch deliberative; in Orfeo it comes after ten years of grief." },
    { sym: "↑", name: "Departure", culhwch: "present", gawain: "present", orfeo: "present",
      gloss: "All three: the hero leaves home." },
    { sym: "D", name: "Donor's first function", culhwch: "present", gawain: "present", orfeo: "present",
      gloss: "Culhwch: the six extraordinary companions are themselves the magical agents. Gawain: Bertilak's bargain. Orfeo: the Fairy King's rash boon. Three different donor-figures: Arthur, the antagonist himself, the antagonist again." },
    { sym: "F", name: "Receipt of magical agent", culhwch: "present", gawain: "present", orfeo: "present",
      gloss: "Culhwch: the companions. Gawain: the green girdle. Orfeo: the harp (brought with him, kept in a hollow tree). Each tale's agent is its central object: a band, a sash, an instrument." },
    { sym: "G", name: "Guidance to the goal", culhwch: "present", gawain: "present", orfeo: "present",
      gloss: "Culhwch: Cynddylig the never-lost guide. Gawain: the Wirral road. Orfeo: the hawking ladies." },
    { sym: "H", name: "Struggle", culhwch: "present", gawain: "present", orfeo: "present",
      gloss: "Culhwch: combat (the boar hunt, the Black Witch). Gawain: standing still under the axe. Orfeo: a verbal contest of speech-acts. Three different forms of contest — combat, endurance, rhetoric." },
    { sym: "J", name: "Victory", culhwch: "present", gawain: "present", orfeo: "present",
      gloss: "Culhwch: boar driven into the sea; Witch beheaded. Gawain: he survives the axe. Orfeo: the Fairy King yields by his own word." },
    { sym: "K", name: "Liquidation of lack", culhwch: "present", gawain: "present", orfeo: "present",
      gloss: "Culhwch: the treasures and the bride won. Gawain: the bargain discharged. Orfeo: Heurodis recovered." },
    { sym: "ε", name: "Reconnaissance", culhwch: "absent", gawain: "present", orfeo: "present",
      gloss: "Gawain and Orfeo have a scouting beat (the Green Knight's hall-survey, the two armed knights in Heurodis's vision). Culhwch has no proper reconnaissance — the deception cluster is absent from the Welsh tale." },
    { sym: "η", name: "Trickery", culhwch: "absent", gawain: "present", orfeo: "minimal",
      gloss: "Gawain is BUILT on trickery (the Green Knight's bluff, the exchange-of-winnings, the lady's wooing). Orfeo's minstrel-disguise is sincere as far as it goes. Culhwch has no scheming villain at all." },
    { sym: "M", name: "Difficult task", culhwch: "present", gawain: "present", orfeo: "inverted",
      gloss: "Culhwch: the ~40 anoethau. Gawain: the temptation triptych. Orfeo: the hero tests the steward (M inverted — the hero sets the test rather than receiving it)." },
    { sym: "↓", name: "Return", culhwch: "absent", gawain: "present", orfeo: "present",
      gloss: "Culhwch stays at the wedding feast — there is no return arc. Gawain rides back to Camelot. Orfeo walks back to Winchester." },
    { sym: "o", name: "Unrecognised arrival", culhwch: "absent", gawain: "absent", orfeo: "present",
      gloss: "Only Orfeo carries the classical Odyssean unrecognised-return motif. Gawain returns honoured; Culhwch never returns." },
    { sym: "Q", name: "Recognition", culhwch: "present", gawain: "present", orfeo: "present",
      gloss: "Each poem has its recognition scene: Goreu beheads Ysbaddaden (recognition of him as the avenger); Bertilak reveals himself to Gawain; Orfeo reveals himself to the steward in the conditional." },
    { sym: "T", name: "Transfiguration", culhwch: "present", gawain: "present", orfeo: "present",
      gloss: "Culhwch wins his bride; Gawain dons the green sash; Orfeo is bathed, shaved, re-crowned." },
    { sym: "W", name: "Wedding (or restoration)", culhwch: "present", gawain: "absent", orfeo: "present",
      gloss: "Culhwch's tale closes on a wedding. Orfeo's closes on a re-coronation of a still-married couple. Gawain's REFUSES the wedding explicitly — Bertilak invites; Gawain declines. The wedding's absence in Gawain is one of the poem's defining structural moves." },
    { sym: "U", name: "Punishment of the villain", culhwch: "present", gawain: "absent", orfeo: "absent",
      gloss: "Culhwch ends with Goreu beheading Ysbaddaden. Neither English poem punishes its antagonist. Bertilak is unmasked but not condemned; the Fairy King is bound but not even unmasked. The Welsh tale closes the villain's account; the English tales let him persist as another kind of power." },
    { sym: "I", name: "Branding", culhwch: "absent", gawain: "present", orfeo: "absent",
      gloss: "Gawain alone carries a wound back. Culhwch is unmarked (he was always the catalyst, not the doer). Orfeo's beard and rags are washed off; he is restored without a sign." },
    { sym: "Pr Rs", name: "Pursuit & Rescue", culhwch: "absent", gawain: "absent", orfeo: "absent",
      gloss: "None of the three poems uses the chase. The Welsh quest hunts but is not chased; the English tales walk away from the Otherworld unhindered. A shared structural absence across the medieval Insular tradition." },
    { sym: "L Ex", name: "False-hero / Exposure of impostor", culhwch: "absent", gawain: "absent", orfeo: "absent",
      gloss: "No impostor claims the hero's prize in any of the three tales. The Exposure function fires in Gawain and Orfeo reflexively (Gawain exposes himself; Orfeo exposes the steward's faithfulness) but never against a usurper. A second shared absence." },
  ],

  archetypeIntro: "Six character archetypes that recur in all three poems, each filled by a different figure. The role-slots are remarkably consistent; what shifts is the moral occupant and the dramatic weight.",
  archetypes: [
    { role: "The hero",
      culhwch: { who: "Culhwch", note: "A king's son and Arthur's cousin; less a doer than a catalyst." },
      gawain:  { who: "Sir Gawain", note: "Arthur's nephew; the pentangle-knight; the youngest at the high table." },
      orfeo:   { who: "Sir Orfeo", note: "King of Winchester; the harper before all other roles." },
      gloss: "Each tale's hero is a king or king-adjacent young man. Only Orfeo is the king in his own right — and only Orfeo's hero brings the magical agent (the harp) with him rather than receiving it." },

    { role: "The taken / the goal",
      culhwch: { who: "Olwen", note: "Daughter of Ysbaddaden; coaches Culhwch to out-promise her father." },
      gawain:  { who: "—", note: "No taken figure; the lack is moral, not personal." },
      orfeo:   { who: "Heurodis", note: "Queen abducted into Faerie at noon under the ympe-tree; speaks twice in the whole poem." },
      gloss: "Culhwch and Orfeo have a woman-as-goal; Gawain explicitly refuses one. Olwen and Heurodis play different versions of the role: Olwen is the prize-by-quest, Heurodis is the prize-by-recovery." },

    { role: "The Otherworld king (antagonist who is also host)",
      culhwch: { who: "Ysbaddaden Bencawr", note: "Chief of Giants; fated to die when his daughter weds; sets the impossible tasks." },
      gawain:  { who: "Bertilak / the Green Knight", note: "Antagonist, host, and donor fused in one figure. Bound to honour, but bound." },
      orfeo:   { who: "The Fairy King", note: "Otherworld king of his own kingdom. Bound by his own word; not punished, only constrained." },
      gloss: "Every tale has a figure who is at once antagonist and host. Culhwch's is a doomed giant; Gawain's is a fused triple-role; Orfeo's is a king who keeps his throne. Three different theologies of the antagonist." },

    { role: "The powers behind",
      culhwch: { who: "The stepmother (sets the geis)", note: "Lays the destiny on Culhwch out of spite; never reappears." },
      gawain:  { who: "Morgan le Fay", note: "Off-stage prime mover of the whole test; in age-disguise at the castle; named at the reveal." },
      orfeo:   { who: "(none)", note: "The Fairy King acts on his own behalf; no off-stage mover." },
      gloss: "Two of the three have a figure behind the figure. The stepmother and Morgan are both women, both work by spoken destiny, and both are demoted from goddess to schemer in their respective traditions. Orfeo refuses this layer: the Fairy King is final cause as well as immediate one." },

    { role: "The threshold helper",
      culhwch: { who: "Custennin & his wife", note: "Fire-breathing herdsman and Culhwch's aunt; warn the company; hide Goreu in a stone chest." },
      gawain:  { who: "Mary on the inside of the shield", note: "Patroness summoned in the Christmas Eve prayer; the castle appears in answer." },
      orfeo:   { who: "The Winchester beggar", note: "Houses Orfeo and Heurodis at the town's edge; lends the disguise; quiet hub of the recognition." },
      gloss: "An aged or marginal figure at the threshold turns the wheel in all three. Each tradition draws on what is available to it: Welsh kin-network, English Marian piety, English roadside almsgiving." },

    { role: "The faithful one (rewarded)",
      culhwch: { who: "Goreu the avenger", note: "Hidden in the stone chest by his mother; emerges to behead Ysbaddaden and take the giant's lands." },
      gawain:  { who: "—", note: "No faithful retainer figure in the same sense; the court itself adopts the green sash but no individual is singled out for reward." },
      orfeo:   { who: "The high steward", note: "Holds the kingdom honestly for ten years; tested by the lying tale; rewarded with the throne after Orfeo's day." },
      gloss: "Culhwch and Orfeo close on the reward of a faithful retainer (Goreu inherits the giant's lands; the steward inherits Orfeo's). Gawain has no equivalent. The two heroes who walk into a court at the end (Culhwch back to Olwen's giant-hall, Orfeo back to his own) reward the faithful one; Gawain rides home into a court that has already moved on." },
  ],
};
