/* Sir Orfeo — a faithful middle-grade retelling (ages ~8-12), the whole
   poem across paged spreads. Plot, names, the harp, the ympe-tree, the
   yard of the half-taken, the rash boon, and the steward's test kept
   faithful. The medieval poem's classical core is preserved as the poem
   itself preserves it — Orpheus made over as a king of Winchester, no
   looking back, no dismemberment, the queen recovered. Each spread
   carries an `illus` brief — an art note for the illustration pass; it
   is not shown. Attaches to window.ORFEO. */
window.ORFEO = window.ORFEO || {};
window.ORFEO.book = {
  meta: {
    kicker: "A Lay from Medieval England",
    note: "A faithful retelling for readers 8 and up — the medieval English Orpheus, page by page. Illustrations to follow.",
  },
  spreads: [
    { title: "Sir Orfeo",
      sub: "A story told in England long ago, of a king who lost his queen to the Land of Faerie — and went, all alone, with only his harp, to bring her back",
      text: "A tale of a fair queen taken at noon under a grafted tree, a king who waited ten years on bark and roots, a journey through a cleft in a rock, a court of crystal whose stones gave light, and a song that opened every door.",
      illus: "Cover: a fair-haired young king (Sir Orfeo) in scarlet medieval royal robes with a small gold circlet, holding a beautifully carved gold-strung small lap-harp under one arm; standing on a green hill at dusk; in the distance, a lady in silver silk with pale-gold hair walking away beside snow-white riders into a glowing crystal castle whose stones cast their own light; warm gouache-and-watercolour painting in the Howard Pyle / Edmund Dulac tradition; cool northern winter palette — deep mossy greens, vermilion reds, oxidised gold, indigo, pewter — with quiet gold accents; magical, gentle, child-friendly." },

    { title: "King Orfeo of Winchester",
      text: "Long ago, England had a king named Orfeo. He ruled in the city of Winchester — which, the old story says, was called Thrace in those days. He was tall and brave, generous and courteous; and most of all he loved to play the harp. When he played, every quiet listener said the world fell still. His queen was the loveliest lady in the land, and her name was Heurodis.",
      illus: "Interior of a great firelit medieval hall in Winchester: a young fair-haired king (Sir Orfeo) seated on a carved wooden throne, playing a small gold-strung Celtic lap-harp; a beautiful young queen (Heurodis) in silver-and-gold silk gown seated beside him listening with quiet pleasure; courtiers in jewel-coloured robes hushed around them; warm orange firelight; sense of peace before storm." },

    { title: "A May Morning Under the Ympe-Tree",
      text: "One bright morning in May, when the day was warm and every field full of flowers, Queen Heurodis went out with two of her ladies to walk in the palace orchard. They sat down all three under a fair grafted tree — a kind of tree that two trees had been grown into one, which the old tales called an <em>ympe-tree</em>. Soon the queen fell asleep on the grass; the maidens did not dare wake her. She slept past the noon hour.",
      illus: "A walled medieval orchard in full May blossom: three women under a particular grafted/doubled fruit tree (the ympe-tree, two trunks twisted into one, white blossom thick on every branch); the queen (Heurodis, silver gown, pale-gold hair) is asleep on the green grass; two maidens in pale linen gowns sit beside her keeping silent watch; bright midday sun, dreamlike, slightly uncanny stillness." },

    { title: "The Strange Waking",
      text: "But the moment the queen woke up, she cried out as if she had seen something terrible. She tore at her own face until it bled; she ripped her fine gown; her eyes looked wild and frightened. The maidens were so afraid that they ran back to the palace and shouted to the knights, “Come quick — the queen has gone mad!” And sixty knights and ladies hurried back with them, and gathered the queen in their arms, and carried her gently home to bed.",
      illus: "The same orchard, sun still high: the queen (Heurodis) sat up in panic on the grass under the ympe-tree, hands at her face but no blood shown (folktale tact), gown disarrayed; one maiden running toward the palace in the background; the other crouched beside her in tears; sense of dreadful waking from a vision, not graphic; warm afternoon light gone slightly cold." },

    { title: "The Queen's Vision",
      text: "King Orfeo came running to her bedside. When she could at last speak, this is what she told him. “While I slept, two fine knights came and bade me come and speak with their king. I said no. Then the king himself came — with a hundred riders all on snow-white horses, and a hundred ladies with him, all in milk-white robes. His crown was no metal at all, but one single shining jewel as bright as the sun. He took me up onto a horse beside him, and showed me his rivers and forests and castles. Then he set me down again in our own orchard, and said: <em>Come back tomorrow at noon, under this same ympe-tree, and live with us forever. If you do not come, we will come and fetch you — and nothing on earth will keep us out.</em>”",
      illus: "A dream-vision scene: in the foreground, the queen (Heurodis) sat up in a richly draped bed, telling her tale; in a glowing dreamlike inset above her bed, the Fairy King — tall, dark-haired, ageless, wearing green and silver, crowned with a single huge radiant gem instead of any metal — on horseback with snow-white knights and damsels in white robes behind him; a hundred white horses; magical, awe-inspiring, not menacing." },

    { title: "A Thousand Knights Around a Tree",
      text: "Orfeo could not bear it. The next morning he summoned a thousand knights, every one armed and ready, and led them with the queen to the ympe-tree. They stood around her in a shield-wall on every side, and swore they would die before they let her go. But in a single instant, from the very middle of the shield-wall, the queen vanished. No one saw how. No one knew where. She was simply gone.",
      illus: "Same orchard, noon: a circle of a thousand armoured medieval knights with locked shields around the ympe-tree, queen at the centre — but the centre is now empty, only her silk veil drifting down to the grass where she stood; bright sun, motion-blur of vanishing, the knights frozen in confusion; uncanny, no violence, beautiful." },

    { title: "“I Will Be King No Longer”",
      text: "Orfeo went into his chamber and wept until he could hardly stand. Then he called his barons together and said: “Lords, I will rule no more. I have lost my queen, the loveliest lady that ever was born; I shall never look upon another woman again. I am going into the wilderness with the wild beasts. I leave my high steward to keep the kingdom in my place. When you know I am gone forever, choose another king.” His people knelt and begged him to stay. He shook his head. “It shall be so,” he said.",
      illus: "Great hall at Winchester: King Orfeo standing on the dais in plain dark robe, no crown; his barons and earls kneeling in a wide arc before him in grief, some weeping into their hands; one older bearded man in russet (the steward) stands quietly beside the king receiving the charge; warm firelight, heavy and sorrowful; sense of an ending." },

    { title: "Out the Gate in a Pilgrim's Cloak",
      text: "He took off his royal clothes and put on a rough wool pilgrim's cloak. He took no shirt, no shoes, no food, no horse — only his harp. And he walked barefoot out of his own city, alone. The people wept in the streets to see him go. Beyond the city he turned into the wild woods and the long heath, and he was not seen again for ten years.",
      illus: "Out of focus behind: Winchester city gate, weeping citizens lining the road. In sharp focus: Sir Orfeo walking away from us up a winding road into a dim wild countryside — beardless still but already tired-looking, barefoot, in rough grey pilgrim's wool cloak (a sclavin), small gold-strung harp in his hand, no other belongings; bare trees ahead, late autumn light, quiet, dignified, painful." },

    { title: "Ten Years on Bark and Roots",
      text: "In summer he lived on wild berries and fruit; in winter on roots and bark. He slept on the cold ground and woke under the snow. His body wasted away. His hair grew long and matted, and his beard grew down to his belt. He who had once worn fine fur on a bed of purple linen now lay on hard heather. He who had once had a hundred knights kneel before him now had only the wild creatures that crossed his path. Ten years.",
      illus: "Wide wild landscape — moss-covered rocks, bare trees, snow on hills behind, a small fire-pit in foreground: Sir Orfeo, very thin, his hair long and unkempt, black beard hanging to his waist, his face calm and weathered, in tattered remains of the grey sclavin, sitting wrapped in his own arms on a moss-covered stone; gentle, melancholy, dignified, not pitiful." },

    { title: "The Harp in a Hollow Tree",
      text: "But he kept his harp. He hid it in the hollow of an old tree, and only brought it out when the weather was clear and bright. Then he sat down and played — and the whole wood listened. The wild beasts came creeping out of their dens for joy of it; the birds came and sat on every briar; even shy stags and shaggy bears lay down quietly at his feet to hear him. And when he stopped playing, the beasts went away again.",
      illus: "A sunlit clearing in summer: Sir Orfeo seated on a fallen log playing his small gold-strung harp; around him, gathered in a wide circle, every kind of wild English animal listening peacefully — a stag with great antlers, a great brown bear lying down with eyes closed, foxes, hares, badgers, every kind of small bird on every briar around them; a hollow oak tree visible behind; warm gold light, magical, gentle." },

    { title: "Three Sights of the Fairy King",
      text: "Sometimes, at the high noon hour, Orfeo would see things in the wood that no one else could see. Once he saw the Fairy King himself, with all his court, ride past on a hunt — with dim horn-blowing and far-off hounds — but he never caught any beast, and he was always gone in a flash. Another time Orfeo saw a great army of fairy knights with bright banners pass by, swords drawn — but never knew where they were going. And another time he saw fairy ladies and lords dancing in a strange slow procession, with drums and pipes — and they passed by him as if he were not there.",
      illus: "A triptych-style composition (three vignettes layered): on the left, a glimpse through trees of the Fairy King and ghostly riders in green hunting with dim hounds at midday; in the middle, a column of armoured fairy knights with painted banners crossing a clearing in silence; on the right, fairy ladies and lords in jewel colours dancing slowly with small drums and pipes; Sir Orfeo (now very thin and bearded, in grey sclavin) watching from behind a tree in each scene; dreamlike, half-real, half-transparent." },

    { title: "Sixty Ladies on Horseback",
      text: "And then one day Orfeo saw sixty ladies riding on horseback — gentle and gay as birds on a branch — and not a single man among them. Each one held a falcon on her hand, and they were hawking by the side of a river. Their falcons rose and brought down birds out of the air. Orfeo, watching them, laughed for the first time in ten years. “By my faith,” he said, “there is fine sport! I used to ride a hunt like that, long ago.” And he got up and went toward them.",
      illus: "A wide river-meadow under a soft bright sky: sixty fair-haired ladies in fine green and gold riding habits on snow-white horses, each with a falcon perched on her gauntleted left hand; the falcons in the air diving on rising mallards over the river; Sir Orfeo (thin, bearded, in tattered grey, with his small harp on his back) walking out from the woods toward them with a small, surprised smile on his face — the first smile in ten years; beautiful, hopeful, the seam between his old life and what is coming." },

    { title: "“It is My Wife”",
      text: "When Orfeo came up close to the ladies, he looked carefully at one of them — and saw, by every sign, that it was his own queen, Heurodis. They looked at each other for a long time. Neither one could speak a word. He was so changed and ragged that when she saw him, the tears fell from her eyes — not for herself, but for what he had become. The other ladies saw this. They surrounded her quickly and rode her away. Orfeo could not follow. But he stood very still and said, in his heart: <em>Wherever they go, that is where I go.</em>",
      illus: "Riverbank, the moment of recognition: Sir Orfeo on the bank, ragged and bearded, his face transformed by recognition; Heurodis on her snow-white horse halted before him, hand raised slightly, a single tear on her cheek; the other fairy ladies on white horses gathering closely around her with grave faces, beginning to wheel away; no words possible; the spaciousness of grief held in a single look; muted gold light; gentle, devastating, restrained." },

    { title: "Into a Cleft in a Rock",
      text: "Orfeo put his cloak back on properly, hung his harp on his back, and followed the ladies as fast as his bare feet could go. He spared neither stone nor briar. He saw them ride straight into a narrow cleft in a great rock — and he ran in after them. He went three miles through the dark, with the rock close on either side of him, and at last he came out into the open again — but into a country he had never seen before.",
      illus: "A great grey rock face in a wild English landscape: a tall narrow vertical cleft in the rock, just wide enough for a horse; the last snow-white horse and lady disappearing into it; Sir Orfeo running barefoot toward the cleft with his harp on his back and his pilgrim's cloak streaming behind him; sense of urgent threshold-crossing; muted natural daylight." },

    { title: "A Castle Bright as Paradise",
      text: "The land on the other side was smooth and green, with no hill or valley. In the middle of it stood a castle. Its outer wall was crystal — clear and shining. It had a hundred towers; its buttresses were red gold; its inner pillars were of burnished gold. Within were chambers all of precious stones. And the most wonderful thing of all: the land was never dark. When night came, the great jewels of the castle gave out their own light, as bright as the noon sun. Orfeo thought, looking at it, that it might almost be Paradise.",
      illus: "Sir Orfeo (small in foreground, in tattered grey pilgrim's cloak with harp on his back) standing at the edge of a perfectly smooth grassy plain looking up at an enormous fairy-castle in the middle of the green: walls of clear crystal, a hundred slender towers, buttresses arching out of a moat in red gold, every battlement detailed; some of the stones in the wall already glowing faintly with their own light though it is daylight; magical, awe-inspiring, bright but slightly uncanny — not quite Paradise; jewel-bright with cool dawn colour." },

    { title: "“I Am a Minstrel”",
      text: "Orfeo went to the great crystal gate and knocked. The porter came at once and asked his business. Orfeo said: “Sir, I am a wandering minstrel. I have come to give the lord of this castle some pleasure with my music, if he will hear it.” The porter opened the gate and let him in. Music was the only key that would have turned this lock — and it turned easily.",
      illus: "Close-up: an enormous crystal-and-gold gate towering above Sir Orfeo; the porter (cloaked, indistinct, slightly otherworldly, faintly luminous) is opening one panel of the gate; Sir Orfeo (small, ragged, harp on back, hands held out empty in supplication) standing at the threshold; sense of awe and quiet welcome; jewel-bright background." },

    { title: "The Yard of the Half-Taken",
      text: "Inside the castle wall Orfeo saw a sight that stopped his breath. There were many, many people lying there — folk from his own world. He saw the brave and the unlucky frozen at the very moment they had been taken: knights still mounted, still armed, in the middle of a charge; sleepers under flowering trees; mothers in childbed; a man in the act of fighting wolves; people who had drowned; people who had been struck by lightning. The poem says they were “thought dead, and were not.” The Fairy King had taken them all — frozen them at the moment of their sudden trouble — and kept them here.",
      illus: "A wide grassy courtyard inside the crystal castle: a strange, beautiful, silent crowd of figures held perfectly still in the postures they were taken in — a fully armoured knight on a stilled white horse with his sword raised mid-stroke, a fair woman peacefully sleeping under a small ympe-tree; a young mother in a serene moment cradling a swaddled baby; a man with one hand raised against an off-stage threat; an oarsman frozen in a small boat half-tilted on calm water; figures handled with tact, NOT gore — beautiful and uncanny, like the figures in a tableau; muted silver-blue light; Sir Orfeo (small, in foreground, looking up) walking through them; awe and pity, not horror." },

    { title: "Asleep Under an Ympe-Tree",
      text: "Among all those still figures Orfeo saw a fair lady asleep under a grafted ympe-tree. The very same kind of tree that grew in the orchard of his own palace in Winchester, ten years before. He knew her not by her face, which he could hardly see, but by the dress she was wearing — the same fine gown she had been wearing the May morning she was taken. It was his Heurodis.",
      illus: "Within the yard of the half-taken, slight zoom-in: under a small grafted fruit tree in May blossom (an ympe-tree, doubled trunk), Queen Heurodis sleeps peacefully on the grass in the same silver-and-gold silk gown from the orchard scene; her hair spread, her face calm; Sir Orfeo (ragged, bearded, in grey sclavin) standing very still a little distance away with his hand to his mouth in recognition; soft cool light; deep tenderness." },

    { title: "Into the Hall of the Fairy King",
      text: "Orfeo went into the great hall of the castle. There, on a high throne under a canopy of shining stones, sat the Fairy King — and beside him his queen. Their crowns and their robes shone so brightly that Orfeo could hardly look at them. He came forward, kneeled, and said: “My lord, if it be your will, let me play my music for you.”",
      illus: "Vast hall of the crystal castle with high arched ceiling: at the far end on a great gold-and-jewel throne, the Fairy King (tall, dark-haired, severe, green and silver robes, crown of one huge radiant jewel) and the Fairy Queen (silver-white robes, hair pale-gold, also crowned with a single jewel) shining almost too brightly to look at; courtiers all around in green and silver finery; Sir Orfeo (small, ragged, in grey sclavin with his small harp under one arm) kneeling on the long stone floor before the throne; awe and beauty." },

    { title: "Orfeo Plays the Harp",
      text: "The Fairy King looked down at him and frowned. “Who are you? Nobody comes here unless I send for him.” Orfeo answered politely: “Sir, I am only a poor harper. It is our way to seek the houses of great lords, whether they welcome us or not, and offer our music.” Then he sat down before the throne, tuned his harp, and began to play. The notes were the most beautiful that anyone had ever heard. Every man and woman in the palace came around and lay down at his feet to listen. The Fairy King sat completely still. The Fairy Queen smiled.",
      illus: "Same hall: Sir Orfeo (ragged, bearded, in his grey pilgrim's cloak) seated on the bottom step of the throne dais playing his small gold-strung harp with closed eyes; the entire fairy court — knights, ladies, courtiers, servants — gathered in a wide circle around him, many lying down on the crystal floor with rapt expressions; the Fairy King and Fairy Queen on the throne above, both leaning slightly forward in deep stillness; warm gold-and-silver light filling the room; the moment power passes from threats to music." },

    { title: "“Ask What You Will”",
      text: "When Orfeo at last set down his harp, the Fairy King said: “Minstrel, your music has given me great pleasure. Ask of me anything you like, and I shall give it to you. Speak.” Orfeo answered: “Sir, I beseech you — give me that lady who lies asleep under an ympe-tree in your yard.”",
      illus: "Closer view of the throne: the Fairy King leaning toward Sir Orfeo (ragged, bearded, in grey pilgrim's cloak, still on the dais step with harp held loosely) with a slight gracious smile and one hand raised in the gesture of an offered gift; Orfeo's face in profile, calm and determined, looking up steadily; the Fairy Queen watching from the side, expression unreadable; warm gold light; the formal moment of a binding word." },

    { title: "“It Were a Fouler Thing”",
      text: "The Fairy King frowned. “Nay — that may not be! You are thin and ragged and rough; she is beautiful beyond any blemish. It would be a sorry, ugly thing to see her in your company.” But Orfeo said, “O sir, gentle king — yet it would be a far <em>fouler</em> thing to hear a lying word from your mouth. You said I could ask what I would, and you must keep your word.” The Fairy King was silent a long moment. Then he said: “Since it is so — take her by the hand, and go.”",
      illus: "Fairy King on the throne, expression troubled and then resolving into reluctant respect; Sir Orfeo (ragged, bearded, in grey pilgrim's cloak) standing tall and quiet on the dais step, harp at his side, looking up; the Fairy Queen watching the moment with grave approval; the silence of a binding word being honoured; warm gold light, slightly cooler now." },

    { title: "Hand in Hand, Out the Way He Came",
      text: "Heurodis came back from where she had been sleeping, and Orfeo took her by the hand. They walked together out of the great hall, out across the crystal gate, out across the bright green country, back through the long dark cleft in the rock — and the poet says, very simply: <em>just as he came, the way he went</em>. He did not look back. Not once.",
      illus: "Sir Orfeo and Queen Heurodis walking hand in hand away from us up the long passage through the rock cleft — backs to us — the crystal castle visible behind them through the cleft fading into bright fairy light; ahead of them, the cleft opens into normal English daylight; both walk steadily, looking forward, no glance back; quiet, complete; an answer to a thousand years of Orpheus poems." },

    { title: "Back at the Walls of Winchester",
      text: "They walked the long road back to Winchester, the city that had once been Orfeo's own. When at last they reached the walls, they did not go inside. Orfeo's hair and beard were so long and wild, and his clothes so ragged, that not one citizen knew him for the king he had been. So at the town's edge he found a kind old beggar with a tiny narrow hut, and they took shelter there.",
      illus: "Winchester city walls in soft daylight; the city gate ahead in the middle distance; in the foreground beside a hedge by the road, a small ramshackle wooden hut with a kind old grey-bearded beggar in a brown cloak standing at its door welcoming Sir Orfeo (ragged, bearded, harp on back) and Queen Heurodis (in her fine silk gown, fairly preserved); the beggar's hands held out in welcome; quiet, humble, hopeful." },

    { title: "The City's News",
      text: "The beggar told Orfeo all the news of the city. Their queen, he said, had been taken away by faerie ten years ago. The king had gone into the wilderness in grief; no one knew where; he was surely dead. The high steward had been keeping the kingdom honestly all this while. Orfeo listened, and said nothing. He had a plan.",
      illus: "Inside the beggar's small hut by firelight: Sir Orfeo and Queen Heurodis seated on a rough bench, listening; the old beggar (grey beard, brown cloak) talking earnestly across a small wooden table by the light of a single candle and the fire; Orfeo's expression thoughtful, focused; Heurodis quietly watching her husband; cozy, humble, conspiratorial." },

    { title: "Into the City in Borrowed Clothes",
      text: "The next morning, at noon-tide, Orfeo asked his wife to wait at the hut. He borrowed the beggar's rough clothes, hung his harp on his back, and walked into Winchester. The lords and ladies and townspeople looked at him and called to one another: “Look at that man! How long his hair! How his beard hangs to his knee! He is shrunk like an old tree.” But not one of them recognised him.",
      illus: "Sir Orfeo in the beggar's brown coarse hooded coat (over his sclavin), small harp on his back, walking down a busy medieval English street in Winchester; townspeople — earls in fur, ladies in headdresses, merchants in heavy wool, children — staring curiously as he passes; Orfeo's face partially hidden by his great black beard and shaggy hair; nobody recognising him; warm noon light; sense of suspense." },

    { title: "Meeting the Steward",
      text: "In the street he came face to face with his high steward. Orfeo called out: “Sir steward, mercy! I am a harper from far away — help me, I am in distress!” The steward answered at once: “Come along with me. What I have, you shall share. Every good harper is welcome in my house — for the sake of my old lord, Sir Orfeo.” Orfeo did not say a word more. He simply walked along beside the steward into the castle.",
      illus: "On a busy medieval English street: the steward (the older bearded man in russet from earlier scenes, kindly faced) standing in surprise as Sir Orfeo (ragged, harp on back) bows low before him with one hand raised; the steward already extending his hand to welcome the harper; townspeople in the background watching; warm midday light; the moment of the test beginning." },

    { title: "The Harp at the Feast",
      text: "That night in the castle's great hall the steward sat at his high table with many lords beside him. The musicians of the court played — trumpets, drums, harpers, fiddlers — and there was much noise. Orfeo sat quietly to one side and waited. When at last the room fell silent, he took his harp and began to play. The hall held its breath. Then the steward looked at the harp very carefully, and his face changed.",
      illus: "Great hall of Winchester castle by torchlight: the steward at the high table with lords; trumpeters and other court musicians off to the side, now silent; Sir Orfeo (in the borrowed beggar's coat, hood pushed back, his long black beard visible) seated on a low stool in the centre of the hall playing his small gold-strung harp with rapt expression; every person in the hall — knights, ladies, servants — leaning forward; the steward's face in close attention, his eyes fixed not on the harper but on the harp itself; warm orange firelight; the moment of an instrument being recognised." },

    { title: "“Where Did You Get That Harp?”",
      text: "The steward stood up. “Harper,” he said, “tell me — where did you get that harp?” Orfeo said, carefully: “Lord, I found it in a wild country, in a dale, beside a man who had been killed by lions and wolves — well ten years ago.” The steward gave a great cry, and fell down on the floor in a swoon. “That was my lord, Sir Orfeo!” he said. “Alas, that I was ever born — to have lost so good a lord, in so vile a way.” His lords lifted him up and tried to comfort him. There was no comforting.",
      illus: "Same hall, moments later: the steward fallen to his knees on the floor with one hand over his eyes, weeping; lords gathered round him reaching to help him up; Sir Orfeo (harp still in hand) standing very still nearby, watching gravely, the test answered; the great hall silenced; warm low firelight; the steward's grief is total and total grief is the right answer." },

    { title: "“If I Were the King…”",
      text: "Then Orfeo, knowing the steward had loved him truly, stood up to his full height. He said, “Steward, hear me. <em>If</em> I were Orfeo your king, and had suffered ten years in the wilderness, and had won my queen back out of the Land of Faerie, and had brought her to the town's edge, and were standing before you now in beggar's clothes — only to test your loyalty — and had found you as true as I have found you here today, then you would not regret it. You would surely be king after my own day. But if I had heard that you had been glad of my death — you would have been thrown out of my house at once.”",
      illus: "Same hall, dramatic charged moment: Sir Orfeo standing now drawn up to his full height, the borrowed beggar's coat falling open to show the grey pilgrim's cloak beneath, his face transformed by the speaking of the truth, the harp held aside in one hand; the steward kneeling at his feet looking up in stunned recognition, hand stretched toward him; the lords behind starting to rise from their seats in dawning understanding; warm gold firelight, dramatic; the conditional reveal as the poem's hinge." },

    { title: "Recognition by the Whole Hall",
      text: "Then everyone in the hall understood at once. The steward threw the table aside and fell at Orfeo's feet, weeping for joy. Every lord and knight in the hall fell to their knees, and all together they cried out: “You are our lord, sir, and our king!” They led him to a chamber, bathed him, shaved off his ten-year beard, and clothed him as a king again. Then with great procession they went out to the town's edge and fetched Queen Heurodis from the beggar's hut, with trumpets and harps lining the road. And the people of Winchester wept with joy, to see them both come home safe.",
      illus: "Wide jubilant scene: at left, the bathed and trimmed Sir Orfeo, hair cropped, beard shaved, dressed in royal scarlet and ermine with the gold circlet on his head, recognisable again, smiling slightly; in the centre, a great procession entering through the city gate with Queen Heurodis at its heart (in her silver silk, walking calmly with grace) preceded by trumpeters and harpers; townspeople crowding the streets weeping with joy and waving green branches; bright sunlight, gold-leaf colours, music, return; the deepest joy in the poem made visible." },

    { title: "The Lay That Bears His Name",
      text: "King Orfeo and Queen Heurodis were crowned again, and ruled long and well — and when at last he died, the faithful steward came to the throne, just as Orfeo had promised. After that, harpers all over Britain heard the strange tale of how the queen had been lost and won again. They composed a song of it, and they named the song <em>Orfeo</em>, after the king. The song is good. The notes are sweet. And so came Sir Orfeo out of his sorrow — and God grant us all well to fare. Amen.",
      illus: "Closing vignette: a peaceful scene of medieval harpers in Britain — a small group of bards in dark robes and small gold-strung Celtic harps gathered around a hearth at evening, singing the tale to a quiet crowd of villagers; in the background, painted on the back wall like a memory or window, a small image of Sir Orfeo and Queen Heurodis crowned together on a throne; the steward standing behind them in russet; warm firelight; cosy, dignified, the warmth of a story finished and folded into song." },
  ],
};
