/* Branwen ferch Llŷr — a faithful retelling for readers ~8 and up, the whole
   Second Branch across paged spreads. It is a tragedy, and the hardest beats
   (the blow to Branwen, the child in the fire, the battle) are handled with
   folktale tact — named, not shown graphically. Each spread carries an `illus`
   brief — an art note for the illustration pass; it is not shown to the reader.

   COMPLETE. Seventeen paged spreads carrying the whole branch from the rock of
   Harlech to the wondrous head and Branwen's grave on the Alaw, at roughly
   three spreads per movement so every major beat has its own page — the same
   density as the early tales. Each spread carries an `illus` art brief (not
   shown to the reader); the tragedy's harshest beats named, not shown.
   Attaches to window.BRANWEN. */
window.BRANWEN = window.BRANWEN || {};
window.BRANWEN.book = {
  meta: {
    kicker: "The Second Branch of the Mabinogi",
    note: "A faithful retelling for readers 8 and up — Branwen daughter of Llŷr, page by page. A great old Welsh story, and a sad one, told with care across the whole branch. Illustrations follow via the pipeline.",
  },
  spreads: [
    { title: "Branwen ferch Llŷr",
      sub: "The Second Branch of the Mabinogi — a tale of a marriage between two islands, a quarrel that could not be mended, a cauldron that gave back the dead, and a giant king whose head went on speaking long after he was gone",
      text: "Long ago, when a giant was king of the Island of Britain, his sister Branwen was married across the sea to the king of Ireland, to make the two islands friends. But a cruel trick spoiled the peace before it began — and from that one unkindness grew a war that emptied both lands. This is her story.",
      illus: "Cover: Bendigeidfran, an immense, noble bearded giant-king in a deep-blue and gold royal mantle with a simple gold crown, seated on a great grey sea-cliff (the rock of Harlech) and gazing out over a grey-green sea; he dwarfs the people around him. Beside him a fair young woman with long dark hair (Branwen) in a green gown. Far out on the water, thirteen ships with bright satin sails approach. Warm gouache-and-watercolour in the Howard Pyle / Edmund Dulac tradition; earthy Welsh palette — slate-greys, sea-greens, ambers, with quiet gold — a mythic, faintly sorrowful grandeur; child-friendly." },

    { title: "The King on the Rock of Harlech",
      text: "Bendigeidfran — which means Brân the Blessed — was so vast a king that no house could hold him. One afternoon he sat on the great rock of Harlech above the sea, with his brother Manawydan and his two half-brothers: gentle Nisien, who could make peace between enemies, and Efnisien, who could start a quarrel between the best of friends. As they sat, they saw thirteen ships come speeding from Ireland, a shield held point-upward on the foremost — the sign that they came in peace.",
      illus: "On a vast grey sea-cliff at Harlech, the giant king Bendigeidfran (immense, bearded, blue-and-gold mantle, gold crown) seated and looking out to sea, with three much smaller men standing near him: Manawydan, and the half-brothers Nisien (kind-faced) and Efnisien (sharp, sullen-faced). Below on the grey-green water, thirteen fine ships with satin flags approach, a round shield raised point-up above the lead ship. Earthy Welsh palette, sea-light, painterly, child-friendly." },

    { title: "The King of Ireland Comes Courting",
      text: "The ships carried Matholwch, king of Ireland, and he had crossed the sea to ask for a wife: Branwen, sister of Bendigeidfran, one of the three chief ladies of Britain and the fairest maiden in the world. He wished to join Ireland and Britain together and make them stronger, and the king and his council thought it a good and noble match. So they came down to the shore to welcome him, and to talk of a wedding.",
      illus: "Matholwch, the red-haired-and-bearded king of Ireland in a green mantle with gold trim, stepping ashore from a fine ship onto a grey Welsh beach, his Irish nobles behind him in checked and bordered wool cloaks with round shields. Welsh lords come down to greet him; the giant king Bendigeidfran looms huge on the cliff above. Cool sea-light, banners, a hopeful air of welcome; earthy Welsh palette with gold; painterly, child-friendly." },

    { title: "The Wedding at Aberffraw",
      text: "At Aberffraw they held the wedding feast. But because no house could ever contain the giant Bendigeidfran, the whole feast was held outdoors, under great bright tents. There Branwen was married to Matholwch, and the two peoples ate and drank and talked together, and for a little while there was nothing in the world but gladness.",
      illus: "A great open-air wedding feast under huge bright pavilion-tents by the sea at Aberffraw. The giant king Bendigeidfran (too large for any building) seated at the head with his brother Manawydan; opposite, Matholwch king of Ireland with the fair dark-haired Branwen beside him in a fine gown. Long tables, candle-light and daylight, banners; joyful but with a faint air of foreboding. Earthy Welsh palette with gold, painterly, child-friendly." },

    { title: "Efnisien's Spite",
      text: "But Efnisien, the brother who loved to make trouble, had not been asked his leave before his sister was given away — and it stung his pride. To take his spite out on someone, he crept to where the king of Ireland's fine horses were kept, and ruined them, cropping and spoiling them so they were of no use to anyone. It was a small, mean act; but from it the whole sorrow of the tale would grow.",
      illus: "Night-time near a Welsh stable-paddock: the lean, sharp-faced, sullen figure of Efnisien in dark muted clothes turning away from a row of fine horses that stand cropped and distressed (shown gently — no blood, no graphic harm). His face is bitter and self-justifying. Moonlight, deep shadow, a sense of small ugly spite; earthy muted palette; painterly, child-friendly, menace without gore." },

    { title: "The Quarrel and the Magic Cauldron",
      text: "When Matholwch learned what had been done to his horses, he was so insulted that he made for his ships in anger. To mend the quarrel, Brân gave him new horses, a staff of silver and a plate of gold — and last of all a wonder, a great old cauldron with a terrible magic in it: any man slain in battle, if he were laid inside it, would rise next morning as strong as ever — but he would never be able to speak again. (It had come long ago out of a lake in Ireland, from a giant and his wife who once burst out of a white-hot iron house.) Matholwch was glad of the gift, and sailed home to Ireland with Branwen; and for a while there was peace.",
      illus: "At the tented feast at Aberffraw by the sea, the giant king Bendigeidfran gestures toward a huge, ancient dark-bronze cauldron (the Cauldron of Rebirth) standing on a low fire, its rim worked with old spiralling Celtic ornament; Matholwch, the red-haired king of Ireland in green and gold, regards it with wonder and unease. Warm hall-light under the great tents; earthy Welsh palette with gold and a cold gleam off the cauldron; painterly, child-friendly, a sense of uncanny power." },

    { title: "Branwen Sails to Ireland",
      text: "Branwen crossed the sea to Ireland a beloved queen, and at first all was well. The land rejoiced at her coming; every great family was glad to see her, and gave her gifts. Within the year she had a son, and they named him Gwern, and gave the little boy out to be fostered with the best people in the land, as was the custom. For a while Branwen was happy, far from home.",
      illus: "Branwen, in a fine green gown, holding her newborn son Gwern (a small swaddled baby) in a sunlit Irish hall, surrounded by glad Irish noblewomen in checked and bordered wool bringing gifts. Warm, hopeful light; the brightest, gladdest scene in the tale. Earthy palette with gold and a little spring-green; painterly, child-friendly, tender." },

    { title: "From the Hall to the Kitchen",
      text: "But across the sea, Ireland had not forgotten the insult of the spoiled horses, and slowly the king's men turned their bitterness on Branwen. They drove her out of the king's company to work in the kitchen, and ordered the cook to box her ear each day. And they forbade any ship to cross to Britain, so that no word of how she was treated could ever reach her brother the king. For three long years Branwen bore it, patient and uncomplaining.",
      illus: "Branwen, now in plain grey wool, dignified and sad but never abject, working at a kitchen kneading-trough in a dim Irish kitchen; a cook stands near. The harm is implied, not shown — her quiet endurance is the focus. A small high window looks out over a grey sea toward home. Muted, sombre light; earthy palette; painterly, child-friendly, handled with great folktale gentleness." },

    { title: "Branwen and the Starling",
      text: "Branwen was patient, and clever. Beside her kneading-trough she raised a little starling, and taught it to speak, and taught it what her brother looked like. Then she wrote down all her sorrows in a letter, tied it carefully under the bird's wing, and sent it flying out over the sea. And the starling found Bendigeidfran far away in Wales, and landed on his great shoulder; and when he read her letter, he wept.",
      illus: "Branwen, in plain grey wool, sad but dignified, kneeling by a kitchen kneading-trough beside a small window that looks out over a grey sea; she gently cups a small speckled starling, a tiny folded letter bound under one of its wings. Soft, tender light; earthy muted Welsh palette; hopeful amid sorrow; painterly, child-friendly, handled with folktale gentleness." },

    { title: "He Who Would Be a Leader, Let Him Be a Bridge",
      text: "When word of Branwen's suffering reached him, Bendigeidfran was filled with grief and anger. He gathered the men of all Britain and crossed the sea to Ireland — and because he was a giant, he simply waded through the water while his ships sailed beside him. The Irish were so afraid that they fled across a deep river and broke down its only bridge. But Brân said, \"He who would be a leader, let him be a bridge.\" And he lay down across the river with his own great body, and his whole army laid down hurdles upon him and walked over him, safe and dry, to the far side.",
      illus: "The giant king Bendigeidfran lying face-down across a wide deep river to make a living bridge of his own body, long hurdles and planks laid along his broad back; his armed host of Welsh warriors walking across him to the far bank. Beyond, the sea and the masts of ships. A scene of awe and sombre grandeur; earthy Welsh palette, cold river-light; painterly, child-friendly." },

    { title: "The House Built for a Giant",
      text: "The frightened Irish offered peace, and built — for the first time ever — a house large enough to hold the giant Bendigeidfran. But it was a trap: along the walls they hung two hundred leather bags, and told anyone who asked that the bags held flour. In each bag was a hidden armed man. Efnisien, who knew a trick when he saw one, went quietly down the row and crushed each hidden head through the bag before the feast began — asking each time, \"What's in this bag?\" \"Flour,\" they would answer. So the ambush was undone before it could spring.",
      illus: "Inside a vast new-built timber hall hung with rows of large leather bags along the pillars; the lean dark figure of Efnisien moving down the row with grim purpose, his hand on one bag. The danger is suggested, not graphic — no blood, no visible bodies, just the sinister rows of bags and his cold, knowing face. Dim torchlight, long shadows, dread; earthy palette; painterly, child-friendly, menace without gore." },

    { title: "The Boy Made King",
      text: "Then the two peoples sat down together in the great house to make peace, and to set things right they gave the kingship of Ireland to the little boy Gwern — Branwen's own son, nephew to the men of Britain. The child went from one loving uncle to the next, and each was glad of him: from Bendigeidfran to Manawydan to gentle Nisien, the boy was passed and petted, and for a moment it seemed the two islands might be friends again after all.",
      illus: "A great firelit hall at a tense peace-feast; the small fair-haired boy Gwern in a little tunic being held warmly by the giant king Bendigeidfran and admired by Manawydan and the kind-faced Nisien. The mood is fragile, hopeful tenderness with an undertow of dread (the sullen Efnisien watches from the shadows at the edge). Warm hall-light against cold shadow; earthy palette with gold; painterly, child-friendly." },

    { title: "The Feast that Turned to Fire",
      text: "But when the boy came at last to Efnisien, that cruel man did a terrible thing, and the little boy was lost in the fire; and Branwen would have thrown herself in after her son had her brother Brân not held her fast. In an instant the whole hall was at war, Britain against Ireland, and the peace was gone past mending.",
      illus: "A great firelit hall erupting into uproar — overturned benches, alarmed figures rising, the giant king Bendigeidfran holding Branwen back with one huge arm as she reaches out in anguish. The fire at the hearth blazes high; the child and the cruelty are kept entirely off the page — only grief and chaos are shown. Dramatic fire-orange and shadow; earthy palette; sombre, painterly, child-friendly, strictly no gore, handled with folktale tact." },

    { title: "The Breaking of the Cauldron",
      text: "Now the battle went badly for Britain, for the Irish had the magic cauldron, and cast their fallen into it, so that each dawn their dead rose to fight again. The men of Britain could not win against an army that would not stay beaten. Then Efnisien, sick with grief for all the ruin he had made, hid himself among the Irish dead; and when they threw him into the cauldron, he stretched and strained with all his might until the great cauldron burst into four pieces — and his own heart broke with it. He gave his life to undo his worst deed.",
      illus: "Inside a smoky firelit hall in uproar, the huge ancient bronze Cauldron of Rebirth splitting apart into four pieces in a burst of sparks and cold light; the lean dark figure of Efnisien straining inside it with his last strength. Dim, armoured figures struggle in the smoky background — suggested, not graphic. Dramatic chiaroscuro, cold cauldron-gleam against fire-orange; earthy palette; sombre, painterly, child-friendly, no gore." },

    { title: "Only Seven Came Home",
      text: "When the terrible fighting was done, only seven of all Brân's men were left alive — among them his brother Manawydan, and Pryderi, the boy from another tale grown to a man. And Brân himself had been wounded in the foot by a poisoned spear, and could not be healed. So the great king gave his men a strange and final command: that they should cut off his head and carry it home. And though it would be only a head, he told them, it would stay alive and merry and talk with them, just as it always had, for many long years.",
      illus: "On a grey, smoking battlefield by the Irish sea at dusk, seven weary Welsh survivors gathered around the immense seated figure of the wounded giant king Bendigeidfran, who speaks to them gravely and kindly, giving his last command. His brother Manawydan kneels close. The mood is sombre, tender, awe-struck; no wounds or gore shown. Cold dusk-light, muted earthy palette with a last gleam of gold; painterly, child-friendly." },

    { title: "The Feast Out of Time",
      text: "So the seven cut off the head, and carried it home; and it stayed alive and merry, and talked with them just as Brân had promised. They feasted seven years at Harlech, with three magical birds singing far out over the sea, and fourscore years more in a bright hall above the ocean at Gwales, where no sorrow could reach them and no one grew any older — until one of them opened a door he had been warned to leave shut. And in that instant all their old grief came rushing back, and they knew it was time to carry the head to its rest.",
      illus: "A great hall above the sea at Gwales: the seven survivors seated at a quiet, golden, timeless feast, and at the head of the table the crowned, undecayed wondrous head of Bendigeidfran set upright among them, serene and calm as if only sleeping. Three small birds glimpsed singing far out over the ocean through a window; one heavy door in the background standing ominously open, cold grey light spilling through it. Soft candle-gold light meeting cold daylight; earthy Welsh palette; painterly, child-friendly, a quiet wonder at its ending." },

    { title: "The Wondrous Head, and Branwen's Grave",
      text: "They carried the head to London and buried it in the White Hill, facing the sea, to guard Britain from her enemies for ever. But gentle Branwen never saw home again. On the way back across the sea, looking from Ireland to Britain and thinking of the two fair islands ruined for her sake, her heart broke, and she died, and was buried on the bank of a river called the Alaw. \"Alas,\" she had said, \"that I was ever born — two good islands laid waste because of me.\" And that is the tale of Branwen, daughter of Llŷr.",
      illus: "A quiet, sorrowful scene on a green riverbank (the Alaw) under a wide grey Welsh sky: a simple four-sided grave-mound being raised, the few survivors standing in mourning, the sea visible beyond. Tender and still, grief without horror. In one upper corner, small and distant, the crowned wondrous head being carried toward a green hill (the White Hill of London). Muted earthy palette, cold soft light, a single quiet note of gold; painterly, child-friendly, elegiac." },
  ],
};
