/* Branwen uerch Lyr — the Second Branch of the Mabinogi. The English shown
   alongside the Welsh is an original translation, written movement by
   movement; Lady Charlotte Guest's public-domain version (1849) is consulted
   as a sense-check, not copied.

   The Welsh is a reading text normalised from the public-domain edition of
   John Rhys & J. Gwenogvryn Evans, "The Text of the Mabinogion ... from the
   Red Book of Hergest" (Oxford, 1887) — the same volume that gives Pwyll,
   Culhwch and Owain on this site. The 1887 edition sets the tale in a special
   Welsh typeface that OCR mis-reads heavily, so the Welsh here is normalised
   by hand into a Middle Welsh reading orthography (the convention used for
   Pwyll), cross-checked against the White Book tradition where the OCR is
   corrupt.

   Both source texts are preserved verbatim under source/:
     branwen-rhys-evans-1887-redbook.txt   (Middle Welsh, Red Book)
     branwen-guest-1849-english.txt        (Guest's comparison translation)
   Attaches to window.BRANWEN. */
window.BRANWEN = window.BRANWEN || {};
window.BRANWEN.tale = {
  meta: {
    blurb: "<strong>Branwen ferch Llŷr</strong> — \"Branwen daughter of Llŷr\" — the <em>Second Branch</em> of the Mabinogi, sister-tale to <em>Pwyll</em> (the First), preserved in the White Book of Rhydderch (c. 1350) and the Red Book of Hergest (c. 1382–1410). It is the great Welsh tragedy. The giant king <strong>Bendigeidfran</strong> (Brân the Blessed) marries his sister <strong>Branwen</strong> to <strong>Matholwch</strong> king of Ireland to bind the two islands; his malicious half-brother <strong>Efnisien</strong>, slighted, mutilates the Irish horses, and the alliance is patched only with gifts — among them the <strong>Cauldron of Rebirth</strong>, which gives slain men back to battle, but dumb. In Ireland the insult festers: Branwen is driven from the king's bed to the kitchen and struck daily by the butcher; over three years she trains a <strong>starling</strong> to carry word of her wrong across the sea. Brân leads the host of Britain over the water (wading it himself, a bridge for his men); the Irish build a house to hold the giant and hide warriors in flour-bags; Efnisien crushes them, then throws Branwen's little son <strong>Gwern</strong> into the fire, and the hall erupts. The cauldron revives the Irish dead until Efnisien destroys it with his own body and bursting heart. Only <strong>seven</strong> of the Britons survive; Brân, mortally wounded, has his head struck off, and it feasts and counsels them, undecayed, for fourscore years before its burial at the White Hill of London, facing France. Branwen dies of grief on the bank of the Alaw: <em>\"Alas that I was ever born — two good islands laid waste because of me.\"</em> The translation below is <strong>original</strong> and proceeds <strong>movement by movement</strong>; the Welsh beside it is a reading text normalised from Rhys &amp; Evans (1887). Full sources preserved at <a href=\"source/branwen-rhys-evans-1887-redbook.txt\">source/branwen-rhys-evans-1887-redbook.txt</a> and <a href=\"source/branwen-guest-1849-english.txt\">source/branwen-guest-1849-english.txt</a>.",
    sources: [
      { label: "The Text of the Mabinogion — Rhys & Evans, 1887 (Oxford, public domain; Red Book of Hergest)", url: "https://archive.org/details/textofmabinogion00rhysiala", host: "Internet Archive" },
      { label: "The Mabinogion — Lady Charlotte Guest, 1838–49 (public-domain English translation)", url: "https://www.gutenberg.org/ebooks/5160", host: "Project Gutenberg" },
      { label: "Branwen ferch Llŷr — overview", url: "https://en.wikipedia.org/wiki/Branwen_ferch_Ll%C5%B7r", host: "Wikipedia" },
      { label: "The Four Branches of the Mabinogi", url: "https://en.wikipedia.org/wiki/Four_Branches_of_the_Mabinogi", host: "Wikipedia" },
    ],
  },
  roadmap: [
    { t: "Source text in hand (Red Book / Rhys & Evans 1887 + Guest 1849)", done: true },
    { t: "I · The marriage of Branwen to Matholwch at Aberffraw", done: true },
    { t: "II · Efnisien's outrage; the amends; the Cauldron of Rebirth", done: true },
    { t: "III · Branwen's punishment in Ireland; the starling's message", done: false },
    { t: "IV · Brân's crossing; the bridge; the house and the flour-bags", done: false },
    { t: "V · The feast; Gwern in the fire; the battle and the cauldron", done: false },
    { t: "VI · The seven survivors; the wondrous head; Branwen's death", done: false },
  ],
  passages: [
    {
      title: "I. The marriage of Branwen to Matholwch at Aberffraw",
      segments: [
        { w: "Bendigeiduran uab Llyr a oed urenhin coronawc ar yr ynys honn, ac arderchawc o goron Lundein. A phrynhawngweith yd oed yn Hardlech yn Ardudwy, yn llys idaw; ac yn eisted yd oedynt ar garrec Hardlech uch penn y weilgi, a Manawydan uab Llyr y vrawt y gyt ac ef, a deu vroder un uam ac ef, Nissyen ac Efnissyen, a gwyrda y am hynny ual y gwedei y gylch brenhin. Y deu uroder un uam ac ef, meibon oedynt y Eurosswyd o'e uam ynteu, Penarddun uerch Veli uab Mynogan. A'r neill o'r gweisson hynny, gwas da oed: ef a barei dangneued y rwng y deulu pan vydynt lidyawckaf; sef oed hwnnw Nissyen. A'r llall a barei ymlad y rwng y deu uroder pan uei uwyhaf yd ymgerynt.",
          e: "Bendigeidfran son of Llŷr was crowned king over this island, and exalted with the crown of London. And one afternoon he was at Harlech in Ardudwy, at his court; and they were seated on the rock of Harlech above the sea — Manawydan son of Llŷr his brother with him, and his two half-brothers by the mother, Nisien and Efnisien, and nobles besides, as is fitting about a king. His two half-brothers were sons of Euroswydd by his own mother, Penarddun daughter of Beli son of Mynogan. And one of those young men was a good young man: he would make peace between the two kindreds when they were angriest — that was Nisien. And the other would stir up strife between the two brothers when they loved each other most.",
          n: "<strong>Bendigeidfran</strong> (\"Brân the Blessed\") is a king the size of myth — a giant no house can hold, son of Llŷr (the sea-god behind Shakespeare's Lear) and brother of <strong>Manawydan</strong> (the Welsh reflex of the Irish sea-god Manannán). The Second Branch is bound to the First by blood and craft: where <em>Pwyll</em> closes on Pryderi, <em>Branwen</em> will end with Pryderi among its seven survivors. The half-brothers <strong>Nisien</strong> (who makes peace) and <strong>Efnisien</strong> (who makes strife) are the tale's moral poles — and Efnisien's malice is the engine of the whole tragedy to come." },

        { w: "Ac ual yd oedynt yn eisted uelly, wynt a welynt teir llong ar dec yn dyuot o deheu Iwerdon, ac yn kyrchu parth ac attunt, a cherdet rugyl ebrwyd gantunt, y gwynt yn eu hol ac yn eu nessau yn ebrwyd attunt. \"Mi a welaf longeu racco,\" heb y brenhin, \"ac yn dyuot yn ebrwyd parth a'r tir; ac erchwch y wyr y llys wiscaw ymdanunt, a mynet y edrych pa uedwl yw yr eidunt.\" Y gwyr a wiscwys ymdanunt ac a nessayssant attunt y waeret. Gwedy gwelet y llongeu o agos, diheu oed gantunt na welsynt llongeu gyweiryach eu hansawd noc wynt: baneri tec gwedus o bali a oed arnunt. Ac ar hynny, nachaf un o'r llongeu yn raculaenu rac y rei ereill, ac y gwelynt dyrchafael taryan yn uch no bwrd y llong, a swch y daryan y uynyd yn arwyd tangneued.",
          e: "And as they sat thus, they saw thirteen ships coming from the south of Ireland, making toward them, gliding swiftly with the wind behind them and nearing fast. \"I see ships yonder,\" said the king, \"coming swiftly toward the land; bid the men of the court arm themselves and go to learn what their intent is.\" The men armed and went down to them. Having seen the ships close to, they were sure they had never seen ships of better trim: fair seemly flags of brocade were on them. And then one of the ships outstripped the rest, and they saw a shield raised above the ship's gunwale, the point of the shield uppermost — the sign of peace.",
          n: "The shield held point-up is the medieval signal of peaceful intent, the inverse of the boss-forward charge. The thirteen Irish ships crossing the sea open the tale's master-motif: the traffic — of marriage, of gifts, of armies — between the Island of the Mighty (Britain) and Ireland, which the rest of the branch turns from alliance into mutual ruin." },

        { w: "Ac y nessawys y gwyr attunt ual yd ymglywynt ymdidan. Bwrw badeu allan a wnaethant wynteu, a nessau parth a'r tir, a chyfarch gwell y'r brenhin. A'r brenhin a'e clywei wynteu o'r lle yd oed ar garrec uchel uch eu penn. \"Duw a rodho da ywch,\" heb ef, \"a graessaw wrthywch. Pieu y niuer llongeu hynn, a phwy yssyd bennaf arnunt?\" \"Arglwyd,\" heb wynt, \"y mae yma Matholwch brenhin Iwerdon, ac ef bieu y llongeu.\" \"Pa beth,\" heb y brenhin, \"a uynnei ef? A uynn ef dyuot y'r tir?\" \"Ny uynn, arglwyd,\" heb wynt, \"negesseawl yw wrthyt, onyt y neges a geiff.\" \"Pa ryw neges yw yr eidaw ef?\" heb y brenhin. \"Mynnu ymgyfathrachu a thidi, arglwyd,\" heb wynt. \"Y erchi Branwen uerch Lyr y doeth ef; ac os da gennyt ti, ef a uynn ymrwymaw Ynys y Kedyrn ac Iwerdon y gyt, ual y bydynt gadarnach.\" \"Ie,\" heb ynteu, \"doet y'r tir, a chynghor a gymerwn ninneu am hynny.\"",
          e: "And the men drew near enough to hold converse. They put out boats and came toward the land, and greeted the king — and the king could hear them from where he sat on the high rock above their heads. \"God give you good,\" he said, \"and welcome. Whose are these ships, and who is chief over them?\" \"Lord,\" they said, \"Matholwch king of Ireland is here, and the ships are his.\" \"What does he want?\" said the king. \"Will he come ashore?\" \"He will not, lord,\" they said; \"he is here on an errand, and will not land unless he has it.\" \"What errand is his?\" said the king. \"He wishes to ally himself with you, lord,\" they said. \"He has come to ask for Branwen daughter of Llŷr; and if it please you, he would bind the Island of the Mighty and Ireland together, that they might be the stronger.\" \"Well,\" said he, \"let him come ashore, and we will take counsel on it.\"",
          n: "<em>Ynys y Kedyrn</em>, \"the Island of the Mighty,\" is the tale's name for Britain. The marriage is conceived as statecraft — a binding of two islands — the same dynastic logic that governs Owain's fountain-marriage and Pwyll's alliance with Annwn. Branwen, like Rhiannon, is the woman through whom realms are joined; the tragedy is that this joining will unmake both." },

        { w: "Yr atteb hwnnw a aeth attaw ef. \"Minneu a af yn llawen,\" heb ef. Ef a doeth y'r tir, a llawen uuwyt wrthaw; a dygyuor mawr a uu yn y llys y nos honno y rwng y niueroed ef a niueroed y llys. Yn y lle drannoeth kymryt kynghor: sef a gahat yn y kynghor hwnnw, rodi Branwen y Uatholwch. A honno oed dryded prif rieni yn yr ynys honn, a theckaf morwyn yn y byt oed. A gwneuthur oet yn Aberffraw y gyscu genthi, ac odyno y gychwyn. Ac y kychwynnassant y niueroed hynny parth ac Aberffraw: Matholwch a'e niueroed yn y llongeu, Bendigeiduran a'e niueroed ynteu ar y tir, yny doethant hyt yn Aberffraw. Yn Aberffraw dechreu y wled ac eisted. Sef ual yd eistedassant: brenhin Ynys y Kedyrn, a Manawydan uab Llyr o'r neill parth, a Matholwch o'r parth arall, a Branwen uerch Lyr y gyd ac ef. Ac nyt y mywn ty yd oedynt, namyn y mywn pebylleu — ny ellit Bendigeiduran y mywn ty eiryoet. Ac y dechreuyssant y wled, ac yuet, ac ymdidan; a phan welsant uot yn well udunt kyscu noc yuet, y gyscu yd aethant. A'r nos honno y bu Branwen yn wreic y Uatholwch.",
          e: "That answer was brought to him. \"I will go gladly,\" he said. He came ashore, and was made welcome; and there was a great throng in the court that night between his hosts and the court's. Next day they took counsel, and this was resolved: to give Branwen to Matholwch. She was one of the three chief ladies of this island, and the fairest maiden in the world. And they set a tryst at Aberffraw to sleep with her, and to set out from there. So those hosts set out for Aberffraw — Matholwch and his men in their ships, Bendigeidfran and his men by land — until they came to Aberffraw. At Aberffraw the feast began, and they sat down. And this is how they sat: the king of the Island of the Mighty, and Manawydan son of Llŷr on the one side, and Matholwch on the other, and Branwen daughter of Llŷr beside him. And they were not within a house but within tents — no house could ever hold Bendigeidfran. And they began the feast, and drank, and talked; and when they found sleep better than drinking, they went to sleep. And that night Branwen became Matholwch's wife.",
          n: "Branwen is one of the <em>tair prif rieni</em>, the three chief matriarchs of Britain — a figure of the first rank, married out to Ireland for an alliance she did not choose. The detail that <strong>no house could ever contain Bendigeidfran</strong> — the wedding-feast must be held in tents — is the tale's quiet, recurring measure of his giant scale, and it becomes the hinge of the plot when the Irish later build him a house. The marriage that should bind two islands is, in the event, the first step toward laying both waste — the refrain the closing colophon will name." },
      ],
    },

    {
      title: "II. Efnisien's outrage, the amends, and the Cauldron of Rebirth",
      segments: [
        { w: "A thrannoeth kyuodi a orugant bawb o niuer y llys; a'r swydwyr a dechreuassant ymarwar am rannyat y meirch a'r gweisson, ac eu rannu a wnaethant ympob kyueir hyt y mor. Ac ar hynny, dydgweith, nachaf Efnissyen — y gwr anhagneuedus a dywedassam ni uchot — yn dywannu y letty meirch Matholwch, a gofyn a wnaeth pieu y meirch. \"Meirch Matholwch brenhin Iwerdon yw y rei hynn,\" heb wynt. \"Pa beth a wnant hwy yma?\" heb ef. \"Yma y mae brenhin Iwerdon, ac yr gyscwys gan Vranwen dy whaer; a'e ueirch yw y rei hynn.\" \"Ae uelly y gwnaethant wy am uorwyn kystal a honno, ac yn chwaer y minneu, y rodi heb uy nghennyat? Ny ellynt wy tremic uwy arnaf i no hwnnw,\" heb ef. Ac yn hynny gwan y dan y meirch, a thorri y gwefleu wrth y danned udunt, a'r clusteu wrth y penneu, a'r rawn wrth y keuyn; a'r ny chaei graf ar yr amranneu, y lladei wrth yr ascwrn. A gwneuthur anfuryf ar y meirch uelly, hyt nat oed rym a ellit ar y meirch.",
          e: "And next day everyone of the court's company rose, and the officers set about apportioning the horses and the grooms, and ranged them in every quarter as far as the sea. And then, one day, here came Efnisien — the quarrelsome man we spoke of above — chancing on the place where Matholwch's horses were kept, and he asked whose horses they were. \"These are the horses of Matholwch king of Ireland,\" they said. \"What are they doing here?\" he said. \"The king of Ireland is here, and he has married Branwen your sister; these are his horses.\" \"And is that what they have done with a maiden as good as she — and my own sister — to give her away without my leave? They could do me no greater insult than this,\" he said. And with that he rushed in under the horses and cut off their lips at the teeth, and their ears close to their heads, and their tails close to their backs; and wherever he could grip the eyelids, he cut them to the bone. And he so disfigured the horses that no use could be had of them.",
          n: "Efnisien's outrage is the hinge of the whole tragedy, and it turns on a point of honour: Branwen was given in marriage <em>heb uy nghennyat</em>, \"without my leave\" — the kindred's slight to him, avenged on the king of Ireland's horses. The mutilation is told with deliberate, methodical cruelty (lips, ears, tails, eyelids, each to the bone): the strife-maker doing exactly what he was named at the outset to do. From this one act of spite grows the war that empties two islands." },

        { w: "Chwedyl a doeth at Uatholwch: dywedut anffuruaw y ueirch a'e llygru, hyt nat oed un mwynyant a ellit o honunt. \"Ie, arglwyd,\" heb yr un, \"dy waradwydaw a wnaethpwyt, a hynny a uynnir y wneuthur itti.\" \"Dioer, eres yw gennyf: os uy ngwaradwydaw a uynnynt, rodi morwyn gystal, kyuurd, kyn annwylet gan y chenedyl, ac a rodyssant ym!\" \"Arglwyd,\" heb un arall, \"ti a wely mae uelly y mae; ac nyt oes itt a wnelych namyn kyrchu dy longeu.\" Ac ar hynny, arouun y longeu a wnaeth ef. A chwedyl a doeth at Uendigeiduran uot Matholwch yn adaw y llys heb ouyn kennyat; a chennadeu a aeth y ouyn idaw paham yd oed hynny: Iddic uab Anarawc, ac Eueyd Hir. Y gwyr hynny a'e gordiwedawd, ac a ouynnassant idaw pa darpar oed yr eidaw, a pha achaws yd oed yn mynet ymeith. \"Dioer,\" heb ynteu, \"pei ys gwypwn, ny down yma. Gwbyl waradwyd a geueis; ac ny duc neb kyrch waeth noc a dugum i yma.\"",
          e: "Word came to Matholwch: that his horses had been disfigured and ruined, so that no use could be had of them. \"Yes, lord,\" said one, \"you have been insulted, and it was meant to be done to you.\" \"By God, it is a wonder to me: if they wished to insult me, why give me a maiden as good, as high, and as dearly loved of her kindred as the one they gave me!\" \"Lord,\" said another, \"you see it is so; and there is nothing for you to do but make for your ships.\" And at that he set out for his ships. And word came to Bendigeidfran that Matholwch was leaving the court without taking leave; and messengers went to ask him why — Iddig son of Anarawd, and Hefeydd Hir. They overtook him and asked what his purpose was, and why he was going away. \"By God,\" he said, \"had I known, I would not have come. I have had nothing but insult, and no man ever fared worse than I have here.\"",
          n: "Matholwch's bewilderment is the tale's tragic register: he cannot square the honour of the marriage with the insult of the horses, and the gap drives him toward the sea and toward war. The Welsh court tries to repair it the only way an honour-culture can — an embassy and an offer of compensation — but the wound is already in the alliance." },

        { w: "\"Ie,\" heb wynt, \"nyt o uod neb a uedei y llys, na neb o'e gynghor, y gwnaethpwyt y gwaradwyd hwnnw itti; a chyt bo gwaradwyd gennyt ti hynny, mwy yw gan Uendigeiduran no chennyt ti y tremic hwnnw.\" \"Ie,\" heb ef, \"mi a debygaf; ac eissoes, ny eill ef uy ngwaradwydaw i o hynny.\" Y gwyr hynny a ymchoelassant a'r atteb hwnnw parth a'r lle yd oed Bendigeiduran, ac a uenegyssant idaw yr atteb a rodassei Matholwch. \"Ie,\" heb ynteu, \"nyt oes ymwaret o'e uynet ef yn anhagneuedus; ac nys gadwn. Kyuodwch, Manawydan uab Llyr, ac Eueyd Hir, ac Unic Glew Yscwyd, ac ewch yn y ol, a menegwch idaw: ef a geiff march iach am bop un o'r a lygrwyt; ac y gyt a hynny, ef a geiff yn wynebwarth llath aryant a uo kyuref a chyhyt ac ef ehun, a chlaur eur kyflet a'e wyneb. A menegwch idaw pa ryw wr a wnaeth hynny, a phanyw o'm anuod inneu y gwnaethpwyt; ac y mae brawt un uam a mi a wnaeth hynny, ac nat hawd gennyf inneu nac y lad nac y diuetha. A doet y ymwelet a mi, a mi a wnaf y dangneued ar y llun y mynno ehun.\"",
          e: "\"Yes,\" they said, \"it was not by the will of anyone who rules the court, nor of his council, that this insult was done to you; and great as the insult is to you, the affront is greater to Bendigeidfran than to you.\" \"Yes,\" he said, \"I believe it; yet that cannot un-insult me.\" The messengers turned back with that answer to Bendigeidfran, and told him the reply Matholwch had given. \"Well,\" he said, \"there is no help for it but to keep him from going away at enmity; and I will not let him. Rise up, Manawydan son of Llŷr, and Hefeydd Hir, and Unig the Bold of Shoulder, and go after him, and tell him: he shall have a sound horse for every one that was ruined; and besides that, as amends to his face, a silver staff as thick and as tall as himself, and a plate of gold as broad as his face. And tell him what kind of man did it, and that it was done against my will; and that it is a brother of mine by the same mother who did it, and not easy for me either to kill or to destroy. And let him come and meet me, and I will make peace in whatever shape he himself will choose.\"",
          n: "Brân's amends are scaled to the honour-economy: not just sound horses but a silver staff and a gold plate measured to Matholwch's own body — the most personal form of <em>wynebwarth</em> (\"face-payment,\" honour-price). And the tragedy's deepest knot is named here: the offender is Brân's own half-brother, whom he can neither kill nor disown — kinship binding the king's hands. The reconciliation will hold just long enough to do far worse damage." },

        { w: "Y kennadeu a aethant ar ol Matholwch, ac a uenegyssant idaw yr ymadrawd hwnnw yn garedic; ac ef a'e gwarandawes. \"Gwyr,\" heb ef, \"ni a gymerwn gynghor.\" Sef kynghor a uedylyassant: os gwrthot hynny a wnelynt, bot yn debygach gantunt kael kewilyd a uei uwy no chael iawn a uei gymeint; a diskynnu a wnaeth ar gymryt hynny, ac yr llys y doethant yn dangneuedus. A chyweiryaw y pebylleu a'r palleu a wnaethant ar ureint kyweirdeb neuad, a mynet y uwyta; ac ual y dechreuyssynt eisted ar dechreu y wled, yd eistedassant yna. A dechreu ymdidan a wnaeth Matholwch a Bendigeiduran; ac nachaf yn ardiawc gan Uendigeiduran ymdidan Matholwch, ac yn drist — a mywarth a gaei gan Uatholwch a'e lewenyd yn wastat kynno hynny. \"A wr,\" heb y Bendigeiduran, \"nyt wyt gystal ymdidanwr heno ac un nos. Ac os yr uychanet gennyt ti dy iawn, ti a gey ychwanegu itt wrth dy uynnu dy hun, ac auory talu dy ueirch itt.\" \"Arglwyd,\" heb ef, \"Duw a dalo itt.\" \"Mi a delediwaf dy iawn heuyt itt,\" heb y Bendigeiduran. \"Mi a rodaf itt peir, a chynnedyf y peir yw: y gwr a lader hediw itt, y uwrw yn y peir, ac erbyn auory y uot yn gystal ac y bu oreu — eithyr na byd llyueryd gantaw.\" A diolwch a wnaeth ynteu hynny, a diruawr lewenyd a gymerth. A thrannoeth y talwyt y ueirch idaw tra barhaawd meirch dof; ac odyna y kyrchwyt ac ef kymwt arall, ac y talwyt ebolyon idaw yny uu gwbyl idaw y dal. Ac wrth hynny y dodet ar y kymwt hwnnw, o hynny allan, Tal Ebolyon.",
          e: "The messengers went after Matholwch and told him these things kindly, and he listened. \"Men,\" he said, \"we will take counsel.\" And this is the counsel they reached: that if they refused, they were likelier to get a shame still greater than to get amends so great; and he came down to accepting it, and they came back to the court in peace. They set the pavilions and tents in the manner of a hall, and went to meat, and sat as they had sat at the beginning of the feast. And Matholwch began to talk with Bendigeidfran; and Matholwch's talk seemed to Bendigeidfran listless and sad — and he had been merry and steady in his cheer before this. \"Man,\" said Bendigeidfran, \"you are not so good a talker tonight as on another night. And if it is for the smallness of your amends, you shall add to them as you yourself choose, and tomorrow I will pay you your horses.\" \"Lord,\" he said, \"God reward you.\" \"And I will perfect your amends too,\" said Bendigeidfran. \"I will give you a cauldron, and its property is this: a man of yours killed today — cast him into the cauldron, and by tomorrow he will be as good as ever he was at his best, save that he will not have his speech.\" And Matholwch gave him thanks, and took huge joy of it. And next morning his horses were paid him as long as the broken-in horses lasted; and then they went with him into another commot, and colts were paid him until the whole was paid. And for that reason that commot was called, from then on, Tal Ebolyon, the Payment of Colts.",
          n: "The gift that should seal the peace is the seed of the catastrophe. The <strong>Cauldron of Rebirth</strong> (<em>Pair Dadeni</em>) gives slain men back as fighters but not as speakers — a resurrection without the soul's voice — and Brân hands it to Ireland as compensation. In Movement V it will be turned against his own host, reviving the Irish dead each night until Efnisien breaks it. The Welsh tale's bitter irony: the king's generosity arms his enemy. (<em>Tal Ebolyon</em> is one of the branch's onomastic anchors — the story explaining a real place on the map.)" },

        { w: "Ar eil nos, eisted y gyt a wnaethant. \"Arglwyd,\" heb y Matholwch, \"pan doeth itt y peir a rodeist ymi?\" \"Ef a doeth ym,\" heb ef, \"y gan wr a uu yth wlat ti; ac ny wnn na bo yno y kaffo.\" \"Pwy oed hwnnw?\" heb ef. \"Llassar Llaesgyfnewit,\" heb ef; \"a hwnnw a doeth yma o Iwerdon, a Chymideu Cymeinuoll y wreic y gyt ac ef, ac a diangyssant o'r ty haearn yn Iwerdon pan wnaethpwyt yn wynyas yn eu kylch. Ac eres yw gennyf ony wdost ti dim y wrth hynny.\" \"Gwn, arglwyd,\" heb ef, \"a chymeint ac a wnn, mi a'e managaf itt. Yn hela yd oedwn yn Iwerdon dydgweith, ar benn gorsed a oed uch penn llynn — a Llynn y Peir y gelwit. Ac mi a welwn wr melyngoch mawr yn dyuot o'r llynn, a pheir ar y geuyn; gwr athrugar mawr drycweith oed, ac yn y ol gwreic; ac ot oed uawr ef, mwy dwyweith oed y wreic noc ef. A chyrchu attaf a wnaethant, a chyfarch gwell ym. 'Pa gerdet yssyd arnawch chwi?' heb y mi. 'Llyna y ryw gerdet, arglwyd: y wreic honn, ym penn pythewnos a mis, y byd beichawc; a'r mab a aner o'r torllwyth hwnn, ym penn y pythewnos a'r mis, y byd gwr ymlad llawn aruawc.' Y kymereis inneu y goffymdeithaw wyntwy, ac y buant ulwydyn y gyt a mi.\"",
          e: "On the second night they sat together. \"Lord,\" said Matholwch, \"whence came the cauldron you gave me?\" \"It came to me,\" he said, \"from a man who had been in your land; and I think it may have been there that he got it.\" \"Who was that?\" he said. \"Llasar Llaes Gyfnewid,\" he said; \"he came here from Ireland, and Cymideu Cymeinfoll his wife with him, escaped from the Iron House in Ireland when it was made white-hot around them. And it is a wonder to me if you know nothing of it.\" \"I do know, lord,\" he said, \"and as much as I know I will tell you. I was hunting in Ireland one day, on the top of a mound above a lake — the Lake of the Cauldron it was called. And I saw a great yellow-red man coming up from the lake, a cauldron on his back — a huge, ill-favoured, ferocious-looking man, and a woman behind him; and big as he was, the woman was twice his size. They came to me and greeted me. 'What journey are you on?' said I. 'This is our journey, lord: this woman, at the end of a month and a fortnight, will be with child; and the boy born of that womb, at the end of the month and the fortnight, will be a fighting man, fully armed.' I took them to keep, and they were a year with me.\"",
          n: "The cauldron carries its own dark prehistory: it comes from a lake in Ireland with a pair of giants — <strong>Llasar Llaes Gyfnewid</strong> and <strong>Cymideu Cymeinfoll</strong>, she twice his size, breeding fully-armed warriors in six weeks. The over-breeding monstrous couple is the tale's quiet mythic logic — the cauldron is bound up with an unkillable, proliferating war-host. The story is told as a guest-tale within the feast, the Welsh narrative's favourite device (Cynon's tale in <em>Owain</em> works the same way)." },

        { w: "\"Yn y ulwydyn y keueis wynt yn diwarauun; o hynny allan y gwarauunwyt ym, a chyn penn y pedwyryd mis wynt eu hun yn peri eu hatcassau ac anghynnwys yn y wlat, yn gwneuthur sarhaedeu ac yn aniweiraw gwyrda a gwraged da. O hynny allan y dygyuores uy nghyuoeth am uy mhenn y erchi ym ymadaw ac wynt, a rodi dewis ym ae uy nghyuoeth ae wynt. A mi a dodeis ar gynghor uy ngwlat beth a wnelit amdanunt — kanys o'e bod ny eynt, ac nyt oed reit udunt o'e hanuod, herwyd ymlad, uynet. Ac yna, yn y kyuyng gynghor, y kawssant gwneuthur ystauell haearn oll. A gwedy bot yn barawt yr ystauell, dyuynnu a oed o of yn Iwerdon, ac o'r a oed berchen geueil a morthwyl; a pheri gossot glo kyuuch a chrib yr ystauell; a gwassanaethu yn diwall o uwyt a llynn ar y wreic a'e gwr a'e phlant. A phan wybuwyt eu medwi, y dechreuwyt kymyscu y tan a'r glo am benn yr ystauell, a chwythu y megineu yny uu yr ty yn wynyas yn eu kylch. Ac yna y bu kynghor ymperued llawr yr ystauell; a thario a oruc ef yny uu y pleit haearn yn burwynyas, ac yna, rac diruawr wres, y gwr a gyrchwys y pleit a'e yscwyd, ac a'e tarawes allan, a'e wreic yn y ol; ac namyn ef a'e wreic, ny diangawd odyno neb. Ac yna, mi a debygaf, arglwyd,\" heb y Matholwch wrth Uendigeiduran, \"y doeth ef drosot ti.\"",
          e: "\"For the year I had them, I had them without grudge; from then on it was grudged me, for before the fourth month was out they were making themselves hated and unwelcome in the land — committing outrages, and dishonouring noblemen and good women. From then on my people thronged about me, demanding I part with them, and giving me the choice of them or my realm. And I put it to the counsel of my land what should be done — for they would not go willingly, and could not be made to go against their will by fighting. And then, in that strait of counsel, they resolved to make a chamber all of iron. And when the chamber was ready, they summoned every smith in Ireland, every man who owned tongs and hammer; had coals heaped as high as the chamber's crest; and had the woman and her husband and her children served unstintingly with food and drink. And when it was known they were drunk, they began to pile the fire and coals about the chamber and to blow the bellows until the house was white-hot around them. And then there was a council held in the middle of the chamber floor; and the man waited until the iron wall was glowing white, and then, in the terrible heat, charged the wall with his shoulder and struck it out, and his wife after him; and except for him and his wife, none escaped. And then, I think, lord,\" said Matholwch to Bendigeidfran, \"he must have come over to you.\"",
          n: "The Iron House — a whole people conspiring to burn their too-fertile guests alive, and the giant bursting white-hot iron with his shoulder — is one of the oldest and most violent images in the Mabinogi, with deep folktale cousins (the burning-house death-trap is Thompson K811). It is also a grim structural rhyme: a house built as a trap, foreshadowing the house the Irish will build to hold Brân in Movement IV. The unkillable couple drive their hosts to attempted genocide and survive it; the cauldron they carry is the residue of that ferocity." },

        { w: "\"Diheu y doeth ef yma,\" heb ef, \"ac y rodes ym y peir.\" \"Pa wed y kymereist ti wy?\" \"Eu rannu a wneuthum ympob lle yn uy nghyuoeth; ac y maent yn lluossogi ac yn kynydu ympob lle, ac yn kadarnhau y lle y bydont o wyr ac arueu, o'r goreu a welas neb.\" Y nos honno, treulaw a wnaethant ar ymdidan a cherd a chyuedach, hyt tra uu uwy digrif udunt kyscu no chyuedach; ac y gyscu yd aethant. Ac uelly y treulwyt y wled honno trwy lewenyd. Ac yn niwed honno, kychwyn a oruc Matholwch parth ac Iwerdon, a Branwen y gyt ac ef; ac o Aber Menei y kychwynnassant a thair llong ar dec, ac y doethant hyt yn Iwerdon. Ac yn Iwerdon y bu diruawr lewenyd o'e dyuodyat.",
          e: "\"Surely he came here,\" said Bendigeidfran, \"and gave me the cauldron.\" \"How did you receive them?\" \"I scattered them through every part of my realm; and they multiply and thrive everywhere, fortifying wherever they are with men and arms, the best anyone ever saw.\" That night they passed in talk and song and carousing, until sleep pleased them better than carousing, and they went to sleep. And so that feast was spent in gladness. And at the end of it Matholwch set out for Ireland, and Branwen with him; from Aber Menai they set out with thirteen ships, and came to Ireland. And in Ireland there was vast joy at her coming.",
          n: "The peace is made and the feast ends in gladness — the false dawn before the tragedy. Brân has dispersed the cauldron-folk through Britain as a fighting reserve (a detail the Triads later develop), and given their cauldron away to Ireland. Branwen sails to her marriage with thirteen ships, as Matholwch came; the symmetry of the crossings frames the whole branch, and the next great crossing will be Brân's war-fleet. Movement III opens on Branwen's year of honour in Ireland — and the slow turn of the Irish court against her." },
      ],
    },
  ],
};
