/* Branwen uerch Lyr — the Second Branch of the Mabinogi. The English shown
   alongside the Welsh is an original translation, written movement by
   movement; Lady Charlotte Guest's public-domain version (1849) is consulted
   as a sense-check, not copied.

   The Welsh is a reading text normalised from the public-domain edition of
   John Rhys & J. Gwenogvryn Evans, "The Text of the Mabinogion ... from the
   Red Book of Hergest" (Oxford, 1887) — the same volume that gives Pwyll,
   Culhwch and Owain on this site. The 1887 edition sets the tale in a special
   Welsh typeface that OCR mis-reads heavily, so the Welsh here is normalised
   by hand into a Middle Welsh reading orthography (the convention used for
   Pwyll), cross-checked against the White Book tradition where the OCR is
   corrupt.

   Both source texts are preserved verbatim under source/:
     branwen-rhys-evans-1887-redbook.txt   (Middle Welsh, Red Book)
     branwen-guest-1849-english.txt        (Guest's comparison translation)
   Attaches to window.BRANWEN. */
window.BRANWEN = window.BRANWEN || {};
window.BRANWEN.tale = {
  meta: {
    blurb: "<strong>Branwen ferch Llŷr</strong> — \"Branwen daughter of Llŷr\" — the <em>Second Branch</em> of the Mabinogi, sister-tale to <em>Pwyll</em> (the First), preserved in the White Book of Rhydderch (c. 1350) and the Red Book of Hergest (c. 1382–1410). It is the great Welsh tragedy. The giant king <strong>Bendigeidfran</strong> (Brân the Blessed) marries his sister <strong>Branwen</strong> to <strong>Matholwch</strong> king of Ireland to bind the two islands; his malicious half-brother <strong>Efnisien</strong>, slighted, mutilates the Irish horses, and the alliance is patched only with gifts — among them the <strong>Cauldron of Rebirth</strong>, which gives slain men back to battle, but dumb. In Ireland the insult festers: Branwen is driven from the king's bed to the kitchen and struck daily by the butcher; over three years she trains a <strong>starling</strong> to carry word of her wrong across the sea. Brân leads the host of Britain over the water (wading it himself, a bridge for his men); the Irish build a house to hold the giant and hide warriors in flour-bags; Efnisien crushes them, then throws Branwen's little son <strong>Gwern</strong> into the fire, and the hall erupts. The cauldron revives the Irish dead until Efnisien destroys it with his own body and bursting heart. Only <strong>seven</strong> of the Britons survive; Brân, mortally wounded, has his head struck off, and it feasts and counsels them, undecayed, for fourscore years before its burial at the White Hill of London, facing France. Branwen dies of grief on the bank of the Alaw: <em>\"Alas that I was ever born — two good islands laid waste because of me.\"</em> The translation below is <strong>original</strong> and proceeds <strong>movement by movement</strong>; the Welsh beside it is a reading text normalised from Rhys &amp; Evans (1887). Full sources preserved at <a href=\"source/branwen-rhys-evans-1887-redbook.txt\">source/branwen-rhys-evans-1887-redbook.txt</a> and <a href=\"source/branwen-guest-1849-english.txt\">source/branwen-guest-1849-english.txt</a>.",
    sources: [
      { label: "The Text of the Mabinogion — Rhys & Evans, 1887 (Oxford, public domain; Red Book of Hergest)", url: "https://archive.org/details/textofmabinogion00rhysiala", host: "Internet Archive" },
      { label: "The Mabinogion — Lady Charlotte Guest, 1838–49 (public-domain English translation)", url: "https://www.gutenberg.org/ebooks/5160", host: "Project Gutenberg" },
      { label: "Branwen ferch Llŷr — overview", url: "https://en.wikipedia.org/wiki/Branwen_ferch_Ll%C5%B7r", host: "Wikipedia" },
      { label: "The Four Branches of the Mabinogi", url: "https://en.wikipedia.org/wiki/Four_Branches_of_the_Mabinogi", host: "Wikipedia" },
    ],
  },
  roadmap: [
    { t: "Source text in hand (Red Book / Rhys & Evans 1887 + Guest 1849)", done: true },
    { t: "I · The marriage of Branwen to Matholwch at Aberffraw", done: true },
    { t: "II · Efnisien's outrage; the amends; the Cauldron of Rebirth", done: false },
    { t: "III · Branwen's punishment in Ireland; the starling's message", done: false },
    { t: "IV · Brân's crossing; the bridge; the house and the flour-bags", done: false },
    { t: "V · The feast; Gwern in the fire; the battle and the cauldron", done: false },
    { t: "VI · The seven survivors; the wondrous head; Branwen's death", done: false },
  ],
  passages: [
    {
      title: "I. The marriage of Branwen to Matholwch at Aberffraw",
      segments: [
        { w: "Bendigeiduran uab Llyr a oed urenhin coronawc ar yr ynys honn, ac arderchawc o goron Lundein. A phrynhawngweith yd oed yn Hardlech yn Ardudwy, yn llys idaw; ac yn eisted yd oedynt ar garrec Hardlech uch penn y weilgi, a Manawydan uab Llyr y vrawt y gyt ac ef, a deu vroder un uam ac ef, Nissyen ac Efnissyen, a gwyrda y am hynny ual y gwedei y gylch brenhin. Y deu uroder un uam ac ef, meibon oedynt y Eurosswyd o'e uam ynteu, Penarddun uerch Veli uab Mynogan. A'r neill o'r gweisson hynny, gwas da oed: ef a barei dangneued y rwng y deulu pan vydynt lidyawckaf; sef oed hwnnw Nissyen. A'r llall a barei ymlad y rwng y deu uroder pan uei uwyhaf yd ymgerynt.",
          e: "Bendigeidfran son of Llŷr was crowned king over this island, and exalted with the crown of London. And one afternoon he was at Harlech in Ardudwy, at his court; and they were seated on the rock of Harlech above the sea — Manawydan son of Llŷr his brother with him, and his two half-brothers by the mother, Nisien and Efnisien, and nobles besides, as is fitting about a king. His two half-brothers were sons of Euroswydd by his own mother, Penarddun daughter of Beli son of Mynogan. And one of those young men was a good young man: he would make peace between the two kindreds when they were angriest — that was Nisien. And the other would stir up strife between the two brothers when they loved each other most.",
          n: "<strong>Bendigeidfran</strong> (\"Brân the Blessed\") is a king the size of myth — a giant no house can hold, son of Llŷr (the sea-god behind Shakespeare's Lear) and brother of <strong>Manawydan</strong> (the Welsh reflex of the Irish sea-god Manannán). The Second Branch is bound to the First by blood and craft: where <em>Pwyll</em> closes on Pryderi, <em>Branwen</em> will end with Pryderi among its seven survivors. The half-brothers <strong>Nisien</strong> (who makes peace) and <strong>Efnisien</strong> (who makes strife) are the tale's moral poles — and Efnisien's malice is the engine of the whole tragedy to come." },

        { w: "Ac ual yd oedynt yn eisted uelly, wynt a welynt teir llong ar dec yn dyuot o deheu Iwerdon, ac yn kyrchu parth ac attunt, a cherdet rugyl ebrwyd gantunt, y gwynt yn eu hol ac yn eu nessau yn ebrwyd attunt. \"Mi a welaf longeu racco,\" heb y brenhin, \"ac yn dyuot yn ebrwyd parth a'r tir; ac erchwch y wyr y llys wiscaw ymdanunt, a mynet y edrych pa uedwl yw yr eidunt.\" Y gwyr a wiscwys ymdanunt ac a nessayssant attunt y waeret. Gwedy gwelet y llongeu o agos, diheu oed gantunt na welsynt llongeu gyweiryach eu hansawd noc wynt: baneri tec gwedus o bali a oed arnunt. Ac ar hynny, nachaf un o'r llongeu yn raculaenu rac y rei ereill, ac y gwelynt dyrchafael taryan yn uch no bwrd y llong, a swch y daryan y uynyd yn arwyd tangneued.",
          e: "And as they sat thus, they saw thirteen ships coming from the south of Ireland, making toward them, gliding swiftly with the wind behind them and nearing fast. \"I see ships yonder,\" said the king, \"coming swiftly toward the land; bid the men of the court arm themselves and go to learn what their intent is.\" The men armed and went down to them. Having seen the ships close to, they were sure they had never seen ships of better trim: fair seemly flags of brocade were on them. And then one of the ships outstripped the rest, and they saw a shield raised above the ship's gunwale, the point of the shield uppermost — the sign of peace.",
          n: "The shield held point-up is the medieval signal of peaceful intent, the inverse of the boss-forward charge. The thirteen Irish ships crossing the sea open the tale's master-motif: the traffic — of marriage, of gifts, of armies — between the Island of the Mighty (Britain) and Ireland, which the rest of the branch turns from alliance into mutual ruin." },

        { w: "Ac y nessawys y gwyr attunt ual yd ymglywynt ymdidan. Bwrw badeu allan a wnaethant wynteu, a nessau parth a'r tir, a chyfarch gwell y'r brenhin. A'r brenhin a'e clywei wynteu o'r lle yd oed ar garrec uchel uch eu penn. \"Duw a rodho da ywch,\" heb ef, \"a graessaw wrthywch. Pieu y niuer llongeu hynn, a phwy yssyd bennaf arnunt?\" \"Arglwyd,\" heb wynt, \"y mae yma Matholwch brenhin Iwerdon, ac ef bieu y llongeu.\" \"Pa beth,\" heb y brenhin, \"a uynnei ef? A uynn ef dyuot y'r tir?\" \"Ny uynn, arglwyd,\" heb wynt, \"negesseawl yw wrthyt, onyt y neges a geiff.\" \"Pa ryw neges yw yr eidaw ef?\" heb y brenhin. \"Mynnu ymgyfathrachu a thidi, arglwyd,\" heb wynt. \"Y erchi Branwen uerch Lyr y doeth ef; ac os da gennyt ti, ef a uynn ymrwymaw Ynys y Kedyrn ac Iwerdon y gyt, ual y bydynt gadarnach.\" \"Ie,\" heb ynteu, \"doet y'r tir, a chynghor a gymerwn ninneu am hynny.\"",
          e: "And the men drew near enough to hold converse. They put out boats and came toward the land, and greeted the king — and the king could hear them from where he sat on the high rock above their heads. \"God give you good,\" he said, \"and welcome. Whose are these ships, and who is chief over them?\" \"Lord,\" they said, \"Matholwch king of Ireland is here, and the ships are his.\" \"What does he want?\" said the king. \"Will he come ashore?\" \"He will not, lord,\" they said; \"he is here on an errand, and will not land unless he has it.\" \"What errand is his?\" said the king. \"He wishes to ally himself with you, lord,\" they said. \"He has come to ask for Branwen daughter of Llŷr; and if it please you, he would bind the Island of the Mighty and Ireland together, that they might be the stronger.\" \"Well,\" said he, \"let him come ashore, and we will take counsel on it.\"",
          n: "<em>Ynys y Kedyrn</em>, \"the Island of the Mighty,\" is the tale's name for Britain. The marriage is conceived as statecraft — a binding of two islands — the same dynastic logic that governs Owain's fountain-marriage and Pwyll's alliance with Annwn. Branwen, like Rhiannon, is the woman through whom realms are joined; the tragedy is that this joining will unmake both." },

        { w: "Yr atteb hwnnw a aeth attaw ef. \"Minneu a af yn llawen,\" heb ef. Ef a doeth y'r tir, a llawen uuwyt wrthaw; a dygyuor mawr a uu yn y llys y nos honno y rwng y niueroed ef a niueroed y llys. Yn y lle drannoeth kymryt kynghor: sef a gahat yn y kynghor hwnnw, rodi Branwen y Uatholwch. A honno oed dryded prif rieni yn yr ynys honn, a theckaf morwyn yn y byt oed. A gwneuthur oet yn Aberffraw y gyscu genthi, ac odyno y gychwyn. Ac y kychwynnassant y niueroed hynny parth ac Aberffraw: Matholwch a'e niueroed yn y llongeu, Bendigeiduran a'e niueroed ynteu ar y tir, yny doethant hyt yn Aberffraw. Yn Aberffraw dechreu y wled ac eisted. Sef ual yd eistedassant: brenhin Ynys y Kedyrn, a Manawydan uab Llyr o'r neill parth, a Matholwch o'r parth arall, a Branwen uerch Lyr y gyd ac ef. Ac nyt y mywn ty yd oedynt, namyn y mywn pebylleu — ny ellit Bendigeiduran y mywn ty eiryoet. Ac y dechreuyssant y wled, ac yuet, ac ymdidan; a phan welsant uot yn well udunt kyscu noc yuet, y gyscu yd aethant. A'r nos honno y bu Branwen yn wreic y Uatholwch.",
          e: "That answer was brought to him. \"I will go gladly,\" he said. He came ashore, and was made welcome; and there was a great throng in the court that night between his hosts and the court's. Next day they took counsel, and this was resolved: to give Branwen to Matholwch. She was one of the three chief ladies of this island, and the fairest maiden in the world. And they set a tryst at Aberffraw to sleep with her, and to set out from there. So those hosts set out for Aberffraw — Matholwch and his men in their ships, Bendigeidfran and his men by land — until they came to Aberffraw. At Aberffraw the feast began, and they sat down. And this is how they sat: the king of the Island of the Mighty, and Manawydan son of Llŷr on the one side, and Matholwch on the other, and Branwen daughter of Llŷr beside him. And they were not within a house but within tents — no house could ever hold Bendigeidfran. And they began the feast, and drank, and talked; and when they found sleep better than drinking, they went to sleep. And that night Branwen became Matholwch's wife.",
          n: "Branwen is one of the <em>tair prif rieni</em>, the three chief matriarchs of Britain — a figure of the first rank, married out to Ireland for an alliance she did not choose. The detail that <strong>no house could ever contain Bendigeidfran</strong> — the wedding-feast must be held in tents — is the tale's quiet, recurring measure of his giant scale, and it becomes the hinge of the plot when the Irish later build him a house. The marriage that should bind two islands is, in the event, the first step toward laying both waste — the refrain the closing colophon will name." },
      ],
    },
  ],
};
