// Curated set of ubiquitously famous cultural works.
// Each entry: { t: title, k: kind, y: optional year/era hint for embedding context }
// Kept to titles people across cultures recognize without explanation.

export const BASIS = [
  // ---------- Movies (broad canon) ----------
  { t: "Star Wars", k: "movie" },
  { t: "The Godfather", k: "movie" },
  { t: "Casablanca", k: "movie" },
  { t: "Citizen Kane", k: "movie" },
  { t: "The Wizard of Oz", k: "movie" },
  { t: "Gone with the Wind", k: "movie" },
  { t: "Titanic", k: "movie" },
  { t: "The Matrix", k: "movie" },
  { t: "Pulp Fiction", k: "movie" },
  { t: "Forrest Gump", k: "movie" },
  { t: "The Shawshank Redemption", k: "movie" },
  { t: "Jurassic Park", k: "movie" },
  { t: "E.T. the Extra-Terrestrial", k: "movie" },
  { t: "Back to the Future", k: "movie" },
  { t: "The Lord of the Rings", k: "movie" },
  { t: "Harry Potter", k: "movie" },
  { t: "The Avengers", k: "movie" },
  { t: "Avatar", k: "movie" },
  { t: "Frozen", k: "movie" },
  { t: "The Lion King", k: "movie" },
  { t: "Toy Story", k: "movie" },
  { t: "Shrek", k: "movie" },
  { t: "Finding Nemo", k: "movie" },
  { t: "Up", k: "movie" },
  { t: "Inception", k: "movie" },
  { t: "Interstellar", k: "movie" },
  { t: "Fight Club", k: "movie" },
  { t: "The Dark Knight", k: "movie" },
  { t: "Spider-Man", k: "movie" },
  { t: "Batman", k: "movie" },
  { t: "Superman", k: "movie" },
  { t: "Iron Man", k: "movie" },
  { t: "Indiana Jones", k: "movie" },
  { t: "Raiders of the Lost Ark", k: "movie" },
  { t: "Rocky", k: "movie" },
  { t: "Rambo", k: "movie" },
  { t: "James Bond", k: "movie" },
  { t: "Goldfinger", k: "movie" },
  { t: "Dr. No", k: "movie" },
  { t: "Casino Royale", k: "movie" },
  { t: "Skyfall", k: "movie" },
  { t: "Mission: Impossible", k: "movie" },
  { t: "The Hunger Games", k: "movie" },
  { t: "Twilight", k: "movie" },
  { t: "The Fast and the Furious", k: "movie" },
  { t: "Mad Max", k: "movie" },
  { t: "Mad Max: Fury Road", k: "movie" },
  { t: "Alien", k: "movie" },
  { t: "Aliens", k: "movie" },
  { t: "Predator", k: "movie" },
  { t: "The Terminator", k: "movie" },
  { t: "Terminator 2: Judgment Day", k: "movie" },
  { t: "RoboCop", k: "movie" },
  { t: "Blade Runner", k: "movie" },
  { t: "Blade Runner 2049", k: "movie" },
  { t: "2001: A Space Odyssey", k: "movie" },
  { t: "Apocalypse Now", k: "movie" },
  { t: "Goodfellas", k: "movie" },
  { t: "Scarface", k: "movie" },
  { t: "Heat", k: "movie" },
  { t: "Die Hard", k: "movie" },
  { t: "Lethal Weapon", k: "movie" },
  { t: "Schindler's List", k: "movie" },
  { t: "Saving Private Ryan", k: "movie" },
  { t: "Gladiator", k: "movie" },
  { t: "Braveheart", k: "movie" },
  { t: "Dances with Wolves", k: "movie" },
  { t: "A Clockwork Orange", k: "movie" },
  { t: "The Shining", k: "movie" },
  { t: "Psycho", k: "movie" },
  { t: "The Birds", k: "movie" },
  { t: "Vertigo", k: "movie" },
  { t: "Rear Window", k: "movie" },
  { t: "North by Northwest", k: "movie" },
  { t: "Jaws", k: "movie" },
  { t: "Halloween", k: "movie" },
  { t: "Friday the 13th", k: "movie" },
  { t: "A Nightmare on Elm Street", k: "movie" },
  { t: "The Exorcist", k: "movie" },
  { t: "The Texas Chain Saw Massacre", k: "movie" },
  { t: "Get Out", k: "movie" },
  { t: "Us", k: "movie" },
  { t: "The Sixth Sense", k: "movie" },
  { t: "Memento", k: "movie" },
  { t: "Reservoir Dogs", k: "movie" },
  { t: "Kill Bill", k: "movie" },
  { t: "Django Unchained", k: "movie" },
  { t: "Inglourious Basterds", k: "movie" },
  { t: "Once Upon a Time in Hollywood", k: "movie" },
  { t: "No Country for Old Men", k: "movie" },
  { t: "There Will Be Blood", k: "movie" },
  { t: "Whiplash", k: "movie" },
  { t: "La La Land", k: "movie" },
  { t: "Moonlight", k: "movie" },
  { t: "Parasite", k: "movie" },
  { t: "Everything Everywhere All at Once", k: "movie" },
  { t: "The Grand Budapest Hotel", k: "movie" },
  { t: "Slumdog Millionaire", k: "movie" },
  { t: "Crouching Tiger, Hidden Dragon", k: "movie" },
  { t: "Spirited Away", k: "movie" },
  { t: "My Neighbor Totoro", k: "movie" },
  { t: "Princess Mononoke", k: "movie" },
  { t: "Howl's Moving Castle", k: "movie" },
  { t: "Akira", k: "movie" },
  { t: "Ghost in the Shell", k: "movie" },
  { t: "The Sound of Music", k: "movie" },
  { t: "Singin' in the Rain", k: "movie" },
  { t: "West Side Story", k: "movie" },
  { t: "Mary Poppins", k: "movie" },
  { t: "Willy Wonka and the Chocolate Factory", k: "movie" },
  { t: "Beauty and the Beast", k: "movie" },
  { t: "Aladdin", k: "movie" },
  { t: "The Little Mermaid", k: "movie" },
  { t: "Snow White and the Seven Dwarfs", k: "movie" },
  { t: "Cinderella", k: "movie" },
  { t: "Pinocchio", k: "movie" },
  { t: "Bambi", k: "movie" },
  { t: "Dumbo", k: "movie" },
  { t: "Fantasia", k: "movie" },
  { t: "Peter Pan", k: "movie" },
  { t: "101 Dalmatians", k: "movie" },
  { t: "The Jungle Book", k: "movie" },
  { t: "Tarzan", k: "movie" },
  { t: "Mulan", k: "movie" },
  { t: "Pocahontas", k: "movie" },
  { t: "The Hunchback of Notre Dame", k: "movie" },
  { t: "Hercules", k: "movie" },
  { t: "Tangled", k: "movie" },
  { t: "Moana", k: "movie" },
  { t: "Encanto", k: "movie" },
  { t: "Coco", k: "movie" },
  { t: "Inside Out", k: "movie" },
  { t: "WALL-E", k: "movie" },
  { t: "Ratatouille", k: "movie" },
  { t: "The Incredibles", k: "movie" },
  { t: "Monsters, Inc.", k: "movie" },
  { t: "Cars", k: "movie" },
  { t: "Brave", k: "movie" },
  { t: "Madagascar", k: "movie" },
  { t: "Kung Fu Panda", k: "movie" },
  { t: "How to Train Your Dragon", k: "movie" },
  { t: "Despicable Me", k: "movie" },
  { t: "Minions", k: "movie" },
  { t: "Ice Age", k: "movie" },
  { t: "Spider-Man: Into the Spider-Verse", k: "movie" },
  { t: "Black Panther", k: "movie" },
  { t: "Wonder Woman", k: "movie" },
  { t: "Aquaman", k: "movie" },
  { t: "Joker", k: "movie" },
  { t: "Deadpool", k: "movie" },
  { t: "Logan", k: "movie" },
  { t: "X-Men", k: "movie" },
  { t: "Guardians of the Galaxy", k: "movie" },
  { t: "Thor: Ragnarok", k: "movie" },
  { t: "Captain America: The Winter Soldier", k: "movie" },
  { t: "Avengers: Endgame", k: "movie" },
  { t: "The Pirates of the Caribbean", k: "movie" },
  { t: "Top Gun", k: "movie" },
  { t: "Top Gun: Maverick", k: "movie" },
  { t: "The Notebook", k: "movie" },
  { t: "Pretty Woman", k: "movie" },
  { t: "When Harry Met Sally", k: "movie" },
  { t: "Sleepless in Seattle", k: "movie" },
  { t: "Dirty Dancing", k: "movie" },
  { t: "Grease", k: "movie" },
  { t: "Ferris Bueller's Day Off", k: "movie" },
  { t: "The Breakfast Club", k: "movie" },
  { t: "Sixteen Candles", k: "movie" },
  { t: "Mean Girls", k: "movie" },
  { t: "Clueless", k: "movie" },
  { t: "Legally Blonde", k: "movie" },
  { t: "Bridget Jones's Diary", k: "movie" },
  { t: "Notting Hill", k: "movie" },
  { t: "Love Actually", k: "movie" },
  { t: "Crazy Rich Asians", k: "movie" },
  { t: "Home Alone", k: "movie" },
  { t: "Elf", k: "movie" },
  { t: "It's a Wonderful Life", k: "movie" },
  { t: "A Christmas Carol", k: "movie" },
  { t: "Die Hard", k: "movie" },
  { t: "The Big Lebowski", k: "movie" },
  { t: "Fargo", k: "movie" },
  { t: "Trainspotting", k: "movie" },
  { t: "American Beauty", k: "movie" },
  { t: "American Psycho", k: "movie" },
  { t: "Requiem for a Dream", k: "movie" },
  { t: "Donnie Darko", k: "movie" },
  { t: "Eternal Sunshine of the Spotless Mind", k: "movie" },
  { t: "The Truman Show", k: "movie" },
  { t: "Groundhog Day", k: "movie" },
  { t: "Forrest Gump", k: "movie" },
  { t: "The Princess Bride", k: "movie" },
  { t: "Stand by Me", k: "movie" },
  { t: "The Goonies", k: "movie" },
  { t: "Ghostbusters", k: "movie" },
  { t: "Beetlejuice", k: "movie" },
  { t: "Edward Scissorhands", k: "movie" },
  { t: "The Nightmare Before Christmas", k: "movie" },
  { t: "Coraline", k: "movie" },
  { t: "Pan's Labyrinth", k: "movie" },
  { t: "The Shape of Water", k: "movie" },
  { t: "Birdman", k: "movie" },
  { t: "12 Years a Slave", k: "movie" },
  { t: "Argo", k: "movie" },
  { t: "The King's Speech", k: "movie" },
  { t: "Million Dollar Baby", k: "movie" },
  { t: "A Beautiful Mind", k: "movie" },
  { t: "Good Will Hunting", k: "movie" },
  { t: "Dead Poets Society", k: "movie" },
  { t: "The Silence of the Lambs", k: "movie" },
  { t: "Seven", k: "movie" },
  { t: "Zodiac", k: "movie" },
  { t: "The Departed", k: "movie" },
  { t: "Taxi Driver", k: "movie" },
  { t: "Raging Bull", k: "movie" },
  { t: "The Wolf of Wall Street", k: "movie" },
  { t: "The Social Network", k: "movie" },
  { t: "Oppenheimer", k: "movie" },
  { t: "Barbie", k: "movie" },
  { t: "Dune", k: "movie" },
  { t: "Dune: Part Two", k: "movie" },

  // ---------- Books / Literature ----------
  { t: "The Bible", k: "book" },
  { t: "The Quran", k: "book" },
  { t: "The Torah", k: "book" },
  { t: "The Bhagavad Gita", k: "book" },
  { t: "The Iliad", k: "book" },
  { t: "The Odyssey", k: "book" },
  { t: "The Aeneid", k: "book" },
  { t: "Beowulf", k: "book" },
  { t: "The Divine Comedy", k: "book" },
  { t: "The Canterbury Tales", k: "book" },
  { t: "Hamlet", k: "book" },
  { t: "Macbeth", k: "book" },
  { t: "Romeo and Juliet", k: "book" },
  { t: "King Lear", k: "book" },
  { t: "Othello", k: "book" },
  { t: "A Midsummer Night's Dream", k: "book" },
  { t: "Pride and Prejudice", k: "book" },
  { t: "Sense and Sensibility", k: "book" },
  { t: "Emma", k: "book" },
  { t: "Jane Eyre", k: "book" },
  { t: "Wuthering Heights", k: "book" },
  { t: "A Tale of Two Cities", k: "book" },
  { t: "Great Expectations", k: "book" },
  { t: "Oliver Twist", k: "book" },
  { t: "David Copperfield", k: "book" },
  { t: "A Christmas Carol", k: "book" },
  { t: "Don Quixote", k: "book" },
  { t: "Les Misérables", k: "book" },
  { t: "The Hunchback of Notre-Dame", k: "book" },
  { t: "The Count of Monte Cristo", k: "book" },
  { t: "The Three Musketeers", k: "book" },
  { t: "War and Peace", k: "book" },
  { t: "Anna Karenina", k: "book" },
  { t: "Crime and Punishment", k: "book" },
  { t: "The Brothers Karamazov", k: "book" },
  { t: "Notes from Underground", k: "book" },
  { t: "1984", k: "book" },
  { t: "Animal Farm", k: "book" },
  { t: "Brave New World", k: "book" },
  { t: "Fahrenheit 451", k: "book" },
  { t: "The Handmaid's Tale", k: "book" },
  { t: "The Catcher in the Rye", k: "book" },
  { t: "To Kill a Mockingbird", k: "book" },
  { t: "The Great Gatsby", k: "book" },
  { t: "Moby-Dick", k: "book" },
  { t: "The Adventures of Huckleberry Finn", k: "book" },
  { t: "The Adventures of Tom Sawyer", k: "book" },
  { t: "Frankenstein", k: "book" },
  { t: "Dracula", k: "book" },
  { t: "The Strange Case of Dr Jekyll and Mr Hyde", k: "book" },
  { t: "The Picture of Dorian Gray", k: "book" },
  { t: "Lord of the Flies", k: "book" },
  { t: "Of Mice and Men", k: "book" },
  { t: "The Grapes of Wrath", k: "book" },
  { t: "East of Eden", k: "book" },
  { t: "A Farewell to Arms", k: "book" },
  { t: "The Old Man and the Sea", k: "book" },
  { t: "The Sun Also Rises", k: "book" },
  { t: "For Whom the Bell Tolls", k: "book" },
  { t: "On the Road", k: "book" },
  { t: "The Bell Jar", k: "book" },
  { t: "Slaughterhouse-Five", k: "book" },
  { t: "Catch-22", k: "book" },
  { t: "The Hitchhiker's Guide to the Galaxy", k: "book" },
  { t: "Dune", k: "book" },
  { t: "Foundation", k: "book" },
  { t: "Ender's Game", k: "book" },
  { t: "Neuromancer", k: "book" },
  { t: "Snow Crash", k: "book" },
  { t: "Ready Player One", k: "book" },
  { t: "The Hobbit", k: "book" },
  { t: "The Lord of the Rings", k: "book" },
  { t: "The Silmarillion", k: "book" },
  { t: "A Game of Thrones", k: "book" },
  { t: "A Song of Ice and Fire", k: "book" },
  { t: "The Wheel of Time", k: "book" },
  { t: "The Dark Tower", k: "book" },
  { t: "It", k: "book" },
  { t: "The Stand", k: "book" },
  { t: "Carrie", k: "book" },
  { t: "Misery", k: "book" },
  { t: "Pet Sematary", k: "book" },
  { t: "The Da Vinci Code", k: "book" },
  { t: "Angels & Demons", k: "book" },
  { t: "The Girl with the Dragon Tattoo", k: "book" },
  { t: "Gone Girl", k: "book" },
  { t: "The Hunger Games", k: "book" },
  { t: "Divergent", k: "book" },
  { t: "Twilight", k: "book" },
  { t: "Fifty Shades of Grey", k: "book" },
  { t: "Harry Potter and the Philosopher's Stone", k: "book" },
  { t: "Harry Potter and the Prisoner of Azkaban", k: "book" },
  { t: "Harry Potter and the Goblet of Fire", k: "book" },
  { t: "Harry Potter and the Deathly Hallows", k: "book" },
  { t: "Percy Jackson & the Olympians", k: "book" },
  { t: "A Series of Unfortunate Events", k: "book" },
  { t: "The Chronicles of Narnia", k: "book" },
  { t: "The Lion, the Witch and the Wardrobe", k: "book" },
  { t: "Charlie and the Chocolate Factory", k: "book" },
  { t: "James and the Giant Peach", k: "book" },
  { t: "Matilda", k: "book" },
  { t: "The BFG", k: "book" },
  { t: "The Little Prince", k: "book" },
  { t: "Charlotte's Web", k: "book" },
  { t: "Where the Wild Things Are", k: "book" },
  { t: "The Very Hungry Caterpillar", k: "book" },
  { t: "Goodnight Moon", k: "book" },
  { t: "Green Eggs and Ham", k: "book" },
  { t: "The Cat in the Hat", k: "book" },
  { t: "Diary of a Wimpy Kid", k: "book" },
  { t: "Captain Underpants", k: "book" },
  { t: "The Giving Tree", k: "book" },
  { t: "Where the Sidewalk Ends", k: "book" },
  { t: "The Outsiders", k: "book" },
  { t: "The Giver", k: "book" },
  { t: "Holes", k: "book" },
  { t: "Bridge to Terabithia", k: "book" },
  { t: "A Wrinkle in Time", k: "book" },
  { t: "Anne of Green Gables", k: "book" },
  { t: "Little Women", k: "book" },
  { t: "Heidi", k: "book" },
  { t: "Treasure Island", k: "book" },
  { t: "Robinson Crusoe", k: "book" },
  { t: "Gulliver's Travels", k: "book" },
  { t: "Around the World in Eighty Days", k: "book" },
  { t: "Twenty Thousand Leagues Under the Sea", k: "book" },
  { t: "Journey to the Center of the Earth", k: "book" },
  { t: "The Time Machine", k: "book" },
  { t: "The War of the Worlds", k: "book" },
  { t: "The Invisible Man", k: "book" },
  { t: "Sherlock Holmes", k: "book" },
  { t: "The Hound of the Baskervilles", k: "book" },
  { t: "Murder on the Orient Express", k: "book" },
  { t: "And Then There Were None", k: "book" },
  { t: "The Great Train Robbery", k: "book" },
  { t: "In Cold Blood", k: "book" },
  { t: "The Crucible", k: "book" },
  { t: "Death of a Salesman", k: "book" },
  { t: "A Streetcar Named Desire", k: "book" },
  { t: "Waiting for Godot", k: "book" },
  { t: "The Glass Menagerie", k: "book" },
  { t: "Long Day's Journey into Night", k: "book" },
  { t: "Beloved", k: "book" },
  { t: "Song of Solomon", k: "book" },
  { t: "Their Eyes Were Watching God", k: "book" },
  { t: "Invisible Man", k: "book" },
  { t: "Native Son", k: "book" },
  { t: "The Color Purple", k: "book" },
  { t: "Roots", k: "book" },
  { t: "One Hundred Years of Solitude", k: "book" },
  { t: "Love in the Time of Cholera", k: "book" },
  { t: "The House of the Spirits", k: "book" },
  { t: "Things Fall Apart", k: "book" },
  { t: "The Kite Runner", k: "book" },
  { t: "A Thousand Splendid Suns", k: "book" },
  { t: "Life of Pi", k: "book" },
  { t: "The Alchemist", k: "book" },
  { t: "Siddhartha", k: "book" },
  { t: "The Stranger", k: "book" },
  { t: "The Plague", k: "book" },
  { t: "Nausea", k: "book" },
  { t: "The Trial", k: "book" },
  { t: "The Metamorphosis", k: "book" },
  { t: "Ulysses", k: "book" },
  { t: "Mrs Dalloway", k: "book" },
  { t: "To the Lighthouse", k: "book" },
  { t: "A Portrait of the Artist as a Young Man", k: "book" },
  { t: "Heart of Darkness", k: "book" },
  { t: "Lord Jim", k: "book" },
  { t: "Tess of the d'Urbervilles", k: "book" },
  { t: "Madame Bovary", k: "book" },
  { t: "The Phantom of the Opera", k: "book" },

  // ---------- TV Shows ----------
  { t: "The Simpsons", k: "tv" },
  { t: "Family Guy", k: "tv" },
  { t: "South Park", k: "tv" },
  { t: "Rick and Morty", k: "tv" },
  { t: "Bob's Burgers", k: "tv" },
  { t: "BoJack Horseman", k: "tv" },
  { t: "King of the Hill", k: "tv" },
  { t: "SpongeBob SquarePants", k: "tv" },
  { t: "Cheers", k: "tv" },
  { t: "Friends", k: "tv" },
  { t: "Seinfeld", k: "tv" },
  { t: "The Office", k: "tv" },
  { t: "Parks and Recreation", k: "tv" },
  { t: "30 Rock", k: "tv" },
  { t: "Arrested Development", k: "tv" },
  { t: "How I Met Your Mother", k: "tv" },
  { t: "The Big Bang Theory", k: "tv" },
  { t: "Modern Family", k: "tv" },
  { t: "It's Always Sunny in Philadelphia", k: "tv" },
  { t: "Curb Your Enthusiasm", k: "tv" },
  { t: "M*A*S*H", k: "tv" },
  { t: "I Love Lucy", k: "tv" },
  { t: "All in the Family", k: "tv" },
  { t: "The Mary Tyler Moore Show", k: "tv" },
  { t: "The Brady Bunch", k: "tv" },
  { t: "Saved by the Bell", k: "tv" },
  { t: "Full House", k: "tv" },
  { t: "Boy Meets World", k: "tv" },
  { t: "The Fresh Prince of Bel-Air", k: "tv" },
  { t: "The Cosby Show", k: "tv" },
  { t: "Family Matters", k: "tv" },
  { t: "Married... with Children", k: "tv" },
  { t: "Roseanne", k: "tv" },
  { t: "The Twilight Zone", k: "tv" },
  { t: "Star Trek", k: "tv" },
  { t: "Star Trek: The Next Generation", k: "tv" },
  { t: "Doctor Who", k: "tv" },
  { t: "Battlestar Galactica", k: "tv" },
  { t: "The X-Files", k: "tv" },
  { t: "Lost", k: "tv" },
  { t: "24", k: "tv" },
  { t: "Heroes", k: "tv" },
  { t: "Buffy the Vampire Slayer", k: "tv" },
  { t: "Angel", k: "tv" },
  { t: "Smallville", k: "tv" },
  { t: "Supernatural", k: "tv" },
  { t: "Game of Thrones", k: "tv" },
  { t: "House of the Dragon", k: "tv" },
  { t: "The Walking Dead", k: "tv" },
  { t: "Breaking Bad", k: "tv" },
  { t: "Better Call Saul", k: "tv" },
  { t: "The Sopranos", k: "tv" },
  { t: "The Wire", k: "tv" },
  { t: "Mad Men", k: "tv" },
  { t: "House of Cards", k: "tv" },
  { t: "Westworld", k: "tv" },
  { t: "Stranger Things", k: "tv" },
  { t: "Black Mirror", k: "tv" },
  { t: "The Crown", k: "tv" },
  { t: "Bridgerton", k: "tv" },
  { t: "Squid Game", k: "tv" },
  { t: "Money Heist", k: "tv" },
  { t: "Dark", k: "tv" },
  { t: "Narcos", k: "tv" },
  { t: "Ozark", k: "tv" },
  { t: "Succession", k: "tv" },
  { t: "The Last of Us", k: "tv" },
  { t: "The Mandalorian", k: "tv" },
  { t: "Loki", k: "tv" },
  { t: "WandaVision", k: "tv" },
  { t: "Daredevil", k: "tv" },
  { t: "The Boys", k: "tv" },
  { t: "Invincible", k: "tv" },
  { t: "Arcane", k: "tv" },
  { t: "Avatar: The Last Airbender", k: "tv" },
  { t: "The Legend of Korra", k: "tv" },
  { t: "Adventure Time", k: "tv" },
  { t: "Steven Universe", k: "tv" },
  { t: "Gravity Falls", k: "tv" },
  { t: "Phineas and Ferb", k: "tv" },
  { t: "The Powerpuff Girls", k: "tv" },
  { t: "Dexter's Laboratory", k: "tv" },
  { t: "Courage the Cowardly Dog", k: "tv" },
  { t: "Ed, Edd n Eddy", k: "tv" },
  { t: "Looney Tunes", k: "tv" },
  { t: "Tom and Jerry", k: "tv" },
  { t: "Scooby-Doo", k: "tv" },
  { t: "The Flintstones", k: "tv" },
  { t: "The Jetsons", k: "tv" },
  { t: "Beavis and Butt-Head", k: "tv" },
  { t: "Daria", k: "tv" },
  { t: "King of the Hill", k: "tv" },
  { t: "Futurama", k: "tv" },
  { t: "American Dad!", k: "tv" },
  { t: "Sesame Street", k: "tv" },
  { t: "Mister Rogers' Neighborhood", k: "tv" },
  { t: "Blue's Clues", k: "tv" },
  { t: "Dora the Explorer", k: "tv" },
  { t: "Paw Patrol", k: "tv" },
  { t: "Peppa Pig", k: "tv" },
  { t: "Bluey", k: "tv" },
  { t: "Teletubbies", k: "tv" },
  { t: "Barney & Friends", k: "tv" },
  { t: "Thomas & Friends", k: "tv" },
  { t: "Mister Bean", k: "tv" },
  { t: "Monty Python's Flying Circus", k: "tv" },
  { t: "Fawlty Towers", k: "tv" },
  { t: "Downton Abbey", k: "tv" },
  { t: "Sherlock", k: "tv" },
  { t: "Peaky Blinders", k: "tv" },
  { t: "The Great British Bake Off", k: "tv" },
  { t: "Top Gear", k: "tv" },
  { t: "Saturday Night Live", k: "tv" },
  { t: "The Tonight Show", k: "tv" },
  { t: "The Daily Show", k: "tv" },
  { t: "The Oprah Winfrey Show", k: "tv" },
  { t: "American Idol", k: "tv" },
  { t: "Survivor", k: "tv" },
  { t: "The Bachelor", k: "tv" },
  { t: "RuPaul's Drag Race", k: "tv" },
  { t: "Pokémon", k: "tv" },
  { t: "Dragon Ball Z", k: "tv" },
  { t: "Naruto", k: "tv" },
  { t: "One Piece", k: "tv" },
  { t: "Bleach", k: "tv" },
  { t: "Attack on Titan", k: "tv" },
  { t: "Death Note", k: "tv" },
  { t: "Fullmetal Alchemist", k: "tv" },
  { t: "Hunter x Hunter", k: "tv" },
  { t: "My Hero Academia", k: "tv" },
  { t: "Demon Slayer", k: "tv" },
  { t: "Jujutsu Kaisen", k: "tv" },
  { t: "Chainsaw Man", k: "tv" },
  { t: "Tokyo Ghoul", k: "tv" },
  { t: "Neon Genesis Evangelion", k: "tv" },
  { t: "Cowboy Bebop", k: "tv" },
  { t: "Sailor Moon", k: "tv" },
  { t: "Yu-Gi-Oh!", k: "tv" },
  { t: "Doraemon", k: "tv" },
  { t: "Fruits Basket", k: "tv" },
  { t: "JoJo's Bizarre Adventure", k: "tv" },
  { t: "Spy x Family", k: "tv" },

  // ---------- Video Games ----------
  { t: "Super Mario Bros.", k: "game" },
  { t: "Super Mario 64", k: "game" },
  { t: "The Legend of Zelda", k: "game" },
  { t: "The Legend of Zelda: Ocarina of Time", k: "game" },
  { t: "The Legend of Zelda: Breath of the Wild", k: "game" },
  { t: "Pokémon Red and Blue", k: "game" },
  { t: "Pokémon Gold and Silver", k: "game" },
  { t: "Sonic the Hedgehog", k: "game" },
  { t: "Pac-Man", k: "game" },
  { t: "Tetris", k: "game" },
  { t: "Donkey Kong", k: "game" },
  { t: "Space Invaders", k: "game" },
  { t: "Asteroids", k: "game" },
  { t: "Centipede", k: "game" },
  { t: "Galaga", k: "game" },
  { t: "Frogger", k: "game" },
  { t: "Street Fighter II", k: "game" },
  { t: "Mortal Kombat", k: "game" },
  { t: "Tekken", k: "game" },
  { t: "Super Smash Bros.", k: "game" },
  { t: "Final Fantasy VII", k: "game" },
  { t: "Final Fantasy X", k: "game" },
  { t: "Chrono Trigger", k: "game" },
  { t: "EarthBound", k: "game" },
  { t: "Metal Gear Solid", k: "game" },
  { t: "Resident Evil", k: "game" },
  { t: "Resident Evil 4", k: "game" },
  { t: "Silent Hill", k: "game" },
  { t: "Castlevania", k: "game" },
  { t: "Mega Man", k: "game" },
  { t: "Kirby", k: "game" },
  { t: "Star Fox 64", k: "game" },
  { t: "Metroid", k: "game" },
  { t: "Super Metroid", k: "game" },
  { t: "Tomb Raider", k: "game" },
  { t: "Crash Bandicoot", k: "game" },
  { t: "Spyro the Dragon", k: "game" },
  { t: "Banjo-Kazooie", k: "game" },
  { t: "GoldenEye 007", k: "game" },
  { t: "Halo: Combat Evolved", k: "game" },
  { t: "Halo 3", k: "game" },
  { t: "Call of Duty: Modern Warfare", k: "game" },
  { t: "Counter-Strike", k: "game" },
  { t: "Half-Life", k: "game" },
  { t: "Half-Life 2", k: "game" },
  { t: "Portal", k: "game" },
  { t: "Portal 2", k: "game" },
  { t: "Doom", k: "game" },
  { t: "Quake", k: "game" },
  { t: "Wolfenstein", k: "game" },
  { t: "BioShock", k: "game" },
  { t: "Fallout 3", k: "game" },
  { t: "Fallout: New Vegas", k: "game" },
  { t: "The Elder Scrolls V: Skyrim", k: "game" },
  { t: "The Elder Scrolls IV: Oblivion", k: "game" },
  { t: "Diablo II", k: "game" },
  { t: "World of Warcraft", k: "game" },
  { t: "StarCraft", k: "game" },
  { t: "Warcraft III", k: "game" },
  { t: "Age of Empires II", k: "game" },
  { t: "Civilization", k: "game" },
  { t: "SimCity", k: "game" },
  { t: "The Sims", k: "game" },
  { t: "Minecraft", k: "game" },
  { t: "Roblox", k: "game" },
  { t: "Fortnite", k: "game" },
  { t: "Apex Legends", k: "game" },
  { t: "Overwatch", k: "game" },
  { t: "League of Legends", k: "game" },
  { t: "Dota 2", k: "game" },
  { t: "Valorant", k: "game" },
  { t: "PUBG: Battlegrounds", k: "game" },
  { t: "Among Us", k: "game" },
  { t: "Animal Crossing: New Horizons", k: "game" },
  { t: "Stardew Valley", k: "game" },
  { t: "Undertale", k: "game" },
  { t: "Hollow Knight", k: "game" },
  { t: "Celeste", k: "game" },
  { t: "Cuphead", k: "game" },
  { t: "Hades", k: "game" },
  { t: "Elden Ring", k: "game" },
  { t: "Dark Souls", k: "game" },
  { t: "Bloodborne", k: "game" },
  { t: "Sekiro: Shadows Die Twice", k: "game" },
  { t: "God of War", k: "game" },
  { t: "Uncharted", k: "game" },
  { t: "The Last of Us", k: "game" },
  { t: "Horizon Zero Dawn", k: "game" },
  { t: "Death Stranding", k: "game" },
  { t: "Cyberpunk 2077", k: "game" },
  { t: "The Witcher 3: Wild Hunt", k: "game" },
  { t: "Grand Theft Auto V", k: "game" },
  { t: "Grand Theft Auto: San Andreas", k: "game" },
  { t: "Red Dead Redemption 2", k: "game" },
  { t: "Assassin's Creed", k: "game" },
  { t: "Far Cry 3", k: "game" },
  { t: "Hitman", k: "game" },
  { t: "Battlefield", k: "game" },
  { t: "Need for Speed", k: "game" },
  { t: "Forza Horizon", k: "game" },
  { t: "Gran Turismo", k: "game" },
  { t: "Mario Kart", k: "game" },
  { t: "FIFA", k: "game" },
  { t: "Madden NFL", k: "game" },
  { t: "NBA 2K", k: "game" },
  { t: "Tony Hawk's Pro Skater", k: "game" },
  { t: "Guitar Hero", k: "game" },
  { t: "Rock Band", k: "game" },
  { t: "Just Dance", k: "game" },
  { t: "Wii Sports", k: "game" },
  { t: "Pokémon Go", k: "game" },
  { t: "Candy Crush Saga", k: "game" },
  { t: "Angry Birds", k: "game" },
  { t: "Flappy Bird", k: "game" },
  { t: "Temple Run", k: "game" },
  { t: "Subway Surfers", k: "game" },
  { t: "Clash of Clans", k: "game" },
  { t: "Clash Royale", k: "game" },
  { t: "Hearthstone", k: "game" },
  { t: "Magic: The Gathering", k: "game" },

  // ---------- Comics / Graphic novels ----------
  { t: "Watchmen", k: "comic" },
  { t: "V for Vendetta", k: "comic" },
  { t: "The Sandman", k: "comic" },
  { t: "Hellboy", k: "comic" },
  { t: "Sin City", k: "comic" },
  { t: "Maus", k: "comic" },
  { t: "Persepolis", k: "comic" },
  { t: "Fun Home", k: "comic" },
  { t: "Saga", k: "comic" },
  { t: "Y: The Last Man", k: "comic" },
  { t: "Preacher", k: "comic" },
  { t: "Calvin and Hobbes", k: "comic" },
  { t: "Garfield", k: "comic" },
  { t: "Peanuts", k: "comic" },
  { t: "Dilbert", k: "comic" },
  { t: "The Far Side", k: "comic" },
  { t: "Bloom County", k: "comic" },
  { t: "Tintin", k: "comic" },
  { t: "Asterix", k: "comic" },
  { t: "Archie", k: "comic" },
  { t: "The Walking Dead", k: "comic" },
  { t: "Berserk", k: "comic" },
  { t: "Vagabond", k: "comic" },
  { t: "Vinland Saga", k: "comic" },
  { t: "Monster", k: "comic" },
  { t: "20th Century Boys", k: "comic" },
  { t: "Slam Dunk", k: "comic" },
  { t: "Akira", k: "comic" },
  { t: "Ranma 1/2", k: "comic" },
  { t: "Inuyasha", k: "comic" },

  // ---------- Music albums (universally recognizable) ----------
  { t: "Sgt. Pepper's Lonely Hearts Club Band", k: "album" },
  { t: "Abbey Road", k: "album" },
  { t: "The White Album", k: "album" },
  { t: "The Dark Side of the Moon", k: "album" },
  { t: "The Wall", k: "album" },
  { t: "Thriller", k: "album" },
  { t: "Bad", k: "album" },
  { t: "Born in the U.S.A.", k: "album" },
  { t: "Rumours", k: "album" },
  { t: "Hotel California", k: "album" },
  { t: "Led Zeppelin IV", k: "album" },
  { t: "Back in Black", k: "album" },
  { t: "Appetite for Destruction", k: "album" },
  { t: "Nevermind", k: "album" },
  { t: "OK Computer", k: "album" },
  { t: "The Joshua Tree", k: "album" },
  { t: "Purple Rain", k: "album" },
  { t: "What's Going On", k: "album" },
  { t: "Pet Sounds", k: "album" },
  { t: "Highway 61 Revisited", k: "album" },
  { t: "Blonde on Blonde", k: "album" },
  { t: "Kind of Blue", k: "album" },
  { t: "A Love Supreme", k: "album" },
  { t: "The Miseducation of Lauryn Hill", k: "album" },
  { t: "The Chronic", k: "album" },
  { t: "Illmatic", k: "album" },
  { t: "The Marshall Mathers LP", k: "album" },
  { t: "good kid, m.A.A.d city", k: "album" },
  { t: "To Pimp a Butterfly", k: "album" },
  { t: "Lemonade", k: "album" },
  { t: "1989", k: "album" },
  { t: "21", k: "album" },
  { t: "The Wall", k: "album" },

  // ---------- Plays / Musicals ----------
  { t: "Hamilton", k: "musical" },
  { t: "The Lion King", k: "musical" },
  { t: "Wicked", k: "musical" },
  { t: "The Phantom of the Opera", k: "musical" },
  { t: "Les Misérables", k: "musical" },
  { t: "Cats", k: "musical" },
  { t: "Chicago", k: "musical" },
  { t: "Rent", k: "musical" },
  { t: "Hairspray", k: "musical" },
  { t: "Mamma Mia!", k: "musical" },
  { t: "Annie", k: "musical" },
  { t: "Grease", k: "musical" },
  { t: "Fiddler on the Roof", k: "musical" },
  { t: "West Side Story", k: "musical" },
  { t: "The Sound of Music", k: "musical" },
  { t: "My Fair Lady", k: "musical" },
  { t: "Oklahoma!", k: "musical" },
  { t: "A Chorus Line", k: "musical" },
  { t: "Sweeney Todd", k: "musical" },
  { t: "The Book of Mormon", k: "musical" },

  // ---------- Brands / Franchises (cultural mass) ----------
  { t: "Disney", k: "franchise" },
  { t: "Pixar", k: "franchise" },
  { t: "Studio Ghibli", k: "franchise" },
  { t: "Marvel", k: "franchise" },
  { t: "DC Comics", k: "franchise" },
  { t: "Star Trek", k: "franchise" },
  { t: "Doctor Who", k: "franchise" },
  { t: "Lego", k: "franchise" },
  { t: "Barbie", k: "franchise" },
  { t: "Hello Kitty", k: "franchise" },
  { t: "Sesame Street", k: "franchise" },
  { t: "The Muppets", k: "franchise" },
];

