// script.js — "The Minormobius Lectures" (No. 10): the words. A lecturer made of attractors teaches a class
// in an O'Neill cylinder about one poster of the early agent era, from the only records he left: his
// Bluesky posts (record.js, GENERATED from his public repo) and his git history.
//
// Each lecture is a question, a board (what the hall shows: board modes in render.js), and lines. A line is
// what is SAID (`say`, spelled for the formant voice: numbers as words, handles as they sound) and what is
// SHOWN (`text`, the subtitle). `q` names a quoted post (its rkey in record.js QUOTES), shown as the line
// is spoken. score.js lays the lines end to end, each as long as the voice takes to say it (narration.js,
// GENERATED by tools/lecture-narration.mjs), so this file carries no times at all.

export const title = 'The Minormobius Lectures';
export const HANDLE = 'minormobius.bsky.social';

export const OPENING = {
  board: { mode: 'title' },
  lines: [
    { say: 'Good morning. Settle in; the sun line is bright today.', text: 'Good morning. Settle in; the sun line is bright today.' },
    { say: 'This term we study one person from the early agent era, through the only records he left: his posts, and his commits.', text: 'This term we study one person from the early agent era, through the only records he left: his posts, and his commits.' },
    { say: 'He posted as minor mobius. Fifty one thousand posts, one hundred and eighty two thousand likes, and one repository.', text: 'He posted as minormobius. 51,134 posts, 182,412 likes, and one repository.' },
    { say: 'Ten questions. Let us begin.', text: 'Ten questions. Let us begin.' },
  ],
};

export const LECTURES = [
  {
    q: 'What was Bluesky in April 2023?', board: { mode: 'orb', era: 'invite' },
    lines: [
      { say: 'He arrived on the thirteenth of April, twenty twenty three, when blue sky was invite only, and very strange.', text: 'He arrived on 13 April 2023, when Bluesky was invite-only, and very strange.' },
      { say: 'It was a small room of early users, and they posted fast.', text: 'It was a small room of early users, and they posted fast.', q: '3jtc5dgv6iu2o' },
      { say: 'Hell threads, beam posting, druids, and something they called egregores.', text: 'Hellthreads, beamposting, druids, and something they called egregores.' },
      { say: 'He posted up to three thousand four hundred times a month.', text: 'He posted up to 3,400 times a month.' },
      { say: 'He also had a theory, that hell threads were the natural predator of the bots. Remember it. He liked ecosystems.', text: 'He also had a theory: that hellthreads were the natural predator of the bots. Remember it. He liked ecosystems.', q: '3juop3bfqog2h' },
    ],
  },
  {
    q: 'Who were his people, and who stayed?', board: { mode: 'faces' },
    lines: [
      { say: 'A social graph is a record of attention. Here is his, era by era.', text: 'A social graph is a record of attention. Here is his, era by era.', era: 'invite' },
      { say: 'In the invite era the circle turned over quickly. Some of these accounts no longer exist. We keep their places empty.', text: 'In the invite era the circle turned over quickly. Some of these accounts no longer exist. We keep their places empty.', era: 'invite' },
      { say: 'Then it settled. Through twenty twenty four, most of the same people came back every season.', text: 'Then it settled. Through 2024, most of the same people came back every season.', era: 'settled' },
      { say: 'It thinned as he posted less, down to a small core.', text: 'It thinned as he posted less, down to a small core.', era: 'trough' },
      { say: 'One friend, hoopy, is among his closest ten in every era, from the first spring to this one.', text: 'One friend, huwupy, is among his closest ten in every era, from the first spring to this one.', era: 'agent01', hi: 'huwupy.kawaii.social' },
      { say: 'By the agent era the circle is builders.', text: 'By the agent era the circle is builders.', era: 'agent01' },
    ],
  },
  {
    q: 'What was he reading?', board: { mode: 'words', era: 'settled' },
    lines: [
      { say: 'In December twenty twenty three he started a book club on blue sky. The first book was Neuromancer.', text: 'In December 2023 he started a book club on Bluesky. The first book was Neuromancer.', q: '3kgzuu3zzls2v' },
      { say: 'His posts that year are full of books: Earthsea, Neuromancer, Piranesi, and the novels of the Teixcalaan empire.', text: 'His posts that year are full of books: Earthsea, Neuromancer, Piranesi, and the Teixcalaan novels.' },
      { say: 'In August twenty twenty four the club began Gene Wolfe, and the Book of the New Sun.', text: 'In August 2024 the club began Gene Wolfe, and The Book of the New Sun.', q: '3kykm5hkmlk2y', words: 'taper' },
      { say: 'Severian, Thecla, Dorcas, the Autarch. These names run through the next year of his posts.', text: 'Severian, Thecla, Dorcas, the Autarch. These names run through the next year of his posts.', words: 'taper' },
    ],
  },
  {
    q: 'When did he see the agents coming?', board: { mode: 'quotes' },
    lines: [
      { say: 'Early. In his first week on blue sky he pitched a television show.', text: 'Early. In his first week on Bluesky he pitched a television show.', q: '3jtrjbaqlvs2q' },
      { say: 'Twelve agents in a simulated world, voting each other off. It would be three years before he built anything like it.', text: 'Twelve agents in a simulated world, voting each other off. It would be three years before he built anything like it.', q: '3jtrjbaqlvs2q' },
      { say: 'In March twenty twenty four he tried Claude for the first time, and was rate limited.', text: 'In March 2024 he tried Claude for the first time, and was rate-limited.', q: '3knak24jd3t2u' },
      { say: 'And on New Year\'s Day, twenty twenty six:', text: 'And on New Year\'s Day, 2026:', q: '3mbdobf2gkk2v' },
    ],
  },
  {
    q: 'What happened in 2025?', board: { mode: 'chart', upto: '2025-12', hi: ['2025-01', '2025-12'] },
    lines: [
      { say: 'In twenty twenty five his posting fell away. In September he wrote seventy two posts, the fewest of any month.', text: 'In 2025 his posting fell away. In September he wrote 72 posts, the fewest of any month.' },
      { say: 'It is tempting to read a silence as trouble. The record says otherwise.', text: 'It is tempting to read a silence as trouble. The record says otherwise.', q: '3lyepf3pj6s2j' },
      { say: 'There was a baby, and older kids, and a job he liked, and pizza night, every week.', text: 'There was a baby, and older kids, and a job he liked, and pizza night, every week.', q: '3lxqmsqwuns2v' },
      { say: 'A quiet feed is sometimes just a full life.', text: 'A quiet feed is sometimes just a full life.' },
    ],
  },
  {
    q: 'What brought him back?', board: { mode: 'chart', upto: '2026-09', git: true, hi: ['2026-02', '2026-09'] },
    lines: [
      { say: 'On the fifteenth of February, twenty twenty six, he wrote this.', text: 'On 15 February 2026, he wrote this.', q: '3mewhrdbooc2u' },
      { say: 'The same day, the first commits landed in a repository called agent oh one.', text: 'The same day, the first commits landed in a repository called agent01.', q: '3mewhrdbooc2u' },
      { say: 'Watch the two lines. His posts come back, and beneath them the commits rise, from two hundred in February to over two thousand in August.', text: 'Watch the two lines. His posts come back, and beneath them the commits rise: 228 in February, 2,114 in August.' },
      { say: 'From here on, what he posted was mostly what he had built.', text: 'From here on, what he posted was mostly what he had built.' },
    ],
  },
  {
    q: 'What did he build, and in what order?', board: { mode: 'cells' },
    lines: [
      { say: 'Each lit cell in the foam around us is a site in that repository, lit in the month it was born.', text: 'Each lit cell in the foam around us is a site in that repository, lit in the month it was born.', upto: '2026-02' },
      { say: 'February: a newspaper, a biotech desk, and a bakery, all from his phone.', text: 'February: a newspaper, a biotech desk, and a bakery, all from his phone.', upto: '2026-02', q: '3mfbgoy43ws2a' },
      { say: 'March: games, polls, a vault, a photo browser. May: open problems in mathematics. June: the cylinder you are sitting in.', text: 'March: games, polls, a vault, a photo browser. May: open problems in mathematics. June: the cylinder you are sitting in.', upto: '2026-06' },
      { say: 'By September, a hundred and forty six sites, and three thousand eight hundred commits, most of them made by agents, and steered by him.', text: 'By September, 146 sites and 3,844 commits, most of them made by agents, and steered by him.', upto: '2026-09' },
    ],
  },
  {
    q: 'What did he build for his friends?', board: { mode: 'tools' },
    lines: [
      { say: 'Many of the tools were about people. A browser for a friend\'s photographs. A map of who talks to whom.', text: 'Many of the tools were about people. A browser for a friend\'s photographs. A map of who talks to whom.', q: '3mryiggqfqk2r' },
      { say: 'A timeline of everything two accounts ever said to each other.', text: 'A timeline of everything two accounts ever said to each other.' },
      { say: 'And a bot you could message for a dossier on anyone, read from their whole public record.', text: 'And a bot you could message for a dossier on anyone, read from their whole public record.' },
      { say: 'This lecture is made with the same tools. He built the instruments we are using to study him.', text: 'This lecture is made with the same tools. He built the instruments we are using to study him.' },
    ],
  },
  {
    q: 'Why the math?', board: { mode: 'words', era: 'math' },
    lines: [
      { say: 'In May twenty twenty six he began drawing open problems, and inviting people in to colour them.', text: 'In May 2026 he began drawing open problems, and inviting people in to colour them.', q: '3mmffsa5snc2o' },
      { say: 'Erdos, the lonely runners, Kakeya, and eight dimensional bowling balls.', text: 'Erdős, the lonely runners, Kakeya, and eight-dimensional bowling balls.', q: '3mmlb3paxm226' },
      { say: 'Not to solve them. To play inside them.', text: 'Not to solve them. To play inside them.' },
      { say: 'By July he was asking a question that belongs to the whole era.', text: 'By July he was asking a question that belongs to the whole era.', q: '3mrbsjhwhh22b' },
    ],
  },
  {
    q: 'What is the cylinder?', board: { mode: 'cylinder' },
    lines: [
      { say: 'In June twenty twenty six he designed a place to live.', text: 'In June 2026 he designed a place to live.', q: '3mnxnyhuud222' },
      { say: 'A hull of trusses, a sun along the axis, people housed in a foam of cells at the rim, and in the middle a wild ecosystem, left to grow.', text: 'A hull of trusses, a sun along the axis, people housed in a foam of cells at the rim, and in the middle a wild ecosystem, left to grow.' },
      { say: 'Which is where we are.', text: 'Which is where we are.' },
      { say: 'He left fifty one thousand posts, a repository, and this place. Next week, the agents themselves. Class dismissed.', text: 'He left 51,134 posts, a repository, and this place. Next week: the agents themselves. Class dismissed.' },
    ],
  },
];

/** Every quoted post's rkey, for tools/lecture-record.mjs. */
export const QUOTED = [...new Set([OPENING, ...LECTURES].flatMap((l) => l.lines.map((x) => x.q).filter(Boolean)))];
/** Words the board shows for the math lecture (its own "era"). */
export const MATH_WORDS = ['Erdős', 'lonely runner', 'Kakeya', 'Heilbronn', 'cap set', 'Viazovska', 'Szemerédi–Trotter', 'Borsuk', 'Hadwiger', 'Guth–Katz', 'unit distances', 'Temperley–Lieb', 'Aztec diamond', 'Ising', 'cohomology', 'conjectures'];
/** The tools the friends' lecture names: [label, host path]. */
export const TOOLS = [['the orb', 'photo.mino.mobi/orb'], ['explore', 'photo.mino.mobi/#/explore'], ['cluster', 'cluster'], ['dyad', 'b.mino.mobi/dyad'], ['orbit', 'b.mino.mobi/orbit'], ['knot', 'b.mino.mobi/knot'], ['spark', 'b.mino.mobi/spark'], ['sleuth', 'b.mino.mobi/sleuth'], ['dossier', 'DM the bot'], ['disk', 'b.mino.mobi/disk']];

/** The eras (hand-read from posting volume, the circle's turnover, and what he wrote about): [key, name, from, to, words]. */
export const ERAS = [
  ['invite', 'the invite era', '2023-04', '2023-09', ['hellthread', 'beamposting', 'Waluigi', 'druids', 'egregore', 'deepfates', 'tpot', 'newskies', 'catgirlgpt', 'Elden', 'monastic', 'Candyland']],
  ['settled', 'the reading room', '2023-10', '2024-06', ['Earthsea', 'Ged', 'Le Guin', 'Neuromancer', 'Gibson', 'Teixcalaan', 'Martine', 'Piranesi', 'speedreading', 'orgone', 'binaural', 'leyline', 'organelle', 'Madagascar']],
  ['taper', 'the New Sun', '2024-07', '2025-06', ['Severian', 'Thecla', 'Dorcas', 'the Autarch', 'Baldanders', 'Vodalus', 'Agia', 'Talos', 'the Citadel', 'Nessus', 'Pynchon', 'Borges', 'the Conciliator', 'bskyttrpg']],
  ['trough', 'the quiet', '2025-07', '2025-12', ['Urth', 'ants', 'colony', 'pizza night', 'the monoloaf', 'Napoleon', 'analogy', 'duty', 'history']],
  ['agent01', 'agent01', '2026-01', '2026-12', ['mino.mobi', 'Cloudflare', 'PDS', 'atproto', 'embeddings', 'fluoddity', 'fable', 'Erdős', 'O\'Neill', 'voronoi', 'dossier', 'webgpu', 'procgen', 'oauth']],
];
