// ansur2.js — GENERATED by reference/ansur2.mjs from ANSUR II; do not edit.
// Body proportions of 6,068 US Army personnel, in heads (see that script).
export default {
 "male": {
  "heads_tall": [
   6.802,
   7.457,
   8.2
  ],
  "suprasternale_below_chin": [
   0.215,
   0.348,
   0.5
  ],
  "cervicale_below_chin": [
   -0.101,
   0.015,
   0.145
  ],
  "acromion_below_chin": [
   0.188,
   0.34,
   0.515
  ],
  "chest_below_chin": [
   0.774,
   0.974,
   1.202
  ],
  "waist_below_chin": [
   1.69,
   1.97,
   2.289
  ],
  "trochanter_below_chin": [
   2.278,
   2.634,
   3.023
  ],
  "crotch_below_chin": [
   2.505,
   2.868,
   3.275
  ],
  "buttock_below_chin": [
   2.326,
   2.689,
   3.093
  ],
  "knee_below_chin": [
   3.912,
   4.383,
   4.923
  ],
  "waist_to_hip_breadth": [
   0.852,
   0.943,
   1.034
  ],
  "bideltoid_to_hip_breadth": [
   1.365,
   1.478,
   1.599
  ],
  "chest_to_hip_breadth": [
   0.76,
   0.839,
   0.917
  ],
  "buttock_to_waist_depth": [
   0.913,
   1.043,
   1.172
  ],
  "chest_to_waist_depth": [
   0.935,
   1.075,
   1.229
  ],
  "neck_circ_to_head": [
   1.501,
   1.684,
   1.913
  ],
  "hip_breadth_heads": [
   1.293,
   1.465,
   1.673
  ],
  "bideltoid_heads": [
   1.919,
   2.168,
   2.444
  ],
  "thigh_circ_to_hip_breadth": [
   1.649,
   1.809,
   1.963
  ],
  "r_chestdepth_chestbreadth": 0.558,
  "r_projection_vs_chestbreadth": -0.271,
  "n": 4082
 },
 "female": {
  "heads_tall": [
   6.844,
   7.496,
   8.261
  ],
  "suprasternale_below_chin": [
   0.243,
   0.377,
   0.531
  ],
  "cervicale_below_chin": [
   -0.042,
   0.075,
   0.197
  ],
  "acromion_below_chin": [
   0.205,
   0.35,
   0.511
  ],
  "chest_below_chin": [
   0.879,
   1.101,
   1.353
  ],
  "waist_below_chin": [
   1.708,
   1.993,
   2.285
  ],
  "trochanter_below_chin": [
   2.261,
   2.608,
   3.005
  ],
  "crotch_below_chin": [
   2.53,
   2.899,
   3.304
  ],
  "buttock_below_chin": [
   2.302,
   2.66,
   3.054
  ],
  "knee_below_chin": [
   3.948,
   4.429,
   4.982
  ],
  "waist_to_hip_breadth": [
   0.76,
   0.842,
   0.949
  ],
  "bideltoid_to_hip_breadth": [
   1.162,
   1.274,
   1.395
  ],
  "chest_to_hip_breadth": [
   0.682,
   0.763,
   0.846
  ],
  "buttock_to_waist_depth": [
   0.949,
   1.103,
   1.256
  ],
  "chest_to_waist_depth": [
   1.004,
   1.169,
   1.357
  ],
  "neck_circ_to_head": [
   1.368,
   1.516,
   1.696
  ],
  "hip_breadth_heads": [
   1.422,
   1.628,
   1.864
  ],
  "bideltoid_heads": [
   1.846,
   2.074,
   2.334
  ],
  "thigh_circ_to_hip_breadth": [
   1.608,
   1.738,
   1.881
  ],
  "r_chestdepth_chestbreadth": 0.645,
  "r_projection_vs_chestbreadth": -0.03,
  "n": 1986
 }
};
