// ─────────────────────────────────────────────────────────────────────────────
// data.js — an ORIGINAL English translation of MACER FLORIDUS, De viribus herbarum
// (the "Macer"), set beside the Latin, line for line.
//
//   Odo Magdunensis ("Macer Floridus"), 11th c. — a Latin hexameter herb-poem of
//   77 plants, the most-copied herbal of the Middle Ages and the direct
//   descendant of Walahfrid's Hortulus. Where the Hortulus is a lyric garden,
//   Macer is an apothecary: each plant opens with its Galenic "degrees" of heat
//   and dryness, then a litany of decoctions, doses, and cures.
//
// WHY IT IS BED #2. It shares 17 of Walahfrid's 23 plants, so the two poems read
// as a dialogue on the same herbs — lyric vs. clinical. Each shared plant here
// carries a `hortulus` link to its Walahfrid counterpart (the crosswalk spine).
// Macer's stated degrees will also feed the garden's correspondence overlay.
//
// SOURCE OF TRUTH (Tranche 1). The Latin is transcribed from the received text on
// Latin Wikisource (the Choulant 1832 vulgate) — read directly, not from OCR
// (the Internet Archive's OCR of Choulant conflates Macer's formulaic chapters
// and is NOT trusted here). Lightly normalised: consonantal j → i. The modern
// critical edition (Schnell & Crossgrove, Tübingen 2003) and the manuscript
// tradition are the spine to converge on.
//
// The English is ours. A chapter is "planted" iff it carries `lines`; the rest
// are fallow, enumerated in the vulgate's order, awaiting later tranches. The 77
// run from the temperate garden herbs to a closing section of Eastern spices
// (Piper … Aloe), of which only Costus touches Walahfrid's plot. CC BY-SA 4.0.
// ─────────────────────────────────────────────────────────────────────────────
'use strict';

export const MACER = {
  meta: {
    title: 'Macer Floridus',
    work: 'De viribus herbarum',
    author: 'Odo Magdunensis ("Macer Floridus"), 11th c.',
    date: 'c. 1070–1100',
    dedicatee: null,
    license: 'CC BY-SA 4.0',
    method:
      'The Hortulus’s own descendant: a Latin hexameter herb-poem of 77 plants, ' +
      'written some two centuries later in the clinical register of the school of ' +
      'Salerno — degree of heat, decoction, dose. Where it shares a plant with ' +
      'Walahfrid (17 of his 23 beds), the two read as a dialogue: the lyric garden ' +
      'against the apothecary. The Latin is transcribed from the received text on ' +
      'Latin Wikisource (the Choulant 1832 vulgate), lightly normalised (j→i); the ' +
      'modern critical edition (Schnell–Crossgrove, 2003) is the spine to converge ' +
      'on. Each herb’s Galenic “degrees” are noted where Macer gives them — the raw ' +
      'material for the garden’s coming correspondence overlay. The English is ours.',
    latinSource: 'Received text (Choulant 1832 vulgate) via Latin Wikisource (transcription covers ~ch. 1–50; the back half, incl. the Eastern spices, awaits the full Choulant text)',
    convergeOn: 'Schnell & Crossgrove, Macer Floridus «De viribus herbarum» (Tübingen, 2003), and the manuscript tradition',
    sources: [
      { label: 'De viribus herbarum (Odo Magdunensis / Macer) — full Latin text', host: 'la.wikisource.org', url: 'https://la.wikisource.org/wiki/De_viribus_herbarum' },
      { label: 'Choulant, Macer Floridus de viribus herbarum (Leipzig, 1832) — the vulgate edition', host: 'archive.org', url: 'https://archive.org/details/deviribusherbaru00mace' },
      { label: 'Schnell & Crossgrove (Tübingen, 2003) — the modern critical edition, to converge on', host: 'reference', url: 'https://www.worldcat.org/oclc/76681313' },
    ],
  },

  // Every chapter in the vulgate's order (seq = chapter number, 1–77). A chapter
  // is "planted" when it has `lines`. `hortulus` is the seq of the matching bed in
  // ../hortulus/ (the crosswalk link) — present only for the 17 shared plants
  // (+ Costus, which Walahfrid names in his clary bed). `degrees` records Macer's
  // Galenic heat/dryness where stated, for the correspondence overlay.
  sections: [
    { seq: 1,  la: 'Artemisia',  en: 'Mugwort',        bot: 'Artemisia vulgaris' },

    // ── 2. Southernwood — pairs with Hortulus IV ──────────────────────────────
    {
      seq: 2, la: 'Abrotanum', en: 'Southernwood', bot: 'Artemisia abrotanum',
      hortulus: 4, degrees: 'hot in the 3rd degree, drying (the seed more fiercely)',
      lines: [
        { la: 'Tertius Abrotano legitur gradus esse caloris,', en: 'Southernwood is reckoned to stand in the third degree of heat,',
          n: 'Macer opens, as he does for nearly every herb, with the Galenic “degrees” — the graded scale of heat and dryness that the correspondence overlay will draw on.' },
        { la: 'et desiccandi semen ferventius herba est,', en: 'and in drying its seed is fiercer than the leaf;' },
        { la: 'unde iuvat nervos et causas pectoris omnes,', en: 'whence it helps the sinews and every trouble of the chest,' },
        { la: 'illius elixi si sit decoctio sumpta.', en: 'if a decoction of it, well boiled, be taken.' },
        { la: 'Sic quoque dysnoicis prodest tussimque repellit,', en: 'So too it helps the short of breath, and drives off the cough,' },
        { la: 'et prodest lumbis, sic vulvarumque querelis.', en: 'and helps the loins, and likewise the complaints of the womb.' },
        { la: 'Omnibus his crudum cum vino proderit haustum,', en: 'For all these, taken raw with wine, it will serve,' },
        { la: 'urinam purgat sic et praecordia mundat,', en: 'thus it purges the urine and cleanses the midriff,' },
        { la: 'sic curat sciasim, sic sumptum menstrua purgat,', en: 'thus it cures sciatica, thus taken it brings on the menses,' },
        { la: 'serpentes nidore fugat, bibitumque venena', en: 'it routs serpents by its reek, and, drunk, the venom' },
        { la: 'illorum extinguit, sedat quoque frigora febris', en: 'of those it quenches; it calms too the chills of fever' },
        { la: 'antea quam veniant si mixto sumitur amne,', en: 'before they come, if it is taken mixed with water,' },
        { la: 'aut oleo quo decoquitur si membra perungas.', en: 'or if you anoint the limbs with the oil it is boiled in.' },
        { la: 'Lumbricos ventris hanc saepe bibendo necabis.', en: 'By drinking it often you will kill the worms of the belly.' },
        { la: 'Huic panis micas et mala cidonia iungens', en: 'Joining to it crumbs of bread and quinces,' },
        { la: 'insimul amne coquas, oculorum cocta dolori', en: 'boil them together in water; the cooked mash, for pain of the eyes' },
        { la: 'apponas vel fervori, curabit utrumque.', en: 'apply, or for their inflammation: it will cure both.' },
        { la: 'Stirpes infixas et spinas abstrahet ipsum', en: 'It will draw out embedded stumps and thorns,' },
        { la: 'appositum per se vel adeps si iungitur illi.', en: 'applied by itself, or if fat is joined to it.' },
        { la: 'Haec etiam venerem pulvino subdita tantum', en: 'This too, merely laid under the pillow,' },
        { la: 'incitat, et veneri nocuis potata resistit.', en: 'rouses desire — and, drunk, withstands what harms it.' },
      ],
      note: 'Set beside Walahfrid’s southernwood (Hortulus IV) the two registers stand bare: Walahfrid gives eight lyric lines on its hair-like foliage and “as many powers as it has threads”; Macer gives a degree of heat and twenty-one lines of pharmacy — chest, loins, womb, urine, sciatica, snakebite, fever, worms, eye-pain, splinters, and a charm under the pillow. Same plant; the garden and the dispensary.',
    },

    // ── 3. Wormwood — pairs with Hortulus VII ─────────────────────────────────
    {
      seq: 3, la: 'Absinthium', en: 'Wormwood', bot: 'Artemisia absinthium', hortulus: 7,
      degrees: 'hot in the 1st degree, dry in the 2nd',
      lines: [
        { la: 'In primo calor esse gradu, vis sicca secundo', en: 'Its heat is said to be in the first degree, its dry power in the second,' },
        { la: 'dicitur absinthii; stomachum corroborat herba', en: 'this of wormwood; the herb strengthens the stomach,' },
        { la: 'illius quocunque modo quis sumpserit illam,', en: 'in whatever way one takes it,' },
        { la: 'sed melius pluviae si sit decocta liquore,', en: 'but better if it is decocted in rain-water,' },
        { la: 'et sic sub divo prius infrigidata bibatur.', en: 'and so, first cooled under the open sky, be drunk.' },
        { la: 'Sic poterit variis eius succurrere morbis,', en: 'Thus it can help in its various diseases,' },
        { la: 'hocque modo pellit lumbricos, mollit et alvum,', en: 'and in this way it drives off worms and softens the belly,' },
        { la: 'eius et immodicum sedat sic sumpta dolorem,', en: 'and so taken it eases its excessive pain,' },
        { la: 'urinam potu producit, menstrua solvit.', en: 'by drink it brings on the urine, and looses the menses.' },
        { la: 'Illi si nardum, quam profert Gallia, iungas', en: 'If you join to it the nard that Gaul produces,' },
        { la: 'et coniuncta teras et mulsa trita resolvas,', en: 'and grind them joined, and dissolve the ground mass in mead,' },
        { la: 'praecipue tali purgabis menstrua potu,', en: 'by such a drink especially you will purge the menses,' },
        { la: 'hoc quoque praestabunt cum lana subdita molli.', en: 'this too they will do, applied below on soft wool.' },
        { la: 'Si siler et nardus et acetum iungitur illi', en: 'If sermountain and nard and vinegar are joined to it,' },
        { la: 'noxia deterges potu fastidia tali.', en: 'by such a drink you will wipe away harmful queasiness.' },
        { la: 'Gramina si rutae iungas huic salque piperque', en: 'If you join blades of rue to it, with salt and pepper,' },
        { la: 'cumque mero tundens des haec decoctave potum,', en: 'and, pounding, give these in wine or decocted as a drink,' },
        { la: 'noxius et crudus stomachi purgabitur humor.', en: 'the harmful raw humour of the stomach will be purged.' },
        { la: 'Iri coniuncta pectus mire iuvat hausta.', en: 'Joined with iris and drunk, it wonderfully helps the chest.' },
        { la: 'Acri cum vino trita se quilibet ungens', en: 'Anyone anointing himself with it crushed in sharp wine' },
        { la: 'non metuat culices, ustaeque fugantur odore.', en: 'need not fear gnats; and burnt, its smell drives them off.' },
        { la: 'Ictericis crudam dabis hanc apio sociatam,', en: 'To the jaundiced you will give it raw, joined with celery;' },
        { la: 'curat hepar, sibi si iungatur gallica nardus,', en: 'it cures the liver if Gallic nard be joined to it,' },
        { la: 'splenque sibi iuncto potata iuvabit aceto.', en: 'and, drunk with vinegar joined to it, it will help the spleen.' },
        { la: 'Sic quoque fungorum depellit sumpta venenum,', en: 'So too, taken, it drives off the poison of mushrooms,' },
        { la: 'obstat letiferae cum vino sumpta cicutae,', en: 'taken with wine it withstands deadly hemlock,' },
        { la: 'sicque venenatis occurrit morsibus hausta,', en: 'and so, drunk, it meets venomous bites,' },
        { la: 'et claros oculos reddit cum melle peruncta.', en: 'and anointed with honey it makes the eyes clear.' },
        { la: 'Hocque modo sugillatis superaddita prodest,', en: 'And so applied it helps bruises,' },
        { la: 'decoctaeque vapor obstrusas liberat aures,', en: 'and the steam of it decocted frees blocked ears;' },
        { la: 'si manant sanie cum melle terens superadde.', en: 'if they run with matter, grind it with honey and apply.' },
        { la: 'Subvenit anginae melli nitroque iugata.', en: 'Joined with honey and natron it relieves quinsy.' },
        { la: 'Vulneribus prodest contrita recentibus illa,', en: 'Crushed, it helps fresh wounds,' },
        { la: 'si superaddatur capitis sic ulcera curat,', en: 'applied, it thus cures ulcers of the head,' },
        { la: 'pruritusque iuvat eius decoctio fotu.', en: 'and its decoction, as a fomentation, helps itching.' },
        { la: 'Nausea non poterit quemquam vexare marina,', en: 'Seasickness will not be able to vex anyone' },
        { la: 'antea commixtam vino qui sumpserit illam.', en: 'who has first taken it mixed with wine.' },
        { la: 'In lini panno si circumcincta geratur', en: 'If it is worn wrapped in a linen cloth,' },
        { la: 'inguinis immodicum fertur cohibere tumorem.', en: 'it is said to check excessive swelling of the groin.' },
        { la: 'Olfactu somnum capiti vel subdita praestat,', en: 'By its smell, or placed under the head, it grants sleep,' },
        { la: 'hanc sibi supponi si non praesenserit aeger.', en: 'if the sick man has not noticed it placed beneath him.' },
        { la: 'Denigrat crines cinis eius, si bene mixtus', en: 'Its ash blackens the hair, if well mixed' },
        { la: 'ceroto fuerit et eo sint saepe peruncti.', en: 'with a wax-salve and they are often anointed with it.' },
        { la: 'A tineis tutam reddit qua conditur arcam.', en: 'It keeps moth-free the chest in which it is stored.' },
        { la: 'Sub lingua factum curat cum melle tumorem,', en: 'With honey it cures a swelling formed under the tongue,' },
        { la: 'livoremque nigrum, qui circa luminis orbem', en: 'and the black bruise that around the eye’s orb' },
        { la: 'apparere solet, purgabit idem medicamen.', en: 'is wont to appear, the same medicine will clear.' },
        { la: 'Auris depellit sonitum cum felle bovino.', en: 'With ox-gall it drives off ringing of the ear.' },
        { la: 'Duritiam splenis eius cataplasma resolvit.', en: 'Its poultice dissolves hardness of the spleen.' },
        { la: 'Coniuncto sibi melle sterae si subditur herba', en: 'If the herb, with honey joined to it, is applied to the womb,',
          n: '“sterae” — the text is corrupt; sense “to the womb” (cf. the same corruption in the betony chapter). Left as transmitted.' },
        { la: 'desiccabit eam, manareque menstrua coget;', en: 'it will dry it, and force the menses to flow;' },
        { la: 'ex oleo fuerit viridis si cocta, iuvabit', en: 'if the green herb is boiled in oil, it will help' },
        { la: 'non modice stomachum, quot erit hoc unguine fotus.', en: 'the stomach not a little, for whoever is fomented with this salve.' },
        { la: 'Incaustum vino, quo sit macerata, resolve:', en: 'Dissolve ink in the wine in which it has been steeped:' },
        { la: 'si scribis chartam mus non teret amplius illam.', en: 'if you write on paper with it, a mouse will gnaw it no more.',
          n: 'A charming aside: wormwood-steeped ink makes the page mouse-proof.' },
        { la: 'Plinius attollit magnis hanc laudibus herbam,', en: 'Pliny extols this herb with great praises,' },
        { la: 'Romanosque refert sacris ex more diebus', en: 'and relates that the Romans, on sacred days by custom,' },
        { la: 'dum quadrigarum cursu certare solerent,', en: 'when they used to compete in the four-horse chariot race,' },
        { la: 'absinthii succum solitos donare bibendum', en: 'were wont to give the juice of wormwood to drink' },
        { la: 'in capitolina victori sede locato,', en: 'to the victor enthroned in the Capitoline seat,' },
        { la: 'credentes pretium prae cunctis reddere dignum', en: 'believing they gave a prize worthy above all others' },
        { la: 'illi, quo firmam posset servare salutem,', en: 'to him — one by which he could keep firm health,' },
        { la: 'quae constat mundi pretio pretiosior omni.', en: 'which is, indeed, more precious than all the world’s price.',
          n: 'Pliny’s anecdote: the Capitoline chariot-victor was given wormwood-juice as his prize — health being worth more than any other reward.' },
      ],
      note: 'Both poems make wormwood the bitterest bed and a head-treatment (Walahfrid’s decoction poured over the crown; Macer’s ulcer-cure and sleep under the pillow). But Macer’s overflows the medicine-chest into the household — a moth-keeper for the linen, a mouse-proof ink — and ends on Pliny’s splendid image of the Capitol chariot-victor crowned not with a wreath but with a draught of wormwood, because health outprices the world.',
    },
    { seq: 4,  la: 'Urtica',     en: 'Nettle',         bot: 'Urtica dioica' },
    { seq: 5,  la: 'Allium',     en: 'Garlic',         bot: 'Allium sativum' },
    { seq: 6,  la: 'Plantago',   en: 'Plantain',       bot: 'Plantago major' },
    // ── 7. Rue — pairs with Hortulus III ──────────────────────────────────────
    {
      seq: 7, la: 'Ruta', en: 'Rue', bot: 'Ruta graveolens', hortulus: 3,
      degrees: 'hot and dry, 3rd degree',
      lines: [
        { la: 'A medicis rutae vis fervida dicitur esse', en: 'Physicians say the power of rue is fiery' },
        { la: 'siccaque, fertur in his gradus illi tertius esse.', en: 'and dry, and it is said to have the third degree in these.' },
        { la: 'Utilis est valde stomacho, si saepe bibatur,', en: 'It is very useful to the stomach, if often drunk,' },
        { la: 'expellit partum potu veneremque coercet,', en: 'by drink it expels the foetus and restrains desire,' },
        { la: 'tussim si bibitur compescit, menstrua purgat.', en: 'if drunk it checks a cough, and purges the menses.' },
        { la: 'Si coquis hanc in aqua, cui vinum iunxeris acre,', en: 'If you boil it in water to which you add sharp wine,' },
        { la: 'compescit talis decoctio tormina ventris,', en: 'such a decoction checks gripes of the belly,' },
        { la: 'pulmones iuvat et pectus, morboque medetur', en: 'it helps the lungs and chest, and heals the disease' },
        { la: 'costarum, quem pleuresim vocat attica lingua,', en: 'of the ribs which the Attic tongue calls pleurisy,' },
        { la: 'arteticos sciasimque iuvat, febrique medetur', en: 'it helps the arthritic and sciatic, and heals fever,' },
        { la: 'hausta vel in oleo viridem si coxeris illam', en: 'drunk — or if you boil it green in oil' },
        { la: 'et foveas tepido patientes ante tremorem.', en: 'and foment the sufferers with it warm before the shivering.' },
        { la: 'Matrici prodest intestinique tumori', en: 'It helps the womb and a swelling of the intestine,' },
        { la: 'hoc unguen vel clysterio si funditur intus,', en: 'this salve, if poured within by a clyster,' },
        { la: 'haustaque cum vino prodesse valebit utrique,', en: 'and drunk with wine it will help both;' },
        { la: 'lumbricos oleo decocta et pota repellit.', en: 'decocted in oil and drunk it drives off worms.' },
        { la: 'Cum caricis decocta diu vinique liquore', en: 'Long decocted with figs and with wine,' },
        { la: 'proderit hydropicis, si sint superaddita nocte.', en: 'it will help the dropsical, if applied at night.' },
        { la: 'Cruda comesta recens oculos caligine curat,', en: 'Eaten raw and fresh it clears the eyes of film,' },
        { la: 'et melius marathri cum succo felleque galli', en: 'and better with fennel-juice and the gall of a cock' },
        { la: 'melleque si succus ex aequo iungitur eius,', en: 'and honey, if its juice is joined in equal measure,' },
        { la: 'indeque sint oculi patientis saepe peruncti.', en: 'and the patient’s eyes are often anointed with it.' },
        { la: 'Cum roseo miscens oleo nec non et aceto', en: 'Mixing its juice with rose-oil and with vinegar,' },
        { la: 'illius succum, capitis curare dolorem', en: 'you will be able to cure any excessive pain' },
        { la: 'quemvis immodicum poteris, hoc saepe perungens.', en: 'of the head, anointing often with this.' },
        { la: 'Naribus expressus si succus funditur eius', en: 'If its pressed juice is poured into the nostrils,' },
        { la: 'sistit manantem bene desiccando cruorem.', en: 'it stops a running nosebleed, drying it well.' },
        { la: 'In corio mali granati si tepefactum', en: 'If, warmed in a pomegranate rind,' },
        { la: 'auribus infundas, depelles inde dolorem,', en: 'you pour it into the ears, you will drive off the pain;' },
        { la: 'cerussae roseoque oleo miscens et aceto', en: 'mixing it with white-lead, rose-oil, and vinegar,' },
        { la: 'illius succum mirandum conficis unguen', en: 'you make from its juice a wondrous salve' },
        { la: 'ad depellendum sacrum quem dicimus ignem,', en: 'to drive off what we call the holy fire (erysipelas),' },
        { la: 'et scabiem derte, quae dicitur herpeta graece,', en: 'and the scab of the skin, called herpes in Greek,',
          n: '“derte” — corrupt in the text; the sense is the scab/scurf of the skin. Left as transmitted.' },
        { la: 'et graece dictas achoras hoc unguine purgas:', en: 'and what are called in Greek “achores” you cleanse with this salve:' },
        { la: 'ulcera sunt capitis humore fluentia pingui.', en: 'these are ulcers of the head that run with greasy matter.' },
        { la: 'Curat et hoc ozinas immissum naribus, haec sunt', en: 'Put in the nostrils it also cures “ozaenae” — these are' },
        { la: 'quae graviter foetent in naribus ulcera nata.', en: 'ulcers grown in the nostrils that stink grievously.' },
        { la: 'obstat pota mero vel cruda comesta venenis', en: 'drunk in wine or eaten raw it withstands poisons —',
          n: 'Rue as the great antidote: the very virtue Walahfrid gives it (Hortulus III, “before all it stands against hidden poisons”).' },
        { la: 'hoc Metridates rex Ponti saepe probavit,', en: 'this Mithridates, king of Pontus, often proved,' },
        { la: 'qui Rutae foliis viginti cum sale pauco', en: 'who, with twenty leaves of rue, a little salt,' },
        { la: 'et magnis nucibus binis caricisque duabus', en: 'two large nuts, and two dried figs,' },
        { la: 'ieiunus vesci consurgens mane solebat,', en: 'was wont to eat, fasting, on rising in the morning,' },
        { la: 'armatusque cibo tali, quascunque veneno', en: 'and armed with such food, whatever poisoned snares' },
        { la: 'quilibet insidias sibi tenderet, haud metuebat.', en: 'anyone might lay for him, he did not fear.',
          n: 'The famous Mithridatic antidote, in which rue is the chief herb — the king who made himself poison-proof.' },
        { la: 'Mustelaeque docent obsistere posse venenis', en: 'And the weasels teach that rue can withstand poisons' },
        { la: 'mirifice rutam, comedunt quae primitus illam,', en: 'wondrously — they eat it first' },
        { la: 'cum pugnaturae sunt cum serpentibus atris.', en: 'when they are about to fight with black serpents.' },
        { la: 'Cum butyro modicoque oleo decocta tumorem', en: 'Decocted with butter and a little oil,' },
        { la: 'matricis subiecta tepens fugat illa colique', en: 'applied warm it routs swelling of the womb and the colon,' },
        { la: 'et cunctis intus morbis sic subdita prodest.', en: 'and so applied it helps all the inner diseases.' },
        { la: 'Hac etiam testes poteris curare tumentes,', en: 'With it too you can cure swollen testicles,' },
        { la: 'cum foliis lauri bene tritam si superaddes.', en: 'if you apply it well crushed with bay-leaves.' },
        { la: 'Ex hac antidotum non paucis utile causis', en: 'From it an antidote useful for not a few cases' },
        { la: 'conficitur, medici dicunt diapiganon illud,', en: 'is made, which physicians call “diapiganon”,' },
        { la: 'piganon in graeca lingua quia ruta vocatur;', en: 'because rue is called “piganon” in the Greek tongue;' },
        { la: 'illius antidoti confectio talis habetur:', en: 'the making of that antidote is held to be thus:' },
        { la: 'pondere iunge pari nitrum, piper atque cyminum,', en: 'join in equal weight natron, pepper, and cumin;' },
        { la: 'de tribus his, quantum de ruta, ponito tantum,', en: 'of these three put as much as of rue,' },
        { la: 'sed prius ex acri vino macerare cyminum', en: 'but first it is fitting to steep the cumin in sharp wine,' },
        { la: 'convenit, in ferro post assari calefacto,', en: 'then to roast it on heated iron,' },
        { la: 'omnia deinde simul bene trita ex melle iugabis,', en: 'then bind all, well ground together, with honey;' },
        { la: 'pectoris et lateris, iecoris, renumque dolores', en: 'pains of chest and side, of liver and kidneys,' },
        { la: 'hoc ex antidoto curantur saepe comesto,', en: 'are often cured by eating this antidote;' },
        { la: 'extenuat bilem, mollit sine tormine ventrem,', en: 'it thins the bile, softens the belly without gripe,' },
        { la: 'confortat stomachum, facit ut bene digerat escam.', en: 'strengthens the stomach, and makes it digest food well.' },
      ],
      note: 'Walahfrid drew rue first as a thing of beauty — a light-filled little thicket — and only then as the antidote “before all against hidden poisons” (Hortulus III). Macer skips the beauty and gives the antidote its full legend: the Mithridatic recipe of the poison-proof king, the weasels that eat rue before fighting serpents, and the physicians’ compound diapiganon, named from the Greek for rue.',
    },
    // ── 8. Celery — pairs with Hortulus XVIII ─────────────────────────────────
    {
      seq: 8, la: 'Apium', en: 'Celery', bot: 'Apium graveolens', hortulus: 18,
      degrees: 'hot and dry, 3rd degree',
      lines: [
        { la: 'Est apium dictum, quod apex hanc ferre solebat', en: 'It is called apium because the victor’s crown (apex) used to bear it,' },
        { la: 'victoris, veterum fieret dum more triumphus.', en: 'when a triumph was held in the manner of the ancients.' },
        { la: 'Ipse sibi talem prior imposuisse coronam', en: 'Alcides is said to have been the first to set such a crown' },
        { la: 'dicitur Alcides, morem tenuere sequentes.', en: 'upon himself; those who came after kept the custom.',
          n: 'Alcides = Hercules. Macer offers two etymologies for apium — from apex, the triumphal crown, and (next) from apes, the bees.' },
        { la: 'Ast alii dictum credunt, quod apes vehementer', en: 'But others believe it so called because bees, eagerly' },
        { la: 'illius soleant avide decerpere flores.', en: 'and greedily, are wont to strip its flowers.' },
        { la: 'Hanc herbam selinon solet attica dicere lingua,', en: 'The Attic tongue is wont to call this herb selinon;' },
        { la: 'virtutis calidae siccae quoque dicitur esse,', en: 'it is said to be of hot and dry power,' },
        { la: 'tertius a medicis datus est gradus huic in utroque.', en: 'and physicians give it the third degree in both.' },
        { la: 'Illius succo si candida mica terendo', en: 'If with its juice a white crumb of bread' },
        { la: 'panis iungatur, oculi sedare tumorem', en: 'be ground and joined, it is said to ease swelling of the eye,' },
        { la: 'dicitur emplastri noctu superaddita more,', en: 'applied at night in the manner of a plaster,' },
        { la: 'sicque ferunt mammis prodesse tumentibus illam.', en: 'and so they say it helps swollen breasts.' },
        { la: 'Sedat fervorem stomachi, pellitque tumorem,', en: 'It calms the heat of the stomach and drives off swelling,' },
        { la: 'et quicquid venti creat includitve nocivi', en: 'and whatever harmful wind it breeds or shuts in,' },
        { la: 'desiccans poris assumpta repellit apertis.', en: 'taken, it dries up and drives off through the opened pores.' },
        { la: 'Provocat urinas haec cruda comesta vel hausta,', en: 'Eaten raw or drunk, it provokes the urine,',
          n: 'The virtue Walahfrid also gives celery (Hortulus XVIII): the seed against stopped urine.' },
        { la: 'sed mage radicum facit hoc decoctio sumpta,', en: 'but the decoction of the roots does this more,' },
        { la: 'hoc itidem semen operatur fortius haustum.', en: 'and likewise the seed, drunk, works more strongly.' },
        { la: 'tota venenatis occurrit morsibus herba,', en: 'the whole herb meets venomous bites,' },
        { la: 'sed semen potius vel apozima proderit eius', en: 'but rather the seed, or its decoction, will help' },
        { la: 'si bibitur, tussimque modo sedabit eodem.', en: 'if drunk, and in the same way will calm a cough.' },
        { la: 'Ventrem constringit, vomitum potata coercet,', en: 'It binds the belly, and drunk it checks vomiting,' },
        { la: 'lymphae commixtum sibi si iungatur acetum;', en: 'if vinegar mixed with water be joined to it;' },
        { la: 'aegris amissum fertur reparare colorem,', en: 'it is said to restore lost colour to the sick,' },
        { la: 'cruda a ieiunis fuerit si saepe comesta.', en: 'if eaten raw, and often, on an empty stomach.' },
        { la: 'Unaquaque die vexantem corpora febrem', en: 'The fever that vexes the body day by day,' },
        { la: 'cum lympha potata iuvat febris ante tremorem.', en: 'drunk with water, it relieves — before the fever’s shivering.' },
        { la: 'Hydropicos et splen tumidum iuvat illa, iecurque', en: 'It helps the dropsical, the swollen spleen, and the liver,' },
        { la: 'si cum feniculi succo contrita bibatur.', en: 'if drunk crushed with fennel-juice.' },
        { la: 'Hacque superposita turpis lentigo fugatur.', en: 'And applied, it puts ugly freckles to flight.' },
        { la: 'Illius succus farris cum polline mixtus', en: 'Its juice, mixed with the flour of spelt' },
        { la: 'atque ovi lacrimo vulnus bene purgat et ulcus,', en: 'and with the white of an egg, well cleanses a wound and an ulcer,' },
        { la: 'si superaddatur emplastri more frequenter.', en: 'if applied often in the manner of a plaster.' },
      ],
      note: 'Where Walahfrid (Hortulus XVIII) crowned celery “the king of the body” (the stomach), Macer opens with the literal crown — the triumphal wreath of Hercules, or the bees that strip its flowers — then the shared virtue: celery provokes the urine.',
    },
    { seq: 9,  la: 'Althaea',    en: 'Marshmallow',    bot: 'Althaea officinalis' },
    { seq: 10, la: 'Anethum',    en: 'Dill',           bot: 'Anethum graveolens' },
    // ── 11. Betony — pairs with Hortulus XIX (both poems' most-praised herb) ───
    {
      seq: 11, la: 'Betonica', en: 'Betony', bot: 'Betonica officinalis', hortulus: 19,
      lines: [
        { la: 'Betonicam soliti sunt cestron dicere Graeci.', en: 'The Greeks were wont to call betony cestron.' },
        { la: 'Urinas potata ciet, lapidesque repellit,', en: 'Drunk, it provokes urine and drives out the stone,' },
        { la: 'fert haemoptoicis cum pusca sumpta iuvamen,', en: 'taken with posca it brings aid to those who spit blood,' },
        { la: 'hydropicos siccat cum vino melleque sumpta.', en: 'with wine and honey it dries up the dropsical.' },
        { la: 'De foliis eius tritis factum cataplasma', en: 'A poultice made of its crushed leaves' },
        { la: 'non modicum prodest oculis, quos laeserit ictus.', en: 'much helps eyes that a blow has injured.' },
        { la: 'Illius succus roseo commixtus olivo', en: 'Its juice, mixed with rose-oil' },
        { la: 'auribus infusus varios fugat inde dolores.', en: 'and poured in the ears, drives off various pains.' },
        { la: 'Betonicae pulvis cocto cum melle iugatus', en: 'Betony powder joined with cooked honey' },
        { la: 'empicos, tussimque iuvat, suspiria sedat,', en: 'helps the empyemic and the cough, and calms shortness of breath,' },
        { la: 'et stomachi varios sumptus iuvat ille dolores,', en: 'and, taken, it helps various stomach pains —' },
        { la: 'si febrit ex calida, cum vino si febris absit.', en: 'with hot water if there is fever, with wine if fever is absent.' },
        { la: 'Cum mulsa bibitus idem pulvis movet alvum.', en: 'The same powder, drunk with mead, moves the bowel.' },
        { la: 'Cum sale contritis foliis cataplasmate facto', en: 'With a poultice made of leaves crushed with salt' },
        { la: 'vulnera curabis, fuerint quae facta recenter,', en: 'you will cure wounds freshly made,' },
        { la: 'tritaque fracturae capitis haec sola medetur.', en: 'and crushed, it alone heals a fracture of the head.',
          n: 'The same use Walahfrid gives betony (Hortulus XIX): the dressing laid on a broken, festering head until the scar knits sound.' },
        { la: 'De foliis eius elixis fit cataplasma', en: 'From its boiled leaves a poultice is made,' },
        { la: 'utile non modicum variis vitiis oculorum;', en: 'very useful for various ailments of the eyes;' },
        { la: 'restringit lacrimas oculorum mansa vel hausta,', en: 'chewed or drunk, it checks the watering of the eyes,' },
        { la: 'hac etiam caligo solet metuenda repelli,', en: 'by it too the dreaded film is wont to be driven off,' },
        { la: 'aequo cum ruta fuerit si pondere iuncta', en: 'if it be joined with rue in equal weight' },
        { la: 'et sic cum lympha sumatur trita tepenti,', en: 'and so, crushed, be taken with warm water:' },
        { la: 'sic oculis nocuus sanguis per subtiliora', en: 'thus the blood harmful to the eyes, through the finer passages,' },
        { la: 'dicitur expelli, sic lumina libera reddi.', en: 'is said to be expelled, and the eyes set free.' },
        { la: 'Sumpta hac cum tepida purgatur vomica dira,', en: 'Taken with warm water it purges a dire abscess,' },
        { la: 'pectoris et morbi potu curantur eodem,', en: 'and diseases of the chest are cured by the same draught;' },
        { la: 'splen iuvat illius decoctio sumpta iecurque.', en: 'its decoction, taken, helps the spleen and the liver.' },
        { la: 'Uncia betonicae socianda quaterna vetusti', en: 'Four ounces of betony are to be joined' },
        { la: 'cum vini cyathis tribus, his sint addita grana', en: 'with three cyathi of old wine; to these add' },
        { la: 'viginti septem piperis, simul haec bene trita', en: 'twenty-seven grains of pepper; these, well ground together' },
        { la: 'haustaque purgabunt renes, pellentque dolores.', en: 'and drunk, will purge the kidneys and drive off pains.' },
        { la: 'Uncia cum cyathis calidae potata duobus', en: 'An ounce drunk with two cyathi of hot water' },
        { la: 'dicitur immodicum ventris sedare dolorem.', en: 'is said to ease excessive pain of the belly.' },
        { la: 'Haec tussim cum melle fugat, ventrem quoque mollit,', en: 'With honey it routs a cough, and softens the belly too;' },
        { la: 'unaquaque die febre si vexabitur aeger', en: 'if a sick man is vexed each day by fever,' },
        { la: 'uncia iungatur plantaginis una duabus', en: 'let one ounce of plantain be joined to two' },
        { la: 'betonicae, sic cum tepida contrita bibantur,', en: 'of betony, and so, crushed, be drunk with warm water,' },
        { la: 'antea quam febris praenuncia frigora fiant.', en: 'before the chills that herald the fever come on.' },
        { la: 'Uncia betonicae calidae cyatho resoluta', en: 'An ounce of betony dissolved in a cyathus of hot water' },
        { la: 'prodest hydropicis, si sit potata frequenter.', en: 'helps the dropsical, if it be drunk often.' },
        { la: 'Radicum pulvis cum mulsa tritus et haustus', en: 'The powder of the roots, ground with mead and drunk,' },
        { la: 'humores (velut elleborum) vomitu cito purgat,', en: 'purges the humours quickly by vomit, like hellebore;' },
        { la: 'bis binas dragmas praecepit Plinius harum', en: 'Pliny prescribed twice two drachms of these' },
        { la: 'radicum dare cum passo mulsove bibendas,', en: 'roots to be given, to be drunk with raisin-wine or mead;' },
        { la: 'praecipue phlegma vomitu purgabitur isto.', en: 'phlegm especially will be purged by that vomit.' },
        { la: 'Cum mulsa bibitus prodest pulvis foliorum', en: 'The powder of the leaves, drunk with mead, helps' },
        { la: 'ruptis atque steras potus levat iste cadentes.', en: 'the ruptured, and this drink relieves the falling [parts].',
          n: '“steras … cadentes” — the text is corrupt here; the sense is relief for ruptures and prolapse. Left as transmitted, to be settled against the critical edition.' },
        { la: 'Cum vino sumptis obstat potata venenis,', en: 'Drunk, it withstands poisons taken in wine,' },
        { la: 'praecipue semen, quod si desit datur herba.', en: 'the seed especially; and if that is lacking, the herb is given.' },
        { la: 'Uncia betonicae cum vino sumpta tepenti', en: 'An ounce of betony taken with warm wine' },
        { la: 'ictericos curat; cum mulsa menstrua solvit;', en: 'cures the jaundiced; with mead it looses the menses;' },
        { la: 'pondere vero fabae pulvis cum melle voratus', en: 'and the powder, to the weight of a bean, swallowed with honey' },
        { la: 'post coenam stomachum iuvat, ut bene digerat escam.', en: 'after dinner helps the stomach to digest the food well.' },
        { la: 'Si de betonica viridi sit facta corona', en: 'If a crown be made of green betony' },
        { la: 'circa serpentes, ut Plinius asserit auctor,', en: 'around serpents, as Pliny the author asserts,' },
        { la: 'audebunt nunquam positam transire coronam,', en: 'they will never dare to cross the encircling crown,' },
        { la: 'sed morsu proprio pereunt et verbere caudae.', en: 'but perish by their own bite and the lashing of their tail.',
          n: 'The Pliny legend: betony so loathed by serpents that, ringed in it, they kill themselves rather than cross.' },
        { la: 'Omnibus antidotis Menemachus eam sociari', en: 'Menemachus bids it be joined to all antidotes,' },
        { la: 'praecipit, ut stomacho magis herbis omnibus aptam.', en: 'as fitter for the stomach than all other herbs.' },
        { la: 'Plinius hanc, inquit, qui secum gesserit herbam,', en: 'Pliny says: whoever carries this herb about him' },
        { la: 'a nullo poterit nocuo medicamine laedi,', en: 'can be harmed by no hurtful drug;' },
        { la: 'et dicunt, quod ea cum vino saepius hausta', en: 'and they say that, drunk often with wine,' },
        { la: 'plumbeus abscedat color et melior revocetur.', en: 'the leaden colour [of the face] departs, and a better is restored.' },
      ],
      note: 'Both poems crown betony. Walahfrid (XIX) said the Muse herself fell short of its praise; Macer gives it the full Pliny legend — the same head-wound healer, an antidote one need only carry to be proof against poison, and a ring of it that makes any serpent destroy itself. The two exaltations meet head-on, lyric beside pharmacopoeia.',
    },
    { seq: 12, la: 'Sabina',     en: 'Savin',          bot: 'Juniperus sabina' },
    { seq: 13, la: 'Porrum',     en: 'Leek',           bot: 'Allium porrum' },
    { seq: 14, la: 'Chamomilla', en: 'Chamomile',      bot: 'Matricaria chamomilla' },
    // ── 15. Catmint — pairs with Hortulus XXII ────────────────────────────────
    {
      seq: 15, la: 'Nepeta', en: 'Catmint', bot: 'Nepeta cataria', hortulus: 22,
      degrees: 'hot and dry, 3rd degree',
      lines: [
        { la: 'Herbam, quam nepetam vulgari more vocamus,', en: 'The herb we commonly call nepeta (catmint),' },
        { la: 'hanc medici graeco calamenti nomine dicunt,', en: 'physicians name by the Greek word calamentum;' },
        { la: 'sicca calensque sibi vis est et tertius illi', en: 'its power is dry and hot, and it has the third' },
        { la: 'est in utroque gradus. Cum mulsa sicca tepenti', en: 'degree in both. Dried and taken with warm mead,' },
        { la: 'sumpta solet totum sudore resolvere corpus;', en: 'it is wont to dissolve the whole body in sweat;' },
        { la: 'ex oleo, quo sit decocta, perunge fricando', en: 'with the oil it is boiled in, anoint by rubbing' },
        { la: 'illum, venturae metuit qui frigora febris,', en: 'the man who fears the chills of a coming fever:' },
        { la: 'non frigus tantum sed febrem saepe repellit;', en: 'it often drives off not the chill only but the fever;' },
        { la: 'illi, qui sciasim patitur, coxae superadde', en: 'for him who suffers sciatica, lay on the hip' },
        { la: 'contritam viridem, fertur comburere pellem', en: 'the green herb crushed: it is said to burn the skin' },
        { la: 'et sic humores siccando fugare dolores;', en: 'and so, by drying the humours, to put the pains to flight;' },
        { la: 'appositu potuque suo cito menstrua purgat.', en: 'by application and by drink it quickly brings on the menses.' },
        { la: 'Est leprae species elephantiasisque vocatur,', en: 'There is a kind of leprosy called elephantiasis,' },
        { la: 'quae cunctis morbis maior sic esse videtur,', en: 'which seems so much the greatest of all diseases' },
        { la: 'ut maior cunctis elephas animalibus extat,', en: 'as the elephant stands greatest of all animals;' },
        { la: 'hunc in principio morbum potus calamenti', en: 'this disease, at its onset, a drink of catmint' },
        { la: 'cum vino curat humores extenuando;', en: 'with wine cures, by thinning the humours;' },
        { la: 'serpentum morsus superaddita trita nocere', en: 'applied crushed, it lets the bites of serpents' },
        { la: 'non sinit, et pellit cum vino sumpta venena.', en: 'do no harm, and drunk with wine it drives off venom.' },
        { la: 'Potus et iniectus lumbricos enecat eius', en: 'Its juice, drunk and injected, kills the round-worms,' },
        { la: 'succus et in membris vermes necat omnibus ipse,', en: 'and itself kills worms in every limb,' },
        { la: 'si mel iungatur huic cum sale plus operatur.', en: 'and works the more if honey with salt be joined to it.' },
        { la: 'Si bibit hanc praegnans aut tritam subdit, abortit.', en: 'If a pregnant woman drinks it, or applies it crushed, she miscarries.' },
        { la: 'Purgat et ictericos, cum vino curat anhelos,', en: 'It purges the jaundiced; with wine it cures the breathless,' },
        { la: 'asthmaticos medici quos graeco nomine dicunt,', en: 'whom physicians call by the Greek name asthmatic,' },
        { la: 'et iecoris morbos cum vino mitigat hausta,', en: 'and drunk with wine it soothes diseases of the liver,' },
        { la: 'hocque modo veterem lateris iuvat illa dolorem,', en: 'and in this way it relieves an old pain in the side,' },
        { la: 'atque cicatrices nigras superaddita trita', en: 'and, laid on crushed, black scars' },
        { la: 'haec naturali reddit purgando colori;', en: 'it restores, by cleansing, to their natural colour;',
          n: 'The very virtue Walahfrid gives catmint (Hortulus XXII): its rose-oil salve that smooths new scars back to clear skin.' },
        { la: 'vino decoctae facit hoc melius cataplasma.', en: 'a poultice of it boiled in wine does this better.' },
        { la: 'Compescit stomachi cum vino sumpta dolorem.', en: 'Taken with wine, it checks pain of the stomach.' },
        { la: 'Fumus de domibus serpentes effugat eius,', en: 'Its smoke drives serpents from the house,' },
        { la: 'tollere singultum cum vino dicitur hausta', en: 'drunk with wine it is said to take away hiccups,' },
        { la: 'hocque modo venerem prohibet potata frequenter.', en: 'and so, drunk often, it restrains desire.' },
      ],
      note: 'Macer’s catmint shares Walahfrid’s scar-virtue exactly — both turn fresh black scars back to natural colour — but around it Macer wraps a full litany: a sweat-cure, a fever-rub, the early treatment of elephantiasis, worms, and (against type) a check on desire.',
    },
    // ── 16. Pennyroyal — pairs with Hortulus XVII ─────────────────────────────
    {
      seq: 16, la: 'Pulegium', en: 'Pennyroyal', bot: 'Mentha pulegium', hortulus: 17,
      degrees: 'hot and dry, 3rd degree',
      lines: [
        { la: 'Fervida pulegii vis siccaque dicitur esse.', en: 'The power of pennyroyal is said to be fiery and dry.' },
        { la: 'Tertius a medicis datus est gradus huic in utroque.', en: 'Physicians give it the third degree in both.' },
        { la: 'Saepius hanc herbam si praegnans sumit, abortit;', en: 'If a pregnant woman takes this herb too often, she miscarries;' },
        { la: 'menstrua deducit cum vino sumpta tepenti,', en: 'taken with warm wine it brings down the menses,' },
        { la: 'hocque modo tardas haec extrahit herba secundas.', en: 'and in this way it draws out the delayed afterbirth.' },
        { la: '(Hoc nomen, quod non notum reor esse quibusdam,', en: '(This word, which I think is not known to some,' },
        { la: 'exponam tali quid nomine significetur:', en: 'I will explain — what is meant by such a name:' },
        { la: 'ut nondum natus testa circumdatur ovi', en: 'as the not-yet-hatched chick is wrapped in the egg’s shell,' },
        { la: 'pullus, sic infans matris vestitur in alvo', en: 'so the infant is clothed, in the mother’s womb,' },
        { la: 'quadam pellicula matris de semine facta,', en: 'in a certain membrane made from the mother’s seed,' },
        { la: 'quam nascens rumpit, quasi testam pullulus ovi,', en: 'which, being born, it breaks, as the chick the egg-shell —' },
        { la: 'istas pelliculas medici dixiere secundas,', en: 'these membranes the physicians have called the “secundae” (afterbirth),' },
        { la: 'quod mox expositos naturae iure sequantur;', en: 'because they soon follow the newborn by nature’s law;' },
        { la: 'hae si plus iusto vitio cogente morantur', en: 'if these, some fault compelling, delay longer than is right,' },
        { la: 'aut mors subsequitur, dolor aut qui vix toleratur;', en: 'either death follows, or a pain scarcely to be borne;' },
        { la: 'istas pulegium praedicto more repellit.)', en: 'these pennyroyal expels, in the way said above.)',
          n: 'Where Walahfrid’s pennyroyal bed (Hortulus XVII) digresses outward into the cosmic economy of trade, Macer’s digresses inward — a clinical aside, with an egg-shell simile, simply explaining what the afterbirth is.' },
        { la: 'Cum sale contritam melli si iunxeris illam', en: 'If you join it, crushed with salt, to honey,' },
        { la: 'unguine contractis potes hoc succurrere membris.', en: 'with this ointment you can relieve cramped limbs.' },
        { la: 'Illius pulvis sumptus cum melle vel haustus', en: 'Its powder, taken with honey or drunk,' },
        { la: 'pectoris humores viscosos extenuare', en: 'can thin the viscous humours of the chest,' },
        { la: 'et per sputa potest illos educere mire.', en: 'and draw them out wondrously by spitting.' },
        { la: 'Nausea vel morsus stomachi curabitur illa', en: 'Nausea, or gnawing of the stomach, will be cured by it,' },
        { la: 'cum pusca sumpta vel aceto quod sit aquosum;', en: 'taken with posca, or with watery vinegar;' },
        { la: 'cum vino nigram choleram potata repellit,', en: 'drunk with wine it drives off black bile,' },
        { la: 'sicque venenatis serpentum morsibus obstat.', en: 'and so withstands the venomous bites of serpents.' },
        { la: 'Si per vim febris nimiove fluore cruoris', en: 'If by force of fever, or too great a flow of blood,' },
        { la: 'aut aliquo casu subito defecerit aeger,', en: 'or by some mischance, the sick man suddenly faints —' },
        { la: 'quod solet a doctis medicis malefactio dici,', en: 'what learned physicians are wont to call a “malefactio” —' },
        { la: 'pulegium valido tritum iungatur aceto,', en: 'let pennyroyal, crushed, be joined to strong vinegar,' },
        { la: 'naribus aegroti sic apponatur, odore', en: 'and so be held to the sick man’s nostrils: by the smell' },
        { la: 'solo confestim dicunt relevare iacentem.', en: 'alone, they say, it at once revives the collapsed.',
          n: 'The transmitted text reads “incentem”; read “iacentem” (the one lying in a faint) — a smelling-salt.' },
        { la: 'Gingivas sicci pulvis confirmat et usti.', en: 'Its powder, dried and burnt, strengthens the gums.' },
        { la: 'Appositam viridem dicunt sedare podagram,', en: 'Laid on green, they say it eases gout,' },
        { la: 'et quosvis alios solet emendare tumores,', en: 'and it is wont to mend any other swellings,' },
        { la: 'si superaddatur tepidae permixta polentae;', en: 'if it be added mixed with warm barley-meal;' },
        { la: 'addita cerotis papulas de corpore tollit.', en: 'added to wax-salves, it takes pimples from the body.' },
        { la: 'Spleneticis multum superaddita cum sale prodest;', en: 'Applied with salt, it much helps the splenetic;' },
        { la: 'elixatura si quisquam saepe tepenti', en: 'if anyone often washes himself with its warm' },
        { la: 'illius abluitur, pruritus non patietur,', en: 'decoction, he will suffer no itching,' },
        { la: 'et sic matricis poteris curare tumorem;', en: 'and so you can cure a swelling of the womb;' },
        { la: 'tussim compescit cum vino sumpta tepenti,', en: 'taken with warm wine it checks a cough,' },
        { la: 'et sic urinam compellit reddere largam,', en: 'and so compels [the body] to pass copious urine,' },
        { la: 'et magis ex vino si sit decoctio facta', en: 'and the more if the decoction be made from wine,' },
        { la: 'aut oleo mixto contritam si superaddas.', en: 'or if you apply it crushed and mixed with oil.' },
        { la: 'Si radix acri contrita iugatur aceto,', en: 'If the root, crushed, be joined to sharp vinegar,' },
        { la: 'sedabit quosvis superaddita saepe tumores;', en: 'applied often it will calm any swellings;' },
        { la: 'obstat serpentum cum vino sumpta venenis', en: 'drunk with wine it withstands serpents’ venom,' },
        { la: 'et sic assumptam venerem stimulare fatentur.', en: 'and so taken, they grant, it stirs desire.' },
        { la: 'Sic quoque pulmonis prodest iecorisque querelis', en: 'Thus too it helps complaints of lung and liver,' },
        { la: 'et sic nutrici sumptum lac praebet abundans.', en: 'and so, taken by a nurse, it yields abundant milk.' },
        { la: 'Herba viridis curat morsus cum melle caninos,', en: 'The green herb, with honey, cures dog-bites,' },
        { la: 'si superaddatur et vino mixta bibatur.', en: 'if it be applied, and also drunk mixed with wine.' },
      ],
      note: 'Walahfrid and Macer both pause longest over pennyroyal. Walahfrid (XVII) turns it into the providence of trade; Macer makes it, above all, a childbirth herb — and stops to define the “afterbirth” with an egg-shell simile — then a reviving smelling-salt for the collapsed, and the usual long train of cures.',
    },
    // ── 17. Fennel — pairs with Hortulus IX ───────────────────────────────────
    {
      seq: 17, la: 'Feniculum', en: 'Fennel', bot: 'Foeniculum vulgare', hortulus: 9,
      degrees: 'hot and dry, 2nd degree',
      lines: [
        { la: 'Feniculum medici calidum siccumque secundo', en: 'Physicians say fennel is hot and dry in the second' },
        { la: 'dicunt esse gradu, marathrum Graecus vocat illud.', en: 'degree; the Greek calls it marathrum.' },
        { la: 'Cum vino cunctis obstat haec herba venenis,', en: 'With wine this herb withstands every poison;' },
        { la: 'hac mansa serpens oculos caligine purgat,', en: 'chewing it, the serpent clears its eyes of film,' },
        { la: 'indeque compertum est humanis posse mederi', en: 'and thence it was learned that it can heal human' },
        { la: 'illam luminibus, atque experiendo probatum;', en: 'eyes — and proven by trial;',
          n: 'The serpent that chews fennel to brighten its sight: the ancient ground of fennel’s eye-virtue — the same Walahfrid names (Hortulus IX, “it helps the eyes that shadow weighs upon”).' },
        { la: 'radicum succus oculis cum melle perunctis', en: 'the juice of the roots — the eyes anointed with honey —' },
        { la: 'pulsa reddit eos omni caligine claros;', en: 'renders them clear, all film driven off;' },
        { la: 'expressus marathri viridi de semine succus', en: 'the juice pressed from fennel’s green seed,' },
        { la: 'soleque siccatus magnum medicamen habetur', en: 'dried in the sun, is held a great medicine' },
        { la: 'ad quoscunque voles oculorum pellere morbos.', en: 'to drive off whatever diseases of the eyes you wish.' },
        { la: 'Auribus infusus vermes succus necat eius,', en: 'Poured into the ears, its juice kills worms;' },
        { la: 'renibus in ptisana radix decocta medetur,', en: 'the root, decocted in barley-water, heals the kidneys;' },
        { la: 'cum vino fugat hydropicos potata tumores,', en: 'drunk with wine it routs dropsical swellings,' },
        { la: 'sicque venenatis obstabit morsibus illa,', en: 'and so it will withstand venomous bites,' },
        { la: 'sic quoque pulmonis obstat iecorisque querelis,', en: 'thus too it counters complaints of lung and liver,' },
        { la: 'et sic nutrici sumpta fit copia lactis.', en: 'and so, taken by a nurse, plenty of milk comes.' },
        { la: 'Cum vino vel aqua radicum coctio sumpta', en: 'The decoction of the roots, taken with wine or water,' },
        { la: 'nefreticis et vesicae morbis medicatur,', en: 'heals the nephritic and the bladder’s diseases,' },
        { la: 'urinas purgat et menstrua sumpta resolvit,', en: 'purges the urine and, taken, looses the menses,' },
        { la: 'vel si trita super pecten haec herba ligetur;', en: 'or if this herb, crushed, be bound over the pubis;' },
        { la: 'nausea cum vino sumpta sedabitur illa,', en: 'nausea will be calmed by it taken with wine,' },
        { la: 'fervorem stomachi cum lympha mitigat hausta.', en: 'and drunk with water it soothes the heat of the stomach.' },
        { la: 'Radix illius vino decocta dolores', en: 'Its root, decocted in wine, by fomentation' },
        { la: 'fomento curat, patitur quos virga virilis,', en: 'cures the pains the male member suffers —' },
        { la: 'hoc quoque, si iungas oleum, facit, hocque perungas.', en: 'this too it does if you add oil, and anoint with it.' },
        { la: 'Ictu vel factos subito quoscunque tumores', en: 'Whatever swellings are made suddenly by a blow,' },
        { la: 'appositum tantum iuncto sedabit aceto.', en: 'it will calm, merely applied with vinegar added.' },
        { la: 'Semen cum vino bibitum veneris movet actus,', en: 'The seed drunk with wine stirs the acts of love,' },
        { la: 'hocque modo lateris diros sedare dolores', en: 'and in this way, they say, it eases the dire pains' },
        { la: 'dicunt aut herbae si sit decoctio sumpta.', en: 'of the side — or if a decoction of the herb be taken.' },
        { la: 'Tradunt auctores eius iuvenescere gustu', en: 'Authors relate that by its taste serpents grow young,' },
        { la: 'serpentes et ob hoc senibus prodesse putatur.', en: 'and for this reason it is thought good for the old.' },
      ],
      note: 'Walahfrid (Hortulus IX) gives fennel three uses in nine lyric lines; Macer gives thirty-three of pharmacy — yet both rest on the same belief that fennel clears the sight, which Macer traces to the serpent that chews it to brighten its eyes and is thereby thought to renew its youth.',
    },
    { seq: 18, la: 'Acidula',    en: 'Sorrel',         bot: 'Rumex acetosa' },
    { seq: 19, la: 'Portulaca',  en: 'Purslane',       bot: 'Portulaca oleracea' },
    { seq: 20, la: 'Lactuca',    en: 'Lettuce',        bot: 'Lactuca sativa' },
    // ── 21. Rose — pairs with Hortulus XXIV (both call it "the flower of flowers") ─
    {
      seq: 21, la: 'Rosa', en: 'Rose', bot: 'Rosa', hortulus: 24,
      degrees: 'cold and dry, 1st degree',
      lines: [
        { la: 'Dici flos florum nobis rosa iure videtur,', en: 'The rose, it seems to us, is rightly called the flower of flowers,',
          n: 'The very title Walahfrid gives it (Hortulus XXIV, “florum flos”) — the two poems agree word for word that the rose is the flower of flowers.' },
        { la: 'quod specie cunctos praecedat odoreque flores.', en: 'because in beauty and in scent it goes before all flowers.' },
        { la: 'Non tamen haec specie tantum nec odore iuvare', en: 'Yet not by beauty only, nor by scent, can it' },
        { la: 'nos valet, at variis nos adiuvat illa medelis,', en: 'help us — but it helps us with various remedies;' },
        { la: 'eius sicca gradu vis est et frigida primo.', en: 'its power is dry and cold in the first degree.' },
        { la: 'Compescit sacrum, si trita apponitur, ignem,', en: 'Crushed and applied, it checks the holy fire (erysipelas),' },
        { la: 'sic quoque, si stomachus calet aut praecordia, sedat;', en: 'so too it soothes, if the stomach or the midriff burns;' },
        { la: 'fluxum matricis cum vino stringit et alvi,', en: 'with wine it stanches flux of the womb and of the bowel;' },
        { la: 'illius succum collyria plurima quaerunt,', en: 'many an eye-salve calls for its juice,' },
        { la: 'et siccae pulvis morbis bene subvenit oris,', en: 'and the powder of the dried rose well aids diseases of the mouth,' },
        { la: 'infrictus per se tantum cum melleve mixtus.', en: 'rubbed in by itself alone, or mixed with honey.' },
        { la: 'Omnes fervores superaddita trita coercet', en: 'Crushed and applied it checks all inflammations,' },
        { la: 'ipsa recens, vel si mulsae commixta bibatur.', en: 'fresh itself, or drunk mixed into mead.' },
        { la: 'Ex hac conficitur oleum, roseumque vocatur,', en: 'From it is made an oil, and it is called rose-oil,' },
        { la: 'diversis morbis et multis utile causis:', en: 'useful for diverse diseases and many cases:' },
        { la: 'si bibitur ventrem mollit stomachique calorem', en: 'drunk, it softens the belly, and the stomach’s heat' },
        { la: 'extinguit nimium; bene si foveatur eodem', en: 'it quenches when excessive; if one is well fomented with it,' },
        { la: 'et dolor et fervor capitis curabitur illo;', en: 'both the pain and the fever of the head will be cured by it;' },
        { la: 'permiscendo sibi si forte iugatur acetum', en: 'if vinegar be mixed and joined to it,' },
        { la: 'expurgat sordens, vulnus repletque profundum', en: 'it cleanses a foul wound, and fills a deep one,' },
        { la: 'et combusturis praeclare convenit ignis;', en: 'and is excellent for burns of fire;' },
        { la: 'ore diu tentum dentis sedare dolorem', en: 'held long in the mouth it is said to ease toothache,' },
        { la: 'dicitur et duras palpebras reddere molles;', en: 'and to make hard eyelids soft;' },
        { la: 'aufert suppositum pruritus interiorum', en: 'applied below, it takes away itching of the inner parts,' },
        { la: 'et stericis variis solet hoc succurrere causis.', en: 'and is wont to aid various complaints of the womb.' },
        { la: 'Hoc oleum quoniam variatur conficiendo,', en: 'Since this oil varies in the making,' },
        { la: 'dicam Palladius quid scripserit inde peritus:', en: 'I will tell what the expert Palladius wrote of it:',
          n: 'Palladius — the late-Roman writer on agriculture (Opus agriculturae); Macer quotes his rose-oil recipe.' },
        { la: 'quod rubeum fuerit foliorum sumito floris', en: 'take of the petals of the flower that is red' },
        { la: 'uncia sic purgatorum iungatur olivi', en: 'an ounce; let it be joined to refined olive-oil,' },
        { la: 'in libra, vitreo sic claudens omnia vase,', en: 'to a pound; shutting all thus in a glass vessel,' },
        { la: 'sub Phoebo tantum septem suspende diebus,', en: 'hang it in the sun for just seven days,' },
        { la: 'inde medelarum varios servetur ad usus.', en: 'and thereafter keep it for the various uses of cures.' },
      ],
      note: 'Both poems crown the rose the “flower of flowers” — but where Walahfrid (XXIV) soars from it into purple, martyrdom, and the Virgin, Macer settles into pharmacy: cold and dry, against erysipelas and inflammation, and a seven-day sun-steeped recipe for rose-oil out of Palladius.',
    },
    // ── 22. Lily — pairs with Hortulus XIII (Macer pairs gold rose + silver lily, as Walahfrid does) ─
    {
      seq: 22, la: 'Lilium', en: 'Lily', bot: 'Lilium candidum', hortulus: 13,
      lines: [
        { la: 'Aurosas ut credo rosas argentea debent', en: 'As golden roses, I believe, silver lilies' },
        { la: 'lilia iure sequi, quae nec specie nec odore', en: 'must rightly follow — which neither in beauty nor in scent',
          n: 'Macer sets the silver lily after the golden rose — the same gold-and-silver pairing Walahfrid makes (rose for the martyr’s blood, lily for the white of faith).' },
        { la: 'cedere creduntur roseo collata decori,', en: 'are thought to yield to the rose’s grace when set beside it,' },
        { la: 'nec minus in multis hominum sunt apta medelis.', en: 'and are no less fit for many human remedies.' },
        { la: 'Eius radicis bulbus, quae lilia profert,', en: 'The bulb of its root, which puts forth the lilies,' },
        { la: 'sub prunis tectos iuncto quoque tritos olivo', en: 'roasted under the coals and crushed with oil added,' },
        { la: 'prodest usturis mire superadditus ignis,', en: 'applied, works wonders on burns of fire,' },
        { la: 'et melius roseum sibi si iungatur olivum;', en: 'and better if rose-oil be joined to it;' },
        { la: 'duras matrices mollit, si subditur, idem.', en: 'the same, applied below, softens a hardened womb.' },
        { la: 'Elixis eius foliis cataplasmate facto', en: 'With a poultice made of its boiled leaves' },
        { la: 'mollescunt nervi, combustaque membra iuvantur,', en: 'the sinews soften, and burnt limbs are helped,' },
        { la: 'sicque superpositis morsus curabitur anguis,', en: 'and so, laid on, a snake’s bite will be cured,',
          n: 'Walahfrid too makes the lily a snakebite remedy (Hortulus XIII, crushed in Falernian wine).' },
        { la: 'aut si cum vino bulbus potabitur ille,', en: 'or if that bulb be drunk with wine,' },
        { la: 'sic quoque fungorum vetat ille venena nocere.', en: 'so too it stops the poison of mushrooms from harming.' },
        { la: 'Hunc vino coctum tritumque pedum superadde', en: 'Cook it in wine, crush it, and lay it on the feet’s' },
        { la: 'clavis, nec solvas nisi cum lux tertia transit;', en: 'corns, and do not unbind until the third day passes;' },
        { la: 'pingui porcino decoctus idem vel olivo', en: 'the same, boiled in pork-fat or in oil,' },
        { la: 'reddere posse pilos membris narratur adustis.', en: 'is said to be able to restore hair to scorched limbs.' },
        { la: 'Cum vino potum nocuum purgare cruorem', en: 'Drunk with wine, [they say] it purges harmful blood' },
        { la: 'per ventrem dicunt et sic prodesse lieni,', en: 'through the belly, and so helps the spleen,' },
        { la: 'sicque iuvat vulvas, sic idem menstrua purgat,', en: 'and so it helps the womb, and purges the menses,' },
        { la: 'vel si cum vino veteri coctum superaddas.', en: 'or if you apply it cooked with old wine.' },
        { la: 'Praecisis nervis tritus cum melle medetur', en: 'For severed sinews, crushed with honey, it heals —' },
        { la: 'expressus succus foliorum, mixtus aceto', en: 'the juice pressed from the leaves, mixed with vinegar' },
        { la: 'et melli coquitur sic, mellis sint et aceti', en: 'and honey, cooked thus: let there be of honey and vinegar' },
        { la: 'ut geminae partes, praedicti quinque liquoris;', en: 'two parts each, and five of the aforesaid juice;' },
        { la: 'ad desiccandas nihil est magis utile plagas,', en: 'for drying wounds nothing is more useful,' },
        { la: 'inque cicatricem ducit licet inveteratas', en: 'and it brings even old wounds to a scar —' },
        { la: 'elixus bulbus et cerotis bene mixtus;', en: 'the boiled bulb, well mixed into wax-salves;' },
        { la: 'rugas distentat vultus, maculas fugat omnes,', en: 'it smooths the face’s wrinkles, drives off every blemish,' },
        { la: 'lichenas purgat, faciem quoque furfure mundat.', en: 'cleanses ringworm, and clears the face of scurf.' },
        { la: 'Exprimitur succus de tritis floribus eius,', en: 'A juice is pressed from its crushed flowers,' },
        { la: 'qui mollit vulvas cum lana subditus illis;', en: 'which softens the womb, applied to it with wool;' },
        { la: 'illitus asseritur sudorem posse movere;', en: 'smeared on, it is said to be able to bring out sweat;' },
        { la: 'turgida maturat, pus concoquit et cito purgat.', en: 'it ripens swellings, concocts the pus, and quickly purges it.' },
      ],
      note: 'Macer follows the silver lily upon the golden rose exactly as Walahfrid pairs them — and both make it a snakebite cure. But where Walahfrid’s crushed lily loses its scent and becomes the emblem of a virginity kept only unspoiled, Macer’s is a burns-salve, a wound-drier, and a face-cosmetic that smooths wrinkles and clears the skin.',
    },
    { seq: 23, la: 'Satureia',   en: 'Savory',         bot: 'Satureja hortensis' },

    // ── 24. Sage — pairs with Hortulus II ─────────────────────────────────────
    {
      seq: 24, la: 'Salvia', en: 'Sage', bot: 'Salvia officinalis',
      hortulus: 2,
      lines: [
        { la: 'Salvia, cui nomen elelisphacus est apud Argos,', en: 'Sage, whose name among the Argives is elelisphacus,',
          n: 'The same Greek name Walahfrid gives it (“elelifagus”, Hortulus II) — the two poems shake hands across two centuries on this one word.' },
        { la: 'cum mulsa iecoris prodest potata querelis,', en: 'drunk with mead, helps the complaints of the liver,' },
        { la: 'pellit abortivum, lotiumque et menstrua purgat,', en: 'drives out the stillbirth, and purges the urine and the menses,',
          n: '“pellit abortivum” — it expels a dead or miscarrying foetus; sage was both emmenagogue and, by reputation, abortifacient.' },
        { la: 'trita venenatos curat superaddita morsus,', en: 'crushed and laid on, it cures venomous bites;' },
        { la: 'crudis vulneribus (quae multo sanguine manant)', en: 'to raw wounds (those that run with much blood)' },
        { la: 'apponas tritam, dicunt retinere cruorem.', en: 'apply it crushed: they say it stanches the gore.' },
        { la: 'Cum vino succus tepidus si sumitur eius,', en: 'If its juice is taken warm with wine,' },
        { la: 'compescit veterem tussim laterisque dolorem.', en: 'it checks an old cough and pain in the side.' },
        { la: 'Pruritus vulvae curat virgaeque virilis,', en: 'It cures the itching of the womb and of the male member,' },
        { la: 'si foveas vino fuerit quo salvia cocta.', en: 'if you bathe with the wine in which sage has been boiled.' },
        { la: 'Illius succo crines nigrescere dicunt,', en: 'With its juice, they say, the hair grows black,' },
        { la: 'si sint hoc uncti crebro sub sole calenti.', en: 'if they are anointed with it often under the hot sun.' },
      ],
      note: 'Walahfrid’s sage (Hortulus II) is a green-youthed plant at war with its own offspring — a fable in seven lines. Macer’s is a working drug: liver, childbirth, urine, menses, snakebite, the stanching of wounds, old coughs, and a recipe for dyeing grey hair black. Only the Greek name elelisphacus is shared word-for-word — the clearest seam between the two poems.',
    },

    // ── 25. Lovage — pairs with Hortulus XI · MACER ANSWERS WALAHFRID BY NAME ──
    {
      seq: 25, la: 'Ligusticum', en: 'Lovage', bot: 'Levisticum officinale', hortulus: 11,
      degrees: 'hot and dry, 3rd degree',
      lines: [
        { la: 'A Ligurum patria sumpsere ligustica nomen,', en: 'Lovage took its name from the land of the Ligurians,' },
        { la: 'copia quod maior ibi nascitur illius herbae;', en: 'because a greater plenty of that herb grows there;' },
        { la: 'tertius huic gradus est sicci calidique vigoris.', en: 'it has the third degree of dry and hot vigour.' },
        { la: 'Maior radicis vis est et seminis eius', en: 'The greater power is in its root and seed,' },
        { la: 'et par est illis vis in medicamine quovis.', en: 'and in any medicine their power is equal.' },
        { la: 'Inflato stomacho cum vino sumpta medetur', en: 'Taken with wine it heals a bloated stomach,' },
        { la: 'et tali potu vis digestiva iuvatur,', en: 'and by such a draught the digestive power is helped,' },
        { la: 'omnibus et morbis sic prodest interiorum,', en: 'and so it helps all diseases of the inner parts;' },
        { la: 'urinas sic sumpta movet et menstrua purgat.', en: 'so taken it moves the urine and purges the menses.' },
        { la: 'tota venenatis medicatur morsibus herba,', en: 'the whole herb is a medicine for venomous bites,' },
        { la: 'si bibitur bene trita prius vinoque soluta,', en: 'if, well crushed and dissolved in wine, it is drunk,' },
        { la: 'et pars contritae ponatur desuper herbae.', en: 'and a part of the crushed herb is laid on top.' },
        { la: 'Non modicum colicis prodest haec mansa vel hausta,', en: 'Chewed or drunk it much helps the colicky,' },
        { la: 'vel si radicis elixatura bibatur,', en: 'or if the decoction of the root be drunk;' },
        { la: 'nec solum colicis decoctio proderit ista,', en: 'nor will that decoction help the colicky only,' },
        { la: 'sed supradictis medicabitur omnibus hausta.', en: 'but drunk it will heal all the aforesaid.' },
        { la: 'Digestibilibus semen bene iungitur eius', en: 'Its seed is well joined to all digestive' },
        { la: 'omnibus antidotis, quod inest sibi peptica virtus.', en: 'antidotes, because a digestive virtue is in it.' },
        { la: 'Hanc oculis Strabus potuque et odore nocivam', en: 'Strabo asserts this herb harmful to the eyes, by drink and by smell,',
          n: '“Strabus” is Walahfrid Strabo. This is Macer citing the Hortulus by name: Walahfrid (XI) wrote that lovage “works upon the twin orbs of the eyes, and brings on their darkness.” Macer records the claim — and then disputes it.' },
        { la: 'asserit, antidotis eius tantummodo semen', en: 'and bade that only its seed be mixed into antidotes;' },
        { la: 'misceri iussit, haec utrum dixerit a se', en: 'whether he said this of his own account,' },
        { la: 'aut a doctorum libris non est mihi notum;', en: 'or out of the books of the learned, I do not know;' },
        { la: 'hoc scio, quod veteres non parvis laudibus istam', en: 'this I know: that the ancients extol this herb' },
        { la: 'attollunt herbam, nec me legisse recordor', en: 'with no small praises, and I do not recall having read' },
        { la: 'ullum, qui Strabi sermonibus astipuletur.', en: 'anyone who agrees with Strabo’s words.',
          n: 'The crosswalk made literal: two centuries on, Macer has read Walahfrid’s lovage bed and pushes back against it — the two poems of this garden in direct, named dialogue.' },
      ],
      note: 'The keystone of the whole crosswalk. Walahfrid’s lovage (Hortulus XI) was the bed where he warned the herb dims the eyes yet kept it as a humble adjunct. Macer answers him BY NAME — “Strabo asserts this harmful to the eyes… but I recall no one who agrees with Strabo” — proof that Macer read the Hortulus, and that these two gardens are one long conversation.',
    },
    { seq: 26, la: 'Ostruthium',     en: 'Masterwort',    bot: 'Peucedanum ostruthium' },
    // ── 27. Chervil — pairs with Hortulus XII ─────────────────────────────────
    {
      seq: 27, la: 'Cerefolium', en: 'Chervil', bot: 'Anthriscus cerefolium', hortulus: 12,
      degrees: 'sharp and very fiery',
      lines: [
        { la: 'Est cerefolio vis acris et ignea valde.', en: 'Chervil has a sharp and very fiery power.' },
        { la: 'Appositum cancris tritum cum melle medetur;', en: 'Applied crushed with honey, it heals spreading ulcers;' },
        { la: 'cum vino bibitum lateris sedare dolorem', en: 'drunk with wine it is often wont to ease pain in the side,' },
        { la: 'saepe solet, tritam si nectis desuper herbam.', en: 'if you also bind the crushed herb on top.' },
        { la: 'cum mulsa bibitum pituitae noxia solvit,', en: 'drunk with mead it dissolves harmful phlegm;' },
        { la: 'ex oleo coctum frigus depellit inunctum,', en: 'cooked in oil and smeared on, it drives off chill;' },
        { la: 'si tritum mixto violento solvis aceto', en: 'if you dissolve it crushed in strong vinegar,' },
        { la: 'lumbricos tali potu tineasque repellis,', en: 'by such a draught you drive off round-worms and tapeworms;' },
        { la: 'cum vino ciet urinas et menstrua purgat.', en: 'with wine it provokes the urine and purges the menses.' },
        { la: 'Virgine cum cera vetus huic axungia mixta', en: 'Old lard mixed for it with virgin wax' },
        { la: 'non modo parotidas verum quoscunque tumores', en: 'cures or checks not only swellings of the parotid' },
        { la: 'curat vel reprimit, si saepius hoc superaddas.', en: 'but any swellings, if you apply it often.' },
        { la: 'Intinctum valido si manducetur aceto', en: 'If it is eaten dipped in strong vinegar' },
        { la: 'saepe solet vomitum ventremque tenere solutum;', en: 'it often checks vomiting and a loose belly;' },
        { la: 'si trito tegitur pecten succusque bibatur', en: 'if the pubis is covered with the crushed herb and the juice drunk,' },
        { la: 'urinae clausos reserat quoscunque meatus;', en: 'it unbars any blocked passages of the urine;' },
        { la: 'illius elixatura vertigo fugatur,', en: 'by its decoction vertigo is put to flight,' },
        { la: 'si caput hac tepida patientis saepe lavetur', en: 'if the patient’s head be often washed with it warm,' },
        { la: 'herbaque temporibus et fronti cocta ligetur.', en: 'and the cooked herb bound to the temples and the brow.' },
      ],
      note: 'Walahfrid’s chervil (Hortulus XII) was the poor man’s ever-renewing herb that staunches blood, summoned under an invocation to Erato. Macer’s is hotter-tempered — “sharp and very fiery” — a worm-killer and urine-opener, and (like his wormwood and betony) a herb bound warm to the brow against vertigo.',
    },
    { seq: 28, la: 'Atriplex',       en: 'Orache',        bot: 'Atriplex hortensis' },
    { seq: 29, la: 'Coriandrum',     en: 'Coriander',     bot: 'Coriandrum sativum' },
    { seq: 30, la: 'Nasturtium',     en: 'Garden cress',  bot: 'Lepidium sativum' },
    { seq: 31, la: 'Eruca',          en: 'Rocket',        bot: 'Eruca sativa' },
    // ── 32. Poppy — pairs with Hortulus XIV ───────────────────────────────────
    {
      seq: 32, la: 'Papaver', en: 'Poppy', bot: 'Papaver somniferum', hortulus: 14,
      degrees: 'cold and dry',
      lines: [
        { la: 'Dicunt vim gelidam siccamque papaveris esse,', en: 'They say the power of poppy is cold and dry,' },
        { la: 'tres illi tribuunt species: flos unius albus,', en: 'and assign it three kinds: of one the flower is white,' },
        { la: 'alterius roseus, rubeus pallensque minoris', en: 'of another rosy; the lesser one’s flower is red and pale —' },
        { la: 'Flos est, hanc vulgo dicunt agreste papaver.', en: 'this they commonly call the wild poppy.' },
        { la: 'Cunctis nobilior est cui flos nascitur albus;', en: 'Noblest of all is the one whose flower comes up white;' },
        { la: 'ex huius teneris opium faciunt capitellis,', en: 'from its tender heads they make opium,' },
        { la: 'incisa leviter summa cute, lacque quod inde', en: 'the top skin lightly cut, and the milk which thence' },
        { la: 'defluit, excipiunt cochleis, siccumque reservant,', en: 'flows down they catch in spoons, and keep dried,' },
        { la: 'antidotis multis aptum variisque medelis.', en: 'fit for many antidotes and various remedies.',
          n: 'Macer gives the technique of opium-extraction — scoring the unripe head and collecting the dried latex — where Walahfrid (XIV) gave only myth and etymology.' },
        { la: 'Sunt, qui contundunt cum lacte suo capitella,', en: 'There are those who pound the heads with their own milk,' },
        { la: 'de quibus expressum siccant in sole liquorem;', en: 'and dry in the sun the liquid pressed from them;' },
        { la: 'post primum succus vires habet iste secundas.', en: 'this juice has powers second after the first.' },
        { la: 'De specie vero, roseos quam gignere flores', en: 'But of the kind I said bears rosy flowers,' },
        { la: 'Dixi, conficiunt oleum de semine tuoso', en: 'they make an oil from its seed,',
          n: '“tuoso” — the transmitted word is corrupt; the sense is “from its seed.” Left as received, to be settled against the critical text.' },
        { la: 'non modicum gustu iocundum somniferumque.', en: 'an oil pleasant enough in taste, and sleep-bringing.' },
        { la: 'Tertia, cui flos est rubeus semenque nigellum,', en: 'The third, whose flower is red and seed blackish,' },
        { la: 'praestat, si bibitur, reliquarum more soporem.', en: 'gives sleep, if drunk, after the manner of the rest.' },
        { la: 'Elixatura tepida cuiuslibet harum', en: 'With the warm decoction of any of these,' },
        { la: 'aeger si foveat faciem, vel si bibat illam,', en: 'if the sick man bathe his face, or drink it,' },
        { la: 'optatum capiet, nisi sit mors proxima, somnum.', en: 'he will get the longed-for sleep — unless death is near.' },
        { la: 'Sperma nigri bibitum cum vino stringere ventrem', en: 'The seed of the black poppy, drunk with wine,' },
        { la: 'dicitur, hocque modo fluxus inhibet muliebres;', en: 'is said to bind the belly, and so checks women’s fluxes;' },
        { la: 'somnum dat bibitum, tussim compescit iniquam.', en: 'drunk it gives sleep, and checks a cruel cough.' },
        { la: 'Pondere denarii debent haec semina sumi,', en: 'These seeds should be taken to the weight of a denarius,' },
        { la: 'nam plus letargum vel mortem saepius infert.', en: 'for more often brings on lethargy, or death.',
          n: 'The dose-warning Walahfrid’s lyric poppy never sounds: past a denarius’ weight, the sleep is fatal.' },
        { la: 'De foliis eius tritis factum cataplasma', en: 'A poultice made of its crushed leaves,' },
        { la: 'eximie fauces dicunt curare tumentes,', en: 'they say, excellently cures swollen throats,' },
        { la: 'quosque vocant sacros extinguere dicitur ignes;', en: 'and is said to quench what they call the holy fires;' },
        { la: 'frigore vel cantu, potuve, cibove, vel aestu', en: 'if by cold or singing, by drink or food or heat' },
        { la: 'aspera si fuerit vocalis reddita vena,', en: 'the vocal cords have been left rough,' },
        { la: 'apposito tali fiet medicamine lenis.', en: 'by such a medicine applied they will be made smooth.' },
        { la: 'Candida meconii species (sic nempe vocari', en: 'The white species, meconium (for so, they say,' },
        { la: 'Graecorum lingua dicunt quodcunque papaver)', en: 'the Greek tongue calls any poppy)' },
        { la: 'longe nobilior est utiliorque duabus;', en: 'is far nobler and more useful than the [other] two;' },
        { la: 'tunc cum lacte fluunt capitella papaveris huius', en: 'when the heads of this poppy run with milk,' },
        { la: 'lecta coquantur aqua, cui sit pars tertia mellis', en: 'let them be picked and boiled in water, with a third part of honey' },
        { la: 'addita, cuncta coquas, donec decoctio spissa', en: 'added; cook all until the decoction is thick' },
        { la: 'sit quasi mel, varios sic conservetur ad usus:', en: 'as honey; thus let it be kept for various uses:' },
        { la: 'sumpta facit somnum, tussim fugat, abstinet alvum,', en: 'taken it brings sleep, routs cough, binds the bowel,' },
        { la: 'vocalis venae bene rheumatismata siccat.', en: 'and well dries the rheums of the vocal cords.' },
        { la: 'Eius de teneris opium factum capitellis,', en: 'Opium made from its tender heads,' },
        { la: 'sicut iam docui, roseo miscebis olivo,', en: 'as I have already taught, you will mix with rose-oil;' },
        { la: 'unge caput mixtis, sedabitur his dolor omnis', en: 'anoint the head with the mixture: every pain will be soothed,' },
        { la: 'et solet hoc unguen somni praestare quietem.', en: 'and this salve is wont to grant the rest of sleep.' },
        { la: 'Praedictis admisce croci redolentia fila,', en: 'To the above add the fragrant threads of saffron,' },
        { la: 'auris curabis haec infundendo dolorem;', en: 'and pouring it in you will cure an earache;' },
        { la: 'hoc quoque femineo cum lacte crocoque subacto', en: 'this too, worked up with woman’s milk and saffron,' },
        { la: 'ungendo calidam poteris sedare podagram;', en: 'by anointing you can ease hot gout;' },
        { la: 'ano suppositum solet hoc adducere somnum,', en: 'applied to the fundament it is wont to bring sleep,' },
        { la: 'istud idem solo praestare putatur odore.', en: 'and the same is thought to do it by its smell alone.' },
      ],
      note: 'Walahfrid’s poppy (XIV) is myth and wordplay — the grieving mother, the pomegranate-head, the name from the sound of chewing. Macer’s is a manual: the three species, the scoring of the head to bleed opium, the lethal dose past a denarius, the sleep-salve with saffron. The garden’s dreamiest flower, read once as legend and once as pharmacology.',
    },
    { seq: 33, la: 'Cepa',           en: 'Onion',         bot: 'Allium cepa' },
    { seq: 34, la: 'Buglossa',       en: 'Bugloss',       bot: 'Anchusa officinalis' },
    { seq: 35, la: 'Sinapi',         en: 'Mustard',       bot: 'Sinapis alba' },
    { seq: 36, la: 'Caulis',         en: 'Cabbage',       bot: 'Brassica oleracea' },
    { seq: 37, la: 'Pastinaca',      en: 'Parsnip',       bot: 'Pastinaca sativa' },
    { seq: 38, la: 'Origanum',       en: 'Oregano',       bot: 'Origanum vulgare' },
    { seq: 39, la: 'Serpillum',      en: 'Wild thyme',    bot: 'Thymus serpyllum' },
    { seq: 40, la: 'Viola',          en: 'Violet',        bot: 'Viola odorata' },
    { seq: 41, la: 'Aristolochia',   en: 'Birthwort',     bot: 'Aristolochia' },
    // ── 42. Horehound — pairs with Hortulus VIII ──────────────────────────────
    {
      seq: 42, la: 'Marrubium', en: 'Horehound', bot: 'Marrubium vulgare', hortulus: 8,
      degrees: 'hot and dry, 2nd degree',
      lines: [
        { la: 'Marrubium nostri, dixerunt prassion Argi;', en: 'Our people call it marrubium; the Argives said prassion;' },
        { la: 'hanc herbam medici calidam siccamque secundo', en: 'physicians hand it down as hot and dry in the second' },
        { la: 'tradunt esse gradu; decoctio totius herbae', en: 'degree. The decoction of the whole herb,' },
        { la: 'seminis aut eius phthisicos mire iuvat hausta,', en: 'or of its seed, drunk, wonderfully helps consumptives;' },
        { la: 'pectoris haec varios compescit potio morbos,', en: 'this draught checks various diseases of the chest,',
          n: 'The use Walahfrid gives horehound (Hortulus VIII): it “presses down the sick anguish of the chest.”' },
        { la: 'et melius prodest, illi si iungitur iris;', en: 'and helps the better if iris is joined to it;',
          n: 'A cross-recipe between two beds these poems share — horehound with iris (Macer 43 / Hortulus X).' },
        { la: 'asthmaticos sic sumpta iuvat tussimque repellit.', en: 'so taken it helps asthmatics and drives off the cough.' },
        { la: 'Accelerat partus eadem pellitque secundas;', en: 'The same hastens birth and expels the afterbirth;' },
        { la: 'si mel marrubio iungatur, vulnera purgat,', en: 'if honey be joined to horehound, it cleanses wounds,' },
        { la: 'hocque modo curat, quae rodunt ulcera carnem;', en: 'and in this way cures the ulcers that gnaw the flesh;' },
        { la: 'dicitur hoc bibitum lateris sedare dolorem.', en: 'drunk, it is said to ease pain in the side.' },
        { la: 'Omnibus his succus siccatus proderit eius;', en: 'For all these, its dried juice will serve;' },
        { la: 'Illius succus cum vino melleve mixtus', en: 'its juice, mixed with wine or honey,' },
        { la: 'prodest luminibus caligine debilitatis;', en: 'helps eyes weakened by film;' },
        { la: 'sic iuvat ictericos iniectus naribus idem,', en: 'so, injected in the nostrils, it helps the jaundiced,' },
        { la: 'auriculaeque gravem dicunt curare dolorem,', en: 'and they say it cures a heavy earache,' },
        { la: 'hunc mixtum roseo si fundas intus olivo.', en: 'if you pour it within, mixed with rose-oil.' },
        { la: 'Usum marrubii dicunt non esse salubrem', en: 'They say the use of horehound is not wholesome' },
        { la: 'his, qui vesicae morbo renumque laborant.', en: 'for those who suffer disease of the bladder and kidneys.' },
      ],
      note: 'The closest echo of the batch: Macer’s horehound, like Walahfrid’s (Hortulus VIII), is above all a chest-and-cough draught — and Macer adds that it works better joined with iris, knitting together two more of the beds these poems share.',
    },
    // ── 43. Iris — pairs with Hortulus X ──────────────────────────────────────
    {
      seq: 43, la: 'Iris', en: 'Iris', bot: 'Iris', hortulus: 10,
      degrees: 'hot and dry, 2nd degree',
      lines: [
        { la: 'Iri dat florum nomen color ipse suorum:', en: 'The very colour of its flowers gives the iris its name:' },
        { la: 'coelestis similes sunt nempe coloribus iris.', en: 'for they are like the colours of the heavenly rainbow.',
          n: 'Macer derives the name from the rainbow (iris); Walahfrid (Hortulus X) derived his “gladiola” from the sword (gladius) — the same plant, two etymologies.' },
        { la: 'Illyricam dicunt illam, quia plurima nasci', en: 'They call it Illyrian, because most of it is said' },
        { la: 'fertur in Illyria. Vis eius sicca calensque', en: 'to grow in Illyria. Its power is dry and hot,' },
        { la: 'dicitur atque gradum dant huic in utroque secundum.', en: 'and they give it the second degree in both.' },
        { la: 'Maior vis huius est in radicibus herbae,', en: 'The greater power of this herb is in its roots,' },
        { la: 'has desiccandas, per frusta rotunda secatas,', en: 'which are to be dried, cut into round pieces,' },
        { la: 'sic ut se partes non tangant insere filo,', en: 'threaded so the pieces do not touch,' },
        { la: 'inque loco sicco fac suspendantur in umbra,', en: 'and hung in a dry place in the shade —' },
        { la: 'vix aliter totum poteris servare per annum.', en: 'scarcely otherwise can you keep them the whole year through.',
          n: 'Walahfrid too works from the dried root (Hortulus X, “the shavings of your root, dried”); Macer gives the method of drying and keeping it — orris.' },
        { la: 'Cum vino sedant tussim, praebentque soporem,', en: 'With wine they calm a cough and bring on sleep,' },
        { la: 'si latitans intus sanies praecordia laedit,', en: 'and if lurking matter within harms the midriff,' },
        { la: 'pellitur illarum cum vino pulvere sumpto;', en: 'it is driven out by taking their powder with wine;' },
        { la: 'cum mulsa bibitus choleram depellit iniquam,', en: 'drunk with mead it drives off cruel bile,' },
        { la: 'tormina commixto bibitus sedabit aceto,', en: 'drunk with vinegar mixed in, it will ease the gripes,' },
        { la: 'hocque modo sumptis dicunt prodesse venenis,', en: 'and so taken, they say, it helps against poisons,' },
        { la: 'spleneticis et contractis et frigore laesis', en: 'for the splenetic, the cramped, and those hurt by cold' },
        { la: 'cum vino bibitus pulvis medicabitur eius,', en: 'its powder, drunk with wine, will be a remedy,' },
        { la: 'hocque modo sumptus tardantia menstrua purgat.', en: 'and so taken it brings on the delayed menses.' },
        { la: 'Duricias stericas radicum coctio mollit,', en: 'The decoction of the roots softens hardnesses of the womb,' },
        { la: 'si subtus tepida foveantur saepius illa;', en: 'if they are often fomented below with it warm;' },
        { la: 'haec cum clysterio si sit subiecta per anum,', en: 'applied through the anus with a clyster,' },
        { la: 'non modicum sciasis dicunt prodesse dolori;', en: 'they say it much helps sciatic pain;' },
        { la: 'de radicibus his mixto collyria melle', en: 'from these roots, with honey mixed, are made eye-salves' },
        { la: 'fiunt, quae vulvae pellunt subiecta secundas,', en: 'which, applied, expel the afterbirth from the womb,' },
        { la: 'inque locis haec fixa cavis syringia curant.', en: 'and set in hollow places they cure fistulas.' },
        { la: 'Commixtus melli desiccat vulnera pulvis,', en: 'The powder mixed with honey dries wounds,' },
        { la: 'carneque nuda replet, si sit superadditus, ossa.', en: 'and fills the bared bones with flesh, if applied.' },
        { la: 'Pulveris ellebori pars tertia iungitur albi', en: 'A third part of white hellebore powder is joined' },
        { la: 'iris radicum tenui cum pulvere duplo,', en: 'to a double part of fine iris-root powder;' },
        { la: 'pulvis uterque simul commixto melle ligatur,', en: 'both powders together are bound with honey mixed in;' },
        { la: 'hoc superappositum purgat lentigine vultum,', en: 'this, applied, cleanses the face of freckles,' },
        { la: 'et papulas eius istud cataplasma repellit.', en: 'and this poultice drives off its pimples.' },
      ],
      note: 'The same plant Walahfrid set beside the mythic hyacinth and gave to the fuller and the bladder. Macer renames it from the rainbow (not the sword), prizes the Illyrian root, and — like Walahfrid — builds everything on the dried root, giving the very method of slicing, threading, and shade-drying it: orris, step by step.',
    },
    { seq: 44, la: 'Enula',          en: 'Elecampane',    bot: 'Inula helenium' },
    { seq: 45, la: 'Hyssopus',       en: 'Hyssop',        bot: 'Hyssopus officinalis' },
    { seq: 46, la: 'Asarum',         en: 'Asarabacca',    bot: 'Asarum europaeum' },
    // ── 47. Mint — pairs with Hortulus XVI ────────────────────────────────────
    {
      seq: 47, la: 'Mentha', en: 'Mint', bot: 'Mentha', hortulus: 16,
      degrees: 'hot and dry, 2nd degree',
      lines: [
        { la: 'Vim calidam siccamque gradu fert mentha secundo.', en: 'Mint has a hot and dry power, in the second degree.' },
        { la: 'Illius potu vis digestiva iuvatur,', en: 'By drinking it the digestive power is helped,' },
        { la: 'confortat stomachum, vomitum quoque detinet hausta,', en: 'it strengthens the stomach, and drunk it checks vomiting,' },
        { la: 'lumbricosque modo depellere fertur eodem.', en: 'and in the same way is said to drive off worms.' },
        { la: 'Diversis morbis occurrit testiculorum,', en: 'It meets various diseases of the testicles,' },
        { la: 'si foveantur aqua, qua menthae cocta sit herba;', en: 'if they are fomented with water in which mint has been boiled;' },
        { la: 'concretum solvit lac mammis addita trita,', en: 'crushed and applied to the breasts it dissolves curdled milk,' },
        { la: 'instillata fugat auris cum melle dolorem,', en: 'instilled with honey it drives off earache,' },
        { la: 'asperitas linguae fugit illa saepe fricatae,', en: 'roughness of the tongue flees when it is often rubbed with it,' },
        { la: 'haustaque cum sapa partum solet accelerare,', en: 'and drunk with must-syrup it is wont to hasten birth,' },
        { la: 'trita canis morsum superaddita cum sale curat.', en: 'crushed and applied with salt it cures a dog’s bite.' },
        { la: 'Haec haemoptoicis mixto succurrit aceto;', en: 'With vinegar mixed it aids those who spit blood;' },
        { la: 'matrici succus si subditur illius, ante', en: 'if its juice is applied to the womb, before' },
        { la: 'quam fiat coitus, mulier non concipit inde.', en: 'intercourse takes place, the woman does not thereby conceive.',
          n: 'Mint-juice as a contraceptive — a use with no echo in Walahfrid’s lyric mint bed.' },
        { la: 'Caseolos succus putrescere non sinit eius', en: 'Its juice does not let little cheeses rot,' },
        { la: 'admixtus vel si viridis superadditur herba.', en: 'mixed in, or if the green herb is laid upon them.' },
      ],
      note: 'Walahfrid’s mint (Hortulus XVI) defeated the catalogue — its kinds as countless as the fish of the Red Sea or the sparks of Etna. Macer takes a single kind and gives its plain pharmacy: a digestive and stomach-settler, with two homely surprises — a contraceptive pessary, and a way to keep cheeses from spoiling.',
    },
    { seq: 48, la: 'Cyperus',        en: 'Galingale',     bot: 'Cyperus longus' },
    { seq: 49, la: 'Paeonia',        en: 'Peony',         bot: 'Paeonia officinalis' },
    { seq: 50, la: 'Melissophyllum', en: 'Balm',          bot: 'Melissa officinalis' },
    { seq: 51, la: 'Senecio',        en: 'Groundsel',     bot: 'Senecio vulgaris' },
    { seq: 52, la: 'Chelidonia',     en: 'Celandine',     bot: 'Chelidonium majus' },
    { seq: 53, la: 'Centaurea',      en: 'Centaury',      bot: 'Centaurium' },
    { seq: 54, la: 'Colubrina',      en: 'Dragonwort',    bot: 'Dracunculus vulgaris' },
    { seq: 55, la: 'Gaisdo',         en: 'Gaisdo (?)',    bot: 'uncertain', crux: 'The vulgate heading is garbled; identity uncertain — to be settled against the critical text.' },
    { seq: 56, la: 'Elleborus albus',en: 'White hellebore',bot: 'Veratrum album' },
    { seq: 57, la: 'Elleborus niger',en: 'Black hellebore',bot: 'Helleborus niger' },
    { seq: 58, la: 'Verbena',        en: 'Vervain',       bot: 'Verbena officinalis' },
    { seq: 59, la: 'Chamaedrys',     en: 'Germander',     bot: 'Teucrium chamaedrys' },
    { seq: 60, la: 'Maurella',       en: 'Black nightshade',bot: 'Solanum nigrum' },
    { seq: 61, la: 'Iusquiamus',     en: 'Henbane',       bot: 'Hyoscyamus niger' },
    { seq: 62, la: 'Malva',          en: 'Mallow',        bot: 'Malva sylvestris' },
    { seq: 63, la: 'Lapatium',       en: 'Dock',          bot: 'Rumex' },
    { seq: 64, la: 'Lolium',         en: 'Darnel',        bot: 'Lolium temulentum' },
    { seq: 65, la: 'Cicuta',         en: 'Hemlock',       bot: 'Conium maculatum' },

    // ── 66–77. The Eastern spices (only Costus touches Walahfrid's plot) ───────
    { seq: 66, la: 'Piper',          en: 'Pepper',        bot: 'Piper nigrum' },
    { seq: 67, la: 'Pyrethrum',      en: 'Pellitory',     bot: 'Anacyclus pyrethrum' },
    { seq: 68, la: 'Zinziber',       en: 'Ginger',        bot: 'Zingiber officinale' },
    { seq: 69, la: 'Cuminum',        en: 'Cumin',         bot: 'Cuminum cyminum' },
    { seq: 70, la: 'Galanga',        en: 'Galangal',      bot: 'Alpinia officinarum' },
    { seq: 71, la: 'Zedoar',         en: 'Zedoary',       bot: 'Curcuma zedoaria' },
    { seq: 72, la: 'Gariofilus',     en: 'Clove',         bot: 'Syzygium aromaticum' },
    { seq: 73, la: 'Cinnamomum',     en: 'Cinnamon',      bot: 'Cinnamomum verum' },
    { seq: 74, la: 'Costus',         en: 'Costmary / costus', bot: 'Tanacetum balsamita', hortulus: 15,
      crux: 'Source gap: the Latin Wikisource transcription of Macer ends around chapter 50, so the Eastern-spice chapters (51–77, including Costus) are not yet available from the working source. Awaits the full Choulant 1832 text / the critical edition before it can be planted faithfully.' },
    { seq: 75, la: 'Spica',          en: 'Spikenard',     bot: 'Nardostachys jatamansi' },
    { seq: 76, la: 'Thus',           en: 'Frankincense',  bot: 'Boswellia' },
    { seq: 77, la: 'Aloe',           en: 'Aloe',          bot: 'Aloe' },
  ],
};
