// ─────────────────────────────────────────────────────────────────────────────
// data.js — an ORIGINAL English translation of MACER FLORIDUS, De viribus herbarum
// (the "Macer"), set beside the Latin, line for line.
//
//   Odo Magdunensis ("Macer Floridus"), 11th c. — a Latin hexameter herb-poem of
//   77 plants, the most-copied herbal of the Middle Ages and the direct
//   descendant of Walahfrid's Hortulus. Where the Hortulus is a lyric garden,
//   Macer is an apothecary: each plant opens with its Galenic "degrees" of heat
//   and dryness, then a litany of decoctions, doses, and cures.
//
// WHY IT IS BED #2. It shares 17 of Walahfrid's 23 plants, so the two poems read
// as a dialogue on the same herbs — lyric vs. clinical. Each shared plant here
// carries a `hortulus` link to its Walahfrid counterpart (the crosswalk spine).
// Macer's stated degrees will also feed the garden's correspondence overlay.
//
// SOURCE OF TRUTH (Tranche 1). The Latin is transcribed from the received text on
// Latin Wikisource (the Choulant 1832 vulgate) — read directly, not from OCR
// (the Internet Archive's OCR of Choulant conflates Macer's formulaic chapters
// and is NOT trusted here). Lightly normalised: consonantal j → i. The modern
// critical edition (Schnell & Crossgrove, Tübingen 2003) and the manuscript
// tradition are the spine to converge on.
//
// The English is ours. A chapter is "planted" iff it carries `lines`; the rest
// are fallow, enumerated in the vulgate's order, awaiting later tranches. The 77
// run from the temperate garden herbs to a closing section of Eastern spices
// (Piper … Aloe), of which only Costus touches Walahfrid's plot. CC BY-SA 4.0.
// ─────────────────────────────────────────────────────────────────────────────
'use strict';

export const MACER = {
  meta: {
    title: 'Macer Floridus',
    work: 'De viribus herbarum',
    author: 'Odo Magdunensis ("Macer Floridus"), 11th c.',
    date: 'c. 1070–1100',
    dedicatee: null,
    license: 'CC BY-SA 4.0',
    method:
      'The Hortulus’s own descendant: a Latin hexameter herb-poem of 77 plants, ' +
      'written some two centuries later in the clinical register of the school of ' +
      'Salerno — degree of heat, decoction, dose. Where it shares a plant with ' +
      'Walahfrid (17 of his 23 beds), the two read as a dialogue: the lyric garden ' +
      'against the apothecary. The Latin is transcribed from the received text on ' +
      'Latin Wikisource (the Choulant 1832 vulgate), lightly normalised (j→i); the ' +
      'modern critical edition (Schnell–Crossgrove, 2003) is the spine to converge ' +
      'on. Each herb’s Galenic “degrees” are noted where Macer gives them — the raw ' +
      'material for the garden’s coming correspondence overlay. The English is ours.',
    latinSource: 'Received text (Choulant 1832 vulgate) via Latin Wikisource',
    convergeOn: 'Schnell & Crossgrove, Macer Floridus «De viribus herbarum» (Tübingen, 2003), and the manuscript tradition',
    sources: [
      { label: 'De viribus herbarum (Odo Magdunensis / Macer) — full Latin text', host: 'la.wikisource.org', url: 'https://la.wikisource.org/wiki/De_viribus_herbarum' },
      { label: 'Choulant, Macer Floridus de viribus herbarum (Leipzig, 1832) — the vulgate edition', host: 'archive.org', url: 'https://archive.org/details/deviribusherbaru00mace' },
      { label: 'Schnell & Crossgrove (Tübingen, 2003) — the modern critical edition, to converge on', host: 'reference', url: 'https://www.worldcat.org/oclc/76681313' },
    ],
  },

  // Every chapter in the vulgate's order (seq = chapter number, 1–77). A chapter
  // is "planted" when it has `lines`. `hortulus` is the seq of the matching bed in
  // ../hortulus/ (the crosswalk link) — present only for the 17 shared plants
  // (+ Costus, which Walahfrid names in his clary bed). `degrees` records Macer's
  // Galenic heat/dryness where stated, for the correspondence overlay.
  sections: [
    { seq: 1,  la: 'Artemisia',  en: 'Mugwort',        bot: 'Artemisia vulgaris' },

    // ── 2. Southernwood — pairs with Hortulus IV ──────────────────────────────
    {
      seq: 2, la: 'Abrotanum', en: 'Southernwood', bot: 'Artemisia abrotanum',
      hortulus: 4, degrees: 'hot in the 3rd degree, drying (the seed more fiercely)',
      lines: [
        { la: 'Tertius Abrotano legitur gradus esse caloris,', en: 'Southernwood is reckoned to stand in the third degree of heat,',
          n: 'Macer opens, as he does for nearly every herb, with the Galenic “degrees” — the graded scale of heat and dryness that the correspondence overlay will draw on.' },
        { la: 'et desiccandi semen ferventius herba est,', en: 'and in drying its seed is fiercer than the leaf;' },
        { la: 'unde iuvat nervos et causas pectoris omnes,', en: 'whence it helps the sinews and every trouble of the chest,' },
        { la: 'illius elixi si sit decoctio sumpta.', en: 'if a decoction of it, well boiled, be taken.' },
        { la: 'Sic quoque dysnoicis prodest tussimque repellit,', en: 'So too it helps the short of breath, and drives off the cough,' },
        { la: 'et prodest lumbis, sic vulvarumque querelis.', en: 'and helps the loins, and likewise the complaints of the womb.' },
        { la: 'Omnibus his crudum cum vino proderit haustum,', en: 'For all these, taken raw with wine, it will serve,' },
        { la: 'urinam purgat sic et praecordia mundat,', en: 'thus it purges the urine and cleanses the midriff,' },
        { la: 'sic curat sciasim, sic sumptum menstrua purgat,', en: 'thus it cures sciatica, thus taken it brings on the menses,' },
        { la: 'serpentes nidore fugat, bibitumque venena', en: 'it routs serpents by its reek, and, drunk, the venom' },
        { la: 'illorum extinguit, sedat quoque frigora febris', en: 'of those it quenches; it calms too the chills of fever' },
        { la: 'antea quam veniant si mixto sumitur amne,', en: 'before they come, if it is taken mixed with water,' },
        { la: 'aut oleo quo decoquitur si membra perungas.', en: 'or if you anoint the limbs with the oil it is boiled in.' },
        { la: 'Lumbricos ventris hanc saepe bibendo necabis.', en: 'By drinking it often you will kill the worms of the belly.' },
        { la: 'Huic panis micas et mala cidonia iungens', en: 'Joining to it crumbs of bread and quinces,' },
        { la: 'insimul amne coquas, oculorum cocta dolori', en: 'boil them together in water; the cooked mash, for pain of the eyes' },
        { la: 'apponas vel fervori, curabit utrumque.', en: 'apply, or for their inflammation: it will cure both.' },
        { la: 'Stirpes infixas et spinas abstrahet ipsum', en: 'It will draw out embedded stumps and thorns,' },
        { la: 'appositum per se vel adeps si iungitur illi.', en: 'applied by itself, or if fat is joined to it.' },
        { la: 'Haec etiam venerem pulvino subdita tantum', en: 'This too, merely laid under the pillow,' },
        { la: 'incitat, et veneri nocuis potata resistit.', en: 'rouses desire — and, drunk, withstands what harms it.' },
      ],
      note: 'Set beside Walahfrid’s southernwood (Hortulus IV) the two registers stand bare: Walahfrid gives eight lyric lines on its hair-like foliage and “as many powers as it has threads”; Macer gives a degree of heat and twenty-one lines of pharmacy — chest, loins, womb, urine, sciatica, snakebite, fever, worms, eye-pain, splinters, and a charm under the pillow. Same plant; the garden and the dispensary.',
    },

    { seq: 3,  la: 'Absinthium', en: 'Wormwood',       bot: 'Artemisia absinthium', hortulus: 7 },
    { seq: 4,  la: 'Urtica',     en: 'Nettle',         bot: 'Urtica dioica' },
    { seq: 5,  la: 'Allium',     en: 'Garlic',         bot: 'Allium sativum' },
    { seq: 6,  la: 'Plantago',   en: 'Plantain',       bot: 'Plantago major' },
    { seq: 7,  la: 'Ruta',       en: 'Rue',            bot: 'Ruta graveolens', hortulus: 3 },
    // ── 8. Celery — pairs with Hortulus XVIII ─────────────────────────────────
    {
      seq: 8, la: 'Apium', en: 'Celery', bot: 'Apium graveolens', hortulus: 18,
      degrees: 'hot and dry, 3rd degree',
      lines: [
        { la: 'Est apium dictum, quod apex hanc ferre solebat', en: 'It is called apium because the victor’s crown (apex) used to bear it,' },
        { la: 'victoris, veterum fieret dum more triumphus.', en: 'when a triumph was held in the manner of the ancients.' },
        { la: 'Ipse sibi talem prior imposuisse coronam', en: 'Alcides is said to have been the first to set such a crown' },
        { la: 'dicitur Alcides, morem tenuere sequentes.', en: 'upon himself; those who came after kept the custom.',
          n: 'Alcides = Hercules. Macer offers two etymologies for apium — from apex, the triumphal crown, and (next) from apes, the bees.' },
        { la: 'Ast alii dictum credunt, quod apes vehementer', en: 'But others believe it so called because bees, eagerly' },
        { la: 'illius soleant avide decerpere flores.', en: 'and greedily, are wont to strip its flowers.' },
        { la: 'Hanc herbam selinon solet attica dicere lingua,', en: 'The Attic tongue is wont to call this herb selinon;' },
        { la: 'virtutis calidae siccae quoque dicitur esse,', en: 'it is said to be of hot and dry power,' },
        { la: 'tertius a medicis datus est gradus huic in utroque.', en: 'and physicians give it the third degree in both.' },
        { la: 'Illius succo si candida mica terendo', en: 'If with its juice a white crumb of bread' },
        { la: 'panis iungatur, oculi sedare tumorem', en: 'be ground and joined, it is said to ease swelling of the eye,' },
        { la: 'dicitur emplastri noctu superaddita more,', en: 'applied at night in the manner of a plaster,' },
        { la: 'sicque ferunt mammis prodesse tumentibus illam.', en: 'and so they say it helps swollen breasts.' },
        { la: 'Sedat fervorem stomachi, pellitque tumorem,', en: 'It calms the heat of the stomach and drives off swelling,' },
        { la: 'et quicquid venti creat includitve nocivi', en: 'and whatever harmful wind it breeds or shuts in,' },
        { la: 'desiccans poris assumpta repellit apertis.', en: 'taken, it dries up and drives off through the opened pores.' },
        { la: 'Provocat urinas haec cruda comesta vel hausta,', en: 'Eaten raw or drunk, it provokes the urine,',
          n: 'The virtue Walahfrid also gives celery (Hortulus XVIII): the seed against stopped urine.' },
        { la: 'sed mage radicum facit hoc decoctio sumpta,', en: 'but the decoction of the roots does this more,' },
        { la: 'hoc itidem semen operatur fortius haustum.', en: 'and likewise the seed, drunk, works more strongly.' },
        { la: 'tota venenatis occurrit morsibus herba,', en: 'the whole herb meets venomous bites,' },
        { la: 'sed semen potius vel apozima proderit eius', en: 'but rather the seed, or its decoction, will help' },
        { la: 'si bibitur, tussimque modo sedabit eodem.', en: 'if drunk, and in the same way will calm a cough.' },
        { la: 'Ventrem constringit, vomitum potata coercet,', en: 'It binds the belly, and drunk it checks vomiting,' },
        { la: 'lymphae commixtum sibi si iungatur acetum;', en: 'if vinegar mixed with water be joined to it;' },
        { la: 'aegris amissum fertur reparare colorem,', en: 'it is said to restore lost colour to the sick,' },
        { la: 'cruda a ieiunis fuerit si saepe comesta.', en: 'if eaten raw, and often, on an empty stomach.' },
        { la: 'Unaquaque die vexantem corpora febrem', en: 'The fever that vexes the body day by day,' },
        { la: 'cum lympha potata iuvat febris ante tremorem.', en: 'drunk with water, it relieves — before the fever’s shivering.' },
        { la: 'Hydropicos et splen tumidum iuvat illa, iecurque', en: 'It helps the dropsical, the swollen spleen, and the liver,' },
        { la: 'si cum feniculi succo contrita bibatur.', en: 'if drunk crushed with fennel-juice.' },
        { la: 'Hacque superposita turpis lentigo fugatur.', en: 'And applied, it puts ugly freckles to flight.' },
        { la: 'Illius succus farris cum polline mixtus', en: 'Its juice, mixed with the flour of spelt' },
        { la: 'atque ovi lacrimo vulnus bene purgat et ulcus,', en: 'and with the white of an egg, well cleanses a wound and an ulcer,' },
        { la: 'si superaddatur emplastri more frequenter.', en: 'if applied often in the manner of a plaster.' },
      ],
      note: 'Where Walahfrid (Hortulus XVIII) crowned celery “the king of the body” (the stomach), Macer opens with the literal crown — the triumphal wreath of Hercules, or the bees that strip its flowers — then the shared virtue: celery provokes the urine.',
    },
    { seq: 9,  la: 'Althaea',    en: 'Marshmallow',    bot: 'Althaea officinalis' },
    { seq: 10, la: 'Anethum',    en: 'Dill',           bot: 'Anethum graveolens' },
    // ── 11. Betony — pairs with Hortulus XIX (both poems' most-praised herb) ───
    {
      seq: 11, la: 'Betonica', en: 'Betony', bot: 'Betonica officinalis', hortulus: 19,
      lines: [
        { la: 'Betonicam soliti sunt cestron dicere Graeci.', en: 'The Greeks were wont to call betony cestron.' },
        { la: 'Urinas potata ciet, lapidesque repellit,', en: 'Drunk, it provokes urine and drives out the stone,' },
        { la: 'fert haemoptoicis cum pusca sumpta iuvamen,', en: 'taken with posca it brings aid to those who spit blood,' },
        { la: 'hydropicos siccat cum vino melleque sumpta.', en: 'with wine and honey it dries up the dropsical.' },
        { la: 'De foliis eius tritis factum cataplasma', en: 'A poultice made of its crushed leaves' },
        { la: 'non modicum prodest oculis, quos laeserit ictus.', en: 'much helps eyes that a blow has injured.' },
        { la: 'Illius succus roseo commixtus olivo', en: 'Its juice, mixed with rose-oil' },
        { la: 'auribus infusus varios fugat inde dolores.', en: 'and poured in the ears, drives off various pains.' },
        { la: 'Betonicae pulvis cocto cum melle iugatus', en: 'Betony powder joined with cooked honey' },
        { la: 'empicos, tussimque iuvat, suspiria sedat,', en: 'helps the empyemic and the cough, and calms shortness of breath,' },
        { la: 'et stomachi varios sumptus iuvat ille dolores,', en: 'and, taken, it helps various stomach pains —' },
        { la: 'si febrit ex calida, cum vino si febris absit.', en: 'with hot water if there is fever, with wine if fever is absent.' },
        { la: 'Cum mulsa bibitus idem pulvis movet alvum.', en: 'The same powder, drunk with mead, moves the bowel.' },
        { la: 'Cum sale contritis foliis cataplasmate facto', en: 'With a poultice made of leaves crushed with salt' },
        { la: 'vulnera curabis, fuerint quae facta recenter,', en: 'you will cure wounds freshly made,' },
        { la: 'tritaque fracturae capitis haec sola medetur.', en: 'and crushed, it alone heals a fracture of the head.',
          n: 'The same use Walahfrid gives betony (Hortulus XIX): the dressing laid on a broken, festering head until the scar knits sound.' },
        { la: 'De foliis eius elixis fit cataplasma', en: 'From its boiled leaves a poultice is made,' },
        { la: 'utile non modicum variis vitiis oculorum;', en: 'very useful for various ailments of the eyes;' },
        { la: 'restringit lacrimas oculorum mansa vel hausta,', en: 'chewed or drunk, it checks the watering of the eyes,' },
        { la: 'hac etiam caligo solet metuenda repelli,', en: 'by it too the dreaded film is wont to be driven off,' },
        { la: 'aequo cum ruta fuerit si pondere iuncta', en: 'if it be joined with rue in equal weight' },
        { la: 'et sic cum lympha sumatur trita tepenti,', en: 'and so, crushed, be taken with warm water:' },
        { la: 'sic oculis nocuus sanguis per subtiliora', en: 'thus the blood harmful to the eyes, through the finer passages,' },
        { la: 'dicitur expelli, sic lumina libera reddi.', en: 'is said to be expelled, and the eyes set free.' },
        { la: 'Sumpta hac cum tepida purgatur vomica dira,', en: 'Taken with warm water it purges a dire abscess,' },
        { la: 'pectoris et morbi potu curantur eodem,', en: 'and diseases of the chest are cured by the same draught;' },
        { la: 'splen iuvat illius decoctio sumpta iecurque.', en: 'its decoction, taken, helps the spleen and the liver.' },
        { la: 'Uncia betonicae socianda quaterna vetusti', en: 'Four ounces of betony are to be joined' },
        { la: 'cum vini cyathis tribus, his sint addita grana', en: 'with three cyathi of old wine; to these add' },
        { la: 'viginti septem piperis, simul haec bene trita', en: 'twenty-seven grains of pepper; these, well ground together' },
        { la: 'haustaque purgabunt renes, pellentque dolores.', en: 'and drunk, will purge the kidneys and drive off pains.' },
        { la: 'Uncia cum cyathis calidae potata duobus', en: 'An ounce drunk with two cyathi of hot water' },
        { la: 'dicitur immodicum ventris sedare dolorem.', en: 'is said to ease excessive pain of the belly.' },
        { la: 'Haec tussim cum melle fugat, ventrem quoque mollit,', en: 'With honey it routs a cough, and softens the belly too;' },
        { la: 'unaquaque die febre si vexabitur aeger', en: 'if a sick man is vexed each day by fever,' },
        { la: 'uncia iungatur plantaginis una duabus', en: 'let one ounce of plantain be joined to two' },
        { la: 'betonicae, sic cum tepida contrita bibantur,', en: 'of betony, and so, crushed, be drunk with warm water,' },
        { la: 'antea quam febris praenuncia frigora fiant.', en: 'before the chills that herald the fever come on.' },
        { la: 'Uncia betonicae calidae cyatho resoluta', en: 'An ounce of betony dissolved in a cyathus of hot water' },
        { la: 'prodest hydropicis, si sit potata frequenter.', en: 'helps the dropsical, if it be drunk often.' },
        { la: 'Radicum pulvis cum mulsa tritus et haustus', en: 'The powder of the roots, ground with mead and drunk,' },
        { la: 'humores (velut elleborum) vomitu cito purgat,', en: 'purges the humours quickly by vomit, like hellebore;' },
        { la: 'bis binas dragmas praecepit Plinius harum', en: 'Pliny prescribed twice two drachms of these' },
        { la: 'radicum dare cum passo mulsove bibendas,', en: 'roots to be given, to be drunk with raisin-wine or mead;' },
        { la: 'praecipue phlegma vomitu purgabitur isto.', en: 'phlegm especially will be purged by that vomit.' },
        { la: 'Cum mulsa bibitus prodest pulvis foliorum', en: 'The powder of the leaves, drunk with mead, helps' },
        { la: 'ruptis atque steras potus levat iste cadentes.', en: 'the ruptured, and this drink relieves the falling [parts].',
          n: '“steras … cadentes” — the text is corrupt here; the sense is relief for ruptures and prolapse. Left as transmitted, to be settled against the critical edition.' },
        { la: 'Cum vino sumptis obstat potata venenis,', en: 'Drunk, it withstands poisons taken in wine,' },
        { la: 'praecipue semen, quod si desit datur herba.', en: 'the seed especially; and if that is lacking, the herb is given.' },
        { la: 'Uncia betonicae cum vino sumpta tepenti', en: 'An ounce of betony taken with warm wine' },
        { la: 'ictericos curat; cum mulsa menstrua solvit;', en: 'cures the jaundiced; with mead it looses the menses;' },
        { la: 'pondere vero fabae pulvis cum melle voratus', en: 'and the powder, to the weight of a bean, swallowed with honey' },
        { la: 'post coenam stomachum iuvat, ut bene digerat escam.', en: 'after dinner helps the stomach to digest the food well.' },
        { la: 'Si de betonica viridi sit facta corona', en: 'If a crown be made of green betony' },
        { la: 'circa serpentes, ut Plinius asserit auctor,', en: 'around serpents, as Pliny the author asserts,' },
        { la: 'audebunt nunquam positam transire coronam,', en: 'they will never dare to cross the encircling crown,' },
        { la: 'sed morsu proprio pereunt et verbere caudae.', en: 'but perish by their own bite and the lashing of their tail.',
          n: 'The Pliny legend: betony so loathed by serpents that, ringed in it, they kill themselves rather than cross.' },
        { la: 'Omnibus antidotis Menemachus eam sociari', en: 'Menemachus bids it be joined to all antidotes,' },
        { la: 'praecipit, ut stomacho magis herbis omnibus aptam.', en: 'as fitter for the stomach than all other herbs.' },
        { la: 'Plinius hanc, inquit, qui secum gesserit herbam,', en: 'Pliny says: whoever carries this herb about him' },
        { la: 'a nullo poterit nocuo medicamine laedi,', en: 'can be harmed by no hurtful drug;' },
        { la: 'et dicunt, quod ea cum vino saepius hausta', en: 'and they say that, drunk often with wine,' },
        { la: 'plumbeus abscedat color et melior revocetur.', en: 'the leaden colour [of the face] departs, and a better is restored.' },
      ],
      note: 'Both poems crown betony. Walahfrid (XIX) said the Muse herself fell short of its praise; Macer gives it the full Pliny legend — the same head-wound healer, an antidote one need only carry to be proof against poison, and a ring of it that makes any serpent destroy itself. The two exaltations meet head-on, lyric beside pharmacopoeia.',
    },
    { seq: 12, la: 'Sabina',     en: 'Savin',          bot: 'Juniperus sabina' },
    { seq: 13, la: 'Porrum',     en: 'Leek',           bot: 'Allium porrum' },
    { seq: 14, la: 'Chamomilla', en: 'Chamomile',      bot: 'Matricaria chamomilla' },
    // ── 15. Catmint — pairs with Hortulus XXII ────────────────────────────────
    {
      seq: 15, la: 'Nepeta', en: 'Catmint', bot: 'Nepeta cataria', hortulus: 22,
      degrees: 'hot and dry, 3rd degree',
      lines: [
        { la: 'Herbam, quam nepetam vulgari more vocamus,', en: 'The herb we commonly call nepeta (catmint),' },
        { la: 'hanc medici graeco calamenti nomine dicunt,', en: 'physicians name by the Greek word calamentum;' },
        { la: 'sicca calensque sibi vis est et tertius illi', en: 'its power is dry and hot, and it has the third' },
        { la: 'est in utroque gradus. Cum mulsa sicca tepenti', en: 'degree in both. Dried and taken with warm mead,' },
        { la: 'sumpta solet totum sudore resolvere corpus;', en: 'it is wont to dissolve the whole body in sweat;' },
        { la: 'ex oleo, quo sit decocta, perunge fricando', en: 'with the oil it is boiled in, anoint by rubbing' },
        { la: 'illum, venturae metuit qui frigora febris,', en: 'the man who fears the chills of a coming fever:' },
        { la: 'non frigus tantum sed febrem saepe repellit;', en: 'it often drives off not the chill only but the fever;' },
        { la: 'illi, qui sciasim patitur, coxae superadde', en: 'for him who suffers sciatica, lay on the hip' },
        { la: 'contritam viridem, fertur comburere pellem', en: 'the green herb crushed: it is said to burn the skin' },
        { la: 'et sic humores siccando fugare dolores;', en: 'and so, by drying the humours, to put the pains to flight;' },
        { la: 'appositu potuque suo cito menstrua purgat.', en: 'by application and by drink it quickly brings on the menses.' },
        { la: 'Est leprae species elephantiasisque vocatur,', en: 'There is a kind of leprosy called elephantiasis,' },
        { la: 'quae cunctis morbis maior sic esse videtur,', en: 'which seems so much the greatest of all diseases' },
        { la: 'ut maior cunctis elephas animalibus extat,', en: 'as the elephant stands greatest of all animals;' },
        { la: 'hunc in principio morbum potus calamenti', en: 'this disease, at its onset, a drink of catmint' },
        { la: 'cum vino curat humores extenuando;', en: 'with wine cures, by thinning the humours;' },
        { la: 'serpentum morsus superaddita trita nocere', en: 'applied crushed, it lets the bites of serpents' },
        { la: 'non sinit, et pellit cum vino sumpta venena.', en: 'do no harm, and drunk with wine it drives off venom.' },
        { la: 'Potus et iniectus lumbricos enecat eius', en: 'Its juice, drunk and injected, kills the round-worms,' },
        { la: 'succus et in membris vermes necat omnibus ipse,', en: 'and itself kills worms in every limb,' },
        { la: 'si mel iungatur huic cum sale plus operatur.', en: 'and works the more if honey with salt be joined to it.' },
        { la: 'Si bibit hanc praegnans aut tritam subdit, abortit.', en: 'If a pregnant woman drinks it, or applies it crushed, she miscarries.' },
        { la: 'Purgat et ictericos, cum vino curat anhelos,', en: 'It purges the jaundiced; with wine it cures the breathless,' },
        { la: 'asthmaticos medici quos graeco nomine dicunt,', en: 'whom physicians call by the Greek name asthmatic,' },
        { la: 'et iecoris morbos cum vino mitigat hausta,', en: 'and drunk with wine it soothes diseases of the liver,' },
        { la: 'hocque modo veterem lateris iuvat illa dolorem,', en: 'and in this way it relieves an old pain in the side,' },
        { la: 'atque cicatrices nigras superaddita trita', en: 'and, laid on crushed, black scars' },
        { la: 'haec naturali reddit purgando colori;', en: 'it restores, by cleansing, to their natural colour;',
          n: 'The very virtue Walahfrid gives catmint (Hortulus XXII): its rose-oil salve that smooths new scars back to clear skin.' },
        { la: 'vino decoctae facit hoc melius cataplasma.', en: 'a poultice of it boiled in wine does this better.' },
        { la: 'Compescit stomachi cum vino sumpta dolorem.', en: 'Taken with wine, it checks pain of the stomach.' },
        { la: 'Fumus de domibus serpentes effugat eius,', en: 'Its smoke drives serpents from the house,' },
        { la: 'tollere singultum cum vino dicitur hausta', en: 'drunk with wine it is said to take away hiccups,' },
        { la: 'hocque modo venerem prohibet potata frequenter.', en: 'and so, drunk often, it restrains desire.' },
      ],
      note: 'Macer’s catmint shares Walahfrid’s scar-virtue exactly — both turn fresh black scars back to natural colour — but around it Macer wraps a full litany: a sweat-cure, a fever-rub, the early treatment of elephantiasis, worms, and (against type) a check on desire.',
    },
    // ── 16. Pennyroyal — pairs with Hortulus XVII ─────────────────────────────
    {
      seq: 16, la: 'Pulegium', en: 'Pennyroyal', bot: 'Mentha pulegium', hortulus: 17,
      degrees: 'hot and dry, 3rd degree',
      lines: [
        { la: 'Fervida pulegii vis siccaque dicitur esse.', en: 'The power of pennyroyal is said to be fiery and dry.' },
        { la: 'Tertius a medicis datus est gradus huic in utroque.', en: 'Physicians give it the third degree in both.' },
        { la: 'Saepius hanc herbam si praegnans sumit, abortit;', en: 'If a pregnant woman takes this herb too often, she miscarries;' },
        { la: 'menstrua deducit cum vino sumpta tepenti,', en: 'taken with warm wine it brings down the menses,' },
        { la: 'hocque modo tardas haec extrahit herba secundas.', en: 'and in this way it draws out the delayed afterbirth.' },
        { la: '(Hoc nomen, quod non notum reor esse quibusdam,', en: '(This word, which I think is not known to some,' },
        { la: 'exponam tali quid nomine significetur:', en: 'I will explain — what is meant by such a name:' },
        { la: 'ut nondum natus testa circumdatur ovi', en: 'as the not-yet-hatched chick is wrapped in the egg’s shell,' },
        { la: 'pullus, sic infans matris vestitur in alvo', en: 'so the infant is clothed, in the mother’s womb,' },
        { la: 'quadam pellicula matris de semine facta,', en: 'in a certain membrane made from the mother’s seed,' },
        { la: 'quam nascens rumpit, quasi testam pullulus ovi,', en: 'which, being born, it breaks, as the chick the egg-shell —' },
        { la: 'istas pelliculas medici dixiere secundas,', en: 'these membranes the physicians have called the “secundae” (afterbirth),' },
        { la: 'quod mox expositos naturae iure sequantur;', en: 'because they soon follow the newborn by nature’s law;' },
        { la: 'hae si plus iusto vitio cogente morantur', en: 'if these, some fault compelling, delay longer than is right,' },
        { la: 'aut mors subsequitur, dolor aut qui vix toleratur;', en: 'either death follows, or a pain scarcely to be borne;' },
        { la: 'istas pulegium praedicto more repellit.)', en: 'these pennyroyal expels, in the way said above.)',
          n: 'Where Walahfrid’s pennyroyal bed (Hortulus XVII) digresses outward into the cosmic economy of trade, Macer’s digresses inward — a clinical aside, with an egg-shell simile, simply explaining what the afterbirth is.' },
        { la: 'Cum sale contritam melli si iunxeris illam', en: 'If you join it, crushed with salt, to honey,' },
        { la: 'unguine contractis potes hoc succurrere membris.', en: 'with this ointment you can relieve cramped limbs.' },
        { la: 'Illius pulvis sumptus cum melle vel haustus', en: 'Its powder, taken with honey or drunk,' },
        { la: 'pectoris humores viscosos extenuare', en: 'can thin the viscous humours of the chest,' },
        { la: 'et per sputa potest illos educere mire.', en: 'and draw them out wondrously by spitting.' },
        { la: 'Nausea vel morsus stomachi curabitur illa', en: 'Nausea, or gnawing of the stomach, will be cured by it,' },
        { la: 'cum pusca sumpta vel aceto quod sit aquosum;', en: 'taken with posca, or with watery vinegar;' },
        { la: 'cum vino nigram choleram potata repellit,', en: 'drunk with wine it drives off black bile,' },
        { la: 'sicque venenatis serpentum morsibus obstat.', en: 'and so withstands the venomous bites of serpents.' },
        { la: 'Si per vim febris nimiove fluore cruoris', en: 'If by force of fever, or too great a flow of blood,' },
        { la: 'aut aliquo casu subito defecerit aeger,', en: 'or by some mischance, the sick man suddenly faints —' },
        { la: 'quod solet a doctis medicis malefactio dici,', en: 'what learned physicians are wont to call a “malefactio” —' },
        { la: 'pulegium valido tritum iungatur aceto,', en: 'let pennyroyal, crushed, be joined to strong vinegar,' },
        { la: 'naribus aegroti sic apponatur, odore', en: 'and so be held to the sick man’s nostrils: by the smell' },
        { la: 'solo confestim dicunt relevare iacentem.', en: 'alone, they say, it at once revives the collapsed.',
          n: 'The transmitted text reads “incentem”; read “iacentem” (the one lying in a faint) — a smelling-salt.' },
        { la: 'Gingivas sicci pulvis confirmat et usti.', en: 'Its powder, dried and burnt, strengthens the gums.' },
        { la: 'Appositam viridem dicunt sedare podagram,', en: 'Laid on green, they say it eases gout,' },
        { la: 'et quosvis alios solet emendare tumores,', en: 'and it is wont to mend any other swellings,' },
        { la: 'si superaddatur tepidae permixta polentae;', en: 'if it be added mixed with warm barley-meal;' },
        { la: 'addita cerotis papulas de corpore tollit.', en: 'added to wax-salves, it takes pimples from the body.' },
        { la: 'Spleneticis multum superaddita cum sale prodest;', en: 'Applied with salt, it much helps the splenetic;' },
        { la: 'elixatura si quisquam saepe tepenti', en: 'if anyone often washes himself with its warm' },
        { la: 'illius abluitur, pruritus non patietur,', en: 'decoction, he will suffer no itching,' },
        { la: 'et sic matricis poteris curare tumorem;', en: 'and so you can cure a swelling of the womb;' },
        { la: 'tussim compescit cum vino sumpta tepenti,', en: 'taken with warm wine it checks a cough,' },
        { la: 'et sic urinam compellit reddere largam,', en: 'and so compels [the body] to pass copious urine,' },
        { la: 'et magis ex vino si sit decoctio facta', en: 'and the more if the decoction be made from wine,' },
        { la: 'aut oleo mixto contritam si superaddas.', en: 'or if you apply it crushed and mixed with oil.' },
        { la: 'Si radix acri contrita iugatur aceto,', en: 'If the root, crushed, be joined to sharp vinegar,' },
        { la: 'sedabit quosvis superaddita saepe tumores;', en: 'applied often it will calm any swellings;' },
        { la: 'obstat serpentum cum vino sumpta venenis', en: 'drunk with wine it withstands serpents’ venom,' },
        { la: 'et sic assumptam venerem stimulare fatentur.', en: 'and so taken, they grant, it stirs desire.' },
        { la: 'Sic quoque pulmonis prodest iecorisque querelis', en: 'Thus too it helps complaints of lung and liver,' },
        { la: 'et sic nutrici sumptum lac praebet abundans.', en: 'and so, taken by a nurse, it yields abundant milk.' },
        { la: 'Herba viridis curat morsus cum melle caninos,', en: 'The green herb, with honey, cures dog-bites,' },
        { la: 'si superaddatur et vino mixta bibatur.', en: 'if it be applied, and also drunk mixed with wine.' },
      ],
      note: 'Walahfrid and Macer both pause longest over pennyroyal. Walahfrid (XVII) turns it into the providence of trade; Macer makes it, above all, a childbirth herb — and stops to define the “afterbirth” with an egg-shell simile — then a reviving smelling-salt for the collapsed, and the usual long train of cures.',
    },
    // ── 17. Fennel — pairs with Hortulus IX ───────────────────────────────────
    {
      seq: 17, la: 'Feniculum', en: 'Fennel', bot: 'Foeniculum vulgare', hortulus: 9,
      degrees: 'hot and dry, 2nd degree',
      lines: [
        { la: 'Feniculum medici calidum siccumque secundo', en: 'Physicians say fennel is hot and dry in the second' },
        { la: 'dicunt esse gradu, marathrum Graecus vocat illud.', en: 'degree; the Greek calls it marathrum.' },
        { la: 'Cum vino cunctis obstat haec herba venenis,', en: 'With wine this herb withstands every poison;' },
        { la: 'hac mansa serpens oculos caligine purgat,', en: 'chewing it, the serpent clears its eyes of film,' },
        { la: 'indeque compertum est humanis posse mederi', en: 'and thence it was learned that it can heal human' },
        { la: 'illam luminibus, atque experiendo probatum;', en: 'eyes — and proven by trial;',
          n: 'The serpent that chews fennel to brighten its sight: the ancient ground of fennel’s eye-virtue — the same Walahfrid names (Hortulus IX, “it helps the eyes that shadow weighs upon”).' },
        { la: 'radicum succus oculis cum melle perunctis', en: 'the juice of the roots — the eyes anointed with honey —' },
        { la: 'pulsa reddit eos omni caligine claros;', en: 'renders them clear, all film driven off;' },
        { la: 'expressus marathri viridi de semine succus', en: 'the juice pressed from fennel’s green seed,' },
        { la: 'soleque siccatus magnum medicamen habetur', en: 'dried in the sun, is held a great medicine' },
        { la: 'ad quoscunque voles oculorum pellere morbos.', en: 'to drive off whatever diseases of the eyes you wish.' },
        { la: 'Auribus infusus vermes succus necat eius,', en: 'Poured into the ears, its juice kills worms;' },
        { la: 'renibus in ptisana radix decocta medetur,', en: 'the root, decocted in barley-water, heals the kidneys;' },
        { la: 'cum vino fugat hydropicos potata tumores,', en: 'drunk with wine it routs dropsical swellings,' },
        { la: 'sicque venenatis obstabit morsibus illa,', en: 'and so it will withstand venomous bites,' },
        { la: 'sic quoque pulmonis obstat iecorisque querelis,', en: 'thus too it counters complaints of lung and liver,' },
        { la: 'et sic nutrici sumpta fit copia lactis.', en: 'and so, taken by a nurse, plenty of milk comes.' },
        { la: 'Cum vino vel aqua radicum coctio sumpta', en: 'The decoction of the roots, taken with wine or water,' },
        { la: 'nefreticis et vesicae morbis medicatur,', en: 'heals the nephritic and the bladder’s diseases,' },
        { la: 'urinas purgat et menstrua sumpta resolvit,', en: 'purges the urine and, taken, looses the menses,' },
        { la: 'vel si trita super pecten haec herba ligetur;', en: 'or if this herb, crushed, be bound over the pubis;' },
        { la: 'nausea cum vino sumpta sedabitur illa,', en: 'nausea will be calmed by it taken with wine,' },
        { la: 'fervorem stomachi cum lympha mitigat hausta.', en: 'and drunk with water it soothes the heat of the stomach.' },
        { la: 'Radix illius vino decocta dolores', en: 'Its root, decocted in wine, by fomentation' },
        { la: 'fomento curat, patitur quos virga virilis,', en: 'cures the pains the male member suffers —' },
        { la: 'hoc quoque, si iungas oleum, facit, hocque perungas.', en: 'this too it does if you add oil, and anoint with it.' },
        { la: 'Ictu vel factos subito quoscunque tumores', en: 'Whatever swellings are made suddenly by a blow,' },
        { la: 'appositum tantum iuncto sedabit aceto.', en: 'it will calm, merely applied with vinegar added.' },
        { la: 'Semen cum vino bibitum veneris movet actus,', en: 'The seed drunk with wine stirs the acts of love,' },
        { la: 'hocque modo lateris diros sedare dolores', en: 'and in this way, they say, it eases the dire pains' },
        { la: 'dicunt aut herbae si sit decoctio sumpta.', en: 'of the side — or if a decoction of the herb be taken.' },
        { la: 'Tradunt auctores eius iuvenescere gustu', en: 'Authors relate that by its taste serpents grow young,' },
        { la: 'serpentes et ob hoc senibus prodesse putatur.', en: 'and for this reason it is thought good for the old.' },
      ],
      note: 'Walahfrid (Hortulus IX) gives fennel three uses in nine lyric lines; Macer gives thirty-three of pharmacy — yet both rest on the same belief that fennel clears the sight, which Macer traces to the serpent that chews it to brighten its eyes and is thereby thought to renew its youth.',
    },
    { seq: 18, la: 'Acidula',    en: 'Sorrel',         bot: 'Rumex acetosa' },
    { seq: 19, la: 'Portulaca',  en: 'Purslane',       bot: 'Portulaca oleracea' },
    { seq: 20, la: 'Lactuca',    en: 'Lettuce',        bot: 'Lactuca sativa' },
    { seq: 21, la: 'Rosa',       en: 'Rose',           bot: 'Rosa', hortulus: 24 },
    { seq: 22, la: 'Lilium',     en: 'Lily',           bot: 'Lilium candidum', hortulus: 13 },
    { seq: 23, la: 'Satureia',   en: 'Savory',         bot: 'Satureja hortensis' },

    // ── 24. Sage — pairs with Hortulus II ─────────────────────────────────────
    {
      seq: 24, la: 'Salvia', en: 'Sage', bot: 'Salvia officinalis',
      hortulus: 2,
      lines: [
        { la: 'Salvia, cui nomen elelisphacus est apud Argos,', en: 'Sage, whose name among the Argives is elelisphacus,',
          n: 'The same Greek name Walahfrid gives it (“elelifagus”, Hortulus II) — the two poems shake hands across two centuries on this one word.' },
        { la: 'cum mulsa iecoris prodest potata querelis,', en: 'drunk with mead, helps the complaints of the liver,' },
        { la: 'pellit abortivum, lotiumque et menstrua purgat,', en: 'drives out the stillbirth, and purges the urine and the menses,',
          n: '“pellit abortivum” — it expels a dead or miscarrying foetus; sage was both emmenagogue and, by reputation, abortifacient.' },
        { la: 'trita venenatos curat superaddita morsus,', en: 'crushed and laid on, it cures venomous bites;' },
        { la: 'crudis vulneribus (quae multo sanguine manant)', en: 'to raw wounds (those that run with much blood)' },
        { la: 'apponas tritam, dicunt retinere cruorem.', en: 'apply it crushed: they say it stanches the gore.' },
        { la: 'Cum vino succus tepidus si sumitur eius,', en: 'If its juice is taken warm with wine,' },
        { la: 'compescit veterem tussim laterisque dolorem.', en: 'it checks an old cough and pain in the side.' },
        { la: 'Pruritus vulvae curat virgaeque virilis,', en: 'It cures the itching of the womb and of the male member,' },
        { la: 'si foveas vino fuerit quo salvia cocta.', en: 'if you bathe with the wine in which sage has been boiled.' },
        { la: 'Illius succo crines nigrescere dicunt,', en: 'With its juice, they say, the hair grows black,' },
        { la: 'si sint hoc uncti crebro sub sole calenti.', en: 'if they are anointed with it often under the hot sun.' },
      ],
      note: 'Walahfrid’s sage (Hortulus II) is a green-youthed plant at war with its own offspring — a fable in seven lines. Macer’s is a working drug: liver, childbirth, urine, menses, snakebite, the stanching of wounds, old coughs, and a recipe for dyeing grey hair black. Only the Greek name elelisphacus is shared word-for-word — the clearest seam between the two poems.',
    },

    { seq: 25, la: 'Ligusticum',     en: 'Lovage',        bot: 'Levisticum officinale', hortulus: 11 },
    { seq: 26, la: 'Ostruthium',     en: 'Masterwort',    bot: 'Peucedanum ostruthium' },
    { seq: 27, la: 'Cerefolium',     en: 'Chervil',       bot: 'Anthriscus cerefolium', hortulus: 12 },
    { seq: 28, la: 'Atriplex',       en: 'Orache',        bot: 'Atriplex hortensis' },
    { seq: 29, la: 'Coriandrum',     en: 'Coriander',     bot: 'Coriandrum sativum' },
    { seq: 30, la: 'Nasturtium',     en: 'Garden cress',  bot: 'Lepidium sativum' },
    { seq: 31, la: 'Eruca',          en: 'Rocket',        bot: 'Eruca sativa' },
    { seq: 32, la: 'Papaver',        en: 'Poppy',         bot: 'Papaver somniferum', hortulus: 14 },
    { seq: 33, la: 'Cepa',           en: 'Onion',         bot: 'Allium cepa' },
    { seq: 34, la: 'Buglossa',       en: 'Bugloss',       bot: 'Anchusa officinalis' },
    { seq: 35, la: 'Sinapi',         en: 'Mustard',       bot: 'Sinapis alba' },
    { seq: 36, la: 'Caulis',         en: 'Cabbage',       bot: 'Brassica oleracea' },
    { seq: 37, la: 'Pastinaca',      en: 'Parsnip',       bot: 'Pastinaca sativa' },
    { seq: 38, la: 'Origanum',       en: 'Oregano',       bot: 'Origanum vulgare' },
    { seq: 39, la: 'Serpillum',      en: 'Wild thyme',    bot: 'Thymus serpyllum' },
    { seq: 40, la: 'Viola',          en: 'Violet',        bot: 'Viola odorata' },
    { seq: 41, la: 'Aristolochia',   en: 'Birthwort',     bot: 'Aristolochia' },
    // ── 42. Horehound — pairs with Hortulus VIII ──────────────────────────────
    {
      seq: 42, la: 'Marrubium', en: 'Horehound', bot: 'Marrubium vulgare', hortulus: 8,
      degrees: 'hot and dry, 2nd degree',
      lines: [
        { la: 'Marrubium nostri, dixerunt prassion Argi;', en: 'Our people call it marrubium; the Argives said prassion;' },
        { la: 'hanc herbam medici calidam siccamque secundo', en: 'physicians hand it down as hot and dry in the second' },
        { la: 'tradunt esse gradu; decoctio totius herbae', en: 'degree. The decoction of the whole herb,' },
        { la: 'seminis aut eius phthisicos mire iuvat hausta,', en: 'or of its seed, drunk, wonderfully helps consumptives;' },
        { la: 'pectoris haec varios compescit potio morbos,', en: 'this draught checks various diseases of the chest,',
          n: 'The use Walahfrid gives horehound (Hortulus VIII): it “presses down the sick anguish of the chest.”' },
        { la: 'et melius prodest, illi si iungitur iris;', en: 'and helps the better if iris is joined to it;',
          n: 'A cross-recipe between two beds these poems share — horehound with iris (Macer 43 / Hortulus X).' },
        { la: 'asthmaticos sic sumpta iuvat tussimque repellit.', en: 'so taken it helps asthmatics and drives off the cough.' },
        { la: 'Accelerat partus eadem pellitque secundas;', en: 'The same hastens birth and expels the afterbirth;' },
        { la: 'si mel marrubio iungatur, vulnera purgat,', en: 'if honey be joined to horehound, it cleanses wounds,' },
        { la: 'hocque modo curat, quae rodunt ulcera carnem;', en: 'and in this way cures the ulcers that gnaw the flesh;' },
        { la: 'dicitur hoc bibitum lateris sedare dolorem.', en: 'drunk, it is said to ease pain in the side.' },
        { la: 'Omnibus his succus siccatus proderit eius;', en: 'For all these, its dried juice will serve;' },
        { la: 'Illius succus cum vino melleve mixtus', en: 'its juice, mixed with wine or honey,' },
        { la: 'prodest luminibus caligine debilitatis;', en: 'helps eyes weakened by film;' },
        { la: 'sic iuvat ictericos iniectus naribus idem,', en: 'so, injected in the nostrils, it helps the jaundiced,' },
        { la: 'auriculaeque gravem dicunt curare dolorem,', en: 'and they say it cures a heavy earache,' },
        { la: 'hunc mixtum roseo si fundas intus olivo.', en: 'if you pour it within, mixed with rose-oil.' },
        { la: 'Usum marrubii dicunt non esse salubrem', en: 'They say the use of horehound is not wholesome' },
        { la: 'his, qui vesicae morbo renumque laborant.', en: 'for those who suffer disease of the bladder and kidneys.' },
      ],
      note: 'The closest echo of the batch: Macer’s horehound, like Walahfrid’s (Hortulus VIII), is above all a chest-and-cough draught — and Macer adds that it works better joined with iris, knitting together two more of the beds these poems share.',
    },
    { seq: 43, la: 'Iris',           en: 'Iris',          bot: 'Iris', hortulus: 10 },
    { seq: 44, la: 'Enula',          en: 'Elecampane',    bot: 'Inula helenium' },
    { seq: 45, la: 'Hyssopus',       en: 'Hyssop',        bot: 'Hyssopus officinalis' },
    { seq: 46, la: 'Asarum',         en: 'Asarabacca',    bot: 'Asarum europaeum' },
    { seq: 47, la: 'Mentha',         en: 'Mint',          bot: 'Mentha', hortulus: 16 },
    { seq: 48, la: 'Cyperus',        en: 'Galingale',     bot: 'Cyperus longus' },
    { seq: 49, la: 'Paeonia',        en: 'Peony',         bot: 'Paeonia officinalis' },
    { seq: 50, la: 'Melissophyllum', en: 'Balm',          bot: 'Melissa officinalis' },
    { seq: 51, la: 'Senecio',        en: 'Groundsel',     bot: 'Senecio vulgaris' },
    { seq: 52, la: 'Chelidonia',     en: 'Celandine',     bot: 'Chelidonium majus' },
    { seq: 53, la: 'Centaurea',      en: 'Centaury',      bot: 'Centaurium' },
    { seq: 54, la: 'Colubrina',      en: 'Dragonwort',    bot: 'Dracunculus vulgaris' },
    { seq: 55, la: 'Gaisdo',         en: 'Gaisdo (?)',    bot: 'uncertain', crux: 'The vulgate heading is garbled; identity uncertain — to be settled against the critical text.' },
    { seq: 56, la: 'Elleborus albus',en: 'White hellebore',bot: 'Veratrum album' },
    { seq: 57, la: 'Elleborus niger',en: 'Black hellebore',bot: 'Helleborus niger' },
    { seq: 58, la: 'Verbena',        en: 'Vervain',       bot: 'Verbena officinalis' },
    { seq: 59, la: 'Chamaedrys',     en: 'Germander',     bot: 'Teucrium chamaedrys' },
    { seq: 60, la: 'Maurella',       en: 'Black nightshade',bot: 'Solanum nigrum' },
    { seq: 61, la: 'Iusquiamus',     en: 'Henbane',       bot: 'Hyoscyamus niger' },
    { seq: 62, la: 'Malva',          en: 'Mallow',        bot: 'Malva sylvestris' },
    { seq: 63, la: 'Lapatium',       en: 'Dock',          bot: 'Rumex' },
    { seq: 64, la: 'Lolium',         en: 'Darnel',        bot: 'Lolium temulentum' },
    { seq: 65, la: 'Cicuta',         en: 'Hemlock',       bot: 'Conium maculatum' },

    // ── 66–77. The Eastern spices (only Costus touches Walahfrid's plot) ───────
    { seq: 66, la: 'Piper',          en: 'Pepper',        bot: 'Piper nigrum' },
    { seq: 67, la: 'Pyrethrum',      en: 'Pellitory',     bot: 'Anacyclus pyrethrum' },
    { seq: 68, la: 'Zinziber',       en: 'Ginger',        bot: 'Zingiber officinale' },
    { seq: 69, la: 'Cuminum',        en: 'Cumin',         bot: 'Cuminum cyminum' },
    { seq: 70, la: 'Galanga',        en: 'Galangal',      bot: 'Alpinia officinarum' },
    { seq: 71, la: 'Zedoar',         en: 'Zedoary',       bot: 'Curcuma zedoaria' },
    { seq: 72, la: 'Gariofilus',     en: 'Clove',         bot: 'Syzygium aromaticum' },
    { seq: 73, la: 'Cinnamomum',     en: 'Cinnamon',      bot: 'Cinnamomum verum' },
    { seq: 74, la: 'Costus',         en: 'Costmary / costus', bot: 'Tanacetum balsamita', hortulus: 15 },
    { seq: 75, la: 'Spica',          en: 'Spikenard',     bot: 'Nardostachys jatamansi' },
    { seq: 76, la: 'Thus',           en: 'Frankincense',  bot: 'Boswellia' },
    { seq: 77, la: 'Aloe',           en: 'Aloe',          bot: 'Aloe' },
  ],
};
