// chipvoice-profile.js — GENERATED by studio/tools/voice_profile.py from the reference voice.
// What lib/chipvoice.js uses in place of its textbook tables when VOICE.profile is 1.
export const PROFILE = {
 "source": "ElevenLabs voice NkiasLzNGB7MWA6gNgU4 (candidate 2c, picked by the owner), measured 2026-09-25",
 "f0": 120.3,
 "range": 0.44,
 "phones_per_sec": 11.67,
 "vowels": {
  "EH": {
   "F": [
    519,
    1815,
    2820
   ]
  },
  "AE": {
   "F": [
    820,
    1657,
    2735
   ]
  },
  "AA": {
   "F": [
    942,
    1349,
    3205
   ]
  },
  "AO": {
   "F": [
    912,
    1220,
    2998
   ]
  },
  "UH": {
   "F": [
    265,
    1471,
    2590
   ]
  },
  "AH": {
   "F": [
    654,
    1514,
    3014
   ]
  },
  "AY": {
   "F": [
    970,
    1798,
    2647
   ]
  },
  "AW": {
   "F": [
    946,
    1473,
    2896
   ]
  }
 },
 "durations": {
  "AA": {
   "dur": 105,
   "dur_stressed": 105
  },
  "AE": {
   "dur": 105,
   "dur_stressed": 105
  },
  "AH": {
   "dur": 45,
   "dur_stressed": 50
  },
  "AO": {
   "dur": 120,
   "dur_stressed": 120
  },
  "AW": {
   "dur": 160,
   "dur_stressed": 152
  },
  "AX": {
   "dur": 45,
   "dur_unstressed": 45
  },
  "AY": {
   "dur": 172,
   "dur_stressed": 172
  },
  "B": {
   "dur": 32
  },
  "CH": {
   "dur": 95
  },
  "D": {
   "dur": 50
  },
  "DH": {
   "dur": 45
  },
  "EH": {
   "dur": 130,
   "dur_stressed": 130
  },
  "ER": {
   "dur": 90,
   "dur_stressed": 115,
   "dur_unstressed": 80
  },
  "EY": {
   "dur": 125,
   "dur_stressed": 125
  },
  "F": {
   "dur": 45
  },
  "G": {
   "dur": 50
  },
  "HH": {
   "dur": 50
  },
  "IH": {
   "dur": 65,
   "dur_stressed": 75,
   "dur_unstressed": 55
  },
  "IY": {
   "dur": 100,
   "dur_stressed": 115,
   "dur_unstressed": 75
  },
  "JH": {
   "dur": 88
  },
  "K": {
   "dur": 70
  },
  "L": {
   "dur": 55
  },
  "M": {
   "dur": 60
  },
  "N": {
   "dur": 55
  },
  "NG": {
   "dur": 65
  },
  "OW": {
   "dur": 125,
   "dur_stressed": 125,
   "dur_unstressed": 65
  },
  "OY": {
   "dur": 165,
   "dur_stressed": 165
  },
  "P": {
   "dur": 80
  },
  "R": {
   "dur": 35
  },
  "S": {
   "dur": 80
  },
  "SH": {
   "dur": 85
  },
  "T": {
   "dur": 60
  },
  "TH": {
   "dur": 78
  },
  "UH": {
   "dur": 85,
   "dur_stressed": 72
  },
  "UW": {
   "dur": 100,
   "dur_stressed": 100
  },
  "V": {
   "dur": 40
  },
  "W": {
   "dur": 20
  },
  "Y": {
   "dur": 32
  },
  "Z": {
   "dur": 55
  },
  "ZH": {
   "dur": 80
  }
 }
};
