/* scripts/illustrate/tales.mjs
 *
 * Registry of every storybook the unified illustrator knows about.
 * Each entry says:
 *   - bookGlobal  the window.X identifier the tale's storybook.js attaches to
 *   - storyFile   path (relative to repo root) of the storybook source
 *   - imgDir      path (relative to repo root) where spread-NN.png lives
 *   - house       the 2–3-sentence shared style preamble for this tale
 *   - pins        { key: prose-pin } — character/setting descriptions reused across spreads
 *   - triggers    [[regex, key], ...] — regex against the spread's `illus` brief; matches add the pin
 *
 * Adding a new tale = one new entry here. Everything else (CLI, idempotency,
 * OpenAI fallback, commit-and-redeploy workflow) is shared.
 */

export const TALES = {
  /* ──────────────────────────── GAWAIN ──────────────────────────── */
  gawain: {
    bookGlobal: "GAWAIN",
    storyFile: "read/gawain/storybook.js",
    imgDir: "read/gawain/img",
    house: [
      "A storybook illustration for an 8–12 readers' faithful retelling of the 14th-century Middle English alliterative romance Sir Gawain and the Green Knight (the Pearl-Poet, Cotton Nero A.x).",
      "Style: warm gouache-and-watercolour painting in the tradition of Howard Pyle and Edmund Dulac, soft painterly textures, a cool northern winter palette — deep mossy greens, vermilion reds, oxidised gold-leaf, indigo and pewter — with quiet gold accents; Pearl-Poet manuscript atmosphere; cinematic but child-friendly.",
      "Single illustrative scene, full bleed, no panel borders, no text, no captions, no lettering, no logos, no watermarks; medieval English North-West Midlands setting around 1380, no modern dress or anachronisms.",
    ].join(" "),
    pins: {
      gawain:       "Sir Gawain: a fair-skinned young knight in his early twenties with golden shoulder-length hair, wearing a scarlet surcoat over mail with a gold five-pointed star — a pentangle, every line drawn continuous, the endless knot — clearly painted on the chest; gold spurs; sky-blue cloak when riding.",
      greenknight:  "The Green Knight: an enormous, vivid green-skinned knight with green hair and a long green beard, green clothes, on a green warhorse; in one hand a small sprig of bright red-berried holly, in the other a colossal gold-bound axe whose handle is as tall as a man; magical, awe-inspiring, not menacing.",
      bertilak:     "Bertilak the lord of the castle (same large frame as the Green Knight but without any green): a broad, jovial, broad-shouldered nobleman with a thick red-brown beard, in russet hunting furs over fine wool, warm and laughing.",
      lady:         "Lady Bertilak: a strikingly beautiful young woman with pale-gold hair coiled and netted in gold, in a flame-red brocade gown with white ermine trim and a gold girdle.",
      morgan:       "Morgan le Fay disguised as the ancient lady: a small wrinkled old woman in dark indigo robes, her face almost wholly hidden by a white wimple and a heavy black veil drawn up to her chin, walking very quietly just behind the young lady — present but barely noticed.",
      arthur:       "King Arthur: a young, beardless king in his mid-twenties with dark hair and a slim gold circlet, in a deep red mantle over mail, restless and bright-eyed.",
      guinevere:    "Queen Guinevere: a fair young queen with grey eyes in a green-and-gold brocade gown, set beside the king.",
      gringolet:    "Gringolet: a powerful chestnut warhorse with a long mane and a richly gold-decorated harness — saddle, breastband and bridle worked with gold trim.",
      pentangle:    "The pentangle: a five-pointed star painted in shining gold leaf on Gawain's red shield, every line drawn unbroken and interlaced — the endeles knot — and inside the shield, on the side toward the bearer, a tiny painted figure of the Virgin Mary.",
      camelot:      "Camelot: a great firelit medieval hall on a snowy winter evening, jewel-coloured tapestries, deep arched stone windows, Christmas greenery on the walls, long high tables and a high seat under a fur-trimmed canopy.",
      hautdesert:   "Hautdesert castle: a warm timber-and-stone winter castle gleaming with lamplight, set in a snow-dusted wood of bare oaks; smoke from chimneys; high battlements; secluded.",
      chapel:       "The Green Chapel: a grass-and-moss-covered ancient burial mound in a snowy valley, with three small openings (one at each end, one on top), beside a clear brook that runs steaming over small stones; bare winter trees, uncanny and quiet.",
      axe:          "The Green Knight's axe: a colossal Danish-style long-axe, gold-bound at the head, the handle bound with bright cloth, freshly sharpened to a mirror edge — four feet of blade plus a man-tall handle.",
      girdle:       "The green girdle: a long bright-green silk sash, narrow as a hand's-breadth, with embroidered ends and gold-thread hems — the lady's lace that becomes Gawain's fault and finally the court's livery.",
      guide:        "Bertilak's guide: a cloaked man on a sturdy horse, hood drawn deep, face barely visible.",
      agravain:     "Agravain à la dure main: a black-haired young knight at the Christmas table, brother to Gawain.",
      yvain:        "Yvain son of Urien: a young knight in russet at the Christmas table.",
      baldwin:      "Bishop Baldwin: a white-haired elderly bishop in red-and-gold vestments, opposite Gawain at the Christmas table.",
    },
    triggers: [
      [/sir gawain|gawain|young knight|hero|pentangle/i, "gawain"],
      [/green knight|green man|the giant\b|green hair|green skin|green beard|\ball (vivid )?green\b|green warhorse|green horse|enormous knight|holly bough|sprig of (red[- ]berried )?holly|huge axe|colossal axe/i, "greenknight"],
      [/bertilak|lord of the castle|laughing lord|broad[- ]bearded|the lord\b|red[- ]brown bear(d|ded)/i, "bertilak"],
      [/the lady|lady bertilak|lady of the castle|young lady|beautiful (young )?(woman|lady)/i, "lady"],
      [/morgan|ancient lady|veiled|wimpled|withered/i, "morgan"],
      [/\barthur\b|king arthur|the king/i, "arthur"],
      [/guinevere|the queen/i, "guinevere"],
      [/gringolet|chestnut (horse|warhorse)|gold[- ]decorated harness/i, "gringolet"],
      [/pentangle|endless knot|five-pointed|gold star/i, "pentangle"],
      [/camelot|great hall|high table|christmas feast|christmas hall|firelit (great )?hall/i, "camelot"],
      [/hautdesert|castle in the wood|winter castle|warm[- ]lit (towers|castle)|castle (gleaming|gates)/i, "hautdesert"],
      [/green chapel|barrow|burial mound|hollow mound|steaming brook|grassy mound|grass[- ]covered .* mound/i, "chapel"],
      [/\baxe\b|axe[- ]handle|whetstone|danish[- ]style/i, "axe"],
      [/girdle|green sash|green silk|silk lace|silk (sash)?\s*trimmed with gold/i, "girdle"],
      [/cloaked (rider|guide)|hooded (man|rider)|silent (rider|guide)|guide on horseback/i, "guide"],
      [/agravain/i, "agravain"],
      [/yvain|ywain/i, "yvain"],
      [/baldwin|bishop/i, "baldwin"],
    ],
  },

  /* ──────────────────────────── CULHWCH ──────────────────────────── */
  culhwch: {
    bookGlobal: "CULHWCH",
    storyFile: "read/culhwch/storybook.js",
    imgDir: "read/culhwch/img",
    house: [
      "A storybook illustration for an 8–12 readers' faithful retelling of the medieval Welsh tale Culhwch ac Olwen.",
      "Style: warm gouache-and-watercolour painting, soft painterly textures, gentle earthy palette — deep mossy greens, ochres, warm reds, with quiet gold accents; Celtic-medieval atmosphere; cinematic but child-friendly.",
      "Single illustrative scene, full bleed, no panel borders, no text, no captions, no lettering, no logos, no watermarks; no modern dress or anachronisms.",
    ].join(" "),
    pins: {
      culhwch:    "Culhwch: a young man in his late teens, fair-skinned with shoulder-length copper-red hair, wearing a dark green tunic with a bronze brooch and a russet wool cloak. When riding, he is on a dappled-grey horse with a golden bridle.",
      olwen:      "Olwen: a young woman with pale skin and very long pale-gold hair, in a flame-red silk dress with a gold torque at her throat; four small white clover-flowers spring up in her footprints wherever she walks.",
      arthur:     "Arthur: a bearded warrior-king in his thirties in a dark indigo-blue cloak with a simple gold circlet on dark hair.",
      ysbaddaden: "Ysbaddaden, Chief of Giants: an enormous shaggy giant with a long grey beard and grotesquely heavy drooping eyebrows propped up by wooden forks held by tiny servants; comic-grotesque, not horrifying.",
      cei:        "Cei: a tall, broad warrior with russet hair and a green wool mantle.",
      bedwyr:     "Bedwyr: a swift, one-handed warrior with dark hair.",
      gwrhyr:     "Gwrhyr: a slim hooded man, hand outstretched toward birds or beasts as if listening.",
      menw:       "Menw the enchanter: a wiry cloaked man with faint silver light wreathing his silhouette.",
      twrch:      "Twrch Trwyth: a colossal black-bristled boar with a small golden comb and silver shears glinting between its ears.",
      oldest:     "The oldest animals: a great wise blackbird, a mighty antlered stag, a vast horned owl, an enormous eagle, and an immense salmon — each with the calm of great age.",
      goreu:      "Goreu: a brave dark-haired boy who has been hidden in a stone chest by the hearth.",
      giantfort:  "The giant's fortress: a vast distant stone keep on a wide green plain, walls and gates outsized.",
    },
    triggers: [
      [/culhwch|young man|hero\b|riding/i, "culhwch"],
      [/olwen|maiden|clover/i, "olwen"],
      [/arthur|kingly/i, "arthur"],
      [/ysbaddaden|chief of giants|giant's hall|eyebrow/i, "ysbaddaden"],
      [/\bcei\b/i, "cei"],
      [/bedwyr/i, "bedwyr"],
      [/gwrhyr|interpret|listening to (a )?bird/i, "gwrhyr"],
      [/menw|enchant/i, "menw"],
      [/twrch|boar/i, "twrch"],
      [/oldest animals|blackbird|stag|owl|eagle|salmon/i, "oldest"],
      [/goreu|stone chest/i, "goreu"],
      [/fortress|castle|keep/i, "giantfort"],
    ],
  },

  /* ──────────────────────────── ORFEO ──────────────────────────── */
  orfeo: {
    bookGlobal: "ORFEO",
    storyFile: "read/orfeo/storybook.js",
    imgDir: "read/orfeo/img",
    house: [
      "A storybook illustration for an 8–12 readers' faithful retelling of the c.1300 Middle English Breton lay Sir Orfeo (the classical Orpheus rebuilt as a king of Winchester whose queen is taken not into Hades but into the Land of Faerie).",
      "Style: warm gouache-and-watercolour painting in the tradition of Howard Pyle and Edmund Dulac, soft painterly textures; a cool northern English palette — deep mossy greens, vermilion reds, silver, indigo, oxidised gold — with quiet jewel-tone accents; medieval English atmosphere (c.1300 setting); cinematic but child-friendly.",
      "Single illustrative scene, full bleed, no panel borders, no text, no captions, no lettering, no logos, no watermarks; medieval English setting around 1300, no modern dress or anachronisms.",
    ].join(" "),
    pins: {
      orfeo_king:    "Sir Orfeo as king: a young, fair-haired English king in his late twenties with shoulder-length golden-blond hair, in fine scarlet medieval royal robes trimmed with ermine, a slim gold circlet on his head, carrying a small carved gold-strung Celtic lap-harp; expressive, gentle, noble.",
      orfeo_pilgrim: "Sir Orfeo in pilgrim/exile form: the same man, now very thin and weathered, with a long unkempt black beard down to his waist, long matted black hair to his shoulders, in a tattered rough grey wool pilgrim's cloak (a sclavin), barefoot, the same small gold-strung Celtic harp hanging on his back by a leather cord; dignified, not pitiful.",
      orfeo_disguise: "Sir Orfeo in beggar's disguise: ragged figure in a rough brown beggar's hooded coat over the grey sclavin, long black beard and shaggy hair, the harp on his back, his face half-hidden by the hood; weary but watchful.",
      heurodis:      "Lady Heurodis (Eurydice): a beautiful young queen with very long pale-gold hair, fine-featured pale skin, wearing a flowing silver-and-gold silk medieval gown trimmed with white ermine, a thin gold circlet on her head; radiant, gentle, grave.",
      fairyking:     "The Fairy King: a tall, dark-haired, otherworldly king ageless and proud, wearing rich green-and-silver medieval robes; crowned not with metal but with a single huge radiant precious stone (a jewel-crown) that shines like the sun; severe but kingly, awe-inspiring, not evil.",
      fairyqueen:    "The Fairy Queen: a regal, otherworldly queen with very pale-gold hair, robed in white-silver silks; crowned, like her king, with a single radiant precious stone instead of metal; shining almost too bright to look at.",
      steward:       "The high steward of Winchester: an older man in his fifties with a kind, careworn face, full grey-brown beard, in fine russet wool robes trimmed with fox-fur, a silver chain of office across his shoulders; dignified, loyal.",
      beggar:        "The Winchester beggar: a kind, weathered old man with a long grey beard, in a worn brown wool cloak with a hood, his face calm and welcoming.",
      porter:        "The porter of the Otherworld castle: a tall cloaked figure standing at a crystal-and-gold gate, robed in deep green, face partly luminous and indistinct, otherworldly.",
      ympetree:      "The ympe-tree: a particular grafted/doubled fruit tree (two trunks twisted into one, like grafted apple or pear), heavy with white blossom in May; a folk-symbol of the fae-frequenting spot.",
      harp:          "Orfeo's harp: a small portable medieval Celtic-style lap harp of dark wood, gold-strung, beautifully carved at the neck and pillar, the size of a child.",
      fairyretinue:  "The Fairy King's retinue: a hundred fair knights and a hundred fair damsels riding snow-white horses, robes as white as milk, gold-thread embroidery, expressions calm and grave; a procession out of the Otherworld.",
      halftaken:     "The half-taken: the inside of the Otherworld castle yard, full of human figures perfectly still, frozen in the postures they were taken in — a fully armoured knight on a stilled horse with sword raised mid-stroke, a sleeping fair woman on grass under a small ympe-tree, a young mother peacefully holding a swaddled baby, an oarsman frozen in a small boat half-tilted on calm water, a man with one hand raised against an off-stage threat. Strictly handled with folktale tact — beautiful and uncanny, NEVER gory, no visible wounds or blood. Like statues in a tableau.",
      wildbeasts:    "The wild beasts and birds of England: a stag with great antlers, a great brown bear, foxes, hares, badgers, every kind of small English bird perched on briars; a peaceful audience to harping in a sunlit clearing.",
      hawkingladies: "Sixty fair-haired ladies in green and gold riding habits on snow-white horses, each with a falcon perched on her gauntleted left hand; gentle, graceful, no men among them; an Otherworld hunt.",
      crystalcastle: "The Otherworld crystal castle: an enormous fairy castle on a smooth green plain; walls of clear crystal as bright as glass; a hundred slender towers; buttresses of red gold arching out of the moat; cornices carved with every manner of beast; some of the stones in the walls glowing faintly with their own light; magical, awe-inspiring, slightly uncanny — not quite Paradise.",
      rockcleft:     "A great grey rock face in a wild English landscape, with a tall narrow vertical cleft in the rock just wide enough for a horse — the threshold between worlds.",
      winchester:    "Medieval Winchester: a small English walled medieval cathedral city with stone walls and slender towers and gatehouses, low timber-and-stone houses inside, the cathedral spire visible above the rooftops; about 1300 in style.",
      greathall:     "A great medieval English hall lit by warm firelight: high arched ceiling, tapestries, long oak tables, carved wooden throne or high seat on a dais, banners on the walls, Christmas-greenery or just rich firelight.",
    },
    triggers: [
      [/\bking orfeo\b|young king orfeo|fair[- ]haired (young )?king|on a (carved wooden )?throne|gold circlet|crowned together on a throne|royal scarlet|king in scarlet/i, "orfeo_king"],
      [/sclavin|pilgrim'?s cloak|ragged|beard (down|hangs) to (his )?(waist|girdle|knee|belt)|long black beard|matted black hair|bearded.*grey|grey pilgrim'?s wool|tattered.*grey/i, "orfeo_pilgrim"],
      [/beggar'?s (brown |coarse |borrowed )?(coat|hood)|in the borrowed beggar'?s|brown beggar'?s hooded coat/i, "orfeo_disguise"],
      [/heurodis|the queen \(heurodis\)|silver[- ]and[- ]gold silk|queen in silver silk|pale[- ]gold hair circlet|silver gown/i, "heurodis"],
      [/fairy king\b|king o fairy|fairy king'?s|jewel[- ]crown|crown of one (huge )?radiant (gem|jewel|stone)/i, "fairyking"],
      [/fairy queen/i, "fairyqueen"],
      [/steward/i, "steward"],
      [/kind (old )?beggar|old beggar|the beggar (standing|talking|seated|in|at)|grey[- ]bearded beggar/i, "beggar"],
      [/porter(?! of the castle gate of fairy)/i, "porter"],
      [/ympe[- ]tree|grafted (\/doubled )?fruit tree|grafted apple|doubled trunk/i, "ympetree"],
      [/\bharp\b/i, "harp"],
      [/snow[- ]white (horses|riders|steeds)|hundred (fair )?(knights|damsels)|fairy retinue/i, "fairyretinue"],
      [/half[- ]taken|frozen in the (postures|moment)|armoured knight on a stilled horse|tableau/i, "halftaken"],
      [/wild beasts|wild creatures|\bstag\b|antlered|brown bear\b|foxes\b|\bhares\b|badgers|every kind of small (english )?bird/i, "wildbeasts"],
      [/sixty (fair[- ]haired )?ladies|hawking|falcon|gauntleted/i, "hawkingladies"],
      [/crystal castle|walls of (clear )?crystal|crystal[- ]and[- ]gold gate|fairy[- ]castle|otherworld castle|crystal gate|hundred (slender )?towers/i, "crystalcastle"],
      [/rock cleft|cleft in (a |the |great )?rock|three miles? through (the )?rock/i, "rockcleft"],
      [/winchester|medieval english city|city gate|cathedral city/i, "winchester"],
      [/great (firelit )?(medieval )?(english )?hall|firelit hall|long oak tables|carved wooden throne/i, "greathall"],
    ],
  },

  /* ──────────────────────────── PWYLL ──────────────────────────── */
  pwyll: {
    bookGlobal: "PWYLL",
    storyFile: "read/pwyll/storybook.js",
    imgDir: "read/pwyll/img",
    house: [
      "A storybook illustration for an 8–12 readers' faithful retelling of the medieval Welsh prose tale Pwyll Pendefig Dyfed, the First Branch of the Mabinogi — a pre-Arthurian tale of a Welsh prince who trades places for a year with Arawn lord of Annwn, wins Rhiannon the fairy bride at the Gorsedd Arberth, outwits Gwawl son of Clud at the wedding feast, and recovers a lost-and-found son who is named Pryderi.",
      "Style: warm gouache-and-watercolour painting in the tradition of Howard Pyle and Edmund Dulac, soft painterly textures; an earthy Welsh palette — mossy greens, ambers, russets, peat-browns, with quiet gold accents and a single bright white-and-red note for the Otherworld; Welsh medieval atmosphere around 1100; cinematic but child-friendly.",
      "Single illustrative scene, full bleed, no panel borders, no text, no captions, no lettering, no logos, no watermarks; Welsh medieval setting around 1100, no modern dress or anachronisms.",
    ].join(" "),
    pins: {
      pwyll:           "Pwyll Prince of Dyfed: a tall young Welsh prince in his mid-twenties, fair-skinned with shoulder-length dark hair, wearing a gold torc at his neck, a russet hunting cloak over a forest-green wool tunic, a leather belt with a hunting horn at his hip; brave, generous, honourable.",
      pwyll_arawn:     "Pwyll wearing Arawn's form: bearing a mature lordly noble face (stately, slightly weathered, kingly) rather than his own youthful Pwyll face, but still wearing the same gold torc and Welsh medieval clothes; the change is shown in face and bearing only.",
      arawn:           "Arawn King of Annwn (in his own form): a tall mature stately lord in grey-brown Welsh wool hunting clothes, mounted on a pale-grey horse, with a curling hunting horn slung around his neck; dignified, slightly stern, otherworldly without being sinister.",
      hafgan:          "Hafgan the rival king of Annwn: a tall otherworldly king in summer-bright clothes — a golden-yellow tunic, a lighter mane of hair, carrying a glowing white-and-gold shield; noble, doomed, never depicted gorily.",
      rhiannon:        "Rhiannon: a beautiful young Welsh woman with long flowing golden-blonde hair, in a flowing gown of gold-shot silk that catches the sun, mounted on a tall, broad, pale-white horse that moves at a slow walking pace; the light around her is soft and enchanted, fairy-suffused.",
      rhiannon_penance: "Rhiannon during her penance at the gate: the same Rhiannon, now in plain dark Welsh wool, no jewellery, hair tied back simply, posture humble but still proud — dignified and quietly noble, never abject. Handled with folktale tact.",
      gwawl:           "Gwawl son of Clud: a tall noble rival suitor with a polished proud face and auburn hair, in a fine silk robe trimmed with light yellow-gold; outwardly fair, inwardly entitled.",
      teirnon:         "Teirnon Twrf Liant: a middle-aged Welsh lord, broad-shouldered, with a kind weather-worn face and a short brown beard, in a warm wool tunic and a leather work-apron; gentle, brave, ‘the best man in the world’.",
      teirnon_wife:    "Teirnon's wife: a kind middle-aged Welsh woman in plain warm wool, calm-faced and capable.",
      pryderi:         "Pryderi / Gwri of the Golden Hair: a fair-skinned boy with bright golden hair, in a well-made child's Welsh green tunic with an embroidered hem and a small leather belt; strong and bright-eyed for his apparent age (he grows fast).",
      queen_annwn:     "The Queen of Annwn (Arawn's wife): a calm regal kind-faced queen with silver-blonde hair, in a shimmering gold-shot silk court robe.",
      pendaran:        "Pendaran Dyfed: an older bearded Welsh noble, grave and trusted, in a heavy wool cloak.",
      cwn_annwn:       "The Cŵn Annwn (Hounds of Annwn): tall noble supernatural hunting-hounds with SHINING BRILLIANT WHITE coats and BRIGHT RED ears, calm and otherworldly (not snarling), softly glowing with Otherworldly light; white-and-red is their visual signature.",
      whitehorse:      "Rhiannon's pale-white horse: a tall, broad, steady pale-white horse moving at an unhurried walking pace; magical, never tiring, impossible to catch.",
      mare_foal:       "Teirnon's mare and her foal: a fine chestnut mare with a newborn chestnut colt on fresh straw inside a stone-built Welsh stable.",
      claw:            "The unseen power's arm at the window: a great dark-grey clawed arm reaches through a high arched glassless window, severed cleanly above the elbow — the rest of it is in the act of being pulled back outside (only its diminishing shadow is suggested). The arm is shown without blood; the unseen power's body is NEVER shown.",
      gorsedd:         "The Gorsedd Arberth: a real-shaped Welsh burial-mound, grass-covered, weathered, gently sloped, set just above a small stone-and-timber Welsh court — a magic-touched place where marvels happen to whoever sits on it.",
      arberth:         "Arberth: Pwyll's chief court — a stone-and-timber Welsh medieval court with a great hall, painted shields on the walls, carved oak tables, set in rolling green Welsh hill country.",
      annwn_hall:      "The great hall of Annwn: a magnificent Welsh medieval great hall at evening, lit by torches and a great hearth-fire — high carved-wood roof, painted shields, long oak tables laden with food; otherworldly in scale, not in style.",
      glyncuch:        "Glyn Cuch: a wide wooded Welsh valley at dawn, forest interior with tall trees, dappled morning light through trunks, a sense of magic and quiet wildness.",
      bag:             "Rhiannon's magic bag: a small dark Welsh wool bag with a long drawstring, plain on the outside, never-filling on the inside — folkloric and unassuming.",
      ford:            "The ford of the duel: a clear shallow river-ford between two green Welsh banks at high noon, with lines of watching nobles on both banks.",
      gwawl_hall:      "Gwawl's feasting hall: a great Welsh medieval feasting hall similar in scale to Hyfaidd Hen's court — long oak tables, warm firelight, carved roof.",
    },
    triggers: [
      [/\bpwyll\b(?! in arawn'?s form)|prince of dyfed|young (welsh )?prince|russet hunting cloak|gold torc/i, "pwyll"],
      [/in arawn'?s form|now bearing arawn'?s|mature lordly face|wearing arawn'?s form|pwyll \(in arawn'?s form\)/i, "pwyll_arawn"],
      [/\barawn\b|king of annwn|grey rider|pale[- ]grey horse|hunting horn (around|slung)/i, "arawn"],
      [/hafgan|the other king|golden[- ]yellow tunic|white[- ]and[- ]gold shield|rival king/i, "hafgan"],
      [/\brhiannon\b(?! during| in plain| now in plain)|golden[- ]blonde|gold[- ]shot silk|fairy bride/i, "rhiannon"],
      [/penance|mounting[- ]block|plain (dark|simple|warm)? ?wool|no jewel(le)?ry|rhiannon (during|in plain|released)|carry(ing)? .* on (her )?back|humble but proud/i, "rhiannon_penance"],
      [/\bgwawl\b|son of clud|auburn hair|fine silk robe trimmed/i, "gwawl"],
      [/teirnon(?!'?s wife)|the best man in the world|brown beard.*wool tunic/i, "teirnon"],
      [/teirnon'?s wife|kitchen[- ]hearth/i, "teirnon_wife"],
      [/pryderi|\bgwri\b|golden[- ]haired boy|golden hair.*boy|golden tufts/i, "pryderi"],
      [/queen of annwn|arawn'?s queen|silver[- ]blonde/i, "queen_annwn"],
      [/pendaran/i, "pendaran"],
      [/cŵn annwn|cwn annwn|white hounds|hounds of (the )?otherworld|red ears|brilliant white coats|shining (brilliant )?white/i, "cwn_annwn"],
      [/pale[- ]white horse|broad pale[- ]white|rhiannon'?s horse|magic horse|never[- ]tiring/i, "whitehorse"],
      [/chestnut mare|chestnut foal|newborn (chestnut )?(foal|colt)|stable|mare (in|on) (her )?stall/i, "mare_foal"],
      [/clawed arm|great clawed|severed arm|the claw|disembodied claw|reaching through (the |a )?(high )?window/i, "claw"],
      [/gorsedd( arberth)?|burial[- ]mound|grass[- ]covered .* mound|low grass[- ]covered mound/i, "gorsedd"],
      [/arberth(?! visible)|court at arberth|gate of arberth|arberth (court|visible)/i, "arberth"],
      [/court of annwn|great hall of annwn|annwn.*hall|magnificent welsh medieval great hall/i, "annwn_hall"],
      [/glyn cuch|wooded valley|welsh forest interior|forest (interior|valley) (at )?dawn/i, "glyncuch"],
      [/\bbag\b|magic bag|small dark wool bag|never[- ]filling|drawstring/i, "bag"],
      [/\bford\b|river[- ]ford|duel at the ford|shallow water between/i, "ford"],
      [/gwawl'?s (feast|hall|feasting hall)/i, "gwawl_hall"],
    ],
  },

  /* ──────────────────────────── OWAIN ──────────────────────────── */
  owain: {
    bookGlobal: "OWAIN",
    storyFile: "read/owain/storybook.js",
    imgDir: "read/owain/img",
    house: [
      "A storybook illustration for an 8–12 readers' faithful retelling of the medieval Welsh romance Owain, neu Iarlles y Ffynnon (Owain, or the Lady of the Fountain), one of the Three Welsh Romances — a knight of Arthur's court who rides to a magic storm-fountain, defeats its Black Knight and weds the widowed Lady, breaks the term she set and runs mad in the wilderness, and is redeemed with the help of a grateful lion.",
      "Style: warm gouache-and-watercolour painting in the tradition of Howard Pyle and Edmund Dulac, soft painterly textures; an earthy Welsh palette — mossy greens, ambers, russets, peat-browns, with quiet gold accents and a single cool storm-grey note for the fountain's tempest; Welsh medieval romance atmosphere around the 12th–13th century; cinematic but child-friendly.",
      "Single illustrative scene, full bleed, no panel borders, no text, no captions, no lettering, no logos, no watermarks; Welsh medieval setting, no modern dress or anachronisms.",
    ].join(" "),
    pins: {
      owain:        "Owain son of Urien: a young Welsh knight in his mid-twenties, fair-skinned with dark shoulder-length hair, a gold torc at his neck, a deep-blue surcoat over mail; brave, courteous, a little headstrong.",
      owain_mad:    "Owain in his madness: the same young man, now gaunt, ragged and barefoot, hair and beard wild and matted, in the tatters of what was once fine cloth, living rough in the wilderness — pitiable but never grotesque; handled with folktale tact.",
      lion:         "The lion: a great tawny lion that moves and sits like a loyal hound at Owain's side, calm and noble, golden-eyed; never snarling except in battle; loyalty made visible.",
      serpent:      "The serpent: a large dark coiling snake gripping the lion's tail, the adversary Owain cuts away; shown without gore.",
      cynon:        "Cynon son of Clydno: a young Welsh knight, brown-haired, in russet and green wool, earnest; the teller of the framing tale.",
      cei:          "Cei: Arthur's broad young steward, close-bearded, quick-faced and sharp-tongued, in a steward's good wool over a belted tunic.",
      arthur:       "The emperor Arthur: a mature, dignified king with a slim gold circlet and a deep-red mantle over fine wool; lordly and calm.",
      gwenhwyfar:   "Queen Gwenhwyfar: a fair young Welsh queen in a green-and-gold gown, at needlework with her maids by a window.",
      glewlwyd:     "Glewlwyd Mighty-Grasp: a huge genial doorward in a heavy wool cloak, standing easily at a hall door — a porter who only welcomes.",
      countess:     "The Countess of the Fountain: a beautiful, dignified Welsh noblewoman with auburn hair bound in gold, in a flowing gown of gold-shot crimson silk; grave and self-possessed, a widow and a ruler.",
      luned:        "Luned: a quick, bright-eyed young Welsh maid with dark plaited hair, in a neat blue-grey gown, always thinking a step ahead — the cleverest person in the story.",
      blackknight:  "The Black Knight of the Fountain: a tall imposing knight all in black armour on a black horse, lance couched, the storm at his back; the fountain's defender, never depicted gorily.",
      keeper:       "The keeper of beasts: an enormous black-skinned wild herdsman seated on a forest mound, ONE-eyed and ONE-footed, leaning on a great iron club, with wild deer, boar, serpents and stags gathered and bowing around him; awe-inspiring, a marvel of the Otherworld, not a monster of horror.",
      fountain:     "The magic fountain: a clear spring under a great evergreen tree, rimmed with stone, with a broad flat slab beside it and a silver bowl on a slab-edge chained near the water; uncanny and quiet, the air charged before a storm.",
      storm:        "The fountain's tempest: a sudden violent storm of black cloud, thunder, white lightning and hail breaking over the wood, stripping the leaves from the great tree — cool storm-grey cutting across the earthy palette.",
      ring:         "The ring of invisibility: a plain gold ring with a dark stone; turned stone-inward and the hand closed, its wearer cannot be seen.",
      castle:       "The Lady's castle: a fine stone-and-timber Welsh castle with a gatehouse and a portcullis, set in green hill-country near the wooded fountain; rich but not vast.",
      caerllion:    "Caerleon-on-Usk: Arthur's chief court — a great stone-and-timber Welsh medieval hall with painted shields, carved oak tables, deep arched windows, on the green banks of the river Usk.",
      gwalchmei:    "Gwalchmei son of Gwyar: a fair courteous young knight in green and gold, Arthur's nephew and champion; the same hero as Sir Gawain, in Welsh dress.",
    },
    triggers: [
      [/owain(?! in his madness| son of urien, now| gaunt| ragged)|deep[- ]blue surcoat|knight of the lion/i, "owain"],
      [/owain in his madness|gaunt, ragged|ragged and barefoot|wild and matted|owain'?s madness|living rough/i, "owain_mad"],
      [/\blion\b|tawny lion|loyal (lion|beast)|like a (loyal )?hound/i, "lion"],
      [/serpent|coiling snake|snake gripping/i, "serpent"],
      [/\bcynon\b|son of clydno/i, "cynon"],
      [/\bcei\b|steward.*sharp|sharp[- ]tongued/i, "cei"],
      [/\barthur\b|the emperor|gold circlet|deep[- ]red mantle/i, "arthur"],
      [/gwenhwyfar|queen.*needlework|green[- ]and[- ]gold gown/i, "gwenhwyfar"],
      [/glewlwyd|mighty[- ]grasp|doorward|porter who only welcomes/i, "glewlwyd"],
      [/countess|lady of the fountain|gold[- ]shot crimson|auburn hair bound in gold|the widow/i, "countess"],
      [/\bluned\b|bright[- ]eyed.*maid|dark plaited|blue[- ]grey gown|cleverest/i, "luned"],
      [/black knight|knight of the fountain|all in black armour|black horse/i, "blackknight"],
      [/keeper of beasts|wild herdsman|one[- ]eyed.*one[- ]footed|iron club|beasts (gathered|bow)/i, "keeper"],
      [/\bfountain\b|magic (spring|fountain)|silver bowl|the slab|spring under (a |the )?(great )?tree/i, "fountain"],
      [/tempest|storm of (black )?cloud|thunder.*hail|stripping the leaves|storm[- ]grey/i, "storm"],
      [/ring of invisibility|invisible|gold ring with a dark stone|turn(ed)? (the )?stone[- ]inward/i, "ring"],
      [/the lady'?s castle|gatehouse|portcullis|stone[- ]and[- ]timber.*castle/i, "castle"],
      [/caerleon|caer llion|arthur'?s (chief )?court|banks of the (river )?usk/i, "caerllion"],
      [/gwalchmei|son of gwyar|arthur'?s nephew/i, "gwalchmei"],
    ],
  },

  /* ──────────────────────────── BRANWEN ──────────────────────────── */
  branwen: {
    bookGlobal: "BRANWEN",
    storyFile: "read/branwen/storybook.js",
    imgDir: "read/branwen/img",
    house: [
      "A storybook illustration for an 8–12 readers' faithful retelling of the medieval Welsh tale Branwen ferch Llŷr, the Second Branch of the Mabinogi — a tragedy of a marriage between Britain and Ireland that turns to war: the giant king Bendigeidfran, his sister Branwen wronged in Ireland, the malicious Efnisien, the Cauldron of Rebirth, and the giant's living severed head.",
      "Style: warm gouache-and-watercolour painting in the tradition of Howard Pyle and Edmund Dulac, soft painterly textures; an earthy Welsh sea-coast palette — slate-greys, sea-greens, ambers, peat-browns, with quiet gold accents and a cold note for grief and battle; a mythic, faintly sorrowful grandeur; Welsh medieval / heroic-age atmosphere; cinematic but child-friendly.",
      "Single illustrative scene, full bleed, no panel borders, no text, no captions, no lettering, no logos, no watermarks; Welsh medieval setting, no modern dress or anachronisms; the harshest events handled with folktale tact, never gory.",
    ].join(" "),
    pins: {
      bran:        "Bendigeidfran (Brân the Blessed): an immense, noble bearded giant-king, far larger than ordinary men, with a simple gold crown and a deep-blue mantle bordered with gold over heroic-age Welsh dress; grave, kingly, sorrowful; so vast no house can hold him.",
      branwen:     "Branwen: a beautiful young Welsh woman with long dark hair, in a flowing green gown with a little gold at the throat; gentle and dignified; in her years of grief, the same woman in plain grey wool at a kitchen kneading-trough, sad but never abject — handled with folktale tact.",
      matholwch:   "Matholwch, king of Ireland: a dignified red-haired-and-bearded king in a green mantle with gold trim; outwardly noble but weak-willed, governed by his court.",
      manawydan:   "Manawydan fab Llŷr: a steady, wise dark-haired Welsh nobleman of middle years in russet and grey wool, brother to Brân; calm and trustworthy.",
      efnisien:    "Efnisien: a lean, sharp-faced, dark young Welshman with a sullen, dangerous look, in darker muted clothes; the strife-maker — menace without caricature.",
      nisien:      "Nisien: an open, kind-faced young Welshman in warmer colours, the gentle brother; visibly the opposite of Efnisien.",
      gwern:       "Gwern: a small fair-haired boy of three or four in a little Welsh tunic; bright and innocent. Always depicted gently and never in harm on the page.",
      cauldron:    "The Cauldron of Rebirth (Pair Dadeni): a huge ancient dark bronze cauldron, big enough to put a man in, its rim worked with old spiralling Celtic ornament, standing on a fire; uncanny, charged with cold power.",
      starling:    "A small starling (speckled dark bird) perched, with a tiny folded letter bound under one wing; intimate and hopeful.",
      head:        "The wondrous head of Bendigeidfran: the giant king's noble crowned head, calm and uncorrupted as if only sleeping, set upright among a seated company at a feast — serene and miraculous, never gruesome; soft golden hall-light.",
      harlech:     "The rock of Harlech: a vast grey sea-cliff above a grey-green sea, with a Welsh timber-and-stone royal court behind it; wide cold sea-light.",
      aberffraw:   "Aberffraw: a great open-air feast under huge bright pavilion-tents by the sea (no hall could hold the giant king); long tables, banners, candlelight and daylight.",
      ships:       "Thirteen fine heroic-age ships with bright satin sails and flags crossing a grey-green sea; on the foremost a round shield raised point-upward, the sign of peace.",
      ireland:     "The Irish host / Matholwch's court: heroic-age Irish warriors and nobles in checked and bordered wool cloaks, with bronze-fitted spears and round shields.",
    },
    triggers: [
      [/bendigeidfran|brân the blessed|\bbrân\b|giant[- ]king|giant, bearded|immense.*giant/i, "bran"],
      [/\bbranwen\b|long dark hair.*green gown|kneading[- ]trough|plain grey wool/i, "branwen"],
      [/matholwch|king of ireland(?!'s host)|red[- ]haired.*king/i, "matholwch"],
      [/manawydan/i, "manawydan"],
      [/efnisien|sullen|strife[- ]maker|sharp[- ]faced.*dark/i, "efnisien"],
      [/\bnisien\b|gentle brother|peace[- ]maker/i, "nisien"],
      [/\bgwern\b|small fair[- ]haired boy|a little (welsh )?tunic/i, "gwern"],
      [/cauldron|pair dadeni/i, "cauldron"],
      [/starling|speckled.*bird|letter bound under/i, "starling"],
      [/wondrous head|severed head|the head of (bendigeidfran|brân)|crowned head/i, "head"],
      [/rock of harlech|sea[- ]cliff|harlech/i, "harlech"],
      [/aberffraw|pavilion[- ]tents|open[- ]air feast under (huge )?(bright )?tents|wedding feast under/i, "aberffraw"],
      [/thirteen.*ships|ships with .*satin|shield raised point[- ]up/i, "ships"],
      [/irish host|matholwch'?s court|irish warriors|heroic[- ]age irish/i, "ireland"],
    ],
  },

  /* ──────────────────────────── MANAWYDAN ──────────────────────────── */
  manawydan: {
    bookGlobal: "MANAWYDAN",
    storyFile: "read/manawydan/storybook.js",
    imgDir: "read/manawydan/img",
    house: [
      "A storybook illustration for an 8–12 readers' faithful retelling of the medieval Welsh prose tale Manawydan uab Llŷr, the Third Branch of the Mabinogi — the sequel to Branwen: a tale of an enchanted mist that empties a kingdom to a wasteland, a fort that appears where none was, and the patient, un-warlike wit of Manawydan, who lifts the whole spell with a craftsman's hands, a captured mouse, and a bargain he will not let go.",
      "Style: warm gouache-and-watercolour painting in the tradition of Howard Pyle and Edmund Dulac, soft painterly textures; an earthy Welsh palette — mossy greens, ambers, russets, peat-browns, slate-greys, with quiet gold accents and a cold silver-grey note for the enchanting mist; a mythic but faintly wry, hopeful atmosphere; Welsh medieval setting; cinematic but child-friendly.",
      "Single illustrative scene, full bleed, no panel borders, no text, no captions, no lettering, no logos, no watermarks; Welsh medieval setting, no modern dress or anachronisms; the eerie and the comic kept side by side, handled with folktale tact, never gory.",
    ].join(" "),
    pins: {
      manawydan:    "Manawydan fab Llŷr: a calm, kind, dignified man of middle years, greying dark hair and short beard, in a plain but noble deep-blue mantle over grey-and-russet Welsh wool; the rightful but un-aspiring king of Britain — patient, shrewd, never warlike; the gentlest hero in the Branches.",
      rhiannon:     "Rhiannon: the wise, beautiful Welsh queen of the First Branch, now a woman of middle years, long dark hair touched with grey, in a fine green-and-gold gown; quick-witted, gracious, gifted in talk; once the fairy bride on the white horse, now Manawydan's wife.",
      pryderi:      "Pryderi: a younger, bright, vigorous Welsh warrior-prince in his prime, dark-haired, in a russet-and-green hunting cloak with a gold torc; brave and impulsive, loyal to a fault; lord of Dyfed, Rhiannon's son.",
      cigfa:        "Cigfa: a gentle, fair young Welsh noblewoman in a soft blue-grey gown, Pryderi's wife; quiet, faithful, the fourth of the company.",
      llwyd:        "Llwyd son of Cil Coed (the enchanter): a tall, robed, otherworldly magician with grave features and a long dark robe, carrying a slender magic wand (hudlath); awe-inspiring and proud, not evil; the hidden author of the whole enchantment.",
      bishop:       "Llwyd disguised as a bishop: a grand, richly-vested bishop in red-and-gold robes and mitre, on a fine horse, with a baggage-train of sumpter-horses and attendants behind him; outwardly holy, inwardly the enchanter pleading for the mouse.",
      mouse:        "The mouse: a small, plump brown mouse — heavy and slow because she is with young — held gently in a hand or set by a thread-noose; she is secretly Llwyd's enchanted wife.",
      ladymouse:    "Llwyd's wife restored: a beautiful young woman appearing in a swirl of light as the mouse transforms back, the fairest of women, in a fine pale gown; handled gently and joyfully.",
      boar:         "The white boar: a wild boar of a pure, shining, otherworldly white, rising from a thicket and standing at bay before hounds; a magical lure, uncanny and beautiful, not monstrous.",
      caer:         "The enchanted caer: a great, lofty stone fortress of fresh new-built work, standing where there had never been so much as a stone before; uncanny, too-perfect, charged with illusion.",
      bowl:         "The golden bowl: a beautiful golden vessel resting above a slab of white marble within a marble fountain, hanging from four chains that rise straight up into a misty void with no visible end; a trap baited with gold, eerie and lovely.",
      gorsedd:      "The Gorsedd of Arberth: a low, grass-covered Welsh burial-mound above a small stone-and-timber court, a magic-touched place where marvels happen to whoever sits on it.",
      gallows:      "A tiny gallows: two small forked sticks set upright with a little crossbar between them, just big enough to hang a mouse — built on the green mound, gently absurd and oddly solemn.",
      wheatfield:   "A field of ripe golden wheat at the edge of an empty Welsh landscape; in places the stalks stand stripped bare, every ear cut off and gone, an uncanny harvest reaped in the night.",
      mice:         "A vast host of small brown mice past counting, each carrying a single ear of wheat, pouring across a moonlit stubble field in every direction; comic and uncanny at once.",
      workshop:     "A busy medieval English craftsman's workshop: a cobbler's or saddler's bench with fine leather, tools, and gleaming gilded buckles catching the light; in the background a cluster of sullen, envious townsfolk-craftsmen muttering together.",
      mist:         "The enchanting mist: a thick, uncanny wall of silver-grey fog rolling over the green mound and the land, just beginning to part to reveal an emptied world; a cold mist-light.",
      wasteland:    "The wasteland: a wide, emptied Welsh landscape of abandoned, roofless houses and cold dark hearths, no people, no cattle, no smoke anywhere; eerie and forlorn but not frightening.",
      arberth:      "Arberth court: a warm Welsh medieval feast-hall with a hearth-fire, candle-light, painted shields, carved oak tables and a harp in the corner; rich and homely.",
      restored:     "The land made whole: the once-empty landscape restored and alive again — green tilled fields, grazing cattle, smoking chimneys, houses and people — in a warm golden light of reunion and restoration.",
    },
    triggers: [
      [/manawydan|calm,? (kind|greying)|deep[- ]blue mantle|un[- ]aspiring king|greying dark hair/i, "manawydan"],
      [/\brhiannon\b|wise.*queen|green[- ]and[- ]gold gown|long dark hair touched with grey/i, "rhiannon"],
      [/pryderi|bright young (prince|warrior)|vigorous warrior[- ]prince|russet[- ]and[- ]green hunting/i, "pryderi"],
      [/\bcigfa\b|gentle young (woman|noblewoman)|blue[- ]grey gown/i, "cigfa"],
      [/llwyd|the (magician|enchanter)(?! disguised)|tall robed enchanter|with a wand|hudlath/i, "llwyd"],
      [/bishop|richly[- ](dressed|vested)|mitre|baggage[- ]train|sumpter[- ]horses|episcopal/i, "bishop"],
      [/\bmouse\b|plump (brown )?mouse|small (brown )?mouse|thread[- ]noose/i, "mouse"],
      [/restored to .* young woman|transform(ing|s)? back into a (beautiful )?young woman|fairest of women|swirl of light/i, "ladymouse"],
      [/white boar|shining[- ]?white|pure,? shining white|otherworldly white (wild )?boar/i, "boar"],
      [/\bcaer\b|enchanted (fort|castle)|shining (castle|fort)|great,? (shining |lofty )?(stone )?(fort|castle)|new[- ]built work|fort that was never there|vanishing tower/i, "caer"],
      [/golden bowl|gold(en)? vessel|four chains|chains (rising|that rise) (up |straight )?into|marble fountain/i, "bowl"],
      [/gorsedd|green mound|burial[- ]mound|low,? grass[- ]covered mound/i, "gorsedd"],
      [/tiny gallows|two forked sticks|forked sticks|little (gallows|gibbet)|gallows of two forks/i, "gallows"],
      [/wheat[- ]?field|field of (ripe )?(golden )?wheat|ripe wheat|stripped bare|stalks stand stripped|bare straw/i, "wheatfield"],
      [/host of mice|vast (host|army) of (small )?mice|mice past counting|moonlit (stubble|wheat)|swarm(ing)? .* mice/i, "mice"],
      [/workshop|cobbler'?s bench|saddler'?s bench|gilded buckles|craftsman'?s (bench|workshop)|envious (townsfolk|craftsmen)/i, "workshop"],
      [/\bmist\b|silver[- ]grey (fog|mist)|wall of (thick )?mist|enchanting mist|mist[- ]light/i, "mist"],
      [/wasteland|emptied (world|land|landscape)|abandoned,? roofless|roofless houses|cold (dark )?hearths|empty (welsh )?landscape/i, "wasteland"],
      [/arberth (court|hall)|welcome[- ]?feast|feast[- ]hall|hearth[- ]fire.*harp|harp in (a |the )?corner/i, "arberth"],
      [/land (made|restored) whole|restored and alive|tilled fields|grazing cattle|smoking chimneys|reunion and restoration/i, "restored"],
    ],
  },

  /* ──────────────────────────── MATH ──────────────────────────── */
  math: {
    bookGlobal: "MATH",
    storyFile: "read/math/storybook.js",
    imgDir: "read/math/img",
    house: [
      "A storybook illustration for an 8–12 readers' faithful retelling of the medieval Welsh prose tale Math uab Mathonwy, the Fourth and last Branch of the Mabinogi — a tale of magicians: the wand-king Math and his trickster nephew Gwydion, a war over Otherworld pigs, men turned to wild beasts, a wife conjured out of flowers, and a man who becomes an eagle.",
      "Style: warm gouache-and-watercolour painting in the tradition of Howard Pyle and Edmund Dulac, soft painterly textures; an earthy Welsh palette — mossy greens, ambers, russets, slate-greys — with quiet gold accents and a single enchanted silver gleam for the magic; a mythic, faintly uncanny atmosphere; Welsh medieval setting; cinematic but child-friendly.",
      "Single illustrative scene, full bleed, no panel borders, no text, no captions, no lettering, no logos, no watermarks; Welsh medieval setting, no modern dress or anachronisms; the dark turns handled with folktale tact, never gory.",
    ].join(" "),
    pins: {
      math:        "Math fab Mathonwy: an old, dignified Welsh magician-king with a long white beard, a slim gold circlet and rich dark-blue robes worked with gold, carrying a slender pale magic wand (the hudlath) from which a soft light spills; grave, wise, powerful.",
      gwydion:     "Gwydion fab Dôn: a clever, sharp-eyed magician-bard in his prime, dark shoulder-length hair, a fine grey-and-blue cloak over Welsh wool, sometimes with a small harp or a wand; charming, cunning, quick — the trickster of the tale.",
      gilfaethwy:  "Gilfaethwy fab Dôn: a younger Welsh nobleman, Gwydion's brother, dark-haired, in muted Welsh wool; troubled and lovelorn in the early scenes, uneasy later.",
      goewin:      "Goewin ferch Pebin: a beautiful, dignified young Welsh maiden in a fine gown, Math's foot-holder; gentle and grave.",
      aranrhod:    "Aranrhod ferch Dôn: a proud, cold, strikingly beautiful Welsh noblewoman, dark hair bound with silver, in a silver-grey gown with a little gold; haughty and self-possessed.",
      lleu:        "Lleu Llaw Gyffes: a bright, fair-haired youth growing through the tale from a boy to a noble young warrior-king; deft and quick; later in mail with a sword, and at the end a fair, noble young king crowned with a slim gold circlet.",
      eagle:       "Lleu as a wounded eagle: a great eagle, gaunt, ragged and bedraggled, perched in a high oak, noble even in its suffering; uncanny, never gruesome — no visible wounds, only a worn and weary bird.",
      blodeuwedd:  "Blodeuwedd: a strikingly beautiful young woman conjured from flowers, her pale beauty subtly flower-like, oak-blossom, yellow broom and white meadowsweet woven through her hair and her pale green-and-white gown; otherworldly and lovely.",
      owl:         "Blodeuwedd transformed into an owl: a tawny owl in flight at dusk, alone, shunned and mobbed by small birds; melancholy, not monstrous.",
      gronw:       "Gronw Pebr: a handsome, strong Welsh huntsman-lord in green hunting dress with a hunting horn and spear; lord of Penllyn.",
      pryderi:     "Pryderi fab Pwyll: a noble Welsh king-prince of the South, dark-haired and vigorous, in a russet-and-green hunting cloak with a gold torc.",
      dylan:       "Dylan Eil Ton: a fair-haired child who plunges into the sea and takes its nature, swimming joyfully as a half-creature of the waves; luminous and uncanny.",
      swine:       "The Otherworld swine: fine, strange, uncannily beautiful pigs sent from Annwn — the first pigs in Britain, with a faint Otherworld gleam about them.",
      illusion:    "Gwydion's conjured illusions: twelve magnificent horses with gold-trimmed saddles, twelve black white-breasted greyhounds with golden collars, and twelve gilded shields, all gleaming like gold with a faint unreal shimmer; or, elsewhere, an illusory war-fleet of countless ships filling the sea, faintly shimmering and not quite real.",
      wand:        "The hudlath: a slender pale magic wand in the hand of Math or Gwydion, spilling a soft silver-gold light when it works its magic.",
      flowers:     "The makings of Blodeuwedd: oak-blossom, yellow broom flowers and white meadowsweet, swirling and glowing with gathering magic as they become a woman — petals into hair, leaves into a gown.",
      oak:         "A great ancient oak beside a brook, its high crown holding a roosting eagle; dappled gold-green forest light, a hush of magic.",
      caerdathyl:  "Caer Dathyl: Math's chief court — a great Welsh medieval hall-fortress in the mountains of Arfon, carved oak, painted shields, warm firelight.",
      caeraranrhod:"Caer Aranrhod: Aranrhod's fort by the sea, a Welsh stone-and-timber fortress on the coast, cool sea-light about it.",
      murcastell:  "Mur Castell: Lleu's court, a Welsh upland court in the hills of Ardudwy.",
    },
    triggers: [
      [/\bmath\b|old (white-bearded )?magician-king|wand-king|the old king math|old magician-king/i, "math"],
      [/gwydion|the (clever|cunning) (sharp-eyed )?magician|trickster|grey-and-blue cloak/i, "gwydion"],
      [/gilfaethwy|lovelorn|his brother(?!s)/i, "gilfaethwy"],
      [/goewin|foot-holder/i, "goewin"],
      [/aranrhod|silver-grey gown|silver-wheel|proud,? (cold,? )?(beautiful|striking)/i, "aranrhod"],
      [/\blleu\b|fair-haired (boy|youth|young man|young king)|fair,? noble young king/i, "lleu"],
      [/\beagle\b|ragged,? .* eagle|gaunt,? .* eagle|bedraggled .* eagle/i, "eagle"],
      [/blodeuwedd|flower-face|made (out )?of (oak-?blossom|flowers)|conjured from flowers|flower-like/i, "blodeuwedd"],
      [/\bowl\b|tawny owl/i, "owl"],
      [/gronw|huntsman-lord|green hunting dress/i, "gronw"],
      [/pryderi|king(-prince)? of the south|russet-and-green/i, "pryderi"],
      [/dylan|son of the wave|child .* (into|of) (the )?(sea|water|waves)|creature of the waves/i, "dylan"],
      [/otherworld (swine|pigs)|\bswine\b|strange,? fine .* pigs/i, "swine"],
      [/twelve (splendid |magnificent )?horses|gilded shields|gold(en)? collars|illusory (war-)?fleet|phantom fleet|war-fleet of countless ships|shimmer of illusion/i, "illusion"],
      [/\bwand\b|glowing wand|hudlath/i, "wand"],
      [/oak-?blossom|\bbroom\b|meadowsweet|blossoms? .* (glow|magic)/i, "flowers"],
      [/great (ancient )?oak|oak (tree )?by (a |the )?brook/i, "oak"],
      [/caer dathyl|hall (at|of) caer dathyl/i, "caerdathyl"],
      [/caer aranrhod|sea-fort|sea-gate/i, "caeraranrhod"],
      [/mur castell|upland court/i, "murcastell"],
    ],
  },
};
