/* Skein — the theme packs.

   Each theme has a clue (shown before you start), spans (the theme
   revealed in a word or a run-together phrase: the one that runs pole to
   pole) and a pool of theme words. A board draws its words from the pool
   until the letters exactly fill the sphere, so the pool is deliberately
   bigger than any one board.

   Rules for a pool: four letters or more, letters only, no word inside
   another theme word of the same pack, nothing obscure. The span list runs
   short to long, because the poles are further apart on bigger spheres
   (C80: 7 letters at least, C180: 10, C240: 11). */
(function () {
  "use strict";
  var NS = (typeof window !== "undefined") ? window : globalThis;
  var K = NS.SKEIN = NS.SKEIN || {};

  function T(clue, spans, words) { return { clue: clue, spans: spans.split(" "), words: words.split(" ") }; }

  K.THEMES = [
    T("Night lights", "STARGAZE CONSTELLATIONS",
      "ORION LYRA CYGNUS DRACO PERSEUS ANDROMEDA CASSIOPEIA PEGASUS AQUILA CENTAURUS CEPHEUS HERCULES BOOTES AURIGA GEMINI TAURUS SCORPIUS AQUARIUS PISCES ARIES VIRGO LIBRA HYDRA CARINA VELA LUPUS CORVUS PHOENIX TUCANA LYNX DELPHINUS SAGITTA COLUMBA MONOCEROS"),
    T("In the kitchen drawer", "UTENSILS KITCHENTOOLS",
      "WHISK LADLE SPATULA TONGS GRATER PEELER ZESTER SIEVE COLANDER SKEWER MASHER SCOOP CORKSCREW TIMER FUNNEL BASTER CLEAVER KNIFE SPOON SKILLET SAUCEPAN STRAINER MANDOLINE JUICER OPENER RAMEKIN TRIVET MORTAR PESTLE THERMOMETER"),
    T("Weather report", "FORECAST STORMYWEATHER",
      "THUNDER LIGHTNING DRIZZLE SLEET HAIL SNOW MIST GALE BREEZE MONSOON TORNADO CYCLONE HURRICANE TYPHOON BLIZZARD SQUALL FROST RAINBOW CLOUD HUMIDITY DROUGHT HEATWAVE SUNSHINE SHOWER DOWNPOUR TEMPEST GUST OVERCAST HAZE SMOG FLURRY"),
    T("Beneath the waves", "UNDERSEA SEACREATURES",
      "OCTOPUS SQUID JELLYFISH STARFISH SEAHORSE DOLPHIN WHALE SHARK ORCA MANATEE WALRUS NARWHAL LOBSTER CRAB SHRIMP OYSTER CLAM MUSSEL URCHIN ANEMONE CORAL MORAY MARLIN TUNA SARDINE ANCHOVY BARRACUDA STINGRAY SEAL OTTER PENGUIN KRILL PLANKTON NAUTILUS CUTTLEFISH LAMPREY GROUPER HALIBUT"),
    T("Orchestra pit", "ENSEMBLE INSTRUMENTS",
      "VIOLIN VIOLA CELLO HARP FLUTE PICCOLO OBOE CLARINET BASSOON TRUMPET TROMBONE TUBA TIMPANI CYMBAL TRIANGLE XYLOPHONE GLOCKENSPIEL CELESTA PIANO ORGAN SAXOPHONE CORNET BUGLE GONG SNARE MARIMBA TAMBOURINE CASTANETS HARPSICHORD BANJO GUITAR UKULELE ACCORDION HARMONICA BAGPIPES LUTE SITAR ZITHER"),
    T("Green fingers", "BLOSSOMS GARDENFLOWERS",
      "ROSE TULIP DAISY LILY IRIS ORCHID POPPY PEONY DAHLIA ASTER LILAC VIOLET PANSY MARIGOLD SUNFLOWER LAVENDER JASMINE MAGNOLIA CARNATION BEGONIA PETUNIA DAFFODIL HYACINTH CROCUS ZINNIA GERANIUM FOXGLOVE BLUEBELL SNOWDROP PRIMROSE CAMELLIA AZALEA GARDENIA HIBISCUS LOTUS LUPIN PHLOX"),
    T("Spice rack", "SEASONING HERBSANDSPICES",
      "BASIL THYME OREGANO ROSEMARY SAGE PARSLEY CILANTRO DILL MINT TARRAGON CHIVES CUMIN PAPRIKA TURMERIC NUTMEG CINNAMON CLOVE GINGER SAFFRON CARDAMOM PEPPER CHILI FENNEL ANISE MACE VANILLA SUMAC ALLSPICE MARJORAM CARAWAY MUSTARD LOVAGE"),
    T("Rock collection", "GEMSTONES PRECIOUSSTONES",
      "DIAMOND RUBY EMERALD SAPPHIRE OPAL PEARL TOPAZ GARNET AMETHYST JADE ONYX TURQUOISE AMBER JASPER AGATE QUARTZ PERIDOT CITRINE TOURMALINE ZIRCON SPINEL BERYL AQUAMARINE MOONSTONE OBSIDIAN LAPIS MALACHITE TANZANITE CARNELIAN"),
    T("Pasta la vista", "NOODLES PASTASHAPES",
      "SPAGHETTI PENNE FUSILLI RIGATONI FARFALLE LINGUINE FETTUCCINE MACARONI LASAGNA RAVIOLI TORTELLINI ORZO GNOCCHI ROTINI ZITI ORECCHIETTE CAVATAPPI BUCATINI TAGLIATELLE PAPPARDELLE CANNELLONI MANICOTTI VERMICELLI DITALINI GEMELLI CAMPANELLE"),
    T("Shape up", "GEOMETRY GEOMETRYCLASS",
      "CIRCLE SQUARE TRIANGLE PENTAGON HEXAGON OCTAGON RHOMBUS OVAL ELLIPSE SPHERE CUBE CONE CYLINDER PYRAMID PRISM TRAPEZOID KITE STAR CRESCENT TORUS HELIX SPIRAL DECAGON HEPTAGON NONAGON TETRAHEDRON OCTAHEDRON ICOSAHEDRON"),
    T("Say cheese", "FROMAGE CHEESEBOARD",
      "CHEDDAR BRIE CAMEMBERT GOUDA EDAM FETA HALLOUMI MOZZARELLA PARMESAN ROQUEFORT STILTON GORGONZOLA RICOTTA MASCARPONE EMMENTAL GRUYERE MANCHEGO PECORINO PROVOLONE HAVARTI MUENSTER COLBY PANEER BURRATA ASIAGO FONTINA TALEGGIO WENSLEYDALE LIMBURGER RACLETTE COTIJA"),
    T("Fruit bowl", "HARVEST FRUITSALAD TUTTIFRUTTI",
      "APPLE BANANA CHERRY GRAPE LEMON LIME MANGO PAPAYA PEACH PEAR PLUM APRICOT KIWI MELON ORANGE GUAVA LYCHEE DATE QUINCE PINEAPPLE COCONUT POMEGRANATE TANGERINE CLEMENTINE RASPBERRY BLUEBERRY CRANBERRY NECTARINE PERSIMMON KUMQUAT DURIAN RAMBUTAN WATERMELON"),
    T("Up in the air", "BIRDSONG BIRDWATCHING",
      "ROBIN SPARROW FINCH WREN CROW RAVEN MAGPIE EAGLE HAWK FALCON HERON CRANE STORK PELICAN FLAMINGO PARROT TOUCAN OSTRICH SWALLOW SWIFT STARLING THRUSH CARDINAL ORIOLE WARBLER PIGEON DOVE GULL PUFFIN KINGFISHER WOODPECKER HUMMINGBIRD NIGHTINGALE LARK CUCKOO PHEASANT PEACOCK VULTURE CONDOR OSPREY ALBATROSS"),
    T("Ballroom", "DANCING DANCEFLOOR SHALLWEDANCE",
      "WALTZ TANGO SALSA RUMBA SAMBA FOXTROT QUICKSTEP MAMBO POLKA JIVE SWING BALLET DISCO BOLERO FLAMENCO LAMBADA CHARLESTON MINUET JITTERBUG MERENGUE BACHATA HULA TWIST LIMBO CONGA BOOGIE CANCAN FANDANGO POLONAISE MAZURKA GAVOTTE REEL"),
    T("Workbench", "HARDWARE WORKSHOPTOOLS",
      "HAMMER WRENCH PLIERS CHISEL DRILL LEVEL CLAMP VISE SCREWDRIVER MALLET FILE RASP SANDER ROUTER LATHE ANVIL CROWBAR HACKSAW JIGSAW RULER PLANE SOCKET RATCHET SPANNER TROWEL SHOVEL SPADE RAKE PICKAXE HATCHET SCYTHE SICKLE STAPLER"),
    T("Out of this world", "PLANETS SOLARSYSTEM",
      "MERCURY VENUS EARTH MARS JUPITER SATURN URANUS NEPTUNE PLUTO CERES MOON COMET ASTEROID METEOR TITAN EUROPA GANYMEDE CALLISTO PHOBOS DEIMOS TRITON CHARON ENCELADUS ERIS ORBIT ECLIPSE GALAXY NEBULA PULSAR QUASAR"),
    T("Good boys", "TOPDOGS LEADERSOFTHEPACK",
      "BEAGLE POODLE BOXER CORGI HUSKY COLLIE DACHSHUND TERRIER SPANIEL RETRIEVER LABRADOR SHEPHERD BULLDOG GREYHOUND WHIPPET CHIHUAHUA MASTIFF ROTTWEILER DOBERMAN DALMATIAN PEKINGESE SAMOYED MALAMUTE AKITA SHIBA BASSET BLOODHOUND POINTER SETTER SCHNAUZER POMERANIAN MALTESE PAPILLON WEIMARANER VIZSLA SALUKI BORZOI"),
    T("Elementary", "ELEMENTS PERIODICTABLE",
      "HYDROGEN HELIUM LITHIUM CARBON NITROGEN OXYGEN NEON SODIUM MAGNESIUM ALUMINUM SILICON SULFUR CHLORINE ARGON CALCIUM IRON COPPER ZINC SILVER GOLD LEAD PLATINUM URANIUM NICKEL COBALT TITANIUM CHROMIUM IODINE RADON XENON KRYPTON BORON FLUORINE POTASSIUM TUNGSTEN RADIUM BISMUTH"),
    T("Make yourself at home", "FURNITURE FURNISHINGS",
      "SOFA COUCH CHAIR TABLE DESK STOOL BENCH OTTOMAN DRESSER WARDROBE CABINET BOOKCASE BUNK CRIB CRADLE FUTON RECLINER ARMCHAIR SETTEE DIVAN CHAISE HAMMOCK CREDENZA BUFFET HUTCH ARMOIRE BUREAU VANITY NIGHTSTAND SIDEBOARD MIRROR LAMP CHANDELIER BEANBAG ROCKER"),
    T("Here be dragons", "MONSTERS MYTHICALBEASTS",
      "DRAGON UNICORN GRIFFIN PHOENIX KRAKEN HYDRA MINOTAUR CENTAUR PEGASUS SPHINX MEDUSA CYCLOPS BASILISK CHIMERA MANTICORE WEREWOLF VAMPIRE ZOMBIE GOBLIN TROLL OGRE DWARF GNOME FAIRY PIXIE BANSHEE YETI SASQUATCH MERMAID SIREN HARPY GOLEM WYVERN LEVIATHAN BEHEMOTH KELPIE GARGOYLE LEPRECHAUN"),
    T("Rise and shine", "BAKEHOUSE BAKERYCOUNTER",
      "BAGEL BAGUETTE BRIOCHE CROISSANT CIABATTA FOCACCIA PITA NAAN SOURDOUGH PUMPERNICKEL CHALLAH MUFFIN SCONE BISCUIT PRETZEL DONUT ROLL CRUMPET TORTILLA CHAPATI MATZO PANETTONE STOLLEN DANISH ECLAIR STRUDEL MACARON BROWNIE COOKIE CUPCAKE TART BABKA CORNBREAD"),
    T("Capital idea", "CAPITALS EUROPEANCAPITALS",
      "PARIS LONDON BERLIN MADRID ROME LISBON DUBLIN VIENNA PRAGUE WARSAW BUDAPEST ATHENS OSLO STOCKHOLM HELSINKI COPENHAGEN AMSTERDAM BRUSSELS BERN RIGA TALLINN VILNIUS KYIV MINSK SOFIA BUCHAREST BELGRADE ZAGREB SARAJEVO TIRANA VALLETTA REYKJAVIK MONACO ANDORRA SKOPJE BRATISLAVA LJUBLJANA NICOSIA"),
    T("Colour me in", "PAINTBOX COLORPALETTE",
      "CRIMSON SCARLET MAROON CORAL SALMON AMBER OCHRE MUSTARD LEMON OLIVE EMERALD JADE TEAL TURQUOISE CYAN AZURE COBALT NAVY INDIGO VIOLET LILAC MAUVE MAGENTA FUCHSIA PLUM BURGUNDY BEIGE TAUPE IVORY SEPIA UMBER SIENNA CHARCOAL SLATE KHAKI CERULEAN VERMILION CHARTREUSE"),
    T("Best foot forward", "FOOTWEAR STEPPINGOUT",
      "BOOT SANDAL SNEAKER LOAFER SLIPPER MOCCASIN CLOG MULE PUMP STILETTO WEDGE ESPADRILLE OXFORD BROGUE DERBY GALOSH WELLINGTON WADERS CLEAT TRAINER PLIMSOLL PLATFORM BOOTIE CHUKKA GETA ZORI HUARACHE SABOT")
  ];
})();
