/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_canvasrenderer_free: (a: number, b: number) => void;
export const canvasrenderer_applyFormat: (a: number, b: number, c: number, d: number, e: number) => void;
export const canvasrenderer_getContentHeight: (a: number) => number;
export const canvasrenderer_getMarkdown: (a: number, b: number) => void;
export const canvasrenderer_getScroll: (a: number) => number;
export const canvasrenderer_getSelectedText: (a: number, b: number) => void;
export const canvasrenderer_handleClick: (a: number, b: number, c: number, d: number) => void;
export const canvasrenderer_handleInput: (a: number, b: number, c: number) => void;
export const canvasrenderer_handleKeyDown: (a: number, b: number, c: number, d: number, e: number) => number;
export const canvasrenderer_hitTest: (a: number, b: number, c: number, d: number) => void;
export const canvasrenderer_isEditing: (a: number) => number;
export const canvasrenderer_new: (a: number, b: number) => void;
export const canvasrenderer_paint: (a: number) => void;
export const canvasrenderer_render: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const canvasrenderer_resize: (a: number, b: number, c: number) => void;
export const canvasrenderer_setScroll: (a: number, b: number) => void;
export const canvasrenderer_startEditing: (a: number, b: number, c: number) => void;
export const canvasrenderer_stopEditing: (a: number, b: number) => void;
export const canvasrenderer_toggleBlink: (a: number) => void;
export const expandTemplate: (a: number, b: number, c: number, d: number, e: number) => void;
export const parseWikilinks: (a: number, b: number, c: number) => void;
export const renderMarkdown: (a: number, b: number, c: number, d: number, e: number) => void;
export const __wbindgen_export: (a: number) => void;
export const __wbindgen_export2: (a: number, b: number) => number;
export const __wbindgen_export3: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
