// gen-slots.mjs — regenerate nave/SLOTS.md (the content-slot manifest hoopy authors pools against) and
// nave/slots.json (the machine-readable profile). Deterministic: node hoop/nave/gen-slots.mjs
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { slotProfile, naveManifest, featureKey } from './manifest.js';
import { FACTIONS, BIOMES } from './nave.js';

const here = dirname(fileURLToPath(import.meta.url));
const p = slotProfile({ seeds: 16 });
const sample = naveManifest(7);

const pad = (s, n) => String(s).padEnd(n);
const tierBand = (t) => (t === 1 ? 'early (rev/pow 1)' : t === 2 ? 'mid (rev/pow 2)' : 'late (rev/pow 3)');

let md = `# nave — content-slot manifest (floor 1)

> Generated by \`node hoop/nave/gen-slots.mjs\` from \`manifest.js\`. The distribution engine already exists
> (\`v099/story/engine.js\`): a room is anonymous geometry until first touch, then \`interact()\` deals ONE
> tier-legal, gate-passing pool item onto its stable **feature_key** and freezes it forever. This doc is the
> list of SLOTS that engine fills on the nave — **author pools against it.** Floor 1 is no-baddies, so there
> are **no creature pools** here.

## How a slot works

Every **room is a feature**. On first touch the dispatcher (\`dispatch(store, player, type)\`) picks unseen,
tier-legal content whose tags match the room's **role**, varied by tag, and binds it to the room's
\`feature_key\` (\`${featureKey('<chunk>', '<room>')}\` — chunk + room ordinal, deterministic per world seed).

- **role** → the dispatcher **tag** to author content for (worship, mend, trade, …).
- **faction** → a flavour tag (rindwalker / continuant / drift); commons content is faction-neutral.
- **tier** → the role's central-place rank ⇒ the band to author at: ${tierBand(1)}, ${tierBand(2)}, ${tierBand(3)}.
- **content types** → which pools a room of that role draws (\`npc\` always; \`item\`/\`lore_fragment\` per role).
- **★ anchor** → the lobe's exclusive building — the natural quest-giver / principal seat (also a \`plot_beat\`).

## Guaranteed every world (the role floors)

- **Commons** (the hub): **≥ 1 of every one of the ${p.guaranteed.commons.length} building types** — so each exclusive still appears here.
`;
for (const [fk, f] of Object.entries(p.guaranteed.factions)) {
  md += `- **${FACTIONS[fk].label}** lobe — over-biases \`${f.shared.join(' ')}\`; its two wards each guarantee \`dwell\` + \`${f.shared.join(' ')}\` + their exclusive: `;
  md += f.wards.map((w) => `**${w.exclusive}** (${w.level})`).join(' and ') + `.\n`;
}

md += `\n## Pool requirements — the authoring checklist

One row per role tag. **avg slots/world** is the mean over 16 seeds across the whole nave (commons + lobes) —
author at least that much UNSEEN variety so the draw pool doesn't deplete in one world. ${p.noCreatures ? 'No creatures on floor 1.' : ''}

| tag | tier | band | factions | avg slots/world | content types | anchor |
|---|---|---|---|---|---|---|
`;
for (const pl of p.pools) {
  md += `| ${pl.glyph} \`${pl.tag}\` | ${pl.tier} | ${tierBand(pl.tier).split(' ')[0]} | ${pl.factions.join(', ')} | ${pl.avgSlotsPerWorld} | ${pl.contentTypes.join(', ')} | ${pl.anchor ? '★' : ''} |\n`;
}

md += `\n## The six lobe anchors (quest hooks)

The exclusive building in each ward is the lobe's anchor — the obvious home for that lobe's principal /
quest-giver and a \`plot_beat\`. They map cleanly to the four-quest spine (unlock each lobe + descend to rind):

`;
for (const b of BIOMES) md += `- **${FACTIONS[b.faction].label} · ${b.exclusive}** (${b.level} ward) — \`feature_key\` tag \`${b.exclusive}\` + \`plot_beat\`.\n`;

md += `\n## Sample world (seed 7)

${sample.totalRooms} feature slots across ${sample.chunks.length} chunks. Example keys (the engine binds content to these):

`;
for (const ch of sample.chunks) {
  const ex = ch.rooms.find((r) => r.exclusive);
  md += `- **${ch.label}** — ${ch.rooms.length} slots${ex ? `, anchor \`${ex.key}\` (${ex.role})` : ''}\n`;
}

md += `\n---
*Regenerate with \`node hoop/nave/gen-slots.mjs\`. Machine-readable profile in \`slots.json\`.*\n`;

writeFileSync(join(here, 'SLOTS.md'), md);
writeFileSync(join(here, 'slots.json'), JSON.stringify({ profile: p, sample }, null, 2));
console.log('wrote nave/SLOTS.md + nave/slots.json ·', p.pools.length, 'role tags ·', sample.totalRooms, 'sample slots');
