// hexagrams.js — VENDORED from clock/yijing/index.html (the inline `const HEX` King Wen table).
// Re-sync from there, never fork (the vendor/auth.js rule). HEX[1..64] = {ch,py,en,b,j};
// b = 6-char binary (bottom line = index 0); j = one-line judgment gloss. Indexed by King Wen number.
export const HEX = [
 null,
 {ch:'乾',py:'Qián',en:'The Creative',b:'111111',j:'Sublime success through tireless, upright action — the dragon-power of pure heaven. Persevere.'},
 {ch:'坤',py:'Kūn',en:'The Receptive',b:'000000',j:'Yielding devotion brings success. Follow, do not lead; find friends in the west and south, and rest.'},
 {ch:'屯',py:'Zhūn',en:'Difficulty at the Beginning',b:'100010',j:'Sprouting through hard ground. Do not advance alone — gather helpers before you set out.'},
 {ch:'蒙',py:'Méng',en:'Youthful Folly',b:'010001',j:'The spring at the mountain’s foot. The fool seeks the sage; answer the first sincere asking only.'},
 {ch:'需',py:'Xū',en:'Waiting',b:'111010',j:'Clouds rise but do not yet rain. Wait in strength and good cheer; nourishment comes to those who endure.'},
 {ch:'訟',py:'Sòng',en:'Conflict',b:'010111',j:'Sincere but obstructed. Halt halfway; seek the great mediator rather than press the quarrel to its bitter end.'},
 {ch:'師',py:'Shī',en:'The Army',b:'010000',j:'The multitude moved by one tried leader. Discipline and a just cause carry the day.'},
 {ch:'比',py:'Bǐ',en:'Holding Together',b:'000010',j:'Union around a center. Come quickly while the bond is fresh; the latecomer meets misfortune.'},
 {ch:'小畜',py:'Xiǎo Chù',en:'Small Taming',b:'111011',j:'Dense clouds, no rain yet. A small force restrains the great — refine your influence and wait.'},
 {ch:'履',py:'Lǚ',en:'Treading',b:'110111',j:'Treading on the tiger’s tail. Conduct yourself with care and it will not bite.'},
 {ch:'泰',py:'Tài',en:'Peace',b:'111000',j:'Heaven and earth unite. The small departs, the great arrives — a flowering season of harmony.'},
 {ch:'否',py:'Pǐ',en:'Standstill',b:'000111',j:'Heaven and earth draw apart. The petty wax, the worthy withdraw; hold your principles in private.'},
 {ch:'同人',py:'Tóng Rén',en:'Fellowship',b:'101111',j:'Companions in the open field. Bind people by shared purpose, never by faction.'},
 {ch:'大有',py:'Dà Yǒu',en:'Great Possession',b:'111101',j:'Fire high in heaven. Great wealth held with modesty — curb evil, foster good.'},
 {ch:'謙',py:'Qiān',en:'Modesty',b:'001000',j:'A mountain hidden within the earth. The modest carry things to completion; all is leveled in grace.'},
 {ch:'豫',py:'Yù',en:'Enthusiasm',b:'000100',j:'Thunder bursts from the earth. Move the many by shared delight; set your forces marching.'},
 {ch:'隨',py:'Suí',en:'Following',b:'100110',j:'Thunder asleep within the lake. To lead, first learn to follow; adapt to the hour.'},
 {ch:'蠱',py:'Gǔ',en:'Work on the Decayed',b:'011001',j:'What has spoiled through neglect. Repair the past with care — three days before, three days after.'},
 {ch:'臨',py:'Lín',en:'Approach',b:'110000',j:'The great approaches. Spring favors you now, but the eighth month brings misfortune — act while it lasts.'},
 {ch:'觀',py:'Guān',en:'Contemplation',b:'000011',j:'Wind moves over the earth. The ablution made, the offering not yet brought; observe with reverence, and be observed.'},
 {ch:'噬嗑',py:'Shì Kè',en:'Biting Through',b:'100101',j:'Jaws closing on the obstacle. Bite through the matter firmly; let justice be exact.'},
 {ch:'賁',py:'Bì',en:'Grace',b:'101001',j:'Fire beneath the mountain. Beauty brings small success — let elegance serve substance, not replace it.'},
 {ch:'剝',py:'Bō',en:'Splitting Apart',b:'000001',j:'The mountain rests on eroded earth. It does not further to go anywhere; lie low until the dark spends itself.'},
 {ch:'復',py:'Fù',en:'Return',b:'100000',j:'Thunder within the earth — the turning point. The light returns; friends come without blame.'},
 {ch:'無妄',py:'Wú Wàng',en:'Innocence',b:'100111',j:'The unexpected, under heaven. Act from a pure motive and succeed; scheme and you stumble.'},
 {ch:'大畜',py:'Dà Chù',en:'Great Taming',b:'111001',j:'Heaven within the mountain. Great force held in check stores power — it furthers to cross the great water.'},
 {ch:'頤',py:'Yí',en:'Nourishment',b:'100001',j:'The open mouth. Watch what you feed yourself and others; seek the right nourishment.'},
 {ch:'大過',py:'Dà Guò',en:'Preponderance of the Great',b:'011110',j:'The ridgepole sags under weight. A critical, passing time — act, even alone, and find a way through.'},
 {ch:'坎',py:'Kǎn',en:'The Abyss',b:'010010',j:'Water pouring into the chasm, doubled. Danger upon danger; keep the heart sincere and win through.'},
 {ch:'離',py:'Lí',en:'The Clinging',b:'101101',j:'Fire clinging to its fuel. Care for what sustains you; cling to what is right and brightness endures.'},
 {ch:'咸',py:'Xián',en:'Influence',b:'001110',j:'A lake upon the mountain. Mutual attraction, gentle and constant — the wooing of the open-hearted.'},
 {ch:'恆',py:'Héng',en:'Duration',b:'011100',j:'Thunder and wind, enduring. Stay the course; what lasts is constancy in motion, not standing still.'},
 {ch:'遯',py:'Dùn',en:'Retreat',b:'001111',j:'The mountain under heaven. The small advances — withdraw in good time, with dignity, not in panic.'},
 {ch:'大壯',py:'Dà Zhuàng',en:'Great Power',b:'111100',j:'Thunder in heaven. Use great strength only joined to what is right, or it gores like a ram in a hedge.'},
 {ch:'晉',py:'Jìn',en:'Progress',b:'000101',j:'The sun rising over the earth. Steady advance and honor; the able one is received and rewarded.'},
 {ch:'明夷',py:'Míng Yí',en:'Darkening of the Light',b:'101000',j:'The sun sunk into the earth. In adversity, veil your brightness; persevere inwardly through the dark.'},
 {ch:'家人',py:'Jiā Rén',en:'The Family',b:'101011',j:'Wind issuing from fire. Each in their proper place — order at the hearth orders the world.'},
 {ch:'睽',py:'Kuí',en:'Opposition',b:'110101',j:'Fire above, lake below, parting ways. In small things, fortune; bridge estrangement with patience.'},
 {ch:'蹇',py:'Jiǎn',en:'Obstruction',b:'001010',j:'Water on the mountain — the hard road. Do not press forward; turn inward and seek the great helper.'},
 {ch:'解',py:'Xiè',en:'Deliverance',b:'010100',j:'Thunder and rain loosing the tension. The knot unties; return to the ordinary, then act swiftly on the rest.'},
 {ch:'損',py:'Sǔn',en:'Decrease',b:'110001',j:'Decrease below to increase above. Sincerity makes even a small offering enough.'},
 {ch:'益',py:'Yì',en:'Increase',b:'100011',j:'Wind and thunder strengthening each other. A time of giving from above — undertake great things.'},
 {ch:'夬',py:'Guài',en:'Breakthrough',b:'111110',j:'The lake risen to heaven. Resolutely expose the wrong — not by arms but by clear, public truth.'},
 {ch:'姤',py:'Gòu',en:'Coming to Meet',b:'011111',j:'Wind under heaven. The dark returns unbidden; do not embrace the bold intruder.'},
 {ch:'萃',py:'Cuì',en:'Gathering Together',b:'000110',j:'The lake upon the earth. The many assemble — bring a great offering and meet the great person.'},
 {ch:'升',py:'Shēng',en:'Pushing Upward',b:'011000',j:'Wood growing within the earth. Effortful, gradual ascent; press upward, and seek the one who can advance you.'},
 {ch:'困',py:'Kùn',en:'Oppression',b:'010110',j:'The lake drained dry. Exhaustion and constraint; the great endure without losing faith — say little, do much.'},
 {ch:'井',py:'Jǐng',en:'The Well',b:'011010',j:'Water drawn up through wood. The town may move, the well does not — tend the source that nourishes all.'},
 {ch:'革',py:'Gé',en:'Revolution',b:'101110',j:'Fire within the lake — the molting. Change only when the time is ripe; then people will trust it.'},
 {ch:'鼎',py:'Dǐng',en:'The Cauldron',b:'011101',j:'Fire over wood — the sacred vessel. Nourishment refined into culture; supreme good fortune.'},
 {ch:'震',py:'Zhèn',en:'The Arousing',b:'100100',j:'Thunder repeated. Terror that gives way to laughter; the sage is shaken but never drops the sacred spoon.'},
 {ch:'艮',py:'Gèn',en:'Keeping Still',b:'001001',j:'Mountain upon mountain. Stillness in the back, beyond the self; act when it is time, rest when it is time.'},
 {ch:'漸',py:'Jiàn',en:'Development',b:'001011',j:'A tree on the mountain, growing slowly. Gradual progress, measured as a marriage; patience perfects.'},
 {ch:'歸妹',py:'Guī Mèi',en:'The Marrying Maiden',b:'110100',j:'Thunder over the lake. A subordinate union — understand its transience; to go on blindly brings misfortune.'},
 {ch:'豐',py:'Fēng',en:'Abundance',b:'101100',j:'Thunder and lightning together — the zenith. Be the sun at noon; enjoy the fullness, knowing it must wane.'},
 {ch:'旅',py:'Lǚ',en:'The Wanderer',b:'001101',j:'Fire on the mountain, passing on. The stranger keeps small and correct; reserve and caution are your shelter.'},
 {ch:'巽',py:'Xùn',en:'The Gentle',b:'011011',j:'Wind following wind. Penetrate by gentle persistence; it furthers to have a goal and to see the great person.'},
 {ch:'兌',py:'Duì',en:'The Joyous',b:'110110',j:'Lake resting on lake. Joy that is true and steadfast; gladness shared persuades people to the hardest tasks.'},
 {ch:'渙',py:'Huàn',en:'Dispersion',b:'010011',j:'Wind over water, scattering. Dissolve the heart’s hardness; the king draws near his temple to reunite the dispersed.'},
 {ch:'節',py:'Jié',en:'Limitation',b:'110010',j:'Water held within the lake. Set measured limits — but galling limits cannot last, so temper the rule.'},
 {ch:'中孚',py:'Zhōng Fú',en:'Inner Truth',b:'110011',j:'Wind over the lake. Sincerity that moves even pigs and fishes; with truth at the center, cross the great water.'},
 {ch:'小過',py:'Xiǎo Guò',en:'Small Exceeding',b:'001100',j:'Thunder on the mountain. Exceed in small things, not great; the bird should fly low, not high.'},
 {ch:'既濟',py:'Jì Jì',en:'After Completion',b:'101010',j:'Water over fire, in perfect order. Success in the small; the work is done — now guard against the disorder that follows.'},
 {ch:'未濟',py:'Wèi Jì',en:'Before Completion',b:'010101',j:'Fire over water, not yet ordered. The crossing nearly made — the little fox wets its tail at the end. Care, to the last step.'},
];
