// the quarter — data for the walkable map of the Bluesky tools.
// One entry per tool. district = functional catalogue, tier = complexity
// progression (the road east climbs it):
//   1 lone page      — a single static page, no backend, no heavy libs
//   2 heavy client   — static, but serious client machinery (canvas, WASM, DuckDB, embeddings)
//   3 worker-backed  — a Cloudflare Worker with state or inference behind it (D1 / AI / cron / secrets)
//   4 citadel-grade  — monorepo, Durable Objects, cryptographic protocol
// status comes from the live audit (docs/SOCIAL-STACK-AUDIT.md); CHECKED is its date.

export const CHECKED = '2026-07-01';

export const TIER_NAMES = ['lone page', 'heavy client', 'worker-backed', 'citadel-grade'];

// rect = [x, y, w, h] in tiles on the 78×52 world grid.
export const DISTRICTS = [
  { id: 'commons',     name: 'analysis commons', accent: '#8fb0d8', rect: [5, 6, 20, 8],
    blurb: 'point a handle, get insight — read-only lenses on a profile' },
  { id: 'graph',       name: 'graph quarter',    accent: '#6fd0a0', rect: [5, 31, 20, 8],
    blurb: 'the follow graph as terrain — communities, circles, discovery' },
  { id: 'threads',     name: 'thread alley',     accent: '#cfd8d0', rect: [28, 5, 13, 6],
    blurb: 'conversation trees, rendered (and one you can play)' },
  { id: 'scriptorium', name: 'scriptorium',      accent: '#d8b85a', rect: [28, 17, 18, 8],
    blurb: 'the rite family — prose pulled from a repo CAR, studied' },
  { id: 'gallery',     name: 'gallery row',      accent: '#9a8fe0', rect: [28, 31, 14, 6],
    blurb: 'every image a handle posted, through different lenses' },
  { id: 'watch',       name: 'the watch',        accent: '#e0884a', rect: [45, 31, 12, 6],
    blurb: 'block intelligence — who blocks whom, off public records' },
  { id: 'citadel',     name: 'the citadel',      accent: '#e0d24a', rect: [50, 10, 22, 9],
    blurb: 'the writers — apps that put records on your PDS' },
  { id: 'hamlet',      name: 'the hamlet',       accent: '#d88fb0', rect: [60, 31, 12, 8],
    blurb: 'your own data, on your own PDS — personal apps riding the protocol' },
  { id: 'undercroft',  name: 'the undercroft',   accent: '#7fd8d0', rect: [8, 45, 62, 5],
    blurb: 'plumbing — the shared workers, libraries and pipelines underneath' },
];

const GH = 'https://github.com/minormobius/agent01/tree/main/';

export const TOOLS = [
  // ── analysis commons ────────────────────────────────────────────────────
  { id: 'empathy', name: 'empathy', glyph: '◉', district: 'commons', tier: 2, status: 'up',
    url: 'https://empath.mino.mobi',
    desc: 'See Bluesky as anyone sees it — a handle’s reconstructed timeline, network, and blocks.',
    chips: ['reads appview'], data: 'public AppView' },
  { id: 'judge', name: 'judge', glyph: '⚖', district: 'commons', tier: 2, status: 'up',
    url: 'https://mino.mobi/judge/',
    desc: 'Posting profile — personality traits and valence from post embeddings, topics via k-means.',
    chips: ['embeddings', 'client-side'], data: 'public AppView' },
  { id: 'novelty', name: 'novelty', glyph: '✦', district: 'commons', tier: 2, status: 'up',
    url: 'https://mino.mobi/novelty/',
    desc: 'Semantic novelty trajectory — how an account’s posting drifts or repeats over time.',
    chips: ['embeddings'], data: 'public AppView' },
  { id: 'ternary', name: 'ternary', glyph: '△', district: 'commons', tier: 1, status: 'up',
    url: 'https://mino.mobi/ternary/',
    desc: 'Three lusts, one chart — a ternary plot of posting temperament: flesh, knowledge, argument.',
    chips: ['client-side'], data: 'public AppView' },
  { id: 'echo', name: 'echo', glyph: '≋', district: 'commons', tier: 1, status: 'up',
    url: 'https://mino.mobi/echo/',
    desc: 'Post density head to head — two handles side by side on volume and patterns.',
    chips: ['client-side'], data: 'public AppView' },
  { id: 'density', name: 'density', glyph: '▤', district: 'commons', tier: 1, status: 'up',
    url: 'https://mino.mobi/density/',
    desc: 'Post brevity, measured — filter posts by exact word count, ranked by character length.',
    chips: ['client-side'], data: 'public AppView' },
  { id: 'wild', name: 'wild', glyph: 'ϟ', district: 'commons', tier: 2, status: 'up',
    url: 'https://mino.mobi/wild/',
    desc: 'Group novelty — semantic novelty across a whole list against the group centroid.',
    chips: ['embeddings', 'lists'], data: 'public AppView' },
  { id: 'spark', name: 'spark', glyph: '✧', district: 'commons', tier: 2, status: 'up',
    url: '/spark/',
    desc: 'What they liked before they followed — every pre-follow like, a hint at what won them over. Seeks the PDS cursor by synthesized TID.',
    chips: ['raw PDS reads'], data: 'PDS listRecords + AppView' },
  { id: 'dyad', name: 'dyad', glyph: '⇄', district: 'commons', tier: 2, status: 'up',
    url: '/dyad/',
    desc: 'A dyadline — every recorded interaction between two accounts, both directions, on one timeline.',
    chips: ['raw PDS reads'], data: '12 parallel repo scans + AppView' },
  { id: 'unique', name: 'unique', glyph: '❋', district: 'commons', tier: 3, status: 'up',
    url: '/unique/',
    desc: 'Phrases only they’ve ever posted — bigrams/trigrams a handle used exactly once that nobody else on Bluesky has. Free once-used pre-filter, then a streamed parallel search fan-out.',
    chips: ['worker fan-out', 'service token', 'NDJSON stream'], data: 'PDS listRecords + authed searchPosts' },

  // ── graph quarter ───────────────────────────────────────────────────────
  { id: 'zoom', name: 'zoom', glyph: '◎', district: 'graph', tier: 2, status: 'up',
    url: 'https://zoom.mino.mobi',
    desc: 'SimCluster community viewer — infinite-canvas map of feed communities, hex-packed avatars, bridge arcs.',
    chips: ['canvas'], data: 'feed.mino.mobi API' },
  { id: 'bisk', name: 'bisk', glyph: '☼', district: 'graph', tier: 3, status: 'up',
    url: 'https://bisk.mino.mobi',
    desc: 'The SimCluster Daily — a deterministic morning digest: top posts, deepest thread, sentiment weather.',
    chips: ['daily cron', 'no inference'], data: 'public AppView, baked JSON' },
  { id: 'cluster', name: 'cluster', glyph: '❋', district: 'graph', tier: 2, status: 'up',
    url: 'https://mino.mobi/cluster/',
    desc: 'Find your tightest circle — the largest group of your follows who all mutually follow each other.',
    chips: ['client-side'], data: 'public AppView' },
  { id: 'seek', name: 'seek', glyph: '➤', district: 'graph', tier: 2, status: 'up',
    url: 'https://mino.mobi/seek/',
    desc: 'Find a friend — follows-of-follows you don’t yet follow, ranked by network density.',
    chips: ['client-side'], data: 'public AppView' },
  { id: 'disk', name: 'disk', glyph: '⊙', district: 'graph', tier: 2, status: 'up',
    url: '/disk/',
    desc: 'Poincaré interaction map — a hyperbolic-disk metro map of a list’s interactions, with live Jetstream traffic and history replay.',
    chips: ['DuckDB-WASM', 'jetstream'], data: 'AppView + Jetstream websocket' },
  { id: 'squares', name: 'squares', glyph: '▦', district: 'graph', tier: 3, status: 'up',
    url: '/squares/',
    desc: 'Your closest circle, in pictures — most-interacted accounts ringed around a handle in their friends’ best photos. Click to walk the graph.',
    chips: ['worker fan-out', 'service token'], data: 'repo scans via b worker' },

  { id: 'track', name: 'track', glyph: '⌇', district: 'graph', tier: 1, status: 'up',
    url: 'https://mino.mobi/track/',
    desc: 'Interaction metro — a subway-map rendering of a handle’s interactions.',
    chips: ['client-side'], data: 'public AppView' },

  // ── thread alley ────────────────────────────────────────────────────────
  { id: 'weft', name: 'weft', glyph: 'ψ', district: 'threads', tier: 2, status: 'up',
    url: 'https://mino.mobi/weft/',
    desc: 'Thread analysis — a tidy-tree canvas of any conversation, contributor weighting, YAML export for LLMs.',
    chips: ['canvas'], data: 'public AppView' },
  { id: 'photo-thread', name: 'thread', glyph: '⑂', district: 'threads', tier: 2, status: 'up',
    url: 'https://photo.mino.mobi/#/thread',
    desc: 'Threaded post viewer — full conversation tree with quote-post expansion. Lives inside photo.',
    chips: ['client-side'], data: 'public AppView' },
  { id: 'tetr', name: 'tetr', glyph: '⬡', district: 'threads', tier: 2, status: 'up',
    url: '/tetr/',
    desc: 'Thread tetris — real threads quantized into hex polyominoes by reply structure; clear rows, read the posts you land.',
    chips: ['canvas', 'hex math'], data: 'AppView + feed.mino.mobi' },

  // ── scriptorium ─────────────────────────────────────────────────────────
  { id: 'rite', name: 'rite', glyph: '✎', district: 'scriptorium', tier: 3, status: 'up',
    url: 'https://rite.mino.mobi',
    desc: 'Sentence-editing drill — rewrite a verbose sentence, scored on fidelity, brevity, clarity, speed. The hub of the family.',
    chips: ['worker', 'D1', 'Workers AI'], data: 'BGE embeddings, shared atpolls-db' },
  { id: 'fodder', name: 'fodder', glyph: '⇋', district: 'scriptorium', tier: 3, status: 'up',
    url: 'https://rite.mino.mobi/fodder/',
    desc: 'Swipe deck crowdsourcing new corpus sentences — mined from Gutenberg every 6h, rewritten by Llama, promoted by votes.',
    chips: ['cron', 'D1', 'Workers AI'], data: 'Gutenberg proxy + D1' },
  { id: 'redact', name: 'redact', glyph: '▓', district: 'scriptorium', tier: 2, status: 'up',
    url: 'https://rite.mino.mobi/redact/',
    desc: 'Redactle over a writer’s longest prose threads — guess the censored words.',
    chips: ['CAR + WASM'], data: 'full repo CAR, parsed client-side' },
  { id: 'ask', name: 'ask', glyph: '?', district: 'scriptorium', tier: 3, status: 'up',
    url: 'https://rite.mino.mobi/ask/',
    desc: 'Semantic search over a profile’s prose threads, mapped in 2D by embedding.',
    chips: ['CAR + WASM', 'D1', 'embeddings'], data: 'CAR → BGE → D1 index' },
  { id: 'atlas', name: 'atlas', glyph: '∴', district: 'scriptorium', tier: 2, status: 'up',
    url: 'https://rite.mino.mobi/atlas/',
    desc: 'Multi-view analytics over a writer’s threads — length, difficulty, Flesch, Pareto. Pure deterministic scoring.',
    chips: ['CAR + WASM'], data: 'full repo CAR, no inference' },
  { id: 'lexicon', name: 'lexicon', glyph: 'λ', district: 'scriptorium', tier: 2, status: 'up',
    note: 'concreteness lexicon never fetched — page falls back to the inline mini-lexicon',
    url: 'https://rite.mino.mobi/lexicon/',
    desc: 'Word-level lenses — emotion, concreteness, sentiment, distinctiveness — over a profile’s vocabulary.',
    chips: ['CAR + WASM', 'open lexicons'], data: 'NRC · AFINN · SUBTLEX' },
  { id: 'list', name: 'list', glyph: '≡', district: 'scriptorium', tier: 3, status: 'up',
    url: 'https://rite.mino.mobi/list/',
    desc: 'Semantic themes across a whole Bluesky list, aggregated from each member’s clusters.',
    chips: ['D1', 'embeddings', 'lists'], data: 'per-member ask indexes' },
  { id: 'web', name: 'web', glyph: '⁂', district: 'scriptorium', tier: 2, status: 'up',
    url: 'https://rite.mino.mobi/web/',
    desc: 'Outbound-link knowledge graph — PageRank over co-occurring URLs in a writer’s posts.',
    chips: ['CAR + WASM', 'PageRank'], data: 'link facets, client-side' },
  { id: 'signal', name: 'signal', glyph: '⇝', district: 'scriptorium', tier: 3, status: 'up',
    url: 'https://rite.mino.mobi/signal/',
    desc: 'A semantic map of what a writer reposts — their taste, as distinct from their voice.',
    chips: ['CAR + WASM', 'D1', 'embeddings'], data: 'repost targets → BGE → D1' },

  // ── gallery row ─────────────────────────────────────────────────────────
  { id: 'photo', name: 'photo', glyph: '▣', district: 'gallery', tier: 3, status: 'up',
    url: 'https://photo.mino.mobi',
    desc: 'Photo explorer — every image from any handle, SQL-queried in the browser: masonry, engagement, eigenpalettes, lightbox.',
    chips: ['React', 'DuckDB-WASM', 'CAR + WASM', 'oauth'], data: 'full repo CAR → DuckDB' },
  { id: 'astro', name: 'astro', glyph: '✴', district: 'gallery', tier: 2, status: 'up',
    url: 'https://photo.mino.mobi/astro/',
    desc: 'Astrology photo analyzer — EXIF timestamp + GPS feed an ephemeris that paints the sky at the moment of capture.',
    chips: ['EXIF', 'ephemeris'], data: 'image EXIF, client-side' },
  { id: 'prism', name: 'prism', glyph: '◬', district: 'gallery', tier: 2, status: 'up',
    url: 'https://photo.mino.mobi/prism/',
    desc: 'Photo prism — keratoconic global effect, hex toggle, EXIF-aware chromatic dispersion.',
    chips: ['canvas'], data: 'image pixels, client-side' },

  { id: 'cat', name: 'cat', glyph: 'ω', district: 'gallery', tier: 3, status: 'up',
    url: 'https://cat.mino.mobi',
    desc: 'Cat pictures, live off the firehose — first image + hashtags per post, via a Jetstream Durable Object.',
    chips: ['jetstream', 'DO', 'D1'], data: 'firehose → atpolls-db' },

  // ── the watch ───────────────────────────────────────────────────────────
  { id: 'gc', name: 'gc', glyph: '⊞', district: 'watch', tier: 2, status: 'up',
    url: '/gc/',
    desc: 'Block matrix — paste accounts and posters, get who directly blocks whom. Public block records, no login.',
    chips: ['raw PDS reads'], data: 'app.bsky.graph.block records' },
  { id: 'gc-mutuals', name: 'gc · mutuals', glyph: '⊟', district: 'watch', tier: 2, status: 'up',
    url: '/gc/mutuals/',
    desc: 'Mutuals of X who block Y — off public follow + block records.',
    chips: ['raw PDS reads'], data: 'follow graph + block records' },
  { id: 'gc-blockers', name: 'gc · blockers', glyph: '⊘', district: 'watch', tier: 3, status: 'up',
    url: '/gc/blockers/',
    desc: 'Everyone who blocks a named user — full count + list from the network-wide block index.',
    chips: ['worker', 'clearsky'], data: 'clearsky index via b worker' },
  { id: 'gc-api', name: 'gc · api', glyph: '⟐', district: 'watch', tier: 3, status: 'up',
    url: '/gc/api/',
    desc: 'The block-intelligence JSON API — relation, matrix, who-blocks, blockers. Read-only, CORS open, built for agents.',
    chips: ['worker', 'JSON API'], data: 'lib/gc.js in the b worker' },

  // ── the citadel ─────────────────────────────────────────────────────────
  { id: 'poll', name: 'poll', glyph: '☑', district: 'citadel', tier: 4, status: 'up',
    url: 'https://poll.mino.mobi',
    desc: 'Anonymous polling with RSA blind signatures — the host can’t link voter to vote. Public like-based mode too.',
    chips: ['writes', 'oauth', 'D1', 'Durable Objects', 'blind sigs'], data: 'PDS writes + DO + D1' },
  { id: 'airchat', name: 'airchat', glyph: '♪', district: 'citadel', tier: 3, status: 'up',
    note: 'ADMIN_KEY unset in prod — admin whitelist API disabled',
    url: 'https://airchat.mino.mobi',
    desc: 'Voice-first social on ATProto — browser records, Whisper transcribes, the audio blob lives on your PDS.',
    chips: ['writes', 'oauth', 'whisper', 'D1'], data: 'PDS uploadBlob + createRecord' },
  { id: 'answers', name: 'answers', glyph: '¿', district: 'citadel', tier: 2, status: 'up',
    url: 'https://mino.mobi/answers/',
    desc: 'Ask anything, answered by the ATmosphere — questions, answers, votes, best-answer as ATProto records.',
    chips: ['writes'], data: 'PDS records' },
  { id: 'feedgen', name: 'feedgen', glyph: '⚙', district: 'citadel', tier: 3, status: 'up',
    url: '/feedgen/',
    desc: 'No-code feed builder — stack inputs and filters, preview live, publish a real feed served by this very worker. Feeds live entirely on ATProto.',
    chips: ['writes', 'oauth', 'worker', 'gemini'], data: 'PDS feed defs, stateless' },

  { id: 'io', name: 'io', glyph: '⊶', district: 'citadel', tier: 3, status: 'warn',
    url: 'https://io.mino.mobi',
    note: 'reply bot off since the 2026-06 takedown incident; drip-mint capped',
    desc: 'ATProto ticket tracker + StumbleUpon portal — mints ticket records, sweeps #atproideasio posts.',
    chips: ['writes', 'D1', 'constellation'], data: 'backlinks + service PDS writes' },
  { id: 'pod', name: 'pod', glyph: '◍', district: 'citadel', tier: 3, status: 'warn',
    url: 'https://pod.mino.mobi',
    note: 'built, awaiting domain attach — not yet live',
    desc: 'Podcast studio — WebRTC recording rooms, multitrack editor, episodes published as records + blobs on your PDS, per-handle RSS.',
    chips: ['writes', 'oauth', 'WebRTC', 'DO'], data: 'PDS records + blobs, no D1' },
  { id: 'wave', name: 'wave', glyph: '∿', district: 'citadel', tier: 2, status: 'up',
    url: 'https://wave.mino.mobi',
    desc: 'Encrypted collaborative messaging + doc editing over ATProto, live via Jetstream.',
    chips: ['writes', 'oauth', 'crypto', 'jetstream'], data: 'sealed PDS records' },
  { id: 'wiki', name: 'wiki', glyph: '⧉', district: 'citadel', tier: 2, status: 'up',
    url: 'https://mino.mobi/wiki/',
    desc: 'Knowledge graph on ATProto — notes as records, linked and browsable.',
    chips: ['writes', 'oauth'], data: 'com.minomobi.wiki.note records' },
  { id: 'time', name: 'time', glyph: '¶', district: 'citadel', tier: 2, status: 'up',
    url: 'https://mino.mobi/time/',
    desc: 'The Mino Times — newspaper viewer over PDS records, plus the markdown → Bluesky thread pipeline behind it.',
    chips: ['writes', 'pipeline'], data: 'WhiteWind records + posting CI' },
  { id: 'fluoddity', name: 'fluoddity', glyph: '❉', district: 'citadel', tier: 2, status: 'up',
    url: 'https://fluoddity.mino.mobi',
    desc: 'Breed generative organisms saved as records on your own account; /clip posts video embeds to Bluesky.',
    chips: ['writes', 'oauth', 'WebGL'], data: 'PDS records + video service' },

  // ── the hamlet ──────────────────────────────────────────────────────────
  { id: 'bakery', name: 'bakery', glyph: '⊚', district: 'hamlet', tier: 2, status: 'up',
    url: 'https://bakery.mino.mobi',
    desc: 'Flour-blend calculator persisting to your PDS — the reference implementation of the shared auth client.',
    chips: ['writes', 'oauth'], data: 'PDS records' },
  { id: 'music', name: 'music', glyph: '♬', district: 'hamlet', tier: 2, status: 'up',
    url: 'https://mino.mobi/music/',
    note: 'inline OAuth — unmigrated to the shared client',
    desc: 'PWA composer writing compositions to your PDS.',
    chips: ['writes', 'PWA'], data: 'com.minomobi.music records' },
  { id: 'sweat', name: 'sweat', glyph: '☲', district: 'hamlet', tier: 1, status: 'up',
    url: 'https://mino.mobi/sweat/',
    note: 'inline OAuth — unmigrated to the shared client',
    desc: 'Workout PWA writing exercise records to your PDS.',
    chips: ['writes', 'PWA'], data: 'com.minomobi.workout records' },
  { id: 'org', name: 'org', glyph: '⌂', district: 'hamlet', tier: 2, status: 'up',
    url: 'https://org.mino.mobi',
    note: 'inline OAuth — unmigrated to the shared client',
    desc: 'Encrypted org hub — spreadsheets and state as sealed ATProto records.',
    chips: ['writes', 'crypto'], data: 'sealed PDS records' },
  { id: 'os', name: 'os', glyph: '⌥', district: 'hamlet', tier: 2, status: 'up',
    url: 'https://os.mino.mobi',
    desc: 'A PDS shell — xterm.js terminal (ls, cat, find, du, blob, sql) against any user’s repo, WASM CAR parse + DuckDB.',
    chips: ['DuckDB-WASM', 'CAR + WASM'], data: 'any repo, client-side' },
  { id: 'crm', name: 'crm', glyph: '☍', district: 'hamlet', tier: 2, status: 'warn',
    url: 'https://crm.mino.mobi',
    note: 'domain pending attach — served under root meanwhile',
    desc: 'Vault CRM — encrypted org state on the founder’s PDS, member discovery via DID resolution.',
    chips: ['writes', 'crypto'], data: 'sealed PDS records' },

  // ── the undercroft ──────────────────────────────────────────────────────
  { id: 'auth', name: 'auth worker', glyph: '§', district: 'undercroft', tier: 3, status: 'up',
    url: 'https://auth.mino.mobi/client-metadata.json',
    desc: 'The shared OAuth BFF — PKCE + DPoP + PAR + private_key_jwt. Every site signs in through it; PDS calls proxy via /pds/*.',
    chips: ['worker', 'D1', 'SSO'], data: 'workers/auth' },
  { id: 'feed', name: 'feed worker', glyph: '⌬', district: 'undercroft', tier: 3, status: 'warn',
    url: 'https://feed.mino.mobi/health',
    note: 'serving (10 communities) but publisher account taken down 2026-06 — appeal pending',
    desc: 'SimCluster feed generator — community detection on the mutual-follow graph every 6h; feeds zoom, bisk, tetr.',
    chips: ['worker', 'D1', 'cron'], data: 'workers/feed' },
  { id: 'scores', name: 'scores', glyph: '⚑', district: 'undercroft', tier: 3, status: 'up',
    url: GH + 'workers/scores',
    desc: 'Generic multi-game leaderboard — identity delegated to the auth worker; any game submits with no worker change.',
    chips: ['worker', 'D1'], data: 'workers/scores' },
  { id: 'bsky-bot', name: 'bsky-bot', glyph: '☏', district: 'undercroft', tier: 3, status: 'up',
    url: GH + 'workers/bsky-bot',
    desc: 'Notification listener — polls listNotifications every 5 minutes, dispatches mention handlers.',
    chips: ['worker', 'cron'], data: 'workers/bsky-bot' },
  { id: 'lib-atproto', name: 'packages/atproto', glyph: '⟠', district: 'undercroft', tier: 2, status: 'up',
    url: GH + 'packages/atproto',
    desc: 'The shared library — identity resolution, authenticated PDS ops, read-only AppView wrappers, vault crypto. No deps, no build.',
    chips: ['library'], data: 'pds.js · bsky.js · crypto.js' },
  { id: 'lib-oauth', name: 'oauth-client', glyph: '⟡', district: 'undercroft', tier: 2, status: 'up',
    url: GH + 'packages/oauth-client',
    desc: 'Browser-side AuthClient — login, session, scope escalation, PDS proxy. What new static sites import.',
    chips: ['library'], data: 'packages/oauth-client/auth.js' },
  { id: 'lib-car', name: 'CAR pipeline', glyph: '≣', district: 'undercroft', tier: 2, status: 'up',
    url: GH + 'rite/lib/atproto',
    desc: 'Browser-side repo-export parsing — a writer’s full CAR through a Rust→WASM reader, thread chains, reading level.',
    chips: ['library', 'WASM'], data: 'rite/lib/atproto' },
  { id: 'post-pipeline', name: 'post pipeline', glyph: '➳', district: 'undercroft', tier: 3, status: 'up',
    url: GH + 'src/post_thread.py',
    desc: 'Markdown → threaded Bluesky posts across three accounts (main, modulo, morphyx), facets and all.',
    chips: ['pipeline', 'actions'], data: 'time/posts/*.md' },
];
