/* Owain, neu Chwedyl Iarlles y Ffynnawn — "Owain, or the Tale of the Lady
   of the Fountain," one of the Three Welsh Romances (Y Tair Rhamant). The
   English shown alongside the Welsh is an original translation written
   movement by movement in subsequent passes; Lady Charlotte Guest's
   public-domain version (1849) is consulted as a sense-check, not copied.

   The Welsh is a reading text normalised from the public-domain edition of
   John Rhys & J. Gwenogvryn Evans, "The Text of the Mabinogion ... from the
   Red Book of Hergest" (Oxford, 1887), pp. 163–192 — the same volume from
   which the Culhwch ac Olwen text on this site is taken. The 1887 edition
   sets the tale in a special Welsh typeface that OCR mis-reads heavily, so
   the Welsh here is normalised by hand into a Middle Welsh reading
   orthography (the convention used for Pwyll on this site), cross-checked
   against the White Book of Rhydderch tradition where the OCR is corrupt.

   Both source texts are preserved verbatim under source/:
     owain-rhys-evans-1887-redbook.txt   (Middle Welsh, Red Book)
     owain-guest-1849-english.txt        (Guest's comparison translation)
   Attaches to window.OWAIN. */
window.OWAIN = window.OWAIN || {};
window.OWAIN.tale = {
  meta: {
    blurb: "<strong>Owain, neu Iarlles y Ffynnon</strong> — \"Owain, or the Lady of the Fountain\" — one of the <em>Three Welsh Romances</em> (with Peredur and Geraint), preserved in the White Book of Rhydderch (c. 1350) and the Red Book of Hergest (c. 1382–1410). It is the Brittonic twin of Chrétien de Troyes' <em>Yvain, ou le Chevalier au Lion</em> (c. 1177–81): whether Wales borrowed from France, France from Wales, or both from a lost common source is the central question of Arthurian transmission — and the reason this tale anchors the Welsh↔Continental branch of the <a href=\"/pendragon/#tree\">evolutionary tree</a> at Pendragon. The story: at Arthur's court Cynon tells of a humiliating defeat at a magic fountain; <strong>Owain</strong> rides out, defeats and mortally wounds the fountain's Black Knight, is trapped in the dead man's castle, and — made invisible by Luned's ring — falls in love with the widow he has just made, <strong>the Countess of the Fountain</strong>. Luned wins her for him; Owain holds the fountain; then Arthur's company arrives, Owain returns to court, <em>forgets his wife past the appointed day</em>, runs mad and naked in the wilderness, is healed by a lady's ointment, rescues and is companioned by a <strong>lion</strong>, frees the imprisoned Luned, and is at last reconciled to the Countess. The translation below is <strong>original</strong> and proceeds <strong>movement by movement</strong>; the Welsh beside it is a reading text normalised from Rhys &amp; Evans (1887). Full sources preserved at <a href=\"source/owain-rhys-evans-1887-redbook.txt\">source/owain-rhys-evans-1887-redbook.txt</a> and <a href=\"source/owain-guest-1849-english.txt\">source/owain-guest-1849-english.txt</a>.",
    sources: [
      { label: "The Text of the Mabinogion — Rhys & Evans, 1887 (Oxford, public domain; Red Book of Hergest, pp. 163–192)", url: "https://archive.org/details/textofmabinogion00rhysiala", host: "Internet Archive" },
      { label: "The Mabinogion — Lady Charlotte Guest, 1838–49 (public-domain English translation)", url: "https://www.gutenberg.org/ebooks/5160", host: "Project Gutenberg" },
      { label: "Owain, or the Lady of the Fountain — overview", url: "https://en.wikipedia.org/wiki/Owain,_or_the_Lady_of_the_Fountain", host: "Wikipedia" },
      { label: "Yvain, the Knight of the Lion — Chrétien de Troyes (the Continental twin)", url: "https://en.wikipedia.org/wiki/Yvain,_the_Knight_of_the_Lion", host: "Wikipedia" },
    ],
  },
  roadmap: [
    { t: "Source text in hand (Red Book / Rhys & Evans 1887 + Guest 1849)", done: true },
    { t: "I · Arthur's court at Caer Llion; Cynon is asked for a tale", done: true },
    { t: "II · Cynon's adventure: the Black Knight and the storm at the fountain", done: true },
    { t: "III · Owain rides out, defeats the Black Knight, is trapped in the castle", done: true },
    { t: "IV · Luned's ring; the funeral; Owain and the Countess of the Fountain", done: false },
    { t: "V · The wedding; Owain holds the fountain; Arthur's company arrives", done: false },
    { t: "VI · The broken term; madness in the wilderness; the healing ointment", done: false },
    { t: "VII · The lion; Luned freed from the stone vault; the Black Oppressor", done: false },
    { t: "VIII · Reconciliation with the Countess; return to court", done: false },
  ],
  passages: [
    {
      title: "I. Arthur's court at Caer Llion, and the asking of a tale",
      segments: [
        { w: "Yr amherawdyr Arthur a oed yg Kaer Llion ar Wysc. Sef yd oed yn eisted diwarnawt yn y ystafell, ac y gyt ac ef Owein uab Uryen, a Chynon uab Clydno, a Chei uab Kynyr; a Gwenhwyfar a'e llawforynyon yn gwniaw wrth y ffenestr. A chyd dywettit uot porthawr ar lys Arthur, nyt oed yr un; Glewlwyt Gauaeluawr oed yno hagen ar ureint porthawr, y arfoll gwesteywyr a phellennigyon, ac y dechreu eu hanrydedu, ac y uenegi udunt moes y llys a'e deuawt — yr neb a dylyei uynet yr neuad neu yr ystafell, oe uenegi idaw, a'r neb a dylyei letty, oe uenegi idaw.",
          e: "The emperor Arthur was at Caer Llion on Usk. One day he was sitting in his chamber, and with him were Owain son of Urien, and Cynon son of Clydno, and Cei son of Cynyr; and Gwenhwyfar and her handmaids were sewing by the window. And though it might be said that there was a porter at Arthur's court, there was none — yet Glewlwyd Mighty-Grasp was there in a porter's office, to receive guests and travellers from afar, to begin their honouring, and to make known to them the usage and the custom of the court: whoever should rightly go to the hall or to the chamber, to direct him; and whoever was owed a lodging, to direct him.",
          n: "The romance opens not at the fountain but at the hearth — the Welsh frame is a tale told <em>at</em> court before it is a tale lived in the wilderness. <strong>Caer Llion ar Wysc</strong> (Caerleon-on-Usk, Monmouthshire) is the Galfridian capital of Arthur's Britain. <strong>Glewlwyd Gafaelfawr</strong> (\"Mighty-Grasp\") is Arthur's porter here as he is in <em>Culhwch ac Olwen</em> — but note the wry inversion: Culhwch's Glewlwyd guards a gate that must not be passed, while here \"there was no porter\" and his office is pure hospitality. The same figure, the opposite function: the comparative seam this site is built to show." },

        { w: "Ac ym perued llawr yr ystafell yd oed yr amherawdyr Arthur yn eisted, ar demyl o irurwyn a llenn o bali melyngoch ydanaw, a gobennyd a'e dudet o bali coch dan penn y elin. Ar hynny y dywawt Arthur: \"Ha wyr,\" heb ef, \"pei nam goganewch, mi a gysgwn tra uewn yn aros uy mwyt; ac ymdidan a ellwch chwitheu, a chymryt ysteneit o ued a golwython y gan Gei.\" A chysgu a oruc yr amherawdyr.",
          e: "And in the middle of the chamber-floor sat the emperor Arthur, on a dais of fresh rushes with a covering of red-and-yellow brocade spread beneath him, and a cushion in a case of red brocade under his elbow. At that Arthur said: \"Men,\" he said, \"if you will not think the less of me for it, I would sleep while I wait for my meat; and you can talk among yourselves, and have a flagon of mead and some collops from Cei.\" And the emperor slept.",
          n: "The flame-coloured satin and the king who dozes while his men talk is a deliberately domestic, un-heroic frame — the marvels are about to be reported, not performed. The detail of <em>irvrwyn</em>, fresh-cut rushes strewn for a seat, is the texture of a real medieval Welsh hall." },

        { w: "A gofyn a oruc Cynon uab Clydno y Gei yr hyn a adawssei Arthur udunt. \"Minneu a uynnaf yr ymdidan da a edewit y minneu,\" heb y Cei. \"Iawn,\" heb y Cynon, \"tecaf yw itti wneuthur edewit Arthur yn gyntaf; ac odyna yr ymdidan goreu a wypom ninneu, ni a'e dywedwn itti.\" Ynet a oruc Cei yr gegin ac yr uedgell, a dyuot ac ysteneit o ued gantaw, ac eurgawc, a lloneit y dwrn o uereu yn dwyn golwython arnunt.",
          e: "And Cynon son of Clydno asked Cei for what Arthur had promised them. \"But I will have the good tale that was promised to me,\" said Cei. \"It is only fair,\" said Cynon, \"that you keep Arthur's promise first; and then the best tale we know, we will tell you.\" So Cei went to the kitchen and the mead-cellar, and came back bearing a flagon of mead, and a golden goblet, and a fistful of skewers carrying broiled collops.",
          n: "<strong>Cei</strong> (the later Sir Kay) is already the court's sharp-tongued steward — bargaining for his story before he will serve the mead. The exchange is courtesy as friction: who owes whom, and in what order. It is the same Cei who, a moment later, will mock Owain; the Welsh tale lets the seneschal's edge show early." },

        { w: "Ac yna y bwytaassant y golwython, ac y dechreuassant yuet y med. \"Weithon,\" heb y Cei, \"amser yw ywch talu y minneu uy ymdidan.\" \"Cynon,\" heb yr Owein, \"tal di y Gei y ymdidan a dyly.\" \"Yn wir,\" heb y Cynon, \"hynaf wyt ti, a gwell ymdidanwr, a mwy a weleist o ryfedodeu; tal ditheu y Gei y ymdidan.\" \"Dechreu dy hun,\" heb yr Owein, \"a'r goreu a wypych.\" \"Mi a'e gwnaf,\" heb y Cynon.",
          e: "And then they ate the collops and began to drink the mead. \"Now,\" said Cei, \"it is time you paid me my tale.\" \"Cynon,\" said Owain, \"pay Cei the tale that is his due.\" \"Truly,\" said Cynon, \"you are the elder, and the better teller, and you have seen more marvels than I — you pay Cei his tale.\" \"Begin yourself,\" said Owain, \"with the best you know.\" \"I will,\" said Cynon.",
          n: "The hand-off from Owain to Cynon is the hinge of the frame: the tale we are about to hear (Movement II) is <em>Cynon's defeat</em>, and it is the very adventure Owain will then ride out to avenge and complete. The romance's deep structure is a relay — one man's humiliating story becomes another man's quest. Cynon's narration begins in the next movement." },
      ],
    },

    {
      title: "II. Cynon's tale — the keeper of beasts, the fountain, and the Black Knight",
      segments: [
        { w: "Namyn vn mab mam a thad oeddwn i, a drythyll oeddwn, a mawr oedd fy ryfic; ac ny thybygwn yn y byt a orffei arnaf o neb ryw gamhwri. A gwedy daruot im gorfot ar bob camhwri o'r a oedd yn vn wlat a mi, ymgyweiraw a wneuthum a cherdet eithafoedd byt a diffeithwch. Ac yn y diwed dywannu a wneuthum ar y glynn teckaf yn y byt, a gwyd gogyfuch yndaw, ac auon redegawc ar hyt y glynn, a ffordd gan ystlys yr auon. A cherdet y ffordd a wneuthum hyt hanner dyd, a'r parth arall a gerdeis hyt pryt nawn; ac yna y deuthum y uaes mawr, ac yn niben y maes yd oedd kaer uawr lywychedic, a gweilgi yn gyfagos yr gaer. Ac y'r gaer y deuthum; ac nachaf y gwelwn deu was penngrych velyn, a ractal eur am penn pob un onadunt, a pheis o bali melyn am bob un, a gwaegeu eur yn kaeu am eu traet; a bwa o asgwrn eliffant yn llaw pob un, a'e saetheu o asgwrn moruil gwedy eu hadeinyaw ag adaned pawn, a phenneu eur arnunt; ac wynt yn saethu eu kylleill.",
          e: "I was the only son of my mother and father, and I was headstrong, and great was my pride; I did not believe there was anything in the world that could master me in any feat. And when I had overcome every trial there was in my own land, I made myself ready and rode to the ends of the earth and its wastes. And at last I came upon the fairest valley in the world, full of trees of even height, with a running river along it and a path beside the river. I followed the path till midday, and the rest of the valley till the hour of nones; and then I came out onto a great plain, and at the plain's end stood a great shining castle, with a torrent hard by it. I came up to the castle — and there were two youths with curling yellow hair, a gold band round the head of each, a tunic of yellow brocade on each, and gold clasps fastening their shoes; in the hand of each a bow of elephant-ivory, their arrows shafted with whalebone, fletched with peacock feathers and tipped with gold; and they were casting their gold-bladed knives at a mark.",
          n: "Cynon's adventure is the romance-quest in its purest grammar: exhaust the challenges of home, ride out to <em>eithafoedd byt a diffeithwch</em> — \"the ends of the earth and the wilderness\" — and find the marvel. He plays the part Chrétien gives to Calogrenant, whose identical defeat opens <em>Yvain</em>. The youths are a luxury-catalogue — ivory, whalebone, peacock, gold — the standard medieval signal that one has crossed into an Otherworld-touched court." },

        { w: "Ac ennyd y wrthunt y gwelwn wr penngrych velyn yn y dewred, a'e uaryf yn newyd eilliaw, a pheis a mantell o bali melyn ymdanaw. A phan y gweleis i ef, dynessau a wneuthum attaw a chyfarch gwell idaw; ac rac dahet y wybot, kynt y kyfarchawd ef well y mi no mi idaw ef. A dyuot gyt a mi a oruc parth ar gaer. Ac nyt oedd gyfanhed yn y gaer namyn a oedd yn vn neuad; ac yno yd oedd pedeir morwyn ar hugeint yn gwniaw pali wrth y ffenestr. A hynn a dywedaf ytti, Gei: tebic oedd gennyf vot yn degach yr hacraf onadunt no'r uorwyn deckaf a weleist ti eiryoet yn Ynys Prydein; a'r anardaf onadunt, hardach oedd no Gwenhwyfar gwreic Arthur pan vu hardaf eiryoet, duw Nadolic neu duw Pasc wrth offeren. A chyuodi a orugant ragof; a chwech onadunt a gymerth vy march ac a'm diarchenwys, a chwech ereill a gymerth vy arueu ac a'e golchassant yn lan, a'r trydydd chwech a dodes llieineu ar y byrdeu ac a arlwyassant uwyt, a'r pedwyryd chwech a diodes vy lludedic wisc ac a dodes gwisc arall ymdanaf. Ac eisted a orugam; ac nyt oedd lestyr yn gwassanaethu namyn eur neu aryant neu vueil. A bwyta a orugam hyt hanner bwyt, ac ny dywawt nac y gwr nac un o'r morynyon un geir wrthyf hyt yna.",
          e: "A little way off from them I saw a man in his prime, his beard newly shaven, in a tunic and mantle of yellow brocade. When I saw him I went up and greeted him; and so gracious was his breeding that he returned my greeting before I had well finished it. He came with me toward the castle. There were no dwellers in it but those in one hall, and there sat four-and-twenty maidens embroidering brocade by the window. And I tell you this, Cei: the plainest of them was lovelier than the fairest maid you ever saw in the Island of Britain, and the least comely of them was comelier than Gwenhwyfar, Arthur's wife, at her fairest ever, at Mass on Christmas Day or Easter. They rose at my coming: six took my horse and unshod me, six took my arms and washed them bright, six laid cloths on the tables and set out food, and six stripped off my travel-worn clothes and dressed me afresh. We sat; and no vessel served at the table but of gold or silver or buffalo-horn. We ate till the meal was half done, and neither the man nor any maiden spoke a word to me until then.",
          n: "The doubled, ascending courtesy — twenty-four maidens, each task done by a set of six — is the Welsh romance's way of marking a place finer than the waking world without making it overtly magical, the same restraint <em>Pwyll</em> uses for the court of Annwn. The silence until the meal is half over is a point of manners, not menace: it would be discourteous to question a guest before he is fed." },

        { w: "A phan vu debic gan y gwr vot yn well gennyf ymdidan no bwyta, gofyn a oruc ym pa ryw wr oeddwn. Ac yna y menegeis i y'r gwr pwy oeddwn, a'r kerdet oedd arnaf, a dywedut vy mot yn keissaw a orffei arnaf, neu vinneu a orffei ar bawb. Ac edrych a oruc y gwr arnaf a gwenu, a dywedut: \"Bei na thybyckwn dyuot gormod o ouut itt, mi a uanagwn itt yr hynn yd wyt yn y geissaw.\" A chymryt tristit a goueileint a wneuthum am hynny; ac adnabot a oruc y gwr hynny, a dywedut: \"Kanys gwell yw gennyt menegi o honaf itt dy aflles no'th les, mi a'e managaf itt. Kwsc yma heno, a chyfot yn vore, a chymer y ffordd ar hyt y dyffryn uchot yny delych y'r koet y deuthost trwydaw; ac yn rynnawd yn y koet y kyferfyd gwahanffordd a thi ar y tu deheu, a cherda honno yny delych y lannerch uawr gysgodawc a thwmpath y'm perued. Ac y gweli wr du mawr ar benn y twmpath, nyt llei no deu wr o wyr y byt hwnn; ac vn troet yssydd idaw, ac vn llygat y'm perued y dalcen, a gwialen haearn yn y law. A gofyn idaw y ffordd, ac ef a'e dengys itt.\"",
          e: "When the man saw that I would rather talk than eat, he asked me what kind of man I was. Then I told him who I was, and the errand I was on, and said I was seeking whether anything could master me, or I could master all. He looked at me and smiled, and said: \"If I did not fear to bring you too much grief, I would show you the very thing you seek.\" At that I grew downcast and sorrowful; and seeing it, he said: \"Since you would rather I showed you your loss than your gain, I will. Sleep here tonight, rise early, and take the road up the valley till you reach the wood you came through; a little way into the wood a side-track branches off on the right — follow it till you come to a great sheltered glade with a mound in the middle. On the mound you will see a great black man, no smaller than two of the men of this world; he has but one foot, and one eye in the middle of his forehead, and an iron staff in his hand. Ask him the way, and he will show it to you.\"",
          n: "The host's careful phrasing — to show \"your loss rather than your gain\" — frames the fountain not as a prize but as a humbling. The romance is honest from the start that this adventure ends in shame; the wonder is that Owain will later ride the same road to a different end." },

        { w: "A hir uu gennyf y nos honno. A thrannoeth y kyuodeis ac ymgyweiraw, a mynet rac vy mronn ar hyt y dyffryn y'r koet, a chymryt y wahanffordd a dangossei y gwr ym, yny deuthum y'r llannerch. Ac yno yd oedd teir gweith mwy o anifeileit gwylltion no'r a dywedassei y gwr ym. A'r gwr du a oedd yn eisted ar benn y twmpath; mawr oedd ef, a mwy o lawer noc y dywedassei y gwr ym. A gofyn a wneuthum idaw pa allu a oedd idaw ar yr anifeileit hynny. \"Mi a'e dangosaf itt, was bychan,\" heb ef. A chymryt y wialen yn y law, a tharaw karw a hi yny vraeawd; ac ar y vrefiat, llyma yr anifeileit yn dyuot mor amyl a'r ser yn yr awyr, yny oedd gyfyng ym y seuyll yn y llannerch y'm plith. Ac edrych a oruc arnunt, ac erchi udunt uynet y bori; a gostwng eu penneu a wnaethant ac y wneuthur idaw gwarogaeth, megys y gwna dynyon ufyd y'w harglwyd. Ac yna y dywawt y gwr du wrthyf: \"A wely di, was bychan, y gallu yssydd ym ar yr anifeileit hynn?\"",
          e: "Long that night seemed to me. Next morning I rose and made ready and went on up the valley to the wood, and took the side-track the man had shown me, till I came to the glade. And there were three times more wild beasts than he had told me. The black man sat on the mound — huge, and far bigger than I had been told. I asked him what power he had over those beasts. \"I will show you, little man,\" he said. He took the staff in his hand and struck a stag with it till it brayed; and at its braying, here came the beasts thronging, thick as the stars in the sky, till there was scarcely room for me to stand among them in the glade. He looked at them and bade them go and graze; and they bowed their heads and did him homage, as obedient men do their lord. Then he said to me: \"Do you see, little man, the power I have over these beasts?\"",
          n: "The one-eyed, one-footed keeper of beasts (Thompson F460, the wild herdsman) is the oldest thing in the tale — a threshold-guardian out of the pre-Christian Otherworld, lord of the animals, who gives directions but no comfort. He is the Welsh cousin of the giant herdsmen of <em>Culhwch</em>, and the romance's bridge between the courtly luxury of the castle and the raw magic of the fountain." },

        { w: "Ac yna y gofynneis i idaw y ffordd; a rwithyaw a oruc yn arw wrthyf, a gofyn ym pa le yd awn. \"Kymer,\" heb ef, \"y ffordd a el parth a phenn y llannerch, a dring y vryn coediawc uchot yny delych y'w benn; ac yno y kymer ti vaes mawr megys dyffryn, ac y'm perued y maes pren mawr, a'e geigeu yn lasach no'r glassaf o'r ffynyddwyd. Ac y dan y pren hwnnw y mae ffynnawn, ac yn ymyl y ffynnawn y mae llech varmor, ac ar y llech y mae bowl aryant wrth gadwyn aryant, hyt na ellir eu gwahanu. A chymer y bowl a bwrw bowleit o'r dwfyr ar y llech; ac yna y klywy twryf mawr, yny tebyckych vot nef a daear yn crynu gan y dwrf. Ac yn ol y twryf y daw kawat, ac odit ny bo bwrw o genllysc; ac wedy y gawat, glaw teg a vyd, ac nyt oes deilen ar y pren ny dyckir ymeith gan y gawat. Ac yna y daw kawat o adar y'r pren, ac ny chiglyf yn dy wlat dy hun gerdoryaeth gystal a'r a ganant hwynt. A phan vych digrifaf gennyt wrandaw arnunt, llyma duchan a chwynuan yn dyuot ar hyt y dyffryn attat; a marchawc a wely ar uarch purdu, a gwisc o bali purdu ymdanaw, a llumman o bali du ar y baladyr; ac yth gyrch mor gynt ac y galler. A chyt ffoych racdaw ef a'th oddiwed, ac o seuy y'w erbyn — marchawc wyt ti — ef a'th gad ar dy droet. Ac ony chefy ouut yn yr antur honno, nyt reit itt geissaw ouut tra vych vyw.\"",
          e: "Then I asked him the way; and he turned rough with me, and asked where I would go. \"Take,\" he said, \"the path that leads to the head of the glade, and climb the wooded hill above till you reach its top; there you will come on a great open ground like a valley, and in the middle of it a tall tree, its branches greener than the greenest pine. Under that tree is a spring, and beside the spring a slab of marble, and on the slab a silver bowl chained with a silver chain, so that the two cannot be parted. Take the bowl and throw a bowlful of the water on the slab; and then you will hear a great crash of thunder, till you think heaven and earth are shaking with it. After the thunder comes a downpour — and it will scarcely fail to be of hailstones — and after the shower, fair weather; but not a leaf will be left on the tree. Then a flock of birds will settle on the tree, and never in your own land have you heard music to match their song. And just when their song delights you most, here will come a moaning and a wailing up the valley toward you, and you will see a knight on a jet-black horse, in jet-black brocade, a black pennon on his lance; and he will charge you as fast as he can. If you flee, he will catch you; and if you stand to meet him — mounted knight though you are — he will leave you on foot. And if you do not find trouble in that adventure, you need never seek trouble as long as you live.\"",
          n: "The storm-fountain (Thompson D2143.1, tempest made by magic) is the engine of the whole romance — a weather-rite bound to a place, with a guardian who must be killed to be succeeded; Chrétien's cousin is the fountain of Barenton in Brocéliande. The bowl chained to the slab is the trigger; the birdsong and the wailing knight are the two faces of the place, its beauty and its reckoning." },

        { w: "A cherdet y ffordd a wneuthum hyt benn y vryn, ac yno y keueis bop peth megys y dywedassei y gwr du ym. A dyuot at y pren a wneuthum; ac y dan y pren y gweleis y ffynnawn, ac yn ymyl y ffynnawn y llech varmor, a'r bowl aryant wrth y gadwyn. A chymryt y bowl a wneuthum a bwrw bowleit o'r dwfyr ar y llech; ac ar hynny, llyma y twryf yn dyuot, mwy o lawer noc y tebygassei y gwr du, ac yn ol y twryf y kawat. A diheu yw gennyf, Gei, nat oes na dyn nac anifail a'r a vo allan a dycko y gawat honno yn vyw, kanys nyt arhoes vn o'r kesseir hynny na chnawt na chroen yny ddel y'r asgwrn. A throi tin vy march wrth y gawat a wneuthum, a dodi pic vy ysgwyt ar benn a mwnwgyl vy march, a dala y rann uchaf o honaw uch vy mhenn vy hun; ac uelly y deleis y gawat. A phan edrycheis ar y pren, nyt oedd vn deilen arnaw; a thengin teg a wnaeth yr awyr. Ac ar hynny llyma yr adar yn disgynnu ar y pren ac yn canu; a diheu yw gennyf, Gei, na chigleu i eiryoet gerdoryaeth gystal a honno na chynt na gwedy.",
          e: "I rode on to the top of the hill, and there found everything as the black man had said. I came to the tree, and beneath it the spring, and beside it the marble slab, and the silver bowl on its chain. I took the bowl and threw a bowlful of water on the slab; and at once the thunder came, far greater than the black man had led me to expect, and after the thunder the downpour. And truly, Cei, I believe there is neither man nor beast caught in the open that could live through that shower — for not one of those hailstones was stopped by flesh or skin until it reached the bone. I turned my horse's hindquarters to the storm and set the boss of my shield over his head and neck, and held the upper part of it over my own head; and so I bore out the shower. And when I looked at the tree there was not a leaf on it; and the sky cleared fair. And then the birds came down on the tree and sang; and truly, Cei, I never heard music to equal it, before or since.",
          n: "Note the practical, soldierly detail of how Cynon survives the hail — the boss of the shield turned to the storm over the horse's head. The Welsh romance keeps its marvels braced against bodily fact: the magic is overwhelming, but a knight still has to put his shield in the right place." },

        { w: "A phan oeddwn ddigrifaf gennyf wrandaw ar yr adar, llyma duchan yn dyuot ar hyt y dyffryn attaf, a dywedut: \"A varchawc, beth a'th dyckwys di yma? Pa drwc a wneuthum i itt, yny gwnelut ti ym i ac y'm kyuoeth y peth a wnaethost ti hediw? Pony wdost ti na edewis y gawat hediw yn vy nherfyn na dyn nac anifail yn vyw o'r a gauas allan?\" Ac ar hynny llyma varchawc ar uarch purdu, a gwisc o bali purdu ymdanaw, a thabar o bali du amdanaw. Ac ymgyrchu a orugam; a chan vot y rwyf yn greulawn, nyt hir y buum kyn vy mwrw y'r llawr. Ac yna y dodes y marchawc baladyr trwy ffrwyn vy march, ac y kerdawd ymeith a'r ddeu varch, gan vyngadu inneu yno; ac ny chymerth gymeint a'm karcharu, na'm hyspeilaw o'm harueu. A dyuot drachefyn y'r ffordd y deuthum a wneuthum; a phan deuthum y'r llannerch lle yd oedd y gwr du, mi a gyffessaf itt, Gei, ryued yw na thodeis i yn lyn o'r kywilyd a gefeis gan watwar y gwr du. A'r nos honno y deuthum y'r un gaer y buaswn y nos kynt; ac y'm digrifach y bum y nos honno no'r nos gynt. A thrannoeth pan gyuodeis, llyma balurei gwineu kalch-las yn barawt ym, a'i ffroeneu yn gochon megys ysgarlat; ac wedy ymarfogi a gadu vy mendith yno, y deuthum hyt vy llys vy hun. A'r march hwnnw a delis ym o hyt; ac ny rown ef am y goreu yn Ynys Prydein.",
          e: "And just when their song delighted me most, here came a wailing up the valley toward me, saying: \"Knight, what brought you here? What wrong did I ever do you, that you should do to me and to my realm what you have done today? Do you not know that today's shower has left neither man nor beast alive within my borders that was caught in the open?\" And with that, here was a knight on a jet-black horse, in jet-black brocade, a black surcoat about him. We charged each other; and because the onset was savage, it was not long before I was thrown to the ground. Then the knight ran the shaft of his lance through my horse's bridle-rein and rode off with both horses, leaving me there; he did not so much as trouble to take me prisoner or strip me of my arms. I went back the way I had come; and when I reached the glade where the black man was, I confess to you, Cei, it is a wonder I did not melt into a pool for the shame of his mockery. That night I came to the same castle as the night before, and was made more welcome that night than the first; and none of them said a word of my going to the fountain, nor did I. And next morning when I rose, there stood ready for me a bay palfrey, calx-grey, its nostrils red as scarlet; and after arming and leaving my blessing there, I came home to my own court. That horse I have to this day — and I would not give him for the best palfrey in the Island of Britain.",
          n: "The defeat is total, and humiliating in a precise, courtly way: the Black Knight does not even trouble to capture or despoil Cynon — the deepest insult is to be judged not worth the keeping. Yet his hosts, with perfect tact, never mention his failure, and send him home better mounted than he came. The red-nostrilled palfrey is the castle's grace laid over the fountain's shame." },

        { w: "Ac yn wir, Gei, ny chyffessawd dyn eiryoet antur kymeint y waradwyd ac y kyffesseis i; a ryued yw gennyf na chigleu na chynt na gwedy son am y peth hwnn, ac y bot yn dyuot o vewn kyuoeth Arthur, heb dyuot neb arall arnaw. \"Weithon,\" heb yr Owein, \"pony bei da uynet y geissaw kaffel y lle hwnnw?\" \"Myn llaw vy nghyfaill,\" heb y Gei, \"mynych y dywedy a'th davawt yr hyn ny chywirit a'th weithret.\" \"Yn wir,\" heb y Wenhwyfar, \"gwell y bydei dy grogi di, Gei, no dywedut geireu mor anghyweir a hynny wrth wr fal Owein.\" \"Myn llaw vy nghyfaill, arglwydes,\" heb y Gei, \"ny dywedeist ti uoliant well y Owein no minneu.\" Ac ar hynny y deffroes Arthur, a gofyn a gysgassei dim. \"Do, arglwyd,\" heb yr Owein, \"talym.\" \"Ai amser yw in vynet y vwyta?\" \"Yw, arglwyd,\" heb yr Owein. Ac yna y kanwyt y korn y ymolchi, ac yd aeth y brenhin a'r holl deulu y vwyta.",
          e: "\"And truly, Cei, never did a man confess an adventure so much to his own shame as I have confessed; and it is a wonder to me that I have never heard, before or since, any word of this thing — that it should lie within Arthur's own dominion, and no one else light upon it.\" \"Now,\" said Owain, \"would it not be a good thing to go and seek out that place?\" \"By the hand of my friend,\" said Cei, \"often do you say with your tongue what you would not make good with your deeds.\" \"Truly,\" said Gwenhwyfar, \"you would be better hanged, Cei, than speak words so uncourteous to a man like Owain.\" \"By the hand of my friend, lady,\" said Cei, \"your praise of Owain was no greater than mine.\" And with that Arthur awoke, and asked whether he had slept at all. \"You have, lord, a while,\" said Owain. \"Is it time for us to go to meat?\" \"It is, lord,\" said Owain. Then the horn was sounded for the washing, and the king and all the household went to eat.",
          n: "The frame snaps shut: Cynon's shame becomes Owain's resolve, and Cei — true to form — mocks the resolve before it can be acted on, earning Gwenhwyfar's sharpest line. The sleeping king wakes knowing nothing of the tale that will send one of his knights out at the next dawn. Owain's quest (Movement III) begins in silence, told to no one." },
      ],
    },

    {
      title: "III. Owain rides the same road — the slain Black Knight and the portcullis",
      segments: [
        { w: "A gwedy daruot bwytta, diflannu a oruc Owein ymeith, a dyuot y'w letty a pharattoi y varch a'e arueu. A phan welas ef y dyd drannoeth, gwisgaw y arueu a oruc ac yscynnu ar y uarch, a cherdet racdaw eithafoedd byt a diffeith vynyded; ac yn y diwed y dywanawd ar y glynn a uanagassei Cynon idaw, fal y gwydyat yn hyspys panyw hwnnw oedd. A cherdet a oruc ar hyt y glynn gan ystlys yr auon yny doeth y'r dyffryn; a'r dyffryn a gerdawd yny welei y gaer, a pharth a'r gaer y deuth. Sef y gwelei y gweisson yn saethu eu kylleill yn y lle y gwelsei Cynon, a'r gwr melyn bieuoedd y gaer yn seuyll gyt eu llaw. A phan ytoedd Owein yn mynnu kyfarch gwell y'r gwr melyn, kyfarch gwell a oruc y gwr y Owein gynt.",
          e: "And when the meal was over, Owain slipped quietly away, went to his lodging, and made ready his horse and his arms. And when the next day broke, he put on his armour, mounted his horse, and rode out across the ends of the earth and desert mountains; and at last he came down into the valley Cynon had described to him, and knew for certain it was the one. He rode along the valley by the side of the river until he reached the plain, and crossed the plain till he saw the castle, and came toward it. And there were the youths casting their knives in the place where Cynon had seen them, and the yellow-clad man who owned the castle standing beside them. And just as Owain made to greet the yellow man, the man greeted Owain first.",
          n: "Owain's quest begins exactly as Cynon's did — the same valley, the same youths, the same gracious host — and the romance leans on the repetition: this is a tale of one road travelled twice, the second time to a different end. He tells no one at court; he simply <em>diflannu</em>, vanishes, after the meal. The Welsh hero acts where Cynon only spoke." },

        { w: "A dyuot yn y vlaen parth a'r gaer; ac ef a welei yr ystauell yn y gaer. A phan deuth y'r ystauell, ef a welei y morynyon yn gwniaw pali ymywn kadeireu eureit; a hoffach o lawer oedd gan Owein eu tecket a'e hardet noc y dywawt Cynon idaw. A chyuodi a wnaethant y wassanaethu Owein mal y gwassanaethassynt Gynon; a hoffach uu gan Owein eu porthiant no chan Gynon. Ac am hanner bwytta, gofyn a oruc y gwr melyn y Owein pa gerdet oedd arnaw; ac y dywawt Owein gwbyl o'e gerdet idaw, ac y ymgeissaw a'r marchawc yssydd yn gwarchadw y ffynnawn y mynnwn vy mot. A gwenu a oruc y gwr melyn, a bot yn anhawd gantaw menegi y Owein y kerdet hwnnw mal y bu anhawd gantaw y uenegi y Gynon; ac eissoes menegi a oruc y Owein gwbyl. Ac y gysgu yd aethant.",
          e: "He went forward toward the castle, and saw the chamber; and when he came into it, there were the maidens embroidering brocade in chairs of gold — and their beauty and grace pleased Owain far more than Cynon had told him. They rose to wait on Owain as they had on Cynon, and their service pleased Owain more than it had Cynon. And when the meal was half done, the yellow man asked Owain what his errand was; and Owain told him the whole of it: that he was come to seek the knight who guards the fountain. The yellow man smiled, and was as loath to point that adventure out to Owain as he had been with Cynon; yet he told him the whole of it. And they went to sleep.",
          n: "Everything is the same, and everything is a little finer — the maidens lovelier, the welcome warmer — as if the place itself rewards the man who comes to act rather than merely to wander. The host's reluctance is unchanged: he still names the fountain a thing of loss, not gain." },

        { w: "A'r bore drannoeth y bu barawt march Owein gan y morynyon; a cherdet a oruc Owein racdaw yny deuth y'r llannerch yd oedd y gwr du yndi. A hoffach uu gan Owein meint y gwr du no chan Gynon; a gofyn ffordd a oruc Owein y'r gwr du, ac ynteu a'e menegis. A cherdet a oruc Owein y ffordd fal Cynon, yny doeth yn ymyl y pren glas; ac ef a welei y ffynnawn, a'r llech yn ymyl y ffynnawn, a'r kawc arni. A chymryt y kawc a oruc Owein a bwrw kawgeit o'r dwfyr ar y llech. Ac ar hynny, nachaf y twryf, ac yn ol y twryf y gawat — mwy o lawer noc y dywedassei Cynon oeddynt. A gwedy y gawat, goleuhau a oruc yr awyr; a phan edrychawd Owein ar y pren, nyt oedd vn dalen arnaw. Ac ar hynny, nachaf yr adar yn disgynnu ar y pren ac yn canu.",
          e: "Next morning Owain's horse was made ready by the maidens; and he rode on until he came to the glade where the black man was. The black man's size pleased Owain more than it had Cynon; he asked the black man the way, and he showed it. Owain rode the road as Cynon had, until he came beside the green tree; and he saw the fountain, and the slab beside the fountain, and the bowl upon it. Owain took the bowl and threw a bowlful of water on the slab; and at once, here came the thunder, and after the thunder the shower — greater by far than Cynon had told. And after the shower the sky cleared; and when Owain looked at the tree, there was not a leaf on it. And then the birds came down on the tree and sang.",
          n: "Owain meets the keeper of beasts with relish, not dread — \"his size pleased Owain\" where it had merely awed Cynon. The same wonders that humbled the first knight are, to the second, the furniture of an adventure he has chosen; and the storm is greater for Owain, because the tale is now in earnest." },

        { w: "A phan oedd digrifaf gan Owein gerd yr adar, ef a welei varchawc yn dyuot ar hyt y dyffryn; ac erbynnyeit a oruc Owein, ac ymwan ac ef yn drut. A thorri y deu baladyr a orugant, a dispeilaw deu gledyf a wnaethant ac ymgyfogi. Ac ar hynny, Owein a drewis dyrnawt ar y marchawc trwy y helym a'r pennffestin a'r penngwch porffwrin, a thrwy y kroen a'r kig a'r asgwrn, yny glwyfawd ar yr emennyd. Ac yna adnabot a oruc y marchawc duawc ry gaffel dyrnawt angheuawl o honaw; ac ymchoelut penn y varch a oruc a ffo.",
          e: "And just when the birds' song delighted Owain most, he saw a knight coming up the valley; Owain received him, and clashed with him fiercely. They broke both their lances, drew their two swords, and fell to hewing. And then Owain dealt the knight a blow through his helmet and his headpiece and his purple coif, and through skin and flesh and bone, until it wounded the very brain. And then the black knight knew he had taken a mortal blow; he turned his horse's head and fled.",
          n: "Where Cynon was unhorsed at the first onset, Owain breaks his lance, draws his sword, and lands the killing stroke — the same encounter, the opposite outcome, told in nearly the same words. The Welsh romance measures its hero against the man who failed: Owain is what Cynon was not. And the mortal wound is itself the engine of the plot — it makes the widow Owain will come to love." },

        { w: "Ac ymlit a oruc Owein, ac nyt ymgaffei Owein a'e vaedu a'r cledyf — nyt oedd bell idaw ynteu. Ac ar hynny Owein a welei gaer uawr lywychedic, ac y porth y gaer y deuthant. Ac ellwng y marchawc duawc a wnaethpwyt ymywn; ac ellwng dor dyrchafat a wnaethpwyt ar Owein. A honno a'e medrawd o dis y bardwgyl y kyfrwy, yny dorres y march yn deu hanner trwydaw, a throelleu yr ysparduneu gan sodleu Owein; ac yny gerda y dor hyt y llawr. A throelleu yr ysparduneu a dryll y march y maes, ac Owein a'r dryll arall o'r march yrwng y dwy dor; a'r dor ymywn a gaewyt, fal na allei Owein vynet o dyno. Ac yng nghyfyng gyngor yd oedd Owein.",
          e: "Owain gave chase, never quite able to reach him with the sword — yet never far behind. And then Owain saw a great shining castle, and they came to the castle gate. The black knight was let in; and a portcullis was dropped on Owain. It caught him just behind the saddle-bow, and cut the horse clean in two through the middle, and sheared off the rowels of the spurs at Owain's heels; and the gate drove on down to the floor. The spur-rowels and the outer half of the horse were left outside; and Owain, with the other half of the horse, was caught between the two gates — and the inner gate was shut, so that he could not get away. And Owain was in a sore strait.",
          n: "The portcullis-trap — the dead man's castle closing on his killer — is one of the most cinematic moments in the corpus: the horse sheared in two behind the saddle, the spur-rowels clipped from Owain's very heels. He has won the combat and ridden straight into a cage. The movement ends here, on the trap; the rescue, the ring, and the lady he will love all wait on the far side of that inner gate." },
      ],
    },
  ],
};
