/* Owain, neu Chwedyl Iarlles y Ffynnawn — "Owain, or the Tale of the Lady
   of the Fountain," one of the Three Welsh Romances (Y Tair Rhamant). The
   English shown alongside the Welsh is an original translation written
   movement by movement in subsequent passes; Lady Charlotte Guest's
   public-domain version (1849) is consulted as a sense-check, not copied.

   The Welsh is a reading text normalised from the public-domain edition of
   John Rhys & J. Gwenogvryn Evans, "The Text of the Mabinogion ... from the
   Red Book of Hergest" (Oxford, 1887), pp. 163–192 — the same volume from
   which the Culhwch ac Olwen text on this site is taken. The 1887 edition
   sets the tale in a special Welsh typeface that OCR mis-reads heavily, so
   the Welsh here is normalised by hand into a Middle Welsh reading
   orthography (the convention used for Pwyll on this site), cross-checked
   against the White Book of Rhydderch tradition where the OCR is corrupt.

   Both source texts are preserved verbatim under source/:
     owain-rhys-evans-1887-redbook.txt   (Middle Welsh, Red Book)
     owain-guest-1849-english.txt        (Guest's comparison translation)
   Attaches to window.OWAIN. */
window.OWAIN = window.OWAIN || {};
window.OWAIN.tale = {
  meta: {
    blurb: "<strong>Owain, neu Iarlles y Ffynnon</strong> — \"Owain, or the Lady of the Fountain\" — one of the <em>Three Welsh Romances</em> (with Peredur and Geraint), preserved in the White Book of Rhydderch (c. 1350) and the Red Book of Hergest (c. 1382–1410). It is the Brittonic twin of Chrétien de Troyes' <em>Yvain, ou le Chevalier au Lion</em> (c. 1177–81): whether Wales borrowed from France, France from Wales, or both from a lost common source is the central question of Arthurian transmission — and the reason this tale anchors the Welsh↔Continental branch of the <a href=\"/pendragon/#tree\">evolutionary tree</a> at Pendragon. The story: at Arthur's court Cynon tells of a humiliating defeat at a magic fountain; <strong>Owain</strong> rides out, defeats and mortally wounds the fountain's Black Knight, is trapped in the dead man's castle, and — made invisible by Luned's ring — falls in love with the widow he has just made, <strong>the Countess of the Fountain</strong>. Luned wins her for him; Owain holds the fountain; then Arthur's company arrives, Owain returns to court, <em>forgets his wife past the appointed day</em>, runs mad and naked in the wilderness, is healed by a lady's ointment, rescues and is companioned by a <strong>lion</strong>, frees the imprisoned Luned, and is at last reconciled to the Countess. The translation below is <strong>original</strong> and proceeds <strong>movement by movement</strong>; the Welsh beside it is a reading text normalised from Rhys &amp; Evans (1887). Full sources preserved at <a href=\"source/owain-rhys-evans-1887-redbook.txt\">source/owain-rhys-evans-1887-redbook.txt</a> and <a href=\"source/owain-guest-1849-english.txt\">source/owain-guest-1849-english.txt</a>.",
    sources: [
      { label: "The Text of the Mabinogion — Rhys & Evans, 1887 (Oxford, public domain; Red Book of Hergest, pp. 163–192)", url: "https://archive.org/details/textofmabinogion00rhysiala", host: "Internet Archive" },
      { label: "The Mabinogion — Lady Charlotte Guest, 1838–49 (public-domain English translation)", url: "https://www.gutenberg.org/ebooks/5160", host: "Project Gutenberg" },
      { label: "Owain, or the Lady of the Fountain — overview", url: "https://en.wikipedia.org/wiki/Owain,_or_the_Lady_of_the_Fountain", host: "Wikipedia" },
      { label: "Yvain, the Knight of the Lion — Chrétien de Troyes (the Continental twin)", url: "https://en.wikipedia.org/wiki/Yvain,_the_Knight_of_the_Lion", host: "Wikipedia" },
    ],
  },
  roadmap: [
    { t: "Source text in hand (Red Book / Rhys & Evans 1887 + Guest 1849)", done: true },
    { t: "I · Arthur's court at Caer Llion; Cynon is asked for a tale", done: true },
    { t: "II · Cynon's adventure: the Black Knight and the storm at the fountain", done: true },
    { t: "III · Owain rides out, defeats the Black Knight, is trapped in the castle", done: true },
    { t: "IV · Luned's ring; the funeral; Owain and the Countess of the Fountain", done: true },
    { t: "V · Luned's embassy; the wedding; Owain holds the fountain", done: true },
    { t: "VI · Arthur's company: Cei unhorsed, Gwalchmei's three-day duel, the recognition", done: true },
    { t: "VII · The broken term; madness in the wilderness; the healing ointment", done: true },
    { t: "VIII · The lion; Luned freed from the stone vault; the Black Oppressor", done: false },
    { t: "IX · Reconciliation with the Countess; return to court", done: false },
  ],
  passages: [
    {
      title: "I. Arthur's court at Caer Llion, and the asking of a tale",
      segments: [
        { w: "Yr amherawdyr Arthur a oed yg Kaer Llion ar Wysc. Sef yd oed yn eisted diwarnawt yn y ystafell, ac y gyt ac ef Owein uab Uryen, a Chynon uab Clydno, a Chei uab Kynyr; a Gwenhwyfar a'e llawforynyon yn gwniaw wrth y ffenestr. A chyd dywettit uot porthawr ar lys Arthur, nyt oed yr un; Glewlwyt Gauaeluawr oed yno hagen ar ureint porthawr, y arfoll gwesteywyr a phellennigyon, ac y dechreu eu hanrydedu, ac y uenegi udunt moes y llys a'e deuawt — yr neb a dylyei uynet yr neuad neu yr ystafell, oe uenegi idaw, a'r neb a dylyei letty, oe uenegi idaw.",
          e: "The emperor Arthur was at Caer Llion on Usk. One day he was sitting in his chamber, and with him were Owain son of Urien, and Cynon son of Clydno, and Cei son of Cynyr; and Gwenhwyfar and her handmaids were sewing by the window. And though it might be said that there was a porter at Arthur's court, there was none — yet Glewlwyd Mighty-Grasp was there in a porter's office, to receive guests and travellers from afar, to begin their honouring, and to make known to them the usage and the custom of the court: whoever should rightly go to the hall or to the chamber, to direct him; and whoever was owed a lodging, to direct him.",
          n: "The romance opens not at the fountain but at the hearth — the Welsh frame is a tale told <em>at</em> court before it is a tale lived in the wilderness. <strong>Caer Llion ar Wysc</strong> (Caerleon-on-Usk, Monmouthshire) is the Galfridian capital of Arthur's Britain. <strong>Glewlwyd Gafaelfawr</strong> (\"Mighty-Grasp\") is Arthur's porter here as he is in <em>Culhwch ac Olwen</em> — but note the wry inversion: Culhwch's Glewlwyd guards a gate that must not be passed, while here \"there was no porter\" and his office is pure hospitality. The same figure, the opposite function: the comparative seam this site is built to show." },

        { w: "Ac ym perued llawr yr ystafell yd oed yr amherawdyr Arthur yn eisted, ar demyl o irurwyn a llenn o bali melyngoch ydanaw, a gobennyd a'e dudet o bali coch dan penn y elin. Ar hynny y dywawt Arthur: \"Ha wyr,\" heb ef, \"pei nam goganewch, mi a gysgwn tra uewn yn aros uy mwyt; ac ymdidan a ellwch chwitheu, a chymryt ysteneit o ued a golwython y gan Gei.\" A chysgu a oruc yr amherawdyr.",
          e: "And in the middle of the chamber-floor sat the emperor Arthur, on a dais of fresh rushes with a covering of red-and-yellow brocade spread beneath him, and a cushion in a case of red brocade under his elbow. At that Arthur said: \"Men,\" he said, \"if you will not think the less of me for it, I would sleep while I wait for my meat; and you can talk among yourselves, and have a flagon of mead and some collops from Cei.\" And the emperor slept.",
          n: "The flame-coloured satin and the king who dozes while his men talk is a deliberately domestic, un-heroic frame — the marvels are about to be reported, not performed. The detail of <em>irvrwyn</em>, fresh-cut rushes strewn for a seat, is the texture of a real medieval Welsh hall." },

        { w: "A gofyn a oruc Cynon uab Clydno y Gei yr hyn a adawssei Arthur udunt. \"Minneu a uynnaf yr ymdidan da a edewit y minneu,\" heb y Cei. \"Iawn,\" heb y Cynon, \"tecaf yw itti wneuthur edewit Arthur yn gyntaf; ac odyna yr ymdidan goreu a wypom ninneu, ni a'e dywedwn itti.\" Ynet a oruc Cei yr gegin ac yr uedgell, a dyuot ac ysteneit o ued gantaw, ac eurgawc, a lloneit y dwrn o uereu yn dwyn golwython arnunt.",
          e: "And Cynon son of Clydno asked Cei for what Arthur had promised them. \"But I will have the good tale that was promised to me,\" said Cei. \"It is only fair,\" said Cynon, \"that you keep Arthur's promise first; and then the best tale we know, we will tell you.\" So Cei went to the kitchen and the mead-cellar, and came back bearing a flagon of mead, and a golden goblet, and a fistful of skewers carrying broiled collops.",
          n: "<strong>Cei</strong> (the later Sir Kay) is already the court's sharp-tongued steward — bargaining for his story before he will serve the mead. The exchange is courtesy as friction: who owes whom, and in what order. It is the same Cei who, a moment later, will mock Owain; the Welsh tale lets the seneschal's edge show early." },

        { w: "Ac yna y bwytaassant y golwython, ac y dechreuassant yuet y med. \"Weithon,\" heb y Cei, \"amser yw ywch talu y minneu uy ymdidan.\" \"Cynon,\" heb yr Owein, \"tal di y Gei y ymdidan a dyly.\" \"Yn wir,\" heb y Cynon, \"hynaf wyt ti, a gwell ymdidanwr, a mwy a weleist o ryfedodeu; tal ditheu y Gei y ymdidan.\" \"Dechreu dy hun,\" heb yr Owein, \"a'r goreu a wypych.\" \"Mi a'e gwnaf,\" heb y Cynon.",
          e: "And then they ate the collops and began to drink the mead. \"Now,\" said Cei, \"it is time you paid me my tale.\" \"Cynon,\" said Owain, \"pay Cei the tale that is his due.\" \"Truly,\" said Cynon, \"you are the elder, and the better teller, and you have seen more marvels than I — you pay Cei his tale.\" \"Begin yourself,\" said Owain, \"with the best you know.\" \"I will,\" said Cynon.",
          n: "The hand-off from Owain to Cynon is the hinge of the frame: the tale we are about to hear (Movement II) is <em>Cynon's defeat</em>, and it is the very adventure Owain will then ride out to avenge and complete. The romance's deep structure is a relay — one man's humiliating story becomes another man's quest. Cynon's narration begins in the next movement." },
      ],
    },

    {
      title: "II. Cynon's tale — the keeper of beasts, the fountain, and the Black Knight",
      segments: [
        { w: "Namyn vn mab mam a thad oeddwn i, a drythyll oeddwn, a mawr oedd fy ryfic; ac ny thybygwn yn y byt a orffei arnaf o neb ryw gamhwri. A gwedy daruot im gorfot ar bob camhwri o'r a oedd yn vn wlat a mi, ymgyweiraw a wneuthum a cherdet eithafoedd byt a diffeithwch. Ac yn y diwed dywannu a wneuthum ar y glynn teckaf yn y byt, a gwyd gogyfuch yndaw, ac auon redegawc ar hyt y glynn, a ffordd gan ystlys yr auon. A cherdet y ffordd a wneuthum hyt hanner dyd, a'r parth arall a gerdeis hyt pryt nawn; ac yna y deuthum y uaes mawr, ac yn niben y maes yd oedd kaer uawr lywychedic, a gweilgi yn gyfagos yr gaer. Ac y'r gaer y deuthum; ac nachaf y gwelwn deu was penngrych velyn, a ractal eur am penn pob un onadunt, a pheis o bali melyn am bob un, a gwaegeu eur yn kaeu am eu traet; a bwa o asgwrn eliffant yn llaw pob un, a'e saetheu o asgwrn moruil gwedy eu hadeinyaw ag adaned pawn, a phenneu eur arnunt; ac wynt yn saethu eu kylleill.",
          e: "I was the only son of my mother and father, and I was headstrong, and great was my pride; I did not believe there was anything in the world that could master me in any feat. And when I had overcome every trial there was in my own land, I made myself ready and rode to the ends of the earth and its wastes. And at last I came upon the fairest valley in the world, full of trees of even height, with a running river along it and a path beside the river. I followed the path till midday, and the rest of the valley till the hour of nones; and then I came out onto a great plain, and at the plain's end stood a great shining castle, with a torrent hard by it. I came up to the castle — and there were two youths with curling yellow hair, a gold band round the head of each, a tunic of yellow brocade on each, and gold clasps fastening their shoes; in the hand of each a bow of elephant-ivory, their arrows shafted with whalebone, fletched with peacock feathers and tipped with gold; and they were casting their gold-bladed knives at a mark.",
          n: "Cynon's adventure is the romance-quest in its purest grammar: exhaust the challenges of home, ride out to <em>eithafoedd byt a diffeithwch</em> — \"the ends of the earth and the wilderness\" — and find the marvel. He plays the part Chrétien gives to Calogrenant, whose identical defeat opens <em>Yvain</em>. The youths are a luxury-catalogue — ivory, whalebone, peacock, gold — the standard medieval signal that one has crossed into an Otherworld-touched court." },

        { w: "Ac ennyd y wrthunt y gwelwn wr penngrych velyn yn y dewred, a'e uaryf yn newyd eilliaw, a pheis a mantell o bali melyn ymdanaw. A phan y gweleis i ef, dynessau a wneuthum attaw a chyfarch gwell idaw; ac rac dahet y wybot, kynt y kyfarchawd ef well y mi no mi idaw ef. A dyuot gyt a mi a oruc parth ar gaer. Ac nyt oedd gyfanhed yn y gaer namyn a oedd yn vn neuad; ac yno yd oedd pedeir morwyn ar hugeint yn gwniaw pali wrth y ffenestr. A hynn a dywedaf ytti, Gei: tebic oedd gennyf vot yn degach yr hacraf onadunt no'r uorwyn deckaf a weleist ti eiryoet yn Ynys Prydein; a'r anardaf onadunt, hardach oedd no Gwenhwyfar gwreic Arthur pan vu hardaf eiryoet, duw Nadolic neu duw Pasc wrth offeren. A chyuodi a orugant ragof; a chwech onadunt a gymerth vy march ac a'm diarchenwys, a chwech ereill a gymerth vy arueu ac a'e golchassant yn lan, a'r trydydd chwech a dodes llieineu ar y byrdeu ac a arlwyassant uwyt, a'r pedwyryd chwech a diodes vy lludedic wisc ac a dodes gwisc arall ymdanaf. Ac eisted a orugam; ac nyt oedd lestyr yn gwassanaethu namyn eur neu aryant neu vueil. A bwyta a orugam hyt hanner bwyt, ac ny dywawt nac y gwr nac un o'r morynyon un geir wrthyf hyt yna.",
          e: "A little way off from them I saw a man in his prime, his beard newly shaven, in a tunic and mantle of yellow brocade. When I saw him I went up and greeted him; and so gracious was his breeding that he returned my greeting before I had well finished it. He came with me toward the castle. There were no dwellers in it but those in one hall, and there sat four-and-twenty maidens embroidering brocade by the window. And I tell you this, Cei: the plainest of them was lovelier than the fairest maid you ever saw in the Island of Britain, and the least comely of them was comelier than Gwenhwyfar, Arthur's wife, at her fairest ever, at Mass on Christmas Day or Easter. They rose at my coming: six took my horse and unshod me, six took my arms and washed them bright, six laid cloths on the tables and set out food, and six stripped off my travel-worn clothes and dressed me afresh. We sat; and no vessel served at the table but of gold or silver or buffalo-horn. We ate till the meal was half done, and neither the man nor any maiden spoke a word to me until then.",
          n: "The doubled, ascending courtesy — twenty-four maidens, each task done by a set of six — is the Welsh romance's way of marking a place finer than the waking world without making it overtly magical, the same restraint <em>Pwyll</em> uses for the court of Annwn. The silence until the meal is half over is a point of manners, not menace: it would be discourteous to question a guest before he is fed." },

        { w: "A phan vu debic gan y gwr vot yn well gennyf ymdidan no bwyta, gofyn a oruc ym pa ryw wr oeddwn. Ac yna y menegeis i y'r gwr pwy oeddwn, a'r kerdet oedd arnaf, a dywedut vy mot yn keissaw a orffei arnaf, neu vinneu a orffei ar bawb. Ac edrych a oruc y gwr arnaf a gwenu, a dywedut: \"Bei na thybyckwn dyuot gormod o ouut itt, mi a uanagwn itt yr hynn yd wyt yn y geissaw.\" A chymryt tristit a goueileint a wneuthum am hynny; ac adnabot a oruc y gwr hynny, a dywedut: \"Kanys gwell yw gennyt menegi o honaf itt dy aflles no'th les, mi a'e managaf itt. Kwsc yma heno, a chyfot yn vore, a chymer y ffordd ar hyt y dyffryn uchot yny delych y'r koet y deuthost trwydaw; ac yn rynnawd yn y koet y kyferfyd gwahanffordd a thi ar y tu deheu, a cherda honno yny delych y lannerch uawr gysgodawc a thwmpath y'm perued. Ac y gweli wr du mawr ar benn y twmpath, nyt llei no deu wr o wyr y byt hwnn; ac vn troet yssydd idaw, ac vn llygat y'm perued y dalcen, a gwialen haearn yn y law. A gofyn idaw y ffordd, ac ef a'e dengys itt.\"",
          e: "When the man saw that I would rather talk than eat, he asked me what kind of man I was. Then I told him who I was, and the errand I was on, and said I was seeking whether anything could master me, or I could master all. He looked at me and smiled, and said: \"If I did not fear to bring you too much grief, I would show you the very thing you seek.\" At that I grew downcast and sorrowful; and seeing it, he said: \"Since you would rather I showed you your loss than your gain, I will. Sleep here tonight, rise early, and take the road up the valley till you reach the wood you came through; a little way into the wood a side-track branches off on the right — follow it till you come to a great sheltered glade with a mound in the middle. On the mound you will see a great black man, no smaller than two of the men of this world; he has but one foot, and one eye in the middle of his forehead, and an iron staff in his hand. Ask him the way, and he will show it to you.\"",
          n: "The host's careful phrasing — to show \"your loss rather than your gain\" — frames the fountain not as a prize but as a humbling. The romance is honest from the start that this adventure ends in shame; the wonder is that Owain will later ride the same road to a different end." },

        { w: "A hir uu gennyf y nos honno. A thrannoeth y kyuodeis ac ymgyweiraw, a mynet rac vy mronn ar hyt y dyffryn y'r koet, a chymryt y wahanffordd a dangossei y gwr ym, yny deuthum y'r llannerch. Ac yno yd oedd teir gweith mwy o anifeileit gwylltion no'r a dywedassei y gwr ym. A'r gwr du a oedd yn eisted ar benn y twmpath; mawr oedd ef, a mwy o lawer noc y dywedassei y gwr ym. A gofyn a wneuthum idaw pa allu a oedd idaw ar yr anifeileit hynny. \"Mi a'e dangosaf itt, was bychan,\" heb ef. A chymryt y wialen yn y law, a tharaw karw a hi yny vraeawd; ac ar y vrefiat, llyma yr anifeileit yn dyuot mor amyl a'r ser yn yr awyr, yny oedd gyfyng ym y seuyll yn y llannerch y'm plith. Ac edrych a oruc arnunt, ac erchi udunt uynet y bori; a gostwng eu penneu a wnaethant ac y wneuthur idaw gwarogaeth, megys y gwna dynyon ufyd y'w harglwyd. Ac yna y dywawt y gwr du wrthyf: \"A wely di, was bychan, y gallu yssydd ym ar yr anifeileit hynn?\"",
          e: "Long that night seemed to me. Next morning I rose and made ready and went on up the valley to the wood, and took the side-track the man had shown me, till I came to the glade. And there were three times more wild beasts than he had told me. The black man sat on the mound — huge, and far bigger than I had been told. I asked him what power he had over those beasts. \"I will show you, little man,\" he said. He took the staff in his hand and struck a stag with it till it brayed; and at its braying, here came the beasts thronging, thick as the stars in the sky, till there was scarcely room for me to stand among them in the glade. He looked at them and bade them go and graze; and they bowed their heads and did him homage, as obedient men do their lord. Then he said to me: \"Do you see, little man, the power I have over these beasts?\"",
          n: "The one-eyed, one-footed keeper of beasts (Thompson F460, the wild herdsman) is the oldest thing in the tale — a threshold-guardian out of the pre-Christian Otherworld, lord of the animals, who gives directions but no comfort. He is the Welsh cousin of the giant herdsmen of <em>Culhwch</em>, and the romance's bridge between the courtly luxury of the castle and the raw magic of the fountain." },

        { w: "Ac yna y gofynneis i idaw y ffordd; a rwithyaw a oruc yn arw wrthyf, a gofyn ym pa le yd awn. \"Kymer,\" heb ef, \"y ffordd a el parth a phenn y llannerch, a dring y vryn coediawc uchot yny delych y'w benn; ac yno y kymer ti vaes mawr megys dyffryn, ac y'm perued y maes pren mawr, a'e geigeu yn lasach no'r glassaf o'r ffynyddwyd. Ac y dan y pren hwnnw y mae ffynnawn, ac yn ymyl y ffynnawn y mae llech varmor, ac ar y llech y mae bowl aryant wrth gadwyn aryant, hyt na ellir eu gwahanu. A chymer y bowl a bwrw bowleit o'r dwfyr ar y llech; ac yna y klywy twryf mawr, yny tebyckych vot nef a daear yn crynu gan y dwrf. Ac yn ol y twryf y daw kawat, ac odit ny bo bwrw o genllysc; ac wedy y gawat, glaw teg a vyd, ac nyt oes deilen ar y pren ny dyckir ymeith gan y gawat. Ac yna y daw kawat o adar y'r pren, ac ny chiglyf yn dy wlat dy hun gerdoryaeth gystal a'r a ganant hwynt. A phan vych digrifaf gennyt wrandaw arnunt, llyma duchan a chwynuan yn dyuot ar hyt y dyffryn attat; a marchawc a wely ar uarch purdu, a gwisc o bali purdu ymdanaw, a llumman o bali du ar y baladyr; ac yth gyrch mor gynt ac y galler. A chyt ffoych racdaw ef a'th oddiwed, ac o seuy y'w erbyn — marchawc wyt ti — ef a'th gad ar dy droet. Ac ony chefy ouut yn yr antur honno, nyt reit itt geissaw ouut tra vych vyw.\"",
          e: "Then I asked him the way; and he turned rough with me, and asked where I would go. \"Take,\" he said, \"the path that leads to the head of the glade, and climb the wooded hill above till you reach its top; there you will come on a great open ground like a valley, and in the middle of it a tall tree, its branches greener than the greenest pine. Under that tree is a spring, and beside the spring a slab of marble, and on the slab a silver bowl chained with a silver chain, so that the two cannot be parted. Take the bowl and throw a bowlful of the water on the slab; and then you will hear a great crash of thunder, till you think heaven and earth are shaking with it. After the thunder comes a downpour — and it will scarcely fail to be of hailstones — and after the shower, fair weather; but not a leaf will be left on the tree. Then a flock of birds will settle on the tree, and never in your own land have you heard music to match their song. And just when their song delights you most, here will come a moaning and a wailing up the valley toward you, and you will see a knight on a jet-black horse, in jet-black brocade, a black pennon on his lance; and he will charge you as fast as he can. If you flee, he will catch you; and if you stand to meet him — mounted knight though you are — he will leave you on foot. And if you do not find trouble in that adventure, you need never seek trouble as long as you live.\"",
          n: "The storm-fountain (Thompson D2143.1, tempest made by magic) is the engine of the whole romance — a weather-rite bound to a place, with a guardian who must be killed to be succeeded; Chrétien's cousin is the fountain of Barenton in Brocéliande. The bowl chained to the slab is the trigger; the birdsong and the wailing knight are the two faces of the place, its beauty and its reckoning." },

        { w: "A cherdet y ffordd a wneuthum hyt benn y vryn, ac yno y keueis bop peth megys y dywedassei y gwr du ym. A dyuot at y pren a wneuthum; ac y dan y pren y gweleis y ffynnawn, ac yn ymyl y ffynnawn y llech varmor, a'r bowl aryant wrth y gadwyn. A chymryt y bowl a wneuthum a bwrw bowleit o'r dwfyr ar y llech; ac ar hynny, llyma y twryf yn dyuot, mwy o lawer noc y tebygassei y gwr du, ac yn ol y twryf y kawat. A diheu yw gennyf, Gei, nat oes na dyn nac anifail a'r a vo allan a dycko y gawat honno yn vyw, kanys nyt arhoes vn o'r kesseir hynny na chnawt na chroen yny ddel y'r asgwrn. A throi tin vy march wrth y gawat a wneuthum, a dodi pic vy ysgwyt ar benn a mwnwgyl vy march, a dala y rann uchaf o honaw uch vy mhenn vy hun; ac uelly y deleis y gawat. A phan edrycheis ar y pren, nyt oedd vn deilen arnaw; a thengin teg a wnaeth yr awyr. Ac ar hynny llyma yr adar yn disgynnu ar y pren ac yn canu; a diheu yw gennyf, Gei, na chigleu i eiryoet gerdoryaeth gystal a honno na chynt na gwedy.",
          e: "I rode on to the top of the hill, and there found everything as the black man had said. I came to the tree, and beneath it the spring, and beside it the marble slab, and the silver bowl on its chain. I took the bowl and threw a bowlful of water on the slab; and at once the thunder came, far greater than the black man had led me to expect, and after the thunder the downpour. And truly, Cei, I believe there is neither man nor beast caught in the open that could live through that shower — for not one of those hailstones was stopped by flesh or skin until it reached the bone. I turned my horse's hindquarters to the storm and set the boss of my shield over his head and neck, and held the upper part of it over my own head; and so I bore out the shower. And when I looked at the tree there was not a leaf on it; and the sky cleared fair. And then the birds came down on the tree and sang; and truly, Cei, I never heard music to equal it, before or since.",
          n: "Note the practical, soldierly detail of how Cynon survives the hail — the boss of the shield turned to the storm over the horse's head. The Welsh romance keeps its marvels braced against bodily fact: the magic is overwhelming, but a knight still has to put his shield in the right place." },

        { w: "A phan oeddwn ddigrifaf gennyf wrandaw ar yr adar, llyma duchan yn dyuot ar hyt y dyffryn attaf, a dywedut: \"A varchawc, beth a'th dyckwys di yma? Pa drwc a wneuthum i itt, yny gwnelut ti ym i ac y'm kyuoeth y peth a wnaethost ti hediw? Pony wdost ti na edewis y gawat hediw yn vy nherfyn na dyn nac anifail yn vyw o'r a gauas allan?\" Ac ar hynny llyma varchawc ar uarch purdu, a gwisc o bali purdu ymdanaw, a thabar o bali du amdanaw. Ac ymgyrchu a orugam; a chan vot y rwyf yn greulawn, nyt hir y buum kyn vy mwrw y'r llawr. Ac yna y dodes y marchawc baladyr trwy ffrwyn vy march, ac y kerdawd ymeith a'r ddeu varch, gan vyngadu inneu yno; ac ny chymerth gymeint a'm karcharu, na'm hyspeilaw o'm harueu. A dyuot drachefyn y'r ffordd y deuthum a wneuthum; a phan deuthum y'r llannerch lle yd oedd y gwr du, mi a gyffessaf itt, Gei, ryued yw na thodeis i yn lyn o'r kywilyd a gefeis gan watwar y gwr du. A'r nos honno y deuthum y'r un gaer y buaswn y nos kynt; ac y'm digrifach y bum y nos honno no'r nos gynt. A thrannoeth pan gyuodeis, llyma balurei gwineu kalch-las yn barawt ym, a'i ffroeneu yn gochon megys ysgarlat; ac wedy ymarfogi a gadu vy mendith yno, y deuthum hyt vy llys vy hun. A'r march hwnnw a delis ym o hyt; ac ny rown ef am y goreu yn Ynys Prydein.",
          e: "And just when their song delighted me most, here came a wailing up the valley toward me, saying: \"Knight, what brought you here? What wrong did I ever do you, that you should do to me and to my realm what you have done today? Do you not know that today's shower has left neither man nor beast alive within my borders that was caught in the open?\" And with that, here was a knight on a jet-black horse, in jet-black brocade, a black surcoat about him. We charged each other; and because the onset was savage, it was not long before I was thrown to the ground. Then the knight ran the shaft of his lance through my horse's bridle-rein and rode off with both horses, leaving me there; he did not so much as trouble to take me prisoner or strip me of my arms. I went back the way I had come; and when I reached the glade where the black man was, I confess to you, Cei, it is a wonder I did not melt into a pool for the shame of his mockery. That night I came to the same castle as the night before, and was made more welcome that night than the first; and none of them said a word of my going to the fountain, nor did I. And next morning when I rose, there stood ready for me a bay palfrey, calx-grey, its nostrils red as scarlet; and after arming and leaving my blessing there, I came home to my own court. That horse I have to this day — and I would not give him for the best palfrey in the Island of Britain.",
          n: "The defeat is total, and humiliating in a precise, courtly way: the Black Knight does not even trouble to capture or despoil Cynon — the deepest insult is to be judged not worth the keeping. Yet his hosts, with perfect tact, never mention his failure, and send him home better mounted than he came. The red-nostrilled palfrey is the castle's grace laid over the fountain's shame." },

        { w: "Ac yn wir, Gei, ny chyffessawd dyn eiryoet antur kymeint y waradwyd ac y kyffesseis i; a ryued yw gennyf na chigleu na chynt na gwedy son am y peth hwnn, ac y bot yn dyuot o vewn kyuoeth Arthur, heb dyuot neb arall arnaw. \"Weithon,\" heb yr Owein, \"pony bei da uynet y geissaw kaffel y lle hwnnw?\" \"Myn llaw vy nghyfaill,\" heb y Gei, \"mynych y dywedy a'th davawt yr hyn ny chywirit a'th weithret.\" \"Yn wir,\" heb y Wenhwyfar, \"gwell y bydei dy grogi di, Gei, no dywedut geireu mor anghyweir a hynny wrth wr fal Owein.\" \"Myn llaw vy nghyfaill, arglwydes,\" heb y Gei, \"ny dywedeist ti uoliant well y Owein no minneu.\" Ac ar hynny y deffroes Arthur, a gofyn a gysgassei dim. \"Do, arglwyd,\" heb yr Owein, \"talym.\" \"Ai amser yw in vynet y vwyta?\" \"Yw, arglwyd,\" heb yr Owein. Ac yna y kanwyt y korn y ymolchi, ac yd aeth y brenhin a'r holl deulu y vwyta.",
          e: "\"And truly, Cei, never did a man confess an adventure so much to his own shame as I have confessed; and it is a wonder to me that I have never heard, before or since, any word of this thing — that it should lie within Arthur's own dominion, and no one else light upon it.\" \"Now,\" said Owain, \"would it not be a good thing to go and seek out that place?\" \"By the hand of my friend,\" said Cei, \"often do you say with your tongue what you would not make good with your deeds.\" \"Truly,\" said Gwenhwyfar, \"you would be better hanged, Cei, than speak words so uncourteous to a man like Owain.\" \"By the hand of my friend, lady,\" said Cei, \"your praise of Owain was no greater than mine.\" And with that Arthur awoke, and asked whether he had slept at all. \"You have, lord, a while,\" said Owain. \"Is it time for us to go to meat?\" \"It is, lord,\" said Owain. Then the horn was sounded for the washing, and the king and all the household went to eat.",
          n: "The frame snaps shut: Cynon's shame becomes Owain's resolve, and Cei — true to form — mocks the resolve before it can be acted on, earning Gwenhwyfar's sharpest line. The sleeping king wakes knowing nothing of the tale that will send one of his knights out at the next dawn. Owain's quest (Movement III) begins in silence, told to no one." },
      ],
    },

    {
      title: "III. Owain rides the same road — the slain Black Knight and the portcullis",
      segments: [
        { w: "A gwedy daruot bwytta, diflannu a oruc Owein ymeith, a dyuot y'w letty a pharattoi y varch a'e arueu. A phan welas ef y dyd drannoeth, gwisgaw y arueu a oruc ac yscynnu ar y uarch, a cherdet racdaw eithafoedd byt a diffeith vynyded; ac yn y diwed y dywanawd ar y glynn a uanagassei Cynon idaw, fal y gwydyat yn hyspys panyw hwnnw oedd. A cherdet a oruc ar hyt y glynn gan ystlys yr auon yny doeth y'r dyffryn; a'r dyffryn a gerdawd yny welei y gaer, a pharth a'r gaer y deuth. Sef y gwelei y gweisson yn saethu eu kylleill yn y lle y gwelsei Cynon, a'r gwr melyn bieuoedd y gaer yn seuyll gyt eu llaw. A phan ytoedd Owein yn mynnu kyfarch gwell y'r gwr melyn, kyfarch gwell a oruc y gwr y Owein gynt.",
          e: "And when the meal was over, Owain slipped quietly away, went to his lodging, and made ready his horse and his arms. And when the next day broke, he put on his armour, mounted his horse, and rode out across the ends of the earth and desert mountains; and at last he came down into the valley Cynon had described to him, and knew for certain it was the one. He rode along the valley by the side of the river until he reached the plain, and crossed the plain till he saw the castle, and came toward it. And there were the youths casting their knives in the place where Cynon had seen them, and the yellow-clad man who owned the castle standing beside them. And just as Owain made to greet the yellow man, the man greeted Owain first.",
          n: "Owain's quest begins exactly as Cynon's did — the same valley, the same youths, the same gracious host — and the romance leans on the repetition: this is a tale of one road travelled twice, the second time to a different end. He tells no one at court; he simply <em>diflannu</em>, vanishes, after the meal. The Welsh hero acts where Cynon only spoke." },

        { w: "A dyuot yn y vlaen parth a'r gaer; ac ef a welei yr ystauell yn y gaer. A phan deuth y'r ystauell, ef a welei y morynyon yn gwniaw pali ymywn kadeireu eureit; a hoffach o lawer oedd gan Owein eu tecket a'e hardet noc y dywawt Cynon idaw. A chyuodi a wnaethant y wassanaethu Owein mal y gwassanaethassynt Gynon; a hoffach uu gan Owein eu porthiant no chan Gynon. Ac am hanner bwytta, gofyn a oruc y gwr melyn y Owein pa gerdet oedd arnaw; ac y dywawt Owein gwbyl o'e gerdet idaw, ac y ymgeissaw a'r marchawc yssydd yn gwarchadw y ffynnawn y mynnwn vy mot. A gwenu a oruc y gwr melyn, a bot yn anhawd gantaw menegi y Owein y kerdet hwnnw mal y bu anhawd gantaw y uenegi y Gynon; ac eissoes menegi a oruc y Owein gwbyl. Ac y gysgu yd aethant.",
          e: "He went forward toward the castle, and saw the chamber; and when he came into it, there were the maidens embroidering brocade in chairs of gold — and their beauty and grace pleased Owain far more than Cynon had told him. They rose to wait on Owain as they had on Cynon, and their service pleased Owain more than it had Cynon. And when the meal was half done, the yellow man asked Owain what his errand was; and Owain told him the whole of it: that he was come to seek the knight who guards the fountain. The yellow man smiled, and was as loath to point that adventure out to Owain as he had been with Cynon; yet he told him the whole of it. And they went to sleep.",
          n: "Everything is the same, and everything is a little finer — the maidens lovelier, the welcome warmer — as if the place itself rewards the man who comes to act rather than merely to wander. The host's reluctance is unchanged: he still names the fountain a thing of loss, not gain." },

        { w: "A'r bore drannoeth y bu barawt march Owein gan y morynyon; a cherdet a oruc Owein racdaw yny deuth y'r llannerch yd oedd y gwr du yndi. A hoffach uu gan Owein meint y gwr du no chan Gynon; a gofyn ffordd a oruc Owein y'r gwr du, ac ynteu a'e menegis. A cherdet a oruc Owein y ffordd fal Cynon, yny doeth yn ymyl y pren glas; ac ef a welei y ffynnawn, a'r llech yn ymyl y ffynnawn, a'r kawc arni. A chymryt y kawc a oruc Owein a bwrw kawgeit o'r dwfyr ar y llech. Ac ar hynny, nachaf y twryf, ac yn ol y twryf y gawat — mwy o lawer noc y dywedassei Cynon oeddynt. A gwedy y gawat, goleuhau a oruc yr awyr; a phan edrychawd Owein ar y pren, nyt oedd vn dalen arnaw. Ac ar hynny, nachaf yr adar yn disgynnu ar y pren ac yn canu.",
          e: "Next morning Owain's horse was made ready by the maidens; and he rode on until he came to the glade where the black man was. The black man's size pleased Owain more than it had Cynon; he asked the black man the way, and he showed it. Owain rode the road as Cynon had, until he came beside the green tree; and he saw the fountain, and the slab beside the fountain, and the bowl upon it. Owain took the bowl and threw a bowlful of water on the slab; and at once, here came the thunder, and after the thunder the shower — greater by far than Cynon had told. And after the shower the sky cleared; and when Owain looked at the tree, there was not a leaf on it. And then the birds came down on the tree and sang.",
          n: "Owain meets the keeper of beasts with relish, not dread — \"his size pleased Owain\" where it had merely awed Cynon. The same wonders that humbled the first knight are, to the second, the furniture of an adventure he has chosen; and the storm is greater for Owain, because the tale is now in earnest." },

        { w: "A phan oedd digrifaf gan Owein gerd yr adar, ef a welei varchawc yn dyuot ar hyt y dyffryn; ac erbynnyeit a oruc Owein, ac ymwan ac ef yn drut. A thorri y deu baladyr a orugant, a dispeilaw deu gledyf a wnaethant ac ymgyfogi. Ac ar hynny, Owein a drewis dyrnawt ar y marchawc trwy y helym a'r pennffestin a'r penngwch porffwrin, a thrwy y kroen a'r kig a'r asgwrn, yny glwyfawd ar yr emennyd. Ac yna adnabot a oruc y marchawc duawc ry gaffel dyrnawt angheuawl o honaw; ac ymchoelut penn y varch a oruc a ffo.",
          e: "And just when the birds' song delighted Owain most, he saw a knight coming up the valley; Owain received him, and clashed with him fiercely. They broke both their lances, drew their two swords, and fell to hewing. And then Owain dealt the knight a blow through his helmet and his headpiece and his purple coif, and through skin and flesh and bone, until it wounded the very brain. And then the black knight knew he had taken a mortal blow; he turned his horse's head and fled.",
          n: "Where Cynon was unhorsed at the first onset, Owain breaks his lance, draws his sword, and lands the killing stroke — the same encounter, the opposite outcome, told in nearly the same words. The Welsh romance measures its hero against the man who failed: Owain is what Cynon was not. And the mortal wound is itself the engine of the plot — it makes the widow Owain will come to love." },

        { w: "Ac ymlit a oruc Owein, ac nyt ymgaffei Owein a'e vaedu a'r cledyf — nyt oedd bell idaw ynteu. Ac ar hynny Owein a welei gaer uawr lywychedic, ac y porth y gaer y deuthant. Ac ellwng y marchawc duawc a wnaethpwyt ymywn; ac ellwng dor dyrchafat a wnaethpwyt ar Owein. A honno a'e medrawd o dis y bardwgyl y kyfrwy, yny dorres y march yn deu hanner trwydaw, a throelleu yr ysparduneu gan sodleu Owein; ac yny gerda y dor hyt y llawr. A throelleu yr ysparduneu a dryll y march y maes, ac Owein a'r dryll arall o'r march yrwng y dwy dor; a'r dor ymywn a gaewyt, fal na allei Owein vynet o dyno. Ac yng nghyfyng gyngor yd oedd Owein.",
          e: "Owain gave chase, never quite able to reach him with the sword — yet never far behind. And then Owain saw a great shining castle, and they came to the castle gate. The black knight was let in; and a portcullis was dropped on Owain. It caught him just behind the saddle-bow, and cut the horse clean in two through the middle, and sheared off the rowels of the spurs at Owain's heels; and the gate drove on down to the floor. The spur-rowels and the outer half of the horse were left outside; and Owain, with the other half of the horse, was caught between the two gates — and the inner gate was shut, so that he could not get away. And Owain was in a sore strait.",
          n: "The portcullis-trap — the dead man's castle closing on his killer — is one of the most cinematic moments in the corpus: the horse sheared in two behind the saddle, the spur-rowels clipped from Owain's very heels. He has won the combat and ridden straight into a cage. The movement ends here, on the trap; the rescue, the ring, and the lady he will love all wait on the far side of that inner gate." },
      ],
    },

    {
      title: "IV. Luned's ring, the funeral, and the Countess of the Fountain",
      segments: [
        { w: "Ac fal yd oedd Owein felly, sef y gwelei trwy gyffwrdd y dor heol gyfarwyneb ac ef, ac ystret o tei o bop tu yr heol. Ac ef a welei vorwyn benngrech velen, a ractal eur am y phenn, a gwisc o bali melyn ymdanei, a dwy wintas o gordwal brith am y thraet. Ac yn dyuot y'r porth, ac erchi agori a oruc. \"Duw a wyr, unbennes,\" heb yr Owein, \"na ellir agori itti o dyma, mwy noc y gelly ditheu waret y minneu o dyna.\" \"Duw a wyr,\" heb y vorwyn, \"oedd dyhed mawr na ellit gwaret itti; ac oedd iawn y wreic wneuthur da itti, kanys ny weleis i eiryoet was well no thidi wrth wreic. O bei gares itt, goreu kar gwreic oedut; o bei orderch itt, goreu orderch oedut. Ac wrth hynny,\" heb hi, \"yr hynn a allwyf o waret itti, mi a'e gwnaf.\"",
          e: "And as Owain was in this strait, he could see, through a chink of the gate, a street facing him with a row of houses on each side. And he saw a maiden with curling yellow hair and a gold frontlet on her head, a dress of yellow brocade about her, and two boots of mottled cordwain on her feet. She came to the gate and asked that it be opened. \"God knows, lady,\" said Owain, \"I can no more open it to you from here than you can free me from there.\" \"God knows,\" said the maiden, \"it would be a great pity that you could not be freed; and it would be right for a woman to do you good, for I never saw a man more faithful in the service of ladies than you. As a kinsman you would be the best of kinsmen; as a lover, the best of lovers. And therefore,\" she said, \"whatever I can do to free you, I will.\"",
          n: "This is <strong>Luned</strong>, the romance's cleverest figure, entering at the moment of greatest helplessness — the hero caged, the maid his only way out. Her praise (\"best of lovers, best of kinsmen\") is also her stated motive: she helps Owain because he has been faithful in the service of ladies, the courtly virtue the tale most prizes. In Chrétien she is Lunete." },

        { w: "\"Cymer y vodrwy honn a dot am dy vys, a dot y maen hwnn ymywn dy law, a chae dy dwrn am y maen; a thra y kudyych ti ef, ef a'th gud ditheu. A phan hambwyllont hwy o'r lleon, y deuant wy y'th gyrchu di y'th dihennydyaw am y gwr; a gwedy na welont hwy dydi, drwc vyd gantunt. A minneu a vydaf ar yr esgynuaen racko y'th aros di; a thydi a'm gwely i, kany welwyf i dydi; a dyret titheu a dot dy law ar penn vy ysgwyd, ac yna y gwybydaf i dy dyuot titheu attaf i. A'r ffordd y delwyf i o dyno, dyret titheu gyt a mi.\" Ac ar hynny mynet a oruc o dyno y wrth Owein; ac Owein a wnaeth a erchis y vorwyn idaw oll. Ac ar hynny y deuth y gwyr o'r llys y geissaw Owein y dihenydu; a phan deuthant y geissaw, ny welsant dim namyn hanner y march, a drwc y daeth arnunt hynny. A diflannu a oruc Owein o'c eu plith, a dyuot at y vorwyn, a dodi y law ar y hyscwyd; a chychwyn a oruc hitheu racdi, ac Owein y gyt a hi, yny deuthant y drws llofft uawr deledyw.",
          e: "\"Take this ring and put it on your finger, and set the stone in your palm and close your hand on it; and as long as you hide it, it will hide you. And when they take counsel in there, they will come to fetch you out and put you to death for their lord's sake; and when they cannot find you, they will be grieved. I will wait for you on the horse-block over there; you will be able to see me, though I cannot see you. Come and lay your hand on my shoulder, and then I will know you have come to me; and the way I go from there, come you with me.\" And with that she went off from Owain; and Owain did all the maiden had told him. And then the men of the court came to seek Owain, to put him to death; and when they came to look, they found nothing but half the horse, and were grieved at it. And Owain vanished from among them, came to the maiden, and laid his hand on her shoulder; and she set off, and Owain with her, until they came to the door of a large and fair chamber.",
          n: "The <strong>ring of invisibility</strong> (Thompson D1361.17) is the romance's neatest magic — turn the stone in, close the hand, \"as long as you hide it, it will hide you.\" The Welsh plays on <em>kudyaw</em>, to hide: the concealing and the concealed change places. It is a woman's gift and a woman's plan; in this tale the hero survives by being led." },

        { w: "Ac agori y llofft a oruc y vorwyn, a dyuot ymywn, a chaeu y llofft a orugant. Ac edrych ar hyt y llofft a oruc Owein, ac nyt oedd yn y llofft un hoel heb y lliwaw a lliw gwerthuawr, ac nyt oedd un ystyllen heb delw eureit arnei yn amryual. A chynnu tan glo a oruc y vorwyn, a chymryt kawc aryant a dwfyr yndaw, a thwel o vliant gwynn ar y hyscwyd, a rodi dwfyr y ymolchi y Owein. A dodi bwrd aryant goreureit rac y vronn, a bliant melyn yn llieinn arnaw, a dyuot a'e ginyaw idaw. A diheu oedd gan Owein na welsei eiryoet vwyt ny welei yno digawn o honaw, eithyr bot yn well kyweirdeb y bwyt yno noc yn lle arall eiryoet; ac nyt oedd un llestyr yn gwassanaethu arnaw namyn llestri aryant neu eur. A bwytta ac yuet a oruc Owein yny oedd pryt nawn hir. Ac ar hynny, nachaf y clywynt diaspedein yn y gaer; a gofyn a oruc Owein y'r vorwyn pwy weidi yw hwnn. \"Dodi oleu ar y gwrda bieu y gaer,\" heb y vorwyn. Ac y gysgu yd aeth Owein; a gwiw oedd y Arthur dahet y gwely a wnaeth y vorwyn idaw, o yscarlat a gra a phali a syndal a bliant.",
          e: "The maiden opened the chamber, came in, and they shut it after them. And Owain looked about it: there was not a single nail in it not painted with rich colour, and not a single panel without sundry images in gold. The maiden kindled a charcoal fire, took a silver bowl with water in it and a towel of white linen on her shoulder, and gave Owain water to wash. She set before him a silver table gilt with gold, with yellow brocade for a cloth, and brought him his meal. And truly Owain thought he had never seen food there was not plenty of there — only the dressing of it was better than anywhere else ever; and no vessel served him but of silver or gold. Owain ate and drank until late in the afternoon; and then they heard a crying in the castle, and Owain asked what wailing it was. \"They are giving extreme unction to the nobleman who owns the castle,\" said the maiden. And Owain went to sleep; and worthy of Arthur was the bed the maiden made him — of scarlet and fur and brocade and sendal and fine linen.",
          n: "The painted chamber — every nail coloured, every panel imaged in gold — is the romance's interior of wonder, the counterpart to the storm outside. The place that traps Owain also keeps him like a king, while in another room its lord receives the last rites for the wound Owain gave him. The tale lets the two facts sit side by side without comment." },

        { w: "Ac am hanner nos y clywynt diaspedein girat. \"Pa ddiaspedein yw hwnn weithon?\" heb yr Owein. \"Y gwrda bieu y gaer yssyd uarw yr awr honn,\" heb y vorwyn. Ac am rynnawd o'r dyd y clywynt diaspedein a gweidi anueidrawl eu meint; a gofyn a oruc Owein pa ystyr yssyd yr gweidi hwnn. \"Mynet a chorff y gwrda bieu y gaer y'r llann,\" heb y vorwyn. A chyuodi a oruc Owein y vynyd a gwisgaw ymdanaw, ac agori ffenestr ar y llofft, ac edrych parth a'r gaer; ac ny welei nac ymyl nac eithaf yr lluoed yn llewni yr heolyd, a hynny yn llawn aruawc, a gwraged llawer y gyt ac wynt ar veirch ac ar draet, a chrefydwyr y dinas oll yn canu. Sef y tebygei Owein bot yr awyr yn diasbedain rac meint y gweidi a'r kyrn, a'r crefydwyr yn canu. Ac ymperued y llu hwnnw, sef yr elor, a llenn o vliant gwynn arnei, a physt kwyr yn llosgi yn amyl yn y chylch; ac nyt oedd un dyn dan yr elor lai no barwn kyuoethawc.",
          e: "And at midnight they heard a piteous crying. \"What crying is this now?\" said Owain. \"The nobleman who owns the castle has just died,\" said the maiden. And a little into the day they heard wailing and outcry beyond measure, and Owain asked what it meant. \"They are bearing the body of the castle's lord to the church,\" said the maiden. Owain rose and dressed, opened a window of the chamber, and looked toward the castle; and he could see neither the near edge nor the far of the hosts thronging the streets, all in full arms, with many women among them on horse and on foot, and all the clergy of the city singing. It seemed to Owain that the very sky rang with the loudness of the cries and the horns and the singing of the clergy. And in the midst of that throng was the bier, a pall of white linen upon it, and wax tapers burning thick about it; and there was no man bearing the bier of lower rank than a powerful baron.",
          n: "The funeral is the tale's great set-piece of crowd and sound — armed thousands, the women on horse and foot, the whole city's clergy singing till the sky rings. It is also a quiet structural irony: Owain watches, hidden and safe, the burial of the man he killed, in the castle that tried to kill him. The Welsh romance loves these layered ironies of vantage." },

        { w: "Ac ar ol y llu hwnnw y gwelei ef wreic velen a'e gwallt dros y dwy yscwyd, ac a gwaet briw amyl yn y brigeu, a gwisc o bali melyn ymdanei gwedy yr rwygaw, a dwy wintas o gordwal brith am y thraet. Ac ryued oedd na bei ysic penneu y byssed rac dycket y maedei y dwylaw y gyt; a hyspys oedd gan Owein na welsei ef eiryoet wreic kymryt a hi, bei tuei ar y ryw furyf iawn. Ac uch oedd y diaspat noc a oedd o dyn ac o gorn yn y llu. A phan welas ef y wreic, ennynu a oruc o'e charyat yny oedd gyflawn pob lle yndaw. A gofyn a oruc Owein y'r vorwyn pwy oedd y wreic. \"Duw a wyr,\" heb y vorwyn, \"gwreic y gellir dywedut idi y bot yn deckaf o'r gwraged, ac yn diweiraf, ac yn haelaf, ac yn doethaf, ac yn vonhedickaf. Vy arglwydes i yw honn racko, a Iarlles y Ffynnawn y gelwir, gwreic y gwr a ledeist ti doe.\" \"Duw a wyr,\" heb yr Owein, \"mae mwyhaf gwreic a garaf i yw hi.\" \"Duw a wyr,\" heb y vorwyn, \"na char hi dydi na bychydic na dim.\"",
          e: "And behind that host he saw a yellow-haired woman, her hair loose over her two shoulders and clotted with blood at the ends, a dress of yellow brocade about her, torn, and two boots of mottled cordwain on her feet. And it was a wonder the tips of her fingers were not bruised, so fiercely did she beat her two hands together. Owain was sure he had never seen a woman so lovely, had she been in her right guise. And her cry was louder than any man's or any horn's in the host. And when he saw the woman, love of her kindled in him until it filled every part of him. And Owain asked the maiden who the woman was. \"God knows,\" said the maiden, \"a woman of whom it may be said she is the fairest of women, and the chastest, and the most generous, and the wisest, and the most noble. She is my mistress yonder — the Countess of the Fountain she is called — the wife of the man you killed yesterday.\" \"God knows,\" said Owain, \"she is the woman I love best.\" \"God knows,\" said the maiden, \"she shall love you too — not a little.\"",
          n: "The hinge of the whole romance: Owain falls in love with the widow at the very moment of her grief — grief he caused. The Welsh does not flinch from the strangeness of it (\"the wife of the man you killed yesterday\"), and Luned's flat reply — <em>she shall love you, not a little</em> — turns the impossible into a plan. Love and killing are tied in one stroke; Luned's wit will untie them in the movement to come. This is the knot at the heart of Chrétien's <em>Yvain</em> too." },
      ],
    },

    {
      title: "V. Luned's embassy, the wedding, and the holding of the fountain",
      segments: [
        { w: "\"Mi a'e managaf,\" heb hi. \"Ti a wdost na ellir kynnal dy gyfoeth di namyn o vilwryaeth ac arueu; ac am hynny keis yn ebrwyd neb a'e kynhalyo.\" \"A pha ffordd y gallaf i hynny?\" heb yr iarlles. \"Managaf,\" heb y Lunet: \"ony elly di gynnal y ffynnawn, ny elly gynnal dy gyfoeth; ac ny eill kynnal y ffynnawn namyn vn o teulu Arthur. A minneu a af,\" heb y Lunet, \"hyt yn llys Arthur; a mefyl im,\" heb hi, \"o deuaf o dyno heb vilwr a gatwo y ffynnawn yn gystal neu yn well no'r gwr a'e kedwis gynt.\" \"Anhawd yw hynny,\" heb yr iarlles; \"ac eissoes dos y brofi yr hynn a dywedy.\"",
          e: "\"I will tell you,\" she said. \"You know your dominion cannot be held but by feats of arms and weapons; therefore seek at once someone to hold it.\" \"And how can I do that?\" said the Countess. \"I will tell you,\" said Luned. \"Unless you can hold the fountain, you cannot hold your land; and none can hold the fountain but one of Arthur's household. I will go,\" said Luned, \"to Arthur's court; and shame on me,\" she said, \"if I come back from there without a warrior who can keep the fountain as well as — or better than — the man who kept it before.\" \"That will be hard,\" said the Countess; \"but go, and make trial of what you say.\"",
          n: "Luned's argument is the romance's coldest, clearest piece of statecraft: the land needs a defender for the fountain; the only possible defender is an Arthur's knight; therefore the marriage. She never says \"Owain\" — she lets necessity make the case. The Welsh tale frames the Countess's swift turn not as a woman's fickleness (the misogynist reading the scene has often drawn) but as a ruler bowing to the logic of survival." },

        { w: "Kychwyn a oruc Lunet ar uedwl mynet y lys Arthur; a dyuot a oruc y'r llofft att Owein, ac yno y bu hi gyt ac Owein yny oedd amser idi dyuot o lys Arthur. Ac yna gwisgaw ymdanei a oruc hi, a dyuot y ymwelet a'r iarlles; a llawen uu yr iarlles wrthi. \"Chwedleu o lys Arthur gennyt?\" heb yr iarlles. \"Goreu chwedyl gennyf, arglwydes,\" heb hi, \"kaffel o honaf vy neges. A pha bryt y mynny di dangos itt yr unben a doeth gyt a mi?\" \"Dyret ti ac ef,\" heb yr iarlles, \"am hanner dyd auory, y ymwelet a mi; a minneu a baraf ysgafalhau y dref erbyn hynny.\" A dyuot a wnaeth hi adref.",
          e: "Luned set out as though to go to Arthur's court; but she went to the chamber to Owain, and stayed there with him as long as it would have taken her to travel to Arthur's court. And then she dressed and came to visit the Countess; and the Countess was glad of her. \"You bring news from Arthur's court?\" said the Countess. \"The best of news, lady,\" she said, \"that I have won my errand. When will you have me show you the chieftain who has come with me?\" \"Bring him,\" said the Countess, \"tomorrow at midday to visit me; and I will have the town made ready by then.\" And Luned went home.",
          n: "The fortnight's pretended embassy is Luned's small, perfect lie: she lets the Countess believe Owain was fetched from Arthur's court, while he has been hidden in her chamber all along. The deception is harmless and entirely in the lady's interest — Luned's trade is arranging the truth so that everyone can accept it." },

        { w: "Ac am hanner dyd drannoeth y gwisgawd Owein ymdanaw peis a swrcot a mantell o bali melyn, ac orffreis lydan yn y vantell o eurllin, a dwy wintas o gordwal brith am y draet, a llun llew o eur yn eu kaeu. A dyuot a wnaethant hyt yn ystauell yr iarlles; a llawen uu yr iarlles wrthunt. Ac edrych ar Owein yn graff a oruc yr iarlles. \"Lunet,\" heb hi, \"nyt oes wed kerdetwr ar yr unben hwnn.\" \"Pa drwc yw hynny, arglwydes?\" heb y Lunet. \"Y rof a Duw,\" heb yr iarlles, \"nat duc dyn eneit vy arglwydi o'e gorff namyn y gwr hwnn.\" \"Goreu oll itt, arglwydes,\" heb hi: \"pei na bei drech noc ef, nys dygei ynteu y eneit ef. Ny ellir dim wrth hynny,\" heb hi, \"kan deryw.\" \"Ewch chwi drachefyn atref,\" heb yr iarlles, \"a minneu a gymeraf gyghor.\"",
          e: "And at midday next day Owain put on a tunic and surcoat and mantle of yellow brocade, with a broad orphrey of gold lace on the mantle, two boots of mottled cordwain on his feet, and gold clasps in the shape of a lion. And they came to the Countess's chamber, and she was glad of them. The Countess looked hard at Owain. \"Luned,\" she said, \"this chieftain has not the look of a man worn with travelling.\" \"What harm in that, lady?\" said Luned. \"Between me and God,\" said the Countess, \"no man but this drove the soul from my lord's body.\" \"So much the better for you, lady,\" she said: \"had he not been the stronger, he would not have taken his life. There is no help for it now,\" she said, \"since it is done.\" \"Go back home,\" said the Countess, \"and I will take counsel.\"",
          n: "The Countess sees through the fiction at once — \"this chieftain has not the look of a man worn with travelling\" — and names the truth: this is her husband's killer. Luned's reply is the tale's hardest line, and its whole argument: strength is the only thing that can hold the fountain, and the proof of his strength is precisely that he killed the man who held it before. The lion-shaped clasps on Owain's shoes quietly foreshadow the beast to come; and where Chrétien makes this scene long and inward, the Welsh makes it three swift exchanges." },

        { w: "A pheri dyfynnu y holl gyuoeth y vn lle drannoeth a oruc yr iarlles, a menegi udunt vot y hiarllaeth yn wedw, ac na ellit y chynnal onyt o varch ac arueu a milwryaeth. \"Sef y rodaf i ar awch dewis chwi: ae vn o honawch chwi a'm kymero i, ae vyg kannyadu inneu y gymryt gwr a'm kynhalyo o le arall.\" Sef a gawssant yn eu kyghor: kanhadu idi gwr o le arall. Ac yna y duc hitheu escyb ac archescyb o'e llys y wneuthur y phriodas hi ac Owein; a gwrhau a orugant gwyr y iarllaeth y Owein.",
          e: "Next day the Countess had all her dominion summoned to one place, and showed them that her earldom was widowed, and could not be held but by horse and arms and feats of war. \"This, then, I put to your choosing: either one of you take me, or grant me leave to take a husband from elsewhere who will hold it for me.\" And this they came to in their counsel: to grant her a husband from elsewhere. And then she brought bishops and archbishops from her court to make her marriage with Owain; and the men of the earldom did homage to Owain.",
          n: "The marriage is, in the Welsh, an act of council, not of passion: the earldom is \"widowed\" (the one word, <em>gwedw</em>, serves for the land and the woman), the magnates deliberate, and the wedding is solemnised by bishops with the men's formal homage. Owain wins the lady by winning the office; the romance is clear-eyed that the two are one prize." },

        { w: "Ac Owein a gedwis y ffynnawn o waew a chledyf. Sef mal y kedwis: y marchawc a delei yno, Owein a'e byryei, ac a'e gwerthei yr y lawn werth; a'r da hwnnw a rannei Owein y varwnyeit ac y uarchogyon, hyt nat oedd vwy gan y gyfoeth garyat dyn o'r byt oll noc eidaw ef. A their blynet y bu ef felly.",
          e: "And Owain held the fountain with lance and sword. And this is how he held it: whatever knight came there, Owain would unhorse him, and ransom him for his full worth; and that wealth Owain would share out among his barons and his knights, until no man in all the world was more beloved of his people than he. And for three years he was thus.",
          n: "Owain at his summit: he keeps the fountain exactly as its dead defender did — unhorse, ransom — but turns the takings outward to his men, and is loved for it. The ascending arc is complete: the wanderer is now a married lord with a kingdom, a famous office, and the devotion of his people. \"For three years he was thus\" is the still point of the tale; from here it falls. Arthur's company, who will pull him back to court, set out in the next movement." },
      ],
    },

    {
      title: "VI. Arthur's company — Cei unhorsed, Gwalchmei's three-day duel, the recognition",
      segments: [
        { w: "Ac ual yd oedd Gwalchmei diwarnawt yn gorymdeith y gyt a'r amherawdyr Arthur, edrych a oruc ar Arthur a'e welet yn trist gystudedic; a doluryaw a oruc Gwalchmei yn vawr o welet Arthur yn y rith hwnnw, a gofyn a oruc idaw: \"Arglwyd, heb py derw itti?\" \"Y rof a Duw, Walchmei,\" heb yr Arthur, \"hiraeth yssyd arnaf am Owein, a golleis y gennyf meint teir blynet; ac o bydaf y bedwared vlwydyn heb y welet, ny byd vy eneit ym corff. A mi a wnn yn hyspys panyw o ymdidan Cynon mab Clydno y colleis Owein y gennym.\" \"Nyt reit itti,\" heb y Gwalchmei, \"luydaw dy gyfoeth yr hynny; namyn ti a gwyr dy dy a eill dial Owein o'r llas, neu y rydhau ot yw yg carchar, ac os byw, y dwyn gyt a thi.\" Ac ar a dywawt Gwalchmei y trigywyt. Ac ymgyweiraw a wnaeth Arthur a gwyr y dy gyt ac ef y geissaw Owein; sef oedd meint y nifer, teir mil heb amlaw dynyon, a Chynon mab Clydno yn gyfarwyd udunt.",
          e: "And as Gwalchmei walked one day with the emperor Arthur, he looked on him and saw him sad and stricken; and Gwalchmei was much grieved to see Arthur in that state, and asked him, \"Lord, what has befallen you?\" \"Between me and God, Gwalchmei,\" said Arthur, \"longing is on me for Owain, whom I have lost these three years; and if a fourth year passes without my seeing him, my soul will not stay in my body. And I know well that it was through Cynon son of Clydno's tale that we lost Owain.\" \"There is no need,\" said Gwalchmei, \"to raise your whole dominion for that; you and the men of your household can avenge Owain if he is slain, or free him if he is in prison, or, if he is alive, bring him back with you.\" And it was settled as Gwalchmei said. And Arthur and the men of his household made ready to seek Owain; the number of them was three thousand, besides attendants, with Cynon son of Clydno for their guide.",
          n: "The tale turns back to court, three years on: Arthur is dying of <em>hiraeth</em> — that untranslatable Welsh longing — for the knight his own household's storytelling sent away. Gwalchmei's counsel is the romance's measure of the Round Table: not a national levy, just Arthur and his <em>teulu</em>, his war-band. The same Cynon whose tale began everything now guides the rescue." },

        { w: "A dyuot a oruc Arthur hyt y gaer y buassei Cynon yndi; a phan deuthant yno yd oedd y gweisson yn saethu yn yr un lle, a'r gwr melyn yn seuyll ger eu llaw. A phan welas y gwr melyn Arthur, kyfarch gwell a oruc idaw a'e wahawd; a chymryt gwahawd a oruc Arthur, ac y'r gaer yd aethant. A chyt bei mawr eu nifer, ny wydit eu hystyr yn y gaer, mor uawr oedd. A chyuodi a oruc y morynyon y eu gwassanaethu; a gwell oedd gwassanaeth gweisson y meirch y nos honno noc a uydei ar Arthur yn y lys ehun. A'r bore drannoeth y kychwynnwys Arthur, a Chynon yn gyfarwyd idaw, ac wynt a deuthant hyt lle yd oedd y gwr du; a hoffach o lawer oedd gan Arthur meint y gwr du noc y dywedyssit idaw. Ac y'r dyffryn hyt yn ymyl y pren glas y deuthant, yny welsant y ffynnawn a'r kawc a'r llech. Ac yna y doeth Cei at Arthur, a dywedut: \"Arglwyd,\" heb ef, \"mi a wnn achaws y kerdet hwnn oll; ac eruyn yw gennyf gadu y mi bwrw y dwfyr ar y llech, ac erbynyeit y gofut kyntaf a del.\" Ac y kanhadawd Arthur.",
          e: "And Arthur came to the castle where Cynon had been; and when they came there the youths were shooting in the same place, and the yellow man standing beside them. When the yellow man saw Arthur he greeted and welcomed him; Arthur accepted, and they went into the castle. And great as their number was, it was scarcely noticed in the castle, so vast it was. The maidens rose to serve them; and the grooms of the horses were better served that night than Arthur would have been in his own court. Next morning Arthur set out, Cynon guiding, and they came to where the black man was; and the black man's size pleased Arthur far more than he had been told. They came down the valley to the green tree, where they saw the fountain and the bowl and the slab. And then Cei came to Arthur and said, \"Lord, I know the whole meaning of this journey; and my prayer is that you let me throw the water on the slab and take the first adventure that comes.\" And Arthur gave him leave.",
          n: "The vastness of the castle that swallows three thousand men without notice, and the grooms lodged better than Arthur in his own hall, are the Welsh romance's quiet hyperboles of Otherworldly plenty. And Cei — who mocked the whole quest in Movement II — is first to claim the adventure now that it is safe to be brave. The tale never forgets his character." },

        { w: "A bwrw kawgeit o'r dwfyr ar y llech a oruc Cei; ac yn y lle ar ol hynny y deuth y twryf, ac yn ol y twryf y gawat; ac ny chlywyssynt eiryoet twryf a chawat gyffelyb y rei hynny. A llawer o amlaw dynyon a oed y gyweithas Arthur a ladawd y gawat. A gwedy peidyaw y gawat y goleuhawys yr awyr; a phan edrychassant ar y pren, nyt oed un dalen arnaw. A disgynnu a oruc yr adar ar y pren; a diheu oed gantunt na chlywyssynt eiryoet kerd gystal a'r adar yn canu. Ac ar hynny y gwelynt varchawc y ar varch purdu a gwisc o bali purdu ymdanaw, a cherdet gwrd gantaw. Ac erbynnyeit a oruc Cei, ac ymwan ac ef; ac ny bu hir yr ymwan, Cei a vyrywyt. Ac yna pebyllyaw a oruc y marchawc, a phebyllyaw a oruc Arthur a'e lu y nos honno.",
          e: "Cei threw a bowlful of water on the slab; and at once the thunder came, and after the thunder the shower; and they had never heard thunder and shower like those. And many of the attendants in Arthur's company were killed by the shower. When the shower had ceased the sky cleared; and when they looked at the tree, there was not a leaf on it. The birds came down on the tree; and surely they had never heard music to match the birds singing. And then they saw a knight on a jet-black horse, in jet-black brocade, riding hard. Cei met him and clashed with him; and the joust was not long — Cei was thrown. Then the knight pitched his tent, and Arthur and his host pitched theirs that night.",
          n: "The fountain has grown deadlier with each telling — now its hail actually kills men of Arthur's train. And the defender is, of course, Owain, unknown behind his black arms, unhorsing the seneschal who first jeered at the adventure. The tale lets the reader hold the secret the characters do not." },

        { w: "A phan gyfodassant y bore drannoeth y vynyd, yd oed arwyd ymwan ar waew y marchawc. A dyuot a oruc Cei at Arthur a dywedut wrthaw: \"Arglwyd,\" heb ef, \"kam y'm byrywyt i doe; ac a oed da y ti y mi hediw vynet y ymwan a'r marchawc?\" \"Gat,\" heb yr Arthur. A mynet a oruc Cei y'r marchawc; ac yn y lle bwrw Cei a oruc ef, ac edrych arnaw a'e waan ar lloft y waew yny tal, yny dyr y helym a'r penffestin a'r croen a'r kic hyt yr asgwrn, kyflet a phenn y paladyr. Ac ymchoelut a oruc Cei at y gedymdeithon drachefyn. Ac o hynny allan yd aeth teulu Arthur bop eilwers y ymwan a'r marchawc, hyt nat oed un heb y vwrw o'r marchawc, namyn Arthur a Gwalchmei.",
          e: "And when they rose next morning, there was the token of combat on the knight's lance. And Cei came to Arthur and said, \"Lord, I was wrongly thrown yesterday; would it please you that I go to fight the knight today?\" \"Go,\" said Arthur. And Cei went to the knight; and at once the knight threw him, and, looking at him, struck with the head of his lance on his forehead, so that it broke the helmet and the headpiece and the skin and the flesh to the bone, the breadth of a spear-head. And Cei went back to his companions. And from then on Arthur's household went, each in his turn, to fight the knight, until there was not one the knight had not thrown — save Arthur and Gwalchmei.",
          n: "Cei's stubborn second try, and his second and bloodier fall, are almost a comic refrain — but the whole Round Table going down one by one is a real measure of Owain's growth: the household that knew him cannot stand against him. Only Arthur and Gwalchmei are left, and the tale holds Arthur back so that the two best of the court can meet without knowing each other." },

        { w: "Ac Arthur a wisgawd ymdanaw y vynet y ymwan a'r marchawc. \"Och, arglwyd,\" heb y Gwalchmei, \"gat y mi vynet y ymwan a'r marchawc yn gyntaf.\" Ac adaw a wnaeth Arthur. Ac ynteu a aeth y ymwan a'r marchawc, a chwnsallt o bali ymdanaw a'e varch, a anuonassei verch iarll Rangyw idaw; ac wrth hynny nys atwaenat neb o'r llu. Ac ymgyrchu a wnaethant, ac ymwan y dyd hwnnw hyt ucher; ac ny bu agos yr un o nadunt a bwrw y gilyd y'r llawr. A thrannoeth y daethant y ymwan a pheleidyr godeuawc gantunt, ac ny orfu yr un o nadunt ar y gilyd. A'r trydyd dyd y daethant y ymwan a pheleidyr kadarnuras godeuawc gan bob un, ac ennynnu o lit a wnaethant ac ymgyrchu am hanner dyd ehun. A hwrd a rodes pob un onadunt y gilyd, yny dorres holl gegleu eu meirch, ac yny vyd pob un onadunt dros bedrein y varch y'r llawr. A chyuodi y vynyd a orugant yn gyflym a thynnu cledyfeu ac ymffust; a diheu oed gan y nifer a'e gwelei wynt velly na welsynt eiryoet deu wr kynwychet a'r rei hynny na chyngryfet; a phei tywyll y nos, hi a vydei oleu gan y tan o'e harueu.",
          e: "And Arthur armed himself to go fight the knight. \"Oh, lord,\" said Gwalchmei, \"let me go to fight the knight first.\" And Arthur allowed it. And he went to fight the knight, with a surcoat of brocade over himself and his horse that the daughter of Earl Rangyw had sent him; and for that no one of the host knew him. They charged, and fought that day until evening, and neither came near to throwing the other to the ground. Next day they came to fight with stout lances, and neither overcame the other. And the third day they came with very strong stout lances, and they kindled with rage and charged at high noon. And each gave the other such a shock that all the girths of their horses broke, and each went over his horse's crupper to the ground. They rose quickly and drew their swords and laid on; and surely those who watched them were certain they had never seen two men so valiant or so strong; and had the night been dark, it would have been lit by the fire from their arms.",
          n: "The three-day duel between Owain and Gwalchmei — neither knowing the other, neither able to win — is the romance's set-piece of matched excellence, the court's two best men proving equal. This is the same hero as our <em>Sir Gawain and the Green Knight</em>, here fighting his own cousin to a standstill in a borrowed coat. The lent robe of honour, the cause of the not-knowing, is the small chivalric machinery the recognition turns on." },

        { w: "Ac ar hynny dyrnawt a rodes y marchawc y Walchmei, yny troes y helym y ar y wyneb, mal y hadnabu y marchawc panyw Gwalchmei oed. Ac yna y dywawt Owein: \"Arglwyd Walchmei, nyt atwaenwn i dydi o achaws dy gwnsallt; a'm kefynderw wyt. Llad dydi vy nghledyf a'm harueu.\" \"Tydi, Owein, yssyd arglwyd,\" heb y Gwalchmei, \"a thi a oruu; a chymer di vy nghledyf.\" Ac ar hynny yd arganfu Arthur wynt, a dyuot attunt a oruc. \"Arglwyd Arthur,\" heb y Gwalchmei, \"llyma Owein, gwedy goruot arnaf, ac ny mynn vy arueu y gennyf.\" \"Arglwyd,\" heb yr Owein, \"ef a oruu arnaf, ac ny mynn vy nghledyf.\" \"Moeswch attaf i,\" heb yr Arthur, \"awch cledyfeu; ac ny oruu yr un o honawch ar y gilyd gan hynny.\" A mynet dwylaw mynwgyl y Arthur a oruc Owein, ac ymgaru a orugant. A dyuot a oruc y llu attunt yna, gan ymsang a bais y geissaw gwelet Owein ac y uynet dwylaw mynwgyl idaw; ac ef a uu agos a bot kalaned yn yr ymsang hwnnw.",
          e: "And then the knight gave Gwalchmei such a blow that it turned the helmet from off his face, so that the knight knew it was Gwalchmei. And then Owain said: \"Lord Gwalchmei, I did not know you, for your surcoat — and you are my cousin. Take my sword and my arms.\" \"You, Owain, are the lord here,\" said Gwalchmei, \"and you have won; take my sword.\" And at that Arthur caught sight of them, and came to them. \"Lord Arthur,\" said Gwalchmei, \"here is Owain, who has beaten me, and will not take my arms.\" \"Lord,\" said Owain, \"it is he that has beaten me, and he will not take my sword.\" \"Give me your swords,\" said Arthur, \"and then neither of you has beaten the other.\" And Owain put his arms about Arthur's neck, and they embraced. And then the host came thronging to them, crushing and pressing to see Owain and to throw their arms about his neck; and there was nearly a death in that crush.",
          n: "The recognition turns on the most courtly of contests: each insists the other won, each refusing the victor's right to the loser's sword, until Arthur dissolves the deadlock with a king's wit — give me both swords, and neither has beaten the other. It is the romance's ideal of friendship over rivalry, and the warmth of it (the near-deadly crush of men trying to embrace Owain) is the tale's purest moment of joy. The same Gwalchmei who keeps faith here is the Gawain who keeps — and breaks, and is forgiven — faith in the English poem." },

        { w: "A'r nos honno y daethant y eu pebyllyeu. A thrannoeth arofyn a oruc Arthur ymeith. \"Arglwyd,\" heb yr Owein, \"nyt velly y mae iawn itt. Teir blynet yr amser hwnn y deuthum i y wrthyt ti, arglwyd, ac y mae y meu i y lle hwnn; ac yr hynny hyt hediw yd wyf i yn darparu gwled itt, kan gwydwn y dout ti y'm keissaw. A thi a deuy gyt a mi y vwrw dy ludet ti a'th wyr, ac enneint a geffwch.\" A dyuot a orugant oll hyt yg kaer Iarlles y Ffynnawn; a'r wled y buwyt teir blynet yn y darparu, yn un trimis y treulwyt; ac ny bu esmwythach udunt gwled eiryoet na gwell no honno. Ac yna arofyn a oruc Arthur ymeith; a gyrru kenadeu a oruc Arthur at yr iarlles y erchi idi ellwng Owein y gyt ac ef o'e dangos y wyrda Ynys Prydein, a'e gwraged, vn trimis. A'r iarlles a'e kanhadawd, a chanhawd uu genthi hynny. A dyuot a oruc Owein y gyt ac Arthur y Ynys Prydein.",
          e: "And that night they went to their tents. And next day Arthur made to leave. \"Lord,\" said Owain, \"it is not right for you to do so. Three years ago this time I came away from you, lord, and this place is mine; and from then until today I have been preparing a feast for you, knowing you would come to seek me. And you shall come with me to throw off your weariness, you and your men, and you shall be bathed.\" And they all went to the castle of the Countess of the Fountain; and the feast that had been three years in the preparing was used up in a single three months; and they never had an easier or a better feast than that. And then Arthur made to leave, and sent messengers to the Countess to ask her to let Owain go with him, to show him to the nobles of the Island of Britain and their ladies, for three months. And the Countess granted it, though it was hard for her. And Owain came with Arthur to the Island of Britain.",
          n: "The reunion's generosity is total — a three-years' feast prepared against the certainty Arthur would come, devoured in three months — and the leave is given lovingly, \"though it was hard for her.\" Everything here is right: friendship restored, the court fed, the lady consenting. The term is set at three months; the tale's whole engine is that Owain will not keep it. Movement VII opens on the broken term." },
      ],
    },

    {
      title: "VII. The broken term — the stripped ring, the madness, and the healing balsam",
      segments: [
        { w: "Ac ual yd oed Owein diwarnawt yn bwyta ar y bwrd yg Kaer Llion ar Wysc, nachaf uorwyn yn dyuot ar uarch gwineu mynggrych a'e vyngen agaffei, a gwisc ymdanei o bali melyn, a'r ffrwyn ac a welit o'r kyfrwy eur oed oll. A hyt rac bronn Owein y deuth, a chymryt y uodrwy a oed ar law Owein. \"Uelly,\" heb hi, \"y gwneir y twyllwr, y bradwr, yr anghywir, yr gwaradwydus, yr divaryf!\" Ac ymchoelut penn y march, ac ymeith. Ac yna y doeth cof y Owein y gerdet honno, a thristau a oruc; a phan daruu bwyta, dyuot y letty a oruc, a gofalu y nos honno.",
          e: "And as Owain sat one day at meat at the table in Caer Llion on Usk, here came a maiden on a bay horse with a curling mane, foam at its bridle, a dress of yellow brocade about her, the bridle and all that showed of the saddle of gold. She came right up before Owain and took the ring from off his hand. \"Thus,\" she said, \"is the deceiver dealt with, the traitor, the false, the shamed, the beardless!\" And she turned her horse's head and was gone. And then his adventure came back to Owain's mind, and he was filled with sorrow; and when the meal was over he went to his lodging, and was troubled all that night.",
          n: "The reckoning rides in unannounced, mid-feast: a messenger strips the ring — the token of the marriage and the magic that once saved Owain — and names his fault in five flat words. <em>Divaryf</em>, \"beardless,\" is the cruellest: in Welsh heroic terms, unmanned, not yet a man. The same broken-promise pattern drives the falls of both this tale and Chrétien's <em>Yvain</em>; it is the one Propp interdiction-and-violation the Welsh romance fully commits to." },

        { w: "A thrannoeth y kyuodes, ac nyt y llys a gyrchwys, namyn eithafoed bydoed a diffeith vynyded. Ac ef a uu uelly yny daruu y dillat oll, ac yny daruu y gorff hayach, ac yny tyfawd blew hir trwydaw. A chyt gerdet a wnaei a bwystuileit a chyt ymborth ac wynt yny oedynt gynefin ac ef; ac yn hynny gwanhau a oruc ef heb allu eu kanhymdeith. Ac estwng o'r mynyd y'r dyffryn, a chyrchu parc teccaf o'r byt, a iarlles wedw bioed y parc.",
          e: "And next morning he rose, and it was not the court he made for, but the ends of the world and desert mountains. And he was thus until all his clothing was worn away, and his body almost wasted, and long hair grew all over him. And he went along with the wild beasts and fed with them, until they were used to him; and in that he grew so weak he could not keep their company. And he came down from the mountain to the valley, and made for the fairest park in the world, and a widowed countess owned that park.",
          n: "Owain's madness is the tale's nadir and its strangest image: the married lord, the famous defender, reduced to a naked thing running with the deer until even they leave him behind. The Welsh wild-man-of-the-woods (the <em>gwyllt</em>, as in the Myrddin–Merlin legend, or Suibhne in the Irish) is a recognised native type — reason lost to grief and guilt, recovered only in the wild. It is the price of the broken word, paid in the body." },

        { w: "A diwarnawt mynet a oruc yr iarlles a'e llawuorynyon y orymdeith gan ystlys llynn a oed yn y parc, hyt ar gyfeir y chanawl. Ac wynt a welynt yno eilun dyn a'e delw; ac agos uu udunt gymryt ofyn racdaw. Ac eissoes nessau a orugant attaw, a'e deymlaw a'e edrych; sef y gwelynt gwythi yn llawn arnaw, ac ynteu yn gwywaw wrth yr heul. A dyuot a oruc yr iarlles drachefyn y'r kastell, a chymryt lloneit gorflwch o ireit gwerthuawr, a'e rodi yn llaw un o'r llawuorynyon. \"Dos,\" heb hi, \"a hwnn gennyt, a duc y march racko a'r dillat gennyt, a dot ger llaw y dyn gynneu; ac ir ef a'r ireit hwnn ar gyfeir y gallon, ac o byd eneit yndaw, ef a gyfyt gan yr ireit hwnn; a gwylya beth a wnel.\"",
          e: "And one day the countess and her handmaids went to walk by the side of a lake that was in the park, as far as its middle. And there they saw the likeness and form of a man; and they were near to taking fright at him. Yet they came up to him, and touched him, and looked at him; and they saw the veins beating full in him, and him withering in the sun. And the countess went back to the castle, and took a flask full of precious ointment, and put it in the hand of one of the handmaids. \"Go,\" she said, \"and take this with you, and take that horse yonder and the clothes, and set them near the man we saw just now; and anoint him with this ointment over his heart, and if there is life in him, he will rise by this ointment; and watch what he does.\"",
          n: "The second Countess — the widow of the park — is the agent of Owain's healing, as the first was the cause of his fall: the romance's symmetry. The precious ointment is the tale's instrument of grace, applied \"over the heart.\" Where Sir Orfeo is recovered out of the Otherworld, here the magic is medicinal — a noblewoman's balsam, not a fairy's gift." },

        { w: "A'r uorwyn a deuth racdi, a chwbyl o'r ireit a rodes arnaw, ac adaw y march a'r dillat ger y law, a mynet ruthur y wrthaw ac ymgudyaw a disgwyl arnaw. Ac ympenn rynnawd hi a'e gwelei yn coffi y vreicheu, ac yn kyfodi y vynyd ac yn edrych ar y gnawt; a chymryt kewilyd a oruc, mor hagyr oed y delw a oed arnaw. Ac arganfot a oruc y march a'r dillat y wrthaw, ac ymlithraw yny gafas tynnu y dillat attaw o'r kyfrwy a'e gwisgaw, ac esgynnu ar y march o abreid. Ac yna ymdangos a oruc y uorwyn idaw a chyfarch gwell idaw; a llawen uu ynteu wrth y vorwyn, a gofyn a oruc idi pa dir oed hwnnw a pha le. \"Dioer,\" heb y uorwyn, \"iarlles wedw bieu y kastell racko; a phan uu uarw y gwr, ef a edewis genthi dwy iarllaeth, a hediw nyt oes ar y helw namyn yr unty hwnn, nys ry dycko iarll ieuanc yssyd gymodawc idi, am nat aei yn wreic idaw.\" \"Truan yw hynny,\" heb yr Owein.",
          e: "And the maiden came to him, and poured the whole of the ointment on him, and left the horse and the clothes beside him, and drew quickly off and hid herself and watched him. And after a while she saw him stirring his arms, and rising up and looking at his flesh; and he took shame, so ugly was the look of him. And he caught sight of the horse and the clothes near him, and crawled until he could draw the clothes to him from the saddle and put them on, and mounted the horse with difficulty. And then the maiden showed herself to him and greeted him; and he was glad of her, and asked her what land this was and what place. \"Truly,\" said the maiden, \"a widowed countess owns yonder castle; and when her husband died he left her two earldoms, and today she has nothing in her keeping but this one dwelling — and that a young earl, a neighbour of hers, has not yet seized, because she would not become his wife.\" \"That is a pity,\" said Owain.",
          n: "The maiden disobeys her mistress in the kindest way — pouring out <em>all</em> the precious balsam, not the careful dab over the heart — and so over-heals the broken hero. Owain's first act on waking is shame at his own body; his first words on hearing the widow's plight are pity. The man is being rebuilt from the inside: grace received, then gratitude felt, then (in the next breath) repaid. The whole back half runs on this economy of kindness owed and returned." },

        { w: "A cherdet a oruc Owein a'r uorwyn y'r kastell; a disgynnu a wnaeth Owein yn y kastell, a'r uorwyn a'e duc y ystauell esmwyth, a chynneu tan idaw a'e adaw yno. A dyuot a oruc y uorwyn at yr iarlles, a rodi y gorflwch yn y llaw. \"Ha uorwyn,\" heb yr iarlles, \"mae yr ireit oll?\" \"Neur golles oll,\" heb hi. \"Ha uorwyn,\" heb yr iarlles, \"nyt hawd gennyf i dy atneiryaw di yr hynny; oed diryeit hagen y minneu treulaw gwerth seith ugeint punt o ireit gwerthuawr wrth dyn heb wybot pwy. Ac eissoes, uorwyn,\" heb hi, \"gwassanaetha di ef yny vo diwall o gwbyl.\" A hynny a oruc y uorwyn: y wassanaethu ar vwyt a diawt a than a gwely ac enneint, yny vu iach. Ac am tri mis y bu yn hynny, a gwynnach oed y gnawt yna noc y buassei gynt.",
          e: "And Owain and the maiden went to the castle; and Owain dismounted, and the maiden brought him to a comfortable chamber, kindled a fire for him, and left him. And the maiden came to the countess and put the flask in her hand. \"Ah, maiden,\" said the countess, \"where is all the ointment?\" \"It is all gone,\" she said. \"Ah, maiden,\" said the countess, \"it is not easy for me to forgive you that; it was a sorry thing for me to spend sevenscore pounds' worth of precious ointment on a man I do not know. Even so, maiden,\" she said, \"serve him until he is wholly recovered.\" And the maiden did so: serving him with food and drink and fire and bed and bathing, until he was well; and for three months he was at that, and his flesh was fairer then than it had been before.",
          n: "The sevenscore-pounds' worth of balsam, poured out all at once, is the tale's small comedy of extravagant mercy: the countess's exasperation is real, but she forgives it, and the healing it buys is total — Owain restored \"fairer than before.\" The three-month convalescence quietly answers the three-month leave he failed to keep; the tale is mending its broken clocks." },

        { w: "Ac ar hynny y clywei Owein diwarnawt kynnwryf yn y kastell a dwyn arueu ymywn; a gofyn a oruc Owein y'r uorwyn pa gynnwryf yw hwnn. \"Yr iarll,\" heb hi, \"a dywedeis i ytti yssyd yn dyuot wrth y kastell y geissaw diua y wreic honn, a llu mawr gantaw.\" A gofyn a oruc Owein a oes uarch ac arueu y'r iarlles. \"Oes,\" heb y uorwyn, \"y rei goreu o'r byt.\" \"Ay di y erchi y mi benffic march ac arueu,\" heb yr Owein, \"pei gallwn vynet yn edrychyat ar y llu?\" \"Af,\" heb y uorwyn. Sef a oruc yr iarlles chwerthin: \"Y rof a Duw, mi a rodaf idaw uarch ac arueu byth; ac ny bu ar y helw eiryoet march ac arueu kystal ac wynt, a da yw gennyf i eu kymryt o honaw, rac eu kaffel o'm gelynyon auory o'm hanuod.\" A dyuot a wnaethpwyt a gwasgwyn du telediw a chyfrwy o ffawyd arnaw, ac adogon o arueu gwr a march. A gwisgaw a oruc Owein ymdanaw ac esgynnu ar y march, a mynet ymeith a deu uackwy gyt ac ef. A phan deuthant parth a llu yr iarll, ny welynt nac ol nac eithaf idaw. A cherdet a oruc Owein racdaw yny gyferuyd a'r iarll, a'e tynnu o'e gyfrwy yny uyd y ryngthaw a chof y uarch, ac ymchoelut penn y uarch parth a'r kastell; a pha ofut bynnac a gafas, ef a deuth a'r iarll y borth y kastell. Ac Owein a rodes y iarll yn anrec y'r iarlles, a dywedut wrthi: \"Wely di, yma y ti bwyth yr ireit bendigedic.\" Ac yr rodi bywyt y'r iarll, y rodes ynteu y dwy iarllaeth idi drachefyn; ac yr rydit idaw y rodes hanner y gyfoeth ehun, a chwbyl o'e eur a'e aryant a'e thlysseu a'e wystlon.",
          e: "And then one day Owain heard a stir in the castle and arms being carried in; and Owain asked the maiden what the stir was. \"The earl,\" she said, \"that I told you of, is coming against the castle to destroy this lady, and a great host with him.\" And Owain asked whether the countess had a horse and arms. \"Yes,\" said the maiden, \"the best in the world.\" \"Will you go and ask me the loan of a horse and arms,\" said Owain, \"that I might go and look at the host?\" \"I will,\" said the maiden. The countess only laughed: \"Between me and God, I will give him a horse and arms for ever; never in her keeping were there horse and arms so good as these, and I am glad to have him take them, lest my enemies get them tomorrow against my will.\" And a fine black Gascon horse was brought, with a beechwood saddle on it, and arms enough for man and horse. And Owain armed himself and mounted, and rode out with two pages with him. And when they came toward the earl's host, they could see neither its beginning nor its end. And Owain rode on until he met the earl, and dragged him out of his saddle until he lay across the saddle-bow of Owain's horse, and turned his horse's head toward the castle; and whatever trouble he had of it, he brought the earl to the castle gate. And Owain gave the earl as a gift to the countess, and said to her: \"See — here is your requital for the blessed ointment.\" And to be given his life, the earl gave her back the two earldoms; and to be set free, he gave her half of his own dominion, and all his gold and his silver and her jewels, and hostages.",
          n: "Owain's recovery is proved by deed: borrowing the lady's own arms, he plucks the besieging earl bodily from the saddle and hands him over as \"requital for the blessed ointment.\" This is the first of the back half's chain of grateful rescues — kindness received, kindness repaid with interest. The young earl who makes war on a widow because she would not wed him is a dark mirror of Owain himself, who won a widow's land by force; the tale quietly sets the two against each other." },

        { w: "Ac ymeith yd aeth Owein; a'e wahawd a oruc yr iarlles idaw, ef a'e holl gyfoeth; ac ny mynnwys Owein namyn kerdet racdaw eithafoed byt a diffeithwch.",
          e: "And Owain took his leave; and the countess and all her dominion begged him to stay; but Owain would have nothing but to ride on, to the ends of the earth and the wilderness.",
          n: "Owain will not stay, not even for a grateful earldom's thanks — the healed man is not yet a whole one, and the romance sends him back to the wild road. He rides out unrewarded by his own choice; the next thing he meets on that road, in Movement VIII, is a lion. The back half is a pilgrimage of debts repaid, and it is not finished." },
      ],
    },
  ],
};
