/* Sir Gawain and the Green Knight.
   English is an original translation. The Middle English shown alongside is
   lightly normalised from Richard Morris's 1864 edition (Cotton Nero A.x,
   Project Gutenberg #14568, public domain): thorn (þ) -> th, yogh (3) -> y/gh,
   ampersand -> and, folio markers and editor's sidenote letters removed; bob-
   and-wheel run into the prose. The full diplomatic source is preserved at
   source/sggk-morris-1864.txt. Attaches to window.GAWAIN. */
window.GAWAIN = window.GAWAIN || {};
window.GAWAIN.tale = {
  meta: {
    blurb: "<strong>Sir Gawain and the Green Knight</strong> — the masterpiece of late-14th-century Middle English alliterative verse, anonymous (the <em>Pearl Poet</em>), surviving in one manuscript (BL Cotton Nero A.x). Below is <strong>Fitt I</strong> in full (21 stanzas, ~490 lines): the Trojan frame, Christmas at Camelot, the Green Knight's entrance, the beheading game. The English is an <strong>original translation</strong>. The Middle English beside it is a <em>lightly normalised reading text</em> after Richard Morris's 1864 edition (Project Gutenberg #14568, public domain) — thorns and yoghs modernised for readability; the diplomatic source is preserved verbatim at <a href=\"source/sggk-morris-1864.txt\">source/sggk-morris-1864.txt</a>.",
    sources: [
      { label: "Sir Gawayne and the Green Knight — Richard Morris (1864), Project Gutenberg #14568", url: "https://www.gutenberg.org/ebooks/14568", host: "Project Gutenberg" },
      { label: "Cotton Nero A.x — BL digitised manuscript", url: "https://www.bl.uk/manuscripts/Viewer.aspx?ref=cotton_ms_nero_a_x", host: "British Library" },
      { label: "Sir Gawain and the Green Knight — background", url: "https://en.wikipedia.org/wiki/Sir_Gawain_and_the_Green_Knight", host: "Wikipedia" },
    ],
  },
  roadmap: [
    { t: "Source text in hand", done: true },
    { t: "Fitt I · The beheading at Camelot", done: true },
    { t: "Fitt II · Gawain rides out, Bertilak's castle", done: false },
    { t: "Fitt III · Three hunts, three temptations, the green girdle", done: false },
    { t: "Fitt IV · The Green Chapel and what was revealed", done: false },
  ],
  passages: [
    {
      title: "Fitt I. The Green Knight at Camelot",
      segments: [
        { w: "Sithen the sege and the assaut was sesed at Troye, the borgh brittened and brent to brondes and askes, the tulk that the trammes of tresoun ther wroght was tried for his tricherie, the trewest on erthe. Hit was Ennias the athel, and his highe kynde, that sithen depreced provinces, and patrounes bicome welneghe of al the wele in the west iles. Fro riche Romulus to Rome ricchis hym swythe, with gret bobbaunce that burghe he biges upon fyrst, and neuenes hit his aune nome, as hit now hat; Ticius to Tuskan turnes, and teldes bigynnes; Langaberde in Lumbardie lyftes up homes; and fer over the French flod Felix Brutus on mony bonkkes ful brode Bretayn he settes, wyth wynne. Where werre, and wrake, and wonder, by sythes hath wont ther-inne, and oft bothe blysse and blunder ful skete hath skyfted synne.",
          e: "When the siege and assault of Troy were ended — the city beaten down to brands and ashes, and the man who had spun the looms of treason there tried for his treachery, the truest traitor on earth — it was noble Aeneas and his high kindred who afterwards subdued provinces and became the lords of almost all the wealth of the western isles. From him came rich Romulus, who hurried to Rome, and with great proud display first raised that city and named it with his own name, as it bears now; Ticius turned to Tuscany and began to build there; Langobard set up homes in Lombardy; and far over the French sea, upon many broad hillsides, Felix Brutus founded Britain with delight — Britain, where war, and ruin, and wonder have many a time held sway, and where bliss and blunder by turns have very swiftly shifted since.",
          n: "The opening trick of the high alliterative tradition: tie Britain's origin back to Troy through the legendary founder Brutus, with Geoffrey of Monmouth's pseudo-history serving the New Year tale." },

        { w: "And quen this Bretayn was bigged by this burn rych, bolde bredden ther-inne, baret that lofden, in mony turned tyme tene that wroghten. Mo ferlyes on this folde han fallen here oft then in any other that I wot, syn that ilk tyme. Bot of alle that here bult of Bretaygne kynges ay was Arthur the hendest, as I haf herde telle; for-thi an aunter in erde I attle to schawe, that a selly in sight summe men hit holden, and an outtrage aventure of Arthures wonderes. If ye wyl lysten this laye but on littel quile, I schal telle hit, as-tit, as I in toun herde, with tonge; as hit is stad and stoken, in stori stif and stronge, with lel letteres loken, in londe so hath ben longe.",
          e: "And after this Britain had been raised by that noble lord, bold men flourished here, men that loved battle, and in many a turning time they wrought trouble. More marvels have fallen on this land since that same time than in any other I know of. But of all who ever ruled in Britain, Arthur was ever the noblest, as I have heard told — and so I mean to set out an adventure on earth, a sight some hold for a marvel beyond marvels, an outrage-adventure of Arthur's wonders. If you will listen to my lay only a little while, I shall tell it now, as I heard it told in town, by tongue — as it stands and is fastened in a story strong and stiff, locked in with loyal letters, as it has long been kept in this land." },

        { w: "This kyng lay at Camylot upon Krystmasse, with mony luflych lorde, ledes of the best, rekenly of the rounde table alle tho rich brether, with rych revel oryght, and rechles merthes; ther tournayed tulkes by-tymes ful mony, justed ful jolilé thise gentyle knyghtes, sythen kayred to the court, caroles to make. For ther the fest was ilyche ful fiften dayes, with alle the mete and the mirthe that men couthe a-vyse; such glaumande gle glorious to here, dere dyn upon day, daunsyng on nyghtes, al was hap upon heghe in halles and chambres, with lordes and ladies, as leuest him thoght; with all the wele of the worlde thay woned ther samen, the most kyd knyghtes under Kryste seluen, and the louelokkest ladies that euer lif haden, and he the comlokest kyng that the court haldes; for al was this fayre folk in her first age, on sille; the hapnest under heuen, kyng hyghest mon of wylle, hit were now gret nye to neuen so hardy a here on hille.",
          e: "This king lay at Camelot at Christmas, with many lovely lords, the choicest of men — gathered in good order, the whole rich brotherhood of the Round Table — in rich revelry indeed, with reckless mirth. Knights tilted at tournament many times; the gentle knights jousted gaily, then turned back to court to make carols. There the feast ran on, full for fifteen days, with all the meat and the mirth that men could devise. Such cheerful glee was glorious to hear — a fine din through the day, dancing through the night, all happiness on high in halls and chambers among lords and ladies as they best loved. With all the world's wealth they dwelt there together — the most renowned knights under Christ Himself, the loveliest ladies that ever lived, and he the comeliest king that holds a court — for all this fair folk in the hall were in their first youth, the happiest under heaven, and the king the man of highest will. It would now be hard to name so bold a band on any hill." },

        { w: "Wyle nw yer was so yep that hit was nwe cummen, that day double on the dece was the douth serued, fro the kyng was cummen with knyghtes in-to the halle, the chauntre of the chapel cheued to an ende; loude crye was ther kest of clerkes and other, Nowel nayted o-newe, neuened ful ofte; and sythen riche forth runnen to reche honde-selle, yeghed yeres yiftes on hi, yelde hem by hond, debated busyly aboute tho giftes; ladies laghed ful loude, thoghe thay lost haden, and he that wan was not wrothe, that may ye wel trawe. Alle this mirthe thay maden to the mete tyme; when thay had waschen, worthyly thay wenten to sete, the best burne ay abof, as hit best semed; whene Guenore ful gay, graythed in the myddes, dressed on the dere des, dubbed al aboute, smal sendal bisides, a selure hir ouer of tryed Tolouse, of Tars tapites in-noghe, that were enbrawded and beten wyth the best gemmes, that myght be preued of prys wyth penyes to bye, in daye; the comlokest to discrye, ther glent with yghen gray, a semloker that euer he syghe, soth moght no mon say.",
          e: "While the New Year was still so young, just newly come, the company was that day doubly served upon the dais. Once the king had come with his knights into the hall, the chanting in the chapel ended; loud cries were cast up by clerics and others — “Nowell!” renewed and named often. And then the company hurried forth to receive their handsels, calling out New Year's gifts on high and handing them out, busily debating the giving. Ladies laughed aloud, though they had lost, and he that had won was not wrathful — you may well believe it. All this mirth they made until the time for meat; when they had washed, worthily they went to their seats — the best man always above, as best became him; bright Guinevere, gaily attired, was set in the midst, placed upon the rich dais and decked all about with smooth sendal silk beside her and a canopy above of fine Toulouse silk and abundant tapestries of Tarsia, embroidered and beaten with the best of gems — gems whose worth no day's wages could prove. Yet she herself, the comeliest to behold, who glanced about with grey eyes — a fairer lady than he had ever set eyes on, in truth no man could claim." },

        { w: "Bot Arthure wolde not ete til al were serued, he was so joly of his joyfnes, and sum-quat child gered, his lif liked hym lyght, he louied the lasse auther to lenge lye, or to longe sitte, so by-sied him his yonge blod and his brayn wylde; and also another maner meued him eke, that he thurgh nobelay had nomen, ho wolde neuer ete upon such a dere day, er hym deuised were of sum auenturus thyng an uncouthe tale, of sum mayn meruayle, that he myght trawe, of alderes, of armes, of other auenturus, other sum segg hym bi-soght of sum siker knyght, to joyne wyth hym in justyng in jopardé to lay, lede lif for lyf, leue uchon other, as fortune wolde fulsun hom the fayrer to haue. This was the kynges countenaunce where he in court were, at uch farand fest among his fre meny, in halle; therfore of face so fere, he stightles stif in stalle, ful yep in that nw yere, much mirthe he mas with alle.",
          e: "But Arthur would not eat until all were served. He was so glad in his youth and a little childlike — his life pleased him light, and he liked the less either to lie long abed or sit long at table, for his young blood and wild brain so urged him. And besides, another custom moved him, taken on himself for honour's sake: he would never eat upon such a high day until he had been told some adventurous thing, some uncouth tale of a great marvel he could believe — of patriarchs, of arms, of other adventures — or some man had asked him for a sure knight to join with him in a joust, to set life against life, each yielding place to the other, and let fortune help whichever should be the fairer. This was the king's custom whenever he was at court, at every grand feast among his free company in hall; and so, with that bold face of his, he stands stiff in his seat, fully youthful in that new year, and makes much mirth with all.",
          n: "The custom — \"no meat till a marvel\" — is the door the Green Knight will walk through. The poem's irony is that the marvel Arthur gets is darker than any he expected." },

        { w: "Thus ther stondes in stale the stif kyng his-seluen, talkkande bifore the hyghe table of trifles ful hende. Ther gode Gawan was graythed, Gwenore bisyde, and Agrauayn a la dure mayn on that other syde sittes, bothe the kynges sister sunes, and ful siker knyghtes; bischop Bawdewyn abof bi-gines the table, and Ywan, Vryn son, ette wit hym-seluen; thise were dight on the des, and derworthly serued, and sythen mony siker segge at the sidbordes. Then the first cors come with crakkyng of trumpes, wyth mony baner ful bryght, that ther-by henged, nwe nakryn noyse with the noble pipes, wylde werbles and wyght wakned lote, that mony hert ful hy hef at her towches; dayntes dryuen ther-wyth of ful dere metes, foysoun of the fresche, and on so fele disches, that pine to fynde the place the peple bi-forne for to sette the syluener, that sere sewes halden, on clothe; iche lede as he loued hym-selue ther laght with-outen lothe, ay two had disches twelue, good ber, and bryght wyn bothe.",
          e: "Thus stands the stalwart king in his place, talking before the high table of trifles in courtly fashion. Beside Queen Guinevere sat good Gawain, and on her other hand Agravain of the Hard Hand — both of them the king's sister's sons and very sure knights. Above them began the table Bishop Baldwin, and Ywain the son of Urien ate with him. These were seated on the dais and royally served, and many trusty knights at the side-tables after. Then the first course came in with cracking of trumpets, with many a bright banner hung beside them, with new nakers' noise and the noble pipes, with wild warblings and lively rousing notes that lifted many a heart at their music. Then the daintiest of the dearest meats were brought, abundance of fresh game and so many dishes that it was hard to find room before the people to set down the silver platters bearing the courses, upon the cloth; each man took his share without grudging, as he best liked — every two had twelve dishes between them, with good beer and bright wine, both." },

        { w: "Now wyl I of hor seruise say yow no more, for uch wyghe may wel wit no wont that ther were; an other noyse ful newe neghed biliue, that the lude myght haf leue lif-lode to cach. For unethe was the noyce not a whyle sesed, and the fyrst cource in the court kyndely serued, ther hales in at the halle dor an aghlich mayster, on the most on the molde on mesure hyghe; fro the swyre to the swange so sware and so thik, and his lyndes and his lymes so longe and so grete, half etayn in erde I hope that he were. Bot mon most I algate mynn hym to bene, and that the myriest in his muckel that myght ride; for of bak and of brest al were his bodi sturne, bot his wombe and his wast were worthily smale, and alle his fetures folghande, in forme that he hade, ful clene; for wonder of his hwe men hade, set in his semblaunt sene; he ferde as freke were fade, and ouer-al enker grene.",
          e: "I will say no more of their serving, for every man may well know there was no lack of anything there. Then another sound, quite new, drew near; the company might leave off taking their food. For scarcely had the music ceased a moment, and the first course been properly served, when there came striding in at the hall door an awesome lord — the tallest of all men on the earth in measure. From the neck to the waist he was so square and so thick, and his loins and his limbs so long and so great, that I believe he must have been half a giant. Yet I will hold him to be a man all the same — and the merriest of his great size that ever bestrode a horse. For though his back and his breast were thick and stern, his belly and his waist were properly small, and all his features matched his frame fittingly. Folk wondered at his hue, plain to see in his very look: he moved like a man fierce and free — and all over he was vividly green.",
          n: "The Pearl Poet's most famous tableau. The Green Knight is one of the great visual inventions in all medieval literature — the colour itself is the wonder." },

        { w: "And al graythed in grene this gome and his wedes, a strayt cote ful streght, that stek on his sides, a mere mantile abof, mensked with-inne, with pelure pured apert the pane ful clene, with blythe blaunner ful bryght, and his hod bothe, that was laght fro his lokkes, and layde on his schulderes; heme wel haled, hose of that same grene, that spenet on his sparlyr, and clene spures vnder, of bryght golde, vpon silk bordes, barred ful ryche; and scholes vnder schankes, there the schalk rides; and alle his vesture verayly was clene verdure, bothe the barres of his belt and other blythe stones, that were richely rayled in his aray clene, aboutte hym-self and his sadel, vpon silk werkes, that were to tor for to telle of tryfles the halue, that were enbrauded abof, wyth bryddes and flyes, with gay gaudi of grene, the golde ay in myddes; the pendauntes of his payttrure, the proude cropure, his molaynes, and alle the metail anamayld was thenne, the steropes that he stod on, stayned of the same, and his arsouns al after, and his athel sturtes, that euer glemered and glent al of grene stones. The fole that he ferkkes on, fyn of that ilke, sertayn; a grene hors gret and thikke, a stede ful stif to strayne, in brawden brydel quik, to the gome he was ful gayn.",
          e: "And this man and his garments were all decked in green: a close-fitting tunic that clung tight to his sides, with a fair mantle above it richly trimmed within with clean white ermine — and his hood likewise, thrown back from his locks and laid over his shoulders. Well-fitted hose of the same green clung to his calves, and bright spurs beneath, of gleaming gold, set upon silken straps cunningly barred; the rider went shoeless. All his vesture was the cleanest green: the bars of his belt, the bright stones richly arranged in his array, the saddle and the saddle-cloth — silken work too elaborate to tell more than half its trifles, embroidered above with birds and flies, with gay green ornament and gold always at the centre. The pendants of his breast-band, the proud crupper-strap, the bosses of his bit, and all the metal-work were enamelled; the stirrups he stood in were stained the same, and the saddle-bows after, and the noble harness-skirts, all gleaming and glittering with green stones. The horse he rode upon was perfectly matched with him: a great thick green horse, a steed stiff to govern, prompt in the plaited bridle — and altogether well-suited to his rider." },

        { w: "Wel gay was this gome gered in grene, and the here of his hed of his hors swete; fayre fannand fax umbe-foldes his schulderes; a much berd as a busk ouer his brest henges, that wyth his hyghlich here, that of his hed reches, was euesed al umbe-torne, a-bof his elbowes, that half his armes ther vnder were halched in the wyse of a kynges capados, that closes his swyre. The mane of that mayn hors much to hit lyke, wel cresped and cemmed wyth knottes ful mony, folden in wyth fildore aboute the fayre grene, ay a herle of the here, an other of golde; the tayl and his toppyng twynnen of a sute, and bounden bothe wyth a bande of a bryght grene, dubbed wyth ful dere stones, as the dok lasted; sythen thrawen wyth a thwong a thwarle knot alofte, ther mony belles ful bryght of brende golde rungen. Such a fole upon folde, ne freke that hym rydes, was neuer sene in that sale wyth syght er that tyme, with yghe; he loked as layt so lyght, so sayd al that hym syghe, hit semed as no mon myght, vnder his dyntes dryghe.",
          e: "Gaily was this man arrayed in green, and the hair of his head matched his horse's. A fair fanning fall of locks folded over his shoulders, and a beard as great as a bush hung down upon his breast — beard and high head-hair together trimmed evenly all around above his elbows, so that half his arms below were enclosed under them, in the fashion of a king's cape that wraps his neck. The mane of his mighty horse was much the same: well-curled and combed and knotted in many places, plaited through with gold thread along the fair green — a strand of hair to a strand of gold. Tail and forelock were twinned in the same way, and both bound with a bright green band, set with full-rich stones along its length, knotted up with a thong in a tight knot at the top, from which many bright bells of refined gold rang. Such a horse on the earth, and such a knight to ride him, was never seen in that hall with mortal eye, not before that time — he looked as bright as a stroke of lightning, said all who saw him: it seemed that no man might endure his blow." },

        { w: "Whether hade he no helme ne hawbergh nauther, ne no pysan, ne no plate that pented to armes, ne no schafte, ne no schelde, to schwne ne to smyte, bot in his on honde he hade a holyn bobbe, that is grattest in grene, when greues ar bare, and an ax in his other, a hoge and vn-mete, a spetos sparthe to expoun in spelle quo-so myght. The hede of an eln-yerde the large lenkthe hade, the grayn al of grene stele and of golde hewen, the bit burnyst bryght, with a brod egge, as wel schapen to schere as scharp rasores; the stele of a stif staf the sturne hit bi-grypte, that was wounden wyth yrn to the wandes ende, and al bigrauen with grene, in gracios werkes; a lace lapped aboute, that louked at the hede, and so after the halme halched ful ofte, wyth tryed tassels therto tacched in-noghe, on botouns of the bryght grene brayden ful ryche. This hathel heldes hym in, and the halle entres, driuande to the heghe dece, dut he no wothe, haylsed he neuer one, but heghe he ouer loked. The fyrst word that he warp, “wher is,” he sayd, “the gouernour of this gyng? Gladly I wolde se that segg in syght, and with hym self speke raysoun.” To knyghtes he kest his yghe, and reled hym up and doun, he stemmed and con studie, quo walt ther most renoun.",
          e: "He had no helm and no hauberk either, no plate-armour that belongs to arms, no spear and no shield to ward or to strike with — but in one hand he held a holly bough, the greenest thing in the wood when the thickets are bare, and in the other an axe, huge and out of measure, a fearsome battleaxe to expound in words for any that could. The head of it was an ell long, broad as a yard, the steel green and chased with gold, the blade burnished bright with a broad edge, as well shaped for shearing as the sharpest razor. The haft was a stiff staff that the stern man gripped, wound with iron to the end of the handle and all engraved in green with graceful work; a lace was lapped about it, fastening at the head and so wound often along the haft, with rich tassels tied to it on buttons of bright green, abundantly embroidered. This lord rode his horse straight into the hall, drove up to the high dais without fear of any harm, never greeted anyone, but looked high over them all. The first word he uttered: “Where is,” he said, “the governor of this gathering? Gladly would I see that man in the eye and speak with him in reason.” He cast his eye over the knights and rolled it up and down, paused, and pondered who held the most renown there.",
          n: "Holly in one hand (peace) and a great axe in the other (war) — the Green Knight's costume is itself the puzzle." },

        { w: "Ther was lokyng on lenthe, the lude to be-holde, for uch mon had meruayle quat hit mene myght, that a hathel and a horse myght such a hwe lach, as growe grene as the gres and grener hit semed, then grene aumayl on golde lowande bryghter. Al studied that ther stod, and stalked hym nerre, wyth al the wonder of the worlde, what he worch schulde. For fele sellyes had thay sen, but such neuer are, for-thi for fantoum and fayryghe the folk there hit demed; therfore to answare was arghe mony athel freke, and al stouned at his steuen, and stonstil seten, in a swoghe sylence thurgh the sale riche, as al were slypped vpon slepe so slaked hor lotes in hyghe; I deme hit not al for doute, but sum for cortaysye, but let hym that al schulde loute, cast vnto that wyghe.",
          e: "There was looking long to behold this lord; every man marvelled what it might mean that a knight and a horse should take such a hue — to grow as green as the grass, and greener it seemed even than that, brighter than green enamel glowing on gold. All who stood there studied him and stepped nearer in wonder of the world, what he might do. Many marvels they had seen, but never such a one — and so they reckoned him a phantom and a fairy thing. Therefore many a noble warrior was afraid to answer, and all astounded at his voice, sat as still as stones, in a swooning silence through the rich hall, as though all had slipped into sleep, so slack went their voices on the sudden. I do not reckon it all for fear — but some for courtesy — letting him to whom they all owed obedience be the one to address that man.",
          n: "“For phantom and fairy thing they deemed it”: from the first instant Camelot reads the Green Knight as Otherworld — and they are right." },

        { w: "Thenn Arthour bifore the hi dece that auenture byholdes, and rekenly hym reuerenced, for rad was he neuer, and sayde, “wyghe, welcum iwys to this place, the hede of this ostel Arthour I hat, lyght luflych adoun, and lenge, I the praye, and quat so thy wylle is, we schal wyt after.” “Nay, as help me,” quod the hathel, “he that on hyghe syttes, to wone any quyle in this won, hit was not myn ernde; bot for the los of the lede is lyft up so hyghe, and thy burgh and thy burnes best ar holden, stifest vnder stel-gere on stedes to ryde, the wyghtest and the worthyest of the worldes kynde, preue for to play wyth in other pure laykes; and here is kydde cortaysye, as I haf herd carp, and that hath wayned me hider, I-wyis, at this tyme. Ye may be seker by this braunch that I bere here, that I passe as in pes, and no plyght seche; for had I founded in fere, in feghtyng wyse, I haue a hauberghe at home and a helme bothe, a schelde, and a scharp spere, schinande bryght, ande other weppenes to welde, I wene wel als, but for I wolde no were, my wedes ar softer. But if thou be so bold as alle burnes tellen, thou wyl grant me godly the gomen that I ask, by ryght.” Arthour con onsware, and sayd, “sir cortays knyght, if thou craue batayl bare, here failes thou not to fyght.”",
          e: "Then Arthur looked upon the adventure before the high dais, and graciously gave him reverence — for he was never afraid — and said: “Sir, welcome indeed to this place. The head of this house am I, Arthur. Alight, I pray you, gently, and stay; and whatever your will is, we shall learn it after.” “Nay, so help me,” said the lord, “He that sits on high — to dwell any while in this dwelling was not my errand. But because the renown of you here is lifted up so high, and your city and your knights held best — stiffest in armour, riding on steeds, the bravest and the worthiest of the world's kindred, proven to play with in other noble games — and because here is famed courtesy, as I have heard it told, that has summoned me hither in truth at this time. You may be sure by this branch that I bear here that I come in peace and seek no quarrel; for had I set out in arms, in fighting wise, I have a hauberk at home, and a helm too, a shield, and a sharp spear shining bright, and other weapons to wield I know well also — but because I wanted no war, my garments are softer. Yet if you are as bold as all men tell, you will graciously grant me the game that I ask of right.” Arthur answered and said: “Sir courteous knight, if you crave a bare-handed combat, here you shall not fail to find a fight.”" },

        { w: "“Nay, frayst I no fyght, in fayth I the telle, hit arn aboute on this bench but berdles chylder; if I were hasped in armes on a heghe stede, here is no mon me to mach, for myghtes so wayke. For-thy I craue in this court a crystmas gomen, for hit is yol and nwe yer, and here ar yep mony; if any so hardy in this hous holdes hym-seluen, be so bolde in his blod, brayn in hys hede, that dar stifly strike a strok for an other, I schal gif hym of my gyft thys giserne ryche, this ax, that is heué in-nogh, to hondele as hym lykes, and I schal bide the fyrst bur, as bare as I sitte. If any freke be so felle to fonde that I telle, lepe lyghtly me to, and lach this weppen, I quit clayme hit for euer, kepe hit as his auen, and I schal stonde hym a strok, stif on this flet, elles thou wyl dyght me the dom to dele hym an other, barlay; and yet gif hym respite, a twelmonyth and a day; — now hyghe, and let se tite, dar any her-inne oght say.”",
          e: "“Nay, I seek no fight, in faith I tell you — there are but beardless children all about on this bench. Were I clasped in armour on a high steed, here is no man to match me, for the might here is so weak. So I crave in this court a Christmas game; it is Yule and New Year, and here are many lusty men. If any here is so hardy as to hold himself bold of blood and brave-brained in his head, and dares stoutly strike a stroke for another, I shall give him as my gift this rich battleaxe — this axe, heavy enough, to handle as he likes — and I shall abide the first blow as bare as I sit. If any fellow is fierce enough to take up what I propose, let him leap lightly to me and grasp this weapon — I quit-claim it forever, let him keep it as his own — and I shall stand his stroke standing firm on this floor, on one condition: that you grant me the right to deal him another in turn, in fair exchange, and yet give him grace, a twelvemonth and a day. Now then, be quick, and let us see whether any here dares say a word.”",
          n: "The beheading game — a Celtic motif also found in the older Irish tale Bricriu's Feast. The bargain is impossible: any man who takes the blow must know the return is death." },

        { w: "If he hem stowned vpon fyrst, stiller were thanne alle the hered-men in halle, the hyghe and the loghe; the renk on his rounce hym ruched in his sadel, and runisch-ly his rede yghen he reled aboute, bende his bresed broghes, bly-cande grene, wayued his berde for to wayte quo-so wolde ryse. When non wolde kepe hym with carp he coghed ful hyghe, ande rimed hym ful richley, and ryght hym to speke: “What, is this Arthures hous,” quod the hathel thenne, “that al the rous rennes of, thurgh ryalmes so mony? Where is now your sourquydrye and your conquestes, your gryndel-layk, and your greme, and your grete wordes? Now is the reuel and the renoun of the rounde table ouer-walt wyth a worde of on wyghes speche; for al dares for drede, with-oute dynt schewed!” Wyth this he laghes so loude, that the lorde greued; the blod schot for scham in-to his schyre face and lere; he wex as wroth as wynde, so did alle that ther were, the kyng as kene by kynde, then stod that stif mon nere.",
          e: "If he had startled them at first, stiller still then were all the household in hall, both the high and the low. The lord on his rouncey shifted himself in his saddle, and savagely rolled his red eyes about, bent his bristled brows, glittering green; waved his beard, watching to see who would rise. When none would meet him with a word, he coughed loudly, and stretched himself in lordly fashion, and made ready to speak again. “What — is this Arthur's house,” said the lord then, “of which the rumour runs through so many realms? Where now is your proud spirit and your conquests, your fierce-fighting, your wrath, your great words? Now is the revel and the renown of the Round Table overturned by one word of one man's speech — for all of you flinch in fear before any blow is even given!” With that he laughed so loud that the king was grieved; the blood shot for shame into his fair face and his cheek. He grew as wroth as the wind, and so did all that were there; the king, keen by nature, then stood close before that stout man." },

        { w: "And sayde, “hathel, by heuen thyn askyng is nys, and as thou foly hath frayst, fynde the be-houes; I know no gome that is gast of thy grete wordes. Gif me now thy geserne, vpon godes halue, and I schal baythen thy bone, that thou boden habbes.” Lyghtly lepes he hym to, and laght at his honde; then feersly that other freke vpon fote lyghtis. Now hath Arthure his axe, and the halme grypes, and sturnely stures hit aboute, that stryke wyth hit thoght. The stif mon hym bifore stod vpon hyght, herre then ani in the hous by the hede and more; wyth sturne schere ther he stod, he stroked his berde, and wyth a countenaunce dryghe he droghe doun his cote, no more mate ne dismayd for hys mayn dintes, then any burne vpon bench hade broght hym to drynk of wyne. Gawan, that sate by the quene, to the kyng he can enclyne, “I be-seche now with sagghes sene, this melly mot be myne.”",
          e: "And he said: “Sir, by heaven your asking is folly, and as you have sought folly, find it you must. I know no man here afraid of your great words. Give me your axe now, in God's name, and I shall grant the boon that you have asked.” Lightly he leapt to him and laid hold of his hand; then fiercely that other man stepped down on foot. Now Arthur has the axe, and grips the haft, and stoutly swings it about, as one who means to strike with it. The bold knight stood before him on his feet, taller than any in the hall by a head and more; with stern face there he stood, stroking his beard, and with a dry countenance drew down his coat — no more dismayed at the coming great blow than if any man at the bench had brought him a drink of wine. Then Gawain, who sat beside the queen, bowed to the king: “I beseech you now in plain words, let this fight be mine.”" },

        { w: "“Wolde ye, worthylych lorde,” quod Gawan to the kyng, “bid me boghe fro this benche, and stonde by yow there, that I wyth-oute vylanye myght voyde this table, and that my legge lady lyked not ille, I wolde com to your counseyl, bifore your cort ryche. For me think hit not semly, as hit is soth knawen, ther such an askyng is heuened so hyghe in your sale, thaghe ye yourself be talenttyf to take hit to your-seluen, whil mony so bolde yow aboute vpon bench sytten, that vnder heuen, I hope, non haghe er of wylle, ne better bodyes on bent, ther baret is rered. I am the wakkest, I wot, and of wyt feblest, and lest lur of my lyf, quo laytes the sothe, but for as much as ye ar myn em, I am only to prayse, no bounté but your blod I in my bodé knowe; and sythen this note is so nys, that noght hit yow falles, and I haue frayned hit at yow fyrst, foldes hit to me, and if I carp not comlyly, let alle this cort rych, bout blame.” Ryche to-geder con roun, and sythen thay redden alle same, to ryd the kyng wyth croun, and gif Gawan the game.",
          e: "“Would you, honoured lord,” said Gawain to the king, “bid me rise from this bench and stand by you there — that I might without discourtesy leave this table, and so my liege lady be not displeased — I would come to your counsel before this rich court. For it seems to me not seemly, as is widely known to be the truth, that when such an asking is raised so high in your hall, you yourself, though willing to take it on yourself, should answer it, while so many bold men sit about you on your benches — than whom, I believe, none under heaven is keener of will, no better bodies on a battlefield where strife is raised. I am the weakest of them, I know, and feeblest of wit, and the loss of my life would be the least of any, whoever looks at the truth; only that you are my uncle is any praise to me — no virtue beyond your blood do I know in my body. And since this is so foolish a matter that it is in no way for you, and since I have first asked it of you, hand it over to me; and if I do not speak fittingly, let this rich court blame me, with no blame to you.” The nobles whispered together — and then they all agreed, to free the crowned king and give Gawain the game.",
          n: "Gawain's intervention is one of the most famous courtly speeches in Middle English — exquisite humility that is also a quietly perfect manoeuvre, since it shames no one and gives Arthur a graceful way out." },

        { w: "Then comaunded the kyng the knyght for to ryse; and he ful radly vp ros, and ruchched hym fayre, kneled doun bifore the kyng, and cacches that weppen; and he luflyly hit hym laft, and lyfte vp his honde, and gef hym goddes blessyng, and gladly hym biddes that his hert and his honde schulde hardi be bothe. “Kepe the cosyn,” quod the kyng, “that thou on kyrf sette, and if thou redes hym ryght, redly I trowe, that thou schal byden the bur that he schal bede after.” Gawan gots to the gome, with giserne in honde, and he baldly hym bydes, he bayst neuer the helder, then carppes to sir Gawan the knyght in the grene, “Refourme we oure for-wardes, er we fyrre passe. Fyrst I ethe the, hathel, how that thou hattes, that thou me telle truly, as I tryst may?” “In god fayth,” quod the goode knyght, “Gawan I hatte, that bede the this buffet, quat-so bi-falles after, and at this tyme twelmonyth take at the another, wyth what weppen so thou wylt, and wyth no wyghe elles, on lyue.” That other on-swares agayn, “Sir Gawan, so mot I thryue, as I am ferly fayn, this dint that thou schal dryue.”",
          e: "Then the king commanded the knight to rise; and he rose up promptly and made himself ready, knelt down before the king, and took up the weapon. The king kindly let it pass to him, and lifted his hand, and gave him God's blessing, and gladly bade him be both hardy of heart and of hand. “Take care, cousin,” said the king, “that you set your cut aright; and if you handle him as you should, I truly believe you shall be able to abide the blow he shall give back after.” Gawain steps up to the knight, axe in hand, and the other boldly awaits him, never abashed in the slightest. Then the knight in the green spoke to Sir Gawain: “Let us go over our bargain again before we go further. First I ask you, sir, what is your name — that you tell me truly, that I may trust it?” “In good faith,” said the good knight, “Gawain I am called — I who give you this buffet, whatever may befall after; and at this time a twelvemonth from now, I shall take from you another, with whatever weapon you choose, and from no other man living.” The other answers him again: “Sir Gawain, as I may thrive, I am most glad that you shall deal this blow.”" },

        { w: "“By God,” quod the grene knyght, “sir Gawan, melykes, that I schal fange at thy fust that I haf frayst here; and thou hath redily rehersed, by resoun ful trwe, clanly al the couenaunt that I the kynge asked, saf that thou schal siker me, segge, by thi trawthe, that thou schal seche me thi-self, where-so thou hopes I may be funde vpon folde, and foch the such wages as thou deles me to day, bifore this douthe ryche.” “Where schulde I wale the,” quod Gauan, “where is thy place? I wot neuer where thou wonyes, by hym that me wroght, ne I know not the, knyght, thy cort, ne thi name. But teche me truly therto, and telle me howe thou hattes, and I schal ware alle my wyt to wynne me theder, and that I swere the for sothe, and by my seker traweth.” “That is in-nogh in nwe yer, hit nedes no more,” quod the gome in the grene to Gawan the hende, “Yif I the telle trwly, quen I the tape haue, and thou me smothely hath smyten, smartly I the teche of my hous, and my home, and myn owen nome, then may thou frayst my fare, and forwardes holde, and if I spende no speche, thenne spedes thou the better, for thou may leng in thy londe, and layt no fyrre, but slokes; ta now thy grymme tole to the, and let se how thou cnokes.” “Gladly sir, for sothe,” quod Gawan; his ax he strokes.",
          e: "“By God,” said the Green Knight, “Sir Gawain, it pleases me well that I shall take from your fist what I have sought here; and you have readily rehearsed, in plain reason, every clause of the covenant I asked of the king — save only that you must pledge me, sir, on your troth, that you shall seek me yourself wherever you may suppose me to be found on the earth, and fetch yourself such wages as you deal me today, before this rich company.” “Where shall I look for you?” said Gawain. “Where is your place? I know not at all where you dwell, by Him that made me; nor do I know your court, knight, nor your name. But teach me truly the way, and tell me how you are called, and I shall lay out all my wit to win there — and that I swear in truth, by my sure pledge.” “That is enough at New Year, no more is needed,” said the man in the green to courteous Gawain. “If I tell you truly, when I have taken the blow and you have smoothly struck me, swiftly shall I teach you of my house and my home and my own name. Then you may seek my dwelling and keep the bargain. But if I do not give speech at all, the better for you — for you may stay in your land and look no further; but enough of this. Take now your grim tool to you, and let us see how you knock.” “Gladly, sir, in truth,” said Gawain; he stroked his axe." },

        { w: "The grene knyght vpon grounde graythely hym dresses, a littel lut with the hede, the lere he discoueres, his longe louelych lokkes he layd ouer his croun. Let the naked nec to the note schewe. Gauan gripped to his ax, and gederes hit on hyght, the kay fot on the folde he be-fore sette, let hit doun lyghtly lyght on the naked, that the scharp of the schalk schyndered the bones, and schrank thurgh the schyire grece, and scade hit in twynne, that the bit of the broun stel bot on the grounde. The fayre hede fro the halce hit felle to the erthe, that fele hit foyned wyth her fete, there hit forth roled; the blod brayd fro the body, that blykked on the grene; and nawther faltered ne fel the freke neuer the helder, but stythly he start forth vpon styf schonkes, and runyschly he raght out, there as renkkes stoden, laght to his lufly hed, and lyft hit vp sone; and sythen boghes to his blonk, the brydel he cachches, steppes in to stel bawe and strydes alofte, and his hede by the here in his honde haldes; and as sadly the segge hym in his sadel sette, as non vnhap had hym ayled, thaghe hedles he were, in stedde; he brayde his bluk aboute, that vgly bodi that bledde, moni on of hym had doute, by that his resounes were redde.",
          e: "The Green Knight upon the ground readied himself, bent his head a little and bared his face — laid his long lovely locks over his crown, and let the bare neck show for the work. Gawain gripped his axe and gathered it on high, set his left foot forward on the floor, and let it come down lightly upon the naked neck — so that the sharp blade shore through the bones, sank through the bright flesh and parted it in two, and the bit of the brown steel bit on the ground beneath. The fair head fell from the neck to the earth; many kicked it about with their feet as it rolled forth; the blood spurted from the body, glittering on the green. And yet the man neither faltered nor fell the slightest the more — but stoutly he started forth upon stiff legs, and savagely he reached out where the men stood by, caught hold of his handsome head and lifted it up at once; and then turned to his horse, caught the bridle, stepped into the stirrup and strode aloft — holding his head by the hair in his hand. And as soberly the man sat in his saddle as though no harm had come to him, though headless he was, in the place. He swung his trunk about — that ugly body that bled — and many a man feared him by the time his words were read out." },

        { w: "For the hede in his honde he haldes vp euen, to-ward the derrest on the dece he dresses the face, and hit lyfte vp the yghe-lyddes, and loked ful brode, and meled thus much with his muthe, as ye may now here. “Loke, Gawan, thou be graythe to go as thou hettes, and layte as lelly til thou me, lude, fynde, as thou hath hette in this halle, herande thise knyghtes; to the grene chapel thou chose, I charge the to fotte, such a dunt as thou hath dalt disserued thou habbes, to be yederly yolden on nw yeres morn; the knyght of the grene chapel men knowen me mony; for-thi me forto fynde if thou frayste3, fayles thou neuer, therfore com, other recreaunt be calde the be-houeus.” With a runisch rout the raynes he tornes, halled out at the hal-dor, his hed in his hande, that the fyr of the flynt flaghe fro fole houes. To quat kyth he be-com, knwe non there, neuermore then thay wyste fram quethen he was wonnen; what thenne? The kyng and Gawen thare, at that grene thay laghe and grenne, yet breued was hit ful bare, a meruayl among tho menne.",
          e: "For he held his head up straight in his hand, and toward the noblest on the dais he turned the face; and it lifted up its eyelids and stared full wide, and spoke this much with its mouth, as you may now hear. “See, Gawain, that you be ready to go as you have promised, and seek truly until you find me, sir, as you have promised in this hall in the hearing of these knights. To the Green Chapel you shall go, I charge you, to fetch such a blow as you have dealt me — well-deserved you have it — to be readily given back on New Year's morning. As Knight of the Green Chapel many know me; therefore, if you set out to find me, you shall not fail. Come therefore — or recreant must you be called.” With a fierce wrench he turned the reins, and bolted out at the hall door, his head in his hand, so that fire flew from the flint of his horse's hooves. To what country he had come, none there knew, no more than they knew from whence he had been gotten. What then? The king and Gawain there at that green one laughed and grinned — yet truly it was made known among those men as a marvel.",
          n: "The talking severed head is the moment everyone remembers. The Green Chapel — wherever it is — becomes the haunted destination of the whole poem." },

        { w: "Thaghe Arther the hende kyng at hert hade wonder, he let no semblaunt be sene, but sayde ful hyghe to the comlych quene, wyth cortays speche, “Dere dame, to day demay yow neuer; wel by-commes such craft vpon cristmasse, laykyng of enterludes, to laghe and to syng. Among thise, kynde caroles of knyghtes and ladyes; neuer-the-lece to my mete I may me wel dres, for I haf sen a selly, I may not for-sake.” He glent vpon sir Gawen, and gaynly he sayde, “Now sir, heng vp thyn ax, that hath in-nogh hewen.” And hit was don abof the dece, on doser to henge, ther alle men for meruayl myght on hit loke, and by trwe tytel ther-of to telle the wonder. Thenne thay boghed to a borde thise burnes to-geder, the kyng and the gode knyght, and kene men hem serued of alle dayntyghes double, as derrest myght falle, wyth alle maner of mete and mynstralcie bothe; wyth wele walt thay that day, til worthed an ende, in londe. Now thenk wel, sir Gawan, for wothe that thou ne wonde, this auenture forto frayn, that thou hath tan on honde.",
          e: "Though Arthur the courteous king had wonder in his heart, he let no sign of it be seen, but said full loudly to the comely queen, with courteous speech: “Dear lady, do not let this day dismay you ever; such craft well becomes Christmastide — the playing of interludes, the laughter and the singing among the gentle carols of knights and ladies. Nevertheless I may now address myself well to my meat, for I have seen a marvel, I cannot deny it.” He glanced at Sir Gawain and graciously said: “Now, sir, hang up your axe — it has hewn enough.” And it was placed above the dais, hung on the tapestry-screen, where all men might look upon it for the marvel and tell the wonder of it by the true title that hung there. Then they bowed to a board together, these men — the king and the good knight — and keen attendants served them with all dainties doubled, as the noblest might befall, with every kind of meat and minstrelsy both. With joy they made their way through that day until it came to its end, in the land. Now think well, Sir Gawain — for no danger shrink from going to find the adventure that you have taken in hand.",
          n: "Fitt I closes here on the narrator's address to Gawain. Fitt II opens with the long, slow turn of the seasons toward next Christmas, the great arming-scene, and the ride into the wilderness." },
      ],
    },
  ],
};
