// AUTO-GENERATED by scripts/sync-zhouyi.mjs from read/iching/data.js — do not edit by hand.
// The oracle's anchor copy of our open Zhouyi translation (Judgments only). The two
// surfaces (g.mino.mobi, read.mino.mobi) deploy from different directories and can't
// share a served file, so the Judgment text is mirrored here for g.mino.mobi/yijing.
// read/iching/data.js is canonical; rerun `node scripts/sync-zhouyi.mjs` after edits.
export const ZHOUYI = {
  1: { z: "元亨利貞", py: "yuán hēng lì zhēn",
      e: "The Creative. From the origin it flows through to success; it furthers, and it rewards the steadfast." },
  2: { z: "元亨，利牝馬之貞。君子有攸往，先迷後得主，利。西南得朋，東北喪朋。安貞吉。", py: "yuán hēng, lì pìnmǎ zhī zhēn. jūnzǐ yǒu yōu wǎng, xiān mí hòu dé zhǔ, lì. xīnán dé péng, dōngběi sàng péng. ān zhēn jí.",
      e: "The Receptive. From the origin, success; favourable is the steadfastness of a mare. The noble one has somewhere to go: at first he loses the way, but later finds a master. Favourable. In the southwest he gains companions; in the northeast he loses companions. In quiet steadfastness, good fortune." },
  3: { z: "元亨利貞，勿用有攸往，利建侯。", py: "yuán hēng lì zhēn, wù yòng yǒu yōu wǎng, lì jiàn hóu.",
      e: "Difficulty at the Beginning. Sublime success; it furthers to be steadfast. Do not set out anywhere. It furthers to install helpers." },
  4: { z: "亨。匪我求童蒙，童蒙求我。初筮告，再三瀆，瀆則不告。利貞。", py: "hēng. fěi wǒ qiú tóng méng, tóng méng qiú wǒ. chū shì gào, zài sān dú, dú zé bù gào. lì zhēn.",
      e: "Youthful Folly. Success. It is not I who seek the young and foolish; the young and foolish seek me. At the first divination I answer; a second and third profane it, and the profaned I do not answer. It furthers to be steadfast." },
  5: { z: "有孚，光亨，貞吉。利涉大川。", py: "yǒu fú, guāng hēng, zhēn jí. lì shè dà chuān.",
      e: "Waiting. There is sincerity: shining success, and steadfast good fortune. It furthers to cross the great water." },
  6: { z: "有孚窒，惕中吉，終凶。利見大人，不利涉大川。", py: "yǒu fú zhì, tì zhōng jí, zhōng xiōng. lì jiàn dàrén, bù lì shè dà chuān.",
      e: "Conflict. Sincerity blocked. Stay wary and stop midway — good fortune; press it to the end — misfortune. It furthers to see the great person; it does not further to cross the great water." },
  7: { z: "貞，丈人吉，无咎。", py: "zhēn, zhàng rén jí, wú jiù.",
      e: "The Army. Steadfastness; a seasoned leader: good fortune, no blame." },
  8: { z: "吉。原筮，元永貞，无咎。不寧方來，後夫凶。", py: "jí. yuán shì, yuán yǒng zhēn, wú jiù. bù níng fāng lái, hòu fū xiōng.",
      e: "Holding Together. Good fortune. Consult once more at the source: with sublime and lasting steadfastness, no blame. The unsettled come to join; but for the one who comes too late, misfortune." },
  9: { z: "亨。密雲不雨，自我西郊。", py: "hēng. mì yún bù yǔ, zì wǒ xī jiāo.",
      e: "The Taming Power of the Small. Success. Dense clouds, but no rain, from our western border." },
  10: { z: "履虎尾，不咥人，亨。", py: "lǚ hǔ wěi, bù dié rén, hēng.",
      e: "Treading on the tiger’s tail: it does not bite the man. Success." },
  11: { z: "小往大來，吉亨。", py: "xiǎo wǎng dà lái, jí hēng.",
      e: "Peace. The small departs, the great approaches. Good fortune, success." },
  12: { z: "否之匪人，不利君子貞，大往小來。", py: "pǐ zhī fěi rén, bù lì jūnzǐ zhēn, dà wǎng xiǎo lái.",
      e: "Standstill. It is the work of the wrong people; it does not further the noble one’s steadfastness. The great departs and the small approaches." },
  63: { z: "亨小，利貞，初吉終亂。", py: "hēng xiǎo, lì zhēn, chū jí zhōng luàn.",
      e: "After Completion. Success in small things; it furthers to be steadfast. At first, good fortune; in the end, disorder." },
  64: { z: "亨，小狐汔濟，濡其尾，无攸利。", py: "hēng, xiǎo hú qì jì, rú qí wěi, wú yōu lì.",
      e: "Before Completion. Success. The little fox, all but across, wets its tail. Nothing is favourable [if it falters]." },
};
