/* Story graph — Pwyll Pendefig Dyfed mapped onto Vladimir Propp's "Morphology
   of the Folktale" (1928): the 31 narrative functions of the wonder-tale.
   The First Branch is the most Propp-rich tale in our corpus — the spine
   gets traversed three times, in three braided arcs that share two heroes
   (Pwyll and Teirnon) and one heroine (Rhiannon): the Glyn Cuch breach and
   the year-exchange with Arawn; the Gorsedd marvel, the rash promise, the
   badger in the bag, and the wedding; the son taken at midnight, the false
   accusation, and the recovery from Teirnon's hand. The deepest absences
   are U Punishment (no figure in the tale is punished — not Hafgan who is
   killed by contract, not Gwawl who is ransomed, not the six women who
   lied) and I Branding (Pwyll carries no mark; Rhiannon's mark is the
   public penance and that ends). Loaded after tale.js; attaches to
   window.PWYLL. */
window.PWYLL = window.PWYLL || {};
window.PWYLL.propp = {
  intro: "Propp argued that wonder-tales, however different on the surface, drew their events from a single fixed sequence of <strong>31 functions</strong> — Absentation, Reconnaissance, Villainy, Departure, the Donor, Struggle, Victory, Liquidation, Return, Recognition, Restoration. <em>Pwyll Pendefig Dyfed</em> is the most Propp-rich tale in our four-poem corpus: the spine gets traversed three times, in three braided arcs sharing two heroes (Pwyll and Teirnon) and one heroine (Rhiannon). The compound structure is itself a Welsh-distinctive shape — Culhwch is a single task-quest, Gawain a single moral-test, Orfeo a single rescue, but Pwyll runs Glyn Cuch into Annwn into the Gorsedd into the bag into the midnight loss into the recovery, every arc a complete wonder-tale of its own. Below the six movements are laid against Propp's spine — 32 moves; what the tale leaves out (no Punishment, no Branding, no Pursuit) is the comparative payoff.",
  acts: [
    { id: "court",    label: "Court at Arberth, breach at Glyn Cuch", color: "#c9a24a" },
    { id: "annwn",    label: "The year in Annwn",                    color: "#6f9ac9" },
    { id: "bride",    label: "The Gorsedd, the bag, the wedding",    color: "#c97f9a" },
    { id: "loss",     label: "The midnight loss, the penance",       color: "#9a6f9a" },
    { id: "found",    label: "Teirnon's hand, the recognition",      color: "#7fb37f" },
  ],
  moves: [
    // ── Act 1: court ─────────────────────────────────────────────
    { act: "court", sym: "α", node: "Setting", name: "Initial situation", gloss: "The family and the hero are introduced.",
      realized: "Pwyll, prince of Dyfed, sets out from Arberth with his companions to hunt at Glyn Cuch. He hears a second pack on the same stag, loses his companions, and goes forward alone — Welsh narrative stripping the hero down to himself before the encounter that matters.", passage: 1 },
    { act: "court", sym: "A", node: "The breach", name: "Villainy / Lack", gloss: "A harm or lack opens the tale.",
      realized: "Pwyll drives off the strange (shining white, red-eared) pack that killed the stag, sets his own on the carcass, and never sees it as a wrong. Arawn, lord of Annwn, names it in his first speech: <em>ansyberwyt</em>, discourtesy, the breach that is owed a hundred stags' worth of dishonour.", passage: 1 },

    // ── Act 2: annwn ─────────────────────────────────────────────
    { act: "annwn", sym: "B", node: "The bargain", name: "Mediation", gloss: "The lack is made known; the hero is sent forth.",
      realized: "Arawn names himself, names his enemy Hafgan, and proposes the year-exchange. Pwyll takes Arawn's form for a year and slays Hafgan with one blow at the ford; in return Arawn rules Dyfed in Pwyll's form, and the breach of courtesy is repaired.", passage: 1 },
    { act: "annwn", sym: "C", node: "Acceptance", name: "Beginning counteraction", gloss: "The hero agrees to act.",
      realized: "<em>Yn llawenn</em> — \"right gladly\" — said Pwyll, \"and I shall go forth.\" The bargain is sealed at the hunting-ground; Arawn promises to lead him to the boundary.", passage: 1 },
    { act: "annwn", sym: "↑", node: "Into Annwn", name: "Departure", gloss: "The hero leaves home.",
      realized: "Arawn lays his form and likeness on Pwyll (<em>pryt</em> and <em>ansawd</em> — the literal disguise that lets him walk into the Otherworld court), and leads him to the threshold. Pwyll walks into the Annwn court alone; no servant suspects.", passage: 2 },
    { act: "annwn", sym: "D", node: "The chaste sleep", name: "Donor's first function", gloss: "The donor proposes a test.",
      realized: "Arawn's queen (whose name the tale keeps unspoken) is set in Pwyll's bed each night, with Arawn's full form upon Pwyll. The test is whether he will treat her as his own. Arawn never warns him that he is being watched.", passage: 2 },
    { act: "annwn", sym: "E", node: "Face to the wall", name: "Hero's reaction", gloss: "The hero responds.",
      realized: "Every night for the year Pwyll turns his face to the bed-edge and his back to her, and says not a word until morning. The Welsh prose names no internal monologue, no struggle. The act is reported as the natural consequence of <em>cedymdeithas</em> — companionship. (For the cross-tale layer: a refined H1556 fidelity test absent in this form from all three other annotated poems.)", passage: 2 },
    { act: "annwn", sym: "H", node: "The ford", name: "Struggle", gloss: "Hero and antagonist meet in direct contest.",
      realized: "At the year's end, at the ford, a herald rises and proclaims the protocol of judicial duelling: <em>y rwng y deu gorff wylldeu</em>, between the two bodies. The two crowned kings of Annwn approach in the middle of the water.", passage: 2 },
    { act: "annwn", sym: "J", node: "The single blow", name: "Victory", gloss: "The antagonist is defeated.",
      realized: "Pwyll, in Arawn's form, strikes Hafgan one mortal blow — boss split, armour broken, body cast an arm's length and a spear-length beyond the horse's rump. Hafgan begs to be finished; Pwyll refuses, by Arawn's instruction: one stroke only, never a second. <strong>The M223 one-blow contract exactly inverted from Gawain</strong> — there the blow received must be returned; here the blow given must not be repeated.", passage: 2 },
    { act: "annwn", sym: "K", node: "Two kingdoms", name: "Liquidation of lack", gloss: "The lack is undone.",
      realized: "Hafgan's nobles testify there is no king but Arawn now. By midday on the morrow the two contending kingdoms of Annwn are united in Pwyll's hand. The breach of courtesy at Glyn Cuch is repaired with the conquest of an entire Otherworld.", passage: 2 },
    { act: "annwn", sym: "↓ / Q", node: "The mirror scene", name: "Return / Recognition", gloss: "The hero returns; the truth is seen.",
      realized: "At Glyn Cuch on the appointed day, Arawn meets him; they restore each other's forms. Arawn rides home and behaves as a husband always behaves at homecoming; his wife is bewildered. The recognition runs in two registers — Arawn's prayer of relief (<em>strong and single is the companionship</em>) and the wife's appraisal of Pwyll's faithfulness. The chaste sleep is recognised as the fidelity test it always was.", passage: 2 },
    { act: "annwn", sym: "T", node: "Penn Annwfn", name: "Transfiguration", gloss: "The hero's standing changes.",
      realized: "Because of the loaned year, the prosperous rule, and the joining of the two kingdoms, his name \"Pwyll Prince of Dyfed\" weakens, and from then on he is called <em>Pwyll Penn Annwfn</em> — Pwyll Head of Annwn — through all subsequent Welsh tradition.", passage: 2 },

    // ── Act 3: bride ─────────────────────────────────────────────
    { act: "bride", sym: "α'", node: "Gorsedd", name: "Initial situation (re-set)", gloss: "A new arc opens with the formulaic Welsh phrase.",
      realized: "<em>A threigylgueith yd oed yn Arberth</em> — \"and one time he was at Arberth.\" Pwyll climbs the Gorsedd Arberth, the named marvel-mound whose custom is one of two: either wounds, or a marvel. He chooses the marvel.", passage: 3 },
    { act: "bride", sym: "ε", node: "Three days riding", name: "Reconnaissance", gloss: "A figure scouts the hero or his court.",
      realized: "Rhiannon, on a great pale-white horse in gold-shot silk, rides past the Gorsedd three days running, at a pace no pursuer on foot or horseback can match — the famous chase-without-catching, a marvel the Welsh imagination uses to mark her as Otherworld-touched. The Z65 white iconography binds her to Arawn's hounds and to the snow-white retinue Sir Orfeo will inherit four centuries later.", passage: 3 },
    { act: "bride", sym: "C", node: "The asking", name: "Counteraction", gloss: "The hero acts.",
      realized: "On the third day Pwyll calls out: <em>for the love of the man you most love, wait for me.</em> Rhiannon stops at once and names what the chase could not deliver: <em>it had been better for the horse if you had asked me long ago.</em> She names herself, her unwanted betrothal to Gwawl, her love for Pwyll already in place.", passage: 3 },
    { act: "bride", sym: "↑", node: "Year and a night", name: "Departure", gloss: "The hero departs for the appointed meeting.",
      realized: "A second <em>blwydyn y heno</em> (\"a year from tonight\") bargain is sealed at the meeting on the road — exactly parallel to Movement I's. At year's end Pwyll arrives at Hyfaidd Hen's court with a hundred horsemen for the wedding feast.", passage: 4 },
    { act: "bride", sym: "η", node: "The unread oath", name: "Trickery", gloss: "The antagonist deceives.",
      realized: "At the start of the after-meal drinking, Gwawl son of Clud enters in royal silk and asks Pwyll for a request before naming what it is. <strong>The same M223 rash-promise architecture as Arthur granting Bertilak's terms unread</strong> in Sir Gawain Fitt I, four hundred years later. Welsh and English imaginations meet on the same single sentence.", passage: 4 },
    { act: "bride", sym: "θ", node: "Given word", name: "Complicity", gloss: "The hero unwittingly assents.",
      realized: "Pwyll grants whatever, in front of nobles: <em>whatever you ask of me, as far as I can grant it, you shall have.</em> Gwawl then names what Pwyll has just given away — the bride, the feast, the preparation. Pwyll falls silent; the rash promise has bound the king.", passage: 4 },
    { act: "bride", sym: "D", node: "Rhiannon's plan", name: "Donor's function (inverted)", gloss: "The donor is the heroine herself; the plot is hers.",
      realized: "Rhiannon, alarmed too late, designs the entire counter-plot: the small unfillable bag, the year-from-tonight redirection, the device of asking the noble to step on the food, the horn-signal. <em>The Welsh hero gets the title-page; the Welsh heroine writes the plot.</em>", passage: 4 },
    { act: "bride", sym: "F", node: "The bag", name: "Receipt of magical agent", gloss: "The hero receives a magical agent.",
      realized: "Rhiannon hands Pwyll the small bag, with the enchantment laid on it that whatever is put in shall remain insufficient. Pwyll keeps it for a year, brings it to Gwawl's feast hidden under heavy old rags and oversized foot-coverings — the K1810 beggar's-disguise that Sir Orfeo will reuse for his own homecoming.", passage: 4 },
    { act: "bride", sym: "H", node: "Badger in the bag", name: "Struggle", gloss: "The hero meets the antagonist.",
      realized: "In disguise, with the bag, Pwyll comes into Gwawl's feast and asks only for a small bag's fill of food. The bag swallows the food and remains empty. Gwawl, at Rhiannon's prompting (<em>a geimat</em>, \"heroic one\"), steps in to press the food down. Pwyll turns the bag, ties the strings, sounds the horn. The household descends. <em>And that was the first time the badger-in-the-bag game was played</em> — A1654 origin of a folk-game, parallel to Sir Orfeo's A1450 (origin of the lay) and Sir Gawain's A1654 (the green sash adopted as Round Table livery).", passage: 4 },
    { act: "bride", sym: "J", node: "Sureties given", name: "Victory", gloss: "The antagonist yields by legal pledge.",
      realized: "Hyfaidd Hen and Rhiannon agree that bag-killing is no proper death. Gwawl pledges (under named sureties, by the form Rhiannon framed) never to seek vengeance, and is released to go home wounded. <em>The Welsh court's preference for legal architecture over execution.</em> Structurally the inverse of Hafgan's clean death-at-the-ford in Movement II: Pwyll-as-Arawn killed; Pwyll-as-himself ransomed.", passage: 4 },
    { act: "bride", sym: "W", node: "Wedding", name: "Wedding", gloss: "The hero marries.",
      realized: "The hall is made ready. Pwyll and Rhiannon spend the night in delight and stillness. The next morning Pwyll satisfies the bards; Hyfaidd Hen offers the customary delay before the bride travels; Pwyll refuses — <em>from here we shall go together</em>. They ride home to Arberth, on Rhiannon's terms, at his side.", passage: 4 },

    // ── Act 4: loss ──────────────────────────────────────────────
    { act: "loss", sym: "β", node: "Midnight cradle", name: "Absentation", gloss: "A family member is taken.",
      realized: "Two prosperous years at Arberth, then political pressure for an heir from the nobles at Preseli, then one more year granted. A son is born to Pwyll and Rhiannon. Six women are set to guard mother and child. They sleep before midnight; toward dawn they wake to find the boy gone. The Welsh prose names no agent. <strong>For the cross-tale layer, F320 fairies-abduct-mortals at the Welsh threshold-hour of midnight — cognate with Sir Orfeo's F255.2 (taking at noon), opposite end of the day.</strong>", passage: 5 },
    { act: "loss", sym: "L", node: "The six women's lie", name: "Unfounded claims", gloss: "False testimony is laid.",
      realized: "The six women, fearing the king's vengeance, kill some of the bitch's whelps, smear Rhiannon's hands and face with blood, scatter the bones, rehearse the testimony, and accuse her of having destroyed her own son. Rhiannon, who out-rode every pursuer on the Gorsedd and out-plotted Gwawl with the unfillable bag, here meets the one form of opposition she cannot work past: six women's coordinated false witness.", passage: 5 },
    { act: "loss", sym: "A'", node: "Horse at the gate", name: "Villainy (on the heroine)", gloss: "Harm is done to the hero or the family.",
      realized: "Pwyll refuses to set Rhiannon aside (<em>children I know there to be to her; the marriage holds</em>) — the moral pivot of the whole Movement. Rhiannon chooses the penance over dispute: seven years at the gate, on the mounting-block, telling every visitor the story, offering to carry guests to the court on her back as a horse. The queen whose iconography is the great pale-white horse, made into a horse at her own gate.", passage: 5 },

    // ── Act 5: found ─────────────────────────────────────────────
    { act: "found", sym: "C'", node: "Teirnon's vigil", name: "Counteraction (by a new hero)", gloss: "A second hero begins to act.",
      realized: "At Gwent Is Coed, far away, Teirnon Twryf Liant — <em>the best man in the world</em>, the Welsh narrator's quietest flag — has had his mare lose her foal to an unseen power every May Eve for years. On this May Eve he brings the mare inside, arms himself, and sits up to find the cause. <strong>Pwyll's tale changes hero at the recovery arc — distinctively Welsh; none of our other three tales transfers protagonist mid-story.</strong>", passage: 6 },
    { act: "found", sym: "H'", node: "The sword cut", name: "Struggle", gloss: "The hero meets the unseen power.",
      realized: "The foal is born. A great claw comes through the window for it. Teirnon cuts the arm off at the elbow. He hears a scream outside and runs after it, cannot see in the dark, remembers the open door, turns back.", passage: 6 },
    { act: "found", sym: "F'", node: "The boy at the door", name: "Receipt of magical agent (the goal itself)", gloss: "The hero receives the goal of the quest, by accident.",
      realized: "At the door — see — a swaddled boy in fine silk. <strong>The two thefts (Pwyll's son seven years ago, Teirnon's foals every May Eve since) were the work of the same hand</strong>, stopped by the same cut. The foal saved that night is the recognition-token: it will be given to the boy as he grows.", passage: 6 },
    { act: "found", sym: "Q", node: "By the father's form", name: "Recognition", gloss: "The hero is recognised.",
      realized: "Years later, Teirnon hears of Rhiannon's penance, looks at the boy carefully, and sees the form of Pwyll Penn Annwn — whom he had served before. <strong>Recognition by pure family resemblance — the cleanest single mechanism in our four-tale corpus.</strong> Sir Orfeo's steward recognises the harp before the man; Gawain's Bertilak reveals by his own confession; Welsh recognition here is just: I knew his father, and the boy looks like him.", passage: 6 },
    { act: "found", sym: "Ex", node: "The lie unmade", name: "Exposure", gloss: "False claims are exposed.",
      realized: "Teirnon rides to Arberth with the boy and two companions. Rhiannon at the mounting-block offers her back; the boy refuses, his first word in the tale: <em>nyt af i</em>, \"I shall not go.\" At the feast Teirnon shows the boy and tells the story. The company recognises the boy as Pwyll's son. Three sentences unmake the lie that ruled the kingdom for seven years.", passage: 6 },
    { act: "found", sym: "T", node: "Pryderi", name: "Transfiguration (the naming)", gloss: "The hero's standing is restored; a true name is given.",
      realized: "Rhiannon's word at the recognition gives the boy his true name. <em>That would be the lifting of my pryder (my anxiety) from me, if that were true.</em> Pendaran Dyfed pronounces: <em>Pryderi</em>, \"Care\", shall be his name. Pwyll affirms the Welsh principle: <em>most right to take the boy's name from the word his mother spoke at the glad tidings of him.</em> Rhiannon's seven years of penance end. Teirnon, offered the fairest jewels and the best horses and the most beloved hounds, takes none — <em>he wanted nothing</em>.", passage: 6 },
    { act: "found", sym: "W'", node: "Succession", name: "Wedding / continuation of the line", gloss: "The hero or his heir is wed; the tale closes.",
      realized: "Pryderi grows; succeeds Pwyll at the seven cantref of Dyfed; expands into the three cantref of Ystrad Tywi and the four cantref of Ceredigion (the seven cantref of Seisyllwch); marries Cigfa, daughter of Gwynn Gohoyw. The First Branch closes on the formula that closes every branch: <em>ac yuelly y teruyna y geing hon yma o'r Mabynnogyon</em>. \"And thus ends this Branch here of the Mabinogi.\"", passage: 6 },
  ],
  absent: {
    note: "<em>Pwyll Pendefig Dyfed</em>'s absences are precise and consistent with the broader Welsh narrative grammar already visible in the Pendragon crosswalk. Four things the tale refuses to do, and one shift it makes:",
    groups: [
      { label: "Punishment", syms: "U", text: "No figure in the tale is punished. Hafgan dies by contractual single combat (the bargain set by Arawn explicitly forbids the second blow). Gwawl is ransomed under sureties (not killed, not even held captive — sent home wounded with his nobles as guarantors). And — the most striking absence in the whole Mabinogi — <strong>the six women who lied are never accounted for</strong>: never named in the formal recognition scene, never charged, never expelled, never even denounced. The lie passes without judgment once Pryderi is restored. Welsh tradition's <em>U absent</em> pattern (also Gawain, also Orfeo) here taken to its furthest point." },
      { label: "Branding", syms: "I", text: "Pwyll carries no mark from his year in Annwn, no mark from the duel, no mark from the bag-trick. Rhiannon's mark — the public penance as the horse at the gate — is undone by the recognition and explicitly ends. Compare Sir Gawain's permanent nick at the neck and green-sash livery: Welsh tradition refuses the indelible sign." },
      { label: "Pursuit & Rescue", syms: "Pr Rs", text: "Neither hero is chased after his victory. The Fairy King's claw flees screaming into the dark, off the page; Teirnon pursues briefly, loses it in the night, returns. Gwawl is released and goes home. The Welsh wonder-tale (and the medieval Insular tradition generally — see the crosswalk row) does not use Pursuit-Rescue." },
      { label: "Hero substitution", syms: "(by C')", text: "The most distinctive structural move in any of our four tales. The recovery arc (Movement V → VI) is not Pwyll's at all: <strong>Teirnon Twryf Liant takes the hero-role for the rescue</strong>, with his own court, his own crisis (the foals stolen every May Eve), his own sword-cut against the unseen power. Pwyll has no part in his own son's recovery. None of our three other annotated poems transfers the protagonist mid-story." },
      { label: "Donor inversion", syms: "D as antagonist; D as heroine", text: "Propp's donor is usually a magical helper distinct from villain and hero. Pwyll inverts the role twice. <strong>In Arc 1, the donor is the villain</strong>: Arawn proposes the test as part of the bargain he himself imposes. <strong>In Arc 2, the donor is the heroine</strong>: Rhiannon teaches the plot and gives the magical agent (the bag). In Arc 3 there is no donor figure at all — the recovery is purely Teirnon's action against the unseen claw. The donor-slot in Welsh tradition is a moving part." },
    ],
    verdict: "Strip away the U Punishment (refused on three fronts), the I Branding (Welsh tradition's mark-refusal), and the Pr/Rs Pursuit-Rescue (medieval Insular constant absence) — and what remains is the cleanest possible <strong>compound wonder-tale</strong>: three full Lack → Counteraction → Departure → Donor → Struggle → Liquidation → Recognition arcs, braided into one continuous narrative across two heroes and one heroine. The cross-tale layer (now four tales deep) lets us name what the Welsh imagination keeps: the bargain, the recognition, the restored marriage, the named heir. What it refuses: the wound, the chase, the condemnation. The lie unmade by a sentence; the punishment not asked for; the kingdom continuous. This is the substrate the English Breton lays draw on, and the substrate Sir Gawain and Sir Orfeo each inherit a piece of.",
  },
};
