/* The motif index — Pwyll Pendefig Dyfed classified against the folklorists'
   "Dewey decimal": the Thompson Motif-Index (letter-classed call-numbers)
   and the Aarne-Thompson-Uther (ATU) tale-type index.

   The First Branch sits at the meeting of three folk-currents: the Welsh-
   distinctive year-exchange and the chaste-sleep test, the international
   Calumniated Wife cluster (ATU 712 / Constance romances), and the older
   Insular Otherworld-bride tradition (Rīgantonā / Epona-cognate, the
   chase-without-catching, the white-and-red colour-grammar of Annwn).
   With four annotated tales on this site, the comparative layer can name
   what is distinctively Welsh, what is shared with the English Breton
   lays (Sir Orfeo) and chivalric romances (Sir Gawain), and what is
   inherited from a deeper Insular substrate.

   This doubles as the second layer of the synergistic graph: each motif
   is a typed node, and its `passages` array is its set of EXHIBITS edges
   (motif → movement) in the shared annotation shape.

   Honesty: exact call-numbers are best-effort identifications, not the
   authoritative index. Each motif carries a confidence flag:
     high = well-attested code & application   med = code right, application interpretive
     spec = the number itself is a guess (shown by class letter where omitted).
   Attaches to window.PWYLL. */
window.PWYLL = window.PWYLL || {};
window.PWYLL.motifs = {
  intro: "Folklorists have their own Dewey decimal: the <strong>Thompson Motif-Index</strong> files every recurring story-atom under a letter-class and number (A mythological, D magic, F marvels, H tests, K deceptions, M ordaining the future, N chance &amp; fate, Q reward &amp; punishment, T love, Z formulas), while the <strong>ATU index</strong> classifies whole tale-types. <em>Pwyll Pendefig Dyfed</em> sits at the meeting of three folk-currents: the Welsh-distinctive year-exchange and chaste-sleep test, the international Calumniated Wife cluster (ATU 712 / the Constance-romance family), and the deeper Insular Otherworld-bride tradition. Below — 36 motifs across 10 Thompson classes, with cross-references to Gawain, Orfeo, and Culhwch where the same call-number lands. With four annotated tales the comparative layer can finally name what is distinctively Welsh, what is shared with the English Breton lays, and what is inherited from a deeper substrate.",
  taletypes: [
    { code: "The Year-Exchange of Kings", name: "Welsh-distinctive motif cluster — no clean ATU type", conf: "high",
      gloss: "One king takes the form and place of another for a year and a day, sleeps chastely beside the other king's queen, fights and kills the other king's enemy in single combat at the appointed ford, and returns. The cluster braids D1361.5 (magic transformation by another's form) with H1556 (fidelity test) and M223 (rash promise / binding contract). No clean ATU tale-type number, but Pwyll Movements I–II preserve the pattern in its most elaborate Insular literary form. The closest comparable scene in the corpus is Sir Gawain's beheading bargain — same one-blow contract architecture, exactly inverted: in Gawain the blow received must be returned; in Pwyll the blow given must not be repeated." },
    { code: "ATU 712 / S400 family", name: "The Calumniated Wife", conf: "high",
      gloss: "A queen is falsely accused — usually of killing her own child, or of unspeakable sexual crime, by attendants or in-laws who frame her. The husband refuses to set her aside; she takes a long public penance. The truth is recovered, often by a fortunate finding of the missing child years later. The international ATU 712 (\"The Cup\") family overlaps the S400 (persecuted heroine) cluster. Geneviève of Brabant, Crescentia, Chaucer's Custance (Constance), and many medieval romance saints are versions of the pattern. Pwyll's Movement V–VI is one of the cleanest medieval examples — and distinctively Welsh in that the false accusers are <em>never punished or even named</em> after the recognition." },
    { code: "Otherworld bride won by asking", name: "Insular F-cluster — the chase-without-catching", conf: "high",
      gloss: "A maiden from the Otherworld appears on a great pale-white horse riding past at a steady pace that no pursuer on foot or horseback can match. She can be approached only by being addressed politely, in a particular formula (in Pwyll's case, <em>for the love of the man you most love, wait for me</em>). The cluster braids F576 (Otherworldly speed, cannot be overtaken), F302 (fairy mistress as bride), and F232 (fairy goddess in human shape). Rhiannon descends from a Brittonic horse-goddess (<em>Rīgantonā</em>, \"Great Queen,\" Epona-cognate); the iconography is one of the deepest layers in the Insular Otherworld tradition. Pwyll's third-day asking is the moment that breaks the enchantment." },
  ],
  classOrder: ["A", "D", "F", "H", "K", "M", "N", "Q", "T", "Z"],
  classes: { A: "Mythological", D: "Magic", F: "Marvels &amp; the Otherworld", H: "Tests &amp; tasks", K: "Deceptions", M: "Ordaining the future", N: "Chance &amp; fate", Q: "Reward &amp; punishment", T: "Love &amp; marriage", Z: "Formulas &amp; symbols" },
  list: [
    // — A · Mythological —
    { cls: "A", code: "A186", name: "Demoted divinity walking as character", conf: "high", passages: [1, 2, 3, 4, 5, 6],
      gloss: "Two layers in Pwyll. (a) <strong>Rhiannon</strong> descends from the Brittonic horse-goddess <em>Rīgantonā</em> (\"Great Queen\"), Epona-cognate; her pale-white horse, her chase-without-catching, her name itself are the marks of an old divinity walking in narrative as a woman. (b) <strong>Arawn</strong> and <strong>Hafgan</strong>, two crowned kings of Annwn, are pre-Christian Otherworld powers walking as kings in their own kingdom. (Compare Gawain's A186 in Bertilak naming Morgan \"Morgne the goddess\"; Orfeo's A186 in the opening euhemerism of Pluto and Juno; Culhwch's A186 in Mabon son of Modron as Maponos.)" },
    { cls: "A", code: "A1654", name: "Origin of a game / first played", conf: "high", passages: [4],
      gloss: "<em>Guare broch yg got</em> — \"the badger-in-the-bag game\" — named here for the first time. The text states the etymology explicitly: <em>ac yna gyntaf y guarywyt broch yg got</em>, \"and that was the first time the badger-in-the-bag was played.\" Welsh folklorists have evidence the game (a bagged opponent beaten with feet and clubs) was actually played in medieval Welsh courts at festivals; the tale supplies its founding story. <strong>Compare Sir Orfeo's A1450</strong> (origin of the lay, in the closing colophon) and <strong>Sir Gawain's A1654</strong> (the green sash adopted as Round Table livery). Each Insular tale closes its frame by naming a real-world afterlife — a poem, a sash, a game. The pattern is one of the cleanest <em>shared rhetorical moves</em> across our four tales." },

    // — D · Magic —
    { cls: "D", code: "D1361.5", name: "Magic transformation by another's form / borrowed likeness", conf: "high", passages: [1, 2],
      gloss: "Arawn lays his <em>pryt</em> (form) and <em>ansawd</em> (appearance) on Pwyll for a year, so that no chamberlain or officer of Annwn knows the substitution. In Dyfed, Arawn-in-Pwyll's-form rules so well the men of the country afterwards beg Pwyll not to undo the policies. The form-loan is the central magical operation of the year-exchange — a refined K1810 (deception by disguise) where the deception is unwilled and the disguise is bound by an external agent. <strong>Cognate with Sir Orfeo's K1812</strong> (king in beggar's disguise) and <strong>Sir Gawain's K1810</strong> (Bertilak as the Green Knight) — but the only one of the three where the disguise is a genuine magical transformation rather than a put-on costume." },
    { cls: "D", code: "D1652", name: "The unfillable bag / magic insufficient vessel", conf: "high", passages: [4],
      gloss: "Rhiannon's small bag, into which any quantity of food can be put without it ever becoming any fuller. The opposite of the wonder-tale's standard D1652 (\"Inexhaustible food vessel\") — same code-family, inverted purpose. The food disappears from the court as it goes in; the bag stays empty until the binding condition is met (a nobleman with land and earth and wealth stepping into it with both feet). The Welsh narrative-mathematics at its most precise: the more you put in, the more nothing happens. Pure magical economics in service of the badger-in-the-bag trap." },
    { cls: "D", code: "D900", name: "Magic place / fae-frequented hunting-ground", conf: "med", passages: [1, 3],
      gloss: "Two such places in Pwyll: <strong>Glyn Cuch</strong>, the named hunting-glade where the breach with Arawn occurs and where (in Movement II) the form-restoration happens; and <strong>Gorsedd Arberth</strong>, the named mound whose custom is one of two — wounds or a marvel — and where Rhiannon first appears. Welsh tradition has distinct named threshold-sites (Annwn-touched places where the membrane is thin); both Glyn Cuch and Gorsedd Arberth are real Pembrokeshire/Carmarthenshire features still mapped today. (Compare Sir Orfeo's D1810.8 magic dream-vision under the ympe-tree; Gawain's D965 holly bough at the chapel-barrow.)" },

    // — F · Marvels &amp; the Otherworld —
    { cls: "F", code: "F167", name: "The shining hounds of the Otherworld", conf: "high", passages: [1],
      gloss: "The <em>Cŵn Annwn</em> — Arawn's hunting-pack: shining brilliant white with bright red ears, of a hue Pwyll had never seen on a hunting-dog. The founding image of the Insular spectral hound; ancestor of every white-with-red dog in British folk-tradition from medieval ghost-pack legends to Conan Doyle's <em>Hound of the Baskervilles</em>. The breach Pwyll commits at Glyn Cuch — driving them off the stag — is the act that opens the whole tale. (For the cross-tale layer, see Z65 below — the Cŵn Annwn anchor the Welsh white-Otherworld palette that <em>contrasts</em> with Sir Gawain's pervasive green.)" },
    { cls: "F", code: "F252", name: "The Otherworld and its court", conf: "high", passages: [1, 2],
      gloss: "Annwn — the Welsh Otherworld — is the most fully imagined Otherworld in our corpus. Pwyll walks into it through no marked door (only across a threshold Arawn leads him to); the court has sleeping-chambers, halls, rooms, fairest furnishings of any building, gold-shot silk court-robes, a queen <em>fairest woman he had ever seen</em>, a fully functioning protocol and household. Distinctively Welsh: no precious-stone walls, no ever-light, no levitating stones. The Otherworld here is not a different reality but a finer one, on the same architectural scale as a Welsh king's hall. (Compare Sir Orfeo's F771.6 castle of crystal with ever-light F165.6: same role-slot, opposite aesthetic vocabulary. The cross-tale Z65 row makes this contrast a real comparative observation.)" },
    { cls: "F", code: "F215", name: "Two contending Otherworld kings / divided realm", conf: "high", passages: [1, 2],
      gloss: "Annwn holds two crowned kings — Arawn and Hafgan (whose name means roughly \"Summer-bright\") — whose realms march together and who are perpetually at war. Hafgan's nobles testify after his death that there is no king of all Annwn but Arawn now; the two kingdoms have always been incomplete. The Welsh Otherworld is internally divided, doubled, perpetually contested. (No exact parallel in the other three tales: Sir Orfeo's Fairy King is singular; Sir Gawain's Bertilak rules Hautdesert alone; Culhwch's Annwn is invoked through Gwyn ap Nudd alone. Distinctively Welsh.)" },
    { cls: "F", code: "F320", name: "Fairies abduct mortals to fairyland", conf: "high", passages: [5, 6],
      gloss: "The unseen power that takes Pryderi from his cradle at midnight, and that takes Teirnon's foals every May Eve. The Welsh prose names no agent — only the action. <strong>Cognate with Sir Orfeo's F255.2</strong> (\"Fairies take at noon\"): same architecture, opposite end of the day. Welsh tradition's threshold-hour for the taking is midnight; the Pearl-Poet's century's threshold-hour is noon. Both are liminal-light times when the membrane is thinnest. Adding Pwyll to the corpus turns this from a two-tale observation into a structural Insular pattern with a chronometric component." },
    { cls: "F", code: "F302.1.2", name: "Fairy mistress comes to live with mortal", conf: "high", passages: [3, 4],
      gloss: "Rhiannon, the Brittonic horse-goddess walking as Hyfaidd Hen's daughter, comes <em>specifically to find Pwyll</em>, in love with him before they meet, and arranges her own deliverance from Gwawl so she can marry him. The Otherworld bride takes initiative in every direction — she is the donor, the strategist, the bride, the architect of the wedding. Most distinctive Insular bride-quest variant: not Olwen-style (won by tasks set by the giant-father), not Heurodis-style (recovered after abduction), but <em>asked correctly and chose him</em>." },
    { cls: "F", code: "F232", name: "Fairy goddess / divinity-figure in fairy form", conf: "med", passages: [3, 4, 5, 6],
      gloss: "<em>Rīgantonā</em> — \"Great Queen\" — the proto-Celtic etymology behind Rhiannon's name marks her as a descended divinity. The Welsh Triads, the Second and Third Branches, and continental Epona iconography all point at the horse-goddess substrate. The tale lets her function as a Welsh princess, but the chase-without-catching, the seven-year penance as the horse at the gate, and the naming-by-mother's-word are all marks of an older mythological figure under the courtly surface. (Compare A186 above for the broader euhemerism pattern in the corpus.)" },
    { cls: "F", code: "F576", name: "Otherworldly speed / supernatural pursuit-eluding", conf: "high", passages: [3],
      gloss: "Rhiannon's pale-white horse, riding past the Gorsedd Arberth three days in succession, at a pace no pursuer on foot or on the fastest horse in the realm can match — and the faster the pursuer, the further it gets. The marvel is not in the horse's speed but in the <em>relationship</em>: pursuit itself fails. The enchantment is broken only by being asked rather than chased. <strong>A new motif Pwyll brings into the corpus</strong> — none of the three other annotated tales carries this exact form of magical pursuit-eluding. Distinctively Welsh." },
    { cls: "F", code: "F156", name: "Threshold of the Otherworld / fae-touched boundary", conf: "med", passages: [1, 2],
      gloss: "Glyn Cuch — the hunting-glade where Pwyll loses his companions, sees the strange pack, and meets Arawn. Less marked than Sir Orfeo's rock-cleft three miles deep or Sir Gawain's Green Chapel as a hollow barrow, but the structural role is the same: the place where the king crosses, alone, into the parallel realm. The tale uses it as the form-restoration place too: at the year's end, Pwyll meets Arawn at Glyn Cuch and they exchange forms back. The threshold is implicit in the geography, not architecturally marked." },
    { cls: "F", code: "F151.1", name: "Perilous path / journey to the Otherworld", conf: "med", passages: [1, 2],
      gloss: "Pwyll's solo ride into Annwn behind Arawn's leading-figure (briefly noted: <em>he led him until he saw the court</em>) is the only Welsh entry-procession in the corpus. Less elaborated than Orfeo's three-mile cleft and Gawain's North-Welsh-and-Wirral winter ride, but conceptually the same act: the king walks alone into a Otherworld he cannot return from without permission. The Welsh narrator gives the threshold its dignity by understating it." },
    { cls: "F", code: "F302.6", name: "Recovery of bride from Otherworld bridegroom", conf: "med", passages: [4],
      gloss: "An interesting inverted variant. Rhiannon is being given against her will to Gwawl son of Clud — \"Brilliance,\" a euhemerised Brythonic light-deity, opposite-number to Pwyll's Annwn-shadow — and the badger-in-the-bag is the mechanism that releases her. The Otherworld <em>bridegroom</em> (not the Otherworld <em>captor</em>) is bound by his own rash promise and his ransom-pledge. (Compare Orfeo's binding-rebuke of the Fairy King in Movement V — both poems use the antagonist's own word to release the bride.)" },

    // — H · Tests &amp; tasks —
    { cls: "H", code: "H1556", name: "Tests of fidelity — the chaste sleep variant", conf: "high", passages: [2],
      gloss: "Pwyll's chaste year in Annwn beside Arawn's queen is the most refined H1556 fidelity test in our corpus. The fairest woman in the Otherworld is placed in his bed with the full form of her own husband upon him; Arawn never warns him that he is being watched; no human eye observes the result. Every night Pwyll turns his face to the bed-edge and his back to her. The test is <em>passed without being declared as a test</em> — the Welsh prose simply reports the act and (at the homecoming) the queen's bewildered silence triggers the recognition. <strong>Compare Sir Gawain's H1556</strong> (the exchange-of-winnings — the test is explicit, the hero half-fails) and <strong>Sir Orfeo's H1556</strong> (the steward's seven-year loyalty — the test is the absent king's idea). Three different vectors on the same call-number: Welsh chaste-sleep, English chivalric exchange, English homecoming-test." },
    { cls: "H", code: "H1242", name: "Hero brings back lost person from the Otherworld", conf: "high", passages: [6],
      gloss: "Teirnon, not Pwyll, brings Pryderi back from where the unseen power had taken him. <strong>Distinctively Pwyll: the hero of the recovery is not the husband</strong> — Welsh tradition's only mid-story protagonist transfer in our corpus. (Compare Sir Orfeo's H1242 — the husband himself rescues the queen from Faerie through the rock-cleft. Pwyll inverts the agent.)" },
    { cls: "H", code: "H310", name: "Suitor tests / asking correctly to win the bride", conf: "high", passages: [3],
      gloss: "Rhiannon waits three days for Pwyll to call out the right form — <em>for the love of the man you most love, wait for me</em> — and her first reply names what was wanted: \"it had been better for the horse if you had asked me long ago.\" The bride is won by a specific speech-act, not by a feat. Welsh fae-bride suitor-test: the magic is broken by request. Compare Culhwch's H335 / G530.2 (Olwen won by the impossible tasks her father sets) — entirely different mode of suitor-test." },

    // — K · Deceptions —
    { cls: "K", code: "K1810", name: "Deception by disguise", conf: "high", passages: [1, 2, 4],
      gloss: "Three layered disguises in Pwyll. (a) Arawn lays his form on Pwyll for the year of impersonation; (b) Pwyll-as-Arawn impersonates Arawn through every social interaction in the Otherworld court; (c) Pwyll, in beggar's rags and oversized foot-coverings, walks into Gwawl's feast for the badger-in-the-bag trap. <strong>Compare Sir Orfeo's K1812</strong> (king as harper at the Fairy King's gate; later as beggar at Winchester) and <strong>Sir Gawain's K1810</strong> (Bertilak as the Green Knight, Morgan as the ancient lady). All three poems deploy disguise as the central deception-mechanism — but with different moral colourings: Welsh disguise is contractual, Orfeo's is rescue-enabling, Gawain's is testing." },
    { cls: "K", code: "K1812", name: "King in disguise", conf: "high", passages: [2, 4],
      gloss: "Two specific instances. Pwyll-as-Arawn rules Annwn for a year as if he were Arawn (the disguise is total; no chamberlain suspects). Pwyll in beggar's rags walks into Gwawl's wedding feast asking for nothing but a small bag's fill of food. Both deployments share the same Welsh principle: the king is recognised by what he <em>does</em>, not by what he wears. (Compare Sir Orfeo's K1812 in the steward-test sequence in Movement VI — the same role-slot, the same disguise as test-vehicle.)" },
    { cls: "K", code: "K1837", name: "Disguise as a beggar", conf: "high", passages: [4],
      gloss: "Pwyll in heavy old rags and oversized foot-coverings, with the magic bag hidden, enters Gwawl's feast at \"the start of the after-meal drinking\" — the moment chosen for maximum host-expansiveness and minimum suspicion. <strong>Sir Orfeo will reuse this exact disguise-and-timing</strong> four centuries later, walking into the steward's feast in borrowed beggar's clothes with his harp on his back. The fairy-tale pacing is precise enough in both texts to be a shared narrative grammar." },
    { cls: "K", code: "K500", name: "Death evaded by trick / legal substitution", conf: "high", passages: [4],
      gloss: "Gwawl, bagged and at Pwyll's mercy, pleads — <em>it is no proper death to be killed in a bag</em> — and Hyfaidd Hen and Rhiannon agree. Gwawl is released by named sureties on his oath never to seek vengeance. The Welsh court's preference for <em>legal architecture over execution</em>, in its purest form. Structurally the inverse of Hafgan's clean death-at-the-ford in Movement II — Pwyll-as-Arawn killed; Pwyll-as-himself ransomed. (Compare Sir Gawain's K500 in the green-girdle scene — the hero himself evades his own death by a similar trick, except the trick has a moral cost.)" },
    { cls: "K", code: "K2110", name: "Slander / false witness against the innocent", conf: "high", passages: [5],
      gloss: "The six women's coordinated false witness against Rhiannon — <em>six of us against her alone shall not fail</em>. Pwyll's deepest K-class motif and the engine of Movement V. The lie holds against Rhiannon's protests, against Pwyll's refusal to set her aside, and rules the kingdom for seven years before Teirnon's recognition unmakes it. The international ATU 712 (Calumniated Wife) cluster cited above turns on this single function." },
    { cls: "K", code: "K2114", name: "Mother accused of killing and eating her own child", conf: "high", passages: [5],
      gloss: "The specific form the lie takes: kill some of the bitch's whelps in the chamber, smear Rhiannon's hands and face with the blood, scatter the bones, and accuse her of having destroyed her own son. The bone-and-blood evidence is fabricated; the witnesses are coordinated; the accusation is unanswerable. Pwyll's only K2114 (and our corpus's only). The motif is medieval-international (cf. Geneviève of Brabant, Crescentia), but the Welsh version is distinctive in (a) using a litter of puppies as forensic prop and (b) the U-absent that follows — the false accusers are <em>never punished</em> after the recognition." },

    // — M · Ordaining the future —
    { cls: "M", code: "M223", name: "The rash promise", conf: "high", passages: [1, 4, 5],
      gloss: "Pwyll runs on rash promises more densely than any other tale in our corpus — at least three. (a) Arawn proposes the year-exchange; Pwyll grants it; (b) Gwawl son of Clud asks Pwyll for a request before naming it, exactly parallel to Arthur granting Bertilak's terms unread in Sir Gawain Fitt I; (c) Pwyll, prompted by the nobles at Preseli, promises to take a second wife within a year if Rhiannon proves barren. <strong>The Pendragon crosswalk's M223 row now has four columns, all present</strong>. Welsh, English-romance, English-Breton-lay: every Insular wonder-tale here runs on this single Welsh-distilled architecture." },
    { cls: "M", code: "M201", name: "Pledge given — and held on honour", conf: "high", passages: [1, 2, 4, 5],
      gloss: "Multiple sealed pledges in Pwyll. (a) The year-exchange covenant at Glyn Cuch; (b) the one-blow-only rule against Hafgan, held even when Hafgan begs the second; (c) Pwyll's grant to Gwawl, held externally while Rhiannon plots to redirect it; (d) Pwyll's promise to the nobles to take counsel within the year; (e) the Gwawl release-pledge. Welsh culture's binding force of the spoken word, repeatedly demonstrated. (Compare Sir Gawain's M201 in the troth-given-on-the-axe-haft and the exchange-of-winnings covenants.)" },
    { cls: "M", code: "M242", name: "Bargain at a fixed future date — blwydyn y heno", conf: "high", passages: [1, 2, 3, 4, 5],
      gloss: "<em>Blwydyn y heno</em> — \"a year from tonight\" — the Welsh formula appears in Pwyll <strong>at least four times</strong>: the year-exchange with Arawn, the year-and-night appointment with Rhiannon on the Gorsedd, the year-from-tonight redirection of Gwawl's claim, the year given to the nobles at Preseli to resolve the heir-question. The Welsh narrative-arithmetic of <em>year-and-a-day appointments</em> as the structural beats of plot. (Compare Sir Gawain's M242 — the Green Knight's year-and-a-day return — which is the single load-bearing instance of the same architecture in Middle English.)" },

    // — N · Chance &amp; fate —
    { cls: "N", code: "N777", name: "Adventure follows from the hunt", conf: "high", passages: [1, 6],
      gloss: "Two such hunting-encounters in Pwyll, framing the tale. (a) The hunt at Glyn Cuch in Movement I leads to the meeting with Arawn and the year-exchange; (b) the May Eve vigil at Teirnon's stable in Movement VI is a kind of mirror-hunt (Teirnon as predator waiting for the unseen taker of his foals) that leads to the recovery of Pryderi. <strong>Compare Sir Gawain's N777</strong> (the three hunts and three temptations) and <strong>Sir Orfeo's N777</strong> (the sixty hawking ladies whose path leads through the rock-cleft). All three English-Insular tales use the hunt as a plot-engine; Pwyll's Welsh version brackets the whole tale with it." },
    { cls: "N", code: "N886", name: "Recognition by family resemblance", conf: "high", passages: [6],
      gloss: "Teirnon, having served Pwyll years ago, looks at the seven-year-old Gwri and sees the form of Pwyll Penn Annwn — and that is the recognition that brings the boy home. <strong>The cleanest single recognition-mechanism in the four-tale corpus</strong>. Sir Orfeo's steward recognises the harp before the man (N886-by-token); Sir Gawain's Bertilak reveals himself by his own confession; Culhwch's Goreu is revealed by his mother. Pwyll's recognition is purely visual and purely familial: <em>I knew his father, and the boy looks like him</em>." },
    { cls: "N", code: "N881", name: "Foundling raised by host until recognition", conf: "high", passages: [6],
      gloss: "The swaddled boy in fine silk at Teirnon's door, raised in the foster-family with no knowledge of his origin, returned at seven on the strength of facial resemblance — the international foundling-cluster (N810–N881) in its most economical Welsh form. The foster-mother who raises him with full love and gives him back with the longest grief — <em>there is no one in the world with greater grief for him in her wake</em> — is the heart of the motif." },

    // — Q · Reward &amp; punishment —
    { cls: "Q", code: "Q40", name: "Kindness rewarded / reward refused", conf: "high", passages: [6],
      gloss: "Teirnon, offered by Pwyll the fairest jewels and the best horses and the most beloved hounds for the return of Pryderi, takes none. <em>And he wanted nothing.</em> The Welsh narrator names the reward-economy in its purest form: the act of restoration is its own pay. (Compare Sir Orfeo's Q40 in the Fairy King's gold-hemmed girdle offered to Gawain — and refused — and offered to Orfeo and accepted as a token of fault. The same code, three different moral positions.)" },
    { cls: "Q", code: "Q450", name: "Absence of punishment — three layers", conf: "high", passages: [2, 4, 5, 6],
      gloss: "<strong>The deepest Q-absent in our corpus.</strong> Hafgan dies by contractual single combat (not punishment, but the terms of the bargain set by Arawn). Gwawl is ransomed under named sureties (not killed, not even imprisoned, sent home wounded). The <strong>six women who lied</strong> against Rhiannon are <em>never named, never charged, never expelled, never even denounced</em> after the recognition. The lie passes without judgment once Pryderi is restored. (Compare Sir Gawain's Q450-absent for the Green Knight, who is unmasked but not condemned; Sir Orfeo's Q450-absent for the Fairy King, who is bound but not even unmasked; and Culhwch's Q450-PRESENT for Ysbaddaden, beheaded by Goreu. Pwyll takes the Welsh-and-English U-absent pattern to its furthest point.)" },

    // — T · Love &amp; marriage —
    { cls: "T", code: "T338", name: "Chaste man tempted by woman, refusing — the chaste sleep", conf: "high", passages: [2],
      gloss: "Pwyll in Annwn beside Arawn's queen for a year, with her husband's full form upon him, the year-long licence and no observer. He turns away every night and says not a word. The Welsh prose registers no internal monologue, no struggle, no exposition — the act is reported as the natural consequence of <em>cedymdeithas</em> (companionship). <strong>Compare Sir Gawain's T331/T338</strong> in the three-day temptation by Lady Bertilak: there the test is explicit, the temptation is named, the hero half-fails. Two opposite vectors on the same family of codes — Welsh tradition's chaste-sleep is the test the hero doesn't know is being given; Gawain's is the test the hero knows about but is bound by exchange-of-winnings not to refuse." },
    { cls: "T", code: "T11.2", name: "Love from sight / love preceding the meeting", conf: "high", passages: [3],
      gloss: "Rhiannon to Pwyll on the Gorsedd: <em>I have wanted no man, and that for love of you</em>. She has loved him before he has seen her face; she has ridden to the Gorsedd specifically to find him. <strong>Compare Culhwch's T11.1</strong> (Culhwch loves Olwen at the bare mention of her name, having never seen her). Both Welsh tales open the marriage-quest with love preceding the meeting; both English tales begin with the marriage already in place or refuse the marriage altogether. Distinctively Welsh." },
    { cls: "T", code: "T211", name: "Faithful spouse against false accusation", conf: "high", passages: [5, 6],
      gloss: "Pwyll's refusal to set Rhiannon aside when the six women's lie convicts her of child-murder — <em>children I know there to be to her, and I shall not separate from her</em> — is the cleanest T211 in our corpus. The marriage is held against a fully-formed legal charge. (None of Culhwch, Gawain, or Orfeo carries this exact form: Orfeo's loyalty is to a queen taken by the Otherworld, against which there is no plausible alternative; Pwyll's loyalty is to a queen the court itself has condemned.)" },

    // — Z · Formulas &amp; symbols —
    { cls: "Z", code: "Z71.1", name: "Formulistic number: three", conf: "high", passages: [1, 3, 4, 6],
      gloss: "Pwyll runs on threes at every layer. Three days of Rhiannon riding past the Gorsedd. Three failed pursuits. Three rash-promise instances. Three layered disguises (Arawn-form, Pwyll-in-Arawn-form, Pwyll-in-beggar-form). The recognition-feast at Arberth seats Pwyll, Rhiannon, and Teirnon in the central triangle. (Compare Sir Gawain's Z71.1 — three blows, three hunts, three temptations, three exchanges — pervasive at every level. Pwyll uses threes more sparingly than Gawain but more structurally than Orfeo.)" },
    { cls: "Z", code: "Z65", name: "Colour symbolism — white-and-red as the Otherworld", conf: "high", passages: [1, 3],
      gloss: "<strong>The most visible cross-tale colour-pattern in our corpus.</strong> Pwyll establishes the Welsh white-and-red palette as the Otherworld's signature: the Cŵn Annwn shining brilliant white with red ears (Movement I); Rhiannon on the great pale-white horse with gold-shot silk shining upon her (Movement III); the Fairy King's snow-white riders and snow-white damsels with robes as white as milk in Sir Orfeo four centuries later, descending directly from this Welsh substrate. <strong>Contrast Sir Gawain's pervasive Z65 green</strong> — the Pearl-Poet's tradition runs on the opposite palette, the green of vegetation and growth and the unworldly hue. Two Insular Otherworld traditions, two opposite chromatic conventions. Adding Pwyll lets the comparative table name this with confidence." },
    { cls: "Z", code: "Z71.6", name: "Year and a day / a year from tonight", conf: "high", passages: [1, 2, 3, 4, 5],
      gloss: "<em>Blwydyn y heno</em> — the Welsh formula for an appointed-meeting-in-a-year — is the structural beat of plot in Pwyll's First Branch (see M242 above for the count). Where Sir Gawain has <em>one</em> year-and-a-day (the Green Knight's return), Pwyll has at least four. Welsh narrative-arithmetic favours the year-and-a-day measure as the pulse against which kingship is conducted and bargains are sealed. (For the cross-tale layer, this is the clean comparative observation: the year-and-a-day is in all four tales, but Pwyll runs on it most densely.)" },
  ],
};
