/* Pwyll Pendefig Dyfed — a faithful middle-grade retelling (ages ~8-12),
   the whole First Branch across paged spreads. Plot, names, the year-
   exchange with Arawn, the chase-without-catching, the badger-in-the-bag,
   and the lost-and-found son kept faithful. The two morally delicate
   scenes — the women's lie against Rhiannon and Rhiannon's penance as
   the horse at the gate — handled with folktale tact: described but not
   shown graphically. Each spread carries an `illus` brief — an art note
   for the illustration pass; it is not shown. Attaches to window.PWYLL. */
window.PWYLL = window.PWYLL || {};
window.PWYLL.book = {
  meta: {
    kicker: "A Tale from the Mabinogion",
    note: "A faithful retelling for readers 8 and up — the First Branch of the Mabinogi, the foundational Welsh prose tale, page by page. Illustrations to follow.",
  },
  spreads: [
    { title: "Pwyll Pendefig Dyfed",
      sub: "The First Branch of the Mabinogi — a Welsh tale of a prince who traded places with the King of Annwn, won a queen on a horse no rider could catch, and lost and found a son with the help of the best man in the world",
      text: "A story of a hunt that ended badly, a year in another king's body, a wedding feast that turned upside down, six women's lie, and the cut of a sword that stopped two robberies at once.",
      illus: "Cover: a tall young Welsh prince (Pwyll, dark hair, gold torc at his neck, russet hunting cloak over forest-green wool) on horseback in the foreground at the edge of a wooded valley, looking outward toward a distant Welsh hillside; behind him, softer painterly suggestions of a pale-white horse with a gold-clad rider in the distance and tall white hounds with red ears at the edge of the wood; warm gouache-and-watercolour in the Howard Pyle / Edmund Dulac tradition; earthy greens and ambers with quiet gold accents; Welsh medieval atmosphere c.1100." },

    { title: "Pwyll, Prince of Dyfed",
      text: "In the old days of Wales, before kings of England ruled the land, there was a prince named Pwyll, lord of Dyfed in the south. His chief court was at Arberth, and his country was the seven cantref — the seven hundred dwellings — of his realm. He was tall, brave, generous, and well-loved. His story begins one bright morning, when he set out from Arberth to hunt at Glyn Cuch.",
      illus: "Pwyll Prince of Dyfed (tall young Welshman, dark hair, gold torc at neck, russet hunting cloak over forest-green wool tunic, leather belt with hunting horn at his hip) standing in the doorway of his stone-and-timber Welsh court at Arberth at dawn, hounds at his feet, attendants nearby. Soft warm Welsh morning light on rolling green hills. Earthy palette." },

    { title: "The Hunt at Glyn Cuch",
      text: "Glyn Cuch was a wide wooded valley on the border of Dyfed, where the stags grew bold. Pwyll rode out at dawn with his companions and his hounds. They sounded the horn, and the hunt began. The dogs caught the scent of a great stag — and as they pursued it, Pwyll rode so far that he lost sight of his friends. Alone in the wood, he listened. He could hear his own pack baying — and another pack baying too, in the same valley. He had never heard those dogs before.",
      illus: "Welsh forest interior in a wide wooded valley at dawn — Pwyll on his horse in mid-canter, hunting horn in hand, alone among the trees. His own brown Welsh hounds visible ahead. In the distance through the trunks, the suggestion of OTHER hounds — pale luminous shapes only suggested — and a fleeing stag. Dappled light through trees, earthy greens and ambers, sense of magic in the wood." },

    { title: "The Hounds of Annwn",
      text: "Pwyll rode toward the sound. In a glade ahead he saw the stag at last — and the strangers pulling it down. The dogs were tall, with shining brilliant white coats and bright red ears. They were the most beautiful hounds in the world, and they were not from this world. They were the <em>Cŵn Annwn</em>, the hounds of the Otherworld. But Pwyll did not know that yet. He drove them off, and set his own dogs on the stag — a great breach of courtesy, he would learn, though he never noticed.",
      illus: "A bright forest glade — Pwyll on horseback, having ridden up. In the centre, a great fallen stag. Beside it, the Cŵn Annwn — three or four tall, noble, supernatural hunting-hounds with SHINING BRILLIANT WHITE coats and BRIGHT RED ears, looking up at Pwyll calmly (not snarling). Pwyll's own brown-and-tan Welsh hounds running in. Pwyll waving his hunting horn at the white hounds in dismissal. The white hounds glow with soft Otherworldly light. Earthy palette with white-and-red as the visual accent." },

    { title: "The Grey Rider",
      text: "While Pwyll fed his own dogs on the stag, he heard the soft thunder of a horse. A tall lord rode up, dressed in grey-brown wool, mounted on a pale-grey horse, with a hunting horn around his neck. He was angry. <em>“I know who you are,”</em> the rider said, <em>“and I will give you no greeting. You drove off my pack to feed your own dogs on my kill. That is a discourtesy worth a hundred stags' worth of dishonour.”</em> Pwyll felt the shame go through him. <em>“Tell me how to make it right,”</em> he said.",
      illus: "The same forest glade — Arawn, lord of Annwn, on a pale-grey horse, in grey-brown wool hunting clothes with a curling hunting horn slung around his neck. He has a mature, stately, slightly stern face. He is speaking down to Pwyll, who has now dismounted and stands beside his own horse, looking up. The white-and-red hounds visible at the edge of the scene, withdrawn quietly. Dignified earthy palette." },

    { title: "The Year-Exchange",
      text: "<em>“I am Arawn, King of Annwn,”</em> the rider said, <em>“and I have an enemy named Hafgan. Take my form for one year, rule my kingdom in my place, and slay Hafgan with a single stroke at the ford. I will rule yours in your form, and no one will know. At the year's end we shall meet here again, restore each other's shapes, and I shall call you my friend.”</em> Pwyll thought of his honour, and of his courtesy-debt. He held out his hand. <em>“I shall go,”</em> he said.",
      illus: "The same glade — Arawn and Pwyll now facing each other, both still on horseback. Arawn is extending a hand toward Pwyll; a magical warm-gold glimmer is beginning to settle on Pwyll, suggesting the form-loan taking effect. Soft watercolour with subtle gold magic-aura, the forest behind them. Earthy and dignified, with a quiet sense of wonder." },

    { title: "In the Court of Annwn",
      text: "Arawn led Pwyll to the boundary of Annwn, and there gave him his form and his name. Pwyll walked alone into Arawn's court. No chamberlain knew him; everyone treated him as if he were Arawn. He sat at the feast that night between the queen — the loveliest woman he had ever seen — and a noble lord. The food was the finest. The conversation with the queen was the warmest. But Pwyll knew the bargain. He had a year, and one rule to keep.",
      illus: "A magnificent Welsh medieval great hall at evening, lit by torches and a great hearth-fire — high carved-wood roof, painted shields on the walls, long oak tables laden with food. Pwyll (now bearing Arawn's mature lordly face, but the same gold torc at his neck) at the head of the hall, with the Queen of Annwn (silver-blonde hair, in shimmering gold-shot silk court robe, calm regal kind face) at his right hand and a richly-dressed earl at his left. The household around them at the feast. Warm gouache, dignified, golden." },

    { title: "The Chaste Bed",
      text: "When the feast was done, the time came for sleep. The queen went with him to the bedchamber. The moment they were in the bed, Pwyll turned his face to the wall and his back to her, and he would say nothing more until morning. He did the same every night for a year. In the day they talked happily, as Arawn and his queen always did. But night after night Pwyll kept his side of the bargain — and never told the queen why.",
      illus: "A quiet bedchamber by candlelight — a richly furnished medieval chamber with tapestries on the walls, a deep carved bed with embroidered coverlets. Pwyll (in Arawn's form) lying with his back turned firmly to the queen, face toward the wall, eyes closed peacefully in sleep. The Queen of Annwn behind him in the same bed, also peacefully asleep, her own face turned to the other side. NO contact between them. Tender, respectful, soft warm candlelight; quiet, dignified composition." },

    { title: "The Duel at the Ford",
      text: "The year passed. At the appointed time, Pwyll rode to the ford with the nobles of Annwn at his back. On the other bank waited Hafgan, the other king. A herald rose between them: <em>“Let no man come between them.”</em> The two kings rode at each other in the middle of the water. With one stroke, Pwyll struck Hafgan's shield in two and brought him down. <em>“Finish me,”</em> Hafgan begged. <em>“No,”</em> said Pwyll. <em>“Find another. I shall not strike you twice.”</em> For Arawn had told him: one blow only — never a second.",
      illus: "A river-ford scene at high noon — clear shallow water between green Welsh banks, two great stately knights on horseback meeting in the middle of the ford. Pwyll (in Arawn's form, in Welsh medieval mail and surcoat) holding a Welsh longsword raised mid-swing, his shield braced. Hafgan (tall king in summer-bright clothes — golden-yellow tunic, lighter mane of hair, with a glowing white-and-gold shield) caught mid-fall sideways from his horse, his own sword falling away. NO blood, NO body horror — the focus is on the clean dramatic moment of the single blow. Lines of watching nobles on both river-banks. Sunlit, dramatic, but clean and folkloric." },

    { title: "The Mirror Scene",
      text: "Pwyll rode back to Glyn Cuch, and there Arawn was waiting. They restored each other's forms with a touch and a word, and parted as the closest of friends. That night Arawn came home to his own queen — and she could not understand why, after a year of silent nights, he was suddenly his old loving self again. So he told her the whole story. <em>“You have got a true companion,”</em> she said. <em>“Strong and faithful.”</em> From then on Pwyll was called Pwyll <em>Penn Annwfn</em> — Pwyll Head of Annwn.",
      illus: "A warm interior chamber — Arawn (now restored to his own true face) seated by his hearth-fire with his queen at his side, both looking at each other with quiet new understanding. Warm firelight, intimate domestic setting. In the background, perhaps a tapestry detail suggesting two horsemen meeting at a forest ford. Domestic and warm; earthy palette." },

    { title: "Pwyll Head of Annwn",
      text: "Pwyll returned to his own court at Arberth. His people praised the year of rule they had had — for Arawn had been a fine king in his form. Pwyll thanked them, kept Arawn's policies, and from then on Arawn and Pwyll sent each other gifts every year: horses, hawks, hounds, and rich treasures. Because Pwyll had ruled the two kingdoms of Annwn so well, his old name <em>Prince of Dyfed</em> began to fade. Everyone called him <em>Penn Annwfn</em> — Head of Annwn — instead.",
      illus: "Pwyll (in his own true form again — dark-haired, gold torc, russet cloak) standing in his court at Arberth, receiving a gift-train sent by Arawn — finely-bridled horses being led in, sleek hawks on perches carried by servants, sleek hounds at their heels, baskets of treasure. Smiling courtiers around. Warm sunlit Welsh hall, generous mood." },

    { title: "The Gorsedd Arberth",
      text: "Years later, Pwyll was at Arberth with his court for a feast. After the eating, he walked out to a low grass-covered mound above the court called the Gorsedd Arberth. There was an old custom about that mound: whatever nobleman sat upon it would either suffer a hurt — or see a marvel. <em>“I am not afraid of hurts among this company,”</em> Pwyll said. <em>“But a marvel I would gladly see.”</em> So he sat down on the Gorsedd and waited.",
      illus: "A real-shaped Welsh burial-mound — grass-covered, weathered, gently sloped, set just above a small stone-and-timber Welsh court (Arberth visible behind it). Pwyll seated cross-legged on the very top of the mound, his court of well-dressed Welsh nobles standing at its foot, looking up at him with quiet expectation. Soft Welsh hillside light, sense of magic about to happen. Earthy palette, atmospheric." },

    { title: "The Lady on the Pale-White Horse",
      text: "As they sat there, they saw a lady riding down the road below the mound. She was on a great pale-white horse, tall and broad and steady, and she wore a gown of gold-shot silk that shone in the sun. She was the most beautiful woman any of them had ever seen. Her horse moved at an easy walking pace. <em>“Does anyone know her?”</em> Pwyll asked. <em>“No one, my lord,”</em> his men said. So Pwyll sent a runner to ask her name. But however fast the runner ran, the lady was always further away than before.",
      illus: "A wide Welsh hillside landscape, the Gorsedd Arberth in the middle distance with Pwyll seated on top. On the road below winding past the mound: Rhiannon — a beautiful young Welsh woman with golden-blonde hair flowing loose, in a flowing gown of gold-shot silk that catches the light, mounted on a tall, broad, pale-white horse that is moving at a slow walking pace. A tiny runner in the foreground sprinting toward her but visibly losing distance. The light around Rhiannon is enchanted and soft, magic-suffused. Wide hillside view." },

    { title: "Three Days of Failed Chase",
      text: "Pwyll sent his fastest horseman, then his fastest horse — and no one could catch her. The next day she came again. And the day after. Each time the same: the runner ran his hardest, the horse galloped its best, but Rhiannon was always just out of reach. The fairy-magic of the pale-white horse was woven so that no pursuit could catch her at all. On the third day, Pwyll himself called out: <em>“Lady — for the love of the man you most love, wait for me.”</em> She halted at once.",
      illus: "A triptych-style composition in three vertical panels of one wide scene, like a fresco. First panel (left): day one, a man on foot running, can't catch Rhiannon on her pale-white horse ahead. Second panel (middle): day two, a knight on horseback at full gallop, can't catch her. Third panel (right, larger): day three, Pwyll himself on his great Welsh horse calling out — and Rhiannon, smiling slightly, turning her pale-white horse around to halt and wait for him. The third panel is the visual climax." },

    { title: "The Asking",
      text: "<em>“I would have waited gladly if you had only asked me,”</em> Rhiannon said. <em>“I am Rhiannon, daughter of Hyfaidd Hen. I have been promised against my will to a man named Gwawl. I have ridden out to find you, because I love you, and I do not love him.”</em> Pwyll was astonished. <em>“If I had all the women in the world to choose from,”</em> he said, <em>“I would choose you.”</em> They made a bargain: a year and a night from then, at her father's court, the wedding feast would be ready.",
      illus: "A close-up scene — Pwyll and Rhiannon meeting on the road. Pwyll has dismounted and is standing close beside her. Rhiannon still on her pale-white horse but leaning down to speak with him, smiling gently. Their faces in warm quiet conversation — joy, recognition, the love already in place. Welsh hillside background. Gentle warm afternoon light, intimate composition." },

    { title: "The Wedding Feast and the Stranger",
      text: "A year and a night later, Pwyll rode to Hyfaidd Hen's court with a hundred horsemen. The feast was set; Rhiannon sat at his side. After the eating, a tall stranger in royal silk walked into the hall. <em>“My lord,”</em> he said, <em>“I have come to ask a favour.”</em> <em>“Whatever you ask of me, as far as I can grant it, you shall have,”</em> Pwyll answered. The stranger smiled. <em>“The lady at your side, and the feast,”</em> he said. <em>“I came for them.”</em> It was Gwawl son of Clud — and Pwyll had given his word.",
      illus: "A great Welsh medieval feasting hall, lit by torches and the fire. Pwyll (in fine prince's clothes again — gold torc, dark hair, embroidered cloak) and Rhiannon (in a wedding gown of silver-grey trimmed in gold, her hair circled by a thin gold band) at the high table, surrounded by the wedding company. Gwawl son of Clud (tall noble, fine silk robe trimmed in light yellow-gold, auburn hair, polished proud face) standing at the foot of the hall, just having made his demand, slight smile. Pwyll's face frozen in shock. Rhiannon already calculating — calm-faced, but her eyes alert. Warm hall light." },

    { title: "Rhiannon's Plan",
      text: "Rhiannon was angry. <em>“You should not have given that answer,”</em> she whispered to Pwyll. <em>“But you have. Now listen.”</em> And she gave him a small bag — and a plan. <em>“A year from tonight, come to his feast in beggar's clothes. Hold this bag, ask for nothing but food enough to fill it, and the bag will never fill. When he comes to press the food down with his own feet, turn the bag over his head, tie the knot, and blow the horn.”</em> Pwyll listened. He took the bag. He waited a year.",
      illus: "A side-chamber of Hyfaidd Hen's court, away from the main hall — Pwyll and Rhiannon together, Rhiannon handing him a small dark wool bag with a long drawstring. She is leaned forward, intent, urgent; he is listening with care, eyes on the bag. In the background through an arched doorway, the feast going on out of focus. Warm intimate lamplight on the two of them. Quiet conspiratorial mood." },

    { title: "The Badger-in-the-Bag",
      text: "A year later, Pwyll came to Gwawl's feast in heavy old rags and oversized shoes, holding the bag. He asked for nothing but food enough to fill it. Gwawl laughed and gave him food — but the bag would not fill. Rhiannon spoke softly to Gwawl: <em>“Press it down with your own two feet.”</em> So Gwawl stepped into the bag. Pwyll pulled the strings up over his head, tied the knot, and blew the horn. A hundred horsemen came running. The wedding had a new ending.",
      illus: "Gwawl's feasting hall, similar in size to Hyfaidd's — Gwawl now half-inside a magic bag in the air, Pwyll (in beggar's rags, hood thrown back to reveal his face) closing the bag tight at the top with both hands, tying a knot. Rhiannon at the side watching with quiet triumph. A hundred Welsh horsemen visible pouring through the doors of the hall behind Pwyll. Comic-dramatic energy, warm hall firelight." },

    { title: "Pwyll and Rhiannon Together",
      text: "After Gwawl had given his word to seek no vengeance, he was let go. The hall was made ready for Pwyll and Rhiannon at last. They sat at the high table, ate and laughed and listened to the harps, and that night they were married. The next morning Pwyll filled the hands of every minstrel with gifts. <em>“I shall set out tomorrow for Dyfed,”</em> he told Rhiannon's father. <em>“And Rhiannon shall come with me, at once.”</em> And so they rode home to Arberth together.",
      illus: "Welsh medieval wedding feast — Pwyll (back in his prince clothes, gold torc, dark hair, warm smile) and Rhiannon (in a fine silver-grey wedding gown trimmed in gold, golden hair circled by a thin gold band) at the high table, dining together. Warm firelit hall, the household feasting around them with joy, harpers playing in a corner. Bright, celebratory, golden mood." },

    { title: "Two Prosperous Years",
      text: "Pwyll and Rhiannon ruled Dyfed together. The country was at peace; the harvests were good. Rhiannon gave a notable gift to every man and every woman of the realm — a brooch, a ring, a precious stone. So it went for one year, and a second. In the third year, the men of Dyfed came to Pwyll, worried. <em>“Lord, we love you. But we need an heir.”</em> Pwyll asked them for one more year. Before the year was out, Rhiannon told him she was with child.",
      illus: "A wide Welsh countryside scene — golden harvest fields under a clear sky, a small Welsh village in the middle distance, livestock grazing, peasants working in the fields with full barns visible. In a smaller inset or detail in one corner: Pwyll and Rhiannon at the gate of Arberth handing notable gifts (brooches, rings) to a small queue of grateful villagers. Warm prosperous earthy tones." },

    { title: "The Birth and the Loss",
      text: "Rhiannon gave Pwyll a son. He was born at Arberth, on a winter night. Six women were set in the chamber to watch the mother and the child. The women slept before midnight. Toward dawn they woke. The baby was gone from the cradle. Empty. No sign at all. They had heard nothing. The window stood open to the cold.",
      illus: "A Welsh medieval birthing chamber by deep night, lit by a single low oil-lamp and the dying fire. Rhiannon asleep in the great curtained bed under heavy coverlets, peaceful. Six women slumped around the room asleep — on stools, leaning against the wall, on a small bench. In the centre of the room: an empty wooden cradle, its coverlet half-thrown back. The high window stands open to the night beyond (dark sky and stars visible). NO menacing figure shown — just emptiness and cold air drifting in. Sense of dread but quiet, not horror-show. Atmospheric, sad." },

    { title: "The Lie",
      text: "The six women were terrified. <em>“If the king finds out, he will burn us,”</em> they whispered. One of them looked at the hearth, where a hound had whelped a few days before. <em>“Let us kill some of the whelps, smear Rhiannon's hands with the blood, scatter the bones, and accuse her,”</em> she said. <em>“Our word, six against one, will hold.”</em> And that is what they did. When Rhiannon woke and asked for her child, they told her she herself had killed him. She could not move them.",
      illus: "Welsh medieval chamber, the same. Rhiannon — just waking from sleep — sitting upright in the bed, hand half-raised in shocked disbelief, looking at her own hands and face which are marked only with the lightest of dye-like reddish stains (handled with tact, NOT graphic — looks more like rust-coloured powder than blood). The six women standing in a tight half-circle in front of the bed, hard expressions, refusing to meet her eye. The empty cradle visible. Atmosphere of betrayal and helplessness. NO actual gore. Quiet, painful, dignified." },

    { title: "Rhiannon at the Gate",
      text: "Pwyll's nobles came to him in fury. <em>“Set her aside,”</em> they said, <em>“and find a new wife.”</em> But Pwyll refused. <em>“If she has done wrong, let her take her penance,”</em> he said, <em>“but she is my wife.”</em> And so Rhiannon did. She sat by the mounting-block at the gate of the court, for seven years. To every visitor who came, she told her story. To any who would let her, she offered to carry them on her back, up to the court — as a penance for what she had not done. And rarely did anyone let her.",
      illus: "The gate of the court at Arberth in soft afternoon daylight. Rhiannon — now in plain simple dark wool, no jewelry, hair tied back simply, posture humble but proud — seated beside a stone mounting-block at the foot of the gate, telling her story to a visitor. The visitor (a Welsh traveller on horseback) has dismounted respectfully, hat in hand, and is gently refusing her offer with quiet upraised hands — clearly indicating “no, my lady”. Other passing folk in the background giving Rhiannon respectful nods. NO actual carrying-on-back scene shown — the moral injustice is shown through dignified composition. Sad but not despairing." },

    { title: "Teirnon and His Mare",
      text: "Far away from Dyfed, in another part of Wales, there lived a lord called Teirnon. He was, the old story says, <em>the best man in the world</em>. He kept the finest mare in the kingdom — a chestnut mare. Every May Eve, in the spring, the mare gave birth to a foal. And every May Eve, by morning, the foal was gone. Teirnon could never find what was taking them. After many years of losing foals he said to his wife: <em>“This year, I shall watch.”</em>",
      illus: "A stone-built Welsh medieval stable interior — a fine chestnut mare standing peacefully in her stall on fresh straw, a Welsh lord (Teirnon — middle-aged, broad-shouldered, kind weather-worn face, brown beard, in warm wool tunic and leather work-apron) standing beside her, stroking her neck. Through an open doorway in the background, his wife visible at the kitchen-hearth of their stone-and-timber court. Warm everyday Welsh life scene, gentle, domestic." },

    { title: "The Vigil and the Claw",
      text: "Teirnon brought the mare inside the great hall, armed himself, and sat up beside her in the dark. At midnight she gave birth to a fine strong colt. Teirnon stood up to look at the colt. And as he stood, a great clawed arm reached through the high window — reached for the foal — and the colt began to be lifted away. Teirnon drew his sword and struck the arm off at the elbow. From outside there came a scream. The arm fell. The foal stayed.",
      illus: "Welsh great hall interior, lit only by a low fire. The mare on straw at one side of the hall with her newborn chestnut foal standing on wobbly legs beside her. Teirnon, in mail tunic and helmet, sword in hand mid-downward-swing, having just struck. A great dark-grey clawed arm reaches through a high arched window (the window is glassless, open to night). The arm is severed just above the elbow — the rest of it is in the act of being pulled back outside (we see only its diminishing shadow), the claw still half-grasping the now-saved foal. NO blood — just the dramatic interruption. The unseen power's body is NEVER shown, only the disembodied claw at the window. Atmosphere of midnight magic and bravery." },

    { title: "The Boy at the Door",
      text: "Teirnon ran outside to chase whatever had screamed. In the night he could see nothing. He turned back to the hall. At the threshold of the door — he stopped. A small swaddled boy was lying there, wrapped in fine silk. He could not have been more than a day old. Teirnon picked him up. Inside, his wife was waking. <em>“Look here,”</em> he said. <em>“Here is a son for you, if you will have him.”</em> And he told her the whole story.",
      illus: "Welsh stone doorway at night, lit by a torch above. Teirnon — sword now sheathed, mail unfastened — kneeling at the threshold of his hall, gently picking up a tiny baby wrapped in fine cream-coloured silk. The baby is small, peaceful, alive — golden tufts of hair visible. A starry sky above; soft suggestion of mystery and miracle. Warm doorway-lamplight on the baby; cool blue night beyond. Tender, reverent." },

    { title: "Years of Growing",
      text: "Teirnon and his wife raised the boy as their own. They named him <em>Gwri of the Golden Hair</em>, because his hair was bright as gold. He grew quickly — by one year he could walk strongly; by two he was as big as a six-year-old; by four he was bargaining with the horse-boys to be taken to the river. The very foal Teirnon had saved on the night of his arrival was now broken in and given to Gwri as his first horse. They grew up together, the boy and the colt.",
      illus: "Outdoor scene at Teirnon's court — a young boy (about 4 years old in apparent size, golden-haired, in well-made child's Welsh clothes — small green tunic with embroidered hem, leather belt) standing proudly beside a sleek young chestnut horse (the broken-in foal, now a fine young horse) at a stable-yard. Teirnon and his wife watching from the doorway with quiet pride. Warm afternoon light, daily life feel, genuine family warmth." },

    { title: "The Recognition",
      text: "Years later, news came to Teirnon's court of Rhiannon's strange penance at Arberth — how she sat at the gate, telling her story, offering to carry visitors. Teirnon thought about it. He looked at Gwri carefully — and saw something. He had been Pwyll's man once, many years ago. He knew Pwyll's face well. <em>Gwri,</em> he saw, <em>looks exactly like Pwyll.</em> Teirnon went to his wife. <em>“We cannot keep this boy,”</em> he said. <em>“He is Pwyll's son.”</em>",
      illus: "Indoor evening scene — Teirnon in his great hall, seated by his fire, looking thoughtfully at Gwri (now about 7 years old, golden-haired, strong, in good child's Welsh clothes) who is playing quietly with a young hound at his feet. In Teirnon's hand a small wooden cup; his expression is one of quiet shocked recognition — eyes wide, mouth slightly open, hand frozen mid-motion. His wife visible in the doorway watching him understand. Warm firelight, quiet revelation. Possibly an old painted shield on the wall hints at Pwyll's house-mark." },

    { title: "To Arberth",
      text: "They rode to Arberth — Teirnon, two companions, and the boy on his foal-now-horse. When they came to the gate of the court, they saw Rhiannon sitting beside the mounting-block. As they drew near, she rose. <em>“Lords,”</em> she said, <em>“I shall carry each of you to the court. That is my penance, for killing my son.”</em> Teirnon shook his head. <em>“No, my lady, I shall not let you.”</em> And the boy himself said quietly: <em>“I shall not go.”</em> It was the first word he ever said about her.",
      illus: "The gate of Arberth, soft daylight. Rhiannon at her place by the mounting-block, having just risen, with quiet sad dignity, simply dressed in plain wool. Teirnon (older, mature, kind-faced, on a fine horse), his two companions on horseback behind him, and the boy Gwri (about 7, mounted on his fine chestnut horse) drawing up near the gate. Teirnon politely gesturing “no, my lady” with one quietly raised hand. The boy looking gravely at Rhiannon — not knowing her — but firmly refusing to dismount. NO carrying scene shown. Dignified composition, no melodrama, gentle Welsh afternoon light." },

    { title: "Pryderi",
      text: "At the feast in the hall, Teirnon told Pwyll the whole story — the mare, the claw, the boy at the door, the years of raising. <em>“Here is your son,”</em> he said. Everyone in the hall agreed: the boy looked exactly like Pwyll. Rhiannon's tears fell. <em>“That would be the lifting of my care, if it were true,”</em> she said. Then Pendaran Dyfed said: <em>“Then his name shall be Pryderi — Care — from the word his mother spoke first when she got the glad tidings of him.”</em> And so Pryderi he was, from then on.",
      illus: "The great hall of Arberth, warmly lit by firelight and torches. Pwyll (older now, with a hint of grey in his hair, but still recognisable, in proper prince's clothes again — gold torc, embroidered cloak) and Rhiannon (released from her penance now — in a proper queen's gown again, hair circled by the thin gold band) at the high table together. Teirnon between them. The boy Pryderi (golden-haired, about 7, in his fine child's clothes) standing before them, with Pwyll's hand raised slightly toward him in welcome. Rhiannon's eyes shining with one quiet visible tear. Pendaran Dyfed (an older bearded Welsh noble) standing at the side, in the act of pronouncing the boy's new name. The whole household full of relief and joy. Warm golden hall light, deep emotional moment." },

    { title: "The End — and the Lay",
      text: "Pryderi grew up in Welsh courts — a fine young prince, beloved by everyone. When Pwyll died, Pryderi succeeded him. He ruled the seven cantref of Dyfed well, and then the three cantref of Ystrad Tywi, and the four cantref of Ceredigion. He married a lady called Cigfa. And the harpers of Wales heard the tale, and made it into the First Branch of the Mabinogi — the oldest cycle of Welsh stories we have. The tale ends, as it always does, with the words: <em>And thus ends this Branch here of the Mabinogi.</em>",
      illus: "A closing vignette — a Welsh hall in the evening with a bard playing a small Celtic harp by the fire, a small audience of medieval Welsh folk seated around listening intently. In the background hanging on the wall, small painted medallion-portraits of Pwyll, Rhiannon, and Pryderi as if from the story itself. Warm gold firelight, cozy story-finished mood. The harper closing the tale for the listening hall. Quiet, satisfying, mythic." },
  ],
};
