/* Pwyll Pendefig Dyfed — the First Branch of the Mabinogi. The English
   shown alongside the Welsh is an original translation written movement
   by movement in subsequent passes. The Welsh is a Middle Welsh reading
   text from the Welsh Wikisource (CC BY-SA 4.0), descending from the
   manuscripts (White Book of Rhydderch, c. 1350; Red Book of Hergest,
   c. 1382–1410). The same manuscript tradition also gives us Culhwch ac
   Olwen, whose reading text on this site is taken from the public-domain
   edition of Rhys & Evans (Oxford, 1887).

   The full source is preserved at source/pwyll-wikisource.txt.
   Attaches to window.PWYLL. */
window.PWYLL = window.PWYLL || {};
window.PWYLL.tale = {
  meta: {
    blurb: "<strong>Pwyll Pendefig Dyfed</strong> — the First Branch of the Mabinogi, the foundational Welsh prose tale (manuscripts c. 1350–1410, oral tradition older). A pre-Arthurian tale of <em>exchanges</em>: Pwyll trades places with Arawn lord of Annwn for a year; Pwyll meets Rhiannon on the Gorsedd mound and outwits her promised bridegroom Gwawl; their son Pryderi is mysteriously taken, Rhiannon is falsely punished as the horse at the gate, and the child is recovered. Below are <strong>Movements I–V</strong>: Glyn Cuch and Arawn; the year in Annwn, the duel, the chaste sleep; Rhiannon on the Gorsedd Arberth and the three days of the chase; the wedding feast, the rash promise, the badger in the bag; the birth of Pryderi, his disappearance at midnight, the falsely-accused mother who chose her penance over dispute. The English is an <strong>original translation</strong>. The Middle Welsh beside it is a <em>reading text</em> from the Welsh Wikisource (CC BY-SA 4.0), preserved in the medieval orthography (medieval <em>u</em> for modern <em>f / v</em>; <em>oed</em> for modern <em>oedd</em>; <em>Dyuet</em> for modern <em>Dyfed</em>). The full source is preserved verbatim at <a href=\"source/pwyll-wikisource.txt\">source/pwyll-wikisource.txt</a>.",
    sources: [
      { label: "Pwyll Pendeuic Dyuet — Welsh Wikisource", url: "https://cy.wikisource.org/wiki/Pwyll_Pendeuic_Dyuet", host: "cy.wikisource" },
      { label: "The Text of the Mabinogion — Rhys & Evans, 1887 (Oxford, public domain)", url: "https://archive.org/details/textofmabinogion00rhysiala", host: "Internet Archive" },
      { label: "The Mabinogion — Lady Charlotte Guest, 1838–45 (public domain English translation)", url: "https://www.gutenberg.org/ebooks/5160", host: "Project Gutenberg" },
      { label: "Pwyll Pendefig Dyfed — overview", url: "https://en.wikipedia.org/wiki/Pwyll_Pendefig_Dyfed", host: "Wikipedia" },
    ],
  },
  roadmap: [
    { t: "Source text in hand", done: true },
    { t: "I · Pwyll meets Arawn lord of Annwn in Glyn Cuch", done: true },
    { t: "II · A year as the king of Annwn; the duel with Hafgan", done: true },
    { t: "III · Rhiannon on the Gorsedd mound", done: true },
    { t: "IV · The wedding feast and the badger in the bag", done: true },
    { t: "V · The birth of Pryderi, his disappearance, Rhiannon's punishment", done: true },
    { t: "VI · Teyrnon's discovery, the recognition, the reconciliation", done: false },
  ],
  passages: [
    {
      title: "I. The hunt at Glyn Cuch, and the meeting with Arawn lord of Annwn",
      segments: [
        { w: "Pwyll Pendeuic Dyuet a oed yn arglwyd ar seith cantref Dyuet. A threigylgweith yd oed yn Arberth, prif lys idaw, a dyuot yn y uryt ac yn y uedwl uynet y hela. Sef kyueir o'y gyuoeth a uynnei y hela, Glynn Cuch. Ac ef a gychwynnwys y nos honno o Arberth, ac a doeth hyt ym Penn Llwyn Diarwya, ac yno y bu y nos honno. A thrannoeth yn ieuengtit y dyd kyuodi a oruc, a dyuot y Lynn Cuch i ellwng e gwn dan y coet. A chanu y gorn a dechreu dygyuor yr hela, a cherdet yn ol y cwn, ac ymgolli a'y gydymdeithon. Ac ual y byd yn ymwarandaw a llef yr erchwys, ef a glywei llef erchwys arall, ac nit oedynt unllef, a hynny yn dyuot yn erbyn y erchwys ef. Ac ef a welei lannerch yn y coet o uaes guastat; ac ual yd oed y erchwys ef yn ymgael ac ystlys y llannerch, ef a welei carw o ulaen yr erchwys arall. A pharth a pherued y llannerch, llyma yr erchwys a oed yn y ol yn ymordiwes ac ef, ac yn y uwrw y'r llawr.",
          e: "Pwyll, Prince of Dyfed, was lord over the seven cantref of Dyfed. And one time he was at Arberth, his chief court, when it came into his mind and heart to go hunting. The quarter of his realm he wished to hunt was Glyn Cuch. And he set out that night from Arberth, and came as far as Penn Llwyn Diarwya, and stayed the night there. And on the morrow, in the youth of the day, he rose and came to Glyn Cuch to loose his hounds beneath the wood. He sounded his horn and began the rousing of the hunt, and rode after the hounds, and lost his companions. And while he was listening to the cry of his pack, he heard the cry of another pack — and they were not of one voice, and that other pack was coming toward his own. He saw a glade in the wood of even ground; and as his pack was reaching the edge of the glade, he saw a stag in front of the other pack. And toward the middle of the glade — see! — that strange pack closing on the stag and bearing it to the ground.",
          n: "The opening establishes the kingdom: the <em>seith cantref Dyuet</em>, the seven cantref of Dyfed, the southwest of Wales — a unit of medieval land-administration meaning \"a hundred dwellings\" times seven, the kingdom of Dyfed entire. Arberth is the principal court (modern Narberth in Pembrokeshire). Glyn Cuch is a real valley on the Dyfed–Carmarthen border. Pwyll loses his companions in the hunt — Welsh narrative often opens by stripping the hero down to himself before the encounter that matters." },

        { w: "Ac yna edrych ohonaw ef ar liw yr erchwys, heb hanbwyllaw edrych ar y carw. Ac o'r a welsei ef o helgwn y byt, ny welsei cwn un lliw ac wynt. Sef lliw oed arnunt, claerwyn llathreit, ac eu clusteu yn gochyon. Ac ual y llathrei wynnet y cwn, y llathrei cochet y clusteu. Ac ar hynny at y cwn y doeth ef, a gyrru yr erchwys a ladyssei y carw e ymdeith, a llithyaw y erchwys e hunan ar y carw.",
          e: "And then he looked at the colour of the strange pack, and gave no further thought to the stag. Of all the hunting-hounds he had ever seen in the world, he had seen none of their colour. The colour they wore: a shining brilliant white, and their ears were red. And as the white of the dogs shone bright, so the red of the ears shone bright. And with that he came up to the hounds, drove off the pack that had killed the stag, and set his own pack on the carcass.",
          n: "The <em>cŵn Annwn</em> — the hounds of Annwn — shining white with red ears. The single most famous Otherworld iconography in all Welsh tradition; the folkloric \"spectral hounds\" run from this passage right through to Conan Doyle's <em>Hound of the Baskervilles</em>. Pwyll's act — <em>driving off the pack and setting his own on the kill</em> — is the breach that opens the entire tale. He does not even know it is a breach. Arawn does." },

        { w: "Ac ual y byd yn llithiau y cwn, ef a welei uarchauc yn dyuot yn ol yr erchwys y ar uarch erchlas mawr; a chorn canu am y uynwgyl, a gwisc o urethyn llwyt tei amdanaw yn wisc hela. Ac ar hynny y marchawc a doeth attaw ef, a dywedut ual hynn wrthaw, “A unben,” heb ef, “mi a wnn pwy wyt ti, ac ny chyuarchaf i well it.”",
          e: "And as he was feeding the dogs, he saw a horseman coming after the pack — on a great pale-grey horse, with a hunting-horn around his neck, dressed in a hunting-garb of grey-brown wool. And the horseman came up to him and spoke to him thus: “Lord,” he said, “I know who you are, and I will give you no greeting.”",
          n: "The Otherworld king arrives in the Otherworld's colour-grammar: grey-brown wool, a great pale-grey horse. He withholds <em>cyfarch</em> — the formal Welsh greeting — and names the breach in his first sentence: <em>I know who you are.</em> The encounter is staged as a courtesy-trial." },

        { w: "“Ie,” heb ef, “ac atuyd y mae arnat o anryded ual nas dylyei.” “Dioer,” heb ef, “nyt teilygdawt uy anryded a'm etteil am hynny.” “A unben,” heb ynteu, “beth amgen?” “Y rof i a Duw,” hep ynteu, “dy anwybot dy hun a'th ansyberwyt.” “Pa ansyberwyt, unben, a weleist ti arnaf i?” “Ny weleis ansyberwyt uwy ar wr,” hep ef, “no gyrru yr erchwys a ladyssei y carw e ymdeith, a llithiau dy erchwys dy hun arnaw; hynny,” hep ef, “ansyberwyt oed: a chyn nyt ymdialwyf a thi, y rof i a Duw,” hep ef, “mi a wnaf o anglot itt guerth can carw.”",
          e: "“Well,” said Pwyll, “perhaps the rank you carry is such that it owes me no greeting from you.” “Truly,” said the other, “it is not the worth of my rank that holds me back from that.” “Lord,” said Pwyll, “what then?” “Between me and God,” said the other, “your own ignorance, and your discourtesy.” “What discourtesy, lord, have you seen on me?” “I never saw greater discourtesy in a man,” said he, “than to drive off the pack that had killed the stag, and to set your own pack on the kill. That,” said he, “was discourtesy. And though I shall not avenge myself on you, between me and God,” said he, “I shall get from you a hundred stags' worth of dishonour.”",
          n: "The opening misreading is one of the most economical character-establishments in Welsh literature. Pwyll assumes the stranger is too low-born to greet him; the stranger turns the table by naming the breach Pwyll did not even notice. Welsh <em>ansyberwyt</em> — discourtesy, unworth — is the tale's central concept; the whole driving force of the First Branch is the repair of it." },

        { w: "“A unbenn,” hep ef, “o gwneuthum gam, mi a brynaf dy gerennyd.” “Pa delw,” hep ynteu, “y pryny di?” “Vrth ual y bo dy anryded, ac ny wnn i pwy wyt ti.” “Brenhin corunawc wyf i yn y wlat yd hanwyf oheni.” “Arglwyd,” heb ynteu, “dyd da itt; a pha wlat yd hanwyt titheu oheni?” “O Annwuyn,” heb ynteu. “Arawn urenhin Annwuyn wyf i.”",
          e: "“Lord,” said Pwyll, “if I have done wrong, I shall buy your friendship.” “In what manner,” said the other, “will you buy it?” “According to the measure of your rank — and I do not know who you are.” “I am a crowned king in the land I come from.” “Lord,” said Pwyll, “good day to you. And what land are you of?” “Of Annwn,” said he. “Arawn, king of Annwn, am I.”",
          n: "The naming. <em>Arawn Urenhin Annwuyn</em> — Arawn, King of Annwn — emerges as one of the great Otherworld kings of Welsh tradition. He is <em>brenhin corunawc</em>, a crowned king, the precise dignity of Pwyll himself: the year-exchange that follows is a fair trade only because both parties wear the same crown." },

        { w: "“Arglwyd,” heb ynteu, “pa furyf y caf i dy gerennyd di?” “Llyma wyd y kyffy,” heb ynteu. “Gwr yssyd gyuerbyn y gyuoeth a'm kyuoeth inheu yn ryuelu arnaf yn wastat. Sef yw hwnnw, Hafgan urenhin o Annwuyn. Ac yr guaret gormes hwnnw y arnaf (a hynny a elly yn haut) y keffy uy gherennyd.” “Minnheu a wnaf hynny,” heb ynteu, “yn llawen. A manac ditheu y mi pa furyf y gallwyf hynny.”",
          e: "“Lord,” said Pwyll, “in what manner shall I gain your friendship?” “Here is how,” said he. “There is a man whose realm marches with mine, and he is at war with me without rest. That man is Hafgan, king from Annwn. To free me of this oppression — and you may do that easily — you shall have my friendship.” “I shall do that gladly,” said Pwyll. “Tell me only how I may.”",
          n: "A second king \"of Annwn\" — <em>Hafgan</em>, a name meaning roughly <em>summer-bright</em> or <em>summer-white</em>, evidently an opposite number to Arawn. The Otherworld in Welsh tradition is not monolithic: two crowned kings, two contending kingdoms, perpetual war. <em>Gormes</em> — oppression — is the same word used elsewhere in the Mabinogi for the Three Oppressions of Britain." },

        { w: "“Managaf,” heb ynteu. “Llyna ual y gelly; mi a wnaf a thi gedymdeithas gadarn. Sef ual y gwnaf, mi a'th rodaf di y'm lle i yn Annwuyn, ac a rodaf y wreic deccaf a weleist eiroet y gyscu gyt a thi beunoeth, a'm pryt innheu a'm ansawd arnat ti, hyt na bo na guas ystauell, na swydawc, na dyn arall o'r a'm canlynwys i yroet, a wyppo na bo miui uych ti. A hynny,” heb ef, “hyt ym penn y ulwydyn o'r dyd auory. An kynnadyl yna yn y lle hon.”",
          e: "“I shall tell you,” said Arawn. “Here is how you may. I shall make a strong companionship with you. This is what I shall do: I shall put you in my place in Annwn, and I shall give you the fairest woman you ever saw to sleep at your side every night; and my form and my likeness shall be upon you, so that there shall be neither chamber-servant nor officer nor any of all those who have ever followed me, who shall know that you are not I. And that,” said he, “until the end of a year from tomorrow — our meeting again here in this place.”",
          n: "The year-exchange. Note what the bargain includes and what it implies: full impersonation (<em>pryt</em> and <em>ansawd</em> — form and likeness — laid on Pwyll); the queen as nightly bedfellow; no one to know. The bargain is morally extreme and proposed casually, with the wife included as if she were the bedroom furniture. Movement II will watch what Pwyll does with the night-by-night opportunity that has been put in his hand." },

        { w: "“Ie,” heb ynteu, “kyt bwyf i yno hyt ympenn y ulwydyn, pa gyuarwyd a uyd ymi o ymgael a'r gwr a dywedy di?” “Blwydyn,” heb ef, “y heno, y mae oet y rof i ac ef, ar y ryt. A byd di i'm rith yno,” heb ef, “ac un dyrnaut a rodych di idaw ef; ny byd byw ef o hwnnw. A chyt archo ef yti rodi yr eil, na dyro, yr a ymbilio a thi. Yr a rodwn i idau ef hagen, kystal a chynt yd ymladei a mi drannoeth.”",
          e: "“Well,” said Pwyll, “if I am to be there until the year's end, how shall I know how to meet the man you speak of?” “A year from tonight,” said Arawn, “is my appointment with him, at the ford. Be in my likeness there,” he said, “and one stroke you shall give him — he shall not live from it. And though he ask you to give him the second stroke, do not give it, however he plead with you. For though I have given him a second, on the morrow he would fight as well as he had before.”",
          n: "The duel's rule. <em>One stroke only.</em> The poem's rash-promise constraint is a one-stroke constraint — and it is precisely the inverse of the bargain in Sir Gawain, where the single blow received <em>must</em> be returned. Two opposite weightings of the same M223 architecture: in Gawain, the one blow must come back; in Pwyll, the one blow must not be repeated. The medieval Insular imagination loves these single-blow contracts." },

        { w: "“Ie,” heb y Pwyll, “beth a wnaf i y'm kyuoeth?” “Mi a baraf,” hep yr Arawn, “na bo i'th gyuoeth na gwr na gwreic a wyppo na bo tidi wwyf i. A miui a af i'th le di.” “Yn llawenn,” hep y Pwyll, “a miui a af ragof.” “Dilesteir uyd dy hynt ac ny russya dim ragot, yny delych y'm kyuoeth i: a mi a uydaf hebryngyat arnat.”",
          e: "“Well,” said Pwyll, “and what shall be done in my own realm?” “I shall arrange,” said Arawn, “that in your realm neither man nor woman shall know that I am not you. And I shall go in your place.” “Right gladly,” said Pwyll. “And I shall go forth.” “Your way shall be unhindered, and nothing shall thwart you, until you come into my realm; and I shall be your guide there.”",
          n: "The double exchange sealed. <em>And I shall go in your place</em> — Arawn will rule Dyfed for the year. The whole structural symmetry of the First Branch is now in place: two kings in each other's realms, each other's wars, each other's beds. The Welsh tradition's most elegant test of trust, proposed on a single hunt by a single offended courtesy. Movement II opens at the boundary." },
      ],
    },

    {
      title: "II. A year as the king of Annwn, the duel at the ford, the chaste sleep, the renaming",
      segments: [
        { w: "Ef a'y hebryghaud yny welas y llys a'r kyuanned. “Llyna,” hep ef, “y llys a'r kyuoeth i'th uedyant. A chyrch y llys. Nit oes yndi nep ni'th adnappo; ac wrth ual y guelych y guassanaeth yndi, yd adnabydy uoes y llys.” Kyrchu y llys a oruc ynteu. Ac yn y llys ef a welei hundyeu ac yneuadeu, ac ysteuyll, a'r ardurn teccaf a welsei neb o adeiladeu. Ac y'r neuad y gyrchwys y diarchenu. Ef a doeth makwyueit a gueisson ieueinc y diarchenu, a phaup ual y delynt kyuarch guell a wneynt idaw. Deu uarchauc a doeth i waret i wisc hela y amdanaw, ac y wiscaw eurwisc o bali amdanaw.",
          e: "He led him until he saw the court and the dwellings. “There,” he said, “is the court and the realm in your power. Make for the court. There is no one in it who will not know you; and from what you see of the service in it, you will learn the custom of the court.” Pwyll made for the court. And in the court he saw sleeping-chambers and halls and rooms, and the fairest furnishings of any building he had ever seen. He went into the great hall to be unshod. Squires and young pages came to unshoe him, and each as he came up gave him greeting. Two knights came to remove his hunting-garb and to dress him in a court-robe of gold-shot silk.",
          n: "The Annwn court — built in Welsh tradition on the same architectural scale as a king's hall, only finer. No precious-stone walls, no levitating stones, no ever-light: just the best of what a Welsh palace could be. The Otherworld here is not a different reality, only a finer one — distinctively Insular, distinctively Welsh, set against the crystal-and-jewel iconography that the English Sir Orfeo will inherit four hundred years later." },

        { w: "A'r neuad a gyweirwyt. Llyma y guelei ef teulu ac yniueroed, a'r niuer hardaf a chyweiraf o'r a welsei neb yn dyuot y mywn, a'r urenhines y gyt ac wynt, yn deccaf gwreic o'r a welsei neb, ac eurwisc amdanei o bali llathreit. Ac ar hynny, e ymolchi yd aethant, a chyrchu y bordeu a orugant, ac eisted a wnaethant ual hynn — y urenhines o'r neill parth idaw ef, a'r iarll, debygei ef, o'r parth arall. A dechreu ymdidan a wnaeth ef a'r urenhines. Ac o'r a welsei eiryoet wrth ymdidan a hi, dissymlaf gwreic a bonedigeidaf i hannwyt a'y hymdidan oed. A threulaw a wnaethant bwyt a llynn a cherdeu a chyuedach. O'r a welsei o holl lyssoed y dayar, llyna y llys diwallaf o uwyt a llynn, ac eur lestri, a theyrndlysseu.",
          e: "And the hall was set. Then he saw a household and companies — the noblest and best-appointed gathering he had ever seen coming in — and the queen with them, the fairest woman he had ever seen, in a court-robe of shining gold-shot silk. And with that they went to wash, and made for the tables, and sat thus: the queen on one side of him, and an earl, as he supposed, on the other. And he began to converse with the queen. Of all he had ever conversed with, she was the most natural and noblest in her ways and in her speech. And they passed the time on meat and drink and song and banquet. Of all the courts of earth he had ever seen, this was the court most furnished of meat and drink and gold vessels and royal treasures.",
          n: "The queen, unnamed in the source (Welsh tradition often keeps the Otherworld queen anonymous, as Sir Orfeo later keeps the Fairy Queen). Pwyll's pleasure in her company is given full weight; the test the night will pose is set up by the courtly fairness of the day." },

        { w: "Amser a doeth udunt e uynet e gyscu, ac y gyscu yd aethant, ef a'r urenhines. Y gyt ac yd aethant yn y guely ymchwelut e weneb at yr erchwyn a oruc ef, a'y geuyn attei hitheu. O hynny hyt trannoeth, ny dywot ef wrthi hi un geir. Trannoeth, tirionwch ac ymdidan hygar a uu y ryngthunt. Peth bynnac o garueidrwyd a wei y rungthunt y dyd, ni bu unnos hyt ym pen y ulwydyn amgen noc a uu y nos gyntaf.",
          e: "The time came for them to go to sleep, and to sleep they went, he and the queen. The moment they were in the bed, he turned his face to the bed-edge, and his back to her. From that until the morrow he did not say one word to her. On the morrow, kindness and gracious conversation between them. Whatever fondness was between them by day, there was not one night until the year's end different from what the first night had been.",
          n: "The chaste night. The fairest woman ever offered, the form of her own husband on him, the year-long licence — and Pwyll turns his back and is silent. The Welsh prose registers no internal monologue, no reasoning, no struggle. The act is reported as the natural consequence of <em>cedymdeithas</em>, companionship. For the cross-tale layer this is a refined H1556 fidelity test of a kind absent from all three of the other annotated poems: the test is what the hero does in the husband's bed, when there is no one to see and the husband himself has put him there." },

        { w: "Treulaw y ulwydyn a wnaeth trwy hela, a cherdeu, a chyuedach, a charueidrwyd, ac ymdidan a chedymdeithon, hyt y nos yd oet y gyfranc. Yn oet y nos honno, kystal y doi y gof y'r dyn eithaf yn yr holl gyuoeth yr oet [ac idaw ynteu]. Ac ynteu a doeth i'r oet, a guyrda y gyuoeth y gyt ac ef. Ac y gyt ac y doeth i'r ryt, marchawc a gyuodes y uynyd, ac a dywot wal hynn: “A wyrda,” heb ef, “ymwerendewch yn da. Y rwng y deu wrenhin y mae yr oet hwnn, a hynny y rwng y deu gorff wylldeu. A fob un o honunt yssyd hawlwr ar y gilyd, a hynny am dir a dayar. A ssegur y digaun pawn o honawch uot, eithyr gadu y ryngthunt wylldeu.”",
          e: "He spent the year in hunting, song, banqueting, fondness, and conversation with companions, until the night of the appointment. On that night, the appointment came as clearly into the mind of the furthest man in all the realm as into his own. And he came to the appointment, with the nobles of his realm beside him. And when they came to the ford, a knight rose up and spoke as follows: “Nobles,” he said, “listen well. Between the two kings is this appointment, and that between their two bodies. Each of them is a claimant against the other, and that for land and territory. It is for each of you to stand idle, save to leave it between the two of them.”",
          n: "The herald's speech is the formal protocol of the duel. <em>Y rwng y deu gorff wylldeu</em> — between the two bodies. Single combat between sovereigns for territory; the witnessing army is forbidden to intervene. Medieval Welsh judicial duelling, transposed onto the Otherworld and given its purest possible setting — a ford, a knight rising in his stirrups, two kings approaching from opposite banks." },

        { w: "Ac ar hynny y deu urenhin a nessayssant y gyt am perued y ryt e ymgyuaruot. Ac ar y gossot kyntaf, y gwr a oed yn lle Arawn, a ossodes ar Hafgan ym perued bogel y daryan yny hyllt yn deu hanner, ac yny dyrr yr arueu oll, ac yny uyd Hafgan hyt y ureich a'e paladyr dros pedrein y uarch y'r llawr, ac angheuawl dyrnawt yndaw ynteu.",
          e: "And with that, the two kings drew together in the middle of the ford for the encounter. And at the first stroke, the man in Arawn's place struck Hafgan on the middle of his shield-boss until it split in two halves, and until all his armour broke, and until Hafgan was thrown an arm's length and a spear-length beyond his horse's rump on the ground, with a death-stroke in him.",
          n: "One stroke. The contract held perfectly. The mortal blow is delivered with the maximum medieval-Welsh poetic precision — the boss, the split, the body's measured cast beyond the horse — but Pwyll's hand is calm. He has done what was asked, no more." },

        { w: "“A unben,” heb yr Hafgan, “pa dylyet a oed iti ar uy angheu i? Nit yttoydwn i yn holi dim i ti. Ni wydwn achos it heuyt y'm llad i; ac yr Duw,” heb ef, “canys dechreueist uy llad, gorffen.” “A unbenn,” heb ynteu, “ef a eill uot yn ediuar gennyf gwneuthur a wneuthum itt. Keis a'th lado; ni ladaf i di.”",
          e: "“Lord,” said Hafgan, “what claim had you on my death? I was not asking anything of you. I know no reason for you to kill me; and for God's sake,” he said, “since you have begun killing me, finish.” “Lord,” said the other, “it may yet be that I shall be sorry for what I have done to you. Find one to kill you; I shall not kill you.”",
          n: "The refusal of the second stroke. Hafgan asks for the kindness of completion; Pwyll, holding to Arawn's instruction — <em>one stroke only, never a second</em> — refuses, by naming an honest oblique reason: <em>it may yet be I shall be sorry.</em> The bargain's narrowness and the hero's restraint coincide. The Insular ethic of mercy and the Insular ethic of honoured contract wear the same name here: <em>cedymdeithas</em>, companionship — owed not only to the friend but, by its logic, even to the enemy he was sent to kill." },

        { w: "“Vy ngwyrda kywir,” heb yr Hafgan, “dygwch ui odyma: neut teruynedic angheu y mi. Nit oes ansawd y mi y'ch kynnal chwi bellach.” “Vy ngwyrda innheu,” heb y gwr a oed yn lle Arawn, “kymerwch ych kyuarwyd, a gwybydwch pwy a dylyo bot yn wyr ymi.” “Arglwyd,” heb y gwyrda, “pawb a'y dyly, canyt oes urenhin ar holl Annwuyn namyn ti.” “Ie,” heb ynteu, “a del yn waredauc, iawn yw [y] gymryt. Ar ny del yn uuyd, kymmeller o nerth cledyueu.” Ac ar hynny, kymryt gwrogaeth y gwyr a dechreu guereskynn y wlat. Ac erbyn hanner dyd drannoeth, yd oed yn y uedyant y dwy dyrnas.",
          e: "“My faithful nobles,” said Hafgan, “carry me from here. My death is now fixed. There is no longer any way for me to support you.” “My nobles, then,” said the man in Arawn's place, “take your counsel and know who is bound to be my men.” “Lord,” said the nobles, “every man is bound to it, since there is now no king of all Annwn but you.” “Well,” said he, “whoever comes obediently, it is right to receive him. Whoever does not come willingly, let him be compelled by the power of the sword.” And with that, he took the homage of the men, and began to subdue the land. And by midday on the morrow, the two kingdoms were in his power.",
          n: "Hafgan's own nobles testify that there is no king but Arawn now. The two contending kingdoms of Annwn united by a single stroke at the ford. Pwyll's year of trust is justifying its weight: by half a day after the appointment, he holds the whole Otherworld." },

        { w: "Ac ar hynny, ef a gerdwys parth a'y gynnadyl, ac a doeth y Lynn Cuch. A phan doeth yno, yd oed Arawn urenhin Annwuyn yn y erbyn. Llawen uu pob un wrth y gilid o honunt. “Ie,” heb yr Arawn, “Duw a dalo itt dy gydymdeithas; mi a'y kygleu.” “Ie,” heb ynteu, “pan delych dy hun i'th wlat, ti a wely a wneuthum i yrot ti.” “A wnaethost,” heb ef, “yrof i, Duw a'y talo itt.” Yna y rodes Arawn y furuf, a'y drych e hun y Pwyll, Pendeuic Dyuet, ac y kymerth ynteu y furuf e hun a'y drych. Ac y kerdaud Arawn racdaw parth a'y lys y Annwuyn, ac y bu digrif ganthaw ymwelet a'y eniuer ac a'y deulu, canis rywelsei ef wy ys blwydyn. Wynteu hagen ni wybuyssynt i eisseu ef, ac ni bu newydach ganthunt y dyuodyat no chynt.",
          e: "And with that, he set out for his appointment, and came to Glyn Cuch. And when he came there, Arawn, king of Annwn, was there to meet him. Each was joyful at the other. “Well,” said Arawn, “may God repay you for your companionship — I have heard of it.” “Well,” said the other, “when you come yourself to your country, you shall see what I have done for you.” “What you have done,” said he, “for me, may God repay you.” Then Arawn gave his form and appearance to Pwyll Prince of Dyfed, and took back his own form and appearance. And Arawn rode on to his court in Annwn, and was delighted to see his household and his people, since he had not seen them for a year. They however had not missed him, and his coming was no fresher to them than any other day.",
          n: "<em>They had not missed him.</em> One of the lay's quietest miracles — the courtiers of Annwn lived with Pwyll-as-Arawn for an entire year without noticing a substitution. Pwyll's impersonation was complete; Arawn's reputation is preserved intact. The exchange's whole point sits in the closing detail of this paragraph." },

        { w: "Y dyd hwnnw a dreulwys trwy digrifwch a llywenyd, ac eisted ac ymdidan a'y wreic ac a'y wyrda. A phan uu amserach kymryt hun no chyuedach, y gyscu yd aethant. Y vely a gyrchwys, a'y vreic a aeth attaw. Kyntaf y gwnaeth ef ymdidan a'y wreic, ac ymyrru ar digriwwch serchawl a charyat arnei. A hynny ny ordifnassei hi ys blwydyn, a hynny a uedylywys hi. “Oy a Duw,” heb hi, “pa amgen uedwl yssyd yndaw ef heno noc ar a uu yr blwydyn y heno?” A medylyaw a wnaeth yn hir. A guedy y medwl hwnnw, duhunaw a wnaeth ef, a farabyl a dywot ef wrthi hi, a'r eil, a'r trydyt; ac attep ny chauas ef genthi hi yn hynny. “Pa achaws,” heb ynteu, “na dywedy di wrthyf i?” “Dywedaf wrthyt,” heb hi, “na dywedeis ys blwydyn y gymmeint yn y kyfryw le a hwnn.”",
          e: "That day he spent in merriment and gladness, sitting and conversing with his wife and his nobles. And when it was rather time for sleeping than for feasting, they went to bed. He made for the bed, and his wife came to him. The first thing he did was to converse with his wife, and to engage in loving fondness and affection with her. And this was not what she had been accustomed to for the year — and at that she pondered. “Oh God,” she said, “what different mind is in him tonight than has been for the year tonight?” And she thought for a long time. And after that thought, he stirred, and spoke a word to her, and a second, and a third — and got no answer from her. “Why,” said he, “do you not speak to me?” “I tell you,” she said, “I have not spoken in a year as much in such a place as this.”",
          n: "The mirror scene. Arawn, returning, behaves as a husband always behaves at homecoming. His wife is bewildered. The poem stages the recognition not as an explanation but as the wife's stunned silence followed by her quiet accusation, leaving Arawn to work out what has happened." },

        { w: "“Paham?” heb ef. “Ys glut a beth yd ymdidanyssam ni.” “Meuyl im,” heb hi, “yr blwydyn y neithwyr o'r pan elem yn nyblyc yn dillat guely, na digrifwch, nac ymdidan, nac ymchwelut ohonot dy wyneb attaf i — yn chwaethach a uei uwy no hynny o'r bu y rom ni.” Ac yna y medylywys ef, “Oy a Arglwyd Duw,” heb ef, “cadarn a ungwr y gydymdeithas, a diffleeis, a geueis i yn gedymdeith.” Ac yna y dywot ef wrth y wreic: “Arglwydes,” heb ef, “na chapla di uiui. Y rof i a Duw,” heb ynteu, “ni chyskeis inheu gyt a thi, yr blwydyn y neithwyr, ac ni orwedeis.” Ac yna menegi y holl gyfranc a wnaeth idi. “I Duw y dygaf uy nghyffes,” heb hitheu, “gauael gadarn a geueist ar gedymdeith yn herwyd ymlad a frouedigaeth y gorff, a chadw kywirdeb wrthyt titheu.” “Arglwydes,” heb ef, “sef ar y medwl hwnnw yd oedwn inheu, tra deweis wrthyt ti.” “Diryued oed hynny,” heb hitheu.",
          e: "“Why?” said he. “We have been close in our conversation often enough.” “Shame on me,” said she, “for the year since last night, from when we entered the folds of the bed-clothes, neither delight, nor conversation, nor turning your face to me — much less anything more than that between us.” And then he thought: “Oh Lord God,” he said, “strong and single is the companionship and the faith I have got for a companion.” And then he said to his wife: “Lady,” said he, “do not blame me. Between me and God,” he said, “I did not sleep with you, for the year since last night, nor did I lie with you.” And then he told her the whole matter. “I take my confession to God,” said she, “you have got a strong grip on a companion in fighting and in bodily temptation, and in keeping faith with you.” “Lady,” said he, “that was the very thought I had while I was silent to you.” “That was not strange,” said she.",
          n: "The reveal is in two registers. Arawn's prayer of relief — <em>strong and single is the companionship and faithful that I have got</em>. The wife's appraisal of Pwyll — <em>you have got a strong grip on a companion in fighting and in bodily temptation, and in keeping faith with you</em>. She names both tests Pwyll has passed (the ford and the bed) and ties them together as one proof of trustworthiness. The Welsh prose passes through the most intimate possible domestic scene without sentimentality and arrives at the most rigorous possible judgment." },

        { w: "Ynteu Pwyll, Pendeuic Dyuet, a doeth y gyuoeth ac y wlat. A dechreu ymouyn a gwyrda y wlat, beth a uuassei y arglwydiaeth ef arnunt hwy y ulwydyn honno y wrth ryuuassei kynn no hynny. “Arglwyd,” heb wy, “ny bu gystal dy wybot; ny buost gyn hygaret guas ditheu; ny bu gyn hawsset gennyt titheu treulaw dy da; ny bu well dy dosparth eiroet no'r ulwydyn honn.” “Y rof i a Duw,” heb ynteu, “ys iawn a beth iwch chwi, diolwch y'r gwr a uu y gyt a chwi, a llyna y gyfranc ual y bu” — a'e datkanu oll o Pwyll. “Ie, Arglwyd,” heb wy, “diolwch y Duw caffael o honot y gydymdeithas honno; a'r arglwydiaeth a gaussam ninheu y ulwydyn honno, nys attygy y gennym, ot gwnn.” “Nac attygaf, y rof i a Duw,” heb ynteu Pwyll.",
          e: "As for Pwyll, Prince of Dyfed, he came to his realm and his land. And he began to ask the nobles of his land what his lordship over them had been that year, compared to what it had been before. “Lord,” they said, “your understanding was never so good; you were never so kind a young man; never was it easier for you to spend your goods; your governance was never better than in this past year.” “Between me and God,” said he, “it is right that you should thank the man who was with you, and here is the matter as it was” — and Pwyll declared it all. “Well, Lord,” they said, “thanks be to God that you got that companionship; and the lordship that we had this past year, you will not take it away from us, will you?” “I shall not take it away, between me and God,” said Pwyll.",
          n: "Pwyll asks <em>how was my lordship?</em> — the question that opens the door for the truth. His nobles, having lived under Arawn's rule a year, give the most generous report he could have hoped for of himself. His honesty in passing the credit on, and his promise not to undo the policies Arawn established, complete the circuit. The exchange has changed both kingdoms." },

        { w: "Ac o hynny allan, dechreu cadarnhau kedymdeithas y ryngthunt, ac anuon o pop un y gilid meirch a milgwn a hebogeu a fob gyfryw dlws, o'r a debygei bob un digrifhau medwl y gilid o honaw. Ac o achaws i drigiant ef y ulwydyn honno yn Annwuyn, a gwledychu o honaw yno mor lwydannus, a dwyn y dwy dyrnas yn un drwy y dewred ef a'y uilwraeth, y diffygywys y enw ef ar Pwyll, Pendeuic Dyuet, ac y gelwit Pwyll Penn Annwuyn o hynny allan.",
          e: "And from then on, friendship began to be strengthened between them, and each sent to the other horses and greyhounds and hawks and every kind of treasure he thought to gladden the other's mind. And because of his dwelling there for a year in Annwn, and because of his ruling so prosperously, and bringing the two kingdoms into one through his bravery and his warriorship — his name “Pwyll Prince of Dyfed” began to weaken, and from then on he was called <em>Pwyll Penn Annwfn</em>: Pwyll Head of Annwn.",
          n: "The renaming. <em>Penn Annwuyn</em> — Head of Annwn, the title Pwyll carries from this moment forward into all later Welsh tradition. The kingdom of the Otherworld is in his title, not by inheritance, not by conquest of his own arm, but by the loaned year and the held companionship. The closing word of Movement II is the new name. Movement III will open with the same Welsh formula that opened Movement I — <em>a threigylgueith yd oed yn Arberth</em>, \"and one time he was at Arberth\" — but a different king now sits at Arberth." },
      ],
    },

    {
      title: "III. Pwyll on the Gorsedd Arberth, the three days of the chase, the bargain with Rhiannon",
      segments: [
        { w: "A threigylgueith yd oed yn Arberth, priflys idaw, a gwled darparedic idaw, ac yniueroed mawr o wyr y gyt ac ef. A guedy y bwyta kyntaf, kyuodi y orymdeith a oruc Pwyll, a chyrchu penn gorssed a oed uch llaw y llys, a elwit Gorssed Arberth. “Arglwyd,” heb un o'r llys, “kynnedyf yr orssed yw, pa dylyedauc bynnac a eistedo arnei, nat a odyno heb un o'r deupeth, a'y ymriw neu archolleu, neu ynteu a welei rywedawt.” “Nyt oes arnaf i ouyn cael kymriw, neu archolleu, ym plith hynn o niuer. Ryuedawt hagen da oed gennyf pei ys guelwn. Mi a af,” heb ynteu, “y'r orssed y eisted.” Eisted a wnaeth ar yr orssed.",
          e: "One time he was at Arberth, his chief court — a feast was prepared for him, and great companies of men with him. And after the first eating, Pwyll arose to walk, and made for the head of a mound above the court that was called Gorsedd Arberth. “Lord,” said one of the court, “it is the custom of this mound that whatever nobleman sits upon it, he does not leave it without one of two things — either wounds or hurts, or else he sees a marvel.” “I have no fear of getting wounds or hurts among this company. But a marvel I would gladly see, if I were to see one. I shall go,” said he, “to the mound to sit.” And he sat upon the mound.",
          n: "The Welsh formula <em>a threigylgueith</em> — \"and one time\" — opens this Movement just as it opened Movement I. The court is reset: same Arberth, same king, same opening grammar, but it is Pwyll Penn Annwfn now, and the question is no longer what he will do in the wild but what wonder will come to him at the court's edge. Gorsedd Arberth is a real Pembrokeshire mound, the named legendary site where the marvels of three of the Four Branches unfold. The custom of <em>wounds or wonder</em> is one of the great threshold-formulae of Welsh tradition." },

        { w: "Ac wal y bydynt yn eisted, wynt a welynt gwreic ar uarch canwelw mawr aruchel, a gwisc eureit, llathreit, o bali amdanei, yn dyuot ar hyt y prifford a gerdei heb law yr orssed. Kerdet araf, guastat oed gan y march ar uryt y neb a'y guelei, ac yn dyuot y ogyuuch a'r orssed. “A wyr,” heb y Pwyll, “a oes ohonawchi, a adnappo y uarchoges?” “Nac oes, Arglwyd,” heb wynt. “Aet un,” heb ynteu, “yn y herbyn y wybot pwy yw.”",
          e: "And as they were sitting, they saw a woman on a great pale-white horse, lofty and tall — and a robe of gold-shot silk shining upon her — coming along the main road that passed below the mound. The horse's pace, by the look of any who saw it, was slow and steady; and she was coming level with the mound. “Men,” said Pwyll, “is there any of you who knows the rider?” “There is not, Lord,” they said. “Let one of you go,” said he, “to meet her, and to know who she is.”",
          n: "The pale-white horse. Rhiannon's iconography is established at her first appearance — a great pale-white horse moving at its own pace, regardless of any pursuit. Her name derives from the proto-Celtic <em>Rīgantonā</em>, \"Great Queen,\" and stands behind the Welsh horse-goddess tradition (Epona-cognate); the horse is no chance choice. The Otherworld's white-horse iconography binds her into the same Insular fae-tradition that gave us Arawn's hounds in Movement I, and that Sir Orfeo will inherit four centuries later in the snow-white retinue." },

        { w: "Un a gyuodes y uynyd, a phan doeth yn y'herbyn y'r ford, neut athoed hi heibaw. Y hymlit a wnaeth ual y gallei gyntaf o pedestric. A fei mwyaf uei y urys ef, pellaf uydei hitheu e wrthaw ef. A phan welas na thygyei idaw y hymlit, ymchwelut a oruc at Pwyll a dywedut wrthaw, “Arglwyd,” heb ef, “ni thykya y pedestric yn y byt e hymlit hi.”",
          e: "One man rose, and when he came to meet her on the road — behold, she had passed him by. He pursued her at his fastest foot-pace. And the greater his haste, the further she was from him. And when he saw that pursuit availed him nothing, he turned back to Pwyll and said, “Lord, no man on foot in the world can pursue her.”",
          n: "The first manifestation of the chase-without-catching. The marvel here is not in the horse's speed but in the <em>relationship</em>: the faster the pursuer, the further she gets. The enchantment is structural. None of our three other annotated poems carries this exact motif — F576-family magical pursuit-eluding — and Pwyll brings it into the cross-tale layer as its distinctive Welsh contribution." },

        { w: "“Ie,” heb ynteu Pwyll, “dos y'r llys, a chymer y march kyntaf a wypych, a dos ragot yn y hol.” Y march a gymerth, ac racdaw yd aeth; y maestir guastat a gauas, ac ef a dangosses yr ysparduneu y'r march. A ffei uwyaf y lladei ef y march, pellaf uydei hitheu e wrthaw ef. Yr vn gerdet a dechreuyssei hitheu, yd oed arnaw. Y uarch ef a ballwys; a phan wybu ef ar y uarch pallu y bedestric, ymchwelut yn yd oed Pwyll a wnaeth. “Arglwyd,” heb ef, “ny thykya y neb ymlit yr unbennes racco. Ny wydwn i varch gynt yn y kyuoyth no hwnnw, ac ni thygyei ymi y hymlit hi.” “Ie,” heb ynteu Pwyll, “y mae yno ryw ystyr hut. Awn parth a'r llys.” Y'r llys y doethant, a threulau y dyd hwnnw a wnaethant.",
          e: "“Right,” said Pwyll, “go to the court, take the fastest horse you know, and go after her.” He took the horse and went on; he found the level open field, and showed the spurs to the horse. And the greater his beating of the horse, the further she was from him. The same pace she had set out at, she still held. And his horse failed; and when he saw his horse was failing in the pursuit, he turned back to where Pwyll was. “Lord,” said he, “pursuit avails no man against that lady. I knew no horse swifter in the realm than that one, yet it did not avail me to pursue her.” “Right,” said Pwyll, “there is some sort of enchantment here. We shall go to the court.” They came to the court, and spent the day there.",
          n: "Pwyll's reading is the right one: <em>hut</em> — enchantment. The chase-without-catching is not a matter of speed but of fate. Three days of failure will follow before the rule is understood — Rhiannon may be approached only by being asked, not by being pursued." },

        { w: "A thrannoeth, kyuodi e uynyd a wnaethant, a threulaw hwnnw yny oed amser mynet y uwyta. A gwedy y bwyta kyntaf, “Ie,” heb ynteu Pwyll, “ni a awn yr yniuer y buam doe, y penn yr orssed. A thidy,” heb ef, wrth vn o'y uakwyueit, “dwg gennyt y march kyntaf a wypych yn y mays.” A hynny a wnaeth y makwyf. Yr orssed a gyrchyssant, a'r march ganthunt. Ac val y bydynt yn eiste, wynt a welynt y wreic ar yr vn march, a'r vn wisc amdanei, yn dyuot yr un ford. “Llyma,” heb y Pwyll, “y uarchoges doe. Bid parawt,” heb ef, “was, e wybot pwy yw hi.” “Arglwyd,” heb ef, “mi a wnaf hynny yn llawen.” Ar hynny, y uarchoges a doeth gywerbyn ac wynt. Sef a oruc y mukwyf yna, yskynnu ar y march, a chynn daruot idaw ymgueiraw yn y gyfrwy neu ry adoed hi heibaw, a chynnwll y rygthunt. Amgen urys gerdet nit oed genthi hi no'r dyd gynt. Ynteu a gymerth rygyng y gan y uarch, ac ef a dybygei yr araued y kerdei y uarch yr ymordiwedei a hi. A hynny ny thy gywys idaw. Ellwg y uarch a oruc wrth auwyneu; nyt oed nes idi yna no chytl bei ar y gam; a phei wyaf y lladei ef y uarch, pellaf uydei hitheu e wrthaw ef: y cherdet hitheu nit oed uwy no chynt. Cany welas ef tygyaw idaw e hymlit ymchwelut a wnueth a dyuot yn yd oet Pwyll. “Arglwyd,” heb ef, “nyt oess allu gan y march amgen noc a weleisti.” “Mi a weleis,” heb ynteu, “ny thykya y neb y herlit hi. Ac y rof i a Duw,” heb ef, “yd oed neges idi wrth rei o'r maes hwnn pei gattei wrthpwythi idi y dywedut; a ni a awn parth a'r llys.”",
          e: "On the morrow they rose and spent the day until it was time to eat. And after the first eating, “Right,” said Pwyll, “let us go to the company we were yesterday, to the head of the mound. And you,” said he to one of his squires, “bring with you the fastest horse you know in the field.” That the squire did. They made for the mound, with the horse with them. And as they were sitting, they saw the woman on the same horse, the same robe upon her, coming the same road. “There,” said Pwyll, “is yesterday's rider. Be ready, boy, to find out who she is.” “Lord,” he said, “I shall do that gladly.” With that, the rider came opposite them. The squire mounted the horse; and before he had settled himself in the saddle, she had gone past him, and there was a gap between them. Her pace of riding was no different from the day before. He held his horse to a canter, thinking that even at the slowness of her pace he could overtake her. And that did not happen. He let his horse loose on the reins; he was no nearer her then than if he had gone on foot. And the more he beat his horse, the further she was from him; her pace was no greater than before. When he saw that pursuit availed him nothing, he turned back, and came to where Pwyll was. “Lord,” said he, “this horse has no more power than you have seen.” “I have seen,” said Pwyll, “that pursuit avails no man against her. And between me and God,” said he, “she had an errand for someone in this field, if she would only let it be spoken to her. Let us go to the court.”",
          n: "Pwyll's second-day reading is sharper. After watching the chase fail again, he names the truth: <em>she had an errand for someone here, if she would only let it be spoken to her.</em> The enchantment is not against pursuit; it is against speech, until the speech is offered as a request rather than as a demand." },

        { w: "Y'r llys y doethant, a threulaw y nos honno a orugant drwy gerdeu a chyuedach, ual y bu llonyd ganthunt. A thrannoeth diuyrru y dyd a wnaethant yny oed amser mynet y wwyta. A phan daruu udunt y bwyd Pwyll a dywot, “Mae yr yniuer y buom ni doe ac echtoe ym penn yr orssed?” “Llymma, Arglwyd,” heb wynt. “Awn,” heb ef, “y'r orssed y eiste, a thitheu,” heb ef, wrth was y uarch, “kyfrwya uy march yn da, a dabre ac ef y'r ford, a dwc uy ysparduneu gennyt.” Y gwas a wnaeth hynny. Dyuot yr orssed a orugant y eisted. Ny buant hayach o enkyt yno, yny welynt y uarchoges yn dyuot yr vn ford, ac yn un ansawd, ac vn gerdet. “Ha was,” heb y Pwyll, “mi a welaf y uarchoges. Moes uy march.” Yskynnu a oruc Pwyll ar y uarch, ac nyt kynt yd yskynn ef ar y uarch, noc yd a hitheu hebdaw ef. Troi yn y hol a oruc ef, a gadel y uarch drythyll, llamsachus y gerdet. Ac ef a debygei, ar yr eil neit, neu ar y trydyd, y gordiwedei. Nyt oed nes hagen idi no chynt. Y uarch a gymhellaud o'r kerdet mwyaf a oed ganthaw. A guelet a wnaeth na thygyei idaw y hymlit.",
          e: "They came to the court, and spent that night with songs and feasting, as was their custom. And on the morrow they passed the day until it was time to eat. And when they had finished eating, Pwyll said, “Where is the company we were yesterday and the day before, on the head of the mound?” “Here, Lord,” they said. “Let us go,” said he, “to the mound to sit; and you,” he said to the horse-page, “saddle my horse well, and bring it to the road, and bring my spurs with you.” The page did so. They came to the mound and sat. They had not been there long when they saw the rider coming the same road, in the same fashion, at the same pace. “Boy,” said Pwyll, “I see the rider. Give me my horse.” Pwyll mounted; and no sooner had he mounted than she had gone past him. He turned after her, and let the horse have its head at its high, leaping pace. He thought that at the second bound, or the third, he would overtake her. She was no nearer to him than before. He drove his horse to its greatest pace. And he saw that pursuit availed him nothing.",
          n: "The third day, the third pursuer, the third failure — the threefold repetition the Welsh imagination loves. Now the king himself rides; the enchantment relents for him as little as for his squires. Pwyll thinks at the second or third bound of his horse he will catch her: no nearer." },

        { w: "Yna y dywot Pwyll. “A uorwyn,” heb ef, “yr mwyn y gwr mwyhaf a gery, arho ui.” “Arhoaf yn llawen,” heb hi, “ac oed llessach y'r march, pei ass archut yr meityn.” Sewyll, ac arhos a oruc y uorwyn, a gwaret y rann a dylyei uot am y hwyneb o wisc y phenn, ac attal y golwc arnaw, a dechreu ymdidan ac ef. “Arglwydes,” heb ef, “pan doy di, a pha gerdet yssyd arnat ti?” “Kerdet wrth uy negesseu,” heb hi, “a da yw gennyf dy welet ti.” “Crassaw wrthyt y gennyf i,” heb ef. Ac yna medylyaw a wnaeth, bot yn diuwyn ganthaw pryt a welsei o uorwyn eiroet, a gwreic, y wrth y ffryt hi. “Arglwydes,” heb ef, “a dywedy di ymi dim o'th negesseu?” “Dywedaf, y rof a Duw,” heb hi. “Pennaf neges uu ymi, keissaw dy welet ti.” “Llyna,” heb y Pwyll, “y neges oreu gennyf i dy dyuot ti idi. Ac a dywedy di ymi pwy wyt?” “Dywedaf, Arglwyd,” heb hi. “Riannon, uerch Heueyd Hen, wyf i, a'm rodi y wr o'm hanwod yd ydys. Ac ny mynneis innheu un gwr, a hynny o'th garyat ti. Ac nys mynnaf etwa, onyt ti a'm gwrthyt. Ac e wybot dy attep di am hynny e deuthum i.”",
          e: "Then Pwyll spoke. “Maiden,” he said, “for the sake of the man you most love, wait for me.” “I shall wait gladly,” said she, “and it had been better for the horse if you had asked me long ago.” She halted, and waited, and drew aside the part of her headdress that should have been over her face, and fixed her gaze upon him, and began to converse with him. “Lady,” he said, “where are you coming from, and at what pace are you riding?” “I am riding on my errands,” she said, “and I am glad to see you.” “You are welcome to me,” he said. And then he thought that beside her face, the fairest face he had ever seen of any maiden or any woman was without beauty. “Lady,” said he, “will you tell me anything of your errands?” “I will, between me and God,” said she. “The chief errand of mine was to seek to see you.” “That,” said Pwyll, “is the best errand to me that you have come to. And will you tell me who you are?” “I will, Lord,” said she. “Rhiannon, daughter of Hyfaidd Hen, am I; and I am being given to a man against my will. I have wanted no man, and that for love of you. And I will not have him yet, unless you reject me. And to know your answer to that, I have come.”",
          n: "The asking. Rhiannon's enchantment is broken not by chase but by request — and her first reply names it: <em>it had been better for the horse, if you had asked me long ago.</em> She has been waiting for him to ask, three days running. The naming is precise: Rhiannon, daughter of Hyfaidd Hen (\"Hyfaidd the Old,\" an Otherworldly father whose court will host the wedding feast). The reveal is doubled: a maiden riding past unsought turns out to have ridden out specifically for him, in love with him already, and being given against her will to another man." },

        { w: "“Rof i a Duw,” heb ynteu Pwyll, “llyna uy attep i iti, pei caffwn dewis ar holl wraged a morynnyon y byt, y mae ti a dewisswn.” “Ie,” heb hitheu, “os hynny a uynny, kyn uy rodi y wr arall, gwna oed a mi.” “Goreu yw gennyf i,” heb y Pwyll, “bo kyntaf; ac yn y lle y mynnych ti, gwna yr oet.” “Gwnaf, Arglwyd,” heb hi, “blwydyn y heno, yn llys Heueyd, mi a baraf bot gwled darparedic yn barawt erbyn dy dyuot.” “Yn llawen,” heb ynteu, “a mi a uydaf yn yr oet hwnnw.” “Arglwyd,” heb hi, “tric yn iach, a choffa gywiraw dy edewit, ac e ymdeith yd af i.” A guahanu a wnaethont, a chyrchu a wnaeth ef parth a'e teulu a'e niuer. Pa ymouyn bynnac a uei ganthunt wy y wrth y uorwyn, y chwedleu ereill y trossei ynteu.",
          e: "“Between me and God,” said Pwyll, “here is my answer to you. If I had a choice of all the women and maidens of the world, you are the one I would choose.” “Well,” said she, “if that is what you want, before I am given to another man, make a meeting with me.” “The sooner the better, by me,” said Pwyll. “And at whatever place you wish, make the meeting.” “I shall, Lord,” said she. “A year from tonight, at the court of Hyfaidd, I shall arrange for a feast to be prepared and ready against your coming.” “Gladly,” said he, “and I shall be at that meeting.” “Lord,” said she, “farewell, and remember to fulfill your promise; and away I go.” And they parted, and he made for his retinue and his company. Whatever they would ask him about the maiden, he turned aside to other tales.",
          n: "The bargain. The Welsh formula is the same as Arawn's in Movement I — <em>blwydyn y heno</em>, \"a year from tonight,\" and an appointed meeting at a named place. Pwyll, who is Penn Annwfn by Arawn's bargain, is bound now by a second blwydyn-bargain — this time with the woman who came riding out of Annwn-coloured iconography to find him. The First Branch's structural symmetry deepens: two year-long bargains, each turning on a single appointed meeting. Movement IV will open at the year's end, at the court of Hyfaidd Hen, where the wedding feast is set — and where, at the doors, a stranger will arrive with the same kind of rash-promise demand the Fairy King will use four hundred years later in Sir Orfeo." },
      ],
    },

    {
      title: "IV. The wedding feast, the rash promise, and the badger in the bag",
      segments: [
        { w: "Odyna treulaw y ulwydyn hyt yr amser a wnaethont; ac ymgueiraw [o Pwyll] ar y ganuet marchauc. Ef a aeth ryngtaw a llys Eueyd Hen, ac ef a doeth y'r llys, a llawen uuwyt wrthaw, a dygyuor a llewenyd ac arlwy mawr a oed yn y erbyn, a holl uaranned y llys wrth y gynghor ef y treulwyt. Kyweiryaw y neuad a wnaethpwyt, ac y'r bordeu yd aethant. Sef ual yd eistedyssont, Heueyd Hen ar neill law Pwyll, a Riannon o'r parth arall idaw; y am hynny pawb ual y bei y enryded. Bwyta a chyuedach ac ymdidan a wnaethont.",
          e: "From there they spent the year until the appointed time. And Pwyll arrayed himself with his hundred horsemen, and went between him and the court of Hyfaidd Hen, and came to the court, and was joyfully received — a great gathering of joy and a great provision were before him, and all the household stores of the court were spent at his direction. The hall was made ready, and they went to the tables. They sat thus: Hyfaidd Hen on one side of Pwyll, and Rhiannon on the other; beyond them, each man according to his rank. They ate and drank and conversed.",
          n: "The wedding feast assembled. Hyfaidd Hen — \"Hyfaidd the Old,\" the Otherworldly father whose name marks him as a figure from beyond ordinary genealogy — receives Pwyll Penn Annwfn formally. Rhiannon's seating beside Pwyll is the public sign that the bargain made on the Gorsedd is being honoured. The Welsh wedding-feast tradition is precise: hours of seating, conversation, drinking, before the moment that will redirect the whole story." },

        { w: "Ac ar dechreu kyuedach gwedy bwyt, wynt a welynt yn dyuot y mywn, guas gwineu, mawr, teyrneid, a guisc o bali amdanaw. A phan doeth y gynted y neuad, kyuarch guell a oruc y Pwyll a'y gedymdeithon. “Cressaw Duw wrthyt, eneit, a dos y eisted,” heb y Pwyll. “Nac af,” heb ef, “eirchat wyf, a'm neges a wnaf.” “Gwna yn llawen,” heb y Pwyll. “Arglwyd,” heb ef, “wrthyt ti y mae uy neges i, ac y erchi it y dodwyf.” “Pa arch bynnac a erchych di ymi, hyt y gallwyf y gaffael, itti y byd.”",
          e: "And at the start of the after-meal drinking, they saw coming in a young man, auburn-haired, tall, royally bearing, in a robe of silk. And when he came to the foot of the hall, he greeted Pwyll and his companions. “God's welcome upon you, friend, and come to sit,” said Pwyll. “I shall not,” said he. “I am a suppliant, and my errand I shall do.” “Do it gladly,” said Pwyll. “Lord,” said he, “my errand is with you, and to ask of you have I come.” “Whatever request you shall ask of me, as far as I can grant it, you shall have.”",
          n: "The rash promise. The stranger — described as <em>teyrneid</em>, \"royally bearing\" — refuses the seat and stands as a suppliant, the formal posture for a request. He asks only that Pwyll grant before naming what is asked; Pwyll grants. This is M223 in its purest Insular form, and Pwyll has just walked into the same trap Arthur walks into in Gawain's first Fitt — granting the terms unread. Welsh and English imaginations both run on the same architecture: the bargain a king cannot refuse without dishonour, made before the bargain itself is even known." },

        { w: "“Och!” heb y Riannon, “paham y rody di attep yuelly?” “Neus rodes y uelly, Arglwydes, yg gwyd gwyrda,” heb ef. “Eneit,” heb y Pwyll, “beth yw dy arch di?” “Y wreic uwyaf a garaf yd wyt yn kyscu heno genthi. Ac y herchi hi a'r arlwy a'r darmerth yssyd ymma y dodwyf i.” Kynhewi a oruc Pwyll, cany bu attep a rodassei.",
          e: "“Alas,” said Rhiannon, “why did you give that answer?” “He gave it thus, Lady, in front of nobles,” said the stranger. “Friend,” said Pwyll, “what is your request?” “The woman I most love, you are sleeping with tonight. To ask for her and the preparation and the feast that is here, have I come.” Pwyll fell silent, because of the answer he had given.",
          n: "Rhiannon's alarm comes too late — the promise has been bound by witnesses (<em>yg gwyd gwyrda</em>, \"in the presence of nobles\"). The stranger names what Pwyll has just given away: the bride, the wedding-feast, the whole evening. The Welsh prose is brutal in its economy. Pwyll falls silent — the same silent freezing Gawain falls into when the Green Knight catches up his own head and rides out. The rash promise has bound the king, and the bound king cannot speak." },

        { w: "“Taw, hyt y mynnych,” heb y Riannon, “ny bu uuscrellach gwr ar y ssynnwyr e hun nog ry uuost ti.” “Arglwydes,” heb ef, “ny wydwn i pwy oed ef.” “Llyna y gwr y mynyssit uy rodi i idaw o'm hanuod,” heb hi, “Guawl uab Clut, gwr tormyn nawc, kyuoethawc. A chan derw yt dywedut y geir a dywedeist, dyro ui idaw rac anglot yt.” “Arglwydes,” heb ef, “ny wnn i pa ryw attep yw hwnnw. Ny allaf ui arnaf a dywedy di uyth.” “Dyro di ui idaw ef,” heb hi, “a mi a wnaf na chaffo ef uiui uyth.”",
          e: "“Be silent, as long as you wish,” said Rhiannon, “no man was ever more foolish in his own wits than you have been.” “Lady,” said he, “I did not know who he was.” “There is the man,” said she, “to whom they wished to give me against my will — Gwawl son of Clud, a man of standing and power. And since you have given the word you have given, give me to him, lest you be dishonoured.” “Lady,” said he, “I do not know what kind of answer that is. I cannot ever bring myself to do what you say.” “Give me to him,” said she, “and I shall arrange that he never has me.”",
          n: "The naming. <em>Gwawl uab Clut</em> — Gwawl son of Clud, a name meaning roughly \"Light\" or \"Brilliance.\" (Welsh scholarship has long suspected a euhemerised Brythonic deity, an opposite-number to Pwyll-as-Annwn-king.) Rhiannon names him, names her unwilling betrothal, and shifts the moral burden onto Pwyll's broken promise: <em>give me to him, lest you be dishonoured.</em> The bargain is now to be honoured outwardly while reversed inwardly — and Rhiannon, who has already arranged the unspeakable enchantment of the chase, will arrange the unspeakable enchantment of the bag." },

        { w: "“Pa furyf uyd hynny?” heb y Pwyll. “Mi a rodaf i'th law got uechan,” heb hi, “a chadw honno gennyt yn da. Ac ef a eirch y wled a'r arlwy a'r darmerth. Ac nit oes y'th uedyant di hynny. A mi ui a rodaf y wled y'r teulu a'r niueroed,” heb hi, “a hwnnw uyd dy attep am hynny. Amdanaf innheu,” heb hi, “mi a wnaf oet ac ef, ulwydyn y heno, y gyscu gennyf; ac ym penn y ulwydyn,” heb hi, “byd ditheu a'r got honn genhyt, ar dy ganuet marchawc yn y perllan uchot. A phan uo ef ar perued y digrifwch a'y gyuedach dyret titheu dy hun ymywn a dillat reudus amdanat, a'r got y'th law,” heb hi, “ac nac arch dim namyn lloneit y got o uwyt. Minheu,” heb hi, “a baraf, bei dottit yssyd yn y seith cantref hynn o uwyt a llynn yndi, na bydei launach no chynt. A guedy byryer llawer yndi, ef a ouyn yt, ‘A uyd llawn dy got ti uyth?’ Dywet titheu, ‘Na uyd, ony chyuyt dylyedauc tra chyuoethauc, a guascu a'y deudroet y bwyt yn y got, a dywedut, “Digawn rydodet ymman.”’ A minheu a baraf idaw ef uynet y sseghi y bwyt yn y got. A phan el ef, tro ditheu y got, yny el ef dros y pen yn y got. Ac yna llad glwm ar garryeu y got. A bit corn canu da am dy uynwgyl, a phan uo ef yn rwymedic yn y got, dot titheu lef ar dy gorn, a bit hynny yn arwyd y rot a'th uarchogyon; pan glywhont llef dy gorn, diskynnent wynteu am ben y llys.”",
          e: "“In what manner?” said Pwyll. “I shall give into your hand a small bag,” said she, “and keep that well by you. And he will ask for the feast and the preparation and the provision. But those are not in your power. I shall give the feast to the household and the companies,” said she, “and that shall be your answer to him for that. As for myself,” said she, “I shall make an appointment with him a year from tonight, to sleep with me. And at the year's end,” said she, “be you with that bag, with your hundred horsemen in the orchard above. And when he is in the midst of his merriment and his drinking, come you in alone, with poor clothes upon you, and the bag in your hand,” said she, “and ask nothing but the bag's full of food. And I shall arrange that even if all the food and drink that are in these seven cantrefs were put in it, it would be no fuller than before. And when much has been put in, he will ask you, ‘Will your bag ever be full?’ Say you, ‘No, unless a nobleman, very wealthy, rises up and presses with his two feet on the food in the bag, and says, “Enough has been put here.”’ And I shall arrange that he will go to press the food in the bag. And when he goes in, turn the bag, until he goes over his head into it. And then tie a knot on the strings of the bag. And let a good horn be around your neck; and when he is bound in the bag, you give a sound on your horn — and let that be the signal between you and your horsemen. When they hear the sound of your horn, let them descend upon the court.”",
          n: "The whole counter-plot in one breath. Rhiannon, who has been the silent rider, the unrecognised princess, the woman given against her will, becomes here the architect of the entire trick. The unfillable bag, the rash-promise echo (Pwyll plays the same trap on Gwawl that Gwawl played on him), the device of the noble's feet, the horn-signal — all of it Rhiannon's invention. The Welsh hero gets the title-page; the Welsh heroine writes the plot. For the cross-tale layer, this is K500 (death evaded by trick) braided with K1700 (bluff) and a new variant of K1810 — disguise as instrument, not as concealment." },

        { w: "“Arglwyd,” heb y Guawl, “madws oed ymi cael attep am a ercheis.” “Kymeint ac a ercheist,” heb y Pwyll, “o'r a uo y'm medyant i, ti a'y keffy.” “Eneit,” heb hitheu Riannon, “am y wled a'r darpar yssyd yma, hwnnw a rodeis i y wyr Dyuet a y'r teulu, a'r yniueroed yssyd ymma. Hwnnw nit eidawaf y rodi y neb. Blwydyn y heno ynteu, y byd gwled darparedic yn y llys honn i titheu, eneit, y gyscu gennyf innheu.”",
          e: "“Lord,” said Gwawl, “it is time that I had an answer for what I asked.” “As much as you asked,” said Pwyll, “as much as is in my power, you shall have.” “Friend,” said Rhiannon, “as for the feast and the preparation that is here — that I have given to the men of Dyfed and to the household and the companies that are here. That is not mine to give to anyone. A year from tonight, in this hall, there shall be a feast prepared for you, friend, to sleep with me.”",
          n: "Rhiannon's public reply is exact. The feast is given to its proper guests (technically true: the food has been distributed). Her own person is put off to a year-from-tonight wedding feast in the same hall. The Welsh rhetorical move — outwardly honour the promise, redirect the terms, name the year — converts Gwawl's rash demand into a one-year delay. Gwawl, evidently believing he has won, accepts and leaves." },

        { w: "Gwawl a gerdawd ryngthaw a'y gyuoeth. Pwyll ynteu a doeth y Dyuet. A'r ulwydyn honno a dreulwys pawb o honunt hyt oet y wled a oed yn llys Eueyd Hen. Gwaul uab Clut a doeth parth a'r wled a oed darparedic idaw, a chyrchu y llys a wnaeth, a llawen uuwyt wrthaw. Pwyll ynteu Penn Annwn a doeth y'r berllan ar y ganuet marchauc, ual y gorchymynnassei Riannon idaw, a'r got ganthaw. Gwiscaw bratteu trwm ymdan[a]w a oruc Pwyll, a chymryt lloppaneu mawr am y draet. A phan wybu y bot ar dechreu kyuedach wedy bwyta, dyuot racdaw y'r neuad.",
          e: "Gwawl went on to his realm. Pwyll for his part came to Dyfed. And that year was spent by every one of them until the appointment of the feast that was at the court of Hyfaidd Hen. Gwawl son of Clud came to the feast that was prepared for him, and made for the court, and was joyfully received. Pwyll Penn Annwfn for his part came to the orchard with his hundred horsemen, as Rhiannon had directed him, with the bag with him. He put heavy old rags upon himself, and large coverings on his feet. And when he knew it was the start of the after-meal drinking, he came forward into the hall.",
          n: "K1810 disguise — the same role-slot Sir Orfeo's beggar's clothes will fill four centuries later. The hero crosses the threshold by looking like nothing the antagonist would notice. The horsemen wait outside; the king walks in alone in heavy rags and oversized foot-coverings. The fairy-tale pacing is exact: the moment chosen — <em>the start of the after-meal drinking</em> — is when the hall is loosest and the host most expansive." },

        { w: "A guedy y dyuot y gynted y neuad kyuarch guell a wnaeth y Wawl uab Clut a'y gedymdeithon o wyr a gwraged. “Duw a ro da yt,” heb y Gwawl, “a chraessaw Duw wrthyt.” “Arglwyd,” heb ynteu, “Duw a dalo yt. Negessawl wyf wrthyt.” “Craessaw wrth dy neges,” heb ef. “Ac os arch gyuartal a erchy ymi, yn llawen ti a'e keffy.” “Kyuartal, Arglwyd,” heb ynteu, “nyt archaf onyt rac eisseu. Sef arch a archaf, lloneit y got uechan a wely di o uwyt.” “Arch didraha yw honno,” heb ef, “a thi a'y keffy yn llawen. Dygwch uwyt idaw,” heb ef. Riuedi mawr o sswydwyr a gyuodassant y uynyd, a dechreu llenwi y got. Ac yr a uyrit yndi ny bydei lawnach no chynt.",
          e: "And when he came to the foot of the hall, he greeted Gwawl son of Clud and his companions of men and women. “May God do you good,” said Gwawl, “and may God welcome you.” “Lord,” said he, “may God repay you. I have come to you with an errand.” “Welcome to your errand,” said he. “And if it is a reasonable request you ask of me, gladly you shall have it.” “Reasonable, Lord,” said he. “I do not ask except out of need. The request I ask is: enough food to fill this small bag you see.” “That is a modest request,” said he, “and you shall have it gladly. Bring him food,” said he. A great number of officials rose up and began to fill the bag. And however much was thrown into it, it was no fuller than before.",
          n: "Gwawl, asked for a small thing, grants gladly — the same gracious posture Pwyll took a year ago. He cannot know that the gracious posture is what Rhiannon has been counting on. The unfillable bag drains the court of provision while remaining empty. The mathematics of the magic is the point: the more thrown in, the more nothing happens." },

        { w: "“Eneit,” heb y Guawl, “a uyd llawn dy got ti uyth?” “Na uyd, y rof a Duw,” heb ef, “yr a dotter yndi uyth, ony chyuyt dylyedauc tir a dayar a chyuoeth, a ssenghi a'y deudroet y bwyt yn y got a dywedut, ‘Digawn ry dodet yma.’” “A geimat,” heb y Riannon, “kyuot y uynyd ar uyrr,” wrth Gwawl vab Clut. “Kyuodaf yn llawen,” heb ef. A chyuodi y uynyd, a dodi y deudroet yn y got, a troi o Pwyll y got yny uyd Guawl dros y penn yn y got ac yn gyflym caeu y got, a llad clwm ar y carryeu, a dodi llef ar y gorn. Ac ar hynny, llyma y teulu am penn y llys, ac yna kymryt pawb o'r niuer a doeth y gyt a Guawl, a'y dodi yn y carchar e hun. A bwrw y bratteu a'r loppaneu a'r yspeil didestyl y amdanaw a oruc Pwyll.",
          e: "“Friend,” said Gwawl, “will your bag ever be full?” “It will not, between me and God,” said he, “no matter how much is put in, unless a nobleman with land and earth and wealth rises and treads with both his feet on the food in the bag, and says, ‘Enough has been put here.’” “Heroic one,” said Rhiannon, to Gwawl son of Clud, “rise up quickly.” “I rise gladly,” said he. And he rose, and placed both his feet in the bag — and Pwyll turned the bag, until Gwawl was over his head in the bag, and quickly closed the bag, and tied a knot on the strings, and gave a sound on the horn. And with that — see! — the household around the court; and they took each man of the company that had come with Gwawl, and put him in Gwawl's own prison. And Pwyll cast off the rags and the leg-coverings and the wretched mantle from himself.",
          n: "<em>A geimat</em> — Rhiannon's tender word to Gwawl, \"heroic one,\" names him with the very dignity she will trap him with. Her plot uses the rash-promise architecture against the architect — Gwawl had used Pwyll's open hand to claim the bride; Pwyll, prompted by Rhiannon, uses Gwawl's open hand to claim him. The horn-signal closes the trap. Pwyll's rags come off; the disguise has done its work; he stands in his own form at last." },

        { w: "Ac mal y delei pob un o'e niuer ynteu y mywn, y trawei pob un dyrnawt ar y got, ac y gouynnei, “Beth yssyd ymma?” “Broch,” medynt wynteu. Sef kyfryw chware a wneynt, taraw a wnai pob un dyrnawt ar y got, ae a'e droet ae a throssawl; ac yuelly guare a'r got a wnaethont. Pawb, ual y delei, a ouynnei, “Pa chware a wnewch chwi uelly?” “Guare broch yg got,” medynt wynteu. Ac yna gyntaf y guarywyt broch yg got.",
          e: "And as each one of his men came in, each struck a blow on the bag, and asked, “What's in here?” “A badger,” they said. The sort of game they were playing was this: each struck a blow on the bag, either with a foot or with a club; and so they played with the bag. Each as he came asked, “What kind of game are you playing this way?” “Badger in the bag,” they said. And that was the first time that <em>badger in the bag</em> was played.",
          n: "A1654 — origin of a game. <em>Guare broch yg got</em>, \"the badger-in-the-bag game,\" is named here for the first time. Folklorists have evidence that the game (a bagged opponent beaten with feet and clubs) was actually played in medieval Welsh courts at festivals; the tale provides its origin-story. Compare A1450 (origin of a lay) at Sir Orfeo's close, and A1654 in Gawain's closing adoption of the green sash as Round Table livery. Each Insular tale closes a frame by naming its real-world afterlife — a poem, a sash, a game." },

        { w: "“Arglwyd,” heb y gwr o'r got, “pei guarandawut uiui, nyt oed dihenyd arnaf uy llad y mywn got.” “Arglwyd,” heb Eueyd Hen, “guir a dyweit. Iawn yw yt y warandaw; nyt dihenyt arnaw hynny.” “Ie,” heb y Pwyll, “mi a wnaf dy gynghor di amdanaw ef.” “Llyna dy gynghor di,” heb Riannon yna. “Yd wyt yn y lle y perthyn arnat llonydu eircheit a cherdoryon. Gat yno ef y rodi drossot y pawb,” heb hi, “a chymer gedernit y ganthaw na bo ammouyn na dial uyth amdanaw, a digawn yw hynny o gosp arnaw.” “Ef a geif hynny yn llawen,” heb y gwr o'r got. “A minheu a'e kymmeraf yn llawen,” heb y Pwyll, “gan gynghor Heueyd a Riannon.” “Kynghor yw hynny gynnym ni,” heb wynt. “Y gymryt a wnaf,” heb y Pwyll. “Keis ueicheu drossot.” “Ni a uydwn drostaw,” heb Heueyd, “yny uo ryd y wyr y uynet drostaw.” Ac ar hynny y gollyngwyt ef o'r got ac y rydhawyt y oreugwyr. “Gouyn ueithon y Wawl weicheu,” heb yr Heueyd. “Ni a adwaenwn y neb a dylyer y kymryt y ganthaw.” Riuaw y meicheu a wnaeth Heueyd. “Llunnya dy hunn,” heb y Guawl, “dy ammot.” “Digawn yw gennyf i,” heb y Pwyll, “ual y llunnyawd Riannon.” Y meicheu a aeth ar yr ammot hwnnw. “Ie, Arglwyd,” heb y Guawl, “briwedic wyf i, a chymriw mawr a geueis, ac ennein yssyd reit ymi, ac y ymdeith yd af i, gan dy gannyat ti. A mi a adawaf wyrda drossof yma, y attep y pawb o'r a'th ouynno di.” “Yn llawen,” heb y Pwyll, “a gwna ditheu hynny.” Guawl a aeth parth a'y gyuoeth.",
          e: "“Lord,” said the man in the bag, “if you would listen to me, it is no proper death for me to be killed inside a bag.” “Lord,” said Hyfaidd Hen, “he speaks truly. It is right that you should listen to him; it is no proper death for him.” “Right,” said Pwyll, “I shall take your counsel about him.” “Here is your counsel,” said Rhiannon then. “You are in the position where it is yours to satisfy bards and minstrels. Let him there give to each on your behalf,” said she, “and take a guarantee from him that there shall be no claim or vengeance for this ever; and that is sufficient punishment upon him.” “He shall have that gladly,” said the man in the bag. “And I shall accept it gladly,” said Pwyll, “by the counsel of Hyfaidd and Rhiannon.” “That is the counsel from us,” they said. “I accept it,” said Pwyll. “Find sureties for yourself.” “We shall stand surety for him,” said Hyfaidd, “until his men are free to go in his stead.” And with that he was released from the bag, and his chief men were freed. “Ask Gwawl now for sureties,” said Hyfaidd. “We know who should be taken from him.” Hyfaidd named the sureties. “Frame the covenant yourself,” said Gwawl. “Sufficient by me,” said Pwyll, “as Rhiannon framed it.” The sureties went on that covenant. “Right, Lord,” said Gwawl, “I am wounded, and I have got great injuries, and I need bathing, and away I shall go with your permission. And I shall leave my nobles here in my stead, to answer to all who would ask of you.” “Gladly,” said Pwyll, “and do that.” Gwawl went to his own realm.",
          n: "The settlement. Rhiannon's counsel — Pwyll uses his standard Welsh king-role of <em>satisfying bards</em> on Gwawl's behalf, takes pledges against vengeance — is the Welsh court's preferred mode: legal architecture instead of execution. The badger-in-the-bag is humiliation, not killing. Gwawl, the offended brilliance-king, is sent home wounded, with his men left as guarantors. Structurally the inverse of Hafgan's death-at-the-ford in Movement II: Pwyll-as-Arawn killed cleanly with the one blow; Pwyll-as-himself spares with the legal pledge. Two kingdoms, two contracts, two endings." },

        { w: "Y neuad ynteu a gyweirwyt y Pwyll a'e niuer, ac yniuer y llys y am hynny. Ac y'r bordeu yd aethont y eisted, ac ual yd eistedyssant ulwydyn o'r nos honno, yd eistedwys paub y nos [honno]. Bwyta a chyuedach a wnaethont, ac amser a doeth y uynet y gyscu. Ac y'r ystauell yd aeth Pwyll a Riannon, a threulaw y nos honno drwy digriuwch a llonydwch. A thrannoeth, yn ieuengtit y dyd, “Arglwyd,” heb Riannon, “kyuot y uynyd, a dechreu lonydu y kerdoryon, ac na ommed neb hediw, o'r a uynno da.” “Hynny a wnaf i, yn llawen,” heb y Pwyll, “a hediw a pheunyd tra parhao y wled honn.” Ef a gyuodes Pwyll y uynyd, a pheri dodi gostec, y erchi y holl eircheit a cherdoryon dangos, a menegi udunt y llonydit pawb o honunt wrth y uod a'y uympwy; a hynny a wnaethpwyd. Y wled honno a dreulwyt, ac ny ommedwyt neb tra barhaud. A phan daruu y wled, “Arglwyd,” heb y Pwyll wrth Heueyd, “mi a gychwynnaf, gan dy gannyat, parth a Dyuet auore.” “Ie,” heb Heueyd, “Duw a rwydhao ragot; a gwna oet a chyfnot y del Riannon i'th ol.” “Y rof i a Duw,” heb ynteu Pwyll, “y gyt y kerdwn odymma.” “Ay uelly y mynny di, Arglwyd?” heb yr Heueyd. “Uelly, y rof a Duw,” heb y Pwyll.",
          e: "The hall was made ready for Pwyll and his retinue, and the household of the court besides. And they went to the tables to sit; and as they had sat a year before that night, each sat that night. They ate and drank, and the time came to go to sleep. And Pwyll and Rhiannon went to the chamber, and spent the night in delight and stillness. And on the morrow, in the youth of the day, “Lord,” said Rhiannon, “rise up, and begin to satisfy the minstrels, and refuse no one today, of those who would have a gift.” “I shall do that gladly,” said Pwyll, “today and every day so long as this feast lasts.” Pwyll rose, ordered silence, called all suppliants and minstrels to present themselves, and announced that each should be satisfied according to his will and his wish; and that was done. The feast was spent, and no one was refused while it lasted. And when the feast was over, “Lord,” said Pwyll to Hyfaidd, “I shall set out, with your permission, for Dyfed tomorrow.” “Right,” said Hyfaidd, “God speed you. And make an appointment and a time when Rhiannon shall come after you.” “Between me and God,” said Pwyll, “from here we shall go together.” “Is that what you want, Lord?” said Hyfaidd. “It is, between me and God,” said Pwyll.",
          n: "The wedding night and the going home. Pwyll's last act at Hyfaidd Hen's court is the standard Welsh king-act — satisfying the bards. Hyfaidd assumes the customary delay (the bride comes later, in her own train); Pwyll refuses it. <em>From here we shall go together.</em> Rhiannon, who has been promised against her will, who has ridden out three times to find him, who has plotted the deliverance — is, at last, going with him on her own terms. Movement V opens at Arberth, two prosperous years, then the political pressure for an heir." },
      ],
    },

    {
      title: "V. The birth of Pryderi, the disappearance, and Rhiannon's penance",
      segments: [
        { w: "Wynt a gerdassant trannoeth parth a Dyuet, a Llys Arberth a gyrchyssant, a gwled darparedic oed yno udunt. Dygyuor y wlat a'r kyuoeth a doeth attunt o'r gwyr goreu a'r gwraged goreu. Na gwr na gwreic o hynny nyt edewis Riannon, heb rodi rod enwauc idaw, ae o gae, ae o uodrwy, ae o uaen guerthuawr. Gwledychu y wlat a wnaethont yn llwydannus y ulwydyn honno, a'r eil.",
          e: "They set out on the morrow toward Dyfed, and made for the court of Arberth, and a feast was prepared for them there. The country and the realm gathered to them, of the best men and the best women. No man and no woman of these did Rhiannon let depart without giving a notable gift — either a brooch, or a ring, or a precious stone. They ruled the country prosperously that year, and the second.",
          n: "Two prosperous years at Arberth. Rhiannon, who has been seen riding past unsought, refused, traded, betrayed, plotted against and rescued, is here for the first time at her own court, giving gifts to every man and woman of the realm. Her name — proto-Celtic <em>Rīgantonā</em>, \"Great Queen\" — finally fits the public position. The two prosperous years sit between the badger-in-the-bag and the disaster the third year will bring." },

        { w: "Ac yn [y] dryded ulwydyn, y dechreuis gwyr y wlat dala trymuryt yndunt, o welet gwr kymeint a gerynt a'e harglwyd ac eu brawduaeth, yn dietiued; a'e dyuynnu attunt a wnaethont. Sef lle y doethont y gyt, y Bresseleu yn Dyuet. “Arglwyd,” heb wynt, “ni a wdom na bydy gyuoet ti a rei o wyr y wlat honn, ac yn ouyn ni yw, na byd it etiued o'r wreic yssyd gennyt. Ac wrth hynny, kymmer wreic arall y bo ettiued yt ohonei. Nyt byth,” heb wynt, “y perhey di, a chyt kerych di uot yuelly, nys diodefwn y gennyt.” “Ie,” heb y Pwyll, “nyt hir ettwa yd ym y gyt, a llawer damwein a digawn bot. Oedwch a mi hynn hyt ym pen y ulwydyn; a blwydyn y'r amser hwnn, ni a wnawn yr oet y dyuot y gyt, ac wrth ych kynghor y bydaf.”",
          e: "In the third year, the men of the country began to be heavy of heart, seeing a man as great as the one they loved as their lord and their brother-by-marriage, without an heir. And they summoned him. The place where they came together was Preseli in Dyfed. “Lord,” they said, “we know you are not the same age as some of the men of this country, and our fear is that there will be no heir to you from the wife who is with you. Therefore take another wife, that you may have an heir from her. Not forever,” they said, “shall you continue thus; and even were it your will to continue thus, we should not suffer it from you.” “Right,” said Pwyll, “not long yet are we together, and many a chance may happen. Wait with me about this until the end of the year; and a year from now, we shall make an appointment to come together, and I shall abide by your counsel.”",
          n: "The political pressure for an heir. The nobles meet at <em>Preseli</em> — the Preseli Hills in north Pembrokeshire, the same range from which the Stonehenge bluestones were quarried in deep prehistory, and a real Welsh political assembly-place. They press Pwyll to set Rhiannon aside for a fertile wife. He answers with the Insular delay-formula already used twice in this tale (Movement I's <em>blwydyn y heno</em>; Movement IV's year-from-tonight wedding-bargain): wait a year. A third blwydyn-bargain enters the First Branch's architecture, this time as the desperate stay of execution." },

        { w: "Yr oet a wnaethant. Kynn dyuot cwbyl o'r oet, mab a anet idaw ef, ac yn Arberth y ganet. A'r nos y ganet, y ducpwyt gwraged y wylat y mab a'y uam. Sef a wnaeth y gwraged kyscu, a mam y mab, Riannon. Sef riuedi o wraged a ducpwyt y'r ystauell hwech wraged. Gwylat a wnaethont wynteu dalym o'r nos, ac yn hynny eisswys, kyn hanner noss, kyscu a wnaeth pawb ohonunt, a thu a'r pylgeint deffroi. A phan deffroyssant, edrych a orugant y lle y dodyssynt y mab, ac nyt oed dim ohonaw yno.",
          e: "The appointment was made. Before the full coming of the appointment, a son was born to him — and at Arberth he was born. And the night he was born, women were brought to watch the boy and his mother. The women fell to sleeping, and the boy's mother also, Rhiannon. The number of women brought to the chamber was six. They watched a portion of the night; but in that, before midnight, every one of them slept; and toward dawn they woke. And when they woke, they looked to the place where they had laid the boy — and there was nothing of him there.",
          n: "The disappearance — silent, total, at midnight, with no struggle. Six women set to guard mother and child fall asleep; the boy is taken without a sound. The Welsh prose gives no agent, no description of <em>what</em> took him; the disappearance is set down as a fact. Folklorists hear the great Insular cluster F320 — fairies abduct mortals — in the silence around the midnight cradle. The pattern is precise: a mortal child taken at the threshold-hour, by an unseen power, leaving only the empty place where he had lain. For the cross-tale layer this is closely cognate with Sir Orfeo's F255.2 (fairies take at noon), except the Welsh threshold-hour is midnight; same architecture, opposite end of the day." },

        { w: "“Och!” heb vn o'r gwraged, “neur golles y mab.” “Ie,” heb arall, “bychan a dial oed yn lloski ni, neu yn dienydyaw am y mab.” “A oes,” heb un o'r guraged, “kynghor o'r byt am hynn?” “Oes,” heb arall, “mi a wnn gynghor da,” heb hi. “Beth yw hynny?” heb wy. “Gellast yssyd yma,” heb hi, “a chanawon genti. Lladwn rei o'r canawon, ac irwn y hwyneb hitheu Riannon a'r gwaet, a'y dwylaw, a byrwn yr eskyrn gyr y bron, a thaerwn arnei e hun diuetha y mab. Ac ni byd yn taered ni an chwech wrthi hi e hun.” Ac ar y kynghor hwnnw y trigwyt.",
          e: "“Alas!” said one of the women, “the boy is lost.” “Right,” said another, “a small revenge it would be to burn us, or to put us to death for the boy.” “Is there,” said one of the women, “any counsel in the world for this?” “There is,” said another, “I know good counsel,” said she. “What is that?” they said. “There is a bitch in here,” said she, “with whelps. Let us kill some of the whelps, and let us smear her face — Rhiannon's — with the blood, and her hands; and let us throw the bones before her, and accuse her, herself, of destroying the boy. And the assertion of the six of us against her alone shall not fail.” And on that counsel they stayed.",
          n: "The lie. The six women, fearing the king's vengeance, build a fiction out of what is to hand: a litter of puppies in the room. The deliberation is appallingly practical — the puppies killed, the blood smeared, the bones scattered, the testimony rehearsed. Welsh tradition is unflinching about the moral economy: six small lives sacrificed to cover the great loss; six women's voices framed against one. The poem will spend the rest of the Movement watching the lie hold." },

        { w: "Parth a'r dyd Riannon a deffroes, ac a dywot, “A wraged,” heb hi, “mae y mab?” “Arglwydes,” heb wy, “na ouyn di yni y mab. Nyt oes ohonam ni namyn cleisseu a dyrnodeu yn ymdaraw a thi; a diamheu yw gennym na welsam eiroet uilwraeth yn un wreic kymeint ac ynot ti. Ac ny thygyawd ynni ymdaraw a thi. Neur diffetheeist du hun dy uab, ac na hawl ef ynni.” “A druein,” heb y Riannon, “yr yr Arglwyd Duw a wyr pob peth, na yrrwch geu arnaf. Duw, a wyr pob peth, a wyr bot yn eu hynny arnaf i. Ac os ouyn yssyd arnawchi, ym kyffes y Duw, mi a'ch differaf.” “Dioer,” heb wy, “ny adwn ni drwc arnam ny hunein yr dyn yn y byt.” “A druein,” heb hitheu, “ny chewch un drwc yr dywedut y wirioned.” Yr a dywettei hi yn dec ac yn druan, ny chaffei namyn yr un atteb gan y gwraged.",
          e: "Toward the day, Rhiannon woke, and said, “Women, where is the boy?” “Lady,” they said, “do not ask of us for the boy. There is nothing of us but bruises and blows from struggling with you; and certain it is to us that we never saw bravery in any one woman as great as in you. And it did not avail us to struggle with you. You yourself have destroyed your boy; do not claim him from us.” “Oh wretches,” said Rhiannon, “for the love of the Lord God who knows all things, do not put false witness on me. God, who knows all things, knows that this is false upon me. And if fear is upon you — by my confession to God, I shall defend you.” “Truly,” they said, “we shall not let evil come upon ourselves for the sake of any human in the world.” “Oh wretches,” she said, “you shall not have any evil for telling the truth.” Although she spoke gently and pitifully, she got nothing but the same answer from the women.",
          n: "Rhiannon, who out-rode every pursuer on the Gorsedd, who out-plotted Gwawl with the unfillable bag, here meets the one form of opposition she cannot work past — six women's coordinated false witness. She offers protection in exchange for truth (<em>by my confession to God, I shall defend you</em>); they refuse. The Welsh prose grants her two appeals, gentle and pitiful, and then names the wall: <em>she got nothing but the same answer.</em> The lie is now lawful in the world." },

        { w: "Pwyll Penn Annwn ar hynny a gyuodes, a'r teulu a'r yniueroed, a chelu y damwein hwnnw ny allwyt. Y'r wlat yd aeth y chwedyl, a phawb o'r guyrda a'e kigleu. A'r guyrda a doethant y gyt y wneuthur kynnadeu at Pwyll, y erchi idaw yscar a'e wreic, am gyflauan mor anwedus ac ar y wnaethoed. Sef attep a rodes Pwyll, “Nyt oed achaws ganthunt wy y erchi y mi yscar a'm gwreic namyn na bydei plant idi. Plant a wnn i y uot idi hi. Ac nyt yscaraf a hi. O gwnaeth hitheu gam, kymeret y phenyt amdanaw.”",
          e: "Pwyll Penn Annwn at that arose, and the household and the companies, and the matter could not be concealed. The tale went to the country, and every one of the nobles heard it. And the nobles came together to make appointments with Pwyll, to ask him to separate from his wife, for a deed so unworthy as she had done. This was the answer Pwyll gave: “There was no cause for them to ask me to separate from my wife except that there should be no children to her. Children I know there to be to her. And I shall not separate from her. If she has done wrong, let her take her penance for it.”",
          n: "Pwyll's answer is the moral pivot of the whole Movement. The same nobles who pressured him to set Rhiannon aside for childlessness now press him to set her aside for child-murder. He refuses both. The logic is exact: <em>children I know there to be to her</em> — the lack the nobles cited as cause is gone, and the new accusation does not unmake the fact. The Welsh king who chastely held the queen of Annwn in Movement II, who took his wife with him from her father's hall in Movement IV, here holds her against a fully-formed lie. The marriage is a stronger covenant than the rule of evidence in the court." },

        { w: "Hitheu Riannon a dyuynnwys attei athrawon a doethon. A gwedy bot yn degach genthi kymryt y phenyt nog ymdaeru a'r gwraged, y phenyt a gymerth. Sef penyt a dodet erni, bot yn y llys honno yn Arberth hyt ym penn y seith mlyned. Ac yskynuaen a oed odieithyr y porth, eisted gyr llaw hwnnw beunyd, a dywedut y pawb a delei o'r a debygei nas gwyppei, y gyffranc oll, ac o'r a attei idi y dwyn, kynnic y westei a phellynic y dwyn ar y cheuyn y'r llys. A damwein y gadei yr un y dwyn. Ac yuelly treulaw talym o'r ulwydyn a wnaeth.",
          e: "And Rhiannon summoned to her teachers and wise men. And after it had seemed fairer to her to take her penance than to keep on disputing with the women, she took her penance. The penance set upon her: to remain in that court at Arberth until the end of seven years. And a mounting-block was outside the gate; to sit beside it every day, and to tell every visitor who came (any she thought might not know) the whole story; and to those who would let her, to offer the guest and the stranger to be carried on her back to the court. And rarely did anyone let her carry them. And thus she spent a portion of the year.",
          n: "Rhiannon takes the penance — at the gate, on the mounting-block, for seven years, as the horse. The Welsh tradition's most uncanny single act of public shaming: the queen whose iconography is the great pale-white horse made into a horse at her own gate. <em>Rarely did anyone let her carry them</em> — the public's silent verdict on the lie, in spite of which her formal humiliation continues. The poet quietly notes that she chose the penance over dispute, <em>after it had seemed fairer to her</em>: the act is her own. Movement VI opens in another part of the kingdom, at the court of Teirnon Twryf Liant, where the stolen foal will provide its own recognition-token." },
      ],
    },
  ],
};
