/* Pwyll Pendefig Dyfed — the First Branch of the Mabinogi. The English
   shown alongside the Welsh is an original translation written movement
   by movement in subsequent passes. The Welsh is a Middle Welsh reading
   text from the Welsh Wikisource (CC BY-SA 4.0), descending from the
   manuscripts (White Book of Rhydderch, c. 1350; Red Book of Hergest,
   c. 1382–1410). The same manuscript tradition also gives us Culhwch ac
   Olwen, whose reading text on this site is taken from the public-domain
   edition of Rhys & Evans (Oxford, 1887).

   The full source is preserved at source/pwyll-wikisource.txt.
   Attaches to window.PWYLL. */
window.PWYLL = window.PWYLL || {};
window.PWYLL.tale = {
  meta: {
    blurb: "<strong>Pwyll Pendefig Dyfed</strong> — the First Branch of the Mabinogi, the foundational Welsh prose tale (manuscripts c. 1350–1410, oral tradition older). A pre-Arthurian tale of <em>exchanges</em>: Pwyll trades places with Arawn lord of Annwn for a year; Pwyll meets Rhiannon on the Gorsedd mound and outwits her promised bridegroom Gwawl; their son Pryderi is mysteriously taken, Rhiannon is falsely punished as the horse at the gate, and the child is recovered. Below is <strong>Movement I</strong> (the hunt at Glyn Cuch, the meeting with Arawn lord of Annwn, the proposal of the year-exchange). The English is an <strong>original translation</strong>. The Middle Welsh beside it is a <em>reading text</em> from the Welsh Wikisource (CC BY-SA 4.0), preserved in the medieval orthography (medieval <em>u</em> for modern <em>f / v</em>; <em>oed</em> for modern <em>oedd</em>; <em>Dyuet</em> for modern <em>Dyfed</em>). The full source is preserved verbatim at <a href=\"source/pwyll-wikisource.txt\">source/pwyll-wikisource.txt</a>.",
    sources: [
      { label: "Pwyll Pendeuic Dyuet — Welsh Wikisource", url: "https://cy.wikisource.org/wiki/Pwyll_Pendeuic_Dyuet", host: "cy.wikisource" },
      { label: "The Text of the Mabinogion — Rhys & Evans, 1887 (Oxford, public domain)", url: "https://archive.org/details/textofmabinogion00rhysiala", host: "Internet Archive" },
      { label: "The Mabinogion — Lady Charlotte Guest, 1838–45 (public domain English translation)", url: "https://www.gutenberg.org/ebooks/5160", host: "Project Gutenberg" },
      { label: "Pwyll Pendefig Dyfed — overview", url: "https://en.wikipedia.org/wiki/Pwyll_Pendefig_Dyfed", host: "Wikipedia" },
    ],
  },
  roadmap: [
    { t: "Source text in hand", done: true },
    { t: "I · Pwyll meets Arawn lord of Annwn in Glyn Cuch", done: true },
    { t: "II · A year as the king of Annwn; the duel with Hafgan", done: false },
    { t: "III · Rhiannon on the Gorsedd mound", done: false },
    { t: "IV · The wedding feast and the badger in the bag", done: false },
    { t: "V · The birth of Pryderi, his disappearance, Rhiannon's punishment", done: false },
    { t: "VI · Teyrnon's discovery, the recognition, the reconciliation", done: false },
  ],
  passages: [
    {
      title: "I. The hunt at Glyn Cuch, and the meeting with Arawn lord of Annwn",
      segments: [
        { w: "Pwyll Pendeuic Dyuet a oed yn arglwyd ar seith cantref Dyuet. A threigylgweith yd oed yn Arberth, prif lys idaw, a dyuot yn y uryt ac yn y uedwl uynet y hela. Sef kyueir o'y gyuoeth a uynnei y hela, Glynn Cuch. Ac ef a gychwynnwys y nos honno o Arberth, ac a doeth hyt ym Penn Llwyn Diarwya, ac yno y bu y nos honno. A thrannoeth yn ieuengtit y dyd kyuodi a oruc, a dyuot y Lynn Cuch i ellwng e gwn dan y coet. A chanu y gorn a dechreu dygyuor yr hela, a cherdet yn ol y cwn, ac ymgolli a'y gydymdeithon. Ac ual y byd yn ymwarandaw a llef yr erchwys, ef a glywei llef erchwys arall, ac nit oedynt unllef, a hynny yn dyuot yn erbyn y erchwys ef. Ac ef a welei lannerch yn y coet o uaes guastat; ac ual yd oed y erchwys ef yn ymgael ac ystlys y llannerch, ef a welei carw o ulaen yr erchwys arall. A pharth a pherued y llannerch, llyma yr erchwys a oed yn y ol yn ymordiwes ac ef, ac yn y uwrw y'r llawr.",
          e: "Pwyll, Prince of Dyfed, was lord over the seven cantref of Dyfed. And one time he was at Arberth, his chief court, when it came into his mind and heart to go hunting. The quarter of his realm he wished to hunt was Glyn Cuch. And he set out that night from Arberth, and came as far as Penn Llwyn Diarwya, and stayed the night there. And on the morrow, in the youth of the day, he rose and came to Glyn Cuch to loose his hounds beneath the wood. He sounded his horn and began the rousing of the hunt, and rode after the hounds, and lost his companions. And while he was listening to the cry of his pack, he heard the cry of another pack — and they were not of one voice, and that other pack was coming toward his own. He saw a glade in the wood of even ground; and as his pack was reaching the edge of the glade, he saw a stag in front of the other pack. And toward the middle of the glade — see! — that strange pack closing on the stag and bearing it to the ground.",
          n: "The opening establishes the kingdom: the <em>seith cantref Dyuet</em>, the seven cantref of Dyfed, the southwest of Wales — a unit of medieval land-administration meaning \"a hundred dwellings\" times seven, the kingdom of Dyfed entire. Arberth is the principal court (modern Narberth in Pembrokeshire). Glyn Cuch is a real valley on the Dyfed–Carmarthen border. Pwyll loses his companions in the hunt — Welsh narrative often opens by stripping the hero down to himself before the encounter that matters." },

        { w: "Ac yna edrych ohonaw ef ar liw yr erchwys, heb hanbwyllaw edrych ar y carw. Ac o'r a welsei ef o helgwn y byt, ny welsei cwn un lliw ac wynt. Sef lliw oed arnunt, claerwyn llathreit, ac eu clusteu yn gochyon. Ac ual y llathrei wynnet y cwn, y llathrei cochet y clusteu. Ac ar hynny at y cwn y doeth ef, a gyrru yr erchwys a ladyssei y carw e ymdeith, a llithyaw y erchwys e hunan ar y carw.",
          e: "And then he looked at the colour of the strange pack, and gave no further thought to the stag. Of all the hunting-hounds he had ever seen in the world, he had seen none of their colour. The colour they wore: a shining brilliant white, and their ears were red. And as the white of the dogs shone bright, so the red of the ears shone bright. And with that he came up to the hounds, drove off the pack that had killed the stag, and set his own pack on the carcass.",
          n: "The <em>cŵn Annwn</em> — the hounds of Annwn — shining white with red ears. The single most famous Otherworld iconography in all Welsh tradition; the folkloric \"spectral hounds\" run from this passage right through to Conan Doyle's <em>Hound of the Baskervilles</em>. Pwyll's act — <em>driving off the pack and setting his own on the kill</em> — is the breach that opens the entire tale. He does not even know it is a breach. Arawn does." },

        { w: "Ac ual y byd yn llithiau y cwn, ef a welei uarchauc yn dyuot yn ol yr erchwys y ar uarch erchlas mawr; a chorn canu am y uynwgyl, a gwisc o urethyn llwyt tei amdanaw yn wisc hela. Ac ar hynny y marchawc a doeth attaw ef, a dywedut ual hynn wrthaw, “A unben,” heb ef, “mi a wnn pwy wyt ti, ac ny chyuarchaf i well it.”",
          e: "And as he was feeding the dogs, he saw a horseman coming after the pack — on a great pale-grey horse, with a hunting-horn around his neck, dressed in a hunting-garb of grey-brown wool. And the horseman came up to him and spoke to him thus: “Lord,” he said, “I know who you are, and I will give you no greeting.”",
          n: "The Otherworld king arrives in the Otherworld's colour-grammar: grey-brown wool, a great pale-grey horse. He withholds <em>cyfarch</em> — the formal Welsh greeting — and names the breach in his first sentence: <em>I know who you are.</em> The encounter is staged as a courtesy-trial." },

        { w: "“Ie,” heb ef, “ac atuyd y mae arnat o anryded ual nas dylyei.” “Dioer,” heb ef, “nyt teilygdawt uy anryded a'm etteil am hynny.” “A unben,” heb ynteu, “beth amgen?” “Y rof i a Duw,” hep ynteu, “dy anwybot dy hun a'th ansyberwyt.” “Pa ansyberwyt, unben, a weleist ti arnaf i?” “Ny weleis ansyberwyt uwy ar wr,” hep ef, “no gyrru yr erchwys a ladyssei y carw e ymdeith, a llithiau dy erchwys dy hun arnaw; hynny,” hep ef, “ansyberwyt oed: a chyn nyt ymdialwyf a thi, y rof i a Duw,” hep ef, “mi a wnaf o anglot itt guerth can carw.”",
          e: "“Well,” said Pwyll, “perhaps the rank you carry is such that it owes me no greeting from you.” “Truly,” said the other, “it is not the worth of my rank that holds me back from that.” “Lord,” said Pwyll, “what then?” “Between me and God,” said the other, “your own ignorance, and your discourtesy.” “What discourtesy, lord, have you seen on me?” “I never saw greater discourtesy in a man,” said he, “than to drive off the pack that had killed the stag, and to set your own pack on the kill. That,” said he, “was discourtesy. And though I shall not avenge myself on you, between me and God,” said he, “I shall get from you a hundred stags' worth of dishonour.”",
          n: "The opening misreading is one of the most economical character-establishments in Welsh literature. Pwyll assumes the stranger is too low-born to greet him; the stranger turns the table by naming the breach Pwyll did not even notice. Welsh <em>ansyberwyt</em> — discourtesy, unworth — is the tale's central concept; the whole driving force of the First Branch is the repair of it." },

        { w: "“A unbenn,” hep ef, “o gwneuthum gam, mi a brynaf dy gerennyd.” “Pa delw,” hep ynteu, “y pryny di?” “Vrth ual y bo dy anryded, ac ny wnn i pwy wyt ti.” “Brenhin corunawc wyf i yn y wlat yd hanwyf oheni.” “Arglwyd,” heb ynteu, “dyd da itt; a pha wlat yd hanwyt titheu oheni?” “O Annwuyn,” heb ynteu. “Arawn urenhin Annwuyn wyf i.”",
          e: "“Lord,” said Pwyll, “if I have done wrong, I shall buy your friendship.” “In what manner,” said the other, “will you buy it?” “According to the measure of your rank — and I do not know who you are.” “I am a crowned king in the land I come from.” “Lord,” said Pwyll, “good day to you. And what land are you of?” “Of Annwn,” said he. “Arawn, king of Annwn, am I.”",
          n: "The naming. <em>Arawn Urenhin Annwuyn</em> — Arawn, King of Annwn — emerges as one of the great Otherworld kings of Welsh tradition. He is <em>brenhin corunawc</em>, a crowned king, the precise dignity of Pwyll himself: the year-exchange that follows is a fair trade only because both parties wear the same crown." },

        { w: "“Arglwyd,” heb ynteu, “pa furyf y caf i dy gerennyd di?” “Llyma wyd y kyffy,” heb ynteu. “Gwr yssyd gyuerbyn y gyuoeth a'm kyuoeth inheu yn ryuelu arnaf yn wastat. Sef yw hwnnw, Hafgan urenhin o Annwuyn. Ac yr guaret gormes hwnnw y arnaf (a hynny a elly yn haut) y keffy uy gherennyd.” “Minnheu a wnaf hynny,” heb ynteu, “yn llawen. A manac ditheu y mi pa furyf y gallwyf hynny.”",
          e: "“Lord,” said Pwyll, “in what manner shall I gain your friendship?” “Here is how,” said he. “There is a man whose realm marches with mine, and he is at war with me without rest. That man is Hafgan, king from Annwn. To free me of this oppression — and you may do that easily — you shall have my friendship.” “I shall do that gladly,” said Pwyll. “Tell me only how I may.”",
          n: "A second king \"of Annwn\" — <em>Hafgan</em>, a name meaning roughly <em>summer-bright</em> or <em>summer-white</em>, evidently an opposite number to Arawn. The Otherworld in Welsh tradition is not monolithic: two crowned kings, two contending kingdoms, perpetual war. <em>Gormes</em> — oppression — is the same word used elsewhere in the Mabinogi for the Three Oppressions of Britain." },

        { w: "“Managaf,” heb ynteu. “Llyna ual y gelly; mi a wnaf a thi gedymdeithas gadarn. Sef ual y gwnaf, mi a'th rodaf di y'm lle i yn Annwuyn, ac a rodaf y wreic deccaf a weleist eiroet y gyscu gyt a thi beunoeth, a'm pryt innheu a'm ansawd arnat ti, hyt na bo na guas ystauell, na swydawc, na dyn arall o'r a'm canlynwys i yroet, a wyppo na bo miui uych ti. A hynny,” heb ef, “hyt ym penn y ulwydyn o'r dyd auory. An kynnadyl yna yn y lle hon.”",
          e: "“I shall tell you,” said Arawn. “Here is how you may. I shall make a strong companionship with you. This is what I shall do: I shall put you in my place in Annwn, and I shall give you the fairest woman you ever saw to sleep at your side every night; and my form and my likeness shall be upon you, so that there shall be neither chamber-servant nor officer nor any of all those who have ever followed me, who shall know that you are not I. And that,” said he, “until the end of a year from tomorrow — our meeting again here in this place.”",
          n: "The year-exchange. Note what the bargain includes and what it implies: full impersonation (<em>pryt</em> and <em>ansawd</em> — form and likeness — laid on Pwyll); the queen as nightly bedfellow; no one to know. The bargain is morally extreme and proposed casually, with the wife included as if she were the bedroom furniture. Movement II will watch what Pwyll does with the night-by-night opportunity that has been put in his hand." },

        { w: "“Ie,” heb ynteu, “kyt bwyf i yno hyt ympenn y ulwydyn, pa gyuarwyd a uyd ymi o ymgael a'r gwr a dywedy di?” “Blwydyn,” heb ef, “y heno, y mae oet y rof i ac ef, ar y ryt. A byd di i'm rith yno,” heb ef, “ac un dyrnaut a rodych di idaw ef; ny byd byw ef o hwnnw. A chyt archo ef yti rodi yr eil, na dyro, yr a ymbilio a thi. Yr a rodwn i idau ef hagen, kystal a chynt yd ymladei a mi drannoeth.”",
          e: "“Well,” said Pwyll, “if I am to be there until the year's end, how shall I know how to meet the man you speak of?” “A year from tonight,” said Arawn, “is my appointment with him, at the ford. Be in my likeness there,” he said, “and one stroke you shall give him — he shall not live from it. And though he ask you to give him the second stroke, do not give it, however he plead with you. For though I have given him a second, on the morrow he would fight as well as he had before.”",
          n: "The duel's rule. <em>One stroke only.</em> The poem's rash-promise constraint is a one-stroke constraint — and it is precisely the inverse of the bargain in Sir Gawain, where the single blow received <em>must</em> be returned. Two opposite weightings of the same M223 architecture: in Gawain, the one blow must come back; in Pwyll, the one blow must not be repeated. The medieval Insular imagination loves these single-blow contracts." },

        { w: "“Ie,” heb y Pwyll, “beth a wnaf i y'm kyuoeth?” “Mi a baraf,” hep yr Arawn, “na bo i'th gyuoeth na gwr na gwreic a wyppo na bo tidi wwyf i. A miui a af i'th le di.” “Yn llawenn,” hep y Pwyll, “a miui a af ragof.” “Dilesteir uyd dy hynt ac ny russya dim ragot, yny delych y'm kyuoeth i: a mi a uydaf hebryngyat arnat.”",
          e: "“Well,” said Pwyll, “and what shall be done in my own realm?” “I shall arrange,” said Arawn, “that in your realm neither man nor woman shall know that I am not you. And I shall go in your place.” “Right gladly,” said Pwyll. “And I shall go forth.” “Your way shall be unhindered, and nothing shall thwart you, until you come into my realm; and I shall be your guide there.”",
          n: "The double exchange sealed. <em>And I shall go in your place</em> — Arawn will rule Dyfed for the year. The whole structural symmetry of the First Branch is now in place: two kings in each other's realms, each other's wars, each other's beds. The Welsh tradition's most elegant test of trust, proposed on a single hunt by a single offended courtesy. Movement II opens at the boundary." },
      ],
    },
  ],
};
