/* Pwyll Pendefig Dyfed — the First Branch of the Mabinogi. The English
   shown alongside the Welsh is an original translation written movement
   by movement in subsequent passes. The Welsh is a Middle Welsh reading
   text from the Welsh Wikisource (CC BY-SA 4.0), descending from the
   manuscripts (White Book of Rhydderch, c. 1350; Red Book of Hergest,
   c. 1382–1410). The same manuscript tradition also gives us Culhwch ac
   Olwen, whose reading text on this site is taken from the public-domain
   edition of Rhys & Evans (Oxford, 1887).

   The full source is preserved at source/pwyll-wikisource.txt.
   Attaches to window.PWYLL. */
window.PWYLL = window.PWYLL || {};
window.PWYLL.tale = {
  meta: {
    blurb: "<strong>Pwyll Pendefig Dyfed</strong> — the First Branch of the Mabinogi, the foundational Welsh prose tale (manuscripts c. 1350–1410, oral tradition older). A pre-Arthurian tale of <em>exchanges</em>: Pwyll trades places with Arawn lord of Annwn for a year; Pwyll meets Rhiannon on the Gorsedd mound and outwits her promised bridegroom Gwawl; their son Pryderi is mysteriously taken, Rhiannon is falsely punished as the horse at the gate, and the child is recovered. Below are <strong>Movements I &amp; II</strong> (the hunt at Glyn Cuch and the meeting with Arawn; the year in Annwn, the duel at the ford, the chaste sleep beside the queen, and the renaming as <em>Pwyll Penn Annwfn</em>). The English is an <strong>original translation</strong>. The Middle Welsh beside it is a <em>reading text</em> from the Welsh Wikisource (CC BY-SA 4.0), preserved in the medieval orthography (medieval <em>u</em> for modern <em>f / v</em>; <em>oed</em> for modern <em>oedd</em>; <em>Dyuet</em> for modern <em>Dyfed</em>). The full source is preserved verbatim at <a href=\"source/pwyll-wikisource.txt\">source/pwyll-wikisource.txt</a>.",
    sources: [
      { label: "Pwyll Pendeuic Dyuet — Welsh Wikisource", url: "https://cy.wikisource.org/wiki/Pwyll_Pendeuic_Dyuet", host: "cy.wikisource" },
      { label: "The Text of the Mabinogion — Rhys & Evans, 1887 (Oxford, public domain)", url: "https://archive.org/details/textofmabinogion00rhysiala", host: "Internet Archive" },
      { label: "The Mabinogion — Lady Charlotte Guest, 1838–45 (public domain English translation)", url: "https://www.gutenberg.org/ebooks/5160", host: "Project Gutenberg" },
      { label: "Pwyll Pendefig Dyfed — overview", url: "https://en.wikipedia.org/wiki/Pwyll_Pendefig_Dyfed", host: "Wikipedia" },
    ],
  },
  roadmap: [
    { t: "Source text in hand", done: true },
    { t: "I · Pwyll meets Arawn lord of Annwn in Glyn Cuch", done: true },
    { t: "II · A year as the king of Annwn; the duel with Hafgan", done: true },
    { t: "III · Rhiannon on the Gorsedd mound", done: false },
    { t: "IV · The wedding feast and the badger in the bag", done: false },
    { t: "V · The birth of Pryderi, his disappearance, Rhiannon's punishment", done: false },
    { t: "VI · Teyrnon's discovery, the recognition, the reconciliation", done: false },
  ],
  passages: [
    {
      title: "I. The hunt at Glyn Cuch, and the meeting with Arawn lord of Annwn",
      segments: [
        { w: "Pwyll Pendeuic Dyuet a oed yn arglwyd ar seith cantref Dyuet. A threigylgweith yd oed yn Arberth, prif lys idaw, a dyuot yn y uryt ac yn y uedwl uynet y hela. Sef kyueir o'y gyuoeth a uynnei y hela, Glynn Cuch. Ac ef a gychwynnwys y nos honno o Arberth, ac a doeth hyt ym Penn Llwyn Diarwya, ac yno y bu y nos honno. A thrannoeth yn ieuengtit y dyd kyuodi a oruc, a dyuot y Lynn Cuch i ellwng e gwn dan y coet. A chanu y gorn a dechreu dygyuor yr hela, a cherdet yn ol y cwn, ac ymgolli a'y gydymdeithon. Ac ual y byd yn ymwarandaw a llef yr erchwys, ef a glywei llef erchwys arall, ac nit oedynt unllef, a hynny yn dyuot yn erbyn y erchwys ef. Ac ef a welei lannerch yn y coet o uaes guastat; ac ual yd oed y erchwys ef yn ymgael ac ystlys y llannerch, ef a welei carw o ulaen yr erchwys arall. A pharth a pherued y llannerch, llyma yr erchwys a oed yn y ol yn ymordiwes ac ef, ac yn y uwrw y'r llawr.",
          e: "Pwyll, Prince of Dyfed, was lord over the seven cantref of Dyfed. And one time he was at Arberth, his chief court, when it came into his mind and heart to go hunting. The quarter of his realm he wished to hunt was Glyn Cuch. And he set out that night from Arberth, and came as far as Penn Llwyn Diarwya, and stayed the night there. And on the morrow, in the youth of the day, he rose and came to Glyn Cuch to loose his hounds beneath the wood. He sounded his horn and began the rousing of the hunt, and rode after the hounds, and lost his companions. And while he was listening to the cry of his pack, he heard the cry of another pack — and they were not of one voice, and that other pack was coming toward his own. He saw a glade in the wood of even ground; and as his pack was reaching the edge of the glade, he saw a stag in front of the other pack. And toward the middle of the glade — see! — that strange pack closing on the stag and bearing it to the ground.",
          n: "The opening establishes the kingdom: the <em>seith cantref Dyuet</em>, the seven cantref of Dyfed, the southwest of Wales — a unit of medieval land-administration meaning \"a hundred dwellings\" times seven, the kingdom of Dyfed entire. Arberth is the principal court (modern Narberth in Pembrokeshire). Glyn Cuch is a real valley on the Dyfed–Carmarthen border. Pwyll loses his companions in the hunt — Welsh narrative often opens by stripping the hero down to himself before the encounter that matters." },

        { w: "Ac yna edrych ohonaw ef ar liw yr erchwys, heb hanbwyllaw edrych ar y carw. Ac o'r a welsei ef o helgwn y byt, ny welsei cwn un lliw ac wynt. Sef lliw oed arnunt, claerwyn llathreit, ac eu clusteu yn gochyon. Ac ual y llathrei wynnet y cwn, y llathrei cochet y clusteu. Ac ar hynny at y cwn y doeth ef, a gyrru yr erchwys a ladyssei y carw e ymdeith, a llithyaw y erchwys e hunan ar y carw.",
          e: "And then he looked at the colour of the strange pack, and gave no further thought to the stag. Of all the hunting-hounds he had ever seen in the world, he had seen none of their colour. The colour they wore: a shining brilliant white, and their ears were red. And as the white of the dogs shone bright, so the red of the ears shone bright. And with that he came up to the hounds, drove off the pack that had killed the stag, and set his own pack on the carcass.",
          n: "The <em>cŵn Annwn</em> — the hounds of Annwn — shining white with red ears. The single most famous Otherworld iconography in all Welsh tradition; the folkloric \"spectral hounds\" run from this passage right through to Conan Doyle's <em>Hound of the Baskervilles</em>. Pwyll's act — <em>driving off the pack and setting his own on the kill</em> — is the breach that opens the entire tale. He does not even know it is a breach. Arawn does." },

        { w: "Ac ual y byd yn llithiau y cwn, ef a welei uarchauc yn dyuot yn ol yr erchwys y ar uarch erchlas mawr; a chorn canu am y uynwgyl, a gwisc o urethyn llwyt tei amdanaw yn wisc hela. Ac ar hynny y marchawc a doeth attaw ef, a dywedut ual hynn wrthaw, “A unben,” heb ef, “mi a wnn pwy wyt ti, ac ny chyuarchaf i well it.”",
          e: "And as he was feeding the dogs, he saw a horseman coming after the pack — on a great pale-grey horse, with a hunting-horn around his neck, dressed in a hunting-garb of grey-brown wool. And the horseman came up to him and spoke to him thus: “Lord,” he said, “I know who you are, and I will give you no greeting.”",
          n: "The Otherworld king arrives in the Otherworld's colour-grammar: grey-brown wool, a great pale-grey horse. He withholds <em>cyfarch</em> — the formal Welsh greeting — and names the breach in his first sentence: <em>I know who you are.</em> The encounter is staged as a courtesy-trial." },

        { w: "“Ie,” heb ef, “ac atuyd y mae arnat o anryded ual nas dylyei.” “Dioer,” heb ef, “nyt teilygdawt uy anryded a'm etteil am hynny.” “A unben,” heb ynteu, “beth amgen?” “Y rof i a Duw,” hep ynteu, “dy anwybot dy hun a'th ansyberwyt.” “Pa ansyberwyt, unben, a weleist ti arnaf i?” “Ny weleis ansyberwyt uwy ar wr,” hep ef, “no gyrru yr erchwys a ladyssei y carw e ymdeith, a llithiau dy erchwys dy hun arnaw; hynny,” hep ef, “ansyberwyt oed: a chyn nyt ymdialwyf a thi, y rof i a Duw,” hep ef, “mi a wnaf o anglot itt guerth can carw.”",
          e: "“Well,” said Pwyll, “perhaps the rank you carry is such that it owes me no greeting from you.” “Truly,” said the other, “it is not the worth of my rank that holds me back from that.” “Lord,” said Pwyll, “what then?” “Between me and God,” said the other, “your own ignorance, and your discourtesy.” “What discourtesy, lord, have you seen on me?” “I never saw greater discourtesy in a man,” said he, “than to drive off the pack that had killed the stag, and to set your own pack on the kill. That,” said he, “was discourtesy. And though I shall not avenge myself on you, between me and God,” said he, “I shall get from you a hundred stags' worth of dishonour.”",
          n: "The opening misreading is one of the most economical character-establishments in Welsh literature. Pwyll assumes the stranger is too low-born to greet him; the stranger turns the table by naming the breach Pwyll did not even notice. Welsh <em>ansyberwyt</em> — discourtesy, unworth — is the tale's central concept; the whole driving force of the First Branch is the repair of it." },

        { w: "“A unbenn,” hep ef, “o gwneuthum gam, mi a brynaf dy gerennyd.” “Pa delw,” hep ynteu, “y pryny di?” “Vrth ual y bo dy anryded, ac ny wnn i pwy wyt ti.” “Brenhin corunawc wyf i yn y wlat yd hanwyf oheni.” “Arglwyd,” heb ynteu, “dyd da itt; a pha wlat yd hanwyt titheu oheni?” “O Annwuyn,” heb ynteu. “Arawn urenhin Annwuyn wyf i.”",
          e: "“Lord,” said Pwyll, “if I have done wrong, I shall buy your friendship.” “In what manner,” said the other, “will you buy it?” “According to the measure of your rank — and I do not know who you are.” “I am a crowned king in the land I come from.” “Lord,” said Pwyll, “good day to you. And what land are you of?” “Of Annwn,” said he. “Arawn, king of Annwn, am I.”",
          n: "The naming. <em>Arawn Urenhin Annwuyn</em> — Arawn, King of Annwn — emerges as one of the great Otherworld kings of Welsh tradition. He is <em>brenhin corunawc</em>, a crowned king, the precise dignity of Pwyll himself: the year-exchange that follows is a fair trade only because both parties wear the same crown." },

        { w: "“Arglwyd,” heb ynteu, “pa furyf y caf i dy gerennyd di?” “Llyma wyd y kyffy,” heb ynteu. “Gwr yssyd gyuerbyn y gyuoeth a'm kyuoeth inheu yn ryuelu arnaf yn wastat. Sef yw hwnnw, Hafgan urenhin o Annwuyn. Ac yr guaret gormes hwnnw y arnaf (a hynny a elly yn haut) y keffy uy gherennyd.” “Minnheu a wnaf hynny,” heb ynteu, “yn llawen. A manac ditheu y mi pa furyf y gallwyf hynny.”",
          e: "“Lord,” said Pwyll, “in what manner shall I gain your friendship?” “Here is how,” said he. “There is a man whose realm marches with mine, and he is at war with me without rest. That man is Hafgan, king from Annwn. To free me of this oppression — and you may do that easily — you shall have my friendship.” “I shall do that gladly,” said Pwyll. “Tell me only how I may.”",
          n: "A second king \"of Annwn\" — <em>Hafgan</em>, a name meaning roughly <em>summer-bright</em> or <em>summer-white</em>, evidently an opposite number to Arawn. The Otherworld in Welsh tradition is not monolithic: two crowned kings, two contending kingdoms, perpetual war. <em>Gormes</em> — oppression — is the same word used elsewhere in the Mabinogi for the Three Oppressions of Britain." },

        { w: "“Managaf,” heb ynteu. “Llyna ual y gelly; mi a wnaf a thi gedymdeithas gadarn. Sef ual y gwnaf, mi a'th rodaf di y'm lle i yn Annwuyn, ac a rodaf y wreic deccaf a weleist eiroet y gyscu gyt a thi beunoeth, a'm pryt innheu a'm ansawd arnat ti, hyt na bo na guas ystauell, na swydawc, na dyn arall o'r a'm canlynwys i yroet, a wyppo na bo miui uych ti. A hynny,” heb ef, “hyt ym penn y ulwydyn o'r dyd auory. An kynnadyl yna yn y lle hon.”",
          e: "“I shall tell you,” said Arawn. “Here is how you may. I shall make a strong companionship with you. This is what I shall do: I shall put you in my place in Annwn, and I shall give you the fairest woman you ever saw to sleep at your side every night; and my form and my likeness shall be upon you, so that there shall be neither chamber-servant nor officer nor any of all those who have ever followed me, who shall know that you are not I. And that,” said he, “until the end of a year from tomorrow — our meeting again here in this place.”",
          n: "The year-exchange. Note what the bargain includes and what it implies: full impersonation (<em>pryt</em> and <em>ansawd</em> — form and likeness — laid on Pwyll); the queen as nightly bedfellow; no one to know. The bargain is morally extreme and proposed casually, with the wife included as if she were the bedroom furniture. Movement II will watch what Pwyll does with the night-by-night opportunity that has been put in his hand." },

        { w: "“Ie,” heb ynteu, “kyt bwyf i yno hyt ympenn y ulwydyn, pa gyuarwyd a uyd ymi o ymgael a'r gwr a dywedy di?” “Blwydyn,” heb ef, “y heno, y mae oet y rof i ac ef, ar y ryt. A byd di i'm rith yno,” heb ef, “ac un dyrnaut a rodych di idaw ef; ny byd byw ef o hwnnw. A chyt archo ef yti rodi yr eil, na dyro, yr a ymbilio a thi. Yr a rodwn i idau ef hagen, kystal a chynt yd ymladei a mi drannoeth.”",
          e: "“Well,” said Pwyll, “if I am to be there until the year's end, how shall I know how to meet the man you speak of?” “A year from tonight,” said Arawn, “is my appointment with him, at the ford. Be in my likeness there,” he said, “and one stroke you shall give him — he shall not live from it. And though he ask you to give him the second stroke, do not give it, however he plead with you. For though I have given him a second, on the morrow he would fight as well as he had before.”",
          n: "The duel's rule. <em>One stroke only.</em> The poem's rash-promise constraint is a one-stroke constraint — and it is precisely the inverse of the bargain in Sir Gawain, where the single blow received <em>must</em> be returned. Two opposite weightings of the same M223 architecture: in Gawain, the one blow must come back; in Pwyll, the one blow must not be repeated. The medieval Insular imagination loves these single-blow contracts." },

        { w: "“Ie,” heb y Pwyll, “beth a wnaf i y'm kyuoeth?” “Mi a baraf,” hep yr Arawn, “na bo i'th gyuoeth na gwr na gwreic a wyppo na bo tidi wwyf i. A miui a af i'th le di.” “Yn llawenn,” hep y Pwyll, “a miui a af ragof.” “Dilesteir uyd dy hynt ac ny russya dim ragot, yny delych y'm kyuoeth i: a mi a uydaf hebryngyat arnat.”",
          e: "“Well,” said Pwyll, “and what shall be done in my own realm?” “I shall arrange,” said Arawn, “that in your realm neither man nor woman shall know that I am not you. And I shall go in your place.” “Right gladly,” said Pwyll. “And I shall go forth.” “Your way shall be unhindered, and nothing shall thwart you, until you come into my realm; and I shall be your guide there.”",
          n: "The double exchange sealed. <em>And I shall go in your place</em> — Arawn will rule Dyfed for the year. The whole structural symmetry of the First Branch is now in place: two kings in each other's realms, each other's wars, each other's beds. The Welsh tradition's most elegant test of trust, proposed on a single hunt by a single offended courtesy. Movement II opens at the boundary." },
      ],
    },

    {
      title: "II. A year as the king of Annwn, the duel at the ford, the chaste sleep, the renaming",
      segments: [
        { w: "Ef a'y hebryghaud yny welas y llys a'r kyuanned. “Llyna,” hep ef, “y llys a'r kyuoeth i'th uedyant. A chyrch y llys. Nit oes yndi nep ni'th adnappo; ac wrth ual y guelych y guassanaeth yndi, yd adnabydy uoes y llys.” Kyrchu y llys a oruc ynteu. Ac yn y llys ef a welei hundyeu ac yneuadeu, ac ysteuyll, a'r ardurn teccaf a welsei neb o adeiladeu. Ac y'r neuad y gyrchwys y diarchenu. Ef a doeth makwyueit a gueisson ieueinc y diarchenu, a phaup ual y delynt kyuarch guell a wneynt idaw. Deu uarchauc a doeth i waret i wisc hela y amdanaw, ac y wiscaw eurwisc o bali amdanaw.",
          e: "He led him until he saw the court and the dwellings. “There,” he said, “is the court and the realm in your power. Make for the court. There is no one in it who will not know you; and from what you see of the service in it, you will learn the custom of the court.” Pwyll made for the court. And in the court he saw sleeping-chambers and halls and rooms, and the fairest furnishings of any building he had ever seen. He went into the great hall to be unshod. Squires and young pages came to unshoe him, and each as he came up gave him greeting. Two knights came to remove his hunting-garb and to dress him in a court-robe of gold-shot silk.",
          n: "The Annwn court — built in Welsh tradition on the same architectural scale as a king's hall, only finer. No precious-stone walls, no levitating stones, no ever-light: just the best of what a Welsh palace could be. The Otherworld here is not a different reality, only a finer one — distinctively Insular, distinctively Welsh, set against the crystal-and-jewel iconography that the English Sir Orfeo will inherit four hundred years later." },

        { w: "A'r neuad a gyweirwyt. Llyma y guelei ef teulu ac yniueroed, a'r niuer hardaf a chyweiraf o'r a welsei neb yn dyuot y mywn, a'r urenhines y gyt ac wynt, yn deccaf gwreic o'r a welsei neb, ac eurwisc amdanei o bali llathreit. Ac ar hynny, e ymolchi yd aethant, a chyrchu y bordeu a orugant, ac eisted a wnaethant ual hynn — y urenhines o'r neill parth idaw ef, a'r iarll, debygei ef, o'r parth arall. A dechreu ymdidan a wnaeth ef a'r urenhines. Ac o'r a welsei eiryoet wrth ymdidan a hi, dissymlaf gwreic a bonedigeidaf i hannwyt a'y hymdidan oed. A threulaw a wnaethant bwyt a llynn a cherdeu a chyuedach. O'r a welsei o holl lyssoed y dayar, llyna y llys diwallaf o uwyt a llynn, ac eur lestri, a theyrndlysseu.",
          e: "And the hall was set. Then he saw a household and companies — the noblest and best-appointed gathering he had ever seen coming in — and the queen with them, the fairest woman he had ever seen, in a court-robe of shining gold-shot silk. And with that they went to wash, and made for the tables, and sat thus: the queen on one side of him, and an earl, as he supposed, on the other. And he began to converse with the queen. Of all he had ever conversed with, she was the most natural and noblest in her ways and in her speech. And they passed the time on meat and drink and song and banquet. Of all the courts of earth he had ever seen, this was the court most furnished of meat and drink and gold vessels and royal treasures.",
          n: "The queen, unnamed in the source (Welsh tradition often keeps the Otherworld queen anonymous, as Sir Orfeo later keeps the Fairy Queen). Pwyll's pleasure in her company is given full weight; the test the night will pose is set up by the courtly fairness of the day." },

        { w: "Amser a doeth udunt e uynet e gyscu, ac y gyscu yd aethant, ef a'r urenhines. Y gyt ac yd aethant yn y guely ymchwelut e weneb at yr erchwyn a oruc ef, a'y geuyn attei hitheu. O hynny hyt trannoeth, ny dywot ef wrthi hi un geir. Trannoeth, tirionwch ac ymdidan hygar a uu y ryngthunt. Peth bynnac o garueidrwyd a wei y rungthunt y dyd, ni bu unnos hyt ym pen y ulwydyn amgen noc a uu y nos gyntaf.",
          e: "The time came for them to go to sleep, and to sleep they went, he and the queen. The moment they were in the bed, he turned his face to the bed-edge, and his back to her. From that until the morrow he did not say one word to her. On the morrow, kindness and gracious conversation between them. Whatever fondness was between them by day, there was not one night until the year's end different from what the first night had been.",
          n: "The chaste night. The fairest woman ever offered, the form of her own husband on him, the year-long licence — and Pwyll turns his back and is silent. The Welsh prose registers no internal monologue, no reasoning, no struggle. The act is reported as the natural consequence of <em>cedymdeithas</em>, companionship. For the cross-tale layer this is a refined H1556 fidelity test of a kind absent from all three of the other annotated poems: the test is what the hero does in the husband's bed, when there is no one to see and the husband himself has put him there." },

        { w: "Treulaw y ulwydyn a wnaeth trwy hela, a cherdeu, a chyuedach, a charueidrwyd, ac ymdidan a chedymdeithon, hyt y nos yd oet y gyfranc. Yn oet y nos honno, kystal y doi y gof y'r dyn eithaf yn yr holl gyuoeth yr oet [ac idaw ynteu]. Ac ynteu a doeth i'r oet, a guyrda y gyuoeth y gyt ac ef. Ac y gyt ac y doeth i'r ryt, marchawc a gyuodes y uynyd, ac a dywot wal hynn: “A wyrda,” heb ef, “ymwerendewch yn da. Y rwng y deu wrenhin y mae yr oet hwnn, a hynny y rwng y deu gorff wylldeu. A fob un o honunt yssyd hawlwr ar y gilyd, a hynny am dir a dayar. A ssegur y digaun pawn o honawch uot, eithyr gadu y ryngthunt wylldeu.”",
          e: "He spent the year in hunting, song, banqueting, fondness, and conversation with companions, until the night of the appointment. On that night, the appointment came as clearly into the mind of the furthest man in all the realm as into his own. And he came to the appointment, with the nobles of his realm beside him. And when they came to the ford, a knight rose up and spoke as follows: “Nobles,” he said, “listen well. Between the two kings is this appointment, and that between their two bodies. Each of them is a claimant against the other, and that for land and territory. It is for each of you to stand idle, save to leave it between the two of them.”",
          n: "The herald's speech is the formal protocol of the duel. <em>Y rwng y deu gorff wylldeu</em> — between the two bodies. Single combat between sovereigns for territory; the witnessing army is forbidden to intervene. Medieval Welsh judicial duelling, transposed onto the Otherworld and given its purest possible setting — a ford, a knight rising in his stirrups, two kings approaching from opposite banks." },

        { w: "Ac ar hynny y deu urenhin a nessayssant y gyt am perued y ryt e ymgyuaruot. Ac ar y gossot kyntaf, y gwr a oed yn lle Arawn, a ossodes ar Hafgan ym perued bogel y daryan yny hyllt yn deu hanner, ac yny dyrr yr arueu oll, ac yny uyd Hafgan hyt y ureich a'e paladyr dros pedrein y uarch y'r llawr, ac angheuawl dyrnawt yndaw ynteu.",
          e: "And with that, the two kings drew together in the middle of the ford for the encounter. And at the first stroke, the man in Arawn's place struck Hafgan on the middle of his shield-boss until it split in two halves, and until all his armour broke, and until Hafgan was thrown an arm's length and a spear-length beyond his horse's rump on the ground, with a death-stroke in him.",
          n: "One stroke. The contract held perfectly. The mortal blow is delivered with the maximum medieval-Welsh poetic precision — the boss, the split, the body's measured cast beyond the horse — but Pwyll's hand is calm. He has done what was asked, no more." },

        { w: "“A unben,” heb yr Hafgan, “pa dylyet a oed iti ar uy angheu i? Nit yttoydwn i yn holi dim i ti. Ni wydwn achos it heuyt y'm llad i; ac yr Duw,” heb ef, “canys dechreueist uy llad, gorffen.” “A unbenn,” heb ynteu, “ef a eill uot yn ediuar gennyf gwneuthur a wneuthum itt. Keis a'th lado; ni ladaf i di.”",
          e: "“Lord,” said Hafgan, “what claim had you on my death? I was not asking anything of you. I know no reason for you to kill me; and for God's sake,” he said, “since you have begun killing me, finish.” “Lord,” said the other, “it may yet be that I shall be sorry for what I have done to you. Find one to kill you; I shall not kill you.”",
          n: "The refusal of the second stroke. Hafgan asks for the kindness of completion; Pwyll, holding to Arawn's instruction — <em>one stroke only, never a second</em> — refuses, by naming an honest oblique reason: <em>it may yet be I shall be sorry.</em> The bargain's narrowness and the hero's restraint coincide. The Insular ethic of mercy and the Insular ethic of honoured contract wear the same name here: <em>cedymdeithas</em>, companionship — owed not only to the friend but, by its logic, even to the enemy he was sent to kill." },

        { w: "“Vy ngwyrda kywir,” heb yr Hafgan, “dygwch ui odyma: neut teruynedic angheu y mi. Nit oes ansawd y mi y'ch kynnal chwi bellach.” “Vy ngwyrda innheu,” heb y gwr a oed yn lle Arawn, “kymerwch ych kyuarwyd, a gwybydwch pwy a dylyo bot yn wyr ymi.” “Arglwyd,” heb y gwyrda, “pawb a'y dyly, canyt oes urenhin ar holl Annwuyn namyn ti.” “Ie,” heb ynteu, “a del yn waredauc, iawn yw [y] gymryt. Ar ny del yn uuyd, kymmeller o nerth cledyueu.” Ac ar hynny, kymryt gwrogaeth y gwyr a dechreu guereskynn y wlat. Ac erbyn hanner dyd drannoeth, yd oed yn y uedyant y dwy dyrnas.",
          e: "“My faithful nobles,” said Hafgan, “carry me from here. My death is now fixed. There is no longer any way for me to support you.” “My nobles, then,” said the man in Arawn's place, “take your counsel and know who is bound to be my men.” “Lord,” said the nobles, “every man is bound to it, since there is now no king of all Annwn but you.” “Well,” said he, “whoever comes obediently, it is right to receive him. Whoever does not come willingly, let him be compelled by the power of the sword.” And with that, he took the homage of the men, and began to subdue the land. And by midday on the morrow, the two kingdoms were in his power.",
          n: "Hafgan's own nobles testify that there is no king but Arawn now. The two contending kingdoms of Annwn united by a single stroke at the ford. Pwyll's year of trust is justifying its weight: by half a day after the appointment, he holds the whole Otherworld." },

        { w: "Ac ar hynny, ef a gerdwys parth a'y gynnadyl, ac a doeth y Lynn Cuch. A phan doeth yno, yd oed Arawn urenhin Annwuyn yn y erbyn. Llawen uu pob un wrth y gilid o honunt. “Ie,” heb yr Arawn, “Duw a dalo itt dy gydymdeithas; mi a'y kygleu.” “Ie,” heb ynteu, “pan delych dy hun i'th wlat, ti a wely a wneuthum i yrot ti.” “A wnaethost,” heb ef, “yrof i, Duw a'y talo itt.” Yna y rodes Arawn y furuf, a'y drych e hun y Pwyll, Pendeuic Dyuet, ac y kymerth ynteu y furuf e hun a'y drych. Ac y kerdaud Arawn racdaw parth a'y lys y Annwuyn, ac y bu digrif ganthaw ymwelet a'y eniuer ac a'y deulu, canis rywelsei ef wy ys blwydyn. Wynteu hagen ni wybuyssynt i eisseu ef, ac ni bu newydach ganthunt y dyuodyat no chynt.",
          e: "And with that, he set out for his appointment, and came to Glyn Cuch. And when he came there, Arawn, king of Annwn, was there to meet him. Each was joyful at the other. “Well,” said Arawn, “may God repay you for your companionship — I have heard of it.” “Well,” said the other, “when you come yourself to your country, you shall see what I have done for you.” “What you have done,” said he, “for me, may God repay you.” Then Arawn gave his form and appearance to Pwyll Prince of Dyfed, and took back his own form and appearance. And Arawn rode on to his court in Annwn, and was delighted to see his household and his people, since he had not seen them for a year. They however had not missed him, and his coming was no fresher to them than any other day.",
          n: "<em>They had not missed him.</em> One of the lay's quietest miracles — the courtiers of Annwn lived with Pwyll-as-Arawn for an entire year without noticing a substitution. Pwyll's impersonation was complete; Arawn's reputation is preserved intact. The exchange's whole point sits in the closing detail of this paragraph." },

        { w: "Y dyd hwnnw a dreulwys trwy digrifwch a llywenyd, ac eisted ac ymdidan a'y wreic ac a'y wyrda. A phan uu amserach kymryt hun no chyuedach, y gyscu yd aethant. Y vely a gyrchwys, a'y vreic a aeth attaw. Kyntaf y gwnaeth ef ymdidan a'y wreic, ac ymyrru ar digriwwch serchawl a charyat arnei. A hynny ny ordifnassei hi ys blwydyn, a hynny a uedylywys hi. “Oy a Duw,” heb hi, “pa amgen uedwl yssyd yndaw ef heno noc ar a uu yr blwydyn y heno?” A medylyaw a wnaeth yn hir. A guedy y medwl hwnnw, duhunaw a wnaeth ef, a farabyl a dywot ef wrthi hi, a'r eil, a'r trydyt; ac attep ny chauas ef genthi hi yn hynny. “Pa achaws,” heb ynteu, “na dywedy di wrthyf i?” “Dywedaf wrthyt,” heb hi, “na dywedeis ys blwydyn y gymmeint yn y kyfryw le a hwnn.”",
          e: "That day he spent in merriment and gladness, sitting and conversing with his wife and his nobles. And when it was rather time for sleeping than for feasting, they went to bed. He made for the bed, and his wife came to him. The first thing he did was to converse with his wife, and to engage in loving fondness and affection with her. And this was not what she had been accustomed to for the year — and at that she pondered. “Oh God,” she said, “what different mind is in him tonight than has been for the year tonight?” And she thought for a long time. And after that thought, he stirred, and spoke a word to her, and a second, and a third — and got no answer from her. “Why,” said he, “do you not speak to me?” “I tell you,” she said, “I have not spoken in a year as much in such a place as this.”",
          n: "The mirror scene. Arawn, returning, behaves as a husband always behaves at homecoming. His wife is bewildered. The poem stages the recognition not as an explanation but as the wife's stunned silence followed by her quiet accusation, leaving Arawn to work out what has happened." },

        { w: "“Paham?” heb ef. “Ys glut a beth yd ymdidanyssam ni.” “Meuyl im,” heb hi, “yr blwydyn y neithwyr o'r pan elem yn nyblyc yn dillat guely, na digrifwch, nac ymdidan, nac ymchwelut ohonot dy wyneb attaf i — yn chwaethach a uei uwy no hynny o'r bu y rom ni.” Ac yna y medylywys ef, “Oy a Arglwyd Duw,” heb ef, “cadarn a ungwr y gydymdeithas, a diffleeis, a geueis i yn gedymdeith.” Ac yna y dywot ef wrth y wreic: “Arglwydes,” heb ef, “na chapla di uiui. Y rof i a Duw,” heb ynteu, “ni chyskeis inheu gyt a thi, yr blwydyn y neithwyr, ac ni orwedeis.” Ac yna menegi y holl gyfranc a wnaeth idi. “I Duw y dygaf uy nghyffes,” heb hitheu, “gauael gadarn a geueist ar gedymdeith yn herwyd ymlad a frouedigaeth y gorff, a chadw kywirdeb wrthyt titheu.” “Arglwydes,” heb ef, “sef ar y medwl hwnnw yd oedwn inheu, tra deweis wrthyt ti.” “Diryued oed hynny,” heb hitheu.",
          e: "“Why?” said he. “We have been close in our conversation often enough.” “Shame on me,” said she, “for the year since last night, from when we entered the folds of the bed-clothes, neither delight, nor conversation, nor turning your face to me — much less anything more than that between us.” And then he thought: “Oh Lord God,” he said, “strong and single is the companionship and the faith I have got for a companion.” And then he said to his wife: “Lady,” said he, “do not blame me. Between me and God,” he said, “I did not sleep with you, for the year since last night, nor did I lie with you.” And then he told her the whole matter. “I take my confession to God,” said she, “you have got a strong grip on a companion in fighting and in bodily temptation, and in keeping faith with you.” “Lady,” said he, “that was the very thought I had while I was silent to you.” “That was not strange,” said she.",
          n: "The reveal is in two registers. Arawn's prayer of relief — <em>strong and single is the companionship and faithful that I have got</em>. The wife's appraisal of Pwyll — <em>you have got a strong grip on a companion in fighting and in bodily temptation, and in keeping faith with you</em>. She names both tests Pwyll has passed (the ford and the bed) and ties them together as one proof of trustworthiness. The Welsh prose passes through the most intimate possible domestic scene without sentimentality and arrives at the most rigorous possible judgment." },

        { w: "Ynteu Pwyll, Pendeuic Dyuet, a doeth y gyuoeth ac y wlat. A dechreu ymouyn a gwyrda y wlat, beth a uuassei y arglwydiaeth ef arnunt hwy y ulwydyn honno y wrth ryuuassei kynn no hynny. “Arglwyd,” heb wy, “ny bu gystal dy wybot; ny buost gyn hygaret guas ditheu; ny bu gyn hawsset gennyt titheu treulaw dy da; ny bu well dy dosparth eiroet no'r ulwydyn honn.” “Y rof i a Duw,” heb ynteu, “ys iawn a beth iwch chwi, diolwch y'r gwr a uu y gyt a chwi, a llyna y gyfranc ual y bu” — a'e datkanu oll o Pwyll. “Ie, Arglwyd,” heb wy, “diolwch y Duw caffael o honot y gydymdeithas honno; a'r arglwydiaeth a gaussam ninheu y ulwydyn honno, nys attygy y gennym, ot gwnn.” “Nac attygaf, y rof i a Duw,” heb ynteu Pwyll.",
          e: "As for Pwyll, Prince of Dyfed, he came to his realm and his land. And he began to ask the nobles of his land what his lordship over them had been that year, compared to what it had been before. “Lord,” they said, “your understanding was never so good; you were never so kind a young man; never was it easier for you to spend your goods; your governance was never better than in this past year.” “Between me and God,” said he, “it is right that you should thank the man who was with you, and here is the matter as it was” — and Pwyll declared it all. “Well, Lord,” they said, “thanks be to God that you got that companionship; and the lordship that we had this past year, you will not take it away from us, will you?” “I shall not take it away, between me and God,” said Pwyll.",
          n: "Pwyll asks <em>how was my lordship?</em> — the question that opens the door for the truth. His nobles, having lived under Arawn's rule a year, give the most generous report he could have hoped for of himself. His honesty in passing the credit on, and his promise not to undo the policies Arawn established, complete the circuit. The exchange has changed both kingdoms." },

        { w: "Ac o hynny allan, dechreu cadarnhau kedymdeithas y ryngthunt, ac anuon o pop un y gilid meirch a milgwn a hebogeu a fob gyfryw dlws, o'r a debygei bob un digrifhau medwl y gilid o honaw. Ac o achaws i drigiant ef y ulwydyn honno yn Annwuyn, a gwledychu o honaw yno mor lwydannus, a dwyn y dwy dyrnas yn un drwy y dewred ef a'y uilwraeth, y diffygywys y enw ef ar Pwyll, Pendeuic Dyuet, ac y gelwit Pwyll Penn Annwuyn o hynny allan.",
          e: "And from then on, friendship began to be strengthened between them, and each sent to the other horses and greyhounds and hawks and every kind of treasure he thought to gladden the other's mind. And because of his dwelling there for a year in Annwn, and because of his ruling so prosperously, and bringing the two kingdoms into one through his bravery and his warriorship — his name “Pwyll Prince of Dyfed” began to weaken, and from then on he was called <em>Pwyll Penn Annwfn</em>: Pwyll Head of Annwn.",
          n: "The renaming. <em>Penn Annwuyn</em> — Head of Annwn, the title Pwyll carries from this moment forward into all later Welsh tradition. The kingdom of the Otherworld is in his title, not by inheritance, not by conquest of his own arm, but by the loaned year and the held companionship. The closing word of Movement II is the new name. Movement III will open with the same Welsh formula that opened Movement I — <em>a threigylgueith yd oed yn Arberth</em>, \"and one time he was at Arberth\" — but a different king now sits at Arberth." },
      ],
    },
  ],
};
