// table/cairn/data.js — the Cairn Second Edition tables this roller draws from.
//
// GENERATED by tools/scrape-srd.py from https://cairnrpg.com/second-edition/:
//   python3 table/cairn/tools/scrape-srd.py > table/cairn/data.js
// Do not hand-edit — re-run the scraper, so the data stays traceable to the SRD
// it came from. Prose keeps light markdown: **item** and *quality*.
//
// Cairn Second Edition is by Yochai Gal, licensed CC BY-SA 4.0. This file is an
// adaptation of that text and is shared under the same licence. Full
// attribution: ./LICENSE.md
export const CAIRN2E = {
 "backgrounds": [
  {
   "id": "aurifex",
   "name": "Aurifex",
   "blurb": "You are an artisan of the arcane, a smith of subtle forces. In the crucible of your workshop, the laws that govern this world are warped to suit your needs.",
   "names": [
    "Hestia",
    "Basil",
    "Rune",
    "Prism",
    "Ember",
    "Quintess",
    "Aludel",
    "Mordant",
    "Salaman",
    "Jazia"
   ],
   "gear": [
    "3d6 Gold Pieces",
    "Rations (3 uses)",
    "Lantern",
    "Oil Can (6 uses)",
    "Needle-knife (d6)",
    "Protective Gloves (*petty*)"
   ],
   "tables": [
    {
     "prompt": "What went horribly wrong?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "text": "There was an explosion, and you lost your sense of smell. Well, almost: you can sniff out gold as a pig does truffles. Take a **Tin of Snuff** (6 uses) to dampen the impact. Use it every day or become *deprived*."
      },
      {
       "n": 2,
       "text": "You dematerialized a beloved pet. Now it follows you around, invisible but always present. Although it cannot interact with the physical realm, you are able to share its senses. (Add a **Fatigue** each time.) It follows basic commands."
      },
      {
       "n": 3,
       "text": "You were exposed to a long-acting truth serum whose effects have yet to wear off. The disorder has its advantages: you cannot repeat lies you’ve heard, either."
      },
      {
       "n": 4,
       "text": "You were adept at creating *fake* gold, which is almost as good. Eventually, your ruse was discovered, and you had to make a hasty retreat. Take a heavy **Metal Ingot** and **Gold Powder** (3 uses)."
      },
      {
       "n": 5,
       "text": "Your alchemical recipe worked, but a rival stole the blueprint before your claims could be proven. Take a prototype **Blunderbuss** (d12, *blast*, *bulky*) that takes one round to reload, and a taste for revenge."
      },
      {
       "n": 6,
       "text": "Ridiculed for discovering how to turn gold into *lead*, you were a laughing stock. Take a bottle of **Universal Solvent** (2 uses) that dissolves anything it touches into its constituent parts."
      }
     ]
    },
    {
     "prompt": "What alchemical marvel is the product of your latest ingenuity?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "title": "**Pyrophoric Gel**",
       "text": "A sticky green fluid that catches fire when exposed to air, then burns for 8 hours. Cannot be extinguished (1 use)."
      },
      {
       "n": 2,
       "title": "**Blast Sphere**",
       "text": "A head-sized iron ball filled with explosive powder that detonates on impact (d12, *blast*, *bulky*, 1 use)."
      },
      {
       "n": 3,
       "title": "**Aqua Vita**",
       "text": "Purifies any liquid, converting it to pure water. Drinking it cures 1d6 STR (1 use)."
      },
      {
       "n": 4,
       "title": "**Mimic Stone**",
       "text": "Records a short phrase that can later be played back."
      },
      {
       "n": 5,
       "title": "**Spark Dust**",
       "text": "Ignites easily and quickly. Useful for starting a fire or as an incendiary device (3 uses)."
      },
      {
       "n": 6,
       "title": "**Homunculus**",
       "text": "A miniature clay replica of yourself that follows your every command. It hates being enthralled to you and complains bitterly whenever possible. Any damage done to the homunculus is also done to you. 3 HP, 4 STR, 13 DEX, 5 WIL"
      }
     ]
    }
   ]
  },
  {
   "id": "barber-surgeon",
   "name": "Barber-Surgeon",
   "blurb": "You walk the line between healer and harrower, knowing the frailty of the flesh but also the secrets that lie within. With the right tools, life and death are merely words.",
   "names": [
    "Wilmot",
    "Patch",
    "Lancet",
    "Sawbones",
    "Theo",
    "Cutwell",
    "Humor",
    "Landsford",
    "Goodeye",
    "Johanna"
   ],
   "gear": [
    "3d6 Gold Pieces",
    "Rations (3 uses)",
    "Torch (3 uses)",
    "Bonesaw (d6)",
    "Bandages (3 uses)",
    "Leech (restores 1 STR, 3 uses)",
    "Stained Medical Finery (*petty*)"
   ],
   "tables": [
    {
     "prompt": "How have you “improved” yourself?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "text": "You have a replacement **eye** that can magnify objects, act as a telescope, and provide minimal night vision. You cannot wear anything metal on your head, and the presence of strong magnets make you *deprived*."
      },
      {
       "n": 2,
       "text": "One **foot** is mostly metal (kick, d6), and you treat some Tough terrain as **Easy**. Carry a **Oil Can** (6 uses). Without a daily application, you are *deprived* and noisy."
      },
      {
       "n": 3,
       "text": "One of your fingers has been swapped, the bone replaced by gold and iron. Take a **Hook** and a **Screwdriver** that can attach to the fingertip."
      },
      {
       "n": 4,
       "text": "Both **ears** have been surgically enhanced, tripling your hearing. You can focus on a specific sound, such as a conversation, at a great distance. You wear an ear flap to protect against sudden loud noises (WIL save to avoid temporary paralysis)."
      },
      {
       "n": 5,
       "text": "Your **chest** is lined with alchemical sigils, *toughening the skin* (1 Armor). Wearing other metallic armor nullifies the effect."
      },
      {
       "n": 6,
       "text": "One **arm** is fully metal and comes off at the shoulder. It can be used as a weapon (d8, *bulky* when not attached) and can move independently if you are within sight of it."
      }
     ]
    },
    {
     "prompt": "What rare tool is essential to your work?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "title": "**Regrowth Salve**",
       "text": "Regrows a body part over the course of a day. 1 use."
      },
      {
       "n": 2,
       "title": "**Graftgrub**",
       "text": "A small worm that can fuse inanimate objects with parts of the body. 1 use."
      },
      {
       "n": 3,
       "title": "**Woundwax**",
       "text": "Heals wounds from fire or chemicals (restoring full STR) but nothing else. 2 uses."
      },
      {
       "n": 4,
       "title": "**Quicksilver**",
       "text": "A stimulant. Go first in combat, and automatically pass any WIL saves for one hour. *Addictive*: Save STR or become *deprived* after 24 hours without it. 4 uses."
      },
      {
       "n": 5,
       "title": "**Pneuma Pump**",
       "text": "Portable iron lungs (*bulky*). Enables life-saving surgery or underwater breathing."
      },
      {
       "n": 6,
       "title": "**Lodestone**",
       "text": "Draws out dangerous elements from the body and acts as a powerful magnetic force."
      }
     ]
    }
   ]
  },
  {
   "id": "beast-handler",
   "name": "Beast Handler",
   "blurb": "You alone can walk among the creatures of the wild, fearless and in control. You share a connection with animals that others can only dream of… so long as you don’t become their snack.",
   "names": [
    "Amara",
    "Wulf",
    "Mireille",
    "Soren",
    "Freki",
    "Aster",
    "Gerrik",
    "Boreas",
    "Veda",
    "Matheus"
   ],
   "gear": [
    "3d6 Gold Pieces",
    "Rations (3 uses)",
    "Torch (3 uses)",
    "Leather Whip (d6)",
    "Soporific Darts (STR save or fall asleep, 6 uses)",
    "Lure",
    "Rope (25ft)"
   ],
   "tables": [
    {
     "prompt": "What creature is your specialty?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "title": "**Arachnids**",
       "text": "Take a **Quick-Flame Rod** and an **Oil Can** (6 uses). It can destroy a large spider nest in seconds."
      },
      {
       "n": 2,
       "title": "**Felines**",
       "text": "Take a sack of **Whiskerwort**. Its odor can calm and control even the largest of cats."
      },
      {
       "n": 3,
       "title": "**Canines**",
       "text": "Take a wreath of **Wolfsbane** and a **Large Net**. Effective against werewolves as well."
      },
      {
       "n": 4,
       "title": "**Birds**",
       "text": "Take a **Warble-Whistle** (3 charges). It can imitate any bird call and can even be used to send simple messages. **Recharge**: Feed a baby bird as its mother would, then blow."
      },
      {
       "n": 5,
       "title": "**Rodents**",
       "text": "Take a **Pan Flute** that emits a high-pitched sound that only rodents can hear. So long as you play, they will follow, even to their deaths."
      },
      {
       "n": 6,
       "title": "**Serpents**",
       "text": "Take a **Warming Stone** that generates an irresistible heat and a vial of **Antitoxin** (2 uses)."
      }
     ]
    },
    {
     "prompt": "What have you learned from the creatures of the wild?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "text": "That there is far more to the world than meets the eye. With quiet concentration, you can borrow the senses of a nearby creature of your **specialty**."
      },
      {
       "n": 2,
       "text": "That the behavior of beasts is a language in itself. When observing beasts of your **specialty** you gain insight into weather patterns and impending disasters."
      },
      {
       "n": 3,
       "text": "That the pulse of the hunt is a powerful impulse. You have a sense for when predators, even those **not of your specialty** are near."
      },
      {
       "n": 4,
       "text": "That the land is a language unto itself. Your chance of becoming lost in a terrain dominated by the beasts of your **specialty** is reduced by one step (e.g. 4-in-6 becomes 3-in-6)."
      },
      {
       "n": 5,
       "text": "That nature’s symphony can be heard if you attune to its rhythm. When surrounded by creatures of your **specialty**, they can alert you to approaching danger before it arrives."
      },
      {
       "n": 6,
       "text": "That survival is all about adaptability. Once per day, you may take on a simple feature from a creature of your **specialty** (webbed fingers, night vision, etc.). Add a **Fatigue** each time."
      }
     ]
    }
   ]
  },
  {
   "id": "bonekeeper",
   "name": "Bonekeeper",
   "blurb": "You are a shepherd to the departed. You listen to the final whispers of the dead as they descend into the cold, unyielding earth. You know that to fully celebrate the gift of life, we must honor its finale as well.",
   "names": [
    "Rook",
    "Ebon",
    "Moro",
    "Yew",
    "Pall",
    "Leth",
    "Bea",
    "Barnaby",
    "Vesper",
    "Leder"
   ],
   "gear": [
    "3d6 Gold Pieces",
    "Rations (3 uses)",
    "Lantern",
    "Oil Can (6 uses)",
    "Stake (d6)",
    "Chains (10ft)"
   ],
   "tables": [
    {
     "prompt": "What did you take from the dead?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "text": "A **crow-shaped amulet**. You can ask a question of the dead but must add a **Fatigue** each time. They do not always speak truthfully."
      },
      {
       "n": 2,
       "text": "A **mortal wound** from a freed *revenant*. You were healed, but the disfigurement has made you a pariah. You require neither air nor sustenance but are still subject to pain and death. Trapped between worlds, the dead see you as one of their own."
      },
      {
       "n": 3,
       "text": "A **Blood Pail** (*bulky*) from a local death-cult. Empty it to raise a servant built from whatever is buried below, with 6 HP, 1 Armor, 13 STR, 11 DEX, 4 WIL, and shard fists (d8+d8). Only one servant can be raised at a time. If destroyed, you permanently lose 1d4 STR. **Recharge**: Fill with the blood of a dying warrior."
      },
      {
       "n": 4,
       "text": "A **burial wagon** (+6 slots, *slow*) from your last job. It came with a stubborn old **donkey** (+4 slots, only +2 slots if pulling wagon)."
      },
      {
       "n": 5,
       "text": "The **Detect Magic** Spellbook, stolen from an ancient library. Your family worked in service to an obscure underworld deity, but you lost your faith. Though exiled, you continue to serve, even as an apostate. Detect Magic: You can see or hear nearby magical auras. *Becomes warm to the touch when magic is used nearby.*"
      },
      {
       "n": 6,
       "text": "A **plague doctor’s mask**, after its owner succumbed to the disease that wiped out everyone you once knew. They should have kept it on."
      }
     ]
    },
    {
     "prompt": "What tool was invaluable in your work?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "title": "**Manacles**",
       "text": "Though old, it’s still effective even against the very strong. You don’t have the key."
      },
      {
       "n": 2,
       "title": "**Sponge**",
       "text": "Supposedly made from the remains of a rare sea creature. It never seems to dry out."
      },
      {
       "n": 3,
       "title": "**Pulley**",
       "text": "Great for moving gravestones, rocks, or even bodies."
      },
      {
       "n": 4,
       "title": "**Incense**",
       "text": "Perfect for rituals or to keep the flies at bay. Cools the blood."
      },
      {
       "n": 5,
       "title": "**Crowbar**",
       "text": "d6 damage. Sometimes you just need to get the damn thing open!"
      },
      {
       "n": 6,
       "title": "**Repellent**",
       "text": "Powerful stuff. Its faded label makes it unclear what it is actually *meant* to repel, though. Perhaps everything. 3 uses."
      }
     ]
    }
   ]
  },
  {
   "id": "cutpurse",
   "name": "Cutpurse",
   "blurb": "You live in the grey space between those who have power and those who don’t. You find opportunity where others see only chaos. With nimble fingers, you unburden both the richest merchant and the lowliest guard.",
   "names": [
    "Arlo",
    "Lyra",
    "Eamon",
    "Salina",
    "Elara",
    "Freya",
    "Bull",
    "Sparrow",
    "Ivy",
    "Silas"
   ],
   "gear": [
    "3d6 Gold Pieces",
    "Rations (3 uses)",
    "Torch (3 uses)",
    "Twin Daggers (d6+d6, *bulky*)",
    "Padded Leather (1 Armor)",
    "Lockpicks",
    "Black Outfit (*petty*)"
   ],
   "tables": [
    {
     "prompt": "What was your last big job?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "text": "A noble’s summer home. The place was full of fancy wine (+20gp) but not much else. Take **Fence Cutters**."
      },
      {
       "n": 2,
       "text": "A bank. (You were caught.) You bear a brand only visible by firelight, and anyone who sees the mark can ask you for a beer. Take **Retractable Wires**."
      },
      {
       "n": 3,
       "text": "A guild warehouse. Take a **Ladder** (*bulky*, 10ft) and **Blinding Powder** (1 use)."
      },
      {
       "n": 4,
       "text": "Moneylender. Someone beat you to the job but left behind a **Scroll** of *Arcane Eye* (*petty*). *Arcane Eye*: You can see through a magical floating eyeball that flies around at your command."
      },
      {
       "n": 5,
       "text": "Constable’s quarters. You escaped but left some friends behind. Take **Strong Silk Rope** (30ft) and a queasy feeling."
      },
      {
       "n": 6,
       "text": "A university. You were seen but not pursued. You still don’t know why. Take **Smoke Pellets** (3 uses)."
      }
     ]
    },
    {
     "prompt": "What helps you steal?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "title": "**Catring**",
       "text": "2 charges. Climb up walls and fall safely. **Recharge**: Place the ring on a stray cat’s tail."
      },
      {
       "n": 2,
       "title": "**Gildfinger**",
       "text": "1 charge. A finger glove that mimics any mundane key. **Recharge**: Bundle it with at least 100gp for a night."
      },
      {
       "n": 3,
       "title": "**Glimpse Glass**",
       "text": "3 uses. A monocle that lets you see through walls or other obstructions. It shatters after the last use."
      },
      {
       "n": 4,
       "title": "**Sweetwhistle**",
       "text": "1 charge. Listeners hear a soft, familiar voice in the distance that they cannot resist following. **Recharge**: Lose a dear memory. (Describe it.)"
      },
      {
       "n": 5,
       "title": "**Vagrant’s Veil**",
       "text": "1 charge. Wear it to blend seamlessly into crowds, appearing as a simple pauper. **Recharge**: Donate the day’s winnings to the poor. *Petty*"
      },
      {
       "n": 6,
       "title": "**Reverse Teetotum**",
       "text": "1 use. When spun, time skips backwards 30 seconds. Everyone remembers what happened."
      }
     ]
    }
   ]
  },
  {
   "id": "fieldwarden",
   "name": "Fieldwarden",
   "blurb": "Protectors of the harvest, defense against pests, thieves, and beasts. A position of great honor, while it lasts: many guardians do not live out their natural lives. Roll a second time on the **Bonds** table.",
   "names": [
    "Seed",
    "Thresh",
    "Dibber",
    "Sow",
    "Stalk",
    "Harrow",
    "Cobb",
    "Flax",
    "Briar",
    "Rye"
   ],
   "gear": [
    "3d6 Gold Pieces",
    "Rations (3 uses)",
    "Torch (3 uses)",
    "Brigandine (1 Armor, *bulky*)",
    "Sling (d6)",
    "Hand Axe (d6)",
    "Repellent (pick the type, 3 uses)"
   ],
   "tables": [
    {
     "prompt": "What got the better of you?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "text": "A voracious swarm of pests that swallowed crops and animals alike. With nothing to defend, you left. Take **Gale Seed Extract** (3 uses). Ingesting it lets you sprint with a speed four times your regular rate. Afterward you add two **Fatigue**."
      },
      {
       "n": 2,
       "text": "A crop spirit, angered by a poor tithing. The fires consumed nearly everything, and afterward you were able to gather a pouch of **Fireseeds** (d8, *blast*, 4 uses)."
      },
      {
       "n": 3,
       "text": "An antlered, toothy demon that nearly ended you. Take a blood-stained **Bone Knife** (d6). On **Critical Damage**, its next attack becomes *enhanced* from contact with blood."
      },
      {
       "n": 4,
       "text": "*The Withering*, a type of stem rot from the **Roots**. Take a **Diseased Crop** (6 uses) that quickly decays any plant it touches."
      },
      {
       "n": 5,
       "text": "Wolves, or so you thought. You are now a **Werewolf** [8 HP, 15 STR, 14 DEX, claws (d6+d6), bite (d8)]. Your WIL remains the same. You can *turn* at will (once per day) but must make a WIL save to revert. Anyone left alive from your attacks must make a WIL save to avoid infection."
      },
      {
       "n": 6,
       "text": "Crop thieves. Not all of them survived, but you were outnumbered. Start with +d4 HP and a **Cusped Falchion** (d8)."
      }
     ]
    },
    {
     "prompt": "What tool saved your life?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "title": "**Bloodvine Whip**",
       "text": "d8 damage. On **Critical Damage**, it drains the target’s blood, granting the weapon’s next attack the *blast* quality"
      },
      {
       "n": 2,
       "title": "**Clatter Keeper**",
       "text": "A hand-cranked device that emits a loud noise, frightening away most creatures."
      },
      {
       "n": 3,
       "title": "**Sun Stick**",
       "text": "Provides ample warmth and light for up to one hour. **Recharge**: Leave in heavy sunlight for a full day. 1 use."
      },
      {
       "n": 4,
       "title": "**Root Tether**",
       "text": "When thrown, binds a creature as large as a wolf to the soil for a short time."
      },
      {
       "n": 5,
       "title": "**Greenwhistle**",
       "text": "A small flute that calms plants, making passage through areas heavy with plant life a bit easier."
      },
      {
       "n": 6,
       "title": "**Everbloom Band**",
       "text": "A circlet adorned with flowers that never wilt. On **Critical Damage**, the flowers dissolve into dust, but you act as if your save succeeded (STR loss still occurs)."
      }
     ]
    }
   ]
  },
  {
   "id": "fletchwind",
   "name": "Fletchwind",
   "blurb": "You strike from afar, but that does not make you a coward. You are a musician, the song of your bowstring naught but a warning, singing the silent promise of a quick death.",
   "names": [
    "Flint",
    "Feather",
    "Crier",
    "Thunder",
    "Falcon",
    "Pluck",
    "Needle",
    "Warsong",
    "Hawk",
    "Cai"
   ],
   "gear": [
    "3d6 Gold Pieces",
    "Rations (3 uses)",
    "Torch (3 uses)",
    "Bow (see table)",
    "Serrated Knife (d6)",
    "Boiled Leather (1 Armor)",
    "Heartroot Salve (restores 1d4 STR, 1 use)"
   ],
   "tables": [
    {
     "prompt": "How did you earn your bow?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "text": "**War**. If you are first to attack, your bow gains the *blast* property for the first round."
      },
      {
       "n": 2,
       "text": "**Falconry**. You keep a falcon [3 hp, 5 STR, 16 DEX, 4 WIL, claws (d6+d6), bite (d8)]. It only eats live game."
      },
      {
       "n": 3,
       "text": "**Hunting**. When taking the Supply action, your ability to secure **Rations** increases by **one step** (e.g. 1d4 becomes 1d6)."
      },
      {
       "n": 4,
       "text": "**Tournaments**. Attacks with your bow are *enhanced* if the target is immobile."
      },
      {
       "n": 5,
       "text": "**Training**. If you are the first to attack, melee attacks against you are *impaired* until you take STR damage."
      },
      {
       "n": 6,
       "text": "**Scouting**. When taking the Travel action, your presence decreases the chance of getting lost by one step (e.g. 4-in-6 becomes 3-in-6)."
      }
     ]
    },
    {
     "prompt": "What kind of wood is your bow made from?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "text": "**Western Yew** (d6, *bulky*). Can be wielded as a blunt weapon (d6). Noisy."
      },
      {
       "n": 2,
       "text": "**Sessile Oak** (d8, *bulky*). Slams into targets. On **Critical Damage** something is torn off."
      },
      {
       "n": 3,
       "text": "**Stone Pine** (d6, *bulky*). Produces one use of **Sticky Sap** per day. The sap is highly explosive."
      },
      {
       "n": 4,
       "text": "**White Ash** (d6, *bulky*). Can be used in place of a shield in melee combat (+1 Armor)."
      },
      {
       "n": 5,
       "text": "**Striped Bamboo** (d6). Collapsible, it only requires one slot (but still requires both hands)."
      },
      {
       "n": 6,
       "text": "**Wych Elm** (d6, *bulky*). Protects the bearer from poisons and toxins, so long as they are holding it."
      }
     ]
    }
   ]
  },
  {
   "id": "foundling",
   "name": "Foundling",
   "blurb": "An odd birthmark, a strange smell: somehow, the touch of *elsewhere* still lingers. Wherever you are, you have trouble fitting in. Roll on the **Omens** table (even if you’re not the youngest player), but keep the results private for now.",
   "names": [
    "Faunus",
    "Snowdrop",
    "Wisp",
    "Silverdew",
    "Brim",
    "Solstice",
    "Steeleye",
    "Artea",
    "Gossamer",
    "Hazel"
   ],
   "gear": [
    "3d6 Gold Pieces",
    "Rations (3 uses)",
    "Torch (3 uses)",
    "Salt Pouch",
    "Heirloom Amulet (*petty*, glows in the presence of magic)",
    "Sling (d6)",
    "Dagger (d6)"
   ],
   "tables": [
    {
     "prompt": "Who took you in?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "text": "An old hunter. You were both quite happy, until it all ended. Take a **Weathered Longbow** (d8, *bulky*) and a **Leather Jerkin** (1 Armor)."
      },
      {
       "n": 2,
       "text": "A wizened apothecary, who taught you the healing arts but maintained a clinical detachment. Take a **Healing Unguent** (restores d4 STR, 1 use)."
      },
      {
       "n": 3,
       "text": "A druid, who taught you the language of trees. When it came time to , you took with you only a **Gnarled Staff** (d8) and left a promise that one day you would return."
      },
      {
       "n": 4,
       "text": "A gruff blacksmith from a sleepy river town. You were always kept at arm’s length. Now the forge is cold, and you’ve moved on. Take a **Smith’s Apron** (*petty*) and a set of **Oft-mended Chain Mail** (2 Armor, *bulky*)."
      },
      {
       "n": 5,
       "text": "A troupe of traveling entertainers. For a time, they were like family to you. One day you woke up and they were gone with no explanation. Take a **Storybook**, a **Dagger** (d6), and some burning questions."
      },
      {
       "n": 6,
       "text": "The monks of a secluded forest monastery. When their rules became too strict, and you snuck away. Take a **Monk’s Habit** (warm, *petty*) and a **Spellbook** of *Control Plants*. Control Plants: Nearby plants and trees obey you and gain the ability to move at a slow pace. *Leaves grow along the spine, and it smells faintly of decay.*"
      }
     ]
    },
    {
     "prompt": "What keeps bad tidings at bay?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "title": "**Pipeweed**",
       "text": "Your good luck charm. Conversations tend to flow more easily after a smoke. 6 uses."
      },
      {
       "n": 2,
       "title": "**Stink Jar**",
       "text": "Shattering this jar releases an odor so foul all nearby must make a STR save or immediately vomit. 1 use."
      },
      {
       "n": 3,
       "title": "**Ivy Worm**",
       "text": "A green worm often mistaken for a weed. Swallowed whole, it absorbs any toxins or rot in the body before exiting through the usual way."
      },
      {
       "n": 4,
       "title": "**Dream Stone**",
       "text": "A smooth blue stone that helps recall dreams more clearly. Overuse can cause dream-addiction."
      },
      {
       "n": 5,
       "title": "**Drowning Rod**",
       "text": "A finger-sized wooden stick that doubles in size each time it is fully submerged in water. It does not shrink down again."
      },
      {
       "n": 6,
       "title": "**Rabbit’s Foot**",
       "text": "You were wearing it when they found you. They say it is the foot of she who left you and that it protects you from witch magic. *Petty*."
      }
     ]
    }
   ]
  },
  {
   "id": "fungal-forager",
   "name": "Fungal Forager",
   "blurb": "You follow the whisperings of the deep earth, the rhythmic pulse of the mycelium forest that grows beneath the surface. The dark holds no terror for you. Also, you really love mushrooms.",
   "names": [
    "Unther",
    "Woozy",
    "Hilda",
    "Current",
    "Leif",
    "Ratan",
    "Mourella",
    "Lal",
    "Per",
    "Madrigal"
   ],
   "gear": [
    "3d6 Gold Pieces",
    "Rations (3 uses)",
    "Sharpened Trowel (d6)",
    "Candle Helmet (+1 Armor, dim, 6 uses)",
    "Rope (25ft)",
    "Metal Pail"
   ],
   "tables": [
    {
     "prompt": "What strange fungus did you discover?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "text": "**Shrieking Trumpet**. When exposed to light, it screams so loudly that all nearby attacks (including your own) are *impaired*. 2 uses."
      },
      {
       "n": 2,
       "text": "**Torch Fungus**. When crushed, it creates a cold blue light for a short while. 2 uses."
      },
      {
       "n": 3,
       "text": "**Murderous Truffle**. Pungent, highly toxic, and very rare (worth 50gp to assassins). Illegal pretty much everywhere. 1 use."
      },
      {
       "n": 4,
       "text": "**Hellcap**. Exposure to its aroma causes intense nausea and vomiting. Either way, it clears the room. Bottled (1 use)."
      },
      {
       "n": 5,
       "text": "**Sproutcup**. Ingest to shrink down to the size of a mouse. (Your belongings stay the same size.) You return to normal size within the hour, often in fits and starts. 1 use."
      },
      {
       "n": 6,
       "text": "**Rootflower**. A white fungus found only on corpses deep underground. Ingest to restore d6 WIL. You will dream of the dead and their stories. 1 use."
      }
     ]
    },
    {
     "prompt": "What keeps you sane, even in utter darkness?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "title": "**Glowsnail**",
       "text": "Casts a soft, bioluminescent light. Feeds on one ration every two days."
      },
      {
       "n": 2,
       "title": "**Silk Moth Shawl**",
       "text": "A weatherproof blanket, it can also douse a fire without being damaged."
      },
      {
       "n": 3,
       "title": "**Milkflower**",
       "text": "A gentle stimulant. Chewing it makes you immune to *panic* for the next hour. 3 uses."
      },
      {
       "n": 4,
       "title": "**Luxcompass**",
       "text": "Hums softly as it moves closer to the Sun. Eventually the noise becomes unbearably loud."
      },
      {
       "n": 5,
       "title": "**Sloth-Tarp**",
       "text": "A tough and weatherproof fabric, useful for hanging off trees. When inside, you have +1 Armor."
      },
      {
       "n": 6,
       "title": "**Miner’s Grease**",
       "text": "Great for dislodging a gem, tool, or limb from a tight crack. Highly explosive. 3 uses."
      }
     ]
    }
   ]
  },
  {
   "id": "greenwise",
   "name": "Greenwise",
   "blurb": "You delve deep into the **Wood**, prying its secrets from between rough boughs and whispering leaves. To this verdant kingdom, you are no mere scholar but its confidant as well.",
   "names": [
    "Gunther",
    "Moss",
    "Fern",
    "Lichen",
    "Root",
    "Willow",
    "Sage",
    "Yarrow",
    "Rowan",
    "Ash"
   ],
   "gear": [
    "3d6 Gold Pieces",
    "Rations (3 uses)",
    "Torch (3 uses)",
    "Iron Pot",
    "Root Knife (d6)",
    "Healing Salve (restore 1d4 STR, 1 use)",
    "Twine Bauble (*petty*, *Ward* once per day) *Ward*: A silver circle 50ft across appears on the ground. Choose one species that cannot cross it."
   ],
   "tables": [
    {
     "prompt": "How has the Wood failed you?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "text": "An ill-tempered forest spirit cursed you for stealing, marking you as an enemy of their kind. Take a **Bezoar Stone**. Ingesting it cures any poison (1 use, unless retrieved)."
      },
      {
       "n": 2,
       "text": "A close friend disappeared into the forest. Now you see their face in any tea you brew. Take a **Soporific Concoction** (3 uses)."
      },
      {
       "n": 3,
       "text": "You were poisoned, losing your sense of taste and smell. You can now withstand noxious fumes and always carry **Antitoxin** (2 uses)."
      },
      {
       "n": 4,
       "text": "Your radical experiments turned your skin green, and you now gain nourishment as a plant. You don’t need **Rations**, but a day without sufficient sunlight and water leaves you *deprived*."
      },
      {
       "n": 5,
       "text": "Your impressive corpseflower won a local contest then promptly killed a judge. You fled, but not without the **Prize Money (100gp)** and a warrant for your arrest."
      },
      {
       "n": 6,
       "text": "You created a restorative tincture that also causes accidental infertility. Take a **Healing Potion** that completely restores STR. Only you know of its unintended side-effects."
      }
     ]
    },
    {
     "prompt": "What keeps you safe while in the Wood?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "title": "**Amadou**",
       "text": "A vermilion fungus that catches fire quite easily. 3 uses."
      },
      {
       "n": 2,
       "title": "**Delphinium**",
       "text": "Breathe water for up to one hour. 1 use, but can be divided into fractional doses."
      },
      {
       "n": 3,
       "title": "**Tacky Stalk**",
       "text": "A woody reed that hardens into a permanent adhesive when chewed. 2 uses."
      },
      {
       "n": 4,
       "title": "**Wisp Lantern**",
       "text": "Caged in wrought iron, provides a dim light so long as the wisp is able to feed on nearby pain and fear."
      },
      {
       "n": 5,
       "title": "**Seed Bomb**",
       "text": "A canvas sack filled with seeds that explode on impact. d6 damage (*blast*, 3 uses)."
      },
      {
       "n": 6,
       "title": "**Briarvine**",
       "text": "Entangles any creature up to horse size (STR to break free). Reusable."
      }
     ]
    }
   ]
  },
  {
   "id": "half-witch",
   "name": "Half Witch",
   "blurb": "Born of both the mortal world and the unseen, you are an enigma to some and feared by many. Yours is the tale of what happens when two worlds collide.",
   "names": [
    "Solena",
    "Veles",
    "Bryn",
    "Sabine",
    "Razvan",
    "Rowena",
    "Galen",
    "Nyx",
    "Vex",
    "Iwan"
   ],
   "gear": [
    "3d6 Gold Pieces",
    "Rations (3 uses)",
    "Torch (3 uses)",
    "Spellbook (Thicket: A thicket of trees and dense brush up to 50ft wide suddenly sprouts up. *Wrapped in vines that must be destroyed again with each use.*)",
    "Iron Dagger (d6)",
    "Herbs Pouch (restore 1 STR, 3 uses)",
    "Ghillie Suit"
   ],
   "tables": [
    {
     "prompt": "What did you bring back from the Unseelie Court?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "text": "A **Black Rose Fiddle** (*bulky*). Its music causes intense sadness and immobility in nearby mortals. (Others are merely fascinated.) You don’t know how to play."
      },
      {
       "n": 2,
       "text": "**Paper legs**. You are extremely light, and can fall a few stories without getting hurt. Try to avoid tearing them or getting them wet."
      },
      {
       "n": 3,
       "text": "A **Living Nightmare** that dwells within you but manifests whenever you are in danger. It has your same **Attributes** and **HP** and attacks with claws (d8+d8). It disappears on **Critical Damage** (take 1d4 WIL damage), re-appearing again on the next full moon."
      },
      {
       "n": 4,
       "text": "A **Raven Familiar** [8 HP, 3 STR, 11 DEX, 13 WIL, beak, (d6)]. It speaks as an intelligent being and is entirely devoted to you."
      },
      {
       "n": 5,
       "text": "A **Briar Thorn**. It can pierce any organic material (quite painfully) but when removed leaves no trace of the intrusion."
      },
      {
       "n": 6,
       "text": "A Fae creature’s **True Name**. Use it to summon its owner for an act of great service, but only once. It could also fetch a hefty price, from the right buyer."
      }
     ]
    },
    {
     "prompt": "What concoction do you carry, and what rare ingredients did you gather to make it?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "title": "**Rebirth Ash**",
       "text": "Remnants of a bark spirit. Sprinkle to reignite a fire that has died or return to life a creature that has died only moments before. 3 uses."
      },
      {
       "n": 2,
       "title": "**Glamour Feather**",
       "text": "Plume of a firebird. Can make any creature appear convincingly as someone (or something) else. 1 use."
      },
      {
       "n": 3,
       "title": "**Hawthorn Seed**",
       "text": "An acorn from the other side, gathered on the spring equinox. When planted, it sprouts a luxurious shelter, collapsing at moonrise the next day. 1 use."
      },
      {
       "n": 4,
       "title": "**Stonetree Sap**",
       "text": "Sap obtained in exchange for blood. Hardens when rubbed on any surface (+1 Armor). 3 uses."
      },
      {
       "n": 5,
       "title": "**Nightdust Powder**",
       "text": "Made from the ritual burning of six owls. When tossed in the air, day turns to night for a short while. 2 uses."
      },
      {
       "n": 6,
       "title": "**Hex Stone**",
       "text": "Gathered from a river that flows from the *other side*. Removed from its iron tin, it can absorb the effects of an active magical effect. If destroyed, the magic is released. 1 use."
      }
     ]
    }
   ]
  },
  {
   "id": "hexenbane",
   "name": "Hexenbane",
   "blurb": "You are a mere digit on the unerring hand of justice. You go where others fear to tread, unyielding and unbroken.",
   "names": [
    "Percival",
    "Felix",
    "Isolde",
    "Wolfram",
    "Aldric",
    "Eira",
    "Oswin",
    "Ivor",
    "Brunhilda",
    "Beatrix"
   ],
   "gear": [
    "3d6 Gold Pieces",
    "Rations (3 uses)",
    "Torch (3 uses)",
    "Vestments of the Order (*petty*)",
    "Blessed Tinctures",
    "Silver Knife (d6)",
    "Crossbow (d8, *bulky*)"
   ],
   "tables": [
    {
     "prompt": "To which order do you belong?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "text": "**Order of the Crossroads**. Take a **Pocket Leyfinder**. It points to nearby ley lines and other sources of arcane power. If you lose it, the punishment is death."
      },
      {
       "n": 2,
       "text": "**Order of the Bleeding Star**. Take a **Star-Iron Mace** (d8). It shines faintly in darkness and becomes very hot in the presence of witchcraft."
      },
      {
       "n": 3,
       "text": "**Order of the Glass Sigil**. Take a short sword (d8) and chainmail (2 Armor, *bulky*). You have contacts in most towns (the more rural, the better) willing to provide aid, food, or even weapons."
      },
      {
       "n": 4,
       "text": "**Order of the Blank Eye**. Take a **Voidglass Shard**. Peer through it to see invisible marks, creatures, and other magical effects. Lose the use of your eye for an hour afterwards (you are *deprived*)."
      },
      {
       "n": 5,
       "text": "**Order of Canaas**. Once per day, you can change into a wolf. Take a **Quicksilver Chain**. Without it, you are unable to shift back."
      },
      {
       "n": 6,
       "text": "**Order of the Silent Veil**. Take a **Quell Stone** (2 uses) wrapped in burlap. Extinguishes any nearby flames once exposed to air."
      }
     ]
    },
    {
     "prompt": "What was your vow?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "text": "**Honesty**. Choose a **weapon type** (blunt, blade, etc). Attacks against you of this type are *impaired*. If your vow is broken, you lose d4 WIL."
      },
      {
       "n": 2,
       "text": "**Poverty**. You carry the *Disassemble* **Spellbook**. Only you can use it. If your vow is broken, it explodes (d12 STR damage). Disassemble: Any of your body parts may be detached and reattached at will, without causing pain or damage. You can still control them. *Regenerates any torn or defaced pages.*"
      },
      {
       "n": 3,
       "text": "**Selflessness**. You are immune to **mind-altering magical effects**, such as *charm*, *hatred*, *frenzy*, and so on. If you break this vow, you lose d6 WIL."
      },
      {
       "n": 4,
       "text": "**Mercy**. Choose a **weapon type** (blunt, blade, etc). Attacks with this weapon are *enhanced*. If your vow is broken, you can never use that weapon type again."
      },
      {
       "n": 5,
       "text": "**Charity**. Once per day you can shrug off a **Fatigue**. If your vow is ever broken, you permanently lose one inventory slot."
      },
      {
       "n": 6,
       "text": "**Valor**. The first time you inflict **Critical Damage**, you receive +d4 HP, returning to the previous limit at the end of combat. If your vow is broken, you die."
      }
     ]
    }
   ]
  },
  {
   "id": "jongleur",
   "name": "Jongleur",
   "blurb": "What inspires the soul more than song, words, and spectacle? Why practice for years to master the arcane when you’ve already got real magic inside?",
   "names": [
    "Jax",
    "Selene",
    "Baladria",
    "Ada",
    "Mort",
    "Saylor",
    "Tripp",
    "Lantos",
    "Echo",
    "Jubilo"
   ],
   "gear": [
    "3d6 Gold Pieces",
    "Rations (3 uses)",
    "Torch (3 uses)",
    "Costume",
    "Simple Instrument (Pipes, Lute, etc.)",
    "Lucky Jerkin (+1 Armor)",
    "Sling (d6)"
   ],
   "tables": [
    {
     "prompt": "What happened at your final performance?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "text": "Despite your training in the deadly arts, an actor died and you were blamed. Take a light-weight **Rapier** (d6) and a false identity."
      },
      {
       "n": 2,
       "text": "The crowd loved your catchy tune about a noble and his romantic failings. The noble in question, not so much. Take the *Read Mind* **Spellbook** and a warrant for your arrest. Read Mind: You can hear the surface thoughts of nearby creatures. *Long-term possession can cause the reader to mistake the thoughts of others as their own.*"
      },
      {
       "n": 3,
       "text": "Your debut composition reduced the audience to a gibbering mess, murmuring of bright creatures descending from the night sky. Later you noticed that the notes resembled stellar constellations. Take a **Book On Astronomy**, and a lot of questions."
      },
      {
       "n": 4,
       "text": "You mocked a forgotten trickster god and were cursed for it. You speak only in perfect rhyme. Ironically, this has only made you more popular among your peers. Take a **Thesaurus** (20gp). Without it, you are *deprived*."
      },
      {
       "n": 5,
       "text": "You were scarred in an on-stage accident. The crowd cheered, thinking it was part of the act. Take well-worn **Stage Mail** (1 Armor), a memorable scar, and a fear of applause."
      },
      {
       "n": 6,
       "text": "Your respectable puppeteering skills were matched only by your mimicry. You were so good you were branded a witch (literally) and banished. Take an **Uncanny Hand-Puppet** and a **Rabbit Skull** (*petty*) that protects against charms."
      }
     ]
    },
    {
     "prompt": "What trinket were you unable to leave behind?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "title": "**False Cuffs**",
       "text": "Comfortable, realistic-looking cuffs. Only you know the trick to get out of them."
      },
      {
       "n": 2,
       "title": "**Pocket Theatre**",
       "text": "A set of small puppets and a folding stage. Good for quick distractions."
      },
      {
       "n": 3,
       "title": "**Ghost Violin**",
       "text": "A dark-gray violin that plays a haunting tune, mirrored by an invisible, distant twin."
      },
      {
       "n": 4,
       "title": "**Tragic Tales**",
       "text": "Banned in proper company, this book becomes less bawdy and more harrowing towards the end. Worth **100gp**."
      },
      {
       "n": 5,
       "title": "**Mythos Mask**",
       "text": "A plaster mask that allows one to take on a monster’s countenance. Once it comes off, add a **Fatigue**."
      },
      {
       "n": 6,
       "title": "**Rebreak Glass**",
       "text": "A wine flute that can be broken multiple times, reforming after 24 hours. Makes a really loud noise."
      }
     ]
    }
   ]
  },
  {
   "id": "kettlewright",
   "name": "Kettlewright",
   "blurb": "You are known by the smell of molten metal and the jingle of tin. You are no mere merchant but an artisan of fire and metal.",
   "names": [
    "Fergus",
    "Eon",
    "Bram",
    "Idris",
    "Hester",
    "Darragh",
    "Seren",
    "Rónán",
    "Berek",
    "Lorenz"
   ],
   "gear": [
    "3d6 Gold Pieces",
    "Rations (3 uses)",
    "Torch (3 uses)",
    "Pincers",
    "Roll of Tin",
    "Gloves (*petty*)",
    "Hammer (d6)"
   ],
   "tables": [
    {
     "prompt": "What is your trade?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "text": "You build small contraptions for local guilds (and don’t ask too many questions). Take an extra 40gp and a wanted poster with your face on it. Given time and materials, you can open almost any door or vault."
      },
      {
       "n": 2,
       "text": "You deal in home goods and tools, hawking your wares to townspeople across the lands. Take 20gp worth of items from the gear table. You are fluent in the *Traveler’s Cant*."
      },
      {
       "n": 3,
       "text": "You were a military smelter, before peace destroyed your livelihood. Take a **smelting hammer** (d10, *bulky*) and a **tin helm** (+1 Armor). Given time and adequate materials, you can repair armor."
      },
      {
       "n": 4,
       "text": "You sell rare and quality items to monasteries and nobles alike. Take a **Spyglass**, a **Necklace** (*petty*) worth 20gp, and a **Scroll** of Mirrorwalk (*petty*)."
      },
      {
       "n": 5,
       "text": "You offer protection as a service, quietly watching for threats as money exchanges hands. You start with **+d4 HP**, and carry a **Long Sword** (d10, *bulky*) and a **Gambeson** (+1 Armor)."
      },
      {
       "n": 6,
       "text": "You scavenge raw tin and iron from battlefields, pulling teeth from still-twitching corpses. Start with a young **Donkey** (+4 slots, slow), a **Crossbow** (d8 damage, *bulky*), and a **Saw** (d6)."
      }
     ]
    },
    {
     "prompt": "What never fails to get you out of trouble?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "title": "**Fire Eggs**",
       "text": "Six small pellets made of sea salt, wood, and crockery-dust. They explode at low heat (d8, *blast*) but the flames dissipate quickly."
      },
      {
       "n": 2,
       "title": "**Black Tar**",
       "text": "Versatile: both sticky and highly flammable. 3 uses."
      },
      {
       "n": 3,
       "title": "**Spiked Boots**",
       "text": "Cracks heads (d8) as easily as it does ice and muck. Travel is also a bit slower, but easier."
      },
      {
       "n": 4,
       "title": "**Tinker’s Paste**",
       "text": "Seals shut any fist-sized opening. 3 uses."
      },
      {
       "n": 5,
       "title": "**Fireworks**",
       "text": "A dazzling albeit dangerous display. Enough explosive material to blow off a finger or three. 2 uses remain."
      },
      {
       "n": 6,
       "title": "**Carrion Cat**",
       "text": "A clever pet, small enough to hide in your pack (*bulky*), but strong enough to scare off smaller predators. Requires one **Ration** a day, and it must be meat."
      }
     ]
    }
   ]
  },
  {
   "id": "marchguard",
   "name": "Marchguard",
   "blurb": "Bound by blood Oath to patrol the border and protect the realm. Once sworn, the Oath cannot be broken. The Guard always finds their own.",
   "names": [
    "Gann",
    "Light",
    "Saoirse",
    "Frost",
    "Thorn",
    "Reed",
    "Dirk",
    "Ragnar",
    "Brie",
    "Aasim"
   ],
   "gear": [
    "3d6 Gold Pieces",
    "Rations (3 uses)",
    "Lantern",
    "Oil Can (6 uses)",
    "Long Sword (d10, *bulky*)",
    "Boiled Leather (1 Armor)"
   ],
   "tables": [
    {
     "prompt": "Why did you take the Oath?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "text": "Your family has a long tradition of serving, and you were trained from an early age on how to survive in the wild. When taking the Supply action, your yield increases by one step (e.g. 1d4 > 1d6)."
      },
      {
       "n": 2,
       "text": "As a convict, the Oath was simply a means of avoiding punishment. Take a set of **Lockpicks** and the **Key** (*petty*) to a safehouse."
      },
      {
       "n": 3,
       "text": "Noble-born, you joined to escape family trouble. Take a **Goosefelt Tarp** (fits two) that you stole before leaving home."
      },
      {
       "n": 4,
       "text": "When your family lost everything, you took the Oath to avoid becoming a burden. Take extra **Rations** (3 uses) and a brace of **Throwing Knives** (d6)."
      },
      {
       "n": 5,
       "text": "Your life was saved by a member of the **Marchguard**, and you were inspired to join their ranks. Take a **Snare Trap** and a **Sketchbook** filled with detailed drawings."
      },
      {
       "n": 6,
       "text": "You were in a dark place and decided that your life needed a little direction. You’re still not so sure it was the right choice. Take an **Oilskin Coat** and **Mapping Paper**."
      }
     ]
    },
    {
     "prompt": "What do you carry as proof of your Oath?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "title": "**Impressive Pin**",
       "text": "A metal badge of honor from the Guard. It can open doors but leaves a trail. *Petty*."
      },
      {
       "n": 2,
       "title": "**Oath Compass**",
       "text": "Points not towards North, but instead to the nearest member of the Guard. It also lets you know when they’re getting close."
      },
      {
       "n": 3,
       "title": "**Pullstones**",
       "text": "Two jet-black stones. When separated, the stones will always roll toward one another."
      },
      {
       "n": 4,
       "title": "**Fireflask**",
       "text": "Highly alcoholic, yet strangely delicious. When thrown, it creates a wall of flames 10ft high that burns out after a few minutes. 1 use."
      },
      {
       "n": 5,
       "title": "**Pain Band**",
       "text": "Touch an injured creature to transfer their wounds to you. (Exchange their lost STR with your own.) **Recharge**: Wear the ring while in perfect health. You will lose 1 STR, permanently. *Petty*."
      },
      {
       "n": 6,
       "title": "**Poacher’s Woe**",
       "text": "Strongly-scented arrows (3 uses). The scent is powerful enough to track with ease."
      }
     ]
    }
   ]
  },
  {
   "id": "mountebank",
   "name": "Mountebank",
   "blurb": "Wits are your sharpest weapon, a facade your strongest shield. But when you do lose, you lose badly.",
   "names": [
    "Ambrose",
    "Lucius",
    "Beauregard",
    "Cornelius",
    "Aria",
    "Toph",
    "Indigo",
    "Delphine",
    "Solene",
    "Noa"
   ],
   "gear": [
    "3d6 Gold Pieces",
    "Rations (3 uses)",
    "Torch (3 uses)",
    "Cart (+4 slots, *bulky* when pulled)",
    "Trick Playing Cards",
    "Fancy Hat (*petty*)",
    "Cane Sword (d6)"
   ],
   "tables": [
    {
     "prompt": "How was your fraud exposed?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "text": "Your “patients” kept reporting miraculous recoveries, despite your lack of training. Start with **Bandages** (3 uses) and a knack for healing."
      },
      {
       "n": 2,
       "text": "After seducing a wealthy patron, their family hired a criminal gang to retrieve you. You got away and need to lay low. Start with **Beauty Cream**, 2 uses. Apply to appear irresistibly beautiful for the next 12 hours."
      },
      {
       "n": 3,
       "text": "You were a peddler of fake prophesies, but when one turned out to be true, it drew unwanted attention. Roll on the **Omens** table, but keep the result to yourself. Start with a concealable **Knife** (d6, *petty*)."
      },
      {
       "n": 4,
       "text": "Your latest stunt destroyed a priceless artifact and injured a dozen bystanders. Start with a **Captain’s Uniform** (*petty*), a **Ceremonial Sword** (harmless, 60gp), and a **Bouquet of Flowers**."
      },
      {
       "n": 5,
       "text": "You were cursed by a hedgewitch for fooling some innocent village folk. Magic acts unpredictably in your hands (*WIL save to avoid disaster*). If you are the target of magic, the same applies to its wielder."
      },
      {
       "n": 6,
       "text": "Your “seances” with the dead were in actuality a ruse involving a cleverly hidden spellbook of Auditory Illusion. Inevitably, a patron discovered your secret. Start with the **Spellbook** and a bundle of scarves. Auditory Illusion: You create illusory sounds that seem to come from a direction of your choice. *Produces random and occasionally inopportune sounds throughout the day*."
      }
     ]
    },
    {
     "prompt": "What keepsake could always identify you?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "title": "**Royal Crest**",
       "text": "Born into royalty, you chose a different life. The crest grants you access but also alerts your family of your whereabouts. *Petty*."
      },
      {
       "n": 2,
       "title": "**Miracle Oil**",
       "text": "A smelly, slippery concoction. 2 uses."
      },
      {
       "n": 3,
       "title": "**Surgeon’s Soap**",
       "text": "A lye and ash block that makes skin temporarily transparent, revealing the anatomy within. 4 uses."
      },
      {
       "n": 4,
       "title": "**Goat Powder**",
       "text": "Derived from the placenta of a baby goat. Temporarily cures any affliction, but symptoms return within hours."
      },
      {
       "n": 5,
       "title": "**Cursed Sapphire**",
       "text": "Worth **200gp**, it noticeably returns to your pocket shortly after you spend it. You can’t seem to get rid of it."
      },
      {
       "n": 6,
       "title": "**Alchemical Tattoo**",
       "text": "A dog, cat, or bird that can leave your body on demand. It follows your commands to the best of its abilities and can pass its injuries (*as STR loss*) back onto you. *Petty*."
      }
     ]
    }
   ]
  },
  {
   "id": "outrider",
   "name": "Outrider",
   "blurb": "Your coin comes from escorting caravans, tracking fugitives, or lending your blade to a cause. You’ve been a savior, an executioner, a hero, and even a villain. Yours is not a solitary path, however: you’ll always have your horse.",
   "names": [
    "Drake",
    "Cyra",
    "Keir",
    "Darius",
    "Valen",
    "Rorik",
    "Yara",
    "Rui",
    "Talon",
    "Jory"
   ],
   "gear": [
    "3d6 Gold Pieces",
    "Rations (3 uses)",
    "Torch (3 uses)",
    "Long Sword (d10, *bulky*)",
    "Leather Jerkin (1 Armor)",
    "Crossbow (d8, *bulky*)",
    "Spyglass"
   ],
   "tables": [
    {
     "prompt": "What personal code or principle do you uphold?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "text": "**No innocent blood**: No bystander will come to harm on your watch. Take a **Steadymade Buckler** (+1 Armor). While holding this shield, you cannot be moved so long as both feet are planted on firm ground."
      },
      {
       "n": 2,
       "text": "**Revere the tools of death**: Weapons are to be respected and maintained. Take a **Wyrmbone Whetstone**. Following a half-hour ritual sharpening, attacks with the weapon are *enhanced* until STR damage is dealt."
      },
      {
       "n": 3,
       "text": "**To the death, always**: You never back down from a fight, no matter the odds. Take a **Death-Whistle**, 1 charge. Its scream frightens away all who hear it (save WIL or flee). **Recharge**: Capture the final breath of a dying warrior."
      },
      {
       "n": 4,
       "text": "**Revere the dead**: Death is a journey we all take, and it deserves respect. Take an extra **30gp**. You always place two gold pieces on the eyelids of a slain foe. Somehow, you always find the coin."
      },
      {
       "n": 5,
       "text": "**Loyalty to the work**: Your word is your bond. Once you’ve accepted a job, you see it through to the end. Take a weathered **Tally Stick**. Once a vow is marked onto its face, the stick hardens (d8) until it is complete. The stick will snap in half if the vow is ever broken."
      },
      {
       "n": 6,
       "text": "**Always pay your debts**: You always repay what you owe, whether in coin or in kind. You expect nothing less from all others. Take a **Blacked-Out Ledger**, then roll a second time on the **Bonds** table."
      }
     ]
    },
    {
     "prompt": "What breed is your horse?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "title": "**Heavy Destrier**",
       "text": "A beast built for war, an imposing creature. 8 HP, 1 Armor, hooves (d10+d10), +2 slots."
      },
      {
       "n": 2,
       "title": "**Blacklegged Dandy**",
       "text": "Hardy and adaptable. **Tough** or **Perilous** terrain are one step easier. 6 HP. +4 slots."
      },
      {
       "n": 3,
       "title": "**Rivertooth**",
       "text": "Impressively strong, capable of carrying heavy loads. 4 HP. +6 slots (only +2 slots if carrying two people)."
      },
      {
       "n": 4,
       "title": "**Piebald Cob**",
       "text": "Intelligent, it can understand simple commands and even has an instinct for danger. 6 HP. +4 slots."
      },
      {
       "n": 5,
       "title": "**Linden White**",
       "text": "Highly trained and agile, it can perform intricate maneuvers in a time of need (no DEX save to flee). 4 HP. +3 slots."
      },
      {
       "n": 6,
       "title": "**Stray Fogger**",
       "text": "Wild but very fast (even in **Tough** terrain). Rides light. 4 HP. +2 slots."
      }
     ]
    }
   ]
  },
  {
   "id": "prowler",
   "name": "Prowler",
   "blurb": "You are a specter in the night, a fleeting shadow that slips by its prey, unseen. Each kill is a test of cunning and animal determination, a contest between life and death. You know that one day you will lose. You look forward to it.",
   "names": [
    "Winda",
    "Brielle",
    "Theron",
    "Chayse",
    "Nuja",
    "Dev",
    "Raven",
    "Arawan",
    "Sable",
    "Baruani"
   ],
   "gear": [
    "3d6 Gold Pieces",
    "Rations (3 uses)",
    "Torch (3 uses)",
    "Tarp",
    "Boiled Leather (1 Armor)",
    "Short Sword (d6)",
    "Spring-Loaded trap (4 STR damage)"
   ],
   "tables": [
    {
     "prompt": "What did you last hunt?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "text": "A *mock firefly*, baiting water carriers with its glowing lure. Take an **Alchemical Limb** (d8, *petty* when worn) to replace the one it tore off and an **Oil Can** (6 uses). The limb is immune to heat and poison. Needs to be oiled daily."
      },
      {
       "n": 2,
       "text": "An *ice nettle*, trapping and draining sheep. You lost your commission when the fungus you introduced killed half the flock. Take a **Rime Seed** (1 use). It freezes any body of water, no matter the size. Don’t eat it."
      },
      {
       "n": 3,
       "text": "A *silver marsh crawler* that killed someone close to you. You now carry its **Tooth** (*petty*) on a chain around your neck as a warning to others of its kind. *The tooth hums softly when something is stalking you*."
      },
      {
       "n": 4,
       "text": "A malicious *forest spirit* that poisoned a homestead. You saved a **Heartseed** from the roots of a dying tree. (Plant it to create a new forest.) Also, take **Iron Bracers** (+1 Armor, *bulky*)."
      },
      {
       "n": 5,
       "text": "A *hollow wolf* that had been frightening travelers. You took pity on the half-starved creature and nursed it back to health. Now it is loyal to you unto death. It is also a great tunneler. 5 HP, 11 STR, 13 DEX, 8 WIL, teeth (d6)."
      },
      {
       "n": 6,
       "text": "An *azure warbler*. The gametes attract a sizeable profit, if properly extracted. You succeeded but left its nest to the wolves. Take a **Paring Knife** (d6), **an extra 20gp**, and a pang of regret."
      }
     ]
    },
    {
     "prompt": "What tool is always in your pack?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "title": "**Fermented Spirits**",
       "text": "Keeps you warm at the best of times and as an explosive at the worst. 3 Uses."
      },
      {
       "n": 2,
       "title": "**Trail Shaker**",
       "text": "A noisy instrument that reveals nearby trails, even when deeply hidden."
      },
      {
       "n": 3,
       "title": "**Drowse Balm**",
       "text": "A wax bar. If boiled in water, the steam acts as a soporific agent."
      },
      {
       "n": 4,
       "title": "**Spike and Cord**",
       "text": "For traversing difficult terrain or for creating makeshift traps and structures."
      },
      {
       "n": 5,
       "title": "**Iron Rattle**",
       "text": "A noisemaker for distracting or scaring your quarry. Sounds convincingly like a snake."
      },
      {
       "n": 6,
       "title": "**Hardening Glue**",
       "text": "Makes any flat material (cloth, leather, sand) as hard as stone. Expensive (20gp a bottle, 3 uses)."
      }
     ]
    }
   ]
  },
  {
   "id": "rill-runner",
   "name": "Rill Runner",
   "blurb": "You sing the stories of rivers and lakes, your talents soothing friends and the elements alike. You’ve seen more than most, but somehow it never seems to be enough.",
   "names": [
    "Gale",
    "Piper",
    "Brook",
    "Adair",
    "Stone",
    "Dale",
    "Wren",
    "Cliff",
    "Rain",
    "Robin"
   ],
   "gear": [
    "3d6 Gold Pieces",
    "Rations (3 uses)",
    "Torch (3 uses)",
    "Water Shoes",
    "Brigandine (1 Armor, *bulky*)",
    "Compass",
    "Dagger (d6)"
   ],
   "tables": [
    {
     "prompt": "What songs are you best known for?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "text": "*The Tinker’s Two-Step*. A humorous fairy tale about a gift-giving traveler. Start with a **Reed Whistle**. Anyone in earshot must pass a WIL save to perform an act of violence."
      },
      {
       "n": 2,
       "text": "*The Sylph and Her Lover*. A bawdy tale of lost love. Start with a **Breeze Knot** (3 charges). Creates a strong breeze. **Recharge**: Tie it to a mast during a storm."
      },
      {
       "n": 3,
       "text": "*Harper’s Devotion*. A sad, short tale about a musician that falls in love with a star. Start with a **Celestial Lute**. Reveals the constellations above, no matter the weather."
      },
      {
       "n": 4,
       "text": "*The Reed Fisher*. A celebrated song about a massive carp that always seems to get away. Begin with a spool of **River Twine** (5 uses). Each dip into the river guarantees a catch, though it might not be pleasant."
      },
      {
       "n": 5,
       "text": "*Song of the Silver Stream*. A wordless lullaby that mimics flowing water. Take a **Stone Flute** that can calm almost any river."
      },
      {
       "n": 6,
       "text": "*The Thrush and the Meadow*. A moody tale told in alternating chorus. Start with a **Feather Quill** (1 use, *petty*). A map drawn with this quill reveals the most expedient course between any two points."
      }
     ]
    },
    {
     "prompt": "What pays your way across the land?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "title": "**Performance**",
       "text": "Performing at taverns always yields both room and board. Sometimes you even get tips! Start with an extra **10gp**."
      },
      {
       "n": 2,
       "title": "**Bodyguard**",
       "text": "You are a protector for those afraid to travel alone. Start with a **Rapier** (d8)."
      },
      {
       "n": 3,
       "title": "**Wares**",
       "text": "You buy low and sell high, always making just enough to get by. Take a **single item** worth **20gp** (or less) from the gear table."
      },
      {
       "n": 4,
       "title": "**Transport**",
       "text": "You deliver “delicate” packages throughout the lands. You have at least one contact in any major town."
      },
      {
       "n": 5,
       "title": "**Sailor’s Friend**",
       "text": "Over troubled waters and dangerous winds, you always make sure a ship reaches its destination. For you, passage is always free."
      },
      {
       "n": 6,
       "title": "**Guide**",
       "text": "You shepherd caravans and travelers across water-soaked lands. Start a **map** (*petty*) relevant to your next journey."
      }
     ]
    }
   ]
  },
  {
   "id": "scrivener",
   "name": "Scrivener",
   "blurb": "You copy ancient texts and illuminate manuscripts, recording the voices of the clever, the great, and the powerful. You will prove that the pen truly is mightier than the sword.",
   "names": [
    "Lazlo",
    "Stilo",
    "Akshara",
    "Pisa",
    "Ji-Yun",
    "Kalamos",
    "Hugo",
    "Shui",
    "Kalam",
    "Julius"
   ],
   "gear": [
    "3d6 Gold Pieces",
    "Rations (3 uses)",
    "Torch (3 uses)",
    "Quill & Ink",
    "Blank Book",
    "Awl (d6)",
    "Badge (*petty*)"
   ],
   "tables": [
    {
     "prompt": "What work did you keep for yourself?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "text": "**The Wild Tongue**. A bundle of leather-bound scrolls. A seminal work, cataloging the hidden languages of beasts and how to understand them."
      },
      {
       "n": 2,
       "text": "**The Silent Symphony**. Bound in fluorescent wrap. Very rare, it chronicles the subtle signs used by those employing invisibility magic."
      },
      {
       "n": 3,
       "text": "**A Treatise on the Abyss**. A nondescript black book. An in-depth, largely theoretical text describing the **Roots**, as well as information about the location of a nearby **Gate**."
      },
      {
       "n": 4,
       "text": "**The Star Waltz**. A comet-shaped clasp bound in a fine leather cover. Detailed astronomical charts, celestial movements, and stellar festivals. Highly valued (100gp) for its usefulness to travelers."
      },
      {
       "n": 5,
       "text": "**The Cathedral and the Canopy**. Large-leaf binding over vellum. Nominally a children’s storybook, the margins detail information about traveling, eating, and sleeping in the cloud forests."
      },
      {
       "n": 6,
       "text": "**Garden of Glass**. Bound in the cover of another book. A heretical work, it describes the materials, procedures, and optimal locations required to open a **Gate**."
      }
     ]
    },
    {
     "prompt": "How do you transcribe sensitive information?",
     "die": 6,
     "entries": [
      {
       "n": 1,
       "title": "**Fib Ink**",
       "text": "Glows when used to write true statements but fades if used to write false ones."
      },
      {
       "n": 2,
       "title": "**Cipher Stone**",
       "text": "A pair of sharp black stones. Each one decrypts any message written by the other."
      },
      {
       "n": 3,
       "title": "**Everquill**",
       "text": "A quill that writes on any surface. You still need ink. *Petty*."
      },
      {
       "n": 4,
       "title": "**Whisper Vial**",
       "text": "Whisper a message into the vial, and it will play it back to whoever opens it next."
      },
      {
       "n": 5,
       "title": "**Sanguine Lens**",
       "text": "Extracts blood from a target without their knowledge. A stolen drop placed on the eye reveals memories from the past day."
      },
      {
       "n": 6,
       "title": "**Echo Leaf**",
       "text": "A blank parchment. Whomever unfurls it sees their actions of the day slowly revealed in a tight scrawl. *Petty*."
      }
     ]
    }
   ]
  }
 ],
 "traits": {
  "physique": [
   "Athletic",
   "Brawny",
   "Flabby",
   "Lanky",
   "Rugged",
   "Scrawny",
   "Short",
   "Statuesque",
   "Stout",
   "Towering"
  ],
  "skin": [
   "Birthmarked",
   "Marked",
   "Oily",
   "Rosy",
   "Scarred",
   "Soft",
   "Tanned",
   "Tattooed",
   "Weathered",
   "Webbed"
  ],
  "hair": [
   "Bald",
   "Braided",
   "Curly",
   "Filthy",
   "Frizzy",
   "Long",
   "Luxurious",
   "Oily",
   "Wavy",
   "Wispy"
  ],
  "face": [
   "Bony",
   "Broken",
   "Chiseled",
   "Elongated",
   "Pale",
   "Perfect",
   "Rakish",
   "Sharp",
   "Square",
   "Sunken"
  ],
  "speech": [
   "Blunt",
   "Booming",
   "Cryptic",
   "Droning",
   "Formal",
   "Gravelly",
   "Precise",
   "Squeaky",
   "Stuttering",
   "Whispery"
  ],
  "clothing": [
   "Antique",
   "Bloody",
   "Elegant",
   "Filthy",
   "Foreign",
   "Frayed",
   "Frumpy",
   "Livery",
   "Rancid",
   "Soiled"
  ],
  "virtue": [
   "Ambitious",
   "Cautious",
   "Courageous",
   "Disciplined",
   "Gregarious",
   "Honorable",
   "Humble",
   "Merciful",
   "Serene",
   "Tolerant"
  ],
  "vice": [
   "Aggressive",
   "Bitter",
   "Craven",
   "Deceitful",
   "Greedy",
   "Lazy",
   "Nervous",
   "Rude",
   "Vain",
   "Vengeful"
  ]
 },
 "bonds": [
  {
   "n": 1,
   "text": "You inherited a **Single Gem** (500gp, cold and brittle) from a long-dead relative. It arrived with a warning: squander your newfound riches, and a debt long thought forgotten would be called in."
  },
  {
   "n": 2,
   "text": "A distant cousin left you a small inheritance. Take **20Gp** and a **Strange Compass** (*petty*) that always points towards something deep in the Wood."
  },
  {
   "n": 3,
   "text": "You carry a **Portrait** in a locket (*petty*) of a past love who disappeared into the Wood long ago. Somehow you know that they are still alive."
  },
  {
   "n": 4,
   "text": "You found a **Tiny Crystal Prism** (*petty*) buried in the dirt. When held up to the light, it shows visions of an unknown location deep within the Wood. Sometimes you feel a presence looking back at you."
  },
  {
   "n": 5,
   "text": "You once freed a Naiad from a choked stream. In return, it gave you some **Silver Moss** (petty). Swallow it near water, and the creature will come, once, to repay its debt."
  },
  {
   "n": 6,
   "text": "You inherited an old **Journal**, bound in bark. Each evening, its pages are filled with the events of the day, crassly written from the journal’s perspective. The writing is crude but accurate."
  },
  {
   "n": 7,
   "text": "You protect a long-dormant family secret. Take one half of an **Ancient Key** (*petty*). They say that if joined with its twin, it opens a **Gate** through any door."
  },
  {
   "n": 8,
   "text": "You received a **Letter** (*petty*) detailing incontrovertible proof that your true parentage is that of Fae nobility. The note also indicates a date and location where you are to meet the letter’s author, deep in the the Wood."
  },
  {
   "n": 9,
   "text": "You owe a great debt to a member of the nobility and carry their **Signet Ring** (*petty*), which serves as proof of their protection as well as your obligation."
  },
  {
   "n": 10,
   "text": "You consumed a **Mischievous Spirit** that wreaks havoc on your insides, demanding to be taken home, deep in the Wood. It occupies one slot but absorbs one **Fatigue** each day. It wants you alive (for now)."
  },
  {
   "n": 11,
   "text": "A roaming storyteller once spun you tales of great treasure hidden deep in the Wood. You thought it naught but fancy, till they gave you **A Rolled-Up Map** (*petty*) marked with an X."
  },
  {
   "n": 12,
   "text": "During your travels, you met a dying hunter who asked you to deliver a message to their loved ones. Take a **Letter** (*petty*), sealed with tree sap. It is addressed only to the **Lord Of Winter**."
  },
  {
   "n": 13,
   "text": "You found a wounded beast in the forest but chose to ignore it. You see it everywhere now, but only when you’re alone. It looks sad but not angry. You cannot become *panicked* when acting alone."
  },
  {
   "n": 14,
   "text": "You promised a childhood friend that you’d bring them back a rare gift, something unique in all the world. Take a **Bracelet** (*petty*) woven from twine and wildflowers."
  },
  {
   "n": 15,
   "text": "You crossed a creature of the Wood, and it cursed you with a **Stone Heart**. With each passing month, the stone grows heavier by one slot. Until your debt is lifted, you cannot truly die."
  },
  {
   "n": 16,
   "text": "You carved a **Whistle** (*petty*) from an **Oak Lord’s** branch. Your act did not go unnoticed. You cannot seem to rid yourself of the whistle either."
  },
  {
   "n": 17,
   "text": "The **Dawn Brigade** did your family a service, giving you a dried **Blood-Red Flower** (*petty*) as proof. When the flower turns white, it means the favor is owed."
  },
  {
   "n": 18,
   "text": "An entertainer once visited your home, filling it with story and song. He left one day without a word, leaving behind only **A Miniature Lute**. Something rattles inside."
  },
  {
   "n": 19,
   "text": "A white crow appeared to you in a dream, holding a twig in its mouth. You awoke the next morning with the **Twig** (*petty*) in your hand. You believe it brings you luck. It smells faintly of sulfur."
  },
  {
   "n": 20,
   "text": "One of your ancestors wronged a **Moss Witch**, who cursed their bloodline. Your visage causes mirrors to shatter. You’ve noticed that the shards can sometimes reveal illusions."
  }
 ],
 "omens": [
  {
   "n": 1,
   "text": "The once rich waters of a life-giving river have turned black and putrid, tainting the land and sickening those who drink from it. A village elder points to some recent desecration as the cause, but most do not heed their words."
  },
  {
   "n": 2,
   "text": "It feels like winter has arrived too quickly this year, frost and snows making their appearance much earlier than expected. There is talk of a pattern to the frost found in windows, ponds, and cracks in the ground. It almost looks like a map."
  },
  {
   "n": 3,
   "text": "A thick, unnatural fog has begun encroaching upon an ancient and holy grove. It is said to be the work of a great forest spirit, angered by nearby deforestation."
  },
  {
   "n": 4,
   "text": "The night sky grows dimmer each evening, as if stars are disappearing one by one. Rumors of hellish creatures capturing farmers and pulling them into the Roots are spreading like wildfire. Village elders believe the two are connected."
  },
  {
   "n": 5,
   "text": "The songbirds of the Wood have fallen eerily silent as of late. Hunters claim that a spectral figure has been spotted wandering the forest, gazing longingly at anyone it encounters."
  },
  {
   "n": 6,
   "text": "Strange, tear-shaped stones have been found throughout the region, sparking a “gold rush” of sorts for jewelers and thieves alike. The locals believe they are the tears of the earth itself, weeping for a great tragedy yet to come."
  },
  {
   "n": 7,
   "text": "Swarming pests gnaw away at the edges of dreams, and farmers speak of a loud buzzing sound emanating from deep within the Wood. They also say that the sound is getting closer."
  },
  {
   "n": 8,
   "text": "There is a village known far and wide for its impressive “mother tree,” said to shelter the town’s secrets in its boughs. Recently it has begun bleeding red sap, worrying the elders."
  },
  {
   "n": 9,
   "text": "The moon turns a deep crimson, bathing the night in an eerie, blood-red light. Some say it heralds a time of chaos and strife, as the boundaries between the Wood and the mortal realm grow thin."
  },
  {
   "n": 10,
   "text": "Strange cracks have appeared in the night sky, revealing a swirling vortex of light and color. Some say that the divide between realms is at its weakest in centuries and fear what may emerge from the other side."
  },
  {
   "n": 11,
   "text": "A night-blooming flower once thought extinct is sprouting up throughout the Wood. Its scent is intoxicating but also causes vivid nightmares."
  },
  {
   "n": 12,
   "text": "Local livestock have grown increasingly agitated and unmanageable as of late. An old shepherd says it is due to an unsettling howl that emanates from the Wood each full moon."
  },
  {
   "n": 13,
   "text": "Swarms of insects are fleeing from the Wood in droves, destroying any wooden structures they come across. The sound of their wings hum a familiar tune as they pass overhead, like a forgotten nursery rhyme."
  },
  {
   "n": 14,
   "text": "Hunters talk of a curse that befalls any who kill a beast with a streak of white fur: soon after, they are found dead in their homes. Each day, there are fewer and fewer creatures to hunt."
  },
  {
   "n": 15,
   "text": "Folks say that a faint laughter can be heard echoing out of wells all over the city, and that the echoes change to sobs at night."
  },
  {
   "n": 16,
   "text": "The constellations have slowly started shifting in the night sky, forming unfamiliar patterns that have stargazers and sages perplexed. Even the animals seem disturbed."
  },
  {
   "n": 17,
   "text": "An ancient tree at the heart of a sleepy village has suddenly withered and died, despite showing no signs of disease. After its trunk was cut, a bloody hand was found in its core."
  },
  {
   "n": 18,
   "text": "Statues have been weeping blood for months on end, and the wombs of the village have lain barren since. A single child has been the only exception, hidden away by elders overcome with fear and dread."
  },
  {
   "n": 19,
   "text": "The local fauna is behaving oddly, displaying heightened aggression or fleeing the area entirely. Hunters talk of a shadowy figure that roams the Wood, calling to the animals."
  },
  {
   "n": 20,
   "text": "Border towns have become riotous in recent weeks after multiple claims of a red-robed figure appearing in their children’s dreams, uttering the same warning: A fire is coming, and it will consume everything."
  }
 ],
 "scars": [
  {
   "n": 1,
   "text": "Lasting Scar: Roll 1d6. 1: Neck, 2: Hands, 3: Eye, 4: Chest, 5: Legs, 6: Ear. Roll 1d6. If the total is higher than your max HP, take the new result."
  },
  {
   "n": 2,
   "text": "Rattling Blow: You’re disoriented and shaken. Describe how you refocus. Roll 1d6. If the total is higher than your max HP, take the new result."
  },
  {
   "n": 3,
   "text": "Walloped: You’re sent flying and land flat on your face, winded. You are deprived until you rest for a few hours. Then, roll 1d6. Add that amount to your max HP."
  },
  {
   "n": 4,
   "text": "Broken Limb: Roll 1d6. 1-2: Leg, 3-4: Arm, 5: Rib, 6: Skull. Once mended, roll 2d6. If the total is higher than your max HP, take the new result."
  },
  {
   "n": 5,
   "text": "Diseased: You’re afflicted with a gross, uncomfortable infection. When you get over it, roll 2d6. If the total is higher than your max HP, take the new result."
  },
  {
   "n": 6,
   "text": "Reorienting Head Wound: Roll 1d6. 1-2: STR, 3-4: DEX, 5-6: WIL. Roll 3d6. If the total is higher than your current attribute, take the new result."
  },
  {
   "n": 7,
   "text": "Hamstrung: You can barely move until you get serious help and rest. After recovery, roll 3d6. If the total is higher than your max DEX, take the new result."
  },
  {
   "n": 8,
   "text": "Deafened: You cannot hear anything until you find extraordinary aid. Regardless, make a WIL save. If you pass, increase your max WIL by 1d4."
  },
  {
   "n": 9,
   "text": "Re-brained: Some hidden part of your psyche is knocked loose. Roll 3d6. If the total is higher than your max WIL, take the new result."
  },
  {
   "n": 10,
   "text": "Sundered: An appendage is torn off, crippled, or useless. (The Warden will tell you which.) Then make a WIL save. If you pass, increase your max WIL by 1d6."
  },
  {
   "n": 11,
   "text": "Mortal Wound: You are deprived and out of action. You die in one hour unless healed. Upon recovery, roll 2d6. Take the new result as your max HP."
  },
  {
   "n": 12,
   "text": "Doomed: Death seemed ever so close, but somehow you survived. If your next save against critical damage is a fail, you die horribly. If you pass, roll 3d6. If the total is higher than your max HP, take the new result."
  }
 ]
};
