// table/cairn/items.js — Cairn 2e's marketplace, reliquary and spellbooks.
//
// GENERATED by tools/scrape-items.py from https://cairnrpg.com/second-edition/:
//   python3 table/cairn/tools/scrape-items.py > table/cairn/items.js
// Do not hand-edit — re-run the scraper.
//
// Every entry's `text` is in the `Name (qualities)` form that roll.js's
// parseItem reads, so a relic out of a tomb and a sword out of a shop pack into
// the ten slots by the same code path.
//
// Cairn Second Edition is by Yochai Gal, licensed CC BY-SA 4.0. This file is an
// adaptation of that text and is shared under the same licence. Full
// attribution: ./LICENSE.md
export const ITEMS = {
 "market": {
  "armor": [
   {
    "text": "Shield (+1 Armor)",
    "cost": 10
   },
   {
    "text": "Helmet (+1 Armor)",
    "cost": 10
   },
   {
    "text": "Gambeson (+1 Armor)",
    "cost": 15
   },
   {
    "text": "Brigandine (1 Armor, *bulky*)",
    "cost": 20
   },
   {
    "text": "Chainmail (2 Armor, *bulky*)",
    "cost": 40
   },
   {
    "text": "Plate (3 Armor, *bulky*)",
    "cost": 60
   }
  ],
  "weapons": [
   {
    "text": "Dagger (d6 damage)",
    "cost": 5
   },
   {
    "text": "Cudgel (d6 damage)",
    "cost": 5
   },
   {
    "text": "Sickle (d6 damage)",
    "cost": 5
   },
   {
    "text": "Staff (d6 damage)",
    "cost": 5
   },
   {
    "text": "Spear (d8 damage)",
    "cost": 10
   },
   {
    "text": "Sword (d8 damage)",
    "cost": 10
   },
   {
    "text": "Mace (d8 damage)",
    "cost": 10
   },
   {
    "text": "Axe (d8 damage)",
    "cost": 10
   },
   {
    "text": "Flail (d8 damage)",
    "cost": 10
   },
   {
    "text": "Halberd (d10 damage, *bulky*)",
    "cost": 20
   },
   {
    "text": "War Hammer (d10 damage, *bulky*)",
    "cost": 20
   },
   {
    "text": "Long Sword (d10 damage, *bulky*)",
    "cost": 20
   },
   {
    "text": "Sling (d6 damage)",
    "cost": 5
   },
   {
    "text": "Bow (d6 damage, *bulky*)",
    "cost": 20
   },
   {
    "text": "Crossbow (d8 damage, *bulky*)",
    "cost": 30
   }
  ],
  "transport": [
   {
    "text": "Cart (+4 slots, *bulky*)",
    "cost": 30
   },
   {
    "text": "Wagon (+8 slots, slow)",
    "cost": 200
   },
   {
    "text": "Horse (+4 slots)",
    "cost": 75
   },
   {
    "text": "Mule (+6 slots, slow)",
    "cost": 30
   },
   {
    "text": "Carriage Seat",
    "cost": 5
   },
   {
    "text": "Ship’s Passage",
    "cost": 10
   }
  ],
  "upkeep-and-recovery": [
   {
    "text": "Room & Board (per night)",
    "cost": 10
   },
   {
    "text": "Private Room & Board (fits 4)",
    "cost": 35
   },
   {
    "text": "Stable & Feed (per night)",
    "cost": 5
   },
   {
    "text": "Medical Healing",
    "cost": 50
   },
   {
    "text": "Rations (3 uses)",
    "cost": 10
   },
   {
    "text": "Animal Feed (3 uses, bulky)",
    "cost": 5
   }
  ],
  "hirelings-(per-day)": [
   {
    "text": "Alchemist",
    "cost": 30
   },
   {
    "text": "Animal Handler",
    "cost": 5
   },
   {
    "text": "Blacksmith",
    "cost": 15
   },
   {
    "text": "Bodyguard",
    "cost": 10
   },
   {
    "text": "Local Guide",
    "cost": 5
   },
   {
    "text": "Lockpick",
    "cost": 10
   },
   {
    "text": "Navigator",
    "cost": 10
   },
   {
    "text": "Sailor",
    "cost": 5
   },
   {
    "text": "Scholar",
    "cost": 20
   },
   {
    "text": "Tracker",
    "cost": 5
   },
   {
    "text": "Trapper",
    "cost": 5
   },
   {
    "text": "Veteran Bodyguard",
    "cost": 20
   }
  ],
  "gear": [
   {
    "text": "Air Bladder",
    "cost": 5
   },
   {
    "text": "Antitoxin",
    "cost": 20
   },
   {
    "text": "Bandages (3 uses)",
    "cost": 30
   },
   {
    "text": "Bathing Goods (Soap, Perfume, etc.)",
    "cost": 5
   },
   {
    "text": "Book",
    "cost": 50
   },
   {
    "text": "Caltrops",
    "cost": 10
   },
   {
    "text": "Card Deck",
    "cost": 5
   },
   {
    "text": "Chain (10ft)",
    "cost": 10
   },
   {
    "text": "Chalk (*petty*)",
    "cost": 1
   },
   {
    "text": "Chest",
    "cost": 25
   },
   {
    "text": "Chisel",
    "cost": 5
   },
   {
    "text": "Common Agents (Glue, Grease, etc.)",
    "cost": 10
   },
   {
    "text": "Common Tools (Hammer, Shovel, etc.)",
    "cost": 10
   },
   {
    "text": "Compass",
    "cost": 75
   },
   {
    "text": "Complex Instruments (Bagpipes, Fiddle, etc.)",
    "cost": 50
   },
   {
    "text": "Containers (Sack, Waterskin, etc.)",
    "cost": 10
   },
   {
    "text": "Cooking Gear (Pots, Utensils, etc.)",
    "cost": 10
   },
   {
    "text": "Costume Gear (Face Paint, Disguise)",
    "cost": 15
   },
   {
    "text": "Dowsing Rod",
    "cost": 15
   },
   {
    "text": "Expeditionary Gear (Climbing Spikes, Pulley, etc.)",
    "cost": 10
   },
   {
    "text": "Fire Oil",
    "cost": 10
   },
   {
    "text": "Fishing Rod",
    "cost": 10
   },
   {
    "text": "Games (Cards, Dice, etc.)",
    "cost": 10
   },
   {
    "text": "Gloves (*petty*)",
    "cost": 20
   },
   {
    "text": "Grappling Hook",
    "cost": 25
   },
   {
    "text": "Lantern",
    "cost": 10
   },
   {
    "text": "Mirror",
    "cost": 5
   },
   {
    "text": "Net",
    "cost": 10
   },
   {
    "text": "Oil Can (6 uses)",
    "cost": 10
   },
   {
    "text": "Outdoor Comfort (Blanket, Hammock, etc.)",
    "cost": 10
   },
   {
    "text": "Parchment (3 uses)",
    "cost": 10
   },
   {
    "text": "Pole (10ft)",
    "cost": 5
   },
   {
    "text": "Repellent (Wolfsbane, Mugwort, etc.)",
    "cost": 10
   },
   {
    "text": "Rope (25ft)",
    "cost": 5
   },
   {
    "text": "Sedative",
    "cost": 30
   },
   {
    "text": "Sewing Kit",
    "cost": 20
   },
   {
    "text": "Simple Instruments (Pipes, Lute, etc.)",
    "cost": 10
   },
   {
    "text": "Smoking Pipe (*petty*)",
    "cost": 15
   },
   {
    "text": "Specialized Tools (Ink, etc.)",
    "cost": 20
   },
   {
    "text": "Spiked Boots",
    "cost": 15
   },
   {
    "text": "Spyglass",
    "cost": 40
   },
   {
    "text": "Tent (fits 2, *bulky*)",
    "cost": 20
   },
   {
    "text": "Thieving Tools (Lockpick, Metal File, etc.)",
    "cost": 25
   },
   {
    "text": "Torch (3 uses)",
    "cost": 5
   },
   {
    "text": "Trap (d6 STR damage)",
    "cost": 35
   },
   {
    "text": "Whistle (*petty*)",
    "cost": 15
   },
   {
    "text": "Wilderness Clothes (Poncho, Cloak, etc.) (*petty*)",
    "cost": 15
   }
  ]
 },
 "relics": [
  {
   "id": "a-blade-called-hope-d6",
   "name": "A Blade Called Hope",
   "text": "A Blade Called Hope (d6)",
   "quals": "d6",
   "effect": "A thin, curved sword that glows with faint light, visible only in total darkness. When bathed in heavy sunlight, its first attack is *Enhanced*.",
   "recharge": null
  },
  {
   "id": "assassins-goblets",
   "name": "Assassin’s Goblets",
   "text": "Assassin’s Goblets",
   "quals": "",
   "effect": "A pair of fragile wine flutes. Any liquid poured into one is swapped with the other.",
   "recharge": null
  },
  {
   "id": "babbleflask-2-uses",
   "name": "Babbleflask",
   "text": "Babbleflask (2 uses)",
   "quals": "2 uses",
   "effect": "A foreign language is automatically understood and can be spoken back with fluency, so long as the drinker’s native tongue is neither spoken nor heard.",
   "recharge": null
  },
  {
   "id": "barbed-epaulets-1-armor",
   "name": "Barbed Epaulets",
   "text": "Barbed Epaulets (+1 Armor)",
   "quals": "+1 Armor",
   "effect": "Spiked shoulder pads that poison anyone that touches them (STR save or lose consciousness).",
   "recharge": null
  },
  {
   "id": "betterwand-2-charges",
   "name": "Betterwand",
   "text": "Betterwand (2 charges)",
   "quals": "2 charges",
   "effect": "Vibrates with increased intensity when pointed at the best of a series of objects.",
   "recharge": null
  },
  {
   "id": "bloodmap-1-charge",
   "name": "Bloodmap",
   "text": "Bloodmap (1 charge)",
   "quals": "1 charge",
   "effect": "A blank leather parchment that absorbs any blood spilled on its surface before rolling into a tight scroll. Unroll to see a rough map revealing the current location of any remaining blood. The image disappears after a few minutes.",
   "recharge": null
  },
  {
   "id": "coin-of-the-father-1-charge-petty",
   "name": "Coin of the Father",
   "text": "Coin of the Father (1 charge, *petty*)",
   "quals": "1 charge, *petty*",
   "effect": "Flip this worthless-looking hunk of flat metal in the air, and it will transform into d100 gold coins. The illusory coins disappear after one hour.",
   "recharge": null
  },
  {
   "id": "dryads-tear-1-use",
   "name": "Dryad’s Tear",
   "text": "Dryad’s Tear (1 use)",
   "quals": "1 use",
   "effect": "Shatter this crystal to merge with a tree you can touch. You can perceive the goings-on within whatever forest that tree belongs to.",
   "recharge": null
  },
  {
   "id": "empathy-rod-3-charges",
   "name": "Empathy Rod",
   "text": "Empathy Rod (3 charges)",
   "quals": "3 charges",
   "effect": "When two creatures touch this wooden pole at the same time, their physical and emotional states become fully intertwined until they let go.",
   "recharge": null
  },
  {
   "id": "eyestone-3-charges",
   "name": "Eyestone",
   "text": "Eyestone (3 charges)",
   "quals": "3 charges",
   "effect": "Choose an object created by living creatures. You can sense the nearest example.",
   "recharge": null
  },
  {
   "id": "falconstone-3-charges",
   "name": "Falconstone",
   "text": "Falconstone (3 charges)",
   "quals": "3 charges",
   "effect": "Perceive the world through the eyes and ears of a nearby bird of prey. You feel whatever it feels but have no control over it.",
   "recharge": null
  },
  {
   "id": "footpads-friend",
   "name": "Footpad’s Friend",
   "text": "Footpad’s Friend",
   "quals": "",
   "effect": "Soft leather shoes that adapt to fit any foot size. Leave behind footprints that scatter and turn in a confusing manner, making tracking nigh-impossible.",
   "recharge": null
  },
  {
   "id": "gate-chalk-1-use-petty",
   "name": "Gate Chalk",
   "text": "Gate Chalk (1 use, *petty*)",
   "quals": "1 use, *petty*",
   "effect": "Draw a doorway on any flat surface to open a one-way passage to the Roots. Good luck.",
   "recharge": null
  },
  {
   "id": "golden-wheat-paste-2-uses",
   "name": "Golden Wheat Paste",
   "text": "Golden Wheat Paste (2 uses)",
   "quals": "2 uses",
   "effect": "When mixed with water, this substance chemically bonds any two objects.",
   "recharge": null
  },
  {
   "id": "gossip-box-1-charge",
   "name": "Gossip Box",
   "text": "Gossip Box (1 charge)",
   "quals": "1 charge",
   "effect": "Wind the crank to replay any sound made in the past day in your current location. Each crank goes back one hour.",
   "recharge": null
  },
  {
   "id": "harbingers-bell-1-charge",
   "name": "Harbinger’s Bell",
   "text": "Harbinger’s Bell (1 charge)",
   "quals": "1 charge",
   "effect": "Hang at chest height to ring when danger is imminent.",
   "recharge": null
  },
  {
   "id": "homunculus-nail-1-use-petty",
   "name": "Homunculus Nail",
   "text": "Homunculus Nail (1 use, *petty*)",
   "quals": "1 use, *petty*",
   "effect": "Prick a finger with the pointy end and hammer into any small object to form a loyal servant [3 HP, 4 STR, 13 DEX, 5 WIL] completely devoted to you. If not destroyed, it will outlive you.",
   "recharge": null
  },
  {
   "id": "honest-earworm-1-use",
   "name": "Honest Earworm",
   "text": "Honest Earworm (1 use)",
   "quals": "1 use",
   "effect": "A foul-smelling, pinky-sized worm that feeds on earwax by crawling into the ear canal of a sleeping person. The victim then loses the ability to lie for 1d4 hours.",
   "recharge": null
  },
  {
   "id": "jar-of-ants",
   "name": "Jar of Ants",
   "text": "Jar of Ants",
   "quals": "",
   "effect": "Break to release a colony of fire ants [6 HP, 2 STR, 10 DEX, 1 WIL, bite (d10), *detachment*]. Consumes a ration every two days.",
   "recharge": null
  },
  {
   "id": "last-breath-d6-1-charge",
   "name": "Last Breath",
   "text": "Last Breath (d6, 1 charge)",
   "quals": "d6, 1 charge",
   "effect": "A chipped short sword of dubious quality. Drive into the earth to form a crystal dome that encircles and immobilizes the wielder. The dome is impenetrable by mundane means, and shatters once the sword is lifted again.",
   "recharge": null
  },
  {
   "id": "lightsucker-candle-3-uses",
   "name": "Lightsucker Candle",
   "text": "Lightsucker Candle (3 uses)",
   "quals": "3 uses",
   "effect": "Once lit, this black tallow wax sheds darkness rather than light, even in the brightest of days.",
   "recharge": null
  },
  {
   "id": "lovers-covenant-1-use",
   "name": "Lover’s Covenant",
   "text": "Lover’s Covenant (1 use)",
   "quals": "1 use",
   "effect": "A bottle of red-tinted ink, a broken heart emblazoned on the front. Write up a contract of any length. Any who sign are bound to obey by penalty of death.",
   "recharge": null
  },
  {
   "id": "mace-of-the-kingslayer-d8-2-charges",
   "name": "Mace of the Kingslayer",
   "text": "Mace of the Kingslayer (d8, 2 charges)",
   "quals": "d8, 2 charges",
   "effect": "Hold the weapon aloft and shout an order or declaration. Any who fail a WIL save must obey, against their better judgment.",
   "recharge": null
  },
  {
   "id": "moth-mirror-bulky",
   "name": "Moth Mirror",
   "text": "Moth Mirror (*bulky*)",
   "quals": "*bulky*",
   "effect": "A full-length, double-sided glass mirror. Step into the mirror to be transported to another mirror you know. You come out of the other side as an enormous swarm of buzzing moths, striking those around you with paralysis (WIL save to avoid) as they gaze upon you in horror. You can revert to your normal form at will. The mirror only operates in one direction.",
   "recharge": null
  },
  {
   "id": "muffle-dust-2-uses",
   "name": "Muffle Dust",
   "text": "Muffle Dust (2 uses)",
   "quals": "2 uses",
   "effect": "A pouch of fine dust that muffles all sound in a 40ft radius when scattered.",
   "recharge": null
  },
  {
   "id": "nightstone-1-use",
   "name": "Nightstone",
   "text": "Nightstone (1 use)",
   "quals": "1 use",
   "effect": "Rare moon-shaped stones dredged from underwater caves and jungle dolines. Swallow whole to relieve all fatigue and deprivation as if you had a good night’s sleep and a good meal. The stone will eventually pass through your system. It isn’t fun.",
   "recharge": null
  },
  {
   "id": "obliteration-scroll-1-use-petty",
   "name": "Obliteration Scroll",
   "text": "Obliteration Scroll (1 use, *petty*)",
   "quals": "1 use, *petty*",
   "effect": "A single-page document filled with gibberish. Sign anywhere on the page to remove any knowledge of your existence from this plane of reality. No one will know or remember you, and any references to your name or lineage will vanish. The scroll disappears in a puff of smoke that smells faintly of sulfur.",
   "recharge": null
  },
  {
   "id": "parliaments-promise-1-armor",
   "name": "Parliament’s Promise",
   "text": "Parliament’s Promise (+1 Armor)",
   "quals": "+1 Armor",
   "effect": "A helmet in the form of an owl’s head. Its wearer can twist their head around like an owl and can see in darkness with perfect clarity. While wearing the helm, the wearer loses the ability to speak, uttering only the simplest of cooing noises.",
   "recharge": null
  },
  {
   "id": "phoenix-ash-1-use",
   "name": "Phoenix Ash",
   "text": "Phoenix Ash (1 use)",
   "quals": "1 use",
   "effect": "Sprinkle over a corpse to resurrect the deceased. They return with full health but no memory of their past life.",
   "recharge": null
  },
  {
   "id": "ring-of-the-snake-1-charge-petty",
   "name": "Ring of the Snake",
   "text": "Ring of the Snake (1 charge, *petty*)",
   "quals": "1 charge, *petty*",
   "effect": "A wrought-iron serpent ring. Place it on your finger and fall into a sleep so deep that most will think you are dead. If the ring is removed, you will awaken feeling refreshed. Otherwise, the effect will wear off after one month.",
   "recharge": null
  },
  {
   "id": "roc-feather-1-use",
   "name": "Roc Feather",
   "text": "Roc Feather (1 use)",
   "quals": "1 use",
   "effect": "Hold while falling to float safely to the ground from any height.",
   "recharge": null
  },
  {
   "id": "skull-whistle-3-charges",
   "name": "Skull Whistle",
   "text": "Skull Whistle (3 charges)",
   "quals": "3 charges",
   "effect": "Produces a chilling scream that forces any who hear it (including the blower) to make a WIL save or become temporarily incapacitated.",
   "recharge": null
  },
  {
   "id": "soul-clump",
   "name": "Soul Clump",
   "text": "Soul Clump",
   "quals": "",
   "effect": "A hard, fist-sized ball covered in small bumps. When rolled on a flat surface, it collects any objects smaller than its current mass, which subsequently increases as more items are attached to its surface. Only living creatures are immune.",
   "recharge": null
  },
  {
   "id": "spystone-1-charge",
   "name": "Spystone",
   "text": "Spystone (1 charge)",
   "quals": "1 charge",
   "effect": "A smooth, flat stone that is slightly warm to the touch. Squeeze to record audio in a 40ft radius. Squeeze again to play it back, as many times as you like.",
   "recharge": null
  },
  {
   "id": "sticky-rope-1-charge",
   "name": "Sticky Rope",
   "text": "Sticky Rope (1 charge)",
   "quals": "1 charge",
   "effect": "A 100ft rope that can stick to any surface.",
   "recharge": null
  },
  {
   "id": "stone-eater-1-use",
   "name": "Stone Eater",
   "text": "Stone Eater (1 use)",
   "quals": "1 use",
   "effect": "A rodent-sized centipede that consumes and digests stone, capable of cutting a small tunnel in under an hour. It can be used more than once, but only if you can catch it (DEX 18).",
   "recharge": null
  },
  {
   "id": "stonewax-gum-3-uses-petty",
   "name": "Stonewax Gum",
   "text": "Stonewax Gum (3 uses, *petty*)",
   "quals": "3 uses, *petty*",
   "effect": "Chew, then spit. The gum will harden and stretch, making a perfect, unbreakable seal.",
   "recharge": null
  },
  {
   "id": "sponge-army-1-use",
   "name": "Sponge Army",
   "text": "Sponge Army (1 use)",
   "quals": "1 use",
   "effect": "A dozen miniature soldiers made of carved sea sponges. When splashed with water, they grow to full size [8 HP, 6 STR, 13 DEX, 5 WIL, hardened sponge (d6), *detachment*] and follow the orders of the person they see until they are destroyed or dry out completely (about 10 minutes).",
   "recharge": null
  },
  {
   "id": "tupshead-crown-1-armor-bulky",
   "name": "Tupshead Crown",
   "text": "Tupshead Crown (+1 Armor, *bulky*)",
   "quals": "+1 Armor, *bulky*",
   "effect": "A beautifully rendered ram’s head helm wrought from tough alpine oak. The horns can be used as weapons (d6+d6).",
   "recharge": null
  },
  {
   "id": "veilsilk-grip-1-charge-petty",
   "name": "Veilsilk Grip",
   "text": "Veilsilk Grip (1 charge, *petty*)",
   "quals": "1 charge, *petty*",
   "effect": "A hand wearing this glove can phase through solid objects.",
   "recharge": null
  },
  {
   "id": "voice-of-the-mountain-1-use",
   "name": "Voice of the Mountain",
   "text": "Voice of the Mountain (1 use)",
   "quals": "1 use",
   "effect": "A rough pebble imbued with the essence of a mountain spirit. Crush to call forth an earthquake or similar natural disaster. Do not expect to be spared.",
   "recharge": null
  },
  {
   "id": "ward-stone-1-use",
   "name": "Ward Stone",
   "text": "Ward Stone (1 use)",
   "quals": "1 use",
   "effect": "A flat, unassuming river stone notched with faded symbols. Smash to release a silvery powder in a 20ft radius that pacifies anyone who breathes it.",
   "recharge": null
  },
  {
   "id": "whispergale-1-use",
   "name": "Whispergale",
   "text": "Whispergale (1 use)",
   "quals": "1 use",
   "effect": "A balloon-shaped plant that captures a spoken message and delivers it to a location within a day’s walk.",
   "recharge": null
  },
  {
   "id": "whistle-rope",
   "name": "Whistle-Rope",
   "text": "Whistle-Rope",
   "quals": "",
   "effect": "15ft of highly flexible leather. Swirl in the air to generate a powerful subsonic effect that drives away wildlife. Also works underwater.",
   "recharge": null
  },
  {
   "id": "wonder-bar-1-charge",
   "name": "Wonder Bar",
   "text": "Wonder Bar (1 charge)",
   "quals": "1 charge",
   "effect": "Pressing the switch on the side of this iron bar freezes it in place, even in midair. Once frozen, it cannot be moved by any force until the switch is depressed.",
   "recharge": null
  },
  {
   "id": "wraith-lantern-1-charge",
   "name": "Wraith Lantern",
   "text": "Wraith Lantern (1 charge)",
   "quals": "1 charge",
   "effect": "Write someone’s name onto its glass, and the name will disappear. The lantern reveals a path to their current location, visible only to the holder (day or night).",
   "recharge": null
  }
 ],
 "spells": [
  {
   "n": 1,
   "name": "Adhere",
   "effect": "An object is covered in extremely sticky slime. *Adjacent objects stick to the book with great force.*"
  },
  {
   "n": 2,
   "name": "Anchor",
   "effect": "A strong wire sprouts from your arms, affixing itself to two points within 50ft on each side. *If a rope is pulled through the iron loop on its spine, it becomes as heavy as an elephant.*"
  },
  {
   "n": 3,
   "name": "Animate Object",
   "effect": "An object obeys your commands as best it can. *Moldable like clay. Childish laughter sprouts from its pages.*"
  },
  {
   "n": 4,
   "name": "Anthropomorphize",
   "effect": "An animal either gains human intelligence or human appearance for one day. *Whimpers, purrs and growls depending on its treatment.*"
  },
  {
   "n": 5,
   "name": "Arcane Eye",
   "effect": "You can see through a magical floating eyeball that flies around at your command. *Needs a spritz of water to open.*"
  },
  {
   "n": 6,
   "name": "Astral Prison",
   "effect": "An object is frozen in time and space within an invulnerable crystal shell. *Silent, abstract, faces scream in anguish within.*"
  },
  {
   "n": 7,
   "name": "Attract",
   "effect": "Two objects are strongly magnetically attracted to each other if they come within 10 feet. *Nearby compasses spin uselessly.*"
  },
  {
   "n": 8,
   "name": "Auditory Illusion",
   "effect": "You create illusory sounds that seem to come from a direction of your choice. *Produces random and occasionally inopportune sounds throughout the day*."
  },
  {
   "n": 9,
   "name": "Babble",
   "effect": "A creature must loudly and clearly repeat everything you think. It is otherwise mute. *When the text is read aloud, the words of others become unintelligible.*"
  },
  {
   "n": 10,
   "name": "Bait Flower",
   "effect": "A plant sprouts from the ground that emanates the smell of decaying flesh. *Attracts flies.*"
  },
  {
   "n": 11,
   "name": "Beast Form",
   "effect": "You and your possessions transform into a mundane animal. *Covered in thick fur, its edges lined with small teeth.*"
  },
  {
   "n": 12,
   "name": "Befuddle",
   "effect": "A creature of your choice is unable to form new short-term memories for the duration of the spell. *Its contents shift and change each time it is opened.*"
  },
  {
   "n": 13,
   "name": "Body Swap",
   "effect": "You switch bodies with a creature you touch. If one body dies, the other dies as well. *The front cover shows an image of the last creature to read it.*"
  },
  {
   "n": 14,
   "name": "Charm",
   "effect": "A creature you can see treats you as a friend. *Warm to the touch, and smells of roses.*"
  },
  {
   "n": 15,
   "name": "Command",
   "effect": "A target obeys a single three-word command that does not cause it harm. *Grows thinner over time, until finally disappearing forever.*"
  },
  {
   "n": 16,
   "name": "Comprehend",
   "effect": "You become fluent in all languages for a short while. *Drips letters, staining whatever it touches.*"
  },
  {
   "n": 17,
   "name": "Cone of Foam",
   "effect": "Dense foam sprays from your hand, coating the target. *Spongy and moist with a soapy residue.*"
  },
  {
   "n": 18,
   "name": "Control Plants",
   "effect": "Nearby plants and trees obey you and gain the ability to move at a slow pace. *Leaves grow along the spine, and it smells faintly of decay.*"
  },
  {
   "n": 19,
   "name": "Control Weather",
   "effect": "You may alter the type of weather at will, but you do not otherwise control it. *Highly resistant to fire and water damage.*"
  },
  {
   "n": 20,
   "name": "Cure Wounds",
   "effect": "Restore 1d4 STR per day to a creature you can touch. *Smells of vinegar and thyme. Turns red after use.*"
  },
  {
   "n": 21,
   "name": "Deafen",
   "effect": "All nearby creatures are deafened. *Nearby instruments occasionally sound off, as if in protest.*"
  },
  {
   "n": 22,
   "name": "Detect Magic",
   "effect": "You can see or hear nearby magical auras. *Becomes warm to the touch if magic is used nearby.*"
  },
  {
   "n": 23,
   "name": "Disassemble",
   "effect": "Any of your body parts may be detached and reattached at will, without causing pain or damage. You can still control them. *Regenerates any torn or defaced pages.*"
  },
  {
   "n": 24,
   "name": "Disguise",
   "effect": "You may alter the appearance of one character at will as long as they remain humanoid. Attempts to duplicate other characters will seem uncanny. *The surface makes a perfect mirror.*"
  },
  {
   "n": 25,
   "name": "Displace",
   "effect": "An object appears to be up to 15ft from its actual position. *Bits of string, clothing, and leaves are sometimes stuffed inside.*"
  },
  {
   "n": 26,
   "name": "Earthquake",
   "effect": "The ground begins shaking violently. Structures may be damaged or collapse. *Sand dribbles from the corners, seemingly without stop.*"
  },
  {
   "n": 27,
   "name": "Elasticity",
   "effect": "Your body can stretch up to 10ft. *Smells of taffy, and is very flexible.*"
  },
  {
   "n": 28,
   "name": "Elemental Wall",
   "effect": "A straight wall of ice or fire 50ft long and 10ft high rises from the ground. *Skin and warmer substances stick to it after use.*"
  },
  {
   "n": 29,
   "name": "Filch",
   "effect": "A visible item teleports to your hands. *An ally’s prized possession may occasionally be found tucked between its covers*."
  },
  {
   "n": 30,
   "name": "Fish Lung",
   "effect": "A target can breathe underwater until they surface again. *Smells strongly of the sea. Attracts wild animals.*"
  },
  {
   "n": 31,
   "name": "Flare",
   "effect": "A bright ball of energy fires a trail of light into the sky, revealing your location to friend or foe. *Faintly glows in complete darkness*."
  },
  {
   "n": 32,
   "name": "Fog Cloud",
   "effect": "A dense fog spreads out from you. *When submersed in water, the book eventually turns all the liquid to vapor.*"
  },
  {
   "n": 33,
   "name": "Frenzy",
   "effect": "A nearby creature erupts in a frenzy of violence. *Rough, sandpaper cover that destroys any book it touches.*"
  },
  {
   "n": 34,
   "name": "Gate",
   "effect": "A portal to a random plane opens. *A large hole is carved into the center, ending in a void. Items dropped within are never seen again*."
  },
  {
   "n": 35,
   "name": "Gravity Shift",
   "effect": "You can change the direction of gravity, but only for yourself. *Attaches itself to the largest object nearby.*"
  },
  {
   "n": 36,
   "name": "Greed",
   "effect": "A creature develops the overwhelming urge to possess a visible item of your choice. *The cover changes depending on the owner, subtly hinting at their deepest desires.*"
  },
  {
   "n": 37,
   "name": "Haste",
   "effect": "Your movement speed is tripled. *Pages flip wildly while open. Can cause paper cuts.*"
  },
  {
   "n": 38,
   "name": "Hatred",
   "effect": "A creature develops a deep hatred of another creature or group and wishes to destroy them. *Long term exposure to the book can cause suspicion, paranoia and distrust of others.*"
  },
  {
   "n": 39,
   "name": "Hear Whispers",
   "effect": "You can hear faint sounds clearly. *The reader’s voice is amplified for a short period of time afterwards.*"
  },
  {
   "n": 40,
   "name": "Hover",
   "effect": "An object hovers, frictionless, 2ft above the ground. It can hold up to one humanoid. *Floats if dropped.*"
  },
  {
   "n": 41,
   "name": "Hypnotize",
   "effect": "A creature enters a trance and will truthfully answer one yes or no question you ask it. *Eye-catching, swirling spirals don its covers.*"
  },
  {
   "n": 42,
   "name": "Icy Touch",
   "effect": "A thick ice layer spreads across a touched surface, up to 10ft in radius. *Gloves required. Nonflammable*."
  },
  {
   "n": 43,
   "name": "Identify Owner",
   "effect": "Letters appear over the object you touch, spelling out the name of the object’s owners, if there are any. *The book’s interior lists the name of its previous owner.*"
  },
  {
   "n": 44,
   "name": "Illuminate",
   "effect": "A floating light moves as you command. *When held in light, the pages become a prism of vibrant rainbows.*"
  },
  {
   "n": 45,
   "name": "Invisible Tether",
   "effect": "Two objects within 10ft of each other cannot be moved more than 10ft apart. *Its pages are not attached by glue or thread, yet stay together nonetheless.*"
  },
  {
   "n": 46,
   "name": "Knock",
   "effect": "A nearby mundane or magical lock unlocks loudly. *Locked. A new owner “produces” the key after their next meal.*"
  },
  {
   "n": 47,
   "name": "Leap",
   "effect": "You jump up to 10ft high, once. *When thrown, it just keeps going.*"
  },
  {
   "n": 48,
   "name": "Liquid Air",
   "effect": "The air around you becomes swimmable. *Floats of its own volition, bouncing off of whatever it touches.*"
  },
  {
   "n": 49,
   "name": "Magic Dampener",
   "effect": "All nearby magical effects have their effectiveness halved. *Relics within 100ft of the spellbook cannot be recharged.*"
  },
  {
   "n": 50,
   "name": "Manse",
   "effect": "A sturdy, furnished cottage appears for hours. You can permit and forbid entry to it at will. *If left inside, both the book and the cottage vanish forever.*"
  },
  {
   "n": 51,
   "name": "Marble Craze",
   "effect": "Your pockets are full of marbles and will refill every 30 seconds. *When jostled, makes a playful rattling sound.*"
  },
  {
   "n": 52,
   "name": "Masquerade",
   "effect": "A character’s appearance and voice becomes identical to those of a character you touch. *Extended use causes the owner to develop unconscious yet noticeable tics.*"
  },
  {
   "n": 53,
   "name": "Miniaturize",
   "effect": "A creature you touch is shrunk down to the size of a mouse. *The text is ludicrously, comically large.*"
  },
  {
   "n": 54,
   "name": "Mirror Image",
   "effect": "An illusory duplicate of yourself appears and is under your control. *Over time, the owner begins to question who is the original, and who is the duplicate.*"
  },
  {
   "n": 55,
   "name": "Mirrorwalk",
   "effect": "A mirror becomes a gateway to another mirror that you looked into today. *Will not open unless the owner politely knocks on the cover.*"
  },
  {
   "n": 56,
   "name": "Multiarm",
   "effect": "You temporarily gain an extra arm. *After use, the caster is wracked with phantom limb syndrome for a day.*"
  },
  {
   "n": 57,
   "name": "Night Sphere",
   "effect": "A 50ft-wide sphere of darkness displaying the night sky appears before you. *Displays a prominent constellation on its cover*."
  },
  {
   "n": 58,
   "name": "Objectify",
   "effect": "You become any inanimate object between the size of a grand piano and an apple. *The owner experiences intense pareidolia for days after use.*"
  },
  {
   "n": 59,
   "name": "Ooze Form",
   "effect": "You become a living jelly. *Slowly drips an acid that eventually eats away anything it touches.*"
  },
  {
   "n": 60,
   "name": "Pacify",
   "effect": "A creature near you has an aversion to violence. *Smells of jasmine and incense. Attracts children.*"
  },
  {
   "n": 61,
   "name": "Passage",
   "effect": "Creates a temporary path through wood, stone or brick. *An object dropped on top of the book inevitably falls through the other side.*"
  },
  {
   "n": 62,
   "name": "Phobia",
   "effect": "A nearby creature becomes terrified of an object of your choice. *Over time, haunting, abstract art begins to fill its pages.*"
  },
  {
   "n": 63,
   "name": "Pit",
   "effect": "A pit 10ft wide and 10ft deep opens in the ground. *A standard piton can be safely stored in its spine*."
  },
  {
   "n": 64,
   "name": "Primal Surge",
   "effect": "A creature rapidly evolves into a future version of its species. *The owner is haunted by strange visions of their own ancestors.*"
  },
  {
   "n": 65,
   "name": "Push/Pull",
   "effect": "An object of any size is pulled directly towards you or pushed directly away from you with the strength of one man. *Any force against the book is comically amplified.*"
  },
  {
   "n": 66,
   "name": "Raise Dead",
   "effect": "A skeleton rises from the ground to serve you. They are incredibly stupid and can only obey simple orders. *The owner becomes more and more fascinated with bones after each use.*"
  },
  {
   "n": 67,
   "name": "Raise Spirit",
   "effect": "The spirit of a nearby corpse manifests and will answer 1 question. *The answers (but not their questions) are forever inscribed in its pages.*"
  },
  {
   "n": 68,
   "name": "Read Mind",
   "effect": "You can hear the surface thoughts of nearby creatures. *Long-term possession can cause the reader to mistake the thoughts of others as their own.*"
  },
  {
   "n": 69,
   "name": "Repel",
   "effect": "Two objects are strongly magnetically repelled from each other within 10 feet. *Closed by two powerful straps that spring open at inopportune times.*"
  },
  {
   "n": 70,
   "name": "Scry",
   "effect": "You can see through the eyes of a creature you touched earlier today. *The owner’s eyes turn milky-white for an hour after use.*"
  },
  {
   "n": 71,
   "name": "Sculpt Elements",
   "effect": "Inanimate material behaves like clay in your hands. *Slowly decays on contact with wood or cloth. Bury in dirt or submerge in water to refresh.*"
  },
  {
   "n": 72,
   "name": "Sense",
   "effect": "Choose one kind of object (key, gold, arrow, jug, etc). You can sense the nearest example. *The book’s previous owner is always aware of the book’s current location.*"
  },
  {
   "n": 73,
   "name": "Shield",
   "effect": "A creature you touch is protected from mundane attacks for one minute. *Bound in rusty ring-mail and is quite heavy. If held, provides +1 Armor.*"
  },
  {
   "n": 74,
   "name": "Shroud",
   "effect": "A creature you touch is invisible until they move. *Invisible to any but the book’s current owner.*"
  },
  {
   "n": 75,
   "name": "Shuffle",
   "effect": "Two creatures you can see instantly switch places. *If stolen but not yet read, it reappears wherever its owner last left it.*"
  },
  {
   "n": 76,
   "name": "Skillful Repair",
   "effect": "You make minor repairs to a nonliving object. *Sewn from the vellum of one hundred books, no two pages are alike.*"
  },
  {
   "n": 77,
   "name": "Sleep",
   "effect": "A creature you can see falls into a light sleep. *Soft as a pillow, but yields only fitful sleep.*"
  },
  {
   "n": 78,
   "name": "Slick",
   "effect": "Every surface in a 30ft radius becomes extremely slippery. *Gloves are required for handling, lest the book is dropped in a most comical fashion.*"
  },
  {
   "n": 79,
   "name": "Smoke Form",
   "effect": "Your body becomes a living smoke that you can control. *Smells of campfire. The pages cannot be burnt, but are very sensitive to moisture.*"
  },
  {
   "n": 80,
   "name": "Sniff",
   "effect": "You can smell even the faintest traces of scents. *Expresses a strong odor detectable only by its owner.*"
  },
  {
   "n": 81,
   "name": "Snuff",
   "effect": "The source of any mundane light you can see is instantly snuffed out. *If left in one place for long periods, nearby light sources eventually dim, then finally go out.*"
  },
  {
   "n": 82,
   "name": "Sort",
   "effect": "Inanimate items sort themselves according to categories you set. *Rights itself when dropped or thrown.*"
  },
  {
   "n": 83,
   "name": "Spellsaw",
   "effect": "A whirling blade flies from your chest, clearing any plant material in its way. It is otherwise harmless. *Wrapped in stained leather, it should be oiled at least once a month*."
  },
  {
   "n": 84,
   "name": "Spider Climb",
   "effect": "You can climb surfaces like a spider. *New cobwebs must be pushed aside prior to each use. They are hard to remove.*"
  },
  {
   "n": 85,
   "name": "Swarm",
   "effect": "You become a swarm of crows, rats, or piranhas. You can only be harmed by *blast* attacks. *Easily broken into a dozen distinct parts that slowly move towards one another over time.*"
  },
  {
   "n": 86,
   "name": "Target Lure",
   "effect": "An object you touch becomes the target of any nearby spell. *Attracts all manner of magical creatures, spell leaks, and scrying.*"
  },
  {
   "n": 87,
   "name": "Telekinesis",
   "effect": "You may mentally 1 move item under 60lbs. *The owner can summon the book through mental command alone (WIL save or become deprived afterwards).*"
  },
  {
   "n": 88,
   "name": "Telepathy",
   "effect": "Two creatures can hear each other’s thoughts, no matter how far apart. *The holder can hear (but not respond) to the thoughts of whoever last possessed it, and vice versa.*"
  },
  {
   "n": 89,
   "name": "Teleport",
   "effect": "An object or person you can see is transported from one place to another in a 50ft radius. *Can be destroyed to create a portal to another dimension.*"
  },
  {
   "n": 90,
   "name": "Thicket",
   "effect": "A thicket of trees and dense brush up to 50ft wide suddenly sprouts up. *Wrapped in vines that must be destroyed again with each use.*"
  },
  {
   "n": 91,
   "name": "Time Control",
   "effect": "Time in a 50ft bubble slows down or increases by 10% for 30 seconds. *Alternates its appearance as either impossibly old or freshly written.*"
  },
  {
   "n": 92,
   "name": "True Sight",
   "effect": "You see through all nearby illusions. *Cannot be concealed by magic, and sticks out like a sore thumb.*"
  },
  {
   "n": 93,
   "name": "Upwell",
   "effect": "A spring of seawater appears. *Hardened leather bindings caked in salt and living barnacles.*"
  },
  {
   "n": 94,
   "name": "Vision",
   "effect": "You completely control what a creature sees. *An unnerving, lidless eye graces the front cover.*"
  },
  {
   "n": 95,
   "name": "Visual Illusion",
   "effect": "A silent, immobile, room-sized illusion of your choice appears. *Filled with rich, colorful pages very much like a children’s bedtime story.*"
  },
  {
   "n": 96,
   "name": "Ward",
   "effect": "A silver circle 50ft across appears on the ground. Choose one species that cannot cross it. *The covers are decorated with bizarre, otherworldly creatures with thousands of eyes.*"
  },
  {
   "n": 97,
   "name": "Web",
   "effect": "Your wrists shoot thick webbing. *The text is alien, yet somehow intelligible, for it is the language of dreams.*"
  },
  {
   "n": 98,
   "name": "Widget",
   "effect": "A primitive version of a drawn tool or item appears before you and disappears after a short time. *Smells of iron and rust, sweat and effort. Faint sounds of harsh labor emanate from deep within its pages.*"
  },
  {
   "n": 99,
   "name": "Wizard Mark",
   "effect": "Your finger can shoot a stream of ulfire-colored paint. This paint is only visible to you and can be seen at any distance, even through solid objects. *Inside the front cover is a small pocket containing a thin pad of paper, listing the name and date of death of all previous owners.*"
  },
  {
   "n": 100,
   "name": "X-Ray Vision",
   "effect": "You can see through walls, dirt, clothing, etc. *Long-term exposure can cause hair loss, blurry vision, and fatigue.*"
  }
 ]
};
