// table/cairn/monsters.js — the Cairn 2e bestiary, as the encounter oracle needs it.
//
// GENERATED by tools/scrape-monsters.py from
// https://cairnrpg.com/second-edition/wardens-guide/bestiary/:
//   python3 table/cairn/tools/scrape-monsters.py > table/cairn/monsters.js
// Do not hand-edit — re-run the scraper.
//
// Cairn Second Edition is by Yochai Gal, licensed CC BY-SA 4.0. This file is an
// adaptation of that text and is shared under the same licence. Full
// attribution: ./LICENSE.md
export const BESTIARY = [
 {
  "id": "acolyte",
  "name": "Acolyte",
  "group": "Humanoid",
  "unmodelled": false,
  "hp": 4,
  "armor": 1,
  "STR": 8,
  "DEX": 11,
  "WIL": 14,
  "attacks": [
   {
    "name": "ceremonial dagger",
    "dice": [
     6
    ],
    "blast": false,
    "note": "d6"
   }
  ],
  "detachment": false,
  "stat": "4 HP, 1 Armor, 8 STR, 11 DEX, 14 WIL, ceremonial dagger (d6)",
  "notes": [
   "Holy servants bound to a particular deity. Typically travel in groups of four or more.",
   "Carry a holy symbol (*Ward* once per day)."
  ]
 },
 {
  "id": "aranea",
  "name": "Aranea",
  "group": "Insectoid",
  "unmodelled": true,
  "hp": 6,
  "armor": 0,
  "STR": 13,
  "DEX": 12,
  "WIL": 15,
  "attacks": [
   {
    "name": "bite",
    "dice": [
     8
    ],
    "blast": false,
    "note": "d8"
   }
  ],
  "detachment": false,
  "stat": "6 HP, 13 STR, 12 DEX, 15 WIL, bite (d8)",
  "notes": [
   "Enormous spiders with greenish-black skin and large brains. Can shape shift into human form at will.",
   "Conduct their magical research in dark, web-filled caverns. Carry the *Charm* and *Command* spellbooks at all times.",
   "Fire damage against Aranea is *enhanced*."
  ]
 },
 {
  "id": "bandit",
  "name": "Bandit",
  "group": "Humanoid",
  "unmodelled": true,
  "hp": 4,
  "armor": 1,
  "STR": 12,
  "DEX": 12,
  "WIL": 9,
  "attacks": [
   {
    "name": "short sword",
    "dice": [
     6
    ],
    "blast": false,
    "note": "d6"
   },
   {
    "name": "short bow",
    "dice": [
     6
    ],
    "blast": false,
    "note": "d6"
   }
  ],
  "detachment": true,
  "stat": "4 HP, 1 Armor, 12 STR, 12 DEX, 9 WIL, short sword (d6) or short bow (d6)",
  "notes": [
   "Outlaws who raid settlements, attack ships, or ambush travelers. Groups of four or more are a *detachment*.",
   "A detachment always travels with one leader wearing chain mail or similar (2 Armor) and a long sword (d10) or crossbow (d8).",
   "**Loyal**: When testing Morale, save using the leader’s WIL (13). If the leader dies, the others will flee."
  ]
 },
 {
  "id": "banshee",
  "name": "Banshee",
  "group": "Mythical",
  "unmodelled": true,
  "hp": 8,
  "armor": 0,
  "STR": 6,
  "DEX": 12,
  "WIL": 15,
  "attacks": [
   {
    "name": "ghostly touch",
    "dice": [
     8
    ],
    "blast": false,
    "note": "d8"
   }
  ],
  "detachment": false,
  "stat": "8 HP, 6 STR, 12 DEX, 15 WIL, ghostly touch (d8)",
  "notes": [
   "Incorporeal spirits that linger long after death to haunt the living.",
   "Unharmed by cold, heat, or the elements. Iron weapon damage is *enhanced*.",
   "**Wail**: Anyone in earshot must make a WIL save or fall unconscious."
  ]
 },
 {
  "id": "basilisk",
  "name": "Basilisk",
  "group": "Lizard",
  "unmodelled": true,
  "hp": 10,
  "armor": 1,
  "STR": 12,
  "DEX": 13,
  "WIL": 13,
  "attacks": [
   {
    "name": "bite",
    "dice": [
     10
    ],
    "blast": false,
    "note": "d10"
   }
  ],
  "detachment": false,
  "stat": "10 HP, 1 Armor, 12 STR, 13 DEX, 13 WIL, bite (d10)",
  "notes": [
   "Long, serpentine lizards that nest deep below the earth or in brambles just underfoot.",
   "Fighting a **Basilisk** without meeting its gaze is difficult. (Attacks facing it are *impaired*.)",
   "**Gaze**: A target facing the Basilisk is slowly petrified from the bottom up and completely frozen after three rounds. An antidote can be brewed from the Basilisk’s gizzards. The creature’s reflection is harmless."
  ]
 },
 {
  "id": "blink-dog",
  "name": "Blink Dog",
  "group": "Magical",
  "unmodelled": true,
  "hp": 5,
  "armor": 0,
  "STR": 11,
  "DEX": 14,
  "WIL": 5,
  "attacks": [
   {
    "name": "bite",
    "dice": [
     6
    ],
    "blast": false,
    "note": "d6"
   }
  ],
  "detachment": false,
  "stat": "5 HP, 11 STR, 14 DEX, 5 WIL, bite (d6)",
  "notes": [
   "Teleporting canines in service of a powerful master.",
   "Can phase out of reality at will. Melee attacks against them are *impaired*."
  ]
 },
 {
  "id": "blood-elk",
  "name": "Blood Elk",
  "group": "Beast",
  "unmodelled": true,
  "hp": 4,
  "armor": 0,
  "STR": 12,
  "DEX": 13,
  "WIL": 5,
  "attacks": [
   {
    "name": "horns",
    "dice": [
     8
    ],
    "blast": false,
    "note": "d8"
   }
  ],
  "detachment": false,
  "stat": "4 HP, 12 STR, 13 DEX, 5 WIL, horns (d8)",
  "notes": [
   "Born from violence resulting from a greedy or selfish act.",
   "Kill their victims for sustenance, but gains no succor. They are always hungry.",
   "**Critical Damage**: Gores its victims by ripping out their entrails."
  ]
 },
 {
  "id": "boggart",
  "name": "Boggart",
  "group": "Fey",
  "unmodelled": true,
  "hp": 3,
  "armor": 0,
  "STR": 4,
  "DEX": 17,
  "WIL": 13,
  "attacks": [],
  "detachment": false,
  "stat": "3 HP, 4 STR, 17 DEX, 13 WIL",
  "notes": [
   "Wild, hairy tricksters that prize shiny trinkets above coin.",
   "Boggarts have true names that describe their true nature. Knowing these names gives a person control over them.",
   "**Magic**: The Boggart can *bring objects to life*, *sow confusion*, *create magical disguises*, use *telekinesis*, and *teleport*."
  ]
 },
 {
  "id": "bone-construct",
  "name": "Bone Construct",
  "group": "Construct",
  "unmodelled": false,
  "hp": 8,
  "armor": 3,
  "STR": 15,
  "DEX": 5,
  "WIL": 3,
  "attacks": [
   {
    "name": "sharpened arms",
    "dice": [
     8,
     8
    ],
    "blast": false,
    "note": "d8+d8"
   }
  ],
  "detachment": false,
  "stat": "8 HP, 3 Armor, 15 STR, 5 DEX, 3 WIL, sharpened arms (d8+d8), *detachment*",
  "notes": [
   "Gigantic, four-armed constructs made of bone and sorcery.",
   "Mindless guardians that stand ready to attack any creature other than their creator."
  ]
 },
 {
  "id": "bugbear",
  "name": "Bugbear",
  "group": "Goblinoid",
  "unmodelled": false,
  "hp": 8,
  "armor": 1,
  "STR": 14,
  "DEX": 12,
  "WIL": 11,
  "attacks": [
   {
    "name": "club",
    "dice": [
     8
    ],
    "blast": false,
    "note": "d8"
   }
  ],
  "detachment": false,
  "stat": "8 HP, 1 Armor, 14 STR, 12 DEX, 11 WIL, club (d8)",
  "notes": [
   "Large, goblin-like creatures covered in fur.",
   "Prefer stealth and trickery to gain an advantage.",
   "Often command parties of like creatures (typically goblins)."
  ]
 },
 {
  "id": "burrowing-horror",
  "name": "Burrowing Horror",
  "group": "Insectoid",
  "unmodelled": true,
  "hp": 6,
  "armor": 1,
  "STR": 16,
  "DEX": 11,
  "WIL": 4,
  "attacks": [
   {
    "name": "bite",
    "dice": [
     10
    ],
    "blast": false,
    "note": "d10"
   },
   {
    "name": "acid squirt",
    "dice": [
     8
    ],
    "blast": true,
    "note": "d8, *blast*"
   }
  ],
  "detachment": false,
  "stat": "6 HP, 1 Armor, 16 STR, 11 DEX, 4 WIL, bite (d10), acid squirt (d8, *blast*)",
  "notes": [
   "Huge insectoids with multiple legs and shiny black eyes. Subsist from dirt, roots, and flesh.",
   "Burrow just beneath surfaces to ambush unsuspecting creatures.",
   "**Critical Damage**: Target loses a body part. Roll 1d6. 1: Head, 2-4: Leg, 5-6: Arm."
  ]
 },
 {
  "id": "cave-locust",
  "name": "Cave Locust",
  "group": "Insectoid",
  "unmodelled": true,
  "hp": 2,
  "armor": 0,
  "STR": 6,
  "DEX": 12,
  "WIL": 3,
  "attacks": [
   {
    "name": "bite",
    "dice": [
     6
    ],
    "blast": false,
    "note": "d6"
   }
  ],
  "detachment": false,
  "stat": "2 HP, 6 STR, 12 DEX, 3 WIL, bite (d6)",
  "notes": [
   "Giant plant-eating crickets that dwell in caves. Immune to most types of poison.",
   "Their natural coloration allows them to blend in with the stone. They emit loud shrieks when threatened."
  ]
 },
 {
  "id": "centaur",
  "name": "Centaur",
  "group": "Hybrid",
  "unmodelled": false,
  "hp": 6,
  "armor": 1,
  "STR": 14,
  "DEX": 12,
  "WIL": 14,
  "attacks": [
   {
    "name": "spear",
    "dice": [
     8
    ],
    "blast": false,
    "note": "d8"
   },
   {
    "name": "short bow",
    "dice": [
     6
    ],
    "blast": false,
    "note": "d6"
   }
  ],
  "detachment": false,
  "stat": "6 HP, 1 Armor, 14 STR, 12 DEX, 14 WIL, spear (d8) or short bow (d6)",
  "notes": [
   "Creatures with the lower body and legs of a horse, but a humanoid upper body.",
   "Rarely found alone, preferring the company of their own."
  ]
 },
 {
  "id": "cobblehounds",
  "name": "Cobblehounds",
  "group": "Construct",
  "unmodelled": false,
  "hp": 12,
  "armor": 2,
  "STR": 14,
  "DEX": 1,
  "WIL": 8,
  "attacks": [
   {
    "name": "bite",
    "dice": [
     10
    ],
    "blast": false,
    "note": "d10"
   }
  ],
  "detachment": false,
  "stat": "12 HP, 2 Armor, 14 STR, 1 DEX, 8 WIL, bite (d10)",
  "notes": [
   "Immobile constructs typically used as guardians to great tombs or artifacts.",
   "Unaffected by mundane persuasion techniques, but love a good bone."
  ]
 },
 {
  "id": "creeping-vines",
  "name": "Creeping Vines",
  "group": "Plant",
  "unmodelled": true,
  "hp": 8,
  "armor": 0,
  "STR": 10,
  "DEX": 12,
  "WIL": 2,
  "attacks": [
   {
    "name": "vines",
    "dice": [
     4
    ],
    "blast": true,
    "note": "d4, *blast*"
   }
  ],
  "detachment": false,
  "stat": "8 HP, 10 STR, 12 DEX, 2 WIL, vines (d4, *blast*)",
  "notes": [
   "Appear as an inert, typical vine. Attacks passing creatures to use their corpses as fertilizer.",
   "**Critical Damage**: Target is pulled into the air where they asphyxiate within a few minutes."
  ]
 },
 {
  "id": "crypt-guardian",
  "name": "Crypt Guardian",
  "group": "Undead",
  "unmodelled": true,
  "hp": 12,
  "armor": 0,
  "STR": 12,
  "DEX": 11,
  "WIL": 14,
  "attacks": [
   {
    "name": "ethereal claws",
    "dice": [
     8,
     8
    ],
    "blast": false,
    "note": "d8+d8"
   }
  ],
  "detachment": false,
  "stat": "12 HP, 12 STR, 11 DEX, 14 WIL, ethereal claws (d8+d8)",
  "notes": [
   "Animated skeletons clothed in billowing robes. Their eye sockets are hypnotically red. Defend crypts and tombs, but will not attack if left undisturbed.",
   "Non-magical attacks against them are *impaired*.",
   "Can teleport any target in eyesight to a random room nearby."
  ]
 },
 {
  "id": "dryad",
  "name": "Dryad",
  "group": "Fey",
  "unmodelled": true,
  "hp": 4,
  "armor": 0,
  "STR": 8,
  "DEX": 12,
  "WIL": 14,
  "attacks": [
   {
    "name": "knotted arms",
    "dice": [
     6
    ],
    "blast": false,
    "note": "d6"
   }
  ],
  "detachment": false,
  "stat": "4 HP, 8 STR, 12 DEX, 14 WIL, knotted arms (d6)",
  "notes": [
   "Shy, protective tree spirits that manifest as beautiful, green-skinned humanoids.",
   "Unable to travel far from the tree they are bound to. They perish if the tree is destroyed.",
   "**Befuddle**: Target becomes confused, gradually moving further and further away from the host tree. WIL save once per round to break free."
  ]
 },
 {
  "id": "ettin",
  "name": "Ettin",
  "group": "Giant",
  "unmodelled": false,
  "hp": 10,
  "armor": 0,
  "STR": 16,
  "DEX": 8,
  "WIL": 6,
  "attacks": [
   {
    "name": "club",
    "dice": [
     10
    ],
    "blast": false,
    "note": "d10"
   }
  ],
  "detachment": false,
  "stat": "10 HP, 16 STR, 8 DEX, 6 WIL, club (d10)",
  "notes": [
   "The two-headed kin of giants. Prefer caves and underground hovels.",
   "Cannot be surprised."
  ]
 },
 {
  "id": "eye-of-terror",
  "name": "Eye of Terror",
  "group": "Extraplanar",
  "unmodelled": true,
  "hp": 15,
  "armor": 0,
  "STR": 9,
  "DEX": 8,
  "WIL": 16,
  "attacks": [
   {
    "name": "bite",
    "dice": [
     8
    ],
    "blast": false,
    "note": "d8"
   }
  ],
  "detachment": false,
  "stat": "15 HP, 9 STR, 8 DEX, 16 WIL, bite (d8)",
  "notes": [
   "Floating spheres with large mouths, enormous eyes, and several small eyes set atop long stalks.",
   "They are highly intelligent, intensely greedy, and completely insane.",
   "Can cast the following spells at will: *Charm, Phobia, Telekinesis, Sleep, Shuffle, Vision*. Magic used against them requires a WIL save or it fizzles out."
  ]
 },
 {
  "id": "frost-elf",
  "name": "Frost Elf",
  "group": "Fey",
  "unmodelled": true,
  "hp": 14,
  "armor": 1,
  "STR": 8,
  "DEX": 13,
  "WIL": 14,
  "attacks": [
   {
    "name": "icicle dagger",
    "dice": [
     6
    ],
    "blast": false,
    "note": "d6"
   }
  ],
  "detachment": false,
  "stat": "14 HP, 1 Armor, 8 STR, 13 DEX, 14 WIL, icicle dagger (d6)",
  "notes": [
   "Beautiful, amoral, and long-lived.",
   "Resistant to most forms of magic.",
   "Can cast the following spells at will: *Sleep*, *Teleport*, *Detect Magic*."
  ]
 },
 {
  "id": "gargoyle",
  "name": "Gargoyle",
  "group": "Construct",
  "unmodelled": true,
  "hp": 8,
  "armor": 3,
  "STR": 14,
  "DEX": 4,
  "WIL": 12,
  "attacks": [
   {
    "name": "claws",
    "dice": [
     8,
     8
    ],
    "blast": false,
    "note": "d8+d8"
   }
  ],
  "detachment": false,
  "stat": "8 HP, 3 Armor, 14 STR, 4 DEX, 12 WIL, claws (d8+d8)",
  "notes": [
   "Magical, slow-moving statues of monstrous winged creatures, typically employed as guards or watchdogs.",
   "Prowl at nights but fear the day, when the sun’s light freezes them in place.",
   "Immune to charms and magical sleep."
  ]
 },
 {
  "id": "gelatinous-ooze",
  "name": "Gelatinous Ooze",
  "group": "Unusual",
  "unmodelled": true,
  "hp": 8,
  "armor": 1,
  "STR": 15,
  "DEX": 6,
  "WIL": 3,
  "attacks": [
   {
    "name": "devouring touch",
    "dice": [
     8
    ],
    "blast": false,
    "note": "d8"
   }
  ],
  "detachment": false,
  "stat": "8 HP, 1 Armor, 15 STR, 6 DEX, 3 WIL, devouring touch (d8)",
  "notes": [
   "Large shapeless masses of transparent jelly. Mindlessly hunt for food in dungeons and underground caverns.",
   "**Critical Damage**: The target is engulfed, losing d6 STR damage per round until they are consumed."
  ]
 },
 {
  "id": "ghost",
  "name": "Ghost",
  "group": "Undead",
  "unmodelled": true,
  "hp": 8,
  "armor": 0,
  "STR": 14,
  "DEX": 12,
  "WIL": 15,
  "attacks": [
   {
    "name": "life drain",
    "dice": [
     6
    ],
    "blast": false,
    "note": "d6"
   }
  ],
  "detachment": false,
  "stat": "8 HP, 14 STR, 12 DEX, 15 WIL, life drain (d6)",
  "notes": [
   "Incorporeal spirits of the restless dead, vulnerable only to magic and specific anointed rites.",
   "**Critical Damage**: Target must save WIL or is possessed, acting only on behalf of the ghost’s whims."
  ]
 },
 {
  "id": "ghoul",
  "name": "Ghoul",
  "group": "Undead",
  "unmodelled": true,
  "hp": 6,
  "armor": 0,
  "STR": 14,
  "DEX": 8,
  "WIL": 3,
  "attacks": [
   {
    "name": "elongated claws",
    "dice": [
     6,
     6
    ],
    "blast": false,
    "note": "d6+d6"
   }
  ],
  "detachment": false,
  "stat": "6 HP, 14 STR, 8 DEX, 3 WIL, elongated claws (d6+d6)",
  "notes": [
   "Grey-skinned man-things wearing shredded clothes that crave only the flesh of the living.",
   "**Critical Damage**: Target is *deprived* from their necrotic wound, dying in d4 days unless treated by a priest or skilled healer. If the body is not burned it later rises as a Ghoul as well."
  ]
 },
 {
  "id": "giant-scorpion",
  "name": "Giant Scorpion",
  "group": "Insectoid",
  "unmodelled": true,
  "hp": 8,
  "armor": 1,
  "STR": 11,
  "DEX": 12,
  "WIL": 4,
  "attacks": [
   {
    "name": "claws",
    "dice": [
     10,
     10
    ],
    "blast": false,
    "note": "d10+d10"
   }
  ],
  "detachment": false,
  "stat": "8 HP, 1 Armor, 11 STR, 12 DEX, 4 WIL, claws (d10+d10)",
  "notes": [
   "Horse-sized arachnids commonly found in dry terrain or caverns.",
   "**Critical Damage**: The stinger’s poison liquefies the target’s insides for an additional d8 STR damage. The STR loss is permanent."
  ]
 },
 {
  "id": "gnoll",
  "name": "Gnoll",
  "group": "Humanoid",
  "unmodelled": false,
  "hp": 6,
  "armor": 1,
  "STR": 12,
  "DEX": 14,
  "WIL": 8,
  "attacks": [
   {
    "name": "spear",
    "dice": [
     8
    ],
    "blast": false,
    "note": "d8"
   }
  ],
  "detachment": true,
  "stat": "6 HP, 1 Armor, 12 STR, 14 DEX, 8 WIL, spear (d8)",
  "notes": [
   "Ferocious humanoid hyenas spawned from arcane experiments long ago.",
   "Deadly warriors, they attack as a pack (as *detachment*) or on their own."
  ]
 },
 {
  "id": "goblin",
  "name": "Goblin",
  "group": "Goblinoid",
  "unmodelled": false,
  "hp": 4,
  "armor": 0,
  "STR": 8,
  "DEX": 12,
  "WIL": 8,
  "attacks": [
   {
    "name": "dagger",
    "dice": [
     6
    ],
    "blast": false,
    "note": "d6"
   },
   {
    "name": "sling",
    "dice": [
     6
    ],
    "blast": false,
    "note": "d6"
   }
  ],
  "detachment": false,
  "stat": "4 HP, 8 STR, 12 DEX, 8 WIL, dagger (d6) or sling (d6)",
  "notes": [
   "Small, grotesque humanoids with skin in earthly tones of green, brown, and grey.",
   "Avoid combat, only attacking when advantageous, using hit-and-run tactics.",
   "Sometimes are found using dire wolves as mounts."
  ]
 },
 {
  "id": "green-dragon",
  "name": "Green Dragon",
  "group": "Behemoth",
  "unmodelled": true,
  "hp": 12,
  "armor": 2,
  "STR": 14,
  "DEX": 15,
  "WIL": 18,
  "attacks": [
   {
    "name": "bite",
    "dice": [
     12
    ],
    "blast": false,
    "note": "d12"
   }
  ],
  "detachment": false,
  "stat": "12 HP, 2 Armor, 14 STR, 15 DEX, 18 WIL, bite (d12), *detachment*",
  "notes": [
   "Forest-dwelling snakes topped with tall green scales. Collect great hoards of treasure.",
   "Use intelligence and cunning to manipulate the weak into their service.",
   "**Chlorine Gas**: Anyone nearby must make a DEX save to escape its reach or lose 1d4 STR and becomes *deprived*."
  ]
 },
 {
  "id": "griffon",
  "name": "Griffon",
  "group": "Mythical",
  "unmodelled": true,
  "hp": 7,
  "armor": 0,
  "STR": 14,
  "DEX": 15,
  "WIL": 12,
  "attacks": [
   {
    "name": "claws",
    "dice": [
     6,
     6
    ],
    "blast": false,
    "note": "d6+d6"
   }
  ],
  "detachment": false,
  "stat": "7 HP, 14 STR, 15 DEX, 12 WIL, claws (d6+d6), *detachment*",
  "notes": [
   "Ravenous hybrids, with the head and wings of an eagle and the lower body of a lion.",
   "Can be used as mounts if taken young and properly trained.",
   "Fly and attack at astonishing speeds, diving in to scoop up their prey.",
   "**Critical Damage**: Tears flesh and bone from its victim with its razor-sharp beak."
  ]
 },
 {
  "id": "grizzly-bear",
  "name": "Grizzly Bear",
  "group": "Beast",
  "unmodelled": true,
  "hp": 6,
  "armor": 0,
  "STR": 15,
  "DEX": 13,
  "WIL": 5,
  "attacks": [
   {
    "name": "claws",
    "dice": [
     8,
     8
    ],
    "blast": false,
    "note": "d8+d8"
   }
  ],
  "detachment": false,
  "stat": "6 HP, 15 STR, 13 DEX, 5 WIL, claws (d8+d8)",
  "notes": [
   "Reddish-brown bears commonly found in mountains, woodlands, and prairies.",
   "Prefer to eat fish and meat, and will attack the rare unfortunate who crosses their path.",
   "**Critical Damage**: Bites the victim for an additional d6 STR damage. They bleed out very quickly."
  ]
 },
 {
  "id": "harpy",
  "name": "Harpy",
  "group": "Mythical",
  "unmodelled": true,
  "hp": 8,
  "armor": 0,
  "STR": 7,
  "DEX": 12,
  "WIL": 14,
  "attacks": [
   {
    "name": "claws",
    "dice": [
     6,
     6
    ],
    "blast": false,
    "note": "d6+d6"
   }
  ],
  "detachment": false,
  "stat": "8 HP, 7 STR, 12 DEX, 14 WIL, claws (d6+d6)",
  "notes": [
   "Hideous monstrosities with the body of a giant eagle and a humanoid head.",
   "Their movements and flight are clumsy due to their disproportionate size. Rely on charmed victims to do anything of note.",
   "**Song**: Anyone nearby must save WIL or be charmed by its voice, following the harpy and defending it from any threat."
  ]
 },
 {
  "id": "hellhound",
  "name": "Hellhound",
  "group": "Demon",
  "unmodelled": true,
  "hp": 8,
  "armor": 0,
  "STR": 12,
  "DEX": 15,
  "WIL": 9,
  "attacks": [
   {
    "name": "bite",
    "dice": [
     8
    ],
    "blast": false,
    "note": "d8"
   },
   {
    "name": "fire breath",
    "dice": [
     6
    ],
    "blast": true,
    "note": "d6, *blast*"
   }
  ],
  "detachment": false,
  "stat": "8 HP, 12 STR, 15 DEX, 9 WIL, bite (d8), fire breath (d6, *blast*)",
  "notes": [
   "Monstrous, intelligent dogs that dwell near volcanoes.",
   "Immune to fire and heat damage. Hot enough to melt iron simply by biting it."
  ]
 },
 {
  "id": "hobgoblin",
  "name": "Hobgoblin",
  "group": "Goblinoid",
  "unmodelled": true,
  "hp": 6,
  "armor": 2,
  "STR": 14,
  "DEX": 8,
  "WIL": 11,
  "attacks": [
   {
    "name": "mace",
    "dice": [
     8
    ],
    "blast": false,
    "note": "d8"
   }
  ],
  "detachment": false,
  "stat": "6 HP, 2 Armor, 14 STR, 8 DEX, 11 WIL, mace (d8)",
  "notes": [
   "Large and burly relatives of goblins. Dwell in underground fortresses until called for war.",
   "Automatically succeed in Morale Saves if a commander is present.",
   "Trained to fight together. Damage dealt is *enhanced* if an ally is also engaged with the same enemy."
  ]
 },
 {
  "id": "hooded-men",
  "name": "Hooded Men",
  "group": "Humanoid",
  "unmodelled": true,
  "hp": 12,
  "armor": 0,
  "STR": 9,
  "DEX": 12,
  "WIL": 14,
  "attacks": [
   {
    "name": "leystaff",
    "dice": [
     8
    ],
    "blast": false,
    "note": "d8"
   }
  ],
  "detachment": false,
  "stat": "12 HP, 9 STR, 12 DEX, 14 WIL, leystaff (d8)",
  "notes": [
   "The Watchers of the Wood; a cult that derive their power from leylines, rune stones, and the like.",
   "**Critical Damage**: Leech a part of the victim’s soul (1d4 WIL damage).",
   "Carries two of the following spellbooks: *Charm, Hypnotize, Push/Pull, Shield*."
  ]
 },
 {
  "id": "hydra",
  "name": "Hydra",
  "group": "Mythical",
  "unmodelled": false,
  "hp": 12,
  "armor": 2,
  "STR": 13,
  "DEX": 7,
  "WIL": 12,
  "attacks": [
   {
    "name": "bite",
    "dice": [
     12
    ],
    "blast": true,
    "note": "d12, *blast*"
   }
  ],
  "detachment": false,
  "stat": "12 HP, 2 Armor, 13 STR, 7 DEX, 12 WIL, bite (d12, *blast*), *detachment*",
  "notes": [
   "Large reptilians with nine serpentine heads. Very difficult to throw off once their quarry is detected.",
   "On taking **Critical Damage**, the hydra loses one head. It then continues fighting until no heads remains."
  ]
 },
 {
  "id": "invisible-stalker",
  "name": "Invisible Stalker",
  "group": "Incorporeal",
  "unmodelled": true,
  "hp": 8,
  "armor": 0,
  "STR": 12,
  "DEX": 12,
  "WIL": 15,
  "attacks": [
   {
    "name": "fists",
    "dice": [
     4,
     4
    ],
    "blast": false,
    "note": "d4+d4"
   }
  ],
  "detachment": false,
  "stat": "8 HP, 12 STR, 12 DEX, 15 WIL, fists (d4+d4)",
  "notes": [
   "Intelligent beings shaped into reality by a powerful wizard. Completely invisible and silent.",
   "Attacks deal direct STR damage (subtracting Armor)."
  ]
 },
 {
  "id": "killer-bees",
  "name": "Killer Bees",
  "group": "Beast",
  "unmodelled": false,
  "hp": 6,
  "armor": 0,
  "STR": 6,
  "DEX": 14,
  "WIL": 8,
  "attacks": [
   {
    "name": "sting",
    "dice": [
     6
    ],
    "blast": false,
    "note": "d6"
   }
  ],
  "detachment": false,
  "stat": "6 HP, 6 STR, 14 DEX, 8 WIL, sting (d6), *detachment*",
  "notes": [
   "Oversized bees that build underground hives. Hyper-aggressive, attack anything that comes near.",
   "Produce special honey that heals 1d6 STR. 3 uses.",
   "When the bees cause STR damage, the stingers are lodged into the target, dealing d4 damage each round until removed."
  ]
 },
 {
  "id": "kobold",
  "name": "Kobold",
  "group": "Lizard",
  "unmodelled": false,
  "hp": 3,
  "armor": 0,
  "STR": 8,
  "DEX": 13,
  "WIL": 4,
  "attacks": [
   {
    "name": "bite",
    "dice": [
     6
    ],
    "blast": false,
    "note": "d6"
   },
   {
    "name": "spear",
    "dice": [
     8
    ],
    "blast": false,
    "note": "d8"
   }
  ],
  "detachment": false,
  "stat": "3 HP, 8 STR, 13 DEX, 4 WIL, bite (d6), spear (d8)",
  "notes": [
   "Hairless humanoids with canine-like features and scaly skin. Can see perfectly in the dark, but are harmed by direct sunlight.",
   "Use traps and ambush to defeat opponents. Often act in service of a more powerful creatures."
  ]
 },
 {
  "id": "lamia",
  "name": "Lamia",
  "group": "Mythical",
  "unmodelled": true,
  "hp": 6,
  "armor": 0,
  "STR": 11,
  "DEX": 12,
  "WIL": 16,
  "attacks": [
   {
    "name": "toothy bite",
    "dice": [
     8
    ],
    "blast": false,
    "note": "d8"
   }
  ],
  "detachment": false,
  "stat": "6 HP, 11 STR, 12 DEX, 16 WIL, toothy bite (d8)",
  "notes": [
   "Centaur-like creatures that prey on the life force of others, seducing their victims through heightened charm and intelligence. Their upper bodies are typically humanoid, the lower half any number of animal hybrids.",
   "Inherently magical. Can create illusions, charm creatures, and disguise themselves at will.",
   "**Critical Damage**: The target takes d6 WIL damage as their spirit is slowly sapped away. They then become enthralled to the Lamia, obeying its every command while in its presence."
  ]
 },
 {
  "id": "lich",
  "name": "Lich",
  "group": "Undead",
  "unmodelled": true,
  "hp": 14,
  "armor": 1,
  "STR": 8,
  "DEX": 8,
  "WIL": 18,
  "attacks": [
   {
    "name": "soul dagger",
    "dice": [
     8
    ],
    "blast": false,
    "note": "d8"
   }
  ],
  "detachment": false,
  "stat": "14 HP, 1 Armor, 8 STR, 8 DEX, 18 WIL, soul dagger (d8)",
  "notes": [
   "Powerful sorcerers that paid the ultimate price for immortality: their own life. Now their thirst for power knows no bounds.",
   "Maintain unlife by binding themselves to an earthly artifact, which is typically protected by at least d6 other undead servants.",
   "Carry up to six of the following spellbooks: *Animate Object*, *Arcane Eye*, *Deafen*, *Disassemble*, *Elemental Wall*, *Frenzy*, *Gate*, *Hover*, *Hatred*, *Identify Owner*, *Knock*, *Pacify*, *Raise Dead*, *Raise Spirit*, *Shield*, *Sleep*, *Smoke Form*, *Telekinesis*, *Telepathy*, *Teleport*, *Vision*, *Wizard Mark*."
  ]
 },
 {
  "id": "manticore",
  "name": "Manticore",
  "group": "Hybrid",
  "unmodelled": true,
  "hp": 6,
  "armor": 0,
  "STR": 15,
  "DEX": 14,
  "WIL": 12,
  "attacks": [
   {
    "name": "claws",
    "dice": [
     6,
     6
    ],
    "blast": false,
    "note": "d6+d6"
   },
   {
    "name": "tail spike",
    "dice": [
     8
    ],
    "blast": false,
    "note": "d8"
   }
  ],
  "detachment": false,
  "stat": "6 HP, 15 STR, 14 DEX, 12 WIL, claws (d6+d6), tail spike (d8)",
  "notes": [
   "Spiteful monstrosities that wear a humanoid face, a lion’s body, wings of a bat, and a scorpion’s tail. Dwell in mountainous regions, abandoned castles, and forgotten dungeons.",
   "Tail spikes act like darts, regrowing after a few days. A single spike is worth 150gp to a collector.",
   "**Critical Damage**: Target is *deprived* until they get a good night’s sleep. Until then, they act boorish, selfish, and cruel (or more so, if that already is their nature)."
  ]
 },
 {
  "id": "mimic",
  "name": "Mimic",
  "group": "Unusual",
  "unmodelled": false,
  "hp": 9,
  "armor": 2,
  "STR": 13,
  "DEX": 6,
  "WIL": 12,
  "attacks": [
   {
    "name": "bite",
    "dice": [
     8
    ],
    "blast": false,
    "note": "d8"
   }
  ],
  "detachment": false,
  "stat": "9 HP, 2 Armor, 13 STR, 6 DEX, 12 WIL, bite (d8)",
  "notes": [
   "Malicious shape shifters that take on the form of inanimate objects commonly found in dungeons.",
   "Remain motionless while in disguise, surprising anyone that comes near.",
   "The mimic’s saliva is extremely sticky and difficult to remove. Alchemists will pay up to 150gp for even the smallest vial."
  ]
 },
 {
  "id": "mind-lasher",
  "name": "Mind Lasher",
  "group": "Extraplanar",
  "unmodelled": true,
  "hp": 12,
  "armor": 0,
  "STR": 8,
  "DEX": 12,
  "WIL": 18,
  "attacks": [
   {
    "name": "tentacles",
    "dice": [
     6
    ],
    "blast": true,
    "note": "d6, *blast*"
   }
  ],
  "detachment": false,
  "stat": "12 HP, 8 STR, 12 DEX, 18 WIL, tentacles (d6, *blast*)",
  "notes": [
   "Humanoid creatures with purple skin and squid-like heads. Dwell deep underground or in spacefaring vessels. Feed on the brains of other humanoids, absorbing their memories and life essence. Highly intelligent, but evil beyond belief.",
   "**Mind Blast**: Nearby targets must save WIL or lose 1d4 WIL and become paralyzed.",
   "**Critical Damage**: A tentacle rips the victim’s brain out of their skull."
  ]
 },
 {
  "id": "minotaur",
  "name": "Minotaur",
  "group": "Hybrid",
  "unmodelled": false,
  "hp": 12,
  "armor": 1,
  "STR": 16,
  "DEX": 12,
  "WIL": 8,
  "attacks": [
   {
    "name": "two-handed axe",
    "dice": [
     10
    ],
    "blast": false,
    "note": "d10"
   },
   {
    "name": "charge",
    "dice": [
     12
    ],
    "blast": false,
    "note": "d12"
   }
  ],
  "detachment": false,
  "stat": "12 HP, 1 Armor, 16 STR, 12 DEX, 8 WIL, two-handed axe (d10), charge (d12)",
  "notes": [
   "Large humanoids (typically male) with the head of a bull. Dwell in mazes or dungeons.",
   "Extraordinary trackers with an excellent sense of smell and navigation skills."
  ]
 },
 {
  "id": "mummy",
  "name": "Mummy",
  "group": "Undead",
  "unmodelled": true,
  "hp": 6,
  "armor": 0,
  "STR": 12,
  "DEX": 8,
  "WIL": 6,
  "attacks": [
   {
    "name": "necrotic touch",
    "dice": [
     10
    ],
    "blast": false,
    "note": "d10"
   }
  ],
  "detachment": false,
  "stat": "6 HP, 12 STR, 8 DEX, 6 WIL, necrotic touch (d10)",
  "notes": [
   "Undead humanoids wrapped in funerary cloth. Found in pyramids, ruins, temples, and tombs.",
   "**Critical Damage**: Target is infected with mummy rot, and is unable to recover STR until they are cured by a specialist healer. The target is also *deprived*."
  ]
 },
 {
  "id": "naga",
  "name": "Naga",
  "group": "Lizard",
  "unmodelled": true,
  "hp": 6,
  "armor": 1,
  "STR": 14,
  "DEX": 12,
  "WIL": 14,
  "attacks": [
   {
    "name": "sword",
    "dice": [
     6
    ],
    "blast": false,
    "note": "d6"
   },
   {
    "name": "bite",
    "dice": [
     10
    ],
    "blast": false,
    "note": "d10"
   }
  ],
  "detachment": false,
  "stat": "6 HP, 1 Armor, 14 STR, 12 DEX, 14 WIL, sword (d6), bite (d10)",
  "notes": [
   "Humanoids with the lower body, tail, and neck of snakes. Dwell in hot jungles and temples lost to time.",
   "Use cunning and hypnosis to capture other creatures to be enslaved.",
   "**Gaze**: A target facing the Naga is hypnotized, falling under its will. Its victims cannot be compelled to violence."
  ]
 },
 {
  "id": "night-cat",
  "name": "Night Cat",
  "group": "Beast",
  "unmodelled": true,
  "hp": 6,
  "armor": 0,
  "STR": 9,
  "DEX": 14,
  "WIL": 5,
  "attacks": [
   {
    "name": "claws",
    "dice": [
     6,
     6
    ],
    "blast": false,
    "note": "d6+d6"
   }
  ],
  "detachment": false,
  "stat": "6 HP, 9 STR, 14 DEX, 5 WIL, claws (d6+d6)",
  "notes": [
   "Intelligent, nocturnal marsupials that make their homes in forests and swamps. Hunt in packs.",
   "Critical Damage: The Night Cat begins to eat the target (d4 STR damage) while they are still alive."
  ]
 },
 {
  "id": "night-hag",
  "name": "Night Hag",
  "group": "Fey",
  "unmodelled": true,
  "hp": 8,
  "armor": 0,
  "STR": 9,
  "DEX": 11,
  "WIL": 16,
  "attacks": [
   {
    "name": "talons",
    "dice": [
     8,
     8
    ],
    "blast": false,
    "note": "d8+d8"
   }
  ],
  "detachment": false,
  "stat": "8 HP, 9 STR, 11 DEX, 16 WIL, talons (d8+d8)",
  "notes": [
   "Hideous old women that dwell in dead forests, swamps, and bogs.",
   "Carry three of the following spellbooks: *Arcane Eye*, *Disguise*, *Fog Cloud*, *Identify Owner*, *Smoke Form*."
  ]
 },
 {
  "id": "nightmare",
  "name": "Nightmare",
  "group": "Demon",
  "unmodelled": true,
  "hp": 8,
  "armor": 0,
  "STR": 15,
  "DEX": 12,
  "WIL": 8,
  "attacks": [
   {
    "name": "flaming hooves",
    "dice": [
     8,
     8
    ],
    "blast": false,
    "note": "d8+d8"
   }
  ],
  "detachment": false,
  "stat": "8 HP, 15 STR, 12 DEX, 8 WIL, flaming hooves (d8+d8)",
  "notes": [
   "Intelligent, demonic horses with eyes like burning coals, smoldering nostrils, and flaming hooves.",
   "Melee attacks against the Nightmare are *impaired* due to the thick clouds of smoke it produces."
  ]
 },
 {
  "id": "ogre",
  "name": "Ogre",
  "group": "Goblinoid",
  "unmodelled": false,
  "hp": 6,
  "armor": 1,
  "STR": 16,
  "DEX": 8,
  "WIL": 6,
  "attacks": [
   {
    "name": "club",
    "dice": [
     10
    ],
    "blast": false,
    "note": "d10"
   }
  ],
  "detachment": false,
  "stat": "6 HP, 1 Armor, 16 STR, 8 DEX, 6 WIL, club (d10)",
  "notes": [
   "Massive, gluttonous brutes of ill-spirit and low intelligence.",
   "Easily impressed by shiny materials, keeping sacks of gold and treasure in their lairs."
  ]
 },
 {
  "id": "owlbear",
  "name": "Owlbear",
  "group": "Hybrid",
  "unmodelled": true,
  "hp": 9,
  "armor": 0,
  "STR": 16,
  "DEX": 12,
  "WIL": 5,
  "attacks": [
   {
    "name": "beak",
    "dice": [
     10
    ],
    "blast": false,
    "note": "d10"
   },
   {
    "name": "claws",
    "dice": [
     8,
     8
    ],
    "blast": false,
    "note": "d8+d8"
   }
  ],
  "detachment": false,
  "stat": "9 HP, 16 STR, 12 DEX, 5 WIL, beak (d10), claws (d8+d8)",
  "notes": [
   "Bear-like carnivores with the face of an owl. Found in dense forests. Rumored spawn of a magical mishap.",
   "**Critical Damage**: A piece of armor is rent and destroyed."
  ]
 },
 {
  "id": "phoenix",
  "name": "Phoenix",
  "group": "Avian",
  "unmodelled": false,
  "hp": 4,
  "armor": 0,
  "STR": 15,
  "DEX": 13,
  "WIL": 12,
  "attacks": [
   {
    "name": "talons",
    "dice": [
     10,
     10
    ],
    "blast": false,
    "note": "d10+d10"
   }
  ],
  "detachment": false,
  "stat": "4 HP, 15 STR, 13 DEX, 12 WIL, talons (d10+d10)",
  "notes": [
   "Intelligent, hawk-like spirits of pure flame, found in isolated deserts and high mountains.",
   "If killed, they explode in a burst of flames. They are reborn 1d3 days later from the ashes.",
   "Their feathers are highly-sought after for their healing properties."
  ]
 },
 {
  "id": "pixie",
  "name": "Pixie",
  "group": "Fey",
  "unmodelled": true,
  "hp": 3,
  "armor": 0,
  "STR": 3,
  "DEX": 15,
  "WIL": 13,
  "attacks": [],
  "detachment": false,
  "stat": "3 HP, 3 STR, 15 DEX, 13 WIL",
  "notes": [
   "Tiny humanoids with insectoid wings. Naturally invisible.",
   "Can cast *Sleep* and *Masquerade* at will."
  ]
 },
 {
  "id": "purple-worm",
  "name": "Purple Worm",
  "group": "Behemoth",
  "unmodelled": true,
  "hp": 18,
  "armor": 1,
  "STR": 18,
  "DEX": 8,
  "WIL": 6,
  "attacks": [
   {
    "name": "bite",
    "dice": [
     12
    ],
    "blast": false,
    "note": "d12"
   }
  ],
  "detachment": false,
  "stat": "18 HP, 1 Armor, 18 STR, 8 DEX, 6 WIL, bite (d12), *detachment*",
  "notes": [
   "Gargantuan worms that lair in enormous burrows deep underground, only coming to the surface to eat. Found in high deserts and hot tundra.",
   "**Critical Damage**: The target is devoured, taking d8 STR damage from the acid in the worm’s stomach."
  ]
 },
 {
  "id": "red-cap",
  "name": "Red Cap",
  "group": "Fey",
  "unmodelled": true,
  "hp": 6,
  "armor": 0,
  "STR": 6,
  "DEX": 12,
  "WIL": 8,
  "attacks": [
   {
    "name": "dual sickles",
    "dice": [
     6,
     6
    ],
    "blast": false,
    "note": "d6+d6"
   }
  ],
  "detachment": false,
  "stat": "6 HP, 6 STR, 12 DEX, 8 WIL, dual sickles (d6+d6)",
  "notes": [
   "Born from blood left to rot in the land of Fairy. Their hats are a deep red from the blood they bathe in.",
   "Ignore those with little to live for, as there is no pleasure in their murder.",
   "**Critical Damage**: Target is eviscerated, the spray of their blood restoring STR loss suffered by the Red Cap."
  ]
 },
 {
  "id": "reptilian",
  "name": "Reptilian",
  "group": "Lizard",
  "unmodelled": false,
  "hp": 5,
  "armor": 1,
  "STR": 14,
  "DEX": 12,
  "WIL": 5,
  "attacks": [
   {
    "name": "bone spear",
    "dice": [
     8
    ],
    "blast": false,
    "note": "d8"
   }
  ],
  "detachment": false,
  "stat": "5 HP, 1 Armor, 14 STR, 12 DEX, 5 WIL, bone spear (d8)",
  "notes": [
   "Amphibian humanoids that live in large tribes near swamps and jungles.",
   "Craft their armor and weapons from the bones of their prey. They will eat anything, including humanoids."
  ]
 },
 {
  "id": "root-goblin",
  "name": "Root Goblin",
  "group": "Goblinoid",
  "unmodelled": true,
  "hp": 4,
  "armor": 0,
  "STR": 8,
  "DEX": 14,
  "WIL": 8,
  "attacks": [
   {
    "name": "spear",
    "dice": [
     6
    ],
    "blast": false,
    "note": "d6"
   }
  ],
  "detachment": false,
  "stat": "4 HP, 8 STR, 14 DEX, 8 WIL, spear (d6)",
  "notes": [
   "Avoid combat unless they have the advantage (such as greater numbers).",
   "Guard their stolen goods to the death.",
   "Root Goblins prize spellbooks and are always willing to trade."
  ]
 },
 {
  "id": "root-witch",
  "name": "Root Witch",
  "group": "Plant",
  "unmodelled": false,
  "hp": 8,
  "armor": 0,
  "STR": 9,
  "DEX": 16,
  "WIL": 14,
  "attacks": [
   {
    "name": "tuber-fingers",
    "dice": [
     6
    ],
    "blast": false,
    "note": "d6"
   }
  ],
  "detachment": false,
  "stat": "8 HP, 9 STR, 16 DEX, 14 WIL, tuber-fingers (d6)",
  "notes": [
   "Excellent tunnelers that hide underground near water. Wiggle tiny fronds into the air as lures.",
   "Above-ground, appear vaguely humanoid with the face of a rotted tree stump.",
   "Will exchange rare minerals for a “fresh corpse” of any kind."
  ]
 },
 {
  "id": "rust-monster",
  "name": "Rust Monster",
  "group": "Unusual",
  "unmodelled": true,
  "hp": 5,
  "armor": 0,
  "STR": 16,
  "DEX": 13,
  "WIL": 5,
  "attacks": [
   {
    "name": "bite",
    "dice": [
     6
    ],
    "blast": false,
    "note": "d6"
   }
  ],
  "detachment": false,
  "stat": "5 HP, 16 STR, 13 DEX, 5 WIL, bite (d6)",
  "notes": [
   "Armadillo-like creatures with club-like tails and long antennae. Feed on iron and rusted metal.",
   "Any mundane metals their antennae touch instantly become rust. Can smell metal from a long distance away.",
   "**Critical Damage**: Metal armor rusts into useless weight."
  ]
 },
 {
  "id": "sea-hag",
  "name": "Sea Hag",
  "group": "Fey",
  "unmodelled": true,
  "hp": 6,
  "armor": 0,
  "STR": 11,
  "DEX": 15,
  "WIL": 14,
  "attacks": [
   {
    "name": "long claws",
    "dice": [
     6,
     6
    ],
    "blast": false,
    "note": "d6+d6"
   }
  ],
  "detachment": false,
  "stat": "6 HP, 11 STR, 15 DEX, 14 WIL, long claws (d6+d6)",
  "notes": [
   "Ghostly, green-skinned hags that dwell in seaweed forests and warm shallow waters.",
   "Immune to magic from spellbooks.",
   "**Hideous Gaze**: A target is overcome with fear (HP drops to 0). WIL save each round to break the spell."
  ]
 },
 {
  "id": "shadow",
  "name": "Shadow",
  "group": "Incorporeal",
  "unmodelled": true,
  "hp": 14,
  "armor": 0,
  "STR": 1,
  "DEX": 18,
  "WIL": 14,
  "attacks": [
   {
    "name": "draining touch",
    "dice": [
     6
    ],
    "blast": false,
    "note": "d6, ignores armor"
   }
  ],
  "detachment": false,
  "stat": "14 HP, 1 STR, 18 DEX, 14 WIL, draining touch (d6, ignores armor)",
  "notes": [
   "Incorporeal monsters that look like animated shadows. Unharmed by mundane attacks, sleep or mind control.",
   "**Critical Damage**: Target loses d4 STR. If reduced to 0 STR, they become a shadow as well."
  ]
 },
 {
  "id": "shambling-mound",
  "name": "Shambling Mound",
  "group": "Plant",
  "unmodelled": true,
  "hp": 9,
  "armor": 0,
  "STR": 15,
  "DEX": 6,
  "WIL": 8,
  "attacks": [
   {
    "name": "tendrils",
    "dice": [
     8,
     8
    ],
    "blast": false,
    "note": "d8+d8"
   }
  ],
  "detachment": false,
  "stat": "9 HP, 15 STR, 6 DEX, 8 WIL, tendrils (d8+d8), *detachment*",
  "notes": [
   "Tall humanoids made of slimy vegetation. Dwell in dark swamps and damp undergrounds.",
   "**Critical Damage**: Target is swallowed whole and dragged away."
  ]
 },
 {
  "id": "skeleton",
  "name": "Skeleton",
  "group": "Undead",
  "unmodelled": false,
  "hp": 5,
  "armor": 1,
  "STR": 8,
  "DEX": 13,
  "WIL": 0,
  "attacks": [
   {
    "name": "rusty sword",
    "dice": [
     6
    ],
    "blast": false,
    "note": "d6"
   },
   {
    "name": "bow",
    "dice": [
     6
    ],
    "blast": false,
    "note": "d6"
   }
  ],
  "detachment": false,
  "stat": "5 HP, 1 Armor, 8 STR, 13 DEX, 0 WIL, rusty sword (d6) or bow (d6)",
  "notes": [
   "Frequently found serving a master or necromancer, often in groups of 3 or more.",
   "Found wearing whatever was on them at the time of their death.",
   "If a skeleton is killed and its bones are not scattered, it reforms."
  ]
 },
 {
  "id": "sky-giant",
  "name": "Sky Giant",
  "group": "Giant",
  "unmodelled": true,
  "hp": 12,
  "armor": 1,
  "STR": 16,
  "DEX": 12,
  "WIL": 14,
  "attacks": [
   {
    "name": "mace",
    "dice": [
     10
    ],
    "blast": false,
    "note": "d10"
   }
  ],
  "detachment": false,
  "stat": "12 HP, 1 Armor, 16 STR, 12 DEX, 14 WIL, mace (d10), *detachment*",
  "notes": [
   "Towering, white-skinned giants that live in castles high in the mountains.",
   "Missile attacks against them are *impaired* due to the powerful winds surrounding them."
  ]
 },
 {
  "id": "sphinx",
  "name": "Sphinx",
  "group": null,
  "unmodelled": true,
  "hp": 18,
  "armor": 0,
  "STR": 12,
  "DEX": 13,
  "WIL": 18,
  "attacks": [
   {
    "name": "claws",
    "dice": [
     8,
     8
    ],
    "blast": true,
    "note": "d8+d8, *blast*"
   },
   {
    "name": "beak",
    "dice": [
     10
    ],
    "blast": false,
    "note": "d10"
   }
  ],
  "detachment": false,
  "stat": "18 HP, 12 STR, 13 DEX, 18 WIL, claws (d8+d8, *blast*), beak (d10)",
  "notes": [
   "Mythical beasts with the upper body and head of a human, the wings of an eagle, and the body of a lion. Immune to magic of any kind.",
   "Poses riddles to anyone they meet. Failure to answer correctly is usually met with death. They know almost everything worth knowing.",
   "**Roar**: Anyone in earshot must save WIL or flee in fear."
  ]
 },
 {
  "id": "storm-giant",
  "name": "Storm Giant",
  "group": "Giant",
  "unmodelled": true,
  "hp": 18,
  "armor": 2,
  "STR": 18,
  "DEX": 16,
  "WIL": 18,
  "attacks": [
   {
    "name": "great sword",
    "dice": [
     12
    ],
    "blast": false,
    "note": "d12"
   }
  ],
  "detachment": false,
  "stat": "18 HP, 2 Armor, 18 STR, 16 DEX, 18 WIL, great sword (d12), *detachment*",
  "notes": [
   "Building-sized humanoids with bronze-hued skin and light-colored hair. Live on the highest mountain peaks and rockiest coastlines.",
   "Unharmed by lightning, can summon storm clouds at their will. Can fly with the wind as a their chariot.",
   "**Thunderclap**: Deals 4 STR damage against a single target. Targets wearing metal armor take double damage."
  ]
 },
 {
  "id": "swine-thing",
  "name": "Swine Thing",
  "group": "Shape Shifter",
  "unmodelled": true,
  "hp": 9,
  "armor": 0,
  "STR": 16,
  "DEX": 8,
  "WIL": 13,
  "attacks": [
   {
    "name": "gore",
    "dice": [
     6,
     6
    ],
    "blast": false,
    "note": "d6+d6"
   }
  ],
  "detachment": false,
  "stat": "9 HP, 16 STR, 8 DEX, 13 WIL, gore (d6+d6)",
  "notes": [
   "Obese humanoids that transform into massive porcine monstrosities to feast on human flesh.",
   "Prefer to hunt in isolated settlements close to forests and wetlands. Can only shapeshift at night.",
   "**Charm**: Target obeys the swine’s every command until it is killed. WIL save once per round to break free."
  ]
 },
 {
  "id": "titan",
  "name": "Titan",
  "group": "Giant",
  "unmodelled": false,
  "hp": 18,
  "armor": 3,
  "STR": 16,
  "DEX": 15,
  "WIL": 18,
  "attacks": [
   {
    "name": "lightning sword",
    "dice": [
     12
    ],
    "blast": false,
    "note": "d12"
   }
  ],
  "detachment": false,
  "stat": "18 HP, 3 Armor, 16 STR, 15 DEX, 18 WIL, lightning sword (d12), *detachment*",
  "notes": [
   "Mythical, humanoid giants of radiant beauty and powerfully athletic bodies. Beneficent of character, but prone to megalomania.",
   "Natives of other planes of existence, but sometimes have strongholds in the mortal world.",
   "Can levitate, shape shift, and sculpt elements at will."
  ]
 },
 {
  "id": "treant",
  "name": "Treant",
  "group": "Plant",
  "unmodelled": false,
  "hp": 10,
  "armor": 3,
  "STR": 15,
  "DEX": 3,
  "WIL": 12,
  "attacks": [
   {
    "name": "roots",
    "dice": [
     8,
     8
    ],
    "blast": true,
    "note": "d8+d8, *blast*"
   }
  ],
  "detachment": false,
  "stat": "10 HP, 3 Armor, 15 STR, 3 DEX, 12 WIL, roots (d8+d8, *blast*)",
  "notes": [
   "Sentient, bipedal trees with a vaguely humanoid face on their trunks. Found in the deepest part of the wood.",
   "Speak slowly and ponderously, with a deep voice. Timeless, living for thousands of years."
  ]
 },
 {
  "id": "triton",
  "name": "Triton",
  "group": "Humanoid",
  "unmodelled": false,
  "hp": 6,
  "armor": 0,
  "STR": 12,
  "DEX": 15,
  "WIL": 12,
  "attacks": [
   {
    "name": "trident",
    "dice": [
     8
    ],
    "blast": false,
    "note": "d8"
   }
  ],
  "detachment": false,
  "stat": "6 HP, 12 STR, 15 DEX, 12 WIL, trident (d8)",
  "notes": [
   "Aquatic humanoids with silvery skin, blue-green hair, and scaled legs ending in fins. Dwell in warmer waters close to land.",
   "Lair in beautiful castles sculpted from sea rock and coral. Command vast schools of fish for both protection and food."
  ]
 },
 {
  "id": "troll",
  "name": "Troll",
  "group": "Goblinoid",
  "unmodelled": true,
  "hp": 14,
  "armor": 1,
  "STR": 14,
  "DEX": 12,
  "WIL": 4,
  "attacks": [
   {
    "name": "bite",
    "dice": [
     10
    ],
    "blast": false,
    "note": "d10"
   },
   {
    "name": "claws",
    "dice": [
     8,
     8
    ],
    "blast": false,
    "note": "d8+d8"
   }
  ],
  "detachment": false,
  "stat": "14 HP, 1 Armor, 14 STR, 12 DEX, 4 WIL, bite (d10), claws (d8+d8)",
  "notes": [
   "Giant, warty humanoids of flesh and bark. Dwell underground or in deep forests, as well as the ruined homes of their former victims. Carnivorous.",
   "When taking **Critical Damage**, a Troll will continue fighting, despite loss of flesh and limb. Only when their STR is 0 are they truly killed. Unless their heads are bathed in acid, fire, or powerful magic, they will fully regenerate within 1d4 days."
  ]
 },
 {
  "id": "unicorn",
  "name": "Unicorn",
  "group": "Mythical",
  "unmodelled": false,
  "hp": 6,
  "armor": 0,
  "STR": 14,
  "DEX": 12,
  "WIL": 14,
  "attacks": [
   {
    "name": "horn",
    "dice": [
     10
    ],
    "blast": false,
    "note": "d10, ignores armor"
   }
  ],
  "detachment": false,
  "stat": "6 HP, 14 STR, 12 DEX, 14 WIL, horn (d10, ignores armor)",
  "notes": [
   "Magical horses with a single long horn on their foreheads. Timid, but proud and willful, are seen as divine beings.",
   "Their hair is worth a small fortune due to its powerful healing properties."
  ]
 },
 {
  "id": "vampire",
  "name": "Vampire",
  "group": "Undead",
  "unmodelled": true,
  "hp": 12,
  "armor": 1,
  "STR": 14,
  "DEX": 12,
  "WIL": 16,
  "attacks": [
   {
    "name": "bite",
    "dice": [
     10
    ],
    "blast": false,
    "note": "d10"
   }
  ],
  "detachment": false,
  "stat": "12 HP, 1 Armor, 14 STR, 12 DEX, 16 WIL, bite (d10)",
  "notes": [
   "Charming, undead creatures that drink the blood of mortals. Act at night and sleep in a coffin during the day. Can change into a bat at will.",
   "**Regeneration**: A damaged vampire regains 6 HP when it bites a target that has blood. If killed, it becomes a cloud of gas and retreats to its coffin, reforming at the next nightfall. Can only be killed if exposed to sunlight or if the coffin is destroyed.",
   "**Critical Damage**: The vampire drains the target’s essence, dealing d12 damage to WIL. If the target reaches 0 WIL this way, it dies and is raised as a thrall of the vampire."
  ]
 },
 {
  "id": "viper",
  "name": "Viper",
  "group": "Beast",
  "unmodelled": true,
  "hp": 3,
  "armor": 0,
  "STR": 5,
  "DEX": 12,
  "WIL": 3,
  "attacks": [
   {
    "name": "bite",
    "dice": [
     6
    ],
    "blast": false,
    "note": "d6"
   }
  ],
  "detachment": false,
  "stat": "3 HP, 5 STR, 12 DEX, 3 WIL, bite (d6)",
  "notes": [
   "Poisonous snakes often found in caves, pits, and other dark places. An antitoxin can be made from their poison sacs.",
   "Use heat and smell to track their victims.",
   "**Critical Damage**: Target is poisoned, dying in 1d12 hours without a cure."
  ]
 },
 {
  "id": "warp-panther",
  "name": "Warp Panther",
  "group": "Magical",
  "unmodelled": true,
  "hp": 8,
  "armor": 0,
  "STR": 13,
  "DEX": 16,
  "WIL": 12,
  "attacks": [
   {
    "name": "tentacles",
    "dice": [
     8,
     8
    ],
    "blast": true,
    "note": "d8+d8, *blast*"
   },
   {
    "name": "bite",
    "dice": [
     10
    ],
    "blast": false,
    "note": "d10"
   }
  ],
  "detachment": false,
  "stat": "8 HP, 13 STR, 16 DEX, 12 WIL, tentacles (d8+d8, *blast*), bite (d10)",
  "notes": [
   "Grotesque panther-like predators with long razored tentacles growing out of their backs.",
   "Resistant to magical attacks. Caster must make a WIL save for the intended effect to succeed.",
   "Can teleport a short distance away at will. Hate Blink Dogs."
  ]
 },
 {
  "id": "warrior-snail",
  "name": "Warrior Snail",
  "group": "Unusual",
  "unmodelled": false,
  "hp": 4,
  "armor": 2,
  "STR": 14,
  "DEX": 6,
  "WIL": 3,
  "attacks": [
   {
    "name": "tentacles",
    "dice": [
     8,
     8
    ],
    "blast": false,
    "note": "d8+d8"
   }
  ],
  "detachment": false,
  "stat": "4 HP, 2 Armor, 14 STR, 6 DEX, 3 WIL, tentacles (d8+d8)",
  "notes": [
   "Giant armored snails with heavy, club-like tentacles.",
   "Some species have colorful shells that can reflect magical attacks."
  ]
 },
 {
  "id": "water-elemental",
  "name": "Water Elemental",
  "group": "Magical",
  "unmodelled": true,
  "hp": 14,
  "armor": 0,
  "STR": 15,
  "DEX": 16,
  "WIL": 4,
  "attacks": [
   {
    "name": "spray",
    "dice": [
     8
    ],
    "blast": false,
    "note": "d8"
   }
  ],
  "detachment": false,
  "stat": "14 HP, 15 STR, 16 DEX, 4 WIL, spray (d8)",
  "notes": [
   "Rare spirits of lakes, rivers, and seas.",
   "Mundane attacks against the Water Elemental are *impaired*.",
   "**Critical Damage**: Target is enveloped by the water and drowns in three rounds."
  ]
 },
 {
  "id": "werewolf",
  "name": "Werewolf",
  "group": "Shape Shifter",
  "unmodelled": true,
  "hp": 8,
  "armor": 0,
  "STR": 15,
  "DEX": 14,
  "WIL": 6,
  "attacks": [
   {
    "name": "claws",
    "dice": [
     6,
     6
    ],
    "blast": false,
    "note": "d6+d6"
   },
   {
    "name": "bite",
    "dice": [
     8
    ],
    "blast": false,
    "note": "d8"
   }
  ],
  "detachment": false,
  "stat": "8 HP, 15 STR, 14 DEX, 6 WIL, claws (d6+d6), bite (d8)",
  "notes": [
   "Ferocious lycanthropes that can transform into a wolf-shape at will.",
   "Mundane attacks are *impaired* against werewolves, but attacks with weapons made of silver are *enhanced*.",
   "**Critical Damage**: Target becomes infected with lycanthropy, transforming into a werewolf by the next full moon."
  ]
 },
 {
  "id": "wight",
  "name": "Wight",
  "group": "Undead",
  "unmodelled": true,
  "hp": 12,
  "armor": 3,
  "STR": 16,
  "DEX": 8,
  "WIL": 12,
  "attacks": [
   {
    "name": "long sword",
    "dice": [
     10
    ],
    "blast": false,
    "note": "d10"
   }
  ],
  "detachment": false,
  "stat": "12 HP, 3 Armor, 16 STR, 8 DEX, 12 WIL, long sword (d10)",
  "notes": [
   "Grotesque, fallen warriors, raised from death for ill purpose. Often astride equally nightmarish steeds, leading lesser undead creatures into battle.",
   "**Critical Damage**: On a fail, any STR loss is permanent."
  ]
 },
 {
  "id": "will-o-wisp",
  "name": "Will-o-Wisp",
  "group": "Fey",
  "unmodelled": false,
  "hp": 3,
  "armor": 0,
  "STR": 6,
  "DEX": 17,
  "WIL": 12,
  "attacks": [],
  "detachment": false,
  "stat": "3 HP, 6 STR, 17 DEX, 12 WIL",
  "notes": [
   "Nocturnal spirits of cool flame, commonly found in dense woodlands, marshes, and swamps.",
   "Known to lead travelers astray, to a corpse, or back home again."
  ]
 },
 {
  "id": "wolf",
  "name": "Wolf",
  "group": "Beast",
  "unmodelled": false,
  "hp": 6,
  "armor": 0,
  "STR": 12,
  "DEX": 14,
  "WIL": 8,
  "attacks": [
   {
    "name": "bite",
    "dice": [
     8
    ],
    "blast": false,
    "note": "d8"
   }
  ],
  "detachment": false,
  "stat": "6 HP, 12 STR, 14 DEX, 8 WIL, bite (d8)",
  "notes": [
   "Large canines that dwell primarily in forest or tundra.",
   "Can be trained with effort if captured at a young age."
  ]
 },
 {
  "id": "wood-troll",
  "name": "Wood Troll",
  "group": "Goblinoid",
  "unmodelled": true,
  "hp": 10,
  "armor": 0,
  "STR": 15,
  "DEX": 12,
  "WIL": 7,
  "attacks": [
   {
    "name": "bite",
    "dice": [
     8
    ],
    "blast": false,
    "note": "d8"
   },
   {
    "name": "club",
    "dice": [
     10
    ],
    "blast": false,
    "note": "d10"
   }
  ],
  "detachment": false,
  "stat": "10 HP, 15 STR, 12 DEX, 7 WIL, bite (d8), club (d10)",
  "notes": [
   "Large humanoids with elongated arms made of bark or root. They live in forests, sharing a deep connection with the vegetation around them.",
   "If killed, they will slowly regenerate unless their corpse is taken out of the forest or burned with fire.",
   "**Critical Damage**: Moss and twigs begin growing out of target’s wounds."
  ]
 },
 {
  "id": "wyvern",
  "name": "Wyvern",
  "group": "Avian",
  "unmodelled": true,
  "hp": 11,
  "armor": 0,
  "STR": 15,
  "DEX": 14,
  "WIL": 13,
  "attacks": [
   {
    "name": "stinger",
    "dice": [
     10
    ],
    "blast": false,
    "note": "d10"
   }
  ],
  "detachment": false,
  "stat": "11 HP, 15 STR, 14 DEX, 13 WIL, stinger (d10)",
  "notes": [
   "Large, intelligent, winged reptiles. Dwell in any terrain, but favor dry cliffs.",
   "Shy away from other creatures, preferring to silently stalk their targets from afar.",
   "**Critical Damage**: The victim is impaled and held in place. The wyvern then bites their head off."
  ]
 },
 {
  "id": "zombie",
  "name": "Zombie",
  "group": "Undead",
  "unmodelled": true,
  "hp": 2,
  "armor": 0,
  "STR": 12,
  "DEX": 6,
  "WIL": 3,
  "attacks": [
   {
    "name": "jagged nails",
    "dice": [
     6
    ],
    "blast": false,
    "note": "d6"
   }
  ],
  "detachment": false,
  "stat": "2 HP, 12 STR, 6 DEX, 3 WIL, jagged nails (d6)",
  "notes": [
   "Re-animated corpse brought back through necromantic ritual or fell influence. Immune to all mind-influencing effects.",
   "If not utterly destroyed (by fire, complete dismemberment, etc.), the Zombie will rise again within a few minutes.",
   "**Critical Damage**: Target is infected and becomes *deprived*. Without the services of a specialist or healer, they will become a zombie in 1d4 days."
  ]
 }
];
