// ─────────────────────────────────────────────────────────────────────────────
// data.js — an original, openly-licensed translation of the Zhouyi (周易), the
// base text of the Yijing: each hexagram's Judgment (卦辭) and line texts (爻辭).
//
// This is the canonical home of the translation. The Chinese shown is the
// RECEIVED text (the transmitted Wang Bi recension). The English is ours. Notes
// mark graph readings, textual cruxes, and Mawangdui variants. It is a
// transparent WORKING translation — corrections welcome — not a claim to be
// definitive. Licensed CC BY-SA 4.0; the source text is ancient / public domain.
//
// Pilot: Hexagram 1 (乾 Qián) only — the template. 63 to come.
// Shape mirrors read/'s tale data: passages → segments {z, py, e, n}.
// ─────────────────────────────────────────────────────────────────────────────

export const ZHOUYI = {
  meta: {
    title: 'Zhouyi 周易 — an open translation',
    license: 'CC BY-SA 4.0',
    method: "Original translation. The Chinese is the received (Wang Bi) recension; the English is ours. "+
      "Notes flag graph readings, cruxes, and where the Mawangdui silk manuscript differs. A transparent "+
      "working translation, openly licensed — not a claim to definitiveness.",
    sources: [
      { label: 'Zhouyi 周易 · 乾 — received text', url: 'https://ctext.org/book-of-changes/qian', host: 'Chinese Text Project (ctext.org)' },
      { label: 'James Legge, The Yî King (Sacred Books of the East XVI, 1882) — reference', url: 'https://sacred-texts.com/ich/index.htm', host: 'sacred-texts.com (public domain)' },
      { label: 'Mawangdui silk Yijing — variants', url: 'https://en.wikipedia.org/wiki/Mawangdui_Silk_Texts', host: 'Wikipedia' },
    ],
  },

  hexagrams: {
    1: {
      no: 1,
      name: { zh: '乾', py: 'Qián', en: 'The Creative · Force' },
      figure: '111111',                   // bottom→top, 1 = yang
      judgment: {
        z: '元亨利貞', py: 'yuán hēng lì zhēn',
        e: 'The Creative. From the origin it flows through to success; it furthers, and it rewards the steadfast.',
        n: '元亨利貞 — read by the Confucian Wings as four cardinal virtues: 元 origin/sublimity, 亨 success '+
           '(originally 享, an offering “accepted”), 利 benefit/furthering, 貞 steadfast correctness. The oldest '+
           'layer reads more plainly as an omen — “a great offering; favourable to divine” — since 貞 in Shang '+
           'oracle-bone use means “to put a question to the oracle.” We render the received virtue-sense and flag '+
           'the divinatory root. In the Mawangdui silk text the hexagram is written 鍵 (jiàn), not 乾.',
      },
      lines: [
        { pos: 1, name: '初九', z: '潛龍勿用', py: 'qián lóng wù yòng',
          e: 'Nine at the beginning: a dragon lies hidden. Do not act.',
          n: '潛龍, the submerged dragon — power present but not yet to be used. The lowest place: the time of '+
             'concealment. 勿用, “do not employ it.”' },
        { pos: 2, name: '九二', z: '見龍在田，利見大人', py: 'xiàn lóng zài tián, lì jiàn dàrén',
          e: 'Nine in the second place: the dragon appears in the field. It furthers one to see the great person.',
          n: 'The graph 見 turns twice: first as xiàn, “appears,” then as jiàn, “to see” — a deliberate pivot. '+
             '在田, “in the field”: emerged, but still on the ground. 大人, the great person — one of standing whose '+
             'help now counts; the second place answers to the fifth, the throne.' },
        { pos: 3, name: '九三', z: '君子終日乾乾，夕惕若厲，无咎', py: 'jūnzǐ zhōngrì qián-qián, xī tì ruò lì, wú jiù',
          e: 'Nine in the third place: the noble one is tireless the whole day through, and at nightfall still wary, as though in danger. No blame.',
          n: '乾乾 reduplicates the hexagram’s own name as a verb — “strong-and-strong,” ceaselessly diligent. '+
             '惕 wary/anxious; 若厲, “as if there were danger.” The third place is the exposed top of the lower '+
             'trigram, a place of risk; vigilance there earns 无咎, “no blame.”' },
        { pos: 4, name: '九四', z: '或躍在淵，无咎', py: 'huò yuè zài yuān, wú jiù',
          e: 'Nine in the fourth place: now it leaps up, now it stays in the deep. No blame.',
          n: '或, “at times / perhaps”; 躍, to leap; 淵, the abyss-pool. The dragon hesitates at the threshold '+
             'between depth and flight — the fourth place, just below the throne, is a place of testing. Either '+
             'way, rightly taken, is blameless.' },
        { pos: 5, name: '九五', z: '飛龍在天，利見大人', py: 'fēi lóng zài tiān, lì jiàn dàrén',
          e: 'Nine in the fifth place: the dragon flies in heaven. It furthers one to see the great person.',
          n: 'The ruling line: a firm line in the honoured, central fifth place — its proper seat. 飛龍在天 is '+
             'power fully come into its own.' },
        { pos: 6, name: '上九', z: '亢龍有悔', py: 'kàng lóng yǒu huǐ',
          e: 'Nine at the top: the dragon overreaches; there is regret.',
          n: '亢 (kàng), strained too high, overweening (the graph also means “throat”). Past the fifth there is '+
             'nowhere left to climb; force pressed beyond its peak brings 悔, “regret.”' },
      ],
      useLine: {
        name: '用九', z: '見群龍无首，吉', py: 'jiàn qún lóng wú shǒu, jí',
        e: 'Using the nines: a host of dragons appears, none of them foremost. Auspicious.',
        n: 'Read only when all six lines are old yang (all changing). 群龍无首, “a flock of dragons without a '+
           'head” — strength that does not insist on leading. Hexagrams 1 and 2 alone carry such an all-lines '+
           'text (here 用九; in Kūn, 用六).',
      },
      note: 'The six lines trace one image through six stages — the dragon hidden, appearing, toiling, poised, '+
            'soaring, overreaching: the life-curve of any rising force, and the warning folded into its peak.',
    },

    2: {
      no: 2,
      name: { zh: '坤', py: 'Kūn', en: 'The Receptive · Field' },
      figure: '000000',
      judgment: {
        z: '元亨，利牝馬之貞。君子有攸往，先迷後得主，利。西南得朋，東北喪朋。安貞吉。',
        py: 'yuán hēng, lì pìnmǎ zhī zhēn. jūnzǐ yǒu yōu wǎng, xiān mí hòu dé zhǔ, lì. xīnán dé péng, dōngběi sàng péng. ān zhēn jí.',
        e: 'The Receptive. From the origin, success; favourable is the steadfastness of a mare. The noble one has somewhere to go: at first he loses the way, but later finds a master. Favourable. In the southwest he gains companions; in the northeast he loses companions. In quiet steadfastness, good fortune.',
        n: 'Earth to Heaven’s heaven — yielding strength. The 牝馬 “mare” is receptive yet tireless; she follows, and following finds her lord (先迷後得主). The directions are the trigram’s placements — Kūn’s home is the southwest; she gains her own kind there and parts from companions in the northeast. 朋 “companions” also named a unit of paired cowries, so a faint sense of “gains/loses wealth” shadows the line.',
      },
      lines: [
        { pos: 1, name: '初六', z: '履霜，堅冰至', py: 'lǚ shuāng, jiān bīng zhì',
          e: 'Six at the beginning: treading on hoarfrost — the hard ice is coming.',
          n: 'The first sign read for what it foretells: frost underfoot means the ice is on its way. Small beginnings accumulate; the yielding power, just stirring, already implies its full winter.' },
        { pos: 2, name: '六二', z: '直方大，不習无不利', py: 'zhí fāng dà, bù xí wú bù lì',
          e: 'Six in the second place: straight, square, vast. Without effort, nothing is unfavourable.',
          n: '直方大 — upright, four-square, broad: the virtues of earth itself. 不習, “without rehearsal”: earth’s rectitude is natural, not learned. The central, correct line of the Receptive needs no contrivance.' },
        { pos: 3, name: '六三', z: '含章可貞，或從王事，无成有終', py: 'hán zhāng kě zhēn, huò cóng wáng shì, wú chéng yǒu zhōng',
          e: 'Six in the third place: holding hidden brilliance, one may stay steadfast. Should you enter the king’s service, claim no completion of your own — yet there is a good end.',
          n: '含章, to “contain the pattern” — keep your brightness veiled. 无成有終: take no credit (无成), and the work still comes to a good close (有終). Serving from the third place, the way of the Receptive is to finish the task without owning it.' },
        { pos: 4, name: '六四', z: '括囊，无咎无譽', py: 'kuò náng, wú jiù wú yù',
          e: 'Six in the fourth place: a tied-up sack. No blame, no praise.',
          n: '括囊, to draw the mouth of the bag shut — prudent reticence near the throne. Say and risk nothing: you earn neither fault nor fame. Safe, and unremarkable.' },
        { pos: 5, name: '六五', z: '黃裳，元吉', py: 'huáng cháng, yuán jí',
          e: 'Six in the fifth place: a yellow lower-garment. Supreme good fortune.',
          n: 'The famous line. 黃 yellow is earth’s colour and the colour of the centre/mean; 裳 is the lower skirt, the garment of the subordinate. Adornment worn humbly and below — sovereignty exercised in the yielding mode. The ruler-place of the Receptive, doing right by staying low.' },
        { pos: 6, name: '上六', z: '龍戰于野，其血玄黃', py: 'lóng zhàn yú yě, qí xiě xuán huáng',
          e: 'Six at the top: dragons battle in the wilds; their blood is black and yellow.',
          n: 'Yielding grown to its extreme contends with the firm: 龍戰于野, dragons at war in the open field. 玄黃 — “black and yellow,” the colours of Heaven (玄) and Earth (黃): cosmic blood. The overreach of the Receptive when it forgets to follow.' },
      ],
      useLine: {
        name: '用六', z: '利永貞', py: 'lì yǒng zhēn',
        e: 'Using the sixes: favourable is lasting steadfastness.',
        n: 'Read when all six lines are old yin (all changing). The yielding’s whole virtue, distilled: not a single act but 永貞 — constancy held for the long term. Kūn’s all-lines text, the counterpart to Qián’s 用九.',
      },
      note: 'From frost underfoot to dragons warring in the field, the six lines trace the rise of the yielding power — and its one danger: that following, grown to extremity, forgets it was meant to follow.',
    },

    11: {
      no: 11,
      name: { zh: '泰', py: 'Tài', en: 'Peace · Pervading' },
      figure: '111000',
      judgment: {
        z: '小往大來，吉亨。', py: 'xiǎo wǎng dà lái, jí hēng.',
        e: 'Peace. The small departs, the great approaches. Good fortune, success.',
        n: 'Heaven (Qián) below, Earth (Kūn) above — and so the light, rising, and the heavy, sinking, move toward each other and interpenetrate. 小 (the yielding) goes, 大 (the firm) comes: the favourable exchange. The season when high and low actually meet.',
      },
      lines: [
        { pos: 1, name: '初九', z: '拔茅茹，以其彙，征吉', py: 'bá máo rú, yǐ qí huì, zhēng jí',
          e: 'Nine at the beginning: pulling up the cogon-grass, its roots come tangled together, each with its kind. To set forth: good fortune.',
          n: '拔茅茹 — tug one reed and its matted roots come with it. 以其彙, “with its kind”: a worthy man drawn into office draws his fellows after him. In the rising season, to advance (征) is right.' },
        { pos: 2, name: '九二', z: '包荒，用馮河，不遐遺，朋亡，得尚于中行', py: 'bāo huāng, yòng píng hé, bù xiá yí, péng wáng, dé shàng yú zhōng háng',
          e: 'Nine in the second place: embracing the wasteland; fording the river on foot; not abandoning the far-off; partisanship gone — thus he wins esteem by the middle course.',
          n: 'A minister of great compass: 包荒, take in even the wild and waste; 馮河, ford the He bare-legged (boldness); 不遐遺, neglect nothing distant; 朋亡, let faction fall away. By 中行, the central path, he is upheld.' },
        { pos: 3, name: '九三', z: '无平不陂，无往不復，艱貞无咎，勿恤其孚，于食有福', py: 'wú píng bù pō, wú wǎng bù fù, jiān zhēn wú jiù, wù xù qí fú, yú shí yǒu fú',
          e: 'Nine in the third place: no plain without a slope, no going without a return. Steadfast through hardship — no blame. Do not fret over your good faith; in your sustenance there is blessing.',
          n: 'The turn, set at the top of the lower trigram: every level ground tilts (无平不陂), every departure circles back (无往不復). Peace already contains its reversal, so hold constant in the hard stretch. 孚, good faith, need not be anxiously guarded; daily bread will not fail.' },
        { pos: 4, name: '六四', z: '翩翩不富，以其鄰，不戒以孚', py: 'piānpiān bù fù, yǐ qí lín, bù jiè yǐ fú',
          e: 'Six in the fourth place: fluttering down, not rich, together with its neighbours — not on guard, but in good faith.',
          n: '翩翩, lightly descending; 不富, the empty yin lines have no wealth to hoard. The upper, yielding lines come down to meet the firm below 以其鄰 (with their neighbours), 不戒以孚 — without suspicion, through trust. High condescends to low, and is believed.' },
        { pos: 5, name: '六五', z: '帝乙歸妹，以祉元吉', py: 'dì yǐ guī mèi, yǐ zhǐ yuán jí',
          e: 'Six in the fifth place: King Yi gives his younger sister in marriage; thereby blessing, and supreme good fortune.',
          n: '帝乙歸妹 — a historical allusion: the Shang king Di Yi marrying off a royal woman (the same event named at Hexagram 54). The sovereign, in the yielding fifth place, condescends in alliance: rank that lowers itself to join brings 祉, blessing.' },
        { pos: 6, name: '上六', z: '城復于隍，勿用師，自邑告命，貞吝', py: 'chéng fù yú huáng, wù yòng shī, zì yì gào mìng, zhēn lìn',
          e: 'Six at the top: the city wall falls back into the moat. Do not use the army. From your own town, proclaim the command. Steadfast — yet remorse.',
          n: '城復于隍 — the rampart crumbles back into the dry ditch it was dug from: Peace, at its limit, collapses into Standstill. 勿用師, do not fight it; 自邑告命, retrench and govern your own. Even constancy (貞) now meets 吝, regret. Every Tài carries its Pǐ.' },
      ],
      note: 'Heaven below and Earth above, the two at last meeting — yet the sixth line warns the wall returns to the ditch. Peace is the season in which its own reversal is already growing.',
    },

    12: {
      no: 12,
      name: { zh: '否', py: 'Pǐ', en: 'Standstill · Obstruction' },
      figure: '000111',
      judgment: {
        z: '否之匪人，不利君子貞，大往小來。', py: 'pǐ zhī fěi rén, bù lì jūnzǐ zhēn, dà wǎng xiǎo lái.',
        e: 'Standstill. It is the work of the wrong people; it does not further the noble one’s steadfastness. The great departs and the small approaches.',
        n: 'Earth below, Heaven above — each withdraws to its own side and they do not meet: stagnation, the exact mirror of Tài. 否之匪人 is a knot: literally “standstill — not [the right] people,” which we read as “the doing of the wrong sort.” 大往小來: now the firm (大) goes and the yielding (小) comes — the unfavourable exchange.',
      },
      lines: [
        { pos: 1, name: '初六', z: '拔茅茹，以其彙，貞吉亨', py: 'bá máo rú, yǐ qí huì, zhēn jí hēng',
          e: 'Six at the beginning: pulling up the cogon-grass, its roots tangled, each with its kind. Steadfast: good fortune, success.',
          n: 'The same uprooted reeds as Tài’s first line, but read in reverse: in Standstill the worthy withdraw together, as a body. To hold firm (and lie low) is auspicious — the retreat is principled, not a rout.' },
        { pos: 2, name: '六二', z: '包承，小人吉，大人否亨', py: 'bāo chéng, xiǎo rén jí, dàrén pǐ hēng',
          e: 'Six in the second place: bearing it with submission. For the small person, good fortune; for the great person, standstill — and so, success.',
          n: 'A debated line. 包承, to take it and serve/submit. In a stagnant time petty men thrive (小人吉); the great person accepts the standstill (大人否) rather than collude, and that acceptance is itself the way through (亨).' },
        { pos: 3, name: '六三', z: '包羞', py: 'bāo xiū',
          e: 'Six in the third place: harbouring shame.',
          n: 'Two characters only. 包羞 — to swallow disgrace: a yielding line wrongly placed, holding in a shame it cannot yet voice.' },
        { pos: 4, name: '九四', z: '有命无咎，疇離祉', py: 'yǒu mìng wú jiù, chóu lí zhǐ',
          e: 'Nine in the fourth place: there is a mandate; no blame. Those of his kind partake of the blessing.',
          n: 'The turn begins as the firm lines arrive above. 有命, a charge from on high, makes action blameless; 疇 (“fellows, his sort”) 離 (cleave to / share in) 祉 (blessing) — and his companions share what comes.' },
        { pos: 5, name: '九五', z: '休否，大人吉。其亡其亡，繫于苞桑', py: 'xiū pǐ, dàrén jí. qí wáng qí wáng, xì yú bāo sāng',
          e: 'Nine in the fifth place: bringing the standstill to rest. For the great person, good fortune. “Lest it perish! lest it perish!” — bind it to a cluster of mulberry roots.',
          n: 'The famous caution. 休否, the ruler halts the stagnation; but security is held only by vigilance — 其亡其亡, “it may fall, it may fall,” and so 繫于苞桑, lash it to the deep-rooted mulberry. The Xici singles this line out: the wise keep danger in mind even when safe.' },
        { pos: 6, name: '上九', z: '傾否，先否後喜', py: 'qīng pǐ, xiān pǐ hòu xǐ',
          e: 'Nine at the top: the standstill tips over. First standstill, then joy.',
          n: '傾否 — stagnation, top-heavy, overturns of itself. Unlike a mountain, Standstill does not last; pushed to its limit it ends, and what follows the obstruction is gladness.' },
      ],
      note: 'Heaven and Earth draw apart and the world stalls — but Standstill is a season, not a fate. Its final line tips it over: first obstruction, then joy.',
    },

    63: {
      no: 63,
      name: { zh: '既濟', py: 'Jì Jì', en: 'After Completion' },
      figure: '101010',
      judgment: {
        z: '亨小，利貞，初吉終亂。', py: 'hēng xiǎo, lì zhēn, chū jí zhōng luàn.',
        e: 'After Completion. Success in small things; it furthers to be steadfast. At first, good fortune; in the end, disorder.',
        n: 'Water over fire — and every one of the six lines stands in its proper place (firm in the odd seats, yielding in the even): the one figure of perfect order. 既濟, “already forded.” Yet order at its peak is exactly where the slide begins: 初吉終亂.',
      },
      lines: [
        { pos: 1, name: '初九', z: '曳其輪，濡其尾，无咎', py: 'yè qí lún, rú qí wěi, wú jiù',
          e: 'Nine at the beginning: he drags his wheels, he wets his tail. No blame.',
          n: 'Restraint at the outset: 曳其輪, braking the cart-wheels; 濡其尾, the animal fording wets its tail and so goes slowly. Holding back at the start of completion — no blame.' },
        { pos: 2, name: '六二', z: '婦喪其茀，勿逐，七日得', py: 'fù sàng qí fú, wù zhú, qī rì dé',
          e: 'Six in the second place: the wife loses the screen of her carriage. Do not chase it; in seven days she gets it back.',
          n: '茀, the curtain that screens a woman’s carriage — her seemly conveyance. Lost, it should not be pursued; the cycle restores it 七日 (the recurring “seven days,” the turn of a small period). Wait, and what is proper returns.' },
        { pos: 3, name: '九三', z: '高宗伐鬼方，三年克之，小人勿用', py: 'gāo zōng fá guǐ fāng, sān nián kè zhī, xiǎo rén wù yòng',
          e: 'Nine in the third place: Gao Zong attacks the Demon Territory; in three years he subdues it. Do not employ petty people.',
          n: 'History again: 高宗 is the Shang king Wu Ding; 鬼方, the Guifang, a frontier people. A great undertaking that costs three years — 小人勿用, no work for small men. Completion won by long and disciplined effort.' },
        { pos: 4, name: '六四', z: '繻有衣袽，終日戒', py: 'rú yǒu yī rú, zhōng rì jiè',
          e: 'Six in the fourth place: the finest silk will have its rags; all day be on guard.',
          n: 'A textually hard line. The plainest sense keeps the boat-image of the hexagram: hold rags (衣袽) ready to plug the leaks even in fine cloth (繻); stay watchful 終日, all day long. After the crossing is made, decay seeps in at the seams.' },
        { pos: 5, name: '九五', z: '東鄰殺牛，不如西鄰之禴祭，實受其福', py: 'dōng lín shā niú, bù rú xī lín zhī yuè jì, shí shòu qí fú',
          e: 'Nine in the fifth place: the eastern neighbour slaughters an ox, but it does not match the western neighbour’s small spring offering, which truly receives the blessing.',
          n: 'Lavishness against sincerity. The 殺牛 ox-sacrifice of the east is outweighed by the modest 禴 (spring) offering of the west, because the latter 實受其福 — really receives the blessing. At completion’s height, what counts is the timely and the heartfelt, not the grand.' },
        { pos: 6, name: '上六', z: '濡其首，厲', py: 'rú qí shǒu, lì',
          e: 'Six at the top: he wets his head. Danger.',
          n: 'The ford overreaches at the very end: the animal that wet only its tail at the start (line 1) now goes in over its head (濡其首). 厲, danger — completion pressed one step too far comes undone.' },
      ],
      note: 'The single figure where every line sits correctly — perfect order — and precisely there the warning is written: order completed is order beginning to come apart.',
    },

    64: {
      no: 64,
      name: { zh: '未濟', py: 'Wèi Jì', en: 'Before Completion' },
      figure: '010101',
      judgment: {
        z: '亨，小狐汔濟，濡其尾，无攸利。', py: 'hēng, xiǎo hú qì jì, rú qí wěi, wú yōu lì.',
        e: 'Before Completion. Success. The little fox, all but across, wets its tail. Nothing is favourable [if it falters].',
        n: 'Fire over water — and now every line is out of its proper place: the figure of the not-yet-finished. 未濟, “not yet forded.” The 小狐 little fox 汔 (almost) makes the crossing, then wets its tail at the last step. The book closes not on completion but on the threshold — change goes on.',
      },
      lines: [
        { pos: 1, name: '初六', z: '濡其尾，吝', py: 'rú qí wěi, lìn',
          e: 'Six at the beginning: he wets his tail. Remorse.',
          n: 'Rushing the crossing from the lowest place, the tail dips at once. 吝, cause for regret: an over-eager start before completion.' },
        { pos: 2, name: '九二', z: '曳其輪，貞吉', py: 'yè qí lún, zhēn jí',
          e: 'Nine in the second place: he drags his wheels. Steadfast: good fortune.',
          n: '曳其輪, braking the wheels — patience and restraint in the central second place. To hold steady (貞) rather than push is auspicious.' },
        { pos: 3, name: '六三', z: '未濟，征凶，利涉大川', py: 'wèi jì, zhēng xiōng, lì shè dà chuān',
          e: 'Six in the third place: before completion; to set forth brings misfortune — yet it furthers to cross the great water.',
          n: 'A real crux: 征凶 (advancing now is ominous, you are not ready) sits oddly beside 利涉大川 (it furthers to cross the great stream). Many take the second clause as the goal one must eventually face; some editions read 不利涉大川, “it does not further to cross.” We give the received text and flag the tension.' },
        { pos: 4, name: '九四', z: '貞吉，悔亡，震用伐鬼方，三年有賞于大國', py: 'zhēn jí, huǐ wáng, zhèn yòng fá guǐ fāng, sān nián yǒu shǎng yú dà guó',
          e: 'Nine in the fourth place: steadfast, good fortune; regret vanishes. With rousing force he attacks the Demon Territory; in three years there are rewards from the great state.',
          n: '震, thunderous energy, thrown into the same frontier war (伐鬼方) named at Hexagram 63. Sustained effort across the threshold is, after three years, 有賞于大國 — rewarded by the great kingdom. The push that finishes the crossing.' },
        { pos: 5, name: '六五', z: '貞吉，无悔，君子之光，有孚吉', py: 'zhēn jí, wú huǐ, jūnzǐ zhī guāng, yǒu fú jí',
          e: 'Six in the fifth place: steadfast, good fortune, no regret. The light of the noble one; there is good faith — good fortune.',
          n: '君子之光, the radiance of the noble one, near the completion; 有孚, sincerity that shines and is trusted. The ruling place of Before Completion, lit from within.' },
        { pos: 6, name: '上九', z: '有孚于飲酒，无咎，濡其首，有孚失是', py: 'yǒu fú yú yǐn jiǔ, wú jiù, rú qí shǒu, yǒu fú shī shì',
          e: 'Nine at the top: there is good faith in the drinking of wine. No blame. But should he wet his head, his good faith loses what is right.',
          n: 'The last line of the book. To celebrate at the brink with confidence (有孚于飲酒) is blameless — but 濡其首, to wet one’s head in the cup, and the very sincerity 失是, loses the mark. The Zhouyi ends not on triumph but on a caution against losing measure on the threshold of completion.' },
      ],
      note: 'Fire above water, every line out of place: the unfinished crossing. The classic ends with the little fox at the brink and a last warning — change is never finished, and measure must hold to the final step.',
    },

    3: {
      no: 3,
      name: { zh: '屯', py: 'Zhūn', en: 'Difficulty at the Beginning' },
      figure: '100010',
      judgment: {
        z: '元亨利貞，勿用有攸往，利建侯。', py: 'yuán hēng lì zhēn, wù yòng yǒu yōu wǎng, lì jiàn hóu.',
        e: 'Difficulty at the Beginning. Sublime success; it furthers to be steadfast. Do not set out anywhere. It furthers to install helpers.',
        n: 'The graph 屯 shows a sprout straining up through the soil — birth-pangs. Thunder stirs beneath the abyss (water): movement amid danger. 勿用有攸往, do not undertake a journey yet; 利建侯, “it furthers to set up vassals” — gather支持 before you move.',
      },
      lines: [
        { pos: 1, name: '初九', z: '磐桓，利居貞，利建侯', py: 'pán huán, lì jū zhēn, lì jiàn hóu',
          e: 'Nine at the beginning: hesitating, circling. It furthers to dwell steadfast. It furthers to install helpers.',
          n: '磐桓, to linger and turn about — the firm line at the very bottom holds rather than rushes. In a hard beginning, settle and gather allies.' },
        { pos: 2, name: '六二', z: '屯如邅如，乘馬班如。匪寇婚媾，女子貞不字，十年乃字', py: 'zhūn rú zhān rú, chéng mǎ bān rú. fěi kòu hūn gòu, nǚzǐ zhēn bù zì, shí nián nǎi zì',
          e: 'Six in the second place: beset and halting, the horses wheel about. They are not robbers but suitors. The maiden, chaste, does not pledge; in ten years she pledges.',
          n: '乘馬班如, mounted riders circling (a wedding party that keeps turning back). 匪寇婚媾, “not bandits, a wooing.” 字 means to betroth (and to bear a child); the obstruction delays the union — 十年乃字, only after ten years does it come.' },
        { pos: 3, name: '六三', z: '即鹿无虞，惟入于林中，君子幾，不如舍，往吝', py: 'jí lù wú yú, wéi rù yú lín zhōng, jūnzǐ jī, bù rú shě, wǎng lìn',
          e: 'Six in the third place: chasing deer with no forester, one only goes deeper into the wood. The noble one, reading the sign, had better let it go; to press on brings regret.',
          n: '即鹿无虞, to hunt deer without the gamekeeper who knows the ground — pursuit without guidance. 君子幾, the noble one catches the incipient sign (幾) and desists; forcing on (往) brings 吝.' },
        { pos: 4, name: '六四', z: '乘馬班如，求婚媾，往吉，无不利', py: 'chéng mǎ bān rú, qiú hūn gòu, wǎng jí, wú bù lì',
          e: 'Six in the fourth place: the horses wheel about; she seeks the wooing. To go brings good fortune; nothing is unfavourable.',
          n: 'The same wheeling riders as line 2, but now the union is rightly sought; to advance toward it is wholly favourable.' },
        { pos: 5, name: '九五', z: '屯其膏，小貞吉，大貞凶', py: 'zhūn qí gāo, xiǎo zhēn jí, dà zhēn xiōng',
          e: 'Nine in the fifth place: the bounty is held back. In small things, steadfast — good fortune; in great things, steadfast — misfortune.',
          n: '膏, fat/richness/grace — the ruler’s beneficence, obstructed (屯) and not flowing down. Constancy serves in small matters; pressed to great ones it fails, for the channels are still blocked.' },
        { pos: 6, name: '上六', z: '乘馬班如，泣血漣如', py: 'chéng mǎ bān rú, qì xiě lián rú',
          e: 'Six at the top: the horses wheel about; weeping tears of blood in streams.',
          n: '泣血漣如, weeping blood without end — the difficulty at its extreme, the riders unable to go forward or back.' },
      ],
      note: 'The sprout forcing the soil: chaos at a beginning. Unions are delayed and helpers gathered; thunder stirs under the deep, and one holds rather than rushes.',
    },

    4: {
      no: 4,
      name: { zh: '蒙', py: 'Méng', en: 'Youthful Folly' },
      figure: '010001',
      judgment: {
        z: '亨。匪我求童蒙，童蒙求我。初筮告，再三瀆，瀆則不告。利貞。',
        py: 'hēng. fěi wǒ qiú tóng méng, tóng méng qiú wǒ. chū shì gào, zài sān dú, dú zé bù gào. lì zhēn.',
        e: 'Youthful Folly. Success. It is not I who seek the young and foolish; the young and foolish seek me. At the first divination I answer; a second and third profane it, and the profaned I do not answer. It furthers to be steadfast.',
        n: '蒙 is the dodder-vine, a “covering” — hence the unlit, ignorant mind. A spring wells at the mountain’s foot. The famous etiquette of consultation: ask once, sincerely; to pester is to pollute (瀆) the oracle, and it falls silent. (The “ask once” rule the consultation here keeps.)',
      },
      lines: [
        { pos: 1, name: '初六', z: '發蒙，利用刑人，用說桎梏，以往吝', py: 'fā méng, lì yòng xíng rén, yòng tuō zhì gù, yǐ wǎng lìn',
          e: 'Six at the beginning: to break open folly, it furthers to discipline people and to strike off their fetters; but to keep on [punishing] brings regret.',
          n: '發蒙, to open the closed mind. 刑人 … 說(脫)桎梏 — make an example, then loosen the stocks-and-cuffs: discipline meant to free, not to bind. Continue past that point (以往) and it turns to 吝.' },
        { pos: 2, name: '九二', z: '包蒙吉，納婦吉，子克家', py: 'bāo méng jí, nà fù jí, zǐ kè jiā',
          e: 'Nine in the second place: to embrace the ignorant — good fortune; to take a wife — good fortune; the son can manage the house.',
          n: 'The strong central line that nurtures rather than scolds: 包蒙, to contain and foster folly with patience. 子克家, the son equal to running the household — capability tempered by tolerance.' },
        { pos: 3, name: '六三', z: '勿用取女，見金夫，不有躬，无攸利', py: 'wù yòng qǔ nǚ, jiàn jīn fū, bù yǒu gōng, wú yōu lì',
          e: 'Six in the third place: do not take this woman in marriage. Seeing a man of gold, she does not keep herself. Nothing is favourable.',
          n: '金夫, a “man of metal/wealth”; 不有躬, she loses possession of her own person — the unrestrained who throws herself away. A line of caution against the heedless.' },
        { pos: 4, name: '六四', z: '困蒙，吝', py: 'kùn méng, lìn',
          e: 'Six in the fourth place: mired in folly. Regret.',
          n: '困蒙, ignorance walled in — the line farthest from any firm guide, shut up in its own dullness. 吝.' },
        { pos: 5, name: '六五', z: '童蒙，吉', py: 'tóng méng, jí',
          e: 'Six in the fifth place: the teachable child. Good fortune.',
          n: 'The docile learner in the ruler’s place — folly that knows itself folly and looks up to be taught. 吉.' },
        { pos: 6, name: '上九', z: '擊蒙，不利為寇，利禦寇', py: 'jī méng, bù lì wéi kòu, lì yù kòu',
          e: 'Nine at the top: striking folly down. It does not further to play the robber, but it furthers to ward robbers off.',
          n: '擊蒙, hard correction at the top. The firm line must not become the aggressor (為寇); its rightful use is to repel aggression (禦寇) — correction that defends, not violates.' },
      ],
      note: 'A spring at the mountain’s foot — the welling of the still-unlit mind. Teach the eager, repel folly, and put your question to the oracle but once.',
    },

    5: {
      no: 5,
      name: { zh: '需', py: 'Xū', en: 'Waiting · Nourishment' },
      figure: '111010',
      judgment: {
        z: '有孚，光亨，貞吉。利涉大川。', py: 'yǒu fú, guāng hēng, zhēn jí. lì shè dà chuān.',
        e: 'Waiting. There is sincerity: shining success, and steadfast good fortune. It furthers to cross the great water.',
        n: '需, to await (also “need, nourishment”). Clouds (water) massed above heaven, the rain not yet fallen: wait, but in confidence (有孚). The crossing will come in its time.',
      },
      lines: [
        { pos: 1, name: '初九', z: '需于郊，利用恆，无咎', py: 'xū yú jiāo, lì yòng héng, wú jiù',
          e: 'Nine at the beginning: waiting in the meadow. It furthers to keep to constancy. No blame.',
          n: '郊, the open country far from the water — far from danger. Far off, the right thing is steady patience (恆).' },
        { pos: 2, name: '九二', z: '需于沙，小有言，終吉', py: 'xū yú shā, xiǎo yǒu yán, zhōng jí',
          e: 'Nine in the second place: waiting on the sand. A little talk; in the end, good fortune.',
          n: '沙, the sandbank nearer the river — danger closer. 小有言, minor reproaches; held steady, it still ends well.' },
        { pos: 3, name: '九三', z: '需于泥，致寇至', py: 'xū yú ní, zhì kòu zhì',
          e: 'Nine in the third place: waiting in the mire. It brings the robbers on.',
          n: '泥, the mud at the very edge of the water. To wait this close to peril (致) invites attack — exposure self-incurred.' },
        { pos: 4, name: '六四', z: '需于血，出自穴', py: 'xū yú xuè, chū zì xué',
          e: 'Six in the fourth place: waiting in blood. Come out of the pit.',
          n: 'Now the danger is reached — 血, blood. The one counsel: 出自穴, climb out of the hole; do not stay where it bleeds.' },
        { pos: 5, name: '九五', z: '需于酒食，貞吉', py: 'xū yú jiǔ shí, zhēn jí',
          e: 'Nine in the fifth place: waiting with wine and food. Steadfast, good fortune.',
          n: '酒食, feasting — composed, unhurried waiting in the ruler’s central place. Patience at ease; 貞吉.' },
        { pos: 6, name: '上六', z: '入于穴，有不速之客三人來，敬之終吉', py: 'rù yú xué, yǒu bù sù zhī kè sān rén lái, jìng zhī zhōng jí',
          e: 'Six at the top: entering the pit. Three uninvited guests arrive; honour them, and in the end, good fortune.',
          n: '不速之客, guests who come unbidden — the three firm lines below now arrive. Met with respect (敬之), the unsought become allies; 終吉.' },
      ],
      note: 'Clouds massed over heaven, the rain withheld — waiting that ripens. The nearer the water the greater the risk; composure, and courtesy to the unbidden, turn the wait to good.',
    },

    6: {
      no: 6,
      name: { zh: '訟', py: 'Sòng', en: 'Conflict' },
      figure: '010111',
      judgment: {
        z: '有孚窒，惕中吉，終凶。利見大人，不利涉大川。',
        py: 'yǒu fú zhì, tì zhōng jí, zhōng xiōng. lì jiàn dàrén, bù lì shè dà chuān.',
        e: 'Conflict. Sincerity blocked. Stay wary and stop midway — good fortune; press it to the end — misfortune. It furthers to see the great person; it does not further to cross the great water.',
        n: '訟, litigation, the lawsuit. The honest claim is obstructed (窒). Halt halfway in wariness; seek the great arbiter (大人); do not embark on risky ventures while at odds.',
      },
      lines: [
        { pos: 1, name: '初六', z: '不永所事，小有言，終吉', py: 'bù yǒng suǒ shì, xiǎo yǒu yán, zhōng jí',
          e: 'Six at the beginning: do not prolong the affair. A little talk; in the end, good fortune.',
          n: 'Drop the quarrel early — 不永所事, don’t let the matter drag on. A small exchange of words, then it ends well.' },
        { pos: 2, name: '九二', z: '不克訟，歸而逋，其邑人三百戶，无眚', py: 'bù kè sòng, guī ér bū, qí yì rén sān bǎi hù, wú shěng',
          e: 'Nine in the second place: he cannot win the suit; he goes home and hides. His townsmen — three hundred households — escape calamity. ',
          n: '不克訟, the case is unwinnable; 歸而逋, withdraw and lie low. A modest fief of 三百戶; by not pressing the fight he spares his people 眚, self-incurred disaster.' },
        { pos: 3, name: '六三', z: '食舊德，貞厲，終吉。或從王事，无成', py: 'shí jiù dé, zhēn lì, zhōng jí. huò cóng wáng shì, wú chéng',
          e: 'Six in the third place: living on old merit. Steadfast amid danger; in the end, good fortune. Should you enter the king’s service, claim no completion.',
          n: '食舊德, subsist on inherited standing rather than grasp for more. Constant though in peril (貞厲). 或從王事，无成 — serve without claiming the credit (the formula also heard at Kūn 6.3).' },
        { pos: 4, name: '九四', z: '不克訟，復即命，渝安貞吉', py: 'bù kè sòng, fù jí mìng, yú ān zhēn jí',
          e: 'Nine in the fourth place: he cannot win the suit; he turns back and submits to the decree, changes his stance, finds peace — steadfast, good fortune.',
          n: '復即命, return and accept the mandate; 渝, to alter one’s course. Letting go of the contention, he settles into constancy and good fortune.' },
        { pos: 5, name: '九五', z: '訟，元吉', py: 'sòng, yuán jí',
          e: 'Nine in the fifth place: the dispute [judged here]. Supreme good fortune.',
          n: 'The ruling line — the just arbiter in the central, honoured place. Brought before the great judge, the case is rightly resolved: 元吉.' },
        { pos: 6, name: '上九', z: '或錫之鞶帶，終朝三褫之', py: 'huò xī zhī pán dài, zhōng zhāo sān chǐ zhī',
          e: 'Nine at the top: he may be granted a leather sash of office, but before the morning is out it is stripped from him three times.',
          n: '鞶帶, the ceremonial belt of rank — honour won by litigation. 終朝三褫之, torn off thrice in a single morning: what is gained by contention does not hold.' },
      ],
      note: 'Heaven and water pulling apart — the lawsuit. The wise halt the quarrel and seek the judge; what is won by strife is stripped away again.',
    },

    7: {
      no: 7,
      name: { zh: '師', py: 'Shī', en: 'The Army' },
      figure: '010000',
      judgment: {
        z: '貞，丈人吉，无咎。', py: 'zhēn, zhàng rén jí, wú jiù.',
        e: 'The Army. Steadfastness; a seasoned leader: good fortune, no blame.',
        n: '師, an army, a host. 丈人, the experienced commander (some read 大人, “great person”). Danger (water, the masses) held within the yielding earth: the multitude moves only by discipline (貞) under one tried leader.',
      },
      lines: [
        { pos: 1, name: '初六', z: '師出以律，否臧凶', py: 'shī chū yǐ lǜ, fǒu zāng xiōng',
          e: 'Six at the beginning: the army marches out by the rules. If not well-ordered, misfortune.',
          n: '以律, by discipline and regulation. 臧 means “good, sound”; 否臧, not in good order — without discipline at the outset, the campaign is doomed.' },
        { pos: 2, name: '九二', z: '在師中，吉无咎，王三錫命', py: 'zài shī zhōng, jí wú jiù, wáng sān xī mìng',
          e: 'Nine in the second place: in the midst of the army — good fortune, no blame. The king thrice confers a charge.',
          n: 'The one firm line, the commander, central among the host. 王三錫命, the king bestows his mandate three times over — repeated, conspicuous trust.' },
        { pos: 3, name: '六三', z: '師或輿尸，凶', py: 'shī huò yú shī, xiōng',
          e: 'Six in the third place: the army may cart corpses home. Misfortune.',
          n: '輿尸, to carry the dead back in the wagons — defeat, or command divided among many. 凶.' },
        { pos: 4, name: '六四', z: '師左次，无咎', py: 'shī zuǒ cì, wú jiù',
          e: 'Six in the fourth place: the army camps to the rear. No blame.',
          n: '左次, to encamp by drawing back. A timely retreat, knowing one’s limits, is not failure: 无咎.' },
        { pos: 5, name: '六五', z: '田有禽，利執言，无咎。長子帥師，弟子輿尸，貞凶', py: 'tián yǒu qín, lì zhí yán, wú jiù. zhǎngzǐ shuài shī, dìzǐ yú shī, zhēn xiōng',
          e: 'Six in the fifth place: there is game in the field; it furthers to take it on [royal] word. No blame. Let the eldest son lead the army; if a younger son leads, he carts corpses — and steadfast though it be, misfortune.',
          n: '田有禽, game (the foe) breaking into the fields — just cause; 執言, to act on the warrant/command. The worthy general (長子) must lead; put a lesser man (弟子) in charge and disaster follows, however “correct” the cause.' },
        { pos: 6, name: '上六', z: '大君有命，開國承家，小人勿用', py: 'dà jūn yǒu mìng, kāi guó chéng jiā, xiǎo rén wù yòng',
          e: 'Six at the top: the great ruler issues commands, founding states and securing families. Do not employ petty people.',
          n: 'The war won, the rewards are apportioned: 開國承家, fiefs established and houses confirmed. 小人勿用 — but never put the small among them.' },
      ],
      note: 'Water within earth — the host gathered and hidden. Discipline and one tried general carry the cause; at the end the spoils are shared out, but never with the small.',
    },

    8: {
      no: 8,
      name: { zh: '比', py: 'Bǐ', en: 'Holding Together · Union' },
      figure: '000010',
      judgment: {
        z: '吉。原筮，元永貞，无咎。不寧方來，後夫凶。',
        py: 'jí. yuán shì, yuán yǒng zhēn, wú jiù. bù níng fāng lái, hòu fū xiōng.',
        e: 'Holding Together. Good fortune. Consult once more at the source: with sublime and lasting steadfastness, no blame. The unsettled come to join; but for the one who comes too late, misfortune.',
        n: '比, to ally, to hold together around a centre. 原筮, re-examine the omen at its source — be sure the bond is sound. Come while the union forms: 不寧方來, the restless gather in; 後夫, the latecomer, misses it.',
      },
      lines: [
        { pos: 1, name: '初六', z: '有孚比之，无咎。有孚盈缶，終來有他，吉', py: 'yǒu fú bǐ zhī, wú jiù. yǒu fú yíng fǒu, zhōng lái yǒu tā, jí',
          e: 'Six at the beginning: hold together in sincerity — no blame. When sincerity brims the earthen jar, in the end more comes besides. Good fortune.',
          n: '盈缶, sincerity filling a plain clay vessel — honesty without ornament. 終來有他, and good comes from unlooked-for quarters too.' },
        { pos: 2, name: '六二', z: '比之自內，貞吉', py: 'bǐ zhī zì nèi, zhēn jí',
          e: 'Six in the second place: holding together from within. Steadfast, good fortune.',
          n: '自內, the bond formed from inside — inner loyalty. The responsive second line cleaves to the ruler at the fifth; constancy is rewarded.' },
        { pos: 3, name: '六三', z: '比之匪人', py: 'bǐ zhī fěi rén',
          e: 'Six in the third place: holding together with the wrong people.',
          n: 'Three characters, terse and dark: 匪人, “not the right sort.” An alliance ill-chosen, whose ruin is left unspoken.' },
        { pos: 4, name: '六四', z: '外比之，貞吉', py: 'wài bǐ zhī, zhēn jí',
          e: 'Six in the fourth place: holding together with what is outside. Steadfast, good fortune.',
          n: '外比, to ally outward — the fourth line cleaves upward to the ruler (the fifth) beside it. Loyalty turned the right way; 貞吉.' },
        { pos: 5, name: '九五', z: '顯比，王用三驅，失前禽，邑人不誡，吉', py: 'xiǎn bǐ, wáng yòng sān qū, shī qián qín, yì rén bù jiè, jí',
          e: 'Nine in the fifth place: holding together made manifest. The king hunts driving on three sides, letting the game ahead escape; his townspeople are not put on guard. Good fortune.',
          n: 'The illustrious centre. 王用三驅, the royal hunt that beats from three sides and leaves the fourth open — clemency built into the method; 失前禽, the fleeing quarry let go. He binds people not by coercion (邑人不誡) but by magnanimity.' },
        { pos: 6, name: '上六', z: '比之无首，凶', py: 'bǐ zhī wú shǒu, xiōng',
          e: 'Six at the top: holding together with no head. Misfortune.',
          n: '无首, without a beginning, or without a leader — the union joined too late, or lacking its centre. 凶.' },
      ],
      note: 'Water over earth, soaking and binding — union around a centre. Come early and in good faith; the king’s own clemency, the hunt open on one side, shows how to hold others: not by force.',
    },

    9: {
      no: 9,
      name: { zh: '小畜', py: 'Xiǎo Chù', en: 'The Taming Power of the Small' },
      figure: '111011',
      judgment: {
        z: '亨。密雲不雨，自我西郊。', py: 'hēng. mì yún bù yǔ, zì wǒ xī jiāo.',
        e: 'The Taming Power of the Small. Success. Dense clouds, but no rain, from our western border.',
        n: 'A single yielding line restrains the many firm — the gentle (wind) reining the strong (heaven). 密雲不雨, the famous image of accumulation just before release. 西郊, the western quarter — the Zhou homeland’s direction.',
      },
      lines: [
        { pos: 1, name: '初九', z: '復自道，何其咎，吉', py: 'fù zì dào, hé qí jiù, jí',
          e: 'Nine at the beginning: returning by one’s own road — what blame in that? Good fortune.',
          n: '復自道, to come back to your proper path of your own accord. No fault attaches to it; 吉.' },
        { pos: 2, name: '九二', z: '牽復，吉', py: 'qiān fù, jí',
          e: 'Nine in the second place: drawn back. Good fortune.',
          n: '牽復, led back to the right way together with its neighbour — returning not alone but in company. 吉.' },
        { pos: 3, name: '九三', z: '輿說輻，夫妻反目', py: 'yú tuō fú, fū qī fǎn mù',
          e: 'Nine in the third place: the cart’s spokes slip their binding; husband and wife turn their eyes from each other.',
          n: '輿說(脫)輻, the wagon loses the lashing of its spokes — a breakdown. 夫妻反目, estrangement: the restraint, pushed too hard at this place, chafes into discord.' },
        { pos: 4, name: '六四', z: '有孚，血去惕出，无咎', py: 'yǒu fú, xuè qù tì chū, wú jiù',
          e: 'Six in the fourth place: there is sincerity. The blood departs, fear goes out. No blame.',
          n: 'The one yin line — the small that tames. By sincerity (有孚), bloodshed is averted (血去) and dread dispelled (惕出); 无咎.' },
        { pos: 5, name: '九五', z: '有孚攣如，富以其鄰', py: 'yǒu fú luán rú, fù yǐ qí lín',
          e: 'Nine in the fifth place: sincerity that binds, as hand clasps hand; rich, and bringing his neighbours with him.',
          n: '攣如, linked as if clasped together. 富以其鄰, wealth that does not hoard but draws the neighbours into its good fortune.' },
        { pos: 6, name: '上九', z: '既雨既處，尚德載，婦貞厲。月幾望，君子征凶', py: 'jì yǔ jì chǔ, shàng dé zài, fù zhēn lì. yuè jī wàng, jūnzǐ zhēng xiōng',
          e: 'Nine at the top: it has rained, it has settled — esteem laden full with virtue. The wife, steadfast, is in danger. The moon almost full; for the noble one to advance, misfortune.',
          n: '既雨既處, the rain has fallen and the restraint is achieved; 尚德載, merit carried to the brim. 婦貞厲, the restraining “wife” at her limit is imperilled; 月幾望, the moon near full — the yielding at its height — warns against excess: to push on now (君子征) is 凶.' },
      ],
      note: 'A single yielding line holds back the strong: small restraint, dense clouds not yet rain. Accumulation by gentleness — perilous only when, like the near-full moon, it presumes too far.',
    },

    10: {
      no: 10,
      name: { zh: '履', py: 'Lǚ', en: 'Treading · Conduct' },
      figure: '110111',
      judgment: {
        z: '履虎尾，不咥人，亨。', py: 'lǚ hǔ wěi, bù dié rén, hēng.',
        e: 'Treading on the tiger’s tail: it does not bite the man. Success.',
        n: '履, to tread — and so, how one conducts oneself (the graph is also a shoe). The image: walk so carefully behind the tiger that it does not turn — right conduct kept up in dangerous nearness.',
      },
      lines: [
        { pos: 1, name: '初九', z: '素履，往无咎', py: 'sù lǚ, wǎng wú jiù',
          e: 'Nine at the beginning: plain treading. To go: no blame.',
          n: '素履, unadorned conduct — to walk simply, without pretension. So setting out, no blame.' },
        { pos: 2, name: '九二', z: '履道坦坦，幽人貞吉', py: 'lǚ dào tǎn tǎn, yōu rén zhēn jí',
          e: 'Nine in the second place: treading a smooth, level road. The retiring person, steadfast — good fortune.',
          n: '坦坦, broad and even. 幽人, the quiet, withdrawn one who keeps his own counsel; for such a one, calm constancy is auspicious.' },
        { pos: 3, name: '六三', z: '眇能視，跛能履，履虎尾，咥人，凶。武人為于大君', py: 'miǎo néng shì, bǒ néng lǚ, lǚ hǔ wěi, dié rén, xiōng. wǔ rén wéi yú dà jūn',
          e: 'Six in the third place: a one-eyed man can still see, a lame man can still walk — but such a one treading the tiger’s tail: it bites him. Misfortune. The mere soldier plays the great ruler.',
          n: 'Capacity overreaching itself: half-sight and a limp set to a task that needs whole eyes and sound feet. 武人為于大君, a common warrior acting the sovereign — presumption that the tiger duly punishes.' },
        { pos: 4, name: '九四', z: '履虎尾，愬愬，終吉', py: 'lǚ hǔ wěi, sù sù, zhōng jí',
          e: 'Nine in the fourth place: treading on the tiger’s tail — wary upon wary, in the end good fortune.',
          n: '愬愬, fearful and circumspect. The very danger, met with unbroken caution, comes through to 終吉.' },
        { pos: 5, name: '九五', z: '夬履，貞厲', py: 'guài lǚ, zhēn lì',
          e: 'Nine in the fifth place: resolute treading. Steadfast — yet danger.',
          n: '夬履, decisive, forceful conduct — the strong ruler striding out. Even correctness (貞) here carries risk (厲): resolve must not harden into recklessness.' },
        { pos: 6, name: '上九', z: '視履考祥，其旋元吉', py: 'shì lǚ kǎo xiáng, qí xuán yuán jí',
          e: 'Nine at the top: look back over your treading and weigh the omens; where it comes full circle, supreme good fortune.',
          n: '視履, review the whole course you have walked; 考祥, examine the signs it leaves. 其旋, where the path returns upon itself and is complete — 元吉.' },
      ],
      note: 'Heaven above the lake — right conduct close to danger. Tread the tiger’s tail with care and it will not bite; and at the last, look back over the whole path to read its fortune.',
    },
  },
};

if (typeof window !== 'undefined') window.ZHOUYI = ZHOUYI;
