/* Vita Merlini — "The Life of Merlin," Geoffrey of Monmouth's Latin poem of
   1,529 hexameters, composed c. 1150 and dedicated to Robert de Chesney,
   Bishop of Lincoln (1148–1166). The English shown alongside the Latin is an
   original translation written movement by movement in subsequent passes;
   John Jay Parry's public-domain prose version (Univ. of Illinois, 1925) is
   consulted as a sense-check, not copied, and Basil Clarke's 1973 edition is
   referenced for its commentary only.

   The Latin is the text of Parry's 1925 edition as transcribed at the
   Internet Sacred Text Archive (public domain — the U.S. copyright was not
   renewed). That transcription prints the poem in a medieval orthography
   (u for consonantal v, enclitic -que set off as a separate word, a raised
   point marking the caesura); the Latin here is normalised by hand into a
   classical reading orthography (v for consonantal u, enclitics rejoined,
   modern punctuation and capitalisation) movement by movement, the same
   convention used for the Welsh of Pwyll and Owain on this site. The source
   is never paraphrased away — only re-spelled.

   Both source texts are preserved verbatim under source/:
     vita-merlini-parry-1925-latin.txt     (the Latin, as transcribed)
     vita-merlini-parry-1925-english.txt   (Parry's comparison translation)
   Attaches to window.VITAMERLINI. */
window.VITAMERLINI = window.VITAMERLINI || {};
window.VITAMERLINI.tale = {
  meta: {
    blurb: "<strong>Vita Merlini</strong> — \"The Life of Merlin\" — Geoffrey of Monmouth's Latin poem in 1,529 hexameters, written about 1150 and dedicated to Robert de Chesney, Bishop of Lincoln. It is not the boy-prophet of Geoffrey's earlier <em>Historia Regum Britanniae</em> but an older, wilder figure drawn from a separate Welsh tradition — the <em>Myrddin Wyllt</em>, Merlin the Wild. After the slaughter of the battle of Arfderydd, <strong>Merlin</strong>, king and prophet of the Demetae (the South Welsh), is broken by grief at the death of his companions, goes mad, and flees into the Caledonian Wood, where he lives as a <em>silvester homo</em>, a man of the woods, among the beasts. His sister <strong>Ganieda</strong> (Welsh Gwenddydd), wife of King <strong>Rhydderch</strong>, sends a messenger who sings him back to his senses; but at court Merlin relapses, is chained, laughs at a leaf caught in his sister's hair, and so reveals the second sight that both damns and frees him — the leaf, the threefold death, the beggar on the buried treasure. He rides a stag to the wedding of his abandoned wife <strong>Guendoloena</strong> and kills the bridegroom with its antlers; he prophesies the kings of Britain to come; and he hears the bard <strong>Taliesin</strong> discourse on the winds and waters and the <em>Insula Pomorum</em>, the Island of Apples, where <strong>Morgen</strong> tends the wounded Arthur. At last a new spring breaks from the earth and its water heals him; and Merlin, his sister, Taliesin, and the once-mad <strong>Maeldin</strong> withdraw together into the woods to watch the stars. The translation below is <strong>original</strong> and proceeds <strong>movement by movement</strong>; the Latin beside it is Parry's 1925 text in a normalised reading orthography. Full sources preserved at <a href=\"source/vita-merlini-parry-1925-latin.txt\">source/vita-merlini-parry-1925-latin.txt</a> and <a href=\"source/vita-merlini-parry-1925-english.txt\">source/vita-merlini-parry-1925-english.txt</a>.",
    sources: [
      { label: "The Vita Merlini — John Jay Parry, ed. & trans., 1925 (University of Illinois Studies in Language and Literature, vol. X no. 3; public domain, copyright not renewed)", url: "https://archive.org/details/vitamerlini0000geof", host: "Internet Archive" },
      { label: "Vita Merlini: Latin & English — Parry 1925, transcribed", url: "https://sacred-texts.com/neu/eng/vm/index.htm", host: "Internet Sacred Text Archive" },
      { label: "Life of Merlin / Vita Merlini — Basil Clarke, ed., 1973 (Univ. of Wales Press; consulted for commentary)", url: "https://en.wikipedia.org/wiki/Vita_Merlini", host: "Wikipedia" },
      { label: "Vita Merlini — overview, dating, manuscripts", url: "https://en.wikipedia.org/wiki/Vita_Merlini", host: "Wikipedia" },
      { label: "Myrddin Wyllt — the Welsh wild-man tradition behind the poem", url: "https://en.wikipedia.org/wiki/Myrddin_Wyllt", host: "Wikipedia" },
    ],
  },
  roadmap: [
    { t: "Latin source in hand (Parry 1925, normalised reading orthography)", done: true },
    { t: "I · The proem; Arfderydd; Merlin's grief, madness, and flight to the wood", done: true },
    { t: "II · The messenger and the harp: sung back from the wild", done: true },
    { t: "III · Rhydderch's court; the chain; the leaf in Ganieda's hair", done: false },
    { t: "IV · The threefold death; Guendoloena released; the stag-ride to the wedding", done: false },
    { t: "V · The threefold laugh; the observatory; the prophecy of the kings", done: false },
    { t: "VI · Taliesin: the winds, the waters, and the Island of Apples", done: false },
    { t: "VII · The healing spring; the discourse on springs and on birds; the refusal of the crown", done: false },
    { t: "VIII · Maeldin healed; the woodland college; Ganieda's prophecy; the envoi", done: false },
  ],
  passages: [
    {
      title: "I. The madness of the prophet — Arfderydd, and the flight to the wood",
      segments: [
        { w: "Fatidici vatis rabiem musamque iocosam\nMerlini cantare paro: tu corrige carmen,\ngloria pontificum, calamos moderando, Roberte;\nscimus enim quia te perfudit nectare sacro\nPhilosophia suo, fecitque per omnia doctum,\nut documenta dares, dux et praeceptor in orbe.\nErgo meis coeptis faveas, vatemque tueri\nauspicio meliore velis quam fecerit alter,\ncui modo succedis merito promotus honori.",
          e: "The madness of the prophet-seer, and a playful song of Merlin — that is what I set myself to sing. Do you correct the song, Robert, glory of bishops, by guiding my pen; for we know that Philosophy has steeped you in her sacred nectar and made you learned in all things, that you might stand as the world's exemplar, its leader and its teacher. Look kindly, then, on what I begin, and consent to watch over the poet with a better grace than did that other man whose place you have just taken, raised to an honour you deserve.",
          n: "The poem opens by announcing itself as a different kind of book. <em>Rabies</em> (madness) and <em>iocosa musa</em> (a playful, joking muse) are the two notes Geoffrey strikes first — this is not the solemn boy-prophet of his <em>Historia Regum Britanniae</em>. <strong>Robert de Chesney</strong> became Bishop of Lincoln in 1148; the \"other man\" he succeeded is <strong>Alexander of Lincoln</strong>, dedicatee of Geoffrey's earlier <em>Prophetiae Merlini</em>, who had died in 1148. Dating the dedication to Robert's early years gives the poem its conventional date of <em>c.</em> 1150." },

        { w: "Sic etenim mores, sic vita probata genusque\nutilitasque loci, clerus populusque petebant,\nunde modo felix Lincolnia fertur ad astra.\nErgo te cuperem complecti carmine digno,\nsed non sufficio, licet Orpheus et Camerinus\net Macer et Marius magnique Rabirius oris\nore meo canerent, Musis comitantibus, omnes.\nAt vos, consuetae mecum cantare, Camenae,\npropositum cantemus opus, citharamque sonate.",
          e: "For your character, your proven life, your birth, your fitness for the see — clergy and people alike were calling for them, and so happy Lincoln is borne up just now to the stars. I would gladly clasp you, then, in a song worthy of you; but I am not equal to it — not though Orpheus and Camerinus, and Macer and Marius and deep-voiced Rabirius, were all to sing with my mouth and the Muses to sing along. But you, my Camenae, who are used to singing with me: let us sing the work I have set us, and sound the lyre.",
          n: "Geoffrey lines up his impossible chorus of poets — <strong>Orpheus</strong>, the Augustan poets <strong>Macer</strong> and <strong>Rabirius</strong>, the obscure <strong>Camerinus</strong> and <strong>Marius</strong> — only to set them aside for the homelier <strong>Camenae</strong>, the old Italian spring-nymphs the Romans identified with the Muses. The modesty is a topos, but the choice of the rustic, water-haunting Camenae over the grand Muses quietly fits a poem about to flee the court for the woods and the springs." },

        { w: "Ergo peragratis sub multis regibus annis,\nclarus habebatur Merlinus in orbe Britannus.\nRex erat et vates: Demetarumque superbis\niura dabat populis, ducibusque futura canebat.",
          e: "Now when many years had been lived out under many kings, Merlin the Briton was held famous through the world. He was a king and a prophet both: to the proud peoples of the Demetae he gave laws, and to their war-leaders he sang what was to come.",
          n: "<strong>Merlinus … Britannus</strong> — Merlin the Briton, here introduced as a historical king of the <strong>Demetae</strong>, the people of Dyfed (south-west Wales). Geoffrey fuses two figures: the Merlin (Myrddin Emrys) of his <em>Historia</em> and the northern <strong>Myrddin Wyllt</strong> of Welsh tradition, a sixth-century madman-bard of the Old North. The double office — <em>rex et vates</em>, king and seer — is the hinge the whole poem turns on: a man who rules and a man who raves." },

        { w: "Contigit interea plures certamen habere\ninter se regni proceres, belloque feroci\ninsontes populos devastavisse per urbes.\nDux Venedotorum Peredurus bella gerebat\ncontra Guennoloum, Scotiae qui regna regebat;\niamque dies aderat bello praefixa, ducesque\nastabant campo, decertabantque catervae,\namborum pariter miseranda caede ruentes.",
          e: "Meanwhile it fell out that several of the kingdom's great lords took up a quarrel among themselves, and laid the innocent folk of the cities waste with savage war. Peredur, leader of the Venedoti, made war on Gwenddoleu, who ruled the realm of Scotland; and now the day appointed for the battle was at hand, the captains stood ready on the field, and the war-bands fought, falling on either side in pitiable slaughter.",
          n: "This is the historical seed of the legend: the battle of <strong>Arfderydd</strong> (Arthuret, near Carlisle), dated by the Welsh annals to 573. <strong>Peredur</strong> leads the <strong>Venedoti</strong> (the men of Gwynedd, the North Welsh); <strong>Gwenddoleu</strong> (Latin <em>Guennolous</em>) is the northern British king at whose fall, in the Welsh tradition, his bard Myrddin lost his wits. Geoffrey relocates a sixth-century northern battle into his pan-British frame, and makes Merlin a combatant in it." },

        { w: "Venerat ad bellum Merlinus cum Pereduro,\nrex quoque Cambrorum Rodarcus — saevus uterque.\nCedunt obstantes invisis ensibus hostes,\ntresque ducis fratres, fratrem per bella secuti,\nusque rebellantes cedunt perimuntque phalanges.\nInde per infestas cum tali munere turmas\nacriter irruerant, subito cecidere perempti.",
          e: "Merlin had come to the war at Peredur's side, and so had Rhydderch, king of the Cumbrians — both of them grim men. They cut down the enemies that stood against them with hateful swords; and three brothers of the prince, who had followed him through his wars, cut and killed the warring ranks without ceasing. But when they had charged so fiercely, with such service, through the hostile squadrons, all at once they fell — slain.",
          n: "<strong>Rhydderch</strong> (Latin <em>Rodarcus</em>) is Rhydderch Hael, the historical king of <strong>Alt Clut</strong> (Strathclyde) — here \"king of the Cumbrians\" — and in the poem Merlin's brother-in-law, husband of his sister Ganieda. The deaths of the <strong>three brothers</strong> are the wound the whole poem opens from: it is grief, not a spell, that unmakes Merlin's reason. The number three sounds the first of the poem's many triads (the threefold death, the three appearances of the boy, the three laughs)." },

        { w: "Hoc viso, Merline, doles, tristesque per agmen\ncommisces planctus, tali quoque voce remugis:\n\"Ergone sic potuit sors importuna nocere,\nut mihi surriperet tantos talesque sodales,\nquos modo tot reges, tot regna remota timebant?\nO dubios hominum casus, mortemque propinquam,\nquae penes est illos semper, stimuloque latenti\npercutit, et miseram pellit de corpore vitam!\"",
          e: "At the sight of it, Merlin, you grieve; through the host you mingle your sorrowing laments, and bellow out in such words as these: \"Could cruel fortune do me such harm, then — to steal away from me companions so many and so great, whom but lately so many kings and so many far-off kingdoms feared? O the uncertain falls of men, and death so near at hand, that is always upon them, and strikes with its hidden goad, and drives the wretched life out of the body!\"",
          n: "Geoffrey breaks into the second person — <em>Hoc viso, Merline, doles</em>, \"at the sight of it, Merlin, you grieve\" — pulling the reader to Merlin's shoulder at the exact moment his mind begins to give. The lament is built on the oldest of consolation-commonplaces (the turning of fortune, death the universal goad), but it is the seed of the wild man's whole later wisdom: from here on Merlin speaks in laments and prophecies, never again in a king's plain commands." },

        { w: "\"O iuvenile decus, quis nunc astabit in armis,\nnunc mihi pone latus, metumque repellet euntes\nin mea damna duces incumbentesque catervas?\nAudaces iuvenes, vobis audacia vestra\neripuit dulces annos dulcemque iuventam!\nQui modo per cuneos discurrebatis in armis,\nobstantesque viros prosternebatis ubique,\nnunc pulsatis humum, rubeoque cruore rubetis.\"",
          e: "\"O the flower of youth — who will stand by me in arms now, now at my side, and beat back my fear of the captains marching to my ruin and the ranks bearing down? Bold young men: your own boldness has robbed you of your sweet years and your sweet youth! You who but now were ranging in arms through the wedges of battle, and everywhere laying low the men who withstood you — now you beat the ground, and are red with red blood.\"",
          n: "The repetitions — <em>dulces annos dulcemque iuventam</em>, <em>rubeo cruore rubetis</em> (\"red with red blood\") — are the figure called <em>traductio</em>, the same root turned twice; Latin elegy used it for exactly this, the helpless circling of a grief that cannot get past itself. Merlin's eloquence is intact even as his reason fails: that these are not opposites is the poem's central wager." },

        { w: "Sic inter turmas lacrimis plangebat obortis,\ndeflebatque viros, nec cessant proelia dira.\nConcurrunt acies, sternuntur ab hostibus hostes;\nsanguis ubique fluit, plurimi moriuntur utrinque.\nAt tandem Britones, revocatis undique turmis,\nconveniunt pariter, pariterque per arma ruentes\ninvadunt Scotos, prosternunt, vulnera dantes;\nnec requieverunt donec sua terga dederunt\nhostiles turmae, per devia diffugientes.",
          e: "So amid the squadrons he wept with starting tears and mourned the men, while still the dreadful fighting did not stop. The battle-lines clashed, enemy was laid low by enemy, blood ran everywhere, and on both sides men past counting died. But at the last the Britons, calling their squadrons in from every quarter, came together as one, and rushing as one through the press of arms fell on the Scots, broke them, dealt them wounds; nor did they rest until the hostile bands turned their backs and scattered away by the trackless paths.",
          n: "The battle is won, but the victory is given exactly one line of relief before the poem turns wholly to Merlin's grief — Geoffrey will not let the public triumph stand in for the private wound. The \"Scots\" (<em>Scoti</em>) here are Gwenddoleu's northern host; in Geoffrey's loose geography the war is Briton against the peoples of the far north." },

        { w: "Evocat e bello socios Merlinus, et illis\npraecipit in varia fratres sepelire capella;\ndeplangitque viros, nec cessat fundere fletus,\npulveribus crines sparsit, vestesque rescidit,\net prostratus humi nunc hac nunc illac volutat.\nSolatur Peredurus eum, proceresque ducesque;\nnec vult solari, nec verba precantia ferre.\nIam tribus emensis defleverat ille diebus,\nrespueratque cibos, tantus dolor usserat illum.",
          e: "Merlin calls his companions out of the battle and bids them bury the brothers in a many-coloured chapel. He mourns the men, and does not cease to pour out his weeping; he scatters dust on his hair, tears his garments, and flung down on the ground rolls now this way, now that. Peredur tries to comfort him, and so do the nobles and the captains; but he will not be comforted, nor bear their pleading words. Three whole days he had wept now, and had refused all food, so great was the grief that burned him.",
          n: "The mourning rites — dust on the hair, the rent garments, the three days' fast — are the ancient grammar of grief, biblical and Homeric at once. The <em>varia capella</em>, the \"many-coloured chapel,\" is a small anachronism of the kind Geoffrey loves: a Christian burial for the dead of a sixth-century pagan-edged war. Three days of fasting is the threshold; on the fourth, the mind breaks." },

        { w: "Inde novas furias, cum tot tantisque querelis\naera complesset, cepit, furtimque recedit,\net fugit ad silvas, nec vult fugiendo videri.\nIngrediturque nemus, gaudetque latere sub ornis;\nmiraturque feras pascentes gramina saltus;\nnunc has insequitur, nunc cursu praeterit illas;\nutitur herbarum radicibus, utitur herbis,\nutitur arboreo fructu morisque rubeti.\nFit silvester homo, quasi silvis deditus esset.",
          e: "Then, when he had filled the air with laments so many and so great, a new frenzy took him, and he steals away in secret and flees to the woods, not wishing to be seen as he flees. He enters the forest and rejoices to lie hidden under the ash trees; he marvels at the wild beasts grazing the grass of the glades; now he chases them, now he outruns them at a run; he lives on the roots of plants, on the grasses, on the fruit of the trees and the blackberries of the thicket. He becomes a man of the woods, as though he had been given over to them.",
          n: "<strong>Fit silvester homo</strong> — \"he becomes a man of the woods.\" This is the heart of the legend and the line on which the whole tradition of the <em>Wild Man</em> turns: Tristan in his madness, the Irish Suibhne Geilt, the hairy <em>wodewose</em> of the misericords. The madness is not raving idiocy but a flight from the human world into the animal one — a wisdom that has to go through the wild before it can return. The prophet's gift, when it comes, will be the gift the woods give back." },

        { w: "Inde per aestatem totam, nullique repertus,\noblitusque sui cognatorumque suorum,\ndelituit silvis, obductus more ferino.\nAt cum venit hiems herbasque tulisset et omnes\narboreos fructus, nec quo frueretur haberet,\ndiffudit tales miseranda voce querelas:",
          e: "So through a whole summer, found by no one, forgetful of himself and of his own kindred, he lay hidden in the woods, overgrown after the manner of a beast. But when winter came and took away the grasses and all the fruit of the trees, and he had nothing to live on, he poured out in a piteous voice such laments as these:",
          n: "The turn of the season is the turn of the poem's first movement: the summer of beast-forgetfulness gives way to a winter of want, and want gives Merlin back his voice. From here the wild man begins to <em>speak</em> again — first in lament, soon in prophecy. The lament that follows is one of the earliest sustained nature-poems in Latin from Britain." },

        { w: "\"Caeli Christe deus, quid agam? qua parte morari\nterrarum potero, cum nil quo vescar adesse\ninspicio, nec gramen humi nec in arbore glandes?\nTres quater et iuges septem poma ferentes\nhic steterant mali; nunc non stant. Ergo quis illas,\nquis mihi surripuit? quo devenere repente?\nNunc illas video, nec non — sic fata repugnant,\nsic quoque concordant — cum dant prohibentque videre.\"",
          e: "\"Christ, God of heaven, what am I to do? In what corner of the earth can I stay, when I see nothing here to feed on — neither grass on the ground nor acorns on the tree? Here once there stood nineteen apple trees, each year bearing their apples; now they do not stand. Who, then — who has stolen them from me? Where have they gone, all at once? Now I see them — and now I do not: so the fates fight me, and so too agree, when they both grant me sight and deny it.\"",
          n: "The <strong>nineteen apple trees</strong> (\"three times four and seven yoked together\") are one of the poem's deep enigmas — apples being the fruit of the Otherworld in Celtic myth, and nineteen the years of the lunar Metonic cycle. The trees that are seen and not seen mark the onset of Merlin's <em>second</em> sight: the same doubled vision — granted and forbidden — that will let him read a leaf, a death, a buried hoard. The apple returns at the poem's far end, on the Island of Apples." },

        { w: "\"Deficiunt nunc poma mihi, nunc cetera quaeque;\nstat sine fronde nemus, sine fructu — plector utroque,\ncum neque fronde tegi valeo neque fructibus uti.\nSingula bruma tulit pluviisque cadentibus auster.\nInvenio si forte napes tellure sub ima,\nconcurrunt avidaeque sues aprique voraces,\neripiuntque napes mihi, quas de caespite vello.\"",
          e: "\"Now the apples fail me, now everything else; the wood stands leafless, fruitless — and I am racked both ways, since I can neither shelter under the leaves nor feed on the fruit. The winter has carried off each one, and the south wind with its falling rains. If by chance I find some turnips deep in the earth, the greedy sows and the ravening boars come running and snatch the turnips from me as I tear them from the turf.\"",
          n: "The fall from king to forager is total: a man who gave laws to nations now fights wild pigs for a turnip. Geoffrey's realism here — the leafless wood, the rooting boars, the rain on the south wind — is unusually exact for twelfth-century Latin verse, and it is the ground against which the coming marvels (the stag-ride, the springs, the Island of Apples) will read as marvels." },

        { w: "\"Tu, lupe care comes, nemorum qui devia mecum\net saltus peragrare soles, vix praeteris arva;\net te dura fames et me languere coegit.\nTu prior has silvas coluisti, te prior aetas\nprotulit in canos; nec habes nec scis quid in ore\nproicias — quod miror ego, cum saltus abundet\ntot capreis aliisque feris, quas prendere posses.\nForsitan ipsa tibi tua detestanda senectus\neripuit nervos cursumque negavit habendum.\nQuod solum superest, comples ululatibus auras,\nat resupinus humi consumptos deicis artus.\"",
          e: "\"You, dear wolf, my companion, who used to roam the byways of the woods and the glades with me — now you can scarcely cross the fields; hard hunger has worn us both thin, you and me. You haunted these woods before I did, and age has turned you grey before me; you have nothing, and do not know what to throw into your mouth — which is a wonder to me, since the glade teems with roe-deer and other beasts you could catch. Perhaps it is your own hateful old age that has stripped the strength from you and denied you the chase. The one thing left you, you fill the air with howling; and stretched on your back on the ground you throw down your wasted limbs.\"",
          n: "The grey wolf is the wild man's one companion and his mirror — old, starving, past the hunt, howling on its back in the snow. Geoffrey gives the madman an animal interlocutor exactly where a king would have councillors; the apostrophe to the wolf is the emotional floor of the poem, the point furthest from the court. Everything after this is a slow return. The Irish <em>Buile Shuibhne</em> gives its wild king the same beast-companions, a sign of the shared Celtic substratum behind both poems." },
      ],
    },
    {
      title: "II. The messenger and the harp — sung back from the wild",
      segments: [
        { w: "Haec inter fruticeta coryletaque densa canebat,\ncum sonus ad quemdam pervenit praetereuntem,\nqui direxit iter quo sermo loquentis in auras\nexierat, reperitque locum reperitque loquentem.\nQuo viso, Merlinus abit, sequiturque viator,\nnec retinere virum potuit sic diffugientem.\nInde viator iter repetit quo coeperat ire,\npropositumque tenet, casu commotus euntis.",
          e: "These things he was singing among the thickets and the dense hazel-clumps, when the sound reached a certain passer-by, who turned his steps to where the speaker's words had gone out upon the air, and found the place and found the speaker. At the sight of him Merlin departs, and the traveller follows, yet could not hold the man as he fled away. So the traveller takes up again the road he had set out on, and keeps to his errand, moved by the fugitive's lot.",
          n: "The structure of the whole episode is a relay of finders: a chance traveller hears Merlin, loses him, and carries word to one of the queen's searchers, who in turn climbs to the spring. Geoffrey stages the return from madness as a chain of human contact reaching, link by link, into the wild — the opposite motion to the solitary flight of movement I." },

        { w: "Ecce viatori venit obvius alter ab aula\nRodarchi regis Cumbrorum, qui Ganiedam\nduxerat uxorem, formosa coniuge felix.\nMerlini soror ista fuit, casumque dolebat\nfratris, et ad silvas et ad arva remota clientes\nmiserat ut fratrem revocarent; ex quibus unus\nobvius huic ibat. Convenere simul, commiscentque mutua verba.\nAt qui missus erat Merlinum quaerere, quaerit\nsi vidisset eum silvis aut saltibus alter.\nIlle virum talem se conspexisse fatetur\ninter dumosos saltus nemoris Calidonis;\ndumque loqui vellet secum secumque sedere,\ndiffugisse virum celeri per robora cursu.\nHaec ait; alter abit, silvasque subintrat, et imas\nscrutatur valles, montes quoque praeterit altos;\nquaerit ubique virum, gradiens per opaca locorum.",
          e: "And lo, there came to meet the traveller another man, from the court of Rhydderch, king of the Cumbrians, who had taken Ganieda to wife and was happy in his lovely consort. She was Merlin's sister, and grieved at her brother's fate; and she had sent retainers to the woods and the far fields to call her brother home, and one of these was coming to meet him. They met, and exchange words between them. And the one sent to seek Merlin asks whether the other had seen him in the woods or the glades. The traveller owns that he had seen such a man among the bramble-glades of the Caledonian wood; and that when he wished to speak with him and sit beside him, the man had fled away at a swift run through the oaks. This he says; the other departs, and goes down into the woods, and searches the deepest valleys, and crosses the high mountains too; everywhere he seeks the man, walking through the shadowed places.",
          n: "<strong>Ganieda</strong> (Welsh <em>Gwenddydd</em>) enters here — Merlin's sister, Rhydderch's queen, and the poem's central woman. It is she, not the king, who sends searchers into the wild for love of her brother; and it is she who will, at the very end, inherit his prophetic gift and outlast him. The <strong>nemus Calidonis</strong> is the <em>Coed Celyddon</em>, the great forest of the Old North that the Welsh tradition assigns to Myrddin Wyllt's exile." },

        { w: "Fons erat in summo cuiusdam vertice montis,\nundique praecinctus corylis densisque frutectis.\nIllic Merlinus consederat, inde per omnes\nspectabat silvas cursusque iocosque ferarum.\nNuntius hunc scandit, tacitoque per ardua gressu\nincedit quaerendo virum; tum denique fontem\nMerlinumque videt super herbas pone sedentem,\ndicentemque suas tali sermone querelas:",
          e: "There was a spring on the very crown of a certain mountain, hedged all about with hazels and dense bushes. There Merlin had sat down, and from there he looked out over all the woods, over the runnings and the play of the wild beasts. The messenger climbs to it, and with silent step up the steep goes on, seeking the man; and then at last he sees the spring, and Merlin sitting on the grass behind it, speaking his laments in such words as these:",
          n: "The <strong>spring on the mountaintop</strong> is the first of the poem's many fountains — and the messenger finds Merlin already seated beside water, watching the beasts. Geoffrey rings the whole poem with springs: the cure that breaks out at the very end (movement VII) is a <em>fons</em> that rises from the earth, and Taliesin's great discourse (movement VI) is largely a catalogue of marvellous waters. The wild man's high seat above the woods is also the germ of the observatory Ganieda will later build him." },

        { w: "\"O qui cuncta regis, quid est cur contigit ut non\ntempora sint eadem, numeris distincta quaternis?\nNunc ver iure suo flores frondesque ministrat,\ndat fruges aestas, autumnus mitia poma;\nconsequitur glacialis hiemps, et cetera quaeque\ndevorat et vastat, pluviasque nivesque reportat;\nsingula quaeque suis arcet laeditque procellis,\nnec permittit humum varios producere flores,\naut quercus glandes, aut malos Punica mala.\"",
          e: "\"O you who govern all things, why has it come about that the seasons are not all one, but parted off by their four numbers? Now spring of its own right furnishes the flowers and the leaves; summer gives the grain, autumn the mellow apples; then icy winter follows and devours and lays waste all the rest, and brings back the rains and the snows. Each season checks and harms the others with its own storms, and will not let the ground put forth its various flowers, nor the oaks their acorns, nor the apple-trees their crimson apples.\"",
          n: "The lament has turned from hunger to <em>cosmology</em>: the madman now arraigns the very ordering of the year. This is the first sign of the philosopher inside the wild man — the same voice that will, by the poem's end, discourse on the winds, the waters, and the stars. <em>Punica mala</em> (\"Punic apples\") are properly pomegranates, but here stand for the apple-tree's red fruit: the apple-thread of movement I, now reframed as a question about the justice of nature." },

        { w: "\"O utinam non esset hiemps aut cana pruina!\nVer foret aut aestas, cuculusque canendo rediret,\net Philomena pio quae tristia pectora cantu\nmitigat, et turtur conservans foedera casta;\nfrondibus inque novis concordi voce volucres\ncantarent aliae, quae me modulando foverent,\ndum nova flore novo tellus spiraret odorem\ngramine sub viridi; levi quoque murmure fontes\ndiffluerent, iuxtaque daret sub fronde columba\nsomniferos gemitus, irritaretque soporem.\"",
          e: "\"O would there were no winter, no hoar frost! Would it were spring, or summer, and the cuckoo came back singing, and the nightingale who soothes sad hearts with her tender song, and the turtle-dove that keeps her chaste troth; and that among the new leaves the other birds sang too with one accord, and cherished me with their music, while the fresh earth breathed out its scent from new flowers under the green grass; and that the springs ran off with a light murmur, and close at hand, under the leaves, the dove gave its sleep-bringing moans and tempted slumber.\"",
          n: "A catalogue of birds — cuckoo, nightingale (<em>Philomena</em>), turtle-dove, wood-pigeon — answered by murmuring springs and scented earth: the wild man dreams the spring he cannot have. The birds prefigure the long ornithological discourse Merlin will deliver near the close (movement VII); his wisdom is of the woods before it is of the court. The nightingale's healing song also quietly cues the harper, who is about to do for Merlin exactly what he wishes the birds would." },

        { w: "Nuntius audierat vatem, rupitque querelas\ncum modulis citharae, quam secum gesserat ultro,\nut sic deciperet demulceretque furentem.\nErgo movens querulas digitis et in ordine chordas,\ntalia pone latens, dimissa voce, canebat:",
          e: "The messenger had heard the seer, and broke off his laments with the strains of a cithara that he had brought with him on purpose, to beguile and soothe the madman so. And so, moving the plaintive strings in their order with his fingers, hidden behind him, in a low voice he sang such things as these:",
          n: "The cure is music. The harp as the medicine for madness is the oldest of mythic patterns — the Orpheus story, which on this site has its own deep-read in <a href=\"/orfeo/\"><em>Sir Orfeo</em></a>, where the harp likewise passes between the wild Otherworld and the human court. The detail that the harper sings <em>pone latens</em>, hidden behind Merlin, is exact craft: the sweetness must reach him before he can flee the man making it." },

        { w: "\"O diros gemitus lugubris Guendoloenae!\nO miseras lacrimas lacrimantis Guendoloenae!\nMe miseret miserae morientis Guendoloenae!\nNon erat in Wallis mulier formosior illa;\nvincebat candore deas foliumque ligustri,\nvernantesque rosas et olentia lilia prati;\ngloria vernalis sola radiabat in illa,\nsidereumque decus geminis gestabat ocellis,\ninsignesque comas auri fulgore nitentes.\"",
          e: "\"O the dreadful groans of mournful Guendoloena! O the wretched tears of weeping Guendoloena! I pity poor Guendoloena, dying of grief! There was no fairer woman in all Wales than she: she outshone the goddesses in whiteness, and the privet's leaf, and the blushing roses, and the fragrant lilies of the meadow; the glory of spring shone in her alone, and she bore a starry loveliness in her two eyes, and splendid hair gleaming with the brightness of gold.\"",
          n: "<strong>Guendoloena</strong> — Merlin's <em>wife</em>, not to be confused with Ganieda his sister. The triple anaphora on her name, with its hammering alliteration (<em>Me miseret miserae morientis</em>), is Geoffrey at his most Ovidian, and the catalogue of her beauty (privet, rose, lily, starry eyes, golden hair) is the textbook <em>descriptio</em> of the beloved. The song reaches Merlin not through reason but through this portrait of a faithful grief — which makes the bitter irony of movement IV, when he rides to her wedding, all the sharper." },

        { w: "\"Hoc totum periit, periit decor omnis in illa,\net color et facies, niveae quoque gloria carnis;\nnon est quod fuerat, multis maeroribus acta;\nnescit enim quo dux abiit, vitane fruatur\nan sit defunctus; languet miserabilis inde,\ntotaque deperiit, longo liquefacta dolore.\"",
          e: "\"All this has perished — all her beauty has perished in her: her colour, her face, the glory of her snow-white flesh. She is not what she was, worn down by many griefs; for she does not know where her lord has gone, whether he still has the joy of life or is dead. And so she pines, pitiable, and is wholly wasted away, melted by her long sorrow.\"",
          n: "The cruelty of Guendoloena's case is precisely its <em>uncertainty</em> — she cannot mourn, because she does not know whether to mourn; her husband is neither dead nor present. It is the particular grief of the wives of the missing, and Geoffrey will sharpen it into law in movement IV, when Merlin frees her to remarry on the condition that he himself may come to the wedding." },

        { w: "\"Collacrimatur ei paribus Ganieda querelis,\namissumque dolet sine consolamine fratrem.\nHaec fratrem flet, et illa virum; communiter ambae\nfletibus incumbunt et tristia tempora ducunt.\nNon cibus ullus eis, nec somnus; nocte vagantes\nsub virgulta — fovet tantus dolor, arcet utramque.\nNon secus indoluit Sidonia Dido, solutis\nclassibus, Aeneae tunc cum properaret abire;\ncum non Demophoon per tempora pacta rediret,\ntaliter ingemuit flevitque miserrima Phyllis;\nBriseis absentem sic deploravit Achillem.\nSic soror et coniunx collamentantur et ardent.\"",
          e: "\"Ganieda weeps with her in laments like her own, and grieves past all comfort for the brother she has lost. The one bewails a brother, the other a husband; together both give themselves to weeping and lead their days in sorrow. No food for them, no sleep; wandering by night beneath the thickets — so great a grief at once cherishes and confines them both. Not otherwise did Sidonian Dido grieve, when the fleet was loosed and Aeneas was hastening then to be gone; just so did most wretched Phyllis groan and weep, when Demophoon did not come back within the appointed days; so Briseis bewailed her absent Achilles. Just so the sister and the wife lament together, and burn.\"",
          n: "Three exempla, all of them Ovid's: <strong>Dido</strong> abandoned by Aeneas (<em>Heroides</em> 7, and <em>Aeneid</em> 4), <strong>Phyllis</strong> waiting for Demophoon past the appointed day (<em>Heroides</em> 2), <strong>Briseis</strong> parted from Achilles (<em>Heroides</em> 3). Geoffrey writes British grief into the Latin canon of abandoned women — and the choice is pointed: all three were left by men who sailed away or failed to return \"within the appointed time,\" the very crime Merlin is about to commit against Guendoloena. The learned comfort carries its own indictment." },

        { w: "Funditus internis cruciatibus, usque dolendo,\nin gravibus querulis dicebat talia cantans\nnuntius; et modulo vatis demulserat aures,\nmitior ut fleret congauderetque canenti.\nOcius assurgit vates, iuvenemque iocosis\naffatur verbis, iterumque movere precatur\ncum digitis chordas, elegosque sonare priores.\nAdmovet ille lyrae digitos, iussumque reformat\ncarmen item, cogitque virum modulando furorem\nponere paulatim, citharae dulcedine captum.",
          e: "From the very depths, with inward torments, ever grieving, in heavy plaints the messenger sang such things; and with his music he had soothed the seer's ears, so that he wept more gently and took joy with the singer. Quickly the seer rises, and addresses the young man with friendly words, and begs him to move the strings again with his fingers and sound the former elegies. The other sets his fingers to the lyre and shapes the bidden song once more, and by his music compels the man, little by little, to lay aside his frenzy — caught by the sweetness of the cithara.",
          n: "Note how the cure works: not by the song's <em>argument</em> (which is, after all, a catalogue of women ruined by absent men) but by its <em>sweetness</em> — <em>citharae dulcedine captum</em>, \"caught by the sweetness of the cithara.\" Merlin even asks for an encore. The madness yields to beauty, not to sense; and that is why it will prove so fragile when, in the next movement, he is set down among a crowd with no music to hold him." },

        { w: "Fit memor ergo sui, recolitque quod esse solebat\nMerlinus, furiasque suas miratur et odit.\nPristina mens rediit, rediit quoque sensus in illo,\net gemit ad nomen, motus pietate sororis\nuxorisque simul, mentis ratione recepta.\nConducique petit Rodarchi regis ad aulam.\nParuit alter ei; silvasque subinde relinquunt,\net veniunt pariter, laetantes, regis in urbem.",
          e: "And so Merlin becomes mindful of himself, and recalls what he used to be, and marvels at his own madness, and hates it. His former mind came back, his senses came back in him; and he groans at the name, moved by tenderness for his sister and his wife at once, his reason now recovered. And he asks to be conducted to the court of King Rhydderch. The other obeyed him; and thereupon they leave the woods, and come together, rejoicing, into the king's city.",
          n: "The return is sealed by <em>pietas</em> — Merlin groans \"at the name,\" bound back to the human world by love of his kin rather than by any cure of the understanding. It is a real recovery, but a social and fragile one: it holds only as long as the music and the names do. The movement closes on the word <em>urbem</em>, the city — the exact opposite of the wood he fled to, and the place where, among its crowds, the madness will seize him again." },
      ],
    },
  ],
};
