/* The cast of Culhwch ac Olwen — the first stratum of the annotation layer.
   Each entry carries its role, the movements it appears in (links into the
   reading), and typed relationships (which seed the character web to come).
   Attaches to window.CULHWCH. */
window.CULHWCH = window.CULHWCH || {};
window.CULHWCH.characters = {
  intro: "The tale runs on an enormous cast — Arthur's court alone is a roll-call of hundreds. These are the figures who actually <em>do</em> something in the story, grouped by the part they play. Each card notes the movements where the character appears (click to read), and the relationships that bind them — the raw material for a character web. Welsh names are given where they differ; familiar English equivalents are noted in brackets.",
  roles: [
    { id: "principal",  label: "Principals",          color: "#c9a24a" },
    { id: "companion",  label: "The six companions",   color: "#6fa8c9" },
    { id: "household",  label: "Kin & household",      color: "#7fb37f" },
    { id: "helper",     label: "Helpers & powers",     color: "#c97f9a" },
    { id: "antagonist", label: "Antagonists",          color: "#cf6a6a" },
    { id: "animal",     label: "The oldest animals",   color: "#8fb0a0" },
  ],
  cast: [
    // — Principals —
    { id: "culhwch", name: "Culhwch", role: "principal", epithet: "the hero, born in a pig-run",
      blurb: "A king's son named for the sty he was born in, and first cousin to Arthur. A curse fixes his whole life on a woman he has never seen; he wins her not by his own deeds but by claiming Arthur's help. He is less a doer than a catalyst — the wish around which the quest organizes itself.",
      appears: [1, 2, 3, 6, 7, 8, 12],
      rel: [{ to: "olwen", label: "loves" }, { to: "arthur", label: "first cousin" }, { to: "goleuddydd", label: "son of" }, { to: "ysbaddaden", label: "must win his daughter" }] },
    { id: "olwen", name: "Olwen", role: "principal", epithet: "“white-track”",
      blurb: "Ysbaddaden's daughter, in whose footsteps white trefoils spring. She appears only twice, but turns the plot: she will not elope (her father dies the day she weds), and instead coaches Culhwch to out-promise the giant. The prize who quietly sets the terms.",
      appears: [6, 12],
      rel: [{ to: "culhwch", label: "loved by" }, { to: "ysbaddaden", label: "daughter of" }] },
    { id: "ysbaddaden", name: "Ysbaddaden Bencawr", role: "antagonist", welsh: "Ysbaddaden Bencawr", epithet: "the Chief Giant",
      blurb: "The giant whose eyebrows must be forked up before he can see, fated to die when his daughter marries. Every impossible task he sets is a giant fighting for his own life. Grotesque, grumbling, and — three poisoned spears later — doomed anyway.",
      appears: [7, 8, 11, 12],
      rel: [{ to: "olwen", label: "father of" }, { to: "custennin", label: "brother (wronged)" }, { to: "culhwch", label: "adversary" }, { to: "goreu", label: "slain by" }] },
    { id: "arthur", name: "Arthur", role: "principal",
      blurb: "Here a Welsh warlord at the head of a fabulous warband, not yet a courtly king. He is the engine Culhwch borrows: he grants the boon, lends the heroes, storms Caer Loyw, hunts the great boar, and kills the Black Witch with his own dagger. The quest is really Arthur's.",
      appears: [2, 3, 9, 10, 11],
      rel: [{ to: "culhwch", label: "kinsman & patron" }, { to: "cei", label: "leads" }, { to: "twrch", label: "hunts" }] },

    // — The six companions —
    { id: "cei", name: "Cei", role: "companion", epithet: "(Kay)",
      blurb: "A hero of outright superpowers — nine days underwater, a furnace for warmth, as tall as a tree at will, his sword-wounds incurable. Prickly (he argues against admitting Culhwch) yet becomes the quest's fiercest champion. Centuries later the French will demote him to Arthur's surly steward.",
      appears: [2, 3, 4, 5, 9, 11],
      rel: [{ to: "arthur", label: "Arthur's man" }, { to: "bedwyr", label: "sworn companion" }] },
    { id: "bedwyr", name: "Bedwyr", role: "companion", epithet: "(Bedivere)",
      blurb: "One-handed, yet none draws blood faster in battle; his spear makes one wound going in and nine coming out. Cei's inseparable comrade. Not yet the knight who returns Excalibur to the lake.",
      appears: [3, 7, 9, 10],
      rel: [{ to: "cei", label: "sworn companion" }] },
    { id: "cynddylig", name: "Cynddylig", role: "companion", welsh: "Cynddylig Gyfarwydd", epithet: "the Guide",
      blurb: "As sure of his way in a land he has never seen as in his own country. The companion who is never lost — pure quest-logic made into a man.",
      appears: [3], rel: [] },
    { id: "gwrhyr", name: "Gwrhyr", role: "companion", welsh: "Gwrhyr Gwalstawd Ieithoedd", epithet: "Interpreter of Tongues",
      blurb: "He knows every language, even those of birds and beasts. His gift drives two of the tale's set-pieces: the parley with the speaking boar, and the council of the world's oldest animals that locates Mabon.",
      appears: [3, 4, 9, 10],
      rel: [{ to: "animals", label: "questions" }, { to: "twrch", label: "parleys with" }] },
    { id: "gwalchmai", name: "Gwalchmai", role: "companion", welsh: "Gwalchmai mab Gwyar", epithet: "(Gawain)",
      blurb: "Best of walkers and best of riders, who never came home without his errand. Arthur's nephew — already, in the oldest tale, the unfailing one.",
      appears: [3], rel: [{ to: "arthur", label: "nephew of" }] },
    { id: "menw", name: "Menw mab Teirgwaedd", role: "companion", epithet: "the enchanter",
      blurb: "Shapeshifter and caster of glamours: he can hide the company in plain sight, tame the herdsman's hound, and fly as a bird to scout the boar's treasures — a scouting that earns him a faceful of venom he never recovers from.",
      appears: [3, 4, 7, 10],
      rel: [{ to: "twrch", label: "scouts" }] },

    // — Kin & household —
    { id: "goleuddydd", name: "Goleuddydd", role: "household",
      blurb: "Culhwch's mother, who goes wild in pregnancy and gives birth among swine. Dying, she leaves the loophole — the two-headed briar — that will eventually loose the whole story.",
      appears: [1], rel: [{ to: "culhwch", label: "mother of" }, { to: "cilydd", label: "wife of" }] },
    { id: "cilydd", name: "Cilydd", role: "household", welsh: "Cilydd mab Celyddon Wledig",
      blurb: "Culhwch's father, who remarries when the briar grows, and later sends his lovesick son to seek Arthur's help.",
      appears: [1], rel: [{ to: "culhwch", label: "father of" }] },
    { id: "stepmother", name: "The stepmother", role: "household",
      blurb: "The queen taken by force from King Doged. It is she who lays the destiny on Culhwch — bind him to Olwen — and so, out of spite or fate, sets the quest in motion.",
      appears: [1], rel: [{ to: "culhwch", label: "curses" }] },
    { id: "custennin", name: "Custennin", role: "household", welsh: "Custennin mab Mynwiedig", epithet: "the herdsman",
      blurb: "A fire-breathing giant herdsman with a monstrous hound — and Ysbaddaden's brother, ruined and dispossessed by him. He turns out to be Culhwch's uncle by marriage, and warns the company that none who seek Olwen leave alive.",
      appears: [4, 5],
      rel: [{ to: "ysbaddaden", label: "brother of" }, { to: "goreu", label: "father of" }] },
    { id: "custennin-wife", name: "Custennin's wife", role: "household",
      blurb: "Culhwch's aunt — his dead mother's sister. Her joy nearly crushes the company (Cei lets her squeeze a log to splinters instead of his ribs); she hides her last surviving son in a stone chest.",
      appears: [5],
      rel: [{ to: "culhwch", label: "aunt of" }, { to: "goreu", label: "mother of" }] },
    { id: "goreu", name: "Goreu mab Custennin", role: "household", epithet: "the avenger",
      blurb: "The one son hidden in the stone chest — twenty-three of his brothers killed by Ysbaddaden. He is the blade the tale keeps in reserve: at the very end it is Goreu who drags the giant to the mound and takes his head.",
      appears: [5, 12],
      rel: [{ to: "custennin", label: "son of" }, { to: "ysbaddaden", label: "beheads" }] },
    { id: "glewlwyd", name: "Glewlwyd Gafaelfawr", role: "household", epithet: "the porter",
      blurb: "Arthur's gatekeeper on New Year's Day, who bars Culhwch until threatened with three world-shaking shouts — the comic threshold-guardian of Arthur's court.",
      appears: [2], rel: [{ to: "arthur", label: "Arthur's porter" }] },

    // — Helpers & powers —
    { id: "mabon", name: "Mabon mab Modron", role: "helper", epithet: "the divine youth",
      blurb: "“Divine Son” son of “Divine Mother” — an old Celtic god (Maponos) in disguise, stolen from his mother at three nights old and imprisoned at Caer Loyw. Freed by Arthur, he is the only huntsman who can handle the hound Drudwyn, and snatches the razor from the boar in the Severn.",
      appears: [8, 9, 10],
      rel: [{ to: "arthur", label: "freed by" }, { to: "twrch", label: "hunts" }] },
    { id: "eidoel", name: "Eidoel mab Aer", role: "helper",
      blurb: "Mabon's kinsman, freed from the fort of Glini. The search for the lost god begins by springing one prisoner to find another.",
      appears: [9], rel: [{ to: "mabon", label: "kinsman of" }] },
    { id: "gwyn", name: "Gwyn ap Nudd", role: "helper", epithet: "lord of Annwn",
      blurb: "King of the Welsh Otherworld and the fair folk, into whom God put the fury of the demons of Annwn lest the world be destroyed. Demanded for the hunt — the deepest the tale reaches into the fae.",
      appears: [8], rel: [{ to: "twrch", label: "needed to hunt" }] },

    // — Antagonists —
    { id: "twrch", name: "Twrch Trwyth", role: "antagonist", epithet: "the great boar",
      blurb: "A king whom God turned into a venomous boar for his sins, with the comb, shears and razor lodged between his ears and seven young pigs at his side. The hunt for him — Ireland to Wales to Cornwall — is the tale's climax; driven into the sea at last, he is never seen again.",
      appears: [8, 10],
      rel: [{ to: "arthur", label: "hunted by" }, { to: "mabon", label: "robbed by" }] },
    { id: "blackwitch", name: "The Black Witch", role: "antagonist", welsh: "Orddu", epithet: "of the Valley of Grief",
      blurb: "Daughter of the White Witch, from the head of a valley on the borders of Hell. Her blood is the last task. She thrashes two pairs of Arthur's men senseless before Arthur himself splits her in two from the cave-mouth with his dagger Carnwennan.",
      appears: [8, 11],
      rel: [{ to: "arthur", label: "slain by" }] },

    // — The oldest animals —
    { id: "animals", name: "The Oldest Animals", role: "animal", epithet: "the council of elders",
      blurb: "An ascending chain of ever-older creatures, each measuring time by something vast worn away: the Blackbird of Cilgwri, the Stag of Rhedynfre, the Owl of Cwm Cawlwyd, the Eagle of Gwernabwy, and — oldest of all — the Salmon of Llyn Llyw, who carries the heroes on his shoulders to Mabon's prison.",
      appears: [9],
      rel: [{ to: "gwrhyr", label: "questioned by" }, { to: "mabon", label: "reveal" }] },
  ],
};
