// sync-zhouyi.mjs — regenerate clock/lib/zhouyi.js (the oracle's anchor copy of
// the Judgments) from read/iching/data.js, the canonical translation home.
// The two surfaces deploy from different dirs and can't share a served file, so
// the Judgment text is mirrored into the oracle here. Run after editing the
// translation:  node scripts/sync-zhouyi.mjs
import { ZHOUYI } from '../read/iching/data.js';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const hex = ZHOUYI.hexagrams;
const nums = Object.keys(hex).map(Number).sort((a, b) => a - b);

const entries = nums.map(n => {
  const j = hex[n].judgment;
  return `  ${n}: { z: ${JSON.stringify(j.z)}, py: ${JSON.stringify(j.py)},\n` +
         `      e: ${JSON.stringify(j.e)} },`;
}).join('\n');

const out =
`// AUTO-GENERATED by scripts/sync-zhouyi.mjs from read/iching/data.js — do not edit by hand.
// The oracle's anchor copy of our open Zhouyi translation (Judgments only). The two
// surfaces (g.mino.mobi, read.mino.mobi) deploy from different directories and can't
// share a served file, so the Judgment text is mirrored here for g.mino.mobi/yijing.
// read/iching/data.js is canonical; rerun \`node scripts/sync-zhouyi.mjs\` after edits.
export const ZHOUYI = {
${entries}
};
`;

writeFileSync(join(ROOT, 'clock/lib/zhouyi.js'), out);
console.log('wrote clock/lib/zhouyi.js — hexagrams:', nums.join(', '));
