/* Manawydan uab Llyr — a faithful retelling for readers ~8 and up, the whole
   Third Branch across paged spreads. Each spread carries an `illus` brief — an
   art note for the illustration pass; it is not shown to the reader.

   COMPLETE. A cover and sixteen spreads carrying the whole branch from the
   burial of Brân's head to the land made whole, at roughly three spreads per
   movement so every major beat has its own page — the same density as the
   early tales. The branch's eerie and comic beats kept side by side, handled
   with folktale tact. Attaches to window.MANAWYDAN. */
window.MANAWYDAN = window.MANAWYDAN || {};
window.MANAWYDAN.book = {
  meta: {
    kicker: "The Third Branch of the Mabinogi",
    note: "A faithful retelling for readers 8 and up — Manawydan son of Llŷr, page by page. The wasteland and the wit that lifts it, told with care across the whole branch. Illustrations follow via the pipeline.",
  },
  spreads: [
    { title: "Manawydan uab Llŷr",
      sub: "The Third Branch of the Mabinogi — a tale of a king who lost his land, a mist that emptied a kingdom, a fort that was never there, and a mouse on a tiny gallows who turned out to be far more than a mouse",
      text: "Long ago there was a man named Manawydan, who had the best right of anyone to be king of Britain — and never asked to be. When an enchantment swallowed his whole kingdom and stole away two of the people he loved most, he did not fight it with an army. He beat it with patience, a craftsman's hands, and a bargain he would not let go. This is his story.",
      illus: "Cover: Manawydan, a calm, kind, dignified middle-aged man with greying hair and beard, in a plain but noble deep-blue mantle, standing on a low green mound (the Gorsedd of Arberth) under a strange sky; in his cupped hands a small brown mouse, regarded gravely. Behind him, a misty empty landscape with a faint outline of a vanishing tower. Warm gouache-and-watercolour in the Howard Pyle / Edmund Dulac tradition; earthy Welsh palette — slate-greys, sea-greens, ambers, with quiet gold; a mythic, faintly wry grandeur; child-friendly." },

    { title: "The King Who Lost His Place",
      text: "When the great giant-king Brân the Blessed died, his seven companions carried his head home and buried it, and his brother Manawydan was left with nothing — for his cousin Caswallon now sat on the throne of Britain. Manawydan was too sad even to want it back. Then his good friend Pryderi, lord of Dyfed, said, \"Come with me. I will give you my own seven cantrefs, and my mother Rhiannon for your wife — she is the wisest and kindest woman you will ever meet.\"",
      illus: "Two men talking on a hill above the sea at dusk: Manawydan (calm, greying, deep-blue mantle), heavy with grief, and the younger bright warrior-prince Pryderi, who lays a kind hand on his shoulder and gestures away toward green hill-country (Dyfed). The mood is sorrow turning toward hope. Cold dusk-light warming to gold on the horizon; earthy Welsh palette; painterly, child-friendly." },

    { title: "A Wedding, and Four Friends",
      text: "So Manawydan went with Pryderi to Dyfed; and he and Rhiannon talked and talked, and grew to love each other, and were married. Pryderi's wife was a gentle young woman named Cigfa, and the four of them — Manawydan and Rhiannon, Pryderi and Cigfa — became such friends that they never wished to be apart, by day or by night. They feasted and hunted and roamed the rich, peaceful land, and were as happy as four people could be.",
      illus: "A warm welcome-feast in a Welsh hall at Arberth: Manawydan (calm, greying, deep-blue mantle) seated in close conversation with Rhiannon (a beautiful, wise-faced woman of middle years, dark hair, fine green-and-gold gown); across from them Pryderi (a bright, vigorous warrior-prince) and Cigfa (a gentle young woman). Candle-light, a harp in the corner, four friends glad in each other's company. Earthy Welsh palette with gold; painterly, child-friendly, full of warmth." },

    { title: "The Mist on the Mound",
      text: "One evening, after a feast, the four of them climbed the green mound called the Gorsedd of Arberth, where wonders were known to happen. As they sat there, a great clap of thunder rolled — and then a thick mist came down, so dense that none of them could see another. When it lifted, the world had changed. Every house was empty, every field bare; no cattle, no smoke from any hearth, no neighbour anywhere. All their people had simply vanished. In the whole kingdom there were only the four of them left.",
      illus: "Four small figures (Manawydan, Rhiannon, Pryderi, Cigfa) seated on a low green mound at dusk, ringed by a wall of thick silver-grey mist that is just beginning to part; beyond it, a wide empty landscape of abandoned, roofless houses, dark cold hearths, no people or animals anywhere. A faint after-glow of uncanny light. Eerie but not frightening; earthy Welsh palette, muted, with a cold mist-light; painterly, child-friendly, a held breath of wonder and loss." },

    { title: "Alone in an Empty Land",
      text: "For two whole years the four of them lived in the empty kingdom, and made the best of it — hunting the deer, catching fish, gathering wild honey from the woods. It was a quiet, free sort of life, and for a while it suited them. But at last they grew weary of being so alone in a land with no one else in it. \"We cannot go on like this,\" said Manawydan. \"Let us go into England, and earn our living by a craft.\"",
      illus: "The four (Manawydan, Rhiannon, Pryderi, Cigfa) living rough but content in the emptied wasteland: a small campfire, fish drying, a deer brought in from the hunt, the ruined empty houses of the land behind them under a wide sky. A self-sufficient woodland life touched with loneliness. Soft gold firelight against muted greys and greens; earthy Welsh palette; painterly, child-friendly." },

    { title: "Living by Their Hands",
      text: "So they went into England, to the town of Hereford, and took up making saddles. Manawydan made them so beautifully, gilded with a lovely blue enamel, that no one in the whole town would buy from any other saddler. When they had to move on, they made shields instead; and after that, shoes — and Manawydan grew so famous a shoemaker that he was called one of the three best in all Britain. Whatever craft he turned his hand to, his work was simply better than anyone else's.",
      illus: "A busy medieval English town workshop, warm with lamplight: Manawydan (calm, greying, sleeves rolled) at a cobbler's bench shaping a fine shoe with a gleaming gilded buckle, Pryderi beside him stitching, Rhiannon and Cigfa nearby. Fine leather, tools, gilt buckles catching the light. Warm workshop glow; earthy palette with gold; painterly, child-friendly." },

    { title: "Too Good to Be Borne",
      text: "But everywhere it was the same. The other craftsmen, losing all their trade to him, grew jealous and angry, and each time they plotted to kill the strangers. Proud Pryderi wanted to fight them; but wise Manawydan would not — \"We would get an evil name,\" he said, \"and besides, word would reach the high king, and we should be ruined.\" So each time he simply led the four of them quietly away to the next town. At last he had had enough of it. \"Let us go home to Dyfed,\" he said.",
      illus: "Through the open door of a workshop at dusk, a cluster of sullen, envious English townsfolk-craftsmen muttering together and glancing in with ill intent; inside, the calm Manawydan quietly gathering his tools while a hot-tempered Pryderi grips a tool like a weapon and Manawydan stays his hand. Tension and the wisdom of restraint. Cool exterior light, warm interior; earthy palette; painterly, child-friendly, menace without violence." },

    { title: "The White Boar",
      text: "Home in Dyfed, Pryderi and Manawydan went hunting one morning, and their dogs flushed a wild boar out of a thicket — a boar of a strange, shining, pure white. It would not run like ordinary prey. Instead it led them on and on across the empty country, always just out of reach, drawing the dogs and the men after it, as if it wanted to be followed.",
      illus: "On a misty Welsh hillside at dawn, a wild boar of an uncanny pure shining white standing at bay before a pack of hunting dogs, just ahead of two mounted hunters (the calm greying Manawydan and the bright Pryderi). The boar is beautiful and otherworldly, not monstrous, and clearly luring them onward. Cold dawn-light, silver mist; earthy palette with an eerie white glow; painterly, child-friendly." },

    { title: "The Fort That Was Never There",
      text: "The boar led them at last to a great, tall castle, standing where there had never before been so much as a single stone. The boar ran inside, and the dogs after it — and then there was no sound at all. \"I will go in and fetch my dogs,\" said Pryderi. \"Do not,\" warned Manawydan. \"We have never seen this fort before. Whoever laid the enchantment on this land has put it here.\" But Pryderi would not abandon his dogs, and in he went.",
      illus: "A great, lofty, too-perfect stone fort standing alone in an empty Welsh landscape where nothing was before — uncanny, new-built, charged with illusion. At its open gate, the bright Pryderi strides in despite the calm Manawydan, behind him, raising a hand in warning. Cold uncanny light around the fort, ordinary daylight behind the men; earthy palette with an eerie cast; painterly, child-friendly." },

    { title: "The Golden Bowl",
      text: "Inside, Pryderi found no dogs and no boar — only a beautiful golden bowl, hanging from chains that rose up into the air with no end that he could see. He was dazzled by it, and laid his hands on it — and at once his hands stuck fast to the bowl, his feet stuck to the floor, and he could not speak a word. When he did not come back, Rhiannon went in after her son, and the very same thing happened to her. Then thunder rolled, and mist fell, and the whole castle vanished — and Pryderi and Rhiannon with it.",
      illus: "Inside a strange, empty stone fort: the bright young Pryderi stands frozen, both hands fixed to a gleaming golden bowl that hangs from chains rising up into a misty void with no top; a marble fountain around its base. His face is caught mid-wonder, unable to move or speak. At the gateway behind, Rhiannon steps in, reaching toward him. Cool, uncanny half-light, a glow off the gold; earthy palette with a cold gleam; eerie but gentle — only enchantment, no harm; painterly, child-friendly." },

    { title: "Manawydan's Promise",
      text: "Now only Manawydan and Cigfa were left, and Cigfa was so frightened and grief-stricken that she hardly cared whether she lived or died. But Manawydan spoke gently to her. \"You have nothing to fear from me,\" he said. \"I give you my word before God: you will never find a truer friend than I will be to you, for as long as this misery lasts. I will keep faith with Pryderi, and with you, just as my own family always has.\" And Cigfa took heart, and trusted him.",
      illus: "Inside the empty hall at Arberth, the calm greying Manawydan speaking gently and reassuringly to the frightened, grief-stricken young Cigfa, who takes courage from his kindness; a quiet, tender, dignified moment of trust between two people left alone in an empty world. Warm hearth-light against the emptiness beyond the door; earthy palette with gold; painterly, child-friendly." },

    { title: "The Three Fields of Wheat",
      text: "Manawydan and Cigfa went to England once more, and back again — and this time Manawydan brought home a sack of wheat, for he had decided to become a farmer. He cleared three fields and sowed them, and the wheat grew finer than any in the world. But when the first field ripened and he came to reap it, he found only bare straw — every ear of wheat cut off and carried away in the night. And the next morning, the second field had been stripped the very same way.",
      illus: "A golden field of ripe wheat at the edge of an empty Welsh landscape at evening; Manawydan (greying, deep-blue mantle) stands looking grimly at a patch where the stalks stand stripped and bare, the ears all gone. Cigfa watches anxiously from near a small farmstead. Long amber harvest light, a sense of mystery and resolve; earthy palette with gold; painterly, child-friendly." },

    { title: "A Watch in the Night",
      text: "\"Whoever began my ruin,\" said Manawydan grimly, \"is finishing it.\" The third field was the finest of all, and ripe. \"I will watch it tonight,\" he said, \"and I will see who the thief is.\" So he took up his arms and sat down at the edge of the field as the dark came on, and waited, while Cigfa kept the fire at home.",
      illus: "Night falling over a fine field of ripe golden wheat; the lone figure of Manawydan (deep-blue mantle, a spear across his knees) seated and watchful at its edge under a rising moon, the empty land around him. A mood of patient, lonely resolve. Deep blue night, silver moonlight on the gold wheat; earthy palette; painterly, child-friendly." },

    { title: "The Host of Mice",
      text: "At midnight, Manawydan heard the greatest tumult in the world — and saw mice, a whole army of mice past counting, pouring into the field. Each one climbed a stalk, bit off the ear of wheat, and scurried away with it. He rushed at them in fury, but they were quicker than birds in the air — all but one, which was so heavy and slow that he was just able to catch it. He shut it carefully in his glove, tied the top with a string, and carried it home.",
      illus: "Moonlit wheat-field at midnight swarming with a vast host of small brown mice, each carrying an ear of wheat, streaming away in every direction; in the centre Manawydan (cloak flying, astonished and determined) has caught one plump mouse in his gloved hand and is drawing the string of his glove tight. Silvery moonlight, golden stubble, a swirl of motion; earthy palette with cool moonlight and gold; painterly, child-friendly, comic and uncanny at once." },

    { title: "The Mouse on the Gallows",
      text: "\"A thief,\" Manawydan told Cigfa, \"that I caught robbing me — and tomorrow I am going to hang it.\" Cigfa thought it foolish for a great man to bother hanging a mouse, but Manawydan had a feeling about this one. He carried it to the top of the Gorsedd and built a tiny gallows of two forked sticks. As he worked, a poor scholar came by and offered him money to set the mouse free; then a priest, offering more; then a grand bishop with a whole train of horses, offering a fortune. Each one he refused. \"But tell me,\" he said to the bishop at last, \"who is this mouse? — and we may yet make a bargain.\"",
      illus: "On the green mound at dusk, Manawydan kneels by a tiny gallows of two forked sticks and a crossbar, a small mouse held gently as he sets a thread-noose; before him a richly-vested bishop on horseback with a baggage-train and attendants pleads with him, purse in hand. The contrast of the grand bishop and the tiny gallows is gently absurd. Low golden evening light; earthy palette with gold and rich episcopal colours; painterly, child-friendly, wry and tense." },

    { title: "The Enchanter's Secret",
      text: "\"She is my wife,\" the bishop admitted at last — for he was no bishop at all, but a magician named Llwyd. Long ago, Manawydan's friends had played a cruel trick on a man called Gwawl; and to avenge that old wrong, Llwyd had enchanted all of Dyfed, emptied the land, taken Pryderi and Rhiannon, and sent his own people, turned into mice, to eat the wheat. The plump, slow little mouse on the gallows was his own wife. Now he begged for her life.",
      illus: "On the green mound, the false bishop transforming in appearance into his true self — Llwyd, a tall robed otherworldly magician with a slender wand — pleading earnestly with the calm, unmoved Manawydan, who still holds the small mouse by its thread. Behind Llwyd, his sumpter-horses and attendants (themselves part of the illusion). Charged, uncanny dusk-light; earthy palette with a cold magical gleam; painterly, child-friendly." },

    { title: "The Land Made Whole",
      text: "So Manawydan made his bargain, and held to every word of it: only when Pryderi and Rhiannon were freed, the enchantment lifted from the land for ever, and a solemn promise given that no one would ever take revenge again — only then did he let the little mouse go. Llwyd touched her with his wand, and she became the fairest of women once more. Manawydan looked around — and saw the whole kingdom alive again, full of houses and herds and people, exactly as it had been. And so the long enchantment ended, not with a battle, but with one patient man who would not be hurried.",
      illus: "On the mound, the magician Llwyd touches a small mouse with his wand and it transforms, in a swirl of light, back into a beautiful young woman; nearby a joyful Manawydan, the freed and relieved Rhiannon and Pryderi, and Cigfa stand together. Beyond them the once-empty landscape is restored and alive — green tilled fields, grazing cattle, smoking chimneys, houses and people. Warm golden light of restoration and reunion; earthy Welsh palette with radiant gold; painterly, child-friendly, a glad and peaceful ending." },
  ],
};
