/* Manawydan uab Llyr — the Third Branch of the Mabinogi. The English shown
   alongside the Welsh is an original translation, written movement by
   movement; Lady Charlotte Guest's public-domain version (1849) is consulted
   as a sense-check, not copied.

   The Welsh is the Welsh Wikisource reading text (CC BY-SA 4.0), the same
   edition that supplies Pwyll on this site — a normalised reading text of the
   White Book / Red Book tradition. It is the direct sequel to Branwen: the
   tale opens on the seven survivors burying Bendigeidfran's head at the White
   Hill, where the Second Branch left off.

   Both source texts are preserved verbatim under source/:
     manawydan-rhys-evans-1887-redbook.txt   (Middle Welsh reading text)
     manawydan-guest-1849-english.txt         (Guest's comparison translation)
   Attaches to window.MANAWYDAN. */
window.MANAWYDAN = window.MANAWYDAN || {};
window.MANAWYDAN.tale = {
  meta: {
    blurb: "<strong>Manawydan uab Llŷr</strong> — \"Manawydan son of Llŷr\" — the <em>Third Branch</em> of the Mabinogi, the direct sequel to <em>Branwen</em> and sister to <em>Pwyll</em> the First, preserved in the White Book of Rhydderch (c. 1350) and the Red Book of Hergest (c. 1382–1410). It opens where the tragedy ended: the <strong>seven survivors</strong> bury the head of <strong>Bendigeidfran</strong> at the White Hill in London, and <strong>Manawydan</strong> — the rightful king of Britain, dispossessed by his cousin <strong>Caswallon</strong> — is left a guest in his own island. His comrade <strong>Pryderi</strong> gives him the seven cantrefs of Dyfed and his widowed mother <strong>Rhiannon</strong> to wife; with Pryderi's own wife <strong>Cigfa</strong>, the four live in perfect friendship. Then, after a feast, a peal of thunder and a <strong>fall of mist</strong> on the Gorsedd of Arberth empties the land: no house, no beast, no smoke, no neighbour — a <strong>wasteland</strong>, and the four alone in it. Driven to England to live by their hands, they prosper at saddle-making, shield-making and shoe-making until jealous craftsmen drive them out of town after town. Home again, a shining <strong>white boar</strong> leads Pryderi's dogs into a vast <strong>caer</strong> that was never there; Pryderi follows against counsel, grips a <strong>golden bowl</strong>, and is held fast and struck dumb; Rhiannon goes after him and is taken too; thunder and mist swallow the fort, and they with it. Manawydan and Cigfa are left. Back at Arberth he sows three crofts of wheat — and a <strong>host of mice</strong> reaps them overnight. He catches one too heavy to flee, builds a tiny <strong>gallows</strong> on the Gorsedd to hang the thief, and refuses, in turn, a scholar, a priest and a <strong>bishop</strong> who come to buy its life — until the bishop confesses he is <strong>Llwyd son of Cil Coed</strong>, who laid the whole enchantment to avenge <strong>Gwawl son of Clud</strong> (the badger-in-the-bag humiliation from <em>Pwyll</em>), and that the mouse is his own <strong>pregnant wife</strong>. Manawydan holds the bargain to the last word — release of Pryderi and Rhiannon, the lifting of the spell, no future revenge — and the land is made whole. The only branch where <strong>wit, not war</strong>, wins. The translation below is <strong>original</strong> and proceeds <strong>movement by movement</strong>; the Welsh beside it is the Wikisource reading text. Full sources preserved at <a href=\"source/manawydan-rhys-evans-1887-redbook.txt\">source/manawydan-rhys-evans-1887-redbook.txt</a> and <a href=\"source/manawydan-guest-1849-english.txt\">source/manawydan-guest-1849-english.txt</a>.",
    sources: [
      { label: "Manawydan uab Llyr — Welsh Wikisource reading text (CC BY-SA 4.0; White Book / Red Book tradition)", url: "https://cy.wikisource.org/wiki/Manawydan_uab_Llyr", host: "Welsh Wikisource" },
      { label: "The Mabinogion — Lady Charlotte Guest, 1838–49 (public-domain English translation)", url: "https://www.gutenberg.org/ebooks/5160", host: "Project Gutenberg" },
      { label: "Manawydan fab Llŷr — overview", url: "https://en.wikipedia.org/wiki/Manawydan_fab_Ll%C5%B7r", host: "Wikipedia" },
      { label: "The Four Branches of the Mabinogi", url: "https://en.wikipedia.org/wiki/Four_Branches_of_the_Mabinogi", host: "Wikipedia" },
    ],
  },
  roadmap: [
    { t: "Source text in hand (Welsh Wikisource reading text + Guest 1849)", done: true },
    { t: "I · The burial of the head; Manawydan given Dyfed and Rhiannon", done: true },
    { t: "II · The feast, the thunder and the mist; the wasteland", done: true },
    { t: "III · England: saddles, shields and shoes; driven from town to town", done: true },
    { t: "IV · The white boar; the caer; Pryderi and Rhiannon taken", done: false },
    { t: "V · England again; the three crofts of wheat", done: false },
    { t: "VI · The mice; the gallows; Llwyd son of Cil Coed; the land made whole", done: false },
  ],
  passages: [
    {
      title: "I. The burial of the head, and Manawydan given Dyfed and Rhiannon",
      segments: [
        { w: "Guedy daruot y'r seithwyr a dywedyssam ni uchot gladu penn Bendigeiduran yn y Gwynuryn yn Llundein, a'y wyneb ar Freinc, edrych a wnaeth Manawydan ar y dref yn Llundein, ac ar y gedymdeithon, a dodi ucheneit uawr, a chymryt diruawr alar a hiraeth yndaw. \"Oy a Duw Hollgyuoethawc, guae ui,\" heb ef, \"nyt oes neb heb le idaw heno namyn mi.\"",
          e: "When the seven men we spoke of above had buried the head of Bendigeidfran at the White Hill in London, its face toward France, Manawydan looked out over the town of London, and at his companions, and heaved a great sigh; and a vast grief and longing came over him. \"Oh, God Almighty, woe is me,\" he said, \"there is no one without a place to call his own tonight, save me alone.\"",
          n: "The branch opens on the last act of <em>Branwen</em>: the <strong>seven survivors</strong> have just buried Brân the Blessed's still-living head at the <em>Gwynfryn</em> — the White Hill (traditionally Tower Hill, London), facing France as a talisman against invasion. <strong>Manawydan</strong>, son of Llŷr and brother of the dead giant-king, is the tale's centre — the Welsh reflex of the Irish sea-god Manannán, but here a quiet, patient, intensely practical man. His opening lament is one of dispossession: while the head was buried, his cousin <strong>Caswallon son of Beli</strong> had seized the crown of Britain (told in Branwen), and Manawydan — the rightful king — is left landless, a guest in his own island. The Third Branch is built on that grief, and on the long, ingenious patience with which he answers it." },

        { w: "\"Arglwyd,\" heb y Pryderi, \"na uit kyn drymhet genhyt a hynny. Dy geuynderw yssyd urenhin yn Ynys y Kedyrn; a chyn gwnel gameu it,\" heb ef, \"ny buost hawlwr tir a dayar eiryoet. Trydyd lledyf unben wyt.\" \"Ie,\" heb ef, \"kyt boet keuynderw y mi y gwr hwnnw, goathrist yw genhyf i guelet neb yn lle Bendigeiduran uy mrawt, ac ny allaf uot yn llawen yn un ty ac ef.\" \"A wney ditheu gynghor arall?\" heb y Pryderi. \"Reit oed im wrth gynghor,\" heb ef, \"a pha gynghor yw hwnnw?\"",
          e: "\"Lord,\" said Pryderi, \"do not take it so heavily as that. Your cousin is king over the Island of the Mighty; and though he has wronged you,\" he said, \"you were never a claimant of land or ground in your life. You are one of the three un-covetous chieftains.\" \"Yes,\" he said, \"but cousin to me though that man be, it grieves me to see anyone in the place of Bendigeidfran my brother, and I cannot be glad in the same house as he.\" \"Will you take other counsel, then?\" said Pryderi. \"I have need of counsel,\" he said, \"and what counsel is that?\"",
          n: "<strong>Pryderi son of Pwyll</strong> — lord of Dyfed, the child whose birth, loss and recovery closed the First Branch — was one of the seven who carried the head home, and he and Manawydan have become close. He names Manawydan one of the <em>tri lledf unben</em>, the \"three un-aspiring (or meek) chieftains\" of Britain: a man with the best claim to the throne who never pressed a claim to so much as a field. The Triads preserve this epithet; it is the moral key to his character — the dispossessed king who will not fight for what is his, and who will, in the end, win everything back by patience and a bargain rather than by the sword." },

        { w: "\"Seith cantref Dyuet yr edewit y mi,\" heb y Pryderi, \"a Riannon uy mam yssyd yno. Mi a rodaf it honno, a medyant y seith cantref genthi. A chyny bei itti o gyuoeth namyn y seith cantref hynny, nyt oes seith cantref well noc wy. Kicua uerch Wyn Gloyw yw uy gwreic inheu,\" heb ef. \"A chyn bo enwedigaeth y kyuoeth y mi, bit y mwynant y ti a Riannon. A phei mynhut gyuoeth eiryoet, atuyd y caffut ti hwnnw.\" \"Na uynhaf, unben,\" heb ef. \"Duw a dalo it dy gydymdeithas.\" \"E gedymdeithas oreu a allwyf i, yti y byd, os mynny.\" \"Mynnaf, eneit,\" heb ef. \"Duw a dalo it. A mi a af gyt a thi y edrych Riannon, ac y edrych y kyuoeth.\"",
          e: "\"The seven cantrefs of Dyfed were left to me,\" said Pryderi, \"and Rhiannon my mother is there. I will give her to you, and the lordship of the seven cantrefs with her. And though you had no domain but those seven cantrefs alone, there are no seven cantrefs better than they. Cigfa daughter of Gwyn Gloyw is my own wife,\" he said; \"and though the title to the land be mine, let the enjoyment of it be yours and Rhiannon's. And had you ever wanted a domain, perhaps you would have had this one.\" \"I do not want it, chieftain,\" he said. \"God reward you for your friendship.\" \"The best friendship I can give shall be yours, if you will have it.\" \"I will, dear soul,\" he said. \"God reward you. And I will go with you to see Rhiannon, and to see the land.\"",
          n: "Pryderi's gift is the engine of the plot. He offers Manawydan both a kingdom — the <strong>seven cantrefs of Dyfed</strong> — and his widowed mother <strong>Rhiannon</strong>, the otherworldly, quick-witted queen of the First Branch (Pwyll's wife, won at the mound of Arberth). The arrangement is unusually generous and frank: Pryderi keeps the legal title but hands over the use of the realm and his mother's hand, asking nothing back but Manawydan's company. It also introduces <strong>Cigfa daughter of Gwyn Gloyw</strong>, Pryderi's wife — who, with the other three, will be one of the four people left alive in the enchanted land. The marriage of the landless king to the realm's dowager queen is exactly the dynastic logic of the Branches: realms are joined through women, and Manawydan steps into the place Pwyll once held." },

        { w: "\"Iawn a wney,\" heb ynteu. \"Mi a debygaf na werendeweist eiryoet ar ymdidanwreic well no hi. Yr amser y bu hitheu yn y dewred, ny bu wreic delediwach no hi; ac etwa ny bydy anuodlawn y phryt.\" Wynt a gerdassant racdunt. A pha hyt bynnac y bydynt ar y ford, wynt a doethant y Dyuet. Gwled darparedic oed udunt erbyn eu dyuot yn Arberth, a Riannon a Chicua wedy y harlwyaw.",
          e: "\"You do well,\" he said. \"I think you never listened to a better woman in conversation than she. In the time she was in her prime, there was no fairer woman than she; and even now you will not be displeased with her looks.\" They went on their way; and however long they were on the road, they came to Dyfed. A feast was made ready for them against their coming to Arberth — Rhiannon and Cigfa had prepared it.",
          n: "Pryderi praises his mother first for her <em>conversation</em> — <em>ymddiddan</em>, the art of talk — and only then for her looks: Rhiannon is the corpus's great talker, the woman who out-argues Pwyll at the mound and out-faces a false murder-charge in the First Branch. <strong>Arberth</strong> (Narberth) is the chief court of Dyfed and the hinge of both branches — Pwyll's seat, and the site of the <em>Gorsedd</em>, the magical mound, where the mist will shortly fall. That the two women have the welcome-feast already laid sets the warm, domestic key the enchantment will so brutally break." },

        { w: "Ac yna dechreu kydeisted ac ymdidan o Uanawydan a Riannon; ac o'r ymdidan tirioni a wnaeth y uryt a'y uedwl wrthi, a hoffi yn y uedwl na welsei eiryoet wreic digonach y theket a'y thelediwet no hi. \"Pryderi,\" heb ef, \"mi a uydaf wrth a dywedeist ti.\" \"Pa dywedwydat oed hwnnw?\" heb y Riannon. \"Arglwydes,\" heb y Pryderi, \"mi a'th roessum yn wreic y Uanawydan uab Llyr.\" \"A minheu a uydaf wrth hynny yn llawen,\" heb y Riannon. \"Llawen yw genhyf inheu,\" heb y Manawydan, \"a Duw a dalo y'r gwr yssyd yn rodi i minheu y gedymdeithas mor difleis a hynny.\" Kyn daruot y wled honno, y kyscwyt genti.",
          e: "And then Manawydan and Rhiannon began to sit together and to talk; and from the talking his heart and his mind grew tender toward her, and he was glad in his mind that he had never seen a woman more complete in beauty and grace than she. \"Pryderi,\" he said, \"I will abide by what you said.\" \"And what saying was that?\" said Rhiannon. \"Lady,\" said Pryderi, \"I gave you as wife to Manawydan son of Llŷr.\" \"And I will gladly abide by that,\" said Rhiannon. \"Glad am I too,\" said Manawydan, \"and God reward the man who gives me a friendship as flawless as this.\" Before that feast was over, he had slept with her.",
          n: "The courtship is over in a paragraph, and it is a courtship of <em>talk</em>: Manawydan falls for Rhiannon across the table, in conversation, exactly as Pryderi promised. Rhiannon — a queen who in the First Branch chose her own husband against her family's plans — assents to this match as freely. The understatement of the close (<em>kyn daruot y wled honno, y kyscwyt genti</em>, \"before that feast was over, he had slept with her\") is the Branches' characteristic decorum: the marriage is made, consummated, and the narrative moves on without a wasted word." },

        { w: "\"Ar ny deryw o'r wled,\" heb y Pryderi, \"treulwch chwi, a minheu a af y hebrwng uy gwrogaeth y Gaswallawn uab Beli hyt yn Lloegyr.\" \"Arglwyd,\" heb y Riannon, \"yg Kent y mae Caswallawn, a thi a elly treulaw y wled honn a'y arhos a uo nes.\" \"Ninheu a'y arhown,\" heb ef. A'r wled honno a dreulyssant, a dechreu a wnaethant kylchaw Dyuet, a'y hela, a chymryt eu digriuwch.",
          e: "\"What is left of the feast,\" said Pryderi, \"spend it together, and I will go to render my homage to Caswallon son of Beli, into England.\" \"Lord,\" said Rhiannon, \"Caswallon is in Kent, and you may spend this feast and wait until he is nearer.\" \"We will wait for him,\" he said. So they spent that feast, and began to make the circuit of Dyfed, and to hunt it, and to take their pleasure.",
          n: "<strong>Caswallon son of Beli</strong> — the historical Cassivellaunus, the British king who fought Julius Caesar, here folded into the Mabinogi's mythic time — holds the crown Manawydan will not contest. Pryderi must do <em>gwrogaeth</em>, homage, for Dyfed to the new high king, the realpolitik that places the warm little kingdom of four inside a larger, indifferent Britain. The detail that homage is owed even here quietly underlines Manawydan's choice: the rightful king sits at a country feast while his cousin holds court in Kent, and he is content." },

        { w: "Ac wrth rodyaw y wlat ny welsynt eiryoet wlat gyuanhedach no hi, na heldir well, nac amlach y mel na'y physcawt no hi. Ac yn hynny tyuu kedymdeithas y rydunt yll pedwar, hyt na mynnei yr un uot heb y gilid na dyd na nos. Ac ymysc hynny, ef a aeth at Caswallawn hyt yn Rytychen, y hebrwng y wrogaeth idaw. A diruawr lewenyd a uu yn y erbyn yno, a diolwch idaw hebrwng y wrogaeth idaw. A guedy ymchwelut, kymryt eu gwledeu ac eu hesmwythder a orugant Pryderi a Manawydan.",
          e: "And in roaming the country they had never seen a land more settled and rich, nor better hunting-ground, nor one of more abundant honey and fish, than it. And in all this a friendship grew up among the four of them, such that not one of them wished to be without the others, by day or by night. And in the midst of it, he went to Caswallon at Oxford to render his homage; and there was great rejoicing to meet him there, and thanks to him for rendering his homage. And after returning, Pryderi and Manawydan took their feasting and their ease.",
          n: "The movement closes on the idyll the rest of the branch exists to shatter: four people in a rich, peaceful, well-stocked land, in a friendship so close that <em>not one of them wished to be without the others, day or night</em>. It is the most contented picture in the Four Branches — and the narrative sets it up precisely so that the mist, when it comes, will fall on the fullest possible happiness. (Manawydan renders the homage Pryderi owed, at <strong>Rhydychen</strong>, Oxford; the small administrative loose-end tied off, the tale turns to the feast at Arberth and the Gorsedd.)" },
      ],
    },

    {
      title: "II. The feast, the thunder and the mist, and the wasteland",
      segments: [
        { w: "A dechreu gwled a orugant yn Arberth, kanys prif lys oed, ac o honei y dechreuit pob anryded. A guedy y bwyta kyntaf y nos honno, tra uei y gwassanaethwyr yn bwyta, kyuodi allan a orugant, a chyrchu Gorssed Arberth a wnaethant yll pedwar, ac yniuer gyt ac wynt.",
          e: "And they began a feast at Arberth, for it was the chief court, and from it every honour took its beginning. And after the first sitting of meat that night, while the servants were still at their food, the four of them rose and went out, and made for the Gorsedd of Arberth — they and their retinue with them.",
          n: "The <strong>Gorsedd of Arberth</strong> is the most charged place in the Four Branches. Its property was set out in <em>Pwyll</em>: whoever sits on this mound will not leave it without either receiving blows and wounds, or seeing a wonder. It was here that Pwyll first saw Rhiannon ride past on her white horse, no faster than a walk yet never overtaken. The four climb it after dinner exactly as one climbs a place where marvels are known to happen — and a marvel is what they get. The mound is a threshold to the Otherworld, and sitting on it has, in effect, opened a door." },

        { w: "Ac ual y bydant yn eisted yuelly, llyma dwryf, a chan ueint y twryf, llyma gawat o nywl yn dyuot, hyt na chanhoed yr un o honunt welet y gilyd. Ac yn ol y nywl, llyma yn goleuhau pob lle. A phan edrychyssant y ford y guelynt y preideu a'r anreitheu a'r kyuanhed kyn no hynny, ny welynt neb ryw dim, na thy, nac aniueil, na mwc, na than, na dyn, na chyuanhed, eithyr tei y llys yn wac, diffeith, anghyuanhed, heb dyn, heb uil yndunt, eu kedymdeithon e hun wedy eu colli, heb wybot dim y wrthunt, onyt wynt yll pedwar.",
          e: "And as they sat thus, behold a peal of thunder; and with the greatness of the thunder, behold a fall of mist came down, so that not one of them could see another. And after the mist, behold, everywhere grew light again. And when they looked toward where, before this, they had seen the flocks and the herds and the dwellings, they saw nothing at all — no house, no beast, no smoke, no fire, no man, no settlement — only the court's own buildings standing empty, ruined, abandoned, with neither man nor beast in them; their own people lost, with no knowing of what had become of them — only the four of them left.",
          n: "This is the great hinge of the branch and one of the most haunting images in medieval Welsh: <strong>thunder, a fall of mist, and a world wiped clean</strong>. The enchantment (<em>hud</em>) does not kill or carry off — it <em>unmakes the inhabited world</em>, leaving the four survivors standing in a depopulated land of empty halls. This is the Insular cousin of the <strong>Grail Wasteland</strong>, the <em>terre gaste</em> of the Continental romances: a kingdom sunk into desolation by an act of enchantment, waiting for the right person and the right act to lift it. The rhythm of the negation — <em>no house, no beast, no smoke, no fire, no man</em> — is the prose tradition at its most incantatory." },

        { w: "\"Oy a Arglwyd Duw,\" heb y Manawydan, \"mae yniuer y llys, ac yn anniuer ninheu namyn hynn? Awn y edrych.\" Dyuot y'r neuad a wnaethant; nyt oed neb. Kyrchu yr ystauell a'r hundy; ny welynt neb. Yn y uedgell, nac yg kegin, nyt oed namyn diffeithwch.",
          e: "\"Oh, Lord God,\" said Manawydan, \"where is the household of the court — and where are we, with none beside us but this? Let us go and look.\" They came into the hall: there was no one. They made for the chamber and the sleeping-quarters: they saw no one. In the mead-cellar, and in the kitchen, there was nothing but desolation.",
          n: "Manawydan's response is, characteristically, not lament but inventory — <em>Awn y edrych</em>, \"let us go and look\". Where Brân in the Second Branch answered catastrophe with a war-host, Manawydan answers it by methodically checking the rooms. The search through hall, chamber, sleeping-quarters, mead-cellar and kitchen — the working anatomy of a Welsh court — finds each one empty. The practical, room-by-room cast of his mind is the quality that will, by the end, lift the whole spell." },

        { w: "Dechreu a wnaethant yll pedwar treulaw y wled, a hela a wnaethant, a chymryt eu digriuwch; a dechreu a wnaeth pob un o honunt rodyaw y wlat a'r kyuoeth, y edrych a welynt ae ty ae kyuanhed; a neb ryw dim ny welynt eithyr guydlwdyn. A guedy treulaw eu gwled ac eu darmerth o honunt, dechreu a wnaethant ymborth ar gic hela, a physcawt, a bydaueu. Ac yuelly blwydyn, a'r eil, a dreulyssant yn digrif gantunt. Ac yn y diwed, dygyaw a wnaethant.",
          e: "The four of them began to use up the feast, and they hunted, and took their pleasure; and each of them began to roam the country and the realm to see whether they could find a house or a settlement — and they saw nothing at all but wild thickets. And when they had used up their feast and their provisions, they began to live on the meat of the hunt, and on fish, and on wild swarms of honey. And so they passed a year, and a second, contentedly. And at the last, they grew weary of it.",
          n: "The wasteland is not, at first, a horror to be fled but a life to be lived — and the four live it well: two years of hunting, fishing and wild honey, told as <em>digrif</em>, \"pleasant\". It is the same self-sufficient woodland survival that Orfeo keeps in the wilderness, and the same patient adaptation that marks Manawydan throughout. The single word that ends the idyll — <em>dygyaw</em>, \"they grew weary, palled of it\" — is what drives them out of the empty country and into England to live by their hands, the subject of the next movement. The enchantment has emptied the land; boredom, not hunger, is what finally moves them." },
      ],
    },

    {
      title: "III. England, and the three crafts: saddles, shields and shoes",
      segments: [
        { w: "\"Dioer,\" heb y Manawydan, \"ny bydwn ual hynn. Kyrchwn Loegyr, a cheisswn greft y kaffom yn ymborth.\" Kyrchu Lloegyr a orugant, a dyuot hyt yn Henford, a chymryt arnunt gwneuthur kyfrwyeu. A dechreu a wnaeth ef, Manawydan, llunyaw coryfeu, ac eu lliwaw ar y wed y guelsei gan Lassar Llaes Gygnwyt a chalch llassar, a gwneuthur calch lassar racdaw, ual y gwnathoed y gwr arall. Ac wrth hynny y gelwir etwa Calch Llassar, am y wneuthur o Lassar Llaes Gygnwyt.",
          e: "\"By God,\" said Manawydan, \"we will not go on like this. Let us make for England, and seek a craft to keep ourselves by.\" They made for England, and came as far as Hereford, and took up the making of saddles. And Manawydan began to shape saddle-bows, and to colour them in the way he had seen done by Llasar Llaes Gyfnewid, with blue enamel; and he made the blue enamel for himself, just as that other man had made it. And for that reason it is still called Calch Lassar — \"Llasar's enamel\" — because Llasar Llaes Gyfnewid first made it.",
          n: "The dispossessed king turns artisan — and the craft he turns to comes <strong>straight out of Branwen</strong>. <em>Llasar Llaes Gyfnewid</em> (here spelled <em>Gygnwyt</em>) is the great yellow-red man who rose from the Lake of the Cauldron, escaped the Iron House in Ireland, and brought the <strong>Cauldron of Rebirth</strong> to Britain — the very gift that wrecked the Second Branch. Manawydan, his brother's companion, learned Llasar's secret of <em>calch lassar</em>, blue enamel, and now uses it to gild saddle-bows in Hereford. It is a quiet, brilliant piece of inter-branch weaving: the same hands, the same world, the catastrophe of one branch becoming a craftsman's trade-secret in the next. The line also gives the branch's first onomastic — the enamel \"still called\" by the giant's name." },

        { w: "Ac o'r gueith hwnnw, tra geffit gan Uanawydan, ny phrynit gan gyfrwyd dros wyneb Henford na choryf na chyfrwy, yny adnabu pob un o'r kyfrwydyon y uot yn colli o'y enill, ac na phrynit dim ganthunt onyt guedy na cheffit gan Uanawydan. Ac yna ymgynullaw y gyt o honunt, a duunaw ar y lad ef a'y gedymdeithon. Ac yn hynny rybud a gawssant wynteu, a chymryt kynghor am adaw y dref. \"E rof i a Duw,\" heb y Pryderi, \"ny chynghoraf i adaw y dref, namyn llad y tayogeu raccw.\" \"Nac ef,\" heb y Manawydan, \"pei ymladem ni ac wyntwy, clot drwc uydei arnam, ac yn carcharu a wneit. Ys guell in,\" heb ef, \"kyrchu tref arall y ymossymdeithaw yndi.\"",
          e: "And of that work, so long as it could be had from Manawydan, no man across the face of Hereford would buy saddle-bow or saddle from any other saddler, until every one of them came to see that he was losing his livelihood — that nothing was bought from them save what could not be had from Manawydan. Then they gathered together and agreed to kill him and his companions. But these had warning of it, and took counsel about leaving the town. \"Between me and God,\" said Pryderi, \"my counsel is not to leave the town, but to kill those churls yonder.\" \"No,\" said Manawydan; \"if we fought them, we should get an ill name, and be thrown in prison. Better for us to make for another town, to keep ourselves there.\"",
          n: "Here is the engine of the whole England episode, and it runs three times in a row: the four are too good at the craft, the local guild loses its trade, the guild resolves to murder them, they get word, and Manawydan moves them on. The contrast between the two men is the moral spine — <strong>Pryderi</strong>, the warrior, wants to kill the <em>taeogion</em> (\"churls, bondmen\"); <strong>Manawydan</strong>, the strategist, refuses, and his reason is political: a fight would bring <em>clot drwc</em>, ill fame, and prison — and (as he says next time) word would reach the high king Caswallon, and the dispossessed have no protector. It is the patience of a man who has already lost everything and will not lose his honour too." },

        { w: "Ac yna kyrchu dinas arall a wnaethant yll pedwar. \"Pa geluydyt,\" heb y Pryderi, \"a gymerwn ni arnam?\" \"Gwnawn taryaneu,\" heb y Manawydan. \"A wdom ninheu dim y wrth hynny?\" heb y Pryderi. \"Ni a'y prouwn,\" heb ynteu. Dechreu gwneuthur gueith y taryaneu, eu llunyaw ar weith taryaneu da a welsynt, a dodi y lliw a dodyssynt ar y kyfrwyeu arnunt. A'r gweith hwnnw a lwydwys racdunt, hyt na phrynit taryan yn yr holl dref onyt guedy na cheffit ganthunt wy.",
          e: "And so the four of them made for another town. \"What craft,\" said Pryderi, \"shall we take up?\" \"Let us make shields,\" said Manawydan. \"Do we know anything about that?\" said Pryderi. \"We will try,\" he said. They set to making shields, shaping them after good shields they had seen, and putting on them the same colour they had put on the saddles. And that work prospered for them, so that no shield was bought in the whole town save what could be had from them.",
          n: "The second craft, the same pattern. Manawydan's serene \"we will try\" (<em>ni a'y prouwn</em>) at a trade neither of them knows — and then their immediate mastery of it — quietly marks these as no ordinary craftsmen. The motif of the <strong>noble who excels at any humble craft he touches</strong> runs through the episode; their hands have a more-than-human deftness, and the blue enamel of the saddles reappears on the shields, the signature of a workshop the locals cannot match." },

        { w: "Kyflym oed eu gueith wynteu, a diuessur a wneynt; ac yuelly y buant yny dygywys eu kytdrefwyr racdunt, ac yny duunyssant ar geissaw eu llad. Rybud a doeth udunt wynteu, a chlybot bot y gwyr a'e bryt ar eu dienydyaw. \"Pryderi,\" heb y Manawydan, \"y mae y gwyr hynn yn mynnu yn diuetha.\" \"Ny chymerwn ninheu y gan y tayogeu hynny. Awn adanunt, a lladwn wynt.\" \"Nac ef,\" heb ynteu, \"Caswallawn a glywei hynny, a'e wyr, a rewin uydem. Kyrchwn tref arall.\" Wynt a doethant y dref arall.",
          e: "Swift was their work, and they made shields beyond counting; and so it went until their fellow-townsmen marked them down and agreed to seek to kill them. But word came to them, and they heard that the men were bent on doing them to death. \"Pryderi,\" said Manawydan, \"these men mean to destroy us.\" \"We will not take that from those churls. Let us go at them, and kill them.\" \"No,\" he said; \"Caswallon would hear of it, and his men, and we should be ruined. Let us make for another town.\" And they went to another town.",
          n: "The second flight, and now Manawydan names the real constraint: <strong>Caswallon</strong> — the cousin who holds the crown Manawydan will not claim. The dispossessed king cannot afford a killing in an English town, because the high king would hear, and four landless people with no lord behind them would be <em>rewin</em>, undone. The whole England sequence is a study in what it costs to have given up power: Manawydan must out-think every quarrel he could once have ended with a sword, because the sword is no longer his to draw." },

        { w: "\"Pa geluydyt yd awn ni wrthi?\" heb y Manawydan. \"Yr honn y mynnych, o'r a wdam,\" heb y Pryderi. \"Nac ef,\" heb ynteu, \"gwnawn grydyaeth. Ny byd o galon gan grydyon nac ymlad a ni nac ymwarauun.\" \"Ny wnn i dim y wrth honno,\" heb y Pryderi. \"Mi a'y gwn,\" heb y Manawydan, \"a mi a dyscaf it wniaw; ac nyt ymyrrwn ar gyweiraw lledyr, namyn y brynu yn barawt, a gwneuthur yn gueith o honaw.\" Ac yna dechreu prynu y cordwal teccaf a gauas yn y dref, ac amgen ledyr no hwnnw ny phrynei ef eithyr lledyr guadneu. A dechreu a wnaeth ymgedymdeithassu a'r eurych goreu yn y dref, a pheri guaegeu y'r eskidyeu, ac euraw y guaegeu, a synnyaw e hun ar hynny yny gwybu. Ac o'r achaws hwnnw y gelwit ef yn tryded eurgryd.",
          e: "\"What craft shall we turn to?\" said Manawydan. \"Whichever you like, of those we know,\" said Pryderi. \"No,\" he said; \"let us make shoes. Cordwainers will have no heart either to fight us or to hinder us.\" \"I know nothing of that,\" said Pryderi. \"I do,\" said Manawydan, \"and I will teach you to stitch. We will not trouble with dressing leather — we will buy it ready, and make our work from it.\" And he began to buy the finest cordovan he could get in the town, and would buy no other leather than that, except sole-leather; and he struck up a friendship with the best goldsmith in the town, and had buckles made for the shoes, and the buckles gilded, and he watched it himself until he had learned it. And for that reason he was called one of the Three Gold-shoemakers.",
          n: "The third craft is chosen with the same cool calculation: shoemakers, Manawydan reckons, are too peaceable to fight back. He buys the best <em>cordwal</em> (cordovan, the fine Spanish goatskin that gives English \"cordwainer\" its name), partners with a goldsmith for gilded buckles, and learns even that by watching — earning the Triadic title <strong>one of the Three Gold-shoemakers</strong> (<em>tri eurgryd</em>) of the Island of Britain. The detail that Manawydan <em>shaped</em> the work and Pryderi <em>stitched</em> it (named in the next breath) is the branch in miniature: the king who plans, the warrior who is taught to sew." },

        { w: "Tra geffit gantaw ef, nac eskit na hossan ny phrynit dim gan gryd yn yr holl dref. Sef a wnaeth y crydyon, adnabot bot eu hennill yn pallu udunt, kanys ual y llunyei Uanawydan y gueith, y gwniei Pryderi. Dyuot y crydyon a chymryt kynghor; sef a gausant yn eu kynghor, duunaw ar eu llad. \"Pryderi,\" heb y Manawydan, \"y mae y guyr yn mynnu an llad.\" \"Pa ham y kymerwn ninheu hynny gan y tayogeu lladron,\" heb y Pryderi, \"namyn eu llad oll?\" \"Nac ef,\" heb y Manawydan, \"nyt ymladwn ac wynt, ac ny bydwn yn Lloegyr bellach. Kyrchwn parth a Dyuet, ac awn y hedrych.\" Byhyt bynnac y buant ar y fford, wynt a doethant y Dyuet, ac Arberth a gyrchyssant. A llad tan a wnaethant, a dechreu ymborth a hela, a threulaw mis yuelly, a chynnull eu cwn attunt, a bot yuelly yno ulwydyn.",
          e: "So long as work could be had from him, neither shoe nor hose was bought from any cordwainer in the whole town. The cordwainers, seeing their livelihood failing them — for as Manawydan shaped the work, Pryderi stitched it — came together and took counsel, and what they resolved was to agree to kill them. \"Pryderi,\" said Manawydan, \"these men mean to kill us.\" \"Why should we take that from thieving churls,\" said Pryderi, \"rather than kill them all?\" \"No,\" said Manawydan; \"we will not fight them, and we will be in England no longer. Let us make for Dyfed, and go to see it.\" However long they were on the road, they came to Dyfed, and made for Arberth. They kindled a fire and began to keep themselves by hunting; and so they spent a month, and gathered their dogs to them, and so were there a year.",
          n: "The third flight ends the English exile: three crafts mastered, three guilds out-earned, three murder-plots out-waited, and Pryderi's patience worn as thin as the joke is now broad. Manawydan's decision is final — <em>we will be in England no longer</em> — and they go home to the empty land, to Arberth and the hearth-fire, to hunting and their dogs. The closing note that they <em>gathered their dogs and were there a year</em> is the quiet set-up for the next movement: a year of hunting in a depopulated country, until one morning the dogs start a shining white boar that was never meant for them to catch." },
      ],
    },
  ],
};
