/* Manawydan uab Llyr — the Third Branch of the Mabinogi. The English shown
   alongside the Welsh is an original translation, written movement by
   movement; Lady Charlotte Guest's public-domain version (1849) is consulted
   as a sense-check, not copied.

   The Welsh is the Welsh Wikisource reading text (CC BY-SA 4.0), the same
   edition that supplies Pwyll on this site — a normalised reading text of the
   White Book / Red Book tradition. It is the direct sequel to Branwen: the
   tale opens on the seven survivors burying Bendigeidfran's head at the White
   Hill, where the Second Branch left off.

   Both source texts are preserved verbatim under source/:
     manawydan-rhys-evans-1887-redbook.txt   (Middle Welsh reading text)
     manawydan-guest-1849-english.txt         (Guest's comparison translation)
   Attaches to window.MANAWYDAN. */
window.MANAWYDAN = window.MANAWYDAN || {};
window.MANAWYDAN.tale = {
  meta: {
    blurb: "<strong>Manawydan uab Llŷr</strong> — \"Manawydan son of Llŷr\" — the <em>Third Branch</em> of the Mabinogi, the direct sequel to <em>Branwen</em> and sister to <em>Pwyll</em> the First, preserved in the White Book of Rhydderch (c. 1350) and the Red Book of Hergest (c. 1382–1410). It opens where the tragedy ended: the <strong>seven survivors</strong> bury the head of <strong>Bendigeidfran</strong> at the White Hill in London, and <strong>Manawydan</strong> — the rightful king of Britain, dispossessed by his cousin <strong>Caswallon</strong> — is left a guest in his own island. His comrade <strong>Pryderi</strong> gives him the seven cantrefs of Dyfed and his widowed mother <strong>Rhiannon</strong> to wife; with Pryderi's own wife <strong>Cigfa</strong>, the four live in perfect friendship. Then, after a feast, a peal of thunder and a <strong>fall of mist</strong> on the Gorsedd of Arberth empties the land: no house, no beast, no smoke, no neighbour — a <strong>wasteland</strong>, and the four alone in it. Driven to England to live by their hands, they prosper at saddle-making, shield-making and shoe-making until jealous craftsmen drive them out of town after town. Home again, a shining <strong>white boar</strong> leads Pryderi's dogs into a vast <strong>caer</strong> that was never there; Pryderi follows against counsel, grips a <strong>golden bowl</strong>, and is held fast and struck dumb; Rhiannon goes after him and is taken too; thunder and mist swallow the fort, and they with it. Manawydan and Cigfa are left. Back at Arberth he sows three crofts of wheat — and a <strong>host of mice</strong> reaps them overnight. He catches one too heavy to flee, builds a tiny <strong>gallows</strong> on the Gorsedd to hang the thief, and refuses, in turn, a scholar, a priest and a <strong>bishop</strong> who come to buy its life — until the bishop confesses he is <strong>Llwyd son of Cil Coed</strong>, who laid the whole enchantment to avenge <strong>Gwawl son of Clud</strong> (the badger-in-the-bag humiliation from <em>Pwyll</em>), and that the mouse is his own <strong>pregnant wife</strong>. Manawydan holds the bargain to the last word — release of Pryderi and Rhiannon, the lifting of the spell, no future revenge — and the land is made whole. The only branch where <strong>wit, not war</strong>, wins. The translation below is <strong>original</strong> and proceeds <strong>movement by movement</strong>; the Welsh beside it is the Wikisource reading text. Full sources preserved at <a href=\"source/manawydan-rhys-evans-1887-redbook.txt\">source/manawydan-rhys-evans-1887-redbook.txt</a> and <a href=\"source/manawydan-guest-1849-english.txt\">source/manawydan-guest-1849-english.txt</a>.",
    sources: [
      { label: "Manawydan uab Llyr — Welsh Wikisource reading text (CC BY-SA 4.0; White Book / Red Book tradition)", url: "https://cy.wikisource.org/wiki/Manawydan_uab_Llyr", host: "Welsh Wikisource" },
      { label: "The Mabinogion — Lady Charlotte Guest, 1838–49 (public-domain English translation)", url: "https://www.gutenberg.org/ebooks/5160", host: "Project Gutenberg" },
      { label: "Manawydan fab Llŷr — overview", url: "https://en.wikipedia.org/wiki/Manawydan_fab_Ll%C5%B7r", host: "Wikipedia" },
      { label: "The Four Branches of the Mabinogi", url: "https://en.wikipedia.org/wiki/Four_Branches_of_the_Mabinogi", host: "Wikipedia" },
    ],
  },
  roadmap: [
    { t: "Source text in hand (Welsh Wikisource reading text + Guest 1849)", done: true },
    { t: "I · The burial of the head; Manawydan given Dyfed and Rhiannon", done: true },
    { t: "II · The feast, the thunder and the mist; the wasteland", done: true },
    { t: "III · England: saddles, shields and shoes; driven from town to town", done: true },
    { t: "IV · The white boar; the caer; Pryderi and Rhiannon taken", done: true },
    { t: "V · England again; the three crofts of wheat", done: true },
    { t: "VI · The mice; the gallows; Llwyd son of Cil Coed; the land made whole", done: true },
  ],
  passages: [
    {
      title: "I. The burial of the head, and Manawydan given Dyfed and Rhiannon",
      segments: [
        { w: "Guedy daruot y'r seithwyr a dywedyssam ni uchot gladu penn Bendigeiduran yn y Gwynuryn yn Llundein, a'y wyneb ar Freinc, edrych a wnaeth Manawydan ar y dref yn Llundein, ac ar y gedymdeithon, a dodi ucheneit uawr, a chymryt diruawr alar a hiraeth yndaw. \"Oy a Duw Hollgyuoethawc, guae ui,\" heb ef, \"nyt oes neb heb le idaw heno namyn mi.\"",
          e: "When the seven men we spoke of above had buried the head of Bendigeidfran at the White Hill in London, its face toward France, Manawydan looked out over the town of London, and at his companions, and heaved a great sigh; and a vast grief and longing came over him. \"Oh, God Almighty, woe is me,\" he said, \"there is no one without a place to call his own tonight, save me alone.\"",
          n: "The branch opens on the last act of <em>Branwen</em>: the <strong>seven survivors</strong> have just buried Brân the Blessed's still-living head at the <em>Gwynfryn</em> — the White Hill (traditionally Tower Hill, London), facing France as a talisman against invasion. <strong>Manawydan</strong>, son of Llŷr and brother of the dead giant-king, is the tale's centre — the Welsh reflex of the Irish sea-god Manannán, but here a quiet, patient, intensely practical man. His opening lament is one of dispossession: while the head was buried, his cousin <strong>Caswallon son of Beli</strong> had seized the crown of Britain (told in Branwen), and Manawydan — the rightful king — is left landless, a guest in his own island. The Third Branch is built on that grief, and on the long, ingenious patience with which he answers it." },

        { w: "\"Arglwyd,\" heb y Pryderi, \"na uit kyn drymhet genhyt a hynny. Dy geuynderw yssyd urenhin yn Ynys y Kedyrn; a chyn gwnel gameu it,\" heb ef, \"ny buost hawlwr tir a dayar eiryoet. Trydyd lledyf unben wyt.\" \"Ie,\" heb ef, \"kyt boet keuynderw y mi y gwr hwnnw, goathrist yw genhyf i guelet neb yn lle Bendigeiduran uy mrawt, ac ny allaf uot yn llawen yn un ty ac ef.\" \"A wney ditheu gynghor arall?\" heb y Pryderi. \"Reit oed im wrth gynghor,\" heb ef, \"a pha gynghor yw hwnnw?\"",
          e: "\"Lord,\" said Pryderi, \"do not take it so heavily as that. Your cousin is king over the Island of the Mighty; and though he has wronged you,\" he said, \"you were never a claimant of land or ground in your life. You are one of the three un-aspiring chieftains.\" \"Yes,\" he said, \"but cousin to me though that man be, it grieves me to see anyone in the place of Bendigeidfran my brother, and I cannot be glad in the same house as he.\" \"Will you take other counsel, then?\" said Pryderi. \"I have need of counsel,\" he said, \"and what counsel is that?\"",
          n: "<strong>Pryderi son of Pwyll</strong> — lord of Dyfed, the child whose birth, loss and recovery closed the First Branch — was one of the seven who carried the head home, and he and Manawydan have become close. He names Manawydan one of the <em>tri lledf unben</em>, the \"three un-aspiring (or meek) chieftains\" of Britain: a man with the best claim to the throne who never pressed a claim to so much as a field. The Triads preserve this epithet; it is the moral key to his character — the dispossessed king who will not fight for what is his, and who will, in the end, win everything back by patience and a bargain rather than by the sword." },

        { w: "\"Seith cantref Dyuet yr edewit y mi,\" heb y Pryderi, \"a Riannon uy mam yssyd yno. Mi a rodaf it honno, a medyant y seith cantref genthi. A chyny bei itti o gyuoeth namyn y seith cantref hynny, nyt oes seith cantref well noc wy. Kicua uerch Wyn Gloyw yw uy gwreic inheu,\" heb ef. \"A chyn bo enwedigaeth y kyuoeth y mi, bit y mwynant y ti a Riannon. A phei mynhut gyuoeth eiryoet, atuyd y caffut ti hwnnw.\" \"Na uynhaf, unben,\" heb ef. \"Duw a dalo it dy gydymdeithas.\" \"E gedymdeithas oreu a allwyf i, yti y byd, os mynny.\" \"Mynnaf, eneit,\" heb ef. \"Duw a dalo it. A mi a af gyt a thi y edrych Riannon, ac y edrych y kyuoeth.\"",
          e: "\"The seven cantrefs of Dyfed were left to me,\" said Pryderi, \"and Rhiannon my mother is there. I will give her to you, and the lordship of the seven cantrefs with her. And though you had no domain but those seven cantrefs alone, there are no seven cantrefs better than they. Cigfa daughter of Gwyn Gloyw is my own wife,\" he said; \"and though the title to the land be mine, let the enjoyment of it be yours and Rhiannon's. And had you ever wanted a domain, perhaps you would have had this one.\" \"I do not want it, chieftain,\" he said. \"God reward you for your friendship.\" \"The best friendship I can give shall be yours, if you will have it.\" \"I will, dear soul,\" he said. \"God reward you. And I will go with you to see Rhiannon, and to see the land.\"",
          n: "Pryderi's gift is the engine of the plot. He offers Manawydan both a kingdom — the <strong>seven cantrefs of Dyfed</strong> — and his widowed mother <strong>Rhiannon</strong>, the otherworldly, quick-witted queen of the First Branch (Pwyll's wife, won at the mound of Arberth). The arrangement is unusually generous and frank: Pryderi keeps the legal title but hands over the use of the realm and his mother's hand, asking nothing back but Manawydan's company. It also introduces <strong>Cigfa daughter of Gwyn Gloyw</strong>, Pryderi's wife — who, with the other three, will be one of the four people left alive in the enchanted land. The marriage of the landless king to the realm's dowager queen is exactly the dynastic logic of the Branches: realms are joined through women, and Manawydan steps into the place Pwyll once held." },

        { w: "\"Iawn a wney,\" heb ynteu. \"Mi a debygaf na werendeweist eiryoet ar ymdidanwreic well no hi. Yr amser y bu hitheu yn y dewred, ny bu wreic delediwach no hi; ac etwa ny bydy anuodlawn y phryt.\" Wynt a gerdassant racdunt. A pha hyt bynnac y bydynt ar y ford, wynt a doethant y Dyuet. Gwled darparedic oed udunt erbyn eu dyuot yn Arberth, a Riannon a Chicua wedy y harlwyaw.",
          e: "\"You do well,\" he said. \"I think you never listened to a better woman in conversation than she. In the time she was in her prime, there was no fairer woman than she; and even now you will not be displeased with her looks.\" They went on their way; and however long they were on the road, they came to Dyfed. A feast was made ready for them against their coming to Arberth — Rhiannon and Cigfa had prepared it.",
          n: "Pryderi praises his mother first for her <em>conversation</em> — <em>ymddiddan</em>, the art of talk — and only then for her looks: Rhiannon is the corpus's great talker, the woman who out-argues Pwyll at the mound and out-faces a false murder-charge in the First Branch. <strong>Arberth</strong> (Narberth) is the chief court of Dyfed and the hinge of both branches — Pwyll's seat, and the site of the <em>Gorsedd</em>, the magical mound, where the mist will shortly fall. That the two women have the welcome-feast already laid sets the warm, domestic key the enchantment will so brutally break." },

        { w: "Ac yna dechreu kydeisted ac ymdidan o Uanawydan a Riannon; ac o'r ymdidan tirioni a wnaeth y uryt a'y uedwl wrthi, a hoffi yn y uedwl na welsei eiryoet wreic digonach y theket a'y thelediwet no hi. \"Pryderi,\" heb ef, \"mi a uydaf wrth a dywedeist ti.\" \"Pa dywedwydat oed hwnnw?\" heb y Riannon. \"Arglwydes,\" heb y Pryderi, \"mi a'th roessum yn wreic y Uanawydan uab Llyr.\" \"A minheu a uydaf wrth hynny yn llawen,\" heb y Riannon. \"Llawen yw genhyf inheu,\" heb y Manawydan, \"a Duw a dalo y'r gwr yssyd yn rodi i minheu y gedymdeithas mor difleis a hynny.\" Kyn daruot y wled honno, y kyscwyt genti.",
          e: "And then Manawydan and Rhiannon began to sit together and to talk; and from the talking his heart and his mind grew tender toward her, and he was glad in his mind that he had never seen a woman more complete in beauty and grace than she. \"Pryderi,\" he said, \"I will abide by what you said.\" \"And what saying was that?\" said Rhiannon. \"Lady,\" said Pryderi, \"I gave you as wife to Manawydan son of Llŷr.\" \"And I will gladly abide by that,\" said Rhiannon. \"Glad am I too,\" said Manawydan, \"and God reward the man who gives me a friendship as flawless as this.\" Before that feast was over, he had slept with her.",
          n: "The courtship is over in a paragraph, and it is a courtship of <em>talk</em>: Manawydan falls for Rhiannon across the table, in conversation, exactly as Pryderi promised. Rhiannon — a queen who in the First Branch chose her own husband against her family's plans — assents to this match as freely. The understatement of the close (<em>kyn daruot y wled honno, y kyscwyt genti</em>, \"before that feast was over, he had slept with her\") is the Branches' characteristic decorum: the marriage is made, consummated, and the narrative moves on without a wasted word." },

        { w: "\"Ar ny deryw o'r wled,\" heb y Pryderi, \"treulwch chwi, a minheu a af y hebrwng uy gwrogaeth y Gaswallawn uab Beli hyt yn Lloegyr.\" \"Arglwyd,\" heb y Riannon, \"yg Kent y mae Caswallawn, a thi a elly treulaw y wled honn a'y arhos a uo nes.\" \"Ninheu a'y arhown,\" heb ef. A'r wled honno a dreulyssant, a dechreu a wnaethant kylchaw Dyuet, a'y hela, a chymryt eu digriuwch.",
          e: "\"What is left of the feast,\" said Pryderi, \"spend it together, and I will go to render my homage to Caswallon son of Beli, into England.\" \"Lord,\" said Rhiannon, \"Caswallon is in Kent, and you may spend this feast and wait until he is nearer.\" \"We will wait for him,\" he said. So they spent that feast, and began to make the circuit of Dyfed, and to hunt it, and to take their pleasure.",
          n: "<strong>Caswallon son of Beli</strong> — the historical Cassivellaunus, the British king who fought Julius Caesar, here folded into the Mabinogi's mythic time — holds the crown Manawydan will not contest. Pryderi must do <em>gwrogaeth</em>, homage, for Dyfed to the new high king, the realpolitik that places the warm little kingdom of four inside a larger, indifferent Britain. The detail that homage is owed even here quietly underlines Manawydan's choice: the rightful king sits at a country feast while his cousin holds court in Kent, and he is content." },

        { w: "Ac wrth rodyaw y wlat ny welsynt eiryoet wlat gyuanhedach no hi, na heldir well, nac amlach y mel na'y physcawt no hi. Ac yn hynny tyuu kedymdeithas y rydunt yll pedwar, hyt na mynnei yr un uot heb y gilid na dyd na nos. Ac ymysc hynny, ef a aeth at Caswallawn hyt yn Rytychen, y hebrwng y wrogaeth idaw. A diruawr lewenyd a uu yn y erbyn yno, a diolwch idaw hebrwng y wrogaeth idaw. A guedy ymchwelut, kymryt eu gwledeu ac eu hesmwythder a orugant Pryderi a Manawydan.",
          e: "And in roaming the country they had never seen a land more settled and rich, nor better hunting-ground, nor one of more abundant honey and fish, than it. And in all this a friendship grew up among the four of them, such that not one of them wished to be without the others, by day or by night. And in the midst of it, he went to Caswallon at Oxford to render his homage; and there was great rejoicing to meet him there, and thanks to him for rendering his homage. And after returning, Pryderi and Manawydan took their feasting and their ease.",
          n: "The movement closes on the idyll the rest of the branch exists to shatter: four people in a rich, peaceful, well-stocked land, in a friendship so close that <em>not one of them wished to be without the others, day or night</em>. It is the most contented picture in the Four Branches — and the narrative sets it up precisely so that the mist, when it comes, will fall on the fullest possible happiness. (Manawydan renders the homage Pryderi owed, at <strong>Rhydychen</strong>, Oxford; the small administrative loose-end tied off, the tale turns to the feast at Arberth and the Gorsedd.)" },
      ],
    },

    {
      title: "II. The feast, the thunder and the mist, and the wasteland",
      segments: [
        { w: "A dechreu gwled a orugant yn Arberth, kanys prif lys oed, ac o honei y dechreuit pob anryded. A guedy y bwyta kyntaf y nos honno, tra uei y gwassanaethwyr yn bwyta, kyuodi allan a orugant, a chyrchu Gorssed Arberth a wnaethant yll pedwar, ac yniuer gyt ac wynt.",
          e: "And they began a feast at Arberth, for it was the chief court, and from it every honour took its beginning. And after the first sitting of meat that night, while the servants were still at their food, the four of them rose and went out, and made for the Gorsedd of Arberth — they and their retinue with them.",
          n: "The <strong>Gorsedd of Arberth</strong> is the most charged place in the Four Branches. Its property was set out in <em>Pwyll</em>: whoever sits on this mound will not leave it without either receiving blows and wounds, or seeing a wonder. It was here that Pwyll first saw Rhiannon ride past on her white horse, no faster than a walk yet never overtaken. The four climb it after dinner exactly as one climbs a place where marvels are known to happen — and a marvel is what they get. The mound is a threshold to the Otherworld, and sitting on it has, in effect, opened a door." },

        { w: "Ac ual y bydant yn eisted yuelly, llyma dwryf, a chan ueint y twryf, llyma gawat o nywl yn dyuot, hyt na chanhoed yr un o honunt welet y gilyd. Ac yn ol y nywl, llyma yn goleuhau pob lle. A phan edrychyssant y ford y guelynt y preideu a'r anreitheu a'r kyuanhed kyn no hynny, ny welynt neb ryw dim, na thy, nac aniueil, na mwc, na than, na dyn, na chyuanhed, eithyr tei y llys yn wac, diffeith, anghyuanhed, heb dyn, heb uil yndunt, eu kedymdeithon e hun wedy eu colli, heb wybot dim y wrthunt, onyt wynt yll pedwar.",
          e: "And as they sat thus, behold a peal of thunder; and with the greatness of the thunder, behold a fall of mist came down, so that not one of them could see another. And after the mist, behold, everywhere grew light again. And when they looked toward where, before this, they had seen the flocks and the herds and the dwellings, they saw nothing at all — no house, no beast, no smoke, no fire, no man, no settlement — only the court's own buildings standing empty, ruined, abandoned, with neither man nor beast in them; their own people lost, with no knowing of what had become of them — only the four of them left.",
          n: "This is the great hinge of the branch and one of the most haunting images in medieval Welsh: <strong>thunder, a fall of mist, and a world wiped clean</strong>. The enchantment (<em>hud</em>) does not kill or carry off — it <em>unmakes the inhabited world</em>, leaving the four survivors standing in a depopulated land of empty halls. This is the Insular cousin of the <strong>Grail Wasteland</strong>, the <em>terre gaste</em> of the Continental romances: a kingdom sunk into desolation by an act of enchantment, waiting for the right person and the right act to lift it. The rhythm of the negation — <em>no house, no beast, no smoke, no fire, no man</em> — is the prose tradition at its most incantatory." },

        { w: "\"Oy a Arglwyd Duw,\" heb y Manawydan, \"mae yniuer y llys, ac yn anniuer ninheu namyn hynn? Awn y edrych.\" Dyuot y'r neuad a wnaethant; nyt oed neb. Kyrchu yr ystauell a'r hundy; ny welynt neb. Yn y uedgell, nac yg kegin, nyt oed namyn diffeithwch.",
          e: "\"Oh, Lord God,\" said Manawydan, \"where is the household of the court — and where are we, with none beside us but this? Let us go and look.\" They came into the hall: there was no one. They made for the chamber and the sleeping-quarters: they saw no one. In the mead-cellar, and in the kitchen, there was nothing but desolation.",
          n: "Manawydan's response is, characteristically, not lament but inventory — <em>Awn y edrych</em>, \"let us go and look\". Where Brân in the Second Branch answered catastrophe with a war-host, Manawydan answers it by methodically checking the rooms. The search through hall, chamber, sleeping-quarters, mead-cellar and kitchen — the working anatomy of a Welsh court — finds each one empty. The practical, room-by-room cast of his mind is the quality that will, by the end, lift the whole spell." },

        { w: "Dechreu a wnaethant yll pedwar treulaw y wled, a hela a wnaethant, a chymryt eu digriuwch; a dechreu a wnaeth pob un o honunt rodyaw y wlat a'r kyuoeth, y edrych a welynt ae ty ae kyuanhed; a neb ryw dim ny welynt eithyr guydlwdyn. A guedy treulaw eu gwled ac eu darmerth o honunt, dechreu a wnaethant ymborth ar gic hela, a physcawt, a bydaueu. Ac yuelly blwydyn, a'r eil, a dreulyssant yn digrif gantunt. Ac yn y diwed, dygyaw a wnaethant.",
          e: "The four of them began to use up the feast, and they hunted, and took their pleasure; and each of them began to roam the country and the realm to see whether they could find a house or a settlement — and they saw nothing at all but wild thickets. And when they had used up their feast and their provisions, they began to live on the meat of the hunt, and on fish, and on wild swarms of honey. And so they passed a year, and a second, contentedly. And at the last, they grew weary of it.",
          n: "The wasteland is not, at first, a horror to be fled but a life to be lived — and the four live it well: two years of hunting, fishing and wild honey, told as <em>digrif</em>, \"pleasant\". It is the same self-sufficient woodland survival that Orfeo keeps in the wilderness, and the same patient adaptation that marks Manawydan throughout. The single word that ends the idyll — <em>dygyaw</em>, \"they grew weary, palled of it\" — is what drives them out of the empty country and into England to live by their hands, the subject of the next movement. The enchantment has emptied the land; boredom, not hunger, is what finally moves them." },
      ],
    },

    {
      title: "III. England, and the three crafts: saddles, shields and shoes",
      segments: [
        { w: "\"Dioer,\" heb y Manawydan, \"ny bydwn ual hynn. Kyrchwn Loegyr, a cheisswn greft y kaffom yn ymborth.\" Kyrchu Lloegyr a orugant, a dyuot hyt yn Henford, a chymryt arnunt gwneuthur kyfrwyeu. A dechreu a wnaeth ef, Manawydan, llunyaw coryfeu, ac eu lliwaw ar y wed y guelsei gan Lassar Llaes Gygnwyt a chalch llassar, a gwneuthur calch lassar racdaw, ual y gwnathoed y gwr arall. Ac wrth hynny y gelwir etwa Calch Llassar, am y wneuthur o Lassar Llaes Gygnwyt.",
          e: "\"By God,\" said Manawydan, \"we will not go on like this. Let us make for England, and seek a craft to keep ourselves by.\" They made for England, and came as far as Hereford, and took up the making of saddles. And Manawydan began to shape saddle-bows, and to colour them in the way he had seen done by Llasar Llaes Gyfnewid, with blue enamel; and he made the blue enamel for himself, just as that other man had made it. And for that reason it is still called Calch Lassar — \"Llasar's enamel\" — because Llasar Llaes Gyfnewid first made it.",
          n: "The dispossessed king turns artisan — and the craft he turns to comes <strong>straight out of Branwen</strong>. <em>Llasar Llaes Gyfnewid</em> (here spelled <em>Gygnwyt</em>) is the great yellow-red man who rose from the Lake of the Cauldron, escaped the Iron House in Ireland, and brought the <strong>Cauldron of Rebirth</strong> to Britain — the very gift that wrecked the Second Branch. Manawydan, his brother's companion, learned Llasar's secret of <em>calch lassar</em>, blue enamel, and now uses it to gild saddle-bows in Hereford. It is a quiet, brilliant piece of inter-branch weaving: the same hands, the same world, the catastrophe of one branch becoming a craftsman's trade-secret in the next. The line also gives the branch's first onomastic — the enamel \"still called\" by the giant's name." },

        { w: "Ac o'r gueith hwnnw, tra geffit gan Uanawydan, ny phrynit gan gyfrwyd dros wyneb Henford na choryf na chyfrwy, yny adnabu pob un o'r kyfrwydyon y uot yn colli o'y enill, ac na phrynit dim ganthunt onyt guedy na cheffit gan Uanawydan. Ac yna ymgynullaw y gyt o honunt, a duunaw ar y lad ef a'y gedymdeithon. Ac yn hynny rybud a gawssant wynteu, a chymryt kynghor am adaw y dref. \"E rof i a Duw,\" heb y Pryderi, \"ny chynghoraf i adaw y dref, namyn llad y tayogeu raccw.\" \"Nac ef,\" heb y Manawydan, \"pei ymladem ni ac wyntwy, clot drwc uydei arnam, ac yn carcharu a wneit. Ys guell in,\" heb ef, \"kyrchu tref arall y ymossymdeithaw yndi.\"",
          e: "And of that work, so long as it could be had from Manawydan, no man across the face of Hereford would buy saddle-bow or saddle from any other saddler, until every one of them came to see that he was losing his livelihood — that nothing was bought from them save what could not be had from Manawydan. Then they gathered together and agreed to kill him and his companions. But these had warning of it, and took counsel about leaving the town. \"Between me and God,\" said Pryderi, \"my counsel is not to leave the town, but to kill those churls yonder.\" \"No,\" said Manawydan; \"if we fought them, we should get an ill name, and be thrown in prison. Better for us to make for another town, to keep ourselves there.\"",
          n: "Here is the engine of the whole England episode, and it runs three times in a row: the four are too good at the craft, the local guild loses its trade, the guild resolves to murder them, they get word, and Manawydan moves them on. The contrast between the two men is the moral spine — <strong>Pryderi</strong>, the warrior, wants to kill the <em>taeogion</em> (\"churls, bondmen\"); <strong>Manawydan</strong>, the strategist, refuses, and his reason is political: a fight would bring <em>clot drwc</em>, ill fame, and prison — and (as he says next time) word would reach the high king Caswallon, and the dispossessed have no protector. It is the patience of a man who has already lost everything and will not lose his honour too." },

        { w: "Ac yna kyrchu dinas arall a wnaethant yll pedwar. \"Pa geluydyt,\" heb y Pryderi, \"a gymerwn ni arnam?\" \"Gwnawn taryaneu,\" heb y Manawydan. \"A wdom ninheu dim y wrth hynny?\" heb y Pryderi. \"Ni a'y prouwn,\" heb ynteu. Dechreu gwneuthur gueith y taryaneu, eu llunyaw ar weith taryaneu da a welsynt, a dodi y lliw a dodyssynt ar y kyfrwyeu arnunt. A'r gweith hwnnw a lwydwys racdunt, hyt na phrynit taryan yn yr holl dref onyt guedy na cheffit ganthunt wy.",
          e: "And so the four of them made for another town. \"What craft,\" said Pryderi, \"shall we take up?\" \"Let us make shields,\" said Manawydan. \"Do we know anything about that?\" said Pryderi. \"We will try,\" he said. They set to making shields, shaping them after good shields they had seen, and putting on them the same colour they had put on the saddles. And that work prospered for them, so that no shield was bought in the whole town save what could be had from them.",
          n: "The second craft, the same pattern. Manawydan's serene \"we will try\" (<em>ni a'y prouwn</em>) at a trade neither of them knows — and then their immediate mastery of it — quietly marks these as no ordinary craftsmen. The motif of the <strong>noble who excels at any humble craft he touches</strong> runs through the episode; their hands have a more-than-human deftness, and the blue enamel of the saddles reappears on the shields, the signature of a workshop the locals cannot match." },

        { w: "Kyflym oed eu gueith wynteu, a diuessur a wneynt; ac yuelly y buant yny dygywys eu kytdrefwyr racdunt, ac yny duunyssant ar geissaw eu llad. Rybud a doeth udunt wynteu, a chlybot bot y gwyr a'e bryt ar eu dienydyaw. \"Pryderi,\" heb y Manawydan, \"y mae y gwyr hynn yn mynnu yn diuetha.\" \"Ny chymerwn ninheu y gan y tayogeu hynny. Awn adanunt, a lladwn wynt.\" \"Nac ef,\" heb ynteu, \"Caswallawn a glywei hynny, a'e wyr, a rewin uydem. Kyrchwn tref arall.\" Wynt a doethant y dref arall.",
          e: "Swift was their work, and they made shields beyond counting; and so it went until their fellow-townsmen marked them down and agreed to seek to kill them. But word came to them, and they heard that the men were bent on doing them to death. \"Pryderi,\" said Manawydan, \"these men mean to destroy us.\" \"We will not take that from those churls. Let us go at them, and kill them.\" \"No,\" he said; \"Caswallon would hear of it, and his men, and we should be ruined. Let us make for another town.\" And they went to another town.",
          n: "The second flight, and now Manawydan names the real constraint: <strong>Caswallon</strong> — the cousin who holds the crown Manawydan will not claim. The dispossessed king cannot afford a killing in an English town, because the high king would hear, and four landless people with no lord behind them would be <em>rewin</em>, undone. The whole England sequence is a study in what it costs to have given up power: Manawydan must out-think every quarrel he could once have ended with a sword, because the sword is no longer his to draw." },

        { w: "\"Pa geluydyt yd awn ni wrthi?\" heb y Manawydan. \"Yr honn y mynnych, o'r a wdam,\" heb y Pryderi. \"Nac ef,\" heb ynteu, \"gwnawn grydyaeth. Ny byd o galon gan grydyon nac ymlad a ni nac ymwarauun.\" \"Ny wnn i dim y wrth honno,\" heb y Pryderi. \"Mi a'y gwn,\" heb y Manawydan, \"a mi a dyscaf it wniaw; ac nyt ymyrrwn ar gyweiraw lledyr, namyn y brynu yn barawt, a gwneuthur yn gueith o honaw.\" Ac yna dechreu prynu y cordwal teccaf a gauas yn y dref, ac amgen ledyr no hwnnw ny phrynei ef eithyr lledyr guadneu. A dechreu a wnaeth ymgedymdeithassu a'r eurych goreu yn y dref, a pheri guaegeu y'r eskidyeu, ac euraw y guaegeu, a synnyaw e hun ar hynny yny gwybu. Ac o'r achaws hwnnw y gelwit ef yn tryded eurgryd.",
          e: "\"What craft shall we turn to?\" said Manawydan. \"Whichever you like, of those we know,\" said Pryderi. \"No,\" he said; \"let us make shoes. Cordwainers will have no heart either to fight us or to hinder us.\" \"I know nothing of that,\" said Pryderi. \"I do,\" said Manawydan, \"and I will teach you to stitch. We will not trouble with dressing leather — we will buy it ready, and make our work from it.\" And he began to buy the finest cordovan he could get in the town, and would buy no other leather than that, except sole-leather; and he struck up a friendship with the best goldsmith in the town, and had buckles made for the shoes, and the buckles gilded, and he watched it himself until he had learned it. And for that reason he was called one of the Three Gold-shoemakers.",
          n: "The third craft is chosen with the same cool calculation: shoemakers, Manawydan reckons, are too peaceable to fight back. He buys the best <em>cordwal</em> (cordovan, the fine Spanish goatskin that gives English \"cordwainer\" its name), partners with a goldsmith for gilded buckles, and learns even that by watching — earning the Triadic title <strong>one of the Three Gold-shoemakers</strong> (<em>tri eurgryd</em>) of the Island of Britain. The detail that Manawydan <em>shaped</em> the work and Pryderi <em>stitched</em> it (named in the next breath) is the branch in miniature: the king who plans, the warrior who is taught to sew." },

        { w: "Tra geffit gantaw ef, nac eskit na hossan ny phrynit dim gan gryd yn yr holl dref. Sef a wnaeth y crydyon, adnabot bot eu hennill yn pallu udunt, kanys ual y llunyei Uanawydan y gueith, y gwniei Pryderi. Dyuot y crydyon a chymryt kynghor; sef a gausant yn eu kynghor, duunaw ar eu llad. \"Pryderi,\" heb y Manawydan, \"y mae y guyr yn mynnu an llad.\" \"Pa ham y kymerwn ninheu hynny gan y tayogeu lladron,\" heb y Pryderi, \"namyn eu llad oll?\" \"Nac ef,\" heb y Manawydan, \"nyt ymladwn ac wynt, ac ny bydwn yn Lloegyr bellach. Kyrchwn parth a Dyuet, ac awn y hedrych.\" Byhyt bynnac y buant ar y fford, wynt a doethant y Dyuet, ac Arberth a gyrchyssant. A llad tan a wnaethant, a dechreu ymborth a hela, a threulaw mis yuelly, a chynnull eu cwn attunt, a bot yuelly yno ulwydyn.",
          e: "So long as work could be had from him, neither shoe nor hose was bought from any cordwainer in the whole town. The cordwainers, seeing their livelihood failing them — for as Manawydan shaped the work, Pryderi stitched it — came together and took counsel, and what they resolved was to agree to kill them. \"Pryderi,\" said Manawydan, \"these men mean to kill us.\" \"Why should we take that from thieving churls,\" said Pryderi, \"rather than kill them all?\" \"No,\" said Manawydan; \"we will not fight them, and we will be in England no longer. Let us make for Dyfed, and go to see it.\" However long they were on the road, they came to Dyfed, and made for Arberth. They kindled a fire and began to keep themselves by hunting; and so they spent a month, and gathered their dogs to them, and so were there a year.",
          n: "The third flight ends the English exile: three crafts mastered, three guilds out-earned, three murder-plots out-waited, and Pryderi's patience worn as thin as the joke is now broad. Manawydan's decision is final — <em>we will be in England no longer</em> — and they go home to the empty land, to Arberth and the hearth-fire, to hunting and their dogs. The closing note that they <em>gathered their dogs and were there a year</em> is the quiet set-up for the next movement: a year of hunting in a depopulated country, until one morning the dogs start a shining white boar that was never meant for them to catch." },
      ],
    },

    {
      title: "IV. The white boar, the caer, and the taking of Pryderi and Rhiannon",
      segments: [
        { w: "A boregueith, kyuodi Pryderi a Manawydan y hela, a chyweiraw eu cwn, a mynet odieithyr y llys. Sef a wnaeth rei o'e cwn, kerdet o'e blaen, a mynet y berth uechan oed gyr eu llaw. Ac y gyt ac yd aant y'r berth, kilyaw yn gyflym, a cheginwrych mawr aruthyr ganthunt, ac ymchwelut at y guyr. \"Nessawn,\" heb y Pryderi, \"parth a'r berth, y edrych beth yssyd yndi.\" Nessau parth a'r berth. Pan nessaant, llyma uaed coet claerwynn yn kyuodi o'r berth; sef a oruc y cwn, o hyder y guyr, ruthraw idaw. Sef a wnaeth ynteu, adaw y berth, a chilyaw dalym y wrth y guyr; ac yny uei agos y guyr idaw, kyuarth a rodei y'r cwn, heb gilyaw yrdunt; a phan ynghei y guyr, y kilyei eilweith, ac y torrei gyuarth.",
          e: "And one morning Pryderi and Manawydan rose to hunt, and made their dogs ready, and went out from the court. Some of the dogs ran on ahead of them and came to a little thicket close by; and the moment they went into the thicket, they sprang back fast, their hackles up in a great, dreadful bristle, and turned back to the men. \"Let us draw near the thicket,\" said Pryderi, \"to see what is in it.\" They drew near the thicket. When they came up, behold a shining-white wild boar rose out of it; and the dogs, emboldened by the men, rushed at him. And he left the thicket and fell back a little from the men; and until the men were close to him he would stand at bay against the dogs without giving ground; and when the men pressed up, he would fall back again, and break the bay.",
          n: "The hunt that opens the trap is a textbook <strong>Otherworld lure</strong>. The boar is <em>claerwyn</em>, \"shining-white\" — and white-with-red-ears or pure-white beasts in the Mabinogi are always from Annwn, the Otherworld (Pwyll's hounds in the First Branch are the type-case). The animal does not behave like quarry: it baits the hunters, standing just long enough to draw them on, falling back, breaking the bay — leading them, deliberately, somewhere. The supernatural white boar that draws a hunting party across a threshold is one of the oldest Celtic story-shapes, kin to Twrch Trwyth in <em>Culhwch</em> and the otherworld boar-hunts of Arthurian romance. The dogs' terror at the thicket is the tale's first signal that this is no ordinary chase." },

        { w: "Ac yn ol y baed y kerdassant, yny welynt gaer uawr aruchel, a gueith newyd arnei, yn lle ny welsynt na maen na gueith eiryoet; a'r baed yn kyrchu y'r gaer yn vuan, a'r cwn yn y ol. A guedy mynet y baed a'r cwn y'r gaer, ryuedu a wnaethant welet y gaer yn y lle ny welsynt eiryoet weith kyn no hynny; ac o ben yr orssed edrych a wnaethant ac ymwarandaw a'r cwn. Pa hyt bynnac y bydynt yuelly, ny chlywynt un o'r cwn na dim y wrthunt.",
          e: "And they followed the boar until they saw a great, lofty caer, with new-built work upon it, in a place where they had never seen stone or building before; and the boar made swiftly for the caer, and the dogs after him. And when the boar and the dogs had gone into the caer, they marvelled to see a caer in a place where they had never before seen any building at all; and from the top of the gorsedd they looked, and listened for the dogs. But however long they stayed there, they could hear not one of the dogs, nor anything of them.",
          n: "The lure delivers them to the trap proper: a <strong>vast fortress that was never there</strong>, <em>gueith newyd</em> (\"new work\") standing where no stone had ever been. The vanishing/appearing Otherworld castle (Thompson F771.1, the magic castle; D2031, illusion) is one of the genre's defining marvels, and a direct ancestor of the Grail Castle that appears and disappears in the Continental romances. That the boar and the whole pack go in and fall utterly silent — no bark, no sound — tells the reader, before either man says a word, that the caer has swallowed them; this is the mouth of the enchantment that emptied Dyfed." },

        { w: "\"Arglwyd,\" heb y Pryderi, \"mi a af y'r gaer y geissaw chwedleu y wrth y cwn.\" \"Dioer,\" heb ynteu, \"nyt da dy gynghor uynet y'r gaer. Ny welsam ni y gaer honn yma eiryoet; ac o gwney uyg kynghor i, nyt ey idi. Y neb a dodes hut ar y wlat a beris bot y gaer yma.\" \"Dioer,\" heb y Pryderi, \"ny madeuaf i uyg kwn.\" A pha gynghor bynnac a gaffei ef y gan Uanawydan, y gaer a gyrchwys ef.",
          e: "\"Lord,\" said Pryderi, \"I will go into the caer to seek tidings of the dogs.\" \"By God,\" said he, \"your counsel is not good, to go into the caer. We have never seen this caer here before; and if you take my counsel, you will not go into it. Whoever laid the enchantment on the land has caused this caer to be here.\" \"By God,\" said Pryderi, \"I will not give up my dogs.\" And for all the counsel Manawydan could give him, into the caer he went.",
          n: "This is Propp's <strong>interdiction, and its violation</strong>, in their starkest form — and the moral of Pryderi's whole life. Manawydan reads the situation exactly right: the caer is the enchanter's work, and to enter is to walk into the trap. Pryderi cannot heed him — not from stupidity but from the same impulsive courage that made him want to kill the churls of Hereford: he will not abandon his dogs. The hot-blooded loyalty that is a virtue in a warrior is, in an enchanted land, fatal. Manawydan, who would give up a kingdom rather than fight a needless fight, cannot save the man who will not give up a hound." },

        { w: "Pan doeth y'r gaer, na dyn na mil na'r baed na'r cwn, na thy nac anhed, ny welei yn y gaer. Ef a welei, ual am gymherued llawr y gaer, ffynnawn a gueith o uaen marmor yn y chylch; ac ar lann y ffynnawn, cawg eur yn rwymedic wrth bedeir cadwyn, a hynny uch benn llech o uaen marmor, a'r cadwyneu yn kyrchu yr awyr, a diben ny welei arnunt. Gorawenu a wnaeth ynteu wrth decket yr eur a dahet gueith y cawc; a dyuot a wnaeth yn yd oed y cawc, ac ymauael ac ef. Ac y gyt ac yd ymeueil a'r cawc, glynu y dwylaw wrth y cawc, a'y draet wrth y llech yd oed yn seuyll arnei, a dwyn y lyueryd y gantaw, hyt na allei dywedut un geir. A seuyll a wnaeth yuelly.",
          e: "When he came into the caer, neither man nor beast, nor boar nor dogs, nor house nor dwelling did he see in it. He saw, as it were toward the middle of the floor of the caer, a fountain with marble work around it; and on the brink of the fountain a golden bowl, fastened by four chains, and that above a slab of marble, the chains going up toward the air, and no end to them that he could see. He was overjoyed at the beauty of the gold and the fine workmanship of the bowl; and he came to where the bowl was, and laid hold of it. And the moment he laid hold of the bowl, his two hands stuck to the bowl, and his feet to the slab he was standing on, and his power of speech was taken from him, so that he could not say a single word. And so he stood.",
          n: "The trap at the centre of the empty fort is one of the eeriest images in the Branches: a <strong>marble fountain, a golden bowl on four chains rising into the air with no visible end</strong>. The chains that vanish upward make the bowl a thing hung between worlds; it is bait, and Pryderi — dazzled by the gold, exactly as the enchanter intends — takes it. The <strong>adhesion-magic</strong> (Thompson D2171, magic adhesion: hands fixed to an object) fixes hands and feet, and the loss of speech (the same dumbness the Cauldron of Rebirth inflicted in Branwen — resurrection without a voice) seals him. He is not killed or carried off; he is <em>held</em>, a living statue at the heart of the illusion. The golden vessel on its chains has been read, like the cauldron, as a far cousin of the Grail." },

        { w: "A'e aros ynteu a wnaeth Manawydan hyt parth a diwed y dyd. A phrynhawn byrr, guedy bot yn diheu gantaw ef na chaei chwedleu y wrth Pryderi nac y wrth y cwn, dyuot a oruc parth a'r llys. Pan daw y mywn, sef a wnaeth Riannon edrych arnaw. \"Mae,\" heb hi, \"dy gedymdeith di a'th cwn?\" \"Llyma,\" heb ynteu, \"uyg kyfranc,\" a'e datcanu oll. \"Dioer,\" heb y Riannon, \"ys drwc a gedymdeith uuosti, ac ys da a gedymdeith a golleisti.\" A chan y geir hwnnw mynet allan, ac y'r traws y managassei ef uot y gwr a'r gaer, kyrchu a wnaeth hitheu.",
          e: "And Manawydan waited for him until near the close of the day. And late in the afternoon, being certain that he would get no tidings of Pryderi nor of the dogs, he came back toward the court. As he came in, Rhiannon looked at him. \"Where,\" she said, \"is your comrade, and your dogs?\" \"Here,\" he said, \"is my tale\" — and he told it all. \"By God,\" said Rhiannon, \"an ill comrade you have been, and a good comrade you have lost.\" And with that word she went out, toward the quarter where he had told her the man and the caer were, and made for it.",
          n: "Manawydan's patience shows here at its most painful: he waits, alone, the whole afternoon, hoping — and only at dusk, sure there is no help, does he walk home to break the news. Rhiannon's reply is one of the sharpest lines in the Branches: <em>ys drwc a gedymdeith uuosti, ac ys da a gedymdeith a golleisti</em> — \"an ill comrade you have been, and a good comrade you have lost.\" It is unjust (Manawydan begged Pryderi not to go) and it is human — a mother lashing out at the man who came home without her son. And then she does exactly what Pryderi did, and what Manawydan would not: she walks straight to the caer." },

        { w: "Porth y gaer a welas yn agoret; ny bu argel arnei. Ac y mywn y doeth; ac y gyt ac y doeth, arganuot Pryderi yn ymauael a'r cawc, a dyuot attaw. \"Och, uy Arglwyd,\" heb hi, \"beth a wney di yma?\" Ac ymauael a'r cawc y gyt ac ef. Ac y gyt ac yd ymeueil, glynu y dwylaw hitheu wrth y cawc, a'y deutroet wrth y llech, hyt na allei hitheu dywedut un geir. Ac ar hynny, gyt ac y bu nos, llyma dwryf arnunt a chawat o nywl, a chan hynny diflannu y gaer, ac e ymdeith ac wynteu.",
          e: "The gate of the caer she found open; there was no concealing it. And in she came; and as she came, she made out Pryderi laying hold of the bowl, and went to him. \"Oh, my lord,\" she said, \"what are you doing here?\" And she laid hold of the bowl together with him. And the moment she laid hold, her two hands stuck to the bowl, and her two feet to the slab, so that she too could not say a single word. And thereupon, as night fell, behold a peal of thunder over them, and a fall of mist — and with that the caer vanished, and they away with it.",
          n: "Rhiannon — the otherworldly queen who, in the First Branch, rode a horse no one could catch and out-argued a kingdom — is undone by a mother's instinct and the same golden bait. The trap takes her exactly as it took her son: hands and feet fixed, voice gone. And then the enchantment's signature returns — <strong>thunder and a fall of mist</strong>, the very sounds that emptied the land in Movement II — and now they carry off the caer itself, and Pryderi and Rhiannon inside it. The two who held the realm by right are gone into the illusion; the land is emptier still, and only the dispossessed king and Pryderi's wife are left." },

        { w: "Pann welas Kicua uerch Wyn Gloyw, gwreic Pryderi, nat oed yn y llys namyn hi a Manawydan, drygyruerth a wnaeth, hyt nat oed well genti y byw no'y marw. Sef a wnaeth Manawydan, edrych ar hynny. \"Dioer,\" heb ef, \"cam yd wyt arnaw, os rac uy ouyn i y drygyruerthy di. Mi a rodaf Duw yn uach it, na weleisti gedymdeith gywirach noc y keffy di ui, tra uynho Duw it uot uelly. Y rof a Duw, bei yth uwn yn dechreu uy ieuengtit, mi a gadwn gywirdeb wrth Pryderi, ac yrot titheu mi a'e cadwn; ac na uit un ouyn arnat,\" heb ef. \"Titheu a gey y gedymdeithas a uynnych y genhyf i, herwyd uyg gallu, tra welho Duw yn bot yn y dihirwch hwnn a'r goual.\" \"Duw a dalho it; hynny a debygwn i.\" Ac yna kymryt llewenyd ac ehofyndra o'r uorwyn o achaws hynny.",
          e: "When Cigfa daughter of Gwyn Gloyw, Pryderi's wife, saw that there was no one in the court but herself and Manawydan, she wept and lamented until she cared not whether she lived or died. Manawydan saw it. \"By God,\" he said, \"you are wrong, if it is for fear of me that you grieve so. I give God as my surety to you that you have never seen a truer comrade than you will find in me, as long as God wills you to be so. Between me and God, were I in the very beginning of my youth, I would keep faith with Pryderi — and for your own sake I will keep it; let there be no fear on you,\" he said. \"You shall have what friendship you wish from me, as far as I am able, as long as God wills us to be in this misery and care.\" \"God reward you; that is what I thought of you.\" And then the young woman took heart and was glad of it.",
          n: "This celebrated passage is the branch's moral heart. A lone man and a lone woman — his stepson's wife — are left together in an empty world, and Manawydan's first act is to swear, on God as surety, that she has nothing to fear from him: he will keep <em>cywirdeb</em>, faith, with the absent Pryderi and with her. It directly echoes the First Branch, where <strong>Pwyll</strong> — Pryderi's father — spent a year in the bed of Arawn's wife in Annwn and turned his back to her every night, keeping faith with a friend. The two generations rhyme: the men of this family keep faith with absent comrades even when no one would know. It is also what makes Manawydan worthy to lift the spell — the enchantment is a test of character as much as a punishment, and he passes the first part of it here, with his honour rather than his sword." },
      ],
    },

    {
      title: "V. England again, and the three crofts of wheat",
      segments: [
        { w: "\"Ie, eneit,\" heb y Manawydan, \"nyt kyfle yni trigyaw yma. Yn cwn a gollyssam, ac ymborth ny allwn. Kyrchwn Loegyr; hawssaf yw in ymborth yno.\" \"Yn llawen, Arglwyd,\" heb hi, \"a ni a wnawn hynny.\" Y gyt y kerdyssant parth a Lloegyr. \"Arglwyd,\" heb hi, \"pa greft a gymery di arnat? Kymer un lanweith.\" \"Ny chymeraf i,\" heb ef, \"namyn crydyaeth, ual y gwneuthum gynt.\" \"Arglwyd,\" heb hi, \"nyt hoff honno y lanet y wr kyn gynhiilet, kyuurd a thydi.\" \"Wrth honno yd af i,\" heb ef.",
          e: "\"Well, dear soul,\" said Manawydan, \"it is no place for us to stay here. We have lost our dogs, and we cannot feed ourselves. Let us make for England; it will be easiest for us to live there.\" \"Gladly, lord,\" she said, \"we will do so.\" Together they set out for England. \"Lord,\" she said, \"what craft will you take up? Take a clean one.\" \"I will take none,\" he said, \"but shoemaking, as I did before.\" \"Lord,\" she said, \"such a craft is not fit, for its cleanliness, for a man so nobly born and of such rank as you.\" \"By that one I will go,\" he said.",
          n: "The second exile mirrors the first, but now the company is two, not four, and the dynamic is gentler. Cigfa's objection — that shoemaking is beneath a man of Manawydan's birth — is the voice of rank speaking; Manawydan's flat refusal to stand on his dignity is exactly the un-aspiring temperament the tale prizes. (There is a wry edge in <em>lanweith</em>/<em>glanet</em>, \"clean,\" applied to the leather-trade: she means a craft befitting his station, and he answers by choosing the same humble one again.) The dispossessed king who will not claim a throne will not refuse a cobbler's bench either." },

        { w: "Dechreu y geluydyt a wnaeth, a chyweiraw y weith o'r cordwal teccaf a gauas yn y dref; ac ual y dechreussant yn lle arall, dechreu guaegeu y'r eskidyeu o waegeu eureit, yny oed ofer a mangueith holl grydyon y dref y wrth yr eidaw ef e hun. A thra geffit y gantaw, nac eskit na hossan, ny phrynit y gan ereill dim. A blwydyn yuelly a dreulwys yno, yny oed y crydyon yn dala kynfigen a chynghoruynt wrthaw, ac yny doeth rybudyeu idaw, a menegi uot y crydyon wedy duunaw ar y lad. \"Arglwyd,\" heb y Kicua, \"pa ham y diodefir hynn gan y tayogeu?\" \"Nac ef,\" heb ynteu, \"ni a awn eissoes y Dyuet.\"",
          e: "He set to the craft, and fashioned his work of the finest cordovan he could get in the town; and, as they had begun in the other place, he set gilded buckles on the shoes, until the work of all the cordwainers of the town was idle and worthless beside his own. And as long as it could be had from him, neither shoe nor hose was bought from any other. A year passed thus, until the cordwainers grew full of envy and ill-will toward him, and warnings came to him that the cordwainers had agreed to kill him. \"Lord,\" said Cigfa, \"why is this borne from the churls?\" \"No,\" he said; \"we will go to Dyfed even so.\"",
          n: "The craft-and-envy cycle runs a fourth time, compressed to a paragraph: mastery, the ruined competition, the murder-plot, the warning. By now the pattern is the branch's running joke and its quiet thesis — wherever these exiles go, their otherworldly skill makes them too good to be tolerated. The difference is that Manawydan no longer even debates: where in Movement III it took an argument to stop Pryderi fighting, here Cigfa's <em>why suffer it?</em> is answered with a single weary <em>no — we will go to Dyfed</em>. He has decided that the answer to the enchantment is not in England at all." },

        { w: "Dyuet a gyrchyssant. Sef a oruc Manawydan, pan gychwynnwys parth a Dyuet, dwyn beich o wenith gantaw, a chyrchu Arberth, a chyuanhedu yno. Ac nyt oed dim digriuach gantaw no gwelet Arberth a'r tiryogaeth y buassei yn hela, ef a Phryderi a Riannon gyt ac wynt. Dechreu a wnaeth kyneuinaw a hela pyscawt, a llydnot ar eu gual yno; ac yn ol hynny dechreu ryuoryaw, ac yn ol hynny heu groft, a'r eil, a'r trydyd. Ac nachaf y guenith yn kyuot yn oreu yn y byt, a'e deir grofd yn llwydaw yn un dwf, hyt na welsei dyn wenith degach noc ef.",
          e: "They made for Dyfed. And what Manawydan did, when he set out for Dyfed, was to take with him a load of wheat; and he came to Arberth and settled there. And nothing was more pleasant to him than to see Arberth and the country he had hunted, he and Pryderi and Rhiannon with them. He began to grow used to fishing, and to hunting the wild creatures in their lairs; and after that he began to break ground, and after that to sow a croft, and a second, and a third. And behold, the wheat came up the best in the world, and his three crofts thrived as one growth, so that no man had ever seen finer wheat than it.",
          n: "Here Manawydan makes the move that wins the branch: he comes home a <strong>farmer</strong>. The <em>beich o wenith</em>, the load of seed-wheat he carries back, is the most quietly decisive object in the tale — the planner's instinct to bring the means of a future with him. He turns from craftsman to husbandman, breaking ground and sowing three crofts in the dead land, and the wheat answers with miraculous growth. The tender note that nothing pleased him more than to see the country where he had hunted <em>with Pryderi and Rhiannon</em> keeps the loss present even in the idyll; the farming is also an act of faith that there is still a kingdom worth restoring." },

        { w: "Treulaw amseroed y ulwydyn a wnaeth. Nachaf y kynhaeaf yn dyuot; ac y edrych un o'e rofdeu y doeth, nachaf honno yn aeduet. \"Mi a uynnaf uedi honn auory,\" heb ef. Dyuot tra y geuyn y nos honno hyt yn Arberth. Y bore glas drannoeth, dyuot y uynnu medi y grofd. Pan daw, nyt oed namyn y calaf yn llwm, wedy daruot torri pob un yn y doi y dywyssen o'r kelefyn, a mynet e ymdeith a'r tywys yn hollawl, ac adaw y calaf yno yn llwm. Ryuedu hynny yn uawr a wnaeth.",
          e: "He passed the seasons of the year. Behold the harvest coming on; and he came to look at one of his crofts, and behold it was ripe. \"I will reap this tomorrow,\" he said. He went home that night to Arberth. At grey dawn the next morning, he came to set about reaping the croft. When he came, there was nothing but the bare stalk — every one of them broken at the joint where it bore its ear, and the ears carried clean away, and the bare stalk left there. He marvelled greatly at it.",
          n: "The miraculous wheat meets a miraculous theft. The image is exact and uncanny: the stalks snapped precisely at the ear-joint, every head taken, the straw left standing — a harvest reaped in the night by something that wanted only the grain. This is a version of the old <strong>night-watch over a plundered field</strong>, the tale-shape in which a magical thief strips a crop until a watcher sits up to catch it (it underlies stories from the apple-stealing firebird to the ox that guards the corn). Manawydan does not yet know it, but he is being baited a second time — the enchanter drawing him toward a confrontation, exactly as the white boar drew Pryderi to the caer." },

        { w: "Dyuot y edrych grofd arall; nachaf honno yn aeduet. \"Dioer,\" heb ef, \"mi a uynnaf uedi honn auory.\" A thrannoeth dyuot ar uedwl medi honno. A phan daw, nyt oed dim namyn y calaf llwm. \"Oy a Arglwyd Duw,\" heb ef, \"pwy yssyd yn gorffen uyn diua i? A mi a'e gwnn: y neb a dechreuis uyn diua yssyd yn y orffen, ac a diuawys y wlat gyt a mi.\"",
          e: "He came to look at another croft, and behold it too was ripe. \"By God,\" he said, \"I will reap this one tomorrow.\" And the next day he came, meaning to reap it. And when he came, there was nothing but the bare stalk. \"Oh, Lord God,\" he said, \"who is it that is finishing my ruin? And I know it: the one who began my ruin is finishing it — the one who has laid the whole land waste along with me.\"",
          n: "The second croft falls exactly as the first, and Manawydan reads it correctly at last: the harvest-thief and the enchanter of the wasteland are <strong>one and the same</strong>. <em>Y neb a dechreuis uyn diua yssyd yn y orffen</em> — \"the one who began my ruin is finishing it.\" He still does not know the enemy's name (it is Llwyd son of Cil Coed, avenging a wrong done in <em>Pwyll</em>), but he now understands that the mist, the empty land, the lost comrades and the stolen wheat are a single campaign against him. The recognition changes him from a victim into a hunter — and on the third night he will arm himself, sit up over the last croft, and meet the thief. The climax follows in the final movement." },
      ],
    },

    {
      title: "VI. The mice, the gallows, and the lifting of the enchantment",
      segments: [
        { w: "Dyuot y edrych y tryded grofd. Pan doeth, ny welsei dyn wenith degach, a hwnnw yn aeduet. \"Meuyl y mi,\" heb ef, \"ony wylaf i heno. A duc yr yt arall a daw y dwyn hwnn, a mi a wybydaf beth yw.\" A chymryt y arueu a wnaeth, a dechreu gwylat y grofd; a menegi a wnaeth y Kicua hynny oll. \"Ie,\" heb hi, \"beth yssyd y'th uryt ti?\" \"Mi a wylaf y grofd heno,\" heb ef. Y wylat y grofd yd aeth. Ac ual y byd am hanner nos yuelly, nachaf twryf mwyhaf yn y byt; sef a wnaeth ynteu edrych: llyma eliwlu y byt o lygot, a chyfrif na messur ny ellit arnunt.",
          e: "He came to look at the third croft, and when he came, no man had ever seen finer wheat, and this too was ripe. \"Shame on me,\" he said, \"if I do not keep watch tonight. Whoever carried off the other corn will come to carry off this, and I will know what it is.\" And he took up his arms, and began to watch the croft; and he told Cigfa all of it. \"Well,\" she said, \"what is in your mind?\" \"I will watch the croft tonight,\" he said. He went to watch the croft. And about midnight, as he was at it, behold the greatest tumult in the world; and he looked — and behold, a whole host of the world's mice, that could be neither counted nor measured.",
          n: "Now Manawydan does what Pryderi could not be persuaded to leave undone: he <strong>arms himself and sits up</strong> over the last croft, turning watchman. The marvel that comes is the branch's most famous image — an <em>eliwlu</em>, an \"innumerable host,\" of mice, beyond counting or measure, swarming out of the dark to reap the field. The grotesque comedy and the menace sit exactly side by side, the way the whole branch holds them: this is a war-host (the enchanter's whole household, as we will learn) shrunk to vermin, and a working field stripped bare in a night." },

        { w: "Ac ny wydat yny uyd y llygot yn guan adan y grofd, a phob un yn dringyaw ar hyt y kyleuyn, ac yn y estwng genti, ac yn torri y dywyssen, ac yn guan a'r tywys e ymdeith, ac yn adaw y calaf yno. Ac ny wydyat ef uot un keleuyn yno ny bei lygoden am pob un; ac y kymerynt eu hynt racdunt a'r tywys gantunt. Ac yna rwng dicter a llit, taraw ymplith y llygot a wnaeth; a mwy noc ar y gwybet neu yr adar yn yr awyr ny chyrhaedei ef ar yr un o honunt, eithyr un a welei yn amdrwm, ual y tebygei na allei un pedestric y gordiwes. Yn ol honno y kerdwys ef, a'y dala a wnaeth, a'y dodi yn y uanec, ac a llinin rwymaw geneu y uanec, a'y chadw gantaw, a chyrchu y llys.",
          e: "Before he knew it the mice were among the croft, each one climbing up a stalk and bending it down with its weight, breaking off the ear and making off with it, and leaving the bare stalk there; and he did not see one stalk there that had not a mouse to it, and away they all went on their road, the ears with them. And then, between fury and rage, he struck among the mice; but he could no more come up with one of them than with gnats, or birds in the air — except one he saw was heavy and slow, so that he thought a man on foot could scarcely overtake it. After that one he went, and caught it, and put it in his glove, and tied the mouth of the glove with a string, and kept it by him, and made for the court.",
          n: "The whole plot turns on a single creature too heavy to flee. The host scatters like gnats, untouchable — but one mouse is <em>amdrwm</em>, slow and weighed-down, and Manawydan runs it down and pockets it in his glove. The reason for its slowness is the hinge the enchanter will reveal at the end (she is pregnant), and it is a small masterpiece of plotting: the one flaw in the enemy's design, the one hostage that can be taken, is the thing the enemy most wants back. The improvised prison — a glove tied with string — is the homely, exact detail the Branches love." },

        { w: "Dyuot y'r ystauell yn yd oed Kicua, a goleuhau y tan, ac wrth y llinyn dodi y uanec ar y wanas a oruc. \"Beth yssyd yna, Arglwyd?\" heb y Kicua. \"Lleidyr,\" heb ynteu, \"a geueis yn lledratta arnaf.\" \"Pa ryw leidyr, Arglwyd, a allut ti y dodi y'th uanec?\" heb hi. \"Llyma oll,\" heb ynteu, a menegi ual yr lygryssit ac y diuwynyssit y grofdeu idaw, ac ual y doeth y llygot idaw y'r grofd diwethaf yn y wyd. \"Ac un o honunt oed amdrwm, ac a deleis, ac yssyd yn y uanec, ac a grogaf inheu auory; ac ym kyffes y Duw, bei as caffwn oll, mi a'e crogwn.\" \"Arglwyd,\" heb hi, \"diryued oed hynny; ac eissoes annwymp yw guelet gwr kyuurd a thidi yn crogi y ryw bryf hwnnw. A phei gwnelut iawn, nyt ymyrrut yn y pryf, namyn y ellwng e ymdeith.\" \"Meuyl y mi,\" heb ef, \"bei as caffwn wy oll onys crogwn — ac a geueis, mi a'e crogaf.\"",
          e: "He came to the chamber where Cigfa was, and lit the fire, and hung the glove by its string on a peg. \"What is there, lord?\" said Cigfa. \"A thief,\" he said, \"that I caught robbing me.\" \"What kind of thief, lord, could you put in your glove?\" she said. \"Here is the whole of it,\" he said, and told how the crofts had been spoiled and ruined for him, and how the mice had come at the last croft in his sight. \"And one of them was heavy and slow, and I caught it, and it is in the glove, and I will hang it tomorrow; and by my confession to God, if I had them all, I would hang them all.\" \"Lord,\" she said, \"that is strange; and still it is unseemly to see a man of rank as high as yours hanging such a creature as that. If you did right, you would not meddle with the creature, but would let it go.\" \"Shame on me,\" he said, \"if I would not hang them all, could I get them — and what I have caught, I will hang.\"",
          n: "Manawydan treats the mouse with absolute legal seriousness: it is a <em>lleidyr</em>, a thief taken in the act, and the law of a thief is hanging. That deadpan gravity — building a case at law against a mouse — is the joke, and it is also the trap. Cigfa raises, for the first time, the objection the enchanter will use three more times: it is <em>annwymp</em>, unseemly, for a man of his <em>rank</em> to bother with a <em>pryf</em> (a \"creeping thing,\" vermin). Manawydan's refusal to be shamed by the dignity-argument is precisely what defeats Llwyd — because the whole enchantment has been, from the start, an assault on what a dispossessed man's dignity is worth, and he will not trade the one piece of leverage he has for it." },

        { w: "\"Ie, Arglwyd,\" heb hi, \"nyt oes achaws y mi y uot yn borth y'r pryf hwnnw, namyn goglyt ansyberwyt y ti; a gwna ditheu dy ewyllys, Arglwyd.\" \"Bei gwypwn inheu defnyd yn y byt y dylyut titheu bot yn borth idaw, mi a uydwn wrth dy gynghor amdanaw; a chanys ny wnn, Arglwydes, medwl yw genhyf y diuetha.\" \"A gwna ditheu yn llawen,\" heb hi. Ac yna y kyrchwys ef Orssed Arberth, a'r llygoden gantaw, a sengi dwy uorch yn y lle uchaf ar yr orssed. Ac ual y byd yuelly, llyma y guelei yscolheic yn dyuot attaw, a hen dillat hydreul tlawt amdanaw; ac neut oed seith mlyned kyn no hynny yr pan welsei ef na dyn na mil, eithyr y pedwar dyn a uuassei y gyt, yny golles y deu.",
          e: "\"Well, lord,\" she said, \"I have no cause to be a protector of that creature, save to guard you from discredit; do your will, lord.\" \"If I knew of any cause in the world why you ought to protect it, I would take your counsel about it; but since I do not, lady, I am minded to destroy it.\" \"Then do so, and welcome,\" she said. And then he made for the Gorsedd of Arberth, the mouse with him, and planted two forks on the highest point of the gorsedd. And as he was at it, behold he saw a scholar coming toward him, in old, worn, poor clothes; and it was now seven years since he had seen there either man or beast, save the four who had been together, until he lost the two.",
          n: "The counter-spell is worked, like the original wonder, on the <strong>Gorsedd of Arberth</strong> — the mound of marvels comes full circle. Manawydan builds a gallows of <em>two forks</em> (and, next, a crossbeam) to hang a mouse, an image both absurd and ritually exact. And the detail that drops here is quietly enormous: it has been <strong>seven years</strong> since he saw any human being but the four — the enchantment has lasted seven years, and the wasteland has been that long empty. The first figure to appear is a poor scholar; he is, of course, no scholar at all, but the first of the enchanter's three disguises, sent to talk Manawydan out of the hanging." },

        { w: "\"Arglwyd,\" heb yr yscolheic, \"dyd da it.\" \"Duw a rodho da it, a grayssaw wrthyt,\" heb ef. \"Pan doy di, yscolheic?\" \"Pan doaf, Arglwyd, o ganu yn Lloegyr; a phaham y gouynny di?\" \"Am na weleis,\" heb ef, \"neut seith mlyned, un dyn yma, onyt pedwar dyn diholedic, a thidi yr awr honn.\" \"Ie, Arglwyd, mynet drwy y wlat honn yd wyf inheu yr awr honn, parth a'm gwlat uy hun. A pha ryw weith yd wyt yndaw, Arglwyd?\" \"Crogi lleidyr a geueis yn lledratta arnaf.\" \"Pa ryw leidyr, Arglwyd? Pryf a welaf i'th law di ual llygoden, a drwc y gueda y wr kyuurd a thidi ymodi pryf kyfryw a hwnnw. Gellwng e ymdeith.\" \"Nac ellynghaf, y rof a Duw,\" heb ynteu. \"Yn lledratta y keueis ef, a chyfreith lleidyr a wnaf ac ef: y grogi.\" \"Arglwyd, rac guelet gwr kyuurd a thidi yn y gueith hwnnw, punt a geueis i o gardotta, mi a'e rodaf it, a gellwng y pryf e ymdeith.\" \"Nac ellynghaf, y rof a Duw, ac nys guerthaf.\" \"Gwna di, Arglwyd,\" heb ef. Ac e ymdeith yd aeth yr yscolheic.",
          e: "\"Lord,\" said the scholar, \"good day to you.\" \"God give you good, and welcome,\" he said. \"Where do you come from, scholar?\" \"I come, lord, from singing in England; and why do you ask?\" \"Because I have not seen, in seven years, one man here, save four banished people — and you, this moment.\" \"Well, lord, I am passing through this country now, toward my own land. And what work are you about, lord?\" \"Hanging a thief I caught robbing me.\" \"What kind of thief, lord? I see a creature in your hand like a mouse, and ill it befits a man of your rank to handle such a creature. Let it go.\" \"I will not, between me and God,\" he said. \"I caught it thieving, and I will deal with it by the law of a thief: hanging.\" \"Lord, rather than see a man of your rank at such work, here is a pound I got by alms; I will give it you, let the creature go.\" \"I will not, between me and God; nor will I sell it.\" \"As you will, lord,\" he said. And the scholar went his way.",
          n: "The first of three temptations, in rising rank and rising price — the most patterned, fairy-tale-shaped passage in the Four Branches. The poor scholar offers a single alms-got pound and, more pointedly, the <em>dignity</em> argument again: it ill becomes a man of your rank. Manawydan answers every approach with the same two refusals — <em>I will not free it, and I will not sell it</em> — and the formula <em>y rof a Duw</em>, \"between me and God,\" tolls through the whole scene. He has grasped, without being told, that the bargaining itself is the battle: whoever wants the mouse this badly is the one who took everything from him." },

        { w: "Ual y byd ynteu yn dodi y dulath yn y fyrch, nachaf offeirat yn dyuot attaw ar uarch yn gyweir. \"Arglwyd, dyd da it.\" \"Duw a ro da it, a'th uendith,\" heb y Manawydan. \"A pha ryw weith, Arglwyd, yd wyt yn y wneuthur?\" \"Crogi lleidyr a geueis yn lledratta arnaf.\" \"Pa ryw leidyr, Arglwyd?\" \"Pryf ar ansawd llygoden, a lledratta a wnaeth arnaf, a dihenyd lleidyr a wnaf arnaw.\" \"Arglwyd, rac dy welet yn ymodi y pryf hwnnw, mi a'e prynaf; ellwng ef.\" \"Y Duw y dygaf uyghyffes, na'e werthu na'e ollwng nys gwnaf.\" \"Guir yw, Arglwyd, nyt guerth arnaw ef dim; rac dy welet yn ymhalogi wrth y pryf hwnnw, mi a rodaf it deir punt, a gellwng ef e ymdeith.\" \"Na uynnaf, y rof a Duw, un guerth namyn yr hwnn a dyly: y grogi.\" \"Yn llawen, Arglwyd, gwna dy uympwy.\" E ymdeith yd aeth yr offeirat. Sef a wnaeth ynteu, maglu y llinin am uynwgyl y llygoden.",
          e: "As he was setting the crossbeam on the forks, behold a priest came toward him on a well-appointed horse. \"Lord, good day to you.\" \"God give you good, and your blessing,\" said Manawydan. \"And what work, lord, are you doing?\" \"Hanging a thief I caught robbing me.\" \"What kind of thief, lord?\" \"A creature in the shape of a mouse; it robbed me, and I will do upon it the doom of a thief.\" \"Lord, rather than see you handle that creature, I will buy it; let it go.\" \"I give my confession to God, I will neither sell it nor free it.\" \"True it is, lord, it is worth nothing to buy; but rather than see you defile yourself with that creature, I will give you three pounds, let it go.\" \"I will not, between me and God, take any price but the one it is owed: hanging.\" \"Gladly, lord; do your whim.\" The priest went his way. And what Manawydan did was to noose the string about the mouse's neck.",
          n: "The second temptation: a priest, mounted and well-furnished, the price now three pounds. The structure is folktale to the bone — scholar, priest, bishop; one pound, three pounds, then a fortune — and the rising splendour of each visitor (the foot-traveller, the man on a good horse, the bishop with a baggage-train) is itself a tell that this is one power dressing in ascending disguises. Manawydan, unmoved, does the chilling next thing: he nooses the string around the mouse's neck. He is not bluffing; the gallows is real, and the enchanter, watching his wife about to hang, must now come himself." },

        { w: "Ac ual yd oed yn y dyrchauael, llyma rwttwr escob a welei a'y swmereu a'y niuer, a'r escob e hun yn kyrchu parth ac attaw. Sef a wnaeth ynteu, gohir ar y weith. \"Arglwyd escob, dy uendith.\" \"Duw a rodho y uendith it. Pa ryw weith yd wyt yndaw?\" \"Crogi lleidyr a geueis yn lledratta arnaf.\" \"Ponyt llygoden a welaf i'th law di?\" \"Ie, a lleidyr uu hi arnaf.\" \"Can doethwyf i ar diuetha y pryf hwnnw, mi a'e prynaf y genhyt; mi a rodaf seith punt it yrdaw, a rac guelet gwr kyuurd a thi yn diuetha pryf mor dielw, gollwng ef, a'r da a geffy.\" \"Na ellynghaf, y rof a Duw.\" \"Kanys gollyngy yr hynny, mi a rodaf it pedeir punt ar ugeint o aryant parawt.\" \"Na ellynghaf, y rof a Duw, yr y gymeint arall.\" \"Canys ny ellyngy yr hynny, mi a rodaf it a wely o uarch yn y maes hwnn, a seith swmer, a seith march y maent arnunt.\" \"Na uynnaf, y rof a Duw.\" \"Cany mynny hynny, gwna y guerth dy hun.\" \"Gwnaf: rydhau Riannon a Phryderi.\" \"Ti a gehy hynny.\" \"Na ellynghaf etwa, y rof a Duw.\" \"Beth a uynny ditheu?\" \"Guaret yr hut a'r lledrith y ar seith cantref Dyuet.\" \"Ti a geffy hynny heuyt; a gellwng y llygoden.\" \"Na ellyngaf, y rof a Duw. Gwybot a uynnaf pwy yw y llygoden.\" \"Uy gwreic i yw hi.\"",
          e: "And as he was raising it up, behold a bishop's train he saw, with his sumpter-horses and his retinue, and the bishop himself making toward him. He paused at his work. \"Lord bishop, your blessing.\" \"God give you his blessing. What work are you about?\" \"Hanging a thief I caught robbing me.\" \"Is that not a mouse I see in your hand?\" \"Yes, and a thief she was to me.\" \"Since I have come upon the destroying of that creature, I will buy it from you; I will give you seven pounds for it, and rather than see a man of your rank destroy so worthless a creature, let it go, and the money is yours.\" \"I will not free it, between me and God.\" \"Since you will not for that, I will give you four-and-twenty pounds of ready silver.\" \"I will not, between me and God, for as much again.\" \"Since you will not for that, I will give you all the horses you see in this field, and seven sumpters, and the seven horses they are on.\" \"I will not, between me and God.\" \"Since you will not have that, name your own price.\" \"I will: the freeing of Rhiannon and Pryderi.\" \"That you shall have.\" \"And still I will not free it, between me and God.\" \"What more do you want?\" \"The lifting of the enchantment and illusion from off the seven cantrefs of Dyfed.\" \"That too you shall have; and free the mouse.\" \"I will not, between me and God. I want to know who the mouse is.\" \"She is my wife.\"",
          n: "The third visitor — a bishop with a baggage-train — and the bargaining proper. The offers climb in a glorious escalation (seven pounds, then twenty-four, then every horse in the field), and each is refused with the same toll, <em>y rof a Duw</em>, until the bishop, desperate, says the fatal words: <em>name your own price</em>. Now Manawydan, who has held his one hostage through every temptation, spends it with surgical patience, one demand at a time, freeing the mouse only after the last: <strong>Pryderi and Rhiannon released</strong>, then <strong>the enchantment lifted from Dyfed</strong>, and still he holds on — <em>I want to know who the mouse is</em>. The answer undoes the whole disguise: <em>she is my wife</em>. The bishop is the enchanter, and the worthless <em>pryf</em> on the gallows is the thing he most loves." },

        { w: "\"Pa gyffuryf y doeth hi attaf i?\" \"Y herwa,\" heb ynteu. \"Mi yw Llwyt uab Kil Coet, a mi a dodeis yr hut ar seith cantref Dyuet; ac y dial Guawl uab Clut, o gedymdeithas ac ef, y dodeis i yr hut; ac ar Pryderi y dieleis i guare broch yg got a wnaeth Pwyll Penn Annwn ar Guawl uab Clut, a hynny yn llys Eueyd Hen o aghynghor. A guedy clybot dy uot yn kyuanhedu y wlat, y doeth uy nheulu attaf y erchi eu rithyaw yn llygot, y diua dy yt; ac y doeth uy nheulu e hunein y nos gyntaf, a'r eil nos, ac y diuayssant y dwy grofd. A'r tryded nos y doeth uy gwreic a gwraged y llys attaf y erchi im eu rithaw, ac y ritheis inheu; a beichawc oed hi, ac ony bei ueichawc nys gordiwedut ti; a chanys bu, a'e dala, mi a rodaf Pryderi a Riannon it, ac a waredaf yr hut a'r lledrith y ar Dyuet. Mi a uenegeis it pwy yw hi; gellwng hi.\" \"Na ellynghaf, y rof a Duw, yny welwyf Pryderi a Riannon yn ryd gyt a mi.\" \"Wely di wynteu yn dyuot,\" heb ef. Ac ar hynny, llyma Pryderi a Riannon. Kyuodi a oruc ynteu yn eu herbyn, a'e graessawu, ac eisted y gyt.",
          e: "\"In what manner did she come to me?\" \"To plunder you,\" he said. \"I am Llwyd son of Cil Coed, and it was I who laid the enchantment on the seven cantrefs of Dyfed; and to avenge Gwawl son of Clud, out of friendship for him, I laid it; and on Pryderi I avenged the game of Badger-in-the-Bag that Pwyll Head of Annwn played on Gwawl son of Clud — and that, in the court of Hyfaidd Hen, rashly. And when it was heard that you were settling the land, my household came to me asking to be shaped into mice, to destroy your corn; and my own household went the first night, and the second night, and they ruined your two crofts. And the third night my wife and the ladies of the court came to me asking to be transformed, and I transformed them — and she was pregnant, and had she not been pregnant you would not have overtaken her; but since it has happened, and she is caught, I will give you Pryderi and Rhiannon, and I will lift the enchantment and illusion from off Dyfed. I have told you who she is; free her.\" \"I will not, between me and God, until I see Pryderi and Rhiannon free with me.\" \"See, here they come,\" he said. And thereupon, behold Pryderi and Rhiannon. He rose to meet them, and welcomed them, and they sat down together.",
          n: "Here at last is the cause of everything — and it reaches back into the <strong>First Branch</strong>. <strong>Llwyd son of Cil Coed</strong> is a magician avenging his friend <strong>Gwawl son of Clud</strong>, the suitor Rhiannon was promised to before she chose Pwyll. In <em>Pwyll</em>, at the court of Hyfaidd Hen, Pwyll tricked Gwawl into a magic bag and his men beat him in the game called <em>Badger-in-the-Bag</em> (<em>gware broch yng nghod</em>) — and the text here passes its own verdict, that Pwyll did it <em>o aghynghor</em>, \"rashly, ill-advisedly.\" The whole Third Branch is the long-delayed payback: the wasteland, the mist, the lost comrades, the stolen wheat are all one act of vengeance for a humiliation a generation old — visited on Pwyll's son Pryderi, his wife Rhiannon, and the man who married into the house. The mice are Llwyd's whole court shape-shifted; the slow one is his pregnant wife; and that one mercy of nature — that she could not run — is the thread on which Manawydan has hung the salvation of a kingdom." },

        { w: "\"A wrda, rytha uy ngwreic im weithon, ac neut ry geueist gwbyl o'r a nodeist.\" \"Ellynghaf yn llawen,\" heb ef. Ac yna y gollyngwys hi; ac y trewis ynteu hi a hutlath, ac y datrithwys hi yn wreigyang deccaf a welsei neb. \"Edrych i'th gylch ar y wlat,\" heb ef, \"a thi a wely yr holl anhedeu a'r kyuanhed ual y buant oreu.\" Ac yna kyuodi a oruc ynteu, ac edrych; a phan edrych, ef a welei yr holl wlat yn gyuanhed, ac yn gyweir o'e holl alauoed a'e hanedeu. \"Pa ryw wassanaeth y bu Pryderi a Riannon yndaw?\" heb ef. \"Pryderi a uydei ac yrd porth uy llys i am y uynwgyl, a Riannon a uydei a mynweireu yr essynn, wedy bydynt yn kywein gueir, am y mynwgyl hitheu; ac yuelly y bu eu carchar.\" Ac o achaws y carchar hwnnw, y gelwit y kyuarwydyt hwnnw Mabinogi Mynweir a Mynordd. Ac yuelly y teruyna y geing honn yma o'r Mabinogi.",
          e: "\"Good sir, free my wife now, for you have had the whole of what you stipulated.\" \"I will free her gladly,\" he said. And then he freed her; and Llwyd struck her with a magic wand, and changed her back into the fairest young woman anyone had seen. \"Look about you at the land,\" he said, \"and you will see all the dwellings and the settlement as they were at their best.\" And then he rose, and looked; and when he looked, he saw the whole land settled, and complete in all its herds and its dwellings. \"What manner of service were Pryderi and Rhiannon in?\" he said. \"Pryderi had the gate-knockers of my court about his neck; and Rhiannon had the collars of the asses, after they had been carrying hay, about her neck — and such was their bondage.\" And on account of that bondage this tale was called the Mabinogi of Mynweir and Mynordd. And so ends this branch here of the Mabinogi.",
          n: "Manawydan has bargained back everything and given up nothing but a mouse — and only once it is safe. Llwyd's <strong>magic wand</strong> (<em>hudlath</em>, the same word as Math's enchanter's-rod) turns the mouse into the fairest of women, and the wasteland is whole again in a glance: every herd, every dwelling, every neighbour restored. The bondage Pryderi and Rhiannon endured in the Otherworld is the branch's last, darkest joke — the prince made to wear the <strong>gate-knockers</strong> of an enemy's court about his neck, the queen the <strong>hay-collars of the asses</strong> — a deliberate humiliation of the proud house of Dyfed. From those two objects (<em>Mynweir</em>, the gate-yoke, and <em>Mynordd</em>) the branch takes its colophon-title. The Third Branch is the only one of the Four where the lack is fully liquidated and the kingdom truly restored — and it is restored not by a sword or a quest but by one patient man who refused, three times over, to be shamed off a hill." },
      ],
    },
  ],
};
