/* Math uab Mathonwy — the Fourth and last Branch of the Mabinogi. The English
   shown alongside the Welsh is an original translation, written movement by
   movement; Lady Charlotte Guest's public-domain version (1849) is consulted
   as a sense-check, not copied.

   The Welsh is the Welsh Wikisource reading text (CC BY-SA 4.0), the same
   edition that supplies Pwyll on this site — a normalised reading text of the
   White Book / Red Book tradition. It is the sequel to Manawydan, and its
   first movement closes the Pryderi thread that has run through all four
   Branches.

   Both source texts are preserved verbatim under source/:
     math-rhys-evans-1887-redbook.txt   (Middle Welsh reading text)
     math-guest-1849-english.txt         (Guest's comparison translation)
   Attaches to window.MATH. */
window.MATH = window.MATH || {};
window.MATH.tale = {
  meta: {
    blurb: "<strong>Math uab Mathonwy</strong> — \"Math son of Mathonwy\" — the <em>Fourth</em> and last Branch of the Mabinogi, the sequel to <em>Manawydan</em> and the close of the cycle, preserved in the White Book of Rhydderch (c. 1350) and the Red Book of Hergest (c. 1382–1410). It is the branch of the <strong>children of Dôn</strong> — a family of magicians — and of transformation. <strong>Math</strong>, the old enchanter-king of Gwynedd, can live only with his feet in a maiden's lap except in time of war; so his nephew <strong>Gwydion</strong>, the great trickster and shape-shifter, starts a war on purpose. He steals the Otherworld swine of <strong>Pryderi</strong> of Dyfed with a herd of illusory horses and gilded shields conjured from fungus, and in the war that follows he kills Pryderi in single combat by strength and magic — ending the thread that has run through all four Branches. The war was only a pretext: in Math's absence Gwydion's brother <strong>Gilfaethwy</strong> forces the king's foot-holder, <strong>Goewin</strong>. Math weds Goewin to mend her honour, and punishes the brothers by turning them, three years running, into paired beasts — deer, then boar, then wolves — each bearing the other young. Then, seeking a new foot-holder, Math tests <strong>Aranrhod</strong>; she fails the test, and in failing drops two boys — one, <strong>Dylan</strong>, takes to the sea, and the other Gwydion rears in secret. Aranrhod lays three curses on that son: he shall have no <strong>name</strong>, no <strong>arms</strong>, and no <strong>wife of any race on earth</strong>, unless from her. Gwydion breaks the first two by trickery — winning him the name <strong>Lleu Llaw Gyffes</strong> — and, with Math, breaks the third by conjuring a wife out of flowers: <strong>Blodeuwedd</strong>. But Blodeuwedd loves another, <strong>Gronw Pebr</strong>; the two contrive the one near-impossible way Lleu can be killed, and strike him down — and Lleu rises as an <strong>eagle</strong> and flies away wounded. Gwydion seeks him over all Gwynedd, finds him by the rotting tree, sings him down and restores him; and the reckoning falls — Blodeuwedd turned to an <strong>owl</strong>, Gronw killed by the spear-blow he once dealt, and Lleu lord of Gwynedd once more. The translation below is <strong>original</strong> and proceeds <strong>movement by movement</strong>; the Welsh beside it is the Wikisource reading text. Full sources at <a href=\"source/math-rhys-evans-1887-redbook.txt\">source/math-rhys-evans-1887-redbook.txt</a> and <a href=\"source/math-guest-1849-english.txt\">source/math-guest-1849-english.txt</a>.",
    sources: [
      { label: "Math uab Mathonwy — Welsh Wikisource reading text (CC BY-SA 4.0; White Book / Red Book tradition)", url: "https://cy.wikisource.org/wiki/Math_uab_Mathonwy", host: "Welsh Wikisource" },
      { label: "The Mabinogion — Lady Charlotte Guest, 1838–49 (public-domain English translation)", url: "https://www.gutenberg.org/ebooks/5160", host: "Project Gutenberg" },
      { label: "Math fab Mathonwy — overview", url: "https://en.wikipedia.org/wiki/Math_fab_Mathonwy", host: "Wikipedia" },
      { label: "The Four Branches of the Mabinogi", url: "https://en.wikipedia.org/wiki/Four_Branches_of_the_Mabinogi", host: "Wikipedia" },
    ],
  },
  roadmap: [
    { t: "Source text in hand (Welsh Wikisource reading text + Guest 1849)", done: true },
    { t: "I · The swine of Annwn, the war, and the death of Pryderi", done: true },
    { t: "II · The wrong to Goewin; Math's punishment of the brothers", done: false },
    { t: "III · The foot-holder test; the births of Dylan and Lleu", done: false },
    { t: "IV · Aranrhod's three curses, and how Gwydion broke two", done: false },
    { t: "V · Blodeuwedd the flower-wife; the betrayal and the eagle", done: false },
    { t: "VI · The finding of Lleu, and the reckoning", done: false },
  ],
  passages: [
    {
      title: "I. The swine of Annwn, the war, and the death of Pryderi",
      segments: [
        { w: "Math uab Mathonwy oed arglwyd ar Wyned, a Pryderi uab Pwyll oed arglwyd ar un cantref ar ugeint yn y Deheu. Sef oed y rei hynny, seith cantref Dyuet, a seith Morgannhwc, a phedwar Kyredigyawn, a thri Ystrat Tywi. Ac yn yr oes honno Math uab Mathonwy ny bydei uyw namyn tra uei y deudroet ymlyc croth morwyn, onyt kynwryf ryuel a'y llesteirei. Sef oed yn uorwyn gyt ac ef, Goewin uerch Pebin o Dol Pebin yn Aruon; a honno teccaf morwyn oed yn y hoes o'r a wydit yno. Ac ynteu yg Kaer Dathyl yn Aruon yd oed y wastatrwyd; ac ny allei gylchu y wlat, namyn Giluaethwy uab Dôn a Gwydyon uab Dôn, y nyeint, meibon y chwaer, a'r teulu gyt ac wy, a aei y gylchu y wlat drostaw.",
          e: "Math son of Mathonwy was lord over Gwynedd, and Pryderi son of Pwyll was lord over the one-and-twenty cantrefs of the South — that is, the seven cantrefs of Dyfed, the seven of Morgannwg, the four of Ceredigion, and the three of Ystrad Tywi. And in that age, Math son of Mathonwy could not live unless his two feet were in the lap of a maiden, except when the tumult of war kept him from it. The maiden who was with him was Goewin daughter of Pebin, of Dôl Bebin in Arfon, and she was the fairest maiden of her time that was known there. And his dwelling was always at Caer Dathyl in Arfon; he could not go the circuit of the land, but Gilfaethwy son of Dôn and Gwydion son of Dôn, his nephews, his sister's sons, and the household with them, went the circuit of the land in his stead.",
          n: "The Fourth Branch opens on a king who is half-myth. <strong>Math son of Mathonwy</strong> is the old magician-king of Gwynedd, bound by a strange sacral condition: save in war, his feet must rest in the lap of a virgin <em>foot-holder</em> (the office is real in Welsh law; the magical compulsion is the tale's own). It is a fragile, archaic kingship — and its one loophole, <em>war</em>, is exactly what Gwydion will exploit. The <strong>children of Dôn</strong> — Gwydion, Gilfaethwy, and (later) Aranrhod — are a family of enchanters, the Welsh counterpart of the Irish Túatha Dé Danann (Dôn ≈ Danu); Gwydion's name was later given to the Milky Way, <em>Caer Wydion</em>. Note the opening also fixes Pryderi, son of Pwyll of the First Branch, as lord of the whole South — setting up the last act of his long story." },

        { w: "A'r uorwyn oed gyt a Math yn wastat; ac ynteu Giluaethwy uab Dôn a dodes y uryt ar y uorwyn, a'y charu hyt na wydat beth a wnâi ymdanei; ac nachaf y liw a'y wed a'y ansawd yn atueilaw o'y charyat, hyt nat oed hawd y adnabot. Sef a wnaeth Gwydyon y urawt, synnyeit dydgweith arnaw yn graf. \"A was,\" heb ef, \"pa derw it?\" \"Beth a wely di arnaf i?\" \"Gwelaf arnat,\" heb ef, \"colli dy bryt a'th liw.\" \"Arglwyd urawt,\" heb ef, \"yr hynn a deryw ymi, ny frwytha ymi y adef y neb… Ti a wdost kynedyf Math uab Mathonwy: ba hustyng bynnac, yr y uychanet, o ry kyuarfo y gwynt ac ef, ef a'y gwybyd.\" \"Ie,\" heb y Gwydyon, \"taw di bellach. Mi a wnn dy uedwl: caru Goewin yd wyt ti.\"",
          e: "The maiden was with Math continually; and Gilfaethwy son of Dôn set his heart on her, and loved her until he did not know what to do for love of her — until his colour and his face and his whole bearing wasted away with longing, so that he was hard to recognise. His brother Gwydion looked hard at him one day. \"Lad,\" he said, \"what has come over you?\" \"What do you see in me?\" \"I see,\" he said, \"that you have lost your looks and your colour.\" \"Lord brother,\" he said, \"what ails me, it would do me no good to confess to anyone… You know the nature of Math son of Mathonwy: whatever whisper there is between people, however low, if the wind meets it, he will know it.\" \"Yes,\" said Gwydion. \"Say no more. I know your mind: you love Goewin.\"",
          n: "The whole branch is set in motion by a love that cannot be spoken — and a king who hears every whisper the wind catches. Math's <em>wind-borne hearing</em> is the magical omniscience of the sacral king; it makes ordinary scheming impossible, so the conspirators need something bigger than a whisper — a war — to get Math away from his court and his foot-holder. <strong>Gwydion</strong>, the elder brother, is the engine of the tale: the cleverest man in the world, a poet, an illusionist and a fixer, who reads Gilfaethwy's secret in a glance and at once begins to plot a way to serve it." },

        { w: "Pan wybu ef adnabot o'y urawt y uedwl, dodi ucheneit dromhaf yn y byt. \"Taw, eneit, a'th ucheneidaw,\" heb ef; \"nyt o hynny y goruydir. Mi a baraf, cany ellir heb hynny, dygyuori Gwyned a Phowys a Deheubarth y geissaw y uorwyn; a byd lawen di.\" Ac ar hynny at Uath uab Mathonwy yd aethant. \"Arglwyd,\" heb y Gwydyon, \"mi a gigleu dyuot y'r Deheu ryw bryuet ny doeth y'r ynys honn eiroet.\" \"Pwy eu henw wy?\" \"Hobeu, Arglwyd.\" \"Pa ryw aniueileit yw y rei hynny?\" \"Aniueileit bychein, gwell eu kic no chic eidon; bychein ynt, ac y maent yn symudaw enweu — moch y gelwir weithon. Pryderi uab Pwyll bieu wynt, yd anuonet idaw o Annwn y gan Arawn urenhin Annwn.\"",
          e: "When Gilfaethwy found that his brother knew his mind, he heaved the heaviest sigh in the world. \"Hush, my soul, and do not sigh,\" said Gwydion; \"it is not by sighing that this is won. I will raise — since it cannot be done otherwise — Gwynedd and Powys and Deheubarth, to seek the maiden. Be of good cheer.\" And with that they went to Math son of Mathonwy. \"Lord,\" said Gwydion, \"I have heard that there have come to the South a kind of beast that never came to this island before.\" \"What are they called?\" \"Hogs, lord.\" \"What sort of animals are these?\" \"Small animals, their flesh better than the flesh of oxen; they are small, and they are changing their name — they are called swine now. Pryderi son of Pwyll owns them; they were sent to him from Annwn, by Arawn king of Annwn.\"",
          n: "Gwydion's plan is breathtaking in its cynicism: to get his brother an hour alone with Goewin, he will set three kingdoms marching. The pretext is the <strong>swine of Annwn</strong> — the first pigs in Britain, a gift to Pryderi from <strong>Arawn king of Annwn</strong> (the Otherworld lord of the First Branch, where Pwyll won his friendship). Pigs are prestige- and Otherworld-animals in Celtic tradition, and these are doubly so. The detail that the beasts are \"changing their name\" from <em>hob</em> to <em>moch</em> is the branch's first onomastic touch — names and naming are one of its great themes, and will become the hinge of Aranrhod's first curse." },

        { w: "\"Mi a af ar uyn deudecuet, yn rith beird, Arglwyd, y erchi y moch.\" \"Ef a ry eill ych necau,\" heb ynteu. \"Nyt drwc uyn trawscwyd i, Arglwyd; ny doaf i heb y moch.\" Ef a aeth, a Giluaethwy, a deg gwyr gyt ac wynt, hyt yg Keredigyawn, y'r lle a elwir Rudlan Teiui yr awrhon; yd oed llys yno y Pryderi. Ac yn rith beird y doethant ymywn; llawen uuwyt wrthunt. Ar neillaw Pryderi y gossodet Gwydyon y nos honno. Ynteu Wydyon, goreu kyuarwyd yn y byt oed; a'r nos honno didanu y llys a wnaeth ar ymdidaneu digrif a chyuarwydyt, yny oed hoff gan paub o'r llys.",
          e: "\"I will go, as one of twelve, in the guise of bards, lord, to ask for the swine.\" \"It may be that he will refuse you,\" said Math. \"My errand will not go badly, lord; I will not come back without the swine.\" So he went, and Gilfaethwy, and ten men with them, into Ceredigion, to the place now called Rhuddlan Teifi, where Pryderi had a court. In the guise of bards they came in, and were made welcome; Gwydion was seated beside Pryderi that night. And Gwydion was the best teller of tales in the world; that night he entertained the court with pleasant talk and stories, until he was the delight of everyone there.",
          n: "Gwydion enters Pryderi's hall disguised as the chief of a company of <strong>bards</strong> — and his cover is no lie: he really is the best storyteller in the world, and charms the whole court, exactly as Welsh tales prize the guest who can recite. It is a portrait of the poet as con-man, and a quietly self-aware one: the Fourth Branch, itself a masterpiece of storytelling, makes its villain-hero a supreme storyteller. The disguise-embassy recalls the trickster-entries of <em>Culhwch</em> (Cei as a sword-burnisher) — deception by disguise is deep in the tradition." },

        { w: "Ac ar diwed hynny, \"Arglwyd,\" heb ef, \"llyma uy neges: ymadolwyn a thidi am yr aniueileit a anuonet it o Annwuyn.\" \"Hawssaf yn y byt oed hynny,\" heb ynteu, \"by na bei ammot y rof a'm gwlat amdanunt: nat elont y genhyf yny hilyont eu deu kymeint yn y wlat.\" \"Arglwyd,\" heb ynteu, \"mi a allaf dy rydhau o'r geireu hynny: na dyro im y moch heno, ac na nacaha ui ohonunt; auory mi a dangossaf gyfnewit amdanunt.\" Ac yna yd aeth ef yn y geluydodeu, ac y dechreuawt dangos y hut: yd hudwys deudec emys, a deudec milgi bronwyn du, a deudec torch ac deudec kynllyuan arnunt — ac ny wydat neb o'r a'e gwelei na bydynt eur — a deudec kyfrwy ar y meirch, a phob lle y dylyei hayarn uot arnunt, y bydei gwbyl o eur.",
          e: "And at the end of it, \"Lord,\" he said, \"here is my errand: to beg of you the beasts that were sent you from Annwn.\" \"That would be the easiest thing in the world,\" said Pryderi, \"were there not a covenant between me and my land concerning them — that they shall not leave me until they have bred twice their number in the land.\" \"Lord,\" said Gwydion, \"I can release you from those words. Do not give me the swine tonight, and do not refuse them me; tomorrow I will show you an exchange for them.\" And that night he went to his arts, and began to work an enchantment: he conjured twelve stallions, and twelve white-breasted black greyhounds, with twelve collars and twelve leashes on them — and no one who saw them could tell they were not gold — and twelve saddles on the horses, and wherever there should have been iron, all was gold.",
          n: "Pryderi's refusal is honourable — he is bound by a <em>covenant with his land</em> not to part with the swine until they have doubled — and Gwydion's answer is pure fraud: he will not buy or be refused, but <em>exchange</em>. Overnight he works his signature magic, <em>hud</em> — conjuring twelve horses, twelve hounds and (next) twelve gilded shields, all gleaming gold, all illusion. Gwydion is the Mabinogi's master illusionist, and this is the first of the branch's many enchantments; the gold-from-nothing trick is as old as fairy money, and as treacherous." },

        { w: "A'r meirch a'r cwn y doeth ef at Pryderi, a'r deudec taryan eureit (y rei hynny a rithassei ef o'r madalch). \"Arglwyd,\" heb ef, \"llyma rydit it am y geir a dywedeist neithwyr: titheu a elly gyfnewit yr a uo gwell.\" Sef a gaussant yn eu kynghor, rodi y moch e Wydyon, a chymryt y meirch a'r cwn a'r taryaneu. Ac yna y dechreussant gerdet a'r moch. \"A geimeit,\" heb y Gwydyon, \"reit yw in gerdet yn bryssur: ny phara yr hut namyn o'r pryt pwy gilyd.\" A'r nos honno y kerdyssant hyt ygwarthaf Keredigyawn, y lle a elwir etwa o achaws hynny Mochtref; a thrannoeth dros Elenit; a'r nos honno y rwng Keri ac Arwystli, yn y dref a elwir heuyt Mochtref; ac odyna hyt yg kymwt ym Powys, a elwir o'r ystyr hwnnw Mochnant.",
          e: "He brought the horses and the dogs to Pryderi, and the twelve gilded shields (those he had conjured out of fungus). \"Lord,\" he said, \"here is a release for you from the word you spoke last night: you may exchange them for something better.\" And the counsel they reached was to give the swine to Gwydion, and take the horses and the dogs and the shields. Then they set off with the swine. \"Comrades,\" said Gwydion, \"we must travel fast: the enchantment will last only from this hour to the same tomorrow.\" That night they travelled to the top of Ceredigion, to the place still called for that reason Mochdref — \"Swine-town\"; the next day across Elenydd; that night between Keri and Arwystli, to the town also called Mochdref; and thence to the commot in Powys called, for the same reason, Mochnant — \"Swine-brook.\"",
          n: "The shields conjured <em>o'r madalch</em>, \"out of fungus,\" are the perfect emblem of Gwydion's magic — splendour grown from rot, doomed to last exactly a day. The race home, one jump ahead of the illusion's collapse, leaves a trail of place-names across mid-Wales: <strong>Mochdref</strong> (swine-town), <strong>Mochnant</strong> (swine-brook), and shortly <strong>Creuwryon</strong> (the swine-sties). The Four Branches are studded with these onomastic anchors — the story explaining a real map — and Math is the densest of all; the cycle remembers itself in the land." },

        { w: "Sef y kyrchyssant y dref uchaf o Arllechwed, ac yno gwneuthur creu y'r moch, ac o'r achaws hwnnw y dodet Creuwryon ar y dref. Ac yna y kyrchyssant ar Uath, hyt yg Kaer Dathyl. A phan doethant, yd oedit yn dygyuori y wlat: \"Dygyuor y mae Pryderi yn ych ol chwi, un cantref ar ugeint.\" Ar hynny y clywynt yr utkyrn a'r dygyuor; gwiscaw a wnaethant, a cherdet yny uydant ym Pennard yn Aruon. A'r nos honno yd ymhoelwys Gwydyon uab Dôn a Giluaethwy y urawt y gyt y Gaer Dathyl; ac y guely Math uab Mathonwy y dygwyt Goewin uerch Pebin o'y hanuod, a chyscu genti y nos honno o'y hanuod.",
          e: "They made for the highest town of Arllechwedd, and there built sties for the swine, and for that reason the town was named Creuwryon. And then they made for Math, to Caer Dathyl. And when they came, the land was being mustered: \"Pryderi is mustering behind you — one-and-twenty cantrefs. It is a wonder you travelled so slowly.\" At that they heard the war-horns and the muster; they armed, and marched until they were at Pennardd in Arfon. But that night Gwydion son of Dôn and his brother Gilfaethwy turned back together to Caer Dathyl; and into Math's own bed Goewin daughter of Pebin was taken against her will, and that night she was forced.",
          n: "Here the war's true purpose is paid out, and the branch turns very dark. With Math drawn off to fight the war Gwydion manufactured, the brothers slip back to the undefended court, and <strong>Goewin is forced</strong> — the outrage the whole rest of the movement, and Math's terrible punishment, will answer. The tale states it with grave brevity, twice naming that it was <em>against her will</em> (<em>o'y hanuod</em>), and the apparatus follows that lead: the wrong is named, not dwelt on. It is a crime against the king's honour and the foot-holder's person at once — and, because Math hears all whispers, one that cannot stay hidden." },

        { w: "Pan welsant y dyd drannoeth, kyrchu a wnaethant parth a'r lle yd oed Math a'y lu. A Phryderi a'y kyrchwys; ac yno y bu y gyfranc, ac y llas lladua uawr o pob parth, ac y bu reit y wyr y Deheu enkil. Ac yna clymu a wnaethant, a cheissaw ymdangneuedu; a gwystlaw a wnaeth Pryderi ar y tangneued, Gwrgi Gwastra a phedwar ar ugeint o ueibyon gwyrda. A guedy hynny, kerdet o honunt yn eu tangneued hyt y Traeth Mawr; ac am na ellit reoli y pedyt rac ymsaethu, gyrru kennadeu o Pryderi y erchi gadu y ryngtaw ef a Gwydyon uab Dôn, kanys ef a baryssei hynny. \"Dygaf y Duw uyg kyffes,\" heb y Gwydyon, \"nat archaf i y wyr Gwyned ymlad drossof i, a minheu uy hun yn cael ymlad a Phryderi. Mi a dodaf uyg korf yn erbyn y eidaw yn llawen.\"",
          e: "When they saw the day next morning, they made for the place where Math and his host were. And Pryderi attacked; and there the battle was joined, and a great slaughter fell on both sides, and the men of the South were forced to retreat. Then they made a truce and sought to come to peace, and Pryderi gave hostages for the peace — Gwrgi Gwastra and four-and-twenty sons of nobles. And after that they went in truce as far as the Traeth Mawr; but because the foot-soldiers could not be kept from shooting, Pryderi sent messengers to ask that it be left between him and Gwydion son of Dôn alone, since it was he who had caused all this. \"I call God to witness,\" said Gwydion, \"I will not ask the men of Gwynedd to fight for me, when I myself may fight Pryderi. I will set my own body against his, gladly.\"",
          n: "Pryderi's demand is just, and it is the moral hinge of the movement: the war was Gwydion's doing, so let Gwydion answer for it in his own body, and spare the two armies. Gwydion accepts at once — and there is real honour in it. But the duel that follows will not be fought on equal terms." },

        { w: "Ac yna o nerth ac angerd, ac o hut a lledrith, Gwydyon a oruu, a Phryderi a las. Ac yg Maen Tyuyawc, uch y Uelen Ryd, y cladwyt; ac yno y mae y ued. Y gwyr y Deheu a gerdyssant tu a'u gwlat ban gwynfanus. Ac nyt oed ryued: eu harglwyd a gollyssynt, a llawer o'u gwyrda, a'u meirch, a'u harueu y ran uwyaf. Y gwyr Gwyned a ymchoelyssant adref yn llawen orfoledus. \"Arglwyd,\" heb y Gwydyon wrth Uath, \"pony chyfreithawn ni ellwng eu gwystlon y wyr y Deheu? Ny dylyynt garchar.\" \"Gellynger wynt,\" heb ynteu.",
          e: "And then by strength and ferocity, and by magic and enchantment, Gwydion prevailed, and Pryderi was slain. At Maen Tyfiawg, above Y Felen Rhyd, he was buried; and there is his grave. The men of the South went back toward their own land in bitter lament — and no wonder: they had lost their lord, and many of their nobles, and their horses and arms for the most part. The men of Gwynedd went home glad and triumphant. \"Lord,\" said Gwydion to Math, \"would it not be lawful to release the men of the South their hostages? They do not deserve imprisonment.\" \"Let them be freed,\" said Math.",
          n: "So <strong>Pryderi dies</strong> — and the death is shadowed, for Gwydion wins not by strength alone but <em>o hut a lledrith</em>, \"by magic and enchantment.\" The boy whose birth, loss and recovery closed the First Branch, who survived the catastrophe of the Second and helped lift the wasteland of the Third, is killed in the Fourth by a magician's trick on a battlefield Gwydion arranged for an utterly private reason. It is the end of the great connecting thread of the Mabinogi, and the tale lets the men of the South grieve him properly. Gwydion's smooth turn to lawyerly courtesy in the very next breath — <em>shall we not free the hostages?</em> — is the measure of the man: the war he started for his brother is, to him, already an administrative matter. His own reckoning, and Gilfaethwy's, is still to come." },
      ],
    },
  ],
};
