/* Math uab Mathonwy — the Fourth and last Branch of the Mabinogi. The English
   shown alongside the Welsh is an original translation, written movement by
   movement; Lady Charlotte Guest's public-domain version (1849) is consulted
   as a sense-check, not copied.

   The Welsh is the Welsh Wikisource reading text (CC BY-SA 4.0), the same
   edition that supplies Pwyll on this site — a normalised reading text of the
   White Book / Red Book tradition. It is the sequel to Manawydan, and its
   first movement closes the Pryderi thread that has run through all four
   Branches.

   Both source texts are preserved verbatim under source/:
     math-rhys-evans-1887-redbook.txt   (Middle Welsh reading text)
     math-guest-1849-english.txt         (Guest's comparison translation)
   Attaches to window.MATH. */
window.MATH = window.MATH || {};
window.MATH.tale = {
  meta: {
    blurb: "<strong>Math uab Mathonwy</strong> — \"Math son of Mathonwy\" — the <em>Fourth</em> and last Branch of the Mabinogi, the sequel to <em>Manawydan</em> and the close of the cycle, preserved in the White Book of Rhydderch (c. 1350) and the Red Book of Hergest (c. 1382–1410). It is the branch of the <strong>children of Dôn</strong> — a family of magicians — and of transformation. <strong>Math</strong>, the old enchanter-king of Gwynedd, can live only with his feet in a maiden's lap except in time of war; so his nephew <strong>Gwydion</strong>, the great trickster and shape-shifter, starts a war on purpose. He steals the Otherworld swine of <strong>Pryderi</strong> of Dyfed with a herd of illusory horses and gilded shields conjured from fungus, and in the war that follows he kills Pryderi in single combat by strength and magic — ending the thread that has run through all four Branches. The war was only a pretext: in Math's absence Gwydion's brother <strong>Gilfaethwy</strong> forces the king's foot-holder, <strong>Goewin</strong>. Math weds Goewin to mend her honour, and punishes the brothers by turning them, three years running, into paired beasts — deer, then boar, then wolves — each bearing the other young. Then, seeking a new foot-holder, Math tests <strong>Aranrhod</strong>; she fails the test, and in failing drops two boys — one, <strong>Dylan</strong>, takes to the sea, and the other Gwydion rears in secret. Aranrhod lays three curses on that son: he shall have no <strong>name</strong>, no <strong>arms</strong>, and no <strong>wife of any race on earth</strong>, unless from her. Gwydion breaks the first two by trickery — winning him the name <strong>Lleu Llaw Gyffes</strong> — and, with Math, breaks the third by conjuring a wife out of flowers: <strong>Blodeuwedd</strong>. But Blodeuwedd loves another, <strong>Gronw Pebr</strong>; the two contrive the one near-impossible way Lleu can be killed, and strike him down — and Lleu rises as an <strong>eagle</strong> and flies away wounded. Gwydion seeks him over all Gwynedd, finds him by the rotting tree, sings him down and restores him; and the reckoning falls — Blodeuwedd turned to an <strong>owl</strong>, Gronw killed by the spear-blow he once dealt, and Lleu lord of Gwynedd once more. The translation below is <strong>original</strong> and proceeds <strong>movement by movement</strong>; the Welsh beside it is the Wikisource reading text. Full sources at <a href=\"source/math-rhys-evans-1887-redbook.txt\">source/math-rhys-evans-1887-redbook.txt</a> and <a href=\"source/math-guest-1849-english.txt\">source/math-guest-1849-english.txt</a>.",
    sources: [
      { label: "Math uab Mathonwy — Welsh Wikisource reading text (CC BY-SA 4.0; White Book / Red Book tradition)", url: "https://cy.wikisource.org/wiki/Math_uab_Mathonwy", host: "Welsh Wikisource" },
      { label: "The Mabinogion — Lady Charlotte Guest, 1838–49 (public-domain English translation)", url: "https://www.gutenberg.org/ebooks/5160", host: "Project Gutenberg" },
      { label: "Math fab Mathonwy — overview", url: "https://en.wikipedia.org/wiki/Math_fab_Mathonwy", host: "Wikipedia" },
      { label: "The Four Branches of the Mabinogi", url: "https://en.wikipedia.org/wiki/Four_Branches_of_the_Mabinogi", host: "Wikipedia" },
    ],
  },
  roadmap: [
    { t: "Source text in hand (Welsh Wikisource reading text + Guest 1849)", done: true },
    { t: "I · The swine of Annwn, the war, and the death of Pryderi", done: true },
    { t: "II · The wrong to Goewin; Math's punishment of the brothers", done: true },
    { t: "III · The foot-holder test; the births of Dylan and Lleu", done: true },
    { t: "IV · Aranrhod's three curses, and how Gwydion broke two", done: true },
    { t: "V · Blodeuwedd the flower-wife; the betrayal and the eagle", done: true },
    { t: "VI · The finding of Lleu, and the reckoning", done: true },
  ],
  passages: [
    {
      title: "I. The swine of Annwn, the war, and the death of Pryderi",
      segments: [
        { w: "Math uab Mathonwy oed arglwyd ar Wyned, a Pryderi uab Pwyll oed arglwyd ar un cantref ar ugeint yn y Deheu. Sef oed y rei hynny, seith cantref Dyuet, a seith Morgannhwc, a phedwar Kyredigyawn, a thri Ystrat Tywi. Ac yn yr oes honno Math uab Mathonwy ny bydei uyw namyn tra uei y deudroet ymlyc croth morwyn, onyt kynwryf ryuel a'y llesteirei. Sef oed yn uorwyn gyt ac ef, Goewin uerch Pebin o Dol Pebin yn Aruon; a honno teccaf morwyn oed yn y hoes o'r a wydit yno. Ac ynteu yg Kaer Dathyl yn Aruon yd oed y wastatrwyd; ac ny allei gylchu y wlat, namyn Giluaethwy uab Dôn a Gwydyon uab Dôn, y nyeint, meibon y chwaer, a'r teulu gyt ac wy, a aei y gylchu y wlat drostaw.",
          e: "Math son of Mathonwy was lord over Gwynedd, and Pryderi son of Pwyll was lord over the one-and-twenty cantrefs of the South — that is, the seven cantrefs of Dyfed, the seven of Morgannwg, the four of Ceredigion, and the three of Ystrad Tywi. And in that age, Math son of Mathonwy could not live unless his two feet were in the lap of a maiden, except when the tumult of war kept him from it. The maiden who was with him was Goewin daughter of Pebin, of Dôl Bebin in Arfon, and she was the fairest maiden of her time that was known there. And his dwelling was always at Caer Dathyl in Arfon; he could not go the circuit of the land, but Gilfaethwy son of Dôn and Gwydion son of Dôn, his nephews, his sister's sons, and the household with them, went the circuit of the land in his stead.",
          n: "The Fourth Branch opens on a king who is half-myth. <strong>Math son of Mathonwy</strong> is the old magician-king of Gwynedd, bound by a strange sacral condition: save in war, his feet must rest in the lap of a virgin <em>foot-holder</em> (the office is real in Welsh law; the magical compulsion is the tale's own). It is a fragile, archaic kingship — and its one loophole, <em>war</em>, is exactly what Gwydion will exploit. The <strong>children of Dôn</strong> — Gwydion, Gilfaethwy, and (later) Aranrhod — are a family of enchanters, the Welsh counterpart of the Irish Túatha Dé Danann (Dôn ≈ Danu); Gwydion's name was later given to the Milky Way, <em>Caer Wydion</em>. Note the opening also fixes Pryderi, son of Pwyll of the First Branch, as lord of the whole South — setting up the last act of his long story." },

        { w: "A'r uorwyn oed gyt a Math yn wastat; ac ynteu Giluaethwy uab Dôn a dodes y uryt ar y uorwyn, a'y charu hyt na wydat beth a wnâi ymdanei; ac nachaf y liw a'y wed a'y ansawd yn atueilaw o'y charyat, hyt nat oed hawd y adnabot. Sef a wnaeth Gwydyon y urawt, synnyeit dydgweith arnaw yn graf. \"A was,\" heb ef, \"pa derw it?\" \"Beth a wely di arnaf i?\" \"Gwelaf arnat,\" heb ef, \"colli dy bryt a'th liw.\" \"Arglwyd urawt,\" heb ef, \"yr hynn a deryw ymi, ny frwytha ymi y adef y neb… Ti a wdost kynedyf Math uab Mathonwy: ba hustyng bynnac, yr y uychanet, o ry kyuarfo y gwynt ac ef, ef a'y gwybyd.\" \"Ie,\" heb y Gwydyon, \"taw di bellach. Mi a wnn dy uedwl: caru Goewin yd wyt ti.\"",
          e: "The maiden was with Math continually; and Gilfaethwy son of Dôn set his heart on her, and loved her until he did not know what to do for love of her — until his colour and his face and his whole bearing wasted away with longing, so that he was hard to recognise. His brother Gwydion looked hard at him one day. \"Lad,\" he said, \"what has come over you?\" \"What do you see in me?\" \"I see,\" he said, \"that you have lost your looks and your colour.\" \"Lord brother,\" he said, \"what ails me, it would do me no good to confess to anyone… You know the nature of Math son of Mathonwy: whatever whisper there is between people, however low, if the wind meets it, he will know it.\" \"Yes,\" said Gwydion. \"Say no more. I know your mind: you love Goewin.\"",
          n: "The whole branch is set in motion by a love that cannot be spoken — and a king who hears every whisper the wind catches. Math's <em>wind-borne hearing</em> is the magical omniscience of the sacral king; it makes ordinary scheming impossible, so the conspirators need something bigger than a whisper — a war — to get Math away from his court and his foot-holder. <strong>Gwydion</strong>, the elder brother, is the engine of the tale: the cleverest man in the world, a poet, an illusionist and a fixer, who reads Gilfaethwy's secret in a glance and at once begins to plot a way to serve it." },

        { w: "Pan wybu ef adnabot o'y urawt y uedwl, dodi ucheneit dromhaf yn y byt. \"Taw, eneit, a'th ucheneidaw,\" heb ef; \"nyt o hynny y goruydir. Mi a baraf, cany ellir heb hynny, dygyuori Gwyned a Phowys a Deheubarth y geissaw y uorwyn; a byd lawen di.\" Ac ar hynny at Uath uab Mathonwy yd aethant. \"Arglwyd,\" heb y Gwydyon, \"mi a gigleu dyuot y'r Deheu ryw bryuet ny doeth y'r ynys honn eiroet.\" \"Pwy eu henw wy?\" \"Hobeu, Arglwyd.\" \"Pa ryw aniueileit yw y rei hynny?\" \"Aniueileit bychein, gwell eu kic no chic eidon; bychein ynt, ac y maent yn symudaw enweu — moch y gelwir weithon. Pryderi uab Pwyll bieu wynt, yd anuonet idaw o Annwn y gan Arawn urenhin Annwn.\"",
          e: "When Gilfaethwy found that his brother knew his mind, he heaved the heaviest sigh in the world. \"Hush, my soul, and do not sigh,\" said Gwydion; \"it is not by sighing that this is won. I will raise — since it cannot be done otherwise — Gwynedd and Powys and Deheubarth, to seek the maiden. Be of good cheer.\" And with that they went to Math son of Mathonwy. \"Lord,\" said Gwydion, \"I have heard that there have come to the South a kind of beast that never came to this island before.\" \"What are they called?\" \"Hogs, lord.\" \"What sort of animals are these?\" \"Small animals, their flesh better than the flesh of oxen; they are small, and they are changing their name — they are called swine now. Pryderi son of Pwyll owns them; they were sent to him from Annwn, by Arawn king of Annwn.\"",
          n: "Gwydion's plan is breathtaking in its cynicism: to get his brother an hour alone with Goewin, he will set three kingdoms marching. The pretext is the <strong>swine of Annwn</strong> — the first pigs in Britain, a gift to Pryderi from <strong>Arawn king of Annwn</strong> (the Otherworld lord of the First Branch, where Pwyll won his friendship). Pigs are prestige- and Otherworld-animals in Celtic tradition, and these are doubly so. The detail that the beasts are \"changing their name\" from <em>hob</em> to <em>moch</em> is the branch's first onomastic touch — names and naming are one of its great themes, and will become the hinge of Aranrhod's first curse." },

        { w: "\"Mi a af ar uyn deudecuet, yn rith beird, Arglwyd, y erchi y moch.\" \"Ef a ry eill ych necau,\" heb ynteu. \"Nyt drwc uyn trawscwyd i, Arglwyd; ny doaf i heb y moch.\" Ef a aeth, a Giluaethwy, a deg gwyr gyt ac wynt, hyt yg Keredigyawn, y'r lle a elwir Rudlan Teiui yr awrhon; yd oed llys yno y Pryderi. Ac yn rith beird y doethant ymywn; llawen uuwyt wrthunt. Ar neillaw Pryderi y gossodet Gwydyon y nos honno. Ynteu Wydyon, goreu kyuarwyd yn y byt oed; a'r nos honno didanu y llys a wnaeth ar ymdidaneu digrif a chyuarwydyt, yny oed hoff gan paub o'r llys.",
          e: "\"I will go, as one of twelve, in the guise of bards, lord, to ask for the swine.\" \"It may be that he will refuse you,\" said Math. \"My errand will not go badly, lord; I will not come back without the swine.\" So he went, and Gilfaethwy, and ten men with them, into Ceredigion, to the place now called Rhuddlan Teifi, where Pryderi had a court. In the guise of bards they came in, and were made welcome; Gwydion was seated beside Pryderi that night. And Gwydion was the best teller of tales in the world; that night he entertained the court with pleasant talk and stories, until he was the delight of everyone there.",
          n: "Gwydion enters Pryderi's hall disguised as the chief of a company of <strong>bards</strong> — and his cover is no lie: he really is the best storyteller in the world, and charms the whole court, exactly as Welsh tales prize the guest who can recite. It is a portrait of the poet as con-man, and a quietly self-aware one: the Fourth Branch, itself a masterpiece of storytelling, makes its villain-hero a supreme storyteller. The disguise-embassy recalls the trickster-entries of <em>Culhwch</em> (Cei as a sword-burnisher) — deception by disguise is deep in the tradition." },

        { w: "Ac ar diwed hynny, \"Arglwyd,\" heb ef, \"llyma uy neges: ymadolwyn a thidi am yr aniueileit a anuonet it o Annwuyn.\" \"Hawssaf yn y byt oed hynny,\" heb ynteu, \"by na bei ammot y rof a'm gwlat amdanunt: nat elont y genhyf yny hilyont eu deu kymeint yn y wlat.\" \"Arglwyd,\" heb ynteu, \"mi a allaf dy rydhau o'r geireu hynny: na dyro im y moch heno, ac na nacaha ui ohonunt; auory mi a dangossaf gyfnewit amdanunt.\" Ac yna yd aeth ef yn y geluydodeu, ac y dechreuawt dangos y hut: yd hudwys deudec emys, a deudec milgi bronwyn du, a deudec torch ac deudec kynllyuan arnunt — ac ny wydat neb o'r a'e gwelei na bydynt eur — a deudec kyfrwy ar y meirch, a phob lle y dylyei hayarn uot arnunt, y bydei gwbyl o eur.",
          e: "And at the end of it, \"Lord,\" he said, \"here is my errand: to beg of you the beasts that were sent you from Annwn.\" \"That would be the easiest thing in the world,\" said Pryderi, \"were there not a covenant between me and my land concerning them — that they shall not leave me until they have bred twice their number in the land.\" \"Lord,\" said Gwydion, \"I can release you from those words. Do not give me the swine tonight, and do not refuse them me; tomorrow I will show you an exchange for them.\" And that night he went to his arts, and began to work an enchantment: he conjured twelve stallions, and twelve white-breasted black greyhounds, with twelve collars and twelve leashes on them — and no one who saw them could tell they were not gold — and twelve saddles on the horses, and wherever there should have been iron, all was gold.",
          n: "Pryderi's refusal is honourable — he is bound by a <em>covenant with his land</em> not to part with the swine until they have doubled — and Gwydion's answer is pure fraud: he will not buy or be refused, but <em>exchange</em>. Overnight he works his signature magic, <em>hud</em> — conjuring twelve horses, twelve hounds and (next) twelve gilded shields, all gleaming gold, all illusion. Gwydion is the Mabinogi's master illusionist, and this is the first of the branch's many enchantments; the gold-from-nothing trick is as old as fairy money, and as treacherous." },

        { w: "A'r meirch a'r cwn y doeth ef at Pryderi, a'r deudec taryan eureit (y rei hynny a rithassei ef o'r madalch). \"Arglwyd,\" heb ef, \"llyma rydit it am y geir a dywedeist neithwyr: titheu a elly gyfnewit yr a uo gwell.\" Sef a gaussant yn eu kynghor, rodi y moch e Wydyon, a chymryt y meirch a'r cwn a'r taryaneu. Ac yna y dechreussant gerdet a'r moch. \"A geimeit,\" heb y Gwydyon, \"reit yw in gerdet yn bryssur: ny phara yr hut namyn o'r pryt pwy gilyd.\" A'r nos honno y kerdyssant hyt ygwarthaf Keredigyawn, y lle a elwir etwa o achaws hynny Mochtref; a thrannoeth dros Elenit; a'r nos honno y rwng Keri ac Arwystli, yn y dref a elwir heuyt Mochtref; ac odyna hyt yg kymwt ym Powys, a elwir o'r ystyr hwnnw Mochnant.",
          e: "He brought the horses and the dogs to Pryderi, and the twelve gilded shields (those he had conjured out of fungus). \"Lord,\" he said, \"here is a release for you from the word you spoke last night: you may exchange them for something better.\" And the counsel they reached was to give the swine to Gwydion, and take the horses and the dogs and the shields. Then they set off with the swine. \"Comrades,\" said Gwydion, \"we must travel fast: the enchantment will last only from this hour to the same tomorrow.\" That night they travelled to the top of Ceredigion, to the place still called for that reason Mochdref — \"Swine-town\"; the next day across Elenydd; that night between Keri and Arwystli, to the town also called Mochdref; and thence to the commot in Powys called, for the same reason, Mochnant — \"Swine-brook.\"",
          n: "The shields conjured <em>o'r madalch</em>, \"out of fungus,\" are the perfect emblem of Gwydion's magic — splendour grown from rot, doomed to last exactly a day. The race home, one jump ahead of the illusion's collapse, leaves a trail of place-names across mid-Wales: <strong>Mochdref</strong> (swine-town), <strong>Mochnant</strong> (swine-brook), and shortly <strong>Creuwryon</strong> (the swine-sties). The Four Branches are studded with these onomastic anchors — the story explaining a real map — and Math is the densest of all; the cycle remembers itself in the land." },

        { w: "Sef y kyrchyssant y dref uchaf o Arllechwed, ac yno gwneuthur creu y'r moch, ac o'r achaws hwnnw y dodet Creuwryon ar y dref. Ac yna y kyrchyssant ar Uath, hyt yg Kaer Dathyl. A phan doethant, yd oedit yn dygyuori y wlat: \"Dygyuor y mae Pryderi yn ych ol chwi, un cantref ar ugeint.\" Ar hynny y clywynt yr utkyrn a'r dygyuor; gwiscaw a wnaethant, a cherdet yny uydant ym Pennard yn Aruon. A'r nos honno yd ymhoelwys Gwydyon uab Dôn a Giluaethwy y urawt y gyt y Gaer Dathyl; ac y guely Math uab Mathonwy y dygwyt Goewin uerch Pebin o'y hanuod, a chyscu genti y nos honno o'y hanuod.",
          e: "They made for the highest town of Arllechwedd, and there built sties for the swine, and for that reason the town was named Creuwryon. And then they made for Math, to Caer Dathyl. And when they came, the land was being mustered: \"Pryderi is mustering behind you — one-and-twenty cantrefs. It is a wonder you travelled so slowly.\" At that they heard the war-horns and the muster; they armed, and marched until they were at Pennardd in Arfon. But that night Gwydion son of Dôn and his brother Gilfaethwy turned back together to Caer Dathyl; and into Math's own bed Goewin daughter of Pebin was taken against her will, and that night she was forced.",
          n: "Here the war's true purpose is paid out, and the branch turns very dark. With Math drawn off to fight the war Gwydion manufactured, the brothers slip back to the undefended court, and <strong>Goewin is forced</strong> — the outrage the whole rest of the movement, and Math's terrible punishment, will answer. The tale states it with grave brevity, twice naming that it was <em>against her will</em> (<em>o'y hanuod</em>), and the apparatus follows that lead: the wrong is named, not dwelt on. It is a crime against the king's honour and the foot-holder's person at once — and, because Math hears all whispers, one that cannot stay hidden." },

        { w: "Pan welsant y dyd drannoeth, kyrchu a wnaethant parth a'r lle yd oed Math a'y lu. A Phryderi a'y kyrchwys; ac yno y bu y gyfranc, ac y llas lladua uawr o pob parth, ac y bu reit y wyr y Deheu enkil. Ac yna clymu a wnaethant, a cheissaw ymdangneuedu; a gwystlaw a wnaeth Pryderi ar y tangneued, Gwrgi Gwastra a phedwar ar ugeint o ueibyon gwyrda. A guedy hynny, kerdet o honunt yn eu tangneued hyt y Traeth Mawr; ac am na ellit reoli y pedyt rac ymsaethu, gyrru kennadeu o Pryderi y erchi gadu y ryngtaw ef a Gwydyon uab Dôn, kanys ef a baryssei hynny. \"Dygaf y Duw uyg kyffes,\" heb y Gwydyon, \"nat archaf i y wyr Gwyned ymlad drossof i, a minheu uy hun yn cael ymlad a Phryderi. Mi a dodaf uyg korf yn erbyn y eidaw yn llawen.\"",
          e: "When they saw the day next morning, they made for the place where Math and his host were. And Pryderi attacked; and there the battle was joined, and a great slaughter fell on both sides, and the men of the South were forced to retreat. Then they made a truce and sought to come to peace, and Pryderi gave hostages for the peace — Gwrgi Gwastra and four-and-twenty sons of nobles. And after that they went in truce as far as the Traeth Mawr; but because the foot-soldiers could not be kept from shooting, Pryderi sent messengers to ask that it be left between him and Gwydion son of Dôn alone, since it was he who had caused all this. \"I call God to witness,\" said Gwydion, \"I will not ask the men of Gwynedd to fight for me, when I myself may fight Pryderi. I will set my own body against his, gladly.\"",
          n: "Pryderi's demand is just, and it is the moral hinge of the movement: the war was Gwydion's doing, so let Gwydion answer for it in his own body, and spare the two armies. Gwydion accepts at once — and there is real honour in it. But the duel that follows will not be fought on equal terms." },

        { w: "Ac yna o nerth ac angerd, ac o hut a lledrith, Gwydyon a oruu, a Phryderi a las. Ac yg Maen Tyuyawc, uch y Uelen Ryd, y cladwyt; ac yno y mae y ued. Y gwyr y Deheu a gerdyssant tu a'u gwlat ban gwynfanus. Ac nyt oed ryued: eu harglwyd a gollyssynt, a llawer o'u gwyrda, a'u meirch, a'u harueu y ran uwyaf. Y gwyr Gwyned a ymchoelyssant adref yn llawen orfoledus. \"Arglwyd,\" heb y Gwydyon wrth Uath, \"pony chyfreithawn ni ellwng eu gwystlon y wyr y Deheu? Ny dylyynt garchar.\" \"Gellynger wynt,\" heb ynteu.",
          e: "And then by strength and ferocity, and by magic and enchantment, Gwydion prevailed, and Pryderi was slain. At Maen Tyfiawg, above Y Felen Rhyd, he was buried; and there is his grave. The men of the South went back toward their own land in bitter lament — and no wonder: they had lost their lord, and many of their nobles, and their horses and arms for the most part. The men of Gwynedd went home glad and triumphant. \"Lord,\" said Gwydion to Math, \"would it not be lawful to release the men of the South their hostages? They do not deserve imprisonment.\" \"Let them be freed,\" said Math.",
          n: "So <strong>Pryderi dies</strong> — and the death is shadowed, for Gwydion wins not by strength alone but <em>o hut a lledrith</em>, \"by magic and enchantment.\" The boy whose birth, loss and recovery closed the First Branch, who survived the catastrophe of the Second and helped lift the wasteland of the Third, is killed in the Fourth by a magician's trick on a battlefield Gwydion arranged for an utterly private reason. It is the end of the great connecting thread of the Mabinogi, and the tale lets the men of the South grieve him properly. Gwydion's smooth turn to lawyerly courtesy in the very next breath — <em>shall we not free the hostages?</em> — is the measure of the man: the war he started for his brother is, to him, already an administrative matter. His own reckoning, and Gilfaethwy's, is still to come." },
      ],
    },

    {
      title: "II. The wrong to Goewin, and Math's punishment of the brothers",
      segments: [
        { w: "Ynteu Math a gyrchwys Caer Dathyl. Giluaethwy uab Dôn a'r teulu a uuassei gyt ac ef a gyrchyssant y gylchaw Gwyned mal y gnotayssynt, heb gyrchu y llys. Ynteu Math a gyrchwys y ystauell, ac a beris kyweiraw lle idaw y benelinyaw, ual y caei dodi y draet ym plyc croth y uorwyn. \"Arglwyd,\" heb y Goewin, \"keis uorwyn a uo is dy draet weithon; gwreic wyf i.\" \"Pa ystyr yw hynny?\" \"Kyrch, Arglwyd, a doeth am uym penn, a hynny yn diargel, ac ny buum distaw inheu; ny bu yn y llys nys gwypei. Sef a doeth, dy nyeint, meibon dy chwaer, Gwydyon uab Dôn a Giluaethwy uab Dôn; a threis arnaf a orugant, a chywilyd y titheu; a chyscu a wnaethpwyt genhyf, a hynny yth ystauell ac yth wely.\"",
          e: "Math then made for Caer Dathyl. Gilfaethwy son of Dôn and the household that had been with him went off about Gwynedd on the circuit, as they were wont, and did not come to the court. Math went to his chamber, and had a place made ready for him to recline, so that he might set his feet in the lap of the maiden. \"Lord,\" said Goewin, \"seek now a maiden to be under your feet; I am a woman.\" \"What do you mean by that?\" \"An assault came upon me, lord, and that openly — and I was not silent; there was no one in the court who did not know of it. It was your nephews who came, your sister's sons, Gwydion son of Dôn and Gilfaethwy son of Dôn; and they did violence to me, and shame to you; I was forced — and that in your own chamber and your own bed.\"",
          n: "The crime surfaces the only way it can in Math's court — Goewin states it plainly to his face, because she did <em>not</em> stay silent and the whole court already knows (nothing escapes the king who hears the wind). The Welsh is careful and unflinching about the wrong: it was <em>treis</em>, violence/rape, done openly, in the king's own bed — an outrage at once against Goewin's person, against the sacral office of the foot-holder (who must be a virgin), and against Math's honour and his very life-condition. Goewin's first words are not for herself but a practical warning to her king: <em>seek another, I am a woman now</em> — the foot-rest can no longer be hers." },

        { w: "\"Ie,\" heb ynteu, \"yr hyn a allaf i, mi a'e gwnaf. Mi a baraf iawn y ti yn gyntaf, ac yn ol uy iawn y bydaf inheu. A thitheu,\" heb ef, \"mi a'th gymeraf yn wreic im, ac a rodaf medyant uyg kyuoeth i'th law.\" Ac yn hynny ny doethant wy yng kyuyl y llys, namyn trigyaw y gylchaw y wlat yny aeth guahard udunt ar eu bwyt a'u llyn.",
          e: "\"Well,\" he said, \"what I can do, I will do. I will make amends to you first, and after my amends to you I will look to my own. And you,\" he said, \"I will take as my wife, and I will put the authority over my realm into your hands.\" And meanwhile the two did not come near the court, but stayed out on the circuit of the land, until they were forbidden their food and their drink.",
          n: "Math's response is the moral counterweight to the whole branch. Before any thought of punishment, he turns to the victim: <em>I will make amends to you first</em> — and the amends is to <strong>marry Goewin and give her authority over the kingdom</strong>, raising the wronged foot-holder to queen. It is a remarkable act in a medieval text: the king repairs the woman's broken honour by sharing his own power with her, and only then turns to the offenders. The brothers, knowing what waits, keep to the open country — until Math cuts off their food and drink and forces them in." },

        { w: "Yn gyntaf ny doethant yn y gyuyl ef; yna y doethant attaw. \"Arglwyd,\" heb wynt, \"dyd da it.\" \"Ie,\" heb ynteu, \"ae y wneuthur iawn ymi y doethawch chwi?\" \"Arglwyd, i'th ewyllus yd ydym.\" \"Bei uy ewyllus, ny chollwn o wyr ac arueu a golleis; uyg kywilyd ny ellwch chwi y dalu ym, heb angheu Pryderi. A chan doethawch y'm ewyllus, mi a dechreuaf boen arnawch.\"",
          e: "At first they did not come into his presence; then they came to him. \"Lord,\" they said, \"good day to you.\" \"Well,\" he said, \"is it to make me amends that you have come?\" \"Lord, we are at your will.\" \"Had it been my will, I would not have lost the men and the arms I have lost; you cannot pay me for my shame, let alone for the death of Pryderi. But since you have come to my will, I will begin your punishment.\"",
          n: "Math names the full bill — the dead men, the lost arms, his own shame, and, set above all the rest, <em>the death of Pryderi</em>. The war Gwydion manufactured as a private favour has cost a king of Britain his life, and Math reckons that the heaviest charge of all. There is no amends that can pay it; what is left is punishment, and Math, the greater magician, will fit it to the crime." },

        { w: "Ac yna y kymerth y hutlath, ac y trewis Giluaethwy yny uyd yn ewic; ac achub y llall yn gyflym — kyt mynhei dianc nys gallei — a'y taraw a'r un hutlath yny uyd yn garw. \"Kanys ywch yn rwymedigaeth, mi a wnaf ywch gerdet y gyt, a'ch bot yn gymaredic ac yn un anyan a'r gwyduilot yd ywch yn eu rith; ac yn yr amser y bo etiued udunt wy, y uot ywchwitheu. A blwydyn y hediw dowch yma attaf i.\"",
          e: "And then he took the wand, and struck Gilfaethwy until he became a hind; and he seized the other quickly — though he wished to escape, he could not — and struck him with the same wand until he became a stag. \"Since you are bound together, I will make you go together, and be coupled, and be of one nature with the wild beasts whose shape you wear; and whenever they have offspring, so shall you. And a year from today, come here to me.\"",
          n: "The punishment is exquisitely, terribly fitted to the crime. The wand (<em>hudlath</em>) — Math's, the same instrument of transformation that runs through the branch — turns the brothers into a <strong>hind and a stag</strong>, and binds them to <em>be of one nature</em> with the beasts they wear: not merely to look like deer but to live and breed as deer. A sexual violation is answered by enforced coupling and the shame of bearing young; and each year, as we will see, the wand swaps which brother is the female, so that each in turn must conceive and carry the other's child. Math's magic effortlessly masters Gwydion's — the trickster who conjured horses from nothing is himself reshaped with a touch." },

        { w: "Ym penn y ulwydyn, o'r un dyd, llyma y clywei odorun adan paret yr ystauell, a chyuarthua cwn y llys am penn y godorun. \"Edrych beth yssyd allan.\" \"Arglwyd, mae yna garw, ac ewic, ac elein gryf gyt ac wynt.\" Kyuodi a oruc ynteu a dyuot allan; a dyrchauael y hutlath. \"Yr hwnn a uu o honawch yn ewic yrllyned, bit uaed coet yleni; a'r hwnn a uu garw, bit hwch goet eleni.\" Ac eu taraw a'r hutlath. \"Y mab hagen a gymeraf i, ac a baraf y ueithryn a'y uedydyaw.\" Sef enw a dodet arnaw, Hydwn.",
          e: "At the year's end, on the same day, he heard a commotion under the wall of the chamber, and the court's dogs baying at the commotion. \"See what is outside.\" \"Lord, there is a stag there, and a hind, and a strong young fawn with them.\" He rose and went out, and lifted the wand. \"The one of you who was a hind last year, be a wild boar this year; and the one who was a stag, be a wild sow.\" And he struck them with the wand. \"The young one, though — I will take him, and have him fostered and baptised.\" And the name given to him was Hyddwn.",
          n: "A year on, the deer come back with a <strong>fawn</strong> — proof the sentence has been served — and Math takes the child to be reared as his own, christening him Hyddwn (\"little stag,\" from <em>hydd</em>). Then he reverses the brothers' sexes for the next year: the one who bore the fawn becomes a boar, the one who sired it a sow. The point is precise and merciless — over three years <em>each</em> brother will be the mother in turn. The offspring, innocent, are gathered up and named for their shapes; the punishment falls only on the guilty." },

        { w: "Ym penn y ulwydyn, llyma y clywyn kyuarthua cwn dan paret yr ystauell, a dygyuor y llys am eu penn. Kyuodi a oruc a mynet allan; a phan daw, baed coet, a hwch goet, a chrenllwdyn da gyt ac wynt, a breisc oed yn yr oet oed arnaw. \"Hwnn a gymeraf i attaf, ac a baraf y uedydyaw\" — a'y daraw a'r hutlath yny uyd yn uab braswineu telediw. Sef enw a dodet arnaw, Hychdwn. \"A chwitheu, yr un a uu baed coet yrllyned, bit bleidast yleni; a'r hwn a uu hwch goet, bit uleid yleni.\" Ac eu taraw a'r hutlath, yny uydant uleid a bleidast.",
          e: "At the year's end, they heard the dogs baying under the chamber wall, and the court gathering about them. He rose and went out; and when he came, there was a wild boar, and a wild sow, and a fine well-grown young pig with them, big for its age. \"This one I will take to me, and have baptised\" — and he struck it with the wand until it became a fine, well-made boy. The name given to him was Hychdwn. \"And you — the one who was a boar last year, be a she-wolf this year; and the one who was a sow, be a wolf.\" And he struck them with the wand, until they became a wolf and a she-wolf.",
          n: "The second year, the second beast-son: <strong>Hychdwn</strong> (\"little pig,\" from <em>hwch</em>), taken and made human like his brother. And the sexes turn again — boar to she-wolf, sow to wolf — so the brother who was male last year is female this year. The relentless symmetry is the punishment's whole design: shame shared exactly, and a year of motherhood forced on each in turn. Three wild kinds — deer, swine, wolves — the order running from the gentlest game to the fiercest predator." },

        { w: "Yr un dyd ym penn y ulwydyn, llyma y clywei dygyuor a chyuarthua dan paret yr ystauell. Ynteu a gyuodes allan, a phan daw, llyma y guelei bleid, a bleidast, a chrubothon cryf gyt ac wynt. \"Hwnn a gymeraf i, ac a baraf y uedydyaw, ac y mae y enw yn parawt: sef yw hwnnw, Bleidwn. Y tri meib yssyd y chwi, a'r tri hynny ynt: <em>Tri meib Giluaethwy enwir, / Tri chenryssedat kywir: / Bleidwn, Hydwn, Hychdwn Hir.</em>\" Ac ar hynny, yn eu taraw yll deu a'r hutlath yny uydant yn eu cnawt eu hun. \"A wyr,\" heb ef, \"o gwnaethawch gam ymi, digawn y buawch ym poen, a chywilyd mawr a gawssawch: bot plant o bob un o honawch o'y gilyd. Perwch enneint y'r gwyr, a golchi eu penneu, ac eu kyweiraw.\"",
          e: "On the same day at the year's end, he heard a tumult and baying under the chamber wall. He rose and went out, and there he saw a wolf, and a she-wolf, and a strong wolf-cub with them. \"This one I will take, and have baptised, and his name is ready: it is Bleiddwn. You have three sons, and these are the three: <em>Three sons of false Gilfaethwy, / three champions true: / Bleiddwn, Hyddwn, Hychdwn the Tall.</em>\" And with that he struck the two of them with the wand, until they were in their own flesh again. \"Men,\" he said, \"if you did me wrong, you have been long enough in pain, and great shame you have had — that each of you has borne the other a child. Have a bath made for the men, and their heads washed, and them made ready.\"",
          n: "The third year brings <strong>Bleiddwn</strong> (\"little wolf,\" from <em>blaidd</em>), and the verse that fixes the three beast-sons in memory — <em>Tri meib Gilfaethwy enwir</em>, \"the three sons of false Gilfaethwy\" — one of the embedded <em>englynion</em> the prose tradition uses to lend a tale the authority of remembered verse. Then the sentence ends. Math's judgement is, in the end, measured: three years, the shame of each having borne the other's child, and no more. He restores them to human shape and at once calls for baths and clean clothes — the ritual of bringing the outcast back into the human, courtly world. The greater magician has punished, and now reconciles; he will need Gwydion again before the next page is out." },
      ],
    },

    {
      title: "III. The foot-holder test, and the births of Dylan and the hidden child",
      segments: [
        { w: "Guedy ymgyweiraw o honunt, attaw ef y kyrchyssant. \"A wyr,\" heb ef, \"tangneued a gawssawch, a cherennyd a geffwch; a rodwch im kynghor pa uorwyn a geisswyf.\" \"Arglwyd,\" heb y Gwydyon uab Dôn, \"hawd yw dy gynghori: Aranrot uerch Dôn, dy nith, uerch dy chwaer.\"",
          e: "When they had made themselves ready, they came to him. \"Men,\" he said, \"you have had peace, and you shall have friendship; now give me counsel — what maiden shall I seek?\" \"Lord,\" said Gwydion son of Dôn, \"that is easy to advise: Aranrhod daughter of Dôn, your niece, your sister's daughter.\"",
          n: "Reconciled and washed clean, the brothers are at once back in counsel — and Gwydion, untroubled, proposes the family's own: <strong>Aranrhod daughter of Dôn</strong>, his sister and Math's niece, to be the new virgin foot-holder. The children of Dôn keep the sacral office in the kindred. Aranrhod (\"silver wheel\") is herself a figure of the old myth — her name survives in <em>Caer Arianrhod</em>, a Welsh name for the Corona Borealis — and the scene that follows will turn her into the branch's other great antagonist, the mother who curses her own son." },

        { w: "Honno a gyrchwyt attaw. Y uorwyn a doeth ymywn. \"A uorwyn,\" heb ef, \"a wyt uorwyn di?\" \"Ny wnn i amgen no'm bot.\" Yna y kymerth ynteu yr hutlath a'y chamu. \"Cama di dros honn,\" heb ef, \"ac ot wyt uorwyn, mi a'th adnabydaf.\" Yna y camawd hitheu dros yr hutlath; ac ar y cam hwnnw, adaw mab brasuelyn mawr a oruc.",
          e: "She was sent for, and the maiden came in. \"Maiden,\" he said, \"are you a virgin?\" \"I know no otherwise than that I am.\" Then he took the wand and bent it. \"Step over this,\" he said, \"and if you are a virgin, I shall know it.\" So she stepped over the wand; and at that step, she dropped a fine large yellow-haired boy.",
          n: "Math's virginity-test is pure folk-magic: step over the bent <strong>wand</strong> (the <em>hudlath</em> again), and the truth will out. Aranrhod's careful answer — <em>I know no otherwise than that I am</em> — is no simple lie; it hints she does not herself fully know what is in her. The test forces the hidden into the open in the most literal way possible: she steps over, and a child is born on the spot. The supernatural, instantaneous birth — and the second birth that follows — marks Aranrhod as a figure of the old mythic stratum, where conception and birth keep their own uncanny rules." },

        { w: "Sef a wnaeth y mab, dodi diaspat uchel. Yn ol diaspat y mab, kyrchu y drws a oruc hi, ac ar hynny adaw y ryw bethan o honei; a chyn cael o neb guelet yr eil olwc arnaw, Gwydyon a'y kymerth, ac a droes llen o bali yn y gylch, ac a'e cudyawd y mywn llaw gist is traet y wely.",
          e: "The boy gave a loud cry. And at the boy's cry, she made for the door — and as she went, she dropped some small thing; and before anyone could get a second look at it, Gwydion took it, and wrapped a sheet of brocade about it, and hid it in a little chest at the foot of his bed.",
          n: "The second birth is the hinge of the whole branch — and it is barely seen. As Aranrhod flees in shame, she drops <em>some small thing</em>, a formless scrap of life; Gwydion snatches it up before anyone can look, wraps it, and hides it in a chest at the foot of his bed. What he is doing is a kind of second gestation: he will incubate and rear this half-born thing himself. The intensity of Gwydion's care for the child — and the secrecy of its origin — has led many readers to suspect Gwydion is himself the father; the tale never says, and that silence is part of its strangeness." },

        { w: "\"Ie,\" heb Uath, \"mi a baraf uedydyaw hwn\" — wrth y mab brasuelyn — \"a'r enw a baraf yw Dylan.\" Bedydyaw y mab a wnaethpwyt, ac y gyt ac y bedydywyt, y mor a gyrchwys; ac yn y lle, annyan y mor a gauas, a chystal y nouyei a'r pysc goreu yn y mor. Ac o achaws hynny y gelwit Dylan Eil Ton; ny thorres tonn adanaw eiryoet. A'r ergyt y doeth y angheu o honaw, a uyrywys Gouannon y ewythyr; a hwnnw a uu trydyd anuat ergyt.",
          e: "\"Well,\" said Math, \"I will have this one baptised\" — meaning the yellow-haired boy — \"and the name I will give him is Dylan.\" The boy was baptised, and the moment he was baptised, he made for the sea; and at once he took on the nature of the sea, and swam as well as the best fish in it. For that reason he was called Dylan Eil Ton — \"Dylan, son of the Wave\"; never did a wave break beneath him. And the blow that brought about his death, his uncle Gofannon struck; and that was one of the Three Ill-Fated Blows.",
          n: "The first-born goes straight back to the element he belongs to. <strong>Dylan Eil Ton</strong> (\"Dylan, Second-Wave\" or \"son of the wave\") is a sea-divinity in all but name: baptised and instantly gone to the sea, swimming like a fish, the waves never breaking under him. His death is one of the Mabinogi's most haunting loose fragments — killed by a blow from his uncle <strong>Gofannon</strong> (the smith-god, the Welsh cousin of the Irish Goibniu), remembered in the Triads as one of the <em>Tri Anfad Ergyd</em>, the Three Ill-Fated Blows of Britain. The tale gives him a sentence and lets him go; the branch's real business is the other child, the one in the chest, who has no name yet at all." },
      ],
    },

    {
      title: "IV. Aranrhod's three curses, and how Gwydion broke two",
      segments: [
        { w: "Ual yd oed Wydyon diwarnawt yn y wely yn deffroi, ef a glywei diaspat yn y gist is y draet; kyny bei uchel hi, kyuuch oed ac y kigleu ef. Kyuodi yn gyflym ac agori y gist a oruc; ac ual y hegyr, ef a welei uab bychan yn rwyuaw y ureicheu o blyc y llen. Ef a gymerth y mab, ac a'y dug y dref lle y gwydat bot gwreic a bronneu genti, ac ymobryn a wnaeth y ueithryn y mab. Yn oet y ulwydyn, breisc oed bei dwy ulwyd; a'r eil ulwydyn mab mawr oed, yn gallu e hun kyrchu y llys; ac yny uu pedeirblwyd, hof oed y uab wyth mlwyd uot yn gynureisget ac ef.",
          e: "One day, as Gwydion lay in bed waking, he heard a cry from the chest at his feet; though it was not loud, it was loud enough that he caught it. He rose quickly and opened the chest; and as it opened, he saw a little boy waving his arms free of the wrappings, and pushing the sheet aside. He took the boy and carried him to a place where he knew there was a woman with milk, and arranged for the boy to be nursed. By the end of a year, he was big enough to be two; and by the second year he was a big boy, able to go to the court by himself; and by the time he was four, he was as big as a boy of eight.",
          n: "The thing in the chest is a child after all — and one who grows at twice a natural rate, like the year-old heroes of the wider tradition. The <strong>prodigiously fast-growing boy</strong> is a deep folktale and mythic pattern (the same uncanny acceleration marks Pryderi in the First Branch and Lleu's Irish cousin Lugh). Gwydion's tender management — finding a wet-nurse, watching him to court — confirms his role as the child's true foster-father; the whole rest of the branch is Gwydion's long campaign to give this boy the social existence his mother will try three times to deny him." },

        { w: "Diwyrnawt ef a gerdawd yn ol Gwydyon, ac y kyrchawd Gwydyon Caer Aranrot a'r mab gyt ac ef. Aranrot a gyuodes yn y erbyn, a chyuarch guell idaw. \"Pa uab yssyd yth ol di?\" heb hi. \"Y mab hwnn, mab y ti yw,\" heb ef. \"Oy a wr, pa beth a doeth arnat, uyg kywilydaw i a dilyt uyg kywilyd, a'y gadw yn gyhyt a hynn?\" \"Ony byd arnat ti gywilyd uwy no meithryn o honaf i uab kystal a hwnn, ys bychan a beth uyd dy gywilyd.\" \"Pwy enw dy uab?\" \"Dioer, nit oes arnaw un enw etwa.\" \"Ie,\" heb hi, \"mi a dynghaf dynghet idaw, na chaffo enw yny caffo y genhyf i.\" \"Direit wreic wyt,\" heb ef, \"a'r mab a geiff enw, kyt boet drwc genhyt. A thitheu, yr awar yssyd arnat am na'th elwir yn uorwyn, ni'th elwir bellach byth yn uorwyn.\"",
          e: "One day the boy followed Gwydion, and Gwydion made for Caer Aranrhod, the boy with him. Aranrhod rose to meet him and greeted him. \"What boy is this following you?\" she said. \"This boy is a son of yours,\" he said. \"Oh, man, what has come over you — to shame me, and to keep my shame going, and hold on to it as long as this?\" \"If you have no greater shame than that I have fostered a fine boy like this, your shame is a small thing.\" \"What is your boy's name?\" \"Truly, he has no name yet.\" \"Well,\" she said, \"I lay this destiny on him: that he shall get no name until he gets one from me.\" \"A wicked woman you are,\" he said; \"and the boy shall get a name, however ill it pleases you. And you — for the grief you have, that you are not called a maiden — you shall never be called a maiden again.\"",
          n: "Here begins the duel of curses that is the spine of the movement. Aranrhod, confronted with the living evidence of her shame, retaliates by laying a <em>tynged</em> (destiny-binding, the Welsh <em>geis</em>) on her own son: <strong>he shall have no name unless she gives it</strong>. A name is the first thing that makes a person a person, and in Welsh law a fatherless, unnamed boy has no standing at all — Aranrhod is trying to deny her son a social existence. Gwydion answers with a counter-curse of his own (she'll be called \"maiden\" no more) and a vow: the boy <em>will</em> be named. The three curses to come — name, arms, wife — are exactly the three thresholds of a man's social life, and Gwydion will trick his sister across two of them." },

        { w: "Ac ar hynny kerdet ymeith drwy y lit, a chyrchu Caer Dathyl. A thrannoeth kymryt y uab gyt ac ef, a mynet y orymdeith gan lann y weilgi; ac yn y lle y guelas delysc a morwyal, hudaw llong a oruc; ac o'r gwymon a'r delysc hudaw cordwal a oruc, a hynny lawer, a'y vrithaw hyt na welsei neb ledyr degach. Ac yna kyweiraw hwyl ar y llong, a dyuot y drws porth Caer Aranrot, ef a'r mab yn y llong; ac yna dechreu llunyaw esgidyeu a'u gwniaw.",
          e: "And with that he went off in his anger, and made for Caer Dathyl. Next day he took the boy with him and went walking along the shore of the sea; and where he saw dulse and sea-girdle weed, he conjured a ship; and out of the seaweed and the dulse he conjured cordovan leather, plenty of it, and stamped it so that no one ever saw finer leather. And then he set a sail on the ship, and came to the gate of Caer Aranrhod, he and the boy in the ship; and they began to shape shoes and to stitch them.",
          n: "Gwydion's method is always the same — illusion as leverage — and his disguise here is a quiet, deliberate echo of the Third Branch. He conjures a ship and fine <em>cordwal</em> (cordovan) leather out of seaweed and sets up as a <strong>shoemaker</strong> at Aranrhod's gate. This is the same trade, and shortly the same Triadic title (\"one of the Three Gold-shoemakers\"), that <strong>Manawydan</strong> takes up in his English exile — the cobbler's bench as the disguise of a magician-prince. The two Branches share the motif almost as a signature." },

        { w: "Pan wybu eu harganuot o'r gaer, dwyn eu heilyw e hun a orugant, a dodi eilyw arall arnunt. \"Pa dynyon yssyd yn y llong?\" heb yr Aranrot. \"Crydyon,\" heb wy. Anuon messur y throet a oruc, ac archu gwneuthur esgidyeu; ynteu a'u lunywys yn uwy, ac yna yn llei no'y throet, yny doeth hi e hun hyt y llong. A phan doeth, yd oed ef yn llunyaw, a'r mab yn gwniaw. Ac ar hynny llyma y dryw yn seuyll ar uwrd y llong; sef a wnaeth y mab, y uwrw a'y uedru y rwng giewyn y esgeir a'r ascwrn. Chwerthin a wnaeth hitheu. \"Dioer,\" heb hi, \"ys llaw gyffes y medrwys y lleu ef.\" \"Ie,\" heb ynteu, \"aniolwch Duw it — neur gauas ef enw; a da digawn yw y enw: Lleu Llaw Gyffes yw bellach.\"",
          e: "When they knew they were spotted from the fort, they put off their own appearance and took on another. \"What men are in the ship?\" said Aranrhod. \"Shoemakers,\" they said. She sent the measure of her foot, and asked for shoes to be made; but he made them too large, and then too small, until she came down to the ship herself. And when she came, he was shaping and the boy was stitching. And then, behold, a wren came and settled on the ship's deck; and the boy threw at it and struck it between the sinew of its leg and the bone. She laughed. \"Truly,\" she said, \"the fair one has struck it with a skilful hand.\" \"Yes,\" he said — \"and no thanks to God for you: now he has got a name. And a good enough name it is: Lleu Llaw Gyffes he is from now on.\"",
          n: "The trap is sprung on a pun. Gwydion makes shoes that never fit so that Aranrhod must come in person; then the boy strikes a <strong>wren</strong> with a single perfect shot, and Aranrhod, delighted, exclaims that the fair one (<em>lleu</em>) struck it with a deft hand (<em>llaw gyffes</em>) — and Gwydion instantly nails the words to the boy as a name: <strong>Lleu Llaw Gyffes</strong>, \"the Bright/Fair One of the Skilful Hand.\" She has named her own son after all, tricked into it. <strong>Lleu</strong> is the Welsh reflex of the great pan-Celtic god <em>Lugus</em> — Irish <em>Lugh</em>, Gaulish <em>Lugus</em> — and like many heroes he earns his name by a feat. The naming-by-deed is the oldest kind of name." },

        { w: "Ac yna difflannu y gueith yn delysc ac yn wymon; a'r gueith ny chanlynwys ef hwy no hynny; ac o'r achaws hwnnw y gelwit ef yn drydyd eur gryd. \"Dioer,\" heb hitheu, \"ni henbydy well di o uot yn drwc wrthyf i.\" \"Ny buum drwc i etwa wrthyt ti,\" heb ef. Ac yna y rydhawd ef y uab yn y bryt e hun, a chymryt y furyf e hun. \"Minheu a dynghaf dynghet y'r mab hwnn,\" heb hi, \"na chaffo arueu byth yny gwiscof i ymdanaw.\" \"Y rof a Duw,\" heb ef, \"o'th direidi di y mae hynny; ac ef a geiff arueu.\"",
          e: "And then the work vanished into dulse and seaweed; and he carried the craft on no longer than that; and for that reason he was called one of the Three Gold-shoemakers. \"Truly,\" she said, \"you will be none the better for being unkind to me.\" \"I have done you no unkindness yet,\" he said. And then he released the boy into his own shape, and took his own form again. \"I lay this destiny on this boy,\" she said: \"that he shall never bear arms until I myself arm him.\" \"Between me and God,\" he said, \"that comes of your own wickedness; and he shall have arms.\"",
          n: "The shoes melt back into seaweed — Gwydion's illusions never outlast their hour — and the branch pauses to tag him, in passing, as one of the <strong>Three Gold-shoemakers</strong> (<em>tri eurgrydd</em>) of the Island of Britain, the very Triad that names Manawydan: the two great Mabinogi enchanters share a title and a trade. Beaten on the name, Aranrhod at once lays her <strong>second curse</strong> — no <em>arms</em>, no warrior's manhood, unless she herself arms him — and Gwydion at once vows to break it too. Name, then arms: she is denying her son each rung of becoming a man, and he is climbing them anyway." },

        { w: "Wynt a doethant parth a Dinas Dinllef; ac yna meithryn Lleu Llaw Gyffes yny allwys uarchogaeth pob march, ac yny oed gwbyl o bryt a thwf a meint. Gwydyon a adnabu y uot yn kymryt dihirwch o eisseu meirch ac arueu, a'y alw attaw. \"A was, ni a awn, ui a thi, y neges auory.\" Trannoeth y kymeryssant yr aruordir parth a Chaer Aranrot, ac amgenu eu pryt, a chyrchu y porth yn rith deu uard. Gellwng y mywn a wnaethpwyt, a diruawr leuenyd yn eu herbyn; a'r nos honno ymdidan a wnaeth hi a Gwydyon, kyuarwyd da.",
          e: "They went toward Dinas Dinlleu; and there Lleu Llaw Gyffes was reared until he could ride every horse, and was full-grown in form and stature and size. Gwydion saw that he was fretting for want of horses and arms, and called him to him. \"Lad, you and I will go on an errand tomorrow.\" Next morning they took the coast road toward Caer Aranrhod, and changed their appearance, and came to the gate in the guise of two bards. They were let in, and made greatly welcome; and that night Aranrhod talked with Gwydion — a fine storyteller.",
          n: "Lleu grows to manhood at <strong>Dinas Dinlleu</strong> (\"the fortress of Lleu,\" a real hillfort on the Arfon coast that still bears his name — another onomastic anchor), and chafes, as a young noble must, for the horses and arms his mother's curse denies him. Gwydion's plan for the second curse reprises the first: disguise (now as two bards — his most natural cover), a welcome at Caer Aranrhod, and a long evening's storytelling to lull the household before the morning's trick." },

        { w: "Hir bylgeint Gwydyon a gyuodes, ac y gelwis ef y hut a'y allu attaw. Erbyn dyd, yd oed gyniweir ac utkyrn a lleuein yn y wlat; a phan oed y dyd yn dyuot, wynt a glywynt taraw drws yr ystauell, ac Aranrot yn erchi agori. \"Lle drwc yd ym,\" heb hi; \"ni chawn welet llyw y weilgi gan pob llong ar dorr y gilyd, ac y maent yn kyrchu y tir.\" \"Nyt oes in gynghor onyt caeu y gaer arnam, a'y chynhal oreu a allom.\" Ac yna yd aeth hi yn ol arueu, a dwy uorwyn gyt a hi, ac arueu deu wr gantunt; a hi e hun a wiscwys am Leu yn gwbyl. \"A derw wiscaw am y gwryanc?\" \"Deryw.\" \"Diodwn ninheu yn arueu weithon; nyt reit ynn wrthunt.\" \"Och! Llyna y llynghes yng kylch y ty!\" \"A wreic, nyt oes yna un llynghes.\" \"Pa ryw dygyuor a uu, ynteu?\" \"Dygyuor y dorri dy dynghetuen am dy uab, ac y geissaw arueu idaw; ac neur gauas arueu, heb y diolwch y ti.\"",
          e: "Long before dawn Gwydion rose, and called his magic and his power to him. By daybreak there was a din of war-horns and shouting through the land; and as the day came, they heard a knock at the chamber door, and Aranrhod asking to be let in. \"We are in an evil place,\" she said; \"I can scarcely see the colour of the sea for the ships, hull against hull, and they are making for the shore.\" \"There is nothing for us but to shut the fort and hold it as best we can.\" And then she went for arms, two maidens with her, and arms for two men with them; and she herself armed Lleu, fully. \"Is the young man fully armed?\" \"He is.\" \"Then let us take our own arms off now; we have no need of them.\" \"Oh! Look — the fleet, all about the house!\" \"Woman, there is no fleet there.\" \"What was all the mustering, then?\" \"A mustering to break your destiny upon your son, and to get him arms; and now he has got arms — and no thanks to you.\"",
          n: "The second trick is the first writ large: where Gwydion once conjured a wren-shot's worth of pretext, here he conjures a whole <strong>besieging fleet</strong> out of nothing — the same illusion-magic (<em>hud</em>) that raised the phantom horses of Movement I — so that Aranrhod, in terror for her own fort, arms Lleu with her own hands before she thinks. The instant the arming is done, Gwydion lets the fleet vanish and tells her plainly what she has done. Two curses broken, two by the same weapon: his sister's own fear and pride, turned against her bindings." },

        { w: "\"E rof a Duw,\" heb hitheu, \"gwr drwc wyt ti; a llawer mab a allei colli y eneit am y dygyuor a bereisti yn y cantref hwnn hediw. A mi a dynghaf dynghet y'r mab hwnn: na chaffo wreic uyth o'r genedyl yssyd ar y dayar honn yr awr honn.\" \"Direitwreic uuost eiroet,\" heb ynteu, \"ac ny dylyei neb uot yn borth it; a gwreic a geiff ef ual kynt.\" Hwynteu a doethant at Uath uab Mathonwy, a chwynaw yn luttaf rac Aranrot, a menegi ual y paryssei yr arueu idaw oll. \"Ie,\" heb y Math, \"keisswn ninheu, ui a thi, o'n hut a'n lledrith, hudaw gwreic idaw o'r blodeu.\"",
          e: "\"Between me and God,\" she said, \"you are a wicked man; and many a boy might have lost his life over the mustering you raised in this cantref today. And I lay this destiny on this boy: that he shall never have a wife of any race that is now on this earth.\" \"A wicked woman you have always been,\" he said, \"and no one ought to help you; and he shall have a wife, as before.\" And they went to Math son of Mathonwy, and complained most bitterly of Aranrhod, and told how she had made him arm Lleu after all. \"Well,\" said Math, \"let us, you and I, by our magic and our enchantment, conjure him a wife out of flowers.\"",
          n: "Beaten twice, Aranrhod lays the curse she thinks unbreakable — Lleu shall never have a <strong>wife of any race now on earth</strong> — and Gwydion meets it with the most famous enchantment in Welsh literature. He turns to Math, the elder magician, and the two of them resolve to defeat the wording by making a woman who is of <em>no</em> earthly race at all: a wife <strong>conjured out of flowers</strong>. That bride is Blodeuwedd, and her making — and her betrayal — are the subject of the next movement. Aranrhod's three curses have given the branch its deepest theme: that a thing made or compelled against nature carries its own undoing inside it." },
      ],
    },

    {
      title: "V. Blodeuwedd the flower-wife, the betrayal, and the eagle",
      segments: [
        { w: "Ac yna y kymeryssant wy blodeu y deri, a blodeu y banadyl, a blodeu yr erwein, ac o'r rei hynny aswynaw yr un uorwyn deccaf a thelediwaf a welas dyn eiroet; a'y bedydyaw o'r bedyd a wneynt yna, a dodi Blodeued arnei.",
          e: "And then they took the flowers of the oak, and the flowers of the broom, and the flowers of the meadowsweet, and out of those they conjured the fairest and most graceful maiden that anyone ever saw; and they baptised her with the baptism they used in those days, and gave her the name Blodeuwedd.",
          n: "The most celebrated enchantment in Welsh literature, and the branch's deepest image. To beat Aranrhod's wording — no wife <em>of any race on earth</em> — Math and Gwydion make a wife of no race at all: <strong>Blodeuwedd</strong> (\"Flower-Face,\" <em>blodau</em> + <em>gwedd</em>), conjured from the blossoms of <strong>oak, broom and meadowsweet</strong>. She is beautiful and entirely without kin, without human nature, without any loyalty she was not made to have — and the rest of the movement is the slow proof that a creature compelled into being for one man's convenience owes him nothing. The flower-bride who becomes a faithless wife has haunted later writers from the Triads to Saunders Lewis to Alan Garner's <em>The Owl Service</em>." },

        { w: "Gwedy kyscu o honunt y gyt, \"Nyt hawd,\" heb y Gwydyon, \"y wr heb gyuoeth idaw ymdeith.\" \"Mi a rodaf idaw,\" heb y Math, \"yr un cantref goreu y was ieuanc y gael.\" \"Pa gantref yw hwnnw?\" \"Cantref Dinodig\" — a hwnnw a elwir yr awr honn Eifyonyd ac Ardudwy. Sef lle y kyuanhedwys lys idaw, yn y lle a elwir Mur Castell, yg gwrthtir Ardudwy; ac yna y gwledychwys, a phawb a uu uodlawn idaw ac y arglwydiaeth.",
          e: "After they had slept together, \"It is not easy,\" said Gwydion, \"for a man to keep himself with no domain of his own.\" \"I will give him,\" said Math, \"the best cantref for a young man to have.\" \"What cantref is that?\" \"The cantref of Dinoding\" — that is now called Eifionydd and Ardudwy. And the place where he made his court was the one called Mur Castell, in the uplands of Ardudwy; and there he ruled, and everyone was well content with him and his lordship.",
          n: "Lleu is now fully a man — named, armed, and married, all three curses broken — and Math completes him with a kingdom: the cantref of <strong>Dinoding</strong>, and a court at <strong>Mur Castell</strong> (the real Roman fort Tomen y Mur, in the Ardudwy uplands — another of the branch's exact topographic anchors). For a paragraph the tale rests in fulfilment: the made wife, the won land, the contented people. It is the calm the betrayal needs, set as carefully as the wedding-feast at the start of Branwen — happiness built up to be knocked down." },

        { w: "Treigylgueith kyrchu a wnaeth ef parth a Chaer Dathyl e ymwelet a Math. Y dyd yd aeth ef, troi o uywn y llys a wnaeth hi; a hi a glywei lef corn, ac yn ol llef y corn llyma hyd blin yn mynet heibaw, a chwn a chynydyon yn y ol, ac yn ol y rei hynny bagat o wyr ar draet. \"Gronw Pebyr yw hwnn, arglwyd Penllyn,\" heb y gwas. Gwedy lad yr hyd, y bu Gronw yny wascawd y nos arnaw, a dyuot heb borth y llys. \"Ni a gawn yn goganu,\" heb hi, \"o'e adu y wlat arall onys gwahodwn.\" Yna y doeth ef y'r llys, ac y doeth hitheu y'w graessawu. Ac yr awr yd edrych arnaw, nyt oed gyueir arnei ny bei yn llawn o'e garyat; ac ynteu a synywys arnei hitheu. Ny allwys ymgelu o'e uot yn y charu, a menegi idi a wnaeth; a hitheu a gymerth diruawr lewenyd. A'r nos honno kyscu y gyt a wnaethant.",
          e: "One time he made for Caer Dathyl, to visit Math. The day he went, she was wandering about the court; and she heard the note of a horn, and after the horn's note, behold, a spent stag going by, with dogs and huntsmen after it, and after them a band of men on foot. \"That is Gronw Pebr, lord of Penllyn,\" said a servant. When the stag was killed, night came on Gronw before he could leave, and he came up to the court gate. \"We shall be reproached,\" she said, \"if we let so great a man go to another land without inviting him in.\" So he came to the court, and she came to welcome him; and from the moment she looked at him, there was no part of her that was not filled with love of him; and he looked on her, and the same thought came to him as had come to her. He could not hide that he loved her, and told her so; and she took great joy of it. And that night they slept together.",
          n: "The betrayal arrives, as so often in this material, on the back of a <strong>hunt</strong> — the same plot-engine (Thompson N777, adventure-follows-the-hunt) that opens <em>Pwyll</em> and turns the trap in <em>Manawydan</em>. With Lleu away visiting Math, a stag-chase brings <strong>Gronw Pebr</strong>, lord of Penllyn, to the gate, and courtesy — the obligation to house a great man overnight — does the rest. The love is instant and total on both sides; the tale does not moralise it, and there is a real pathos in Blodeuwedd, a being made for one man, discovering for herself a feeling no one conjured. But the consequence will be murder." },

        { w: "Drannoeth arouun a wnaeth ef e ymdeith. \"Nyt ey y wrthyf i heno,\" heb hi. Teir nos y buant y gyt; ac yna y bu yr ymgynghor pa furu y kehynt uot yg kyt. \"Nyt oes it gynghor,\" heb ef, \"onyt keissaw y gantaw wybot pa furu y del y angheu, a hynny yn rith ymgeled amdanaw.\" Y nos honno, pan dywot ef parabyl wrthi, parabyl nys cauas. \"Pa derw it?\" heb ef. \"Goualu am dy angheu di yd wyf,\" heb hi, \"ot elut yn gynt no mi. A wney di yr Duw ac yrof, menegi pa furu y galler dy lad?\" \"Dywedaf yn llawen,\" heb ef. \"Nyt hawd uy llad o ergyt: reit oed uot blwydyn yn gwneuthur y par y'm byrhit ac ef, a heb gwneuthur dim o honaw namyn pan uythit ar yr aberth duw Sul. Ny ellir uy llad y mywn ty, ny ellir allan; ny ellir ar uarch, ny ellir ar uyn troet.\" \"Pa delw, ynteu?\" heb hi. \"Gwneuthur ennein im ar lan auon, a chromglwyt uch benn y gerwyn, a'y thoi yn didos; a dwyn bwch a'y dodi gyr llaw y gerwyn, a dodi o honof uinheu y neilltroet ar geuyn y bwch a'r llall ar emyl y gerwyn. Pwy bynnac a'm trewi yuelly, ef a wnay uy angheu.\"",
          e: "Next day he made to leave. \"You shall not go from me tonight,\" she said. Three nights they were together; and then they took counsel how they might be together always. \"There is no way for you,\" he said, \"but to learn from him how his death may come — and that under the guise of caring for him.\" That night, when Lleu spoke a word to her, he got no word in return. \"What ails you?\" he said. \"I am troubled about your death,\" she said, \"if you should go before me. Will you, for God's sake and mine, tell me how you can be killed?\" \"Gladly,\" he said. \"I am not easy to kill by a blow. The spear that is to strike me must be a year in the making, and no work done on it except during mass on Sundays. I cannot be killed inside a house, nor out of doors; I cannot be killed on horseback, nor on foot.\" \"How, then?\" she said. \"By making a bath for me on a riverbank, and a thatched frame over the tub, well roofed; and bringing a buck and setting it beside the tub; and my setting one foot on the buck's back and the other on the edge of the tub. Whoever should strike me so would bring about my death.\"",
          n: "Lleu's near-invulnerability is hedged by a classic <strong>\"neither–nor\" death-riddle</strong>: not in a house nor outside it, not on horseback nor on foot, by a spear a year in the making and worked only at the forbidden hour of Sunday mass. Such impossible, liminal conditions guard the deaths of gods and heroes across Indo-European myth (and the sacrilegious year-long spear marks the killing as a thing against God as well as nature). The cruel irony is that Lleu, named and armed against his mother's curses, is undone by the one social bond Gwydion could only counterfeit — a wife — who coaxes the secret out of him <em>in the guise of caring for him</em>. He tells her everything." },

        { w: "Nyt kynt y cauas hi yr ymadrawd, noc y hanuones at Gronw Pebyr. Gronw a lauurywys gueith y guayw, a'r un dyd ym penn y ulwydyn y bu barawt. Hitheu a beris kyweiraw y glwyt a'r ennein; a Gronw a aeth y gyscawt y brynn a elwir Brynn Kyuergyr, yglan Auon Gynuael. \"Ti a ey y'r ennein, Arglwyd?\" \"Af yn llawen.\" Ef a aeth y'r ennein, ac ymenneinaw; ac yna kyuodi, a dodi y neilltroet ar emyl y gerwyn a'r llall ar geuyn y bwch. Ynteu Gronw a gyuodes ar benn y neill glin, ac a'r guenwynwayw y uwrw, a'y uedru yn y ystlys, yny neita y paladyr o honaw, a thrigyaw y penn yndaw. Ac yna bwrw ehetuan o honaw ynteu yn rith eryr, a dodi garymleis anhygar; ac ny chahat y welet odyna. Yn gyn gyflymet ac yd aeth ef ymeith, y kyrchyssant wynteu y llys; a thrannoeth Gronw a wereskynnwys Ardudwy, ac a wledychwys yny oed yn y eidaw Ardudwy a Phenllyn.",
          e: "No sooner had she got the secret than she sent it to Gronw Pebr. Gronw set to work on the spear, and on the same day at the year's end it was ready. She had the frame and the bath made ready; and Gronw went to the shelter of the hill now called Bryn Cyfergyr, on the bank of the river Cynfael. \"Will you go into the bath, lord?\" \"Gladly.\" He went into the bath and bathed; and then he rose, and set one foot on the edge of the tub and the other on the back of the buck. And Gronw rose up on one knee, and cast the poisoned spear, and struck him in the side, so that the shaft sprang out of it and the head stayed in him. And then he flew up in the form of an eagle, and gave a horrible scream; and from then on he was not to be seen. As soon as he was gone, the two of them went to the court; and the next day Gronw conquered Ardudwy, and ruled until Ardudwy and Penllyn were his.",
          n: "The murder is worked exactly to the riddle: the riverbank, the thatched frame, the bath, the buck, the one-foot-on-each pose — Blodeuwedd stages the whole liminal tableau under the guise of an innocent demonstration, and Gronw, hidden behind Bryn Cyfergyr by the Cynfael (real places still bearing these names), casts the spear a year in the making. But Lleu does not die. He <strong>flies up as an eagle</strong> with a dreadful scream and is gone — for Lleu is the Welsh Lugus, a solar god in the bones of the story, and the wounded eagle in the high oak is one of the oldest images in the branch. Gronw takes the land and the wife; the wrong sits unrepaired, waiting for Gwydion." },

        { w: "Yna y chwedyl a aeth at Uath uab Mathonwy. Trymuryt a goueileint a gymerth Math yndaw, a mwy Wydyon noc ynteu lawer. \"Arglwyd,\" heb y Gwydyon, \"ny orffwyssaf uyth yny gaffwyf chwedleu y wrth uy nei.\" \"Duw a uo nerth it,\" heb y Math. Ac yna kychwynnu a wnaeth ef, a dechreu rodyaw racdaw — rodyaw Gwyned, a Phowys yn y theruyn; a gwedy rodyaw pob lle, ef a doeth y Aruon, ac a doeth y dy uab eillt ym Maynawr Bennard.",
          e: "Then the news came to Math son of Mathonwy. Heavy sorrow and grief took hold of Math, and far more of Gwydion than of him. \"Lord,\" said Gwydion, \"I shall never rest until I get tidings of my nephew.\" \"God be your strength,\" said Math. And then he set out, and began to wander on — wandering through Gwynedd, and the borders of Powys; and when he had wandered everywhere, he came to Arfon, and came to the house of a bondman in Maenor Bennardd.",
          n: "The grief that ends the movement measures the whole strange bond at the heart of the branch: Math sorrows, but <em>far more Gwydion than he</em> — the foster-father who incubated Lleu in a chest, tricked him a name, a sword and a wife, and now will not rest until he is found. Gwydion's restless search across Gwynedd and Powys opens the last movement: the trickster who began the tale by manufacturing a war for a selfish whim ends it on a long, selfless quest to undo a death and set the world right — the closest thing the branch has to redemption. The finding, and the reckoning, follow." },
      ],
    },

    {
      title: "VI. The finding of Lleu, and the reckoning",
      segments: [
        { w: "Diskynnu yn y ty a wnaeth, a thrigyaw yno y nos honno. Gwr y ty a'y dylwyth a doeth ymywn, ac yn diwethaf y doeth y meichat. \"A was,\" heb gwr y ty, \"a doeth dy hwch di y mywn heno?\" \"Doeth; yr awr honn y doeth at y moch.\" \"Pa ryw gerdet,\" heb y Gwydyon, \"yssyd ar yr hwch honno?\" \"Ban agorer y creu beunyd, yd a allan; ny cheir graf arnei, ac ny wybydir pa ford yd a, mwy no chyn elei yn y daear.\" \"A wney di yrof i,\" heb y Gwydyon, \"nat agorych y creu yny uwyf i yn y neillparth y'r creu y gyt a thi?\" \"Gwnaf yn llawen.\"",
          e: "He came down into the house, and stayed there that night. The man of the house and his household came in, and last of all came the swineherd. \"Lad,\" said the man of the house, \"did your sow come in tonight?\" \"She did; just now she came to the swine.\" \"What sort of going,\" said Gwydion, \"is on that sow?\" \"Whenever the sty is opened each day, she is off; no hold can be got on her, and no one knows which way she goes, any more than if she went into the earth.\" \"Will you do this for me,\" said Gwydion: \"not open the sty until I am beside it with you?\" \"Gladly.\"",
          n: "The finding turns, like so much in this branch, on an animal that knows more than the people do. The bondman's <strong>sow</strong> vanishes each morning by a road no one can follow — the beast-guide of folktale, who will lead the searcher to the hidden thing. Gwydion, who has read every other secret in the tale, here simply watches and follows; the great manipulator becomes, for once, a patient tracker." },

        { w: "Drannoeth y kyuodes y meichat, ac agori y creu. Y gyt ac y hagyr, hitheu a uwryawd neit allan, a cherdet yn braf; a Gwydyon a'y canlynwys, hyt y nant a elwir weithon Nantlleu, ac yna guastatau a phori a oruc. Gwydyon a doeth y dan y prenn, ac a edrychwys pa beth yd oed yr hwch yn y bori; ef a welei yr hwch yn pori kic pwdyr a chynron. Ac edrych ym blaen y prenn a oruc; a phan edrych, ef a welei eryr ym blaen y prenn; a phan ymyskytwei yr eryr, y syrthei y pryuet a'r kic pwdyr o honaw, a'r hwch yn yssu y rei hynny. Sef a wnaeth ynteu, medylyaw mae Lleu oed yr eryr.",
          e: "Next morning the swineherd rose and opened the sty. The moment it opened, she sprang out and went off at a great pace; and Gwydion followed her, as far as the brook now called Nantlleu, and there she slackened and grazed. Gwydion came under a tree, and looked at what the sow was feeding on; and he saw the sow feeding on rotten flesh and maggots. And he looked up to the top of the tree; and when he looked, he saw an eagle at the top of the tree; and whenever the eagle shook itself, the maggots and the rotten flesh fell from it, and the sow devoured them. And he thought to himself that the eagle was Lleu.",
          n: "The image is one of the most harrowing in the Mabinogi, and unforgettable: Lleu, transformed and dying, perched as a rotting <strong>eagle</strong> at the top of an oak by the brook ever after called <strong>Nantlleu</strong> (\"Lleu's brook\" — the onomastics run to the very end), his own flesh and maggots dropping to the sow below. It is the wounded god in the world-tree, half-dead between worlds — and Gwydion, reading the riddle of the sow's strange pasture, knows the bird at once. What follows is the branch's answer to all its enchantment: not a wand-stroke but a poem." },

        { w: "Sef a wnaeth ynteu, canu englyn: \"Dar a dyf y rwng deu lenn, / gordufrych awyr a glenn; / ony dywedaf i eu, / o flodeu Lleu ban yw hynn.\" Sef a wnaeth yr eryr, ymellwng yny oed yg kymherued y prenn. Canu englyn arall: \"Dar a dyf yn ard uaes, / nys gwlych glaw, mwy nys tawd gwres; / ugein angerd a borthes, / yn y blaen, Lleu Llaw Gyffes.\" Ymellwng idaw ynteu yny uyd yn y geing issaf. Canu englyn idaw yna: \"Dar a dyf dan anwaeret, / mirein modur yn y mywet; / ony dywedaf i eu, / ef dydaw Lleu y'm arfet.\" Ac y dygwydawd ynteu ar lin Gwydyon. Ac yna y trewis Gwydyon ef a'r hudlath, yny uyd yn y rith e hun. Ny welsei neb wr dremynt druanach noc a oed arnaw: nit oed dim onyt croen ac ascwrn.",
          e: "What Gwydion did was to sing an englyn: \"An oak grows between two lakes, / dark-shadowing sky and glen; / if I do not speak falsely, / this is from the flowers [the doom] of Lleu.\" At that, the eagle let itself down until it was in the middle of the tree. He sang another englyn: \"An oak grows on a high plain; / rain does not wet it, nor heat melt it; / twenty agonies it has borne; / in its top, Lleu Llaw Gyffes.\" It let itself down until it was on the lowest branch. Then he sang it this englyn: \"An oak grows on the slope, / the refuge of a fair lord; / if I do not speak falsely, / Lleu will come into my lap.\" And it dropped down onto Gwydion's knee. And then Gwydion struck it with the wand, until it was in its own shape. No one ever saw a more piteous sight of a man than was on him: there was nothing but skin and bone.",
          n: "The three <strong>englynion</strong> are among the most famous verses in medieval Welsh, and they do what no wand could: sung one after another, each calls the wounded eagle down a stage — from the crown of the oak, to its middle, to the lowest branch, and at last into Gwydion's lap. It is poetry as power, and the proof that Gwydion's bardic disguise was never only a disguise: he is the supreme <em>cyfarwydd</em>, and his craft is real magic. (The verses are textually difficult and half-obscured by age; the renderings here follow their sense.) Only when Lleu is in his lap does the <strong>wand</strong> finish the work — restoring the eagle to a man, though one wasted to skin and bone." },

        { w: "Yna kyrchu Caer Dathyl a wnaeth ef, ac yno y ducpwyt idaw a gahat o uedyc da yg Gwyned. Kyn kyuyl y'r ulwydyn, yd oed ef yn holl iach. \"Arglwyd,\" heb ef wrth Uath, \"madws oed ymi caffael iawn gan y gwr y keueis ouut gantaw.\" \"Dioer,\" heb y Math, \"ny eill ef ymgynhal a'th iawn di gantaw.\" \"Goreu yw genhyf,\" heb ynteu, \"bo kyntaf y caffwyf iawn.\" Yna dygyuoryaw Gwyned a wnaethant, a chyrchu Ardudwy; a Gwydyon a gerdwys yn y blaen, a chyrchu Mur Castell.",
          e: "Then he made for Caer Dathyl, and there every good physician that could be had in Gwynedd was brought to him. Before the year's end he was wholly well. \"Lord,\" he said to Math, \"it is high time I had redress from the man who got me into this misery.\" \"Truly,\" said Math, \"he cannot maintain himself and keep from giving you your redress.\" \"The sooner I have my redress, the better I shall like it,\" he said. Then they mustered Gwynedd, and made for Ardudwy; and Gwydion went on ahead, and made for Mur Castell.",
          n: "Healed over a year at Caer Dathyl, Lleu — named, armed, wived, killed and restored — comes at last into his own as a man who claims his own justice. The branch that opened with a war manufactured by fraud closes with a war that is simply <em>owed</em>: Math raises Gwynedd, and Gwydion goes ahead to Lleu's stolen court at Mur Castell, where the two who wronged him are waiting. The reckoning falls on each in the measure of their guilt." },

        { w: "Sef a wnaeth Blodeuwed, clybot eu bot yn dyuot, a chymryt y morynyon gyt a hi, a chyrchu y mynyd; a thrwy Auon Gynuael kyrchu llys a oed ar y mynyd. Ac ny wydyn gerdet rac ofyn namyn a'u hwyneb tra eu keuyn, ac yna ny wybuant yny syrthyssant yn y llyn ac y bodyssant oll, eithyr hi e hun. Ac yna y gordiwawd Gwydyon hitheu. \"Ny ladaf i di,\" heb ef; \"mi a wnaf yssyd waeth it: dy ellwng yn rith ederyn. Ac o achaws y kywilyd a wnaethost y Leu Llaw Gyffes, na ueidych dangos dy wyneb lliw dyd byth, rac ouyn yr holl adar, a bot gelynyaeth y rwng yr adar a thi, ac na cholly dy enw, namyn dy alw uyth yn Blodeuwed.\"",
          e: "What Blodeuwedd did, hearing that they were coming, was to take her maidens with her and make for the mountain; and crossing the river Cynfael she made for a court that was on the mountain. And for fear they could not go but with their faces turned back over their shoulders; and so they did not know until they fell into the lake and were all drowned, save only herself. And then Gwydion overtook her. \"I will not kill you,\" he said; \"I will do what is worse for you: I will let you go in the shape of a bird. And because of the shame you did to Lleu Llaw Gyffes, you shall never dare show your face by day, for fear of all the birds; there shall be enmity between you and all birds; it shall be their nature to mob and harry you wherever they find you; and you shall not lose your name, but be called Blodeuwedd forever.\"",
          n: "Blodeuwedd's punishment is the branch's last great transformation, and crueller than death by design. Gwydion turns the <strong>flower-face into an owl</strong> — condemned never to show her face by day, shunned and mobbed by all other birds, keeping her name as a curse: <em>Blodeuwedd</em> is still a Welsh word for the owl. The made-woman is unmade into a creature of night and exile, and the tale offers its etiology with grim neatness — <em>this is why the birds hate the owl</em>. (Her drowned maidens, fleeing face-backward into the lake, leave their own faint onomastic trace.) Made for one man against nature, she ends outside nature altogether." },

        { w: "Ynteu Gronwy Pebyr a gyrchwys Penllyn, ac odyno y gofynnwys a uynnei Lleu, ae tir, ae dayar, ae eur, ae aryant, am y sarhaet. \"Na chymeraf, y Duw dygaf uyg kyffes,\" heb ef. \"Llyma y peth lleiaf a gymeraf: mynet o honaw ef y'r lle yd oedwn i ban y'm byryawd a'r par, a minheu y'r lle yd oed ynteu, a gadel y minheu y uwrw ef a phar.\" Sef a wnaeth Gronwy, erchi y'w deulu a'y urodyr maeth a oes a gymerei yr ergyt drosaw; ac o achaws gomed o honunt, y gelwir wynt y trydyd Anniweir Deulu. \"Ie,\" heb ef, \"mi a'e kymeraf.\" Ac yna y govynnwys gadel idaw dodi y llech a welei ar lan yr auon y ryngtaw a'r ergyt. \"Ni'th omedaf,\" heb y Lleu. Ac yna y byryawd Lleu ef a'r par, ac y gwant y llech drwydi, ac ynteu drwydaw, yny dyrr y geuyn. Ac yno y llas Gronwy Pebyr; ac yno y mae y llech ar lan Auon Gynuael, a'r twll drwydi, ac o achaws hynny y gelwir Llech Gronwy.",
          e: "Gronw Pebr made for Penllyn, and from there he sent to ask whether Lleu would take land, or ground, or gold, or silver for the injury. \"I will not, by my confession to God,\" he said. \"Here is the least I will take: that he go to the place where I was when he cast the spear at me, and I to the place where he was, and let me cast a spear at him.\" What Gronw did was to ask his war-band and his foster-brothers whether any would take the blow for him; and because they refused, they are called the Third Disloyal War-Band. \"Well,\" he said, \"I will take it.\" And then he asked to be allowed to set between himself and the blow a slab he saw on the riverbank. \"I will not refuse you that,\" said Lleu. And then Lleu cast the spear at him, and it pierced the slab and him through it, until his back was broken. And there Gronw Pebr was killed; and there the slab is, on the bank of the river Cynfael, with the hole through it, and for that reason it is called Llech Gronw — \"Gronw's Stone.\"",
          n: "Gronw's death is justice as exact symmetry: he offers wealth, but Lleu will take only the <strong>return-blow</strong> — let Gronw stand where Lleu stood and take a spear in his turn. Gronw's men refuse to take the cast for their lord, earning them a place in the Triads as one of the <em>Tri Anyweir Deulu</em>, the Three Disloyal War-Bands of Britain. And the symmetry holds to the last grim detail: the stone Gronw hides behind is pierced through by Lleu's spear, as Lleu's body was pierced — and the holed slab, <strong>Llech Gronw</strong>, still stands by the Cynfael in Ardudwy. The branch keeps its accounts in the land itself." },

        { w: "Ynteu Lleu Llaw Gyffes a oreskynnwys eilweith y wlat, ac y gwledychwys yn llwydanhus; a herwyd y dyweit y kyuarwydyt, ef a uu arglwyd wedy hynny ar Wyned. Ac yuelly y teruyna y geing honn o'r Mabinogi.",
          e: "And Lleu Llaw Gyffes took possession of the land a second time, and ruled it prosperously; and, as the lore relates, he was lord over Gwynedd ever after. And so ends this branch of the Mabinogi.",
          n: "The Fourth Branch — and with it the Four Branches — closes on Lleu restored, lord of Gwynedd. The cycle's two great dynastic threads have changed places: the line of <strong>Pwyll</strong>, which carried the story from the First Branch through Pryderi, ends with Pryderi's death in this branch's first movement; and the line of <strong>Dôn</strong> rises in his place, with Lleu — the Welsh Lugus, the bright god of the skilful hand — settled at last as a man and a king. The Mabinogi ends not with a wedding or a quest but with a long act of repair: a foster-father's poem calling a wounded god out of a tree, and a justice measured to the wrong. The comparative reading of all four Branches together lives at the <a href=\"/mabinogi/\">Mabinogi</a> hub." },
      ],
    },
  ],
};
