/* Math uab Mathonwy — the Fourth and last Branch of the Mabinogi. The English
   shown alongside the Welsh is an original translation, written movement by
   movement; Lady Charlotte Guest's public-domain version (1849) is consulted
   as a sense-check, not copied.

   The Welsh is the Welsh Wikisource reading text (CC BY-SA 4.0), the same
   edition that supplies Pwyll on this site — a normalised reading text of the
   White Book / Red Book tradition. It is the sequel to Manawydan, and its
   first movement closes the Pryderi thread that has run through all four
   Branches.

   Both source texts are preserved verbatim under source/:
     math-rhys-evans-1887-redbook.txt   (Middle Welsh reading text)
     math-guest-1849-english.txt         (Guest's comparison translation)
   Attaches to window.MATH. */
window.MATH = window.MATH || {};
window.MATH.tale = {
  meta: {
    blurb: "<strong>Math uab Mathonwy</strong> — \"Math son of Mathonwy\" — the <em>Fourth</em> and last Branch of the Mabinogi, the sequel to <em>Manawydan</em> and the close of the cycle, preserved in the White Book of Rhydderch (c. 1350) and the Red Book of Hergest (c. 1382–1410). It is the branch of the <strong>children of Dôn</strong> — a family of magicians — and of transformation. <strong>Math</strong>, the old enchanter-king of Gwynedd, can live only with his feet in a maiden's lap except in time of war; so his nephew <strong>Gwydion</strong>, the great trickster and shape-shifter, starts a war on purpose. He steals the Otherworld swine of <strong>Pryderi</strong> of Dyfed with a herd of illusory horses and gilded shields conjured from fungus, and in the war that follows he kills Pryderi in single combat by strength and magic — ending the thread that has run through all four Branches. The war was only a pretext: in Math's absence Gwydion's brother <strong>Gilfaethwy</strong> forces the king's foot-holder, <strong>Goewin</strong>. Math weds Goewin to mend her honour, and punishes the brothers by turning them, three years running, into paired beasts — deer, then boar, then wolves — each bearing the other young. Then, seeking a new foot-holder, Math tests <strong>Aranrhod</strong>; she fails the test, and in failing drops two boys — one, <strong>Dylan</strong>, takes to the sea, and the other Gwydion rears in secret. Aranrhod lays three curses on that son: he shall have no <strong>name</strong>, no <strong>arms</strong>, and no <strong>wife of any race on earth</strong>, unless from her. Gwydion breaks the first two by trickery — winning him the name <strong>Lleu Llaw Gyffes</strong> — and, with Math, breaks the third by conjuring a wife out of flowers: <strong>Blodeuwedd</strong>. But Blodeuwedd loves another, <strong>Gronw Pebr</strong>; the two contrive the one near-impossible way Lleu can be killed, and strike him down — and Lleu rises as an <strong>eagle</strong> and flies away wounded. Gwydion seeks him over all Gwynedd, finds him by the rotting tree, sings him down and restores him; and the reckoning falls — Blodeuwedd turned to an <strong>owl</strong>, Gronw killed by the spear-blow he once dealt, and Lleu lord of Gwynedd once more. The translation below is <strong>original</strong> and proceeds <strong>movement by movement</strong>; the Welsh beside it is the Wikisource reading text. Full sources at <a href=\"source/math-rhys-evans-1887-redbook.txt\">source/math-rhys-evans-1887-redbook.txt</a> and <a href=\"source/math-guest-1849-english.txt\">source/math-guest-1849-english.txt</a>.",
    sources: [
      { label: "Math uab Mathonwy — Welsh Wikisource reading text (CC BY-SA 4.0; White Book / Red Book tradition)", url: "https://cy.wikisource.org/wiki/Math_uab_Mathonwy", host: "Welsh Wikisource" },
      { label: "The Mabinogion — Lady Charlotte Guest, 1838–49 (public-domain English translation)", url: "https://www.gutenberg.org/ebooks/5160", host: "Project Gutenberg" },
      { label: "Math fab Mathonwy — overview", url: "https://en.wikipedia.org/wiki/Math_fab_Mathonwy", host: "Wikipedia" },
      { label: "The Four Branches of the Mabinogi", url: "https://en.wikipedia.org/wiki/Four_Branches_of_the_Mabinogi", host: "Wikipedia" },
    ],
  },
  roadmap: [
    { t: "Source text in hand (Welsh Wikisource reading text + Guest 1849)", done: true },
    { t: "I · The swine of Annwn, the war, and the death of Pryderi", done: true },
    { t: "II · The wrong to Goewin; Math's punishment of the brothers", done: true },
    { t: "III · The foot-holder test; the births of Dylan and Lleu", done: false },
    { t: "IV · Aranrhod's three curses, and how Gwydion broke two", done: false },
    { t: "V · Blodeuwedd the flower-wife; the betrayal and the eagle", done: false },
    { t: "VI · The finding of Lleu, and the reckoning", done: false },
  ],
  passages: [
    {
      title: "I. The swine of Annwn, the war, and the death of Pryderi",
      segments: [
        { w: "Math uab Mathonwy oed arglwyd ar Wyned, a Pryderi uab Pwyll oed arglwyd ar un cantref ar ugeint yn y Deheu. Sef oed y rei hynny, seith cantref Dyuet, a seith Morgannhwc, a phedwar Kyredigyawn, a thri Ystrat Tywi. Ac yn yr oes honno Math uab Mathonwy ny bydei uyw namyn tra uei y deudroet ymlyc croth morwyn, onyt kynwryf ryuel a'y llesteirei. Sef oed yn uorwyn gyt ac ef, Goewin uerch Pebin o Dol Pebin yn Aruon; a honno teccaf morwyn oed yn y hoes o'r a wydit yno. Ac ynteu yg Kaer Dathyl yn Aruon yd oed y wastatrwyd; ac ny allei gylchu y wlat, namyn Giluaethwy uab Dôn a Gwydyon uab Dôn, y nyeint, meibon y chwaer, a'r teulu gyt ac wy, a aei y gylchu y wlat drostaw.",
          e: "Math son of Mathonwy was lord over Gwynedd, and Pryderi son of Pwyll was lord over the one-and-twenty cantrefs of the South — that is, the seven cantrefs of Dyfed, the seven of Morgannwg, the four of Ceredigion, and the three of Ystrad Tywi. And in that age, Math son of Mathonwy could not live unless his two feet were in the lap of a maiden, except when the tumult of war kept him from it. The maiden who was with him was Goewin daughter of Pebin, of Dôl Bebin in Arfon, and she was the fairest maiden of her time that was known there. And his dwelling was always at Caer Dathyl in Arfon; he could not go the circuit of the land, but Gilfaethwy son of Dôn and Gwydion son of Dôn, his nephews, his sister's sons, and the household with them, went the circuit of the land in his stead.",
          n: "The Fourth Branch opens on a king who is half-myth. <strong>Math son of Mathonwy</strong> is the old magician-king of Gwynedd, bound by a strange sacral condition: save in war, his feet must rest in the lap of a virgin <em>foot-holder</em> (the office is real in Welsh law; the magical compulsion is the tale's own). It is a fragile, archaic kingship — and its one loophole, <em>war</em>, is exactly what Gwydion will exploit. The <strong>children of Dôn</strong> — Gwydion, Gilfaethwy, and (later) Aranrhod — are a family of enchanters, the Welsh counterpart of the Irish Túatha Dé Danann (Dôn ≈ Danu); Gwydion's name was later given to the Milky Way, <em>Caer Wydion</em>. Note the opening also fixes Pryderi, son of Pwyll of the First Branch, as lord of the whole South — setting up the last act of his long story." },

        { w: "A'r uorwyn oed gyt a Math yn wastat; ac ynteu Giluaethwy uab Dôn a dodes y uryt ar y uorwyn, a'y charu hyt na wydat beth a wnâi ymdanei; ac nachaf y liw a'y wed a'y ansawd yn atueilaw o'y charyat, hyt nat oed hawd y adnabot. Sef a wnaeth Gwydyon y urawt, synnyeit dydgweith arnaw yn graf. \"A was,\" heb ef, \"pa derw it?\" \"Beth a wely di arnaf i?\" \"Gwelaf arnat,\" heb ef, \"colli dy bryt a'th liw.\" \"Arglwyd urawt,\" heb ef, \"yr hynn a deryw ymi, ny frwytha ymi y adef y neb… Ti a wdost kynedyf Math uab Mathonwy: ba hustyng bynnac, yr y uychanet, o ry kyuarfo y gwynt ac ef, ef a'y gwybyd.\" \"Ie,\" heb y Gwydyon, \"taw di bellach. Mi a wnn dy uedwl: caru Goewin yd wyt ti.\"",
          e: "The maiden was with Math continually; and Gilfaethwy son of Dôn set his heart on her, and loved her until he did not know what to do for love of her — until his colour and his face and his whole bearing wasted away with longing, so that he was hard to recognise. His brother Gwydion looked hard at him one day. \"Lad,\" he said, \"what has come over you?\" \"What do you see in me?\" \"I see,\" he said, \"that you have lost your looks and your colour.\" \"Lord brother,\" he said, \"what ails me, it would do me no good to confess to anyone… You know the nature of Math son of Mathonwy: whatever whisper there is between people, however low, if the wind meets it, he will know it.\" \"Yes,\" said Gwydion. \"Say no more. I know your mind: you love Goewin.\"",
          n: "The whole branch is set in motion by a love that cannot be spoken — and a king who hears every whisper the wind catches. Math's <em>wind-borne hearing</em> is the magical omniscience of the sacral king; it makes ordinary scheming impossible, so the conspirators need something bigger than a whisper — a war — to get Math away from his court and his foot-holder. <strong>Gwydion</strong>, the elder brother, is the engine of the tale: the cleverest man in the world, a poet, an illusionist and a fixer, who reads Gilfaethwy's secret in a glance and at once begins to plot a way to serve it." },

        { w: "Pan wybu ef adnabot o'y urawt y uedwl, dodi ucheneit dromhaf yn y byt. \"Taw, eneit, a'th ucheneidaw,\" heb ef; \"nyt o hynny y goruydir. Mi a baraf, cany ellir heb hynny, dygyuori Gwyned a Phowys a Deheubarth y geissaw y uorwyn; a byd lawen di.\" Ac ar hynny at Uath uab Mathonwy yd aethant. \"Arglwyd,\" heb y Gwydyon, \"mi a gigleu dyuot y'r Deheu ryw bryuet ny doeth y'r ynys honn eiroet.\" \"Pwy eu henw wy?\" \"Hobeu, Arglwyd.\" \"Pa ryw aniueileit yw y rei hynny?\" \"Aniueileit bychein, gwell eu kic no chic eidon; bychein ynt, ac y maent yn symudaw enweu — moch y gelwir weithon. Pryderi uab Pwyll bieu wynt, yd anuonet idaw o Annwn y gan Arawn urenhin Annwn.\"",
          e: "When Gilfaethwy found that his brother knew his mind, he heaved the heaviest sigh in the world. \"Hush, my soul, and do not sigh,\" said Gwydion; \"it is not by sighing that this is won. I will raise — since it cannot be done otherwise — Gwynedd and Powys and Deheubarth, to seek the maiden. Be of good cheer.\" And with that they went to Math son of Mathonwy. \"Lord,\" said Gwydion, \"I have heard that there have come to the South a kind of beast that never came to this island before.\" \"What are they called?\" \"Hogs, lord.\" \"What sort of animals are these?\" \"Small animals, their flesh better than the flesh of oxen; they are small, and they are changing their name — they are called swine now. Pryderi son of Pwyll owns them; they were sent to him from Annwn, by Arawn king of Annwn.\"",
          n: "Gwydion's plan is breathtaking in its cynicism: to get his brother an hour alone with Goewin, he will set three kingdoms marching. The pretext is the <strong>swine of Annwn</strong> — the first pigs in Britain, a gift to Pryderi from <strong>Arawn king of Annwn</strong> (the Otherworld lord of the First Branch, where Pwyll won his friendship). Pigs are prestige- and Otherworld-animals in Celtic tradition, and these are doubly so. The detail that the beasts are \"changing their name\" from <em>hob</em> to <em>moch</em> is the branch's first onomastic touch — names and naming are one of its great themes, and will become the hinge of Aranrhod's first curse." },

        { w: "\"Mi a af ar uyn deudecuet, yn rith beird, Arglwyd, y erchi y moch.\" \"Ef a ry eill ych necau,\" heb ynteu. \"Nyt drwc uyn trawscwyd i, Arglwyd; ny doaf i heb y moch.\" Ef a aeth, a Giluaethwy, a deg gwyr gyt ac wynt, hyt yg Keredigyawn, y'r lle a elwir Rudlan Teiui yr awrhon; yd oed llys yno y Pryderi. Ac yn rith beird y doethant ymywn; llawen uuwyt wrthunt. Ar neillaw Pryderi y gossodet Gwydyon y nos honno. Ynteu Wydyon, goreu kyuarwyd yn y byt oed; a'r nos honno didanu y llys a wnaeth ar ymdidaneu digrif a chyuarwydyt, yny oed hoff gan paub o'r llys.",
          e: "\"I will go, as one of twelve, in the guise of bards, lord, to ask for the swine.\" \"It may be that he will refuse you,\" said Math. \"My errand will not go badly, lord; I will not come back without the swine.\" So he went, and Gilfaethwy, and ten men with them, into Ceredigion, to the place now called Rhuddlan Teifi, where Pryderi had a court. In the guise of bards they came in, and were made welcome; Gwydion was seated beside Pryderi that night. And Gwydion was the best teller of tales in the world; that night he entertained the court with pleasant talk and stories, until he was the delight of everyone there.",
          n: "Gwydion enters Pryderi's hall disguised as the chief of a company of <strong>bards</strong> — and his cover is no lie: he really is the best storyteller in the world, and charms the whole court, exactly as Welsh tales prize the guest who can recite. It is a portrait of the poet as con-man, and a quietly self-aware one: the Fourth Branch, itself a masterpiece of storytelling, makes its villain-hero a supreme storyteller. The disguise-embassy recalls the trickster-entries of <em>Culhwch</em> (Cei as a sword-burnisher) — deception by disguise is deep in the tradition." },

        { w: "Ac ar diwed hynny, \"Arglwyd,\" heb ef, \"llyma uy neges: ymadolwyn a thidi am yr aniueileit a anuonet it o Annwuyn.\" \"Hawssaf yn y byt oed hynny,\" heb ynteu, \"by na bei ammot y rof a'm gwlat amdanunt: nat elont y genhyf yny hilyont eu deu kymeint yn y wlat.\" \"Arglwyd,\" heb ynteu, \"mi a allaf dy rydhau o'r geireu hynny: na dyro im y moch heno, ac na nacaha ui ohonunt; auory mi a dangossaf gyfnewit amdanunt.\" Ac yna yd aeth ef yn y geluydodeu, ac y dechreuawt dangos y hut: yd hudwys deudec emys, a deudec milgi bronwyn du, a deudec torch ac deudec kynllyuan arnunt — ac ny wydat neb o'r a'e gwelei na bydynt eur — a deudec kyfrwy ar y meirch, a phob lle y dylyei hayarn uot arnunt, y bydei gwbyl o eur.",
          e: "And at the end of it, \"Lord,\" he said, \"here is my errand: to beg of you the beasts that were sent you from Annwn.\" \"That would be the easiest thing in the world,\" said Pryderi, \"were there not a covenant between me and my land concerning them — that they shall not leave me until they have bred twice their number in the land.\" \"Lord,\" said Gwydion, \"I can release you from those words. Do not give me the swine tonight, and do not refuse them me; tomorrow I will show you an exchange for them.\" And that night he went to his arts, and began to work an enchantment: he conjured twelve stallions, and twelve white-breasted black greyhounds, with twelve collars and twelve leashes on them — and no one who saw them could tell they were not gold — and twelve saddles on the horses, and wherever there should have been iron, all was gold.",
          n: "Pryderi's refusal is honourable — he is bound by a <em>covenant with his land</em> not to part with the swine until they have doubled — and Gwydion's answer is pure fraud: he will not buy or be refused, but <em>exchange</em>. Overnight he works his signature magic, <em>hud</em> — conjuring twelve horses, twelve hounds and (next) twelve gilded shields, all gleaming gold, all illusion. Gwydion is the Mabinogi's master illusionist, and this is the first of the branch's many enchantments; the gold-from-nothing trick is as old as fairy money, and as treacherous." },

        { w: "A'r meirch a'r cwn y doeth ef at Pryderi, a'r deudec taryan eureit (y rei hynny a rithassei ef o'r madalch). \"Arglwyd,\" heb ef, \"llyma rydit it am y geir a dywedeist neithwyr: titheu a elly gyfnewit yr a uo gwell.\" Sef a gaussant yn eu kynghor, rodi y moch e Wydyon, a chymryt y meirch a'r cwn a'r taryaneu. Ac yna y dechreussant gerdet a'r moch. \"A geimeit,\" heb y Gwydyon, \"reit yw in gerdet yn bryssur: ny phara yr hut namyn o'r pryt pwy gilyd.\" A'r nos honno y kerdyssant hyt ygwarthaf Keredigyawn, y lle a elwir etwa o achaws hynny Mochtref; a thrannoeth dros Elenit; a'r nos honno y rwng Keri ac Arwystli, yn y dref a elwir heuyt Mochtref; ac odyna hyt yg kymwt ym Powys, a elwir o'r ystyr hwnnw Mochnant.",
          e: "He brought the horses and the dogs to Pryderi, and the twelve gilded shields (those he had conjured out of fungus). \"Lord,\" he said, \"here is a release for you from the word you spoke last night: you may exchange them for something better.\" And the counsel they reached was to give the swine to Gwydion, and take the horses and the dogs and the shields. Then they set off with the swine. \"Comrades,\" said Gwydion, \"we must travel fast: the enchantment will last only from this hour to the same tomorrow.\" That night they travelled to the top of Ceredigion, to the place still called for that reason Mochdref — \"Swine-town\"; the next day across Elenydd; that night between Keri and Arwystli, to the town also called Mochdref; and thence to the commot in Powys called, for the same reason, Mochnant — \"Swine-brook.\"",
          n: "The shields conjured <em>o'r madalch</em>, \"out of fungus,\" are the perfect emblem of Gwydion's magic — splendour grown from rot, doomed to last exactly a day. The race home, one jump ahead of the illusion's collapse, leaves a trail of place-names across mid-Wales: <strong>Mochdref</strong> (swine-town), <strong>Mochnant</strong> (swine-brook), and shortly <strong>Creuwryon</strong> (the swine-sties). The Four Branches are studded with these onomastic anchors — the story explaining a real map — and Math is the densest of all; the cycle remembers itself in the land." },

        { w: "Sef y kyrchyssant y dref uchaf o Arllechwed, ac yno gwneuthur creu y'r moch, ac o'r achaws hwnnw y dodet Creuwryon ar y dref. Ac yna y kyrchyssant ar Uath, hyt yg Kaer Dathyl. A phan doethant, yd oedit yn dygyuori y wlat: \"Dygyuor y mae Pryderi yn ych ol chwi, un cantref ar ugeint.\" Ar hynny y clywynt yr utkyrn a'r dygyuor; gwiscaw a wnaethant, a cherdet yny uydant ym Pennard yn Aruon. A'r nos honno yd ymhoelwys Gwydyon uab Dôn a Giluaethwy y urawt y gyt y Gaer Dathyl; ac y guely Math uab Mathonwy y dygwyt Goewin uerch Pebin o'y hanuod, a chyscu genti y nos honno o'y hanuod.",
          e: "They made for the highest town of Arllechwedd, and there built sties for the swine, and for that reason the town was named Creuwryon. And then they made for Math, to Caer Dathyl. And when they came, the land was being mustered: \"Pryderi is mustering behind you — one-and-twenty cantrefs. It is a wonder you travelled so slowly.\" At that they heard the war-horns and the muster; they armed, and marched until they were at Pennardd in Arfon. But that night Gwydion son of Dôn and his brother Gilfaethwy turned back together to Caer Dathyl; and into Math's own bed Goewin daughter of Pebin was taken against her will, and that night she was forced.",
          n: "Here the war's true purpose is paid out, and the branch turns very dark. With Math drawn off to fight the war Gwydion manufactured, the brothers slip back to the undefended court, and <strong>Goewin is forced</strong> — the outrage the whole rest of the movement, and Math's terrible punishment, will answer. The tale states it with grave brevity, twice naming that it was <em>against her will</em> (<em>o'y hanuod</em>), and the apparatus follows that lead: the wrong is named, not dwelt on. It is a crime against the king's honour and the foot-holder's person at once — and, because Math hears all whispers, one that cannot stay hidden." },

        { w: "Pan welsant y dyd drannoeth, kyrchu a wnaethant parth a'r lle yd oed Math a'y lu. A Phryderi a'y kyrchwys; ac yno y bu y gyfranc, ac y llas lladua uawr o pob parth, ac y bu reit y wyr y Deheu enkil. Ac yna clymu a wnaethant, a cheissaw ymdangneuedu; a gwystlaw a wnaeth Pryderi ar y tangneued, Gwrgi Gwastra a phedwar ar ugeint o ueibyon gwyrda. A guedy hynny, kerdet o honunt yn eu tangneued hyt y Traeth Mawr; ac am na ellit reoli y pedyt rac ymsaethu, gyrru kennadeu o Pryderi y erchi gadu y ryngtaw ef a Gwydyon uab Dôn, kanys ef a baryssei hynny. \"Dygaf y Duw uyg kyffes,\" heb y Gwydyon, \"nat archaf i y wyr Gwyned ymlad drossof i, a minheu uy hun yn cael ymlad a Phryderi. Mi a dodaf uyg korf yn erbyn y eidaw yn llawen.\"",
          e: "When they saw the day next morning, they made for the place where Math and his host were. And Pryderi attacked; and there the battle was joined, and a great slaughter fell on both sides, and the men of the South were forced to retreat. Then they made a truce and sought to come to peace, and Pryderi gave hostages for the peace — Gwrgi Gwastra and four-and-twenty sons of nobles. And after that they went in truce as far as the Traeth Mawr; but because the foot-soldiers could not be kept from shooting, Pryderi sent messengers to ask that it be left between him and Gwydion son of Dôn alone, since it was he who had caused all this. \"I call God to witness,\" said Gwydion, \"I will not ask the men of Gwynedd to fight for me, when I myself may fight Pryderi. I will set my own body against his, gladly.\"",
          n: "Pryderi's demand is just, and it is the moral hinge of the movement: the war was Gwydion's doing, so let Gwydion answer for it in his own body, and spare the two armies. Gwydion accepts at once — and there is real honour in it. But the duel that follows will not be fought on equal terms." },

        { w: "Ac yna o nerth ac angerd, ac o hut a lledrith, Gwydyon a oruu, a Phryderi a las. Ac yg Maen Tyuyawc, uch y Uelen Ryd, y cladwyt; ac yno y mae y ued. Y gwyr y Deheu a gerdyssant tu a'u gwlat ban gwynfanus. Ac nyt oed ryued: eu harglwyd a gollyssynt, a llawer o'u gwyrda, a'u meirch, a'u harueu y ran uwyaf. Y gwyr Gwyned a ymchoelyssant adref yn llawen orfoledus. \"Arglwyd,\" heb y Gwydyon wrth Uath, \"pony chyfreithawn ni ellwng eu gwystlon y wyr y Deheu? Ny dylyynt garchar.\" \"Gellynger wynt,\" heb ynteu.",
          e: "And then by strength and ferocity, and by magic and enchantment, Gwydion prevailed, and Pryderi was slain. At Maen Tyfiawg, above Y Felen Rhyd, he was buried; and there is his grave. The men of the South went back toward their own land in bitter lament — and no wonder: they had lost their lord, and many of their nobles, and their horses and arms for the most part. The men of Gwynedd went home glad and triumphant. \"Lord,\" said Gwydion to Math, \"would it not be lawful to release the men of the South their hostages? They do not deserve imprisonment.\" \"Let them be freed,\" said Math.",
          n: "So <strong>Pryderi dies</strong> — and the death is shadowed, for Gwydion wins not by strength alone but <em>o hut a lledrith</em>, \"by magic and enchantment.\" The boy whose birth, loss and recovery closed the First Branch, who survived the catastrophe of the Second and helped lift the wasteland of the Third, is killed in the Fourth by a magician's trick on a battlefield Gwydion arranged for an utterly private reason. It is the end of the great connecting thread of the Mabinogi, and the tale lets the men of the South grieve him properly. Gwydion's smooth turn to lawyerly courtesy in the very next breath — <em>shall we not free the hostages?</em> — is the measure of the man: the war he started for his brother is, to him, already an administrative matter. His own reckoning, and Gilfaethwy's, is still to come." },
      ],
    },

    {
      title: "II. The wrong to Goewin, and Math's punishment of the brothers",
      segments: [
        { w: "Ynteu Math a gyrchwys Caer Dathyl. Giluaethwy uab Dôn a'r teulu a uuassei gyt ac ef a gyrchyssant y gylchaw Gwyned mal y gnotayssynt, heb gyrchu y llys. Ynteu Math a gyrchwys y ystauell, ac a beris kyweiraw lle idaw y benelinyaw, ual y caei dodi y draet ym plyc croth y uorwyn. \"Arglwyd,\" heb y Goewin, \"keis uorwyn a uo is dy draet weithon; gwreic wyf i.\" \"Pa ystyr yw hynny?\" \"Kyrch, Arglwyd, a doeth am uym penn, a hynny yn diargel, ac ny buum distaw inheu; ny bu yn y llys nys gwypei. Sef a doeth, dy nyeint, meibon dy chwaer, Gwydyon uab Dôn a Giluaethwy uab Dôn; a threis arnaf a orugant, a chywilyd y titheu; a chyscu a wnaethpwyt genhyf, a hynny yth ystauell ac yth wely.\"",
          e: "Math then made for Caer Dathyl. Gilfaethwy son of Dôn and the household that had been with him went off about Gwynedd on the circuit, as they were wont, and did not come to the court. Math went to his chamber, and had a place made ready for him to recline, so that he might set his feet in the lap of the maiden. \"Lord,\" said Goewin, \"seek now a maiden to be under your feet; I am a woman.\" \"What do you mean by that?\" \"An assault came upon me, lord, and that openly — and I was not silent; there was no one in the court who did not know of it. It was your nephews who came, your sister's sons, Gwydion son of Dôn and Gilfaethwy son of Dôn; and they did violence to me, and shame to you; I was forced — and that in your own chamber and your own bed.\"",
          n: "The crime surfaces the only way it can in Math's court — Goewin states it plainly to his face, because she did <em>not</em> stay silent and the whole court already knows (nothing escapes the king who hears the wind). The Welsh is careful and unflinching about the wrong: it was <em>treis</em>, violence/rape, done openly, in the king's own bed — an outrage at once against Goewin's person, against the sacral office of the foot-holder (who must be a virgin), and against Math's honour and his very life-condition. Goewin's first words are not for herself but a practical warning to her king: <em>seek another, I am a woman now</em> — the foot-rest can no longer be hers." },

        { w: "\"Ie,\" heb ynteu, \"yr hyn a allaf i, mi a'e gwnaf. Mi a baraf iawn y ti yn gyntaf, ac yn ol uy iawn y bydaf inheu. A thitheu,\" heb ef, \"mi a'th gymeraf yn wreic im, ac a rodaf medyant uyg kyuoeth i'th law.\" Ac yn hynny ny doethant wy yng kyuyl y llys, namyn trigyaw y gylchaw y wlat yny aeth guahard udunt ar eu bwyt a'u llyn.",
          e: "\"Well,\" he said, \"what I can do, I will do. I will make amends to you first, and after my amends to you I will look to my own. And you,\" he said, \"I will take as my wife, and I will put the authority over my realm into your hands.\" And meanwhile the two did not come near the court, but stayed out on the circuit of the land, until they were forbidden their food and their drink.",
          n: "Math's response is the moral counterweight to the whole branch. Before any thought of punishment, he turns to the victim: <em>I will make amends to you first</em> — and the amends is to <strong>marry Goewin and give her authority over the kingdom</strong>, raising the wronged foot-holder to queen. It is a remarkable act in a medieval text: the king repairs the woman's broken honour by sharing his own power with her, and only then turns to the offenders. The brothers, knowing what waits, keep to the open country — until Math cuts off their food and drink and forces them in." },

        { w: "Yn gyntaf ny doethant yn y gyuyl ef; yna y doethant attaw. \"Arglwyd,\" heb wynt, \"dyd da it.\" \"Ie,\" heb ynteu, \"ae y wneuthur iawn ymi y doethawch chwi?\" \"Arglwyd, i'th ewyllus yd ydym.\" \"Bei uy ewyllus, ny chollwn o wyr ac arueu a golleis; uyg kywilyd ny ellwch chwi y dalu ym, heb angheu Pryderi. A chan doethawch y'm ewyllus, mi a dechreuaf boen arnawch.\"",
          e: "At first they did not come into his presence; then they came to him. \"Lord,\" they said, \"good day to you.\" \"Well,\" he said, \"is it to make me amends that you have come?\" \"Lord, we are at your will.\" \"Had it been my will, I would not have lost the men and the arms I have lost; you cannot pay me for my shame, let alone for the death of Pryderi. But since you have come to my will, I will begin your punishment.\"",
          n: "Math names the full bill — the dead men, the lost arms, his own shame, and, set above all the rest, <em>the death of Pryderi</em>. The war Gwydion manufactured as a private favour has cost a king of Britain his life, and Math reckons that the heaviest charge of all. There is no amends that can pay it; what is left is punishment, and Math, the greater magician, will fit it to the crime." },

        { w: "Ac yna y kymerth y hutlath, ac y trewis Giluaethwy yny uyd yn ewic; ac achub y llall yn gyflym — kyt mynhei dianc nys gallei — a'y taraw a'r un hutlath yny uyd yn garw. \"Kanys ywch yn rwymedigaeth, mi a wnaf ywch gerdet y gyt, a'ch bot yn gymaredic ac yn un anyan a'r gwyduilot yd ywch yn eu rith; ac yn yr amser y bo etiued udunt wy, y uot ywchwitheu. A blwydyn y hediw dowch yma attaf i.\"",
          e: "And then he took the wand, and struck Gilfaethwy until he became a hind; and he seized the other quickly — though he wished to escape, he could not — and struck him with the same wand until he became a stag. \"Since you are bound together, I will make you go together, and be coupled, and be of one nature with the wild beasts whose shape you wear; and whenever they have offspring, so shall you. And a year from today, come here to me.\"",
          n: "The punishment is exquisitely, terribly fitted to the crime. The wand (<em>hudlath</em>) — Math's, the same instrument of transformation that runs through the branch — turns the brothers into a <strong>hind and a stag</strong>, and binds them to <em>be of one nature</em> with the beasts they wear: not merely to look like deer but to live and breed as deer. A sexual violation is answered by enforced coupling and the shame of bearing young; and each year, as we will see, the wand swaps which brother is the female, so that each in turn must conceive and carry the other's child. Math's magic effortlessly masters Gwydion's — the trickster who conjured horses from nothing is himself reshaped with a touch." },

        { w: "Ym penn y ulwydyn, o'r un dyd, llyma y clywei odorun adan paret yr ystauell, a chyuarthua cwn y llys am penn y godorun. \"Edrych beth yssyd allan.\" \"Arglwyd, mae yna garw, ac ewic, ac elein gryf gyt ac wynt.\" Kyuodi a oruc ynteu a dyuot allan; a dyrchauael y hutlath. \"Yr hwnn a uu o honawch yn ewic yrllyned, bit uaed coet yleni; a'r hwnn a uu garw, bit hwch goet eleni.\" Ac eu taraw a'r hutlath. \"Y mab hagen a gymeraf i, ac a baraf y ueithryn a'y uedydyaw.\" Sef enw a dodet arnaw, Hydwn.",
          e: "At the year's end, on the same day, he heard a commotion under the wall of the chamber, and the court's dogs baying at the commotion. \"See what is outside.\" \"Lord, there is a stag there, and a hind, and a strong young fawn with them.\" He rose and went out, and lifted the wand. \"The one of you who was a hind last year, be a wild boar this year; and the one who was a stag, be a wild sow.\" And he struck them with the wand. \"The young one, though — I will take him, and have him fostered and baptised.\" And the name given to him was Hyddwn.",
          n: "A year on, the deer come back with a <strong>fawn</strong> — proof the sentence has been served — and Math takes the child to be reared as his own, christening him Hyddwn (\"little stag,\" from <em>hydd</em>). Then he reverses the brothers' sexes for the next year: the one who bore the fawn becomes a boar, the one who sired it a sow. The point is precise and merciless — over three years <em>each</em> brother will be the mother in turn. The offspring, innocent, are gathered up and named for their shapes; the punishment falls only on the guilty." },

        { w: "Ym penn y ulwydyn, llyma y clywyn kyuarthua cwn dan paret yr ystauell, a dygyuor y llys am eu penn. Kyuodi a oruc a mynet allan; a phan daw, baed coet, a hwch goet, a chrenllwdyn da gyt ac wynt, a breisc oed yn yr oet oed arnaw. \"Hwnn a gymeraf i attaf, ac a baraf y uedydyaw\" — a'y daraw a'r hutlath yny uyd yn uab braswineu telediw. Sef enw a dodet arnaw, Hychdwn. \"A chwitheu, yr un a uu baed coet yrllyned, bit bleidast yleni; a'r hwn a uu hwch goet, bit uleid yleni.\" Ac eu taraw a'r hutlath, yny uydant uleid a bleidast.",
          e: "At the year's end, they heard the dogs baying under the chamber wall, and the court gathering about them. He rose and went out; and when he came, there was a wild boar, and a wild sow, and a fine well-grown young pig with them, big for its age. \"This one I will take to me, and have baptised\" — and he struck it with the wand until it became a fine, well-made boy. The name given to him was Hychdwn. \"And you — the one who was a boar last year, be a she-wolf this year; and the one who was a sow, be a wolf.\" And he struck them with the wand, until they became a wolf and a she-wolf.",
          n: "The second year, the second beast-son: <strong>Hychdwn</strong> (\"little pig,\" from <em>hwch</em>), taken and made human like his brother. And the sexes turn again — boar to she-wolf, sow to wolf — so the brother who was male last year is female this year. The relentless symmetry is the punishment's whole design: shame shared exactly, and a year of motherhood forced on each in turn. Three wild kinds — deer, swine, wolves — the order running from the gentlest game to the fiercest predator." },

        { w: "Yr un dyd ym penn y ulwydyn, llyma y clywei dygyuor a chyuarthua dan paret yr ystauell. Ynteu a gyuodes allan, a phan daw, llyma y guelei bleid, a bleidast, a chrubothon cryf gyt ac wynt. \"Hwnn a gymeraf i, ac a baraf y uedydyaw, ac y mae y enw yn parawt: sef yw hwnnw, Bleidwn. Y tri meib yssyd y chwi, a'r tri hynny ynt: <em>Tri meib Giluaethwy enwir, / Tri chenryssedat kywir: / Bleidwn, Hydwn, Hychdwn Hir.</em>\" Ac ar hynny, yn eu taraw yll deu a'r hutlath yny uydant yn eu cnawt eu hun. \"A wyr,\" heb ef, \"o gwnaethawch gam ymi, digawn y buawch ym poen, a chywilyd mawr a gawssawch: bot plant o bob un o honawch o'y gilyd. Perwch enneint y'r gwyr, a golchi eu penneu, ac eu kyweiraw.\"",
          e: "On the same day at the year's end, he heard a tumult and baying under the chamber wall. He rose and went out, and there he saw a wolf, and a she-wolf, and a strong wolf-cub with them. \"This one I will take, and have baptised, and his name is ready: it is Bleiddwn. You have three sons, and these are the three: <em>Three sons of false Gilfaethwy, / three champions true: / Bleiddwn, Hyddwn, Hychdwn the Tall.</em>\" And with that he struck the two of them with the wand, until they were in their own flesh again. \"Men,\" he said, \"if you did me wrong, you have been long enough in pain, and great shame you have had — that each of you has borne the other a child. Have a bath made for the men, and their heads washed, and them made ready.\"",
          n: "The third year brings <strong>Bleiddwn</strong> (\"little wolf,\" from <em>blaidd</em>), and the verse that fixes the three beast-sons in memory — <em>Tri meib Gilfaethwy enwir</em>, \"the three sons of false Gilfaethwy\" — one of the embedded <em>englynion</em> the prose tradition uses to lend a tale the authority of remembered verse. Then the sentence ends. Math's judgement is, in the end, measured: three years, the shame of each having borne the other's child, and no more. He restores them to human shape and at once calls for baths and clean clothes — the ritual of bringing the outcast back into the human, courtly world. The greater magician has punished, and now reconciles; he will need Gwydion again before the next page is out." },
      ],
    },
  ],
};
