// table/srd5/data.js — classes, feats and the official encounter maths
//
// GENERATED by tools/scrape-srd.py from the SRD 5.2.1 PDF:
//   python3 table/srd5/tools/scrape-srd.py
// Do not hand-edit — re-run the scraper.
//
// This work includes material from the System Reference Document 5.2.1
// ("SRD 5.2.1") by Wizards of the Coast LLC, available at
// https://www.dndbeyond.com/srd. The SRD 5.2.1 is licensed under the Creative
// Commons Attribution 4.0 International License, available at
// https://creativecommons.org/licenses/by/4.0/legalcode.

export const XP_BUDGET = {
 "1": {
  "low": 50,
  "moderate": 75,
  "high": 100
 },
 "2": {
  "low": 100,
  "moderate": 150,
  "high": 200
 },
 "3": {
  "low": 150,
  "moderate": 225,
  "high": 400
 },
 "4": {
  "low": 250,
  "moderate": 375,
  "high": 500
 },
 "5": {
  "low": 500,
  "moderate": 750,
  "high": 1100
 },
 "6": {
  "low": 600,
  "moderate": 1000,
  "high": 1400
 },
 "7": {
  "low": 750,
  "moderate": 1300,
  "high": 1700
 },
 "8": {
  "low": 1000,
  "moderate": 1700,
  "high": 2100
 },
 "9": {
  "low": 1300,
  "moderate": 2000,
  "high": 2600
 },
 "10": {
  "low": 1600,
  "moderate": 2300,
  "high": 3100
 },
 "11": {
  "low": 1900,
  "moderate": 2900,
  "high": 4100
 },
 "12": {
  "low": 2200,
  "moderate": 3700,
  "high": 4700
 },
 "13": {
  "low": 2600,
  "moderate": 4200,
  "high": 5400
 },
 "14": {
  "low": 2900,
  "moderate": 4900,
  "high": 6200
 },
 "15": {
  "low": 3300,
  "moderate": 5400,
  "high": 7800
 },
 "16": {
  "low": 3800,
  "moderate": 6100,
  "high": 9800
 },
 "17": {
  "low": 4500,
  "moderate": 7200,
  "high": 11700
 },
 "18": {
  "low": 5000,
  "moderate": 8700,
  "high": 14200
 },
 "19": {
  "low": 5500,
  "moderate": 10700,
  "high": 17200
 },
 "20": {
  "low": 6400,
  "moderate": 13200,
  "high": 22000
 }
};

export const FEATS = [
 {
  "name": "Alert",
  "category": "Origin",
  "prerequisite": null,
  "text": "You gain the following benefits. Initiative Proficiency. When you roll Initiative, you can add your Proficiency Bonus to the roll. Initiative Swap. Immediately after you roll Initiative, you can swap your Initiative with the Initiative of one willing ally in the same combat. You can't make this swap if you or the ally has the Incapacitated condition."
 },
 {
  "name": "Magic Initiate",
  "category": "Origin",
  "prerequisite": null,
  "text": "You gain the following benefits. Two Cantrips. You learn two cantrips of your choice from the Cleric, Druid, or Wizard spell list. Intelligence, Wisdom, or Charisma is your spellcasting ability for this feat's spells (choose when you select this feat). Level 1 Spell. Choose a level 1 spell from the same list you selected for this feat's cantrips. You always have that spell prepared. You can cast it once without a spell slot, and you regain the ability to cast it in that way when you finish a Long Rest. You can also cast the spell using any spell slots you have. Spell Change. Whenever you gain a new level, you can replace one of the spells you chose for this feat with a different spell of the same level from the chosen spell list. Repeatable. You can take this feat more than once, but you must choose a different spell list each time."
 },
 {
  "name": "Savage Attacker",
  "category": "Origin",
  "prerequisite": null,
  "text": "You've trained to deal particularly damaging strikes. Once per turn when you hit a target with a weapon, you can roll the weapon's damage dice twice and use either roll against the target."
 },
 {
  "name": "Skilled",
  "category": "Origin",
  "prerequisite": null,
  "text": "You gain proficiency in any combination of three skills or tools of your choice. Repeatable. You can take this feat more than once. General Feats"
 },
 {
  "name": "Ability Score Improvement",
  "category": "General",
  "prerequisite": "Level 4+)",
  "text": "(Prerequisite: Level 4+) Increase one ability score of your choice by 2, or increase two ability scores of your choice by 1. This feat can't increase an ability score above 20. Repeatable. You can take this feat more than once."
 },
 {
  "name": "Grappler",
  "category": "General",
  "prerequisite": "Level 4+, Strength or",
  "text": "(Prerequisite: Level 4+, Strength or Dexterit y 13+) You gain the following benefits. Ability Score Increase. Increase your Strength or Dexterity score by 1, to a maximum of 20. Punch and Grab. When you hit a creature with an Unarmed Strike as part of the Attack action on your turn, you can use both the Damage and the Grapple option. You can use this benefit only once per turn. Attack Advantage. You have Advantage on attack rolls against a creature Grappled by you. Fast Wrestler. You don't have to spend extra movement to move a creature Grappled by you if the creature is your size or smaller. Fighting Style Feats"
 },
 {
  "name": "Archery",
  "category": "Fighting Style",
  "prerequisite": "Fighting Style",
  "text": "(Prerequisite: Fighting Style Feature) You gain a +2 bonus to attack rolls you make with Ranged weapons."
 },
 {
  "name": "Defense",
  "category": "Fighting Style",
  "prerequisite": "Fighting Style",
  "text": "(Prerequisite: Fighting Style Feature) While you're wearing Light, Medium, or Heavy armor, you gain a +1 bonus to Armor Class."
 },
 {
  "name": "Great Weapon Fighting",
  "category": "Fighting Style",
  "prerequisite": "Fighting Style",
  "text": "(Prerequisite: Fighting Style Feature) When you roll damage for an attack you make with a Melee weapon that you are holding with two hands, you can treat any 1 or 2 on a damage die as a 3. The weapon must have the Two-Handed or Versatile property to gain this benefit."
 },
 {
  "name": "Two-Weapon Fighting",
  "category": "Fighting Style",
  "prerequisite": "Fighting Style",
  "text": "(Prerequisite: Fighting Style Feature) When you make an extra attack as a result of using a weapon that has the Light property, you can add your ability modifier to the damage of that attack if you aren't already adding it to the damage. Epic Boon Feats"
 },
 {
  "name": "Boon of Combat Prowess",
  "category": "Epic Boon",
  "prerequisite": "Level 19+)",
  "text": "(Prerequisite: Level 19+) You gain the following benefits. Ability Score Increase. Increase one ability score of your choice by 1, to a maximum of 30. Peerless Aim. When you miss with an attack roll, you can hit instead. Once you use this benefit, you can't use it again until the start of your next turn."
 },
 {
  "name": "Boon of Dimensional Travel",
  "category": "Epic Boon",
  "prerequisite": "Level 19+)",
  "text": "(Prerequisite: Level 19+) You gain the following benefits. Ability Score Increase. Increase one ability score of your choice by 1, to a maximum of 30. Blink Steps. Immediately after you take the Attack action or the Magic action, you can teleport up to 30 feet to an unoccupied space you can see."
 },
 {
  "name": "Boon of Fate",
  "category": "Epic Boon",
  "prerequisite": "Level 19+)",
  "text": "(Prerequisite: Level 19+) You gain the following benefits. Ability Score Increase. Increase one ability score of your choice by 1, to a maximum of 30. Improve Fate. When you or another creature within 60 feet of you succeeds on or fails a D20 Test, you can roll 2d4 and apply the total rolled as a bonus or penalty to the d20 roll. Once you use this benefit, you can't use it again until you roll Initiative or finish a Short or Long Rest."
 },
 {
  "name": "Boon of Irresistible Offense",
  "category": "Epic Boon",
  "prerequisite": "Level 19+)",
  "text": "(Prerequisite: Level 19+) You gain the following benefits. Ability Score Increase. Increase your Strength or Dexterity score by 1, to a maximum of 30. Overcome Defenses. The Bludgeoning, Piercing, and Slashing damage you deal always ignores Resistance. Overwhelming Strike. When you roll a 20 on the d20 for an attack roll, you can deal extra damage to the target equal to the ability score increased by this feat. The extra damage's type is the same as the attack's type."
 },
 {
  "name": "Boon of Spell Recall",
  "category": "Epic Boon",
  "prerequisite": "Level 19+, Spellcasting",
  "text": "(Prerequisite: Level 19+, Spellcasting Feature) You gain the following benefits. Ability Score Increase. Increase your Intelligence, Wisdom, or Charisma score by 1, to a maximum of 30. Free Casting. Whenever you cast a spell with a level 1–4 spell slot, roll 1d4. If the number you roll is the same as the slot's level, the slot isn't expended."
 },
 {
  "name": "Boon of the Night Spirit",
  "category": "Epic Boon",
  "prerequisite": "Level 19+)",
  "text": "(Prerequisite: Level 19+) You gain the following benefits. Ability Score Increase. Increase one ability score of your choice by 1, to a maximum of 30. Merge with Shadows. While within Dim Light or Darkness, you can give yourself the Invisible condition as a Bonus Action. The condition ends on you immediately after you take an action, a Bonus Action, or a Reaction. Shadowy Form. While within Dim Light or Darkness, you have Resistance to all damage except Psychic and Radiant."
 },
 {
  "name": "Boon of Truesight",
  "category": "Epic Boon",
  "prerequisite": "Level 19+)",
  "text": "(Prerequisite: Level 19+) You gain the following benefits. Ability Score Increase. Increase one ability score of your choice by 1, to a maximum of 30. Truesight. You have Truesight with a range of 60 feet. sEllinG EquipMEnt Equipment fetches half its cost when sold. In contrast, trade goods and valuables—like gems and art objects—retain their full value in the marketplace. \"Magic Items\" has prices for magic items. Equipment Coins Characters often find coins on their adventures and can spend those coins in shops, inns, and other businesses. Coins come in different denominations based on the relative worth of their material. The Coin Values table lists coins and how much they're worth relative to the Gold Piece, which is the game's main coin. For example, 100 Copper Pieces are worth 1 Gold Piece. A coin weighs about a third of an ounce, so fifty coins weigh a pound. Coin Values Coin Value in GP Copper Piece (CP) 1/100 Silver Piece (SP) 1/10 Electrum Piece (EP) 1/2 Gold Piece (GP) 1 Platinum Piece (PP) 10 Weapons The Weapons table in this section shows the game's main weapons. The table lists the cost and weight of each weapon, as well as the following details: Category. Every weapon falls into a category: Simple or Martial. Weapon proficiencies are usually tied to one of these categories. For example, you might have proficiency with Simple weapons. Melee or Ranged. A weapon"
 }
];

export const CLASSES = {
 "Barbarian": {
  "name": "Barbarian",
  "primary": "Strength",
  "hitDie": 12,
  "saves": "Proficiencies",
  "weapons": "Simple and Martial weapons",
  "armor": "Light and Medium armor and",
  "features": {
   "1": [
    "Rage",
    "Unarmored Defense",
    "Weapon Mastery"
   ],
   "2": [
    "Danger Sense",
    "Reckless Attack"
   ],
   "3": [
    "Barbarian Subclass",
    "Primal Knowledge",
    "Frenzy"
   ],
   "4": [
    "Ability Score Improvement"
   ],
   "5": [
    "Extra Attack",
    "Fast Movement"
   ],
   "6": [
    "Mindless Rage"
   ],
   "7": [
    "Feral Instinct",
    "Instinctive Pounce"
   ],
   "9": [
    "Brutal Strike"
   ],
   "10": [
    "Retaliation"
   ],
   "11": [
    "Relentless Rage"
   ],
   "13": [
    "Improved Brutal Strike"
   ],
   "14": [
    "Intimidating Presence"
   ],
   "15": [
    "Persistent Rage"
   ],
   "17": [
    "Improved Brutal Strike"
   ],
   "18": [
    "Indomitable Might"
   ],
   "19": [
    "Epic Boon"
   ],
   "20": [
    "Primal Champion"
   ]
  }
 },
 "Bard": {
  "name": "Bard",
  "primary": "Charisma",
  "hitDie": 8,
  "saves": "Proficiencies",
  "weapons": "Simple weapons",
  "armor": "Light armor",
  "features": {
   "1": [
    "Bardic Inspiration",
    "Spellcasting"
   ],
   "2": [
    "Expertise",
    "Jack of All Trades"
   ],
   "3": [
    "Bard Subclass",
    "Bonus Proficiencies",
    "Cutting Words"
   ],
   "4": [
    "Ability Score Improvement"
   ],
   "5": [
    "Font of Inspiration"
   ],
   "6": [
    "Magical Discoveries"
   ],
   "7": [
    "Countercharm"
   ],
   "10": [
    "Magical Secrets"
   ],
   "14": [
    "Peerless Skill"
   ],
   "18": [
    "Superior Inspiration"
   ],
   "19": [
    "Epic Boon"
   ],
   "20": [
    "Words of Creation"
   ]
  }
 },
 "Cleric": {
  "name": "Cleric",
  "primary": "Wisdom",
  "hitDie": 8,
  "saves": "Proficiencies",
  "weapons": "Simple weapons",
  "armor": "Light and Medium armor and",
  "features": {
   "1": [
    "Spellcasting",
    "Divine Order"
   ],
   "2": [
    "Channel Divinity"
   ],
   "3": [
    "Cleric Subclass",
    "Disciple of Life",
    "Life Domain Spells",
    "Preserve Life"
   ],
   "4": [
    "Ability Score Improvement"
   ],
   "5": [
    "Sear Undead"
   ],
   "6": [
    "Blessed Healer"
   ],
   "7": [
    "Blessed Strikes"
   ],
   "10": [
    "Divine Intervention"
   ],
   "14": [
    "Improved Blessed Strikes"
   ],
   "17": [
    "Supreme Healing"
   ],
   "19": [
    "Epic Boon"
   ],
   "20": [
    "Greater Divine Intervention"
   ]
  }
 },
 "Druid": {
  "name": "Druid",
  "primary": "Wisdom",
  "hitDie": 8,
  "saves": "Proficiencies",
  "weapons": "Simple weapons",
  "armor": "Light armor and Shields",
  "features": {
   "1": [
    "Spellcasting",
    "Druidic",
    "Primal Order"
   ],
   "2": [
    "Wild Shape",
    "Wild Companion"
   ],
   "3": [
    "Druid Subclass",
    "Circle of the Land Spells",
    "Land's Aid"
   ],
   "4": [
    "Ability Score Improvement"
   ],
   "5": [
    "Wild Resurgence"
   ],
   "6": [
    "Natural Recovery"
   ],
   "7": [
    "Elemental Fury"
   ],
   "10": [
    "Nature's Ward"
   ],
   "14": [
    "Nature's Sanctuary"
   ],
   "15": [
    "Improved Elemental Fury"
   ],
   "18": [
    "Beast Spells"
   ],
   "19": [
    "Epic Boon"
   ],
   "20": [
    "Archdruid"
   ]
  }
 },
 "Fighter": {
  "name": "Fighter",
  "primary": "Strength or Dexterity",
  "hitDie": 10,
  "saves": "Proficiencies",
  "weapons": "Simple and Martial weapons",
  "armor": "Light, Medium, and Heavy armor and Shields",
  "features": {
   "1": [
    "Fighting Style",
    "Second Wind",
    "Weapon Mastery"
   ],
   "2": [
    "Action Surge",
    "Tactical Mind"
   ],
   "3": [
    "Fighter Subclass",
    "Improved Critical",
    "Remarkable Athlete"
   ],
   "4": [
    "Ability Score Improvement"
   ],
   "5": [
    "Extra Attack",
    "Tactical Shift"
   ],
   "7": [
    "Additional Fighting Style"
   ],
   "9": [
    "Indomitable",
    "Tactical Master"
   ],
   "10": [
    "Heroic Warrior"
   ],
   "11": [
    "Two Extra Attacks"
   ],
   "13": [
    "Studied Attacks"
   ],
   "15": [
    "Superior Critical"
   ],
   "18": [
    "Survivor"
   ],
   "19": [
    "Epic Boon"
   ],
   "20": [
    "Three Extra Attacks"
   ]
  }
 },
 "Monk": {
  "name": "Monk",
  "primary": "Dexterity and Wisdom",
  "hitDie": 8,
  "saves": "Proficiencies",
  "weapons": "Simple weapons and Martial",
  "armor": "None",
  "features": {
   "1": [
    "Martial Arts",
    "Unarmored Defense"
   ],
   "2": [
    "Monk's Focus",
    "Unarmored Movement",
    "Uncanny Metabolism"
   ],
   "3": [
    "Deflect Attacks",
    "Monk Subclass",
    "Open Hand Technique"
   ],
   "4": [
    "Ability Score Improvement",
    "Slow Fall"
   ],
   "5": [
    "Extra Attack",
    "Stunning Strike"
   ],
   "6": [
    "Empowered Strikes",
    "Wholeness of Body"
   ],
   "7": [
    "Evasion"
   ],
   "9": [
    "Acrobatic Movement"
   ],
   "10": [
    "Heightened Focus",
    "Self-Restoration"
   ],
   "11": [
    "Fleet Step"
   ],
   "13": [
    "Deflect Energy"
   ],
   "14": [
    "Disciplined Survivor"
   ],
   "15": [
    "Perfect Focus"
   ],
   "17": [
    "Quivering Palm"
   ],
   "18": [
    "Superior Defense"
   ],
   "19": [
    "Epic Boon"
   ],
   "20": [
    "Body and Mind"
   ]
  }
 },
 "Paladin": {
  "name": "Paladin",
  "primary": "Strength and Charisma",
  "hitDie": 10,
  "saves": "Proficiencies",
  "weapons": "Simple and Martial weapons",
  "armor": "Light, Medium, and Heavy armor and Shields",
  "features": {
   "1": [
    "Lay On Hands",
    "Spellcasting",
    "Weapon Mastery"
   ],
   "2": [
    "Fighting Style",
    "Paladin's Smite"
   ],
   "3": [
    "Channel Divinity",
    "Paladin Subclass",
    "Oath of Devotion Spells",
    "Sacred Weapon"
   ],
   "4": [
    "Ability Score Improvement"
   ],
   "5": [
    "Extra Attack",
    "Faithful Steed"
   ],
   "6": [
    "Aura of Protection"
   ],
   "7": [
    "Aura of Devotion"
   ],
   "9": [
    "Abjure Foes"
   ],
   "10": [
    "Aura of Courage"
   ],
   "11": [
    "Radiant Strikes"
   ],
   "14": [
    "Restoring Touch"
   ],
   "15": [
    "Smite of Protection"
   ],
   "18": [
    "Aura Expansion"
   ],
   "19": [
    "Epic Boon"
   ],
   "20": [
    "Holy Nimbus"
   ]
  }
 },
 "Ranger": {
  "name": "Ranger",
  "primary": "Dexterity and Wisdom",
  "hitDie": 10,
  "saves": "Proficiencies",
  "weapons": "Simple and Martial weapons",
  "armor": "Light and Medium armor and",
  "features": {
   "1": [
    "Spellcasting",
    "Favored Enemy",
    "Weapon Mastery"
   ],
   "2": [
    "Deft Explorer",
    "Fighting Style"
   ],
   "3": [
    "Ranger Subclass",
    "Hunter's Lore",
    "Hunter's Prey"
   ],
   "4": [
    "Ability Score Improvement"
   ],
   "5": [
    "Extra Attack"
   ],
   "6": [
    "Roving"
   ],
   "7": [
    "Defensive Tactics"
   ],
   "9": [
    "Expertise"
   ],
   "10": [
    "Tireless"
   ],
   "11": [
    "Superior Hunter's Prey"
   ],
   "13": [
    "Relentless Hunter"
   ],
   "14": [
    "Nature's Veil"
   ],
   "15": [
    "Superior Hunter's Defense"
   ],
   "17": [
    "Precise Hunter"
   ],
   "18": [
    "Feral Senses"
   ],
   "19": [
    "Epic Boon"
   ],
   "20": [
    "Foe Slayer"
   ]
  }
 },
 "Rogue": {
  "name": "Rogue",
  "primary": "Dexterity",
  "hitDie": 8,
  "saves": "Proficiencies",
  "weapons": "Simple weapons and Martial",
  "armor": "Light armor",
  "features": {
   "1": [
    "Expertise",
    "Sneak Attack",
    "Thieves' Cant",
    "Weapon Mastery"
   ],
   "2": [
    "Cunning Action"
   ],
   "3": [
    "Rogue Subclass",
    "Steady Aim",
    "Fast Hands",
    "Second-Story Work"
   ],
   "4": [
    "Ability Score Improvement"
   ],
   "5": [
    "Cunning Strike",
    "Uncanny Dodge"
   ],
   "7": [
    "Evasion",
    "Reliable Talent"
   ],
   "9": [
    "Supreme Sneak"
   ],
   "11": [
    "Improved Cunning Strike"
   ],
   "13": [
    "Use Magic Device"
   ],
   "14": [
    "Devious Strikes"
   ],
   "15": [
    "Slippery Mind"
   ],
   "17": [
    "Thief's Reflexes"
   ],
   "18": [
    "Elusive"
   ],
   "19": [
    "Epic Boon"
   ],
   "20": [
    "Stroke of Luck"
   ]
  }
 },
 "Sorcerer": {
  "name": "Sorcerer",
  "primary": "Charisma",
  "hitDie": 6,
  "saves": "Proficiencies",
  "weapons": "Simple weapons",
  "armor": "None",
  "features": {
   "1": [
    "Spellcasting",
    "Innate Sorcery"
   ],
   "2": [
    "Font of Magic",
    "Metamagic"
   ],
   "3": [
    "Sorcerer Subclass",
    "Draconic Resilience",
    "Draconic Spells"
   ],
   "4": [
    "Ability Score Improvement"
   ],
   "5": [
    "Sorcerous Restoration"
   ],
   "6": [
    "Elemental Affinity"
   ],
   "7": [
    "Sorcery Incarnate"
   ],
   "14": [
    "Dragon Wings"
   ],
   "18": [
    "Dragon Companion"
   ],
   "19": [
    "Epic Boon"
   ],
   "20": [
    "Arcane Apotheosis"
   ]
  }
 },
 "Warlock": {
  "name": "Warlock",
  "primary": "Charisma",
  "hitDie": 8,
  "saves": "Proficiencies",
  "weapons": "Simple weapons",
  "armor": "Light armor",
  "features": {
   "1": [
    "Eldritch Invocations",
    "Pact Magic"
   ],
   "2": [
    "Magical Cunning"
   ],
   "3": [
    "Warlock Subclass",
    "Dark One's Blessing",
    "Fiend Spells"
   ],
   "4": [
    "Ability Score Improvement"
   ],
   "6": [
    "Dark One's Own Luck"
   ],
   "9": [
    "Contact Patron"
   ],
   "10": [
    "Fiendish Resilience"
   ],
   "11": [
    "Mystic Arcanum"
   ],
   "14": [
    "Hurl Through Hell"
   ],
   "19": [
    "Epic Boon"
   ],
   "20": [
    "Eldritch Master"
   ]
  }
 },
 "Wizard": {
  "name": "Wizard",
  "primary": "Intelligence",
  "hitDie": 6,
  "saves": "Proficiencies",
  "weapons": "Simple weapons",
  "armor": "None",
  "features": {
   "1": [
    "Spellcasting",
    "Ritual Adept",
    "Arcane Recovery"
   ],
   "2": [
    "Scholar"
   ],
   "3": [
    "Wizard Subclass",
    "Evocation Savant",
    "Potent Cantrip"
   ],
   "4": [
    "Ability Score Improvement"
   ],
   "5": [
    "Memorize Spell"
   ],
   "6": [
    "Sculpt Spells"
   ],
   "10": [
    "Empowered Evocation"
   ],
   "14": [
    "Overchannel"
   ],
   "18": [
    "Spell Mastery"
   ],
   "19": [
    "Epic Boon"
   ],
   "20": [
    "Signature Spells"
   ]
  }
 }
};

